### ISSUE TITLE
[BUG][GLK] HDMI failed to get afg sub nodes, no soundcard

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#1001]
Daily build of 0530 has no soundcard due to HDMI failures.
linux-80a2cb89
sof-92fc7067

I tried daily build of 0530 onto my GLK Ubuntu RT7219 platform but I see hdmi codec failure, no soundcard. (full log attached)

[ 5.018689] HDMI HDA Codec ehdaudio0D2: HDMI: failed to get afg sub nodes
[ 5.018693] HDMI HDA Codec ehdaudio0D2: Failed in parse and map nid with err: -22
[ 5.018710] HDMI HDA Codec: probe of ehdaudio0D2 failed with error -22

[glk_ubuntu_0530_hdmi_failure.log](https://github.com/thesofproject/linux/files/3242828/glk_ubuntu_0530_hdmi_failure.log)

**Comment by fredoh9** [comment]
@ranj063 reported she found same issue in CML chromebook. And Chrome team found suspicious commit.

I tried to revert the commit id, but looks same to me.
333ee2257de8 ASoC: SOF: Intel: hda: fix the hda init chip

I can try git bisect and update the candidate commit here.

**Comment by fredoh9** [comment]
In terms of audio playback in GLK(sof-dev),
072cf06e35eb Merge pull request #970 from plbossart/merge/broonie-next-20190521		<==  bad
d807d30dcf40 ASoC: SOF: Intel: ipc: don't check for HIPCCTL register value		<== good

After git bisect, the result is,
e57ccca1ba33e1d92cc3bbf8b6304a46948844b0 is the first bad commit
e57ccca1ba33 (refs/bisect/bad) Merge tag 'sound-5.2-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound

This error started from e57ccca1ba33
[ 5.018689] HDMI HDA Codec ehdaudio0D2: HDMI: failed to get afg sub nodes
[ 5.018693] HDMI HDA Codec ehdaudio0D2: Failed in parse and map nid with err: -22
[ 5.018710] HDMI HDA Codec: probe of ehdaudio0D2 failed with error -22


One more update, I tried today's daily build(20190601, China time), surprisingly it works. For more build info,
linux build : 0a747dc2
sof build : 3e3f1d0c

**Comment by keqiaozhang** [comment]
@fredoh9 
The latest code base works on my GLK-Ubuntu.
Kernel: sof-dev/0a747dc
sof/tplg: master/8901e0

**Comment by keqiaozhang** [comment]
This issue cannot be reproduced on GLK. let's close this bug.
Kernel: sof-dev/0a747dc
sof/tplg: master/14b724

**Comment by keyonjie** [comment]
I am still seeing this errors in today's latest commits:
```
[    5.227101] HDMI HDA Codec ehdaudio0D2: HDMI: failed to get afg sub nodes
[    5.227105] HDMI HDA Codec ehdaudio0D2: Failed in parse and map nid with err: -22
[    5.227121] HDMI HDA Codec: probe of ehdaudio0D2 failed with error -22
```
@fredoh9 @keqiaozhang how about you?

**Comment by sathyap-chrome** [comment]
I've seen coupe of CML boot instances failing with same error signature. 
HDMI HDA Codec ehdaudio0D2: HDMI: failed to get afg sub nodes
HDMI HDA Codec ehdaudio0D2: Failed in parse and map nid with err: -22
HDMI HDA Codec: probe of ehdaudio0D2 failed with error -22

Test tried : run reboot script and check card lists everytime after boot. Happens 1 in 10 machines and 1 in 1000 iterations..

cc @ranj063
