### ISSUE TITLE
sof-rt5682: need to enable MCLK for BYT/Minnowboard

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1010]
The sof-rt5682 does not rely on the MCLK for Baytrail. That's not good, this signal is available since the Turbot revision.
We should add this support and not assume the MCLK is only used for CML. This also creates a validation gap since we don't currently have a platform using the MCLK on the legacy platforms.

**Comment by xun2z** [comment]
#1033 does this help?

**Comment by wenqingfu** [comment]
fixed by #1033. Thank you, @xun2z !
