### ISSUE TITLE
System S3 failed on CNL

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#102]
Summary: 
Two different situations:
1. I run "echo mem > /sys/power/state" and after system recovered, audio couldn't work.
2. I run playback, at the mean time I run "echo mem > /sys/power/state" in another terminal, leading to system hang.

Environment:
on CNL using gcc
sof : stable 1.2 branch 7346243e596cd91ff4342308e680392600496b3a
        master 9944905a7c3950f0f20e8623c9ca7842d58c43ed
soft ： 41861aac373eb1f6978bfdb0bbe97cd882b1785a
sof-dev: bafb59032343459cc4019cb65e515595451357e7
tplg:test-ssp0-mclk-0-I2S-volume-s16le-s16le-48k-24000k-nocodec.tplg

Log:
I only got log files of situation 1:
[dmesg-s3.log](https://github.com/thesofproject/linux/files/2335270/dmesg-s3.log)
[rmbox-s3.log](https://github.com/thesofproject/linux/files/2335271/rmbox-s3.log)
[rmbox-t-s3.log](https://github.com/thesofproject/linux/files/2335272/rmbox-t-s3.log)

**Comment by mengdonglin** [comment]
Close this bug for lack of BIOS support for S3 on CNL. We will cover S3 on APL. Will reopen this issue if situation changes.
