### ISSUE TITLE
[FEATURE] Add multi-client support

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#1032]
The SOF driver stack is currently only permits audio use cases. Add MFD support to allow other client drivers to register with SOF MFD driver in order to:

1) Register / unregister with SOF driver.
2) Send and receive IPC
3) Increment/decrement runtime PM usage.

The MFD layer should sit above the IPC layer and below the PCM layer (the PCM layer will be it's first client).

**Comment by plbossart** [comment]
done with sof-client.
