### ISSUE TITLE
[Feature] Coexistence of SOF, legacy HD-A and close source FW driver

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#1039]
Upstream thread: https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149968.html

Speaking for distributions, we need to correctly identify the driver which
will load the proper firmware files. From notes posted to the alsa-devel ML,
it seems that there are three drivers for similar hardware (sound bridges) now
and it is not easy to identify the proper driver, because the similar PCI ID
is registered in all of them:

1) legacy HDA
2) sound/soc/intel
3) sound/soc/sof/intel

Do not forget that the distributions include all driver modules in their
universal kernels. It seems like a problem for the Intel hardware at the
moment.

**Comment by mengdonglin** [comment]
Pierrie's RFC to fix this open:
[alsa-devel] [RFC PATCH 0/6] ALSA/HDA: abort probe when DMICs are detected
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149729.html

**Comment by mengdonglin** [comment]
The solution is aligned with upstream, Canonical will test it . Thanks @plbossart !

**Comment by plbossart** [comment]
all code is already upstream.
