### ISSUE TITLE
[Bug]Headset can’t be detected when plug in headset just after system boot up 

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1054]
**Describe the bug**
Headset can’t be detected when plug in headset within 2s after system boot up

**To Reproduce**
1. System auto login is on (setting->details->users to turn on automatic login)
2. Do system reboot via "sudo reboot"
3. Plug in headset as soon as unit boot up (display on and enter desktop page.)

**frequency**
100%

**Actual result**
Check jack detection via 'amixer cget numid=34', headset can't be detected

Recover method: Play music.

**Expected result**
Jack detection should detected successfully

**Environment**
Firmware: 6cc8da10, https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable
Kernel: 1cd1a89 sof-v5.0
Topology: file: sof-hda-generic.tplg same path as firmware

No error log.
[jackdetectNotWorkWhenpluginASAPafterBootup_dmesg.log](https://github.com/thesofproject/linux/files/3320064/jackdetectNotWorkWhenpluginASAPafterBootup_dmesg.log)

**Comment by RanderWang** [comment]
I setup the serial port in whiskylake and connected it to a host machine to check the secret behind the boot up. I can reproduce this bug and found at this time, SOF was being initialized. I may need to dig deeper.

**Comment by ClarexZhou** [comment]
Error not occurred with PR #1060

**Comment by RanderWang** [comment]
The patch has been merged
