### ISSUE TITLE
[Bug][CML]Headset arecord not work when plug in headset  as soon as wake up from S3   (2/12)

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1055]
**Describe the bug**
Headset arecord not work when plug in headset as soon as  login account when wake up from S3

**To Reproduce**
1. System auto login is off (setting->details->users to turn off automatic login)
2. Enter suspend via Power menu (Long press Shutdown icon after click top right corner, icon will change to suspend icon, then select it)
3. Press any button to wake up, account password is query.
4. Plug in headset quickly, just after login account.
5. 'arecord -Dhw:0,0  -r48000 -c2 -fs16_le 1.wav -vv -i' to catpure.

**frequency**
2/12

**Actual result**
Check jack detection via 'amixer cget numid=34', headset can't be detected

Recover method: plug out headset, wait for more than 5 seconds, plug in headset again. Error can be recovered.

**Expected result**
Arecord should work successfully

**Environment**
Firmware: 6cc8da10, https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable
Kernel: 1cd1a89 sof-v5.0
Topology: file: sof-hda-generic.tplg same path as firmware

No error log.
[captureNotWorkAfterPluginASAPafterWakeup_dmesg.log](https://github.com/thesofproject/linux/files/3320145/captureNotWorkAfterPluginASAPafterWakeup_dmesg.log)
[captureNotWorkAfterPluginASAPafterWakeup_logger.log](https://github.com/thesofproject/linux/files/3320146/captureNotWorkAfterPluginASAPafterWakeup_logger.log)

**Comment by ClarexZhou** [comment]
Error also occurred when do quickly plug in/ out during account login when system bootup (4/40)

**Comment by ClarexZhou** [comment]
Error also can be reproduced when quick plug in/out several times during sound setting opened.

**Comment by ranj063** [comment]
@ClarexZhou could you please check if https://github.com/thesofproject/linux/pull/977 helps ?

**Comment by RanderWang** [comment]
this issue is same as https://github.com/thesofproject/linux/issues/1054.

**Comment by RanderWang** [comment]
> Error also can be reproduced when quick plug in/out several times during sound setting opened.

This is not a bug, it is can be reproduced with legacy hda driver.

**Comment by RanderWang** [comment]
> @ClarexZhou could you please check if #977 helps ?

@ranj063  this PR has been merged in v5.0, but makes no effect for this case.
I have a idea but need to be confirmed

**Comment by RanderWang** [comment]
The patch has been merged

**Comment by ClarexZhou** [comment]
Capture not work issue still occurred with PR #1060. 
Scenario 1: System Boot up -> quickly plug in headset -> Then arecord ->capture not work (3/10)
Scenario 2:  Enter S3->wake up->quickly plug in headset just after enter account password.->arecord to check->capture not work. (2/12)

Can be recovered via plug out headset, wait for more than 5 seconds, plug in headset again. Error can be recovered.

**Comment by plbossart** [comment]
@ClarexZhou this issue has been stale for 6+ months, can we close it?

**Comment by ClarexZhou** [comment]
close for error not occurred after run 10 times on release/sof-v5.0 fb3a8e4.
