### ISSUE TITLE
[BUG][WHL] dmesg dons't  stop flushing sof log after s3 

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#1064]
I just did a test and finally reproduce this issue of "repeatedly print out ipc rx in the dmesg" again. (it is not easy to reproduce)

1. Booting up without headset plug in

2. open a terminal, and run dmesg -w

3, open the gnome-sound-setting and choose input (the dmic is selected by default)

4. run s3 from gnome power button  (right top corner)

5. press physical power button or physical enter button to wake up the system

6. repeat 5 times of step 4 and step 5, not reproduce the issue

7. plug a headset and choose the headset mic in the input tab from the sound setting

8. run s3 and press power button to wake up.

9. the issue of  "repeatedly print out ipc rx in the dmesg" is reproduced.

**Comment by mengdonglin** [comment]
@jason77-wang Could you please paste dmesg and sof-logger output as well?

**Comment by mengdonglin** [comment]
Closing,  same issue as #1594, and fixed by thesofproject/linux#1072.
