### ISSUE TITLE
[Bug][CML]Microphone without headphones stops work after S3.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1071]
**Describe the bug**
Pure Mic stop work after S3.

**To Reproduce**
1. Plug in one pure MIC
2. Open alsamixer, press Tab to switch to Capture page-> change 'Input Source' to 'Headphone Mic'
3. Open sound setting, select Input table, highlight headset mic, ensure MIC capture works OK. As below snapshot.
![Screenshot from 2019-07-03 01-17-53](https://user-images.githubusercontent.com/49641224/60560884-33188680-9d84-11e9-902f-f98e999e4cf6.png)
4. Enter S3 and wake up, check Mic capture not work in sound setting.

**frequency**
100%

**Actual result**
Pure Mic capture not work work after S3.

**Expected result**
Pure Mic capture should work normally after S3.

**Environment**
FW: 6cc8da1 https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable
Kernel: https://github.com/thesofproject/linux/tree/release/sof-v5.0 (top commit: f2a920c)
Topology: file: sof-hda-generic.tplg same path as firmware
platform: CML

No error message.
[pureMic_afterS3_dmesg.log](https://github.com/thesofproject/linux/files/3353108/pureMic_afterS3_dmesg.log)
[pureMic_afterS3_soflogger.log](https://github.com/thesofproject/linux/files/3353109/pureMic_afterS3_soflogger.log)

**Comment by ranj063** [comment]
@ClarexZhou what is a "Pure Mic"?

**Comment by ClarexZhou** [comment]
@ranj063  Microphone without headphones is used in this bug.
![IMG_20190704_093623](https://user-images.githubusercontent.com/49641224/60634000-c82c8580-9e3f-11e9-8f0f-bc48326091bc.jpg)

**Comment by ranj063** [comment]
@ClarexZhou can you please check if this patch helps?
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-July/151943.html

**Comment by ClarexZhou** [comment]
Close. Fixed by https://mailman.alsa-project.org/pipermail/alsa-devel/2019-July/151943.html. And merged in sof-v5.0.  Error not seen on sof-v5.0 .
