### ISSUE TITLE
[BUG][CML] Sound card not listing : Error ASoC: CODEC DAI intel-hdmi-hifi1 not registered

### ISSUE THREAD

**Issue by kamal-ap** [thesofproject/linux#1074]
Platform : CML
SOF firmware & topology :
SOF FW source | URL: https://github.com/thesofproject/sof/tree/cml-004-drop-stable   Commit:  f82d9dad7bd48fa3243d94d45dac68261184bc55
UCM :
https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/1648310

Kernel: :
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1650019/6

Steps to repoduce:
1) on above kernel cherry-pick  the patch "ASoC: SOF: Intel: hda: fix the hda init chip"
2) flash this kernel and reboot the system
3) run aplay -l

Expected result:
Sound card should be listed

Actual result:
localhost ~ # aplay -l
aplay: device_list:272: no soundcards found...

Error logs :
localhost ~ # dmesg | grep sof
[    0.424819] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.424821] software IO TLB: mapped [mem 0x85afc000-0x89afc000] (64MB)
[    4.033368] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.033488] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[    4.076596] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops 0xffffffff8dca0730)
[    4.081085] sof-audio-pci 0000:00:1f.3: no hda codecs found!
[    4.083949] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[    4.083953] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[    4.174525] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:1:0-03057
[    4.174529] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:8:0 Kernel ABI 3:7:0
[    4.174531] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    4.175428] sof-audio-pci 0000:00:1f.3: firmware boot complete
[    4.602451] sof_rt5682 sof_rt5682: info: override FE DAI link SSP0-Codec
[    4.602454] sof_rt5682 sof_rt5682: info: override FE DAI link dmic01
[    4.602456] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp1
[    4.602457] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp2
[    4.602458] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp3
[    4.602459] sof_rt5682 sof_rt5682: info: override FE DAI link SSP1-Codec
[    4.602465] sof_rt5682 sof_rt5682: ASoC: CODEC DAI intel-hdmi-hifi1 not registered
[    4.805563] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[    4.896595] sof-audio-pci 0000:00:1f.3: firmware boot complete
[    4.896832] sof_rt5682 sof_rt5682: info: override FE DAI link SSP0-Codec
[    4.896834] sof_rt5682 sof_rt5682: info: override FE DAI link dmic01
[    4.896835] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp1
[    4.896837] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp2
[    4.896838] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp3
[    4.896839] sof_rt5682 sof_rt5682: info: override FE DAI link SSP1-Codec
[    4.896845] sof_rt5682 sof_rt5682: ASoC: CODEC DAI intel-hdmi-hifi1 not registered

**Comment by kamal-ap** [comment]
if we revert " "ASoC: SOF: Intel: hda: fix the hda init chip" , sound card is listing properly

**Comment by xiulipan** [comment]
@kamal-ap Can you try to boot the device with 
- HDMI cable connected only
- HDMI cable connected to a monitor
- DP cable connected only
- DP cable connected to a monitor

**Comment by xiulipan** [comment]
Duplicate with #1027

**Comment by xiulipan** [comment]
@kamal-ap BTW please try to find dmesg like below and paste in more test result.

> [    5.650903] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power on
> [    5.655848] sof-audio-pci 0000:00:0e.0: no hda codecs found!
> [    5.655855] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power off

**Comment by ranj063** [comment]
> @kamal-ap Can you try to boot the device with
> 
> * HDMI cable connected only
> * HDMI cable connected to a monitor

@xiulipan i already asked @kamal-ap to try this and he mentioned connecting a HDMI monitor didnt  help in his case

**Comment by ranj063** [comment]
@kamal-ap can you please check if https://github.com/thesofproject/linux/pull/1075 helps?

**Comment by kamal-ap** [comment]
> Duplicate with #1027

Ranjani is right we already checked booting with HDMI  and issue was reproducible. Also this was regression of  patch "ASoC: SOF: Intel: hda: fix the hda init chip"   so we raised seperate issue . But yes rootcause may be same.

**Comment by kamal-ap** [comment]
> @kamal-ap can you please check if #1075 helps?

That patch worked . Now sound card is detecting

**Comment by xiulipan** [comment]
@kamal-ap @ranj063 We can also close this as #1075 merged?
