### ISSUE TITLE
[BUG][ICL]No audio output when play music after plug in headset from idle.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1083]
**Describe the bug**
Headset no audio output when plug in headset after idle for a while, and then play music.

**To Reproduce**
1. Do system reboot via "sudo reboot"
2. Insert headset and play music via aplay, music is output on headset normally
3. Plug out headset. Stop music and wait for more than 5s.
4. Plug in headset and play music via aplay again.

**frequency**
100%

**Actual result**
No audio output on headset. Though headphone jack already detected.

```
ubuntu@sh-icl-rvp-hda-03:~$ amixer cget numid=36
numid=36,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```

**Expected result**
Music output on headset normally.

**Environment**
Firmware: 27cdfbdb Master
Kernel: fdfcca4c on topic/sof-dev 
Topology: file: sof-hda-generic.tplg same path as firmware
platform: ICL-RVP

No error message.

[headsetnoOutputAfterpluginHeadsetFromIdle_soflooger.txt](https://github.com/thesofproject/linux/files/3367235/headsetnoOutputAfterpluginHeadsetFromIdle_soflooger.txt)
[headsetnoOutputAfterpluginHeadsetFromIdle_dmesg.txt](https://github.com/thesofproject/linux/files/3367236/headsetnoOutputAfterpluginHeadsetFromIdle_dmesg.txt)

**Comment by mengdonglin** [comment]
@ClarexZhou could you dump and compare the amixer settings between step 2 and 4? Is there any difference?

**Comment by ClarexZhou** [comment]
No difference after diff the amixer contents between step2 and 4 
Attach the amixer contents.
[amixercontents_issue.txt](https://github.com/thesofproject/linux/files/3370995/amixercontents_issue.txt)

**Comment by dengyangchao** [comment]
issue still can Reproduced

test recipe:
Firmware: 9e2aa3d3 Master
Kernel: 53d77540 on topic/sof-dev
Topology: file: sof-hda-generic.tplg same path as firmware
platform: ICL-RVP

**Comment by dengyangchao** [comment]
No audio output when play music after system reboot

**To Reproduce**
1.Do system reboot via "sudo reboot"
2.wait runtime_status to suspend
3.play music through"aplay -Dhw:0,0 -f dat 1.wav -vv -i"

**frequency**
3/10

**Actual result**
No audio output on headset. Though headphone jack already detected.

**Expected result**
Music output on headset normally

**Environment**
Firmware: c6f1b08f  Master
Kernel: b45315d5 on topic/sof-dev
Topology: file: sof-hda-generic-4ch.tplg same path as firmware
platform: ICL-RVP

[dmesg.log](https://github.com/thesofproject/linux/files/3504282/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3504283/logger.log)

**Comment by dengyangchao** [comment]
use below commands catch some info on ICL-RVP and CFL
```
# echo 1  > /sys/module/snd_hda_codec/parameters/dump_coef
# cat /proc/asound/card0/codec#0
```

[CFL_normal_output.txt](https://github.com/thesofproject/linux/files/3524024/CFL_normal_output.txt)
[CFL_without_headset.txt](https://github.com/thesofproject/linux/files/3524025/CFL_without_headset.txt)
[ICL_issue_occur.txt](https://github.com/thesofproject/linux/files/3524026/ICL_issue_occur.txt)
[ICL_normal_output.txt](https://github.com/thesofproject/linux/files/3524027/ICL_normal_output.txt)
[ICL_without_headset.txt](https://github.com/thesofproject/linux/files/3524028/ICL_without_headset.txt)

**Comment by ClarexZhou** [comment]
@kailangyang Could you take a look?

**Comment by KailangYang** [comment]
@ClarexZhou 
Intel service owner was not me.
I will forward mail to my colleage.

**Comment by dengyangchao** [comment]
Try on another ICL RVP,  issue can not reproduce
Hardware issue, so close it
