### ISSUE TITLE
[BUG][CML]: Sound card not detected with Error ASoC: physical link iDisp1 (id 2) not exist

### ISSUE THREAD

**Issue by kamal-ap** [thesofproject/linux#1086]
CML SOF 0.45 Release 
SOF FW source 	URL: https://github.com/thesofproject/sof/tree/cml-0045-drop-stable
 Commit:  afbb2a6f53192234d2d3de0ba2e229490d516e3b
 SOF Drivers source 	URL: https://github.com/thesofproject/linux/commits/topic/sof-dev
Commit: 08d3631

Chromium kernel: https://github.com/kamal-ap/chromium-4.19/commits/gtot4_19
Note : this kernel include revert of "ASoC: Intel: sof-rt5682: correct naming for dmic16k "
as this looks a regression.

With "ASoC: Intel: sof-rt5682: correct naming for dmic16k" patch, sound card is not detected.
when i revert this patch , sound card is detected 

DMESG:
localhost ~ # dmesg | grep sof
[    0.420998] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.421000] software IO TLB: mapped [mem 0x85afc000-0x89afc000] (64MB)
[    4.168152] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.168284] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[    4.184004] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops 0xffffffff9aaa09e0)
[    4.192722] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 4
[    4.212684] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[    4.212687] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[    4.303244] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:1:0-03057
[    4.303248] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:8:0 Kernel ABI 3:8:0
[    4.304125] sof-audio-pci 0000:00:1f.3: firmware boot complete
[    4.790570] sof_rt5682 sof_rt5682: info: override FE DAI link SSP0-Codec
[    4.790573] sof_rt5682 sof_rt5682: info: override FE DAI link dmic01
[    4.790574] sof_rt5682 sof_rt5682: info: override FE DAI link dmic16k
[    4.790576] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp1
[    4.790577] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp2
[    4.790578] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp3
[    4.790579] sof_rt5682 sof_rt5682: info: override FE DAI link SSP1-Codec
[    4.791984] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:8:0 Kernel ABI 3:8:0
[    4.813479] sof-audio-pci 0000:00:1f.3: ASoC: physical link iDisp1 (id 2) not exist
[    4.813547] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -22
[    4.813553] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[    4.813554] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[    4.813567] sof_rt5682 sof_rt5682: ASoC: failed to instantiate card -22
[   64.823524] udevd[163]: seq 2151 '/devices/pci0000:00/0000:00:1f.3/sof_rt5682' is taking a long time

**Comment by keyonjie** [comment]
@kamal-ap have you updated tplg also?
We need to cherry-pick the FW commits also(if you update the Kernel) to
https://github.com/thesofproject/sof/tree/cml-0045-drop-stable

**Comment by kamal-ap** [comment]
@keyonjie   @ranj063  
FW branch and kernel was as per the release notes  & 
sof-audio-pci 0000:00:1f.3: **Topology: ABI 3:8:0 Kernel ABI 3:8:0**

I tried taking topology from master as ranjani suggested .Still Sound card is not detected 
and errors are different 

now Topology and kernel versions mismatch
[    4.714199] sof-audio-pci 0000:00:1f.3: **Topology: ABI 3:9:0 Kernel ABI 3:8:0**
[    4.714202] sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel

DMESG:
dmesg | grep sof
[    0.427905] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.427907] software IO TLB: mapped [mem 0x85afc000-0x89afc000] (64MB)
[    4.122605] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.122726] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[    4.185271] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops 0xffffffffb36a09e0)
[    4.193963] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 4
[    4.196307] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[    4.196311] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[    4.287189] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:1:0-03057
[    4.287193] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:8:0 Kernel ABI 3:8:0
[    4.287931] sof-audio-pci 0000:00:1f.3: firmware boot complete
[    4.711817] sof_rt5682 sof_rt5682: info: override FE DAI link SSP0-Codec
[    4.711820] sof_rt5682 sof_rt5682: info: override FE DAI link dmic01
[    4.711822] sof_rt5682 sof_rt5682: info: override FE DAI link dmic16k
[    4.711823] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp1
[    4.711824] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp2
[    4.711825] sof_rt5682 sof_rt5682: info: override FE DAI link iDisp3
[    4.711826] sof_rt5682 sof_rt5682: info: override FE DAI link SSP1-Codec
[    4.714199] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:9:0 Kernel ABI 3:8:0
[    4.714202] sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    4.726117] sof-audio-pci 0000:00:1f.3: can't find host comp to bind pcm
[    4.726121] sof-audio-pci 0000:00:1f.3: error: can't bind pcm to host
[    4.726123] sof-audio-pci 0000:00:1f.3: ASoC: DAI loading failed
[    4.732684] sof-audio-pci 0000:00:1f.3: ASoC: physical link SSP1-Codec (id 5) not exist
[    4.732775] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -22
[    4.732781] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[    4.732783] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[    4.732800] sof_rt5682 sof_rt5682: ASoC: failed to instantiate card -22
[   64.309107] udevd[165]: seq 2146 '/devices/pci0000:00/0000:00:1f.3/sof_rt5682' is taking a long time

**Comment by keyonjie** [comment]
@kamal-ap just noticed that you are using sof-cml-rt5682-max98357a.m4, we need do similar update to it  also(similar to what we did for sof-cml-rt5682.m4), let me submit a fix for it.

**Comment by sathyap-chrome** [comment]
@keqiaozhang  Thanks, understood the issue with master branch.
But root cause for this issue originally is that , the .45 release FW branch didnt have the topology changes but kernel driver already has the change. Hence on .45, we need to revert the machine driver change.

**Comment by keyonjie** [comment]
@kamal-ap @sathyap-chrome the SOF PR https://github.com/thesofproject/sof/pull/1621 will fix this.

**Comment by sathyap-chrome** [comment]
Thanks @keyonjie

**Comment by kamal-ap** [comment]
Awsome @keyonjie  . can you also merge to https://github.com/thesofproject/sof/tree/cml-005-drop-stable   &  https://github.com/thesofproject/sof/tree/cml-0045-drop-stable ?

**Comment by sathyap-chrome** [comment]
@kamal-ap 0045 - we should not merge as the previous commit Topology: sof-cml-rt5682: add dmic16k PCM and dai is not merged in 0045.

**Comment by kamal-ap** [comment]
Awsome @keyonjie. Thanks for very quick fixes and merge to cml-005-drop-stable branch.

Closing this issue
