### ISSUE TITLE
[GLK] Driver fails to handle resume/suspend properly when no firmware present

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#1088]
Present in GLK v1.1 and v1.2, if the firmware is not present and the device the suspends and then resumes it either panics (v1.1) or deadlocks the device (v1.2) which is not an appropriate behaviour for the driver.

See https://bugs.chromium.org/p/chromium/issues/detail?id=983706 for local bug.

**Comment by ranj063** [comment]
Thanks for reporting @cujomalainey 
@mengdonglin can you please assign this to someone?

**Comment by xiulipan** [comment]
@ranj063 
I think we have already fix a similar issue https://github.com/thesofproject/linux/issues/945 with #946

@cujomalainey 
Could you try to cherry-pick #946 to see if this fix the issue when FW load fail

**Comment by ranj063** [comment]
@xiulipan 946 is a very old commit and is already included in the releases that @cujomalainey has commented on.

**Comment by plbossart** [comment]
@cujomalainey I just tried with the latest everything and the behavior with "rtcwake -m mem -s 3"
is as follows

````
[  294.806514] sof-audio-pci 0000:00:0e.0: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  295.308294] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x40010000 size 76
[  295.308296] sof-audio-pci 0000:00:0e.0: info: preventing DSP entering D3 state to preserve context
[  295.308300] sof-audio-pci 0000:00:0e.0: unknown ROM status value 05000001
[  295.308304] sof-audio-pci 0000:00:0e.0: error: status = 0x00000000 panic = 0x00000000
[  295.308306] sof-audio-pci 0000:00:0e.0: unknown ROM status value 05000001
[  295.308310] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
[  295.308312] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  295.308316] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000000
[  295.308318] sof-audio-pci 0000:00:0e.0: ctx_save ipc error -110, proceeding with suspend
[  295.308334] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x1010303 successful
[  295.308339] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x303 successful
[  295.308342] sof-audio-pci 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[  295.308362] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000010 at  00000044
[  295.308454] wlp0s12f0: deauthenticating from f4:f5:e8:6b:45:ba by local choice (Reason: 3=DEAUTH_LEAVING)
[  296.492520] PM: Some devices failed to suspend, or early wake event detected
[  296.620682] elan_i2c i2c-ELAN0000:00: invalid report id data (ff)
[  297.454953] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000044
[  297.454958] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000040 at  00000048
[  297.454963] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000000 at  00000048
[  297.458189] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000048
[  297.458191] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000040 at  00000048
[  297.458224] sof-audio-pci 0000:00:0e.0: loading firmware
[  297.458257] sof-audio-pci 0000:00:0e.0: Direct firmware load for intel/sof/sof-glk.ri failed with error -2
[  297.458261] sof-audio-pci 0000:00:0e.0: error: request firmware intel/sof/sof-glk.ri failed err: -2
[  297.458262] sof-audio-pci 0000:00:0e.0: error: failed to load DSP firmware after resume -2
[  297.458269] PM: dpm_run_callback(): pci_pm_resume+0x0/0x90 returns -2
[  297.458273] PM: Device 0000:00:0e.0 failed to resume: error -2
````

We should definitively try to avoid an IPC if there is no firmware on suspend, but other than that I am not sure if the behavior is incorrect?

@ranj063 what do you think?

**Comment by cujomalainey** [comment]
If we are no longer freezing or crashing then I think it's fine. Errors are fair game.

**Comment by ranj063** [comment]
@plbossart the errors are fine but does audio work at all after system resume?

**Comment by plbossart** [comment]
> @plbossart the errors are fine but does audio work at all after system resume?

no, there's no firmware...

**Comment by ranj063** [comment]
> no, there's no firmware...

ok thats expected. @cujomalainey and I fixed this part on Friday. So we have audio working after suspend/resume cycle. We will post the patches after cleanup. we still have to get runtime PM working though.

**Comment by ranj063** [comment]
@plbossart sorry I got confused with BYT here. 

When there is no FW present, yes we should avoid the IPC. But how do we tell there is not FW?

**Comment by plbossart** [comment]
we probably need to use a boolean state variable, like first_boot or something, and avoid saving the context when it's not relevant.

**Comment by plbossart** [comment]
@ranj063 that issue should be fixed now with your state machine changes? Can we close?

**Comment by cujomalainey** [comment]
I can give it a test when I am back in MTV next week and close this

**Comment by plbossart** [comment]
@cujomalainey @ranj063 can we close this?

**Comment by cujomalainey** [comment]
I can't build upstream kernels for some reason right now, but I trust that you fixed it as said above.
