### ISSUE TITLE
[BUG] Intel match building for arm allmodconfig

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#1091]
It appears that CONFIG_SND_SOC_ACPI_INTEL_MATCH is not defined in kconfig so it is building for arm allmodconfig and therefore is causing the build to fail. This will need to be cherry-picked back to glk v1.2.

**Comment by cujomalainey** [comment]
I forgot the CONFIG_ prefix is dropped in kconfig, so the config is there, but there is still a bug it appears for make allmodconfig for arm.

```
chromeos-kernel-4_14-4.14.133-r852: ERROR: "snd_soc_acpi_codec_list" [sound/soc/intel/common/snd-soc-acpi-intel-match.ko] undefined!
chromeos-kernel-4_14-4.14.133-r852: make[2]: *** [/build/arm-generic/tmp/portage/sys-kernel/chromeos-kernel-4_14-4.14.133-r852/work/chromeos-kernel-4_14-4.14.133/scripts/Makefile.modpost:92: __modpost] Error 1
```

**Comment by plbossart** [comment]
isn't this what Guenter Roeck reported some time back? You are probably missing one of the upstream patches

**Comment by cujomalainey** [comment]
Very possible, I have been split across a few things lately so it is very possible I forgot about that patch

**Comment by plbossart** [comment]
I checked that with the latest sof-dev the code compiles fine with arm64/allmodconfig, so it's a backport issue.

**Comment by cujomalainey** [comment]
any chance you have an idea what patch it is so I can backport it myself?

**Comment by plbossart** [comment]
try "ASoC: acpi: add missing includes for non-ACPI platforms"

**Comment by cujomalainey** [comment]
Ok, now I'm back from being OOO. Tried the to cherry-pick the commit and it came up as an empty commit

**Comment by dbaluta** [comment]
@cujomalainey usually this happens when the commit is already in your branch.

**Comment by cujomalainey** [comment]
Yea I figured. I think the commit that is missing is "ASoC: Intel: Fix if statements for SOF in Kconfigs"

**Comment by cujomalainey** [comment]
We were missing "ASoC: soc-acpi: add static inline fallbacks when CONFIG_ACPI=n"
