### ISSUE TITLE
should check num_hw_configs and default_hw_config_id in topology handler

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/linux#11]
https://github.com/thesofproject/linux/blob/cb05347d9f85e18b414098d512c8287c297933d2/sound/soc/sof/topology.c#L1703
Always uses the first hw_config, we have multiple BE the num_hw_configs will be not 1 and we need to handle that.

**Comment by plbossart** [comment]
I think this is a duplicate: we need to deal with multiple configurations as already filed here: https://github.com/thesofproject/soft/issues/11

**Comment by xiulipan** [comment]
Yes, https://github.com/thesofproject/soft/issues/11 is topology support.
And I think we also need some change in kernel part, too.
In the reference code, we could not switch to different config even if we had more config from topology.

**Comment by wenqingfu** [comment]
close as duplicate of #697
