### ISSUE TITLE
[BUG][CML] Occasional no sound or long playback latency on DP through Type-c to DP converter

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#1105]
**Describe the bug**
Connect the DP Monitor through the left USB type-c port to DP converter, monitor can display, but no sound can be heard via aplay acasionally. But HDMI works well through the same type-c port to HDMI converter.
The reproduce rate is less than 10%,’  And this issue only happens on the left side of USB type-c connector.  The other USB type-C port on the right works well and cannot reproduce this issue.

**To Reproduce**
1. connect the DP Monitor through type-c to DP converter.
2. set the amixer properly.
```
amixer cset name="Pin5-Port0 Mux" 1
amixer cset name="Pin5-Port1 Mux" 1
amixer cset name="Pin5-Port2 Mux" 1
amixer cset name="Pin6-Port0 Mux" 2
amixer cset name="Pin6-Port1 Mux" 2
amixer cset name="Pin6-Port2 Mux" 2
amixer cset name="Pin7-Port0 Mux" 3
amixer cset name="Pin7-Port1 Mux" 3
amixer cset name="Pin7-Port2 Mux" 3
```
3. run aplay:
aplay -Dhw:0,2 -f dat -c 2 audio.wav 

Environment
linux: https://github.com/thesofproject/linux/commit/f267c3dcfd7f88bf505e13e09f4cd0e5b90bb9fd
firmware:
https://github.com/thesofproject/sof/commit/442cfb2f2bbc05cd1617cd205aeeb18d9dfb699a
Topology: sof-cml-rt5682-max98357a.tplg
platform: CML

**dmesg**
```
[   85.573499] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   85.573535] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   86.073446] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   86.073480] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   86.090211] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: hif5-1 Output event failed: -5
[   86.091949] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 2 dir 0 cmd 1
[   86.092487] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[   86.092496] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   86.092721] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   86.092733] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[   87.073534] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
```
[dmesg-dp.txt](https://github.com/thesofproject/linux/files/3451104/dmesg-dp.txt)
[logger-t-dp.txt](https://github.com/thesofproject/linux/files/3451105/logger-t-dp.txt)

**Comment by mengdonglin** [comment]
This seems to be HW specific for the left USB type-C port on DP support. Closing as won't fix. Will open later if need.
