### ISSUE TITLE
Refactor sof_fw_ready

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/linux#1107]
@dbaluta can you add '/* mandatory */' comment as @plbossart mentioned please?

I can imagine that we should change sof_fw_ready() to be like this in the future:
```
/* check for ABI compatibility and create memory windows on first boot */
- int sof_fw_ready(struct snd_sof_dev *sdev, u32 msg_id)
+ int sof_fw_ready(struct snd_sof_dev *sdev, u32 offset)
{
	struct sof_ipc_fw_ready *fw_ready = &sdev->fw_ready;
-	int offset;
	int bar;
	int ret;

+      if (offset) {
-	/* mailbox must be on 4k boundary */
-	offset = snd_sof_dsp_get_mailbox_offset(sdev);
-	if (offset < 0) {
-		dev_err(sdev->dev, "error: have no mailbox offset\n");
-		return offset;
-	}
+              /* no valid offset from fw_ready message, use the default one */
+	        offset = snd_sof_dsp_get_mailbox_offset(sdev);
+	        if (offset < 0) {
+		        dev_err(sdev->dev, "error: have no mailbox offset\n");
+		        return offset;
+	        }
+        } else {
+                /* mailbox must be on 4k boundary */
+                offset <= 12;
+        }
```

_Originally posted by @keyonjie in https://github.com/thesofproject/linux/pull/1103_

**Comment by plbossart** [comment]
@dbaluta is this still required or was it fixed already with your changes?

**Comment by dbaluta** [comment]
@plbossart not fixed. I think this can be seen as a future enhancement.

**Comment by plbossart** [comment]
@dbaluta Is this still needed, I can't recall what the issue was?

**Comment by dbaluta** [comment]
Me too. Lets close it. I also added the gsoc label to look into it when we will have some resources from different open source initiatives like gsoc/outreachy.
