### ISSUE TITLE
HDA-legacy bugfix backport list to SOF

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1118]
This is a meta issue to track the task of porting bugfixes from legacy driver to SOF.

**HDA audio**

- [ ] ALSA: hda - Fix intermittent CORB/RIRB stall on Intel chips
      - commit https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?h=for-next&id=2756d9143aa517b97961e85412882b8ce31371a6

**HDMI (hdac-hdmi)** 

- not yet tracking -- currently investigating whether we can move to hdac-hdmi in SOF

**Comment by plbossart** [comment]
@kv2019i should we close this?
