### ISSUE TITLE
HDA: debugfs warnings on startup

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1122]
I see the following warnings on an Acer WHL laptop with HDAudio+DMICs

````
root@plb-Swift-SF314-55:~# dmesg | grep debugfs
[  108.612663] debugfs: Directory 'ehdaudio0D0-hdaudio' with parent 'regmap' already present!
[  108.914066] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  108.918372] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  108.972734] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  108.976863] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  109.087712] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  121.080840] debugfs: Directory 'ehdaudio0D0-hdaudio' with parent 'regmap' already present!
[  121.392215] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  121.396600] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  121.450987] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  121.454970] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
[  121.523875] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
````
This doesn't prevent any operation but tells me we have a leak somewhere.

**Comment by plbossart** [comment]
@kv2019i is this something you see as well?

**Comment by ranj063** [comment]
@plbossart I see this on the mantis too

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i is this something you see as well?

Hmm, actually no. On Mantis, neither in boot messages or while playing something (with latest sof-hda-generic-2ch.tplg topology). Same on a CFL system.

@ranj063 What topology and when do you get this on Mantis (during boot/mod-load I'd assume)?

**Comment by plbossart** [comment]
This looks really bad, when I add the following trace:

````diff
diff --git a/sound/soc/soc-pcm.c b/sound/soc/soc-pcm.c
index da657c8179cc..25f4f299c623 100644
--- a/sound/soc/soc-pcm.c
+++ b/sound/soc/soc-pcm.c
@@ -1171,6 +1171,7 @@ static int dpcm_be_connect(struct snd_soc_pcm_runtime *fe,
                        stream ? "<-" : "->", be->dai_link->name);
 
 #ifdef CONFIG_DEBUG_FS
+       pr_err("%s: debugfs_create_dir %s\n", __func__, be->dai_link->name);
        dpcm->debugfs_state = debugfs_create_dir(be->dai_link->name,
                                                 fe->debugfs_dpcm_root);
        debugfs_create_u32("state", 0644, dpcm->debugfs_state, &dpcm->state);
````

then I see that we are calling the same dpcm_be_connect() multiple times, so there's clearly a leak or bad flow somewhere that's only tracked by debugfs warnings....

**Comment by plbossart** [comment]
Dmesg log attached
[dmesg_debugfs.log](https://github.com/thesofproject/linux/files/3506509/dmesg_debugfs.log)

**Comment by plbossart** [comment]
@ranj063 can you take a look, I don't speak DPCM fluently :-)

**Comment by plbossart** [comment]
@wenqingfu can you assign someone on this one? I suspect it's a bad regression, we need to figure it out.

**Comment by ranj063** [comment]
@plbossart I'm picking this one up

**Comment by ranj063** [comment]
@plbossart I think these warnings are harmless. It looks like the debugfs entries are created just before when a PCM stream is opened and removed before the pcm is closed. Looking at the attached log, when Pulseaudio opens the playback stream first the debugfs entry creation succeeds. But when the capture stream is opened before the playback stream is closed, we see the warning. 

[  592.522405] dpcm_be_connect: debugfs_create_dir Analog Playback and Capture
**[  592.567722] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0**
[  592.567727] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[  592.567736] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[  592.567739] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[  592.568089] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  592.568305] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  592.568353] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[  592.568388] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 0
[  592.568394] sof-audio-pci 0000:00:1f.3: generating page table for 000000003ca92a57 size 0x4b00 pages 5
[  592.568422] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[  592.568455] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  592.568462] sof-audio-pci 0000:00:1f.3: period_bytes:0x12c0
[  592.568464] sof-audio-pci 0000:00:1f.3: periods:4
[  592.568491] sof-audio-pci 0000:00:1f.3: stream_tag 1
[  592.568503] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  592.568833] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  592.568842] sof-audio-pci 0000:00:1f.3: pcm: stream dir 0, posn mailbox offset is 790604
[  592.575083] dpcm_be_connect: debugfs_create_dir Analog Playback and Capture
[  592.575094] debugfs: Directory 'Analog Playback and Capture' with parent 'HDA Analog' already present!
**[  592.575109] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 1**

**Comment by plbossart** [comment]
Sorry @ranj063 'harmless' isn't an excuse... We shouldn't do this.
I think it comes from GKH's cleanups in 'ASoC: core: no need to check return value of debugfs_create functions' SHA1 fee531d6fc49b9a616525e30955c4cf3b403f632
````diff
 #ifdef CONFIG_DEBUG_FS
-	if (fe->debugfs_dpcm_root)
-		dpcm->debugfs_state = debugfs_create_u32(be->dai_link->name, 0644,
-				fe->debugfs_dpcm_root, &dpcm->state);
+	dpcm->debugfs_state = debugfs_create_dir(be->dai_link->name,
+						 fe->debugfs_dpcm_root);
+	debugfs_create_u32("state", 0644, dpcm->debugfs_state, &dpcm->state);
 #endif
````

**Comment by ranj063** [comment]
@plbossart what I meant by harmless was that for both the playback and capture streams "be->dai_link->name" will be the same. So the debugfs entry creation will fail or emit a warning when opening a capture stream while playback stream is already open. Going by Greg's commit, we should not handle this warning and just ignore it right?

**Comment by plbossart** [comment]
I think we should not go into a case where we generate a warning. Greg's point of not depending on the results of past debugfs calls is fine, but here it generates warnings for no good reason.

**Comment by plbossart** [comment]
this is no longer happening
