### ISSUE TITLE
[enhancement] Use snd-hda-codec-hdmi for  SOF HDMI/DP support

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1123]
There are currently two i915 HDMI codec implementations in upstream kernel, snd-hda-codec-hdmi (sound/pci/hda) and hdac_hdmi (sound/soc/codecs).

SOF is currently using the latter to enable HDMI/DP features for Intel HDA platforms.

Maintaining two codecs for the same hardware is not efficient as a fair amount of bugfixes and hw quirks are maintained for different hardware generations. And as of now, the snd-hda-codec-hdmi driver is much more widely used.

SOF should move to use the snd-hda-codec-hdmi driver as well and eventually to merge the drivers. SOF already reuses the HDAC library for HDA audio and HDMI/DP is programmed via HDA interface on the i915 hardware, so using this solution also for HDMI makes sense.

**Comment by fredoh9** [comment]
I'm attaching more logs for ICL HDA. This is not 100% reproducible, only sometimes I can see  this failures.
```
[    5.556801] sof-audio-pci 0000:00:1f.3: error: codec #1 probe error, ret: -5
[    5.556804] sof-audio-pci 0000:00:1f.3: Turning i915 HDAC power off
[    5.556957] sof-audio-pci 0000:00:1f.3: error: no matching ASoC machine driver found - aborting probe
[    5.556958] sof-audio-pci 0000:00:1f.3: error: failed to get machine info -19
[    5.556959] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -19
```
[0809_icl6_hdmi_error.log](https://github.com/thesofproject/linux/files/3493784/0809_icl6_hdmi_error.log)
[0812_icl5_hdmi_error.log](https://github.com/thesofproject/linux/files/3493785/0812_icl5_hdmi_error.log)
[0812_icl5_no_soundcard.log](https://github.com/thesofproject/linux/files/3493786/0812_icl5_no_soundcard.log)
[0812_icl6_booting_ok.log](https://github.com/thesofproject/linux/files/3493787/0812_icl6_booting_ok.log)

**Comment by kv2019i** [comment]
New patch series uploaded on https://github.com/thesofproject/linux/pull/1155 -- see progress update in the PR description.

**Comment by kv2019i** [comment]
This enhancement is now implemtend with #1404 and #1422
