### ISSUE TITLE
[BUG][BYT]Fail to boot system on byt rt5682 platform.

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/linux#1127]
***Describe the bug***
Fail to boot system on byt rt5682 platform: failed to start network manager wait online.

***To Reproduce***
1.Flash kernel version 87140602 and reboot.

***Actual result***
![webwxgetmsgimg](https://user-images.githubusercontent.com/44258626/62926332-e3979280-bde6-11e9-851d-088abfa0c9e0.jpg)

***Environment***
Firmware: c6f1b08f https://github.com/thesofproject/sof/commits/master
Kernel: 87140602 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: sof-byt-rt5682.tplg

**Comment by juimonen** [comment]
I have different error with same setup, for me it is: 
"ASoC: no sink widget found for DMic" and " ASoC: Failed to add route SoC DMIC -> direct ->DMic" 
then kernel NULL pointer dereference...

**Comment by juimonen** [comment]
@bardliao any idea of the above?

**Comment by bardliao** [comment]
@juimonen I think it is a bug from sof_rt5682.c
We add [{"DMic", NULL, "SoC DMIC"},](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_rt5682.c#L323) unconditionally. However, "DMic" is defined at [SND_SOC_DAPM_INPUT("DMic"),](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/dmic.c#L124), and we have to create a dai link for it.
But, we won't create DMIC dai link for byt.
[dmic_be_num = 0;](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_rt5682.c#L563)
So I think we should move ```{"DMic", NULL, "SoC DMIC"},``` to a separate dapm route.
Just like what we do for [{ "Spk", NULL, "Speaker" },](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_rt5682.c#L329)

**Comment by juimonen** [comment]
@bardliao, yes thanks, it fixes the issue (just my own quick hack with your suggestion). With that issue gone, I still can't boot to ubuntu UI. Not seeing it would be related to sound in any way....

**Comment by xiulipan** [comment]
@juimonen 
Are you seeing something like "A start job is running for ...."?

**Comment by juimonen** [comment]
@xiulipan yes exactly

**Comment by juimonen** [comment]
@xiulipan there's something really dodgy in ubuntu 18.04 in mb-byt when kernel crashes. Shutdown and boot after that takes ages.... don't know if it is writing some log etc. If I wait like 1/2 hour it will eventually boot to UI.

So my suspicion here is: without Bard's fix https://github.com/thesofproject/linux/pull/1133 kernel oopses and the UI gets into some log writing etc state which takes a long time. If you once wait for the UI to come up (some wait timeout is gone I guess) and have applied Bard's fix, the ubuntu works pretty normal.

I have to say that ubuntu ver 16 was slow on mb-byt but 18.04 is even slower in all respects...

**Comment by xiulipan** [comment]
@juimonen Actually if we changed a kernel, it will just boot very fast. And I think there will be some other issues with Net to make us can not boot.

Need to check what is the root-cause to this boo up. Or we can try to use some Xubuntu for test device.

**Comment by juimonen** [comment]
@xiulipan what kernel did you try? I tried 5.3rc3, rc2, rc1 without sof patches on top and had exactly same jam... the boot was just stuck all the time. Then once I waited for very long time, it booted to UI. then the consecutive boots we're faster...

**Comment by juimonen** [comment]
even the stock kernel coming with ubuntu 18.04 was stuck for me

**Comment by juimonen** [comment]
@xiulipan but I agree it could be something to do with network, maybe it is trying to send crash report with some huge timeout etc.

**Comment by plbossart** [comment]
@juimonen isn't this closed with the sof-rt5682 changes?

**Comment by Jiangxinx** [comment]
Passed as #1133 had been merged.
