### ISSUE TITLE
[CML] Recording volume via internal Mic is relatively low

### ISSUE THREAD

**Issue by ch181** [thesofproject/linux#1131]
Describe the bug
Input volume via DMIC is low 

To Reproduce
1. Record a sound clip using arecord (/w ~50% Input volume set in sound settings)
2. Play back the sound click (/w ~100% Output volume set in sound settings)

frequency
100% on CML laptop.

Actual result
The audio playback volume is low even at maximum volume setting

Expected result
The audio playback volume should be comparable to other non-DMIC systems

Environment
A CML laptop with the production SOF driver/firmware received from Intel

**Comment by ch181** [comment]
No obvious found in the alsa-info log from the failed unit
[alsa-info.txt](https://github.com/thesofproject/linux/files/3499630/alsa-info.txt)

**Comment by ranj063** [comment]
@ch181 can you please check if this PR helps? https://github.com/thesofproject/sof/pull/1725

**Comment by plbossart** [comment]
@ch181 any feedback? If not we'll close as won't fix.

**Comment by plbossart** [comment]
no feedback in 27 days, closing.
