### ISSUE TITLE
Support unloading/reloading a subset of pipelines(and its widgets/components) when they are not used.

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#1146]
On some platforms like byt/cht, there is very limited SRAM for aDSP to use, and on other platforms when aDSP run on D0ix, we hope to use as less of the SRAM as possible, so adding support to unload a subset of all existed pipelines(and its widgets/components) from FW is meaningful and inevitable.

To implement the feature on today's base, changes needed in driver side:

1. Keep all widgets (pipeline components for FW), routes (pipeline connection for FW), dais (dai config for FW), kcontrol values stored in driver side after they are created at topology binary parsing, even though they are unloaded in FW.

2. Implement a helper function to unload/free and reload/new a specific pipeline and then its widgets(check with swidget->pipeline_id).

3. call helper function implemented in #2 at d0i0<->d0i3 transition, for each idle PCMs(need to figure out how to find pipeline_id from PCM), to unload/reload the subset of pipelines and its widgets.

**Comment by keyonjie** [comment]
@plbossart @ranj063 @mmaka1 @lbetlej please help review this feature reqirement.

**Comment by plbossart** [comment]
For power optimizations, you want to have both D0ix signaling and activation of pipelines on a need basis, but each can be developed separately. You will have a lot of development issues if you lump the two aspects in one milestone. one step at a time is my recommendation.

**Comment by keyonjie** [comment]
> For power optimizations, you want to have both D0ix signaling and activation of pipelines on a need basis, but each can be developed separately. You will have a lot of development issues if you lump the two aspects in one milestone. one step at a time is my recommendation.

Good point, thanks.

**Comment by plbossart** [comment]
@keyonjie @ranj063 isn't this implemented with dynamic pipelines already? If yes there's no reason to keep this as an enhancement request. Please close unless I missed something.

**Comment by mengdonglin** [comment]
@RanderWang I think this is the driver behavior to work with converged FW. Right?

**Comment by RanderWang** [comment]
> @RanderWang I think this is the driver behavior to work with converged FW. Right?

sure, driver will disable everything unnecessary in FW.

**Comment by ranj063** [comment]
@mengdonglin no this is a feature already available today in SOF.
