### ISSUE TITLE
[BUG][playback] Underrun after pause-release on HDA Link pipelines

### ISSUE THREAD

**Issue by tlauda** [thesofproject/linux#1160]
There is a random underrun after pause-release sequence done on HDA Link pipelines. Repro rate is under 5%. It shows up during CI tests. It looks like Link DMA doesn't copy anything after release, so DSP has no free space for copying data from buffer.
There are two possibilities that we could check:
1. See if the right Link DMA is started by kernel after release. I remember that we've already had such problem before.
2. Fix sequence of pausing/stopping the pipelines. Kernel should first send pause/stop ipc to the FW and only then deassert stream RUN bit. Doing it other way around can potentially lead to incrementing Gateway FPI by the DSP, when RUN bit is already 0 and such behavior can have undefined consequences.

**Comment by tlauda** [comment]
@mengdonglin @wenqingfu Could you assign someone to this issue? It's randomly failing CI.

**Comment by mengdonglin** [comment]
Xiuli is fixing PCM STOP sequence in https://github.com/thesofproject/linux/pull/1169

But we still need to fix PCM PAUSE sequence for the rendering pipeline here , please see comment:　https://github.com/thesofproject/linux/pull/1169#issuecomment-527762654

**Comment by mengdonglin** [comment]
Pause/release problem on capture is a different issue and tracked by https://github.com/thesofproject/sof/issues/1760

**Comment by ranj063** [comment]
> But we still need to fix PCM PAUSE sequence for the rendering pipeline here , please see comment:　[#1169 (comment)](https://github.com/thesofproject/linux/pull/1169#issuecomment-527762654)

@mengdonglin PR #1169 addresses both the STOP and the PAUSE sequence. And I am having a very hard time reproducing this issue with that PR. Could we have a stress test run with this PR to make sure this is still reproducible?

**Comment by fredoh9** [comment]
@ranj063 @xiulipan 
I ran stress test, pause-resume-playback test on my UP2. I upgraded to 0917 daily build(without this PR) and run 1000 times. I slightly modify the script to run only hw:0,1(first HDMI PCM device). I was able to reproduce  `aplay: pcm_write:2011: write error: Input/output error` 2-3 times.
Then I pick up PR #1169, first 1000 times, there was no error. But I found a problem next 1000 iteration.
[0916_sof-logger.log](https://github.com/thesofproject/linux/files/3618484/0916_sof-logger.log)
[0916_xiuli_stop_seq_failure.log](https://github.com/thesofproject/linux/files/3618485/0916_xiuli_stop_seq_failure.log)

BTW, I ran stress test on two WHL_RVP_HDAs too, Even without this PR(0917 daily build), I couldn't reproduce this issue. I was hoping we may see some failure like CML_MANTIS_HDA.

**Comment by xiulipan** [comment]
@fredoh9 
There maybe a chance that the I/O have some issue?
Not sure where is the error comes from.

**Comment by ranj063** [comment]
@xiulipan it is an underrun in the DAI comp. Sometimes it takes forever to hit the issue. But sometimes you hit it right away

**Comment by ranj063** [comment]
@tlauda I am able to hit the underrun even with the sequence change to PAUSE?STOP in @xiulipan 's PR #1169 . I've attached the logs herewith, I've added some more trace in the code  to show what is actually going on. Eventually, when the xrun occurs, it looks like the dai_copy() fails because the dma buffer is full. DGCS & DGCS_BF is true. Could you please take a look?
[apl-pause-resume-log.txt](https://github.com/thesofproject/linux/files/3622597/apl-pause-resume-log.txt)

**Comment by xiulipan** [comment]
@ranj063 Actually there are two issues from @tlauda one is for pause/release playback and on is for capture. The #1169 will only fix playback but capture is something wrong with inside FW.

**Comment by ranj063** [comment]
@xiulipan Im only talking about playback here.

**Comment by xiulipan** [comment]
@ranj063 
The issue happen at the release, and a bit different with the issue I meet with stop. It seems @tlauda 2 is already fixed. So we need to check if his guess 1 is valid issue here.

>1. See if the right Link DMA is started by kernel after release. I remember that we've already had such problem before.

**Comment by mengdonglin** [comment]
@tlauda Can you please check if you still see this issue with https://github.com/thesofproject/linux/pull/1250?  I feel 1 should be okay with #1250

**Comment by tlauda** [comment]
@mengdonglin If it's already merged for CI, then the issue is still visible.

**Comment by tlauda** [comment]
@mengdonglin @ranj063 @xiulipan @fredoh9 @kv2019i  I think I have finally rootcaused the issue. The problem is  in start sequence. HDA Link DMA is started **after** trigger start ipc is sent to FW. HDA Link pipelines are scheduled on timer, so first pipeline copy can happen before even link is set to run. We end up filling the buffer, but since the link is not yet enabled, the data is not consumed. I assume that even if the Link DMA is started moments later, it doesn't see any data to consume. The issue is not seen on TRIGGER_START, because due to preload in FW the start is deferred by 1 ms. That's why only TRIGGER_RELEASE is affected.

**Comment by ranj063** [comment]
@tlauda good finding. But I can see the same problem even if we start DMA first and then send the start IPC too. How do we explain that?

**Comment by tlauda** [comment]
@ranj063 Can you attach kernel diff for your change and also retry with https://github.com/thesofproject/sof/pull/1891 included?
I need diff, so I could retest this myself.

**Comment by ranj063** [comment]
@tlauda there's no changes in my kernel. What I meant was that I am able to hit this issue on APL with or without the kernel PR #1169 which switches the order in which the IPC is sent and the DMA is stopped/started. 

I just tried the FW PR 1891 and still hit the issue as well.

**Comment by ranj063** [comment]
@tlauda I am in the process of implementing the nocodec support for link DMA and I had a couple of questions for you:
1. Just like we have the nocodec support for SSP, does it make sense to do the same for Link DMA? 
2. If so, the idea is to not initialize the i915 and probe the codecs. Is it just enough if I have pick a Link DMA stream tag and start the stream for such a mode to work?

**Comment by tlauda** [comment]
@ranj063 Change in stop sequence was also needed, but it doesn't fix this particular problem. We also have a problem with start sequence. You cannot start pipeline in FW and start Link DMA after that. It needs to be the other way around. Could you try to make such change in kernel and see if you still see the issue?
As for nocodec mode, I don't think it's going to work. There needs to be something, that will consume the data from the link. Without the codec I think that DSP will see full buffer gateway all the time and it'll end up in overrun.

**Comment by ranj063** [comment]
> @ranj063 Change in stop sequence was also needed, but it doesn't fix this particular problem. We also have a problem with start sequence. You cannot start pipeline in FW and start Link DMA after that. It needs to be the other way around. Could you try to make such change in kernel and see if you still see the issue?
> As for nocodec mode, I don't think it's going to work. There needs to be something, that will consume the data from the link. Without the codec I think that DSP will see full buffer gateway all the time and it'll end up in overrun.



> @ranj063 Change in stop sequence was also needed, but it doesn't fix this particular problem. We also have a problem with start sequence. You cannot start pipeline in FW and start Link DMA after that. It needs to be the other way around. Could you try to make such change in kernel and see if you still see the issue?

@tlauda the START/RELEASE sequence in the kernel already does start Link DMA and then send the START IPC.

**Comment by ranj063** [comment]
> As for nocodec mode, I don't think it's going to work. There needs to be something, that will consume the data from the link. Without the codec I think that DSP will see full buffer gateway all the time and it'll end up in overrun.

@tlauda are you sure about this? @plbossart suggested that this should work even if there is no codec to consume the data.

**Comment by plbossart** [comment]
On 10/3/19 9:29 AM, Ranjani Sridharan wrote:
>     As for nocodec mode, I don't think it's going to work. There needs
>     to be something, that will consume the data from the link. Without
>     the codec I think that DSP will see full buffer gateway all the time
>     and it'll end up in overrun.
> 
> @tlauda <https://github.com/tlauda> are you sure about this? @plbossart 
> <https://github.com/plbossart> suggested that this should work even if 
> there is no codec to consume the data.

Yes, the PCH owns the clock and can push data out even if there is no 
codec consuming the data.
The example I have in mind is sending audio to the HDMI devices in 
legacu mode when there is no HDMI link. It just consumes data at the 
usual 48kHz rate.
