### ISSUE TITLE
kabylake/skylake load firmware

### ISSUE THREAD

**Issue by zhuyingjiang** [thesofproject/linux#117]
The Skylake/Kabylake has different load firmware sequence with APL, and the different DMA. This issue is to track enable skylake/kabylake to load the firmware

**Comment by zhuyingjiang** [comment]
with call the  snd_dma_alloc_pages the error occurs: 

[   15.292195] sof-audio sof-audio: in ==cl_stream_prepare_skl==1===
[   15.292196] sof-audio sof-audio: in =====cl_alloc_dma_buf_skl====
[   15.292212] WARNING: CPU: 6 PID: 82 at ./include/linux/dma-mapping.h:516 snd_dma_alloc_pages+0x144/0x1e0 [snd_pcm]
[   15.292212] Modules linked in: sof_pci_dev snd_sof_intel_hda_common snd_sof_intel_byt intel_rapl snd_sof_nocodec snd_sof x86_pkg_temp_thermal snd_sof_xtensa_dsp intel_powerclamp snd_soc_acpi_intel_match coretemp snd_soc_acpi snd_soc_core kvm_intel snd_compress kvm arc4 snd_pcm_dmaengine ac97_bus irqbypass joydev snd_pcm iwlmvm snd_seq_midi mac80211 snd_seq_midi_event crct10dif_pclmul snd_rawmidi crc32_pclmul 8250_dw snd_seq snd_seq_device ghash_clmulni_intel snd_timer pcbc snd iwlwifi soundcore btusb aesni_intel idma64 aes_x86_64 input_leds virt_dma crypto_simd btrtl btbcm cryptd processor_thermal_device glue_helper serio_raw btintel int340x_thermal_zone intel_lpss_pci bluetooth cfg80211 mei_me ecdh_generic intel_soc_dts_iosf mei intel_pch_thermal intel_lpss int3400_thermal acpi_thermal_rel mac_hid
[   15.292233]  acpi_pad nfsd auth_rpcgss nfs_acl lockd grace sunrpc parport_pc ppdev lp parport autofs4 hid_generic usbhid hid i915 i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops e1000e drm sdhci_pci ahci cqhci sdhci libahci wmi pinctrl_sunrisepoint video pinctrl_intel
[   15.292247] CPU: 6 PID: 82 Comm: kworker/6:1 Not tainted 4.18.0+ #2
[   15.292247] Hardware name: Intel Corporation Kabylake Client platform/Kabylake R DDR4 RVP, BIOS KBLSE2R1.R00.X073.P03.1701171658 01/17/2017
[   15.292250] Workqueue: events request_firmware_work_func
[   15.292253] RIP: 0010:snd_dma_alloc_pages+0x144/0x1e0 [snd_pcm]
[   15.292254] Code: b7 00 00 00 48 83 c4 10 5b 5d 41 5c 41 5d c3 83 ff 01 75 1d 48 89 d7 e8 5a fe ff ff 48 c7 43 18 00 00 00 00 48 89 43 10 eb b7 <0f> 0b e9 6d ff ff ff 89 fe 48 c7 c7 f0 da 82 c0 e8 65 ab 8b e3 48 
[   15.292270] RSP: 0018:ffffab51c11afb60 EFLAGS: 00010246
[   15.292271] RAX: ffff9237eebf7410 RBX: ffff9237eebf1618 RCX: 0000000000000000
[   15.292271] RDX: 000000000000001f RSI: ffff9237eebf7410 RDI: 0000000000000002
[   15.292272] RBP: 0000000000020000 R08: 0000000000000001 R09: 0000000000000384
[   15.292272] R10: 00000000000002f1 R11: 0000000000000384 R12: 0000000000000004
[   15.292273] R13: ffffffffa4e1a9e0 R14: 0000000000000029 R15: 0000000000000000
[   15.292274] FS:  0000000000000000(0000) GS:ffff9237fed80000(0000) knlGS:0000000000000000
[   15.292274] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   15.292275] CR2: 00007f62d007b000 CR3: 00000001e020a003 CR4: 00000000003606e0
[   15.292276] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   15.292276] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   15.292277] Call Trace:
[   15.292281]  cl_dsp_init_skl+0xc4/0x280 [snd_sof_intel_hda_common]
[   15.292282]  hda_dsp_cl_boot_firmware_skl+0x44/0x180 [snd_sof_intel_hda_common]
[   15.292285]  snd_sof_run_firmware+0x7a/0x1d0 [snd_sof]
[   15.292287]  ? request_firmware+0x3b/0x50
[   15.292289]  sof_probe+0x1a8/0x330 [snd_sof]
[   15.292291]  platform_drv_probe+0x3a/0x90
[   15.292293]  ? driver_sysfs_add+0x71/0xd0
[   15.292294]  driver_probe_device+0x2b0/0x490
[   15.292295]  ? __driver_attach+0x110/0x110
[   15.292296]  bus_for_each_drv+0x64/0xb0
[   15.292297]  __device_attach+0xd9/0x150
[   15.292299]  bus_probe_device+0x8a/0xa0
[   15.292300]  device_add+0x3bc/0x620
[   15.292302]  ? complete_all+0x31/0x40
[   15.292303]  platform_device_add+0x100/0x260
[   15.292305]  platform_device_register_full+0xf0/0x120
[   15.292306]  sof_pci_fw_cb+0x6a/0xc0 [sof_pci_dev]
[   15.292308]  request_firmware_work_func+0x47/0x90
[   15.292310]  process_one_work+0x15e/0x3d0
[   15.292311]  worker_thread+0x4c/0x440
[   15.292313]  kthread+0xf8/0x130
[   15.292314]  ? rescuer_thread+0x350/0x350
[   15.292315]  ? kthread_associate_blkcg+0x90/0x90
[   15.292317]  ret_from_fork+0x35/0x40
[   15.292319] ---[ end trace 7439e9ae441b9717 ]---
[   15.292320] sof-audio sof-audio: Alloc FW buffer failed: fffffff4
[   15.292321] sof-audio sof-audio: CL dma prepare failed : -12
[   15.292324] BUG: unable to handle kernel paging request at ffffab51c1510000
[   15.292342] PGD 2b6142067 P4D 2b6142067 PUD 2b6143067 PMD 2aabf2067 PTE 0
[   15.292357] Oops: 0000 [#1] SMP PTI
[   15.292364] CPU: 6 PID: 82 Comm: kworker/6:1 Tainted: G        W         4.18.0+ #2
[   15.292379] Hardware name: Intel Corporation Kabylake Client platform/Kabylake R DDR4 RVP, BIOS KBLSE2R1.R00.X073.P03.1701171658 01/17/2017
[   15.292403] Workqueue: events request_firmware_work_func
[   15.292415] RIP: 0010:hda_dsp_read+0x5/0x10 [snd_sof_intel_hda_common]
[   15.292427] Code: 68 f7 87 c0 eb e1 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 89 16 c3 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 <8b> 06 c3 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 89 16 c3 0f 1f 
[   15.292477] RSP: 0018:ffffab51c11afa88 EFLAGS: 00010286
[   15.292487] RAX: ffffffffc087a0c0 RBX: ffff9237eebf1418 RCX: ffffab51c1490000
[   15.292501] RDX: 0000000000000000 RSI: ffffab51c1510000 RDI: ffff9237eebf1418
[   15.292514] RBP: ffff9237eebf1418 R08: 0000000000000001 R09: 00000000000003b3
[   15.292528] R10: 00000000000002f1 R11: 00000000000003b3 R12: ffff9237eebf1618
[   15.292541] R13: ffff9237eebf7410 R14: 0000000000000029 R15: 0000000000000000
[   15.292555] FS:  0000000000000000(0000) GS:ffff9237fed80000(0000) knlGS:0000000000000000
[   15.292570] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   15.292581] CR2: ffffab51c1510000 CR3: 00000001e020a003 CR4: 00000000003606e0
[   15.292595] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   15.292611] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   15.292628] Call Trace:
[   15.292637]  hda_dsp_get_status+0x2c/0xb0 [snd_sof_intel_hda_common]
[   15.292670]  hda_dsp_dump+0x29/0x240 [snd_sof_intel_hda_common]
[   15.292684]  ? dev_printk_emit+0x4a/0x70
[   15.292693]  ? dev_err+0x64/0x80
[   15.292703]  ? snd_dma_alloc_pages+0xc0/0x1e0 [snd_pcm]
[   15.292715]  cl_dsp_init_skl+0x224/0x280 [snd_sof_intel_hda_common]
[   15.292728]  hda_dsp_cl_boot_firmware_skl+0x44/0x180 [snd_sof_intel_hda_common]
[   15.292744]  snd_sof_run_firmware+0x7a/0x1d0 [snd_sof]
[   15.292756]  ? request_firmware+0x3b/0x50
[   15.292766]  sof_probe+0x1a8/0x330 [snd_sof]
[   15.292776]  platform_drv_probe+0x3a/0x90
[   15.292786]  ? driver_sysfs_add+0x71/0xd0
[   15.292794]  driver_probe_device+0x2b0/0x490
[   15.292804]  ? __driver_attach+0x110/0x110
[   15.292813]  bus_for_each_drv+0x64/0xb0
[   15.292823]  __device_attach+0xd9/0x150
[   15.292847]  bus_probe_device+0x8a/0xa0
[   15.292855]  device_add+0x3bc/0x620
[   15.292863]  ? complete_all+0x31/0x40
[   15.292871]  platform_device_add+0x100/0x260
[   15.292881]  platform_device_register_full+0xf0/0x120
[   15.292891]  sof_pci_fw_cb+0x6a/0xc0 [sof_pci_dev]
[   15.292902]  request_firmware_work_func+0x47/0x90
[   15.292912]  process_one_work+0x15e/0x3d0
[   15.293446]  worker_thread+0x4c/0x440
[   15.293984]  kthread+0xf8/0x130
[   15.294527]  ? rescuer_thread+0x350/0x350
[   15.295076]  ? kthread_associate_blkcg+0x90/0x90
[   15.295637]  ret_from_fork+0x35/0x40
[   15.296231] Modules linked in: sof_pci_dev snd_sof_intel_hda_common snd_sof_intel_byt intel_rapl snd_sof_nocodec snd_sof x86_pkg_temp_thermal snd_sof_xtensa_dsp intel_powerclamp snd_soc_acpi_intel_match coretemp snd_soc_acpi snd_soc_core kvm_intel snd_compress kvm arc4 snd_pcm_dmaengine ac97_bus irqbypass joydev snd_pcm iwlmvm snd_seq_midi mac80211 snd_seq_midi_event crct10dif_pclmul snd_rawmidi crc32_pclmul 8250_dw snd_seq snd_seq_device ghash_clmulni_intel snd_timer pcbc snd iwlwifi soundcore btusb aesni_intel idma64 aes_x86_64 input_leds virt_dma crypto_simd btrtl btbcm cryptd processor_thermal_device glue_helper serio_raw btintel int340x_thermal_zone intel_lpss_pci bluetooth cfg80211 mei_me ecdh_generic intel_soc_dts_iosf mei intel_pch_thermal intel_lpss int3400_thermal acpi_thermal_rel mac_hid
[   15.298338]  acpi_pad nfsd auth_rpcgss nfs_acl lockd grace sunrpc parport_pc ppdev lp parport autofs4 hid_generic usbhid hid i915 i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops e1000e drm sdhci_pci ahci cqhci sdhci libahci wmi pinctrl_sunrisepoint video pinctrl_intel
[   15.299144] CR2: ffffab51c1510000
[   15.299946] ---[ end trace 7439e9ae441b9718 ]---
[   15.300793] RIP: 0010:hda_dsp_read+0x5/0x10 [snd_sof_intel_hda_common]
[   15.301617] Code: 68 f7 87 c0 eb e1 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 89 16 c3 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 <8b> 06 c3 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 89 16 c3 0f 1f 
[   15.302515] RSP: 0018:ffffab51c11afa88 EFLAGS: 00010286
[   15.303412] RAX: ffffffffc087a0c0 RBX: ffff9237eebf1418 RCX: ffffab51c1490000
[   15.304354] RDX: 0000000000000000 RSI: ffffab51c1510000 RDI: ffff9237eebf1418
[   15.305275] RBP: ffff9237eebf1418 R08: 0000000000000001 R09: 00000000000003b3
[   15.306206] R10: 00000000000002f1 R11: 00000000000003b3 R12: ffff9237eebf1618
[   15.307146] R13: ffff9237eebf7410 R14: 0000000000000029 R15: 0000000000000000
[   15.308126] FS:  0000000000000000(0000) GS:ffff9237fed80000(0000) knlGS:0000000000000000
[   15.309098] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   15.310067] CR2: ffffab51c1510000 CR3: 00000001e020a003 CR4: 00000000003606e0
[   15.311052] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   15.312077] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   16.104209] Adding 8271868k swap on /dev/sda3.  Priority:-2 extents:1 across:8271868k FS
[   16.336361] asix 1-6:1.0 eth0: register 'asix' at usb-0000:00:14.0-6, ASIX AX88772 USB 2.0 Ethernet, 00:24:8c:01:36:21
[   16.336420] usbcore: registered new interface driver asix
[   16.337188] sof-nocodec sof-nocodec: ASoC: CPU DAI SSP0 Pin not registered

**Comment by wenqingfu** [comment]
are we done with SKL/KBL fw loading? can we close this tracker? @zhuyingjiang

**Comment by zhuyingjiang** [comment]
Yes, this is done, close it.
