### ISSUE TITLE
[BUG][SDW]Aplay -l shows no soundcards when system boot up.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1172]
**Describe the bug**
Aplay -l shows no soundcards when system boot up. Run ./sof_remove.sh then ./sof_insert.sh scripts can recover the issue.

**To Reproduce**

1.Do system reboot
2.Run "aplay -l"

**frequency**

30%

**Expected result**
aplay -l shows all playback devices

**Actual result**
aplay -l shows no soundcards

**Environment**
Firmware: 0223d94 https://github.com/thesofproject/sof/commits/sdw-001-drop-stable 
+PR https://github.com/thesofproject/sof/pull/1781
Kernel: a8f3408 https://github.com/thesofproject/linux/commits/integration/soundwire-alpha 
Topology: file: same with firmware branch, sof-icl-rt700.m4
platform: ICLL RVP with onboard ALC700 in SDW mode

**dmesg**
```
[    3.564387] int-sdw int-sdw.0: Updating Slave 1 status
[    3.564390] int-sdw int-sdw.0: sdw_handle_slave_status: Updating Slave 1 status done
[    3.564392] int-sdw int-sdw.0: sdw_handle_slave_status: end
[    3.564397] int-sdw int-sdw.0: sdw_cdns_thread: Slave sticky status 00000060 00000000
[    3.564401] int-sdw int-sdw.0: sdw_cdns_thread: end
[    3.564492] int-sdw int-sdw.0: sdw_cdns_thread: start
[    3.564496] int-sdw int-sdw.0: sdw_cdns_thread: Slave sticky status 00000020 00000000
[    3.564498] int-sdw int-sdw.0: sdw_handle_slave_status: start
[    3.564499] int-sdw int-sdw.0: processing Slave 1 Status 1
[    3.564501] int-sdw int-sdw.0: Slave 1 status attached, was alert, ignoring
[    3.564502] int-sdw int-sdw.0: Updating Slave 1 status
[    3.564504] int-sdw int-sdw.0: sdw_handle_slave_status: Updating Slave 1 status done
[    3.564505] int-sdw int-sdw.0: sdw_handle_slave_status: end
[    3.564515] int-sdw int-sdw.0: sdw_cdns_thread: Slave sticky status 00000020 00000000
[    3.564519] int-sdw int-sdw.0: sdw_cdns_thread: end
[    3.603467] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x5000001 successful
[    3.616490] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x5 successful
[    3.616966] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[    3.616971] sof-audio-pci 0000:00:1f.3: Firmware download successful, booting...
[    3.618515] Console: switching to colour frame buffer device 480x135
[    3.623100] sof-audio-pci 0000:00:1f.3: ipc rx: 0x70000000: FW_READY
[    3.623104] sof-audio-pci 0000:00:1f.3: ipc: DSP is ready 0x70000000 offset 0x81000
[    3.623245] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:1:0-d200a
[    3.623247] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:10:0 Kernel ABI 3:10:0
[    3.623496] sof-audio-pci 0000:00:1f.3: found ext header type 1 size 0xb8
[    3.623556] sof-audio-pci 0000:00:1f.3:  mailbox upstream 0x81000 - size 0x1000
[    3.623558] sof-audio-pci 0000:00:1f.3:  mailbox downstream 0xa0000 - size 0x2000
[    3.623559] sof-audio-pci 0000:00:1f.3:  stream region 0xc1000 - size 0x1000
[    3.623564] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x70000000: FW_READY
[    3.623660] sof-audio-pci 0000:00:1f.3: firmware boot complete
[    3.623680] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[    3.623694] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000002 at  00000048
[    3.623705] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000004 at  00000044
[    3.623712] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000000 at  00000044
[    3.623737] sof-audio-pci 0000:00:1f.3: generating page table for 00000000690e609b size 0x10000 pages 16
[    3.623739] sof-audio-pci 0000:00:1f.3: dma_trace_pages: 16
[    3.623771] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[    3.623808] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[    3.623813] sof-audio-pci 0000:00:1f.3: period_bytes:0x0
[    3.623814] sof-audio-pci 0000:00:1f.3: periods:1
[    3.623848] sof-audio-pci 0000:00:1f.3: stream_tag: 1
[    3.623855] sof-audio-pci 0000:00:1f.3: ipc tx: 0x90030000: GLB_TRACE_MSG
[    3.624270] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x90030000: GLB_TRACE_MSG
[    3.624831] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x2014001e successful
[    3.624912] sof-audio-pci 0000:00:1f.3: created machine sdw_rt700
[    3.624913] sof-audio-pci 0000:00:1f.3: Completing SOF PCI probe
[    3.628506] sdw_rt700 sdw_rt700: Entry mc_probe
[    3.628517] sdw_rt700 sdw_rt700: ASoC: failed to init link iDisp1: -517
[    3.628519] sdw_rt700 sdw_rt700: snd_soc_register_card failed -517
[    3.634625] asix 3-8.1:1.0 eth0: register 'asix' at usb-0000:00:14.0-8.1, ASIX AX88772B USB 2.0 Ethernet, 00:0e:c6:c6:86:b2
[    3.634679] sdhci-pci 0000:00:14.5: SDHCI controller found [8086:34f8] (rev 30)
[    3.636000] sdw_rt700 sdw_rt700: Entry mc_probe
[    3.636009] sdw_rt700 sdw_rt700: ASoC: failed to init link iDisp1: -517
[    3.636011] sdw_rt700 sdw_rt700: snd_soc_register_card failed -517
[    3.636142] usbcore: registered new interface driver asix
[    3.641052] asix 3-8.1:1.0 enx000ec6c686b2: renamed from eth0
[    3.657830] i915 0000:00:02.0: fb0: i915drmfb frame buffer device
[    3.778956] systemd-udevd (326) used greatest stack depth: 12224 bytes left
[    4.293868] int-sdw int-sdw.0: sdw_cdns_thread: start
[    4.293873] int-sdw int-sdw.0: sdw_cdns_thread: Slave sticky status 00000040 00000000
[    4.293874] int-sdw int-sdw.0: sdw_handle_slave_status: start
[    4.293875] int-sdw int-sdw.0: processing Slave 1 Status 2
[    4.294168] rt700 sdw:0:25d:700:0:0: Slave impl defined interrupt
[    4.294172] rt700 sdw:0:25d:700:0:0: rt700_interrupt_callback control_port_stat=4
[    4.294592] int-sdw int-sdw.0: Updating Slave 1 status
[    4.294595] int-sdw int-sdw.0: sdw_handle_slave_status: Updating Slave 1 status done
[    4.294597] int-sdw int-sdw.0: sdw_handle_slave_status: end
[    4.294612] int-sdw int-sdw.0: sdw_cdns_thread: Slave sticky status 00000060 00000000
[    4.294616] int-sdw int-sdw.0: sdw_cdns_thread: end
[    4.294710] int-sdw int-sdw.0: sdw_cdns_thread: start
```
[NosoundCard_dmesg.log](https://github.com/thesofproject/linux/files/3558136/NosoundCard_dmesg.log)
[Nosoundcard_logger.log](https://github.com/thesofproject/linux/files/3558137/Nosoundcard_logger.log)

**Comment by plbossart** [comment]
please retest with firmware master and kernel integration/soundwire-latest

**Comment by YvonneYang2** [comment]
Whether set "options snd_sof_pci sof_debug=1" in /etc/modprobe.d/alsa-base.conf  or not, issue still can be reproduced with test recipe as below. 

Add snd_sof_pci in blacklist.conf, and set "options snd_sof_pci sof_debug=1" in /etc/modprobe.d/alsa-base.conf. Reboot system, then modprobe modules can recover the issue.

**Reproduced rate** 
9/10

Test recipe:
Firmware: 460c41aa https://github.com/thesofproject/sof/commits/master
Kernel: 4ac5440 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg:  sof-icl-rt700.tplg
platform: ICL RVP with codec ALC700 in SDW mode

**dmesg**
```
[    3.665903] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[    3.732586] asix 3-8.1:1.0 eth0: register 'asix' at usb-0000:00:14.0-8.1, ASIX AX88772B USB 2.0 Ethernet, 00:0e:c6:c6:86:f2
[    3.732608] usbcore: registered new interface driver asix
[    3.732751] sdhci-pci 0000:00:14.5: SDHCI controller found [8086:34f8] (rev 30)
[    3.736566] asix 3-8.1:1.0 enx000ec6c686f2: renamed from eth0
[    4.056173] iwlwifi 0000:00:14.3: Applying debug destination EXTERNAL_DRAM
[    4.217076] iwlwifi 0000:00:14.3: FW already configured (0) - re-configuring
[    4.224566] iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS
[    5.373862] IPv6: ADDRCONF(NETDEV_CHANGE): enx000ec6c686f2: link becomes ready
[    5.376867] asix 3-8.1:1.0 enx000ec6c686f2: link up, 100Mbps, full-duplex, lpa 0xCDE1
[    5.591696] HDMI HDA Codec ehdaudio0D2: HDMI: failed to get afg sub nodes
[    5.591700] HDMI HDA Codec ehdaudio0D2: Failed in parse and map nid with err: -22
[    5.591718] HDMI HDA Codec: probe of ehdaudio0D2 failed with error -22
[    5.594058] sdw_rt700 sdw_rt700: Entry mc_probe
[    5.594072] sdw_rt700 sdw_rt700: ASoC: failed to init link iDisp1: -517
[    5.594079] sdw_rt700 sdw_rt700: snd_soc_register_card failed -517
[    5.597862] systemd-udevd (298) used greatest stack depth: 12208 bytes left
[   34.736064] random: crng init done
[   34.736068] random: 7 urandom warning(s) missed due to ratelimiting
[   36.942656] rfkill: input handler disabled
```
[dmesg.log](https://github.com/thesofproject/linux/files/3634394/dmesg.log)

**Comment by YvonneYang2** [comment]
Issue still reproduced on icl rvp rt700 when run modules reload stress test 17th.

[reload_fail_dmesg.txt](https://github.com/thesofproject/linux/files/3646028/reload_fail_dmesg.txt)

Test recipe:
Firmware: 9794dd7 https://github.com/thesofproject/sof/commits/master + +PR1851 (For HDMI tplg)
Kernel: 07bdd03 https://github.com/thesofproject/linux/tree/integration/soundwire-latest-pm
tplg:  sof-icl-rt700.tplg same path as FW.
platform: ICL RVP, with codec ALC700 in SDW mode

**Comment by plbossart** [comment]
what does 'system boot up' mean?

can you clarify if
a) this error happens only when booting (initial probe without any blacklist for snd-sof-pci)?
b) this error happens during a module load/unload test?

Also the error reported is related to HDMI, please test without HDMI....

The code updated on integration/soundwire-latest has fixes for startup race conditions, please test. I ran module load/unload tests without HDMI overnight without issues.

**Comment by YvonneYang2** [comment]
> Also the error reported is related to HDMI, please test without HDMI....

Tried to remove HDMI via Device Drivers  --->  <*> Sound card support  --->  <*>   Advanced Linux Sound  Architecture  --->ALSA for SoC audio support ---> unmark SOF support for HAD Links (HAD/HDMI), but it seems not work. Could you help to share how to test without HDMI ? Thanks.

> The code updated on integration/soundwire-latest has fixes for startup race conditions, please test. I ran module load/unload tests without HDMI overnight without issues.

On latest FW and Kernel on master and integration/soundwire-latest, 
**Test preconditions:**
set "options snd-sof-pci sof_debug=1" and "options soundwire_intel sdw_md_flags=0x01010101" in /etc/modprobe.d/alsa-base.conf	

boot up with 4 scenarios as below:

1. Boot up with blacklist for snd-sof-pci and without HDMI connected: **Fail**
2. Boot up with blacklist for snd-sof-pci and with HDMI connected: **Pass**
3. Boot up without blacklist for snd-sof-pci and without HDMI connected: **Fail**
4. Boot up without blacklist for snd-sof-pci and with HDMI connected: **Fail**

Do module reload stress test with 2 scenarios as below:
1. Do module reload with HDMI connected : **pass for 40 times**
2. Do module reload without HDMI connected : **Fail at 5th**

Moreover, found similar issue on icl hda, please see https://github.com/thesofproject/linux/issues/1184

Logs please see:
[boot_without_blst_with_HDMI.log](https://github.com/thesofproject/linux/files/3651701/boot_without_blst_with_HDMI.log)
[boot_without_blst_without_HDMI.log](https://github.com/thesofproject/linux/files/3651703/boot_without_blst_without_HDMI.log)
[module_reload_stress_fail_at_5th.log](https://github.com/thesofproject/linux/files/3651705/module_reload_stress_fail_at_5th.log)
[boot_with_blst_with_HDMI.log](https://github.com/thesofproject/linux/files/3651706/boot_with_blst_with_HDMI.log)
[boot_with_blst_without_HDMI.log](https://github.com/thesofproject/linux/files/3651707/boot_with_blst_without_HDMI.log)

**Comment by plbossart** [comment]
> > Also the error reported is related to HDMI, please test without HDMI....
> 
> Tried to remove HDMI via Device Drivers  --->  <_> Sound card support  --->  <_>   Advanced Linux Sound  Architecture  --->ALSA for SoC audio support ---> unmark SOF support for HAD Links (HAD/HDMI), but it seems not work. Could you help to share how to test without HDMI ? Thanks.

It's really not complicated. remove all other machine drivers and make sure HDAC_HDMI is not in your config. Then also use a topology where all idisp parts are removed.

**Comment by plbossart** [comment]
Not reproducible on my side, please retest and close if relevant.

**Comment by YvonneYang2** [comment]
Test with latest kernel , FW and previous no-hdmi topology as attached. Issue reproduced rate gets lower, about 1/5

**Comment by YvonneYang2** [comment]
previous no-hdmi tplg as below 

[sof-icl-rt700.tplg.txt](https://github.com/thesofproject/linux/files/3720037/sof-icl-rt700.tplg.txt)

**Comment by YvonneYang2** [comment]
> remove all other machine drivers and make sure HDAC_HDMI is not in your config. Then also use a topology where all idisp parts are removed

Test it 50 times with latest kernel without HDAC_HDMI and topology idisp parts are removed, issue cannot reproduce on icl rt700 rvp. 

So it's a HDMI relevant issue. 
Replaced by https://github.com/thesofproject/linux/issues/1184
