### ISSUE TITLE
[BUG] no sound via HDMI/DP after module reloading

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1181]
**Description**
no sound output via HDMI/DP after module reloading, but unplug and then reconnect HDMI/DP cable, sound output normally.

**Reproduce**
1. playback via HDMI with `aplay -Dhw:0,3 -f dat -i -vvv -c2 ./longwave.wav`, sound output normally.
2. unload and then reload modules with script `sof_remove.sh` and `sof_insert.sh`.
3. rerun `aplay`, there is no sound output.
4. unplug HDMI/DP cable, and reconnect HDMI/DP cable, sound output normally.

**Rate**
100%

**Environment**
Kernel:  `topic/sof-dev fa20ceba`
SOF: `master ba32f4ad`
Topology: `sof-cml-rt5682-max98357a.tplg`
Platform: `CML Chrome`

[dmesg.log](https://github.com/thesofproject/linux/files/3582346/dmesg.log)

**Comment by dengyangchao** [comment]
issue also can reproduce with DP on CFL-S RVP (on board codec ALC700 in HD-A mode), and HDMI can not reproduce the issue

Environment
Kernel: topic/sof-dev fa20ceba
SOF: master ba32f4ad
Topology: sof-hda-generic-4ch.tplg
Platform: CFL-S RVP


[dmesg.log](https://github.com/thesofproject/linux/files/3583207/dmesg.log)
[logger1.log](https://github.com/thesofproject/linux/files/3583208/logger1.log)

**Comment by dengyangchao** [comment]
issue can not reproduce on CFL-S RVP in below recipe

Firmware: 8c61213c https://github.com/thesofproject/sof/commits/master
Kernel: fa20ceb https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by aiChaoSONG** [comment]
There are some messages about HDMI Pin，include :
> HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 5:0
> HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:1

these messages may be useful to resolve this issue.

[dmesg.log](https://github.com/thesofproject/linux/files/3614715/dmesg.log)

**Comment by dengyangchao** [comment]
correct the alsamixer config, CFL can not reproduce the issue

**Comment by aiChaoSONG** [comment]
issue not reproduced with right amixer config, this is not a kernel bug nor sof bug, let's close it.
