### ISSUE TITLE
[BUG][SDW]Cannot enter deep suspend with aplay or capture.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1206]
**Describe the bug**
Cannot enter deep suspend during aplay. When run "sudo rtcwake -m mem -s 10", music will stop and HDMI screen which is connected to device will turn dark. But dmesg shows no enter suspend info. 

**To Reproduce**
1.Boot up system 
2.Run ./rt1308_mixer.sh, ./rt711_mixer.sh and ./rt715_mixer.sh
3.echo deep> /sys/power/mem_sleep to switch to deep suspend mode
4.Aplay via aplay -Dhw:0,2 test.wav
5.Enter deep suspend via "sudo rtcwake -m mem -s 10"

**frequency**
100%

**Expected result**
System should enter deep suspend

**Actual result**
Music will stop and HDMI screen connected to device will turn dark. But dmesg shows no enter suspend info. 

**Environment**
Firmware: bccf4a8a https://github.com/bardliao/linux/tree/topic/for-3-in-1 
Kernel: 54e8eb5 https://github.com/thesofproject/sof/commits/sdw-001-drop-stable
tplg: sof-icl-rt711-rt1308-rt715-hdmi.tplg   rename sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**dmesg**
```
[   69.504308] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   69.504309] plb: soc_pcm_trigger component name snd-soc-dummy
[   69.504311] plb: soc_pcm_trigger cpu_dai name SDW1-speakers 2
[   69.504313] plb: soc_pcm_trigger codec_dai name sdw:1:25d:1308:0:0
[   69.504314] plb: soc_pcm_trigger component name int-sdw.1
[   69.504315] plb: soc_pcm_trigger component name sdw:1:25d:1308:0:0
[   69.504316] plb: soc_pcm_trigger component name 0000:00:1f.3
[   69.504317] plb: soc_pcm_trigger cpu_dai name SDW1 Pin2
[   69.505546] rt1308 sdw:1:25d:1308:0:0: rt1308_clock_config clock_config complete
[   69.927192] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   69.927230] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   70.427246] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   70.427288] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
```
[dmesg.log](https://github.com/thesofproject/linux/files/3604151/dmesg.log)

**Comment by YvonneYang2** [comment]
Tried to enter s2idle suspend with aplay or capture, HDMI screen connected to device cannot get dark and aplay is still playing.

**dmesg**
```
[  378.657991] plb: soc_pcm_trigger component name 0000:00:1f.3
[  378.657993] plb: soc_pcm_trigger cpu_dai name SDW0 Pin2
[  379.157638] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  379.157677] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  379.657076] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  379.657113] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  400.116888] PM: suspend entry (s2idle)
[  400.118133] Filesystems sync: 0.001 seconds
[  400.118648] Freezing user space processes ... (elapsed 0.002 seconds) done.
[  400.120978] OOM killer disabled.
[  400.120979] Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
[  400.121908] printk: Suspending console(s) (use no_console_suspend to debug)
[  400.122935] int-sdw int-sdw.3: Config update timedout
[  400.122937] int-sdw int-sdw.3: cannot disable interrupts on suspend
[  400.122946] PM: dpm_run_callback(): platform_pm_suspend+0x0/0x40 returns -11
[  400.122948] PM: Device int-sdw.3 failed to suspend: error -11
[  400.122950] PM: Some devices failed to suspend, or early wake event detected
[  400.124234] sdhci-pci 0000:00:14.5: SDHCI controller found [8086:34f8] (rev 30)
[  400.124718] OOM killer enabled.
[  400.124719] Restarting tasks ... done.
[  400.127857] video LNXVIDEO:00: Restoring backlight state
[  400.127860] PM: suspend exit
[  406.105406] plb: soc_pcm_trigger codec_dai name snd-soc-dummy-dai
[  406.105415] plb: soc_pcm_trigger component name 0000:00:1f.3
[  406.105425] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  406.106773] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[  406.106790] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  406.106995] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_S
```
[s2idle_dmesg.log](https://github.com/thesofproject/linux/files/3604236/s2idle_dmesg.log)
[s2idle_logger.log](https://github.com/thesofproject/linux/files/3604237/s2idle_logger.log)

**Comment by plbossart** [comment]
suspend is not supported for now with Soundwire.

**Comment by mengdonglin** [comment]
Depend on feature https://github.com/thesofproject/linux/issues/1238

**Comment by YvonneYang2** [comment]
Issue can reproduce on cml rvp rt700 with test recipe as below. Screen will get dark but dmesg shows no enter suspend info after run "sudo rtcwake -m mem -s 10"

**Test preconditions**:
make sure both options are commented out.
#options snd-sof-pci sof_debug=1
#options soundwire_intel sdw_md_flags=0x01010101

**Test recipe**:
Firmware: 9794dd7 https://github.com/thesofproject/sof/commits/master + +PR1851 (For HDMI tplg)
Kernel: 07bdd03 https://github.com/thesofproject/linux/tree/integration/soundwire-latest-pm
Topology: Same with FW branch   sof-cml-rt700.m4
Platform: CML RVP with codec ALC700 in SDW mode

**Comment by YvonneYang2** [comment]
Issue can still be reproduced as https://github.com/thesofproject/linux/issues/1206#issuecomment-530702908 said with test recipe as below.

Test recipe:
Firmware: 9794dd7 https://github.com/thesofproject/sof/commits/master + +PR1851 (For HDMI tplg)
Kernel: 07bdd03 https://github.com/thesofproject/linux/tree/integration/soundwire-latest-pm
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  path same as FW branch
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by plbossart** [comment]
bug confirmed, now added with SDW_DEV label for visibility

**Comment by YvonneYang2** [comment]
Issue can still be reproduced with test recipe as below. 

Test preconditions:
make sure both options are commented out.
#options snd-sof-pci sof_debug=1
#options soundwire_intel sdw_md_flags=0x01010101

Test recipe:
Firmware: e755494 https://github.com/thesofproject/sof/commits/master
Kernel: d2b55e0 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg: sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg path same as FW branch
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by plbossart** [comment]
Please recheck with the latest integration/soundwire-latest (19df577a9096437d50ad77fa5af34f90a8f858da), these errors are gone for me.

The behavior is not fully right just yet, so added new issue https://github.com/thesofproject/linux/issues/1311

**Comment by YvonneYang2** [comment]
Test it with latest latest integration/soundwire-latest (19df577) on icl 3-in-1 rvp and cml rt700 rvp, these errors are gone. New behavior will track in #1311.
