### ISSUE TITLE
[BUG] Paplay audio output volume is very low when playing captured fs24_le audio.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1224]
**Describe the bug**
Paplay has no audio output when playing captured fs24_le audio. Audio can be played via aplay successfully.

**To Reproduce**
1. arecord -Dhw:0,1 -r48000 -c2 -fs24_le 1.wav -vv -i
2. paplay 1.wav

**frequency**
100%

**Actual result**
Paplay has no audio output when playing captured fs24_le audio. Audio can be played via aplay successfully.

**Expected result**
audio should be played normally.

**Environment**
linux: https://github.com/thesofproject/linux/commits/integration/soundwire-alpha commit: a8f3408
sof: https://github.com/thesofproject/sof/commits/sdw-001-drop-stable commit: 0223d94
Topology: file: sof-cml-rt700.m4 same path as firmware
platform: CML SDW RVP

No error messages.
[paplay_soflogger.txt](https://github.com/thesofproject/sof/files/3558271/paplay_soflogger.txt)
[paplay_dmesg.txt](https://github.com/thesofproject/sof/files/3558272/paplay_dmesg.txt)

**Comment by plbossart** [comment]
@ClarexZhou please retest with the firmware master branch. It's not helpful if you keep testing with sdw-001-drop-stable...

**Comment by plbossart** [comment]
and test on the kernel side with integration/soundwire-latest

**Comment by ClarexZhou** [comment]
Error seen with firmware master and kernel integration/soundwire-latest branch.

**Environment**
Firmware: 460c41a Master
Kernel: 4ac5440 on integration/soundwire-latest
Topology: file: same with firmware branch, sof-cml-rt700.m4
platform: CML rt700 SDW RVP

**Comment by plbossart** [comment]
@RanderWang can you look into this? I don't have access to a CML/SDW board.

**Comment by ClarexZhou** [comment]
@bardliao  to check this paplay fs24_le issue first.

**Comment by bardliao** [comment]
@plbossart This can be seen on ICL, too. But there is no issue if we play with aplay.

**Comment by bardliao** [comment]
@ClarexZhou Can you test it with I2S/HDA interfaces?

**Comment by dengyangchao** [comment]
issue also seen on ICL HDA and GLK i2s chrome

**test recipe**
Firmware: 9794dd78  master
Kernel: e03f8829   topic/sof-dev
Topology: file: sof-hda-generic-4ch.tplg/ sof-glk-da7219.tplg

**Comment by ClarexZhou** [comment]
Arecorded fs24_le audio can be played normally via aplay.   Not sof issue.
Paplay also can play audio which captured via parecord normally. 
Current issue scenario isn't common case. Close.
