### ISSUE TITLE
[BUG][SDW]System will hang when set ./rt1308 amixer if not add options snd_sof_pci sof_debug=1 in alsa-base.conf 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1226]
**Describe the bug**
System will hang when set ./rt1308 amixer if not add options snd_sof_pci sof_debug=1 in alsa-base.conf

**To Reproduce**
1.Make sure options snd_sof_pci sof_debug=1 not in alsa-base.conf
2.Reboot system
3.run ./rt1308_mixer.sh

**frequency**
100%

**Expected result**
./rt1308_mixer.sh run successfully

**Actual result**
system will hang when run ./rt1308_mixer.sh

**Environment**
Firmware: 460c41aa https://github.com/thesofproject/sof/commits/master
Kernel: 4ac5440 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  https://github.com/bardliao/sof/blob/fix/soundwire-tplg/tools/topology/
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/3629697/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3629699/logger.log)
[rt1308_mixer.txt](https://github.com/thesofproject/linux/files/3629738/rt1308_mixer.txt)

**Comment by plbossart** [comment]
This is not really a bug. You are allowing the PCI device to suspend, which takes the SoundWire IP off, and then sending a command over SoundWire without waking up the PCI device or powering-up the IP.
This will have to be re-tested when suspend-resume are implemented.

**Comment by mengdonglin** [comment]
Depend on feature https://github.com/thesofproject/linux/issues/1238

**Comment by bardliao** [comment]
@YvonneYang2 Could you retest it with https://github.com/bardliao/linux/tree/integration/soundwire-latest ?

**Comment by YvonneYang2** [comment]
Retest it with test recipe as below, issue cannot reproduced, but set it up will cost about 3-5s. 

Test recipe:
 Firmware: 3ce82a1 https://github.com/thesofproject/sof/commits/master + +PR1851 (For HDMI tplg)
Kernel: 03b41fb  https://github.com/bardliao/linux/tree/integration/soundwire-latest 
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  path same as FW branch
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/3657002/dmesg.log)

**Comment by bardliao** [comment]
> Retest it with test recipe as below, issue cannot reproduced, but set it up will cost about 3-5s.
> 

The delay is expected. There is a 2s delay in resume for each devices.

**Comment by plbossart** [comment]
well, to be clearer, the delay is fixed for now to 2s until we figure out how to use an async mechanism to check that all devices are operational before exiting resume

**Comment by plbossart** [comment]
replaced by https://github.com/thesofproject/linux/issues/1303
