### ISSUE TITLE
[BUG][SDW]Volume is always 0 when Arecord by ALC715/MIC (device 0,4)

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1228]
**Describe the bug**
Volume is always 0 when Arecord 0,4 

**To Reproduce**
1.Make sure "options snd_sof_pci sof_debug=1" in /etc/modprobe.d/alsa-base.conf and system use legancy interrupt mode
2.Reboot system
3. Run ./rt1308_mixer.sh, ./rt711_mixer.sh, ./rt715_mixer.sh scripts.
4.Run arecord -Dhw:0,4 -f s24_le -r 48000 -c 2  test.wav -vv -i

**frequency**
100%

**Expected result**
Arecord should work 

**Actual result**
Arecord 0,4 volume is always 0 , and aplay test.wav cannot hear anything.

**Environment**
Firmware: 460c41aa https://github.com/thesofproject/sof/commits/master
Kernel: 4ac5440 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  https://github.com/bardliao/sof/blob/fix/soundwire-tplg/tools/topology/
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**dmesg**
```
[    4.148692] intel-sdw sdw-master-0: Updating Slave 1 status
[    4.148693] intel-sdw sdw-master-0: sdw_handle_slave_status: Updating Slave 1 status done
[    4.148694] intel-sdw sdw-master-0: sdw_handle_slave_status: end
[    4.408703] rt711 sdw:0:25d:711:0:1: in rt711_jack_detect_handler, jack_type=0x3
[    4.408704] rt711 sdw:0:25d:711:0:1: in rt711_jack_detect_handler, btn_type=0x0
[    4.471048] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[    4.471075] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[    5.152999] rfkill: input handler disabled
[    5.429532] IPv6: ADDRCONF(NETDEV_CHANGE): enx000ec6c686f2: link becomes ready
[    5.432134] asix 3-9.1:1.0 enx000ec6c686f2: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   42.800126] sof-audio-pci 0000:00:1f.3: pcm: open stream 4 dir 1
[   42.800127] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[   42.800128] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[   42.800128] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[   42.802110] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   42.802328] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[   42.802337] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 4 dir 1
[   42.802342] sof-audio-pci 0000:00:1f.3: generating page table for 00000000e9acca54 size 0xffc0 pages 16
[   42.802362] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[   42.802390] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[   42.802417] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[   42.802418] sof-audio-pci 0000:00:1f.3: periods:4
[   42.802452] sof-audio-pci 0000:00:1f.3: stream_tag 2
[   42.802466] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   42.802764] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   42.802768] sof-audio-pci 0000:00:1f.3: pcm: stream dir 1, posn mailbox offset is 790528
[   42.872354] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 1 cmd 1
[   42.872439] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x2024001e successful
[   42.872447] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   42.872811] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   43.471593] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   43.471638] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   47.011141] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 1 cmd 0
[   47.011431] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20240000 successful
[   47.011440] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   47.011827] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   47.011832] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   47.012057] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   47.014358] sof-audio-pci 0000:00:1f.3: pcm: free stream 4 dir 1
[   47.014610] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   47.014830] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[   47.014906] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 1
[   47.971428] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   47.971472] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
```
[logger.log](https://github.com/thesofproject/linux/files/3630551/logger.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3630552/dmesg.log)
[rt715_mixer.txt](https://github.com/thesofproject/linux/files/3630593/rt715_mixer.txt)
[rt1308_mixer.txt](https://github.com/thesofproject/linux/files/3630594/rt1308_mixer.txt)
[rt711_mixer.txt](https://github.com/thesofproject/linux/files/3630595/rt711_mixer.txt)

**Comment by plbossart** [comment]
@bardliao can you look into this, looks like rt715 is not functional or not well configured?

**Comment by bardliao** [comment]
@plbossart Yes, I did a quick check yesterday and found that somehow DAPM widget connection status is not changed when I configure the ADC Mux controls. Besides, when I set the ADC Mux back and forth, the dapmDAPM widget connection status can be connected as we expected. But we still can't record anything even when DAPM power status is correct. I can't reproduce the issue on my side and I have reported it to Realtek. @jack-cy-yu

**Comment by jack-cy-yu** [comment]
@plbossart @bardliao I've done some modifications on ALC715's driver regarding to ADC Mux issue, could you please review the latest PR in "realtek-sdw-codecs" branch and I also can't reproduce recording issue on my side, but the original MUX syntax might be the potential bug for this issue.

**Comment by bardliao** [comment]
@ClarexZhou @YvonneYang2 Can you retest it with https://github.com/bardliao/linux/tree/for-rt715? Thanks.

**Comment by jack-cy-yu** [comment]
@bardliao Please note that rt715_mixer.sh should also be modified since mux setting are changed in latest driver. Please check the script to see if below contents are included
 "amixer cset name='ADC 24 Mux' 'DMIC1'
amixer cset name='ADC 25 Mux' 'DMIC2'"

**Comment by YvonneYang2** [comment]
Test it with  https://github.com/bardliao/linux/tree/for-rt715, issue cannot reproduce on icl rvp 3-in-1.

Test recipe:
Firmware: 9794dd7 https://github.com/thesofproject/sof/commits/master + +PR1851 (For HDMI tplg)
Kernel: 35c4315https://github.com/bardliao/linux/tree/for-rt715
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  same branch as FW
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by plbossart** [comment]
@YvonneYang2 the code is now in integration/soundwire-latest, if this is solved please close.

**Comment by YvonneYang2** [comment]
Issue cannot reproduce with test recipe as below on ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode. So close it.

Test recipe:
Firmware: 3ce82a1 https://github.com/thesofproject/sof/commits/master + +PR1851 (For HDMI tplg)
Kernel: 49d28c3 https://github.com/thesofproject/linux/commits/integration/soundwire-latest
tplg: sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg same branch as FW
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode
