### ISSUE TITLE
[Feature] Add a SOF module parameter to disable runtime PM by default

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#1237]
Define a parameter like ''disable_runtime_pm'. So we can set it as a kernel boot parameter to disable SOF runtime power management by default.

It will be useful to validate new features (e.g SoundWire) but its PM is still not ready, or check if a issue can be reproduced when runtime PM is disabled.

**Comment by ranj063** [comment]
@mengdonglin this is already there. sof_debug=0x1 disables PM

**Comment by mengdonglin** [comment]
@ranj063 Great. Thank you!
