### ISSUE TITLE
Firmware boot failure after unloading and reloading driver

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#124]
Summary:
run the "soft/kmod_scripts/sof_bootone.sh" script, that means do the module reload one time, but boot failed on APL, BYT and CNL.

Environment：
kernel: sof-dev 64cf3e3

Log on APL:
[boot_fail.log](https://github.com/thesofproject/linux/files/2370484/boot_fail.log)

**Comment by mengdonglin** [comment]
@lyakh  could you help to check this issue?

**Comment by lyakh** [comment]
@ZhendanYang could you please point out where in the attached log the failure is seeing? Also, on which specific platforms / test boards and with which topology configurations has it been possible to reproduce this?

**Comment by lgirdwood** [comment]
@lyakh Looks like an earlier PM failure is breaking things.

```
[  264.573413] sof-audio sof-audio: tplg: complete pipeline PIPELINE.1.SSP0.OUT id 5
[  264.573422] sof-audio sof-audio: ipc tx: 0x30130000
[  264.573471] sof-audio sof-audio: ipc tx succeeded: 0x30130000
[  264.573494] sof-audio sof-audio: error: failed to enter PM idle -11
[  264.573571] sof-nocodec sof-nocodec: snd-soc-dummy-dai <-> SSP0 Pin mapping ok
[  264.573588] sof-nocodec sof-nocodec: snd-soc-dummy-dai <-> SSP1 Pin mapping ok
```

**Comment by mengdonglin** [comment]
@lyakh I think the firmware cannot support PM on byt. PM should only be enabled on APL and GLK. Could you try to disable PM on BYT?

@ranj063 Is runtime PM on BYT disabled by default? Or need manually disabling?

@ZhendanYang Which firmware branch are you testing with? Could you share the latest result for both sof master and 1.2-stable branch?

**Comment by lgirdwood** [comment]
@mengdonglin yes - S0ix should be disabled on BYT Minnowboard, there should be a runtime flag set in platform data whether to enable or disable S0ix. @lyakh checking DMI name in sof-acpi-dev.c and then setting a flag to disable runtime_pm should be enough here.

**Comment by ZhendanYang** [comment]
This issue still exists.
Test env:
kernel: sof-dev 160b45f36c3d5b294449867df2e62c02c9a784dd
sof tool: 57b5212
sof stable-1.2 : 7dd4b1d
[boot_fail.log](https://github.com/thesofproject/linux/files/2418691/boot_fail.log)

**Comment by mengdonglin** [comment]
@stevyan @markyang Could you help to check if this issue is gone with fixing of #144 by #311?

**Comment by markyang** [comment]
**Summary:**
This issue cannot be reproduced on BYT with ALC5651 using the build on Dec 7.
There is no Kernel Panic, both arecord and aplay worked fine.

**Test steps:**
kmod_scripts/sof_bootone.sh
arecord -Dhw:0,0 -c2 -fS16_LE -vv -i ~/mytest.wav #OK
aplay -Dhw:0,0 -c2 -fS16_LE -vv -i ~/mytest.wav #OK

**Test env:**
sof master: b5d6c71b #Dec 7
kernel sof-dev: a71221d #Dec 7
tplg: test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-codec.tplg
