### ISSUE TITLE
[BUG] ipc timeout and card instantiation failure in reboot stress test

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1245]
**Describe the bug**
When do reboot stress test on CML Chrome, there will be ipc timeout and card instantiation failure. Sometimes only ipc timeout occurs, sometimes both issues occur. if card instantiation failed occurs, topology will be failed to load.

**To Reproduce**
do system reboot

**Reproduction Rate**
2/100

**Expected behavior**
no ipc timeout, card instantiated and tplg load succesfully

**Environment**
Kernel: topic/sof-dev f05b2682
SOF: master 0b47129
Topology: sof-cml-rt5682-max98357a.tplg
Platform: CML Chrome
OS: Ubuntu1804

***only ipc timeout***
```
[    8.974952] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50020000: GLB_COMP_MSG: GET_VALUE
[    9.478396] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x50020000 size 108
[    9.478415] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[    9.478750] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[    9.478767] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[    9.478771] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[    9.478786] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[    9.478790] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[    9.478795] sof-audio-pci 0000:00:1f.3: error: set/get ctrl ipc comp 17
[    9.478799] sof-audio-pci 0000:00:1f.3: error: kcontrol value get for widget: 17
[    9.478814] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50020000: GLB_COMP_MSG: GET_VALUE
[    9.982506] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x50020000 size 108
[    9.982524] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[    9.982857] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[    9.982874] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[    9.982878] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[    9.982893] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[    9.982896] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[    9.982902] sof-audio-pci 0000:00:1f.3: error: set/get ctrl ipc comp 7
[    9.982906] sof-audio-pci 0000:00:1f.3: error: kcontrol value get for widget: 7
[    9.982921] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50020000: GLB_COMP_MSG: GET_VALUE
[   10.486519] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x50020000 size 108
[   10.486539] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[   10.486872] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[   10.486895] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[   10.486899] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[   10.486917] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[   10.486921] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[   10.486927] sof-audio-pci 0000:00:1f.3: error: set/get ctrl ipc comp 1
[   10.486931] sof-audio-pci 0000:00:1f.3: error: kcontrol value get for widget: 1
```
***ipc timeout and card instantiation failure***
```
[    2.903093] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x80010000 size 144
[    2.903105] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[    2.903274] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[    2.903286] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[    2.903287] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[    2.903296] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[    2.903298] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[    2.903299] sof-audio-pci 0000:00:1f.3: error: failed to set DAI config for DMIC1
[    2.903301] sof-audio-pci 0000:00:1f.3: ASoC: physical link loading failed
[    2.903338] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[    2.903346] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[    2.903349] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903361] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903368] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903372] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903382] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903390] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903393] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903401] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903408] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903412] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903420] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903427] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903431] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903439] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903446] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903449] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903457] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903465] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903468] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903476] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903483] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903487] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903495] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903502] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.903505] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.903507] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -110
[    2.903512] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[    2.903513] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[    2.903533] sof_rt5682 sof_rt5682: ASoC: failed to instantiate card -22
[    2.903554] sof_rt5682: probe of sof_rt5682 failed with error -22
```

[dmesg_failed_89_ipc_tmeout.log](https://github.com/thesofproject/linux/files/3641465/dmesg_failed_89_ipc_tmeout.log)

[dmesg_failed_100_both.log](https://github.com/thesofproject/linux/files/3641466/dmesg_failed_100_both.log)

**Comment by aiChaoSONG** [comment]
issue and test recipe originally from  #1184 , after disable i915 power well with `GRUB_CMDLINE_LINUX_DEFAULT="i915.disable_power_well=0 ` in /etc/defaults/grub (remember to `update-grub`), issue can reporduce too

**Comment by kv2019i** [comment]
@aiChaoSONG Do we have FW traces for this case? This could be a case of invalid DMIC config getting applied:

[    2.885067] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x80010000 size 144
[    2.885168] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[    2.885507] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[    2.885616] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[    2.885722] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[    2.885807] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[    2.885896] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[    2.885964] sof-audio-pci 0000:00:1f.3: error: failed to set DAI config for DMIC1
[    2.886082] sof-audio-pci 0000:00:1f.3: ASoC: physical link loading failed

Log bit "host status 0x00000000" tells that DSP has not responded with a IPC reply, so initial analysis is that FW got stuck while programming the DMIC hw.

**Comment by kv2019i** [comment]
In the other log, similar problem but for another IPC. No response to pipeline-complete and there does not seem to be a IPC pending from DSP to host:

[    2.423934] sof-audio-pci 0000:00:1f.3: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    2.423986] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[    2.424015] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[    2.861737] asix 1-3.1:1.0 eth0: register 'asix' at usb-0000:00:14.0-3.1, ASIX AX88772 USB 2.0 Ethernet, 00:0e:c6:b7:2c:17
[    2.861775] usbcore: registered new interface driver asix
[    2.868937] asix 1-3.1:1.0 enx000ec6b72c17: renamed from eth0
[    2.923980] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[    2.924003] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[    2.927275] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x30130000 size 12
[    2.927304] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[    2.927628] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[    2.927666] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[    2.927701] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[    2.927728] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[    2.927751] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers

**Comment by aiChaoSONG** [comment]
run reboot stress test several times, not reproduce

**Comment by aiChaoSONG** [comment]
let's close this issue, because it is not seen for several days
