### ISSUE TITLE
sof related alsamixer sliders don't reflect amixer settings

### ISSUE THREAD

**Issue by juimonen** [thesofproject/linux#1257]
if I open "alsamixer -c 0" then issue "amixer sset 'PGA1.0 1 Master' 50%", I don't see corresponding slider mirroring the change. HDA volume control sliders will react to amixer commands. I mean volume is actually changed with sof sliders, but it is quite misleading in some testing cases than you don't "see" the change for example.

**Comment by plbossart** [comment]
is this an SOF issue? what happens if you do the same with e.g. a codec mixer setting?

**Comment by juimonen** [comment]
So messages are going through to dsp, volume is changing, the change is just not reflected in alsamixer graphical sliders. With HDA related controls the sliders move. So I don't know are we missing some callback to user space etc?

**Comment by juimonen** [comment]
wait, some new info. If I set sof pga mixer with amixer _and_ close alsamixer and reopen, I see the change reflected in the slider. If I don't close and reopen slider doesn't move (?).

**Comment by ranj063** [comment]
@juimonen I was going to comment that I see the change happening at my end. But yes I only open alsamixer after I issue the amixer command. So it may not be a SOF issue. possibly an alsamixer utility issue.

**Comment by juimonen** [comment]
I don't think this is like showstopper, it is just really annoying to see what's happening with alsa controls when I'm testing UCM use cases. Some changes are reflected some aren't (if I don't close and opne alsamixer in between every command)

**Comment by dragosht** [comment]
If nobody is currently working on this issue I'd like to investigate it further. I see I can still reproduce the problem on my board with the latest master using a very basic topology.

**Comment by juimonen** [comment]
@dragosht yes please!
