### ISSUE TITLE
[FEATURE] register setting log: dynamically show register setting in kernel log

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/linux#1268]
For driver debugging,  we need to know which registers are set by driver before special issue reproduced, e.g. HW hang. It can be implemented as IPC VERBOSE log. It was suggested by @lgirdwood

**Comment by plbossart** [comment]
this is 2 years old and I am not sure I get the idea. @lgirdwood @RanderWang should we close? if not please clarify what the ask is.

**Comment by RanderWang** [comment]
Not usable
