### ISSUE TITLE
[BUG] HDMI/DP monitor not detected on CML Chrome

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1292]
**Describe the bug**
No video or audio output to monitor after HDMI/DP cable connected, check display settings, the monitor is not detected.

**Reproduction Rate**
100%

[dmesg.log](https://github.com/thesofproject/linux/files/3705563/dmesg.log)

**Comment by dengyangchao** [comment]
[DPMST] use DP-HUB connect 2 DP monitor, device can't detected DP monitor, and DP monitor lost display
issue observed on GLK-Chrome, CFL-S RVP, CML HDA.
1. commit:  9af032a3  sof-dev  detected DPMST, monitor display normal
2. commit:  c710364f  sof-dev  can't detect DPMST, monitor lost display

**Comment by mengdonglin** [comment]
@aiChaoSONG @dengyangchao Is this issue a regression? If yes, please help to find the regression point.

**Comment by dengyangchao** [comment]
> @aiChaoSONG @dengyangchao Is this issue a regression? If yes, please help to find the regression point.

as i see, the issue caused by c710364, how do you think? @aiChaoSONG

**Comment by aiChaoSONG** [comment]
> > @aiChaoSONG @dengyangchao Is this issue a regression? If yes, please help to find the regression point.
> 
> as i see, the issue caused by [c710364](https://github.com/thesofproject/linux/commit/c710364f78afdef8c2ed07556d0743c5a30ed429), how do you think? @aiChaoSONG

on my side, commit c710364f doesn't work, commit 9af032a3 works. but I think the code in c710364f has nothing to do with display. btw, c710364f is 5.3, but 9af032a3 is 5.3rc2, there must be a lot of code change in between, that's why I am confused.

**Comment by aiChaoSONG** [comment]
closed for cannot reproduce
