### ISSUE TITLE
snd-sof-pci module unload gets stuck due to hda_jackpoll_work

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1293]
With latest sof-dev tip, a stress test to unload&load the SOF modules, test leads to modprobe getting stuck on "sudo modprobe -r snd_sof_pci".
 
Linux: 0f665a4f8bf1 (ASoC: SOF: dai-imx: remove spurious newline at EOF)
Reproduction rate: 30%
Impact: system has to be rebooted to recover

Other notes:
- does not occur if runtime-pm is disabled
-  initial debug show this to be caused by a race in trying to cancel "codec->jackpoll_work"

Last lines in dmesg:
```
[  692.958745] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  692.958976] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  692.958987] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  692.958991] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  692.959014] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  692.959026] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  692.959030] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  692.959057] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  692.959068] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  692.959073] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
```

Test sequence shell script
```
set -x
while true ; do 
  sudo modprobe snd_sof_pci
  sleep 3
  aplay -l
  sudo modprobe -r snd_sof_pci
  sudo modprobe -r snd_soc_skl_hda_dsp
  sudo modprobe -r snd_hda_codec_hdmi
  sudo modprobe -r snd_hda_codec_realtek
  sudo modprobe -r snd_hda_codec
done
```

**Comment by kv2019i** [comment]
FYI @keyonjie and @ranj063  You might hit this with MFD and/or S0ix work.

Did some debug today, but no clue on on rootcause.  Notably when this happens,
sofi_pci_remove() -> snd_sof_device_remove() -> platform_device_unregister+0x17/0x30

... takes a very long time, but it does complete, so doesn't explain why unload eventually fails.

**Comment by dengyangchao** [comment]
Similar issue also seen when removing snd_sof_pci with PA off,  takes a very long time, but still  it does complete.

Firmware: c8bc4b2c https://github.com/thesofproject/sof/commits/master
Kernel: 0f665a4f https://github.com/thesofproject/linux/commits/topic/sof-dev
platform: CML HDA-Notebook, ICL-HDA RVP, CFL-S HDA RVP

**Comment by kv2019i** [comment]
Ack, most probably the same issue. This seems to be related to the HDA codec suspend/resume actions at device removal. If I modify the bug script with following:

<load module>
echo "on" >/sys/bus/pci/devices/0000\:00\:1f.3/ehdaudio0D0/power/control
<unload module>

... the problem goes away. I.e. by disabling codec's runtime PM, the card removal goes through without delays.

**Comment by plbossart** [comment]
We had a similar issue with SoundWire yesterday, with a race between remove and resume. Our fix was to disable pm_runtime in the .remove, and do so for all the device children

**Comment by plbossart** [comment]
On 10/9/19 6:18 AM, Kai Vehmanen wrote:
> Ack, most probably the same issue. This seems to be related to the HDA 
> codec suspend/resume actions at device removal. If I modify the bug 
> script with following:
> 
> echo "on" >/sys/bus/pci/devices/0000\:00\:1f.3/ehdaudio0D0/power/control
> 
> ... the problem goes away. I.e. by disabling codec's runtime PM, the 
> card removal goes through without delays.

I just found another issue. When we compile the kernel with HDA_LINK 
support, but don't use the HDMI stuff in the topology/machine driver, 
then the PCI device does not suspend.

When I remove HDA_LINK then suspend works fine.

**Comment by kv2019i** [comment]
@plbossart wrote:
> We had a similar issue with SoundWire yesterday, with a race between remove and resume. 
> Our fix was to disable pm_runtime in the .remove, and do so for all the device children

Ack, that works for HDA as well, tested on two machiens, now waiting for CI results:
https://github.com/thesofproject/linux/pull/1301

**Comment by kv2019i** [comment]
@plbossart wrote:
> I just found another issue. When we compile the kernel with HDA_LINK support, but don't use the HDMI stuff in the topology/machine driver, then the PCI device does not suspend. When I remove HDA_LINK then suspend works fine.

Filed as https://github.com/thesofproject/linux/issues/1302

**Comment by kv2019i** [comment]
Candidate fix -> https://github.com/thesofproject/linux/pull/1301

**Comment by dengyangchao** [comment]
run over 200 times, issue can not reproduce on CFL-S HDA RVP, after applied #1301

**Comment by stripes416** [comment]
@kv2019i THANK YOU. Im working on kmod load / unload tests for CI and hitting this exact issue! Teaches me not to check github for issues im facing!

**Comment by dengyangchao** [comment]
issue can't reproduce on CFL-S RVP HDA with below recipe

Firmware: 78b022b https://github.com/thesofproject/sof/commits/master
Kernel: 34562a4 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware
