### ISSUE TITLE
PCI device does not suspend with HDA_LINK=1 but no HDMI in topology

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1302]
Forked as separate issue from:
https://github.com/thesofproject/linux/issues/1293

From @plbossart :
I just found another issue. When we compile the kernel with HDA_LINK
support, but don't use the HDMI stuff in the topology/machine driver,
then the PCI device does not suspend.

When I remove HDA_LINK then suspend works fine.

**Comment by plbossart** [comment]
@kv2019i is this issue still current, now that we changed to the common HDMI module?

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i is this issue still current, now that we changed to the common HDMI module?

Let me check, assigning to myself.

**Comment by plbossart** [comment]
@kv2019i this is probably obsolete, no?

**Comment by kv2019i** [comment]
Ack @plbossart , closing.
