### ISSUE TITLE
[SDW] alsamixer reports Device Busy when PCI device is 'suspended'

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1303]
After probe, when the PCI device, SoundWire master and SoundWire slaves are suspended (pm_runtime), accesses to some kcontrols generates a -EBUSY reply.

This is fixed for RT711 and RT1308, but we still have problems with RT700 and RT715, need patches from Realtek.

**Comment by YvonneYang2** [comment]
Issue #1226 #1205 cannot reproduced on icl 3-in-1 when set ./rt1308 amixer settings. 
But when set rt715 amixer setting, dmesg will show rt715 sdw read failed. amixer contents shows "read error:  Device and resource busy".   Activate RT715 codec(arecord 0,4), then set it again can recover the issue.

Test preconditions:
make sure both options are commented out.
#options snd-sof-pci sof_debug=1
#options soundwire_intel sdw_md_flags=0x01010101

Firmware: e755494 https://github.com/thesofproject/sof/commits/master 
Kernel: d2b55e0 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  path same as FW branch
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by YvonneYang2** [comment]
Open alsamixer will show cannot load mixer control on icl rt700 rvp.  Run arecord 0,1 capture, then open alsamixer will recover the issue.

Firmware: e755494 https://github.com/thesofproject/sof/commits/master
Kernel: d2b55e0 https://github.com/thesofproject/linux/tree/integration/soundwire-latest

**Comment by plbossart** [comment]
it's expected that mixer access to RT700 and RT715 will fail, Realtek will provide patches next week.

**Comment by YvonneYang2** [comment]
Issue not reproduced with integration/soundwire-latest(commit :d88ee7d )+ PR1327, and master (commit:81cc31b) on icl 3-in-1 rvp and icl rt700 rvp.

**Comment by YvonneYang2** [comment]
Close the bug since not reproduce anymore.
