### ISSUE TITLE
[SDW] race conditions between system and runtime PM

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1309]
If we use system suspend/resume without any pm_runtime, things are fine.
If we use pm_runtime, things are fine.

If we use system suspend-resume and let pm_runtime kick-in, then we have conflicts

See attached test files to reproduce the issue
[pm_test.tar.gz](https://github.com/thesofproject/linux/files/3719605/pm_test.tar.gz)

aplay_system.sh works fine
aplay_runtime.sh works fine
aplay_runtime_system.sh does not work at all.

see log attached and look for "<<" markers
[dmesg_aplay_runtime_system.log](https://github.com/thesofproject/linux/files/3719609/dmesg_aplay_runtime_system.log)

WIP branch is at https://github.com/plbossart/sound/tree/fix/soundwire-pm-debug

**Comment by plbossart** [comment]
This should be fixed before even looking at #1206 and #1196

**Comment by plbossart** [comment]
ok, so it turns out to be a case of RTFM.

With the patch below, we keep track of the pm_runtime status and if we do a system suspend with a pm_runtime 'suspended' device, we mark it as active to set its status on system resume, thus avoiding a race with the pm_runtime resume.

<details> 
<summary> diff to solve the issue </summary>

```diff
diff --git a/drivers/soundwire/intel.c b/drivers/soundwire/intel.c
index 0857672f5ea1..ca20f94737db 100644
--- a/drivers/soundwire/intel.c
+++ b/drivers/soundwire/intel.c
@@ -1307,6 +1307,7 @@ static int intel_master_remove(struct sdw_master_device *md)
 
 static int intel_suspend(struct device *dev)
 {
+	struct sdw_master_device *md = to_sdw_master_device(dev);
 	struct sdw_cdns *cdns = dev_get_drvdata(dev);
 	struct sdw_intel *sdw = cdns_to_intel(cdns);
 	int ret;
@@ -1317,6 +1318,20 @@ static int intel_suspend(struct device *dev)
 		return 0;
 	}
 
+	if (pm_runtime_status_suspended(dev)) {
+		dev_dbg(dev,
+			"%s: pm_runtime status: suspended\n",
+			__func__);
+
+		/*
+		 * keep track of the state for the system resume, where
+		 * we will need to reset the pm_runtime status to active
+		 */
+		md->pm_runtime_suspended = true;
+
+		return 0;
+	}
+
 	ret = sdw_cdns_enable_interrupt(cdns, false);
 	if (ret < 0) {
 		dev_err(dev, "cannot disable interrupts on suspend\n");
@@ -1365,6 +1380,7 @@ static int intel_suspend_runtime(struct device *dev)
 
 static int intel_resume(struct device *dev)
 {
+	struct sdw_master_device *md = to_sdw_master_device(dev);
 	struct sdw_cdns *cdns = dev_get_drvdata(dev);
 	struct sdw_intel *sdw = cdns_to_intel(cdns);
 	int ret;
@@ -1375,6 +1391,20 @@ static int intel_resume(struct device *dev)
 		return 0;
 	}
 
+	if (md->pm_runtime_suspended) {
+		dev_dbg(dev,
+			"%s: pm_runtime status was suspended, forcing active\n",
+			__func__);
+
+		/* follow required sequence from runtime_pm.rst */
+		pm_runtime_disable(dev);
+		pm_runtime_set_active(dev);
+		pm_runtime_mark_last_busy(dev);
+		pm_runtime_enable(dev);
+
+		md->pm_runtime_suspended = false;
+	}
+
 	ret = intel_init(sdw);
 	if (ret) {
 		dev_err(dev, "%s failed: %d", __func__, ret);
diff --git a/include/linux/soundwire/sdw.h b/include/linux/soundwire/sdw.h
index 4e8ade022273..5b29d3bdae44 100644
--- a/include/linux/soundwire/sdw.h
+++ b/include/linux/soundwire/sdw.h
@@ -574,6 +574,7 @@ struct sdw_master_device {
 	struct device dev;
 	int link_id;
 	struct sdw_md_driver *driver;
+	bool pm_runtime_suspended;
 	void *pdata; /* core does not touch */
 };
```
</details>

**Comment by plbossart** [comment]
@bardliao @ranj063 does this look ok to you?

@ClarexZhou @YvonneYang2 please add those tests to your regression suite, it's important to detect such problems, thanks.

**Comment by bardliao** [comment]
@plbossart Yes, it can solve the race conditions between system and runtime PM. I don't see any error/failed when I did suspend in aplay test. But somehow I still got ``aplay: pcm_write:2011: write error: Input/output error`` after resume.

Forgot to mention that https://github.com/thesofproject/linux/pull/1310 is needed

**Comment by ranj063** [comment]
@plbossart I have a question about the sequence with sdw device. With the SOF PCI device, the device is runtime resumed before it is suspended during system suspend. This is likely what avoids the race that you're seeing with sdw. Does this not happen with the sdw device?

**Comment by bardliao** [comment]
> @plbossart I have a question about the sequence with sdw device. With the SOF PCI device, the device is runtime resumed before it is suspended during system suspend. This is likely what avoids the race that you're seeing with sdw. Does this not happen with the sdw device?

@ranj063 I didn't see this happened with sdw device.

**Comment by bardliao** [comment]
@plbossart Questions to your patch 
1. Can we just use pm_runtime_status_suspended(dev) to check if the device is runtime suspended?
2. Currently our runtime and system suspend/resume functions are almost the same. Do we need to do a resume/suspend cycle when the device is already runtime suspended?

**Comment by ranj063** [comment]
> @bardliao @ranj063 does this look ok to you?

@plbossart the sequence looks good but for one change. The pm_runtime_mark_last_busy() should go at the end of the if (md->pm_rutime_suspended){} block, I think

**Comment by plbossart** [comment]
> @plbossart I have a question about the sequence with sdw device. With the SOF PCI device, the device is runtime resumed before it is suspended during system suspend. This is likely what avoids the race that you're seeing with sdw. Does this not happen with the sdw device?

no, the runtime_resume happens *after* the system resume for the SoundWire master.

**Comment by plbossart** [comment]
> > @bardliao @ranj063 does this look ok to you?
> 
> @plbossart the sequence looks good but for one change. The pm_runtime_mark_last_busy() should go at the end of the if (md->pm_rutime_suspended){} block, I think

no, in all the cases where we do pm_runtime_enable(), we set pm_runtime_mark_last_busy() to avoid an immediate suspend.

**Comment by ranj063** [comment]
> no, in all the cases where we do pm_runtime_enable(), we set pm_runtime_mark_last_busy() to avoid an immediate suspend.

@plbossart but its after pm_runtime_enable(), isnt it?

**Comment by ranj063** [comment]
> no, the runtime_resume happens _after_ the system resume for the SoundWire master.

@plbossart im wondering if there's a way we could force the same behavior as the SOF device for the SDW device too? ie to runtime resume before system suspend. or Does it not make sense?

**Comment by plbossart** [comment]
> > no, in all the cases where we do pm_runtime_enable(), we set pm_runtime_mark_last_busy() to avoid an immediate suspend.
> 
> @plbossart but its after pm_runtime_enable(), isnt it?

when we invoke pm_runtime_enable(), the activity counters are set way in the past, so refreshing the values before doing a pm_runtime_enable() is not silly. i've seen in the case of the soundwire codecs that this was mandatory. I haven't tested here if the order matters but I don't see why we would take the risk of adding a race condition if the sequence works as is...

**Comment by plbossart** [comment]
> > no, the runtime_resume happens _after_ the system resume for the SoundWire master.
> 
> @plbossart im wondering if there's a way we could force the same behavior as the SOF device for the SDW device too? ie to runtime resume before system suspend. or Does it not make sense?

no, we don't want to do this to remain future-proof. In the future (like next week), pm_runtime suspend will use the clock-stop mode, and will not require a full init/re-enumeration on pm_runtime resume. The full init/re-enumeration will still needed for system resume

There is an open whether we need to do a pm_runtime resume *before* doing a system suspend. It would make sense for state consistency, however since we take out power during system suspend I don't think we need to care, all state will be lost. Just a hunch, we will have to try this out when the clock-stop mode is enabled.

**Comment by ClarexZhou** [comment]
@plbossart  should this be close now?

**Comment by plbossart** [comment]
Thanks for the reminder @ClarexZhou, yes this is no longer an issue I think. Let's close for now
