### ISSUE TITLE
[SDW][BUG]Sound setting cannot update when unplug/plug-in headset  

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1313]
**Describe the bug**
Open sound setting cannot activate soundwire PM suspend status. Switch to sound setting input page, can observe the input volume is dynamic, but check soundwire PM status still suspended.

**To Reproduce**
1.boot up without headset
2.wait soundwire pm status to suspend via cat /sys/bus/soundwire/devices/sdw-master-0/power/runtime_status
3.Open sound setting 
4.Plug in headset , check soundwire pm status again  --> suspended
5.Switch input source page. Check sound wire pm status again  --> suspended
 

**frequency**
100%

**Expected result**
Sound setting will update when plug in headset. Open sound setting and switch to input page will activate soundwire pm status

**Actual result**
Soundwire pm status cannot be activeted via openning sound setting .

**Environment**
Firmware: c7d0149 https://github.com/thesofproject/sof/commits/master 
Kernel: e7fb5a5 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  path same as FW branch
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/3723988/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3723989/logger.log)

**Comment by plbossart** [comment]
@YvonneYang2 Please try and revisit the bug description. I don't know what 'switch to input page' means.
If you are inserting a headset while the SoundWire master/codec are suspended, then indeed nothing will happen for now. We'd have to wait for the clock-stop mode to be supported, in D3 there is no check detection.

Can you retry while playing back sound?

**Comment by YvonneYang2** [comment]
> @YvonneYang2 Please try and revisit the bug description. I don't know what 'switch to input page' means.

Input page means input source setting page in sound setting.
![1015_1](https://user-images.githubusercontent.com/50347470/66813254-04a36d80-ef67-11e9-8844-7d3629af81bf.jpg)


> If you are inserting a headset while the SoundWire master/codec are suspended, then indeed nothing will happen for now. We'd have to wait for the clock-stop mode to be supported, in D3 there is no check detection.

Yes, but open sound setting cannot activate SoundWire master/codec, that's the problem is. Soundwire PM status is always suspended, so user open sound setting, plug in headset but cannot see it updated in sound setting. 

> Can you retry while playing back sound?

when issue occurred,  aplay 0,0(activate pm status) --> open sound setting --> unplug/plug-in headset --> sound setting updated

**Comment by plbossart** [comment]
@YvonneYang2 The logs provide ZERO information that helps locate when the 'sound setting' is used.
It seems to be that the issue is that there should be a capture going on to show the input level, but it's not happening. Again please provide usable traces that can clearly be correlated with the bug description.

**Comment by YvonneYang2** [comment]
The issue is not relevant to capture. Clarify the issue is that open sound setting cannot activate the PM status. So when end user open sound setting with suspended soundwire pm status, then plug in/unplug headset, it won't update. 

Upload the dmesg with my reproduce actions which divide the log like this:
```
[   45.412096] sof-audio-pci 0000:00:1f.3: Copying cached debugfs data
[   45.412099] sof-audio-pci 0000:00:1f.3: Copying cached debugfs data
[   45.412102] sof-audio-pci 0000:00:1f.3: Copying cached debugfs data

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Start to open sound setting, logs as below:

[   90.781889] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[   90.781904] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000040 at  00000048
[   90.781908] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[   90.784946] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[   90.784961] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
```

[dmesg.log](https://github.com/thesofproject/linux/files/3733023/dmesg.log)

**Comment by YvonneYang2** [comment]
Issue still can be reproduced as below steps.  Amixer contents value will not changed when unplug HDMI/DP external port.  When issue reproduced, unplug/plug in HDMI/DP, dmesg wouldn't update.
If test with DP, need set DP port in alsamixer (pin10 port0 cvt3)manually first.

Steps:
1. Boot up with HDMI or DP external port
2. Check via "amixer contents | less" 
```
numid=67,iface=CARD,name='HDMI/DP, pcm=6 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```
3.  Wait about 1 minute, then unplug HDMI or DP external port.
4.  Check via "amixer contents | less"
```
numid=67,iface=CARD,name='HDMI/DP, pcm=6 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```
[dmesg.log](https://github.com/thesofproject/linux/files/3761580/dmesg.log)

ucm: https://github.com/bardliao/intel-UCM/tree/for-sdw/sof-sdw-rt711-1308-715

**Comment by plbossart** [comment]
@YvonneYang2 your bug description has nothing to do with headsets, this is an HDMI bug?
Also @bardliao added a change to report the jacks, so please double-check.

**Comment by bardliao** [comment]
> Issue still can be reproduced as below steps. Amixer contents value will not changed when unplug HDMI/DP external port. When issue reproduced, unplug/plug in HDMI/DP, dmesg wouldn't update.
> If test with DP, need set DP port in alsamixer (pin10 port0 cvt3)manually first.
> 
> Steps:
> 
> 1. Boot up with HDMI or DP external port
> 2. Check via "amixer contents | less"
> 
> ```
> numid=67,iface=CARD,name='HDMI/DP, pcm=6 Jack'
>   ; type=BOOLEAN,access=r-------,values=1
>   : values=on
> ```
> 
> 1. Wait about 1 minute, then unplug HDMI or DP external port.
> 2. Check via "amixer contents | less"
> 
> ```
> numid=67,iface=CARD,name='HDMI/DP, pcm=6 Jack'
>   ; type=BOOLEAN,access=r-------,values=1
>   : values=on
> ```
> 
> [dmesg.log](https://github.com/thesofproject/linux/files/3761580/dmesg.log)
> 
> ucm: https://github.com/bardliao/intel-UCM/tree/for-sdw/sof-sdw-rt711-1308-715

@YvonneYang2 Is this related to this issue? Please file another issue if you find something wrong on HDMI plug/unplug status.

**Comment by bardliao** [comment]
@plbossart Let me describe the issue :) 
@YvonneYang2 want to check headphone plug/unplug status by ubuntu sound setting page. Ideally, we won't see Headphone on the Output device selection. However, the headphone option is still there while headphone is unplugged. I told her we don't support codec interrupt in runtime suspended. So she check the runtime_status of sdw-master-0, but it is suspended even when the headset mic is active. 
I can see rt711 jack detection report the wrong status, but, the runtime_status works perfectly on my side. I have report the rt711 jack detection issue to Realtek. @YvonneYang2 Could you recheck the runtime_status issue with updated UCM? I think it is not possible that capture can work in runtime suspended status, right?

**Comment by YvonneYang2** [comment]
Yes. Thanks Bard. That's what I want to express.  
I rechecked it again with updated UCM,  when issue reproduced which means the headphone option is still there while headphone is unplugged,  capture cannot work. 

The https://github.com/thesofproject/linux/issues/1313#issuecomment-545365762 is not related with the original issue. So split it to https://github.com/thesofproject/linux/issues/1364

**Comment by RanderWang** [comment]
please check https://github.com/thesofproject/linux/pull/1392

**Comment by plbossart** [comment]
@YvonneYang2 please retest with integration/soundwire-latest, this should be fixed now

**Comment by YvonneYang2** [comment]
Changed rt711->jd_src from RT711_JD2 to RT711_JD1 in rt711.c , then test it again. Issue cannot be reproduced. 
Split the clock stop mode feature to https://github.com/thesofproject/linux/issues/1409

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b 
FW: https://github.com/thesofproject/sof/commits/master  commit: 59c9338
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by YvonneYang2** [comment]
JD source issue will track in #1420 
Since this issue not reproduced, close it.
