### ISSUE TITLE
[SDW][BUG] I/O error occurred when stop/restart, pause/release or switch to foreground from background.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1329]
**Describe the bug**
I/O error occurred when push_pause arecord/aplay then push_release. 
I/O error occurred when stop arecord/aplay then restart.
I/O error occurred when switch to foreground from background. 
It seems related to https://github.com/thesofproject/sof/issues/1925#issuecomment-542249084 since #1935 and #1946 have been merged into master while https://github.com/thesofproject/linux/pull/1277 hasn't been merged into kernel branch yet. After applying https://github.com/thesofproject/linux/pull/1277, the issue is gone.

**To Reproduce**
1.Aplay via "aplay "aplay -Dhw:0,2 wav/48California_Dreaming.wav -vv -i "
2.Push_pause aplay
3.Push_release aplay 

**frequency**
100%

**Expected result**
Aplay resume normaly

**Actual result**
I/O error occurred

**Environment**
Firmware: 0d54df1d https://github.com/thesofproject/sof/commits/master 
Kernel: 0ebe10b https://github.com/thesofproject/linux/tree/integration/soundwire-latest 
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.m4
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode, CML RT700 RVP

<details>
 <summary>error logger</summary>

````

 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          DAI 3.16    1701278316.406250              nan      src/audio/dai.c:605 	dai_check_for_xrun() error: underrun due to no data available
    0      1         COMP         1701278326.145833         9.739583 of/audio/component.h:743 	comp_underrun() error: dev->comp.id = 16, source->avail = 1152, copy_bytes = 0
    0      1         PIPE         1701278424.427083        98.281250 src/audio/pipeline.c:833 	pipeline_copy() error: ret = -61
    0      1         PIPE 3.17    1701278434.479167        10.052083 src/audio/pipeline.c:1037	pipeline_task(): xrun recover failed! pipeline will be stopped!

````
</details>

[dmesg.log](https://github.com/thesofproject/linux/files/3737280/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3737281/logger.log)

**Comment by plbossart** [comment]
works for me with kernel https://github.com/thesofproject/linux/commit/0ebe10b38e4c70a9c8f52994725aa84f1769775d with PR https://github.com/thesofproject/linux/pull/1327 on top

the only thing that doesn't work is doing a system suspend with rtcwake while in paused mode, and that's tracked by https://github.com/thesofproject/linux/issues/1328

Please retest with PR #1327, thanks!

**Comment by YvonneYang2** [comment]
Issue can still reproduce with latest kernel d88ee7d + PR #1327 on top. But after applying PR #1277 , issue is gone.

**Comment by YvonneYang2** [comment]
Issue cannot reprocue on ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode with test recipe as below.

kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 7c85d69
FW: https://github.com/thesofproject/sof/commits/master  commit: 8b059f6
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode
