### ISSUE TITLE
[SDW][BUG]Paplay is still running but no sound output after waking up from s3.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1330]
**Describe the bug**
Paplay is still running but no sound output after wake up from s3.

**To Reproduce**
1.paplay via command "paplay wav/48California_Dreaming.wav -vvvv"
2.do s3 via command "sudo rtcwake -m mem -s 10"

**frequency**
100%

**Expected result**
Paplay should output normally after waking up from s3

**Actual result**
Console shows paplay is still running, but no sound output after waking up from s3

**Environment**
Firmware: 0d54df1d https://github.com/thesofproject/sof/commits/master 
Kernel: 0ebe10b https://github.com/thesofproject/linux/tree/integration/soundwire-latest 
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.m4
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

[paplay_dmesg.log](https://github.com/thesofproject/linux/files/3738233/paplay_dmesg.log)
[paplay_logger.log](https://github.com/thesofproject/linux/files/3738234/paplay_logger.log)

**Comment by dengyangchao** [comment]
issue also reproduce on CML RVP with codec ALC700 in SDW mode


<details>
 <summary>logger_error</summary>

````
CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          DAI 1.4      83296344.270833  83296344.000000      src/audio/dai.c:605 	dai_check_for_xrun() error: underrun due to no data available
    0      1         COMP          83296350.781250         6.510417 of/audio/component.h:743 	comp_underrun() error: dev->comp.id = 4, source->avail = 1152, copy_bytes = 0
    0      1         PIPE          83296412.968750        62.187500 src/audio/pipeline.c:833 	pipeline_copy() error: ret = -61
    0      1         PIPE 1.5      83296419.375000         6.406250 src/audio/pipeline.c:1037	pipeline_task(): xrun recover failed! pipeline will be stopped!
````
</details>

**Comment by YvonneYang2** [comment]
replaced by #1311
