### ISSUE TITLE
[TGL] HDA playback has 1~2s latency

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#1332]
**Describe the bug**
There're 1~2s latency when doing the audio playback. this issue happens on both HDA analog and HDMI playback.

**To Reproduce**
1) run audio playback on HDA analog: aplay -Dhw:0,0 -f dat -c 2 test.wav
2) run audio playback on HDMI(micro HDMI): aplay -Dhw:0,4 -f dat -c 2 test.wav 

**Reproduction Rate**
100%

**Expected behavior**
playback latency should less than 0.5s.

**Impact**
1~2s latency

**Environment**
Firmware: c8bc4b2 https://github.com/thesofproject/sof/commits/tgl-002-drop-stable
Kernel: intel-next kernel, tag intel-5.4-rc2-2019-10-10, commit id: fc2de5669533
tplg: sof-hda-generic.m4
platform: TGL with onboard ALC711 in HD-A mode. Connected an external monitor via microHDMI port.

**Screenshots or console output**
time aplay -Dhw:0,0 -f dat -c2 doreimi-48k-s16le-stereo.wav -d 5
Playing WAVE 'doreimi-48k-s16le-stereo.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo

real    0m7.528s
user    0m0.006s
sys     0m0.039s

[latency-dmesg.txt](https://github.com/thesofproject/linux/files/3738480/latency-dmesg.txt)
[latency-logger-t.txt](https://github.com/thesofproject/linux/files/3738481/latency-logger-t.txt)

**Comment by plbossart** [comment]
@keqiaozhang what is this kernel and does it have the fixes for the sync_writes that are in topic/sof-dev?

**Comment by keqiaozhang** [comment]
@plbossart 
We are using intel-next kernel branch for testing.
@xiulipan 
Please help to confirm if intel-next has the fixes for sync_writes. Thanks!

**Comment by xiulipan** [comment]
@plbossart @keqiaozhang Will check and try to add the patch in.

**Comment by xiulipan** [comment]
@keqiaozhang can not reproduce on latest code base. Could you help to confirm?
Also try to merge the latest fix about sync_wirte to make sure no more issues later.

**Comment by Bin-QA** [comment]
Verify with Kernel: intel-next kernel, tag intel-5.4-rc5-2019-10-29, commit id: d6aec649c24
Couldn't reproduce this issue on the TGL
