### ISSUE TITLE
[SDW][BUG]Arecord0,4(RTC715) capture empty audio after waking up from s3

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1340]
**Describe the bug**
Arecord0,4(RTC715) capture empty audio after waking up from s3.  Terminate it and restart arecord  can recover the issue.

**To Reproduce**
1.Arecord 0,4 via "arecord -Dhw:0,4 -f s16_le -r 48000 -c 2  test2.wav -vv -i"
2.do s3 via command "sudo rtcwake -m mem -s 10"

**frequency**
100%

**Expected result**
RT715 capture empty audio after waking up from s3

**Actual result**
RT715 works normally after waking up from s3

**Environment**
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 29debf8
FW: https://github.com/thesofproject/sof/commits/master  commit: 3d5d314
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

Logs:
[logger.log](https://github.com/thesofproject/linux/files/3748962/logger.log)
[rt715_capture_empty_dmesg.log](https://github.com/thesofproject/linux/files/3748963/rt715_capture_empty_dmesg.log)

**Comment by YvonneYang2** [comment]
Issue cannot reproduce on CML SDW Laptop with ALC711+ ALC1308+ ALC715 


kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 15f27d8 + PR1359
FW: https://github.com/thesofproject/sof/commits/master commit: f277189
tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by bardliao** [comment]
@YvonneYang2 Can we close the issue?

**Comment by YvonneYang2** [comment]
Issue cannot reproduce on ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 1c3de3d 
FW: https://github.com/thesofproject/sof/commits/master  commit: 89ef0af
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by YvonneYang2** [comment]
Close it.
