### ISSUE TITLE
[BUG][SDW]Input volume in sound setting stuck in level 1 status and parecord audio is not correct after switch source from Digital Micrphone to headset.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1345]
**Describe the bug**
Switch source from headset and Digital Micrphone in sound setting, parecord cannot work normally. Input volume in sound setting stuck in level 1 status and parecord audio is not correct.

**To Reproduce**
1.Boot up with headset. 
2.Open sound setting and swtich input source from headset to Micrphone.
3.Wait 15s then switch back to headset
4.Repeat steps 2/3 till issue reproduced.

**frequency**
3/10

**Expected result**
When input source is headset, parecord via headset works normally.

**Actual result**
When input source is headset after switching source, input volume in sound setting stuck in level 1.And parecord audio is not correct. Sometimes keeps repeat the latest word or sometimes capture empty audio.

**Environment**
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 29debf8
FW: https://github.com/thesofproject/sof/commits/master  commit: 3d5d314
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/3750220/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3750221/logger.log)

**Comment by YvonneYang2** [comment]
Issue not reproduced on CML Laptop with ALC711+ ALC1308+ ALC715.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 15f27d8 + PR1359
FW: https://github.com/thesofproject/sof/commits/master  commit: f277189
tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by bardliao** [comment]
@YvonneYang2 Could you test it on ICL RVP with https://github.com/thesofproject/linux/tree/integration/soundwire-latest + commit https://github.com/thesofproject/linux/pull/1359/commits/40e56a912942effd90f927d3207aee4b31b059a9?

**Comment by YvonneYang2** [comment]
Issue cannot reproduce on ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode with test recipe as below:

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b + https://github.com/thesofproject/linux/commit/40e56a912942effd90f927d3207aee4b31b059a9
FW: https://github.com/thesofproject/sof/commits/master  commit: 2ca6a4a
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by plbossart** [comment]
@YvonneYang2 can you close if it's no longer an issue? Or can you clarify if the commit 40e56a9 is actually needed?

**Comment by YvonneYang2** [comment]
Tested it without commit https://github.com/thesofproject/linux/commit/40e56a912942effd90f927d3207aee4b31b059a9 , and changed rt711->jd_src from RT711_JD2 to RT711_JD1 in rt711.c , issue cannot be reproduced.  So commit https://github.com/thesofproject/linux/commit/40e56a912942effd90f927d3207aee4b31b059a9 is not actually needed. 

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b 
FW: https://github.com/thesofproject/sof/commits/master  commit: 59c9338
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by plbossart** [comment]
ok, so if there is no issue let's close?

**Comment by YvonneYang2** [comment]
JD source issue will track in #1420
Since this issue not reproduced, close it.
