### ISSUE TITLE
Enable SOF driver to support DP-MST (DisportPort's Multi-Stream Transport)

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#136]

**Comment by libinyang** [comment]
DPMST hub mode works. And daisy chain mode can't be tested as the display is unstable. Will try to find why display is not stable.

**Comment by libinyang** [comment]
Daisy-chain mode works after using another Dell model moniter. (u2414Hb REV A01).
Now the status is: Daisy-chain mode works, DP-MST hub mode works. DP-MST with HDMI (3 monitors) doesn't work. Can't playback the third PCM.

**Comment by libinyang** [comment]
Now Now HDMI together with DPMST both works after I used the latest topology.

**Comment by mengdonglin** [comment]
@libinyang could you share your recipe (kernel, firrmware branch/commit and topology m4) for testing on UP2?

**Comment by lgirdwood** [comment]
@libinyang since this is a non trivial recipe, can you add some detail on enabling this in sof-docs.

**Comment by libinyang** [comment]
> @libinyang since this is a non trivial recipe, can you add some detail on enabling this in sof-docs.

@lgirdwood 
I would like to. Where can I get the sof-docs and add the information to?

**Comment by libinyang** [comment]
Now DPMST works very well with different DPMST modes, differnent DPMST hub on different platforms.
Here is the summary for the DPMST:

kernel: 41e4680a035ec574a170947b79a93c6db3a85749
SOF: 52f99da480fb4a9519715d870bc5f86d9392b95b
tplg: 52f99da480fb4a9519715d870bc5f86d9392b95b

Platforms: UP2, WHL are both OK
mode: DPMST, Daisy-chain mode are both OK
DPMST hub: club, StarTech are both OK (StarTech has compatibility issue with monitors)
DPMST + HDMI mode: is OK
DPMST S3: is OK (after HDMI S3 RFC patches are merged)

**Comment by plbossart** [comment]
@libinyang you clearly found a problem for S3 that needs to be fixed and that's really good progress. However, the feedback from Takashi is clearly that a different solution needs to be found. Are you working on an update? I'd rather merge an update or better yet get the solution through the weekly alsa-devel backport than take the existing patches as is and revert.

Also what topology did you use on Up2?

**Comment by libinyang** [comment]
@plbossart Yes, I'm working on it. I will check whether Takashi's solution is reasonable to implement. I will work on it today. I didn't give the updated patch last 2 days because I don't have environment at home to test to see if Takashi's suggestion is feasible.

tplg: 52f99da480fb4a9519715d870bc5f86d9392b95b

> @libinyang you clearly found a problem for S3 that needs to be fixed and that's really good progress. However, the feedback from Takashi is clearly that a different solution needs to be found. Are you working on an update? I'd rather merge an update or better yet get the solution through the weekly alsa-devel backport than take the existing patches as is and revert.
> 
> Also what topology did you use on Up2?

**Comment by plbossart** [comment]
> tplg: 52f99da480fb4a9519715d870bc5f86d9392b95b

I was asking about the topology filename (HDMI alone or PCM512-hdmi?)

**Comment by libinyang** [comment]
@plbossart 

It is sof-apl-pcm512x.tplg.

**Comment by mengdonglin** [comment]
Close this issue based on https://github.com/thesofproject/linux/issues/136#issuecomment-475955568
We can track HDMI audio failure after S3 by https://github.com/thesofproject/linux/issues/737 and https://github.com/thesofproject/linux/issues/489
