### ISSUE TITLE
[Bug][CML]Headphone is always listed in sound setting when not connected.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1371]
**Describe the bug**
Headphone is always listed in sound setting when not connected.

**To Reproduce**
1. No headphone is connected
2. Boot up system
3. open Settings ->Sound, headphone is listed in output setting and headset MIC is also listed in Input setting.

**frequency**
100%

**Actual result**
Headphone is always listed in sound setting when not connected.  Headset mic jack is off in alsamixer.
![image](https://user-images.githubusercontent.com/49641224/67553611-31fad300-f740-11e9-885a-19b8c9a14ac3.png)

**Expected result**
Headphone shouldn't list when not connected

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (6a4a824) + PR#1366
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/alsa-project/alsa-ucm-conf (c8808f6d)+ PR#4
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15
Platform: CML WA*-L notebook in HDA mode

No error message.
[bootupwithoutHeadset_dmesg.txt](https://github.com/thesofproject/linux/files/3771005/bootupwithoutHeadset_dmesg.txt)

**Comment by ClarexZhou** [comment]
@juimonen , could you please check on this?

**Comment by ClarexZhou** [comment]
Error is partly fixed on https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (a8b94e2)
Current behavior is:  Headset won’t be listed in sound output setting when headset isn’t connected.   But Headset MIC is still always listed in Sound input setting when headset isn’t connected.
![image](https://user-images.githubusercontent.com/49641224/67661690-ceb9ac80-f99c-11e9-9c50-5430f90d6f80.png)

**Comment by juimonen** [comment]
@ClarexZhou I updated https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test to "tie" the headset mic to headphones. So headset mic should be now only there when headphones are connected.... (even though there's no headset mic, but this is kind of best we can do atm)

**Comment by ClarexZhou** [comment]
Error not seen on https://github.com/juimonen/alsa-ucm-conf-1/commits/dell_test (c06c2385)

**Comment by dengyangchao** [comment]
issue can't reproduce with below recipe

Kernel repo: https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo: https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: Same as above SOF repo, sof-hda-generic.tplg
UCM https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (c06c238)
Kconfig: https://github.com/thesofproject/kconfig(55a0a0f) + PR#15
Platform: CML WA*-L notebook in HDA mode
