### ISSUE TITLE
[Bug][CML]Paplay hasn't audio output when select "Speaker" in  sound setting during headset connected.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1372]
**Describe the bug**
Paplay hasn't audio output when select "Speaker" in  sound setting during headset connected.

**To Reproduce**
1. Headphone is connected
2. Paplay 1.wav -vvvv
3. open Settings ->Sound, select "Speaker", found no audio output.

**frequency**
100%

**Actual result**
Speaker hasn't audio output once headset is connected

**Expected result**
Speaker should output normally once selected or should be listed once headset is connected.

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (6a4a824) + PR#1366
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/alsa-project/alsa-ucm-conf (c8808f6d)+ PR#4
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15
Platform: CML WA*-L notebook in HDA mode

No error message.

[SpeakerNoOutputOnceHeadsetConnected_amixer.txt](https://github.com/thesofproject/linux/files/3771041/SpeakerNoOutputOnceHeadsetConnected_amixer.txt)
[SpeakerNoOutputOnceHeadsetConnected.txt](https://github.com/thesofproject/linux/files/3771043/SpeakerNoOutputOnceHeadsetConnected.txt)

**Comment by ClarexZhou** [comment]
Might related with #1371

**Comment by ClarexZhou** [comment]
Error still seen on https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (a8b94e2)

**Comment by juimonen** [comment]
hmm ok, this is strange because it works for me in my dell laptop... @ClarexZhou can you take logs (pactl list sinks > log.txt) before and after the change to speakers?

**Comment by ClarexZhou** [comment]
@juimonen 
Here comes the pactl list sinks logs.
[log_headphone.txt](https://github.com/thesofproject/linux/files/3777775/log_headphone.txt)
[log_speaker.txt](https://github.com/thesofproject/linux/files/3777776/log_speaker.txt)

```
dell@dell-Latitude-3311:~$ diff log_headphone.txt log_speaker.txt
14c14
<       Latency: 229211 usec, configured 341000 usec
---
>       Latency: 310871 usec, configured 341000 usec
49c49
<       Active Port: [Out] Headphone
---
>       Active Port: [Out] Speaker

``

**Comment by juimonen** [comment]
@ClarexZhou ok yes no big difference as they are going to the same sink... can you open "alsamixer -c 0" and see how are the headphone/Speaker volumes and mute switches? so are both mute switches for some reason "on"?

**Comment by ClarexZhou** [comment]
speaker is  already unmuted and headphone is muted when selecting Speaker in sound settting. But  can't hear audio output from internal speaker.
[amixer_headphone.txt](https://github.com/thesofproject/linux/files/3777860/amixer_headphone.txt)
[amixer_speaker.txt](https://github.com/thesofproject/linux/files/3777861/amixer_speaker.txt)
[amixer_speaker_withoutheadset.txt](https://github.com/thesofproject/linux/files/3777862/amixer_speaker_withoutheadset.txt)
 
![image](https://user-images.githubusercontent.com/49641224/67664922-9073bb80-f9a3-11e9-9559-36f13dd7eef2.png)

```
dell@dell-Latitude-3311:~$ diff amixer_speaker.log amixer_headphone.log
32c32
<   : values=off,off
---
>   : values=on,on
144c144
<   : values=on,on
---
>   : values=off,off
dell@dell-Latitude-3311:~$ diff amixer_speaker.log amixer_speaker_withoutheadset.log
12c12
<   : values=on
---
>   : values=off

```

**Comment by juimonen** [comment]
@ClarexZhou hmm ok, for me the speaker/headset switches are mutually exclusive...
ok can you still take me pulseaudio logs when doing the routing switch...?
1) disable autospawn by open /etc/pulse/client.conf ;autospawn = yes -> autospawn = no (so remove semicolon and set to "no")
2) pulseaudio --kill
3) pulseaudio 2> log.txt
4) do the use case

**Comment by juimonen** [comment]
@ClarexZhou if you do this, remember to change back the /etc/pulse/client.conf, otherwise pulseaudio doesn't start at boot...

**Comment by juimonen** [comment]
@ClarexZhou and item 3) should be actually  "pulseaudio -vvvv 2> log.txt"

**Comment by dengyangchao** [comment]
@juimonen after change autospawn = yes to autospawn = no,      and issue still exist.

kernel: https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
sof: https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
tplg: Same as above SOF repo, sof-hda-generic.tplg
UCM: https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (c06c238)
kconfig: https://github.com/thesofproject/kconfig(55a0a0f) + PR#15

 add log.txt below
```
I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted
I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted
D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
D: [pulseaudio] core-util.c: RealtimeKit worked.
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: This is PulseAudio 11.1
D: [pulseaudio] main.c: Compilation host: x86_64-pc-linux-gnu
D: [pulseaudio] main.c: Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/pulseaudio-YrFCYf/pulseaudio-11.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wextra -pipe -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wformat-security -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings -Wno-unused-parameter -ffast-math -fno-common -fdiagnostics-show-option -fdiagnostics-color=auto
D: [pulseaudio] main.c: Running on host: Linux x86_64 5.0.8-hda-validation-20191029-0-8ea23bd #5.0.8 SMP Tue Oct 29 09:31:34 CST 2019
D: [pulseaudio] main.c: Found 8 CPUs.
I: [pulseaudio] main.c: Page size is 4096 bytes
D: [pulseaudio] main.c: Compiled with Valgrind support: no
D: [pulseaudio] main.c: Running in valgrind mode: no
D: [pulseaudio] main.c: Running in VM: no
D: [pulseaudio] main.c: Optimized build: yes
D: [pulseaudio] main.c: FASTPATH defined, only fast path asserts disabled.
I: [pulseaudio] main.c: Machine ID is 3957d6542a64480bb95c45aba7b7766f.
I: [pulseaudio] main.c: Session ID is 1.
I: [pulseaudio] main.c: Using runtime directory /run/user/1001/pulse.
I: [pulseaudio] main.c: Using state directory /home/dell/.config/pulse.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-11.1/modules.
I: [pulseaudio] main.c: Running in system mode: no
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
```
[log.txt](https://github.com/thesofproject/linux/files/3781974/log.txt)

**Comment by ClarexZhou** [comment]
Speaker disappears from sound setting on previous UCM https://github.com/RanderWang/intel-UCM/tree/hdmi
 
![image](https://user-images.githubusercontent.com/49641224/67745035-210ed200-fa5e-11e9-813d-8ff11ffb482c.png)

**Comment by ClarexZhou** [comment]
Error not seen on https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (8e298933)
