### ISSUE TITLE
[BUG][SDW]Switch source in sound setting, sound output stopped but paplay still running. 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1373]
**Describe the bug**
Switch source in sound setting, sound output stopped but paplay still running. 

**To Reproduce**
1.paplay via command "paplay test.wav -vvv "
2.open sound settings and switch output source between speaker and headphone.

**frequency**
100%

**Expected result**
Palay work normally.

**Actual result**
Paplay has sound output before switch source, then sound stopped but paplay still running when switch source.

**Environment**
Firmware: c7d0149 https://github.com/thesofproject/sof/commits/master 
Kernel: e7fb5a5 https://github.com/thesofproject/linux/tree/integration/soundwire-latest
tplg:  sof-icl-rt711-rt1308-rt715-hdmi.tplg rename sof-icl-rt711-rt1308-rt715.tplg  path same as FW branch
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

<details>
 <summary>error logger</summary>

````
	CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          DAI 3.16    299449417.239583 299449408.000000      src/audio/dai.c:588 	dai_check_for_xrun() error: underrun due to no data available
    0      1         COMP         299449427.031250         9.791667 of/audio/component.h:743 	comp_underrun() error: dev->comp.id = 16, source->avail = 768, copy_bytes = 0
    0      1         PIPE         299449518.489583        91.458336 src/audio/pipeline.c:833 	pipeline_copy() error: ret = -61
    0      1         PIPE 3.17    299449528.541667        10.052083 src/audio/pipeline.c:1037	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      1          DAI 2.10    324766764.062500  25317236.000000      src/audio/dai.c:593 	dai_check_for_xrun() error: overrun due to no data available
    0      1         COMP         324766773.802083         9.739583 of/audio/component.h:759 	comp_overrun() error: dev->comp.id = 10, sink->free = 768, copy_bytes = 0
    0      1         PIPE         324766900.260417       126.458336 src/audio/pipeline.c:854 	pipeline_copy() error: ret = -61, start->comp.id = 10, dir = 0
    0      1         PIPE 2.11    324766912.135417        11.875000 src/audio/pipeline.c:1037	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      1         COMP         360414329.687500  35647416.000000 rc/audio/component.c:192 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET

````
</details>

[switch_source_insoundsetting_no_sound.log](https://github.com/thesofproject/linux/files/3720526/switch_source_insoundsetting_no_sound.log)
[switch_source_insoundsetting_no_sound_dmesg.log](https://github.com/thesofproject/linux/files/3720527/switch_source_insoundsetting_no_sound_dmesg.log)
[switch_source_insoundsetting_no_sound_error.log](https://github.com/thesofproject/linux/files/3720528/switch_source_insoundsetting_no_sound_error.log)

**Comment by RanderWang** [comment]
fixed by https://github.com/bardliao/linux/pull/3

**Comment by RanderWang** [comment]
@YvonneYang2  can yo move this bug to kernel side ? thanks!

**Comment by plbossart** [comment]
@YvonneYang2 can you clarify why PR #1359 (or what parts of it) is needed here, and on which platform you test? if you take the "[HACK] ASoC: intel: sdw_rt711_rt1308_rt715: comment out patch" then this is not going to work on ICL

Something is wrong, please update your bug description and retest with integration/soundwire-latest 661d2612aabbd222c4b6af99df530ce3c37ff24a

**Comment by bardliao** [comment]
> @YvonneYang2 can you clarify why PR #1359 (or what parts of it) is needed here, and on which platform you test? if you take the "[HACK] ASoC: intel: sdw_rt711_rt1308_rt715: comment out patch" then this is not going to work on ICL
> 
> Something is wrong, please update your bug description and retest with integration/soundwire-latest [661d261](https://github.com/thesofproject/linux/commit/661d2612aabbd222c4b6af99df530ce3c37ff24a)

@plbossart It should be [ASoC: codec: fix codec io init issue when resuming](https://github.com/thesofproject/linux/pull/1359/commits/c52607fddd4359f24435e559bff909a2e4d12454).
Codec driver will redo io_init if it received SDW_SLAVE_UNATTACHED, and all mixer controls 
 (and maybe other configurations) will be reset after that.

**Comment by plbossart** [comment]
@bardliao @RanderWang We need to reset all the codec when the slave becomes ATTACHED. Please clarify why removing the inits makes things work better! There is something very unclear behind your fix.
I believe that what happens is rather that the mixer settings are not restored during a resume, but that's not a reason to remove the inits. We need to fix the init and make sure the mixer settings are re-applied.

**Comment by RanderWang** [comment]
I update the detail in PR https://github.com/thesofproject/linux/pull/1359

**Comment by YvonneYang2** [comment]
First change rt711->jd_src from RT711_JD2 to RT711_JD1 in rt711.c for rvp test.
For now, issue only can be reproduced on icl 3-in-1 board with integration/soundwire-latest (9f1bd5b)+ pr #1407 
CML SDW Laptop with ALC711+ ALC1308+ ALC715  cannot reproduce the issue with same kernel as above.

Test steps:

1. Paplay a song via headset/HDMI/DP
2. Wait for 2 minute, switch output source to speaker in sound setting.
if issue not reproduced, repeat step1 and 2 till issue reproduced.

Logs:
[dmesg.log](https://github.com/thesofproject/linux/files/3797352/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3797353/logger.log)

**Comment by YvonneYang2** [comment]
Test it with integration/soundwire-latest(9f1bd5b) + https://github.com/thesofproject/linux/commit/2a3a03a3f86d781cf274a314ebd7d8347bbde046 , issue cannot be reproduced on icl 3-in-1 boards.   

Without commit https://github.com/thesofproject/linux/commit/2a3a03a3f86d781cf274a314ebd7d8347bbde046, issue can still be reproduced. But reproduced rate is lower than before, tested it 15 rounds, only reproduced two times. When issue is reproduced, amxier contents shows the value of rt1308 speaker is off. Stop paplay, and set rt1308 amixer setting again, issue can be recovered.

Logs as below:
[all_logger.log](https://github.com/thesofproject/linux/files/3802966/all_logger.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3802967/dmesg.log)
[error_logger.log](https://github.com/thesofproject/linux/files/3802968/error_logger.log)


Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b + https://github.com/thesofproject/linux/commit/2a3a03a3f86d781cf274a314ebd7d8347bbde046
FW: https://github.com/thesofproject/sof/commits/master  commit: e5fe2ca
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by bardliao** [comment]
@YvonneYang2 Could you retest it? It should be fixed now.

**Comment by plbossart** [comment]
@YvonneYang2  @mengdonglin integration/soundwire-latest now has all the known fixes for suspend/resume please retry (along with the latest firmware)

**Comment by YvonneYang2** [comment]
Checked it on CML laptop, issue cannot be reproduced. 
CPU on ICL RVP is broken, will test it tomorrow. If issue is not reproduced, will close the bug.

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced on CML SDW Laptop with ALC711+ ALC1308+ ALC715 , close it. 
Will create a new issue once issue is reproduced on ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode.
