### ISSUE TITLE
[Bug][CML] Default 'Headphone Playback Volume' is zero

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1377]
**Describe the bug**
Default 'Headphone Playback Volume' is zero

**To Reproduce**
1. No headphone is connected
2. Boot up system
3. Connect headset
4. aplay -Dhw:0,0 -r48000 -c2 -fs16_le 1.wav -vv -i , no sound output on headset
5. alsamixer and amixer contents to check, find 'Headphone Playback Volume' is zero"

**frequency**
Tried about 3 times and keeps reproudced.
But not reproduced anymore after 4hours testing.

**Actual result**
Default 'Headphone Playback Volume' is zero
```
numid=1,iface=MIXER,name='Headphone Playback Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=87,step=0
  : values=0,0
  | dBscale-min=-65.25dB,step=0.75dB,mute=0
```

**Expected result**
Headphone volume should be set, not zero.

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (6a4a824) + PR#1366
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/alsa-project/alsa-ucm-conf (c8808f6d)+ PR#4
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15
Platform: CML WA*-L notebook in HDA mode

[dmesg_headsetVolumeDefault0.txt](https://github.com/thesofproject/linux/files/3771781/dmesg_headsetVolumeDefault0.txt)
[amixerContentswithheadset.txt](https://github.com/thesofproject/linux/files/3771782/amixerContentswithheadset.txt)

**Comment by ClarexZhou** [comment]
@juimonen , could you please check first?

**Comment by ClarexZhou** [comment]
Error not seen on https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (a8b94e2)

**Comment by dengyangchao** [comment]
issue can't reproduce with below recipe and Default 'Headphone Playback Volume' is 80

Kernel repo: https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo: https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology:  Same as above SOF repo, sof-hda-generic.tplg
UCM https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (c06c238)
Kconfig: https://github.com/thesofproject/kconfig(55a0a0f) + PR#15
Platform: CML WA*-L notebook in HDA mode
