### ISSUE TITLE
[Bug][CML]System hang at 'Ubuntu' page during boot up with WD19 dock connected

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1378]
**Describe the bug**
System hang at 'Ubuntu' loading page during boot up with WD19 dock connected

**To Reproduce**
1. WD19 with both HDMI and DP is connected to unit
2. Long press power button to power off unit
3. Press power button to boot up

**frequency**
<10%
Details as below: Error not occurred after blacklist sof

Scenaro | With WD19 dock | blacklist sof_with WD19 dock
-- | -- | --
Cold Boot (Power off via long press power   button) | Pass: 9 times pass     Fail: Hang at ubuntu loading page during boot up: failed at the 7th time.   (wait 5 mins no udpate.) | Pass: all 10 times pass
Cold Boot (Power off via power off menu) | Pass: all 10 times pass | Pass:all 10 times pass
Warm boot ("sudo reboot"   command) | Pass: all 5 times pass | Pass: all 5 times pass

**Actual result**
Hang at 'ubuntu' displaying page.

**Expected result**
Should boot up successfully.

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (6a4a824) + PR#1366
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/alsa-project/alsa-ucm-conf (c8808f6d)+ PR#4
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15
Platform: CML WA*-L notebook in HDA mode

Did't get log for system hang.

**Comment by dengyangchao** [comment]
tried 10 times Cold Boot (Power off via long press power button), issue can't reproduce with below recipe


Kernel repo: https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo: https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology:  Same as above SOF repo, sof-hda-generic.tplg
UCM https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (c06c238)
Kconfig: https://github.com/thesofproject/kconfig(55a0a0f) + PR#15
Platform: CML WA*-L notebook in HDA mode
