### ISSUE TITLE
strange ipc error flow

### ISSUE THREAD

**Issue by juimonen** [thesofproject/linux#1379]
in ipc.c function tx_wait_done:

if (msg->reply_size)
                        memcpy(reply_data, msg->reply_data, msg->reply_size);
if (ret < 0)
                        dev_err(sdev->dev, "error: ipc error for 0x%x size %zu\n",
                                hdr->cmd, msg->reply_size);

so we are first copying before checking the error? is this intended behavior?
for e.g. demux is returning -einval with get_data, so kcontrol cache will be borked....

**Comment by juimonen** [comment]
@plbossart @ranj063 @lyakh FYI

**Comment by plbossart** [comment]
If you look at the Intel stuff, there is already another copy happening earlier

````c
	/* get IPC reply from DSP in the mailbox */
	sof_mailbox_read(sdev, sdev->host_box.offset, &reply,
			 sizeof(reply));

	if (reply.error < 0) {
		memcpy(msg->reply_data, &reply, sizeof(reply));
		ret = reply.error;
	} else {
````

why we'd even look at data returned with an error baffles me.

**Comment by ranj063** [comment]
@juimonen we discussed this exact same thing when @singalsu was making changes to the byte control IO functions but this requires some invasive changes so we left it for later. But yes please do submit a patch to fix the sequence.

**Comment by plbossart** [comment]
@juimonen @ranj063 isn't this fixed?

**Comment by ranj063** [comment]
@plbossart I dont think so. @singalsu was supposed to take care of it most recently

**Comment by juimonen** [comment]
@ranj063 I don't remember now at all what we we're discussing about possible invasive fixes...?

@plbossart the snippet you we're mentioning AFAIK relates to DSP initiated message from DSP to host. This part that I'm referring relates to setting/getting data from host to DSP.

Anyway I made  https://github.com/thesofproject/linux/pull/1728, so just changing the order of error code check and memcpy.

**Comment by plbossart** [comment]
@juimonen can we close this? This seems super-old...

**Comment by singalsu** [comment]
I'm not working with byte control IPC changes. The new controls flow via PM cache changed things fundamentally and we can't prevent illegal messages from failing later since we don't parse the binary controls in kernel. Also my +1 for closing this.
