### ISSUE TITLE
[Feature] Enable clock-stop mode for SoundWire

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1380]
we need to enable clock-stop mode to allow for jack detection while in pm_runtime suspend.

**Comment by RanderWang** [comment]
@plbossart  I ported your clock_stop2 branch to soundwire-latest. With my changes, https://github.com/RanderWang/linux/commits/clock_stop_test,  now plugging event can be detected. But I got IPC timeout for the first IPC cmd with playback. I will go on debugging.

**Comment by plbossart** [comment]
All features implemented, now we are in bug fix territory
