### ISSUE TITLE
[Bug][CML]Paplay has no sound output after plug out HDMI during paplay when both DP and HDMI are connected

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1396]
**Describe the bug**
Paplay has no sound output after plug out HDMI during paplay when both DP and HDMI are connected

**To Reproduce**
1. Both DP and HDMI are connected 
2. In sound setting, select HDMI as audio output source
3. 'paplay test.wav -vvv'
4. Disconnect HDMI 
![image](https://user-images.githubusercontent.com/49641224/67832536-e4ee7680-fb1c-11e9-9017-f702b0d5f605.png)

**frequency**
100%

**Actual result**
 DP is audio highlighted in sound setting, but no output  -> Can output normally when re-select audio output source  or  just stop current paplay and trigger paplay again.

More info:
If select DP in step2 and disconnect DP in step 4. Error not seen. Paplay will auto switch to Speaker and output normally.

**Expected result**
Audio should output on DP normally

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (8e298933)
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15

Logs are disabled.

**Comment by kv2019i** [comment]
I can reproduce this. It seems PA correctly see unplug of the HDMI monitor (HDMI1) and tries to move to DP monitor (HDMI2 in the log), but this fails for some reason. When I check ALSA kernel procfs, pcm3 (HDMI1) is still running and pcm4 is closed. So PA did not switch the PCM device. Logs:

```
Oct 30 10:05:40 rukoilijasirkka pulseaudio[1365]: ( 849.841|  10.868) [pulseaudio] module-alsa-card.c: Jack 'HDMI/DP,pcm=3 Jack' is now unplugged
Oct 30 10:05:40 rukoilijasirkka pulseaudio[1365]: ( 849.841|   0.000) [pulseaudio] device-port.c: Setting port [Out] HDMI1 to status no
Oct 30 10:05:40 rukoilijasirkka pulseaudio[1365]: ( 849.841|   0.000) [pulseaudio] core.c: default_sink: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_gene
ric.Hdmi__hw_sofsklhdacard_3__sink -> alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.Hdmi__hw_sofsklhdacard_4__sink
Oct 30 10:05:40 rukoilijasirkka pulseaudio[1365]: ( 849.841|   0.000) [pulseaudio] module-switch-on-port-available.c: Trying to switch away from port [Out] HDM
I1, found [Out] HDMI2
```

FYI @juimonen

**Comment by juimonen** [comment]
@ClarexZhou can you test this with latest dell_test? I separated hdmi's to their own use cases...

**Comment by ClarexZhou** [comment]
Original steps issue is fixed on https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test  (bf4885eb4).  But DP has no output when plug in HDMI again. Can't be recovered via release current paplay and trigger another. Can be recovered via re-select output source in sound setting.
**Detail steps**:
1. Both DP and HDMI are connected
2. In sound setting, select HDMI as audio output source
3. 'paplay test.wav -vvv'
4. Disconnect HDMI   -> Pass. Working ok now.  Switched to DP and output normally
5. Connect HDMI again ->Fail.  DP has no audio output

**Comment by kv2019i** [comment]
@ClarexZhou wrote: 
> Original steps issue is fixed on https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (bf4885eb4). But DP has no output when plug in HDMI again. Can't be recovered via release current paplay and trigger another. Can be recovered via re-select output source in sound setting.
> **Detail steps**:
> 
>     1. Both DP and HDMI are connected
> 
>     2. In sound setting, select HDMI as audio output source
> 
>     3. 'paplay test.wav -vvv'
> 
>     4. Disconnect HDMI   -> Pass. Working ok now.  Switched to DP and output normally
> 
>     5. Connect HDMI again ->Fail.  DP has no audio output

I could reproduce this as well. This would seem to be a PA11.x bug as well. The detection back is detected but PA fails to activate the PCM.

Unplug is ok, HDMI->DP switch is made:
```
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.274) [pulseaudio] module-alsa-card.c: Jack 'HDMI/DP,pcm=3 Jack' is now unplugged
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.000) [pulseaudio] device-port.c: Setting port [Out] HDMI1 to status no
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.000) [pulseaudio] core.c: default_sink: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.Hdmi1__hw_sofsklhdacard_3__sink -> alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock_1__sink
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.000) [pulseaudio] module-switch-on-port-available.c: Trying to switch away from port [Out] HDMI1, found [Out] HDMI2
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.000) [pulseaudio] module-switch-on-port-available.c: Trying to switch to port [Out] HDMI2
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.000) [pulseaudio] module-switch-on-port-available.c: Finding best profile for port [Out] HDMI2, preferred = Hdmi2
Oct 31 12:19:17 rukoilijasirkka pulseaudio[3861]: (  86.501|   0.000) [pulseaudio] sink-input.c: Starting to move sink input 1 from 'alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.Hdmi1__hw_sofsklhdacard_3__sink'
```

But upon reconnect, the action fails:
```
Oct 31 12:19:23 rukoilijasirkka pulseaudio[3861]: (  92.616|   5.565) [pulseaudio] module-alsa-card.c: Jack 'HDMI/DP,pcm=3 Jack' is now plugged in
Oct 31 12:19:23 rukoilijasirkka pulseaudio[3861]: (  92.616|   0.000) [pulseaudio] device-port.c: Setting port [Out] HDMI1 to status yes
Oct 31 12:19:23 rukoilijasirkka pulseaudio[3861]: (  92.616|   0.000) [pulseaudio] module-switch-on-port-available.c: Trying to switch to port [Out] HDMI1
Oct 31 12:19:23 rukoilijasirkka pulseaudio[3861]: (  92.616|   0.000) [pulseaudio] module-switch-on-port-available.c: Finding best profile for port [Out] HDMI1, preferred = Hdmi1
Oct 31 12:19:23 rukoilijasirkka pulseaudio[3861]: (  92.616|   0.000) [pulseaudio] module-switch-on-port-available.c: No suitable profile found
```

This does not seem to be a driver or UCM bug but rather in PA11 logic. @juimonen , thoughts?

**Comment by ClarexZhou** [comment]
Close for won't fix UCM1 issue
