### ISSUE TITLE
[Bug] [CML] Auto switch to headset when select Speaker during paplay via HDMI

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1397]
**Describe the bug**
Paplay has no sound output after plug out HDMI during paplay when both DP and HDMI are connected

**To Reproduce**
1. Both HDMI and headset are connected 
2. In sound setting, select headset as audio output souce
3. 'paplay test.wav -vvv'
4. In sound setting, select HDMI as audio output source
5. In sound setting, select Speaker as audio output source

**frequency**
100%

**Actual result**
Audo switch to headset.

**Expected result**
Audio should output on Speaker

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (8e298933)
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15

Logs are disabled.

**Comment by juimonen** [comment]
@ClarexZhou my latest dell_test branch should fox this...

**Comment by ClarexZhou** [comment]
Issue not seen on https://github.com/juimonen/alsa-ucm-conf-1/commits/dell_test (bae8581)

**Comment by ClarexZhou** [comment]
Reopen for error seen on UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/, commit id 53f931681

**Comment by ClarexZhou** [comment]
Close UCM1 issues for won't fix
