### ISSUE TITLE
[BUG][TGL]Dmesg shows "failed to reset HDA controller gctl 0x1"  info when do aplay0,2(rt1308) stop/restart stress test.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1399]
**Describe the bug**
Speaker's playback is stopped at 267th time. Dmesg shows "failed to reset HDA controller gctl 0x1"  info.

**To Reproduce**
1.Reboot system.
2.Run "sudo ./sof-test-playback.sh ".

**frequency**
Run 500 times and failed at 267th time .

**Expected result**
Failed info should not show when do speaker playback stress test.

**Actual result**
Speaker's playback is stopped at 267th time. Dmesg shows "failed to reset HDA controller gctl 0x1"  info.

Test recipe:
Kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b
FW: https://github.com/thesofproject/sof/commits/master commit: 2ca6a4a
tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform: TGL RVP, with codec ACL711 in SDW mode,  ALC1308 in I2S mode

<details>
 <summary>dmesg logger</summary>

````
[ 4240.194212] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 2 dir 0 cmd 0
[ 4240.194218] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 4240.194484] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 4240.195068] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[ 4240.195086] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 4240.195238] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 4240.195246]  SSP2-Codec: ASoC: trigger BE SSP2-Codec cmd 0
[ 4240.195387]  Speaker: ASoC: hw_free FE Speaker
[ 4240.195407] sof-audio-pci 0000:00:1f.3: pcm: free stream 2 dir 0
[ 4240.195420]  SSP2-Codec: ASoC: hw_free BE SSP2-Codec
[ 4240.195479]  SSP2-Codec: ASoC: close BE SSP2-Codec
[ 4240.195486]  Speaker: ASoC: close FE Speaker
[ 4240.195489] sof-audio-pci 0000:00:1f.3: pcm: close stream 2 dir 0
[ 4240.195495]  SSP2-Codec: ASoC: BE SSP2-Codec event 2 dir 0
[ 4240.396839] sof-audio-pci 0000:00:1f.3: snd_sof_runtime_idle
[ 4240.396889]  Speaker: ASoC: BE playback disconnect check for SSP2-Codec
[ 4240.396894]  Speaker: freed DSP playback path Speaker -> SSP2-Codec
[ 4240.955251] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 4240.955633] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 4242.695588] sof-audio-pci 0000:00:1f.3: snd_sof_runtime_suspend
[ 4242.695593] sof-audio-pci 0000:00:1f.3: sof_suspend
[ 4242.696097] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[ 4242.736888] sof-audio-pci 0000:00:1f.3: sof_send_pm_ctx_ipc
[ 4242.736917] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 4242.737568] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 4242.737606] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf010f0f successful
[ 4242.737620] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[ 4242.737627] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 4242.737705] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[ 4242.925914] sof-audio-pci 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[ 4242.925922] sof-audio-pci 0000:00:1f.3: error: failed to reset controller during suspend
[ 4242.925924] sof-audio-pci 0000:00:1f.3: error: failed to power down DSP during suspend -5
[ 4242.925931] sof-audio-pci 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -5)
[ 4244.495513]  Speaker: ASoC: found 4 audio playback paths
[ 4244.495519] rt711_rt1308 rt711_rt1308: ASoC: find BE for widget SSP2.OUT
[ 4244.495521] rt711_rt1308 rt711_rt1308: ASoC: try BE : ALH2.OUT
[ 4244.495522] rt711_rt1308 rt711_rt1308: ASoC: try BE : (not set)
[ 4244.495524] rt711_rt1308 rt711_rt1308: ASoC: try BE : SSP2.OUT
[ 4244.495527]  Speaker: connected new DPCM playback path Speaker -> SSP2-Codec
[ 4244.495539]  Speaker: ASoC: found 1 new BE paths
[ 4244.495542]  SSP2-Codec: ASoC: open playback BE SSP2-Codec
[ 4244.495549]  Speaker: ASoC: open FE Speaker
[ 4244.495554] sof-audio-pci 0000:00:1f.3: pcm: open stream 2 dir 0
[ 4244.495557] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 4244.495559] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 4244.495560] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 4244.495846] sof-audio-pci 0000:00:1f.3: rate_min: 48000 rate_max: 48000
[ 4244.495849] sof-audio-pci 0000:00:1f.3: channels_min: 2 channels_max: 2
[ 4244.495851]  SSP2-Codec: ASoC: hw_params BE SSP2-Codec
[ 4244.495855] sof-audio-pci 0000:00:1f.3: rate_min: 48000 rate_max: 48000
[ 4244.495858] sof-audio-pci 0000:00:1f.3: channels_min: 2 channels_max: 2
[ 4244.495861] rt1308 i2c-10EC1308:00: bclk_ms is 1 and pre_div is 1 for iis 0
[ 4244.495863] rt1308 i2c-10EC1308:00: lrck is 48000Hz and pre_div is 1 for iis 0
[ 4244.495870] rt1308 i2c-10EC1308:00: Update DAI routes for rt1308-aif playback
[ 4244.495873] rt1308 i2c-10EC1308:00: Connecting DAI route AIF1 Playback -> AIF1RX
[ 4244.495876] sof-audio-pci 0000:00:1f.3: rate_min: 48000 rate_max: 48000
[ 4244.495877] sof-audio-pci 0000:00:1f.3: channels_min: 2 channels_max: 2
[ 4244.495879] sof-audio-pci 0000:00:1f.3: Update DAI routes for SSP2 Pin playback
[ 4244.495883]  Speaker: ASoC: hw_params FE Speaker rate 48000 chan 2 fmt 2
[ 4244.495885] sof-audio-pci 0000:00:1f.3: Update DAI routes for Speaker 2 playback
[ 4244.495887] sof-audio-pci 0000:00:1f.3: Connecting DAI route Passthrough Playback 2 -> PCM2P
[ 4244.495889] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 2 dir 0
[ 4244.495893] sof-audio-pci 0000:00:1f.3: generating page table for 000000009bb05176 size 0xffc0 pages 16
[ 4244.495960] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[ 4244.497163] sof-audio-pci 0000:00:1f.3: error: stream reset failed
[ 4244.497174] sof-audio-pci 0000:00:1f.3: error: hdac prepare failed: ffffff92
[ 4244.497178] sof-audio-pci 0000:00:1f.3: error: platform hw params failed
[ 4244.497191] sof-audio-pci 0000:00:1f.3: ASoC: 0000:00:1f.3 hw params failed: -110
[ 4244.497198]  Speaker: ASoC: hw_params FE failed -110
[ 4244.497203]  SSP2-Codec: ASoC: hw_free BE SSP2-Codec
[ 4244.497205]  Speaker: ASoC: hw_free FE Speaker
[ 4244.497207] sof-audio-pci 0000:00:1f.3: pcm: free stream 2 dir 0
[ 4244.497225]  SSP2-Codec: ASoC: hw_free BE SSP2-Codec
[ 4244.497300]  SSP2-Codec: ASoC: close BE SSP2-Codec
[ 4244.497305]  Speaker: ASoC: close FE Speaker
[ 4244.497307] sof-audio-pci 0000:00:1f.3: pcm: close stream 2 dir 0
[ 4244.497327]  SSP2-Codec: ASoC: BE SSP2-Codec event 2 dir 0
[ 4244.497352]  Speaker: ASoC: BE playback disconnect check for SSP2-Codec
[ 4244.497353]  Speaker: freed DSP playback path Speaker -> SSP2-Codec
 


````
</details>

[aplay_error_267_dmesg.log](https://github.com/thesofproject/linux/files/3787309/aplay_error_267_dmesg.log)
[aplay_error_267_logger_all.log](https://github.com/thesofproject/linux/files/3787311/aplay_error_267_logger_all.log)
[sof-test-playback.txt](https://github.com/thesofproject/linux/files/3787313/sof-test-playback.txt)

**Comment by plbossart** [comment]
@sinahuang can you try to run this test in nocodec mode with topic/sof-dev. I'd like to make sure some of the quirks we added for SoundWire don't get in the way (we have additional reset assert/de-assert cycles).

**Comment by sinahuang** [comment]
This issue can not be reproduced on BYT MinnowBoard in nocodec mode  and APL UP2 in nocodec mode with topic/sof-dev.

Test for 500 times.

Test recipe:
Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit: f5e70ced
FW: https://github.com/thesofproject/sof/commits/master commit: 59c93383
Tplg: sof-byt-nocodec.tplg and sof-apl-nocodec.tplg
Platform: APL UP2 in nocodec mode , BYT MinnowBoard in nocodec mode.

**Comment by plbossart** [comment]
@sinahuang I meant nocodec mode on TGL! The MinnowBoard has a DSP that's 4 generations older so it's not the same test at all.

**Comment by sinahuang** [comment]
Verified the issue on TGL RVP in nocodec mode with topic/sof-dev, issue can't be reproduced.

Test for 1000 times.

Test recipe:

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit: c265f25d
FW: https://github.com/thesofproject/sof/commits/master commit: fe321d65
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP, with codec ACL711 in SDW mode, ALC1308 in I2S mode

**Comment by plbossart** [comment]
Thanks @sinahuang, that's useful information.

One of the differences with SoundWire is the commit 10f5534a81708bbec68ccc014c8c8a2f3a844401
this introduces an additional cycle of DSP reset and that's precisely the register that can't be modified without a timeout.

can you retest with topic/sof-dev + 10f5534a81708bbec68ccc014c8c8a2f3a844401 on top?
Thanks!

**Comment by sinahuang** [comment]
Verified the issue on TGL RVP in nocodec mode with topic/sof-dev + 10f5534, issue can't be reproduced.

Test for 1000 times.

Test recipe:

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit: 4e76b4a +10f5534
FW: https://github.com/thesofproject/sof/commits/master commit: 0b7fd03
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP, with codec ACL711 SDW mode, ALC1308 in I2S mode.

**Comment by plbossart** [comment]
@sinahuang ok, so if the nocodec path is fine, can you try w/ SoundWire again, but this time disable the HDAudio link with make menuconfig?

**Comment by sinahuang** [comment]
Verified the issue on TGL RVP with codec in SDW mode after disabling HDAudio link, issue can't be reproduced. 

Test for 1000 times

Test recipe:

Kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 35dd388
FW: https://github.com/thesofproject/sof/commits/master commit: 9844920
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform: TGL RVP with codec ACL711 in SDW mode, ALC1308 in I2S mode.

More info: HDAudio links always can be disabled when I compiled the kernel on TGL RVP with codec in SDW mode.

**Comment by plbossart** [comment]
thanks @sinahuang 
What this means is that we have a difference in the initialization of our hardware, and somehow the code that's executed with SOF_HDA_LINK interferes with the controller reset.
Maybe a problem with the i915/HDMI stuff.

That's not an easy one to fix. @mengdonglin @wenqingfu FYI, we need folks to look into this.

**Comment by sinahuang** [comment]
HDAudio links always are disabled in TGL SDW test, for blocked by TGL i915 issue.

Issue still can be reproduced on TGL RVP in SDW mode when do multiple_pipeline-test stress test.

Test for 500 time, failed at 81th time.

<details>
 <summary>dmesg logger</summary>

````
[ 4179.004624] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 4179.004985] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 4181.506082] intel-sdw sdw-master-0: intel_suspend_runtime start
[ 4181.506164] intel-sdw sdw-master-0: intel_suspend_runtime done
[ 4181.506173] sof-audio-pci 0000:00:1f.3: snd_sof_runtime_idle
[ 4181.506179] sof-audio-pci 0000:00:1f.3: snd_sof_runtime_suspend
[ 4181.506183] sof-audio-pci 0000:00:1f.3: sof_suspend
[ 4181.506731] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[ 4181.563199] sof-audio-pci 0000:00:1f.3: sof_send_pm_ctx_ipc
[ 4181.563219] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 4181.563854] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 4181.563887] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[ 4181.563912] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[ 4181.563917] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 4181.564011] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[ 4181.707229] sof-audio-pci 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[ 4181.707237] sof-audio-pci 0000:00:1f.3: error: failed to reset controller during suspend
[ 4181.707240] sof-audio-pci 0000:00:1f.3: error: failed to power down DSP during suspend -5
[ 4181.707246] sof-audio-pci 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -5)
[ 4183.233546]  SDW0-headphone: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 4183.233581]  Speaker: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 4183.233615]  SSP2-Codec: ASoC: pop wq checking: AIF1 Playback status: inactive waiting: yes


````
</details>
**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: b12acfe
FW: https://github.com/thesofproject/sof/commits/master commit: 5211799
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.


[multipipeline_test_81_dmesg.log](https://github.com/thesofproject/linux/files/3824112/multipipeline_test_81_dmesg.log)

Scripts:
[multiplex_pipeline-test.txt](https://github.com/thesofproject/linux/files/3824139/multiplex_pipeline-test.txt)

**Comment by sinahuang** [comment]
Test the issue with legacy interrupt mode, issue still can be reproduced when doing multiple_pipeline-test stress test.

Test for 500 times, failed at 207th time.
```
[ 2229.230001] sof-audio-pci 0000:00:1f.3: snd_sof_runtime_suspend
[ 2229.230004] sof-audio-pci 0000:00:1f.3: sof_suspend
[ 2229.230842] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[ 2229.287545] sof-audio-pci 0000:00:1f.3: sof_send_pm_ctx_ipc
[ 2229.287564] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 2229.288185] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 2229.288219] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[ 2229.288244] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[ 2229.288250] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 2229.288329] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[ 2229.552576] sof-audio-pci 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[ 2229.552584] sof-audio-pci 0000:00:1f.3: error: failed to reset controller during suspend
[ 2229.552587] sof-audio-pci 0000:00:1f.3: error: failed to power down DSP during suspend -5
[ 2229.552593] sof-audio-pci 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -5)
[ 2231.485913]  Speaker: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 2231.485956]  SSP2-Codec: ASoC: pop wq checking: AIF1 Playback status: inactive waiting: yes
[ 2231.487963]  SDW0-headphone: ASoC: pop wq checking: Playback status: inactive waiting: yes
```

Test recipe

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest commit: 391b5f9
FW: https://github.com/thesofproject/sof/commits/master commit: fb068e6
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[dmesg.log](https://github.com/thesofproject/linux/files/3834430/dmesg.log)

**Comment by sinahuang** [comment]
Test the issue with legacy interrupt mode, issue still can be reproduced when doing multiple_pipeline-test stress test.

Test for 500 times, failed at 205th time.

Scripts:
[multiplex_pipeline-test-tgl.txt](https://github.com/thesofproject/linux/files/3890566/multiplex_pipeline-test-tgl.txt)

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: fb40b85 + PR1451
FW: https://github.com/thesofproject/sof/commits/master commit: 835d876
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[multipipeline_test_205_all_logger.log](https://github.com/thesofproject/linux/files/3840635/multipipeline_test_205_all_logger.log)
[multipipeline_test_205_logger_error.log](https://github.com/thesofproject/linux/files/3840639/multipipeline_test_205_logger_error.log)
[multipipeline_test_205_dmesg.log](https://github.com/thesofproject/linux/files/3840646/multipipeline_test_205_dmesg.log)

**Comment by sinahuang** [comment]
Verified this issue with MSI mode on TGL RVP, issue can't be reproduced when doing multiple_pipeline-test stress test.
I will also check this issue with legacy mode later.

Test for 500 times.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 413de1
FW: https://github.com/thesofproject/sof/commits/master commit: decd206
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

**Comment by sinahuang** [comment]
Verified this issue with legacy mode on TGL RVP, issue still can be reproduced when doing multiple_pipeline-test stress test.

Test for 500 times, failed at 164th time.

Scripts:
[multiplex_pipeline-test-tgl.txt](https://github.com/thesofproject/linux/files/3890570/multiplex_pipeline-test-tgl.txt)


**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 1bb06ec
FW: https://github.com/thesofproject/sof/commits/master commit: f004d11
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[multipipeline_test_164_dmesg.log](https://github.com/thesofproject/linux/files/3850362/multipipeline_test_164_dmesg.log)
[multipipeline_test_164_all_logger.log](https://github.com/thesofproject/linux/files/3850363/multipipeline_test_164_all_logger.log)

**Comment by sinahuang** [comment]
Issue still can be reproduced when doing suspeand & resume without playback stress test , but after occured "error: failed to reset HDA controller gctl 0x1" , dmesg shows "error: ipc timed out for 0x40010000 size 76" error info.

Test for 500 times , failed at 127th time.

**To Reproduce**
1.Boot up system;
2.Run "sudo ./stress_s3.sh 300 1 0";

Scripts:
[stress-s3.txt](https://github.com/thesofproject/linux/files/3895945/stress-s3.txt)


<details>
 <summary>dmesg error log</summary>

````
[ 2173.999533] sof-audio-pci 0000:00:1f.3: sof_send_pm_ctx_ipc
[ 2173.999551] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 2174.000090] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 2174.000122] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[ 2174.000135] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[ 2174.000139] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 2174.000223] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[ 2174.168557] sof-audio-pci 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[ 2174.168564] sof-audio-pci 0000:00:1f.3: error: failed to reset controller during suspend
[ 2174.168567] sof-audio-pci 0000:00:1f.3: error: failed to power down DSP during suspend -5
[ 2174.168573] sof-audio-pci 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -5)
[ 2177.835483] PM: suspend entry (s2idle)
[ 2177.835907] Filesystems sync: 0.000 seconds
[ 2177.836233] Freezing user space processes ... (elapsed 0.002 seconds) done.
[ 2177.838748] OOM killer disabled.
[ 2177.838749] Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
[ 2177.839710] printk: Suspending console(s) (use no_console_suspend to debug)
[ 2177.840162] intel-sdw sdw-master-0: intel_suspend start
[ 2177.840165] intel-sdw sdw-master-0: intel_suspend: pm_runtime status: suspended
[ 2177.856310] sof-audio-pci 0000:00:1f.3: snd_sof_suspend
[ 2177.856312] sof-audio-pci 0000:00:1f.3: sof_suspend
[ 2177.856314] sof-audio-pci 0000:00:1f.3: sof_send_pm_ctx_ipc
[ 2177.856318] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 2178.356899] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
[ 2178.356902] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[ 2178.356919] sof-audio-pci 0000:00:1f.3: unknown ROM status value 01009701
[ 2178.357245] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x001d003c trace 0x00000000
[ 2178.357277] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0x00000000 rirb 00
[ 2178.357278] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 2178.357303] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
[ 2178.357305] sof-audio-pci 0000:00:1f.3: ctx_save ipc error -110, proceeding with suspend
[ 2178.376862] ACPI: EC: interrupt blocked
[ 2185.519498] ACPI: EC: interrupt unblocked
[ 2185.597247] sof-audio-pci 0000:00:1f.3: snd_sof_resume
[ 2185.597249] sof-audio-pci 0000:00:1f.3: sof_resume
[ 2185.597251] sof-audio-pci 0000:00:1f.3: loading firmware
[ 2185.597263] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000002 at  00000048
[ 2185.597268] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[ 2185.597274] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[ 2185.597279] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000004 at  00000044
[ 2185.597279] sof-audio-pci 0000:00:1f.3: booting DSP firmware
[ 2185.597309] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[ 2185.598122] sof-audio-pci 0000:00:1f.3: error: stream reset failed
[ 2185.598123] sof-audio-pci 0000:00:1f.3: error: hdac prepare failed: ffffff92
[ 2185.598130] sof-audio-pci 0000:00:1f.3: error: dma prepare for fw loading err: ffffff92
[ 2185.598130] sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
[ 2185.598131] sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
[ 2185.598135] PM: dpm_run_callback(): pci_pm_resume+0x0/0xa0 returns -110
[ 2185.598136] PM: Device 0000:00:1f.3 failed to resume: error -110
````
</details>


**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: d6078f9
FW: https://github.com/thesofproject/sof/commits/master commit: d740a3e
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[test_127.log](https://github.com/thesofproject/linux/files/3895954/test_127.log)
[s3_test_127_logger_all.log](https://github.com/thesofproject/linux/files/3895956/s3_test_127_logger_all.log)

**Comment by plbossart** [comment]
@sinahuang can you please retest on CML and TGL with a more recent kernel version. Thanks!

**Comment by sinahuang** [comment]
Check this issue on TGL-RVP with soundwire-latest, test for 1000 times original issue cannot be reproduced, so closed it.
**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 121c751
FW: https://github.com/thesofproject/sof/commits/master commit: f587993
Tplg: Same with TGL FW branch : sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode
