### ISSUE TITLE
[Bug][CML]Speaker isn't default sound output source when plug out headset after power off

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1406]
**Describe the bug**
Both speaker and headset are muted when plug out headset after unit power off 

**To Reproduce**
1. Headset is connected
2. In sound setting, select Headphone as output source
4. Power off unit system
5. Plug out headset
6. Boot up system. Go sound setting and alsamixer, find Speaker isn't output souce and is muted
![image](https://user-images.githubusercontent.com/49641224/67912702-b9739680-fbc5-11e9-942f-261799ffdc14.png)
![image](https://user-images.githubusercontent.com/49641224/67912717-c98b7600-fbc5-11e9-88d6-80c04224f3bb.png)

More info:
Seems this is one regression when fixing #1397. 
Error not seen on first UCM in Oct 30th.

**frequency**
100%

**Actual result**

Speaker is't default sound output source. 
To get speaker output: Open sound setting and select output source to recover.

**Expected result**
Speaker should be default sound output source and should be muted.D

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (bae85818b)
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15

Logs are disabled.

**Comment by ClarexZhou** [comment]
Error also seen when disconnect HDMI.
Steps:
1. Both HDMI and headset are connected
2. In sound setting, select HDMI as output source
3. Power off system
4. Disconnect HDMI
5. Boot up system, paplay to check , output still using HDMI.  Expected headphone be used
![image](https://user-images.githubusercontent.com/49641224/67913974-b7133b80-fbc9-11e9-8ab5-918c90054672.png)

**Comment by kv2019i** [comment]
I can reproduce this. It seems when fallback between profiles does not work in PA11.1 (PA in Ubuntu 18.04LTS).

Logs I get are following. Hdmi2 was active, then I power-off, disconnect Hdmi2, and reboot. What follows is situation after boot:

```
Oct 31 10:44:10 rukoilijasirkka pulseaudio[3479]: (   2.220|   0.000) [pulseaudio] device-port.c: Setting port [Out] HDMI2 to status no
Oct 31 10:44:10 rukoilijasirkka pulseaudio[3479]: (   2.220|   0.000) [pulseaudio] alsa-ucm.c: Add port [Out] HDMI2: HDMI2/DP2 Output
Oct 31 10:44:10 rukoilijasirkka pulseaudio[3479]: (   2.220|   0.000) [pulseaudio] alsa-ucm.c: Port [Out] HDMI2 direction output, priority 100
Oct 31 10:44:10 rukoilijasirkka pulseaudio[3479]: (   2.220|   0.000) [pulseaudio] alsa-ucm.c: Adding profile Hdmi2 to port [Out] HDMI2.
```

So status of Hdmi2 is correctly read by PA (it's disconnected), but it still proceeds to route audio to it:

```
Oct 31 10:44:10 rukoilijasirkka pulseaudio[3479]: (   2.231|   0.000) [pulseaudio] alsa-sink.c: Successfully opened device hw:sofsklhdacard,4.
Oct 31 10:44:10 rukoilijasirkka pulseaudio[3479]: (   2.231|   0.000) [pulseaudio] alsa-sink.c: Selected mapping 'HDMI2/DP2 Output' (Hdmi2: hw:sofsklhdacard,4:
 sink).
```

FYI @juimonen

**Comment by kv2019i** [comment]
@juimonen rootcaused this to bug in Pulseaudio 11.x when using UCMs with multiple use-cases. This can be fixed by backporting following patches from Pulseaudio upstream:

33e31b5b70be30a9b59de155aec59807d5f93bc7 card-restore: log the correct profile name
d65974d8501052bafb03e65f5df954511e9949a2 card-restore: don't restore unavailable profiles
0d50e787f86b385bf33aeb53b16ca40543f1db63 alsa-card: improve the profile availability logic

**Comment by ClarexZhou** [comment]
Error not seen on https://github.com/juimonen/alsa-ucm-conf-1/tree/wang_test  UCM and https://github.com/juimonen/alsa-ucm-conf-1/tree/lenovo_test2 UCM

**Comment by ClarexZhou** [comment]
Close for not seen on UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/, commit id 53f931681
