### ISSUE TITLE
[BUG][BYT][I2S]it can not detect the status of headset in amixer contents when  unplug headset 

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1410]
**Describe the bug**
it can not detect the status  of headset in amixer contents when  unplug headset 

**To Reproduce**
1.sudo reboot with headset
2.unplug head set
3.amixer contents
4.check the status of Headphone Jack Switch/Headset Mic Switch
5.the status is still on 

**Reproduction Rate**
5/5
tried 5times can reproduced 5times

**Expected behavior**
the status should be off after unplug headset

**Impact**
plug/unplug  can't detect headset status

Environment
platform: BYT MinnowBoard in I2S mode
Firmware: 59c93383 https://github.com/thesofproject/sof/commits/master
Kernel: f5e70ced https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-byt-rt5682.tplg same as firmware
                                               

<details>
 <summary>Amixercontents</summary>

````
numid=6,iface=MIXER,name='Headphone Jack Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=30,iface=MIXER,name='ADCDAT Mux'
  ; type=ENUMERATED,access=rw------,values=1,items=2
  ; Item #0 'ADCDAT1'
  ; Item #1 'ADCDAT2'
  : values=0
numid=2,iface=MIXER,name='CBJ Boost Volume'
  ; type=INTEGER,access=rw---R--,values=1,min=0,max=8,step=0
  : values=1
  | dBrange-
    rangemin=0,,rangemax=0
      | dBscale-min=0.00dB,step=0.00dB,mute=0
    rangemin=1,,rangemax=1
      | dBscale-min=20.00dB,step=0.00dB,mute=0
    rangemin=2,,rangemax=2
      | dBscale-min=24.00dB,step=0.00dB,mute=0
    rangemin=3,,rangemax=5
      | dBscale-min=30.00dB,step=5.00dB,mute=0
    rangemin=6,,rangemax=6
      | dBscale-min=44.00dB,step=0.00dB,mute=0
    rangemin=7,,rangemax=7
      | dBscale-min=50.00dB,step=0.00dB,mute=0
    rangemin=8,,rangemax=8
      | dBscale-min=52.00dB,step=0.00dB,mute=0

numid=35,iface=MIXER,name='DAC L1 Source'
  ; type=ENUMERATED,access=rw------,values=1,items=2
  ; Item #0 'Stereo1 DAC Mixer'
  ; Item #1 'DAC1'
  : values=1
numid=36,iface=MIXER,name='DAC R1 Source'
  ; type=ENUMERATED,access=rw------,values=1,items=2
  ; Item #0 'Stereo1 DAC Mixer'
  ; Item #1 'DAC1'
  : values=1
numid=32,iface=MIXER,name='DAC1 MIXL DAC1 Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=31,iface=MIXER,name='DAC1 MIXL Stereo ADC Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=34,iface=MIXER,name='DAC1 MIXR DAC1 Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=33,iface=MIXER,name='DAC1 MIXR Stereo ADC Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=1,iface=MIXER,name='DAC1 Playback Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=86,step=0
  : values=73,73
  | dBscale-min=-65.25dB,step=0.75dB,mute=0
numid=41,iface=MIXER,name='HPOL Playback Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=42,iface=MIXER,name='HPOR Playback Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=7,iface=MIXER,name='Headset Mic Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
````
</details>

[dmesg.log](https://github.com/thesofproject/linux/files/3792554/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3792565/logger.log)
[insert.txt](https://github.com/thesofproject/linux/files/3792566/insert.txt)
[uninsert.txt](https://github.com/thesofproject/linux/files/3792567/uninsert.txt)

**Comment by plbossart** [comment]
@bardliao is this a supported functionality, not sure if we have an interrupt line to signal jack detection?

**Comment by bardliao** [comment]
@plbossart @Liviali155 No, I don't know if we connect rt5682's interrupt pin to BYT either. And the other problem is ``4.check the status of Headphone Jack Switch/Headset Mic Switch``. We can't use the status of Headphone Jack Switch/Headset Mic Switch to check if jack is detected or not. The two controls here are mixer controls and not for jack detection.

**Comment by Liviali155** [comment]
> @plbossart @Liviali155 No, I don't know if we connect rt5682's interrupt pin to BYT either. And the other problem is `4.check the status of Headphone Jack Switch/Headset Mic Switch`. We can't use the status of Headphone Jack Switch/Headset Mic Switch to check if jack is detected or not. The two controls here are mixer controls and not for jack detection.

amixer contents > insert.txt  (plug headset)
amixer contents > uninsert.txt (unplug headset)
diff insert.txt uninsert.txt 
it has nothing  difference

**Comment by bardliao** [comment]
> 
> amixer contents > insert.txt (plug headset)
> amixer contents > uninsert.txt (unplug headset)
> diff insert.txt uninsert.txt
> it has nothing difference

@Liviali155 That's what I tried to explain. You can't tell if a jack is plugged or not by amixer control status on BYT + rt5682. The Headphone Jack Switch and Headset Mic Switch are kcontrols. See [sof_controls[]](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_rt5682.c#L310). That is different from [sdw_jack_pins[]](https://github.com/thesofproject/linux/blob/integration/soundwire-latest/sound/soc/intel/boards/sdw_rt711_rt1308_rt715.c#L108)

**Comment by Liviali155** [comment]
sync with bardliao，it has no method to check jack status when plug/unplug headset now ，close it
