### ISSUE TITLE
[BUG][SDW]Need to change JD source JD2 --> JD1 in kernel manually for RVP validation. 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1420]
Now JD source in kernel uses JD2 in default, it's for laptop. For rvp, it needs to change JD2 --> JD1 manually. 

If not modify code manually, some test results as below will be blocked:
https://github.com/thesofproject/linux/issues/1313
https://github.com/thesofproject/linux/issues/1333
https://github.com/thesofproject/linux/issues/1345

if boot up with kernel set JD2, will occur 
1. Boot up with headset connected.
2. Check headphone jack and headset mic jack vlaues --> off.
3. Aplay0,0 via " aplay -Dhw:0,0 -r48000 -c2 -fs16_le test.wav -vv -i " --> headset has sound output.
Check headphone jack and headset mic jack values --> on.
4. Open sound setting , then unplug headset. --> headphone jack and headset mic jack value shows on, headphone option is still in sound setting.
5. Plug in headset again --> headphone option disappeared in sound setting, headphone jack and headset jack values are off. Jack status is opposite of headset hot-plug action.

**Comment by plbossart** [comment]
@bardliao is there a way to do this JD change with controls?
or do we need to implement a quirk? we could e.g. set the RT711 property in the machine driver as done for bytcr_rt5640

**Comment by bardliao** [comment]
> @bardliao is there a way to do this JD change with controls?
> or do we need to implement a quirk? we could e.g. set the RT711 property in the machine driver as done for bytcr_rt5640

@plbossart Sounds good. And we can pass jd_src by snd_soc_component_set_jack()

Edit: On the second though. It is better to use device property than a parameter of  snd_soc_component_set_jack() to pass jd_src since jd_src is HW related and it should not be changed at run time.

**Comment by bardliao** [comment]
@plbossart The PRs are #1427 and #1428.

**Comment by YvonneYang2** [comment]
Test it with integration/soundwire-latest ( 9f1bd5b)+ #1427 + #1428 on icl rvp, issue cannot be reproduced.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b + #1427 + #1428 
FW: https://github.com/thesofproject/sof/commits/master  commit: e5fe2ca
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by plbossart** [comment]
@YvonneYang2 please retry with integration/soundwire-latest, the two PRs were merged. Thanks!

**Comment by YvonneYang2** [comment]
Tested it with latest integration/soundwire-latest branch(085b4bf), issue cannot be reproduced on ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode. 

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 085b4bf 
FW: https://github.com/thesofproject/sof/commits/master commit: 0b7fd03
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by YvonneYang2** [comment]
Close it.
