### ISSUE TITLE
[BUG][BYT][I2S]Alsabat playback test failed

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1421]
**Describe the bug**
Alsabat playback test failed

**To Reproduce**
1.open a terminal:              alsabat -Phw:0,0 -c 2 -r 48000 -f s16_le --standalone -n 240000
2.open another  terminal:  alsabat -Chw:1,0 -c 1 -r 48000 -f s16_le

**Reproduction Rate**
tested twice on CI, all failed
tested manually 5 times,all failed

**Expected behavior**
the return value should be 0 at second terminal

**Impact**
2019-11-01 00:28:40 UTC [REM_INFO]: toplogy file is /lib/firmware/intel/sof-tplg/sof-byt-rt5682.tplg
2019-11-01 00:28:40 UTC [REM_INFO]: device= BYT_MB_RT5682
2019-11-01 00:28:40 UTC [REM_INFO]: platform is byt
2019-11-01 00:28:40 UTC [REM_COMMAND]: alsactl --file alsa_settings/BYT_MB_RT5682.asound.state restore
No state is present for card sofrt5682
Found hardware: "sof-rt5682" "" "" "" ""
Hardware is initialized using a generic method
No state is present for card sofrt5682
2019-11-01 00:28:40 UTC [REM_COMMAND]: alsabat -Phw:0,0 -c 2 -r 48000 -f s16_le --standalone -n 240000
2019-11-01 00:28:41 UTC [REM_COMMAND]: alsabat -Chw:1,0 -c 1 -r 48000 -f s16_le
WARNING: Signal overflow!
 FAIL: Peak freq too high 2991.21 Hz
 FAIL: Peak freq too high 4985.60 Hz
 FAIL: Peak freq too high 6979.25 Hz
 FAIL: Peak freq too high 8973.63 Hz
alsa-utils version 1.1.3

Entering capture thread (ALSA).
Get period size: 3000  buffer size: 24000
Recording ...
Capture completed.

BAT analysis: signal has 65536 frames at 48000 Hz, 1 channels, 2 bytes per sample.

Channel 1 - Checking for target frequency 997.00 Hz
Amplitude: 47117.7; Percentage: [143]
Detected peak at 996.83 Hz of 34.88 dB
 Total 40.2 dB from 985.84 to 1008.54 Hz
 PASS: Peak detected at target frequency
Detected peak at 2991.21 Hz of 30.55 dB
 Total 40.8 dB from 2990.48 to 2991.94 Hz
Detected peak at 4985.60 Hz of 26.87 dB
 Total 41.1 dB from 4984.13 to 4987.06 Hz
Detected peak at 6979.25 Hz of 23.24 dB
 Total 41.3 dB from 6978.52 to 6979.98 Hz
Detected peak at 8973.63 Hz of 20.82 dB
 Total 41.3 dB from 8973.63 to 8973.63 Hz
Detected at least 5 signal(s) in total

Return value is -1003
alsa-utils version 1.1.3

Entering playback thread (ALSA).
Get period size: 2064  buffer size: 16368
Playing generated audio sine wave
Playback completed.

Return value is 0
2019-11-01 00:28:51 UTC [REM_INFO]: === CASE FAILED ===

**Environment**
platform: BYT MinnowBoard with I2S  RT5682
Firmware: fe321d65 https://github.com/thesofproject/sof/commits/master
Kernel: c265f25d https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-byt-rt5682.tplg   
[dmesg.txt](https://github.com/thesofproject/linux/files/3797608/dmesg.txt)
[slogger.txt](https://github.com/thesofproject/linux/files/3797609/slogger.txt)

same as firmware

**Comment by Liviali155** [comment]
Test pass on CI  on 20191105 ，I tested it manually also passed
Kernel:4e76b4a1   https://github.com/thesofproject/linux/commits/topic/sof-dev
Firmware：0b7fd030   https://github.com/thesofproject/sof/commits/master

**Comment by Liviali155** [comment]
test pass on 20191031
f5e70ced:https://github.com/thesofproject/linux/commits/topic/sof-dev
59c93383:https://github.com/thesofproject/sof/commits/master

**Comment by Liviali155** [comment]
error not seen on 20191106, environmemt as below:
Kernel:4e76b4a1 https://github.com/thesofproject/linux/commits/topic/sof-dev
Firmware:9b6ad970 https://github.com/thesofproject/sof/commits/master

**Comment by Liviali155** [comment]
rror not seen on 20191107, environmemt as below:
Kernel:872e5e80 https://github.com/thesofproject/linux/commits/topic/sof-dev
Firmware:7fe0dbd2https://github.com/thesofproject/sof/commits/master

**Comment by wenqingfu** [comment]
this has been confirmed as a CI issue, right? @xiulipan

**Comment by xiulipan** [comment]
@wenqingfu Yes, the alas-mixer setting for codec is not restore right as the card name change.
Now we have update the setting.

**Comment by Liviali155** [comment]
error not seen on 20191108, environmemt as below:
Kernel:872e5e80 https://github.com/thesofproject/linux/commits/topic/sof-dev
Firmware:52117991 https://github.com/thesofproject/sof/commits/master

**Comment by Liviali155** [comment]
Closed for can  not  be reproduced
