### ISSUE TITLE
CML : HDMI not detecting when both ports use non-MST hub

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#1426]
This issue is seen only 1 customer board using the machine driver cml_rt1011_rt5682 machine driver from here:
https://patchwork.kernel.org/patch/11161145/

And not seen with sof_rt5682.c

The issue in details is as below:

Use Chrome device to connect 2 HDMI / DP monitors on 2 type C port using a non-MST hub.
So 1 type C to HDMI cable on 1 side and 1 on the other side.

Expectation is in the UI, we should be able to see both monitors to select as Audio output.
But we see only 1.

When we run evtest, both monitor plug unplug is seen on same jack control ( it should be different)

Kernel , FW & TPLG : cml_drop_007_stable
machine driver as given in link.

UCM used for testing is attached.
[HiFi.conf.txt](https://github.com/thesofproject/linux/files/3799958/HiFi.conf.txt)

**Comment by sathyap-chrome** [comment]
Also 1 more finding : if we use MST hub on any 1 port, the use case works fine.

**Comment by macchian** [comment]
@sathyap-chrome , we also find the same issue on Kohaku. Here is the finding, 

The current Pin mux settings are working on MST hub, but SST(Single Stream Transport).
        cset "name='Pin5-Port0 Mux' 1"
	cset "name='Pin5-Port1 Mux' 2"
	cset "name='Pin5-Port2 Mux' 3"
	cset "name='Pin6-Port0 Mux' 1"
	cset "name='Pin6-Port1 Mux' 2"
	cset "name='Pin6-Port2 Mux' 3"
	cset "name='Pin7-Port0 Mux' 1"
	cset "name='Pin7-Port1 Mux' 2"
	cset "name='Pin7-Port2 Mux' 3"

On the contrast, I modified the Pin mux as below, it works for SST, but MST hub.
	cset "name='Pin5-Port0 Mux' 2"
	cset "name='Pin5-Port1 Mux' 2"
	cset "name='Pin5-Port2 Mux' 2"
	cset "name='Pin6-Port0 Mux' 1"
	cset "name='Pin6-Port1 Mux' 1"
	cset "name='Pin6-Port2 Mux' 1"
	cset "name='Pin7-Port0 Mux' 3"
	cset "name='Pin7-Port1 Mux' 3"
	cset "name='Pin7-Port2 Mux' 3"

We are trying to backport the https://github.com/thesofproject/linux/pull/1155
However, the codebase is far away and conflicted with too many relevance.

Hope someone can point out the key changes for verifying this issue by PR1155?

**Comment by sathyap-chrome** [comment]
Thanks for checking on other platforms too. 
This is surprisingly not seen on hatch platform.

**Comment by plbossart** [comment]
> Thanks for checking on other platforms too.
> This is surprisingly not seen on hatch platform.

There is nothing specific about hatch, it's likely a validation miss...

**Comment by kv2019i** [comment]
> Hope someone can point out the key changes for verifying this issue by PR1155?

We now have PR1155 merged to usptream and we have also backported the core changes (plus one example machine driver) to the 5.0 release branch:
https://github.com/thesofproject/linux/tree/release/sof-v5.0

UCM changes are also merged to ALSA UCM upstream repository.

Let me know if you need help in trying this out.

**Comment by sathyap-chrome** [comment]
Got few suggestions based on Mux and cvt settings currently used.
I've updated the UCM and its undergoing validation - once i've the report, i can close this.

Earlier Mux setting in UCM:

		cset "name='Pin5-Port0 Mux' 1"
		cset "name='Pin5-Port1 Mux' 2"
		cset "name='Pin5-Port2 Mux' 3"
		cset "name='Pin6-Port0 Mux' 1"
		cset "name='Pin6-Port1 Mux' 2"
		cset "name='Pin6-Port2 Mux' 3"
		cset "name='Pin7-Port0 Mux' 1"
		cset "name='Pin7-Port1 Mux' 2"
		cset "name='Pin7-Port2 Mux' 3"

Modified:

		cset "name='Pin5-Port0 Mux' 1"
		cset "name='Pin5-Port1 Mux' 2"
		cset "name='Pin5-Port2 Mux' 3"
		cset "name='Pin6-Port0 Mux' 3"
		cset "name='Pin6-Port1 Mux' 1"
		cset "name='Pin6-Port2 Mux' 2"
		cset "name='Pin7-Port0 Mux' 2"
		cset "name='Pin7-Port1 Mux' 3"
		cset "name='Pin7-Port2 Mux' 1"

**Comment by macchian** [comment]
> Got few suggestions based on Mux and cvt settings currently used.
> I've updated the UCM and its undergoing validation - once i've the report, i can close this.
> 
> Earlier Mux setting in UCM:
> 
> ```
> 	cset "name='Pin5-Port0 Mux' 1"
> 	cset "name='Pin5-Port1 Mux' 2"
> 	cset "name='Pin5-Port2 Mux' 3"
> 	cset "name='Pin6-Port0 Mux' 1"
> 	cset "name='Pin6-Port1 Mux' 2"
> 	cset "name='Pin6-Port2 Mux' 3"
> 	cset "name='Pin7-Port0 Mux' 1"
> 	cset "name='Pin7-Port1 Mux' 2"
> 	cset "name='Pin7-Port2 Mux' 3"
> ```
> 
> Modified:
> 
> ```
> 	cset "name='Pin5-Port0 Mux' 1"
> 	cset "name='Pin5-Port1 Mux' 2"
> 	cset "name='Pin5-Port2 Mux' 3"
> 	cset "name='Pin6-Port0 Mux' 3"
> 	cset "name='Pin6-Port1 Mux' 1"
> 	cset "name='Pin6-Port2 Mux' 2"
> 	cset "name='Pin7-Port0 Mux' 2"
> 	cset "name='Pin7-Port1 Mux' 3"
> 	cset "name='Pin7-Port2 Mux' 1"
> ```

Thanks Sathya. I did a quick test on kahaku and the new mux settings are both working between SST and MST audio separately.

**Comment by sathyap-chrome** [comment]
Validation reports are good. will close this issue.

**Comment by sathyap-chrome** [comment]
[HiFi.conf_helios.txt](https://github.com/thesofproject/linux/files/3817166/HiFi.conf_helios.txt)
[HiFi.conf_kohaku.txt](https://github.com/thesofproject/linux/files/3817167/HiFi.conf_kohaku.txt)

The UCM files used
