### ISSUE TITLE
[BUG]Still need to set pin-port in alsamixer manually

### ISSUE THREAD

**Issue by dengyangchao** [thesofproject/linux#1434]
**Describe the bug**
Since kconfig #15, is only changed for hdaudio-codecs-defconfig, this config will only be used for building HDA kernel. Also need to build  I2S and SDW kernel.

**To Reproduce**
1.Reboot system via "sudo reboot"
2.Open alsamixer 

**frequency**
100%

**Expected result**
No need to set pin-port manually

**Actual result**
Still need to set pin-port manually
![L_E55F tmp](https://user-images.githubusercontent.com/52945407/68189429-33e94f80-ffe6-11e9-8065-3a98b681d80a.PNG)

**Environment**
Firmware: 0b7fd030 https://github.com/thesofproject/sof/commits/master
Kernel:4e76b4a1 https://github.com/thesofproject/linux/commits/topic/sof-dev
Platform:GLK Chrome with onboard DA7219 in I2S mode

**Comment by YvonneYang2** [comment]
Issue can also be reproduced on CML SDW Laptop with ALC711+ ALC1308+ ALC715

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 085b4bf + PR1403
FW: https://github.com/thesofproject/sof/commits/master  commit: 0b7fd03
tplg: same path as FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by xiulipan** [comment]
@YvonneYang2 @kv2019i @dengyangchao Please try to use https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh to generate kconfig for both I2S, HDA and SDW codec test. 
@plbossart Could we share kconfig for all codec paltforms now? Or we still need some separate kconfig for different codec?
 
If you find any issue with the default config, we may need some change or some other modification with kconfig.

**Comment by ClarexZhou** [comment]
Error not seen with kconfig build from https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Close
