### ISSUE TITLE
[BUG][DMIC]The warning of DMIC requested rate is wrong.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1437]
Arecord0,4 rate is requested for 48000 Hz as below: 
```
ubuntu@sh-icl-rvp-hda-001:~$ arecord -Dhw:0,4 --dump-hw-params
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
HW Params of device "hw:0,4":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S16_LE S24_LE S32_LE
SUBFORMAT:  STD
SAMPLE_BITS: [16 32]
FRAME_BITS: [32 64]
CHANNELS: 2
RATE: 48000
PERIOD_TIME: [500 85000]
PERIOD_SIZE: [24 4080]
PERIOD_BYTES: [192 16320]
PERIODS: [2 16]
BUFFER_TIME: [1000 341000]
BUFFER_SIZE: [48 16368]
BUFFER_BYTES: [192 65472]
TICK_TIME: ALL
--------------------
```

But when set arecord0,4 rate 16000 Hz, the warning is wrong. It says requested rate is 16000 rather than 48000 Hz
```
ubuntu@sh-icl-rvp-hda-001:~$ arecord -Dhw:0,4 -fs16_le -c2 -r 16000 -vv -i tmp.wav
Recording WAVE '11.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Stereo
Warning: rate is not accurate (requested = 16000Hz, got = 48000Hz)
         please, try the plug plugin
```

Test recipe: 
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 313bb6e 
FW: https://github.com/thesofproject/sof/commits/master  commit: 9b6ad970
tplg: same path as FW branch,sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
platform: TGL RVP with codec ACL711 in SDW mode, ALC1308 in I2S mode

**Comment by mengdonglin** [comment]
Closed as a fake issue. The warning is correct.
