### ISSUE TITLE
[BUG][SDW] UCM needs to be updated.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1438]
Since using @kv2019i  HDMI module now, ucm on CML SDW Laptop with ALC711+ ALC1308+ ALC715 needs to be updated. 

If using old ucm, will occur :
1. Three HDMI/DP options are always shown in sound setting output source selection even without HDMI/DP external port connected. At the same time, check amixer contents and it shows HDMI/DP is disconnected. 
2. Cannot play HDMI/DP source when selected HDMI/DP option in sound setting.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 313bb6e 
FW: https://github.com/thesofproject/sof/commits/master  commit: 9b6ad970
tplg: same path as FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by plbossart** [comment]
@kv2019i can you help? the suggested UCM file is here: https://github.com/thesofproject/alsa-ucm-conf/blob/master/ucm/sof-sdw-rt711-1308-715/HiFi

**Comment by kv2019i** [comment]
Ack @plbossart and @mengdonglin . I'll upload a patch.

**Comment by plbossart** [comment]
@YvonneYang2 GitHub closed the issue but please double-check on your side.

**Comment by YvonneYang2** [comment]
Checked it with newest https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 , ucm works fine.
