### ISSUE TITLE
[Bug][TGL][SDW] Can't hear audio output when aplay via headset without eDP display.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1439]
**Describe the bug**
Can't heart audio output when aplay via headset and arecord via headset always can't capture any audio. 

Note:Error can't be reproduced if system boot up with eDP display connected.

**To Reproduce**
1.Reboot the system
2.Run"amixer contents | less" to check the "headphone jack" is off.
2.Run "aplay -Dhw:0,0 -fs16_le -c2 -r 48000 -vv -i wav/48California_Dreaming.wav"  -->no audio output
3.Run "alsamixer" to unmute the headphone.
4.Run "aplay -Dhw:0,0 -fs16_le -c2 -r 48000 -vv -i wav/48California_Dreaming.wav"  -->have audio output
5.Run"amixer contents | less" to check the "headphone jack" still is off.

**Frequency**
5/5

**Expected result**
Audio should output normally after reboot 

**Actual result**
No audio output after reboot.
Note: can't recover.

Amixer contents display:
```
numid=10,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=11,iface=CARD,name='Headset Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=12,iface=MIXER,name='Headphone Switch'
  ; type=BOOLEAN,access=rw------,values=1

```
Arecord with headset display:
```
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16368
  period_size  : 4080
  period_time  : 85000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4080
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 16368
  silence_threshold: 0
  silence_size : 0
  boundary     : 9214364837600034816
  appl_ptr     : 0
  hw_ptr       : 0
Max peak (8160 samples): 0x00000000 #                    0%
Max peak (8160 samples): 0x00000000 #                    0%
Max peak (8160 samples): 0x00000000 #                    0%
Max peak (8160 samples): 0x00000000 #                    0%
Max peak (8160 samples): 0x00000000 #                    0%
Max peak (8160 samples): 0x00000000 #                    0%
Max peak (8160 samples): 0x00000000 #                    0%
```

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: 313bb6e
FW: https://github.com/thesofproject/sof/commits/master commit: b5c8f83
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mode and ALC1308 in I2S mode.

**Comment by sinahuang** [comment]
Same behavior with #1333

**Comment by sinahuang** [comment]
Issue still can be reproduced on TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: 391b5f9
FW: https://github.com/thesofproject/sof/commits/master commit: fb068e6
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

**Comment by RanderWang** [comment]
This is caused by JD source.  On TGL RVP, JD1 is used but ACPI reports JD2

**Comment by plbossart** [comment]
@RanderWang what do you mean by "ACPI reports JD2"? We typically have no information on jack detection in DSDT tables? 
Or could it be that we apply the wrong DMI quirk?
Confused on your problem statement

**Comment by sinahuang** [comment]
Verified this issue with legacy mode, issue can't be reproduced.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: fb40b85
FW: https://github.com/thesofproject/sof/commits/master commit: 835d876
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

**Comment by sinahuang** [comment]
Closed it, since cannot be reproduced.
