### ISSUE TITLE
[Bug][CML] ipc timeout when aplay via speaker pipeline on Chromebook

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1441]
**Bug Description**

***sof-dev + cml-008-drop-stable:***
Everytime do playback via speaker pipeline (hw:0,5), there will be io error in terminal, check dmesg, you will see ipc timeout. this seems to be the rt1011 machine driver is not ready to work with sof.
this phenomenon is observed both on ChromeOS and Ubuntu1804.

***keyword_dectect + cml-007-drop-stable:***
Do playback via speaker pipeline (hw:0,5) on Ubuntu1804, there is no sound output, and there is no error in dmesg.  there is sound output on ChromeOS.

**To Reproduce**
run `aplay -Dhw:0,5 -f dat -i -vvv -c 2 ./audio.wav`

**Reproduction Rate**
100%

**Environment**
On sof-dev + cml-008-drop-stable branch:
1. Kernel: 872e5e80
2. SOF: f7dfd05b

On keyword_dectect + cml-007-drop-stable branch
1. kernel: 169c6594
2. SOF: f5dff2940

Tplg: sof-cml-rt1011-rt5682
Platform: CML Chromebook 
OS: ChromeOS & Ubuntu 1804

[helios-speaker-sof-logs.txt](https://github.com/thesofproject/linux/files/3822690/helios-speaker-sof-logs.txt)
[hatch-speaker-sof-log.txt](https://github.com/thesofproject/linux/files/3822691/hatch-speaker-sof-log.txt)

**Comment by keyonjie** [comment]
0      2          DMA         182369944.947917     12677.656250 src/drivers/dw/dma.c:1044               dw_dma_free_data_size() size is 0! Channel enable = 0.
0      2       BUFFER         182369967.135417        22.187500   src/audio/buffer.c:126                comp_update_buffer_produce(), no bytes to produce, source->comp.id = 35, source->comp.type = 5, sink->comp.id = 38, sink->comp.type = 2

Looks the dw dma channel is not enabled! We hit this issue previously, we need to debug why the dai trigger start doesn’t enable the dma channel.

@tlauda the log added previous helps here :) can you chime in?

**Comment by aiChaoSONG** [comment]
Keyon said Machine driver of rt1011 on sof-dev is the same as 007 release, let's move this issue to sof, see [sof issue 2075](https://github.com/thesofproject/sof/issues/2075)
