### ISSUE TITLE
[TGL][BUG]Dmesg shows "ASoC: failed to init link SSP2-Codec: -517" when do module reload.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1447]
**Describe the bug**
Dmesg occured "ASoC: failed to init link SSP2-Codec: -517" when do module reload.

**To Reproduce**
1.Boot up system.
2.Run "sudo ./sof_remove.sh".
3.Waiting for 5s.
4.Run "sudo ./sof_insert.sh"
5.Run "aplay -l" to check, display "no soundcard".

**Frequency**
5/5

**Expected result**
No failed info should display when do module reload. 

**Actual result**
Module reload occured "ASoC: failed to init link SSP2-Codec: -517".

<details>
 <summary>error logger</summary>

````
[   78.355886] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 3721 <= 00c0
[   78.355964] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 3712 <= 0020
[   78.356041] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 3713 <= 0020
[   78.356110] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 371a <= 0020
[   78.356231] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 371b <= 0020
[   78.356413] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7321 83a1 <= a080
[   78.356550] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7321 83a1 <= 9080
[   78.356693] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7308 8388 <= 6080
[   78.356821] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7308 8388 <= 5080
[   78.356971] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7309 8389 <= 6080
[   78.357096] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7309 8389 <= 5080
[   78.357254] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4f12 <= 0091
[   78.357320] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4e12 <= 00d6
[   78.357383] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4d12 <= 0011
[   78.357388] rt711_rt1308 rt711_rt1308: Entry mc_probe
[   78.357399] rt711_rt1308 rt711_rt1308: ASoC: failed to init link SSP2-Codec: -517
[   78.357479] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4c12 <= 0020
[   78.357551] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4f13 <= 0091
[   78.357656] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4e13 <= 00d6
[   78.357756] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4d13 <= 0011
[   78.357840] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4c13 <= 0021
[   78.357906] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4c21 <= 00f0
[   78.357981] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4d21 <= 0011
[   78.358058] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4e21 <= 0011
[   78.358195] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 4f21 <= 0001
[   78.358473] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7520 85a0 7420 84a0 <= 0091 0154
[   78.358806] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7520 85a0 7420 84a0 <= 004a 201b
[   78.359071] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7520 85a0 7420 84a0 <= 0045 5089
[   78.359460] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7520 85a0 7420 84a0 <= 006b 5064
[   78.359735] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7520 85a0 7420 84a0 <= 0048 d249
[   78.359805] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 3501 <= 0003
[   78.359812] rt711 sdw:0:25d:711:0: rt711_io_init hw_init complete



````
</details>

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: 35dd388
FW: https://github.com/thesofproject/sof/commits/master commit: 9844920
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with codec ACL711 in SDW mod, ALC1308 in I2S mode.

[dmesg-20191107.log](https://github.com/thesofproject/linux/files/3819053/dmesg-20191107.log)
[logger1107.log](https://github.com/thesofproject/linux/files/3819054/logger1107.log)

Scripts:
[sof_insert.txt](https://github.com/thesofproject/linux/files/3819064/sof_insert.txt)
[sof_remove.txt](https://github.com/thesofproject/linux/files/3819065/sof_remove.txt)

**Comment by plbossart** [comment]
@sinahuang can you try adding in sof_insert.sh
insert_module snd_soc_rt1308

for now we insert_module snd_soc_rt1308_sdw, but I am not sure this is enough to force the codec to probe again.

**Comment by sinahuang** [comment]
Check this issue after insert_module snd_soc_rt1308 in sof_insert.sh, issue can't be reproduced.
So closed it.

**Comment by sinahuang** [comment]
Verified the issue after insert_module snd_soc_rt1308 in sof_insert.sh, run "aplay -l" can display the devices info, but dmesg still show the error info "ASoC: failed to init link SSP2-Codec: -517".




**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: b12acfe
FW: https://github.com/thesofproject/sof/commits/master commit: 5211799
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with codec ACL711 in SDW mod, ALC1308 in I2S mode.


[dmesg-1108.log](https://github.com/thesofproject/linux/files/3822823/dmesg-1108.log)
[logger-1108.log](https://github.com/thesofproject/linux/files/3822824/logger-1108.log)

**Comment by plbossart** [comment]
#define EPROBE_DEFER      517

This is not a real error, this means the core will retry the probe at a later point. If the probe succeed at a later point we are good.

**Comment by sinahuang** [comment]
Closed it, since it is not a real error.
