### ISSUE TITLE
[BUG][CML]unplug/plug headset during aplay ,sound setting occur Dummy Output

### ISSUE THREAD

**Issue by dengyangchao** [thesofproject/linux#1450]
**Describe the bug**
Unplug/plug headset during aplay sound setting occur Dummy Output, alsamixer shows headphone and speaker muted

**To Reproduce**
1.Reboot system via"sudo reboot"
2.Wait runtime PM to suspended status
3.plug headset and aplay via```aplay -Dhw:0,0 -fs16_le -c2 -r 48000 test.wav -vv -i```
4.unplug/plug headset

**Reproduction Rate**
5/5

**Expected behavior**
unplug headset output change to speaker, plug headset output change to headphone

**Impact**
no sound output and sound setting occur Dummy Output,alsamixer shows headphone and speaker muted

![image](https://user-images.githubusercontent.com/52945407/68447835-5664ae00-021c-11ea-9803-28444e50342a.png)
![image](https://user-images.githubusercontent.com/52945407/68447852-6aa8ab00-021c-11ea-81eb-68fe1a4dbea7.png)

**Environment**
Firmware: https://github.com/thesofproject/sof/commits/cml-hda-dmic-002-drop-stable (0f736283)
Kernel: https://github.com/thesofproject/linux/commits/release/sof-v5.0 (abbc71ca)
Topology: Same as above SOF repo, sof-hda-generic-2ch.tplg rename to sof-hda-generic.tplg
Ucm:https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (3333df89 sof-skl_hda: add priorities to use cases )
Platform: CFL notebook with onboard codec ALC3254 in HDA mode

[amixer.txt](https://github.com/thesofproject/linux/files/3822894/amixer.txt)
[dmesg.log](https://github.com/thesofproject/linux/files/3822895/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3822896/logger.log)

**Comment by ClarexZhou** [comment]
@jajanusz  This issue only occurred when plug/unplug headset during aplay. Error not seen when plug/unplug during paplay or idle.
Issue occurred after separate speaker and headset profile in UCM.

**Comment by juimonen** [comment]
yes I can reproduce. I'm not sure we are able to handle all use cases here from all layers... pulseaudio tries to move the output to card 0 (back to speakers), but it can't open it as it is "Device or resource busy" as we are playing at the same time with aplay to same device... @plbossart @kv2019i asking your advice as better alsa experts: should the access to sof/alsa cards be mutually exclusive?

**Comment by juimonen** [comment]
@jajanusz I think our nicks are resembling each others from far away, but feel free to jump on board :)

**Comment by juimonen** [comment]
so pulseaudio can't understand that "oh someone else is playing to alsa than me, but I should still do routing, but not open the device, just set ucm verbs".

**Comment by kv2019i** [comment]
@juimonen and @dengyangchao I would not classify this as a bug. If you run pulseaudio and any apps that access ALSA devices natively (like aplay in this case), at the same time, all bets are off. Pulseaudio is not designed to handle cases like this and you will get failures.

**Comment by plbossart** [comment]
Agree with @kv2019i 
first this is not an SOF bug,
It's not a scenario we care about and want test results on.
The other question is why you have a Dummy Output in the first place? That should not happen.

**Comment by juimonen** [comment]
@plbossart pulseaudio will always move the playback to dummy output when routing between devices (or profiles), because it takes time to create new output device and old output is just vanishing. You see this in headphone/speaker case because I created separate profiles (use cases) for them. However even if everything would be 1 use case, you would see this between hdmi ->speaker/headphone switch because they are different alsa devices (pulseaudio would anyway create different profiles for them). So if you block the device where pulseaudio is about to route, the routing stays in intermittent "dummy device", as there is no other available output.

**Comment by juimonen** [comment]
should we close this?

**Comment by dengyangchao** [comment]
Not SOF bug, close
