### ISSUE TITLE
[TGL][BUG][Deep]Dmesg shows "error: ipc timed out for 0x40010000 size 76" when doing S3 suspend & resume without playback in stress test.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1453]
**Describe the bug**
Dmesg shows "error: ipc timed out for 0x40010000 size 76" when do suspend & resume without playback stress test.
 Issue occurs when do deep suspend. S2idle suspend can't be tested, because it is blocked by issue #1387 
 

**To Reproduce**
1.Boot up system.
2.Switch to deep suspend mode via "echo deep>/sys/power/mem_sleep"
3.Run "sudo ./stress-s3.sh 100 1 0".

**Frequency**
Test for 100 times,occured at 89th time.

**Expected result**
No error occured when do suspend & resume without playback stress test.

**Actual result**
"Ipc timed out" occured when do do suspend & resume without playback stress test.

<details>
 <summary>error logger</summary>

````
[ 5210.011507] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[ 5210.012696] printk: Suspending console(s) (use no_console_suspend to debug)
[ 5210.012950] intel-sdw sdw-master-0: intel_resume_runtime start
[ 5210.013520] rt711 sdw:0:25d:711:0: sdw_modify_slave_status: initializing completion for Slave 1
[ 5210.013535] intel-sdw sdw-master-0: intel_resume_runtime done
[ 5212.039888] rt711 sdw:0:25d:711:0: Initialization not complete, timed out
[ 5212.039914] intel-sdw sdw-master-0: intel_suspend start
[ 5212.039947] intel-sdw sdw-master-0: intel_suspend done
[ 5212.056911] sof-audio-pci 0000:00:1f.3: snd_sof_suspend
[ 5212.056915] sof-audio-pci 0000:00:1f.3: sof_suspend
[ 5212.056918] sof-audio-pci 0000:00:1f.3: sof_set_hw_params_upon_resume
[ 5212.056921] sof-audio-pci 0000:00:1f.3: sof_send_pm_ctx_ipc
[ 5212.056934] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 5212.559917] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
[ 5212.559920] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[ 5212.559958] sof-audio-pci 0000:00:1f.3: unknown ROM status value 01009701
[ 5212.560262] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x001d003c trace 0x00000000
[ 5212.560315] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0x00000000 rirb 00
[ 5212.560317] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 5212.560355] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
[ 5212.560359] sof-audio-pci 0000:00:1f.3: ctx_save ipc error -110, proceeding with suspend
[ 5212.610612] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1d003c timedout
[ 5212.610616] sof-audio-pci 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[ 5212.610618] sof-audio-pci 0000:00:1f.3: error: dsp core reset failed: core_mask 1
[ 5212.610620] sof-audio-pci 0000:00:1f.3: error: failed to power down core during suspend
[ 5212.610621] sof-audio-pci 0000:00:1f.3: error: suspending dsp
[ 5212.610624] sof-audio-pci 0000:00:1f.3: error: failed to power down DSP during suspend -110
[ 5212.610635] PM: pci_pm_suspend(): snd_sof_suspend+0x0/0x100 [snd_sof] returns -110
[ 5212.610641] PM: dpm_run_callback(): pci_pm_suspend+0x0/0x140 returns -110
[ 5212.610645] PM: Device 0000:00:1f.3 failed to suspend: error -110
[ 5212.610649] PM: Some devices failed to suspend, or early wake event detected
[ 5212.611182] serial 00:03: activated
[ 5212.612772] intel-sdw sdw-master-0: intel_resume start
[ 5212.613358] intel-sdw sdw-master-0: intel_resume done
[ 5212.827493] nvme nvme0: 8/0/0 default/read/poll queues
[ 5212.839842] atkbd serio0: Failed to deactivate keyboard on isa0060/serio0
[ 5213.223869] atkbd serio0: Failed to enable keyboard on isa0060/serio0
[ 5214.663899] rt711 sdw:0:25d:711:0: Initialization not complete, timed out
[ 5214.663909] PM: dpm_run_callback(): rt711_dev_resume+0x0/0x90 [snd_soc_rt711] returns -110
[ 5214.663913] PM: Device sdw:0:25d:711:0 failed to resume: error -110
[ 5214.663926] rt711_rt1308 rt711_rt1308: ASoC: Scheduling resume work
[ 5214.663934] rt711_rt1308 rt711_rt1308: ASoC: starting resume work
[ 5214.665425] acpi LNXPOWER:0b: Turning OFF
[ 5214.676764] acpi LNXPOWER:07: Turning OFF
[ 5214.679179] rt711_rt1308 rt711_rt1308: ASoC: resume work completed

````
</details>

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: b12acfe
FW: https://github.com/thesofproject/sof/commits/master commit: 5211799
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[s3_test_89_logger_all.log](https://github.com/thesofproject/linux/files/3823392/s3_test_89_logger_all.log)
[test_89.log](https://github.com/thesofproject/linux/files/3823393/test_89.log)

Scripts:
[stress-s3.txt](https://github.com/thesofproject/linux/files/3823394/stress-s3.txt)

**Comment by plbossart** [comment]
@sinahuang please retest with s2idle first, this should work now.

**Comment by sinahuang** [comment]
Test the issue with legacy interrupt mode, issue can't be reproduced.

Test for 500 times.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: 391b5f9
FW: https://github.com/thesofproject/sof/commits/master commit: fb068e6
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

**Comment by sinahuang** [comment]
Verified this issue with MSI mode, issue can't be reproduced, so closed it.

Test for 300 times.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/integration/soundwire-latest   commit: 2933f73
FW: https://github.com/thesofproject/sof/commits/master commit: d1dcdfe
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.
