### ISSUE TITLE
[BUG][SDW]Aplay0,0(RT711) has no sound output after waking up from deep s3

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1462]
**Describe the bug**
 Aplay0,0(RT711) has no sound output but console shows it's still running after waking up from deep suspend.  Or arecord0,1 (RT711) capture empty audio after waking up from deep s3

**To Reproduce**
1. Boot up, then switch to deep suspend mode via "sudo echo deep > /sys/power/mem_sleep"
2. Aplay0,0(RT711) via "aplay -Dhw:0,0 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i"
3. sudo rtcwake -m mem -s 10

 
**Reproduced rate**
100%
Terminate it, and aplay0,0 again can recover the issue.

**Expected result**
Aplay0,,0 (RT711) output normally after waking up from deep s3

**Actual result**
Aplay0,,0 (RT711) has no sound output after waking up from deep s3

dmesg when do aplay0,0
```
[  137.759336] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: start
[  137.759339] sdw_enable_stream: SDW0 Pin2-Playback: start
[  137.761954] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0001
[  137.762614] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0001
[  137.762617] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=6000000
[  137.764091] sdw_enable_stream: SDW0 Pin2-Playback: done
[  137.764095] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: done
[  137.764099]  Headphone: ASoC: post trigger FE Headphone cmd 1
[  137.764103] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 1
[  137.765224] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[  137.765227] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  137.765390] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  137.808735] PM: suspend exit
[  137.817041] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  137.817061] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  138.317038] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  138.317068] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  140.352594] intel-sdw sdw-master-1: intel_suspend_runtime start
[  140.352661] intel-sdw sdw-master-1: intel_suspend_runtime done
[  140.352665] intel-sdw sdw-master-3: intel_suspend_runtime start
```
Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 391b5f9c 
FW: https://github.com/thesofproject/sof/commits/master  commit: fb068e6a
tplg: same path as FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715 

Logs:
[error_logger.log](https://github.com/thesofproject/linux/files/3830165/error_logger.log)
[logger.log](https://github.com/thesofproject/linux/files/3830166/logger.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3830167/dmesg.log)

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced after close the TPM2.0 in BOIS setting. So close the bug.

**Comment by YvonneYang2** [comment]
Checked it on RT1308, issue cannot be reproduced. Seems issue only reproduce on RT711. Codec logs as below:

[register_fail.txt](https://github.com/thesofproject/linux/files/3830824/register_fail.txt)
[register_ok.txt](https://github.com/thesofproject/linux/files/3830825/register_ok.txt)

**Comment by plbossart** [comment]
@YvonneYang2  @mengdonglin integration/soundwire-latest now has all the known fixes for suspend/resume please retry (along with the latest firmware)

I tested with rtcwake mem/freeze and no issues seen on my side

**Comment by YvonneYang2** [comment]
There are two CML laptops on my side, only one laptop can reproduce the issue. The reproduced HW was just received and set up yesterday.  
 
Tested it with legacy and MSI mode , issue can be reproduced on both mode.

**Comment by bardliao** [comment]
I checked the dmesg.log and didn't find anything wrong. It indeed do cache sync after resume. According to @shumingfan , the codec registers dump shows jack is plugged out. I don't know if we need to redo jack detection after resume in some cases. Note that we didn't do rt711_io_init in this case. We call sdw_modify_slave_status() in [sdw_clear_slave_status()](https://github.com/thesofproject/linux/blob/integration/soundwire-latest/drivers/soundwire/bus.c#L1194), but we doesn't call sdw_update_slave_status(). So rt711_update_status() is not triggered in this case. @shumingfan Do you have any comment?

**Comment by shumingfan** [comment]
@YvonneYang2  Could you dump the registers again by cache_bypass mode when the issue happened?
To enable cache_bypass:
$ sudo -i  // change to root
$ echo 1 > /sys/kernel/debug/regmap/sdw\:0\:25d\:711\:0/cache_bypass
$ cat /sys/kernel/debug/regmap/sdw\:0\:25d\:711\:0/registers

**Comment by bardliao** [comment]
@shumingfan I can reproduce the issue on my side now. There is no output from headphone after deep suspend mode. But the sound comes out right after when I cat  /sys/kernel/debug/regmap/sdw:0:25d:711:0/registers. Is there any register need to be toggled?

**Comment by shumingfan** [comment]
@YvonneYang2  Please update #1475 . This PR should fix this issue.

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced with latest integration/soundwire-latest + #1475 

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: fb40b85 + #1475 
FW: https://github.com/thesofproject/sof/commits/master  commit: 835d876
tplg: same path as FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced after #1475 is merged.  Close it.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit:  413de1e 
FW: https://github.com/thesofproject/sof/commits/master  commit: decd206
tplg: same path as FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715
