### ISSUE TITLE
[TGL] HDMI jack detection not working

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1464]
HDMI monitor jack status detection is not working on TGL.

FYI  @xiulipan

**Comment by kv2019i** [comment]
By switching to common HDMI codec driver and with following patch, jack detection works as expected:
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-November/158328.html

**Comment by xiulipan** [comment]
@kv2019i With hdac_hdmi and eDP connected the jack dection is working.
I will cherry-pick the patches to test.

PS: could you test with/without eDP? To us it will show different result.

@Bin-QA Could you test this later?

**Comment by kv2019i** [comment]
WIth following patches, jack detection now works with SOF and legacy drivers and the common HDMI codec:

ALSA: hda: hdmi - fix port numbering for ICL and TGL platforms  
https://patchwork.kernel.org/patch/11246315/
ALSA: hda: hdmi - fix pin setup on Tigerlake
https://patchwork.kernel.org/patch/11237009/
ALSA: hda: hdmi - add Tigerlake support
https://patchwork.kernel.org/patch/11228249/

@Bin-QA Can you verify? If ok, issue can be closed.

**Comment by kv2019i** [comment]
I verified this, closing. Please reopen if still seen.
