### ISSUE TITLE
[BUG][SDW]"Program transport params failed: -22" occured during multipipline stress test.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1494]
**Describe the bug**
"Program transport params failed: -22" occured during multipipline stress test, but aplay function will not be effected.

Issue can be reproduced with MSI interrupt mode and legacy interrupt mode.

**To Reproduce**
1.Boot up system;
2.Run "./multiplex_pipeline-test.sh pcm0p pcm2p pcm1c pcm3c pcm4c";

Scripts:
[multiplex_pipeline-test.txt](https://github.com/thesofproject/linux/files/3849852/multiplex_pipeline-test.txt)

**Reproduce rate**
1st try: 16/100;
2nd try:12/100;

**Expected result**
Multipipline works normally. 

**Actual result**
"Program transport params failed: -22" occured during multipipline stress test.

<details>
 <summary>dmesg </summary>

````
[  501.586917] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: start
[  501.586953] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  501.587056] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  501.587069] sof-audio-pci 0000:00:1f.3: nothing to do in IPC IRQ thread
[  501.587230] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0003
[  501.587288] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0003
[  501.587291] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=4800000
[  501.587293] intel-sdw sdw-master-0: Program transport params failed: -22
[  501.587298] intel-sdw sdw-master-0: Program params failed: -22
[  501.587303] sdw_enable_stream: SDW0 Pin2-Playback: done
[  501.587307] intel-sdw sdw-master-0: intel_trigger trigger 1 failed: -22
[  501.587308] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: done
[  501.587311] intel-sdw sdw-master-0: Update DAI routes for SDW0 Pin3 capture
[  501.587315] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: done
[  501.587317]  SDW0-mics: ASoC: hw_params FE SDW0-mics rate 48000 chan 2 fmt 2
[  501.587320] sof-audio-pci 0000:00:1f.3: Update DAI routes for SDW0-mics 1 capture
[  501.587322]  SDW0-Playback: ASoC: trigger BE failed -22
[  501.587324] sof-audio-pci 0000:00:1f.3: Connecting DAI route PCM1C -> Passthrough Capture 1
[  501.587326] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 1 dir 1
[  501.587329]  SDW0-headphone: ASoC: trigger FE cmd: 1 failed: -22
[  501.587332] sof-audio-pci 0000:00:1f.3: generating page table for 000000002e0a4024 size 0xffc0 pages 16
[  501.587336]  SDW0-headphone: ASoC: pre trigger FE SDW0-headphone cmd 0
[  501.587340] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  501.587342] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  501.587345] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  501.587373] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  501.587376] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[  501.587377] sof-audio-pci 0000:00:1f.3: periods:4

````
</details>

sof error trace:
```
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1           SA         992692582.656250 992692608.000000      src/lib/agent.c:55  	validate(), ll drift detected, delta = 41475
    0      1           SA         992710650.416667     18067.759766      src/lib/agent.c:55  	validate(), ll drift detected, delta = 40411
    0      1           SA         992712786.822917      2136.406250      src/lib/agent.c:55  	validate(), ll drift detected, delta = 41022
    0      1           SA         992714910.937500      2124.114502      src/lib/agent.c:55  	validate(), ll drift detected, delta = 40780
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 1bb06ec
FW: https://github.com/thesofproject/sof/commits/master commit: decd206
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[multipipeline_test_40_dmesg.log](https://github.com/thesofproject/linux/files/3849855/multipipeline_test_40_dmesg.log)
[multipipeline_test_40_all_logger.log](https://github.com/thesofproject/linux/files/3849857/multipipeline_test_40_all_logger.log)
[multipipeline_test_40_error_logger.log](https://github.com/thesofproject/linux/files/3849858/multipipeline_test_40_error_logger.log)

**Comment by sinahuang** [comment]
Issue still can be reproduced on TGL RVP, issue first occured at 66th time.

Reproduce rate:  65/500

sof_error_trace log:
```
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1           SA         1533810371.093750              nan      src/lib/agent.c:55  	validate(), ll drift detected, delta = 40532
    0      1           SA         1533982535.364583    172164.265625      src/lib/agent.c:55  	validate(), ll drift detected, delta = 41426
    0      1           SA         1533984695.364583      2160.000000      src/lib/agent.c:55  	validate(), ll drift detected, delta = 41469
```

Dmesg log:
```
[  501.586917] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: start
[  501.586953] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  501.587056] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  501.587069] sof-audio-pci 0000:00:1f.3: nothing to do in IPC IRQ thread
[  501.587230] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0003
[  501.587288] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0003
[  501.587291] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=4800000
[  501.587293] intel-sdw sdw-master-0: Program transport params failed: -22
[  501.587298] intel-sdw sdw-master-0: Program params failed: -22
[  501.587303] sdw_enable_stream: SDW0 Pin2-Playback: done
[  501.587307] intel-sdw sdw-master-0: intel_trigger trigger 1 failed: -22
[  501.587308] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: done
[  501.587311] intel-sdw sdw-master-0: Update DAI routes for SDW0 Pin3 capture
[  501.587315] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: done
[  501.587317]  SDW0-mics: ASoC: hw_params FE SDW0-mics rate 48000 chan 2 fmt 2
[  501.587320] sof-audio-pci 0000:00:1f.3: Update DAI routes for SDW0-mics 1 capture
[  501.587322]  SDW0-Playback: ASoC: trigger BE failed -22
[  501.587324] sof-audio-pci 0000:00:1f.3: Connecting DAI route PCM1C -> Passthrough Capture 1
[  501.587326] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 1 dir 1
[  501.587329]  SDW0-headphone: ASoC: trigger FE cmd: 1 failed: -22
[  501.587332] sof-audio-pci 0000:00:1f.3: generating page table for 000000002e0a4024 size 0xffc0 pages 16
[  501.587336]  SDW0-headphone: ASoC: pre trigger FE SDW0-headphone cmd 0
[  501.587340] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  501.587342] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  501.587345] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  501.587373] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  501.587376] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[  501.587377] sof-audio-pci 0000:00:1f.3: periods:4


```

 **Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 246ab27
FW: https://github.com/thesofproject/sof/commits/master commit: 655d077
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.


[66th log.zip](https://github.com/thesofproject/linux/files/3857963/66th.log.zip)

**Comment by YvonneYang2** [comment]
Run multi-pipline stress test, issue can be reproduced on integration/soundwire-latest(b4f9bfa) + #1580 with sof-pci-debug=1 and sdw_md_flags=0x01000001. 
Platforms: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

When issue reproduced, terminate it then start again can recover it. 
 
[multipipeline_test_22_all_logger.log](https://github.com/thesofproject/linux/files/3920241/multipipeline_test_22_all_logger.log)
[multipipeline_test_22_dmesg.log](https://github.com/thesofproject/linux/files/3920242/multipipeline_test_22_dmesg.log)

**Comment by YvonneYang2** [comment]
With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1 for not allowed, run multi-pipline stress test 500 times, issue can be reproduced at 291th/292th/293th/294th/295th time. Terminate it and restart again can recover the issue.

dmesg 
```
[ 3184.269543] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[ 3184.269712] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0001
[ 3184.269753] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0001
[ 3184.269754] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=6000000
[ 3184.269755] intel-sdw sdw-master-0: Program transport params failed: -22
[ 3184.269756] intel-sdw sdw-master-0: Program params failed: -22
[ 3184.269758] sdw_enable_stream: SDW0 Pin2-Playback: done
[ 3184.269759] intel-sdw sdw-master-0: intel_trigger trigger 1 failed: -22
[ 3184.269760] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: done
[ 3184.269761] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: done
[ 3184.269763] intel-sdw sdw-master-0: Update DAI routes for SDW0 Pin3 capture
[ 3184.269764]  SDW0-Playback: ASoC: trigger BE failed -22
[ 3184.269764]  Headset mic: ASoC: hw_params FE Headset mic rate 48000 chan 2 fmt 2
[ 3184.269766]  Headphone: ASoC: trigger FE cmd: 1 failed: -22
[ 3184.269766] sof-audio-pci 0000:00:1f.3: Update DAI routes for Headset mic 1 capture
[ 3184.269767] sof-audio-pci 0000:00:1f.3: Connecting DAI route PCM1C -> Passthrough Capture 1
```

[multipipeline_test_291_all_logger.log](https://github.com/thesofproject/linux/files/3938077/multipipeline_test_291_all_logger.log)
[multipipeline_test_291_dmesg.log](https://github.com/thesofproject/linux/files/3938078/multipipeline_test_291_dmesg.log)



Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: b036eac + #1586
FW: https://github.com/thesofproject/sof/commits/master  commit: 65de27d
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

**Comment by YvonneYang2** [comment]
With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1 for not allowed, run multi-pipline stress test 500 times, issue cannot be reproduced. 

kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: e375909+ PR1586
FW: https://github.com/thesofproject/sof/commits/master  commit: 8f51e6b
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

**Comment by sinahuang** [comment]
With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1,now issue cannot be reproduced on CML-U Laptop and CML-H Laptop, but TGL-RVP can still reproduce this issue during multipipline stress test.

[multipipeline_test_138_dmesg.log](https://github.com/thesofproject/linux/files/3944377/multipipeline_test_138_dmesg.log)
[multipipeline_test_138_all_logger.log](https://github.com/thesofproject/linux/files/3944378/multipipeline_test_138_all_logger.log)
[multipipeline_test_138_logger_error.log](https://github.com/thesofproject/linux/files/3944379/multipipeline_test_138_logger_error.log)

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: e375909 +PR #1586
FW: https://github.com/thesofproject/sof/commits/master commit: 8f51e6b
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg

**Comment by YvonneYang2** [comment]
> With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1 for not allowed, run multi-pipline stress test 500 times, issue cannot be reproduced.
> 
> kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: [e375909](https://github.com/thesofproject/linux/commit/e37590970601495e64b8a2cff82c00fb49ca03a4)+ PR1586
> FW: https://github.com/thesofproject/sof/commits/master commit: 8f51e6b
> tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
> platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

Run 1000 times again with same environment , issue can still be reproduced. Reproduced rate is about 5/1000 

[multipipeline_test_320_dmesg.log](https://github.com/thesofproject/linux/files/3948090/multipipeline_test_320_dmesg.log)
[multipipeline_test_320_all_logger.zip](https://github.com/thesofproject/linux/files/3948091/multipipeline_test_320_all_logger.zip)

**Comment by plbossart** [comment]
@YvonneYang2 can you retry with integration/soundwire-latest 121c7512e56b9f4e01c71d772d5436b8adda555e

I added a set of traces to figure out what the -22 (-EINVAL) return value might come from.

**Comment by YvonneYang2** [comment]
Issue can be reproduced with option 0x0, run 300 times, failed at 287th time.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 121c751 
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: 5e5f69e 
tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

[multipipeline_test_287_dmesg.log](https://github.com/thesofproject/linux/files/3981850/multipipeline_test_287_dmesg.log)
[multipipeline_test_287_logger_error.log](https://github.com/thesofproject/linux/files/3981851/multipipeline_test_287_logger_error.log)
[multipipeline_test_287_all_logger.log](https://github.com/thesofproject/linux/files/3981852/multipipeline_test_287_all_logger.log)

**Comment by plbossart** [comment]
Thanks @YvonneYang2 the traces do show what happens:

````
[ 3159.832414] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=6000000
[ 3159.832419] rt711 sdw:0:25d:711:0: invalid dpn_prop direction 1 port_num 0 <<<<
[ 3159.832424] sdw_program_slave_port_params failed -22
[ 3159.832429] intel-sdw sdw-master-0: Program transport params failed: -22
[ 3159.832433] intel-sdw sdw-master-0: Program params failed: -22
````

something is clearly wrong, we should not be using port 0, so there's bad code somewhere...

**Comment by plbossart** [comment]
I can reproduce this error on a CML laptop with a single amp with https://github.com/thesofproject/linux/pull/1640 73faa6b7a08d5bec342f49c49ac24c2a32d3d2db

with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8

this happens at the 3rd stress test so quite easy to see

**Comment by sinahuang** [comment]
With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8, issue still can be reproduced on TGL-U.

Run 500 times, failed at 6th time.

Dmesg:

```
[  408.284531] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: start
[  408.284546] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  408.284635] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  408.284799] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0003
[  408.284877] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0003
[  408.284878] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=4800000
[  408.284879] rt711 sdw:0:25d:711:0: invalid dpn_prop direction 1 port_num 0
[  408.284881] sdw_program_slave_port_params failed -22
[  408.284882] intel-sdw sdw-master-0: Program transport params failed: -22
[  408.284883] intel-sdw sdw-master-0: Program params failed: -22
[  408.284884] sdw_enable_stream: SDW0 Pin2-Playback: done
[  408.284886] intel-sdw sdw-master-0: intel_trigger trigger 1 failed: -22
[  408.284886] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: done
[  408.284887]  SDW0-Playback: ASoC: trigger BE failed -22
[  408.284888] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: done
[  408.284889] intel-sdw sdw-master-0: Update DAI routes for SDW0 Pin3 capture
[  408.284890]  SDW0-headphone: ASoC: trigger FE cmd: 1 failed: -22
[  408.284891]  SDW0-mics: ASoC: hw_params FE SDW0-mics rate 48000 chan 2 fmt 2
[  408.284893] sof-audio-pci 0000:00:1f.3: Update DAI routes for SDW0-mics 1 captur

```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 121c751
FW: https://github.com/thesofproject/sof/commits/master commit: f587993
Tplg: Same with TGL FW branch : sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode


[6th.zip](https://github.com/thesofproject/linux/files/3986679/6th.zip)

**Comment by bardliao** [comment]
I suspect that the issue is somehow sdw_program_slave_port_params() is called between sdw_port_alloc() and sdw_compute_slave_ports(). @sinahuang @YvonneYang2 Could you apply 
[0001-TEST-soundwire-add-trace-for-invalid-port-number.patch.txt](https://github.com/thesofproject/linux/files/3994140/0001-TEST-soundwire-add-trace-for-invalid-port-number.patch.txt) and test it?

**Comment by sinahuang** [comment]
Checked this issue on TGL-U RVP and CML-U Laptop after applying [0001-TEST-soundwire-add-trace-for-invalid-port-number.patch.txt](https://github.com/thesofproject/linux/files/3994140/0001-TEST-soundwire-add-trace-for-invalid-port-number.patch.txt) in soudnwire-latest(commit:121c751), issue still can be reproduced.

Verified with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8 on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode, test for 500 times , failed 121 times
dmesg :
```
  363.179599] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  363.179746] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0003
[  363.179804] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0003
[  363.179804] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=4800000
[  363.179806] rt711 sdw:0:25d:711:0: bard: sdw_program_slave_port_params p_rt->num != t_params->port_num t_params->port_num 0 p_rt->num 3
[  363.179807] rt711 sdw:0:25d:711:0: invalid dpn_prop direction 0 port_num 0
[  363.179808] sdw_program_slave_port_params failed -22
[  363.179809] intel-sdw sdw-master-0: Program transport params failed: -22
[  363.179810] intel-sdw sdw-master-0: Program params failed: -22
[  363.179813] sdw_enable_stream: SDW0 Pin3-Capture: done
[  363.179814] intel-sdw sdw-master-0: intel_trigger trigger 1 failed: -22
[  363.179815] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin3: done
[  363.179816]  SDW0-Capture: ASoC: trigger BE failed -22
[  363.179817]  SDW0-mics: ASoC: trigger FE cmd: 1 failed: -22
[  363.179818]  SDW0-mics: ASoC: pre trigger FE SDW0-mics cmd 0
[  363.179819] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 1 dir 1 cmd 0
[  363.179821] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  363.179853] intel-sdw sdw-master-0: bard: sdw_port_alloc p_rt->num = 2
[  363.179856] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin2: done
[  363.179858] intel-sdw sdw-master-0: Update DAI routes for SDW0 Pin2 playback
[  363.179861]  SDW0-headphone: ASoC: hw_params FE SDW0-headphone rate 48000 chan 2 fmt 2
[  363.179862] sof-audio-pci 0000:00:1f.3: Update DAI routes for SDW0-headphone 0 playback
```

[multipipeline_test_22_dmesg.log](https://github.com/thesofproject/linux/files/3997363/multipipeline_test_22_dmesg.log)
[multipipeline_test_22_logger_error.log](https://github.com/thesofproject/linux/files/3997364/multipipeline_test_22_logger_error.log)


Verified with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1 on CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode.test  for 500 times, failed 5 times.

dmesg:
```
[ 6377.988069] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=6000000
[ 6377.988074] rt711 sdw:0:25d:711:0: bard: sdw_program_slave_port_params p_rt->num != t_params->port_num t_params->port_num 0 p_rt->num 4
[ 6377.988078] rt711 sdw:0:25d:711:0: invalid dpn_prop direction 1 port_num 0
[ 6377.988081] sdw_program_slave_port_params failed -22
[ 6377.988085] intel-sdw sdw-master-0: Program transport params failed: -22
[ 6377.988088] intel-sdw sdw-master-0: Program params failed: -22
[ 6377.988094] sdw_enable_stream: SDW0 Pin2-Playback: done
[ 6377.988098] intel-sdw sdw-master-0: intel_trigger trigger 1 failed: -22
[ 6377.988102] intel-sdw sdw-master-0: bard: sdw_port_alloc p_rt->num = 3
[ 6377.988106] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin3: done
[ 6377.988108] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin2: done
[ 6377.988112]  SDW0-Playback: ASoC: trigger BE failed -22
[ 6377.988116]  Headphone: ASoC: trigger FE cmd: 1 failed: -22
[ 6377.988119]  Headphone: ASoC: pre trigger FE Headphone cmd 0
[ 6377.988124] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[ 6377.988127] intel-sdw sdw-master-0: Update DAI routes for SDW0 Pin3 capture
[ 6377.988133]  Headset mic: ASoC: hw_params FE Headset mic rate 48000 chan 2 fmt 2
[ 6377.988136] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
```
[multipipeline_test_363_all_logger.log](https://github.com/thesofproject/linux/files/3997382/multipipeline_test_363_all_logger.log)
[multipipeline_test_363_dmesg.log](https://github.com/thesofproject/linux/files/3997383/multipipeline_test_363_dmesg.log)
[multipipeline_test_363_logger_error.log](https://github.com/thesofproject/linux/files/3997384/multipipeline_test_363_logger_error.log)

**Comment by bardliao** [comment]
Thanks @sinahuang the trace do show  sdw_program_slave_port_params() is called between sdw_port_alloc() and sdw_compute_slave_ports(). 
```
[  363.178329] rt711 sdw:0:25d:711:0: rt711_pcm_hw_params rt711-aif1
[  363.178331] rt711 sdw:0:25d:711:0: bard: sdw_port_alloc p_rt->num = 3 <<<
[  363.178353]  SDW0-Capture: ASoC: trigger BE SDW0-Capture cmd 1
[  363.178354] intel-sdw sdw-master-0: intel_trigger: SDW0 Pin3: start
[  363.178499] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7203 8283 <= 0041
[  363.178907] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7209 8289 <= 0041
[  363.179374] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7208 8288 <= 0041
[  363.179375] rt711 sdw:0:25d:711:0: Update DAI routes for rt711-aif1 playback
[  363.179376] rt711 sdw:0:25d:711:0: Connecting DAI route DP3 Playback -> DP3RX
[  363.179378] intel-sdw sdw-master-0: intel_hw_params: SDW0 Pin2: start
[  363.179405] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  363.179599] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  363.179746] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00e0 <= 0003
[  363.179804] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 00f0 <= 0003
[  363.179804] rt711 sdw:0:25d:711:0: rt711_clock_config complete, clk_freq=4800000
[  363.179806] rt711 sdw:0:25d:711:0: bard: sdw_program_slave_port_params p_rt->num != t_params->port_num t_params->port_num 0 p_rt->num 3 <<<
[  363.179807] rt711 sdw:0:25d:711:0: invalid dpn_prop direction 0 port_num 0
[  363.179808] sdw_program_slave_port_params failed -22
```

**Comment by YvonneYang2** [comment]
Tested it 1000 times, issue cannot be reproduced with latest integration/soundwire-latest(https://github.com/thesofproject/linux/commit/121c7512e56b9f4e01c71d772d5436b8adda555e) + #1640 + #1654

**Comment by YvonneYang2** [comment]
Tested it 1000 times on CML-U sdw laptop DVT2,  issue cannot be reproduced with latest integration/soundwire-latest + #1665.

**Comment by sinahuang** [comment]
Tested it 1000 times on CML-H/TGL-U sdw laptop with integration/soundwire-latest(commit:07348fa), issue cannot be reproduced, so closed it.
