### ISSUE TITLE
[BUG][BYT][I2S]Aplay/arecord  via headset only have pop noise 

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1507]
**Describe the bug**
Aplay/arecord occured pop noise   after sudo reboot then insert headset

Error not seen if boot up system with headset connected

**To Reproduce**
1."sudo reboot "without headset
2.insert headset
3.aplay -Dhw:0,1 -fS16_LE -c2 -r 16000 star0.wav  -vv -i
or
   aplay -Dhw:0,0 -fS16_LE -c2 -r 16000 star0.wav  -vv -i
   
```****List of PLAYBACK Hardware Devices ****
card 0: sofrt5682 [sof-rt5682], device 0: Low Latency (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 1: Media Playback 1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
**Reproduction Rate**
10/10
**Expected behavior**
Aplay and arecord normally after sudo reboot without headset

**Impact**
Only pop noise output when aplay
Using "arecord -Dhw:0,0 -r48000 -c2 -fs16_le s30.wav -vvv -i" to record a audio file the progress display normal ,but when  play  the recorded file, just noise output
After "sudo reboot" with headset,it can  aplay and arecord normally

**Environment**
Platform: BYT MB  with I2S  RT5682
Firmware:  655d077f  https://github.com/thesofproject/sof/commits/master
Kernel:  fd302303https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-byt-rt5682.tplg same as firmware

[sof_trace.log](https://github.com/thesofproject/linux/files/3857037/sof_trace.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3857038/dmesg.log)
[arecordfile.zip](https://github.com/thesofproject/linux/files/3857042/arecordfile.zip)

**Comment by bardliao** [comment]
It seems to be a jack detection issue.  To get jack detection work, you have to connect rt5682 irq pin to BYT's irq pin. Also, you have to add a proper GopiInt information to rt5682's asl file.
Something like
```
                        GpioInt (Edge, ActiveHigh, ExclusiveAndWake, PullNone, 0x0000,
                            "\\_SB.GPO2", 0x00, ResourceConsumer, ,
                            )
                            {   // Pin list
                                0x0000 //Pin 21 of JP1 (GPIO_S5_00)
                            }
```

**Comment by ClarexZhou** [comment]
Close for codec driver and HW issue. Won't fix.
