### ISSUE TITLE
[BUG][SDW][TGL]Starting/stopping headset playback have some pop noise output if booting up system without headset connected..

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1514]
**Describe the bug**
Pop noise output when starting/stopping headset playback if plug in headset after system bootup. Headset playback always has noise when starting/stopping playback no matter PM status is in suspended or not.

Issue cannot be reproduced if boot up system with headset connected.

**To Reproduce**
1.Boot up system without headset connected.
2.Plug in headset after boot up successfully.
3.Run " aplay -Dhw:0,0 -fs16_le -c2 -r 48000 -vv -i wav/48California_Dreaming.wav"
4."Ctrl+c " to stop playback.

**Reproduce rate**
5/5

**Expected result**
Headset playback should not have noise output when staring/stopping playback. 

**Actual result**
Pop noise output when starting/stopping headset playback.

sof_error_trace:
```
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1           SA         5786900243.645834              nan      src/lib/agent.c:55  	validate(), ll drift detected, delta = 41532
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 4cd6497
FW: https://github.com/thesofproject/sof/commits/master commit: dbb70c8
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

<img width="399" alt="1" src="https://user-images.githubusercontent.com/56706782/69127800-e987c880-0ae5-11ea-88ee-80e3eca2faca.PNG">

<img width="818" alt="2" src="https://user-images.githubusercontent.com/56706782/69127829-fad0d500-0ae5-11ea-90b0-21ab4892f050.PNG">

<img width="530" alt="3" src="https://user-images.githubusercontent.com/56706782/69127852-0ae8b480-0ae6-11ea-89c2-f977cb40a9a3.PNG">

[dmesg1119.log](https://github.com/thesofproject/linux/files/3862635/dmesg1119.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/3862638/sof_trace.log)

**Comment by sinahuang** [comment]
This issue might be related to #1331

**Comment by plbossart** [comment]
@sinahuang can we close this? This hasn't moved since January

**Comment by sinahuang** [comment]
Issue can't be reproduced on TGL RVP with 711 and 1308 in SDW mode, so closed it.
