### ISSUE TITLE
[BUG][BYT][Nocodec]Sof will change from card1 to card 0 after modules reload

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1521]
**Describe the bug**
Sof will change from card1 to card 0 after modules reload

After reboot sof will change from card 0 to card1

**To Reproduce**
1.sudo reboot 
2."aplay -l " to check PCM list 
    sof is using card1
2.kill sof-logger process
3.sudo ./sof_remove.sh
4.sudo ./sof_insert.sh
5."aplay -l" to check PCM list 
   

**Reproduction Rate**
5/5

**Expected behavior**
Sof card will not change after modules reload

**Impact**
sof card will change from card1 to card0

**Environment**
Platform: BYT MB  with nocodec
Firmware:  63a55299 https://github.com/thesofproject/sof/commits/master
Kernel:  ecc776ae https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-byt-nocodec.tplg  same as firmware

[dmesg1120.log](https://github.com/thesofproject/linux/files/3868698/dmesg1120.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/3868699/sof_trace.log)

**Comment by Liviali155** [comment]
SOF is using card0 after system bootup when blacklist snd_hda_intel

**Comment by Liviali155** [comment]
@xiulipan  CI test will be effected

**Comment by plbossart** [comment]
Rather than a PR change, it's more likely that it's the fact that I enabled HDaudio by default in the Kconfig maybe?
How big of a problem is this if you add this blacklist on CI target devices? we don't test HDMI, do we?

**Comment by Liviali155** [comment]
Issue can be reproduced  on below commit 
Platform: BYT MB with nocodec
Firmware: 9b5dc8c6 https://github.com/thesofproject/sof/commits/master
Kernel: bc30957c https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-byt-nocodec.tplg same as firmware

**Comment by Liviali155** [comment]
Error not seen when blacklist snd_hda_intel
The result of CI test is also pass,closed it
