### ISSUE TITLE
Headset playback is silent after capture on GLK

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#154]
Moved from https://github.com/thesofproject/sof/issues/344, since this is not a firmware issue or SOF driver issue, but most likely a codec or machine driver issue.

Test with headset: use arecord to capture audio, then use aplay to check the recorded data or play audio file, there's nothing can be heard. But after hot-plug the headset, you can hear the sound. repetition rate is 100%. I also tried to play with speaker after arecord, no such issue.
How to reproduce:
arecord -D hw:0,1 -f s32_le -c 2 -r 48000 test.wav
aplay -D hw:0,1 test.wav (you can hear nothing at all)
do headset hot-plug during the playback, then you can hear the sound.
Test env:
kernel-cros-sof-v4.14-rebase: e4bc814c982d5
sof-glk-003-drop-stable: f245831
soft-master:d77beaf8b

[rmbox-t.log](https://github.com/thesofproject/linux/files/2404830/rmbox-t.log)
[rmbox.log](https://github.com/thesofproject/linux/files/2404831/rmbox.log)
[dmesg.log](https://github.com/thesofproject/linux/files/2404832/dmesg.log)

**Comment by mengdonglin** [comment]
@keqiaozhang could you help to check if this issue can still be reproduced with latest Chrome?

**Comment by ranj063** [comment]
@keqiaozhang @mengdonglin we need to use the same chrome image and ucm file as the chrome team to verify if this issue exists or not

**Comment by keyonjie** [comment]
@keqiaozhang have you disabled cras for this test?

**Comment by keyonjie** [comment]
I am afraid cras will do some ucm switching during that which is invisible to us here.

**Comment by keqiaozhang** [comment]
@keyonjie 
This issue is still exists, after disabling the cras, this issue can also be reproduced, even do headset hotplug, still nothing can be heard.

**Comment by keqiaozhang** [comment]
This is a UCM issue, Naveen will help to fix it.

**Comment by mengdonglin** [comment]
@keqiaozhang Could you check with Naveen which Chrome release can fix this issue?

**Comment by cujomalainey** [comment]
Is the 1mic vs 2mic ucm bug?

**Comment by naveen-manohar** [comment]
Hi Curtis,
The lead board should support dual mic configuration and I believe current tracker is not related to UCM load which we are tracking in b:117289797 - (except spk playback none of the endpoints work).

Seems like Codec mixer control isn't applied properly while headset capture was initially tried ising alsa cmds.
AMIC record(Headset capture):
stop cras
amixer -c0 cset name='Headphone Jack Switch' on
amixer -c0 cset name='Headset Mic Switch' on
amixer -c0 cset name='STO1 ADC Capture Switch' on
amixer -c0 cset name='RECMIX1L CBJ Switch' 1
amixer -c0 cset name='IF1 01 ADC Swap Mux' 2
amixer -c0 cset name='CBJ Boost Volume' 3
amixer -c0 cset name='Stereo1 ADC L Mux' 0
amixer -c0 cset name='Stereo1 ADC L1 Mux' 1
amixer -c0 cset name='Stereo1 ADC R1 Mux' 1
amixer -c0 cset name='Stereo1 ADC MIXL ADC2 Switch' 0
amixer -c0 cset name='Stereo1 ADC MIXR ADC2 Switch' 0
amixer -c0 cset name='Stereo1 ADC MIXL ADC1 Switch' 1
amixer -c0 cset name='Stereo1 ADC MIXR ADC1 Switch' 1
amixer -c0 cset name='Spk Switch' 0
arecord -Dhw:0,1 -f S32_LE -c 2 -r 48000 /home/root/hs1.wav

Headset Playback:
amixer -c0 cset name='Headphone Playback Volume' 11
amixer -c0 cset name='Headphone Jack Switch' on
amixer -c0 cset name='HPOL Playback Switch' 1
amixer -c0 cset name='HPOR Playback Switch' 1
amixer -c0 cset name='Stereo1 DAC MIXL DAC L1 Switch' 1
amixer -c0 cset name='Stereo1 DAC MIXR DAC R1 Switch' 1
aplay -D hw:0,1 /home/root/hs1.wav

**Comment by naveen-manohar** [comment]
Can you please confirm, does the same scenario(use-case) works fine with cmd line post applying codec mixer controls ?
If you are using alsa cmds to capture and playback, you will need to enable codec mixer control as mentioned.

Reason being:
With the v0.5 release that we made to Google, we dint observe this issue (on ww37 CPFE + SoF image).
Also I did recheck with the latest SoF BKM (that I have aligned with Ranjani) and dint observe any issue with the amic captured file’s headset audio playback on the DUT.

**Comment by keqiaozhang** [comment]
@naveen-manohar 
I still can reproduce this issue on my Yorp with latest sof-master.
I tried to apply the amixer setting you provided above, but some kcontrols cannot be found.
chronos@localhost ~ $ amixer -c0 cset name='STO1 ADC Capture Switch' on
amixer: Cannot find the given element from control hw:0
chronos@localhost ~ $ amixer -c0 cset name='STO1 ADC Capture Switch' on
amixer: Cannot find the given element from control hw:0
chronos@localhost ~ $ amixer -c0 cset name='RECMIX1L CBJ Switch' 1
amixer: Cannot find the given element from control hw:0
chronos@localhost ~ $ amixer -c0 cset name='IF1 01 ADC Swap Mux' 2
amixer: Cannot find the given element from control hw:0

Any ideas about this?

**Comment by naveen-manohar** [comment]
face-palm.. i was working on another variant of this platform and sent its mixer controls..
Shall update on the correct settings for this board.. but bottom line is codec mixer controls are needed.

For me the same usecase on CRAS works fine (on ww37 + SoF image)..

**Comment by plbossart** [comment]
@keqiaozhang Is this still a bug or should this be closed?

**Comment by keqiaozhang** [comment]
@plbossart 
Yes, this is still a bug to me. I will re-test this issue with new kernel branch.

**Comment by keqiaozhang** [comment]
This issue is still there, I retested it with debug/cros-sof-v4.14-rebase +sof-master
I have dumped all amixer controls for reference.
@naveen-manohar , please help to check.
[amixer-controls.txt](https://github.com/thesofproject/linux/files/2541517/amixer-controls.txt)

**Comment by keqiaozhang** [comment]
@naveen-manohar 
Sorry to trouble you again, this issue is still open to me, could you share the updated UCM files that you used for test to me?

**Comment by mengdonglin** [comment]
@naveen-manohar We'll close this issue here since it's not a SOF driver or fimrware issue.

**Comment by keqiaozhang** [comment]
Close it, not a firmware or kernel driver issue.
