### ISSUE TITLE
Dmesg console is flooded with repeated open/hw_params/hw_free/close pattern

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1542]
When the hw_params fails, the dmesg log is constantly updated with the same pattern.
I don't know if this is a kernel issue or PulseAudio/apps repeatedly trying to use the devices.

Adding as an issue so that we have a trace of this.
Example trace attached

[dmesg.log](https://github.com/thesofproject/linux/files/3881411/dmesg.log)

**Comment by lgirdwood** [comment]
@plbossart this can be caused by PA probing capabilities of the sound card. Perhaps these should be dev_dbg() level now ?

**Comment by plbossart** [comment]
I can't even remember what this bug was, closing
