### ISSUE TITLE
[SDW][BUG]IO transfer timed out occurred during multi-pipline stress test

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1555]
**Describe the bug**
Occurred IO transfer timed out when run multi-pipline stress test.

**To Reproduce**
1. Boot up
2. Run with comman "./multiplex_pipeline-test_update.sh pcm0p pcm2p pcm5p pcm1c pcm4c"

script: 
[multiplex_pipeline-test_update.sh.txt](https://github.com/thesofproject/linux/files/3895535/multiplex_pipeline-test_update.sh.txt)

**Reproduced rate**
Round1 : Run 300 times, failed at 171th time.
Round2: Run 300 times, failed at 132th time.
 
**Expected result**
Run multi-pipline stress test successfully

**Actual result**
Occurred IO transfer timeed out during multi-pipline stress test

Dmesg
```
[ 1853.884397] intel-sdw sdw-master-0: intel_startup: SDW0 Pin2: start
[ 1853.884401] intel-sdw sdw-master-0: intel_startup: SDW0 Pin2: done
[ 1853.884403]  Headphone: ASoC: open FE Headphone
[ 1853.884406] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[ 1853.884407] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 1853.884408] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 1853.884408] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 1853.884532]  SDW0-Playback: ASoC: hw_params BE SDW0-Playback
[ 1853.884535] rt711 sdw:0:25d:711:0: rt711_pcm_hw_params rt711-aif1
[ 1855.910857] intel-sdw sdw-master-0: IO transfer timed out
[ 1857.959011] intel-sdw sdw-master-0: IO transfer timed out
[ 1857.959191] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7203 8283 <= 0031
[ 1860.007068] intel-sdw sdw-master-0: IO transfer timed out
```
Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: d740a3e
FW: https://github.com/thesofproject/sof/commits/master  commit: d740a3e
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

Logs:
[failed_multipipeline_test_171_dmesg.log](https://github.com/thesofproject/linux/files/3895536/failed_multipipeline_test_171_dmesg.log)
[failed_multipipeline_test_171_all_logger.log](https://github.com/thesofproject/linux/files/3895537/failed_multipipeline_test_171_all_logger.log)
[multipipeline_test_132_all_logger.log](https://github.com/thesofproject/linux/files/3895853/multipipeline_test_132_all_logger.log)
[multipipeline_test_132_dmesg.log](https://github.com/thesofproject/linux/files/3895854/multipipeline_test_132_dmesg.log)

**Comment by bardliao** [comment]
@YvonneYang2 Could you test it with https://github.com/bardliao/linux/commit/690b1518f68240a864605c85024888f55ecdcc38 ?

**Comment by YvonneYang2** [comment]
Tested it 300 times, issue can still be reproduced with latest integration/soundwire-latest + https://github.com/bardliao/linux/commit/690b1518f68240a864605c85024888f55ecdcc38

Run 500 times, failed at 243th time.

Dmesg:
```
[ 2656.934491] intel-sdw sdw-master-1: intel_suspend_runtime start
[ 2656.934501] intel-sdw sdw-master-0: intel_suspend_runtime start
[ 2656.934638] intel-sdw sdw-master-1: intel_suspend_runtime done
[ 2656.935155] intel-sdw sdw-master-0: Link power down failed: -11
[ 2656.982207] intel-sdw sdw-master-3: intel_suspend_runtime start
[ 2656.982284] intel-sdw sdw-master-3: intel_suspend_runtime done
[ 2658.982463]  HDMI1: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 2658.982533]  Headphone: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 2658.982595]  SDW1-speakers: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 2661.140283]  Headphone: ASoC: found 0 audio playback paths
[ 2661.140285]  Headphone: ASoC: Headphone no valid playback route
[ 2661.140287] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: ASoC: find BE for widget ALH2.OUT
[ 2661.140288] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: ASoC: try BE : ALH2.OUT
[ 2661.140289]  Headphone: connected new DPCM playback path Headphone -> SDW0-Playback
[ 2661.140295]  Headphone: ASoC: found 1 new BE paths
[ 2661.140296]  SDW0-Playback: ASoC: open playback BE SDW0-Playback
[ 2661.140302] intel-sdw sdw-master-0: intel_startup: SDW0 Pin2: start
[ 2661.140306] intel-sdw sdw-master-0: intel_startup: SDW0 Pin2: done
[ 2661.140308]  Headphone: ASoC: open FE Headphone
[ 2661.140311] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[ 2661.140312] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 2661.140313] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 2661.140314] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 2661.140438]  SDW0-Playback: ASoC: hw_params BE SDW0-Playback
[ 2661.140440] rt711 sdw:0:25d:711:0: rt711_pcm_hw_params rt711-aif1
[ 2663.142438] intel-sdw sdw-master-0: IO transfer timed out
[ 2665.190452] intel-sdw sdw-master-0: IO transfer timed out
[ 2665.190473] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7203 8283 <= 0031
[ 2667.238473] intel-sdw sdw-master-0: IO transfer timed out
[ 2669.286264] intel-sdw sdw-master-0: IO transfer timed out
[ 2669.286285] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7209 8289 <= 0031
```

[failed_multipipeline_test_243_all_logger.log](https://github.com/thesofproject/linux/files/3900972/failed_multipipeline_test_243_all_logger.log)
[failed_multipipeline_test_243_dmesg.log](https://github.com/thesofproject/linux/files/3900973/failed_multipipeline_test_243_dmesg.log)

**Comment by bardliao** [comment]
Look like "Link power down failed: -11" can be seen on all the error dmesg log. Let's fix it first. @YvonneYang2 Could you test it with [0001-soundiwre-Intel-set-link_control-bits-again-when-it-.patch.txt](https://github.com/thesofproject/linux/files/3903276/0001-soundiwre-Intel-set-link_control-bits-again-when-it-.patch.txt)?

<details>
<summary> patch </summary>

```
diff --git a/drivers/soundwire/intel.c b/drivers/soundwire/intel.c
index 63931cda51ab..91bd6fe550fc 100644
--- a/drivers/soundwire/intel.c
+++ b/drivers/soundwire/intel.c
@@ -407,6 +407,7 @@ static int intel_link_power_down(struct sdw_intel *sdw)
 	unsigned int link_id = sdw->instance;
 	void __iomem *shim = sdw->link_res->shim;
 	u16 ioctl;
+	int retry = 3;
 
 	/* Glue logic */
 	ioctl = intel_readw(shim, SDW_SHIM_IOCTL(link_id));
@@ -424,6 +425,12 @@ static int intel_link_power_down(struct sdw_intel *sdw)
 	link_control &=  spa_mask;
 
 	ret = intel_clear_bit(shim, SDW_SHIM_LCTL, link_control, cpa_mask);
+	while (ret == -EAGAIN && retry >= 0) {
+		msleep(1);
+		ret = intel_clear_bit(shim, SDW_SHIM_LCTL,
+				      link_control, cpa_mask);
+		retry--;
+	}
 	if (ret < 0)
 		return ret;
 
```
</details>

**Comment by YvonneYang2** [comment]
Tested it 500 times with latest integration/soundwire-latest (commit:d6078f9) + 
[0001-soundiwre-Intel-set-link_control-bits-again-when-it-.patch.txt](https://github.com/thesofproject/linux/files/3903633/0001-soundiwre-Intel-set-link_control-bits-again-when-it-.patch.txt)
, IO transfer timed out issue and "Link power down failed: -11" both cannot be reproduced.

**Comment by bardliao** [comment]
@YvonneYang2 To double confirm. Could you check it with below patch instead?
```
diff --git a/drivers/soundwire/intel.c b/drivers/soundwire/intel.c
index 63931cda51ab..686c409d66c3 100644
--- a/drivers/soundwire/intel.c
+++ b/drivers/soundwire/intel.c
@@ -150,7 +150,7 @@ static inline void intel_writew(void __iomem *base, int offset, u16 value)
 
 static int intel_clear_bit(void __iomem *base, int offset, u32 value, u32 mask)
 {
-	int timeout = 10;
+	int timeout = 100;
 	u32 reg_read;
 
 	writel(value, base + offset);
```

**Comment by YvonneYang2** [comment]
@bardliao 
Issue can still be reproduced with latest integration/soundwire-latest (commit:d6078f9) + patch as above. 

Run 300 times, failed at 175th.

Dmesg:
```
[ 1878.026234] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[ 1878.026235] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 1878.026236] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 1878.026237] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 1878.026357]  SDW0-Playback: ASoC: hw_params BE SDW0-Playback
[ 1878.026360] rt711 sdw:0:25d:711:0: rt711_pcm_hw_params rt711-aif1
[ 1880.038362] intel-sdw sdw-master-0: IO transfer timed out
[ 1882.086346] intel-sdw sdw-master-0: IO transfer timed out
[ 1882.086368] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7203 8283 <= 0031
```
[failed_multipipeline_test_175_all_logger.log](https://github.com/thesofproject/linux/files/3904634/failed_multipipeline_test_175_all_logger.log)
[failed_multipipeline_test_175_dmesg.log](https://github.com/thesofproject/linux/files/3904635/failed_multipipeline_test_175_dmesg.log)

**Comment by bardliao** [comment]
@YvonneYang2 Could you test it with https://github.com/thesofproject/linux/pull/1573?

**Comment by plbossart** [comment]
@bardliao what's interesting is that the only time when the error happens when the sequences for pm_runtime are interleaved:

````
[ 1873.951019] intel-sdw sdw-master-1: intel_suspend_runtime start
[ 1873.951031] intel-sdw sdw-master-0: intel_suspend_runtime start
[ 1873.951108] intel-sdw sdw-master-1: intel_suspend_runtime done
[ 1873.956341] intel-sdw sdw-master-0: Link power down failed: -11
[ 1873.963366] intel-sdw sdw-master-3: intel_suspend_runtime start
[ 1873.963433] intel-sdw sdw-master-3: intel_suspend_runtime done
````

so it's likely we need a mutual exclusion between links...

And looking at the code, it's pretty clear:

````c
static int intel_link_power_up(struct sdw_intel *sdw)
{
	unsigned int link_id = sdw->instance;
	void __iomem *shim = sdw->link_res->shim;
	int spa_mask, cpa_mask;
	int link_control, ret;

	/* Link power up sequence */
	link_control = intel_readl(shim, SDW_SHIM_LCTL);
	spa_mask = (SDW_SHIM_LCTL_SPA << link_id);
	cpa_mask = (SDW_SHIM_LCTL_CPA << link_id);
	link_control |=  spa_mask;

	ret = intel_set_bit(shim, SDW_SHIM_LCTL, link_control, cpa_mask);
	if (ret < 0)
		return ret;

	sdw->cdns.link_up = true;
	return 0;
}
````

so what happens is that we have a common register which is accessed for different fields independently. that can't be good...

**Comment by plbossart** [comment]
it's even worse for power-down, we also touch the glue logic

````c
static int intel_link_power_down(struct sdw_intel *sdw)
{
	int link_control, spa_mask, cpa_mask, ret;
	unsigned int link_id = sdw->instance;
	void __iomem *shim = sdw->link_res->shim;
	u16 ioctl;

	/* Glue logic */
	ioctl = intel_readw(shim, SDW_SHIM_IOCTL(link_id));
	ioctl |= SDW_SHIM_IOCTL_BKE;
	ioctl |= SDW_SHIM_IOCTL_COE;
	intel_writew(shim, SDW_SHIM_IOCTL(link_id), ioctl);

	ioctl &= ~(SDW_SHIM_IOCTL_MIF);
	intel_writew(shim, SDW_SHIM_IOCTL(link_id), ioctl);

	/* Link power down sequence */
	link_control = intel_readl(shim, SDW_SHIM_LCTL);
	spa_mask = ~(SDW_SHIM_LCTL_SPA << link_id);
	cpa_mask = (SDW_SHIM_LCTL_CPA << link_id);
	link_control &=  spa_mask;

	ret = intel_clear_bit(shim, SDW_SHIM_LCTL, link_control, cpa_mask);
	if (ret < 0)
		return ret;

	sdw->cdns.link_up = false;
	return 0;
}
````

**Comment by plbossart** [comment]
@YvonneYang2 @bardliao can you look at https://github.com/thesofproject/linux/pull/1577 ?
This uses some of Bard's ideas but explicitly used to prevent concurrent access to all SHIM registers.
It sounds obvious now that I think of it but since it wasn't in the initial code it wasn't straightforward to reverse-engineer.

**Comment by bardliao** [comment]
Thanks @plbossart You always think more than me. I believe that #1577 will fix the issue.

**Comment by YvonneYang2** [comment]
Tested it 1000 times with #1577, issue cannot be reproduced.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: b4f9bfa + #1577 
FW: https://github.com/thesofproject/sof/commits/master  commit: feb9e2b
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

**Comment by plbossart** [comment]
> Thanks @plbossart You always think more than me. I believe that #1577 will fix the issue.

Nah, you did all the hard work and made it easy to connect the dots. Thanks @bardliao

**Comment by plbossart** [comment]
> Tested it 1000 times with #1577, issue cannot be reproduced.
> 
> Test recipe:
> kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: [b4f9bfa](https://github.com/thesofproject/linux/commit/b4f9bfa37f3ed78f102eb4d90c9419c58f26811d) + #1577
> FW: https://github.com/thesofproject/sof/commits/master commit: feb9e2b
> tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
> platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

very cool, thanks @YvonneYang2

**Comment by YvonneYang2** [comment]
Since commit is merged into soundwire-latest, tested it 1000 times, passed for 300 times so far. Stress test is still on going, will check it tomorrow.

**Comment by YvonneYang2** [comment]
Checked it today but found system hung. So I ran it again, system showed 
```
[ 1911.982675] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x2024001e successful
[ 1912.407409] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60040000 size 12
[ 1912.407422] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[ 1912.407432] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[ 1912.407536] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[ 1912.407550] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000387 rirb 00
[ 1912.407556] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 1912.407567] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 1912.407573] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[ 1912.407897] sof-audio-pci 0000:00:1f.3: error: trace IO error
[ 1912.407903] sof-audio-pci 0000:00:1f.3: error: trace IO error
[ 1912.407912] sof-audio-pci 0000:00:1f.3: error: trace IO error
[ 1912.407916] sof-audio-pci 0000:00:1f.3: error: trace IO error
[ 1912.407920] sof-audio-pci 0000:00:1f.3: error: trace IO error
```
**Note**: Run it with master and sof runtime PM enabled. 

Kernel: integration/soundwire-latest(f6e2dba)
FW: master(0205c95)

[failed_multipipeline_test_172_all_logger.log](https://github.com/thesofproject/linux/files/3925389/failed_multipipeline_test_172_all_logger.log)
[failed_multipipeline_test_172_dmesg.log](https://github.com/thesofproject/linux/files/3925390/failed_multipipeline_test_172_dmesg.log)

**Comment by YvonneYang2** [comment]
Tested it 1000 times with latest soundwire-latest branch (top commit: add887ef ), issue cannot be reproduced. Close it.

Note: Run it with master and sof runtime PM enabled.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: add887e
FW: https://github.com/thesofproject/sof/commits/master  commit: 65de27d
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode
