### ISSUE TITLE
[Bug][SDW][CML_2 RTC1308]Headset jack is always on even after boot up system without headset connected

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1563]
**Describe the bug**
Headset jack is always on even after boot up system without headset connected

**To Reproduce**
1. No headset connected.
2. Do system reboot via "sudo reboot"  
3. 'amixer contents ' to check headset jack status. 

**Reproduce Rate**
100%

**Actual result**
Headset jack is on when not connected
```
numid=27,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=28,iface=CARD,name='Headset Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=29,iface=MIXER,name='Headphone Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on

```

**Expected result**
Headset Mic jack should be off when not connected.

**Environment**
Firmware: decd206  cml-009-drop-stable
Kernel: d6078f9 on integration/soundwire-latest
Kernel config: Run https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Topology: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
platform: CML Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 commit: 39528c5

No message update when plug in or unplug headset.
[amixerConnects.txt](https://github.com/thesofproject/linux/files/3903859/amixerConnects.txt)
[bootup_dmesg.txt](https://github.com/thesofproject/linux/files/3903835/bootup_dmesg.txt)
[bootup_soflogger.txt](https://github.com/thesofproject/linux/files/3903836/bootup_soflogger.txt)

**Comment by ClarexZhou** [comment]
@bardliao Error not seen with UCM https://github.com/bardliao/alsa-ucm-conf/tree/separate-speakers/ucm/sof-sdw-rt711-1308-715 And PR https://github.com/thesofproject/linux/pull/1567

**Comment by bardliao** [comment]
@ClarexZhou Could you retest it since #1567 has merged?

**Comment by ClarexZhou** [comment]
Error not seen on latest kernel: soundwire-latest/b4f9bfa3. Close
