### ISSUE TITLE
[Bug][SDW][CML_2 RTC1308] Paplay via speaker only has Left Channel Output.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1564]
**Describe the bug**
Paplay via speaker only has Left Channel Output. Because Paplay is using device 2: SDW1-speakers.  
And device 2: SDW1-speakers is using Left channel. device 3: SDW2-speakers is using Right Channel.  

UCM is using one 1308 UCM https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 commit: 39528c5

**To Reproduce**
1. Do system reboot via "sudo reboot"  
2. Run ./rt1308_mixer.sh to setup amixer setting for speaker
[rt1308_mixer.txt](https://github.com/thesofproject/linux/files/3903885/rt1308_mixer.txt)
3. Open Setting->Sound, select Speaker as Output Source.
4. paplay 48California_Dreaming.wav -vvv

**Reproduce Rate**
100%

**Actual result**
Only Left channel has output. Paplay is using device 2: SDW1-speakers.  
And device 2: SDW1-speakers is using Left channel. device 3: SDW2-speakers is using Right 

```
ubuntu@ubuntu-XPS-17-9700-02:~$ paplay 48California_Dreaming.wav -vvv
Opening a playback stream with sample specification 's16le 2ch 48000Hz' and channel map 'front-left,front-right'.
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=384000, prebuf=380164, minreq=3840
Using sample spec 's16le 2ch 48000Hz', channel map 'front-left,front-right'.
Connected to device alsa_output.pci-0000_00_1f.3-platform-sdw_rt711_rt1308_rt715.HiFi__hw_sofsdwrt7111308_2__sink (index: 4, suspended: no).
Stream started.

```

**Expected result**
Both L and R channel should have output when paplay via speaker.

**Environment**
Firmware: decd206  cml-009-drop-stable
Kernel: d6078f9 on integration/soundwire-latest
Kernel config: Run https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Topology: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
platform: CML Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 commit: 39528c5

[logger.txt](https://github.com/thesofproject/linux/files/3903898/logger.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/3903899/dmesg.txt)

**Comment by ClarexZhou** [comment]
use UCM https://github.com/bardliao/alsa-ucm-conf/tree/separate-speakers/ucm/sof-sdw-rt711-1308-715 And PR https://github.com/thesofproject/linux/pull/1567 
2 RTC1308 Speaker are listed separately in sound setting. As below snapshot. 
Is it expected?  Or should list one speaker and output on both 2 RTC1308 at same time? 
![image](https://user-images.githubusercontent.com/49641224/69852629-bd2b3380-12bf-11ea-8fd0-4382535929bd.png)

**Comment by bardliao** [comment]
> use UCM https://github.com/bardliao/alsa-ucm-conf/tree/separate-speakers/ucm/sof-sdw-rt711-1308-715 And PR #1567
> 2 RTC1308 Speaker are listed separately in sound setting. As below snapshot.
> Is it expected? Or should list one speaker and output on both 2 RTC1308 at same time?
> ![image](https://user-images.githubusercontent.com/49641224/69852629-bd2b3380-12bf-11ea-8fd0-4382535929bd.png)

@ClarexZhou It is expected for now. The two rt1308 are on different sdw link. Use multi-codecs in a dai link is a new feature on Soundwire and we will implement it soon.

**Comment by mengdonglin** [comment]
Depend on the new feature of synchronized playbackm https://github.com/thesofproject/linux/pull/1644 is to address the feature in driver and WIP

**Comment by bardliao** [comment]
FW change is also required for the issue. A WIP PR is https://github.com/thesofproject/sof/pull/2258

**Comment by sinahuang** [comment]
Issue can't be seen with sof-dev(commit：8f1c6ad) +PR https://github.com/thesofproject/linux/pull/2058 (note :PR2058 is for other blocked issue https://github.com/thesofproject/linux/issues/2031) and master (commit:af38b20b), closed it.
