### ISSUE TITLE
[Bug][CML-H]HDMI jack detection is still on when disconnect HDMI during S2idle/S3

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1566]
**Describe the bug**
HDMI jack detection is still on when disconnect HDMI during S2idle. Also reproduce when disconnect HDMI during S3. 

Error not seen if connected HDMI then disconnect again after work up.

**To Reproduce**
1. HDMI is connected
2. Do system reboot via "sudo reboot"  
3. sudo rtcwake -m mem -s 20
4. Unplug HDMI during suspend
5. amixer contents to check HDMI jack status.

**Reproduce Rate**
100%

**Actual result**
HDMI jack is still on.
```
numid=32,iface=CARD,name='HDMI/DP,pcm=5 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=38,iface=CARD,name='HDMI/DP,pcm=6 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=44,iface=CARD,name='HDMI/DP,pcm=7 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```

**Expected result**
HDMI jack should be off.

**Environment**
Firmware: decd206  cml-009-drop-stable
Kernel: d6078f9 on integration/soundwire-latest
Kernel config: Run https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Topology: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
platform: CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 commit: 39528c5

[dmesg_s3.txt](https://github.com/thesofproject/linux/files/3903933/dmesg_s3.txt)
[amixerContents_s3.txt](https://github.com/thesofproject/linux/files/3903934/amixerContents_s3.txt)
[logger_s3.txt](https://github.com/thesofproject/linux/files/3903935/logger_s3.txt)

**Comment by ClarexZhou** [comment]
Error also seen on CML-H RVP with onboard ALC711 in HDA mode.
Detail reproduce steps:
1. Both HDMI and DP are connected
2. sudo rtcwake -m mem -s 20
3.Unplug HDMI during suspend
4. amixer contents to check HDMI jack status after system wake up.
Error seen. Both HDMI and DP jack are on.
To recover: Connect HDMI then disconnect again, HDMI jack is off now.

**Environment**
Kernel:  sof-dev 709427e6
Firmware: Master 15201664
TPLG: Same with firmware branch. sof-hda-generic-4ch.tplg

**Comment by kv2019i** [comment]
Ack, will take a look. This could be related to #1440, which is also still open.

**Comment by kv2019i** [comment]
@ClarexZhou Could you take DRM logs for the scenario? Logs can be enabled at runtime with:

sudo bash
echo 0x1f > /sys/module/drm/parameters/debug    

... then run through the scanerario and capture dmesg.

**Comment by ClarexZhou** [comment]
Here comes DRM log:
Original steps with one HDMI on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode: 
[kern_sdw.txt](https://github.com/thesofproject/linux/files/3924711/kern_sdw.txt)
And https://github.com/thesofproject/linux/issues/1566#issuecomment-561529251 HDMI+DP steps on CML-H RVP with onboard ALC711 in HDA mode: 
[kern_HDA.txt](https://github.com/thesofproject/linux/files/3924715/kern_HDA.txt)

**Comment by kv2019i** [comment]
Thanks @ClarexZhou !

I think this is a bug on i915 side. When I compare succesful case on a CML system with this log, after resume, in your failing case log I see this:

Nov  1 13:00:22 ubuntu-XPS-17-9700-01 kernel: [  122.361478] [drm:intel_dp_compute_config [i915]] DP link computation with max lane count 2 max rate 162000 max bpp 24 pixel clock 154000KHz
Nov  1 13:00:22 ubuntu-XPS-17-9700-01 kernel: [  122.361496] [drm:intel_dp_compute_config [i915]] Force DSC en = 0
Nov  1 13:00:22 ubuntu-XPS-17-9700-01 kernel: [  122.361522] [drm:intel_atomic_check [i915]] Encoder config failure: -22

In success case (another system), same flow has logs as follows:
Dec  5 08:12:31 sof-ol-latitude-9510 kernel: [  440.672381] [drm:intel_dp_compute_config [i915]] DP link computation with max lane count 4 max rate 162000 max bpp 36 pixel clock 148500KHz
Dec  5 08:12:31 sof-ol-latitude-9510 kernel: [  440.672390] [drm:intel_dp_compute_config [i915]] Force DSC en = 0
Dec  5 08:12:31 sof-ol-latitude-9510 kernel: [  440.672398] [drm:intel_dp_compute_config [i915]] DP lane count 4 clock 162000 bpp 30
Dec  5 08:12:31 sof-ol-latitude-9510 kernel: [  440.672406] [drm:intel_dp_compute_config [i915]] DP link rate required 556875 available 648000

And then finally (this updates amixer state):
Dec  5 08:12:31 sof-ol-latitude-9510 kernel: [  440.672797] [drm:drm_atomic_commit [drm]] committing 000000003b946186
Dec  5 08:12:31 sof-ol-latitude-9510 kernel: [  440.672863] [drm:hsw_audio_codec_disable [i915]] Disable audio codec on transcoder B

Can you file a bug to i915 (example bug: https://bugs.freedesktop.org/show_bug.cgi?id=110595 ). You can put me in cc and attach following:
 - kern_sdw.txt kernel log
 - as root, record output of "cat /sys/kernel/debug/dri/0/i915_display_info " after resume is completed and amixer shows wrong state

**Comment by ClarexZhou** [comment]
Can't report bugs on  https://bugs.freedesktop.org now.  Seems moved to gitlab. 
Report and track in bug https://gitlab.freedesktop.org/drm/intel/issues/735 [i915][CML-H] HDMI jack detection is still on when disconnect HDMI during S2idle/S3

Close for not SOF issue.
