### ISSUE TITLE
[BUG][SDW]"rt1308 sdw:1:25d:1308:0: Initialization not complete, timed out" occurred during multi-pipline stress test.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1600]
**Describe the bug**
Firstly disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001. Tested it with integration/soundwire-latest + #1589
"rt1308 sdw:1:25d:1308:0: Initialization not complete, timed out" occurred during multi-pipline stress test. Then aplay0,2(RT1308) cannot work anymore.

**To Reproduce**
1. Disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001, then reboot to make it work.
2. Run with command "./multiplex_pipeline-test_update.sh pcm0p pcm2p pcm5p pcm1c pcm4c"

**Reproduced rate**
Run 300 times, failed at 289th time
Only reboot can make RT1308 work again.
 
**Expected result**
Should not occur any error during multi-pipline test

**Actual result**
"rt1308 sdw:1:25d:1308:0: Initialization not complete, timed out" occurred during multi-pipline stress test. Then aplay0,2(RT1308) cannot work anymore.

Dmesg
```
[ 3758.642549] intel-sdw sdw-master-1: Updating Slave 1 status
[ 3758.642552] intel-sdw sdw-master-1: sdw_handle_slave_status: Updating Slave 1 status done
[ 3758.642554] intel-sdw sdw-master-1: sdw_handle_slave_status: end
[ 3759.313092] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 3759.314552] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 3760.679886] rt1308 sdw:1:25d:1308:0: Initialization not complete, timed out
[ 3760.679908] intel-sdw sdw-master-1: intel_startup: SDW1 Pin2: start
[ 3760.679921] intel-sdw sdw-master-1: intel_startup: SDW1 Pin2: done
[ 3760.679932]  SDW1-speakers: ASoC: open FE SDW1-speakers
[ 3760.679944] sof-audio-pci 0000:00:1f.3: pcm: open stream 2 dir 0
[ 3760.679950] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 3760.679954] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 3760.679957] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 3760.680018]  HDMI1: ASoC: found 0 audio playback paths
[ 3760.680024]  HDMI1: ASoC: HDMI1 no valid playback route
```
Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: add887ef + PR1589
FW: https://github.com/thesofproject/sof/commits/master  commit: 65de27d
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

[failed_multipipeline_test_289_all_logger.log](https://github.com/thesofproject/linux/files/3929998/failed_multipipeline_test_289_all_logger.log)
[failed_multipipeline_test_289_dmesg.log](https://github.com/thesofproject/linux/files/3929999/failed_multipipeline_test_289_dmesg.log)

**Comment by YvonneYang2** [comment]
Tested it with #1589 + #1594 , issue still can be reproduced. 
Run 1000 times, failed at 887th time. So seems #1594 doesn't fix the issue.

[failed_multipipeline_test_887_all_logger.log](https://github.com/thesofproject/linux/files/3930039/failed_multipipeline_test_887_all_logger.log)
[failed_multipipeline_test_887_dmesg.log](https://github.com/thesofproject/linux/files/3930040/failed_multipipeline_test_887_dmesg.log)

**Comment by YvonneYang2** [comment]
With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8 for bus reset
```
rt711 sdw:0:25d:711:0: Initialization not complete, timed out
```
Occurred when run suspend/resume with playback stress test. Failed at 95th time. 
It seems same with this issue. And will retest it with #1599 to check if it can be fixed by #1599 

Kernel: integration/soundwire-latest(d64c4a3) + #1586 
FW:master(65de27d)

[s3_test_95_logger_all.log](https://github.com/thesofproject/linux/files/3930589/s3_test_95_logger_all.log)
[test_95.log](https://github.com/thesofproject/linux/files/3930590/test_95.log)

**Comment by bardliao** [comment]
I checked all attached error log , and found that all of them are failed to read device id.
for example
```
[ 9482.368443] intel-sdw sdw-master-1: Slave attached, programming device number
[ 9482.368882] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[ 9482.368885] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 9482.369027] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 9482.369405] intel-sdw sdw-master-1: Msg Ack not received
[ 9482.369407] intel-sdw sdw-master-1: Msg Ack not received
[ 9482.369408] intel-sdw sdw-master-1: Msg Ack not received
[ 9482.369409] intel-sdw sdw-master-1: Msg Ack not received
[ 9482.369409] intel-sdw sdw-master-1: Msg Ack not received
[ 9482.369410] intel-sdw sdw-master-1: Msg Ack not received
[ 9482.369412] intel-sdw sdw-master-1: Msg ignored for Slave 0
[ 9482.369413] intel-sdw sdw-master-1: No more devices to enumerate
[ 9482.369414] intel-sdw sdw-master-1: End of sdw_program_device_num ret 0
```

**Comment by YvonneYang2** [comment]
Tested it 500 times,  issue cannot be reproduced with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1.


kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: e375909+ PR1586
FW: https://github.com/thesofproject/sof/commits/master  commit: 8f51e6b
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

**Comment by YvonneYang2** [comment]
Firstly disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001. 
Tested multipipline stress 1000 times with integration/soundwire-latest + #1586, original issue cannot be reproduced. Then will test suspend/resume with playback, if issue can also not be reproduced, will close it.

**Comment by YvonneYang2** [comment]
> With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8 for bus reset
> 
> ```
> rt711 sdw:0:25d:711:0: Initialization not complete, timed out
> ```
> 
> Occurred when run suspend/resume with playback stress test. Failed at 95th time.
> It seems same with this issue. And will retest it with #1599 to check if it can be fixed by #1599
> 
> Kernel: integration/soundwire-latest([d64c4a3](https://github.com/thesofproject/linux/commit/d64c4a30ecf3751d2416982d39ddf048a82a9f87)) + #1586
> FW:master(65de27d)
> 
> [s3_test_95_logger_all.log](https://github.com/thesofproject/linux/files/3930589/s3_test_95_logger_all.log)
> [test_95.log](https://github.com/thesofproject/linux/files/3930590/test_95.log)

As for this comment, tested it with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8, issue cannot be reproduced on integration/soundwire-latest(e375909) + #1586 after suspend/resume with playback stress test 500 times.

**Comment by YvonneYang2** [comment]
Since issue cannot be reproduced, close it.

**Comment by YvonneYang2** [comment]
Firstly disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001. 
Issue can still be reproduced with PR #1586 , PR #1618 and configuration with no amplifier on link-2. 
Failed at 289th time. So reopen it.

Dmesg:
```
[ 3126.469686] intel-sdw sdw-master-1: Msg Ack not received
[ 3126.469687] intel-sdw sdw-master-1: Msg Ack not received
[ 3126.469688] intel-sdw sdw-master-1: Msg ignored for Slave 0
[ 3126.469689] intel-sdw sdw-master-1: No more devices to enumerate
[ 3126.469690] intel-sdw sdw-master-1: End of sdw_program_device_num ret 0
[ 3126.470054] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[ 3126.470056] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 3126.470190] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 3126.995503] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 3126.996927] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 3128.487448] rt1308 sdw:1:25d:1308:0: Initialization not complete, timed out
[ 3128.487472] intel-sdw sdw-master-1: intel_startup: SDW1 Pin2: start
[ 3128.487485] intel-sdw sdw-master-1: intel_startup: SDW1 Pin2: done
[ 3128.487498]  SDW1-speakers: ASoC: open FE SDW1-speakers
[ 3128.487512] sof-audio-pci 0000:00:1f.3: pcm: open stream 2 dir 0
[ 3128.487519] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 3128.487523] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 3128.487527] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 3128.487646]  HDMI1: ASoC: found 0 audio playback paths
[ 3128.487652]  HDMI1: ASoC: HDMI1 no valid playback route
[ 3128.487661] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: ASoC: find BE for widget HDA0.OUT
[ 3128.487666] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: ASoC: try BE : ALH2.OUT
```
[failed_multipipeline_test_289_all_logger.log](https://github.com/thesofproject/linux/files/3953420/failed_multipipeline_test_289_all_logger.log)
[failed_multipipeline_test_289_dmesg.log](https://github.com/thesofproject/linux/files/3953421/failed_multipipeline_test_289_dmesg.log)

**Comment by YvonneYang2** [comment]
Firstly disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001.
Tested it 500 times with integration/soundwire-latest( cf2660a ) and cml-010-drop-stable( 5e5f69e),
issue cannot be reproduced. Close it.
