### ISSUE TITLE
[Bug][UCM1]Should remove the whole headphone mic from Mics.conf

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1617]
**Describe the bug**
Can separate detect Headphone, Headset and Microphone via jack detection in amixer. Seems should remove the whole headphone mic from Mics.conf. For no difference for headset capture usage when selecting Headset Mic or Headphone MIC from sound input setting. Also Pure mic capture always not work in current visible profile.

**Headset：**
numid=15,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=12,iface=CARD,name='Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on

**Headphone:**
numid=15,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=12,iface=CARD,name='Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off

**Pure Microphone:**
numid=15,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=12,iface=CARD,name='Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off

**To Reproduce**
1. Connect headset
2. Open system sound input setting, select Headset Mic and Headphone Mic 
3. Do paplay and parecord via headset. Always works
4. Connect Headphone Mic to check function.

**frequency**
100%

**Actual result**
Headset playback and capture always works when selecting Headset Mic or Headphone MIC from sound input setting. Also Pure mic capture always not work in current visible profile. 

**Expected result**
Should remove the whole headphone mic from Mics.conf.

**Environment**
Kernel: release/sof-v5.0 32c6c62
Firmware: https://github.com/thesofproject/linux-firmware/tree/master/intel/sof/cnl/intel  sof-cnl-v1.3-0f73628.ri rename to sof-cnl.ri   
Kernel config: Run https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Topology: Same with FW branch,  sof-hda-generic-2ch.tplg
platform: WHL Laptop with codec ALC285 in HDA mode
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/

**Comment by bardliao** [comment]
> **Pure Microphone:**
> numid=15,iface=CARD,name='Headphone Jack'
> ; type=BOOLEAN,access=r-------,values=1
> : values=on
> numid=12,iface=CARD,name='Mic Jack'
> ; type=BOOLEAN,access=r-------,values=1
> : values=off

It should be 'Headphone Jack' off and 'Mic Jack' on if it detects right.  However, I am not sure if the HW design support pure Microphone or not.

**Comment by jason77-wang** [comment]
No pure mic on Lenovo machines.

For headset mic on Lenovo machines, just use the 'Mic Jack'

**Comment by juimonen** [comment]
removed in https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1 head

**Comment by ClarexZhou** [comment]
@juimonen , Headphone Mic is removed on https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1, commit 463ea8f1. 

But still shown 'Headset Microphone' when connecting Headphone. Could  you also fix this? or should create and follow up in new bug?

**Comment by juimonen** [comment]
@ClarexZhou hmm ok, let me see what I can do...

**Comment by juimonen** [comment]
@ClarexZhou @jason77-wang if I use "Mic Jack" in headset mic it doesn't show me headset mic at all, as I'm not getting any change in "Mic Jack" event. So even if I insert headset, Mic Jack is alway "off" in alsa... Do we need to configure something more in kernel perhaps?

**Comment by juimonen** [comment]
@ClarexZhou can you try to insert headset and see if Mic Jack value changes for you:
amixer contents | grep "Mic Jack" -A2

**Comment by ClarexZhou** [comment]
@juimonen, The Mic Jack also not changed in my side now. But it works in the environment when creating this issue. Double checking now.

**Comment by ClarexZhou** [comment]
Now Mic Jack works after boot up or s3. Details as below:
1. Boot up when headset connected -> Mic jack is On. Pass
2. Unplug Headset and plug in headset again-> Mic jack is off. Failed
3. sudo rtcwake -m mem -s 10 ->Mic jack is back to On. Pass

Any ideas about this?  Will this be effected after alsa-lib and pulseaudio update? @juimonen @jason77-wang

**Comment by ClarexZhou** [comment]
Close this bug for headphone mic is already removed. Will create new issue to track once Mic jack is supported.
