### ISSUE TITLE
[BUG][SDW]Snd_sof_pci cannot be unloaded when do module unload.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1626]
**Describe the bug**
With options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8, snd_sof_pci cannot be unloaded and snd_spf_pci switched to -1 in lsmod

**To Reproduce**
1. Disable Pulse audio, then reboot.
2. Run ./sof_remove.sh
3. Check the snd_sof_pci status via command "lsmod"

Script:
[sof_remove.sh.txt](https://github.com/thesofproject/linux/files/3960363/sof_remove.sh.txt)

**Reproduced rate**
100%
 
**Expected result**
snd_sof_pci can be unloaded.

**Actual result**
snd_sof_pci cannot be unloaded and snd_spf_pci switched to -1 in lsmod

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9645962
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: cc4c356
tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML-H Laptop with codec ALC711, RT1308, RT715 in SDW mode

[log.log](https://github.com/thesofproject/linux/files/3960384/log.log)

**Comment by plbossart** [comment]
@bardliao can you look into this, this looks related to the driver_unregister() in sdw_intel_exit()
Thanks!

@YvonneYang2 can you check if this happens only with the 0x8 option, it's likely it should happen as well with 0x1

**Comment by plbossart** [comment]
@bardliao the error goes away if I invert the sequence

````diff
void sdw_intel_exit(struct sdw_intel_ctx *ctx)
 {
-       sdw_intel_cleanup(ctx);
        driver_unregister(&intel_sdw_driver.driver);
+       sdw_intel_cleanup(ctx);
        kfree(ctx);
 }
````

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced with latest integration/soundwire-latest (e6392c0) and cml-010-drop-stable
(5e5f69e) , close it.
