### ISSUE TITLE
[Bug][UCM1][WHL]Should separate Headphone and headset profile.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1629]
**Describe the bug**
Can separate detect Headphone, Headset via jack detection in amixer. Should separate Headphone and headset profile.

**Headset：**
numid=15,iface=CARD,name='Headphone Jack'
; type=BOOLEAN,access=r-------,values=1
: values=on
numid=12,iface=CARD,name='Mic Jack'
; type=BOOLEAN,access=r-------,values=1
: values=on

**Headphone:**
numid=15,iface=CARD,name='Headphone Jack'
; type=BOOLEAN,access=r-------,values=1
: values=on
numid=12,iface=CARD,name='Mic Jack'
; type=BOOLEAN,access=r-------,values=1
: values=off

**To Reproduce**
Plug Headphone, open sound setting, the headphone should be on

**frequency**
100%

**Actual result**
Both headphone and headset Mic is on when connecting Headphone.

**Expected result**
Only Headphone should be on when connecting Headphone.

**Environment**
Kernel: release/sof-v5.0 32c6c62
Firmware: https://github.com/thesofproject/linux-firmware/tree/master/intel/sof/cnl/intel  sof-cnl-v1.3-0f73628.ri rename to sof-cnl.ri   
Kernel config: Run https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Topology: Same with FW branch,  sof-hda-generic-2ch.tplg
platform: WHL Laptop with codec ALC285 in HDA mode
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ commit 463ea8f1.

**Comment by juimonen** [comment]
@ClarexZhou I'm not sure if the division into 2 profiles is the solution... let's try to get first the mic detection working, then see what would be the best solution.

**Comment by ClarexZhou** [comment]
@juimonen  MIC detection can work when HDA analog is in use.  
So could you please try to separate headset and headphone in UCM first, and don't wait #1628?

**Comment by juimonen** [comment]
@ClarexZhou hmm I still don't understand what you mean...? With current UCM, at least for my X1, headset mic only appears if you plugin headset, it doesn't appear if you plugin headphones. And you have to play something all the time for the detection to work.

So what functionality do you want exactly?

**Comment by ClarexZhou** [comment]
@juimonen , 
headset mic only appears if you plugin headset, it doesn't appear if you plugin headphones
This is the exactly what i wanted.

But headpset mic still apprears if i plugin headset into my X1.
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ commit 463ea8f1.

**Comment by juimonen** [comment]
@ClarexZhou oh there's 1 commit more in the repo, so move to that ucm.

**Comment by ClarexZhou** [comment]
Error not seen on UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/  commit 948cfcc8. Close.
