### ISSUE TITLE
Need rate limit the trace IPC debug

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#1632]
This feature request comes from https://github.com/thesofproject/sof/issues/2211 where FW can send a a lot of IPC debug in abnormal situation.

**Comment by plbossart** [comment]
isn't this implemented already at the firmware level by @lyakh 's changes?

I am not sure what the kernel could do anyways, it could change the debug level but for rate-limiting we have to filter at the source, i.e. within the firmware.

@mengdonglin can you comment?

**Comment by lyakh** [comment]
> isn't this implemented already at the firmware level by @lyakh 's changes?

"it wasn't me" (TM)? At least the version that has been merged eventually wasn't mine. But that's unrelated anyway?

> I am not sure what the kernel could do anyways, it could change the debug level but for rate-limiting we have to filter at the source, i.e. within the firmware.
> 
> @mengdonglin can you comment?

I guess we could use `dev_dbg_ratelimited()`?

**Comment by plbossart** [comment]
@mengdonglin last call. Without clarifications I will close this enhancement request.

**Comment by plbossart** [comment]
no information, closing
