### ISSUE TITLE
[BUG][CML]Occurred "Clock Stop prepare failed for slave: -61" during suspend/resume stress test.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1638]
**Describe the bug**
Occurred "rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61" during suspend/resume stress test.  When issue occurred, aplay0,2(RT1308) cannot work.

**To Reproduce**
1. Boot up with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x0
2. Run command "sudo ./stress-s3.sh 300 1 0"
3. Check logs after stress test.
[stress-s3.sh.txt](https://github.com/thesofproject/linux/files/3977594/stress-s3.sh.txt)

**Reproduced rate**
Run 300 times, failed at 47th time.
Only reboot can recover the issue.
 
**Expected result**
No error occurred during stress test.

**Actual result**
Occurred "rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61" during suspend/resume stress test.  Aplay0,2 cannot work after issue occurred.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: e6392c0 
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: 5e5f69e 
tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

Dmesg
```
[ 1336.534046] PM: suspend exit
[ 1336.968044] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1336.968295] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1337.467830] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1337.468153] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1338.049406] asix 1-6.1:1.0 enx000ec6b72c3c: link up, 100Mbps, full-duplex, lpa 0x41E1
[ 1340.087030] intel-sdw sdw-master-1: intel_suspend_runtime start
[ 1340.087042] intel-sdw sdw-master-1: sdw_cdns_clock_stop: start
[ 1340.087053] intel-sdw sdw-master-1: sdw_cdns_clock_stop: slave attached 1
[ 1340.087074] rt711 sdw:0:25d:711:0: rt711_dev_suspend start
[ 1340.087079] rt711 sdw:0:25d:711:0: rt711_dev_suspend end
[ 1340.087087] intel-sdw sdw-master-0: intel_suspend_runtime start
[ 1340.087091] intel-sdw sdw-master-0: sdw_cdns_clock_stop: start
[ 1340.087099] intel-sdw sdw-master-0: sdw_cdns_clock_stop: slave attached 1
[ 1340.087324] intel-sdw sdw-master-0: sdw_cdns_clock_stop: end
[ 1340.087335] intel-sdw sdw-master-0: intel_suspend_runtime done
[ 1340.087642] intel-sdw sdw-master-1: Slave status change
[ 1340.087648] intel-sdw sdw-master-1: Slave 1 UNATTACHED
[ 1340.087652] intel-sdw sdw-master-1: sdw_handle_slave_status: start
[ 1340.087658] rt1308 sdw:1:25d:1308:0: sdw_modify_slave_status: changing status slave 1 status 1 new status 0
[ 1340.087662] rt1308 sdw:1:25d:1308:0: sdw_modify_slave_status: initializing completion for Slave 1
[ 1340.087667] intel-sdw sdw-master-1: Updating Slave 1 status
[ 1340.087673] intel-sdw sdw-master-1: sdw_handle_slave_status: Updating Slave 1 status done
[ 1340.087678] intel-sdw sdw-master-1: sdw_handle_slave_status: end
[ 1340.087689] intel-sdw sdw-master-1: Msg ignored for Slave 1
[ 1340.087693] rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61
[ 1340.087697] rt1308 sdw:1:25d:1308:0: pre-prepare failed:-61
[ 1340.087702] intel-sdw sdw-master-1: prepare clock stop failed -61
[ 1340.087706] intel-sdw sdw-master-1: cannot enable clock stop on suspend
[ 1340.088060] intel-sdw sdw-master-1: Slave status change
[ 1340.088082] intel-sdw sdw-master-1: Slave 0 ATTACHED
[ 1340.088093] intel-sdw sdw-master-1: sdw_handle_slave_status: start
[ 1340.088102] intel-sdw sdw-master-1: Slave attached, programming device number
[ 1340.088313] intel-sdw sdw-master-1: SDW Slave Addr: 20025d130800
[ 1340.088325] intel-sdw sdw-master-1: SDW Slave class_id 0, part_id 1308, mfg_id 25d, unique_id 0, version 2
[ 1340.088331] intel-sdw sdw-master-1: in sdw_assign_device_num
```

[test_47.log](https://github.com/thesofproject/linux/files/3977562/test_47.log)
[s3_test_47_logger_all.log](https://github.com/thesofproject/linux/files/3977569/s3_test_47_logger_all.log)

**Comment by plbossart** [comment]
@RanderWang @bardliao can you take a look at the log?

It seems we have an initial error
````
[ 1340.087648] intel-sdw sdw-master-1: Slave 1 UNATTACHED
````
which happens during a clock-stop sequence

the bad sequence seems to be
a) pm_runtime suspend with clock stopped
b) system suspend
c) system resume
d) pm_runtime_suspend -> failed clock stop.

There is probably a bad state defined in b), maybe the glue logic is not reset properly.

**Comment by YvonneYang2** [comment]
Tested it 600 times with latest integration/soundwire-latest(121c751), issue cannot be reproduced. Will keep monitor it.

**Comment by RanderWang** [comment]
> @RanderWang @bardliao can you take a look at the log?
> 
> It seems we have an initial error
> 
> ```
> [ 1340.087648] intel-sdw sdw-master-1: Slave 1 UNATTACHED
> ```
> 
> which happens during a clock-stop sequence
> 
> the bad sequence seems to be
> a) pm_runtime suspend with clock stopped
> b) system suspend
> c) system resume
> d) pm_runtime_suspend -> failed clock stop.
> 
> There is probably a bad state defined in b), maybe the glue logic is not reset properly.

@plbossart  Bard discussed with me, and we got an idea.
at c), 1308 was set dev num correctly, so b) should be ok.
slave was in clock stop mode in b) and bus was reset at c) but we didn't clear clock stop status in slave.  Maybe slave was out of order for  uncleared clock stop status, then it sent unattached event at d).  Maybe we need to check and clear slave status after bus reset.

**Comment by plbossart** [comment]
> slave was in clock stop mode in b) and bus was reset at c) but we didn't clear clock stop status in slave. Maybe slave was out of order for uncleared clock stop status, then it sent unattached event at d). Maybe we need to check and clear slave status after bus reset.

we do clear the status before bus reset, so when the bus restarts it should appear as ATTACHED. if it loses sync then there is something wrong...

**Comment by YvonneYang2** [comment]
> Tested it 600 times with latest integration/soundwire-latest([121c751](https://github.com/thesofproject/linux/commit/121c7512e56b9f4e01c71d772d5436b8adda555e)), issue cannot be reproduced. Will keep monitor it.

Ran it 1000 times again, issue was reproduced at 121st time. 

[test_121.log](https://github.com/thesofproject/linux/files/3986299/test_121.log)

**Comment by RanderWang** [comment]
> > slave was in clock stop mode in b) and bus was reset at c) but we didn't clear clock stop status in slave. Maybe slave was out of order for uncleared clock stop status, then it sent unattached event at d). Maybe we need to check and clear slave status after bus reset.
> 
> we do clear the status before bus reset, so when the bus restarts it should appear as ATTACHED. if it loses sync then there is something wrong...

sorry, I mean to clear clock stop status in systemctrl register in slave
we clear it for intel_resume_runtime, but if intel_resume is called after intel_suspend_runtime is called, we don't clear the status and just reset bus.

**Comment by YvonneYang2** [comment]
Tested it 2000 times with latest integration/soundwire-latest + 9cdb114, issue cannot be reproduced.

**Comment by RanderWang** [comment]
thanks @YvonneYang2 .  I also did the test a few times and found no problem.

**Comment by YvonneYang2** [comment]
Tested it 1000 times, issue cannot be reproduced with latest integration-soundwire-latest(https://github.com/thesofproject/linux/commit/121c7512e56b9f4e01c71d772d5436b8adda555e) + #1640 .

**Comment by YvonneYang2** [comment]
On CML-H sdw laptop, with options **0x8**, issue can be reproduced on latest soundwire-latest (https://github.com/thesofproject/linux/commit/121c7512e56b9f4e01c71d772d5436b8adda555e) ,  retest it with soundwire-latest+PR #1640, issue can be blocked by issue #1660 .

[multipipeline_test_299_dmesg.log](https://github.com/thesofproject/linux/files/4028814/multipipeline_test_299_dmesg.log)
[multipipeline_test_299_all_logger.log](https://github.com/thesofproject/linux/files/4028815/multipipeline_test_299_all_logger.log)

**Comment by YvonneYang2** [comment]
Checked it on CML-U sdw laptop, with latest integration/soundwire-latest + #1665 , issue cannot be reproduced after 1000 iterations of multipipline stress test.

**Comment by sinahuang** [comment]
Checked it on CML-H sdw laptop, with latest integration/soundwire-latest + #1665 , issue cannot be reproduced after 1000 iterations of multipipline stress test or 500 iterations of suspend/resume with aplay stress test.

**Comment by YvonneYang2** [comment]
Tested it on CML-U and CML-H sdw laptop,with latest integration/soundwire-latest(top commit:07348fa), issue cannot be reproduced after #1665 merged, so close it.
