### ISSUE TITLE
Support 4 HDMI CVTs in generic HDA machine driver

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1639]
Add support for 4 HDMI CVTs to the generic HDA machine driver.

This allows to play audio to four different HDMI/DP receivers at the same time (e.g. one display attached to HDMI and a three monitor DP-MST hub connected to USB-C/DP, system with four separate physical connectors, or some combination).

Similar patch is needed as was done for e.g. sof_rt5682 already with:
ASoC: intel: sof_rt5682: Add quirk for number of HDMI DAI's

**Comment by kv2019i** [comment]
A quick update: I was planning to implement this as a quick task this week, but this turns out to be somewhat more complicated. The current generic HDA machine driver topology and machine driver are used across multiple generations of hardware, some supporting only 3 iDisp outputs, while some support 4. To add 4th iDisp converter to generic HDA driver, following changes are needed:
1. ~~SOF Intel DSP code needs to support 4 iDisp~~ (done in #1636)
2. topology needs to be extended
3. machine driver needs to be extended
4. UCM file for generic HDA needs to be updated

With UCM2, the step 4 could be done in compatible manner (new UCM file could be deployed without breaking existing setups).

For steps 2 and 3, situation is trickier. I did today some experiments whether we could add iDisp4 in a conditional manner, but this does not seem to work. Currently, if topology is added but kernel is not, or if kernel mach driver is updated without matching  topology update, audio probe will fail subset of machines and for a widely used machine driver in upstream, this is not acceptable.

So it seems for now four converters are only supported in new machine drivers (like some of the TGL I2S mach drivers and the SDW machine driver which enables the converter based on quirks).

To add 4 iDisp support to generic HDA driver, a new topology file is needed and the logic to identify which tplg file to load, needs to be extended. 

FYI @plbossart (related to the design chosen in sof_sdw using DMI matching)

**Comment by kv2019i** [comment]
FYI @mengdonglin -- I downgraded this feature to P3 for now. 4 CVTs can be enabled, but requires a separate tplg+machdriver for now (or using legacy driver).

**Comment by plbossart** [comment]
> 2. topology needs to be extended
> 3. machine driver needs to be extended

> For steps 2 and 3, situation is trickier. I did today some experiments whether we could add iDisp4 in a conditional manner, but this does not seem to work. Currently, if topology is added but kernel is not, or if kernel mach driver is updated without matching topology update, audio probe will fail subset of machines and for a widely used machine driver in upstream, this is not acceptable.

We can add a quirk in the machine driver to only add the 4th link starting <SOC+>, and likewise we can have a quirk on the SOF side that selects a different topology file for <SOC+>. It's just a matter of adding a suffix, either before or after the dmic number.

**Comment by plbossart** [comment]
no plans to add 4th DisplayAudio path for HDaudio.
