### ISSUE TITLE
failed to get afg sub nodes on ChromeOS devices

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#1642]
Multiple sightings have been reported of failure to probe the HDMI codec in i915 at boot, specifically on ChromeOS devices and a recent 5.4/5.5 kernel.

Error logs:
[   79.756783] snd_hda_codec_hdmi ehdaudio0D2: HDMI: failed to get afg sub nodes                                                                               
[   79.756800] snd_hda_codec_hdmi ehdaudio0D2: patch failed -22                                                                                                
[   79.756862] snd_hda_codec_hdmi ehdaudio0D2: ASoC: failed to probe                                                                                           
component -22                                                                                                                                                  
[   79.756930] bxt_da7219_max98357a glk_da7219_max98357a: ASoC: failed                                                                                         
to instantiate card -22                                                                                                                                        
...                                                                                                                                                            
[   79.769445] bxt_da7219_max98357a: probe of glk_da7219_max98357a                                                                                             failed with error -22   

Fixes to #1001 ,  #1183 and #1374 do not help as e.g. 5.5-rc1 has all the fixes included and the error still happens.

**Comment by kv2019i** [comment]
FYI @yongzhi1 and @cujomalainey 
I've still not been able to reproduce this myself on any device (including a GLK device running ChromeOS, but will continue to try ith this one). As it seems we have to gather sightings and data from a larger set of devices, filing a bug for tracking.

**Comment by kv2019i** [comment]
@yongzhi1 and @cujomalainey -- I've now reproduced the issue on a GLK Chromebook using a kernel module load-unload stress test.

Flow-wise there is nothing wrong in the sequence, but I did notice a slight difference between legacy-HDA and SOF drivers. If I add an extra GET_PARAMETERS HDA verb to the SOF flow (right after power-up) to imitate what happens with legacy HDA driver, the errors are gone. I'll continue investigating (why this flow change helps and how to turn it into a upstream-acceptable fix).

**Comment by kv2019i** [comment]
I uploaded a potential bugfix at:
https://github.com/kv2019i/linux/commit/4685d86b63370d86b169e8c96ede4b98c0bdd788
https://github.com/kv2019i/linux/tree/topic/cras/l5.4-glk-hdmi-afg-fix

**Comment by cujomalainey** [comment]
Been trying to bisect this but failures go back pretty far. Your branch by itself is fine.

**Comment by kv2019i** [comment]
It seems the above fix does not work on all Bobba devices. I posted a 2nd experimental patch to the above branch:
https://github.com/kv2019i/linux/commit/b3c8d21a566b87c7f8f58c06687cbc1e20c328ff
https://github.com/kv2019i/linux/tree/topic/cras/l5.4-glk-hdmi-afg-fix
... waiting to gather more data whether this helps. Still no signs of this issue in CI or from other reporters.

**Comment by cujomalainey** [comment]
@kv2019i probe works with that second patch and I get devices :smiley_cat: 

I cherry-picked over the top 2 commits to sof-dev and I have playback again. Thanks so much.

**Comment by kv2019i** [comment]
@cujomalainey wrote
> @kv2019i probe works with that second patch and I get devices 😺
> 
> I cherry-picked over the top 2 commits to sof-dev and I have playback again. Thanks so much.

Excellent! :sunglasses: I'll start working out an upstream-worthy patchset. 2nd patch should be easy, but first one may require some more effort to get through.

**Comment by sathya-nujella** [comment]
Hi @kv2019i 
We are seeing this issue in TGL also.
==from dmesg ===
[   69.972113] snd_hda_codec_hdmi ehdaudio0D2: HDMI: failed to get afg sub nodes
[   69.980129] snd_hda_codec_hdmi ehdaudio0D2: patch failed -22
[   69.986539] snd_hda_codec_hdmi ehdaudio0D2: ASoC: failed to probe component -22
[   69.994766] sof_rt5682 tgl_max98357a_rt5682: ASoC: failed to instantiate card -22
[   70.015778] sof_rt5682: probe of tgl_max98357a_rt5682 failed with error -22

**Comment by ranj063** [comment]
@sathya-nujella does the fix provided in comment https://github.com/thesofproject/linux/issues/1642#issuecomment-573076000 help your case too?

**Comment by sathya-nujella** [comment]
yes @ranj063 .. we applied 3 patches from this one: https://github.com/thesofproject/linux/pull/1713
with these patches, afg sub node issue is gone.
Sound card binds good.. tried 8 times power cycling DUT.

**Comment by kv2019i** [comment]
Ack @sathya-nujella -- that is good to know. Please let us know if any errors are seen after applying PR1713.

**Comment by kv2019i** [comment]
#1713 now merged upstream, closing this.
