### ISSUE TITLE
[BUG][TGL][SDW][UCM] Headset status can't be updated in sound setting when unplug/plug in headset.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1653]
**Describe the bug**
With sound setting opened, headset status in sound setting and amixer contents can't be updated.
Closed and reopened sound settings can recover it.

**To Reproduce**
1.Boot up system.
2.Open sound setting.
3.Unplug and plug in headset .
4.Check headset status in sound setting and 'Headphone Jack' and 'Headset Mic Jack' status in amixer contents.

**Reproduce rate**
5/5

**Expected result**
Headset status should update in sound setting when unplug/plug in headset.

**Actual result**
Headset status can't be updated in sound setting when unplug/plug in headset.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 121c751
FW: https://github.com/thesofproject/sof/commits/master commit: 9bae27f
Tplg: Same with TGL FW branch : sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode
[dmesg.log](https://github.com/thesofproject/linux/files/4001191/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4001192/sof_trace.log)

**Comment by plbossart** [comment]
Can you re-run this test with the latest integration/soundwire-latest.

Also please clarify if you have a problem on the playback side (headphone) or on the capture side (headset with mic).

**Comment by sinahuang** [comment]
Test with the latest integration/soundwire-latest(commit:07348fa), issue still can be reproduced. But after issue happened aplay (headphone) or arecod(headset with mic) function is OK and the headset status in sound setting will update at once.

**Comment by ClarexZhou** [comment]
@sinahuang  Is this issue reported with UCM1?  Please close if this's UCM1 issue since won't fix.

**Comment by sinahuang** [comment]
Close for won't fix for UCM1 issue.
