### ISSUE TITLE
[BUG][TGL][SDW]Dmesg warning show "ASoC: can't open codec intel-hdmi-hifi2: -16" when power on with HDMI connected.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1655]
**Describe the bug**
Dmesg show "ASoC: can't open codec intel-hdmi-hifi2: -16" when boot up system with HDMI connected, but not effect aplay HDMI.

**To Reproduce**
1.Boot up with HDMI connected.
2.Check dmesg .

**Reproduce rate**
5/5

**Expected result**
Aplay HDMI/DP successfully, no error.

**Actual result**
"ASoC: can't open codec intel-hdmi-hifi2: -16" occured when boot up system with HDMI connected..

Dmesg：
```
[  348.593939] rt711_rt1308 rt711_rt1308: ASoC: try BE : (not set)
[  348.593940] rt711_rt1308 rt711_rt1308: ASoC: try BE : HDA0.OUT
[  348.593941] rt711_rt1308 rt711_rt1308: ASoC: try BE : HDA1.OUT
[  348.593942]  HDMI2: connected new DPCM playback path HDMI2 -> iDisp2
[  348.593948]  HDMI2: ASoC: found 1 new BE paths
[  348.593949]  iDisp2: ASoC: open playback BE iDisp2
[  348.593952] snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open codec intel-hdmi-hifi2: -16
[  348.593955]  iDisp2: ASoC: BE open failed -16
[  348.593957]  HDMI2: ASoC: failed to start some BEs -16
[  348.593958]  HDMI2: ASoC: BE playback disconnect check for iDisp2
[  348.593959]  HDMI2: freed DSP playback path HDMI2 -> iDisp2
[  348.594005]  HDMI4: ASoC: hw_free FE HDMI4
[  348.594007] sof-audio-pci 0000:00:1f.3: pcm: free stream 8 dir 0
[  348.594010] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  348.594168] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  348.594172]  iDisp4: ASoC: hw_free BE iDisp4
[  348.594187] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  348.594300] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  348.594324]  iDisp4: ASoC: close BE iDisp4
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 121c751+commit:ac42b14 and commit:
7fde475
FW: https://github.com/thesofproject/sof/commits/master commit: 9bae27f
Tplg: Same with TGL FW branch : sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

[dmesg26.log](https://github.com/thesofproject/linux/files/4001921/dmesg26.log)
[sof_trace26.log](https://github.com/thesofproject/linux/files/4001926/sof_trace26.log)

**Comment by sinahuang** [comment]
This issue may relate to https://github.com/thesofproject/linux/issues/1537

**Comment by sinahuang** [comment]
This issue might be related to issue #1652, because  if I reboot successfully without HDMI connected then plug in HDMI to aplay HDMI , error can't be reproduced.

**Comment by dengyangchao** [comment]
Issue can't be reproduced on below platforms:
ICL-U RVP with onboard codec  ALC700 in HDA mode
TGL-U RVP with onboard codec ALC711 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
APL UP2 with codec PCM512 in I2S mode

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev 7fde4754
FW: https://github.com/thesofproject/sof/commits/master commit: 9bae27f

**Comment by sinahuang** [comment]
Issue still can be reproduced on TGL-U RVP with soundwire-latest(commit:921ce33).
[dmesg.log](https://github.com/thesofproject/linux/files/4043703/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4043704/sof_trace.log)

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 921ce33 
FW: https://github.com/thesofproject/sof/commits/master commit: c6baa97
Tplg: Same with TGL FW branch : sof-tgl-rt711-rt1308.tplg
Platform:Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by sinahuang** [comment]
Issue still can be reproduced on TGL-U with sof-dev(commit:075b242)+PR1692.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit: 075b242 + PR1692
FW: http://sof-ci-storage.sh.intel.com/release/sof/tgl-003-drop-stable commit: 1bb517ab
Tplg: Same with TGL FW branch : sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

[dmesg15.log](https://github.com/thesofproject/linux/files/4062675/dmesg15.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4062676/sof_trace.log)

**Comment by kv2019i** [comment]
@sinahuang I see multiple PCM opens in the log. I assume these are from pulseaudio which is opening all the nods during boot. The error code in question (-16) is EBUSY, so all HDMI converters are taken when aplay tries to open it. 

Could the problem be a race between pulseaudio and aplay in this case? You could try disabling pulseaudio temporarily and repeating the test.

**Comment by sinahuang** [comment]
Issue can't be reproduced after disabling pulseaudio.

**Comment by sinahuang** [comment]
Issue can't be reproduced on TGL-RVP with  sof-dev(commit:f19d23b4 ), so closed it.
**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:f19d23b4 
FW:  https://github.com/thesofproject/sof/commits/master commit: 7e88cc0
Tplg: Same with FW branch, rename sof-tgl-rt711-i2s-rt1308.tplg to sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by sinahuang** [comment]
Sorry for wrong operation, because issue #1790 might effect the test result of this issue , so reopen it and keep monitor it. @kv2019i  please help to check this issue.

**Comment by sinahuang** [comment]
For this issue can't effect the function, so closed it.
