### ISSUE TITLE
[BUG][APL-PCM512x]ABI mismatch and aplay -l dispaly no soundcard on mainline kernel

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1657]
**Describe the bug**
ABI mismatch and aplay -l dispaly no soundcard on mainline kernel

**To Reproduce**
1.install  kernel(Sound for next)  +firmware  (master) 
2.sudo reboot
3.aplay -l

**Reproduction Rate**
10/10

**Expected behavior**
"aplay -l" can display PLAYBACK Hardware Devices

**Actual result**
"aplay -l " display no soundcards

```
ubuntu@cd-apl-up2-pcm512x-07:~$ aplay -l
aplay: device_list:270: no soundcards found...
```

```
[    5.300181] random: 7 urandom warning(s) missed due to ratelimiting
[    5.888874] sof-audio-pci 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    5.889212] sof-audio-pci 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    5.889407] sof-audio-pci 0000:00:0e.0: use msi interrupt mode
[    5.889679] sof-audio-pci 0000:00:0e.0: bound 0000:00:02.0 (ops vgt_balloon_space [i915])
[    5.897378] sof-audio-pci 0000:00:0e.0: hda codecs found, mask 4
[    5.953269] sof-audio-pci 0000:00:0e.0: Firmware info: version 1:1:0-9bae2
[    5.953273] sof-audio-pci 0000:00:0e.0: Firmware: ABI 3:12:0 Kernel ABI 3:11:0
[    5.953275] sof-audio-pci 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    5.953277] sof-audio-pci 0000:00:0e.0: Firmware debug build 1 on Dec 25 2019-05:20:06 - options:
                GDB: disabled
                lock debug: disabled
                lock vdebug: disabled
[    5.953316] sof-audio-pci 0000:00:0e.0: warning: unknown ext header type 2 size 0x4d
[    5.953371] sof-audio-pci 0000:00:0e.0: firmware boot complete
[    6.073298] systemd-udevd (291) used greatest stack depth: 12280 bytes left
[    6.628796] Generic FE-GE Realtek PHY r8169-200:00: attached PHY driver [Generic FE-GE Realtek PHY] (mii_bus:phy_addr=r8169-200:00, irq=IGNORE)
[    6.730129] r8169 0000:02:00.0 enp2s0: Link is Down
```
[dmesg1230.log](https://github.com/thesofproject/linux/files/4009433/dmesg1230.log)
[sof_trace1230.log](https://github.com/thesofproject/linux/files/4009434/sof_trace1230.log)

**Environment**
Platform: APL UP2 with I2S PCM512x
Firmware: 9bae27fd https://github.com/thesofproject/sof/commits/master
Kernel: 7d8d3c37 https://kernel.googlesource.com/pub/scm/linux/kernel/git/tiwai/sound.git/+/refs/heads/for-next
Topology: file: tools/topology/sof-apl-pcm512x.tplg same as firmware

**Comment by paulstelian97** [comment]
I'm surprised the topology isn't even trying to load (strict ABI check is enabled in KConfig?). If it's enabled, can you disable it? (the mismatch is important though, but I think it's also important to know if something else is broken as well)

**Comment by Liviali155** [comment]
> I'm surprised the topology isn't even trying to load (strict ABI check is enabled in KConfig?). If it's enabled, can you disable it? (the mismatch is important though, but I think it's also important to know if something else is broken as well)

Strict ABI is disabled  in kconfig,as below:
# CONFIG_SND_SOC_SOF_STRICT_ABI_CHECKS is not set

**Comment by plbossart** [comment]
I don't think it has anything to do with ABI proper but rather this:
[    5.953316] sof-audio-pci 0000:00:0e.0: warning: unknown ext header type 2 size 0x4d

**Comment by xiulipan** [comment]
@plbossart @paulstelian97 key point here is that we do not have bxt_pcm512x machine driver in mainline kernel.
Do we plan to upstream it?

**Comment by plbossart** [comment]
@Liviali155 this is an invalid configuration. The bxt-pcm512x has not been submitted upstream so there's no way you'd ever see a card created.
