### ISSUE TITLE
[CML][BUG]Occurred "rt715 sdw:3:25d:715:0: Clock Stop prepare failed for slave: -61" during suspend/resume with aplay0,5 stress test.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1678]
**Describe the bug**
Occurred "rt715 sdw:3:25d:715:0: Clock Stop prepare failed for slave: -61" during suspend/resume with aplay0,5 stress test. When issue occurred, arecord0,4(RT715) cannot work.

This issue seems same as https://github.com/thesofproject/linux/issues/1636, but issue cannot be reproduced in 500 iterations of suspend/resume without playback or with aplay0,0 playback stress test.

**To Reproduce**

1. Boot up with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x8
2. Run command " aplay -Dhw:0,5 -r48000 -c2 -fs16_le /dev/zero & sudo ./stress-s3.sh 500 1 1"
3. Check logs after stress test.
[stress-s3.sh.txt](https://github.com/thesofproject/linux/files/4039686/stress-s3.sh.txt)

**Reproduced rate**
Round1: run 500 times, failed at 412th time.
Round2: run 500 times, failed at 308th time.

**Expected result**
No error occurred during stress test.

**Actual result**
Occurred "rt715 sdw:3:25d:715:0: Clock Stop prepare failed for slave: -61" during suspend/resume with aplay0,5 stress test.  Arecord0,4 cannot work after issue occurred.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 07348fa
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: 5e5f69e
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode

dmesg:
```
[ 5413.575747] intel-sdw sdw-master-3: sdw_handle_slave_status: start
[ 5413.575751] intel-sdw sdw-master-3: Slave attached, programming device number
[ 5413.576348] intel-sdw sdw-master-3: Msg ignored for Slave 1
[ 5413.576359] rt715 sdw:3:25d:715:0: Clock Stop prepare failed for slave: -61
[ 5413.576367] rt715 sdw:3:25d:715:0: pre-prepare failed:-61
[ 5413.576374] intel-sdw sdw-master-3: prepare clock stop failed -61
[ 5413.576380] intel-sdw sdw-master-3: cannot enable clock stop on suspend
[ 5413.576572] intel-sdw sdw-master-3: SDW Slave Addr: 21025d071500
[ 5413.576578] intel-sdw sdw-master-3: SDW Slave class_id 0, part_id 715, mfg_id 25d, unique_id 1, version 2
[ 5413.576581] intel-sdw sdw-master-3: in sdw_assign_device_num
[ 5413.576584] intel-sdw sdw-master-3: in sdw_assign_device_num
```

[test_412.log](https://github.com/thesofproject/linux/files/4039684/test_412.log)
[s3_test_412_logger_all.log](https://github.com/thesofproject/linux/files/4039685/s3_test_412_logger_all.log)

**Comment by YvonneYang2** [comment]
Will check more times in suspend/resume with all kinds of pipline playback and without playback test.

**Comment by plbossart** [comment]
This looks like a case where the RT715 becomes UNATTACHED during the clock stop sequence. Not sure how this can happen, but it's really tricky to debug

**Comment by plbossart** [comment]
I am a bit puzzled by this bug

a) It's not clear to me why keeping audio playback (be it with hw:0,0 with SoundWire of hw:0,5 with HDMI) would have an impact. In the clock_quirks=0x0 option, we play with pm_runtime reference counts so that the DSP remains powered. @YvonneYang2 can you clarify if using aplay is a requirement to see this issue?

b) This seems to be a case where we suspend, so in theory we lose state, the DSP is not powered,  etc.  It's not clear to me if the Slave becomes UNATTACHED on its own, or as a result of the clock being touched. It'd be interesting to have longer traces to see what happened prior to the error (full dmesg)

c) I suggested a tentative work-around to prevent the Slave from being re-enumerated, but I am not fully happy with the solution. Still if PR #1682 makes the problem go away it'd be a good way to analyze further.

**Comment by RanderWang** [comment]
@YvonneYang2  Can you help to attach test_411.log ? this is important for debugging

**Comment by sinahuang** [comment]
Test 1000 times on CML-H with soudwire-latest(commit:07348fa), issue can't be reproduced.

**Comment by YvonneYang2** [comment]
@RanderWang 
test_411.log is as attached. 

[test_441.log](https://github.com/thesofproject/linux/files/4043619/test_441.log)

**Comment by RanderWang** [comment]
> @RanderWang
> test_411.log is as attached.
> 
> [test_441.log](https://github.com/thesofproject/linux/files/4043619/test_441.log)

thanks.  But it is 441.log, how about 411.log

**Comment by YvonneYang2** [comment]
> > @RanderWang
> > test_411.log is as attached.
> > [test_441.log](https://github.com/thesofproject/linux/files/4043619/test_441.log)
> 
> thanks. But it is 441.log, how about 411.log

Sorry for the wrong log. Here you are test_411.log
[test_411.log](https://github.com/thesofproject/linux/files/4043641/test_411.log)

**Comment by YvonneYang2** [comment]
> I am a bit puzzled by this bug
> 
> a) It's not clear to me why keeping audio playback (be it with hw:0,0 with SoundWire of hw:0,5 with HDMI) would have an impact. In the clock_quirks=0x0 option, we play with pm_runtime reference counts so that the DSP remains powered. @YvonneYang2 can you clarify if using aplay is a requirement to see this issue?

Many sorry for wrong typo in bug description.. Issue is reproduced with clock_quirks=0x8 option, not clock_quirks=0x0 option. Aplay with hw:0,5 is the requirement to see this issue. Only aplay0,5 can reproduce the issue. Suspend/resume with aplay0,0 or without playback cannot reproduce it.

Update: Issue can be reproduced with aplay0,0.

**Comment by plbossart** [comment]
Thanks @YvonneYang2, it actually makes more sense with the quirk 0x8. if the parent device remains active, but SoundWire is suspended things could go sideways indeed.

**Comment by YvonneYang2** [comment]
Tested it 1000 times with latest integration/soundwire-latest + #1683 , issue cannot be reproduced.

**Comment by YvonneYang2** [comment]
Tested it 1000 times with latest integration/soundwire-latest + #1682 , issue cannot be reproduced.

**Comment by YvonneYang2** [comment]
Tested it 300 times with topic/sof-dev(921ce33) + #1692 , issue cannot be reproduced.

**Comment by plbossart** [comment]
PR #1692 is merged, can we retry this test with topic/sof-dev and close if it's no longer relevant?

**Comment by YvonneYang2** [comment]
Tested it 600 times, issue cannot be reproduced on latest topic/sof-dev(top commit:ef67419). Close it.
