### ISSUE TITLE
Kernel panic after system booted

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#170]
Summary:
kernel panic happened after system booted. Only happen on BYT, not found on UP2 and CNL.

[    8.223585] sysfs: cannot create duplicate filename '/bus/platform/devices/bytcr_rt5651'
[    8.223591] CPU: 2 PID: 248 Comm: systemd-udevd Not tainted 4.18.0+ #5
[    8.223593] Hardware name: ADI Minnowboard Turbot D0 PLATFORM/MinnowBoard Turbot, BIOS MNW2MAX1.X64.0097.R01.1709211052 09/21/2017

[    8.223594] Call Trace:
[    8.223606]  dump_stack+0x5c/0x7b
[    8.223613]  sysfs_warn_dup+0x56/0x70
[    8.223617]  sysfs_do_create_link_sd.isra.2+0x98/0xb0
[    8.223622]  bus_add_device+0x77/0x160
[    8.223626]  device_add+0x38c/0x620
[    8.223630]  ? _cond_resched+0x15/0x40
[    8.223633]  platform_device_add+0x10e/0x260

[    8.223904] sof-audio sof-audio: free topology...
[    8.223915] BUG: unable to handle kernel NULL pointer dereference at 00000000000000b0
[    8.224013] PGD 0 P4D 0 
[    8.224048] Oops: 0000 [#1] SMP PTI
[    8.224089] CPU: 2 PID: 248 Comm: systemd-udevd Not tainted 4.18.0+ #5
[    8.224158] Hardware name: ADI Minnowboard Turbot D0 PLATFORM/MinnowBoard Turbot, BIOS MNW2MAX1.X64.0097.R01.1709211052 09/21/2017
[    8.224294] RIP: 0010:snd_soc_tplg_component_remove+0x2e/0x3e0 [snd_soc_core]

[    8.225265] Call Trace:
[    8.225306]  snd_sof_free_topology+0xc0/0xf0 [snd_sof]
[    8.225370]  sof_probe+0x397/0x3d0 [snd_sof]
[    8.225423]  platform_drv_probe+0x3a/0x90
[    8.225470]  ? driver_sysfs_add+0x75/0xd0
[    8.225517]  driver_probe_device+0x2fa/0x470
[    8.225567]  ? __driver_attach+0x100/0x100

Test env:
sof master:
sof tool:
kernel sof-dev:
tplg: test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-codec.tplg

I test with kernel sof-dev commit 1f6c9cfc12eb05218b9d8c8529854cdb09904c11 and found no kernel panic issue. So should be caused by Rander's patch. @RanderWang

Log:
[dmesg-kernel.log](https://github.com/thesofproject/linux/files/2430378/dmesg-kernel.log)

**Comment by RanderWang** [comment]
find root cause. It is caused by a strange usage of machine driver.

**Comment by plbossart** [comment]
What is the status of this bug and is anyone looking at it?

**Comment by ZhendanYang** [comment]
This issue can't be reproduced for a long time. I'll just close it.
