### ISSUE TITLE
[bug]tgl]Dmesg show "intel-sdw sdw-master-0: Link power down failed: -11" after doing s2idle/s3 from idle

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1711]
**Describe the bug**
Dmesg show "intel-sdw sdw-master-0: Link power down failed: -11" after doing s2idle/s3 from idle
Error only seen on TGL HDA,not seen on TGL SDW
Error not seen when do  s2idle/s3 with playback
error not seen without PR 1692,It is a regression caused by PR1692

**To Reproduce**
1.sudo reboot
2.sudo rtcwake -m mem -s 10

**Reproduction Rate**
10/10

**Expected behavior**
Suspend&resume normally

**Actual result**
Dmesg show "intel-sdw sdw-master-0: Link power down failed: -11",suspend again failed

```
test@sh-tgl-rvp-hda-01:~$ sudo rtcwake -m mem -s 10
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Wed Jan 15 15:05:39 2020
rtcwake: write error

```

<details>
 <summary>dmesgerror.log</summary>

````
[  175.922892] intel-sdw sdw-master-0: intel_suspend_runtime start
[  175.922897] intel-sdw sdw-master-0: sdw_cdns_clock_stop: start
[  175.922910] intel-sdw sdw-master-0: Clock is already stopped
[  175.923766] intel-sdw sdw-master-0: Link power down failed: -11
[  175.925290] done.
[  175.926347] thermal thermal_zone2: failed to read out thermal zone (-61)
[  175.926478] PM: suspend exit
[  294.336076] PM: suspend entry (s2idle)
[  294.336891] Filesystems sync: 0.000 seconds
[  294.337349] Freezing user space processes ... (elapsed 0.002 seconds) done.
[  294.339471] OOM killer disabled.
[  294.339472] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[  294.340692] printk: Suspending console(s) (use no_console_suspend to debug)
[  294.353617] intel-sdw sdw-master-0: intel_suspend start
[  294.354282] intel-sdw sdw-master-0: Link power down failed: -11
[  294.354291] PM: dpm_run_callback(): intel_suspend+0x0/0x160 [soundwire_intel] returns -11
[  294.354293] PM: Device sdw-master-0 failed to suspend: error -11
[  294.354295] PM: Some devices failed to suspend, or early wake event detected
[  294.354305] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Scheduling resume work
[  294.354310] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: starting resume work
[  294.354404] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: resume work completed
[  294.801097] snd_hda_codec_realtek ehdaudio0D0: Unable to sync register 0x3b8000. -5
[  294.801117] snd_hda_codec_realtek ehdaudio0D0: Unable to sync register 0x3b8000. -5
[  294.802789] OOM killer enabled.
[  294.802791] Restarting tasks ... 
[  294.802901] intel-sdw sdw-master-0: intel_suspend_runtime start
````
</details>

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: SOF:[tgl-003-drop-stable][1bb517ab
Kernel: Kernel: [Sof-dev][075b2421] +PR1692
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

[dmesg0115.log](https://github.com/thesofproject/linux/files/4063636/dmesg0115.log)
[sof_trace0115.log](https://github.com/thesofproject/linux/files/4063637/sof_trace0115.log)

**Comment by dengyangchao** [comment]
Issue seen on TGL-U RVP ALC711 HDA,  can't be reproduced on CML laptop cedec ALC 3204 in HDA mode

**Comment by Liviali155** [comment]
after disable sdw link used below method, error not seen

add "options soundwire_intel_init sdw_link_mask=0x10"to /etc/modprob.d/alsa-base.conf

**Comment by plbossart** [comment]
@Liviali155 HDaudio and SoundWire are mutually exclusive and share the same pins. I don't think this is a legit configuration to have the master0 enabled along with HDaudio.

Can you send a picture of what your BIOS configuration menu looks like (e.g. the 'advanced menu'

**Comment by Liviali155** [comment]
> HDaudio and SoundWire are mutually exclusive and share the same pins. I don't think this is a legit configuration to have the master0 enabled along with HDaudio.



> @Liviali155 HDaudio and SoundWire are mutually exclusive and share the same pins. I don't think this is a legit configuration to have the master0 enabled along with HDaudio.
> 
> Can you send a picture of what your BIOS configuration menu looks like (e.g. the 'advanced menu'

Set Audio Link Mode as HD Audio link as below picture
 
![524381214](https://user-images.githubusercontent.com/56707932/72486582-48e42980-3846-11ea-8c3b-70651432d00d.jpg)

**Comment by plbossart** [comment]
> > HDaudio and SoundWire are mutually exclusive and share the same pins. I don't think this is a legit configuration to have the master0 enabled along with HDaudio.
> 
> > @Liviali155 HDaudio and SoundWire are mutually exclusive and share the same pins. I don't think this is a legit configuration to have the master0 enabled along with HDaudio.
> > Can you send a picture of what your BIOS configuration menu looks like (e.g. the 'advanced menu'
> 
> Set Audio Link Mode as HD Audio link as below picture
> 
> ![524381214](https://user-images.githubusercontent.com/56707932/72486582-48e42980-3846-11ea-8c3b-70651432d00d.jpg)

you should select the audio link mode "advanced mode" and double-check that you have a valid configuration in the "Advanced configuration submenu"
There is no support planned for HDaudio external codec concurrently with SoundWire. The configuration selected for the links need to match the reworks for your board.

**Comment by Liviali155** [comment]
After set Audio Link Mode as "Advanced Link Config" as below,error not seen


![1091200793](https://user-images.githubusercontent.com/56707932/72488410-da09cf00-384b-11ea-9239-5779de38119f.jpg)

**Comment by Liviali155** [comment]
closed it
