### ISSUE TITLE
[BUG][GLK]Pop noise when do playback and capture Simultaneous via headset

### ISSUE THREAD

**Issue by dengyangchao** [thesofproject/linux#1727]
**Describe the bug**
Pop noise when do playback and capture Simultaneous via headset

**To Reproduce**
1.Reboot system via "sudo reboot"
2.Wait runtime PM to suspend status
3.Insert headset
4.Open one terminal Arecord via "arecord -Dhw:0,1 -r48000 -c2 -fs16_le test.wav -vv -i" 
5.Open another terminal Aplay via "aplay -Dhw:0,1 -r48000 -c2 -fs16_le /dev/zero -vv -i"
6.Pause-release aplay or stop aplay via "ctrl+c"

**Reproduction Rate**
100%

**Expected behavior**
Aplay or arecord normal, no pop noise occur

**Impact**
Pop noise occur

**Environment**
Firmware: 415273fb https://github.com/thesofproject/sof/commits/master
Kernel: ef674192 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-glk-da7219.tplg same as firmware
platform：GLK Chrome with onboard codec DA7219 in I2S mode

**Screenshots or console output**
![Capture](https://user-images.githubusercontent.com/52945407/72587324-d3ed1e80-392f-11ea-9b78-f6b7a78b5483.PNG)

No dmesg error nor error-logger observed
[amixer.txt](https://github.com/thesofproject/linux/files/4075235/amixer.txt)
[dmesg.log](https://github.com/thesofproject/linux/files/4075236/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/4075237/logger.log)

**Comment by dengyangchao** [comment]
When issue occur, back kernel to sof-dev 52ec20e also can reproduce, 
when issue can't reproduce, change kernel to 52e20e and ef67419 both can't reproduce.
So might be hardware issue, and keep issue open to monitor

**Comment by Liviali155** [comment]
Reproduced this issue on below scene
Firmware: 7e88cc01 https://github.com/thesofproject/sof/commits/master
Kernel: f19d23b4 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-glk-da7219.tplg same as firmware
platform：GLK Chrome with onboard codec DA7219 in I2S mode

**Comment by plbossart** [comment]
No information in 16 months and no issue reported by the Chrome team, closing.
