### ISSUE TITLE
[BUG][ICL]Dmesg show "error: failed to reset HDA controller gctl 0x1" when do reboot test

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1735]
**Describe the bug**
Dmesg show "error: failed to reset HDA controller gctl 0x1" when do reboot test

**To Reproduce**
1.add test-reboot.sh to startup Application
2./test -reboot.sh 10

**Reproduction Rate**
1/10

**Expected behavior**
There is no error meaasge in dmesg

**Actual result**
There is error message in dmesg,but can bootup successfully

```
[    2.511530] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    2.511607] sdhci-pci 0000:00:14.5: SDHCI controller found [8086:34f8] (rev 30)
[    2.550686] random: crng init done
[    2.550688] random: 7 urandom warning(s) missed due to ratelimiting
[    2.566214] atkbd serio0: Failed to enable keyboard on isa0060/serio0
[    2.566254] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input3
[    2.614574] sof-audio-pci 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[    2.614579] sof-audio-pci 0000:00:1f.3: error: get caps error
[    2.614736] sof-audio-pci 0000:00:1f.3: error: failed to probe DSP -5
[    2.614738] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -5
[    2.617641] [drm] Initialized i915 1.6.0 20191101 for 0000:00:02.0 on minor 0
[    2.618746] sdhci-pci 0000:00:14.5: SDHCI controller found [8086:34f8] (rev 30)
```
No error sof trace

***Environment***
Platform: ICL-U  RVP with onboard codec ALC700 in HDA mode
Firmware: 415273fb https://github.com/thesofproject/sof/commits/master
Kernel: 674afed2 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

[dmesg_failed_3.log](https://github.com/thesofproject/linux/files/4082474/dmesg_failed_3.log)
[test-reboot.txt](https://github.com/thesofproject/linux/files/4082476/test-reboot.txt)

**Comment by Liviali155** [comment]
Retested 500 times on ICL,reproduced 4times
 Environment
Platform: ICL-U RVP with onboard codec ALC700 in HDA mode
Firmware: 415273fb https://github.com/thesofproject/sof/commits/master
Kernel: 674afed https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by plbossart** [comment]
can you try to comment out this code in hda_dsp_ctrl_get_caps?

````c
	/*
	 * On some devices, one reset cycle is necessary before reading
	 * capabilities
	 */
	ret = hda_dsp_ctrl_link_reset(sdev, true);
	if (ret < 0)
		return ret;
	ret = hda_dsp_ctrl_link_reset(sdev, false);
	if (ret < 0)
		return ret;
````

This was added for SoundWire devices but I could never figure out why this was needed

**Comment by Liviali155** [comment]
> can you try to comment out this code in hda_dsp_ctrl_get_caps?
> 
> ```c
> 	/*
> 	 * On some devices, one reset cycle is necessary before reading
> 	 * capabilities
> 	 */
> 	ret = hda_dsp_ctrl_link_reset(sdev, true);
> 	if (ret < 0)
> 		return ret;
> 	ret = hda_dsp_ctrl_link_reset(sdev, false);
> 	if (ret < 0)
> 		return ret;
> ```
> 
> This was added for SoundWire devices but I could never figure out why this was needed

- ICL HDA RVP will not be manually tested. Will only monitor CI test result recenty,so  I can  only try it later

**Comment by plbossart** [comment]
@Liviali155 is this still current or can we close?

**Comment by plbossart** [comment]
no information provided, closing.
