### ISSUE TITLE
[BUG] 5.5.0-rc7 - the dmic PCM devices gone

### ISSUE THREAD

**Issue by perexg** [thesofproject/linux#1741]
I am trying the vanilla 5.5.0-rc7 kernel and I do not see the DMIC PCM devices on CML with the HDA codec (4ch):

<pre>
[   11.112134] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   11.112210] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   11.327910] snd_soc_skl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   11.328540] snd_soc_skl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   11.390248] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   11.391521] sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   11.391658] sof-audio-pci 0000:00:1f.3: warning: No matching ASoC machine driver found
[   11.391663] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   11.391775] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[   11.391956] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   11.402372] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[   11.402373] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   11.465730] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[   11.465731] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   11.555760] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:4:2-66a5a
[   11.555762] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:11:0 Kernel ABI 3:11:0
[   11.556533] sof-audio-pci 0000:00:1f.3: firmware boot complete
[   11.563085] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:11:0 Kernel ABI 3:11:0
[   11.563088] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp3 Tx not handled
[   11.564077] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec0_in not handled
[   11.564078] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp2 Tx not handled
[   11.564875] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec1_in not handled
[   11.564876] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp1 Tx not handled
[   11.565696] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec0_out not handled
[   11.565697] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Analog CPU Playback not handled
[   11.566530] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec1_out not handled
[   11.566531] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Digital CPU Playback not handled
[   11.566532] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec2_in not handled
[   11.566533] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Alt Analog CPU Playback not handled
[   11.566533] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec2_out not handled
[   11.566534] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Analog CPU Capture not handled
[   11.567360] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp1_out not handled
[   11.567361] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Digital CPU Capture not handled
[   11.568108] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp2_out not handled
[   11.568109] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Alt Analog CPU Capture not handled
[   11.568910] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp3_out not handled
[   11.580853] sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[   11.611982] snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[   11.611984] snd_hda_codec_realtek ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   11.611985] snd_hda_codec_realtek ehdaudio0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[   11.611986] snd_hda_codec_realtek ehdaudio0D0:    mono: mono_out=0x0
[   11.611986] snd_hda_codec_realtek ehdaudio0D0:    inputs:
[   11.611987] snd_hda_codec_realtek ehdaudio0D0:      Mic=0x19
[   11.653640] snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[   11.653644] snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
[   11.653703] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> DMIC48kHz 6 mapping ok
[   11.653712] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> DMIC16kHz 7 mapping ok
[   11.653724] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDA Analog 0 mapping ok
[   11.653738] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDA Digital 1 mapping ok
[   11.653747] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI1 3 mapping ok
[   11.653755] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI2 4 mapping ok
[   11.653765] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI3 5 mapping ok
[   11.666554] input: sof-hda-dsp Mic as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input15
[   11.666605] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input16
[   11.666632] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input17
[   11.666657] input: sof-hda-dsp HDMI/DP,pcm=4 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input18
[   11.666680] input: sof-hda-dsp HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input19

# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #1413 
</pre>

Does anybody have a quick idea what's wrong?

**Comment by plbossart** [comment]
arecord -l ?

**Comment by perexg** [comment]
Huh, you're right. I am probably too much tired today :-) Closing and sorry :-)

**Comment by plbossart** [comment]
> Huh, you're right. I am probably too much tired today :-) Closing and sorry :-)

no worries, I do stuff like this all the time.
