### ISSUE TITLE
[BUG] IPC errors with 5.5.0-rc7

### ISSUE THREAD

**Issue by perexg** [thesofproject/linux#1747]
Running latest signed firmware (1.4.2) with the vanilla 5.5.0-rc7 kernel and it does not work (IPC errors):

<pre>
0:1f.3 Audio device: Intel Corporation Cannon Point-LP High Definition Audio Controller (rev 11)
0:1f.3 0403: 8086:9dc8 (rev 11)

[   11.113534] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   11.113691] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[   11.113916] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   11.125243] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[   11.125244] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   11.185116] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[   11.185118] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   11.274561] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:4:2-66a5a
[   11.274562] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:11:0 Kernel ABI 3:11:0
[   11.275357] sof-audio-pci 0000:00:1f.3: firmware boot complete
[   11.285114] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:11:0 Kernel ABI 3:11:0
[   11.285118] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp3 Tx not handled
[   11.287323] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec0_in not handled
[   11.287324] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp2 Tx not handled
[   11.288206] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec1_in not handled
[   11.288208] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp1 Tx not handled
[   11.288920] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec0_out not handled
[   11.288922] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Analog CPU Playback not handled
[   11.289615] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec1_out not handled
[   11.289616] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Digital CPU Playback not handled
[   11.289618] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec2_in not handled
[   11.289619] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Alt Analog CPU Playback not handled
[   11.289621] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec2_out not handled
[   11.289622] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Analog CPU Capture not handled
[   11.290428] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp1_out not handled
[   11.290429] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Digital CPU Capture not handled
[   11.291550] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp2_out not handled
[   11.291552] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Alt Analog CPU Capture not handled
[   11.292466] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp3_out not handled
[   11.307231] sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[   11.344451] snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[   11.344452] snd_hda_codec_realtek ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   11.344453] snd_hda_codec_realtek ehdaudio0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[   11.344453] snd_hda_codec_realtek ehdaudio0D0:    mono: mono_out=0x0
[   11.344454] snd_hda_codec_realtek ehdaudio0D0:    inputs:
[   11.344454] snd_hda_codec_realtek ehdaudio0D0:      Mic=0x19
[   11.391214] snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[   11.391219] snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
[   11.391285] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> DMIC48kHz 6 mapping ok
[   11.391292] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> DMIC16kHz 7 mapping ok
[   11.391304] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDA Analog 0 mapping ok
[   11.391316] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDA Digital 1 mapping ok
[   11.391323] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI1 3 mapping ok
[   11.391330] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI2 4 mapping ok
[   11.391338] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI3 5 mapping ok
[   11.407572] input: sof-hda-dsp Mic as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input15
[   11.407607] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input16
[   11.407636] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input17
[   11.407662] input: sof-hda-dsp HDMI/DP,pcm=4 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input18
[   11.407690] input: sof-hda-dsp HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input19
[   19.980546] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   19.980553] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
[   19.982229] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   19.982235] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
[   19.983618] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   19.983624] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for iDisp1
[   19.985030] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   19.985036] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for iDisp2
[   19.987346] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   19.987352] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for iDisp3
</pre>

I've tried to disable PM using the snd-sof-pci.sof_pci_debug=1 module parameter, but it does not help. The firmware/topology and user space works with another SOF kernel, so it looks like a regression somewhere. Perhaps, someone will have a quick idea what can be wrong. Thanks.

**Comment by paulstelian97** [comment]
Can you mention platform and everything else for completeness?

**Comment by perexg** [comment]
It's Lenovo Carbon X1 7th gen (CNL).

**Comment by kv2019i** [comment]
@perexg Hmm, this does not look. I tried the same combo on a CFL device (CNL fw, vanilla 5.0.0-rc7 without any extra patches + 1.4.2 fw + plus topology files built from 1.4.2 fw) and could not reproduce this -- SOF loads just fine. I also tried to take topology from latest master, but that works as well (and your logs indicate a matching v11 topology to be used). 

FW logs with sof-logger would be helpful (sof-logger -t -l /lib/firmware/intel/sof/sof-cnl.ldc ) if we can't reproduce this locally.	

FYI @lgirdwood and @plbossart -- potential issue with 1.4.2 release.

**Comment by lgirdwood** [comment]
Adding @slawblauciak for FW, but it could be more kernel or topology specific since it seems HDA related. Firmware log should provide insights though.

**Comment by perexg** [comment]
The problem persists with 5.5.2 kernel. It looks like a timing or usage error:

<pre>
 sof-logger -l  /lib/firmware/intel/sof/signed/debug/sof-cnl.ldc 
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          DAI 2.13     10790900.364583  10790900.000000      src/audio/dai.c:690 	dai_config() error: Component is in active state.
    0      1          IPC          10790904.531250         4.166667        src/ipc/ipc.c:466 	ipc_comp_dai_config() error: comp_dai_config() failed
    0      1         COMP 2.10     10791276.250000       371.718750 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1         COMP 2.13     10791292.291667        16.041666 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1          DAI 1.5      10792556.614583      1264.322876      src/audio/dai.c:690 	dai_config() error: Component is in active state.
    0      1          IPC          10792560.364583         3.750000        src/ipc/ipc.c:466 	ipc_comp_dai_config() error: comp_dai_config() failed
    0      1         COMP 1.2      10793335.156250       774.791687 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1         COMP 1.5      10793351.510417        16.354166 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1          DAI 7.41     10795195.052083      1843.541626      src/audio/dai.c:690 	dai_config() error: Component is in active state.
    0      1          IPC          10795198.750000         3.697917        src/ipc/ipc.c:466 	ipc_comp_dai_config() error: comp_dai_config() failed
    0      1         COMP 7.38     10795752.395833       553.645813 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1         COMP 7.41     10795768.750000        16.354166 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1          DAI 8.49     10797406.822917      1638.072876      src/audio/dai.c:690 	dai_config() error: Component is in active state.
    0      1          IPC          10797410.520833         3.697917        src/ipc/ipc.c:466 	ipc_comp_dai_config() error: comp_dai_config() failed
    0      1         COMP 8.46     10797731.197917       320.677094 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1         COMP 8.49     10797747.760417        16.562500 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1          DAI 9.57     10799397.656250      1649.895874      src/audio/dai.c:690 	dai_config() error: Component is in active state.
    0      1          IPC          10799401.302083         3.645833        src/ipc/ipc.c:466 	ipc_comp_dai_config() error: comp_dai_config() failed
    0      1         COMP 9.54     10799572.187500       170.885422 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1         COMP 9.57     10799588.281250        16.093750 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
</pre>

**Comment by lgirdwood** [comment]
@slawblauciak for bug scrub.

**Comment by perexg** [comment]
Can I help to debug this somehow?

**Comment by lgirdwood** [comment]
@perexg yes, could you enable the IPC debug within the SOF driver (it will fill up dmesg), this should show us the sequence of IPCs (either based on ALSA PCM ops, kcontrol ops or PM ops) that lead to this state.
Fwiw, @mengdonglin and @fkaczmar are looking at the possibility of doing a regular (maybe weekly) "snapshot" release of signed firmware. This would be unvalidated code (except for CI) but would help us in progressing debug of these issues.

**Comment by perexg** [comment]
Please, check https://gist.github.com/perexg/4f6df2f0d03a89b31eb653e94c425504 .

**Comment by perexg** [comment]
Can I help to debug this more? The suspend/resume does not work with 5.5 and Fedora and the behaviour is racy.

**Comment by kv2019i** [comment]
@perexg Our validation run a test on a similar X1 carbon with 5.5.0-rc7 and 1.4.2 and could not reproduce the results. Did some other version of SOF succesfully run on this device? And can you link/attach the exact tplg file you used to this bug? I can ask validation to retest with the same tplg file as you.

**Comment by perexg** [comment]
It's the 1.4.2 tplg file built in docker. I am using this firmware package for Fedora: https://www.alsa-project.org/files/pub/misc/sof/sof-firmware-1.4.2.tar.bz2 . The used topology file is there.

It might be a problem with latest pulseaudio / UCM etc. How do you test the interaction with the user space? I would recommend to do tests with the latest user space packages (Fedora is just an example, I don't know if other distributions are going in this way): https://bugzilla.redhat.com/show_bug.cgi?id=1772498 .

It is not ideal, when you don't see the problem from logs even if the topology files are broken.

**Comment by perexg** [comment]
Ok, the IPC errors are visible also without pulseaudio (it seems sufficient to run aplay).

**Comment by perexg** [comment]
BTW: Could you point me to your tested .tplg file?

**Comment by lgirdwood** [comment]
@xiulipan @fredoh9 how far up the stack is CI today ? Do we include Pulseaudio and UCM in the test suite today or is it still TODO ?
@ClarexZhou can you provide @perexg with the name of the topology file you tested.

**Comment by kv2019i** [comment]
@perexg wrote:
> BTW: Could you point me to your tested .tplg file?

@ClarexZhou Can you provide the tplg file you used in the test?

> It is not ideal, when you don't see the problem from logs even if the topology files are broken.

Fully agreed. The rootcause is probably something else, but good to check the topology files just in case. In the logs you shared, there is actually a full cycle of setting up a stream, starting and stopping it and the errors seem to be happening at end with  PCM_TRIGGER_STOP for the dai link. At this step it sends a link config IPC to free te DMA channel, but this fails for some reasons:

ref: https://gist.github.com/perexg/4f6df2f0d03a89b31eb653e94c425504
[   14.940348] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   19.948288] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 6 dir 1 cmd 0
[   19.948299] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[   19.948526] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[...]
[   19.948933] sof-audio-pci 0000:00:1f.3: pcm: close stream 6 dir 1
[   19.950553] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   19.950730] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   19.950736] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
[   19.950741]  Analog Playback and Capture: ASoC: trigger BE failed -22

... but we should be hitting this as well on other devices.
@ranj063 Does this ring any bell? I remember we had patches to change the DMA stop ordering, but based on my review, all those patches are in upstream.

**Comment by perexg** [comment]
It's not related to TRIGGER_STOP. I see this also after TRIG_START:

<pre>
   46.160087] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   46.160527] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   46.161372] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 1
[   46.161626] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   46.161747] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   46.868040] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   46.868182] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[   46.868188] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
[   46.868193]  Analog Playback and Capture: ASoC: trigger BE failed -22
[   46.868197]  HDA Analog: ASoC: trigger FE cmd: 0 failed: -22
[   46.868266] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 0
[   46.868271] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   46.868488] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   46.868548] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   46.868752] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[   46.868833] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 0
[   49.015446] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   49.015702] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
</pre>

And the weird thing - DSP / driver is unable to recover from S3:

<pre>
[  271.341163] sof-audio-pci 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3
[  275.837832] sof-audio-pci 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3
[  283.928420] sof-audio-pci 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3
[  290.803861] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[  290.803875] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000040 at  00000048
[  290.803882] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[  290.806980] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[  290.806995] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
[  290.807012] sof-audio-pci 0000:00:1f.3: loading firmware
[  290.807019] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000002 at  00000048
[  290.807025] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[  290.807032] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[  290.807038] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000004 at  00000044
[  290.807040] sof-audio-pci 0000:00:1f.3: booting DSP firmware
[  290.808402] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[  293.915223] sof-audio-pci 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[  293.915241] sof-audio-pci 0000:00:1f.3: error: load fw failed ret: -110
[  293.915282] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
[  293.915290] sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
[  293.915293] sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
</pre>

It seems that DSP is not working correctly (PM?). The same firmware / topology combo works with other kernels which I can test. Can I trace PM transitions?

**Comment by ClarexZhou** [comment]
Error also not seen when using this firmware package for Fedora: https://www.alsa-project.org/files/pub/misc/sof/sof-firmware-1.4.2.tar.bz2. I'm test on lenovo x1 yoga @perexg  I am using tplg v1.4.2/topology/intel/sof-hda-generic-4ch.tplg from https://github.com/thesofproject/sof-bin/commit/162c2320ab794cc540c32af5ed743bfa2aa607df, and fw v1.4.2/firmware/intel/intel-signed/sof-cnl-v1.4.2.ri, rename to sof-cnl.ri.    Could you please try on this?

**Comment by xiulipan** [comment]
@lgirdwood PA will not be enabled in CI for now as it will randomly hold the PCM and we could not continue the test. 
The UCM test is WIP as we need a way to update the alsalib to support UCM v2.

**Comment by lgirdwood** [comment]
@slawblauciak could this be DMA STOP/DRAIN related (i.e. channel never goes back to idle) ? This would cause the subsequent stream issues and could potentially break component state machine/suspend ?
@perexg are you able to dump FW logs with sof-logger ?

**Comment by perexg** [comment]
This is the simplest log with IPC error (booted without pulseaudio, invoked aplay):

<pre>
[  649.092936] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[  649.092942] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[  649.092945] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[  649.092947] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[  649.094376] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  649.094545] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  649.094594] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 0
[  649.094601] sof-audio-pci 0000:00:1f.3: generating page table for 00000000fde50935 size 0xffc0 pages 16
[  649.094679] sof-audio-pci 0000:00:1f.3: stream_tag 1
[  649.094691] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  649.094889] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  649.096115] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 1
[  649.096644] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  649.096798] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  649.659940] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  649.660187] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[  649.660193] sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
[  649.660197]  Analog Playback and Capture: ASoC: trigger BE failed -22
[  649.660200]  HDA Analog: ASoC: trigger FE cmd: 0 failed: -22
[  649.660267] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 0
[  649.660273] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  649.660524] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  649.660609] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  649.660830] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  649.660927] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 0
</pre>

<pre>
# sof-logger -l  /lib/firmware/intel/sof/signed/debug/sof-cnl.ldc 
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          DAI 1.5     797734551.093750 797734528.000000      src/audio/dai.c:690 	dai_config() error: Component is in active state.
    0      1          IPC         797734555.156250         4.062500        src/ipc/ipc.c:466 	ipc_comp_dai_config() error: comp_dai_config() failed
    0      1         COMP 1.2     797734964.375000       409.218750 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
    0      1         COMP 1.5     797734980.572917        16.197916 rc/audio/component.c:172 	comp_set_state() error: wrong state = 5, COMP_TRIGGER_RESET
</pre>

**Comment by perexg** [comment]
The used topology file (sof-hda-generic-idisp-4ch.tplg) is identical to file in your sof-bin repo. Also, it works with another kernel. I will try to compare code and the kernel config again.

**Comment by perexg** [comment]
I found it. I added a wrong check for the old firmware to allow booting 1.3 SOF FW with new kernels, but this check did not pass against corrected fw version number in 1.4.2:

https://github.com/thesofproject/sof/issues/2102
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-November/159055.html

The condition should be `if (v->abi_version > SOF_ABI_VER(3, 7, 0)) {` .

I will resend a better patch to the alsa-devel mailing list with the better commit message.

**Comment by perexg** [comment]
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-February/163649.html

**Comment by kv2019i** [comment]
@perexg Excellent, that's good news! As and we didn't have the "ASoC: SOF - topology - do not change the link triger order for old firmware" patch in vanilla upstream, we did not hit this. But ok, that makes sense. I'll test your patch your patch as well.

**Comment by kv2019i** [comment]
Continued discussion on alsa-devel:
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-February/163892.html

@perexg If you are ok with the solution, I can close this bug.

**Comment by kv2019i** [comment]
Priority P1->P2 -- only happens with old FW.

**Comment by perexg** [comment]
Ok, I would close this, too. Appearently, my code has a wrong test and the new kernels don't require this hack for the older firmware, too. Thank you for your support.
