### ISSUE TITLE
TGL: Sound card does not bind some times, showing hda codec probe error

### ISSUE THREAD

**Issue by sathya-nujella** [thesofproject/linux#1756]
Log shows these errors:
[   19.827200] sof-audio-pci 0000:00:1f.3: codec #2 probe error, ret: -5
[   19.827378] sof-audio-pci 0000:00:1f.3: no hda codecs found!

response is not right for HDA commands:
[ 18.458082] sof-audio-pci 0000:00:1f.3: HDA codec sending probe
[ 19.460230] sof-audio-pci 0000:00:1f.3: HDA codec #2 probe STATUS: response: ffffffff

Our Chrome kernel already has the patches from:
https://github.com/thesofproject/linux/pull/1713/commits

**Comment by kv2019i** [comment]
I believe this is now fixed with #1764 and #1767 -- combined patch is sent to alsa-devel today. Ok to close @sathya-nujella ?

**Comment by mengdonglin** [comment]
@sathya-nujella @kv2019i close this bug atm. We can reopen this bug if it can still be reproduced with the fixes. Thanks.
