### ISSUE TITLE
[BUG][SOF DRIVER] the system will hang when suspending/resuming if sof_probe_continue() fails

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#1762]
This issue is reproduced on sof-v5.0 and mainline-kernel-5.3, and I guess this issue also exists in the latest mainline kernel.

After enabled CONFIG_SND_SOC_SOF_PROBE_WORK_QUEUE (it is enabled by default), the sof init is divided into 2 phases, if the 2nd phase fails (sof_probe_continue), the 1st phase ( sof_pci_probe) still thinks the init is successful, and the snd_sof_suspend()/resume() will be called; apart from that, if the 2nd phase finishes loading the hda codec module, it will not release/unload them if the 2nd phase fails, and the suspend/resume in those codec modules will also be called, that is a problem too.

To reproduce this bug, just remove the /lib/firmware/intel/sof folder and reboot, then do s3 test.

**Comment by plbossart** [comment]
it's fixed in the latest code, we worked on this with Takashi and @kv2019i 

https://github.com/thesofproject/linux/pull/1746/commits

**Comment by mengdonglin** [comment]
Thanks @plbossart We'll apply and check the fix on https://github.com/thesofproject/linux/tree/release/sof-v5.0

**Comment by ClarexZhou** [comment]
Error can be reproduced on sof-v5.0 + cml-hda-dmic-002-drop-stable after removing sof folder.
Error not seen on latest sof-dev + master

**Comment by mengdonglin** [comment]
Close this issue. We won't backport the fix on sof-v5.0 and mainline-kernel-5.3.
