### ISSUE TITLE
[SOF-V5.0] the sof driver randomly fails on a Dell machine

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#1770]
When problem happens, the dmesg will print out:
[   50.211793] sof-audio-pci 0000:00:1f.3: CORB reset timeout#1, CORBRP = 0

Whenever we saw the CORB  reset timeout, the audio will fail to work and dmesg print the error logs as below:

sof-audio-pci 0000:00:1f.3: error: timeout waiting for stream reset
sof-audio-pci 0000:00:1f.3: error: hdac prepare failed: ffffff92
sof-audio-pci 0000:00:1f.3: error: dma prepare for fw loading err: ffffff92
sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x80010000 size 120
sof-audio-pci 0000:00:1f.3: error: status = 0x001d003c panic = 0x00000001
sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
sof-audio-pci 0000:00:1f.3: ASoC: can't set Analog CPU DAI hw params: -110
 Analog Playback and Capture: ASoC: hw_params BE failed -110
 HDA Analog: ASoC: hw_params BE failed -110
sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60030000 size 12
sof-audio-pci 0000:00:1f.3: error: status = 0x001d003c panic = 0x00000001
sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x80010000 size 120
sof-audio-pci 0000:00:1f.3: error: status = 0x001d003c panic = 0x00000001
sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
sof-audio-pci 0000:00:1f.3: ASoC: can't set Analog CPU DAI hw params: -110
 Analog Playback and Capture: ASoC: hw_params BE failed -110
 HDA Analog: ASoC: hw_params BE failed -110
sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60030000 size 12
sof-audio-pci 0000:00:1f.3: error: status = 0x001d003c panic = 0x00000001
sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x80010000 size 120
sof-audio-pci 0000:00:1f.3: error: status = 0x001d003c panic = 0x00000001
sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
sof-audio-pci 0000:00:1f.3: error: failed to set dai config for Analog Playback and Capture
sof-audio-pci 0000:00:1f.3: ASoC: can't set Analog CPU DAI hw params: -110
 Analog Playback and Capture: ASoC: hw_params BE failed -110
 HDA Analog: ASoC: hw_params BE failed -110
....

**Comment by jason77-wang** [comment]
This is the dmesg when problem happens:
[fail1.txt](https://github.com/thesofproject/linux/files/4169945/fail1.txt)

**Comment by jason77-wang** [comment]
This is the dmesg we met this problem on the 2nd time:

[fail2.txt](https://github.com/thesofproject/linux/files/4169949/fail2.txt)

**Comment by jason77-wang** [comment]
The firmware we are using is v1.3-0f73628

**Comment by jason77-wang** [comment]
This is the lspci.txt for that machine.
[lspci.txt](https://github.com/thesofproject/linux/files/4170437/lspci.txt)

**Comment by plbossart** [comment]
@jason77-wang can you please test with the latest topic/sof-dev kernel - and a more recent firmware? this 1.3 thing is from 6 months ago.

That would help us check if there's a real problem with the hardware, or if this is a backport issue.
I've never seen this CORB reset error personally

**Comment by jason77-wang** [comment]
could not reproduce this issue on other machines, probably this is a hw issue. close this bug first.
