### ISSUE TITLE
[GLK] Suspend/resume failed at second time with HDMI/DP connected

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#178]
How to reproduce:
1.  sudo suspend_stress_test -c 10
chronos@localhost ~ $ sudo suspend_stress_test -c 10
Password:
Running 10 iterations with:
  suspend: 5-10 seconds
  wake: 5-10 seconds
  backup_rtc: false
  errors_fatal: true
  fw_errors_fatal: true
  bugs fatal:  true
  warnings fatal:  false
  crcs fatal:  true
  suspend command: powerd_dbus_suspend --delay=0
  wakeup source to ignore: none
  record_dmesg_dir:
  pm_print_times:  true
powerd start/running, process 2684
tlsdated stop/waiting
Suspend     1 of 10: sleep for 6 seconds... wake for 10 seconds...
Suspend     2 of 10: sleep for 10 seconds...Suspend failed.

powerd start/running, process 3076
tlsdated start/running, process 3094

Finished 2 iterations.
Suspend_failures: 1
Firmware log errors: 0
s0ix errors: 0

The output shows that suspend failed at the second time. without HDMI/DP, suspend/resume work well.

Test ENV:
SOF: 22fa01d059589b4710c12f1e8718ffdb73d75f18 branch: glk-003-drop-stable
SOFT: 6157e899e21792885766c018a6c579122eea502d branch: master
kernel: 274bfc6031d320a73308a0e5c93bc774ade6664a branch: topic/cros-sof-v4.14-rebase

[dmesg.log](https://github.com/thesofproject/linux/files/2455260/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/linux/files/2455262/rmbox-t.log)

**Comment by ranj063** [comment]
@keqiaozhang is this behaviour seen after you start audio playback or without audio playback?

**Comment by keqiaozhang** [comment]
@ranj063 
This issue can be reproduced without audio playback, only need to connect the HDMI or DP monitor.

**Comment by ranj063** [comment]
@keqiaozhang can we close this issue now that it works with the updated ucm?

**Comment by keqiaozhang** [comment]
@ranj063 
Unfortunately, this issue still can be reproduced with the updated UCM,  Confirmed that Pin*-Port* and hif*-* are set correctly in amixer setting and both two Yorp boards get the same result.

**Comment by mengdonglin** [comment]
Keqiao verified that PR #186 can fix this issue.

**Comment by keqiaozhang** [comment]
This issue is almost fixed except for one case: with playing audio on HDMI via command line(console), suspend/resume will cause system reboot.  Since this is not a common case for user, so adjust the priority as P2.

**Comment by plbossart** [comment]
@keqiaozhang can we have information on this? Anything that causes a system reboot is pretty much a P1 bug in my book?

**Comment by keqiaozhang** [comment]
I will re-test this issue with new kernel branch(debug/cros-sof-v4.14-rebase ) and update the result soon.

**Comment by keqiaozhang** [comment]
I still can reproduce this issue under the following condition：
1. run aplay -Dhw:0,5 -f dat -c 2 audio.wav via commad line(shell console)
2. do suspend/resume in another console.

Tested with:
soft-master:4ac9248f
sof-master:43da16
kernel-debug/cros-v4.14-rebase: 90eee4

**Comment by keqiaozhang** [comment]
This issue is fixed on Ranjani's personal kernel branch-cros-sof-v4.14-rebase.
I will close this issue once the google release branch is updated(thesofproject/linux/tree/topic/cros-sof-v4.14).

kernel driver- ranja063-cros-sof-v4.14-rebase:a38231
sof-master:1607737
soft-master:2cd668c

**Comment by keqiaozhang** [comment]
Confirmed that this issue is fixed.
Kernel-topic/cros-sof-v4.14-rebase: a38231
DSP FW-origin/glk-004-drop-stable: 1f79920
Topology-origin/master: 5894ed
