### ISSUE TITLE
[bug][tgl]"Unable to install hw params" showed when run multipipeline

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1783]
**Describe the bug**
"Unable to install hw params"  showed when run multipipeline
After issues reproduced, all the pipeline can not work,only reboot can recovery

**To Reproduce**
1.connected with HDMI and DP
2. ./multiplex_pipeline-test.sh pcm0p pcm3p pcm4p pcm0c pcm6c pcm7c

**Reproduction Rate**
Run 300 times,failed at 83th

**Expected behavior**
Aplay/Rrecord can work when test Multipipeline 

**Actual result**
Tips"unable to install hw params",aplay/arecord failed
<img width="283" alt="Capture" src="https://user-images.githubusercontent.com/56707932/74303365-77e1b280-4d94-11ea-9226-67723f7d2b0f.PNG">

There is no error dmesg and soflogger

Platform: TGL-U RVP with onboard codec ALC711 in HDA modeFirmware: 
Firmware: 274049c5 https://github.com/thesofproject/sof/commits/master
Kernel: 91ed8f42 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

[multipipeline_test_83_all_logger.log](https://github.com/thesofproject/linux/files/4189849/multipipeline_test_83_all_logger.log)
[multipipeline_test_83_dmesg.log](https://github.com/thesofproject/linux/files/4189853/multipipeline_test_83_dmesg.log)

**Comment by sinahuang** [comment]
Issue also can be reproduced on TGL-U RVP with soundwire-latest(commit: 91ed8f4).
Test for 300 times, failed at 65th time, after issue happened all pipeline can't work and only reboot can recover.
[multipipeline_test_64_dmesg.log](https://github.com/thesofproject/linux/files/4190347/multipipeline_test_64_dmesg.log)
[multipipeline_test_64_all_logger.log](https://github.com/thesofproject/linux/files/4190353/multipipeline_test_64_all_logger.log)

[multipipeline_test_65_all_logger.log](https://github.com/thesofproject/linux/files/4190348/multipipeline_test_65_all_logger.log)
[multipipeline_test_65_dmesg.log](https://github.com/thesofproject/linux/files/4190349/multipipeline_test_65_dmesg.log)




**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:91ed8f4 
FW:  https://github.com/thesofproject/sof/commits/master commit: 274049c
Tplg: Same with FW branch, rename sof-tgl-rt711-i2s-rt1308.tplg to sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by paulstelian97** [comment]
Anything relevant in etrace? Whenever I get hangs, etrace holds info that didn't reach regular DMA trace on my platform, this might be true in this case as well. (sof-logger without -t option)

**Comment by fredoh9** [comment]
I found same issue in APL. Multipipeline test with many iteration easily reproduce this, I had same issues in some of platforms, so I would say this is not just APL or TGL problem.
In this case, i was running check-pause-resume-playback-100.sh in **APL_UP2_NOCODEC**.

```
2020-02-11 22:35:43 UTC [REMOTE_INFO] Entering expect script with: aplay -D hw:0,0 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
spawn aplay -D hw:0,0 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
aplay: set_params:1363: Unable to install hw params:


kernel: [ 3521.366244] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
kernel: [ 3521.869655] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x60010000 size 108
kernel: [ 3521.869665] sof-audio-pci 0000:00:0e.0: info: preventing DSP entering D3 state to preserve context
kernel: [ 3521.869673] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
kernel: [ 3521.869719] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
kernel: [ 3521.869729] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
kernel: [ 3521.869733] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
kernel: [ 3521.869740] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
kernel: [ 3521.869744] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
kernel: [ 3521.869750] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
kernel: [ 3521.869756] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -110
kernel: [ 3521.869766]  Port0: ASoC: hw_params FE failed -110
```

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:91ed8f4
FW: https://github.com/thesofproject/sof/commits/master commit: 274049c
TPLG: sof-apl-nocodec.tplg
[check-pause-resume-playback-100.zip](https://github.com/thesofproject/linux/files/4193853/check-pause-resume-playback-100.zip)
[dmesg.txt](https://github.com/thesofproject/linux/files/4194508/dmesg.txt)

**Comment by ranj063** [comment]
> I found same issue in APL. Multipipeline test with many iteration easily reproduce this, I had same issues in some of platforms.
> In this case, i was running check-pause-resume-playback-100.sh in **APL_UP2_NOCODEC**.

@fredoh9 your case seems to be because of the tplg mismatch. Could you please make sure you're using the right tplg and confirm this is still a problem?

**Comment by fredoh9** [comment]
@ranj063 I'm using daily build and I get the tplg file also from daily build. Do you have any proof I have tplg mismatch?
And this is part of daily test suite. 1-14 test cases was passed, this was 15th test case.

**Comment by Liviali155** [comment]
Bi-sect result: It is a kernel  regression caused by  commit  [#877eab2d](https://github.com/thesofproject/linux/commit/877eab2da69a60545b36246e348d16a04583d11f)

**Comment by YvonneYang2** [comment]
Issue can be reproduced on SDW CML-U laptop when run multipipline stress test. Failed at 34th time. 

Kernel: topic/sof-dev (f19d23b)
FW: master (7e88cc0)

[multipipeline_test_34_dmesg.log](https://github.com/thesofproject/linux/files/4198067/multipipeline_test_34_dmesg.log)

**Comment by aiChaoSONG** [comment]
issue also observed on Helios with sof-test before 14th, Feb:
- clone sof-test to local: `git clone https://github.com/thesofproject/sof-test`
- go to `sof-test/test-case/`
- export TPLG=/lib/firmware/intel/sof-tplg/your-tplg-name
- run `./multiple-pipeline-playback -l 50`, test case will PASS
- run `./multiple-pipeline-capture -l 50`, test case FAILED (unable to install hw params)
- no dmesg error nor sof-logger error.
seems fixed by accidentally on UTC+8 Valentine‘s Day？

**Comment by Liviali155** [comment]
Tested 300 times with TGL-U SOF HDA on 20200214,issue can not be reproduced

Platform: TGL-U RVP with onboard codec ALC711 in HDA modeFirmware:
Firmware: 4d17d0de https://github.com/thesofproject/sof/commits/master
Kernel: daf71dce https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by sinahuang** [comment]
Tested 300 times with TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode, issue can not be reproduced.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:daf71dce
FW:  https://github.com/thesofproject/sof/commits/master commit: 36d4c9f
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by Liviali155** [comment]
Tested 500 times with TGL-U SOF HDA on 20200217,issue can not be reproduced

Platform: TGL-U RVP with onboard codec ALC711 in HDA modeFirmware:
Firmware: b206b7a8 https://github.com/thesofproject/sof/commits/master
Kernel: b2d98237 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware
