### ISSUE TITLE
[BUG][UCM][SDW]UCM need update.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1788]
**Describe the bug**
Based on the latest topic/sof-dev(top commit: f19d23b) and master branch(top commit: 7e88cc0), ucm applied  https://github.com/thesofproject/alsa-ucm-conf/pull/24 on SDW CML-U laptop cannot work now. It blocked the test related ucm. 

The ucm which cannot work: https://github.com/thesofproject/alsa-ucm-conf/commits/master(top commmit:39528c5) + https://github.com/thesofproject/alsa-ucm-conf/pull/24 

[amixer_contents.txt](https://github.com/thesofproject/linux/files/4197318/amixer_contents.txt)
![Screenshot from 2019-11-26 21-52-54](https://user-images.githubusercontent.com/50347470/74417666-0b44e180-4e82-11ea-9d24-81359e3ce0a1.png)

**Comment by plbossart** [comment]
@RanderWang can you look into this? It's likely a board name change.

**Comment by plbossart** [comment]
This is caused by a topology change: https://github.com/thesofproject/sof/issues/2385

**Comment by plbossart** [comment]
[HiFi.txt](https://github.com/thesofproject/linux/files/4202207/HiFi.txt)

Temporary work-around: cp Hifi.txt /usr/share/alsa/ucm/sof-sdw-rt711-1308-715/HiFi

**Comment by RanderWang** [comment]
@YvonneYang2  what's the status with 1796 ? Does it work ?

**Comment by YvonneYang2** [comment]
@RanderWang  
Tested it with topic/sof-dev(top commit:b2d9823)+PR1769+PR1796 and latest master branch FW, using https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 + https://github.com/thesofproject/alsa-ucm-conf/pull/24 for multi profile ucm, it can work.
