### ISSUE TITLE
[TGL][BUG][SDW]Arecord 0,1 (rt711) can't capture the sound.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1789]
**Describe the bug**
Arecord(0,1) can capture but the captured sound file is empty, headset mic jack in amixer contents/alsamixer display on. 

Amixer contents:
[amixer contents.txt](https://github.com/thesofproject/linux/files/4197561/amixer.contents.txt)

**To Reproduce**
1.Boot up system successfully.
2.Run "arecord -Dhw:0,1 -fs16_le -c2 -r 48000 -vv -i 11.wav".

**Reproduce rate**
5/5

**Expected result**
Arecord0,1 (rt711)should work normally.

**Actual result**
Arecord(0,1) can't capture the sound.
![Screenshot from 2018-01-29 00-29-51](https://user-images.githubusercontent.com/56706782/74420329-36313480-4e86-11ea-88bc-ef903e5e7d3d.png)

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:f19d23b4 
FW:  https://github.com/thesofproject/sof/commits/master commit: 7e88cc0
Tplg: Same with FW branch,  sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

[sof_trace13.log](https://github.com/thesofproject/linux/files/4197388/sof_trace13.log)
[dmesg13.log](https://github.com/thesofproject/linux/files/4197393/dmesg13.log)

**Comment by sinahuang** [comment]
Bi-sect result: It is a kernel regression caused by commit #https://github.com/thesofproject/linux/commit/f19d23b45e97def172b5538c50572d7f6c666ed8   @RanderWang , please help to check it.

**Comment by plbossart** [comment]
> Bi-sect result: It is a kernel regression caused by commit #[f19d23b](https://github.com/thesofproject/linux/commit/f19d23b45e97def172b5538c50572d7f6c666ed8) @RanderWang , please help to check it.

it's more like you need to install the proper topology file?

**Comment by RanderWang** [comment]
@sinahuang   if " amixer cset numid=2 on;    amixer cset numid=3 on" works, could you help to close this bug ? thanks!

**Comment by sinahuang** [comment]
> @sinahuang if " amixer cset numid=2 on; amixer cset numid=3 on" works, could you help to close this bug ? thanks!

Verified it and it can work, but I think you could give me a PR then I can closed it.

**Comment by RanderWang** [comment]
@sinahuang  The setting is for amixer. It is done in UCM file. NO PR

**Comment by sinahuang** [comment]
Test with latest UCM( https://github.com/RanderWang/intel-UCM/tree/tgl_hdmi commit: a7ff374) in your repo, issue still can be reproduced.

**Comment by plbossart** [comment]
@RanderWang do you have a PR for the UCM files?

**Comment by RanderWang** [comment]
> @RanderWang do you have a PR for the UCM files?

I will create a PR for UCM for TGL RVP.

**Comment by sinahuang** [comment]
Arecord(0,1) can capture sound now on TGL-RVP with latest UCM commit: a257780, but now I need to unmute headset in alsamixer manually.

**Comment by sinahuang** [comment]
Tested it with latest UCM, issue can't be reproduced on TGL-RVP with codec ALC711 in SDW mode and RT1308 in I2S mode, so closed it

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:8bf1a29
FW:  https://github.com/thesofproject/sof/commits/master commit: 8b59506
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode
