### ISSUE TITLE
[BUG][UCM][SDW][TGL]UCM need update. 

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1790]
**Describe the bug**
 Ucm applied https://github.com/RanderWang/intel-UCM/tree/tgl_hdmi commit:8579a06 on SDW CML-H RVP cannot work now. It blocked the test related ucm. 

amixer contents：
[amixer contents.txt](https://github.com/thesofproject/linux/files/4197552/amixer.contents.txt)

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:f19d23b4 
FW:  https://github.com/thesofproject/sof/commits/master commit: 7e88cc0
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

![Screenshot from 2018-01-29 00-44-25](https://user-images.githubusercontent.com/56706782/74421759-83160a80-4e88-11ea-9779-c35714fd1a19.png)

**Comment by RanderWang** [comment]
@sinahuang  I updated the git repo, please sync it and test. thanks!

**Comment by RanderWang** [comment]
@sinahuang I updated the git repo, please sync it and test. thanks! I don't have a stable device around to test, so I need your help.

**Comment by sinahuang** [comment]
Test with latest UCM( https://github.com/RanderWang/intel-UCM/tree/tgl_hdmi commit: a7ff374) in your repo, issue still can be reproduced.

**Comment by RanderWang** [comment]
I update UCM and validated on my RVP.  But on QA`s device, the error message is :  HiFi is not found.
but the file and path all exist.

**Comment by sinahuang** [comment]
Test with latest UCM commit: a257780, UCM can work now on TGL-RVP, keep monitor it.

**Comment by sinahuang** [comment]
UCM can work now on TGL-RVP, so closed it.
