### ISSUE TITLE
[BUG][GLK] glk_rt5682_max98357a in probe deferral loop

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#1793]
Kernel SHA b2d982370860640838a30fd6927eab57b7de615b
SOF SHA: 01a589581abfc786964e67c00ae7e4580b6a6a29

Running latest kernel on glk chromebook with rt5682 we see this loop running because we are missing a CPU DAI but I can't spot anything particular in the machine driver link that has changed, maybe there was a core change that broke things? Any ideas? This is a blocker.

```
[   30.809389] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link Glk Audio Echo Reference cap
[   30.809403] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link SSP1-Codec
[   30.809411] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link SSP2-Codec
[   30.809419] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link dmic01
[   30.809428] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link iDisp1
[   30.809435] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link iDisp2
[   30.809443] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link iDisp3                                                  
[   30.809677] glk_rt5682_max98357a glk_rt5682_max98357a: ASoC: CPU DAI Echoref Pin not registered
[   30.825873] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link Glk Audio Echo Reference cap
[   30.825890] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link SSP1-Codec
[   30.825898] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link SSP2-Codec
[   30.825906] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link dmic01
[   30.825914] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link iDisp1
[   30.825922] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link iDisp2
[   30.825930] glk_rt5682_max98357a glk_rt5682_max98357a: info: override BE DAI link iDisp3                                                                                                                        
[   30.826145] glk_rt5682_max98357a glk_rt5682_max98357a: ASoC: CPU DAI Echoref Pin not registered
```

**Comment by plbossart** [comment]
The only references I see to 'Echo Reference' are for Front-end dailinks, which should be ignored by SOF.

The only thing that comes to my mind is this patch from @dbaluta ('ASoC: soc-core: Set dpcm_playback / dpcm_capture')

That's directly related to the FE override. Maybe try reverting it?

**Comment by cujomalainey** [comment]
I will try that Tuesday, as a temporary work around I commented out the link but for some reason the rt5682 i2c probe was still not being called even though the module was loaded so it was failing to link

**Comment by cujomalainey** [comment]
Also this is isolated to this machine driver, not the dialog one which makes me wonder if some of the sdw changes in the 5682 driver are possibly causing this

**Comment by keyonjie** [comment]
@sathya-nujella can you help to check this as we don't have the platform here?

**Comment by keyonjie** [comment]
@cujomalainey can you help attach the full dmesg log please?

**Comment by sathya-nujella** [comment]
> @sathya-nujella can you help to check this as we don't have the platform here?

Shipped a BIP DUT to PRC team. DUT reached, but need a coreboot to boot Ubuntu.

**Comment by cujomalainey** [comment]
@keyonjie I will see if I can get some time this week to test this out.

**Comment by cujomalainey** [comment]
@keyonjie it looks like its top of sof-dev is no longer looping, but just hangs. No cards show up in aplay after like 5min
[dmesg.txt](https://github.com/thesofproject/linux/files/4346442/dmesg.txt)

**Comment by cujomalainey** [comment]
I stand corrected. it triggered again. 
[dmesg.txt](https://github.com/thesofproject/linux/files/4346447/dmesg.txt)

**Comment by keyonjie** [comment]
@cujomalainey thanks for the log, we need to do some debugging here, we have just received the BIP here, will start to debug soon.

**Comment by keqiaozhang** [comment]
@cujomalainey 
Please share your chrome kernel branch?  I will try to reproduce your issue with ChromeOS.

**Comment by cujomalainey** [comment]
@keqiaozhang that kernel is a sof-dev kernel
@keyonjie  thanks

**Comment by keqiaozhang** [comment]
@cujomalainey  So you tested it on linux/Ubuntu OS? Or how to run sof-dev on ChromeOS directly?

**Comment by cujomalainey** [comment]
I tested in chromeos. I checkout the linux kernel in chromeos sdk, write my config to src/third_party/chromiumos-overlay/eclass/cros-kernel/x86_64_defconfig

Sometimes tooling doesn't work correctly so I will build in the 5.4 directory rather than 4.14

**Comment by ranj063** [comment]
@plbossart @cujomalainey I looked into the Echoref FE DAI link definition in glk_rt5682_max98357a.c and it turns out that dynamic is not set to 1 for the Echref capture DAI link (as below). This means the DAI link will not be ignored. I believe setting it to 1 will ignore the dai link and solve the issue.

[GLK_DPCM_AUDIO_ECHO_REF_CP] = {
		.name = "Glk Audio Echo Reference cap",
		.stream_name = "Echoreference Capture",
		.init = NULL,
		.capture_only = 1,
		.nonatomic = 1,
		SND_SOC_DAILINK_REG(echoref, dummy, platform),
	},
