### ISSUE TITLE
[BUG][CML]Can't detect Mic jack of combo headset

### ISSUE THREAD

**Issue by qinwan-hp** [thesofproject/linux#1798]
**Describe the bug**
Plug in headset, the headphone jack can be detected, but the mic jack can seldom to be detected.
If prohibit the codec runtime auto-suspend, the headphone and mic jack can be detected normally.
If change to hda driver, the headphone jack and mic jack can be detected normally.

**To Reproduce**
Plugin headset

**Reproduction Rate**
Almost near to 100%

**Expected behavior**
Both headphone and mic jack can be detected.

**Impact**
Cannot record sound if plugin headset

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: a55aa89 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git Tag: 5.3-rc6
    * SOF: fcf6c8c4 https://github.com/thesofproject/sof.git   Tag: v.1.4.1
2) Name of the topology file
    * Topology:  sof-hda-generic-2ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: A notebook with CometLake LP, codec ALC3247 and combo headset 

[codecinfo.txt](https://github.com/thesofproject/sof/files/4058785/codecinfo.txt)
[dmesg.txt](https://github.com/thesofproject/sof/files/4058790/dmesg.txt)
[sof.txt](https://github.com/thesofproject/sof/files/4058792/sof.txt)

**Comment by qinwan-hp** [comment]
@juimonen Original we have hda with CONFIG_SND_HDA_POWER_SAVE_DEFAULT =0 on our platform, so hda is OK.  Change config to  CONFIG_SND_HDA_POWER_SAVE_DEFAULT = 2, I did see the same issue happend. But the failure rate is very low and can be igonored.

**Comment by mengdonglin** [comment]
@qinwan-hp Can you please share your email here or on GitHub personal profile? We want to understand if this is a HP device and who can support from codec driver side. Thanks!

**Comment by qinwan-hp** [comment]
We still do not enable runtime control to make jack detection work normally.
And the crash of FW can be fixed with latest version.
