### ISSUE TITLE
Fix sparse issues in sound/soc/intel and sound/soc/sof/intel

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#18]
We have a number of issues reported by sparse in the core, pcm and ipc/mailbox usage
see log attached generated with make SUBDIRS=sound/soc/sof C=1 

[log.txt](https://github.com/thesofproject/linux/files/2157153/log.txt)

**Comment by keqiaozhang** [comment]
This issue is fixed by https://github.com/thesofproject/linux/pull/17
