### ISSUE TITLE
[TGL][SDW][BUG]RT1308 in I2S mode can't load i2c driver. 

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1806]
**Describe the bug**
RT1308 in I2S mode can't load i2c driver. 

lsmod:
[lsmod19.txt](https://github.com/thesofproject/linux/files/4224544/lsmod19.txt)

**To Reproduce**
1.Boot up system successfully.
2. aplay -l

**Reproduce rate**
5/5

**Expected result**
RT1308 in I2S mode should can be loaded normally.

**Actual result**
RT1308 in I2S mode can't load i2c driver. 

```
[    4.496062] systemd-journald[269]: Received request to flush runtime journal from PID 1
[    4.516398] systemd-journald[269]: File /var/log/journal/ac2eb779b4cc43d8b5f21bac741ef3f0/system.journal corrupted or uncleanly shut down, renaming and replacing.
[    4.581323] acpi PNP0C14:02: duplicate WMI GUID 05901221-D566-11D1-B2F0-00A0C9062910 (first instance was on PNP0C14:01)
[    4.591914] random: crng init done
[    4.591915] random: 7 urandom warning(s) missed due to ratelimiting
[    4.592398] mei_me 0000:00:16.0: enabling device (0000 -> 0002)
[    4.599434] intel-lpss 0000:00:15.0: enabling device (0000 -> 0002)
[    4.612587] i2c i2c-16: Failed to register i2c client 10EC1308:01 at 0x10 (-16)
[    4.614019] i2c i2c-16: failed to add I2C device 10EC1308:01 from ACPI
[    4.629838] intel-lpss 0000:00:15.1: enabling device (0000 -> 0002)
[    4.656840] intel-lpss 0000:00:15.2: enabling device (0000 -> 0002)
[    4.686115] intel-lpss 0000:00:15.3: enabling device (0000 -> 0002)
[    4.691589] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    4.691865] sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    4.691868] sof-audio-pci 0000:00:1f.3: PCI DSP detected
[    4.691879] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[    4.692244] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:861c308+PR1796+pr1769
FW:  https://github.com/thesofproject/sof/commits/master commit: 53d35e49
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

[dmesg.log](https://github.com/thesofproject/linux/files/4224554/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4224555/sof_trace.log)

**Comment by sinahuang** [comment]
Test with kernel on ww08.1 + PR1796 on ww08.1, issue can't be reproduced. I try to test with  kernel on ww08.1 +PR1796 today, but there are some conflicts.

**Comment by RanderWang** [comment]
@sinahuang  thanks for your hard work!

**Comment by RanderWang** [comment]
found root reason.  SND_SOC_1308 should be select in KConfig  for sdw_rt711_rt1308_rt715.
For sdw_rt711_i2s_rt1308 is deleted in KConfig, SND_SOC_1308 is missed.

**Comment by plbossart** [comment]
@sinahuang please retest with #1810

**Comment by sinahuang** [comment]
Issue can't be reproduced after PR#1810 merged, so closed it.
