### ISSUE TITLE
[BUG][CML] System doesn't wake up automatically after suspend to s2idle

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1815]
**Describe the bug**
System can not be wake up auto after suspend in s2idle mode, need to press power key to wake up
Error not seen in deep mode

**To Reproduce**
1.sudo reboot
2.sudo rtcwake -m mem -s 10
3.wait  for system  to wake up automatically (should never wake up, unless you press keyboard)

**Reproduction Rate**
10/10

**Expected behavior**
System will wake up automatically

**Actual result**
System will not wake up auto, need to press power key to wake up

Platform: CML with onboard codec ALC3204 in HDA mode
Firmware: 135cace3 https://github.com/thesofproject/sof/commits/master
Kernel: bad8ea4d https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware

[dmesg0221.log](https://github.com/thesofproject/linux/files/4234141/dmesg0221.log)
[sof_trace0221.log](https://github.com/thesofproject/linux/files/4234143/sof_trace0221.log)

**Comment by Liviali155** [comment]
Bisect result:
Regression caused by kernel  commit 90c55e8d[](https://github.com/thesofproject/linux/commit/90c55e8d8d9c1da3b84b447be13522156c5700c6)

@kv2019i  please check it

**Comment by Liviali155** [comment]
On below platforms also can reproduce this issue
TGL-U RVP with onboard codec ALC711 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
CML Chrome with onboard codec RT5682 and RT1011 in I2S mode

**Comment by sinahuang** [comment]
Issue also can reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode, but  on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode system can't wake after suspend to s2idle and deep mode.

**Comment by kv2019i** [comment]
We merged around 500 patches from upstream, so there's quite a bit to go through. I cannot get this on my CFL and APL systems, but I did get this on a CML system. I will continue bisect now, but at least this warning is printed on the CML:

```
[   66.273261] NETDEV WATCHDOG: enxe46f13f3d535 (ax88179_178a): transmit queue 0 timed out
[   66.273280] WARNING: CPU: 9 PID: 0 at net/sched/sch_generic.c:443 dev_watchdog+0x4c3/0x4d0
[   66.273281] Modules linked in: ax88179_178a usbnet iwlmvm i915 x86_pkg_temp_thermal intel_powerclamp i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sdhci_pci xhci_pci cqhci sysimgblt fb_sys_fops iwlwifi sdhci intel_lpss_pci mei_me intel_lpss drm mei mfd_core processor_thermal_device xhci_hcd intel_soc_dts_iosf intel_pch_thermal i2c_hid int3403_thermal int340x_thermal_zone int3400_thermal acpi_thermal_rel efivarfs
[   66.273299] CPU: 9 PID: 0 Comm: swapper/9 Not tainted 5.6.0-rc2+ #228
[   66.273300] Hardware name: Dell Inc. XPS 17 9700/, BIOS 11.2.20 01/03/2020
[   66.273302] RIP: 0010:dev_watchdog+0x4c3/0x4d0
[   66.273304] Code: ff ff 4c 8b 74 24 10 c6 05 5b 41 56 01 01 4c 89 f7 e8 c1 a3 fa ff 89 d9 48 89 c2 4c 89 f6 48 c7 c7 00 7e 19 b2 e8 4d 9a 46 ff <0f> 0b e9 ff fe ff ff 66 0f 1f 44 00 00 41 57 41 56 4c 8d bf 40 01
[   66.273305] RSP: 0018:ffff888253849da8 EFLAGS: 00010286
[   66.273306] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000001
[   66.273307] RDX: 0000000000000007 RSI: dffffc0000000000 RDI: ffff888253861770
[   66.273308] RBP: ffff888240878440 R08: ffffed104a70c2ef R09: ffffed104a70c2ef
[   66.273309] R10: 0000000000000001 R11: ffffed104a70c2ee R12: ffff88823f66e000
[   66.273310] R13: ffff888240878388 R14: ffff888240878000 R15: ffff88823f66e090
[   66.273311] FS:  0000000000000000(0000) GS:ffff888253840000(0000) knlGS:0000000000000000
[   66.273312] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   66.273313] CR2: 000056227a1ba378 CR3: 0000000286c0e006 CR4: 00000000003606e0
[   66.273313] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   66.273314] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   66.273315] Call Trace:
[   66.273316]  <IRQ>
[   66.273319]  ? qdisc_put+0x30/0x30
[   66.273320]  ? qdisc_put+0x30/0x30
[   66.273323]  call_timer_fn+0x43/0x1c0
[   66.273325]  ? qdisc_put+0x30/0x30
[   66.273326]  run_timer_softirq+0x6e3/0x7e0
[   66.273328]  ? smp_apic_timer_interrupt+0xd5/0x210
[   66.273329]  ? call_timer_fn+0x1c0/0x1c0
[   66.273331]  ? __do_softirq+0x4e/0x446
[   66.273332]  __do_softirq+0x110/0x446
[   66.273335]  irq_exit+0xd6/0xe0
[   66.273336]  smp_apic_timer_interrupt+0xd5/0x210
[   66.273338]  apic_timer_interrupt+0xf/0x20
[   66.273339]  </IRQ>
```

**Comment by YvonneYang2** [comment]
Issue can be reproduced on CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode.

Then tested it with deep mode suspend/resume stress test. System works fine but demsg shows failed info like below:
```
[  115.392608] int-sdw int-sdw.0: IO transfer timed out, cmd 2 device 1 addr 40 len 1
[  115.392614] int-sdw int-sdw.0: trf on Slave 1 failed:-110
[  115.392617] int-sdw int-sdw.0: SDW_SCP_INT1 read failed:-110
[  115.392621] int-sdw int-sdw.0: Slave 1 alert handling failed: -110
[  115.392673] int-sdw int-sdw.1: IO transfer timed out, cmd 2 device 1 addr 40 len 1
[  115.392677] int-sdw int-sdw.1: trf on Slave 1 failed:-110
[  115.392680] int-sdw int-sdw.1: SDW_SCP_INT1 read failed:-110
[  115.392684] int-sdw int-sdw.1: Slave 1 alert handling failed: -110
```

[test_1.log](https://github.com/thesofproject/linux/files/4235868/test_1.log)
[s3_test_1_logger_all.log](https://github.com/thesofproject/linux/files/4235869/s3_test_1_logger_all.log)
[s3_test_1_logger_error.log](https://github.com/thesofproject/linux/files/4235871/s3_test_1_logger_error.log)

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit: dfd3776
FW: https://github.com/thesofproject/sof/commits/master commit: c35e1aa
tplg: https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 
commit: 39528c5  +  https://github.com/thesofproject/alsa-ucm-conf/pull/24

**Comment by kv2019i** [comment]
Ok, found the cuplprit, see #1819 

I'll report this upstream and let's see how to solve this. It seems this is specific to waking up from RTC timer. 
UPDATE: reported on linux-acpi list -> https://lore.kernel.org/linux-acpi/alpine.DEB.2.21.2002211426350.2957@eliteleevi.tm.intel.com/T/#u

**Comment by plbossart** [comment]
@YvonneYang2 @Liviali155 @sinahuang can you check with PR #1820 applied?

**Comment by Liviali155** [comment]
> @YvonneYang2 @Liviali155 @sinahuang can you check with PR #1820 applied?

Tried with PR #1820,error not seen on below platforms:
TGL-U RVP with onboard codec ALC711 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
CML Chrome with onboard codec RT5682 and RT1011 in I2S mode
CML with onboard codec ALC3204 in HDA mode

**Comment by Liviali155** [comment]
> Ok, found the cuplprit, see #1819
> 
> I'll report this upstream and let's see how to solve this. It seems this is specific to waking up from RTC timer.
> UPDATE: reported on linux-acpi list -> https://lore.kernel.org/linux-acpi/alpine.DEB.2.21.2002211426350.2957@eliteleevi.tm.intel.com/T/#u

Tried with PR #1819,error not seen on 
TGL-U RVP with onboard codec ALC711 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
CML Chrome with onboard codec RT5682 and RT1011 in I2S mode
CML with onboard codec ALC3204 in HDA mode

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced after applied PR1820 on CML-U sdw laptop.

**Comment by sinahuang** [comment]
Issue cannot be reproduced after applied PR1820 on CML-H  sdw laptop and TGL-U SDW RVP .

**Comment by Liviali155** [comment]
PR #1820 merged,closed
