### ISSUE TITLE
[BUG][UCM]Parecord via DMIC will capture empty sound after turn down the input volume to zero then turn it up.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1823]
**Describe the bug**
System boot up or wake up from s3, then do parecord via DMIC(RT715). Turn down the input volume to zero directly then turn it up, DMIC will capture empty sound.

**To Reproduce** 
1. Boot up system 
2. Open sound setting. Choose DMIC input source.
3. Run command "parecord 1.wav -vvvv"
4. Turn down the input volume to zero directly then trun it up.

**Reproduced rate**
100%

 
**Expected result**
DMIC capture normally.

**Actual result**
DMIC capture empty sound after turn up input volume from zero.

**Environment**
kernel: https://github.com/bardliao/linux/tree/sdw_release commit: 38d0dcd5
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: 5e5f69e + PR#2431
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg rename to sof-cml-rt711-rt1308-rt715.tplg 
UCM :https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715 
commit: 39528c5  +  https://github.com/thesofproject/alsa-ucm-conf/pull/24
platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/4248512/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/4248513/logger.log)

**Comment by ClarexZhou** [comment]
Error also seen on WHL laptop with UCM https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/LENOVO-20QE000VMC-ThinkPadX1Carbon7th-20QE000VMC and sof-v5.0 kernel+ cml-hda-dmic-002-drop-stable  firmware.
Error only occurred when drag volume to 0 in first volume change operation. Error not seen if switch volume to 0 via clicking 0 volume point directly

**Comment by ClarexZhou** [comment]
@libinyang @juimonen could you please check first?

**Comment by juimonen** [comment]
yes let me check.

**Comment by juimonen** [comment]
@ClarexZhou can you check is the mute switch going "on" for some reason?
So something like "amixer contents | grep -i dmic -A 2" with both when you hear something and when things are silent.

**Comment by YvonneYang2** [comment]
Belowing steps can also reproduce this issue on CML-U & H sdw  laptop. 

1. Run command "areocrd -Dhw:0,4 -r 48000 -c 2 -f s16_le test.wav -vv -i" or "areocrd -Dhw:0,1 -r 48000 -c 2 -f s16_le test.wav -vv -i"
2. Turn capture volume"PGA2.0 2" to zero in alsamixer
3. Turn it back to normal volume.

[dmesg.log](https://github.com/thesofproject/linux/files/4249181/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/4249182/logger.log)

**Comment by YvonneYang2** [comment]
Tested it with ww50 pv kernel+fw+ucm, issue cannot be reproduced.

**Comment by ClarexZhou** [comment]
> @ClarexZhou can you check is the mute switch going "on" for some reason?
> So something like "amixer contents | grep -i dmic -A 2" with both when you hear something and when things are silent.

Capture switch in amixer contens is already back to OK once error occurred. But can't capture any audio.  "Input level" always no data.   Can be recovered via system S3 then wake up.

**Comment by ClarexZhou** [comment]
On whl platform, only can reproduced via parecord, not reproduce via aplay

**Comment by ClarexZhou** [comment]
On SDW laptop, error only seen with tplg https://github.com/thesofproject/sof/commits/cml-010-drop-stable, commit: 5e5f69e + PR#2431. Error not seen with tplg wihout PR#2431. 
For cml-u, sof-cml-rt711-rt1308-mono-rt715.tplg, need rename to sof-cml-rt711-rt1308-rt715.tplg to use.

**Comment by juimonen** [comment]
@ClarexZhou can you get "pactl list sources" and "pactl list source-outputs" when the error happens and before the error? If it is the switch in tplg, something is wrongly configured or some hidden mute is on...

**Comment by ClarexZhou** [comment]
Error not seen if using Master FW, commit a6726cf2,  with tplg https://github.com/thesofproject/sof/commits/cml-010-drop-stable, commit: 5e5f69e + PR#2431

**Comment by ClarexZhou** [comment]
> @ClarexZhou can you get "pactl list sources" and "pactl list source-outputs" when the error happens and before the error? If it is the switch in tplg, something is wrongly configured or some hidden mute is on...

Check on SDW laptop, error also seen with arecord after disabled pulseaudio.  Seems fw issue.

**Comment by libinyang** [comment]
This bug should be the fw issue. Master branch fw works well

**Comment by ClarexZhou** [comment]
Close and track in 
[[BUG][BUG][UCM]DMIC will capture empty sound after turn down volume to zero then turn it up.#2438 ](https://github.com/thesofproject/sof/issues/2438)
