### ISSUE TITLE
[BUG]Sink.monitor is used for parecord when parecord via DMIC

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1825]
**Describe the bug**
sink.monitor is used for parecord when parecord via DMIC after belowing steps.

**To Reproduce** 
Step1: Headset is connected-> Headphone is selected as sound output source -> input source: select headset then select DMIC
Step2: ‘parecord 1.wav -vvv’
Step3: Unplug headset
Step4: Close the parecord in step 2, and trigger another parecord to check, sink.monitor is used for parecord. 

**Reproduced rate**
100%
Error can be recovered if plug in headset and select input source again.  
Error not seen if without step 2. Error not seen if paplay not parecord in step2.  
Error also can be reproduced when connect and disconnect HDMI in step 1 and step 3.
 
**Expected result**
Parecord works normally.

**Actual result**
Parecord via DMIC cannot work, console shows sink.monitor is used for parecord.

**Environment**
kernel: https://github.com/bardliao/linux/tree/sdw_release commit: 38d0dcd5
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: 5e5f69e + PR#2431
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg rename to sof-cml-rt711-rt1308-rt715.tplg 
platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

![0225_1](https://user-images.githubusercontent.com/50347470/75231968-5dc2be00-57f1-11ea-840d-6579c34999ea.jpg)

**Comment by ClarexZhou** [comment]
Error also seen on WHL laptop when plug HDMI instead of headset with UCM https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/LENOVO-20QE000VMC-ThinkPadX1Carbon7th-20QE000VMC and sof-v5.0 kernel+ cml-hda-dmic-002-drop-stable firmware.

**Comment by ClarexZhou** [comment]
Error not seen after Disable “
load-module module-device-restore
load-module module-stream-restore
  load-module module-card-restore”
in /etc/pulse/default.pa. 

But will also have below 2 issues once disable above function:
1.  Parecord used source will not change if select DMIC/ headset MIC from Sound input setting
2.  Mic will always auto unmuted after system reboot.

@libinyang @juimonen Could you please comment on this?

**Comment by sinahuang** [comment]
Error also can be reproduced on CML-H laptop with UCM https://github.com/thesofproject/alsa-ucm-conf/commits/sof_ucm-synchronized_speaker and cml-010-drop-stable(commit: 5e5f69e + PR#2431) firmware and sdw_release(commit :38d0dcd5) kernel.

**Comment by juimonen** [comment]
@ClarexZhou so I guess this is pulseaudio issue. Is this now using new pulseaudio and ver2 ucm?

**Comment by ClarexZhou** [comment]
Still using  UCM1.  CML -U SDW is using UCM https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm/sof-sdw-rt711-1308-715, commit: 39528c5  +  https://github.com/thesofproject/alsa-ucm-conf/pull/24. 
But alsa lib is updated to 1.2.1.2 and pulseaudio is updated to your provided pulseaudio deb on WHL Laptop

**Comment by juimonen** [comment]
@ClarexZhou isn't it so that the UI (and the metering) is still recording from the correct source? So somehow the UI can move to correct source but parecord can't..

**Comment by ClarexZhou** [comment]
> @ClarexZhou isn't it so that the UI (and the metering) is still recording from the correct source? So somehow the UI can move to correct source but parecord can't..

DMIC is manually  selected as input source after plug in headset.  Then unplug headset, still using DMIC.  But close parecord and tirgger another parecord, sink.monitor instead of DMIC is used.

**Comment by juimonen** [comment]
@ClarexZhou yeah this is because parecord uses different logic than metering in ui-settings (it has also record stream open). In this case source becomes unavailable and for some reason stream-restore saves sink.monitor as source...

BTW I talked to pulseaudio developers, currently pulseaudio doesn't support a feature where recording would be moved to another source if the first one becomes unavailable. This is a new feature coming in pulseaudio 14.

**Comment by juimonen** [comment]
@ClarexZhou so can you replicate this in X1 with HDMI? I tried and it is quite hard to get it... I think I got it once, but it is quite random.

**Comment by ClarexZhou** [comment]
> @ClarexZhou so can you replicate this in X1 with HDMI? I tried and it is quite hard to get it... I think I got it once, but it is quite random.

Tried again, error can be 100% reproduce via below steps:
1. HDMI is connected,  hdmi is selected as output source
2. parecord 1.wav -vvv to ensure DMIC is used for capture. [Can plugin headset and select DMIC if wasn't ]
3. Unplug HDMI, parecord in step 2 is still using DMIC
4. Stop previous Parecord and trigger another parecord to check.  -> sink.monitor is in use now.

**Comment by ClarexZhou** [comment]
Error not seen after update pulseaudio to https://gitlab.freedesktop.org/juimonen/pulseaudio/-/tree/lenovo_test3. Close
