### ISSUE TITLE
[CML][Codec] rt5682 sysclk/dai not set correctly

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1829]
**Description**
Catch " i2c-10EC5682:00: sysclk/dai not set correctly" error after boot and module insertion.  No functional impact found.
This message is from rt5682 codec driver. once seen this error,  below code is jumped:
```
snd_soc_dapm_mutex_lock(dapm);

snd_soc_dapm_force_enable_pin_unlocked(dapm, "MICBIAS");
snd_soc_component_update_bits(component, RT5682_PWR_ANLG_1,
				RT5682_PWR_MB, RT5682_PWR_MB);
snd_soc_dapm_force_enable_pin_unlocked(dapm, "I2S1");
snd_soc_dapm_force_enable_pin_unlocked(dapm, "PLL2F");
snd_soc_dapm_force_enable_pin_unlocked(dapm, "PLL2B");
snd_soc_dapm_sync_unlocked(dapm);

snd_soc_dapm_mutex_unlock(dapm);
```

**Comment by plbossart** [comment]
@aiChaoSONG it's probably harmless.
The codec registers a set of clocks, but they only make sense when the codec is clock master.
We use the codec in clock slave mode, so those clocks are useless.

Still it's not clear why we end-up preparing a clock that we don't need.

@oder-chiou FYI

**Comment by kv2019i** [comment]
P3 as no functional impact.

**Comment by plbossart** [comment]
@aiChaoSONG is this still relevant or can we close?

**Comment by aiChaoSONG** [comment]
This issue has not been seen for months, close
