### ISSUE TITLE
[GLK] IPC communication misaligned with SOF FW

### ISSUE THREAD

**Issue by slawblauciak** [thesofproject/linux#183]
Attempting to enable HDMI/DP on Yorp [GLK] results in an IPC error:

dmesg:
`[  133.586371] sof-audio sof-audio: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  133.586534] sof-audio sof-audio: error: ipc error for 0x60010000 size 0x14
[  133.586546] sof-audio sof-audio: ASoC: sof-audio hw params failed: -22
[  133.586553]  HDMI1: ASoC: hw_params FE failed -22`

SOF FW: master, ccaff5c87e5bb2ba29fc804abde0f47bd93cebea

**Comment by ranj063** [comment]
@slawblauciak is this caused due to incorrect amixer settings?

**Comment by slawblauciak** [comment]
@ranj063 they're not. I've created this issue in line what you said - the fact that the kernel is not currently working properly with the master branch of SOF FW.

**Comment by mengdonglin** [comment]
Need to monitor if PR #182 can help on this issue.

**Comment by mengdonglin** [comment]
Set to P1 since we need to assist firmware engineers to set up ChromeOS on Yorp

**Comment by keyonjie** [comment]
@ranj063 we don't have this issue with #186 merged?

**Comment by keyonjie** [comment]
@slawblauciak as #186 is merged, can you retry?

**Comment by slawblauciak** [comment]
That PR will likely fix a different issue we were having with suspend.
I'm closing this issue as it has been fixed internally in the FW.
