### ISSUE TITLE
[Bug][CML][SDW]System cannot enter PC10  when SoundWire DKMS is loaded 

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1831]
**Describe the bug**
System cannot enter PC10  when SoundWire DKMS is loaded.

**To Reproduce** 
1. Boot up system 
2. Enter s2idle and wake up (sudo rtcwake -m mem -s 10)
3. ‘cat /sys/kernel/debug/pmc_core/package_cstate_show’ to check C10 status.

**Reproduced rate**
100%
 
**Expected result**
Should get C10 value, like below after blacklist sof: for s2idle
![image](https://user-images.githubusercontent.com/49641224/75342162-d2205e80-58d0-11ea-8d7a-ff970e973b17.png)
And Below is for deep suspend after blacklist SOF
![image](https://user-images.githubusercontent.com/49641224/75342446-6b4f7500-58d1-11ea-8cfe-3fe281904ca5.png)

**Actual result**
Can't get C10 value, like below: for s2idle
![image](https://user-images.githubusercontent.com/49641224/75342240-fa0fc200-58d0-11ea-9079-6c0922c6fda9.png)
And Below is for deep suspend with SOF.
![image](https://user-images.githubusercontent.com/49641224/75342413-596dd200-58d1-11ea-9cfc-32c8180e6dbb.png)

**Environment**
ISO: http://162.213.32.53/aqcKWUEnjzAJahV5J0Z3Q6Vq/beaver-osp1-highsparrow/IEVF_X32/
Contains kernel from https://github.com/thesofproject/linux/tree/integration/soundwire-latest
Commit: cf2660a      Tag: cml_sdw_w50_pv, 
FW: https://github.com/thesofproject/sof/tree/cml-010-drop-stable Commit:  5e5f69e
TPLG: Same with FW brach, sof-cml-rt711-rt1308-mono-rt715.tplg, rename to sof-cml-rt711-rt1308-rt715.tplg
Platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

[kernLog.txt](https://github.com/thesofproject/linux/files/4255481/kernLog.txt)

**Comment by plbossart** [comment]
I'd be worth testing with the latest topic/sof-dev kernel, the w50 release had limitations for clock-stop and power management

**Comment by YvonneYang2** [comment]
Here comes the lspci -vvv info when error occurred. @RanderWang Could you please have a look, thanks.

[error_package.txt](https://github.com/thesofproject/linux/files/4259343/error_package.txt)
[lspci_info.txt](https://github.com/thesofproject/linux/files/4259344/lspci_info.txt)

**Comment by YvonneYang2** [comment]
> Here comes the lspci -vvv info when error occurred. @RanderWang Could you please have a look, thanks.
> 
> [error_package.txt](https://github.com/thesofproject/linux/files/4259343/error_package.txt)
> [lspci_info.txt](https://github.com/thesofproject/linux/files/4259344/lspci_info.txt)

[lspci.txt](https://github.com/thesofproject/linux/files/4259659/lspci.txt)

**Comment by ClarexZhou** [comment]
wk50 released with ‘options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1'

**Comment by YvonneYang2** [comment]
Tried to test with the latest topic/sof-dev kernel with the iso kernel kconfig, but the linux-image*.deb file seems cannot be installed. And dmesg shows it cannot find the right tplg. Thanks for @RanderWang 's help, it seems caused by the kernel config.

**Comment by YvonneYang2** [comment]
> Tried to test with the latest topic/sof-dev kernel with the iso kernel kconfig, but the linux-image*.deb file seems cannot be installed. And dmesg shows it cannot find the right tplg. Thanks for @RanderWang 's help, it seems caused by the kernel config.

Tested it on latest topic/sof-dev with sof-default kconfig merged to the iso kernel kconfig, it can be loaded up successfully.  Then tried to do s2idle suspend/resume, seems it can enter PC10?
```
root@ubuntu-Latitude-9510:/sys/kernel/debug/pmc_core# cat package_cstate_show 
Package C2 : 282988823
Package C3 : 7554675
Package C6 : 1089060
Package C7 : 485943
Package C8 : 34571545
Package C9 : 0
Package C10 : 7129772
```

iso kernel kconfig:
[config-5.0.0-1033-oem-osp1.log](https://github.com/thesofproject/linux/files/4261241/config-5.0.0-1033-oem-osp1.log)

Kconfig which sof-default kconfig merged into iso kernel kconfig:
[kernel_config.log](https://github.com/thesofproject/linux/files/4261237/kernel_config.log)

Other info:
[dmesg.log](https://github.com/thesofproject/linux/files/4261228/dmesg.log)
[lspci.txt](https://github.com/thesofproject/linux/files/4261233/lspci.txt)

**Comment by YvonneYang2** [comment]
Tested it with sof-dev compiled via kconfig which sof-default kconfig merged into iso kernel kconfig + cml-010-hotfix branch, compared to sof-dev+master, found 4 issues as below:
#1843 
#1844 
#1845 
#1846

**Comment by ClarexZhou** [comment]
> Tested it with sof-dev compiled via kconfig which sof-default kconfig merged into iso kernel kconfig + cml-010-hotfix branch, compared to sof-dev+master, found 4 issues as below:
> #1843
> #1844
> #1845
> #1846

This 4 issues are not reproduced with Kernel: sof-dev, commit:65f9d39d, and FW: cml-010-hot-fix, commit: 0ed0dba + https://github.com/thesofproject/sof/commit/f73332eafedf5443f01bf26027fde2578e847ced#

**Comment by ClarexZhou** [comment]
Also can get C10 when tested with  and release/sdw_cml_hotfix  branch, build with below kconfig, 
https://github.com/thesofproject/linux/files/4261237/kernel_config.log

Both C9 and C10 can be get if without options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1
And can get C10, can't get C9 if with options snd-sof-intel-hda-common sdw_clock_stop_quirks=0x1

**Comment by keyonjie** [comment]
@jason77-wang has figured out that the issue is because of the mismatched between the SOF audio driver and i915 audio PM interface, and working on patch to fix on 5.0 kernel without upgrading the whole i915 driver, which actually means revert the audio change introduced by the commit d31c85fc86426 "snd/hda, drm/i915: Track the display_power_status using a cookie"

**Comment by kv2019i** [comment]
@keyonjie Ack, thanks. Ok, I'm suprised it worked at all without modification to the cookie-based interface. But ack, this explains.

**Comment by ClarexZhou** [comment]
Close. For can enter PC10 with latest DKMS.
