### ISSUE TITLE
[BUG]Sink.monitor is used for parecord when parecord via DMIC when select headset in output source

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1849]
**Describe the bug**
sink.monitor is used for parecord when parecord via DMIC after belowing steps. Might related to https://github.com/thesofproject/linux/issues/1825

**To Reproduce** 
Step1: Headset is connected-> select Headset then select Speaker in output source 
Step2: Select DMIC in input source.
Step3: ‘parecord 1.wav -vvv’
Step4: Close the parecord in step 3
Step5: Select headphone in output source, and trigger another parecord to check, sink.monitor is used for parecord. 

**Reproduced rate**
100%
 
**Expected result**
Parecord works normally.

**Actual result**
Parecord via DMIC cannot work, console shows sink.monitor is used for parecord.

**Environment**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:30887e1
 FW: https://github.com/thesofproject/sof/commits/master commit: c3db256
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg 
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

![Screenshot from 2020-03-02 19-45-01](https://user-images.githubusercontent.com/50347470/75673735-96193f00-5cbe-11ea-86e1-2fe72738d4e3.png)

**Comment by ClarexZhou** [comment]
Error also seen on WHL laptop when using HDMI instead of headset.  UCM https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/LENOVO-20QE000VMC-ThinkPadX1Carbon7th-20QE000VMC and sof-v5.0 kernel+ cml-hda-dmic-002-drop-stable firmware.

**Comment by ClarexZhou** [comment]
Error not seen after update pulseaudio to https://gitlab.freedesktop.org/juimonen/pulseaudio/-/tree/lenovo_test3. Close
