### ISSUE TITLE
[BUG][SDW][CML-H]"ASoC: physical link SDW2-Playback (id 3) not exist" occurred when boot up. 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1855]
**Describe the bug**
Occurred "ASoC: physical link SDW2-Playback (id 3) not exist" when system boot up.
Check kernel with top commit 65f9d39 cannot reproduce the issue. So it seems a regression, @bardliao @RanderWang Could you please help to have a look. 
 
**To Reproduce**
1. Boot up 
2. Check dmesg.

**Reproduced rate**
100%

**Expected result**
System boot up successfully

**Actual result**
Dmesg shows "ASoC: physical link SDW2-Playback (id 3) not exist" , and aplay -l has no sound card.

**Environment**
Firmware: 182e62a1 https://github.com/thesofproject/sof/commits/master 
Kernel: 51b461fe https://github.com/thesofproject/linux/commits/topic/sof-dev 
tplg:  Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML-H Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

dmesg
```
[    4.259347] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    4.259637] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    4.259641] sof-audio-pci 0000:00:1f.3: ASoC: physical link SDW2-Playback (id 3) not exist
[    4.259735] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[    4.259744] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    4.259748] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    4.259758] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
```
[dmesg.log](https://github.com/thesofproject/linux/files/4285646/dmesg.log)

**Comment by RanderWang** [comment]
@bardliao    can you help to update topology ?  Now cml-h is going to support multi-cpu DAI mode.

**Comment by bardliao** [comment]
Yes, I can update the topology. But we will meet DSP panic issue if we try to duplicate a stream to different ALH out.

**Comment by juimonen** [comment]
@bardliao let me see the topology you are trying to use, I'll check the demux blob is fine...

**Comment by plbossart** [comment]
@RanderWang Can I suggest that you add a version of the machine driver with no multi-cpu dais for the amplifiers, that way we can test for regressions in parallel with @bardliao's work?

Edit: for example add a quirk that's false for now, and we set it to true when the synchronized playaback is enabled.

**Comment by bardliao** [comment]
Finally, https://github.com/thesofproject/sof/pull/2495 can fix it. I will clean up and create a formal PR soon
