### ISSUE TITLE
[SDW][BUG]Pop noise occurred when terminate aplay0,2(RT1308) or aplay0,0(RT711) via "Ctrl+C"

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1865]
**Describe the bug**
Pop noise occurred when terminate aplay0,2(RT1308) or aplay0,0(RT711) via Ctrl-C.

**To Reproduce**
1. Boot up.
2. Aplay 0,2 via "aplay -Dhw:0,2 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i"
3. Terminate it by "Ctrl+C". If issue not reproduced, please try step2/3 more times.
 
**frequency**
Not each terminate will occur pop noise. Do step2/3 10 times, could reproduce about 5 times.

**Expected result**
Terminate it via "Ctrl+C" has no pop noise.

**Actual result**
Terminate it via "Ctrl+C" has pop noise.

**Environment**
Kernel:release/sdw_cml_hotfix, commit:38d0dcd
FW: commits/cml-010-hot-fix, commit: 0ed0dba
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg 
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode
ucm: https://github.com/thesofproject/alsa-ucm-conf.git+PR#24  or PR#28

[ctrlc_demsg.log](https://github.com/thesofproject/linux/files/4296623/ctrlc_demsg.log)
[ctrlc_soflogger.log](https://github.com/thesofproject/linux/files/4296624/ctrlc_soflogger.log)

**Comment by YvonneYang2** [comment]
Tested with nocodec tplg, please see the picture and attached wave.

![ctl-cToStop](https://user-images.githubusercontent.com/50347470/76067681-bd2b8580-5fca-11ea-8b7c-55bba7f39d95.png)

**Comment by sinahuang** [comment]
Issue also can be reproduced on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode, but can't be reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode.

**Comment by plbossart** [comment]
@YvonneYang2 does this happen with the master branches for fw and kernel?

I don't know if we have a good solution, when playback is interrupted the link remains on for some time but the data transfers will stop abruptly. Even if we push zeroes on the link we'd still have discontinuities so maybe this is an amplifier issue.

@shumingfan @bardliao what do you think?

**Comment by bardliao** [comment]
> abruptly

@plbossart I can see this issue with latest kernel and fw code. And it happens not only when terminate but also start. The pop doesn't sound like discontinuities. The pop is much louder than the music if I set the volume to a very low level. However, there is no pop if I play with /dev/zero.

**Comment by YvonneYang2** [comment]
Error still seen when playing same level audio file

**Comment by shumingfan** [comment]
@plbossart I want to do a silent playback test and @bardliao had completed it. If there is no pop with this test, I think the pop noise doesn't come from the codec.

**Comment by YvonneYang2** [comment]
Checked on latest sof-dev + master, still can produce it.
Then tried headset loopback noise, got the snapshot and wav.

Sine wav:
![Ctrl_C](https://user-images.githubusercontent.com/50347470/76188456-0a9a3380-6213-11ea-8622-d541a51336b1.PNG)
[sinewave.zip](https://github.com/thesofproject/linux/files/4304958/sinewave.zip)

Same level wav:
![Ctrl_C](https://user-images.githubusercontent.com/50347470/76188486-2271b780-6213-11ea-91f7-55c309c56b94.png)
[samelevel.zip](https://github.com/thesofproject/linux/files/4304959/samelevel.zip)

**Comment by ClarexZhou** [comment]
Error is much improved with PR#1897. But still has very light pop via scenario "pause aplay first then Ctl+c to release aplay". Can observe this pop sound when increase speaker volume to Max via PGA3.0 3
Tested with kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: https://github.com/thesofproject/sof/tree/cml-010-hot-fix, commit thesofproject/sof@0ed0dba + commit thesofproject/sof@f73332e
And with same kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: Master, commit: thesofproject/sof@afd9770,

**Comment by YvonneYang2** [comment]
Since #1897 has been merged, retest it om cml-u laptop, issue cannot be reproduced with latest sof-dev(8dc1789) and master(0befebb7). Close it.
