### ISSUE TITLE
[SDW][BUG]Pop noise occurred when switch to background/foreground during aplay0,2(RT1308) or aplay0,0(RT711) 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1866]
**Describe the bug**
Pop noise occurred when terminate aplay0,2(RT1308) or aplay0,0(RT711) via "Ctrl-C".

**To Reproduce**
1. Boot up.
2. Aplay 0,2 via "aplay -Dhw:0,2 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i"
3. Switch to background via "Ctrl+z" and switch to foreground via "fg".  If issue not reproduced, please try step2/3 more times.
 
**frequency**
Not each time occurred pop noise. Do step2/3 10 times, could reproduce about 5 times.

**Expected result**
There's no pop noise when switch background or foreground.

**Actual result**
Pop noise occurred when switch to background/foreground during aplay0,2(RT1308) or aplay0,0(RT711) 

**Environment**
Kernel:release/sdw_cml_hotfix, commit:38d0dcd
FW: commits/cml-010-hot-fix, commit: 0ed0dba
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg 
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode
ucm: https://github.com/thesofproject/alsa-ucm-conf.git+PR#24  or PR#28

[bg_demsg.log](https://github.com/thesofproject/linux/files/4296640/bg_demsg.log)
[bg_soflogger.log](https://github.com/thesofproject/linux/files/4296642/bg_soflogger.log)

**Comment by YvonneYang2** [comment]
Tested with nocodec tplg, please see the picture and attached wave.

![forgroundBg](https://user-images.githubusercontent.com/50347470/76067785-e9470680-5fca-11ea-8934-d56e719ce663.png)
![forgroundBg_zoomedin](https://user-images.githubusercontent.com/50347470/76067798-ed732400-5fca-11ea-8006-f32a6485f4e7.png)

[sine_fg.zip](https://github.com/thesofproject/linux/files/4297367/sine_fg.zip)

**Comment by sinahuang** [comment]
Issue also can be reproduced on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode, but can't be reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode.

**Comment by plbossart** [comment]
@YvonneYang2 same question as for issue #1865, does this happen with the master branches.

This is the same case of abrupt stops and discontinuities in the data, there's not much we can do at the SOF level. Only the amplifier could do something here.

**Comment by YvonneYang2** [comment]
Error still seen when playing same level audio file

**Comment by ClarexZhou** [comment]
Error not seen with kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: https://github.com/thesofproject/sof/tree/cml-010-hot-fix, commit thesofproject/sof@0ed0dba + commit thesofproject/sof@f73332e

But still has slight noise on internal speaker with same kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: Master, commit: thesofproject/sof@afd9770

**Comment by YvonneYang2** [comment]
Error not seen with latest sof-dev+PR1897 and cml-010-hotfix2 branch except that has slight pop noise on internal speaker and headphone when switch foreground from background. 

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:45f6424 + PR1897
FW : https://github.com/thesofproject/sof/commits/cml-010-hot-fix2 commit:  9ddcb00
Topology: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg

**Comment by YvonneYang2** [comment]
Since #1897 has been merged, retest it om cml-u laptop, issue cannot be reproduced with latest sof-dev(8dc1789e) and master(0befebb7)

**Comment by YvonneYang2** [comment]
Close it for PR #1897 merged.
