### ISSUE TITLE
[SDW][BUG]Pop noise occurred at the beginning of aplay0,2(RT1308) or aplay0,0(RT711) 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1867]
**Describe the bug**
Pop noise occurred at the beginning of aplay0,2(RT1308) or aplay0,0(RT711) 

**To Reproduce**
1. Boot up.
2. Aplay 0,2 via "aplay -Dhw:0,2 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i"

**frequency**
Not each time occurred pop noise. Do step2/3 10 times, could reproduce about 5 times.

**Expected result**
Should not have any pop noise.

**Actual result**
Pop noise occurred at the beginning of aplay0,2(RT1308) or aplay0,0(RT711) 

**Environment**
Kernel:release/sdw_cml_hotfix, commit:38d0dcd
FW: commits/cml-010-hot-fix, commit: 0ed0dba
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg 
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode
ucm: https://github.com/thesofproject/alsa-ucm-conf.git+PR#24  or PR#28

[start_demsg.log](https://github.com/thesofproject/linux/files/4296722/start_demsg.log)
[start_soflogger.log](https://github.com/thesofproject/linux/files/4296725/start_soflogger.log)

**Comment by sinahuang** [comment]
Issue also can be reproduced on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode and TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode.

**Comment by YvonneYang2** [comment]
Tested with nocodec tplg, please see the wav picture.

![Screenshot from 2020-03-06 17-56-54](https://user-images.githubusercontent.com/50347470/76073250-45625880-5fd4-11ea-9e60-e900fa03ca78.png)
![Screenshot from 2020-03-06 17-57-41](https://user-images.githubusercontent.com/50347470/76073257-485d4900-5fd4-11ea-81e1-c88692b5b68e.png)

**Comment by YvonneYang2** [comment]
Error still seen when playing same level audio file

**Comment by ClarexZhou** [comment]
Error not seen with kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: https://github.com/thesofproject/sof/tree/cml-010-hot-fix, commit thesofproject/sof@0ed0dba + commit thesofproject/sof@f73332e

But still about 3/10 reproduce rate, has slight noise on internal speaker with same kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: Master, commit: thesofproject/sof@afd9770

**Comment by YvonneYang2** [comment]
Error not seen on headphone with kernel sof-dev(commit: 33f864de) + master(commit: b8b96a2)
Error also not seen on speaker with kernel sof-dev(commit: 33f864de) + master commit: b8b96a2 + https://github.com/thesofproject/sof/pulls?q=2603 to avoid issue https://github.com/thesofproject/sof/issues/2570
So close the bug.
