### ISSUE TITLE
[SDW][BUG]Pop noise occurred when do pause/release during aplay0,0(RT711) or aplay0,2(RT1308)

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1869]
**Describe the bug**
Pop noise occurred during aplay0,0(RT711) or aplay0,2(RT1308)

**To Reproduce**
1. Boot up.
2. Aplay 0,2 via "aplay -Dhw:0,2 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i"
3. PUSH_PAUSE and PUSE_RELEASE. Interval time between pause/release is about 0.5s

**frequency**
Not each PUSH_RAUSE/PUSH_RELEASE will occur pop noise. Pause/release 10 times, reproduced 5 times.

**Expected result**
Pause/release has no pop noise.

**Actual result**
Pause/release will have pop noise.

**Environment**
Kernel:release/sdw_cml_hotfix, commit:38d0dcd
FW: commits/cml-010-hot-fix, commit: 0ed0dba
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg 
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode
ucm: https://github.com/thesofproject/alsa-ucm-conf.git+PR#24  or PR#28

[pause_release__soflogger.log](https://github.com/thesofproject/linux/files/4297214/pause_release__soflogger.log)
[pause_release_dmesg.log](https://github.com/thesofproject/linux/files/4297216/pause_release_dmesg.log)

**Comment by YvonneYang2** [comment]
Tested with nocodec tplg, please see the picture and attached wave.

![PauseRelease](https://user-images.githubusercontent.com/50347470/76067167-ea2b6880-5fc9-11ea-958b-bd31120c7e7f.png)


[sine_releaseatPause.zip](https://github.com/thesofproject/linux/files/4297358/sine_releaseatPause.zip)

**Comment by sinahuang** [comment]
Issue also can be reproduced on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode, but can't be reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode.

**Comment by YvonneYang2** [comment]
Error still seen when playing same level audio file

**Comment by ClarexZhou** [comment]
This pop noise sound same with https://github.com/thesofproject/sof/issues/2203

**Comment by YvonneYang2** [comment]
Checked on latest sof-dev + master, still can produce it. 
Then tried headset loopback noise, got the snapshot and wav.

Sine wav:
![Capture](https://user-images.githubusercontent.com/50347470/76191286-f279e280-6219-11ea-914c-d99809bd2379.PNG)
wav files:
[sinewave.zip](https://github.com/thesofproject/linux/files/4304951/sinewave.zip)

Same level wav:
![ause_release pngP](https://user-images.githubusercontent.com/50347470/76188274-a7100600-6212-11ea-8e5e-d7a3f4f087e1.PNG)
wav files:
[samelevel.zip](https://github.com/thesofproject/linux/files/4304953/samelevel.zip)

**Comment by ClarexZhou** [comment]
Error not seen with kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: https://github.com/thesofproject/sof/tree/cml-010-hot-fix, commit thesofproject/sof@0ed0dba + commit thesofproject/sof@f73332e

Also not observed with same kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897 and FW: Master, commit: thesofproject/sof@afd9770

**Comment by YvonneYang2** [comment]
Since #1897 has been merged, retest it om cml-u laptop, issue cannot be reproduced with latest sof-dev(8dc1789) and master(0befebb7)
