### ISSUE TITLE
[BUG][SDW][CML] arecord record only silence with headset mic

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#1871]
This is tested with CML_RVP_SDW platform. Software doesn't matter, I saw this ever since.

- linux (topic/sof-dev)  = ac3abc56
- sof (master) =	9ebb2881
- Topology file = sof-cml-rt700.tplg

Headset playback works fine after setting HPO Mux to 0.
`$ amixer cset name='HPO Mux' 0`

but for arecord on headset mic it has only silence.
```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofsdwrt700 [sof-sdw-rt700], device 1: SDW1-mics (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: sofsdwrt700 [sof-sdw-rt700], device 2: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsdwrt700 [sof-sdw-rt700], device 3: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ arecord -Dhw:0,1 -c2 -r48000 -f dat -vv temp.wav
```

Looks jack is detected. All ADC gains set to MAX. No luck.
```
$ amixer contents | grep -i jack --context 3
numid=8,iface=CARD,name='AMIC Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=12,iface=CARD,name='HDMI/DP,pcm=4 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=18,iface=CARD,name='HDMI/DP,pcm=5 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=24,iface=CARD,name='HDMI/DP,pcm=6 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=7,iface=CARD,name='Headphones Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```

**Comment by plbossart** [comment]
@fredoh9 do you have a UCM file or do you still use asound.conf files?

**Comment by fredoh9** [comment]
@plbossart I don't have UCM for this platform. If you have it, can you share the link?

**Comment by plbossart** [comment]
@bardliao @shumingfan do you have a UCM file or settings needed to enable the headset capture with rt700?

**Comment by bardliao** [comment]
@fredoh9 I don't have UCM for CML + rt700. Please see the settings below for rt700 capture. 
```
amixer cset name='ADC 22 Mux' 'MIC2'
amixer cset name='ADC 09 Capture Volume' 63 
amixer cset name='ADC 09 Capture Switch' 1
amixer cset name='AMIC Volume' 1
```

**Comment by fredoh9** [comment]
@bardliao @plbossart with about amixer settings, finally I can see input level is changing and I can hear recorded voice. Thanks!

**Comment by fredoh9** [comment]
For now, I will store alsa controls and restore when we need them. I close this issue now.
