### ISSUE TITLE
sof-logger shows nothing with -t parameter

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#188]
This is a kernel driver regression and caused by cros-sof-v4.14-rebase: 8031d7f4f82096834e0d046787b74d96827f31d3

How to reproduce:
sudo /usr/local/bin/sof-logger -l sof-apl.ldc -t 

Configure:
1. sof-master: fda4f1a3 
2. kernel-cros-sof-v4.14-rebase: 3ad0e4ddebf
3. soft-master: 5b51dc0d4

**Comment by keyonjie** [comment]
I can duplicate this issue on UP2, it can be worked around with disabling runtime suspend.

**Comment by mengdonglin** [comment]
@keqiaozhang @RanderWang Could you share more info here why this is a kernel driver bug? This will help Keyon to check this issue asap.

**Comment by keyonjie** [comment]
hi @keqiaozhang , can you paste sof-logger error, is it something like this?
root@UP-02:/home/apl# ./sof-logger -l sof-apl.ldc -t
 CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT
root@UP-02:/home/apl# ./sof-logger -l sof-apl.ldc
 CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT
    0      1      DMA     77403.645833     77403.648438                dma.c:59         No DMAs installed
root@UP-02:/home/apl#

**Comment by keqiaozhang** [comment]
@keyonjie @mengdonglin 
Because this issue cannot be reproduced after rejecting the kernel commit 8031d7f.
The sof-logger error is exactly the same as yours. 
1. with -t parameter, no trace log output there.
2. without -t parameter, only shows one line trace log:
CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT
    0      1      DMA     85943.645833     85943.648438                dma.c:59         No DMAs installed

**Comment by keyonjie** [comment]
@keqiaozhang thanks, it looks dma initialization after resume fails here. so we may need debug FW to root cause it.

**Comment by mengdonglin** [comment]
@keyonjie So it seems to be duplicate of https://github.com/thesofproject/sof/issues/401
I think @akloniex could help to align driver/firmware behavior with you.

**Comment by Jiangxinx** [comment]
Not reproduced with kernel branch debug/v4.19-backport, on APL UP2 platfrom.

STEP:
1. sudo sof-logger -l sof-apl.ldc -t

Test env:
hardware version: UP2
sof-master: 04b1ce48
soft-master: 4ac9248
kernel debug/v4.19-backport: e7da1c44
tplg: sof-apl-pcm512x.tplg

**Comment by keqiaozhang** [comment]
This issue is fixed in kernel-debug/cros-v4.14-rebase: 90eee4 on YORP
