### ISSUE TITLE
TGL: RT5682-SDW S16_LE SoC Loop Playback is Noisy

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#1880]
**Issue Description:**
RT5682-SDW Playback was Noisy and on debug observed that SOC output source has L/R channel phase error to Codec (PFA: ![Phase_err](https://user-images.githubusercontent.com/33264352/76297911-aa70c380-62de-11ea-8a7d-cb97a375ec62.jpg))

Further tried experiments wrt SoC Loop Playback using simultaneous arecord(muted) and aplay to observe issue happens only with S16_LE(2ch) playback file. PFA Tabulated Experiments 
![SoC_Loop_Playback](https://user-images.githubusercontent.com/33264352/76298194-19e6b300-62df-11ea-98cb-16acb2b60a34.png)

**Recipe Used: Based on TGL_SoF_V0.3**
Kernel: https://github.com/naveen-manohar/linux/commits/chrome_bp_sof-dev_debug_noise
Topology: https://github.com/naveen-manohar/sof/commit/5f110327a1c21b9b0594f1453230438f29e5ea34
DSP FW: SOF TGL v0_3 Beta release
Platform: TGL Reference Chromebook with Daughter Card - RT5682+Max98373 - SDW 
Coreboot(SNDW): PFA [coreboot_nondebug-SNDW.zip](https://github.com/thesofproject/linux/files/4317857/coreboot_nondebug-SNDW.zip)

**Validation Steps to Reproduce the Issue:**
Step#1: Flash the Coreboot & OS Recipe mentioned on TGL Reference Chromebook with Daughter Card - RT5682+Max98373 - SDW
Step#2: Plug Jack Headset
Step#3: Run following script for SoC Loop playback 
[s16-soc-output.sh.txt](https://github.com/thesofproject/linux/files/4311436/s16-soc-output.sh.txt)

**Observation:** Noise observed with S16_LE SoC Loop Playback File PFA 
[original-vs-soc_loop_playback.zip](https://github.com/thesofproject/linux/files/4311476/original-vs-soc_loop_playback.zip)

**Comment by plbossart** [comment]
@naveen-manohar can you please explain what the issue is?

"SOC output source has phase error to Codec" is rather unclear to me.

if you are doing a loopback inside of the codec, well of course the data will be delayed on the capture side...

**Comment by keqiaozhang** [comment]
@naveen-manohar 
Could you please send the PRs of machine driver and topology to github? I will try to reproduce your issue on my TGL device.

**Comment by naveen-manohar** [comment]
Hi @plbossart ,
RT5682-SDW was observing headset playback noise and Realtek found that headphone **L/R channel has phase error**. On further analysis they found RT5682's SDW interface loop-back to check source from SOC to Codec has this phenomenon.

To check above scenario, tried SoC Loop Playback(below code) using simultaneous arecord(muted) and aplay to observe **issue happens only with S16_LE(2ch) playback file**
 ```
+++ b/drivers/soundwire/generic_bandwidth_allocation.c
@@ -140,8 +141,8 @@ static void _sdw_compute_port_params(struct sdw_bus *bus,
                                            sdw_compute_master_ports(m_rt, &params[i],
                                                                                          port_bo, hstop);
-                                            block_offset += m_rt->ch_count *
-                                                                          m_rt->stream->params.bps;
+                                           //block_offset += m_rt->ch_count *
+                                           //                           m_rt->stream->params.bps;
                                            port_bo = block_offset;
                             }
```


@keqiaozhang : Sure, I'm working on it, shall send it asap, ETA:ww11.4.

**Comment by naveen-manohar** [comment]
Hi @keqiaozhang :
Please check following PRs based on TGL_SoF_V0.3, let me know if you observe any issues.
https://github.com/thesofproject/linux/pull/1885
https://github.com/thesofproject/sof/pull/2527/commits/d58fb7c54937668df2796292cc3aba3b483fad19

**Comment by bardliao** [comment]
@naveen-manohar @plbossart I just checked with Albert from Realtek. He confirmed that the phase error was originally from the testing source. I.e. They use a wav with phase error between L and R channels to do the loopback test. So, that is not from SoC

**Comment by naveen-manohar** [comment]
Thanks for the clarification @bardliao , Lets re-do the validation and close then close this issue.

**Comment by naveen-manohar** [comment]
Realtek shared additional settings in codec-driver(rt5682-sdw) with this Headset Audio Playback is Good and no-artifact is observed. 
[0001-Sync-with-upstream.txt](https://github.com/thesofproject/linux/files/4324182/0001-Sync-with-upstream.txt)

Appreciate the efforts of all to analyse the issue and share inputs. Closing it for now. Thanks

**Comment by bardliao** [comment]
> Realtek shared additional settings in codec-driver(rt5682-sdw) with this Headset Audio Playback is Good and no-artifact is observed.
> [0001-Sync-with-upstream.txt](https://github.com/thesofproject/linux/files/4324182/0001-Sync-with-upstream.txt)
> 
> Appreciate the efforts of all to analyse the issue and share inputs. Closing it for now. Thanks

I guess the key point is below :)
+	regmap_update_bits(rt5682->regmap, RT5682_HP_CHARGE_PUMP_1,
+			RT5682_PM_HP_MASK, RT5682_PM_HP_HV);
