### ISSUE TITLE
Trace init failed

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#189]
Summary:
[   97.249675] sof-audio sof-audio:  Firmware info: version 1.1-b9717 build 43 on Oct 16 2018:21:24:56
[   97.249768] sof-audio sof-audio: found ext header type 1 size 0x9c
[   97.249783] sof-audio sof-audio: booting DSP firmware completed
[   97.249788] sof-audio sof-audio: ipc rx done: 0x70000000
[   97.256163] sof-audio sof-audio: Firmware download successful, booting...
[   97.256171] sof-audio sof-audio: firmware boot complete
[   97.256310] sof-audio sof-audio: generating page table for 000000003e4a4c6c size 0x10000 pages 16
[   97.256316] sof-audio sof-audio: pfn i 0 idx 0 pfn 16cd00
[   97.256322] sof-audio sof-audio: pfn i 1 idx 2 pfn 16cd01
[   97.256327] sof-audio sof-audio: pfn i 2 idx 5 pfn 16cd02
[   97.256332] sof-audio sof-audio: pfn i 3 idx 7 pfn 16cd03
[   97.256337] sof-audio sof-audio: pfn i 4 idx 10 pfn 16cd04
[   97.256342] sof-audio sof-audio: pfn i 5 idx 12 pfn 16cd05
[   97.256347] sof-audio sof-audio: pfn i 6 idx 15 pfn 16cd06
[   97.256352] sof-audio sof-audio: pfn i 7 idx 17 pfn 16cd07
[   97.256357] sof-audio sof-audio: pfn i 8 idx 20 pfn 16cd08
[   97.256362] sof-audio sof-audio: pfn i 9 idx 22 pfn 16cd09
[   97.256367] sof-audio sof-audio: pfn i 10 idx 25 pfn 16cd0a
[   97.256373] sof-audio sof-audio: pfn i 11 idx 27 pfn 16cd0b
[   97.256378] sof-audio sof-audio: pfn i 12 idx 30 pfn 16cd0c
[   97.256383] sof-audio sof-audio: pfn i 13 idx 32 pfn 16cd0d
[   97.256388] sof-audio sof-audio: pfn i 14 idx 35 pfn 16cd0e
[   97.256393] sof-audio sof-audio: pfn i 15 idx 37 pfn 16cd0f
[   97.256398] sof-audio sof-audio: dma_trace_pages: 16
[   97.256414] sof-audio sof-audio: error: cannot create debugfs entry for trace
[   97.256433] sof-audio sof-audio: **warning: failed to init trace after resume -19**

Test env:
sof-master: b971739
soft-master: 5b51dc0
kernel sof-dev: bf67a28d6732fe0f7c5e50c9c0273d97b34f2ab1
kernel commit 93853cbf8f8252ec04dd8b70328cb004d1d4566a has no such issue.

**Comment by mengdonglin** [comment]
@ZhendanYang Can this issue be reproduced by kernel commit ASoC: SOF: set up memory windows only at first boot  …?
https://github.com/thesofproject/linux/commit/2a28aca029bf8ce2dd0c1bef8e09385f548b23af

**Comment by keyonjie** [comment]
this should be fixed by #190
