### ISSUE TITLE
[BUG][TGL]"rt1308 i2c-10EC1308:00: Device with ID register 0 is not rt1308" occurred when system boot up on TGL.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1891]
**Describe the bug**
“rt1308 i2c-10EC1308:00: Device with ID register 0 is not rt1308” when system boot up. Aplay -l shows no sound card.

Checked kernel on ww11.4, cannot reproduce this issue.

**To Reproduce**
1. Boot up .
2. Check dmesg.

**Reproduced rate**
100%

**Expected result**
System boot up succeffully

**Actual result**
"rt1308 i2c-10EC1308:00: Device with ID register 0 is not rt1308" and aplay -l shows no sound card.

**Environment**
kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit: ae18d452
FW: https://github.com/thesofproject/sof/commits/master  commit: 0d0e5b73
tplg:  Same with FW branch,  sof-tgl-rt711-i2s-rt1308.tplg 
platform: TGL RVP with codec ACL711 in SDW mode and  ALC1308 in I2S

dmesg:
```
[    4.440667] intel-lpss 0000:00:15.0: enabling device (0000 -> 0002)
[    4.466742] intel-lpss 0000:00:15.1: enabling device (0000 -> 0002)
[    4.481847] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    4.482077] sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    4.482080] sof-audio-pci 0000:00:1f.3: PCI DSP detected
[    4.482093] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[    4.482238] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.485277] rt1308 i2c-10EC1308:00: Device with ID register 0 is not rt1308
[    4.491666] intel-lpss 0000:00:15.2: enabling device (0000 -> 0002)
[    4.529666] intel-lpss 0000:00:15.3: enabling device (0000 -> 0002)
[    4.535266] random: crng init done
[    4.535268] random: 7 urandom warning(s) missed due to ratelimiting
[    4.553744] intel-lpss 0000:00:19.0: enabling device (0000 -> 0002)
[    4.575662] intel-lpss 0000:00:19.1: enabling device (0000 -> 0002)
[    4.597666] intel-lpss 0000:00:1e.0: enabling device (0000 -> 0002)
[    4.610677] intel-lpss 0000:00:1e.3: enabling device (0000 -> 0002)
[    4.634778] pxa2xx-spi pxa2xx-spi.7: no DMA channels available, using PIO
```
[dmesg.log](https://github.com/thesofproject/linux/files/4328468/dmesg.log)

**Comment by plbossart** [comment]
@YvonneYang2 this is likely a merge issue and a problem on the I2C side. Can you try and bisect?

**Comment by YvonneYang2** [comment]
Seems hardware issue.  It can boot up now, so close it.
