### ISSUE TITLE
[BUG][tgl]"no soundcards found“ after power on without HDMI/DP connected

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1902]
Describe the bug
"no soundcards found“ after power on without HDMI/DP connected
wait about 1min can recovery

sof/dev(45f64244)+ [tgl-003-drop-stable][1bb517ab] has no this issue,but has another issue https://github.com/thesofproject/linux/issues/1847

To Reproduce
1.unplug power supply
2.plugin power supply to power on without HDMI/DP connected
3.aplay -l

Reproduction Rate
2/4

Expected behavior
Sof can be loaded normally

Actual result
“no soundcards found” when aplay -l,wait about 1min can recovery

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware:1bb517ab https://github.com/thesofproject/sof/commits/tgl-003-drop-stable
Kernel: 3326e676(https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?h=for-next)
Topology: file: tools/topology/ sof-hda-generic-4ch.tplg same as firmware

[demsg0318.log](https://github.com/thesofproject/linux/files/4346916/demsg0318.log)
[sof_trace0318.log](https://github.com/thesofproject/linux/files/4346919/sof_trace0318.log)

**Comment by ClarexZhou** [comment]
Previous sof-dev (commit: 8bf1a29 ) Seems also had this issue  Find in #1826

**Comment by Liviali155** [comment]
closed for not reoroduced on latest sof/dev(45f6424)
