### ISSUE TITLE
[TGL][BUG]"no soundcards found" after boot up system without HDMI/DP connected.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1905]
Describe the bug
"no soundcards found“ after power on without HDMI/DP connected. The terminal will be freezed When aplay -l didn't show nosoundcard.

Note: if power on with HDMI/DP connected, issue can't be reproduced.
HMID connected dmesg log:

[dmesg11.log](https://github.com/thesofproject/linux/files/4353216/dmesg11.log)

To Reproduce
1. Unplug power cable
2. Plugin power cable to power on without HDMI/DP connected.
3. Aplay -l

Reproduction Rate

Test for 8 times, freeze 1 time, failed 7 times.
Freezed log:
[dmesgfreeze.log](https://github.com/thesofproject/linux/files/4353006/dmesgfreeze.log)
Freezed display:

```
ubuntu@TGL-SDW-10:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofsdwrt7111308 [sof-sdw-rt711-1308-715], device 0: Headphone (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsdwrt7111308 [sof-sdw-rt711-1308-715], device 2: SDW1-speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsdwrt7111308 [sof-sdw-rt711-1308-715], device 5: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsdwrt7111308 [sof-sdw-rt711-1308-715], device 6: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsdwrt7111308 [sof-sdw-rt711-1308-715], device 7: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
Failed log:
[dmesg2.log](https://github.com/thesofproject/linux/files/4353111/dmesg2.log)

After Pulseaudio disabled:
Test for 10 times, pass 4 time, failed 6 times.
Pass log:
[dmesg3.log](https://github.com/thesofproject/linux/files/4353109/dmesg3.log)

Failed log:
[dmesgpano.log](https://github.com/thesofproject/linux/files/4353028/dmesgpano.log)

Expected behavior
Sof can be loaded normally

Actual result
“no soundcards found” when aplay -l.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:45f6424
FW:  https://github.com/thesofproject/sof/commits/master commit:  a133d5
Tplg: Same with FW branch, sof-tgl-rt711-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711  and  RT1308 in SDW mode

[dmesgtgl.log](https://github.com/thesofproject/linux/files/4348121/dmesgtgl.log)

**Comment by sinahuang** [comment]
This issue can't be reproduced on TGL -RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode, and issue #1709 occured on TGL -RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode.

**Comment by kv2019i** [comment]
This is the same bug as on:
https://github.com/thesofproject/linux/issues/1847

The outcome is different as with HDA codecs, HDMI gets disabled but probe does not fail completely. With the SDW machine driver, if HDMI probe fails, the whole SOF probe fails and result is "no soundcards filed". This can be detected from this trace:
[    4.676938] sof-audio-pci 0000:00:1f.3: codec #2 probe error, ret: -5

This bug is fixed by:
https://github.com/thesofproject/linux/pull/1901

**Comment by sinahuang** [comment]
Issue can't be reproduced with sof-dev(commit:722d8e2) +PR#1901 +master(commit:f1fa3be9).

**Comment by plbossart** [comment]
@kv2019i PR #1901 is still marked as Draft, is it ready to merge then?

Also I don't really get why there's a difference between SoundWire and HDaudio, should we add something in the machine driver then?

**Comment by kv2019i** [comment]
@plbossart No, no, #1901 requires more work and needs to through intel-gfx. I'll submit a version to sof-dev once I get it through to the graphics tree.

And yes, sdw machine drivers are lacking support to disable HDMI at runtime. I.e. what I did in
https://github.com/thesofproject/linux/pull/1731/commits/3757a940a5bbd8e259d9f44557dfca4c7156f7bb

**Comment by plbossart** [comment]
@kv2019i how can we force iDISP to disappear with codec_mask = 0? On CML devices there's no issue even when HDMI is not plugged in, this seems to be a TGL-specific issue?

**Comment by sinahuang** [comment]
Test with sof-dev(commit: a27277) +master(commit: ae53aeb), issue still can be reproduced after PR1932 merged.

**Comment by kv2019i** [comment]
The i915 patch accepted as well. Together #1957 (pending merge) and #1932 (merged) close this bug in sof-dev as well.
