### ISSUE TITLE
[BUG][CML][UCM]Speaker can't display in sound setting.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1910]
**Describe the bug**
Speaker can't display in sound setting.
 UCM:
https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm-synchronized_speaker_4_with_enable_switches

**To Reproduce**
1.Boot up system successfully.
2.Check the speaker in sound setting.

**Reproduce rate**
5/5

**Expected result**
Speaker should exist in sound setting.

**Actual result**
Speaker can't display in sound setting.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:e4ba56
FW: https://github.com/thesofproject/sof/commits/master commit:  f1fa3be9
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

![Screenshot from 2020-03-17 11-32-45](https://user-images.githubusercontent.com/56706782/77025027-04eadd80-69cb-11ea-8b1e-99bf327cc333.png)

**Comment by YvonneYang2** [comment]
Issue can be reproduced on sdw cml-u with ucm  https://github.com/thesofproject/alsa-ucm-conf (commit: a5338fe ) +PR#28

**Comment by sinahuang** [comment]
Issue still can be reproduced on CML-H with latest UCM:https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +PR#32.

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced on cml-u with latest UCM: https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +https://github.com/thesofproject/alsa-ucm-conf/pull/33

**Comment by ClarexZhou** [comment]
Close for not seen with UCM1 with PR#33 or UCM2 with PR#29
