### ISSUE TITLE
[TGL][BUG]"snd_soc_register_card failed -517" disaplay after system boot up successfully.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1911]
**Describe the bug**
"snd_soc_register_card failed -517" disaplay after system boot up successfully, run "aplay -l" display no soundcard. 
Can recovery after power outages for long time.

**To Reproduce**
1.Boot up system successfully.
2.Aplay -l

**Reproduce rate**
5/5

**Expected result**
System should load normally after booting up successfully.

**Actual result**
No soundcard display when run "aplay -l".
```
[    3.644098] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp1
[    3.644099] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp2
[    3.644099] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp3
[    3.644100] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp4
[    3.644135] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: snd_soc_register_card failed -517
[    3.653801] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link SDW0-Playback
[    3.653803] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link SDW0-Capture
[    3.653803] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link SSP2-Codec
[    3.653804] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link dmic01
[    3.653805] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link dmic16k
[    3.653806] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp1
[    3.653806] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp2
[    3.653807] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp3
[    3.653808] sdw_rt711_rt1308_rt715 sdw_rt711_rt1308_rt715: info: override BE DAI link iDisp4
[    3.653962] sof-audio-pci 0000:00:1f.3: loading topology:intel/sof-tplg/sof-tgl-rt711-i2s-rt1308.tplg
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:e4ba56
FW:  https://github.com/thesofproject/sof/commits/master commit:  f1fa3be9
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

[dmesg19.log](https://github.com/thesofproject/linux/files/4352484/dmesg19.log)

**Comment by sinahuang** [comment]
Bi-sect result: 
commit:https://github.com/thesofproject/linux/commit/722d8e2bb435833a5199537d6e5a2ef7908a19ef is ok , but when I manually build commit :https://github.com/thesofproject/linux/commit/39e906ec03b6070d4ee0066e069bf1a6be9b30d3, occurred some errors, so I can't confirmed this issue was caused by commit :https://github.com/thesofproject/linux/commit/39e906ec03b6070d4ee0066e069bf1a6be9b30d3 or commit: https://github.com/thesofproject/linux/commit/e4ba562e67a6fb9e0a4ffb77a07a7d9a58d17d4d .

**Comment by RanderWang** [comment]
@shumingfan Does 1308 support  tdm in I2S mode ? If yes, can you help to add it or share us how to add it. Thanks!

**Comment by RanderWang** [comment]
@shumingfan sorry, I notified you with shuming, now correct it.

**Comment by shumingfan** [comment]
@RanderWang Yes, 1308 supports TDM in I2S mode, but the driver doesn't add the callback function of configuration yet.
My colleague Derek <derek.fang@realtek.com> will add it later.

**Comment by RanderWang** [comment]
Thanks @shumingfan

**Comment by ClarexZhou** [comment]
wait ALC1308 to support TDM in I2S mode.

**Comment by oortcomet** [comment]
@RanderWang You can test the RT1308 TDM playback by using the patch.
It is only for test. If there is any problem, please let me know.

[rt1308_tdm_playback.zip](https://github.com/thesofproject/linux/files/4375114/rt1308_tdm_playback.zip)

**Comment by RanderWang** [comment]
@oortcomet  Thanks!  @sinahuang   Hi sina, could you help to validate this patch?  thanks!

**Comment by sinahuang** [comment]
Checked with sof-dev  (commit:33f864d)+ rt1308_tdm_playback patch and master (commit:  b8b96a20b), original issue can't be reproduced,  speaker RT1308 can work normally.

**Comment by kv2019i** [comment]
@RanderWang Can you provide an update to this? This has been open since March.

**Comment by RanderWang** [comment]
The issue was caused by tdm usage in sof_sdw,  but now the code was discarded.
