### ISSUE TITLE
[BUG] No sound on Lenovo IdeaPad S540-13IML i7-10510U on ClearLinux w. kernel 5.5.3x

### ISSUE THREAD

**Issue by chrysophylax** [thesofproject/linux#1913]
**Describe the bug**
Failure to load drivers on i7-10510U leads to only Dummy Output being available.

What have you tried to diagnose or workaround this issue?
Running very recent kernel (5.5.3.x)

**To Reproduce**
Boot Intel ClearLinux 5.5.3 on a Lenovo S540 13IML with an i7-10510U CPU. No sound.

**Reproduction Rate**
Every time.

**Expected behavior**
Working sound card output selectable in GNOME or through pactl.

**Impact**
Showstopper for Linux deployment on this SKU.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: N/A
    * SOF: N/A
2) Name of the topology file
    * Topology: Unfortunately not sure where this is stored on clearlinux
3) Name of the platform(s) on which the bug is observed.
    * Platform: Lenovo Ideapad S540 13IML with GenuineIntel i7-10510U running ClearLinux 32310 on kernel 5.5.3 

I've cross-filed the bug with the Intel distro guys & gals over here as well https://github.com/clearlinux/distribution/issues/1771

[dmesg.txt](https://github.com/thesofproject/sof/files/4233037/dmesg.txt)
[verbose-lspci.txt](https://github.com/thesofproject/sof/files/4233038/verbose-lspci.txt)

**Comment by kv2019i** [comment]
@ahkok Fix is 858b4f944a67b921b0c0e81310a376a0663291a2 in stable/linux-5.5.y and e68d6696575e1af3f92125e842f2853708f34589 in upstream.

Ok to close, @tlauda ?
