### ISSUE TITLE
[SDW][BUG]Output source in sound setting is wrong(shows:multichannel output ).

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1918]
**Describe the bug**
Output source in sound setting is wrong. It seems UCM can't work.

Shows:
![Screenshot from 2020-03-17 11-16-49](https://user-images.githubusercontent.com/56706782/77140477-ad28a100-6ab4-11ea-84dd-9f9d962a2722.png)

**To Reproduce**
1.Boot up system successfully.
2.Check sound setting.

**Reproduce rate**
5/5

**Expected result**
Output source in sound setting should be right.

**Actual result**
Output source in sound setting is wrong.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:12cdaef
FW: https://github.com/thesofproject/sof/commits/master commit:  c639886
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

no error info in dmesg:
[dmesg20.log](https://github.com/thesofproject/linux/files/4358147/dmesg20.log)

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced with sof-dev(top commit:https://github.com/thesofproject/linux/commit/2be2a042be46c852b664ac29ae3d78ccbbd73240) + master which reverted thesofproject/sof@5e8de9f. Then I tried next commit https://github.com/thesofproject/linux/commit/69837211d560b2db2d8ee67274e23eb1fcc3ecfc, but sof cannot load up successfully. So I'm not sure if it's caused by commit 69837211

**Comment by plbossart** [comment]
You need to update the UCM file, see https://github.com/thesofproject/alsa-ucm-conf/pull/29

The card name changed and you need to have the files in /usr/share/alsa/ucm2/sof-soundwire

**Comment by sinahuang** [comment]
Issue also can be reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by bardliao** [comment]
> Issue also can be reproduced on TGL-U RVP with codec ALC711 in SDW mode and RT1308 in I2S mode

We should use new UCM for this too.

**Comment by sinahuang** [comment]
Issue can't be reproduced on CML-H with latest UCM:https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +PR#32.

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced on cml-u with latest UCM: https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +thesofproject/alsa-ucm-conf#33

**Comment by ClarexZhou** [comment]
Error not reproduced on latest UCM1 PR#32 and PR#33.
For UCM2 PR#29:  
CML-H will be tested after 1308 sync playback are ready
CML-U, tested with ubuntu 20.04 (pulseaudio default version 13.99.1 and alsa lib default version 1.2.2-2.1 )current issue not seen. UCM works, but still has several issues. See https://github.com/thesofproject/alsa-ucm-conf/pull/29#issuecomment-604179600

**Comment by ClarexZhou** [comment]
close for ucm 1 not reproduced with PR #32/ PR#33
and UCM2 also not reproduced  on CML-U in SDW mode or with 2 1303 sync playback prs on CML-H

**Comment by sinahuang** [comment]
Tested with UCM2 https://github.com/thesofproject/alsa-ucm-conf/pull/29, sound setting shows dummy on CML-H. 
Error can't be seen on CML-H  with 4 1308 speakers sync playback enabled.
