### ISSUE TITLE
[bug][SDW]Arecord0,1 by RT711 headset captured empty audio.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1919]
**Describe the bug**
Headset Mic jack is on in alsamixer and amixer conetnts when issue happened.

**To Reproduce**
1.Boot up system successfully.
2. Arecord -Dhw:0,1 -fs16_le -c2 -r 48000 -vv -i 00.wav

**Reproduce rate**
5/5

**Expected result**
Arecord0,1 RT711 should capture audio normally.

**Actual result**
Arecord0,1 RT711 captured empty audio. 

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:12cdaef
FW: https://github.com/thesofproject/sof/commits/master commit:  c639886
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.
no error info in dmesg:

[dmesg.log](https://github.com/thesofproject/linux/files/4358593/dmesg.log)

**Comment by YvonneYang2** [comment]
Issue can be reproduced on cml-u

**Comment by sinahuang** [comment]
Issue can be reproduced on TGL-RVP with codec ALC711  and  RT1308 in SDW mode

**Comment by RanderWang** [comment]
please try, ucm issue
amixer cset numid=2 on  
amixer cset numid=3 on

**Comment by sinahuang** [comment]
Tried with command "amixer cset numid=2 on" and "amixer cset numid=3 on", issue can't be reproduced.
```
numid=2,iface=MIXER,name='rt711 ADC 08 Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=off,off
numid=3,iface=MIXER,name='rt711 ADC 09 Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=off,off
```

**Comment by plbossart** [comment]
which ucm are you using?
@RanderWang Can you verify this is correct in https://github.com/thesofproject/alsa-ucm-conf/pull/29

**Comment by sinahuang** [comment]
attached UCM:
https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm-synchronized_speaker_4_with_enable_switches

**Comment by plbossart** [comment]
@sinahuang This UCM looks obsolete now? we only want to support UCM2 and the file names are wrong.

**Comment by RanderWang** [comment]
@plbossart  I tried to update pulse audio to support UCM2, but it doesn't work now. @juimonen @libinyang Do you have a solution to update PA ?

**Comment by plbossart** [comment]
@RanderWang You don't need to update pulseaudio, just libasound2. @libinyang has a package already 
[libasound2_1.2.1.2-intel_amd64.deb.gz](https://github.com/thesofproject/linux/files/4375750/libasound2_1.2.1.2-intel_amd64.deb.gz)

**Comment by RanderWang** [comment]
@plbossart I tested and It doesn't work. According to @libinyang  we need to update all pulse audio components. And I also found some commits for UCM2 in PA.

**Comment by plbossart** [comment]
@RanderWang do you use Ubuntu 19.10? If not then please update first. I have zero issues with Ubutun19.10.

**Comment by RanderWang** [comment]
> @RanderWang do you use Ubuntu 19.10? If not then please update first. I have zero issues with Ubutun19.10.

I worked on OEM ubuntu image base on 18.04. I will install 19.10 and have a try

**Comment by sinahuang** [comment]
Verified with sof-dev and master branch on latest UCM:https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +PR#https://github.com/thesofproject/alsa-ucm-conf/pull/32, issue can't be reproduced.

**Comment by RanderWang** [comment]
> > @RanderWang do you use Ubuntu 19.10? If not then please update first. I have zero issues with Ubutun19.10.
> 
> I worked on OEM ubuntu image base on 18.04. I will install 19.10 and have a try

PR29 on 19.10,  issue can't be reproduced.

**Comment by ClarexZhou** [comment]
RT711 headset not work with PR#29 on ubuntu 20.04. See https://github.com/thesofproject/alsa-ucm-conf/pull/29#issuecomment-604179600

**Comment by sinahuang** [comment]
Verified it on UCM2 +PR https://github.com/thesofproject/alsa-ucm-conf/pull/29 with sof-dev ( commit:052e45d) and master (commit:  b4e8b1e4) on CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode, issue can't be reproduced. So closed it.
