### ISSUE TITLE
[BUG][CML-U]Occurred “ ASoC: physical link SDW3-Capture (id 4) not exist" when system boot up.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1921]
**Describe the bug**
Occurred " ASoC: physical link SDW3-Capture (id 4) not exist" when system boot up.

**To Reproduce**
1. Boot up 
2. Check dmesg.

**Reproduced rate**
100%

**Expected result**
System boot up successfully

**Actual result**
Dmesg shows " ASoC: physical link SDW3-Capture (id 4) not exist" , and aplay -l has no sound card.

**Environment**
Firmware: 9da1fce https://github.com/thesofproject/sof/commits/master + PR28
Kernel: 9b5b6c2a https://github.com/thesofproject/linux/commits/topic/sof-dev 
tplg:  Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

dmesg
```
[    2.916466] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[    2.916472] sof-audio-pci 0000:00:1f.3: tplg: 1 hw_configs found, default id: 0!
[    2.916476] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    2.916688] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    2.916691] sof-audio-pci 0000:00:1f.3: tplg: 1 hw_configs found, default id: 1!
[    2.916694] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    2.916861] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    2.916863] sof-audio-pci 0000:00:1f.3: tplg: 1 hw_configs found, default id: 2!
[    2.916866] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    2.917049] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    2.917052] sof-audio-pci 0000:00:1f.3: ASoC: physical link SDW3-Capture (id 4) not exist
[    2.917113] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[    2.917117] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[    2.917119] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.917123] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.917127] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.917128] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
```
[dmesg.log](https://github.com/thesofproject/linux/files/4367376/dmesg.log)

**Comment by RanderWang** [comment]
@plbossart  The SKU is 0983, not the 09c6 on your device.  I wonder if this can be changed when the production is released.

**Comment by RanderWang** [comment]
we also checked a newer version (DVT2),  the SKU is 09c6.  so the validation device is out of date. @YvonneYang2  can we test on DVT2 ?

**Comment by YvonneYang2** [comment]
Error not seen on CML-U DVT2.  
Then tried it on DVT1 with the patch @RanderWang provided, latest sof-dev kernel can load up successfully.

Patch:
[sku.txt](https://github.com/thesofproject/linux/files/4367733/sku.txt)

**Comment by plbossart** [comment]
ok, I'll add a patch to keep the DVT1 functional, thanks @RanderWang and @YvonneYang2

**Comment by plbossart** [comment]
See PR #1927

**Comment by RanderWang** [comment]
@YvonneYang2  could you help to validate this PR ? thanks!

**Comment by YvonneYang2** [comment]
Checked latest sof-dev + PR #1927 , issue cannot be reproduced on CML-U DVT1.

**Comment by RanderWang** [comment]
@YvonneYang2  Thanks! So this PR works on DVT1.

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced on DVT1 since PR #1927 has been merged. So close it.
