### ISSUE TITLE
[BUG][CML]Arecord0,4 by RT715 captured empty audio. 

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1923]
**Describe the bug**
Arecord0,4 by RT715 captured empty audio. Issue only can be reproduced on Dell ISO system. With Ubuntu18.04 issue can't be reproduced.

More info:
Run "amixer cset numid=11 on" can recover.

UCM:
https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm-synchronized_speaker_4_with_enable_switches(commit: e145aaf2)

**To Reproduce**
1.Boot up system successfully.
2.Arecord -Dhw:0,4 -fs16_le -c2 -r 48000 -vv -i 00.wav

**Reproduce rate**
5/5

**Expected result**
Arecord0,4 (rt715)should work normally.

**Actual result**
Arecord0,4 by RT715 captured empty audio

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:9b5b6c2a3
FW: https://github.com/thesofproject/sof/commits/master commit:  9da1fce2
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

[dmesg.log](https://github.com/thesofproject/linux/files/4369580/dmesg.log)

**Comment by plbossart** [comment]
@sinahuang can you provide more info on what  "amixer cset numid=11 on" is? 
It looks like you are using a bad UCM file or something?

**Comment by sinahuang** [comment]
Attached amixer contents:
numid=11,iface=MIXER,name='rt715 ADC 07 Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=off,off
[unnormal.zip](https://github.com/thesofproject/linux/files/4379230/unnormal.zip)

**Comment by sinahuang** [comment]
Issue can't be reproduced now, keep monitor it.

**Comment by sinahuang** [comment]
Verified with latest sof-dev and master branch on latest UCM:https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +PR#thesofproject/alsa-ucm-conf#32, issue can't be reproduced.
