### ISSUE TITLE
Topology loading needs pm_runtime_get() held.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#193]
It looks like there may be a race between topology loading and runtime PM entry. Can we make sure that pm_runtime_get() is called for duration of topology loading.

```
[    5.445558] sof-audio sof-audio: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    5.445615] sof-audio sof-audio: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    5.445623] sof-audio sof-audio: tplg: complete pipeline PIPELINE.2.SSP2.OUT id 13
[    5.445632] sof-audio sof-audio: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    5.445693] sof-audio sof-audio: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    5.445700] sof-audio sof-audio: tplg: complete pipeline PIPELINE.1.SSP4.OUT id 6
[    5.445709] sof-audio sof-audio: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    5.445768] sof-audio sof-audio: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    5.445792] sof-audio sof-audio: error: failed to enter PM idle -11

```

**Comment by mengdonglin** [comment]
@lgirdwood Would you provide more info here so validation can reproduce and follow up? 
- topology
- the steps to reproduce this issue

I think you're using UP2, latest sof-dev, and sof master branch.

**Comment by lgirdwood** [comment]
Leafhill, I've only seen it once and it looks like an obvious runtime PM get() is needed during the duration of all topology loading.

**Comment by plbossart** [comment]
@lgirdwood did you mean something like this:

````c
int snd_sof_load_topology(struct snd_sof_dev *sdev, const char *file)
{
	const struct firmware *fw;
	struct snd_soc_tplg_hdr *hdr;
	int ret;

	dev_dbg(sdev->dev, "loading topology:%s\n", file);

	ret = request_firmware(&fw, file, sdev->dev);
	if (ret < 0) {
		dev_err(sdev->dev, "error: tplg %s load failed with %d\n",
			file, ret);
		return ret;
	}

	ret = pm_runtime_get_sync(sdev->dev);
	if (ret < 0) {
		dev_err(sdev->dev, "error: topology load pm_runtime_get_sync failed with %d\n",
			ret);
		return ret;
	}

	hdr = (struct snd_soc_tplg_hdr *)fw->data;
	ret = snd_soc_tplg_component_load(sdev->component,
					  &sof_tplg_ops, fw,
					  SND_SOC_TPLG_INDEX_ALL);
	if (ret < 0) {
		dev_err(sdev->dev, "error: tplg component load failed %d\n",
			ret);
		ret = -EINVAL;
	}

	ret = pm_runtime_put(sdev->dev);
	if (ret < 0)
		dev_err(sdev->dev, "error: topology load pm_runtime_put failed with %d\n",
			ret);

	release_firmware(fw);
	return ret;
}
````

**Comment by lgirdwood** [comment]
@plbossart  yep

**Comment by plbossart** [comment]
ok, will push this code then. Thanks

**Comment by ranj063** [comment]
@plbossart we enable runtime pm on sof device after the topology is loaded. To make the change above, maybe we need to change that as well?

**Comment by lgirdwood** [comment]
@ranj063 is that a recent update ? If not then why did we get D3 entry during topology loading as above log.

**Comment by ranj063** [comment]
@lgirdwood no this is not a recent change. Let me look into this today and I will comment on @plbossart 's pull request

**Comment by xiulipan** [comment]
@ranj063 
How about the resume process?
We will reload the tplg after the DSP is resumed, which means that

> [    5.445792] sof-audio sof-audio: error: failed to enter PM idle -11
May not happen at the first boot.

I believe this PR is good for the following resume tplg load.

**Comment by ranj063** [comment]
https://github.com/thesofproject/linux/pull/249 fixes this issue
