### ISSUE TITLE
[Bug][CML] MIC jack is off if plug in headset when HDA Analog isn't in use.

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#1938]
Similar to #1628 but not same.  The difference is #1628 is for WHL platforms, and after setting the autosuepend_delay to codec driver, the mic could be detected on WHL platforms. On CML platforms, even setting the autosuspend_delay, the mic could not be detected, It also needs to revert a commit:

37a0794

ASoC: SOF: Intel: hda-loader: clear the IPC ack bit after FW_PURGE done

Set DONE bit after the FW_PURGE IPC is polled successfully, to clear the
interrupt and avoid the arrival of the confusing unexpected ipc.

Signed-off-by: Keyon Jie yang.jie@linux.intel.com

**Comment by kv2019i** [comment]
@keyonjie Can you take a look at this. Reverting your patch seems to have a surprising effect to the HDA codec:
 https://github.com/thesofproject/linux/pull/1837

**Comment by keyonjie** [comment]
So are we good to close this one now?

**Comment by jason77-wang** [comment]
I just built the latest topic/sof-dev branch, and tested on 2 LENOVO cml laptops, the issue is fixed. So the problem has nothing to do with:

37a0794

ASoC: SOF: Intel: hda-loader: clear the IPC ack bit after FW_PURGE done

Set DONE bit after the FW_PURGE IPC is polled successfully, to clear the
interrupt and avoid the arrival of the confusing unexpected ipc.

Signed-off-by: Keyon Jie yang.jie@linux.intel.com


Since I can't reproduce the issue anymore with the latest topic/sof-dev, now close this issue.

**Comment by mengdonglin** [comment]
@kv2019i @keyonjie FYI. It seems this issue is also fixed by https://github.com/thesofproject/linux/pull/1983
