### ISSUE TITLE
[BUG][CML]Aplay0,2 rt1308 right speaker have sound output when muted speaker in alsamixer.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1953]
**Describe the bug**
Aplay0,2 rt1308 right sepaker have sound output when muted speaker in alsamixer

**To Reproduce**
1.Boot up system successfully.
2.Switch speaker to mute in alsamixer.
2.Aplay -Dhw:0,2 -fs16_le -c2 -r 48000 -vv -i 00.wav

**Reproduce rate**
5/5

**Expected result**
Speaker should't have sound output when selected headphone in soundsetting.

**Actual result**
Aplay0,2 rt1308 right speaker have sound output when muted speaker in alsamixer.

**Test recipe**
kernel: topic/sof-dev commit a272777 + #1943 +#1897
FW: cml-011-drop-stable commit: 37ad771
tplg: cml-011-drop-stable + 827d1f6 which is the same as https://github.com/bardliao/sof/tree/cml-topology
platform: CML-H Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/4397130/dmesg.log)
[sof_error_trace28.log](https://github.com/thesofproject/linux/files/4397131/sof_error_trace28.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4397132/sof_trace.log)

**Comment by plbossart** [comment]
@sinahuang are you sure you muted all speakers? There are 4 speakers on CML-H

**Comment by sinahuang** [comment]
> @sinahuang are you sure you muted all speakers? There are 4 speakers on CML-H





I use the 'Speaker Switch' to mute speaker, not rt1308 switch.
<img width="367" alt="mute-speaker" src="https://user-images.githubusercontent.com/56706782/77871970-3fc8fd00-7278-11ea-933a-ddf8385c17bb.png">

Attached the amixer contents before mute speaker and after mute speaker.
[befor mute speaker.txt](https://github.com/thesofproject/linux/files/4400477/befor.mute.speaker.txt)
[after mute speaker.txt](https://github.com/thesofproject/linux/files/4400478/after.mute.speaker.txt)

**Comment by sinahuang** [comment]
Verified this issue with sof-dev (commit :a272777 + #1943 +#1897+#1954), issue can't be reproduced.
