### ISSUE TITLE
Error while building linux repo with NOCODEC FORCE flag.

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#1965]
When trying to build kernel using scripts with additional flags there is error during building:

steps:

1. git clean -fdx
2. make defconfig
3. config merging using script: kconfig/blob/master/kconfig-sof-default.sh
4. make menuconfig: set NOCODEC support and NOCODEC force flags
5. make bindeb-pkg -j16

**Comment by emilchudzik** [comment]
There is no building issue when using script: kconfig/blob/master/kconfig-sof-nocodec.sh

**Comment by plbossart** [comment]
Fixed already https://github.com/thesofproject/linux/pull/1959
