### ISSUE TITLE
[BUG][CML]Error message cl_dsp_init: timeout for HIPCIE done

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1973]
Bug Description
run sudo rtcwake -s 10 -m mem, after the machine sleep back, check dmesg, you can see the error message: cl_dsp_init: timeout for HIPCIE done error. But no impact on audio functionality.

To Reproduce
1.reboot
2.run sudo rtcwake -s 10 -m mem

Reproduction Rate
5/5

Impact
no functional impact, just error messages
<details>
 <summary>dmesg_error.log</summary>

````
[  103.484427] ACPI: EC: interrupt blocked
[  113.367316] ACPI: EC: interrupt unblocked
[  113.745455] pci 0000:01:00.0: Enabling HDA controller
[  113.917590] iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS
[  114.062946] ata1: SATA link down (SStatus 4 SControl 300)
[  114.600322] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout for HIPCIE done
[  114.600331] sof-audio-pci 0000:00:1f.3: error: status = 0xffffffff panic = 0xffffffff
[  114.600921] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[  114.684773] sof-audio-pci 0000:00:1f.3: firmware boot complete
[  114.739473] OOM killer enabled.
[  114.739473] Restarting tasks ... done.
[  114.776632] PM: suspend exit
````
</details>

Kernel: [97453d9] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)
SOF:[2ef369d57][ https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2/lib/firmware/intel/sof/v1.4.2]
rename sof-cnl.ri to sof-cml.ri
tplg: [sof-hda-generic-2ch.tplg ]
Platform:[CML laptop with onboard codec ALC3204 in HDA mode]
PalseAudio Version: [13.99.1]
UCM2:https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp

[dmesg20200402.log](https://github.com/thesofproject/linux/files/4419087/dmesg20200402.log)
[sof_trace0402.log](https://github.com/thesofproject/linux/files/4419088/sof_trace0402.log)

**Comment by Liviali155** [comment]
Seems same as https://github.com/thesofproject/linux/issues/1472

**Comment by ranj063** [comment]
this issue was fixed when the D0i3 series was merged. Can we please check if this kernel is missing those patches?

**Comment by ClarexZhou** [comment]
Error not seen on latest sof-dev.  Close

**Comment by flotho** [comment]
Hi @ClarexZhou , you wrote that it's solved in sof-dev .
Is there any deadline / info for having this patch in the main packages ?

Please accept all my apologize if this is a totally newbie question.

Anyway thanks for reading this,
Regards

**Comment by mengdonglin** [comment]
@ranj063 Can you comment?

**Comment by keyonjie** [comment]
@mengdonglin just checked and confirmed @ranj063 's D0Ix refinement series are already in the mainline linux master: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/

**Comment by flotho** [comment]
thanks a lot

**Comment by ClarexZhou** [comment]
Verified error not seen with mainline linux master: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git , commit dc56c5acd850_
