### ISSUE TITLE
[Bug][WHL] UCM2 sof-hda-dsp not work on Lenovo X1 Yoga laptop

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1974]
**Bug Description**
UCM2 sof-hda-dsp not work on WHL laptop

**To Reproduce**
1. DUT system os is ubuntu 20.04: cdimage.ubuntu.com/ubuntu/daily-live/current, which include alsa lib version 1.2.2-2.1, pulseaudio verison: 13.99.1
2. Get https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp via git clone and put it under DUT /usr/share/alsa/ucm2  folder
3. Boot up system
4. Open sound setting to check sound input and output source

Reproduction Rate
5/5

Impact
Dummy output is listed in output source. None for input source.

Kernel: [97453d9] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)
FW:[2ef369d57][ https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2/lib/firmware/intel/sof/v1.4.2]
tplg: Same with FW branch [sof-hda-generic-4ch.tplg ]
Platform:[WHL laptop with onboard codec ALC285 in HDA mode]
UCM2:  https://github.com/thesofproject/alsa-ucm-conf, commit 4722f5b3

Dmesg and pulseaudio log
[amixercontents.txt](https://github.com/thesofproject/linux/files/4419128/amixercontents.txt)
[syslog.txt](https://github.com/thesofproject/linux/files/4419129/syslog.txt)

**Comment by juimonen** [comment]
@ClarexZhou can you attach pulseaudio log? So the "normal" procedure... uncomment and set autospawn=no in /etc/pulse/client.conf, pulseaudio --kill, pulseaudio -vvvv 2>&1 pulse.log

**Comment by ClarexZhou** [comment]
Add pulseaudio log with original kernel 5.5.8 
```
I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted
I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted
D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
D: [pulseaudio] core-util.c: RealtimeKit worked.
I: [pulseaudio] core-util.c: Successfully gained nice level -11.
I: [pulseaudio] main.c: This is PulseAudio 13.99.1
D: [pulseaudio] main.c: Compilation host: x86_64-pc-linux-gnu
D: [pulseaudio] main.c: Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/pulseaudio-DSBRDw/pulseaudio-13.99.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wextra -pipe -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wformat-security -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings -Wno-unused-parameter -fno-common -fdiagnostics-show-option -fdiagnostics-color=auto
D: [pulseaudio] main.c: Running on host: Linux x86_64 5.5.8-0401-stablelinux-97453d9b9b2b #1 SMP Wed Apr 1 18:09:05 CST 2020
D: [pulseaudio] main.c: Found 8 CPUs.
I: [pulseaudio] main.c: Page size is 4096 bytes
D: [pulseaudio] main.c: Compiled with Valgrind support: no
D: [pulseaudio] main.c: Running in valgrind mode: no
D: [pulseaudio] main.c: Running in VM: no
D: [pulseaudio] main.c: Running from build tree: no
D: [pulseaudio] main.c: Optimized build: yes
D: [pulseaudio] main.c: FASTPATH defined, only fast path asserts disabled.
I: [pulseaudio] main.c: Machine ID is 29acacf822a9429c990adb1c8c8dca49.
I: [pulseaudio] main.c: Using runtime directory /run/user/1000/pulse.
I: [pulseaudio] main.c: Using state directory /home/ubuntu/.config/pulse.
I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-13.99.1/modules.
I: [pulseaudio] main.c: Running in system mode: no
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
```

And error not seen on latest sof-dev, commit: 052e45d7. Should issue be closed?

**Comment by juimonen** [comment]
@ClarexZhou sorry the pulseaudio log was very short for some reason... so can't too much see what was the original issue. Do we have some requirement for the kernel version here, @mengdonglin ?

**Comment by mengdonglin** [comment]
@juimonen we hope to clarify what's missing in Linux stable kernel 5.5.8 (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8) and figure out what's the recommended upstream kernel for SOF v1.4.2 for upstream users.

**Comment by kv2019i** [comment]
Yeah @juimonen and @mengdonglin , let's investigate this. This is similar to many existing many user reports in https://github.com/thesofproject/linux/issues/1877 . But with 20.04, this should not happen, the alsa-lib should be new enough for UCM2, so let's figure out what is missing.

**Comment by juimonen** [comment]
@ClarexZhou can you still try to attach the "full" pulseaudio log? would be good with non-working and working kernel, if possible. Sorry about this, I have some issues/delays bootstrapping my test device with new ubuntu and ucm2...

**Comment by ClarexZhou** [comment]
@juimonen  Here attach logs on sof dev and 5.5.8 kernel.
Pulseaudio log seems no difference between 2 kernel. Still previous listed messages used command ‘pulseaudio -vvvv >pulse_5.5.8.txt 2>&1’. For file is empty when using ‘pulseaudio -vvvv 2>&1 >pulse_5.5.8.txt ’
Also attached /etc/pulse/client.conf, to check if anything wrong. 
And attached syslog for boot up with pulseaudio.
[amixer_5.5.8.txt](https://github.com/thesofproject/linux/files/4449541/amixer_5.5.8.txt)
[amixer_sofdev.txt](https://github.com/thesofproject/linux/files/4449542/amixer_sofdev.txt)
[client.conf.txt](https://github.com/thesofproject/linux/files/4449545/client.conf.txt)
[dmesg_5.5.8.txt](https://github.com/thesofproject/linux/files/4449546/dmesg_5.5.8.txt)
[dmesg_sofdev.txt](https://github.com/thesofproject/linux/files/4449547/dmesg_sofdev.txt)
[syslog_5.5.8.txt](https://github.com/thesofproject/linux/files/4449550/syslog_5.5.8.txt)
[syslog_sofdev.txt](https://github.com/thesofproject/linux/files/4449553/syslog_sofdev.txt)

**Comment by juimonen** [comment]
@ClarexZhou @mengdonglin I did fresh install of ubuntu 20.04 beta to x1 yoga. Sof is loading and everything seem to work for me... well at least mute leds blink and I can hear sound. sof-hda-dsp is loaded. sound output in settings seems to be Speaker- Cannon point-LP high definition...I did not update any software... the kernel is older as default so 5.4.0-21-generic...

So have you done some dnf upgrade or similar to get newer kernel?

**Comment by ClarexZhou** [comment]
@juimonen  Yes the default kernel is 5.4.0-21-generic..  Tried beta release ubuntu 20.04 http://releases.ubuntu.com/20.04

And Error only can be reproduced when i updated kernel to below v5.5.8
Kernel: [97453d9] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)

Error also not seen if using kernel v5.6.3 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.6.y

**Comment by mengdonglin** [comment]
@kv2019i @juimonen Should we recommend users to use stable kernel 5.6.3 or newer, instead of 5.5.8?

**Comment by ClarexZhou** [comment]
bisect on upstream kernel. Error seen on v5.5.8, but error not seen with next commit ASoC: intel/skl/hda - export number of digital microphones via control compon...
```

2020-03-12 | ASoC: intel/skl/hda - export number of digital microphones via control compon... | Jaroslav Kysela | 
2020-03-05 | Linux 5.5.8v5.5.8
```
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.5.y&id=21b61983da1c701133112d17f18782b129cdfc84

**Comment by plbossart** [comment]
Yes this is a known requirement for HDAudio+dmic UCMs to work. It's my mistake that I indicated v5.5.8 supported this, it was off by one line. So 5.5.9 is the minimal version required. Thanks @ClarexZhou for bisecting.

@mengdonglin FYI, we need to update our minimum recommendation,

**Comment by ClarexZhou** [comment]
close
