### ISSUE TITLE
[BUG][CML]The playback/capture will can't be recovered after stopping then resuming playback/capture on ubuntu 20.04.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1975]
**Describe the bug**
 The playback/capture will can't be recovered after stopping then resuming playback/capture, and all playback/capture pipelines have this issue.

More info:
Issue only can be reproduced on Ubuntu 20.04.
Ctrl+c can recover it.

**To Reproduce**
1.Boot up system successfully;
2. Aplay -Dhw:0,0 -fs16_le -c2 -r 48000 -vv -i wav/48California_Dreaming.wav;
3.Ctrl+z to background;
4. Run "fg" to foreground;

**Reproduce rate**
5/5

**Expected result**
Playback should work normally after background/foreground.

**Actual result**
The playback will can't be recovered after stopping then resuming playback/capture. 
```
ubuntu@ubuntu-XPS-17-9700:~$ aplay -Dhw:0,0 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i
Playing WAVE 'wav/48California_Dreaming.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-soundwire' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16368
  period_size  : 4080
  period_time  : 85000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4080
  period_event : 0
  start_threshold  : 16368
  stop_threshold   : 16368
  silence_threshold: 0
  silence_size : 0
  boundary     : 9214364837600034816
  appl_ptr     : 0
  hw_ptr       : 0
####     +                                         | 16%^Z
[1]+  Stopped                 aplay -Dhw:0,0 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i
ubuntu@ubuntu-XPS-17-9700:~$ fg
aplay -Dhw:0,0 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i
##+                                                | 03%
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:b8464d14
FW: https://github.com/thesofproject/sof/commits/master commit:  5452ac5
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

No error info occured in dmesg when issue happened:
[dmesg11.log](https://github.com/thesofproject/linux/files/4419167/dmesg11.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4419168/sof_trace.log)

**Comment by ClarexZhou** [comment]
Same with #1220 .  Close for system os issue.

**Comment by ClarexZhou** [comment]
Reopen for need debug on 20.04

**Comment by aiChaoSONG** [comment]
This should be an issue of BASH, I have seen this issue with zsh, Ubuntu2004 bash, and ChromeOS bash. Seems the stop/resume case only work with Ubuntu1804 bash

**Comment by ClarexZhou** [comment]
close for bash issue.

**Comment by ClarexZhou** [comment]
No this issue if command without -i
