### ISSUE TITLE
[BUG][TGL]Two channels both output sound at the same time during speaker test on aplay0,0(speaker).

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1977]
**Describe the bug**
Two channels both output sound at the same time when do speaker-test on aplay0,0(Speaker)

**To Reproduce**
1. Boot up.
2. Run command via "speaker-test -Dhw:0,0 -r48000 -f1000 -c2 -t wav -l 5"
3. Check the channels 

**Reproduced rate**
100%
 
**Expected result**
Left channel should be muted status when said "Right", Right channel should be muted status when said "Left"

**Actual result**
Left cahnnel output sound when said "Right".Right cahnnel output sound when said "Left".

**Environment**
kernel:  https://github.com/thesofproject/linux/commits/topic/sof-dev commit b8464d1 + https://github.com/thesofproject/linux/pull/1971 (DSM support) 
FW: https://github.com/thesofproject/sof/tree/tgl-004-drop-stablecommit: 8ad6761 + https://github.com/thesofproject/sof/pull/2405 (WOV tplg) 
tplg: sof-tgl-max98373-rt5682.m4  https://github.com/thesofproject/sof/tree/tgl-004-drop-stablecommit: 8ad6761 + https://github.com/thesofproject/sof/pull/2405 (WOV tplg)
platform: TGL Chromebook w/ RT5682 and Max98373 in I2S mode

due to the issue https://github.com/thesofproject/sof/issues/2507, it blocked the sof-trace log.
[dmesg_speaker.log](https://github.com/thesofproject/linux/files/4419946/dmesg_speaker.log)

**Comment by sinahuang** [comment]
Issue can't be reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by keqiaozhang** [comment]
@sathya-nujella  please help to assign this bug to jairaj-arava. I cannot find his GitHub ID. Thanks.

**Comment by keyonjie** [comment]
This is the max98373 codec configuration issue, each amplifier is configured to work in channel 0/1 mixed mode.

**Comment by keyonjie** [comment]
@YvonneYang2 @sinahuang @keqiaozhang please try run below commands and retry:
```
#amixer cset name='Left DAI Sel Mux' 0
#amixer cset name='Right DAI Sel Mux' 1
```

**Comment by jairaj-arava** [comment]
> @sathya-nujella please help to assign this bug to jairaj-arava. I cannot find his GitHub ID. Thanks.

can you please try now ?

**Comment by jairaj-arava** [comment]
I tried on the Volteer board from both user space and aplay but couldn't repro the issue.
https://www.youtube.com/watch?v=hTvJoYnpeRQ

**Comment by sathya-nujella** [comment]
> @sathya-nujella please help to assign this bug to jairaj-arava. I cannot find his GitHub ID. Thanks.

This is the UCM for this configuration:
https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/b0415c0d6b3c530f6200560ff331f69410f59f3c/overlay-volteer/chromeos-base/chromeos-bsp-volteer/files/ucm-config/sof-tgl_max73rt82/HiFi.conf

please apply both mixer settings from "Speaker" and also default section.

**Comment by keqiaozhang** [comment]
Confirmed that with below 2 amixer settings, this issue is not reproducible. This issue can be closed now.
```
#amixer cset name='Left DAI Sel Mux' 0
#amixer cset name='Right DAI Sel Mux' 1
```
