### ISSUE TITLE
[BUG][TGL]Warning message "snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open DAI intel-hdmi-hifi2: -16" occurred during multipipline test.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1978]
**Describe the bug**
WARNIG messge "snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open DAI intel-hdmi-hifi2: -16" occurred during multipipline test. Other function won't be effected after the warning message shows up.

**To Reproduce**
1. Boot up wiht HDMI external port connected.
2. Run test-case in sof-test with "./multiple-pipeline-playback.sh -c 4 -l 200 -r -t /lib/firmware/intel/sof-tplg/sof-tgl-max98373-rt5682.tplg"

Script:
https://github.com/thesofproject/sof-test/blob/master/test-case/multiple-pipeline-playback.sh

**Reproduced rate**
Will reproduce the issue within 10 iterations each round.
 
**Expected result**
multipipine test works fine.

**Actual result**
Test failed, and dmesg showed "snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open DAI intel-hdmi-hifi2: -16" .

**Environment**
kernel:  https://github.com/thesofproject/linux/commits/topic/sof-dev commit b8464d1 + https://github.com/thesofproject/linux/pull/1971 (DSM support) 
FW: https://github.com/thesofproject/sof/tree/tgl-004-drop-stablecommit: 8ad6761 + https://github.com/thesofproject/sof/pull/2405 (WOV tplg) 
tplg: sof-tgl-max98373-rt5682.m4  https://github.com/thesofproject/sof/tree/tgl-004-drop-stablecommit: 8ad6761 + https://github.com/thesofproject/sof/pull/2405 (WOV tplg)
platform: TGL Chromebook in I2S mode

due to the issue thesofproject/sof#2507, it blocked the sof-trace log.

dmesg:
```
[  308.948705] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x24001e successful
[  308.948712] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  308.948916] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  308.952213] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[  308.952218] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 0 cmd 1
[  308.955342] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x34001e successful
[  308.955353] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  308.955396] snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open DAI intel-hdmi-hifi2: -16
[  308.955406]  iDisp2: ASoC: BE open failed -16
[  308.955410]  HDMI2: ASoC: failed to start some BEs -16
[  308.955503] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  309.373308] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  309.373339] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  309.873274] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  309.873312] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  313.984290] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 0 cmd 0
```
[multipipline_dmesg.log](https://github.com/thesofproject/linux/files/4420025/multipipline_dmesg.log)

**Comment by sinahuang** [comment]
Issue also can be reproduced on TGL-U RVP.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:b8464d14
FW:  https://github.com/thesofproject/sof/commits/master commit: 5452ac5
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode

**Comment by kv2019i** [comment]
I wonder if test is opening the wrong PCM as part of the test (or Pulseaudio running on background)? This error trace is expected if trying to play to a HDMI/DP PCM that is not connected to a monitor. This should not happen in normal usage as Pulseaudio/CRAS only show HDMI/DP PCM devices that are connected.

**Comment by ClarexZhou** [comment]
Error not occurred on TGL chrome with 373 i2s+ 5682 with Kernel https://github.com/thesofproject/linux/commit/5cb79ee6f1cde60dbe8d4d31ff497399dda110af  + PR#2062
FW branch:  tgl-006-drop-stable Commit:f45bf94

**Comment by sinahuang** [comment]
Error also can be seen with https://github.com/thesofproject/sof/tree/tgl-007-drop-stable  on chrome book with codec 98373 in I2S mode.

**Comment by Liviali155** [comment]
Error not seen on TGL Volteer I2S with codec 98357
