### ISSUE TITLE
sof-logger shows nothing w/ or w/o -t parameter

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#198]
There's no trace available with sof-logger.

How to reproduce:
1. aplay -Dhw:0,1 audio.wav
2. sudo /usr/local/bin/sof-logger -l /root/sof-apl.ldc
 CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT
3. sudo /usr/local/bin/sof-logger -l /root/sof-apl.ldc -t
 CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT

Test-env:
GLK hardware version:  Proto2
sof-master:6baff99
soft-master:a1dfcb7
kernel--cros-sof-v4.14-rebase: 3ad0e4ddebf
tplg:sof-glk-da7219.tplg
[dmesg-logger.log](https://github.com/thesofproject/linux/files/2500580/dmesg-logger.log)

**Comment by zhuqingliang** [comment]
On APL: no log with sof-apl-pcm512x.tplg, but have log with test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg

**Comment by Jiangxinx** [comment]
This issue cannot be reproduced with topic/sof-dev branch on UP2.

sof-logge can show error trace without -t on UP2. 

0      1   VOLUME  31120390.833333   1004787.812500             volume.c:463        xro
0      1     PIPE  31120404.739583        13.906250           pipeline.c:903        ePU
0      1  unknown  31120406.927083         2.187500           pipeline.c:904        value 4
0      1     PIPE  31120410.000000         3.072917           pipeline.c:1198       pxr
0      1   VOLUME  32124928.281250   1004518.250000             volume.c:463        xro
0      1     PIPE  32124941.927083        13.645833           pipeline.c:903        ePU
0      1  unknown  32124944.270833         2.343750           pipeline.c:904        value 4
0      1     PIPE  32124947.187500         2.916667           pipeline.c:1198       pxr
0      1   VOLUME  33129776.875000   1004829.687500             volume.c:463        xro
0      1     PIPE  33129790.885417        14.010417           pipeline.c:903        ePU
0      1  unknown  33129793.072917         2.187500           pipeline.c:904        value 4
0      1     PIPE  33129795.989583         2.916667           pipeline.c:1198       pxr

STEP:
1.aplay -Dhw:0,0 audio.wav
2.sudo ./xrun_injection.sh
3.sudo sof-logger -l sof-apl.ldc

Test env:
hardware version: UP2
sof-master: b793f0c1
soft-master: c9a4c87
kernel sof-dev: fe8404a3ba3a
tplg: sof-apl-pcm512x.tplg

**Comment by Jiangxinx** [comment]
Not reproduced with kernel branch debug/v4.19-backport, on APL UP2 platfrom.

STEP:
1.aplay -Dhw:0,0 audio.wav
2.sudo ./xrun_injection.sh
3.sudo sof-logger -l sof-apl.ldc

Test env:
hardware version: UP2
sof-master: 04b1ce48
soft-master: 4ac9248
kernel debug/v4.19-backport: e7da1c44
tplg: sof-apl-pcm512x.tplg

**Comment by keqiaozhang** [comment]
This issue is fixed in kernel-debug/cros-v4.14-rebase: 90eee4 on YORP
