### ISSUE TITLE
[SDW UCM2][BUG][CML-H] Speaker mixer settings are muted by default in alsamixer 

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1997]
**Describe the bug**
Both rt1308-1 DAC L rt1308-1 DAC R and rt1308-2 DAC R rt1308-2 DAC L are muted in default in alsamixer. 

More info:
Need manually change  rt1308-1 DAC L rt1308-1 DAC R and rt1308-2 DAC R rt1308-2 DAC L to unmute in alsamixer can recover.
UCM2:
 https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +https://github.com/thesofproject/alsa-ucm-conf/pull/29

**To Reproduce**
1. Install Ubuntu 20.04 Beta, copy ucm2, update the kernel the firmware.

2. reboot system, without headset connected.
    Confirm speaker is the default output device in Sound Settings.

3. Play a test wave file via PulseAudio: 
    $paplay xx.wav file  
    There is no sound output from the speaker.

4. Check the following RT1308 mixer settings in alsamixer, and found they're all muted
   rt1308-1 DAC L 
   rt1308-1 DAC R 
   rt1308-2 DAC R 
   rt1308-2 DAC L

![Screenshot from 2020-04-08 11-03-17](https://user-images.githubusercontent.com/56706782/78740446-56163d80-7989-11ea-8695-0083d63b96ad.png)

**Reproduce rate**
5/5

**Expected result**
These RT1308 mixser settings should unmuted by default in alsamixer, and there should be audio output from the speaker whey running paplay.

**Actual result**
No sound output when paplay on speaker.
It seems the defaut value of these mixer settings are muted, and not configured successfully by ucm2.

**Test recipe**
OS: Ubuntu 20.04 daily image
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:052e45d
FW: https://github.com/thesofproject/sof/commits/master commit:  b4e8b1e4
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by YvonneYang2** [comment]
This issue can also be reproduced on cml-u laptop sometimes when we boot system for the 1st time after installing Ubuntu 20.04 Beta. If the default speaker mixer value are muted, no sound output are got although speaker is the default output device.  After we manually use alsamixer to unmute the speaker mixers, we can get the sound output from the speaker. And then everything works well even if we reboot the system.

But we also observed the default speaker values can be unmuted on other cml-u devices at 1st boot after installing the Ubuntu 20.04.

It seems the default speaker mixer value is random after we install Ubuntu 20.04 and boot the system.  UCM2 cannot help to unmute the speaker. PulseAudio doesn't care amixer state.

But this issue never happens on the headset (ALC711)

**Comment by plbossart** [comment]
Why are you guys playing with alsamixer and interfering with UCM?

Also can you clarify that the control names are, the screenshots are not very useful since they only show parts of the name

**Comment by plbossart** [comment]
@sinahuang can you please retry with https://github.com/thesofproject/alsa-ucm-conf/pull/34

**Comment by sinahuang** [comment]
Tried with https://github.com/thesofproject/alsa-ucm-conf/pull/34, issue still can be reproduced by the below scenarios.
scenario1:
 Mute speaker and rt1308-1 DAC L rt1308-1 DAC R and rt1308-2 DAC R rt1308-2 DAC L  in alsamixer manually then switch output source to speaker in sound setting, it cannot be unmuted in alsamixer. 
scenario2:
Mute speaker and rt1308-1 DAC L rt1308-1 DAC R and rt1308-2 DAC R rt1308-2 DAC L in alsamixer manually, then tried to reboot system, checked alsamixer after booting up successfully, they are still muted.
```
101 numid=66,iface=MIXER,name='rt1308-1 DAC L Switch'
102   ; type=BOOLEAN,access=rw------,values=1
103   : values=off
104 numid=67,iface=MIXER,name='rt1308-1 DAC R Switch'
105   ; type=BOOLEAN,access=rw------,values=1
106   : values=off
107 numid=9,iface=MIXER,name='rt1308-1 RX Channel Select'
108   ; type=ENUMERATED,access=rw------,values=1,items=4
109   ; Item #0 'LR'
110   ; Item #1 'LL'
111   ; Item #2 'RL'
112   ; Item #3 'RR'
113   : values=0
114 numid=68,iface=MIXER,name='rt1308-2 DAC L Switch'
115   ; type=BOOLEAN,access=rw------,values=1
116   : values=off
117 numid=69,iface=MIXER,name='rt1308-2 DAC R Switch'
118   ; type=BOOLEAN,access=rw------,values=1
119   : values=off
```

[amixer contensts.txt](https://github.com/thesofproject/linux/files/4453614/amixer.contensts.txt)

**Comment by plbossart** [comment]
Again, invalid test. Don't use UCM and change values with alsamixer, that's just wrong.

**Comment by sinahuang** [comment]
The default value of these speaker mixers were off when I boot up for the first time after installing ubuntu 20.04 with UCM2.

**Comment by YvonneYang2** [comment]
Reinstall Ubuntu 20.04 Beta on SDW CML-U and CML-H laptop, copy ucm2, update the kernel the firmware, and reboot system without headphone. Speaker mixer setting are muted by default in alsamixer. Issue can be reproduced. 

More info on CML-U laptop: 
[amixer_contents.txt](https://github.com/thesofproject/linux/files/4460231/amixer_contents.txt)

Screenshot:
![alsamixer](https://user-images.githubusercontent.com/50347470/78969441-843a7f80-7b39-11ea-8203-67dd31e2e4b8.png)
![soundsetting](https://user-images.githubusercontent.com/50347470/78969518-b21fc400-7b39-11ea-9b61-611eb4bc1a4c.png)

**Comment by libinyang** [comment]
> Again, invalid test. Don't use UCM and change values with alsamixer, that's just wrong.

@plbossart We found on some customers' machine, the speaker switch state is "mute". They complained that they can never make the speaker sound however they changed the setting in the "sound setting". This is why we do such test.
I checked the UCM2 configuration with sof-test/test-case/verify-ucm-config.sh. It shows the UCM2 configuration works and can unmute the speaker correctly when the speaker is enabled. This means the UCM2 and alsa-lib is OK for alsaucm. I will continue check the pulseaudio.

This is the same with HDMI: https://github.com/thesofproject/linux/issues/2000

**Comment by libinyang** [comment]
After some debug, it seems to be the pulseaudio issue. I checked UCM2 and UCM on the ubuntu 20.04. Both doesn't work for the enableseqence/disablesequence in the "SectionDevice". And alsa-lib proves to work well with UCM2 with the verify-ucm-config.sh in sof-test. 
It can be ubuntu "sound setting" or pulseaudio issue. To prove it's the pulseaudio issue. I updated the pulseaudio and alsa-lib in ubuntu 18.04. With the new pulseaudio, the bug can be reproduced on ubuntu18.04. So the conclusion is:
ubuntu 20.04:
pulseaudio 13.xx + UCM2: doesn't work
pulseaudio 13.xx + UCM: doesn't work
ubuntu 18.04:
pulseaudio 13.xx + UCM2: doesn't work
pulseaudio 13.xx + UCM: doesn't work
pulseaudio 11.xx + UCM: works
From upper table, in ubuntu 18.04, pulseaudio being updated will cause UCM doesn't work.

**Comment by plbossart** [comment]
> After some debug, it seems to be the pulseaudio issue. I checked UCM2 and UCM on the ubuntu 20.04. Both doesn't work for the enableseqence/disablesequence in the "SectionDevice". And alsa-lib proves to work well with UCM2 with the verify-ucm-config.sh in sof-test.
> It can be ubuntu "sound setting" or pulseaudio issue. To prove it's the pulseaudio issue. I updated the pulseaudio and alsa-lib in ubuntu 18.04. With the new pulseaudio, the bug can be reproduced on ubuntu18.04. So the conclusion is:
> ubuntu 20.04:
> pulseaudio 13.xx + UCM2: doesn't work
> pulseaudio 13.xx + UCM: doesn't work
> ubuntu 18.04:
> pulseaudio 13.xx + UCM2: doesn't work
> pulseaudio 13.xx + UCM: doesn't work
> pulseaudio 11.xx + UCM: works
> From upper table, in ubuntu 18.04, pulseaudio being updated will cause UCM doesn't work.

that's really useful information, now it's going to be challenging to correct this but at least we know where to start, thanks @libinyang

**Comment by libinyang** [comment]
Jaroslav has a patch which has been merged in pulseaudio. I tested the latest pulseaudio, 
the EnableSequence/DisableSequence in SectionDevice works now but it only works when pulseaudio is initializing. After pulseaudio starts, when I switched audio from "Speaker" to "Headphone" in sound setting.

Please check https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/854 for more details

**Comment by libinyang** [comment]
This bug is caused that we are using the single profile (or may be more accurate: switch between ports in the same profile). If we switch to multi profiles mode, this bug is fixed. I'm not sure this is a bug in pulseaudio of single support or it is designed so. I'm confirming with Jaroslav.

**Comment by sinahuang** [comment]
Error not seen with UCM2 https://github.com/libinyang/alsa-ucm-conf/tree/sdw_ucm2_singleprofile/ucm2/sof-soundwire commit:  6bc827

**Comment by sinahuang** [comment]
Error can't be seen with UCM2 https://github.com/thesofproject/alsa-ucm-conf/commits/master commit:12743d2, closed it.
