### ISSUE TITLE
[Bug][EHL]Many unexpected warning sdw message in dmesg after boot up.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#2008]
**Describe the bug**
Unexpected sdw message in dmesg after system boot up, and keeps repeat below 2 message. No effect for I2S functions
```
	Line 837: [    3.864146] intel-master sdw-master-0: Bus clash for control word
	Line 838: [    3.864400] intel-master sdw-master-0: Parity error
```

**To Reproduce**
sudo reboot to boot up system 

**Reproduction Rate**
3/3

**Expected behavior**
Shouldn't have SDW related message, since EHL is using I2S now.

**Impact**
Only SDW message in dmesg, not effect functions.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev, commit 4b4681e
    * SOF: https://github.com/thesofproject/sof/releases/tag/v1.5-rc1, commit: 5f7d4e2, using sof-tgl.ri rename to sof-ehl.ri
2) Name of the topology file
    * Topology: sof-ehl-rt5660.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: EHL RVP with RT5660 in I2S mode

Dmesg
```
	Line 766: [    3.718110] intel-master sdw-master-0: SDW Slave Addr: 10025d070100
	Line 767: [    3.718112] intel-master sdw-master-0: SDW Slave class_id 0, part_id 701, mfg_id 25d, unique_id 0, version 1
	Line 768: [    3.718120] intel-master sdw-master-0: SDW Slave Addr: 10025d070000
	Line 769: [    3.718122] intel-master sdw-master-0: SDW Slave class_id 0, part_id 700, mfg_id 25d, unique_id 0, version 1
	Line 770: [    3.718161] intel-master sdw-master-0: SDW Slave Addr: 10025d070000
	Line 771: [    3.718162] intel-master sdw-master-0: SDW Slave class_id 0, part_id 700, mfg_id 25d, unique_id 0, version 1
	Line 772: [    3.718165] intel-master sdw-master-0: SDW Slave Addr: 10025d070100
	Line 773: [    3.718166] intel-master sdw-master-0: SDW Slave class_id 0, part_id 701, mfg_id 25d, unique_id 0, version 1
	Line 778: [    3.736001] rt700 sdw:0:25d:700:0: probe complete
	Line 820: [    3.857541] intel-master sdw-master-0: intel_link_power_up: powering up all links
	Line 821: [    3.857542] intel-master sdw-master-0: intel_link_power_up: first link up, programming SYNCPRD
	Line 822: [    3.863606] intel-master sdw-master-0: PCM cap bd:6 in:0 out:0
	Line 823: [    3.863618] intel-master sdw-master-0: PDM cap bd:0 in:4 out:0
	Line 836: [    3.864115] intel-master sdw-master-0: Parity error
	Line 837: [    3.864146] intel-master sdw-master-0: Bus clash for control word
	Line 838: [    3.864400] intel-master sdw-master-0: Parity error
	Line 839: [    3.864424] intel-master sdw-master-0: Bus clash for control word
	Line 841: [    3.864490] intel-master sdw-master-0: Parity error
	Line 842: [    3.864512] intel-master sdw-master-0: Bus clash for control word
	Line 843: [    3.864581] intel-master sdw-master-0: Parity error
	Line 844: [    3.864606] intel-master sdw-master-0: Bus clash for control word
	Line 845: [    3.864701] intel-master sdw-master-0: Parity error
```
[dmesg.txt](https://github.com/thesofproject/linux/files/4469305/dmesg.txt)
[soflogger_all.txt](https://github.com/thesofproject/linux/files/4469307/soflogger_all.txt)

**Comment by ClarexZhou** [comment]
Error also seen on sof Master, commit 3808dfec

**Comment by plbossart** [comment]
@ClarexZhou please disable SoundWire in the BIOS menu....

**Comment by libinyang** [comment]
The BIOS setting seems OK. We set "Audio Link Mode" to "SSP (I2S)" mode. Please see the attachment.

![1](https://user-images.githubusercontent.com/10509113/79190537-266aa800-7e57-11ea-8bce-09ce4c19d81d.png)

**Comment by libinyang** [comment]
I tried to use "Advanced Link Config" and manually disabled SDW. And now the sdw message disappears. So the bug can be closed. It should be the BIOS issue that it doesn't really turn off all the SDW related setting in SSP mode.  
@plbossart Do you know whether it is expected that SDW will be enabled in SSP mode? If it is not, should we report a bug to BIOS?

![2](https://user-images.githubusercontent.com/10509113/79194662-8402f280-7e5f-11ea-8a40-06fea6086958.png)

**Comment by plbossart** [comment]
@libinyang I think everyone uses the advanced mode, that way you control what you really need. Let's close this bug, thanks @ClarexZhou and @libinyang
