### ISSUE TITLE
[BUG][CML]Pop noise occured in headset when resume from suspend without aplay via headset

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2015]
Describe the bug
Pop noise occured in headset when resume from suspend without aplay via headset
Reboot with headset connected,resume from suspend  without playback or resume from suspend  with HDMI/DP/speaker/ playback can reproduce this issue
Error  only occured when wakeup,not seen when suspend

To Reproduce
1.sudo reboot with headset connected
2."sudo rtcwake -m mem -s 10" to suspend without playback
3.wait device to wake up

Reproduction Rate
Suspend/resume 10 times,6times the pop noise is very loud,4times the sound is small
If connected headset after reboot,suspend/resume 10 times ,the pop noise is always  small

Expected behavior
There is no pop noise when suspend/resume

Actual result
Pop noise occured in headset when wake up

Platform: CML laptop with onboard codec ALC3204 in HDA mode
Firmware: 5f7d4e2 https://github.com/thesofproject/sof/releases/tag/v1.5-rc1
Kernel: stable linux 5.5.9 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.9, commit 81b6e04
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2:UCM2:https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp

[dmesg0415.log](https://github.com/thesofproject/linux/files/4480750/dmesg0415.log)
[sof-logger0415.log](https://github.com/thesofproject/linux/files/4480751/sof-logger0415.log)

**Comment by Liviali155** [comment]
Issue can not be reproduced on sof/dev(commit:73187435)

Issue can be reproduced on :
5.5.8 Kernel: [97453d9b] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)
5.6.3 kernel:commit f9fb8575

**Comment by Liviali155** [comment]
On sof/dev
Fail on commit https://github.com/thesofproject/linux/commit/2f0d4d4b2e9d48fd9a776332808439b92cb8ca96
Pass on commit https://github.com/thesofproject/linux/commit/22d5e98fe5cf82e842fb025d59d6edcf9f03a528

Seems PR #1983 fix this issue on /sof/dev

**Comment by Liviali155** [comment]
Issue can be reproduced after revert PR #1983

**Comment by ClarexZhou** [comment]
Close, for error can be fixed by PR #1983  which already merged in sof-dev
