### ISSUE TITLE
[BUG][TGL]HDMI aplay failed after reboot with HDMI connected on ubuntu 20.04 Beta

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2024]
***Describe the bug***
HDMI aplay failed after reboot with HDMI connected
If connect HDMI after reboot,error not seen
If reboot with HDMI and DP,error not seen
After error occured,other pipeline will also aplay failed

Error only occured on ubuntu 20.04(http://releases.ubuntu.com/20.04),not seen on ubuntu 18.04

***To Reproduce***
1.Connect HDMI monitor
2.Reboot system via "sudo reboot"
3.Reboot system via "sudo reboot"
4.aplay -Dhw:0,4 -r48000 -c2 -fs16_le  wav/48California_Dreaming.wav -vv -i

***Reproduction Rate***
5/5

Expected behavior
HDMI aplay normally

Impact
HDMI aplay failed
<img width="300" alt="hdmi" src="https://user-images.githubusercontent.com/56707932/79706996-99f43580-82ed-11ea-80fc-7c61f44ec2e9.PNG">

<img width="264" alt="Capture" src="https://user-images.githubusercontent.com/56707932/79707871-72eb3300-82f0-11ea-9abe-fefd5f91cddc.PNG">

<details>
 <summary>dmesgerror.log</summary>

````
[    7.916115] [drm] Reducing the compressed framebuffer size. This may lead to less power savings than a non-reduced-size. Try to increase stolen memory size if available in BIOS.
[    8.101613] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    8.199367] rfkill: input handler disabled
[  379.002994] snd_hda_codec_hdmi ehdaudio0D2: Unable to sync register 0x2f8100. -5
[  906.967209] [drm] Reducing the compressed framebuffer size. This may lead to less power savings than a non-reduced-size. Try to increase stolen memory size if available in BIOS.
````
</details>

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: 9915b803 https://github.com/thesofproject/sof/commits/master
Kernel: f9b87470 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/ sof-hda-generic-4ch.tplg same as firmware

[dmesg0418.log](https://github.com/thesofproject/linux/files/4500831/dmesg0418.log)
[sof-logger0418.log](https://github.com/thesofproject/linux/files/4500832/sof-logger0418.log)

**Comment by Liviali155** [comment]
Error not seen on
CML laptop with onboard codec ALC3204 in HDA mode

**Comment by ClarexZhou** [comment]
@kv2019i  could help to check this HDMI issue?

**Comment by kv2019i** [comment]
Ack, will take a look.

**Comment by Liviali155** [comment]
On stable linux 5.5.9 both  HDMI&DP aplay failed  on below scene
1.sudo reboot with HDMI/DP connected
2.Plug HDMI/DP after reboot

Also only occued  on ubuntu 20.04

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
linux 5.5.9 , commit [81b6e04c] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.9
FW v1.5-rc4 (2d72fd2c)
Topology: file: tools/topology/ sof-hda-generic-4ch.tplg same as firmware


[dmesg0423.log](https://github.com/thesofproject/linux/files/4522123/dmesg0423.log)
[sof-logger0423.log](https://github.com/thesofproject/linux/files/4522124/sof-logger0423.log)

**Comment by kv2019i** [comment]
@Liviali155 This seems like HDMI audio not powering up properly:
[  379.002994] snd_hda_codec_hdmi ehdaudio0D2: Unable to sync register 0x2f8100. -5

Would you be able to take DRM logs when the error happens (sof-dev is ok as kernel version). The first attached log doesn't have DRM debugs, and the most recent one is a very short one and doesn't messages from start of system boot.

**Comment by Liviali155** [comment]
> @Liviali155 This seems like HDMI audio not powering up properly:
> [ 379.002994] snd_hda_codec_hdmi ehdaudio0D2: Unable to sync register 0x2f8100. -5
> 
> Would you be able to take DRM logs when the error happens (sof-dev is ok as kernel version). The first attached log doesn't have DRM debugs, and the most recent one is a very short one and doesn't messages from start of system boot.

drmlog as attachment,you can check it if useful
[drm.log](https://github.com/thesofproject/linux/files/4526880/drm.log)

**Comment by kv2019i** [comment]
@Liviali155 wrote:
> drmlog as attachment,you can check it if useful
> [drm.log](https://github.com/thesofproject/linux/files/4526880/drm.log)

It's still missing the early boot. The DRM log is so verbose that it fills the dmesg buffer very quickly and e.g. this log is missing lot of events from the early boot. You can overcome by increasing the dmesg size. "log_buf_len=1M" should be sufficient. You can add this e.g. with following to to /etc/default/grub:

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash log_buf_len=1M"

**Comment by Liviali155** [comment]
After added GRUB_CMDLINE_LINUX_DEFAULT="quiet splash log_buf_len=1M",log as attachment
[kern.log](https://github.com/thesofproject/linux/files/4534523/kern.log)

**Comment by kv2019i** [comment]
Thanks @Liviali155  This now contains a lot of useful information. At least following trace pops out:

Apr 26 10:23:39 ubuntu-Tiger-Lake-Client-Platform kernel: [    7.641614] [drm:audio_config_hdmi_pixel_clock [i915]] HDMI audio pixel clock setting for 154000 not found, falling back to defaults
Apr 26 10:23:39 ubuntu-Tiger-Lake-Client-Platform kernel: [    7.641627] [drm:audio_config_hdmi_pixel_clock [i915]] Configuring HDMI audio for pixel clock 25200 (0x00010000)

I'd like to ask a few more logs.

1) logs showing debugs from HDMI codec driver on ALSA side

You can enable these without rebuilding kernel by adding following to a file under /etc/modprobe.d/

```
options snd_hda_core dyndbg=+p
options snd_hda_codec dyndbg=+p
options snd_hda_codec_generic dyndbg=+p
options snd_hda_ext_core dyndbg=+p
options snd_hda_codec_hdmi dyndbg=+p
```

2. Logs with same settings for succesful case

Could you take a log from a scenario where aplay works on the otherwise same machine? I'd like to compare the logs between success and failure cases.

In the background I'll start trying to reproduce this myself as well.

**Comment by Liviali155** [comment]
@kv2019i 
1.After  enable below items,failed log as attachment
 ```
options snd_hda_core dyndbg=+p
options snd_hda_codec dyndbg=+p
options snd_hda_codec_generic dyndbg=+p
options snd_hda_ext_core dyndbg=+p
options snd_hda_codec_hdmi dyndbg=+p
```
[kern_failed.log](https://github.com/thesofproject/linux/files/4543163/kern_failed.log)

2.Reboot with both HDMI and DP connected,HDMI can aplay successfully,pass log as attachment
[kern_pass.log](https://github.com/thesofproject/linux/files/4543164/kern_pass.log)

**Comment by ClarexZhou** [comment]
Error not occurred on Dell TGL laptop with onboard codec ALC3204 in HDA mode

**Comment by Liviali155** [comment]
Error only seen on ubuntu20.04 beta release(http://releases.ubuntu.com/20.04/ )
Error not seen on ubuntu20.04  LTS(https://ubuntu.com/download/desktop/thank-you?version=20.04&architecture=amd64 )
So closed it

**Comment by mengdonglin** [comment]
I guess this issue was fixed by GFX firmware or drm-lib update in ubuntu20.04 LTS, as we're using the same kernel and audio firmware.

**Comment by kv2019i** [comment]
Ack @Liviali155 and @mengdonglin . This is pretty suprising indeed.
