### ISSUE TITLE
[BUG][CML][UCM2]Sometimes no sound output after unplug headset then plug again(random)

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2025]
Describe the bug
Sometimes no sound output after unplug headset then plug again(random)
Ubuntu 20.04
```
ubuntu@cml-hda-mantis-1:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
To Reproduce
1.sudo reboot
2.wait runtime pm status suspend
3.plugin headset
4.open sound settings
5.set input device as “Headset Mono Microphone-sof-hda-dsp”,output Device as "Headphone-sof-hda-dsp"
6.aplay -Dhw:0,0 -r48000 -c2 -fs16_le  wav/48California_Dreaming.wav -vv -i(has sound output) or paplay -vv wav/48California_Dreaming.wav(has sound output)
7.unplug headset
8.plugin headset again
9.has no sound output in headset

Reproduction Rate
8/10

Expected behavior
There is sound output after unplug headset then plugin again

Actual result
The input device was “Headset Mono Microphone-sof-hda-dsp”  after unplug/plug headset, But Sometimes still no sound output 
Need to change input device as "Headphones Stereo Microphone-sof-hda-dsp",then “Headset Mono Microphone-sof-hda-dsp” again,there is sound output in headset
log and amixer contents as attachment, seems there is no difference betweem amixercontents_pass.txt and amixercontents_fail.txt

Platform: Dell CML laptop with onboard codec ALC3204 in HDA mode
Firmware: 504ec438 https://github.com/thesofproject/sof/commits/master
Kernel: 202bac22 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2: 907c8309 https://github.com/alsa-project/alsa-ucm-conf 
                          +  https://github.com/alsa-project/alsa-ucm-conf/pull/21

[amixercontents_fail.txt](https://github.com/thesofproject/linux/files/4501436/amixercontents_fail.txt)
[amixercontents_pass.txt](https://github.com/thesofproject/linux/files/4501437/amixercontents_pass.txt)
[dmesg0420.log](https://github.com/thesofproject/linux/files/4501438/dmesg0420.log)
[sof-logger-0420.log](https://github.com/thesofproject/linux/files/4501439/sof-logger-0420.log)

**Comment by juimonen** [comment]
Debugging this further:

I can see that when inserting headset, pulseaudio is actually enabling first "Headphones2" from ucm and sending to codec the command to set "Input Source" to "Headphone Mic", however immediately after that it is enabling "Headset" from ucm and setting the "Input Source" correctly to "Headset Mic".

I can see this HDA verb sequence set with "cat /sys/kernel-debug/tracing/trace | grep 2336 -A1" so hda_send_cmd sets input source first to "Headphone Mic" then immediately after to "Headset  Mic". 
Also the response from command setting is 0, so successful.

There's no difference in "cat /proc/asound/card0/codec#0" with cases where the sound is muted or audible. There's also no difference in alsamixer (as reported before by @Liviali155)

So I can only deduce that somehow the codec is losing the second setting for "Headset Mic" even though it is sent, and there is no bus error etc. So don't know is the codec somehow busy executing the first command set and can't somehow react to second set?

@kailangyang any thoughts?

**Comment by juimonen** [comment]
@Liviali155 @mengdonglin we should add some label if this is related to only some codec/platform like mantis...

**Comment by ClarexZhou** [comment]
Error also seen on CFL ALC3254 HDA laptop. which also support headphone stere microphone and headset mono microphone.
UCM2: https://github.com/alsa-project/alsa-ucm-conf/UCM2 + https://github.com/alsa-project/alsa-ucm-conf/pull/21
Kernel: sof-dev 8dc1789e
Firmware & tplg: Master 0befebb7

**Comment by ClarexZhou** [comment]
No this issue on Lenovo X1 yoga

**Comment by Liviali155** [comment]
On matins changed to legacy HDA,runtime_status  is always active
After unplug headset then plug again,it will popup "select audio device " as below:
if select Headset,it has sound output in headset,so error not seen on legacy HDA
<img width="298" alt="Capture" src="https://user-images.githubusercontent.com/56707932/80298823-97e51780-87c2-11ea-8bba-7f10a5a9c5ee.PNG">
after used “echo 1 > /sys/module/snd_hda_intel/parameters/power_save“ to enable pm runtime_status,it can enter susupend,unplug/plug headset 50times,issue still can not be reproduced

**Comment by ClarexZhou** [comment]
Error also seen on CML I3 DIS SRN5 with ALC3204 in HDA mode, which also support Headphone stero Micrphone and Headset Mono Microphone.

Recover method: 
Method 1: select Headphone stero Micrphone in sound setting, then select Headset Mono Micrphone again.
Method 2: stop current aplay/paplay, wait till runtime PM suspended, then play again, audio can output normally.

UCM2: https://github.com/alsa-project/alsa-ucm-conf/UCM2 + https://github.com/alsa-project/alsa-ucm-conf/pull/21

**Comment by juimonen** [comment]
@ClarexZhou what if we disable PM in SOF case? I mean this is a use case where we are playing all the time, but if the controller part is doing some sleep etc?

**Comment by ClarexZhou** [comment]
@juimonen  Error not seen when wait runtime PM suspend.
Error only can be reproduced when do both "plug out" and "plug in headset" action during playback.
And once issue occurred, release current playback and wait till runtime PM suspended, then play again,  audio can output normally.

**Comment by juimonen** [comment]
@kailangyang ping. Sorry to bother you with this, but I'm little bit out of tools/skills to debug this further. Would there be anyone in realtek to check this out? For me it seems correct webs are sent to coded, but they are just not "sticking"... This is the mantis hw.

**Comment by KailangYang** [comment]
Please also test it with legacy hda driver.

**Comment by KailangYang** [comment]
If legacy HDA driver passed this issue.
I think this symptom was not related with codec driver.

**Comment by Liviali155** [comment]
> Please also test it with legacy hda driver.

Have tested with legacy hda on matins ,error not seen,details as previous comments

**Comment by KailangYang** [comment]
So, it shows codec driver was good.
You need to move focus to hda controller code of SOF.

**Comment by juimonen** [comment]
@Liviali155 @kailangyang legacy hda doesn't work the same way as you get the pop up... when you set something on pop-up it will send the command to switch again. So it is not the same use case. I'm pretty sure the sof will also work with the pop-up.

The actual use case is to send to codec in very rapid manner switch from one 'Input source' to another. And that's when something strange happens with the bus, so it can't "digest" all settings even though there' no error. I don't know if we could "mimic" the rapid verb changing as pulseaudio does it?

**Comment by ClarexZhou** [comment]
To replace of alsa-project/alsa-ucm-conf#21.
@jason77-wang:  try to change the MR for libgvc based on the available_group and type members.
But for those don't use gnome, I send a PR to pulseaudio to let pulseaudio handle them with priority considered. Hope this could be accepted.
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/294

**Comment by Liviali155** [comment]
Because issue #1991  after update pulseaudio to default pulseaudio of Ubuntu20.04+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/294+ https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295
HAD UCM2: https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 81465c56),
error not seen,do not use alsa-project/alsa-ucm-conf#21,so closed this issue

**Comment by Liviali155** [comment]
> Because issue #1991 after update pulseaudio to default pulseaudio of Ubuntu20.04+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/294+ https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295
> HAD UCM2: https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 81465c56),
> error not seen,do not use [alsa-project/alsa-ucm-conf#21](https://github.com/alsa-project/alsa-ucm-conf/pull/21),so closed this issue

Reopen this issue 
after update pulseaudio to default pulseaudio of Ubuntu20.04+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/294+ https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295
> HAD UCM2: https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 81465c56),
> error still can be reproduced,the frequency is lower,about 1/20

**Comment by Liviali155** [comment]
Test with latest sof-dev(866e4d55)+Master(6cfd3e5a) used below step:
1."sudo reboot" to reboot system
2.Plug headset
3.paplay -vv wav/48California_Dreaming.wav
4.wait for 5s to unplug headset
5.wait for 5s to plug headset
6.repeat step4-step5
1st: Error occured when repeat step4-step5 35th
2nd: Error occured when repeat step4-step5 first

**Comment by mengdonglin** [comment]
Won't fix this codec issue.
