### ISSUE TITLE
[BUG] X1 Carbon 7th Gen, Linux 5.5.0-2-amd64 Debian 5.5.17-1 microphones undetected

### ISSUE THREAD

**Issue by HilleniusGijs** [thesofproject/linux#2026]
**Describe the bug**
Thinkpad X1 Carbon 7th generation
Debian Unstable, Linux 5.5.0-2-amd64 Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux
Has sound, but microphones are not detected. Or perhaps they're detected, but ... they're not working

**Expected behavior**
It would be great to have the mics working. 

**Impact**
A headset microphone works fine, so not all is lost.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: Linux 5.5.0-2-amd64 Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux
    * SOF: {SHA} I don't know, sorry.  

Should I be downloading firmware? Update: I have installed SOF firmware 1.4.2 in /lib/firmware/intel/sof/. But this does not make any difference.

The module is "snd_soc_sof_rt5682.ko" (I think)
alsa-ucm-conf  alsa-topology-conf alsa-utils : 1.2.2-1

2) Name of the topology file
    * Topology: the ucm2 directory has: 
HDA-Capture-value.conf 
Hdmi.conf
HiFi.conf
sof-hda-dsp.conf 

3) Name of the platform(s) on which the bug is observed.
Debian unstable

**Screenshots or console output**
from syslog:

snd_hda_intel 0000:00:1f.3: dmic_detect option is deprecated, pass snd-intel-dspcfg.dsp_driver=1 option instead
snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])

and also:

snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
snd_hda_codec_realtek hdaudioC0D0:    inputs:
snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19

alsaucm listcards
ALSA lib utils.c:261:(uc_mgr_config_load) could not open configuration file /usr/share/alsa/ucm2/HDA-Intel/HDA-Intel.conf
alsaucm: error failed to get card list: No such file or directory

alsaucm -i
alsaucm: Interacive mode - 'q' to quit
alsaucm>> open sof-hda-dsp
ALSA lib ucm_cond.c:207:(if_eval_control_exists) cannot determine control device
ALSA lib main.c:962:(snd_use_case_mgr_open) error: failed to import sof-hda-dsp use case configuration -22
alsaucm: error failed to open sound card sof-hda-dsp: Invalid argument
^^^ error, try again

/usr/share/alsa/ucm2/ has sof-hda-dsp
/usr/share/alsa/ucm is empty bar a README.md

**Comment by HilleniusGijs** [comment]
thanks @kv2019i 

here is an update:

I have sof-cnl.ri in /lib/firmware/intel/sof which is "sof-cnl-1.4.2.ri"
I also have symlinked sof-hda-generic-4ch.tplg  sof-hda-generic.tpl in /lib/firmware/intel/sof-tplg/ 

And the kernel command line has  snd-intel-dspcfg.dsp_driver=3

This results in (dmesg | grep sof-adio):

[   38.869672] sof-audio-pci 0000:00:1f.3: warning: No matching ASoC machine driver found
[   38.869676] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   38.869813] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[   38.870079] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   38.880583] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[   38.880584] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   38.967944] sof-audio-pci 0000:00:1f.3: firmware: direct-loading firmware intel/sof/sof-cnl.ri
[   38.968640] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[   38.968641] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   42.033944] sof-audio-pci 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   42.034454] sof-audio-pci 0000:00:1f.3: error: load fw failed ret: -110
[   42.034469] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
[   42.034476] sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
[   42.034477] sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware -110
[   42.085010] sof-audio-pci 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[   42.085011] sof-audio-pci 0000:00:1f.3: error: dsp core reset failed: core_mask f
[   42.101336] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -110

and so no sound no microphone. I guess I need at least some options in 
/etc/modprobe.d/alsa-base.conf

**Comment by kv2019i** [comment]
Ok good @dingesista -- just as I moved to kernel component, this error now seems like a FW one. Based on the errors, it would seem the firmware is not a signed one and the error seems same as https://github.com/thesofproject/sof/issues/2264 

You should be using this firmware file:
https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2/lib/firmware/intel/sof/v1.4.2/intel-signed

**Comment by HilleniusGijs** [comment]
@kv2019i 

Thanks! 

Here is the current situation: I've downloaded those three files, and cleaned out the previous versions:

ls /lib/firmware/intel/sof/
sof-apl-v1.4.2.ri  sof-cnl-v1.4.2.ri  sof-icl-v1.4.2.ri

I also removed /lib/firmware/intel/sof-tplg

the kernel command line is:
 
Kernel command line: BOOT_IMAGE=/vmlinuz-5.5.0-2-amd64 root=/dev/mapper/inauditus--vg-root ro snd-intel-dspcfg.dsp_driver=3 quiet

rebooting results in: 
snd_hda_intel 0000:00:1f.3: dmic_detect option is deprecated, pass snd-intel-dspcfg.dsp_driver=1 option instead
[   11.296812] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   11.414512] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[   11.414514] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   11.414515] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[   11.414516] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[   11.414517] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[   11.414518] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19

Sound works, but there is no mic. And I have a feeling this does not use the right module. Previously  - linux 5.3 - I had to blacklist snd_hda_intel *and* snd_soc_skl.

FWIW, I will now attempt: snd-intel-dspcfg.dsp_driver=0 as kernel command line:

dmesg | grep snd
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.5.0-2-amd64 root=/dev/mapper/inauditus--vg-root ro snd-intel-dspcfg.dsp_driver=0 quiet
[    0.184217] Kernel command line: BOOT_IMAGE=/vmlinuz-5.5.0-2-amd64 root=/dev/mapper/inauditus--vg-root ro snd-intel-dspcfg.dsp_driver=0 quiet
[   20.435249] snd_hda_intel 0000:00:1f.3: dmic_detect option is deprecated, pass snd-intel-dspcfg.dsp_driver=1 option instead
[   20.435431] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   20.476414] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[   20.476416] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   20.476417] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[   20.476418] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[   20.476418] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[   20.476419] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19

**Comment by HilleniusGijs** [comment]
I renamed the firmware files:

ls /lib/firmware/intel/sof
sof-apl.ri  sof-cnl.ri	sof-icl.ri

I added again the topology files (in /lib/firmware/intel/sof-tplg/ 

but these are perhaps the wrong ones? 

dmesg | grep snd
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.5.0-2-amd64 root=/dev/mapper/inauditus--vg-root ro snd-intel-dspcfg.dsp_driver=0 quiet
[    0.183970] Kernel command line: BOOT_IMAGE=/vmlinuz-5.5.0-2-amd64 root=/dev/mapper/inauditus--vg-root ro snd-intel-dspcfg.dsp_driver=0 quiet
[   20.217140] snd_hda_intel 0000:00:1f.3: dmic_detect option is deprecated, pass snd-intel-dspcfg.dsp_driver=1 option instead
[   20.226849] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   20.288623] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[   20.288625] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   20.288626] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[   20.288627] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[   20.288627] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[   20.288628] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19

**Comment by plbossart** [comment]
@dingesista please remove all sof and sof-tplg directories and re-install from https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2 (with the go.sh script).

Also remove all options and let the kernel select the right driver, you are likely using the wrong option anyways:
````
[ 20.217140] snd_hda_intel 0000:00:1f.3: dmic_detect option is deprecated, pass snd-intel-dspcfg.dsp_driver=1 option instead
````

**Comment by HilleniusGijs** [comment]
@plbossart  thanks!

Sorry, I need a little more help. I'm not sure what that go.sh script is supposed to do. Running it just like that puts some files in /root and also a symlink to a non-existing directory in  / (root). 

So, next step: I undid all of the above modifcations, to grub, rm the sof and sof-tplg directories in /lib/firmware/intel and used the file names and paths from the go script.

I recreated the /lib/firmware/intel/sof directory, and in there are: 
sof-apl.ri  sof-bdw.ri  sof-byt.ri  sof-cht.ri  sof-cnl.ri  sof-icl.ri 

these are symlinks to the same files in a 14.2/intel-signed directory, same as in the go script.

Then I put all 68 topology files in the /lib/firmware/intel/sof-tplg directory.

Rebooted. the result is same as before: the snd_hda_codec_realtek is used and there is audio, but no mike. 

Next, I decided to blacklist snd_hda_intel and snd_soc_skl (something that I had to do with  linux-5.3). Rebooted.. and dmesg indicates lots of  sof-audio messages except now there is neither sound nor microphone and a headset will not work either. 

[   14.682323] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   14.682434] sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   14.682573] sof-audio-pci 0000:00:1f.3: warning: No matching ASoC machine driver found
[   14.682721] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   14.682839] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[   14.683472] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   14.692283] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[   14.692284] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   14.707402] sof-audio-pci 0000:00:1f.3: firmware: direct-loading firmware intel/sof/sof-cnl.ri
[   14.708014] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[   14.708016] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   14.807419] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:4:2-66a5a
[   14.807421] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:11:0 Kernel ABI 3:11:0
[   14.807651] sof-audio-pci 0000:00:1f.3: firmware boot complete
[   14.858683] sof-audio-pci 0000:00:1f.3: firmware: direct-loading firmware intel/sof-tplg/sof-hda-generic-4ch.tplg
[   14.858692] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:11:0 Kernel ABI 3:11:0
[   14.858696] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp3 Tx not handled
[   14.859765] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec0_in not handled
[   14.859768] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp2 Tx not handled
[   14.862323] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec1_in not handled
[   14.862325] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp1 Tx not handled
[   14.863702] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec0_out not handled
[   14.863703] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Analog CPU Playback not handled
[   14.865507] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec1_out not handled
[   14.865508] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Digital CPU Playback not handled
[   14.865509] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec2_in not handled
[   14.865510] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Alt Analog CPU Playback not handled
[   14.865511] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec2_out not handled
[   14.865513] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Analog CPU Capture not handled
[   14.868279] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp1_out not handled
[   14.868280] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Digital CPU Capture not handled
[   14.869663] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp2_out not handled
[   14.869665] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Alt Analog CPU Capture not handled
[   14.872935] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp3_out not handled
[   14.881210] sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[   17.207701] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   17.301906] sof-audio-pci 0000:00:1f.3: firmware boot complete
[   22.079662] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   22.173890] sof-audio-pci 0000:00:1f.3: firmware boot complete

**Comment by HilleniusGijs** [comment]
I've made some progress on this @lgirdwood @mengdonglin The short version: with one change, the firmware is loaded. However it all works oddly and only temporarily.

here is what I did:

1) I noticed that  https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2 and the go.sh script have been updated. 
2) So, I cleaned the slate (no tweaks in /etc/modprobe) , and refreshed the sof and sof-tplg firmware files.

That resulted in errors such as:
Direct firmware load for intel/sof/sof-cnl.ri failed with error -2
sof-audio-pci 0000:00:1f.3: error: request firmware intel/sof/sof-cnl.ri failed err: -2
sof-audio-pci 0000:00:1f.3: error: failed to load DSP firmware -2
sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -2

Then, reading https://github.com/thesofproject/linux/issues/2013 I created a symlink from the cnl file to the cml file. That works!

[   11.435367] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   11.435500] sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   11.435649] sof-audio-pci 0000:00:1f.3: warning: No matching ASoC machine driver found
[   11.435654] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   11.435775] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[   11.435985] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   11.445566] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[   11.445568] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   11.531609] sof-audio-pci 0000:00:1f.3: firmware: direct-loading firmware intel/sof/sof-cnl.ri
[   11.532844] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[   11.532845] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   11.618185] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:4:2-66a5a
[   11.618187] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:11:0 Kernel ABI 3:11:0
[   11.618547] sof-audio-pci 0000:00:1f.3: firmware boot complete
[   11.685730] sof-audio-pci 0000:00:1f.3: firmware: direct-loading firmware intel/sof-tplg/sof-hda-generic-4ch.tplg
[   11.685737] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:11:0 Kernel ABI 3:11:0
[   11.685739] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp3 Tx not handled
[   11.686619] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec0_in not handled
[   11.686621] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp2 Tx not handled
[   11.687309] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec1_in not handled
[   11.687310] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp1 Tx not handled
[   11.688008] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec0_out not handled
[   11.688010] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Analog CPU Playback not handled
[   11.688701] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec1_out not handled
[   11.688703] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Digital CPU Playback not handled
[   11.688704] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec2_in not handled
[   11.688705] sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Alt Analog CPU Playback not handled
[   11.688706] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec2_out not handled
[   11.688708] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Analog CPU Capture not handled
[   11.689397] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp1_out not handled
[   11.689398] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Digital CPU Capture not handled
[   11.690104] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp2_out not handled
[   11.690105] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Alt Analog CPU Capture not handled
[   11.690828] sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp3_out not handled
[   11.701948] sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred

I also have a beautiful set of knobs in alsamixer:

![alsa](https://user-images.githubusercontent.com/12935595/80080122-6e718500-8551-11ea-9bec-55ce1d82f7e3.png)

Speakers work, and so does the headset. Or actually, they produce sound at the same time. That is not how it is supposed to be. Unplugging the headset will cause something to fail, after which there is no more sound. Rebooting will fix this, but again, only for a while. And I have not yet managed to test the microphones.

**Comment by kv2019i** [comment]
@dingesista It starts to seem the basics are working. The speaker+headset concurrent playback sounds like a codec driver and/or Pulseaudio config issue. There have been multiple smaller codec driver fixes that affect X1 posted to ALSA.

To double-check you hardware doesn't have any yet-not-seen new variation, I'd suggest to try a live-image of Ubuntu 20.04 or latest Fedora Rawhide. Both should work well out-of-the-box on your laptop.

If those are ok, then you probably need to forklift some changes from Ubuntu to your Debian machine (should be limited to kernel, pulseaudio and alsa-ucm package).

**Comment by HilleniusGijs** [comment]
thanks @kv2019i 

I just tried Ubuntu Focal Fossa, and the log looks pretty much identical: except that indeed, now it all works. FYI: here is the dmesg | grep sof-audio from Ubuntu. I'll take a close look at the 
pulsaudio and alsa-ucm packages: first glance seems to indicate Debian (sid) is ahead.

sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
sof-audio-pci 0000:00:1f.3: warning: No matching ASoC machine driver found
sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
sof-audio-pci 0000:00:1f.3: use msi interrupt mode
sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
sof-audio-pci 0000:00:1f.3: Firmware info: version 1:4:2-66a5a
sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:11:0 Kernel ABI 3:10:0
sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
sof-audio-pci 0000:00:1f.3: firmware boot complete
sof-audio-pci 0000:00:1f.3: Topology: ABI 3:11:0 Kernel ABI 3:10:0
sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel
sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp3 Tx not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec0_in not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp2 Tx not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec1_in not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 7 name iDisp1 Tx not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec0_out not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Analog CPU Playback not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec1_out not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Digital CPU Playback not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec2_in not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 7 name Alt Analog CPU Playback not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 1 name codec2_out not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Analog CPU Capture not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp1_out not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Digital CPU Capture not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp2_out not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 0 name Alt Analog CPU Capture not handled
sof-audio-pci 0000:00:1f.3: warning: widget type 1 name iDisp3_out not handled
sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
sof-audio-pci 0000:00:1f.3: firmware boot complete
sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
sof-audio-pci 0000:00:1f.3: firmware boot complete
sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
sof-audio-pci 0000:00:1f.3: firmware boot complete
sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
sof-audio-pci 0000:00:1f.3: firmware boot complete
sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
sof-audio-pci 0000:00:1f.3: firmware boot complete

**Comment by HilleniusGijs** [comment]
for others out there that find this page. See here

https://wiki.debian.org/InstallingDebianOn/Thinkpad/X1%20Carbon%207th%20Gen
