### ISSUE TITLE
sof-audio-pci doesn't work under discrete-only mode

### ISSUE THREAD

**Issue by khfeng** [thesofproject/linux#2032]
**Describe the bug**
After disable Intel GFX in the BIOS, sof-audio-pci doesn't work anymore under discrete-only mode.

**To Reproduce**
1.Disable Intel GFX, system is in Nvidia only mode.
2.Lose both audio input/output.

**Reproduce rate**
100%

**Expected result**
Audio keeps working under discrete-only mode.

**Actual result**
For both linux-next and sof-dev:
[   14.025657] sof-audio-pci 0000:00:1f.3: ASoC: can't set iDisp3 Pin hw params: -22
[   14.026189] sof-audio-pci 0000:00:1f.3: ASoC: DAI prepare error: -22
[   14.026192]  iDisp3: ASoC: backend prepare failed -22

There's a NULL kernel dereference in sof-dev nonetheless.
**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit: 7136b5a8267fba0390a044294665792ac06d15e8
FW: SoF 1.4.2
Tplg: From SoF 1.4.2
Platform:CML-H Laptop with ALC285

[dmesg-sof-dev.txt](https://github.com/thesofproject/linux/files/4510290/dmesg-sof-dev.txt)
[dmesg-next.txt](https://github.com/thesofproject/linux/files/4510293/dmesg-next.txt)

**Comment by plbossart** [comment]
@kv2019i can you look at the kernel ooops? even if this looks like a missing Kconfig option I don't recall seeing an oops before.

@khfeng we are aware of a problem leading to a system hang, firmware 1.4.2 is missing an important fix unfortunately see https://github.com/thesofproject/sof/issues/2806

**Comment by khfeng** [comment]
The system doesn't hang.

Is it possible to release signed 1.5-rc* firmware so I can test it?

**Comment by plbossart** [comment]
@lgirdwood what's the ETA for 1.5? we are at -rc3, so should be coming right up, yes?

**Comment by kv2019i** [comment]
@khfeng Can you post alsa-info.sh output from this system? 

You may also need to update alsa-ucm package. Only git master currently has fixes needed for these laptops where HDMI/DP of the integrated graphics is disabled. See my comment at https://github.com/thesofproject/linux/issues/1985#issuecomment-615226041

This doesn't help with the oops, but will be needed in the end as well.

**Comment by khfeng** [comment]
Yes the latest UCM files help. Let's close this issue.
The oops is a different issue though.
