### ISSUE TITLE
Mic Mute LED doesn't work on CML-H + ALC285

### ISSUE THREAD

**Issue by khfeng** [thesofproject/linux#2035]
**Describe the bug**
Mic Mute LED doesn't work on CML-H + ALC285

**To Reproduce**
1.Press mic mute hotkey.
2.Make sure it's muted
3.Mic mute LED isn't on.

**Reproduce rate**
100%

**Expected result**
Mic mute LED turns on.

**Actual result**
Mic mute LED doesn't light up.

**Test recipe***

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:8dc1789eda0cf4f91d015f01f4b00856e7b516e6
FW: SoF 1.4.2
Tplg: Same with FW branch
Platform:CML-H Laptop with codec ALC285

[dmesg.txt](https://github.com/thesofproject/linux/files/4514718/dmesg.txt)
[alsa-info.txt](https://github.com/thesofproject/linux/files/4514721/alsa-info.txt)

**Comment by kv2019i** [comment]
@juimonen Can you take a look? This is a HP Omen system with discrete GPU, but otherwise nothing unusual so the topology-driven mic-led control should work.

**Comment by juimonen** [comment]
@kv2019i ack. 

@khfeng there are couple of variations why this would not work: 
- mute led support not turned on in kernel
- topology doesn't have mute switch defined
- mute switch definition not found by pulseaudio

it seems from your alsa info that dmic0 mute switch is there, so should not be topology. Can you check that mute leds are on in kernel config and that pulseaudio can find the dmic capture switch?

**Comment by khfeng** [comment]
The issue is fixed by commit 87dc36482cab3a4ea34f203fc3f4da35712eb783 ("ALSA: hda/realtek - Add LED class support for micmute LED").

Thanks!
