### ISSUE TITLE
TGL: max98373-sdw codec observes SDW_DP0_INTMASK read failed:-61

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#2039]
While trying to integrate max98373-sdw on chrome-environment(coreboot) observe the following error, tried configuring this sub-property as NULL in coreboot but still observe the same issue.
Log: 
[dmesg_DP0_ww18.log](https://github.com/thesofproject/linux/files/4519402/dmesg_DP0_ww18.log)

```
[    5.591825] intel-master sdw-master-1: SDW_DP0_INTMASK read failed:-61
[    5.591828] intel-master sdw-master-1: Slave 1 initialization failed: -61

```
Further to the Query to Maxim-Team about max98373 codec supports SDW_DP0_INT_PORT_READY and SDW_DP0_INT_BRA_FAILURE cmd or not. And also check imp_def_interrupts which is retrieved from “mipi-sdw-imp-def-dp0-interrupts-supported” in ACPI table.
**Codec vendor assured that DP0 isn't supported in max98373-sdw.**
 ![dp0](https://user-images.githubusercontent.com/33264352/80042533-ea050f00-851c-11ea-98ae-e87a6785fa3a.png)

Recipe:
Kernel & DSP FW are based on TGL_v0.4 sof-dev-rebase - https://github.com/naveen-manohar/linux/commits/chrome_max98373-rebased_ww18

**Comment by plbossart** [comment]
@naveen-manohar you probably have a bad table in Coreboot. I checked the code and I see no case where we read DP0 interrupt registers if slave->dp0_prop is NULL.

BTW no one currently reads those properties from ACPI tables, see the realtek codecs they implement their own _read_prop callback and hard-code the values directly in the codec driver.

**Comment by plbossart** [comment]
@naveen-manohar also enable dynamic debug for the SoundWire core please. I do this by copying this file to /etc/modprobe.d/sof-debug.conf : 
[ddebug.txt](https://github.com/thesofproject/linux/files/4526450/ddebug.txt)

**Comment by naveen-manohar** [comment]
Thanks for the quick turn-around @plbossart , Guess you are right.
I rebased the codec driver to latest version and now i'm not observing the 'SDW_DP0_INTMASK read failed' issue. even after removing the hacks - [link](https://github.com/naveen-manohar/linux/commits/chrome_max98373-rebased_ww18-DEBUG)

Log(with Debug enabled): 
[dmesg_debug-hack-removed.log](https://github.com/thesofproject/linux/files/4528736/dmesg_debug-hack-removed.log)

Shall do few more experiments and later close this bug.

**Comment by plbossart** [comment]
@naveen-manohar do you mind submitting the codec driver as an RFC PR against topic/sof-dev? This would help the rest of us provide feedback. It doesn't need to be perfect, but you have a set of people willing to help so don't keep this to yourself :-)

**Comment by naveen-manohar** [comment]
Sure @plbossart Thanks for the support.
Working with codec-author(Ryan), shall post it start-of-week.

**Comment by naveen-manohar** [comment]
Submitted https://github.com/thesofproject/linux/pull/2062, please help review

**Comment by naveen-manohar** [comment]
Thnaks to @plbossart, @RanderWang, @bardliao for supporting during this debug and helping with PR#2062
