### ISSUE TITLE
[BUG][SDW]"rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61" occurred when do long time suspend/resume with audio stress test.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2040]
**Describe the bug**
"rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61" occurred when do long time suspend/resume with audio stress test.  

**To Reproduce**
1.System boot up.
2. cd sof-test then run "export TPLG=/lib/firmware/intel/sof-tplg/sof-cml-rt711-rt1308-mono-rt715.tplg"
3. cd test-case then run "./check-suspend-resume-with-audio.sh -l 2000 -m capture"

**Reproduction Rate**
In one round sof-test(base+stress), there are 10% chance to reproduce the issue on suspend/resume with audio test case.
Then I tried to run the suspend/resume with audio stress test all night, issue can be reproduced.

**Expected behavior**
There is no error or failed info in dmesg

**Actual result**
"rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61" occurred when do long time suspend/resume with audio stress test.  Then aplay with speaker(0,2) cannot work, and only reboot can recover the issue.

**dmesg**
```
kernel: [11003.749869] PM: suspend exit
kernel: [11004.170387] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [11004.170427] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [11004.670405] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [11004.670447] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [11005.170397] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [11005.170439] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [11005.670396] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [11005.670439] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [11006.170371] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [11006.170413] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [11006.670327] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [11006.670368] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [11006.835722] cdns_fill_msg_resp: 9 callbacks suppressed
kernel: [11006.835730] intel-master sdw-master-2: Msg Ack not received
kernel: [11006.835735] intel-master sdw-master-2: Msg ignored for Slave 15
kernel: [11006.835739] intel-master sdw-master-2: ClockStopNow Broadcast msg ignored -61
kernel: [11006.836285] intel-master sdw-master-1: Msg Ack not received
kernel: [11006.836289] intel-master sdw-master-1: Msg ignored for Slave 1
kernel: [11006.836296] rt1308 sdw:1:25d:1308:0: Clock Stop prepare failed for slave: -61
kernel: [11006.836303] rt1308 sdw:1:25d:1308:0: pre-prepare failed:-61
kernel: [11006.836308] intel-master sdw-master-1: prepare clock stop failed -61
kernel: [11006.836312] intel-master sdw-master-1: cannot enable clock stop on suspend
kernel: [11008.822253] PM: suspend entry (s2idle)
kernel: [11008.823243] Filesystems sync: 0.000 seconds
kernel: [11008.823477] Freezing user space processes ... (elapsed 0.001 seconds) done.
kernel: [11008.825112] OOM killer disabled.
kernel: [11008.825112] Freezing remaining freezable tasks ... (elapsed 0.000 seconds) done.
kernel: [11008.826090] printk: Suspending console(s) (use no_console_suspend to debug)
kernel: [11008.826473] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 1 dir 1 cmd 5
kernel: [11008.826477] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
kernel: [11008.826594] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
kernel: [11008.827048] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x240000 successful
kernel: [11008.827052] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
kernel: [11008.827171] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
kernel: [11008.828455] intel-master sdw-master-3: intel_suspend: pm_runtime status: suspended
```

***Environment***
Platform: CML-U in ALC711 -RT1308, RT715 SDW mode
Firmware: 0befebb7 https://github.com/thesofproject/sof/commits/master
Kernel: 8dc1789e https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-cml-rt711-rt1308-mono-rt715.tplg same as firmware

[all_logs.zip](https://github.com/thesofproject/linux/files/4519986/all_logs.zip)

**Comment by bardliao** [comment]
@YvonneYang2 Could you re-test with below patch?
```patch
diff --git a/drivers/soundwire/bus.c b/drivers/soundwire/bus.c
index ad077cd5894a..0a9d0e84040c 100644
--- a/drivers/soundwire/bus.c
+++ b/drivers/soundwire/bus.c
@@ -161,7 +161,7 @@ static inline int find_response_code(enum sdw_command_response resp)
                return 0;
 
        case SDW_CMD_IGNORED:
-               return -ENODATA;
+               return 0;
 
        case SDW_CMD_TIMEOUT:
                return -ETIMEDOUT;

```

**Comment by plbossart** [comment]
@bardliao we can't do that. There are multiple checks for -ENODATA in the rest of the code, this is really needed.

CMD_IGNORED can be a bug or a feature. It is a a bug if you receive this during 'normal' transactions, it means that either the software attempted to reach an non-implemented registers, or that the Slave did not receive the command for some reason (including when it's not attached).

But it's a feature when we do the enumeration, CMD_IGNORED means all Slaves have been enumerated and there are no Device0 Slaves any longer.

So so we can't change that part....

**Comment by sinahuang** [comment]
Verified this issue with Bard's patch, test for 1000 times, error not seen.

**Comment by bardliao** [comment]
@sinahuang @YvonneYang2 Could you test below patch? Thanks.
```patch
diff --git a/drivers/soundwire/bus.c b/drivers/soundwire/bus.c
index ad077cd5894a..d05ec2fdc497 100644
--- a/drivers/soundwire/bus.c
+++ b/drivers/soundwire/bus.c
@@ -921,12 +921,14 @@ int sdw_bus_clk_stop(struct sdw_bus *bus)
        ret = sdw_bwrite_no_pm(bus, SDW_BROADCAST_DEV_NUM,
                               SDW_SCP_CTRL, SDW_SCP_CTRL_CLK_STP_NOW);
        if (ret < 0) {
-               if (ret == -ENODATA)
+               if (ret == -ENODATA) {
                        dev_dbg(bus->dev,
                                "ClockStopNow Broadcast msg ignored %d", ret);
-               else
+                       ret = 0;
+               } else {
                        dev_err(bus->dev,
                                "ClockStopNow Broadcast msg failed %d", ret);
+               }
                return ret;
        }
```

**Comment by bardliao** [comment]
> @bardliao we can't do that. There are multiple checks for -ENODATA in the rest of the code, this is really needed.
> 
> CMD_IGNORED can be a bug or a feature. It is a a bug if you receive this during 'normal' transactions, it means that either the software attempted to reach an non-implemented registers, or that the Slave did not receive the command for some reason (including when it's not attached).
> 
> But it's a feature when we do the enumeration, CMD_IGNORED means all Slaves have been enumerated and there are no Device0 Slaves any longer.
> 
> So so we can't change that part....

@plbossart Yes, I get your point. The purpose of the testing patch is to know if all the IGNORE are harmless and is there other issue except IGNORE.

**Comment by plbossart** [comment]
@bardliao I am wondering if this comes from a race condition in sdw_cdns_clock_stop()

a) we disable the Slave interrupts, so I guess we will not be notified if a Slave becomes unattached
b) we force the command to be be treated as error if there is no Slave present
c) we get an -ENODATA on a prep_clk_stop
d) we don't do the actual clock stop so the pm_runtime status does not become suspended
this shows in the log with 
````
kernel: [11008.828455] intel-master sdw-master-3: intel_suspend: pm_runtime status: suspended
kernel: [11008.828460] intel-master sdw-master-2: intel_suspend: pm_runtime status: suspended
````
we are missing sdw-master-1 as suspended here.

e) not clear what happens on system resume then

But the main question is why the Slave becomes UNATTACHED?

**Comment by plbossart** [comment]
I am not able to reproduce this, no 'prepare clock error' in dmesg.txt after overnight test, but I see this:

````
2020-04-28 01:00:05 UTC [ERROR] Caught dmesg error
===========================>>
[28398.793959] FS:  0000000000000000(0000) GS:ffff946d1c480000(0000) knlGS:0000000000000000
[28398.793960] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[28398.793960] CR2: 00007fb664ca4680 CR3: 000000012ec0a004 CR4: 00000000003606e0
[28398.793961] Call Trace:
[28398.793967]  iwl_mvm_wait_sta_queues_empty+0x58/0xb0 [iwlmvm]
[28398.793970]  iwl_mvm_mac_flush+0xd0/0x280 [iwlmvm]
[28398.793972]  __ieee80211_flush_queues+0xdb/0x1d0
[28398.793975]  ieee80211_set_disassoc+0x3fa/0x5a0
[28398.793977]  ieee80211_mgd_deauth.cold+0x4a/0x1c2
<<===========================
2020-04-28 01:00:05 UTC Sub-Test: [ERROR] Catch error in dmesg
2020-04-28 01:00:05 UTC Sub-Test: [INFO] Test Result: FAIL!
2020-04-28 01:00:05 UTC [ERROR] suspend resume failed
2020-04-28 01:00:07 UTC [WARNING] Process(es) started by ./check-suspend-resume-with-audio.sh are still active, kill these process(es):
2020-04-28 01:00:07 UTC [WARNING] Catch pid: 18006 arecord -Dhw:0,1 -r 48000 -c 2 -f S16_LE /dev/null -q
2020-04-28 01:00:07 UTC [WARNING] Kill cmd:'arecord -Dhw:0,1 -r 48000 -c 2 -f S16_LE /dev/null -q' by kill -9
2020-04-28 01:00:07 UTC [INFO] Test Result: FAIL!
````

This is clearly unrelated to SOF...

**Comment by sinahuang** [comment]
Checked this issue with sof-dev(commit:8f1c6ad) + Bard's patch, test for 2000 times, issue can't be reproduced.

**Comment by bardliao** [comment]
I am not able to reproduce this, too. I ran ./check-suspend-resume-with-audio.sh -l 1000 -m capture last night, and the test result is PASS.

**Comment by plbossart** [comment]
@YvonneYang2 does this still happen on your side? Not sure what to do here.

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced after 1000 iterations stress test with latest topic/sof-dev(commit: 0d22f66b ) and  master(commit: caae629f)
So close it for issue not reproduced now.
