### ISSUE TITLE
[DSM][TGL]: speaker L/R channel route in codec driver doesn't match with amixer kcontrol 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2045]
**Describe the bug**
The behavior of speaker L/R channel is wrong when testing DSM on TGL Chromebook.
For example:
Use amixer to set speaker L channel "Left DAI Sel Mux" as 0 and run speaker-test,  the left channel should be able to hear "Front Left", but only Front Right can be heard during speaker-test on both channels at the same time.  
looks  like the route of L/R channel is not set correctly in codec driver side. Need chrome team help to check.

**To Reproduce**
1. use amixer to set L/R channel for speaker 
amixer cset name='Left DAI Sel Mux' 0
amixer cset name='Right DAI Sel Mux' 1
2.  do speaker-test on hw:0,0 
speaker -Dhw:0,0 -t wav -c 2 

**Expected behavior**
Hear Front Left and Front right separately

**Environment**
Kernel: https://github.com/thesofproject/linux/tree/topic/smart-amp
firmware:https://github.com/thesofproject/sof/tree/tgl-005-drop-stable
tplg: sof-tgl-max98373-rt5682.tplg

**Comment by keyonjie** [comment]
I think the comments in the code below is somewhat confused:
```
struct snd_soc_dai_link_component max_98373_components[] = {
	{  /* For Left */
		.name = MAX_98373_DEV0_NAME,
		.dai_name = MAX_98373_CODEC_DAI,
	},
	{  /* For Right */
		.name = MAX_98373_DEV1_NAME,
		.dai_name = MAX_98373_CODEC_DAI,
	},
};
```

we followed Left--DEV0 and debugged for long time with:
amixer cset name='Left DAI Sel Mux' Left
amixer cset name='Right DAI Sel Mux' Right 
 
where the captured data was always incorrect.
 
So I think only correct the comment message should be good enough.

@RDharageswari FYI.

**Comment by RDharageswari** [comment]
Sure..Thanks :)

**Comment by RDharageswari** [comment]
Incorporated the fix in the following patch:
https://github.com/thesofproject/linux/pull/2123/commits/24e5b2678814dc47a771c6e658896eab57c10104

**Comment by sinahuang** [comment]
Currently  right speaker output left channel audio, left speaker output right channel audio with https://github.com/thesofproject/sof/tree/tgl-007-drop-stable on chrome book with codec 98373 in I2S mode.
[dmesg24.log](https://github.com/thesofproject/linux/files/4823708/dmesg24.log)
[amixer24.txt](https://github.com/thesofproject/linux/files/4823709/amixer24.txt)

**Comment by ClarexZhou** [comment]
only one Channle has audio output after run DSM command.  Frequency: 5/10
Steps:
1. Boot up system
2. ```speaker-test -Dhw:0,0 -t wav -c 2 ```   -> both 2 channels has audio output, but L output R, R output L.  amixer contents is here 
[amixer_default.txt](https://github.com/thesofproject/linux/files/4877128/amixer_default.txt)
3. run DSM command ```aplay -Dhw:0,0 -f s16_le -c 2 -r 48000 sine_48k_16bit_10s_stereo_l5_r2.wav -d 5 & arecord -Dhw:0,0 -f s16_le -c 4 -r 48000 record.wav -d 5```
4. wait for about 3s.
5. ```speaker-test -Dhw:0,0 -t wav -c 2 ```  only one channel is output. amixer is here 
[amixer_373change.txt](https://github.com/thesofproject/linux/files/4877140/amixer_373change.txt)
```

ubuntu@TGL-Volteer-01:~$ diff amixer_default.txt amixer_373change.txt           186c186
<   : values=0
---
>   : values=183
205c205
<   : values=0
---
>   : values=49

```
[dmesg_373amixerchange.txt](https://github.com/thesofproject/linux/files/4877153/dmesg_373amixerchange.txt)
[sof-trace_373amixerchange.txt](https://github.com/thesofproject/linux/files/4877168/sof-trace_373amixerchange.txt)

**Comment by ClarexZhou** [comment]
Error not seen , previous connected speaker issue. Close
