### ISSUE TITLE
CI: Need to trap SOF driver compilation warnings

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#205]
Our esteemed developers don't seem to look at the kernel compilation logs, as a result we have patches that are merged even when they generate warnings such as 

````text
 CC [M]  sound/soc/sof/trace.o
sound/soc/sof/trace.c: In function ‘snd_sof_init_trace_ipc’:
sound/soc/sof/trace.c:155:3: warning: ‘return’ with no value, in function returning non-void [-Wreturn-type]
   return;
   ^~~~~~
sound/soc/sof/trace.c:148:5: note: declared here
 int snd_sof_init_trace_ipc(struct snd_sof_dev *sdev)
     ^~~~~~~~~~~~~~~~~~~~~~
````
We need the CI build to trap such errors and flag them as errors.

**Comment by xiulipan** [comment]
@mengdonglin 
Who is the maintainer of  the 0-day CI?

@plbossart 
Would you like to enable a Travis CI for this kernel repo? It will involve file .travis.yml into the repo.

**Comment by cujomalainey** [comment]
@xiulipan if you use Travis there is a very good chance that we can find another yml file already configured for this

**Comment by xiulipan** [comment]
@cujomalainey 
For Linux I believe there are must a lot of yml file. 
We can modify some to meet our requirement here.

Another problem is how to get config.

**Comment by mengdonglin** [comment]
@xiulipan Fuwei has enabled trapping the compilation warnings in 0-day CI.

It will be great if Travis CI can support kernel. @plbossart would you recommend a kconfig?

**Comment by plbossart** [comment]
@mengdonglin it's fine to use the same kconfig as 0day. Alternatively we could use the fragments that are already managed at https://github.com/thesofproject/kconfig for faster compilation.

**Comment by xiulipan** [comment]
@plbossart 
Enabled with #351

**Comment by wenqingfu** [comment]
close as #351 fixed this
