### ISSUE TITLE
CI: add checkpatch.pl checks

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#206]
Our esteemed developers don't seem to run checkpatch so CI will need to run it for them.
Basic checkpatch fails is an error
checkpatch --strict may report issues but it's up to the maintainer to check if they require a change or not.

**Comment by xiulipan** [comment]
@plbossart 
For 0-day CI, the checkpatch.pl checks is already enabled.

From https://github.com/thesofproject/linux/pull/196
https://download.01.org/0day-ci/sof/kernel-checkpatch-pr-196-75cb5a.txt
> ERROR: Remove Gerrit Change-Id's before submitting upstream.
> #9: 
> Change-Id: I5f174135f500485bfba4a6515282430f43fd4f8d
> 
> total: 1 errors, 0 warnings, 0 checks, 8 lines checked
> 
> NOTE: For some of the reported defects, checkpatch may be able to
>       mechanically convert to the typical style using --fix or --fix-inplace.
> 
> ./linux-sof-driver/0001-Remove-developer-debug-code.patch has style problems, please review.
> 
> NOTE: If any of the errors are false positives, please report
>       them to the maintainer, see CHECKPATCH in MAINTAINERS.
>

**Comment by plbossart** [comment]
@xiulipan I don't believe there is any integration with github CI. I would just like parity with the firmware where the results can be seen directly.

**Comment by xiulipan** [comment]
@plbossart 
You mean some patch check tool directly show change comments in the review board?
I know that github have some extensions can do that. Let me check and make the update once I found some chould meet the requirement.

**Comment by plbossart** [comment]
@xiulipan the firmware repo shows me the results of checkpatch directly in github, the linux repo doesn't.

**Comment by xiulipan** [comment]
@plbossart 
checkpatch is a part of the CI check.
For Travis CI, I can now only enable 1 build for each PR with 2 jobs:
1 for checkpatch, 1 for build.
If you want to the same as firmware, we may enable other CI

@mengdonglin 
When will 0-day CI stop to work?

**Comment by plbossart** [comment]
it's working fine now, thaks @xiulipan
