### ISSUE TITLE
[UCM2][CML-H][BUG]Speaker0,2 can't have sound output when do paplay.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2060]
**Describe the bug**
Speaker0,2 can't have sound output when do paplay. Aplay0,2 have sound output. 

Alsamixer display as below:

![Screenshot from 2020-04-28 15-25-02](https://user-images.githubusercontent.com/56706782/80459250-ad924280-8964-11ea-83ab-3e0830e960ed.png)

**To Reproduce**
1.Boot up system
2.Open sound setting to select speaker in output source.
3.Run "paplay wav/48California_Dreaming.wav -vvv"

**Reproduce rate**
5/5

**Expected result**
Paplay0,2 shoould have sound output.

**Actual result**
Speaker0,2 can't have sound output when do paplay.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:8f1c6ad +PR https://github.com/thesofproject/linux/pull/2058
FW: https://github.com/thesofproject/sof/commits/master commit: de2dcbbc
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.
UCM2: https://github.com/thesofproject/alsa-ucm-conf +PR https://github.com/thesofproject/alsa-ucm-conf/pull/37 +PR # https://github.com/thesofproject/alsa-ucm-conf/pull/35

**Comment by sinahuang** [comment]
Change the "name='PGA3.0 3 Master Playback Volume' "  to " name='PGA3.1 3 Master Playback Volume" from RT1308-1.conf in sof-soundwire, only left speaker have sound output.

**Comment by ClarexZhou** [comment]
Error not seen with UCM2 https://github.com/libinyang/alsa-ucm-conf/tree/sdw_ucm2_singleprofile/ucm2/sof-soundwire  commit: c2c5042

**Comment by sinahuang** [comment]
Error can't be seen with UCM2 https://github.com/thesofproject/alsa-ucm-conf/commits/master commit:12743d2 , closed it
