### ISSUE TITLE
[Bug][EHL] Runtime PM keeps active and "Unable to install hw " when aplay via HDMI

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#2061]
**Describe the bug**
Runtime PM keeps active after system boot up, "Unable to install hw " when aplay via HDMI. Other pipline works ok. Also no HDMI jack detection in amixer contents.

**To Reproduce**
1. system boot up
2. cat "/sys/bus/pci/devices/0000:00:1f.3/power/runtime_status"
3. aplay -Dhw:0,3 -f dat 48K_Let_It_Go.wav -vv -i 

**Reproduction Rate**
3/3

**Expected behavior**
HDMI should work normally

**Impact**
HDMI pipline can't be used, other pipline works ok.
```
test@test-Elkhart-Lake-Embedded-Platform:~$ aplay -Dhw:0,3 -f dat 48K_Let_It_Go.wav -vv -i
Playing WAVE '48K_Let_It_Go.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
aplay: set_params:1403: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: 85000
PERIOD_SIZE: 4080
PERIOD_BYTES: 16320
PERIODS: (4 5)
BUFFER_TIME: 341000
BUFFER_SIZE: 16368
BUFFER_BYTES: 65472
TICK_TIME: 0
```

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: topic/sof-dev, commit 8f1c6ad6  and add below 2 patches for add codec acpi
[0001-ASoC-rt5660-Add-the-codec-ID-of-EHL-CRB.patch.txt](https://github.com/thesofproject/linux/files/4549476/0001-ASoC-rt5660-Add-the-codec-ID-of-EHL-CRB.patch.txt)
[0002-ehl-use-intc-codec-id.patch.txt](https://github.com/thesofproject/linux/files/4549477/0002-ehl-use-intc-codec-id.patch.txt)

    * SOF: master, commit de2dcbbc. using sof-tgl.ri rename to sof-ehl.ri
2) Name of the topology file
    * Topology: sof-ehl-rt5660.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: EHL RVP with RT5660 in I2S mode

Didn't find error message.
[sof-logger_full.txt](https://github.com/thesofproject/linux/files/4545082/sof-logger_full.txt)
[amixer.txt](https://github.com/thesofproject/linux/files/4545083/amixer.txt)
[dmesg_2.txt](https://github.com/thesofproject/linux/files/4545084/dmesg_2.txt)
[drmDmesg.txt](https://github.com/thesofproject/linux/files/4545176/drmDmesg.txt)

Can't do bi-sect, since commit seems changed. But 20200413 kernel works OK. Here is dmesg when issue not reproduced with previous kernel.
[noIssue_drmDmesg.txt](https://github.com/thesofproject/linux/files/4545179/noIssue_drmDmesg.txt)

**Comment by libinyang** [comment]
EHL graphics device is not properly supported by i915 kernel module. It will skip the probing and setting the hdmi audio. Add i915.force_probe=4571 can bypass this issue.

**Comment by sinahuang** [comment]
After adding i915.force_probe=4571 to "/boot/grub/grub.cfg" files, issue can't be seen. So track this i915 issue in https://gitlab.freedesktop.org/drm/intel/-/issues/1843, closed it.
