### ISSUE TITLE
[BUG] kernel 5.7 failed to boot on TGL chrome device 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2063]
**Describe the bug**
We tried linux kernel v5.7 on TGL chromebook, but failed to boot up. screen goes black after passing the grub page, so there're no logs available.
This issue cannot be reproduced with 5.6-rc7 kernel + latest sof/tplg of master,  so looks like this is a kernel regression after 5.7 kernel rebase from upstream.

**Environment**
1) kernel: sof-dev/8f1c6ad6
2) firmware: master/af38b20b
3) tplg: sof-tgl-max98373-rt5682.tplg
4) HW: TGL Chromebook prototype device

**Comment by plbossart** [comment]
@keqiaozhang no one else that you has access to this platform so you will have to bisect. It's horrible I know but that's what we've done on other platforms as well.

**Comment by keqiaozhang** [comment]
@plbossart, 
Bi-sect result points to:
```
6a7c533d4a1854f54901a065d8c672e890400d8a is the first bad commit
commit 6a7c533d4a1854f54901a065d8c672e890400d8a
Author: Mika Westerberg <mika.westerberg@linux.intel.com>
Date:   Thu Mar 12 16:45:17 2020 +0200

    xhci-pci: Allow host runtime PM as default for Intel Tiger Lake xHCI

    In the same way as Intel Ice Lake TCSS (Type-C Subsystem) the Tiger Lake
    TCSS xHCI needs to be runtime suspended whenever possible to allow the
    TCSS hardware block to enter D3cold and thus save energy.

    Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>
    Signed-off-by: Mathias Nyman <mathias.nyman@linux.intel.com>
    Link: https://lore.kernel.org/r/20200312144517.1593-10-mathias.nyman@linux.intel.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
```
I also verified that latest sof-dev can boot on TGL chrome device after reverting this commit.

**Comment by plbossart** [comment]
@keqiaozhang I think this is root-caused, can we close this?

**Comment by mengdonglin** [comment]
@plbossart, we still haven't got a coreboot fix now.  Close it as won't fix?

**Comment by ClarexZhou** [comment]
Error not seen after coreboot updated. Close
