### ISSUE TITLE
[FEATURE] UCM: support for multiple conflicting PCM streams (multi/single-profile problem)

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#2068]
Current user-space infrastructure provided by UCM and how it is used by system servers such as Pulseaudio, has a gap in terms of how systems such as SoundWire PCMs are described in UCMs such that Pulseaudio can correctly switch routing between the PCMs.

Details and latest discussion in Pulseaudio bug:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/854

@libinyang @juimonen

**Comment by kv2019i** [comment]
@libinyang Can you confirm I got this right and that this change:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295
... will allow to solve the conflicting stream issue without 
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 
?

Based on latest results for #2110 , this seems to to be the case.

**Comment by libinyang** [comment]
@kv2019i Currently https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 is abandoned.
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 is enough for us to support single profile.
And we also need the patch: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/302 to fix the bug https://github.com/thesofproject/linux/issues/2148

**Comment by kv2019i** [comment]
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 and https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/322 are now merged and this feature is now fully implemented. Thanks @libinyang  !
