### ISSUE TITLE
[BUG][TGL HDA] Runtime PM status will always keeps active after boot up system with AC power

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#2073]
**Describe the bug**
Runtime PM status will always keeps active if boot up system with HDMI/DP connected.

**Steps**
1. "sudo reboot" to reboot system

Reproduce Rate:
6/10

**Actual result:**
Runtime PM will always keeps active, even after disconnect HDMI/DP

**Expect result:**
Runtime PM should be suspended

Platform: Dell TGL laptop with onboard codec ALC3204 in HDA mode
Firmware: [7e6cd4b][https://github.com/thesofproject/sof/commits/v1.5]
Kernel:  default 5.6.0 kernel in OS http://162.213.32.53/O85vvT7641N5Ei5KLrC8RwAN/fossa-bulbasaur/X20/dell-bto-focal-fossa-bulbasaur-X20-20200428-40.iso
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2: 907c8309 https://github.com/alsa-project/alsa-ucm-conf 
+  alsa-project/alsa-ucm-conf#21

Error not seen dmesg:
[dmesg_runtimePMworksOK.txt](https://github.com/thesofproject/linux/files/4557794/dmesg_runtimePMworksOK.txt)
Error seen dmesg:
[dmesg_runtimPM_noHDMI_fail.txt](https://github.com/thesofproject/linux/files/4557869/dmesg_runtimPM_noHDMI_fail.txt)
[dmesg_runtimePM_DP.txt](https://github.com/thesofproject/linux/files/4557795/dmesg_runtimePM_DP.txt)
[dmesg_runtimePM.txt](https://github.com/thesofproject/linux/files/4557793/dmesg_runtimePM.txt)

**Comment by ClarexZhou** [comment]
Error also seen on latest sof-dev: commit c05a3f86. Error seems always can be reproduced now.

**Comment by ClarexZhou** [comment]
Change back to random, still not find stable method to reproduce this issue. But seems error always can be reproduce once occurred.

**Comment by xiulipan** [comment]
@ClarexZhou Checked on the device,  when error happened we can see:
```
$ cat /sys/bus/pci/devices/0000:00:1f.3/power/control
on
```
After reset the control to auto the PM is back to normal. Please help to confirm above findings.

@ranj063 @keyonjie Any idea here? I think either we forget to enable the runtime PM or the runtime PM is disabled by something?

**Comment by keyonjie** [comment]
@xiulipan good catch. Can you check if PM_RUNTIME is disabled via module params sof_pci_debug on the platform?

```
tatic void sof_pci_probe_complete(struct device *dev)
{
        dev_dbg(dev, "Completing SOF PCI probe");

        if (sof_pci_debug & SOF_PCI_DISABLE_PM_RUNTIME)
                return;
...
}
```

**Comment by ClarexZhou** [comment]
Verified, cat /sys/bus/pci/devices/0000:00:1f.3/power/control is on once error occurred. And Runtime PM status can be suspended sucessfully once echo auto.

**Comment by xiulipan** [comment]
@keyonjie I tried to check what cause the issue.
It seems not caused by sof_pci_debug.
Try to add some debug logs into kernel to check what goes on.
@ClarexZhou do we see issue with other kernels?

**Comment by ClarexZhou** [comment]
@xiulipan  Error occurred on default dell ubuntu 20.02 kernel, sof dev and stable linux 5.6.3.

**Comment by xiulipan** [comment]
@ClarexZhou I will use sof-dev to debug for this issue.

**Comment by xiulipan** [comment]
@keyonjie @ranj063 @ClarexZhou After add some debug code below, it appears that something must set pm control to `on` somewhere. But I could not know where or who did that. 

@plbossart @kv2019i @lyakh Any idea about this? 

```
diff --git a/drivers/base/power/sysfs.c b/drivers/base/power/sysfs.c
index 2b99fe1eb207..797895827d9f 100644
--- a/drivers/base/power/sysfs.c
+++ b/drivers/base/power/sysfs.c
@@ -107,6 +107,7 @@ static ssize_t control_show(struct device *dev, struct device_attribute *attr,
 static ssize_t control_store(struct device * dev, struct device_attribute *attr,
                             const char * buf, size_t n)
 {
+       dev_err(dev, "PXL: pm_runtime control_store %s", buf);
        device_lock(dev);
        if (sysfs_streq(buf, ctrl_auto))
                pm_runtime_allow(dev);
```

```
[   23.121118] pci 0000:00:00.0: PXL: pm_runtime control_store on
[   23.123498] i915 0000:00:02.0: PXL: pm_runtime control_store on
[   23.125402] proc_thermal 0000:00:04.0: PXL: pm_runtime control_store on
[   23.129087] pci 0000:00:0a.0: PXL: pm_runtime control_store on
[   23.131067] xhci_hcd 0000:00:0d.0: PXL: pm_runtime control_store on
[   23.146720] pci 0000:00:0d.2: PXL: pm_runtime control_store on
[   23.149932] pci 0000:00:12.0: PXL: pm_runtime control_store on
[   23.152728] xhci_hcd 0000:00:14.0: PXL: pm_runtime control_store on
[   23.155077] pci 0000:00:14.2: PXL: pm_runtime control_store on
[   23.157735] iwlwifi 0000:00:14.3: PXL: pm_runtime control_store on
[   23.159780] intel-lpss 0000:00:15.0: PXL: pm_runtime control_store on
[   23.175003] intel-lpss 0000:00:15.1: PXL: pm_runtime control_store on
[   23.192674] pci 0000:00:1f.0: PXL: pm_runtime control_store on
[   23.195721] sof-audio-pci 0000:00:1f.3: PXL: pm_runtime control_store on
[   23.207961] sof-audio-pci 0000:00:1f.3: Turning i915 HDAC power 1
```

Some guess about 
```
$ systemctl status upower.service
● upower.service - Daemon for power management
     Loaded: loaded (/lib/systemd/system/upower.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2020-05-09 01:16:30 EDT; 6min ago
       Docs: man:upowerd(8)
   Main PID: 1839 (code=exited, status=217/USER)

May 09 01:16:30 ubuntu-Inspiron-5301 systemd[1]: upower.service: Scheduled restart job, restart counter is at 5.
May 09 01:16:30 ubuntu-Inspiron-5301 systemd[1]: Stopped Daemon for power management.
May 09 01:16:30 ubuntu-Inspiron-5301 systemd[1]: upower.service: Start request repeated too quickly.
May 09 01:16:30 ubuntu-Inspiron-5301 systemd[1]: upower.service: Failed with result 'exit-code'.
May 09 01:16:30 ubuntu-Inspiron-5301 systemd[1]: Failed to start Daemon for power management.
```
Any similar issues found with Ubuntu 20.04?

**Comment by keyonjie** [comment]
@xiulipan, can you dump the callstack, my rough guess is that it came from the pm_runtime_forbid call if the PM runtime is not disabled via sof_pci_debug:

$ grep "pm_runtime_forbid" sound/* -rn
sound/pci/hda/hda_codec.c:3395:		pm_runtime_forbid(dev);
sound/pci/hda/hda_tegra.c:450:		pm_runtime_forbid(hda->dev);

**Comment by xiulipan** [comment]
@keyonjie The `pm_runtime_forbid` is called by `control_store`
```
static ssize_t control_store(struct device * dev, struct device_attribute *attr,
			     const char * buf, size_t n)
{
	dev_err(dev, "PXL: pm_runtime control_store %s", buf);
	device_lock(dev);
	if (sysfs_streq(buf, ctrl_auto))
		pm_runtime_allow(dev);
	else if (sysfs_streq(buf, ctrl_on))
		pm_runtime_forbid(dev);
	else
		n = -EINVAL;
	device_unlock(dev);
	return n;
}
```
which means something in the user space write the debugfs to disable the runtime pm for  `0000:00:1f.3`
`[   23.195721] sof-audio-pci 0000:00:1f.3: PXL: pm_runtime control_store on`

**Comment by kv2019i** [comment]
I can reproduce the problem now. It seems there is some new logic to white/black list devices capable of runtime-PM in Ubuntu -- see /lib/udev/rules/6*suspend.rules. I've yet to figure out how the control gets set, but it's definitely coming from user-space.

The autosuspend rules are geneted by following script of systemd:
https://github.com/systemd/systemd/blob/master/tools/chromiumos/gen_autosuspend_rules.py

By writing a separate udev rule that adds the SOF PCI dev to autosuspend list seems to solve the issue. but need to do a bit more work to confirm this is really the cause.

**Comment by kv2019i** [comment]
@ClarexZhou Ok, rootcause seems to be default configuration of "tlp" package. It has:

SOUND_POWER_SAVE_ON_AC="0"

... as the default. So whenever you have AC power plugged, it will write "on" to SOF PCI device's runtime-pm control and disable runtime-pm. When you unplug, it goes back to "auto". There can be a slight delay in boot before "tlp" gets to run where the state is briefly "auto" even though AC is connected. You can see current status with "tlp-stat -e".

**Comment by xiulipan** [comment]
@kv2019i Nice catch! I think we should have some sharing about this kind of user-space PM configuration
@ClarexZhou I believe we can close this issue as this is user-space configure. Could you manually test without AC plug in to confirm the findings from Kai

**Comment by ClarexZhou** [comment]
Verified runtime PM status can be suspended if without AC plug. This issue only occurred with OEM ubuntu for Shuri, and error not seen on public ubuntu 20.04. Close.
