### ISSUE TITLE
[BUG][UCM2]All sources don't have sound output after switching source in sound setting.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2100]
**Describe the bug**
Sound only output from first auto selected source after reboot, then switch to any source, there is no sound output. But check the alsamixer the source is unmuted.

Precondition:
1.Install ubuntu 20.04
2.Upgrade pulseaudio (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f)+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290)
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/40

**To Reproduce**
1.Boot up system.
2.Run "paplay wav/48California_Dreaming.wav -vvv" and check the sound output 
3.Open sound setting and switch source and check the sound output. (https://github.com/thesofproject/sof-test/blob/master/test-case/manual/check-pulseaudio.md)

**Reproduce rate**
5/5

**Expected result**
Sound should output from any source after switching source.

**Actual result**
Sound only output from first auto selected source after reboot.

![Screenshot from 2020-05-13 12-54-58](https://user-images.githubusercontent.com/56706782/81773828-d0535800-951b-11ea-8b82-3105a88f4c28.png)

![Screenshot from 2020-05-13 12-54-54](https://user-images.githubusercontent.com/56706782/81773903-f5e06180-951b-11ea-9ac9-cd5cd927111f.png)

[amixer contents.txt](https://github.com/thesofproject/linux/files/4619955/amixer.contents.txt)

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0773fe
FW: https://github.com/thesofproject/sof/commits/master commit: 782066
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
This UCM+ PulseAudio test combination is deprecated now.
Because @plbossart @perexg NAKed defining Conflicting Device in UCM if these PCM devices are not conflicting in hardware. So we can no longer define such fake Conflicting Device in single-profile UCM, and depend on PulseAudio to automatically create profiles per conflicting device group for
for the exclusive device usage: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290

Please find more info in thesofproject/alsa-ucm-conf#40 (comment)

**Comment by ClarexZhou** [comment]
Close first since pulseaudio create profiles PR https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 might not be used.
