### ISSUE TITLE
[BUG][UCM2][CML]Mute LED auto light off after reboot

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2103]
**Describe the bug**
Mute input device then reboot, input device will auto change to be unmuted status. Mute LED also light off after boot up.     

Note: delete the MIC switch in RT715.conf and RT711.conf and retest it , mute LED only light up when mute both headset and DMIC at the same time before reboot. If just only mute one input source, after reboot, the input source volume is muted in sound setting but mute led keeps light off.

Precondition:
1.Install ubuntu 20.04
2.Upgrade pulseaudio (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f)+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290)
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/40

**To Reproduce**
1.Press mute led and make it light up 
2. Reboot
3.Open sound setting then check the input device volume status.

**Reproduce rate**
5/5

**Expected result**
Mute led still light up after reboot and input device keeps muted in sound setting.

**Actual result**
Mute led light off after reboot and input device is auto unmuted in sound setting.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0773fe
FW: https://github.com/thesofproject/sof/commits/master commit: 782066
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
This UCM+ PulseAudio test combination is deprecated now.
Because @plbossart @perexg NAKed defining Conflicting Device in UCM if these PCM devices are not conflicting in hardware. So we can no longer define such fake Conflicting Device in single-profile UCM, and depend on PulseAudio to automatically create profiles per conflicting device group for
for the exclusive device usage: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290

Please find more info in thesofproject/alsa-ucm-conf#40 (comment)

**Comment by YvonneYang2** [comment]
Issue can still be reproduced with multi-profile UCM+ PulseAudio test combination as below.
multi profile ucm2 (https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR thesofproject/alsa-ucm-conf#41)+ default pulseaudio(version:13.99.1)

**Comment by YvonneYang2** [comment]
Issue can still be reproduced with single UCM+ PulseAudio test combination as below.

1.Pulseaudio version: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f) + https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295
2.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR thesofproject/alsa-ucm-conf#35 + #PR thesofproject/alsa-ucm-conf#39

**Comment by mengdonglin** [comment]
Wait for fix by future global mute solution

**Comment by plbossart** [comment]
@mengdonglin @libinyang what's the plan here? No information for 3+ months.

**Comment by libinyang** [comment]
@plbossart The plan is we will wait for the global mute solution. Ubuntu will has raised a proposal for the global mute solution. It seems they are busy on other projects currently. On our platforms, Mute LED works well currently except some corner low priority issue, such as this issue.

**Comment by plbossart** [comment]
@libinyang can we close this issue? It's been 6+ months without an update.

**Comment by plbossart** [comment]
@libinyang @mengdonglin @keyonjie in the absence of any update since May 2020, I will close this issue.
