### ISSUE TITLE
[Bug][TGL] TGL laptop with HDA AL3204 codec can't enter s0ix

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#2109]
**Describe the bug**
Current Dell TGL HDA laptop with AL3204 codec can't enter s0ix, silicon is below B0.
s0ix depends on silicon. Keep this issue open to monitor.

**Steps**
1. 'sudo su', then 'cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec'
2. "sudo rtcwake -m mem -s 10' to enter s2idle and wake up
3.  'cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec' again

Reproduce Rate:
3/3

**Actual result:**
slp_s0_residency_usec is always 0, can't enter s0ix.

**Expect result:**
slp_s0_residency_usec count should be increased for entering s0ix

Platform: Dell TGL laptop with onboard codec ALC3204 in HDA mode
Firmware: [7e6cd4b][https://github.com/thesofproject/sof/commits/v1.5]
Kernel:  default 5.6.0 kernel in OS http://162.213.32.53/O85vvT7641N5Ei5KLrC8RwAN/fossa-bulbasaur/X20/dell-bto-focal-fossa-bulbasaur-X20-20200428-40.iso
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2: 907c8309 https://github.com/alsa-project/alsa-ucm-conf

**Comment by mengdonglin** [comment]
To fix issue depends on 3 items:
1. Need B-stepping silicon
2. thunderbolt/xhci blocking runtime PC10. Kernel team is debugging this. 
3. S0i3 is blocked by AUDIO PLL being ON https://github.com/thesofproject/sof/issues/2936

**Comment by ClarexZhou** [comment]
Verifed s0i3 on B0 silicon, audio is not a blocker. Close
