### ISSUE TITLE
[BUG][CML][UCM2]Audio output can't be auto switched to HDMI in some scenarios

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2110]
***Describe the bug***
Audio output can't be auto switched to HDMI in some scenarios

***To Reproduce***
Scenario 1
1.sudo reboot’ to reboot system without HDMI connetion
2.plug HDMI 

Scenario 2
1.sudo reboot’ to reboot system without HDMI connetion
2.plug HDMI
3.open soundsetting to set output Device as "HDMI1/DP1 Output-sof-hda-dsp“
4.keep sound setting open
5.paplay -vv wav/48California_Dreaming.wav
6.unplug HDMI then plug again 
7.Check output Device in sound settings

***Reproduction Rate***
5/5

***Expected behavior***
Output Device can be changed to HDMI auto when plug HDMI again

***Actual result***
Scenario 1 &Scenario 2  : Output Device can not be changed to  HDMI auto  when plug HDMI again

More info:
 in scenario 1:if select HDMI as output one time, then unplug and plug again,error not seen 
 in scenario2:error not seen if closed sound setting in step4 or without step5
 

Platform: Dell CML laptop with onboard codec ALC3204 in HDA mode
Firmware: 83cecc95 https://github.com/thesofproject/sof/commits/master
Kernel: a43e72a3 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2: https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/(12743d2) or
https://github.com/alsa-project/alsa-ucm-conf/UCM2 + alsa-project/alsa-ucm-conf#21 can reproduce this issue

[amixercontents_failed.txt](https://github.com/thesofproject/linux/files/4626152/amixercontents_failed.txt)
[amixercontents_pass.txt](https://github.com/thesofproject/linux/files/4626153/amixercontents_pass.txt)
[dmesg0514.log](https://github.com/thesofproject/linux/files/4626154/dmesg0514.log)
[sof-logger0514.log](https://github.com/thesofproject/linux/files/4626155/sof-logger0514.log)

**Comment by ClarexZhou** [comment]
@kv2019i @juimonen  is this issue depend on new feature #2068 ?

**Comment by ClarexZhou** [comment]
same on TGL notebook with ALC3204 in HD-A mode

**Comment by Liviali155** [comment]
update pulseaudio to  default pulseaudio of Ubuntu20.04 + https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 ,error not seen

**Comment by Liviali155** [comment]
On matins:
Output Device switched to Headphones，but Input Device will not switched to Headset when first insert headset,still is “Digital Microphone-sof-had-dsp”, after set it once manual,error not seen

After update pulseaudio to default pulseaudio of Ubuntu20.04 + https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 ,error not seen

**Comment by kv2019i** [comment]
Fixed by PA patches, assigning for @libinyang to follow-up.

**Comment by libinyang** [comment]
with the latest recipe:

UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: http://sof-ci-storage.sh.intel.com/share/alsa/alsa-lib/latest/libasound2_1.2.3.2-a3ca480/
Pulseaudio: http://sof-ci-storage.sh.intel.com/share/pulseaudio/latest/pulseaudio_13.99.1.1-47d8112/
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

This bug is fixed.
Verified on SDW and sof HDA (CML platforms)
