### ISSUE TITLE
[UCM2][CML]Mute LED will flash one time when switch output source in output device.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2112]
**Describe the bug**
Switch source in output device, mute led will fast flash for one time.

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: 13.99.1
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/41

**To Reproduce**
1. Boot up system with HDMI/DP external port and headphone connected.
2. Open sound setting;
3. Try to switch source in output device. 

**Reproduce rate**
5/5

**Expected result**
 Mute led will not flash.

**Actual result**
Mute led will fast flash for 0.5s when switch source in output device.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0a43e72a3
FW: https://github.com/thesofproject/sof/commits/master commit: 83cecc95
Tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
Platform:CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
ALSA maintainer prefers single profile UCM than multi-profile UCM. So closed this issue, as it's only reproduced with multi-profile UCM.
