### ISSUE TITLE
[BUG][CML][SDW UCM2]Input source won't auto highlight on headset when plug in headset with sound setting open

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2113]
**Describe the bug**
Input source won't auto highlight on headset when plug in headset with sound setting open.

Note: 
Unplug headset then plug in headset with sound setting closed, then open sound setting to check. Issue cannot be reproduced, it will auto highlight headset. 

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: 13.99.1
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/41

**To Reproduce**
1. Boot up system with headset connected.
2. Open sound setting, select headset as input device.
3. Unplug headset then plug in it.

**Reproduce rate**
5/5

**Expected result**
Input device will auto highlight on headset.

**Actual result**
Input device cannot auto highlight on headset.
If do step 3 with sound setting closed, issue cannot be reproduced.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0a43e72a3
FW: https://github.com/thesofproject/sof/commits/master commit: 83cecc95
Tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
Platform:CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
ALSA maintainer prefers single profile UCM than multi-profile UCM. So closed this issue, as it's only reproduced with multi-profile UCM.
