### ISSUE TITLE
[BUG][TGL]System will hang about 20s after unplug DP during S3

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2116]
***Describe the bug***
System will hang about 20s after unplug DP during S3,plugin DP again can detect normally,legacy HDA also has this problem 
Error only occured when ubplug DP,HDMI has no this issue

***To Reproduce***
1."sudo reboot" to reboot system with DP connected
2."sudo rtcwake -m mem -s 15" to suspend
3.Unplug DP in suspend
4.wait device to wake up

***Reproduction Rate***
5/5

Expected behavior
System will not hang after wake up

***Impact***
System will hang about 20s after wake up

<details>
 <summary>dmesg_error.log</summary>

````
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.266486] i915 0000:00:02.0: [drm:intel_dp_aux_xfer [i915]] AUX D/port D: timeout (status 0x7d400bff)
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.326486] i915 0000:00:02.0: [drm:intel_dp_aux_xfer [i915]] AUX D/port D: timeout (status 0x7d400bff)
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.326491] [drm:drm_dp_dpcd_access [drm_kms_helper]] Too many retries, giving up. First error: -110
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.326492] i915 0000:00:02.0: [drm] *ERROR* failed to enable link training
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.326506] i915 0000:00:02.0: [drm:intel_dp_start_link_train [i915]] [CONNECTOR:292:DP-1] Link Training failed at link rate = 162000, lane count = 4
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.326524] [drm:intel_dp_modeset_retry_work_fn [i915]] [CONNECTOR:292:DP-1]
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.386488] i915 0000:00:02.0: [drm:intel_dp_aux_xfer [i915]] AUX D/port D: timeout (status 0x7d400bff)
May 14 18:09:31 ubuntu-Tiger-Lake-Client-Platform kernel: [   88.446486] i915 0000:00:02.0: [drm:intel_dp_aux_xfer [i915]] AUX D/port D: timeout (status 0x7d400bff)
````
</details>

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: 83cecc95 https://github.com/thesofproject/sof/commits/master
Kernel: a43e72a3 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/ sof-hda-generic-4ch.tplg same as firmware

[sof-logger0514.log](https://github.com/thesofproject/linux/files/4627708/sof-logger0514.log)

[kern.zip](https://github.com/thesofproject/linux/files/4627733/kern.zip)

**Comment by Liviali155** [comment]
@kv2019i  please help to check it

**Comment by kv2019i** [comment]
Ack, will take a look. This will be take some time due to WFH limitations (I can't unplug the DP remotely).

**Comment by Liviali155** [comment]
Error still can be reproduced after disable audio

**Comment by Liviali155** [comment]
Error still can be reproduced after disable audio,not a audio issue,closed it
