### ISSUE TITLE
[BUG][TGL]UI hang in some Scenarios

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2125]
***Describe the bug***
UI hang in some Scenarios, after issue occured Mouse can  slide,but has no response when you tap anything,the keyboard can work,but screen has no response(ex:press "space" to pause/release aplay,the music will be pause/release,but screen has any response)
only reboot can recovery

***To Reproduce***
Scenario 1:
1.”sudo reboot” to reboot system
2. open terminal 1
3.aplay/arecord(any pipeline)
4.open terminal 2
5.alsamixer to change the volume of the pipeline you used in step 3
6.tap terminal 1

Scenario 2:
1. ”sudo reboot” to reboot system with HDMI and DP
2. open terminal 1 to “aplay -Dhw:0,0 -r48000 -c2 -fs16_le  wav/48California_Dreaming.wav -vv -i
3. open terminal 2 to “aplay -Dhw:0,3 -r48000 -c2 -fs16_le  wav/48California_Dreaming.wav -vv -i
4. open terminal 3 to “aplay -Dhw:0,4 -r48000 -c2 -fs16_le  wav/48California_Dreaming.wav -vv -i
5. open terminal 4 to “arecord -Dhw:0,0 -r48000 -c2 -fs16_le  test.wav -vv -i”
6. open terminal 5 to “arecord -Dhw:0,6 -r48000 -c4 -fs16_le  6.wav -vv -i”
7. open terminal 6 to “arecord -Dhw:0,7 -r48000 -c4 -fs16_le  7.wav -vv -i”
8.Change between 6 terminals  to pause/release

***Reproduction Rate***
6/10

Expected behavior
System  has response when tap anything

***Impact***
System has no response,Mouse can  slide,but has no response when you tap anything

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: 83cecc95 https://github.com/thesofproject/sof/commits/master
Kernel: 1697493f https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/ sof-hda-generic-4ch.tplg same as firmware
 ubuntu20.04 LTS(https://ubuntu.com/download/desktop/thank-you?version=20.04&architecture=amd64 )

Only can catch the kern.log in /var/log, can not catch other logs because sysytem hang
[kern.log](https://github.com/thesofproject/linux/files/4642902/kern.log)

**Comment by Liviali155** [comment]
sof-dev( 0773fe68 ) +https://github.com/thesofproject/sof/commits/tgl-006-drop-stable(e1bafa173) also has this issue

**Comment by Liviali155** [comment]
Changed kernel and firmware to 20200309 ( sof-dev:ac3abc56 +master:6cd8acc1) also has  this issue
Legacy HDA also has this issue

**Comment by ClarexZhou** [comment]
Error also occurred on TGL Notebook with ALC3204 in HDA mode when operating in different terminals.

Error can be reproduced via scenario 2.

**Comment by Liviali155** [comment]
On TGL HDA RVP
After error occured can connect it with ssh,add more logs

<details>
 <summary>sys_error.log</summary>

````
         May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.001024] [drm:__drm_atomic_state_free [drm]] Freeing atomic state 0000000010969822
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.003410] Asynchronous wait on fence 0000:00:02.0:gnome-shell[1023]:426 timed out (hint:intel_atomic_commit_ready+0x0/0x48 [i915])
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.003424] Asynchronous wait on fence 0000:00:02.0:gnome-shell[1023]:426 timed out (hint:intel_atomic_commit_ready+0x0/0x48 [i915])
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.003435] Asynchronous wait on fence 0000:00:02.0:gnome-shell[1023]:426 timed out (hint:intel_atomic_commit_ready+0x0/0x48 [i915])
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.005957] [drm:drm_atomic_state_init [drm]] Allocated atomic state 0000000010969822
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.005961] [drm:drm_atomic_get_plane_state [drm]] Added [PLANE:209:cursor C] 0000000072479bfd state to 0000000010969822
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.005965] [drm:drm_atomic_get_crtc_state [drm]] Added [CRTC:213:pipe C] 000000002ca304d5 state to 0000000010969822
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.005968] [drm:drm_atomic_set_crtc_for_plane [drm]] Link [PLANE:209:cursor C] state 0000000072479bfd to [NOCRTC]
May 19 05:39:13 ubuntu-Tiger-Lake-Client-Platform kernel: [  105.005970] [drm:drm_atomic_set_fb_for_plane [drm]] Set [NOFB] for [PLANE:209:cursor C] state 0000000072479bfd
````
</details>



<details>
 <summary>sys_error.log</summary>

````
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813214] Please file a _new_ bug report at https://gitlab.freedesktop.org/drm/intel/issues/new.
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813214] Please see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813214] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813215] The GPU crash dump is required to analyze GPU hangs, so please always attach it.
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813215] GPU crash dump saved to /sys/class/drm/card0/error
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813230] i915 0000:00:02.0: Resetting rcs0 for stopped heartbeat on rcs0
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813241] i915 0000:00:02.0: Xorg[776] context reset due to GPU hang
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813265] i915 0000:00:02.0: [drm:__i915_request_reset [i915]] context Xorg[776]: guilty 1, banned
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.813275] i915 0000:00:02.0: [drm:__i915_request_reset [i915]] client Xorg[776]: gained 3 ban score, now 3
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.815195] [drm:drm_mode_addfb2 [drm]] [FB:332]
May 19 05:39:18 ubuntu-Tiger-Lake-Client-Platform kernel: [  109.815210] [drm:drm_atomic_state_init [drm]] Allocated atomic state 0000000010969822
````
</details>


[kern.log](https://github.com/thesofproject/linux/files/4649582/kern.log)
[sof-logger0519.log](https://github.com/thesofproject/linux/files/4649584/sof-logger0519.log)
[syslog.zip](https://github.com/thesofproject/linux/files/4649608/syslog.zip)


After disable pulseaudio,issue still can be reproduced
After issue occured， Ctl+alt+F1/F2/F3/F4 to switched screen,has no response

**Comment by Liviali155** [comment]
Have creat a drm issue https://gitlab.freedesktop.org/drm/intel/-/issues/1908 to track,closed this issue
