### ISSUE TITLE
[BUG][CML][UCM2]Output Device will auto switched to speaker after unplug DP in some scenarios when connecting both HDMI & DP displays

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2128]
***Describe the bug***
Output Device will auto switched to speaker after unplug DP in some scenarios when connecting both HDMI & DP displays 
  

***To Reproduce***
**Scenario 1:**
1.sudo reboot to reboot system
2.plug both HDMI & DP displays
3.open sound settings (we can see the default output device is still speaker)
4.set output Device as "HDMI"
5.keep sound setting opening
6.unplug DP

Expected behavior
Output Device should keep HDMI after unplug DP

Actual result
Output Device switched to speaker after unplug DP,if closed sound setting in step5, error not seen

**Scenario 2:**
1."sudo reboot" to reboot system
2.plug HDMI&DP (we can see the default output device is still speaker)
3.open sound settings
4.set output Device as "DP"
5.keep sound setting opening or closed sound setting
6.unplug DP

Expected behavior
Output Device should auto swithed to  HDMI after unplug DP

Actual result
Output Device auto switched to  Speaker after unplug DP

***Reproduction Rate***
10/10

Platform: CML laptop with onboard codec ALC3204 in HDA mode
Firmware: 8a4ec564 https://github.com/thesofproject/sof/commits/master
Kernel: 1697493f https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 81465c56) 
[amixercontents_0519.txt](https://github.com/thesofproject/linux/files/4648920/amixercontents_0519.txt)
[dmesg0519.log](https://github.com/thesofproject/linux/files/4648921/dmesg0519.log)
[sof-logger0519.log](https://github.com/thesofproject/linux/files/4648922/sof-logger0519.log)

**Comment by Liviali155** [comment]
After update pulseaudio to With single profile UCM2 + default pulseaudio of Ubuntu20.04+ https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295   
HAD UCM2: https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 81465c56)
error not seen

**Comment by libinyang** [comment]
with the latest recipe:

UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: https://github.com/alsa-project/alsa-lib (commit a3ca480)
Pulseaudio: https://gitlab.freedesktop.org/pulseaudio/pulseaudio (commit 47d8112)
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

This bug is fixed.
