### ISSUE TITLE
[BUG] No sound with SOF drivers on 5.6.14 and previous kernels

### ISSUE THREAD

**Issue by Valerio1474** [thesofproject/linux#2133]
**Describe the bug**
Hardware: HP Omen 15-dh0002nl
My digital mic is not working with the classic alsa driver. So I tried the SOF drivers this  leads to errors that renders the sound card unusable.

**To Reproduce**
Boot kernel without snd-intel-dspcfg.dsp_driver=1 option or using any other value except 1 (0,2,3)

**Reproduction Rate**
Always with custom and stock kernels since 5.3.x to 5.6.14

**Expected behavior**
I'm trying to use the SOF drivers to make the digital integrated mic work, but things get worse and even sound disappears.

**Impact**
I cannot use the sound card at all. 

**Environment**
1) Branch name and commit hash of the 2 repositories: vanilla kernels from kernel.org compiled by me and stock kernel from Debian vmlinuz-5.6.0-1-amd64
2) firmware from Debian repository Package: firmware-intel-sound Version: 20190717-2
3) Name of the platform(s) on which the bug is observed.
    * Platform:  Debian/Sid

**Screenshots or console output**
\`\`\`[    2.479155] sof-audio-pci 0000:00:1f.3: error: init i915 and HDMI codec failed
[    2.479181] sof-audio-pci 0000:00:1f.3: error: failed to probe DSP -19
[    2.479202] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -19\`\`\`

[dmesg.txt](https://github.com/thesofproject/sof/files/4664435/dmesg.txt)

Sorry no sof-logger output (but you can point me on how to create it)

**Comment by Valerio1474** [comment]
You must be right

**Comment by plbossart** [comment]
@Valerio1474 do you still see an issue? I think @kv2019i fixed support for HP devices

**Comment by Valerio1474** [comment]
Hi @plbossart, I have tried to follow the instructions here [https://github.com/thesofproject/linux/issues/2065#issuecomment-623105810](url) and compile and install kernel 5.7rc7 but I think something is still wrong, maybe I'm missing something, here is an excerpt from dmesg.
\`\`\`[    2.158770] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    2.159669] sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cfl.ri failed with error -2
[    2.159671] sof-audio-pci 0000:00:1f.3: error: request firmware intel/sof/sof-cfl.ri failed err: -2
[    2.159751] sof-audio-pci 0000:00:1f.3: error: failed to load DSP firmware -2
[    2.160141] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -2\`\`\`

**Comment by plbossart** [comment]
@Valerio1474 you don't have the firmware installed on lib/firmware/intel/sof. please install with https://github.com/thesofproject/sof-bin/tree/stable-v1.4.3

If you see a hang you can try the 1.5 version, but that will also lead to issues with dmic names. we should have 1.5.1 "soon".

**Comment by Valerio1474** [comment]
Hi @plbossart thank you for your instructions, I was sure to have installed the fw in the right directory supposing it was Cannon Lake platform, but I was surely wrong. Anyway I followed your suggestion and the only bit to correct is the go.sh script that has nothing inside, so I copied the one from 1.4.2 branch and changed 1.4.2=>1.4.3 in the version stanza.
Kernel boots without errors using the sof driver, sound plays but the mic is still not working, it's present but it's unable to capture any input...
![Screenshot_20200528_101759](https://user-images.githubusercontent.com/30036939/83116871-acbc1000-a0cc-11ea-8e64-f9987dceebc1.jpg)
[dmesg_280420_h1021am.txt](https://github.com/thesofproject/linux/files/4694200/dmesg_280420_h1021am.txt)

I'm willing to try and test new solutions. Have a nice day

**Comment by plbossart** [comment]
can you try to capture at the driver level with 

arecord -Dhw:0,6 -c4 -r48000 -f32_LE -d 10 test.wav

if this doesn't work try with -c2 and check that the device 6 is correct with arecord -l

**Comment by Valerio1474** [comment]
I tried this (I added the S in the -f argument I hope it was correct):
```
arecord -Dhw:1,6 -c2 -r48000 -fS32_LE -d 10 test.wav
Recording WAVE 'test.wav' : Signed 32 bit Little Endian, Rate 48000 Hz, Stereo
```
and I got a playable record of my ugly voice. :)

**Comment by plbossart** [comment]
@Valerio1474 so you are having a problem with pulseaudio.  You need recent version of alsa-lib and alsa-ucm-conf as well. I am pretty sure it's in Debian testing, not sure about sid.

**Comment by Valerio1474** [comment]
After installing alsa-ucm-conf I got many error messages from the sof driver:
```
sof-audio-pci 0000:00:1f.3: ASoC: can't set iDisp3 Pin hw params: -22
[    6.646027]  iDisp3: ASoC: hw_params BE failed -22
[    6.646028]  HDMI3: ASoC: hw_params BE failed -22
[    6.646209] sof-audio-pci 0000:00:1f.3: ASoC: can't set iDisp3 Pin hw params: -22
[    6.646210]  iDisp3: ASoC: hw_params BE failed -22
[    6.646210]  HDMI3: ASoC: hw_params BE failed -22
[    6.646350] sof-audio-pci 0000:00:1f.3: ASoC: can't set iDisp3 Pin hw params: -22
```
Audio was not working at all after boot.
I think alsa-ucm-conf has messed with the file hdmi.conf I got yesterday from here [https://bugzilla.kernel.org/show_bug.cgi?id=206085](url)
Alsa packages in Debian/Sid are version 1.2 and I think they are too old to manage properly my soundcard, so I had to resort to manually update Hdmi.conf again to fix the sof-driver behavior.
Now I've everything working: my mixer shows all the option (I must select the dmic input to get records of my voice in Skype) a really great improvement! Thank you

P.S.: what PGA1, PGA3.... stand for?

**Comment by kv2019i** [comment]
Good to hear @Valerio1474 . The alsa-ucm is a known problem with laptops with separate discrete graphics (like the HP Omen you have -> see https://github.com/thesofproject/linux/issues/2065#issuecomment-623105810 ). A fix is merged to upstream alsa-ucm git repository, but local fix to Hdmi.conf is also fine.

For default routing of Skype calls, one solution for Debian is here (I've not tested this myself, just passing on):
https://wiki.debian.org/InstallingDebianOn/Thinkpad/X1%20Carbon%207th%20Gen

> P.S.: what PGA1, PGA3.... stand for?

These are digital volume controls implemented on the DSP and PGA (Programmable Gain Amplifier) is the standard acronym used in ASoC (and common elsewhere as well).

If you are good with this, ok to close the bug?

**Comment by Valerio1474** [comment]
@kv2019i Sure I can close the bug, thank you for your work and support!

**Comment by Valerio1474** [comment]
@kv2019i Sure I can close the bug, thank you for your work and support!
