### ISSUE TITLE
sof-audio-acpi 80860F28:00: error: ipc timed out for 0x60050000 size 12

### ISSUE THREAD

**Issue by youling257** [thesofproject/linux#2142]
[  332.048218] sof-audio-acpi 80860F28:00: error: ipc timed out for 0x60050000 size 12
[  332.048280] sof-audio-acpi 80860F28:00: error: unexpected fault 0x600a0001 trace 0x00000000
[  332.048287] sof-audio-acpi 80860F28:00: error: ipc host -> DSP: pending no complete no raw 0x8000000000000000
[  332.048290] sof-audio-acpi 80860F28:00: error: mask host: pending no complete no raw 0x0
[  332.048294] sof-audio-acpi 80860F28:00: error: ipc DSP -> host: pending no complete yes raw 0x600a0001
[  332.048297] sof-audio-acpi 80860F28:00: error: mask DSP: pending no complete no raw 0x0
[  332.048304]  Low Latency: ASoC: trigger FE cmd: 0 failed: -110
[  332.552324] sof-audio-acpi 80860F28:00: error: ipc timed out for 0x60030000 size 12
[  332.552387] sof-audio-acpi 80860F28:00: error: unexpected fault 0x600a0001 trace 0x00000000
[  332.552393] sof-audio-acpi 80860F28:00: error: ipc host -> DSP: pending no complete no raw 0x8000000000000000
[  332.552397] sof-audio-acpi 80860F28:00: error: mask host: pending no complete no raw 0x0
[  332.552400] sof-audio-acpi 80860F28:00: error: ipc DSP -> host: pending no complete yes raw 0x600a0001
[  332.552403] sof-audio-acpi 80860F28:00: error: mask DSP: pending no complete no raw 0x0

**Comment by plbossart** [comment]
please provide more context and full dmesg logs - also enable dynamic debug

**Comment by youling257** [comment]
how to enable dynamic debug?

**Comment by plbossart** [comment]
copy this as /etc/modprobe.d/sof-ddebug.conf

[ddebug.txt](https://github.com/thesofproject/linux/files/4690157/ddebug.txt)

**Comment by youling257** [comment]
tell me echo which file?
echo 'file xxxx +p' > /sys/kernel/debug/dynamic_debug/control

**Comment by plbossart** [comment]
> tell me echo which file?
> echo 'file xxxx +p' > /sys/kernel/debug/dynamic_debug/control

I already provided all the information you need.

**Comment by youling257** [comment]
my system not support /etc/modprobe.d/, not use /etc/modprobe.d/.

**Comment by youling257** [comment]
echo 'file sound/soc/sof/*  +p' > /sys/kernel/debug/dynamic_debug/control
a lot of warning
[  348.356554] sof-audio-acpi 80860F28:00: pcm: open stream 0 dir 0
[  348.356561] sof-audio-acpi 80860F28:00: period min 192 max 16384 bytes
[  348.356564] sof-audio-acpi 80860F28:00: period count 2 max 16
[  348.356567] sof-audio-acpi 80860F28:00: buffer max 65536 bytes
[  348.356613] sof-audio-acpi 80860F28:00: pcm: free stream 0 dir 0
[  348.356654] sof-audio-acpi 80860F28:00: pcm: close stream 0 dir 0

**Comment by plbossart** [comment]
no information provided and no issues with IPC in all CI/daily tests -> closing
