### ISSUE TITLE
tplg loading failed on Yorp

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#215]
The sof-glk-da7219.tplg cannot be loaded on Yorp, since the SSP token is changed in soft/pull/114. But no such issue on UP^2 with latest sof-dev and soft-master. So maybe some kernel patches are missing in cros-sof-v4.14-rebase, please help to check.

Test config:
1. sof-master: b793f0c
2. kernel-cros-sof-v4.14-rebase: 3ad0e4d
3. soft-master: 8d0f178

error log:
[    5.967369] sof-audio sof-audio: error: source SSP0.OUT not found
[    5.967376] sof-audio sof-audio: ASoC: no source widget found for SSP0.OUT
[    5.967379] sof-audio sof-audio: ASoC: Failed to add route SSP0.OUT -> direct -> codec0_out
[    5.967382] sof-audio sof-audio: sink codec1_out control none source SSP0.OUT
[    5.967384] sof-audio sof-audio: error: source SSP0.OUT not found
[    5.967388] sof-audio sof-audio: ASoC: no source widget found for SSP0.OUT
[    5.967390] sof-audio sof-audio: ASoC: Failed to add route SSP0.OUT -> direct -> codec1_out
[    5.967393] sof-audio sof-audio: sink ssp1 Tx control none source SSP0.OUT
[    5.967395] sof-audio sof-audio: error: source SSP0.OUT not found
[    5.967399] sof-audio sof-audio: ASoC: no source widget found for SSP0.OUT
[    5.967401] sof-audio sof-audio: ASoC: Failed to add route SSP0.OUT -> direct -> ssp1 Tx
[    5.967404] sof-audio sof-audio: sink SSP0.IN control none source ssp1 Rx
[    5.967406] sof-audio sof-audio: error: sink SSP0.IN not found
[    5.967410] sof-audio sof-audio: ASoC: no sink widget found for SSP0.IN
[    5.967413] sof-audio sof-audio: ASoC: Failed to add route ssp1 Rx -> direct -> SSP0.IN
[    5.967416] sof-audio sof-audio: sink Capture control none source SSP0.OUT
[    5.967417] sof-audio sof-audio: error: source SSP0.OUT not found
[    5.967421] sof-audio sof-audio: ASoC: no source widget found for SSP0.OUT
[    5.967424] sof-audio sof-audio: ASoC: Failed to add route SSP0.OUT -> direct -> Capture
[    5.967427] sof-audio sof-audio: sink SoC DMIC control none source SSP0.OUT
[    5.967428] sof-audio sof-audio: error: source SSP0.OUT not found
[    5.967432] sof-audio sof-audio: ASoC: no source widget found for SSP0.OUT
[    5.967435] sof-audio sof-audio: ASoC: Failed to add route SSP0.OUT -> direct -> SoC DMIC
[    5.967438] sof-audio sof-audio: sink SSP0.IN control none source codec0_in
[    5.967439] sof-audio sof-audio: error: sink SSP0.IN not found
[    5.967443] sof-audio sof-audio: ASoC: no sink widget found for SSP0.IN
[    5.967446] sof-audio sof-audio: ASoC: Failed to add route codec0_in -> direct -> SSP0.IN
[    5.967457] sof-audio sof-audio: tplg: config SSP1 fmt 0x4001 mclk 19200000 bclk 1536000 fclk 48000 width (0)16 slots 2 mclk id 0
[    5.967474] sof-audio sof-audio: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    5.967578] sof-audio sof-audio: error: ipc error for 0x80010000 size 0xc
[    5.967587] sof-audio sof-audio: error: failed to set DAI config for SSP1
[    5.967590] sof-audio sof-audio: ASoC: physical link loading failed
[    5.967593] sof-audio sof-audio: error: tplg component load failed -22
[    5.967605] sof-audio sof-audio: error: failed to load DSP topology -22
[    5.967608] sof-audio sof-audio: ASoC: failed to probe component -22
[tplg-dmesg.log](https://github.com/thesofproject/linux/files/2515041/tplg-dmesg.log)

**Comment by plbossart** [comment]
well yes, if you are using cros-v4.14 with the latest topology and firmware ipc it cannot work.

**Comment by mengdonglin** [comment]
@plbossart So we need to back port https://github.com/thesofproject/linux/pull/204 to cros-v4.14/cros-v4.14-rebase?

**Comment by mengdonglin** [comment]
@ranj063 What's your plan for this?

**Comment by ranj063** [comment]
@mengdonglin @keqiaozhang this issue is fixed with debug/cros-sof-v4.14-rebase.

**Comment by plbossart** [comment]
can we please close this?

**Comment by keqiaozhang** [comment]
Confirmed that this issue is fixed.
kernel-debug/cros-v4.14-rebase: 90eee4
sof-master: 43da169+ revert 62c568
soft-master: 4ac9248
