### ISSUE TITLE
[JSL] runtime PM causes the system to hang 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2152]
**Describe the bug**
We observed the system hang issue when runtime PM is suspended on JSL ChromeBook. 
if runtime PM is disabled like below, this issue cannot be reproduced.
$ echo on > /sys/bus/pci/devices/0000:00:1f.3/power/control
Pulseaudio is disabled.
Since this issue will cause the system to hang, so no logs can be dumped.

**To Reproduce**
After the system boots, idle for a few seconds, then runtime PM will suspend automatically.
then you will observe the system hang issue.

**Reproduction Rate**
10/10

**Impact**
system hang

**Environment**
 * Kernel: topic/sof-dev
       Commit: 866e4d5 and cherry-pick 4 patches from chrome repo to enable pinctrl for JSL.
https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/refs/heads/master/overlay-dedede/sys-kernel/chromeos-kernel-5_4/files/0001-CHROMIUM-pinctrl-intel-Allow-pin-as-IRQ-even-in-ACPI.patch
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2150573
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2150572
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2150571

  * SOF: Branch: https://github.com/thesofproject/sof/tree/jsl-002-drop-stable
Commit : d8a5f4c
Topology:  sof-jsl-da7219.m4  
  * Platform: JSL chromebook

**Screenshots or console output**
N/A

*sof-logger*. 
N/A

**Comment by sinahuang** [comment]
Error not seen with sof-dev (commit:b0c0ab3) +jsl-002-drop-stable (commit:d8a5f4c )branch on JSL-RVP with ALC700 in HDA mode.

**Comment by xiulipan** [comment]
duplicated issues https://github.com/thesofproject/linux/issues/2166 https://github.com/thesofproject/linux/issues/2170 https://github.com/thesofproject/linux/issues/2152

Issue root cause to be related to DA7219 headset. When no headset plugin. No issue seen.
Test also with Chrome OS kernel 5.4. No issue seen.

Need to check what is the gap for pinctl support for JSL and DA7219

**Comment by keqiaozhang** [comment]
This issue cannot be reproduced after updating kernel to r5.8 (JSL-v0.3 release).
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 for DP fix 
+ PR#2184 for wov S0i2
