### ISSUE TITLE
[JSL][bug]" error at snd_soc_dai_hw_params on iDisp3 Pin: -22" occured when aplay via HDMI.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2153]
**Describe the bug**
Boot up system without DP/HDMI found that there is no HDMI jack detection in amixer contents . Then aplay via HDMI dmesg shows " error at snd_soc_dai_hw_params on iDisp3 Pin: -22" and terminal shows "Unable to install hw". Other pipline works well. 
```
ubuntu@sh-Jasper-Lake-HDA:~$ aplay -Dhw:0,4 -r48000 -c2 -fs16_le wav/48K_Let_It_Go.wav -vv -i
Playing WAVE 'wav/48K_Let_It_Go.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
aplay: set_params:1407: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: 85000
PERIOD_SIZE: 4080
PERIOD_BYTES: 16320
PERIODS: (4 5)
BUFFER_TIME: 341000
BUFFER_SIZE: 16368
BUFFER_BYTES: 65472
TICK_TIME: 0
```

**To Reproduce**
1.Boot up system without HDMI/DP connected.
2.Run "aplay -Dhw:0,4 -r48000 -c2 -fs16_le wav/48K_Let_It_Go.wav -vv -i"

**Reproduce rate**
5/5

**Expected result**
System should work normally and no error info.

**Actual result**
"ASoC: error at snd_soc_dai_hw_params on iDisp3 Pin: -22" occured when reboot system without HDMI connected. 

dmesg log:
```
[    8.404681] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[    8.404699] sof-audio-pci 0000:00:1f.3: pcm: open stream 5 dir 0
[    8.404703] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[    8.404720] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[    8.404722] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[    8.405021] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.405138] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.405145] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on iDisp3 Pin: -22
[    8.405151]  iDisp3: ASoC: hw_params BE failed -22
[    8.405154]  HDMI3: ASoC: hw_params BE failed -22
[    8.405160] sof-audio-pci 0000:00:1f.3: pcm: free stream 5 dir 0
[    8.405275] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.405395] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.405399] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on iDisp3 Pin: -22
[    8.405403]  iDisp3: ASoC: hw_params BE failed -22
[    8.405406]  HDMI3: ASoC: hw_params BE failed -22
[    8.405410] sof-audio-pci 0000:00:1f.3: pcm: free stream 5 dir 0
[    8.405505] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.405632] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.405637] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on iDisp3 Pin: -22
[    8.405643]  iDisp3: ASoC: hw_params BE failed -22
[    8.405646]  HDMI3: ASoC: hw_params BE failed -22
```
**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:  b0c0ab3
FW: https://github.com/thesofproject/sof/commits/master commit: 145d9aa
Tplg: sof-hda-generic-4ch.tplg
Platform:JSP-RVP with ALC700 in HDA mode
[sof-trace1.log](https://github.com/thesofproject/linux/files/4710496/sof-trace1.log)
[dmesg1.log](https://github.com/thesofproject/linux/files/4710498/dmesg1.log)
[dmesg_drm.log](https://github.com/thesofproject/linux/files/4710797/dmesg_drm.log)

**Comment by kv2019i** [comment]
@sinahuang I'd say this is expected. In normal usage, user-space audio server (Pulseaudio, CRAS) will look at the alsamixer controls to see whether a monitor is connected and not route audio to HDMI/DP if no monitor is present. In this case aplay is run when monitors are not connected and the error is expected. Or did I miss some aspect in the report?

**Comment by Liviali155** [comment]
Error not seen on TGL laptop with aboard codec ALC3204 in HDA mode with latest sof-dev(16d98cd5)+master(ef43899c),drm log as below



[kern.zip](https://github.com/thesofproject/linux/files/4727382/kern.zip)

**Comment by sinahuang** [comment]
Error can't be seen with sof-dev (commit: 16d98c)+PR https://github.com/thesofproject/linux/pull/2167.

**Comment by ClarexZhou** [comment]
Close for PR#2167 is merged.
