### ISSUE TITLE
[JSL][BUG]Aplay via HDMI takes 5 mins to response after system wake up from s2idle.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2154]
**Describe the bug**
Aplay stuck and doesn't started after system wake up from s2idle.  Waiting for about 4mins" Unable to sync register 0x2f8100. -5" shows in dmesg. Then waiting for about 1 mins  HDMI begin to  playback normally.

**To Reproduce**
1.Boot up system with HDMI connected.
2.Run " sudo rtcwake -m mem -s 10" and waiting for system wake up from s2idle.
3.Run "aplay -Dhw:0,4 -r48000 -c2 -fs16_le wav/48K_Let_It_Go.wav -vv -i"

**Reproduce rate**
5/5

**Expected result**
HDMI should  work after system wake up from s2idle.

**Actual result**
HDMI can't work after system wake up from s2idle.
```
[  241.485682] snd_hda_codec_hdmi ehdaudio0D2: Unable to sync register 0x2f8100. -5
[  241.485700] snd_hda_codec_hdmi ehdaudio0D2: HDMI: detected monitor DELL U2414H at connection type HDMI
[  241.485704] snd_hda_codec_hdmi ehdaudio0D2: HDMI: available speakers: FL/FR
[  241.485710] snd_hda_codec_hdmi ehdaudio0D2: HDMI: supports coding type LPCM: channels = 2, rates = 32000 44100 48000, bits = 16 20 24
[  246.496716] sof-audio-pci 0000:00:1f.3: pcm: open stream 4 dir 0
[  246.496721] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[  246.496724] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[  246.496727] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[  246.497331] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 0


```

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:  b0c0ab
FW: https://github.com/thesofproject/sof/commits/master commit: 145d9a
Tplg: sof-hda-generic-4ch.tplg
Platform:JSP-RVP with ALC700 in HDA mode
[dmesg.log](https://github.com/thesofproject/linux/files/4710668/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4710675/sof_trace.log)

**Comment by sinahuang** [comment]
Might be same root cause with https://github.com/thesofproject/linux/issues/1719

**Comment by sinahuang** [comment]
Error also can be seen after pulseaudio disabled.

**Comment by ClarexZhou** [comment]
@kv2019i  could you help to confirm https://lists.freedesktop.org/archives/intel-gfx/2020-April/236415.html is backport on sof-dev?

**Comment by kv2019i** [comment]
@ClarexZhou wrote:
> @kv2019i could you help to confirm https://lists.freedesktop.org/archives/intel-gfx/2020-April/236415.html is backport on sof-dev?

Ouch, indeed, that's still missing (although merged in drm tree). I'll backport that to sof-dev.

**Comment by sinahuang** [comment]
Error can't be seen with sof-dev (commit: 16d98c)+PR https://github.com/thesofproject/linux/pull/2167.
