### ISSUE TITLE
[JSL][BUG]System will hang for about 5mins after wake up from s2idle with sound setting opened .

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2156]
**Describe the bug**
It takes about 5mins to reponse after system wake up if enter S2idle in sound setting open status. And then system can't enter S2ilde again.

**To Reproduce**
1.Boot up system with HDMI connected.
2.Open sound setting
3.Run "sudo rtcwake -m mem -s 10"
4.Waiting for about 5 mins

**Reproduce rate**
5/5

**Expected result**
System should work normally after wake up from s2idle with sound setting opened .

**Actual result**
System will hang for about 5mins after wake up from s2idle with sound setting opened .

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:  b0c0ab3
FW: https://github.com/thesofproject/sof/commits/master commit: 145d9aa
Tplg: sof-hda-generic-4ch.tplg
Platform:JSP-RVP with ALC700 in HDA mode

No error info in dmesg:
[dmesg22.log](https://github.com/thesofproject/linux/files/4711122/dmesg22.log)
[sof_trace22.log](https://github.com/thesofproject/linux/files/4711123/sof_trace22.log)

**Comment by sinahuang** [comment]
Error can't be seen when disabled pulseaudio and the opened setting isn't sound setting .

**Comment by kv2019i** [comment]
This is very likely same rootcause as #2154

**Comment by sinahuang** [comment]
Error can't be seen with sof-dev (commit: 16d98c)+PR https://github.com/thesofproject/linux/pull/2167.
