### ISSUE TITLE
Soundwire support in upstream?

### ISSUE THREAD

**Issue by perexg** [thesofproject/linux#2157]
Trying linux-next and I don't see the c960b4636c4d500ed745544347873e44b7f1e2e8 commit applied. When do you expect the initial soundwire support in the official linux kernel? The soundwire core code issues were resolved so the SDW support should be added ASAP.

I will update this bug, if I find other commits missing..

**Comment by plbossart** [comment]
> Trying linux-next and I don't see the [c960b46](https://github.com/thesofproject/linux/commit/c960b4636c4d500ed745544347873e44b7f1e2e8) commit applied. When do you expect the initial soundwire support in the official linux kernel? The soundwire core code issues were resolved so the SDW support should be added ASAP.
> 
> I will update this bug, if I find other commits missing..

We wanted to add the build support when it's really usable, but without waiting for everything to be accepted.

see the tentative order of patches here:
https://github.com/thesofproject/linux/commits/topic/sof-dev-rebase

**Comment by perexg** [comment]
It's 86 patches, 7023 diff lines on top of linux-next now. What else is missing?

**Comment by plbossart** [comment]
> It's 86 patches, 7023 diff lines on top of linux-next now. What else is missing?

Sorry, I don't understand the question. We don't have any other patches than what is listed on topic/sof-dev-rebase. Everything was done in public, there's no secret patches we kept back on the Intel side.

**Comment by perexg** [comment]
I meant when you expect to activate the SOF soundwire code in the official linux kernel. Our (Fedora, RHEL) policy for kernel is "don't accept the code until it's at least in the maintainer tree".

**Comment by plbossart** [comment]
oh, yes absolutely, we haven't stopped, @bardliao will be working on this and applying feedback/changes as needed. We are hoping most patches will be accepted for 5.9 with corrections/fixes for 5.10. All the code is really mostly incremental, from enabling the 'right' programming sequences to power management/clock stop and multi-link.

**Comment by perexg** [comment]
Thank you for your answer. It's a bit late than we expected, but I understand that this code is complex.

**Comment by plbossart** [comment]
@perexg the rest of the code is really Intel-specific and I don't think there will be a lot of pushback since we just implemented the right programming sequences required by the hardware. Of course there will be bike-shed paint comments but at some point the hardware is what it is.

**Comment by plbossart** [comment]
closing since there's no bug here, just a painfully slow upstream process.
