### ISSUE TITLE
[BUG][TGL]SOF cannot load successfully with kernel on latest topic/sof-dev

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2161]
**Describe the bug**
"soundwire sdw:0:25d:5682:0: Probe not complete, timed out" shows in boot up dmesg. 

**To Reproduce**
1.Boot up .
2.Check dmesg.

**Reproduce rate**
5/5

**Expected result**
System boot up successfully

**Actual result**
aplay -l shows no sound card and "soundwire sdw:0:25d:5682:0: Probe not complete, timed out" shows in boot up dmesg. 

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit: b0c0ab3b
Revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a
Revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d
FW: https://github.com/thesofproject/sof/tree/tgl-006-drop-stable  commit: f45bf945962813e6e
Tplg: same as fw plus pr3006 sof-tgl-sdw-max98373-rt5682-4ch.tplg rename to sof-tgl-sdw-max98373-rt5682.tplg
Platform: TGL SDW chromebook with rt5682-max98373 

[dmesg_latest_sof-dev.log](https://github.com/thesofproject/linux/files/4715382/dmesg_latest_sof-dev.log)

**Comment by YvonneYang2** [comment]
Tested it with latest sof-dev(commit: 16d98cd5) + revert 2 commits + #2160 , issue cannot be reproduced.

**Comment by bardliao** [comment]
The issue is that ``SDW_SLAVE_ENTRY_EXT(0x025d, 0x5682, 0x1, 0, 0),`` is described in rt5682-sdw.c. However, current sdw version of rt5682 is 1.1 (0x2). 
```
soundwire sdw-master-0: SDW Slave Addr: 20025d568200
```
