### ISSUE TITLE
[BUG][GLK][sound/for -next]"error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read" occured  when do module load/unload test .

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2163]
**Describe the bug**
"error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read" occured  when do module load/unload test . After issue occured can't load/unload module again and all pipeline can't work.
Power cycle can recover.

```
2020-04-01 17:24:41 UTC [INFO] checking for general errors after kmod insert with sof-kernel-log-check tool
2020-04-01 17:24:41 UTC [INFO] checking if firmware is loaded successfully
2020-04-01 17:24:41 UTC [INFO] ==== firmware boot complete: 1 of 50 ====
2020-04-01 17:24:59 UTC [INFO] ===== Starting iteration 2 of 50 =====
2020-04-01 17:24:59 UTC [INFO] wait dsp power status to become suspended
2020-04-01 17:25:18 UTC [INFO] dsp is not suspended after 15s, end test
2020-04-01 17:25:18 UTC [INFO] Test Result: FAIL!

```

**To Reproduce**
1.sudo reboot
2. cd sof-test
3.cd test-case
4.export TPLG=/lib/firmware/intel/sof-glk-da7219.tplg
5../check-kmod-load-unload.sh(https://github.com/thesofproject/sof-test/blob/master/test-case/check-kmod-load-unload.sh)

**Reproduction Rate**
10/10

**Expected behavior**
 Module load/unload should work normally and no error info.

**Impact**
"error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read" occured  when do module load/unload test .

```
[   31.436729] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x3010202 successful
[   31.466535] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x5000001 successful
[   34.467067] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x0 timedout
[   34.467074] sof-audio-pci 0000:00:0e.0: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   34.467099] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[   34.467105] sof-audio-pci 0000:00:0e.0: error: load fw failed ret: -110
[   34.467151] sof-audio-pci 0000:00:0e.0: unknown ROM status value 00000000
[   34.467157] sof-audio-pci 0000:00:0e.0: error: status = 0x00000000 panic = 0x00000130
[   34.467165] sof-audio-pci 0000:00:0e.0: unknown ROM status value 00000000
[   34.467180] sof-audio-pci 0000:00:0e.0: error: failed to reset DSP
[   34.467186] sof-audio-pci 0000:00:0e.0: error: failed to boot DSP firmware -110
[   34.517539] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x1d003c timedout
[   34.517545] sof-audio-pci 0000:00:0e.0: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[   34.517553] sof-audio-pci 0000:00:0e.0: error: dsp core reset failed: core_mask 3
[   34.531974] sof-audio-pci 0000:00:0e.0: error: sof_probe_work failed err: -110
```
**Environment**
    * Kernel:https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?h=for-next 
 (commit:f99e24a6)
    * SOF:https://github.com/thesofproject/sof/commits/master (commit:30e801 )
2) Name of the topology file
    * Topology: {sof-glk-da7219.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {GLK Chrome with onboard codec DA7219 in I2S mode}

Module can't load, so can't cat the sof trace.
[dmesg1.log](https://github.com/thesofproject/linux/files/4716597/dmesg1.log)

**Comment by plbossart** [comment]
@sinahuang does this work with topic/sof-dev?

Also you should take Mark Brown's tree, not Takashi's for ASoC tests. You may be testing code from the previous cycle that has not been merged by Takashi.

**Comment by sinahuang** [comment]
Issue can't be reproduced with sound/for-next(commit: 951e273) +master(commit: b5043671), so closed it.
