### ISSUE TITLE
[BUG] S2idle will cause system hang on JSL Chromebook

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2170]
**Describe the bug**
Just use this bug to track the S0ix on JSL. we need to verify WoV during the S0ix, but S0ix is not supported yet. current stats is that system will hang when entering to S0ix.

**To Reproduce**
S0ix:
1. Ensure suspend mode is S2idle,k 
    echo s2idle > /sys/power/mem_sleep 
2. cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec
3. sudo rtcwake -m mem -s 10
4. cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec  to check the residency time is increasing or not 

 S3:
1. echo deep >  /sys/power/mem_sleep
2. sudo rtcwake -m mem -s 10

**Reproduction Rate**
10/10

**Impact**
system hang

**Environment**
 * Kernel: topic/sof-dev
       Commit: 866e4d5 and cherry-pick 4 patches from chrome repo to enable pinctrl for JSL.
https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/refs/heads/master/overlay-dedede/sys-kernel/chromeos-kernel-5_4/files/0001-CHROMIUM-pinctrl-intel-Allow-pin-as-IRQ-even-in-ACPI.patch
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2150573
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2150572
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2150571

  * SOF: Branch: https://github.com/thesofproject/sof/tree/jsl-002-drop-stable
Commit : d8a5f4c
Topology:  sof-jsl-da7219.m4  
  * Platform: JSL chromebook

**Screenshots or console output**
N/A

```
*sof-logger*. 
N/A

**Comment by sinahuang** [comment]
System only can't enter s0ix on JSL RVP in HDA mode, and system will not hang when entering s2ilde.

**Comment by xiulipan** [comment]
@sinahuang Will the JSL HDA RVP also be hang when enter S3?

**Comment by sinahuang** [comment]
> @sinahuang Will the JSL HDA RVP also be hang when enter S3?

System can't hang on JSL linux RVP with HDA codec when enter S3 and s2idle. Thought S0ix can't be achieved on JSL linux RVP

**Comment by ClarexZhou** [comment]
S3 isn't supported even after disable audio

**Comment by xiulipan** [comment]
duplicated issues https://github.com/thesofproject/linux/issues/2166 https://github.com/thesofproject/linux/issues/2170 https://github.com/thesofproject/linux/issues/2152

Issue root cause to be related to DA7219 headset. When no headset plugin. No issue seen.
Test also with Chrome OS kernel 5.4. No issue seen.

Need to check what is the gap for pinctl support for JSL and DA7219

**Comment by keqiaozhang** [comment]
This issue cannot be reproduced after updating kernel to r5.8 (JSL-v0.3 release).
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 for DP fix 
+ PR#2184 for wov S0i2
