### ISSUE TITLE
[BUG][CML] kernel NULL pointer dereference in rt5682_jack_detect_handler

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#2187]
- Device: cml helios
- linux hash: a7bffa42fe2a
- Kconfig : default + memory-debug-defconfig
- toplogy : sof-cml-rt1011-rt5682.tplg
- test command: ./check-kmod-load-unload.sh -l 3

I was testing sof-test test cases with KASAN enabled.
```
[  477.292099] BUG: kernel NULL pointer dereference, address: 000000000000031c
[  477.292106] #PF: supervisor read access in kernel mode
[  477.292109] #PF: error_code(0x0000) - not-present page
[  477.292113] PGD 0 P4D 0
[  477.292119] Oops: 0000 [#1] SMP DEBUG_PAGEALLOC KASAN NOPTI
[  477.292126] CPU: 1 PID: 2637 Comm: kworker/1:3 Tainted: G    B             5.7.0-rc7-test+ #4
[  477.292130] Hardware name: Google Helios/Helios, BIOS  01/21/2020
[  477.292140] Workqueue: events_power_efficient rt5682_jack_detect_handler [snd_soc_rt5682]
[  477.292151] RIP: 0010:rt5682_jack_detect_handler+0x72/0x380 [snd_soc_rt5682]
```
[0610_cml_helios_null_pointer.txt](https://github.com/thesofproject/linux/files/4760703/0610_cml_helios_null_pointer.txt)
(sorry lost full dmesg)

card's address seems to be wrong
`while (!rt5682->component->card->instantiated)`

Tried reproduce again but seeing same issue with https://github.com/thesofproject/linux/issues/2186. Creating an issue not to lose possible BUG.

update:
Able to reproduce same error, attached full dmesg. Seeing KASAN same with 2186 and null pointer dereference.
[0610_dmesg04_null_pointer_dereference.log](https://github.com/thesofproject/linux/files/4761158/0610_dmesg04_null_pointer_dereference.log)

**Comment by plbossart** [comment]
@fredoh9 can you try to the same solution we added for sof_rt5682, I think it's a requirement that we use snd_soc_component_set_jack(NULL, NULL). Adding @bardliao for more comments.

````c
static int sof_rt5682_remove(struct platform_device *pdev)
{
	struct snd_soc_card *card = platform_get_drvdata(pdev);
	struct snd_soc_component *component = NULL;

	for_each_card_components(card, component) {
		if (!strcmp(component->name, rt5682_component[0].name)) {
			snd_soc_component_set_jack(component, NULL, NULL);
			break;
		}
	}

	return 0;
}
````

**Comment by fredoh9** [comment]
@plbossart @bardliao 
I added same code above in rt5682_remove() but i'm still able to reproduce the KASAN error, Not sure what else is missed. I need your comment and help. This commit is based on topic/sof-dev + find_next_bit fix to avoid known kasan bugs.
https://github.com/fredoh9/linux/commit/2757d5ea2818ad8c264d954bfa357f852d3cbafd

[0613_dmesg03_kasan_debug_log_on_kmod.log](https://github.com/thesofproject/linux/files/4775697/0613_dmesg03_kasan_debug_log_on_kmod.log)

**Comment by bardliao** [comment]
@fredoh9 Could you try @plbossart in https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/cml_rt1011_rt5682.c? Maybe do it in rt5682 driver itself is too late. Thanks.

**Comment by plbossart** [comment]
@fredoh9 you probably want to add more traces in the codec driver to figure out which pointer is used.

**Comment by plbossart** [comment]
> @fredoh9 Could you try @plbossart in https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/cml_rt1011_rt5682.c? Maybe do it in rt5682 driver itself is too late. Thanks.

Yes the code needs to be added to the machine driver, not the codec driver.

**Comment by fredoh9** [comment]
I applied same change to machine driver, cmd_rt1011_rt5682.c. Looks working fine with kmod test of 15 times. I will make sure the KASAN bug is not reproduced with more testings. I will submit a PR today.
