### ISSUE TITLE
HDA/HDMI memory leaks on module remove

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2195]
The sequences to release resources when we remove drivers generates a lot of memory leaks, specifically for HDAudio/HDMI.

Tests on top of https://github.com/thesofproject/linux/pull/2194

[sof-dev-defconfig.txt](https://github.com/thesofproject/linux/files/4772814/sof-dev-defconfig.txt)

bash test file (ajust as needed, this is for a SoundWire platform) 
[leak.txt](https://github.com/thesofproject/linux/files/4772817/leak.txt)

results 
[kmemleak.txt](https://github.com/thesofproject/linux/files/4772820/kmemleak.txt)

**Comment by kv2019i** [comment]
@plbossart Hmm, this is pretty bad actually. Actual cleanup routines are correct, but when used via hdac_hda.c, they are not called! :( D'oh, will provide a fix later, but this will require some rework in generic HDA code.
