### ISSUE TITLE
[JSL][BUG][s0ix]System can't enter s0ix.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2197]
**Describe the bug**
System can't enter s0ix and only can enter s2idle and s3.

**To Reproduce**
S0ix:
1. Ensure suspend mode is S2idle, echo s2idle > /sys/power/mem_sleep 
2. cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec
3. sudo rtcwake -m mem -s 10
4. cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec  to check the residency time is increasing or not 
```
root@sh-Jasper-Lake-HDA:/home/ubuntu# cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec
0
root@sh-Jasper-Lake-HDA:/home/ubuntu# cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec
0

```
```
root@sh-Jasper-Lake-HDA:/sys/kernel/debug/pmc_core# cat package_cstate_show
Package C2 : 0
Package C3 : 0
Package C6 : 0
Package C7 : 0
Package C8 : 0
Package C9 : 0
Package C10 : 0
```
**Reproduction Rate**
10/10

**Actual result**
System can't enter s0ix.

**Expected result**
System should  enter s0ix normally.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:  140f27c
FW: https://github.com/thesofproject/sof/commits/master commit: a10b0ad2
Tplg: sof-hda-generic-4ch.tplg
Platform:JSL-RVP with ALC700 in HDA mode

[dmesg15.log](https://github.com/thesofproject/linux/files/4777946/dmesg15.log)
[sof_trace15.log](https://github.com/thesofproject/linux/files/4777947/sof_trace15.log)

**Comment by ClarexZhou** [comment]
Kernel team only get PC2. Kernel team is debugging on that

**Comment by Liviali155** [comment]
ES1 can enter S0ix after below settings with intel next 5.7:
BIOS: JasperLake_Label2194_00 , https://onebkc.intel.com/#/ingredientVersion/14011505469?executionConfig=JSL-P-20H1-REV02
OS: ubuntu 19.10 
BIOS setting:
Disable all the PCIe root ports
Disable SATA Devslp settings in Bios
OS settings:
powertop --auto-tune
echo Y > /sys/module/acpi/parameters/sleep_no_lps0
Ignore IsCLK and MODPHY from CPPM 2
 IsCLK PLL Shutdown Qualification Disable 
MPHY Core Power Gated Qualification Disable 

closed it
