### ISSUE TITLE
[bug][JSL]Warning "ASoC: error at snd_soc_dai_startup on intel-hdmi-hifi1: -16" shows in dmesg when boot up with DP connected.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2216]
**Describe the bug**
Warning "ASoC: error at snd_soc_dai_startup on intel-hdmi-hifi1: -16" shows in dmesg when boot up with DP connected. Issue can't effect function.

**To Reproduce**
scenario 1:
1.Boot up system with DP connected.
2.Check dmesg.

scenario 2:
1.Boot up system only with HDMI.
2.Open sound setting after system boot up successfully
3.Plug in DP .
4.Manually switch output source to DP .

scenario 3:
1.Boot up system.
2.cd sof-test/test-case
3.export TPLG=/lib/firmware/intel/sof-tplg/sof-hda-generic-4ch.tplg
2. Run "./multiple-pipeline-playback.sh -c 7 -r -l 5". (https://github.com/thesofproject/sof-test/blob/master/test-case/multiple-pipeline-playback.sh)

**Reproduce rate**
5/5

**Expected result**
No error should disaplay when boot up with DP connected.

**Actual result**
Warning "ASoC: error at snd_soc_dai_startup on intel-hdmi-hifi1: -16" shows in dmesg when connected with DP connected.
```
[    8.679478] snd_hda_codec_hdmi ehdaudio0D2: hdmi_pin_hbr_setup: NID=0x6, pinctl=0x40
[    8.679609] snd_hda_codec_hdmi ehdaudio0D2: hda_codec_setup_stream: NID=0x5, stream=0x2, channel=0, format=0x31
[    8.679995] snd_hda_codec_hdmi ehdaudio0D2: ASoC: error at snd_soc_dai_startup on intel-hdmi-hifi1: -16
[    8.680002] snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open DAI intel-hdmi-hifi1: -16
[    8.680008]  iDisp1: ASoC: BE open failed -16
[    8.680012]  HDMI1: ASoC: failed to start some BEs -16
[    8.680094] sof-audio-pci 0000:00:1f.3: pcm: free stream 5 dir 0
[    8.680102] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[    8.680220] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[    8.680246] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.680369] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[    8.680379] snd_hda_codec_hdmi ehdaudio0D2: hda_codec_cleanup_stream: NID=0x3
[    8.680435] snd_hda_codec_hdmi ehdaudio0D2: HDMI: hinfo 000000009143f9fe not registered
```

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit: 1b2f2606 +PR https://github.com/thesofproject/linux/pull/2208
FW: https://github.com/thesofproject/sof/commits/master commit: 3d8a0ac
Tplg: sof-hda-generic-4ch.tplg
Platform:JSL-RVP with ALC700 in HDA mode

[dmesg19.log](https://github.com/thesofproject/linux/files/4803880/dmesg19.log)
[sof_trace19.log](https://github.com/thesofproject/linux/files/4803881/sof_trace19.log)

**Comment by sinahuang** [comment]
Issue still can be seen with PR https://github.com/thesofproject/linux/pull/2223.
[dmesg_all.log](https://github.com/thesofproject/linux/files/4816812/dmesg_all.log)

**Comment by kv2019i** [comment]
I've rootcaused the problem now. Initial test on JSL RVP with two monitors connects is successful. I'll provide a proper fix patch next week.

**Comment by Liviali155** [comment]
Error not seen with PR  #2240
