### ISSUE TITLE
[BUG][TGL]Terminal shows "cannot load mixer controls: Device or resource busy" when open alsamixer when pm runtime in suspended status.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2221]
**Describe the bug**
Terminal shows "cannot load mixer controls: Device or resource busy" when open alsamixer when pm runtime in suspended status. 

Note: Issue cannot be reproduced when aplay with speaker(aplay0,2)

**To Reproduce**
1. Boot up system.
2. Wait pm runtime in suspended status
```
$cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
```
3. Run command "alsamixer" to open alsamixer.

**Reproduction Rate**
10/10

**Expected behavior**
Terminal shows "cannot load mixer controls: Device or resource busy" when open alsamixer when pm runtime in suspended status.

**Environment**
**Kernel:**
https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a   
revert  d4b41f8bb
revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d 
**FW:**
https://github.com/thesofproject/sof/tree/releases/tgl/v7.0-rc2 commit: b36dabe4
revert e35e91de652e06183c51ecc9814e7165f780c116
+PR 3069
**TPLG:** same as fw path sof-tgl-sdw-max98373-rt5682-4ch.tplg rename to sof-tgl-sdw-max98373-rt5682.tplg
platform: TGL chrome book with codec 98373 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/4811850/dmesg.log)
[all-logger.log](https://github.com/thesofproject/linux/files/4811852/all-logger.log)

**Comment by YvonneYang2** [comment]
Error still seen with kernel + tgl-006-stable branch.

**Comment by RanderWang** [comment]
it is caused by inaccessible register in max98373.  I am debugging driver

**Comment by YvonneYang2** [comment]
Verified #2226 , issue can be fixed.

**Comment by bardliao** [comment]
@YvonneYang2 Could you list which mixer will you get "cannot load mixer controls: Device or resource busy" error? I think if should not be an issue if it is an volatile mixer.

**Comment by YvonneYang2** [comment]
@bardliao 
Diff and verified the amixer info of error reproduced and error not reproduced. The value of name='Left/Right Spk Switch' will cause the issue. With value off, issue can be reproduced, while with on, error not seen.

When error seen, cannot get these values of below numid:
```
numid=83,iface=MIXER,name='Left ADC PVDD'
numid=84,iface=MIXER,name='Left ADC TEMP'
numid=95,iface=MIXER,name='Left BDE Active Level'
numid=71,iface=MIXER,name='Left FS Max Volume'
numid=72,iface=MIXER,name='Left Output Voltage'
numid=70,iface=MIXER,name='Left Speaker Volume'
numid=27,iface=MIXER,name='Right ADC PVDD'
numid=28,iface=MIXER,name='Right ADC TEMP'
numid=39,iface=MIXER,name='Right BDE Active Level'
numid=15,iface=MIXER,name='Right FS Max Volume'
numid=16,iface=MIXER,name='Right Output Voltage'
numid=14,iface=MIXER,name='Right Speaker Volume'
```
[error_seen.txt](https://github.com/thesofproject/linux/files/4841729/error_seen.txt)
[error_not_seen.txt](https://github.com/thesofproject/linux/files/4841730/error_not_seen.txt)
