### ISSUE TITLE
[BUG][TGL]Get blob test failed when using sof-ctl tools

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2222]
**Describe the bug**
When run command " ./sof-ctl -Dhw:0 -c name= 'SMART_AMP3.0 Smart_amp Model' -br -s dsmparam_.txt -t 1 "
It shows "sof-ctl: control.c:302: snd_ctl_elem_info: Assertion `ctl && info && (info->id.name[0] || info->id.numid)' failed."
@keyonjie  Could you have a look? Thanks.

**To Reproduce**
1. System boot up.
2. put dsmparam_.txt and sof-ctl in ./ folder.
[dsmparam_.txt](https://github.com/thesofproject/linux/files/4812909/dsmparam_.txt)
3. Run command "./sof-ctl -Dhw:0 -c name= 'SMART_AMP3.0 Smart_amp Model' -br -s dsmparam_.txt -t 1 " 

Console shows:
```
~$ amixer contents | grep "SMART_AMP"
numid=186,iface=MIXER,name='SMART_AMP3.0 Smart_amp Config'
numid=187,iface=MIXER,name='SMART_AMP3.0 Smart_amp Model'
~$ sof-ctl -Dhw:0 -c name= 'SMART_AMP3.0 Smart_amp Model' -br -s dsmparam_.txt -t 1
sof-ctl: control.c:302: snd_ctl_elem_info: Assertion `ctl && info && (info->id.name[0] || info->id.numid)' failed.
Aborted (core dumped)

```
**Reproduction Rate**
10/10

**Expected behavior**
sof-ctl can read it successfully.

**Environment**
https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a   
revert  d4b41f8bb
revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d 
**FW:**
https://github.com/thesofproject/sof/tree/releases/tgl/v7.0-rc2 commit: b36dabe4
revert e35e91de652e06183c51ecc9814e7165f780c116
+PR 3069
**TPLG:** same as fw path sof-tgl-sdw-max98373-rt5682-4ch.tplg rename to sof-tgl-sdw-max98373-rt5682.tplg
platform: TGL chrome book with codec 98373 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/4812918/dmesg.log)
[all-logger.log](https://github.com/thesofproject/linux/files/4812920/all-logger.log)

**Comment by sinahuang** [comment]
Issue also can be seen on TGL chrome book with codec 98373 in I2S mode.

**Comment by YvonneYang2** [comment]
Verified #2226 , error can still be reproduced.

**Comment by RanderWang** [comment]
After tracing ALSA lib, I finally found root reason. no space after "name="

````diff
- " ./sof-ctl -Dhw:0 -c name= 'SMART_AMP3.0 Smart_amp Model' -br -s dsmparam_.txt -t 1 "
+ " ./sof-ctl -Dhw:0 -c name='SMART_AMP3.0 Smart_amp Model' -br -s dsmparam_.txt -t 1 "
````

**Comment by YvonneYang2** [comment]
Checked it with "./sof-ctl -Dhw:0 -c name='SMART_AMP3.0 Smart_amp Model' -br -s dsmparam_.txt -t 1" 
Issue cannot be reproduced. 

Close it.
