### ISSUE TITLE
[TGL] [SDW]: RT5682 Jack-detection fails with TRS headset (headphones without MIC)

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#2230]
RT5682-SDW codec fails to detect TRS jack(without mic) interrupts, while TRRS Jack (with mic) detects fine.
evtest also fails to detect the stereo headphones(without mic)
 
NOTE: On I2S recipe, this issue is not observed

Hardware: TGL Reference Board SKU3/SKU5
Recipe Used: 
Kernel & Firmware based on SoF_v0.6
For reference https://github.com/naveen-manohar/linux/commits/ww255_sdw_dsm_rtd3

Steps to reproduce:
> Insert stereo headphones (not a headset w/ mic)
> Boot system
> Click on system tray, then headphone icon on volume slider panel. Observe which devices have headset audio icon.

Expected Results:
> The headphone icon should be present in volume slider panel after hot-plug/cold-boot/warm-boot

Actual Results:
> The headphone icon wasn't present in volume slider panel after hot-plug/cold-boot/warm-boot

**Comment by naveen-manohar** [comment]
Working with Albert from Realtek and have shared the dump with TRS & TRRS Jack
[lineout_regdump_not-working.log](https://github.com/thesofproject/linux/files/4825525/lineout_regdump_not-working.log)
[headphone_jack-working.log](https://github.com/thesofproject/linux/files/4825526/headphone_jack-working.log)

**Comment by plbossart** [comment]
There was a patch shared yesterday on alsa-devel on this: https://mailman.alsa-project.org/pipermail/alsa-devel/2020-June/169522.html, is this related?

**Comment by naveen-manohar** [comment]
Thanks for the input pierre, I checked the patch, issue mentions about pop noise during OMTP jack-detection..
Here i'm observing issue with jack detection itself - with TRS jack-type detection: Fails.., TRRS detection works fine.

**Comment by naveen-manohar** [comment]
Working with codec vendor to understand the register content difference observed between TRS(Jack_dettect fail) & TRRS(Jack detect pass) scenarios. Also trying to understand the impedance requirement between the Jack-Tip & Sleeve.
LOG:
[jack_TRRS_detect-PASS_Debug_reg-rw.log](https://github.com/thesofproject/linux/files/4845098/jack_TRRS_detect-PASS_Debug_reg-rw.log)
[jack_TRS_detect-FAIL_Debug_reg-rw.log](https://github.com/thesofproject/linux/files/4845100/jack_TRS_detect-FAIL_Debug_reg-rw.log)

**Comment by naveen-manohar** [comment]
With TRS Jack, observe that jack has detected and codec can recognized type is TRS
[  114.395508] rt5682 sdw:0:25d:5682:0: jack_type = 1

**But evtest isn’t detecting this event. And hence even UI fails too**

**Comment by RanderWang** [comment]
@naveen-manohar  I tested sdw5682 on ubuntu with the reference TGL device. evtest works. please follow these command to check jack event in kernel.

````
#echo 1 > /sys/kernel/debug/tracing/events/asoc/snd_soc_jack_irq/enable
#echo 1 > /sys/kernel/debug/tracing/events/asoc/snd_soc_jack_report/enable
#echo 1 > /sys/kernel/debug/tracing/events/asoc/snd_soc_jack_notify/enable

#cat /sys/kernel/debug/tracing/trace // do it after plug & unplug operations
     kworker/6:3-2393  [006] ....  1797.904957: snd_soc_jack_notify: jack=Headset Jack 1
     kworker/6:3-2393  [006] ....  1800.735287: snd_soc_jack_report: jack=Headset Jack 0/7803
     kworker/6:3-2393  [006] ....  1800.735290: snd_soc_jack_notify: jack=Headset Jack 0
     kworker/6:3-2393  [006] ....  1836.516951: snd_soc_jack_report: jack=Headset Jack 1/7803
     kworker/6:3-2393  [006] ....  1836.516955: snd_soc_jack_notify: jack=Headset Jack 1

Testing ... (interrupt to exit)
Event: time 1581471087.439324, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 1
Event: time 1581471087.439324, -------------- SYN_REPORT ------------
Event: time 1581471091.826577, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 0
Event: time 1581471091.826577, -------------- SYN_REPORT ------------

````

**Comment by Liviali155** [comment]
On TGL chromebook with codec 98373 in SDW mode test 

> @naveen-manohar I tested sdw5682 on ubuntu with the reference TGL device. evtest works. please follow these command to check jack event in kernel.
> 
> ```
> #echo 1 > /sys/kernel/debug/tracing/events/asoc/snd_soc_jack_irq/enable
> #echo 1 > /sys/kernel/debug/tracing/events/asoc/snd_soc_jack_report/enable
> #echo 1 > /sys/kernel/debug/tracing/events/asoc/snd_soc_jack_notify/enable
> 
> #cat /sys/kernel/debug/tracing/trace // do it after plug & unplug operations
>      kworker/6:3-2393  [006] ....  1797.904957: snd_soc_jack_notify: jack=Headset Jack 1
>      kworker/6:3-2393  [006] ....  1800.735287: snd_soc_jack_report: jack=Headset Jack 0/7803
>      kworker/6:3-2393  [006] ....  1800.735290: snd_soc_jack_notify: jack=Headset Jack 0
>      kworker/6:3-2393  [006] ....  1836.516951: snd_soc_jack_report: jack=Headset Jack 1/7803
>      kworker/6:3-2393  [006] ....  1836.516955: snd_soc_jack_notify: jack=Headset Jack 1
> 
> Testing ... (interrupt to exit)
> Event: time 1581471087.439324, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 1
> Event: time 1581471087.439324, -------------- SYN_REPORT ------------
> Event: time 1581471091.826577, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 0
> Event: time 1581471091.826577, -------------- SYN_REPORT ------------
> ```

Use  this  method  test on  TGL chromebook with codec 98373 in SDW mode with ubuntu OS, evtest works ok as below:

```
Testing ... (interrupt to exit)
Event: time 1593481633.584947, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 0
Event: time 1593481633.584947, -------------- SYN_REPORT ------------
Event: time 1593481643.177981, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 1
Event: time 1593481643.177981, -------------- SYN_REPORT ------------

```

**Comment by naveen-manohar** [comment]
@Liviali155, @RanderWang  Please help confirm if the above observation is with TRS headset.
At my end, TRRS detects & passes EVTEST without any issue. Issue is with TRS headset failing evtest.

More details on TRS & TRRS type jack can be found here - https://components101.com/connectors/35mm-audio-jack

**Comment by Liviali155** [comment]
> @Liviali155, @RanderWang Please help confirm if the above observation is with TRS headset.
> At my end, TRRS detects & passes EVTEST without any issue. Issue is with TRS headset failing evtest.
> 
> More details on TRS & TRRS type jack can be found here - https://components101.com/connectors/35mm-audio-jack

I used the TRS headset as below without microphone

<img width="194" alt="Capture" src="https://user-images.githubusercontent.com/56707932/87002687-b5842380-c1ec-11ea-9dfd-dc4c3f022a5f.PNG">

**Comment by naveen-manohar** [comment]
ok thanks for confirming.. yes it is TRS you are using..

I tried enabling dynamic_debug and followed the tracing methods as mentioned but at my end, Codec reports jack_type=1, seems like codec_driver found irq but dint invoke jack_report..

```
> cat /sys/kernel/debug/tracing/trace
> # tracer: nop
> #
> # entries-in-buffer/entries-written: 6/6   #P:8
> #
> #                              _-----=> irqs-off
> #                             / _----=> need-resched
> #                            | / _---=> hardirq/softirq
> #                            || / _--=> preempt-depth
> #                            ||| /     delay
> #           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
> #              | |       |   ||||       |         |
>            udevd-1950  [004] ....     3.356122: ipu_pci_probe: B|1950|TMWK
>            udevd-1950  [006] ....     3.364908: ipu_pci_probe: E|0|TMWK
>            udevd-1950  [006] ....     3.389098: isys_probe: B|1950|TMWK
>            udevd-1950  [006] ....     3.401686: isys_probe: E|0|TMWK
>    kworker/u16:1-59    [006] ....     3.428072: ipu_psys_probe: B|59|TMWK
>    kworker/u16:1-59    [006] ....     3.430913: ipu_psys_probe: E|0|TMWK
>  

```
Shall apply some prints, recheck & update whats happening..

**Comment by naveen-manohar** [comment]
Based on all the experiments, Conclude that this isn't a hardware or codec related issue.

Chrome Kernel missed config that was impacting TRS Jack-Type detection, have fixed this wrt Kernel & UCM and submitted patch to Customer.. 

Closing this issue.. Thanks all for the debug inputs & support.
