### ISSUE TITLE
kernel oops due to failed debugfs allocation + IPC message

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2236]
Found this error with module load/unload tests, something looking fishy in our error flows....

[dmesg_debugfs.log](https://github.com/thesofproject/linux/files/4838800/dmesg_debugfs.log)

**Comment by ranj063** [comment]
@plbossart which platform was this on? I think I know whats causing this but which platform can I test it on?

**Comment by plbossart** [comment]
@ranj063 I saw it on cherrytrail, a small headless device that works much better than the other baytrail devices. You should be able to see this on any platform since all I did was modprobe snd-sof-acpi; sleep 15; rmmod snd-sof-acpi;

**Comment by ranj063** [comment]
@plbossart I think https://github.com/thesofproject/linux/pull/2237 should fix the problem. I dont have a CHT device but I'll test on my CML.

**Comment by plbossart** [comment]
can't reproduce this, closing
