### ISSUE TITLE
[BUG][JSL][DP-MST]Cannot playback to 2 DP displays connected through a DP-MST hub simultaneously

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2239]
**Describe the bug**
Both the monitors connected show display but can not  play audio at the same time when check 2 DP playback in MST mode

**To Reproduce**

1.Two monitors are connected via one DP hub using DP-DP cables
2."sudo reboot" to reboot sysytem
3."amixer contents |less" to check jack status(0,3 and 0,4 are on)
4.aplay -Dhw:0,4 -r 48000 -c 2 -fs16_le wav/2.wav wav/2.wav wav/2.wav -vv -i
5.open another terminal to "aplay -Dhw:0,3 -r 48000 -c 2 -fs16_le wav/2.wav wav/2.wav wav/2.wav -vv -i"

<img width="407" alt="Capture" src="https://user-images.githubusercontent.com/56707932/85991994-d9927880-ba26-11ea-9d7f-378cbe30b028.PNG">

**Reproduce rate**
5/5

**Expected result**
 the monitors connected can play video and has sound output

**Actual result**

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit: 1b2f2606 +PR https://github.com/thesofproject/linux/pull/2208 +PR https://github.com/thesofproject/linux/pull/2184
FW: https://github.com/thesofproject/sof/tree/releases/jsl/v3.0-rc1(commit: 3d8a0ac8)
+PR #https://github.com/thesofproject/sof/pull/3053 
+PR # https://github.com/thesofproject/sof/pull/2987
Tplg: sof-hda-generic-4ch.tplg
Platform:JSL-RVP with ALC700 in HDA mode

[dmesg_0629.log](https://github.com/thesofproject/linux/files/4844777/dmesg_0629.log)
[sof-logger_0629.log](https://github.com/thesofproject/linux/files/4844781/sof-logger_0629.log)

**Comment by Liviali155** [comment]
When check check DP playback in dasiy chain mode also has this issue, both the display can not play audio at the same time

**Comment by Liviali155** [comment]
Reboot then connected two monitors  via one DP hub using DP-DP cables,also has this issue when playback via 2 DP displays
[dmesg062900.log](https://github.com/thesofproject/linux/files/4848864/dmesg062900.log)

**Comment by Liviali155** [comment]
After applied #2240 
Error not seen when check DP playback in dasiy chain mode and 2 DP playback in MST mode

**Comment by kv2019i** [comment]
Thanks @Liviali155 ! So it seems this is fixed by #2240 as well.

**Comment by ClarexZhou** [comment]
close for PR #2240 is merged.
