### ISSUE TITLE
[BUG][sof-tgl-max98373-rt5682]No 'Headphone Jack' or 'Headset Jack' in amixer contents. 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2242]
**Describe the bug**
No 'Headphone Jack' or 'Headset Jack' in amixer contents. 
 
**To Reproduce**
1. Boot up system with headset connected.
2. Run with command "amixer contents" 
3.  Check if there is 'Headphone Jack" or "Headset Jack"

**Reproduce rate**
5/5

**Expected result**
There should be 'Headphone Jack" and "Headset Jack"

**Actual result**
No 'Headphone Jack' or 'Headset Jack' in amixer contents. 

**Environment**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 for DP fix 
+ PR#2184 for wov S0i2 
+ [0001-hack-hack-98373-for-feedback-data-validation.patch.txt](https://github.com/thesofproject/sof/files/4812034/0001-hack-hack-98373-for-feedback-data-validation.patch.txt)
For TGL chrome book:
+ revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a   
+ revert  d4b41f8bb
+ revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d  

FW:
https://github.com/thesofproject/sof/tree/releases/tgl/v7.0-rc5 commit: https://github.com/thesofproject/sof/commit/1dd07a8aa27d22df56a43635975f4e151cbb4dbf

TPLG:sof-tgl-max98373-rt5682.tplg
Platform:Chromebook with codec 98373 in I2S mode.

[sof-trace.log](https://github.com/thesofproject/linux/files/4849766/sof-trace.log)
[dmesg.log](https://github.com/thesofproject/linux/files/4849767/dmesg.log)
[amixer.txt](https://github.com/thesofproject/linux/files/4849768/amixer.txt)

**Comment by ClarexZhou** [comment]
@naveen-manohar  could you please help to check on this?

**Comment by Liviali155** [comment]
TGL Volteer I2S with codec 98357 also has this issue

**Comment by naveen-manohar** [comment]
@sathya-nujella : As i'm having only sdw daughter card, please help check this.

**Comment by sathya-nujella** [comment]
> @sathya-nujella : As i'm having only sdw daughter card, please help check this.

Hi @keqiaozhang 
Can you help cross check on 98373 DB?  Now, you have latest CB supporting it.. please suggest if you can not confirm.

**Comment by naveen-manohar** [comment]
I can observe the following with sdw-rt5682-max98373 daughtercard

> localhost ~ # amixer -c0 controls | grep "Headphone Jack"
> numid=120,iface=CARD,name='Headphone Jack'
> localhost ~ # aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: sofsoundwire [sof-soundwire], device 0: Headphone (*) []
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
>

**Comment by keqiaozhang** [comment]
@naveen-manohar, we are using the latest CB image which provided by Usha. But this issue still can be seen.
@RanderWang, please help to check the machine driver side first.

**Comment by RanderWang** [comment]
I don't find any wrong in machine driver. I need to debug the device.

**Comment by plbossart** [comment]
@naveen-manohar @RanderWang no update since 6 months, can we close this?

**Comment by naveen-manohar** [comment]
RT5682 only requires the following mixer controls & its reflecting in I2S TGL DUTs
```
		cset "name='Headphone Jack Switch' on"
                cset "name='='Headset Mic Switch' on"
                cset "name='HPOL Playback Switch' 1"
                cset "name='HPOR Playback Switch' 1"
                cset "name='Stereo1 DAC MIXL DAC L1 Switch' 1"
		cset "name='Stereo1 DAC MIXR DAC R1 Switch' 1"
```
May be the script used by the validator needs to be updated, I believe we can close this issue.
