### ISSUE TITLE
[BUG][TGL][max98357-I2S]Continuous buzzing  output from speaker after pause aplay (speaker(0,0)) about 40s

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2249]
***Describe the bug***
Continuous buzzing  output from speaker after pause aplay (speaker(0,0)) about 40s
Sometimes not need  wait need 40s after pause

***To Reproduce***
1."sudo reboot" to reboot system
2. aplay -Dhw:0,0 -f s32_le -c 2 -r 48000 wav/48California_Dreaming.wav -vv -i
3.press space to pause
4.wait about 40s
```
ubuntu@ubuntu-Volteer:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofrt5682 [sof-rt5682], device 0: max357a-spk (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 2: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 3: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 4: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 5: HDMI4 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

***Reproduction Rate***
10/10

***Expected behavior***
No noise output from speaker after pause aplay

***Impact***
Continuous buzzing  output from speaker after pause aplay (via speaker(0,0)) about 40s

[dmesg0703.log](https://github.com/thesofproject/linux/files/4868018/dmesg0703.log)
[sof-logger0703.log](https://github.com/thesofproject/linux/files/4868019/sof-logger0703.log)
[noise.zip](https://github.com/thesofproject/linux/files/4868021/noise.zip)

**Comment by ClarexZhou** [comment]
@keyonjie  could you please help to check this first?

Error not seen on max98373 in I2S mode.

**Comment by ClarexZhou** [comment]
@sathya-nujella , could you please help to check on this?

**Comment by sathya-nujella** [comment]
Hi @ClarexZhou 
In your tests, how much is the value for this "max98357a->sdmode"
https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/max98357a.c#L36

**Comment by sathya-nujella** [comment]
> Hi @ClarexZhou
> In your tests, how much is the value for this "max98357a->sdmode"
> https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/max98357a.c#L36

I checked in coreboot code, it is sending 5milli second delay..
https://github.com/coreboot/coreboot/blob/master/src/mainboard/google/volteer/variants/volteer/overridetree.cb#L117
register "sdmode_delay" = "5"

please help check in your test setup and confirm.

**Comment by Liviali155** [comment]
Issue still can be reproduced with  https://github.com/thesofproject/sof/commits/releases/tgl/v7.0-rc7 ,commit: 33cfa90e on  TGL  chromebook in  I2S  mode with codec 98357

**Comment by ClarexZhou** [comment]
@sathya-nujella  Error still seen with below changes.
```

diff --git a/sound/soc/codecs/max98357a.c b/sound/soc/codecs/max98357a.c
index a8bd793..a833f0c 100644
--- a/sound/soc/codecs/max98357a.c
+++ b/sound/soc/codecs/max98357a.c
@@ -33,13 +33,15 @@ static int max98357a_sdmode_event(struct snd_soc_dapm_widget *w,
        struct max98357a_priv *max98357a =
                snd_soc_component_get_drvdata(component);

+       dev_err(NULL, "sdmode %d" ,  max98357a->sdmode);
+
        if (!max98357a->sdmode)
                return 0;

        if (event & SND_SOC_DAPM_POST_PMU) {
                msleep(max98357a->sdmode_delay);
-               gpiod_set_value(max98357a->sdmode, 1);
-               dev_dbg(component->dev, "set sdmode to 1");
+               gpiod_set_value(max98357a->sdmode, 5);
+               dev_dbg(component->dev, "set sdmode to 5");
        } else if (event & SND_SOC_DAPM_PRE_PMD) {
                gpiod_set_value(max98357a->sdmode, 0);
                dev_dbg(component->dev, "set sdmode to 0");

```
[dmesg.txt](https://github.com/thesofproject/linux/files/4894354/dmesg.txt)
[sof_trace.txt](https://github.com/thesofproject/linux/files/4894355/sof_trace.txt)

**Comment by Liviali155** [comment]
Error still can be reproduced with https://github.com/thesofproject/sof/tree/releases/tgl/v7.0-rc8 ,commit: 2057409 on TGL chrome laptop I2S with codec 98357

**Comment by ClarexZhou** [comment]
Error still seen with below changes.
```
diff --git a/sound/soc/codecs/max98357a.c b/sound/soc/codecs/max98357a.c
index a8bd793a7867..eae454ea3a12 100644
--- a/sound/soc/codecs/max98357a.c
+++ b/sound/soc/codecs/max98357a.c
@@ -115,6 +115,8 @@ static int max98357a_platform_probe(struct platform_device *pdev)
                        "default: no delay\n");
        }

+       max98357a->sdmode_delay = 5;
+
        dev_set_drvdata(&pdev->dev, max98357a);

        return devm_snd_soc_register_component(&pdev->dev,

```

**Comment by plbossart** [comment]
@mengdonglin @keyonjie can we close this?

**Comment by plbossart** [comment]
no update since July 2020, closing.
