### ISSUE TITLE
[bug][ucm2]UCM2 can not work on HDA and SDW

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2250]
**Describe the bug** 
UCM2 can not work on HDA and SDW,display Multichannel
Tried on TGL-Laptop  with aboard codec ALC3204  in HDA mode, TGL HDA RVP,CML-U with aboard codec  ALC711 -RT1308, RT715  in SDW mode,all can not work

**To Reproduce**
1.sudo reboot
2.open sound setting
3.check Output Device and Input Device

**Reproduction Rate**
10/10

**Expected behavior**
UCM2 can work

**Actual result**
UCM2 can not work on HDA and SDW

**Environment**
TGL-Laptop  with aboard codec ALC3204  in HDA mode
UCM2:https://github.com/alsa-project/alsa-ucm-conf/commits/master(ffe0cab5)
alsa-lib: version 1.2.3.2

[amixercontents0703.txt](https://github.com/thesofproject/linux/files/4868666/amixercontents0703.txt)
[dmesg0703.log](https://github.com/thesofproject/linux/files/4868667/dmesg0703.log)
[sof-logger_0703.log](https://github.com/thesofproject/linux/files/4868668/sof-logger_0703.log)

**Comment by libinyang** [comment]
This is a bug in alsa-lib. The latest UCM support Syntax v3 and it uses "$var". The root cause is the alsa-lib initialization sequence doesn't support redefine the variable well. I have reported a bug in alsa-lib. Please see the details in https://github.com/alsa-project/alsa-lib/issues/67.

**Comment by Liviali155** [comment]
After update alsalib ,ucm2 can work on HDA and ADW
