### ISSUE TITLE
[Bug][TGL]Pop noise on I2S max98373 speaker when doing pause/resume test 

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#2255]
**Describe the bug**
Slight pop noise can be observed when do pause during playing sine wav via speaker

**To Reproduce**
1. aplay -Dhw:0,0 -f s16_le -c 2 -r 48000 sine_48k_16bit_10s_stereo_l5_r2.wav -vv -i
2. press SPACE to pause resume

**Reproduction Rate**
3/3

**Expected behavior**
no pop noise after resuming playback

**Impact**
slight pop noise
More info:
Check captured audio via DSM
![image](https://user-images.githubusercontent.com/49641224/86866011-c48ea700-c102-11ea-81f6-6d2973763ebc.png)
[dmesg.txt](https://github.com/thesofproject/linux/files/4888029/dmesg.txt)
[sof_trace.txt](https://github.com/thesofproject/linux/files/4888030/sof_trace.txt)
[capture.zip](https://github.com/thesofproject/linux/files/4888031/capture.zip)

**Environment**
FW: on https://github.com/thesofproject/sof/tree/tgl-007-drop-stable.
TPLG: same with FW branch, sof-tgl-max98373-rt5682.tplg
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 + PR#2240 for DP fix 
+ PR#2184 for wov S0i2 
+PR#2238 for max98373-sdw jack switch

**Comment by RanderWang** [comment]
update status:  I can reproduce this issue. no pop noise is generated with only stream of zero data. And I also check it with SSP loop back, no garbage data is captured. I don't think it is caused by FW for above evidence

**Comment by RanderWang** [comment]
if we test start-stop pattern,  stream of zero data also produce garbage data at beginning & end.  The difference of start-stop pattern and pause-release pattern is that SSP clk is stopped in start-stop case.

**Comment by RanderWang** [comment]
I enabled SSP loop back in this case and disable DSM feedback input. The loop back data showed nothing wrong. So the data sent by SSP was correct. It is caused by 98373 only.  The pop noise is very slight and user can't notice it in daily usage.
