### ISSUE TITLE
[BUG][TGL]"runtime_status" is always active if aplay&arecord stop at the same time when check dsm

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2267]
**Describe the bug**
"runtime_status" is always active if aplay&arecord stop at the same time when check dsm
amixer cget numid=122&amixer cget numid=123,the value is on 
Reboot can  not recovery

**To Reproduce**
1."sudo reboot" to reboot
2.aplay -Dhw:0,2 -f s32_le -c 2 -r 48000 sine_48k_32bit_10s_stereo_l5_r2.wav -d 5 & arecord -Dhw:0,3 -f s32_le -c 4 -r 48000 capture.wav -d 5     (the time -d of aplay &arecord is the same)
3. after aplay &arecord stoped to check runtime_status using 'cat "/sys/bus/pci/devices/0000:00:1f.3/power/runtime_status"'

```
ubuntu@Volteer-rt5682-max98373-i2s:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 0: Headphone (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 2: smart373-spk (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 6: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 7: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 8: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 9: HDMI4 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
```
ubuntu@Volteer-rt5682-max98373-i2s:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 1: Headset mic (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 3: echo (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 4: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 5: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Reproduction Rate**
5/5

**Expected behavior**
]"runtime_status" can suspend after dsm stop

**Impact**
"runtime_status" is always active if aplay&arecord stop at the same time when check dsm

**Environment**
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel:Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 for DP fix 
+PR#2238 for max98373-sdw jack switch
+ https://github.com/mrajwa/linux/commit/5acaef7ee24d1fdfd368294b5a65a79518484155
+ https://github.com/mrajwa/linux/commit/fa927384c558ebecc07e5b35660569d323ef6e3c
+ https://github.com/mrajwa/linux/commit/34b60f83d781b1797823e462a2228f43b00a2dc5
For volteer:
+ codec hack commit to verify this captured data.

https://github.com/thesofproject/sof/commits/releases/tgl/v7.0-rc9,commit: be6c3479
 
Name of the topology file
Topology: rename sof-tgl-sdw-max98373-rt5682-4ch .tplg to  sof-tgl-sdw-max98373-rt5682.tplg
Name of the platform(s) on which the bug is observed.
Platform: TGL chromebook  with codec 98373 in SDW mode

[dmesg0710.log](https://github.com/thesofproject/linux/files/4902253/dmesg0710.log)
[sof-logger_0710.log](https://github.com/thesofproject/linux/files/4902254/sof-logger_0710.log)

**Comment by Liviali155** [comment]
@RanderWang please help to check

**Comment by ClarexZhou** [comment]
Error seen on sdw-5682-max98373,  error not seen on i2s-5682-max98373

**Comment by Liviali155** [comment]
Error also seen on  sdw-5682-max98373 when do module reload
1."sudo reboot" to reboot
2.cd sof-test
3.cd test-case
4.export TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-sdw-max98373-rt5682.tplg
5.  ./check-kmod-load-unload.sh
[sof-logger0716.log](https://github.com/thesofproject/linux/files/4929564/sof-logger0716.log)

<img width="684" alt="Capture" src="https://user-images.githubusercontent.com/56707932/87632370-d825b780-c76b-11ea-8b91-362a30be453b.PNG">

reboot can not recovery
https://github.com/thesofproject/sof/commits/releases/tgl/v7.0-rc10 ,commit: fb801c8e5e3090406955d82e06c20fcdbfd302b4
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 for DP fix 
+PR#2238 for max98373-sdw jack switch
+ mrajwa/linux@5acaef7
+ mrajwa/linux@fa92738
+ mrajwa/linux@34b60f8
For volteer:
+ codec hack commit to verify this captured data.

**Comment by mengdonglin** [comment]
This seems to be Max98373 codec driver issue in SDW mode. @naveen-manohar can you please check?
