### ISSUE TITLE
[BUG] [TGL] Audio routes to onboard 3.5mm jack instead of HDMI after suspend/resume

### ISSUE THREAD

**Issue by askmish** [thesofproject/linux#2272]
**Describe the bug**
 Audio routes to onboard 3.5mm jack instead of HDMI after suspend/resume

**To Reproduce**
1. Open browser and play some music on HDMI monitor speakers
2. Suspend via gui controls/commandline
3. Resume by pressing key in USB keyboard/or any wake event
4. Audio will now route to onboard 3.5mm jack, instead of previously selected HDMI speakers

**Reproduction Rate**
How often does the issue happen ?
10/10
Does the reproduction rate vary with any other configuration or user action, if so please describe and show the new reproduction rate.
No

**Expected behavior**
When playing audio via HDMI before suspend, audio should route to same HDMI target after resume.
It should not route to onboard 3.5mm jack plugged in.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
showstopper

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA} linux-5.4.39 kernel  + patches backported from 5.6/also tested with sof-dev 2839e03e573a
    * SOF: {SHA} Default sof packaged with Ubuntu 20.04 LTS OS linux-firmware version: 1.187.1
2) Name of the topology file
    * Topology: {FILE} sof-hda-generic-4ch.tplg  
3) Name of the platform(s) on which the bug is observed.
    * Platform: {PLATFORM} TGL-RVP

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Attached dmesg and pulseaudio logs tested with sof-dev 2839e03e573a
[hdmiaudio3.5mmrerouting.zip](https://github.com/thesofproject/sof/files/4902472/hdmiaudio3.5mmrerouting.zip)

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

**Comment by libinyang** [comment]
@askmish I don't have TGL to test now. But I tested it on CML platform and it works well now. As Pierre mentioned, we don't think this is an SOF issue. It's more like a UCM/Pulseaudio issue. As pulseaudio & alsa-lib has merged some key patches to switch the sinks correctly. Could you please have a try on a updated pulseaudio, alsa-lib?
I'm working on the recipe:
- UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306) (maybe you can keep using your UCM)
- Alsa-lib: https://github.com/alsa-project/alsa-lib (commit a3ca480)
- Pulseaudio: https://gitlab.freedesktop.org/pulseaudio/pulseaudio (commit 47d8112)
- Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

**Comment by plbossart** [comment]
@askmish can you update your software and test? This has been stuck for 1.5 months.

**Comment by askmish** [comment]
Hi,
Sorry for late update. We tested the suggested stack on tgl but it did not resolve the issue.

**Comment by libinyang** [comment]
@askmish Thanks for update. I will try to find a TGL platform to reproduce this issue. But the settings of TGL and CML are the same. It's weird that CML works well but TGL doesn't. 

BTW: you are using the latest UCM from https://github.com/alsa-project/alsa-ucm-conf and you didn't manually select 3.5mm jack as output ever before, right? If you selected 3.5mm jack before, the jack will be the configured default sink, and its priority will be higher that HDMI.

**Comment by libinyang** [comment]
And if you manually select the HDMI as output after suspend/resume, the sound can also be out from HDMI, right?

**Comment by askmish** [comment]
@libinyang Yes, I tried with latest UCM as well as the UCM in the commit#3e897306.
If I'm playing audio via HDMI before, the audio should route to HDMI after suspend/resume.

**Comment by askmish** [comment]
In the sound settings UI, I've selected HDMI as output source. I didn't select 3.5mm jack.

**Comment by askmish** [comment]
We were able to solve this issue by upgrading pulseaudio to: 13.99.1 via apt install pulseaudio

**Comment by plbossart** [comment]
@askmish can we close this issue then?
