### ISSUE TITLE
Power management error on Up2

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#228]
Dmesg yells about an obscure PM issue with HDMI connected.

[    4.396798] sof-audio sof-audio: error: failed to enter PM idle -11

[dmesg.log](https://github.com/thesofproject/linux/files/2527493/dmesg.log)

**Comment by mengdonglin** [comment]
@DarrenxWang Can you reproduce this issue on UP2?

**Comment by markyang** [comment]
_@mengdonglin:_ this issue can be reproduced on UP2.
**dmesg:**
[    6.453999] sof-audio sof-audio: error: failed to enter PM idle -11
**Test env:**
sof master: 43da1696
sof tool: 4ac9248
kernel debug/v4.19-backport: 925637e3
tplg: sof-apl-pcm512x.tplg-4ac9248

[dmesg-apl.txt](https://github.com/thesofproject/linux/files/2537683/dmesg-apl.txt)

**Comment by plbossart** [comment]
@ranj063 The error still shows up with latest firmware, sof-dev on Up2 w/ HDMI, so something is still off with your PM patches?

**Comment by plbossart** [comment]
@ranj063 I don't see the error any longer with the latest sof-dev, firmware and topology, not sure if I did something wrong last week or if this was corrected.

**Comment by mengdonglin** [comment]
@markyang Can you help to check if this issue is still reproducible on your UP2? If not, please close it.

**Comment by markyang** [comment]
**Summary:**
  This issue cannot be reproduced on UP2 any more.

**Test env:**
sof master: 73475e3f
sof tool: 2cd668c
kernel sof-dev: 165b34de
tplg: sof-apl-pcm512x.tplg-2cd668c
