### ISSUE TITLE
BUG] [TGL v7.0-rc10] Wov lost historical data after wake up from s0ix with long wake up latency when using format s32_le 

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2283]
**Describe the bug**
 Wov lost data after wake up from s0i2x when using format s32_le
Error not seen if using format s16_le, ex:
arecord -Dhw:0,100 -M -N -f s16_le -r 16000 -c 2 --buffer-size=296000 ww.wav -vv -i

**To Reproduce**
1."sudo reboot" to reboot sysytem
2.open terminal1 to run " arecord -Dhw:0,100 -M -N -f s32_le -r 16000 -c 2 --buffer-size=296000 ww.wav -vv -i"
3.open terminal2 to run "sudo su ,echo freeze>/sys/power/state"
4.count "one,two,three......"
5.clap hands to trigger wov at five

**Reproduction Rate**
2/3

**Expected behavior**
Wov has no data lost after wake up from s0ix

**Impact**
It takes about 9s for system fully wake up and Wov recovery when count sixteen  Wov  data lost before sixteen
<img width="325" alt="Capture" src="https://user-images.githubusercontent.com/56707932/87738451-08269680-c810-11ea-9544-305ee6700c72.PNG">

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {https://github.com/thesofproject/linux/commits/tgl-007-cr-20200716}
    * SOF: {https://github.com/thesofproject/sof/commits/releases/tgl/v7.0-rc10 ,commit: fb801c8e5e3090406955d82e06c20fcdbfd302b4
 }
Chrome os
Topology: sof-tgl-max98357a-5682.tplg
Name of the platform(s) on which the bug is observed.
Platform: TGL chrome laptop with max98357a and 5682in i2s mode

[dmesg0717.log](https://github.com/thesofproject/linux/files/4935221/dmesg0717.log)

**Comment by Liviali155** [comment]
After set buffer-size as 128000 also has data lost
<img width="368" alt="Capture" src="https://user-images.githubusercontent.com/56707932/87738903-05787100-c811-11ea-904f-a98db68afe4f.PNG">
[dmesg_0717.log](https://github.com/thesofproject/linux/files/4935257/dmesg_0717.log)

**Comment by keyonjie** [comment]
This issue will disappear once the long resuming time issue is fixed from the Chrome system side, @sathya-nujella assign it to you for tracking it.

**Comment by sathya-nujella** [comment]
> This issue will disappear once the long resuming time issue is fixed from the Chrome system side, @sathya-nujella assign it to you for tracking it.

Hi @keyonjie 
With Google-5.4 kernel, we see resume time is high. Internally TCSS team shared new kernel.. without, resume time is reduced ..it seems around~600ms.  Jairaj is following up with them. Will update as soon as I hear on it.

**Comment by keyonjie** [comment]
Thanks @sathya-nujella , please let us know if we need update kernel or CB.

**Comment by sathya-nujella** [comment]
> Thanks @sathya-nujella , please let us know if we need update kernel or CB.

Hi @keyonjie 
Fix is in USB4/TCSS kernel patches. Those kernel patches are not yet in CPFE google tree. They are only available in internal tree.
Message from TCSS team: TCSS Fixes are not in upstream. so, to test from Chrome tree, we may need to wait for some more time.

**Comment by keyonjie** [comment]
> > Thanks @sathya-nujella , please let us know if we need update kernel or CB.
> 
> Hi @keyonjie
> Fix is in USB4/TCSS kernel patches. Those kernel patches are not yet in CPFE google tree. They are only available in internal tree.
> Message from TCSS team: TCSS Fixes are not in upstream. so, to test from Chrome tree, we may need to wait for some more time.

Thanks for the information, looks we need to work-around that with similar solution as 007 release for WW34 one.

**Comment by jairaj-arava** [comment]
Hi @keyonjie ,
As per the update from TCSS team, all the required patches are already merged in CPFE google tree (images from #13396 will the changes). There is only patch related to RTD3 & is yet to merged (https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2339936/1). 

Even with these patches, TCSS team is still observing ~600ms no_irq resume delay and there are debugging this issue.

**Comment by keyonjie** [comment]
@jairaj-arava thanks for the update, I think 600ms for no_irq resuming can be tolerated for the coming release.

**Comment by keyonjie** [comment]
@sathya-nujella @jairaj-arava as this is already fixed from the Chrome side, can we close this now?

**Comment by keyonjie** [comment]
@sathya-nujella @jairaj-arava I would close this, please reopen it if it needed.
