### ISSUE TITLE
[BUG] No audio with 1.5.1 and kernel 5.7.9-1

### ISSUE THREAD

**Issue by Enerccio** [thesofproject/linux#2302]
After updating to a new kernel, sof audio no longer outputs anything. I think I managed to get my output from my thunderbolt 3 dock with jack working, but without dock no audio from speakers or built in jack.
[dmesg.txt](https://github.com/thesofproject/sof/files/4949148/dmesg.txt)

**Comment by plbossart** [comment]
can you share the result of alsa-info?

**Comment by Enerccio** [comment]
http://alsa-project.org/db/?f=5734453ba564ff970f23475fc2322afb13a28207

**Comment by plbossart** [comment]
Nothing really suspicious @Enerccio 
Can you try speaker-test -Dhw:0,0 -c2 -r48000 and see if the streaming progresses? if it does then it's a codec configuration issue, maybe a wrong set of mixer settings or the codec pins themselves not well configured.

I am assuming you can hear audio playing when you use blacklist snd-sof-pci and force the snd-hda-intel driver to be used with a kernel parameter.

**Comment by Enerccio** [comment]
No sound input from `speaker-test`.

I tried older kernel, 1.4.1 sof, forcing snd-hda-intel, no sound. I had big update this morning so something might have fucked it up.

**Comment by Enerccio** [comment]
However, this is not a hardware problem. If I disable all drivers and boot to qemu running windows, sound is working 100%

**Comment by Enerccio** [comment]
https://pastebin.com/FGae8gPz this is what I upgraded this morning

**Comment by plbossart** [comment]
Alsa-lib and alsa-ucm-conf could be the problem, but that wouldn't explain why you can't hear anything with the legacy snd-hda-intel driver. You really need to get to a point where the legacy audio driver plays audible audio, at which point we can look into SOF-related issues.

**Comment by Enerccio** [comment]
I set it up with https://wiki.archlinux.org/index.php/Lenovo_Yoga_c940#Linux_5.5_and_later so I am not sure if legacy audio driver should even work after 5.5 though

When I block sof and unblock other drivers, I get only dummy output

**Comment by Enerccio** [comment]
When I boot with legacy intel drivers:

http://alsa-project.org/db/?f=e06737b31090a5bc2549a032c0aa0449c917f9ce

[dmesg-no-sof.txt](https://github.com/thesofproject/linux/files/4949943/dmesg-no-sof.txt)

    speaker-test -Dhw:0,0 -c2 -r48000
    
    speaker-test 1.2.3
    
    Playback device is hw:0,0
    Stream parameters are 48000Hz, S16_LE, 2 channels
    Using 16 octaves of pink noise
    ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
    Playback open error: -2,No such file or directory

**Comment by Enerccio** [comment]
Ok you were right, it was alsa,

warning: downgrading package alsa-lib (1.2.3.2-1 => 1.2.2-1)
warning: downgrading package lib32-alsa-lib (1.2.3.2-1 => 1.2.2-1)
warning: downgrading package alsa-topology-conf (1.2.3-1 => 1.2.2-1)
warning: downgrading package alsa-ucm-conf (1.2.3-2 => 1.2.2-1)

and I have sound back. Why would alsa cause this though?

**Comment by plbossart** [comment]
@perexg can you help here? which versions of alsa-lib and friends are currently recommended, or are you aware of potential issues with 1.2.3.2? I know there's been a lot of changes recently but haven't tracked version numbers. Thanks for your help!

**Comment by perexg** [comment]
Please, show the pulseaudio debug log for the latest alsa packages.

**Comment by kv2019i** [comment]
@Enerccio any update?

**Comment by kv2019i** [comment]
No update for a month and missing input, so closing. Reporter, please reopen if this issue is still valid.
