### ISSUE TITLE
KASAN out  of bounds access in module load/unload tests

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2311]
still a couple of issues with topic/sof-dev 53f2da654545df7fbc3bd69b488f1ce03b8eb922

[dmesg_kasan.log](https://github.com/thesofproject/linux/files/4962536/dmesg_kasan.log)

[sof-dev-defconfig.txt](https://github.com/thesofproject/linux/files/4962539/sof-dev-defconfig.txt)

Command

````bash
while true; do echo "MORE MORE MORE"; modprobe snd-sof-pci; sleep 20; rmmod snd-sof-pci; sleep 10; cat /sys/kernel/debug/kmemleak; cat /sys/kernel/debug/kmemleak  > kmemleak1.txt; done
````

**Comment by plbossart** [comment]
@kv2019i FYI in case your missed this.

**Comment by kv2019i** [comment]
Ack  @plbossart , I can take a look at this.

**Comment by kv2019i** [comment]
@plbossart Finally got around to this. I've been trying to reproduce this on a TGL SDW machine, but so far with no luck (with sof-dev).

The logs suggest that HDA codec probe would have failed, but all cases should be caught without crash:
  - if codec probe fails -> we got to no-i915 mode and I checked this works with the commit-id you use
  - if it silently fails and/or takes long -> patch "ASoC: Intel: sof_sdw: avoid crash if invalid DSP topology loaded" which you had in your tree, would catch this

So we should be good.

**Comment by kv2019i** [comment]
Uh, should have picked this up sooner:
[  212.133355] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[  212.133455] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[  212.133559] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0

What an earth, @plbossart you've somehow managed to load the old hdac-hdmi driver which has no support in our SDW machine. I could not recreate this situation even with handcrafted blacklists. Is this is the CML laptop?

**Comment by plbossart** [comment]
@kv2019i I plead not guilty. See the command line above, this is strictly with a modprobe/rmmod snd-sof-pci.

And yes this was on CML Olympic (1 amplifier).
That said, maybe it's fixed, it was a month ago, I haven't tried since (and busy today).

**Comment by kv2019i** [comment]
@plbossart Ack. On TGL, hdac-hdmi doesn't support the hw at all, so this can't happen, but on CML in theory yes. I'll try to reproduce with a CML laptop.

**Comment by kv2019i** [comment]
FYI @plbossart , managed to reproduce this now on a CML SDW laptop.

**Comment by kv2019i** [comment]
@plbossart The problem occurs in following situation:

all snd* modules unloaded:
modprobe snd-soc-hdac-hdmi
modprobe snd-sof-pci

The above case matches with your test script. When you remove "snd-sof-pci", the codec driver is not removed and once you reload "snd-sof-pci", you'll hit the bug.

The bug does not occur with:
modprobe snd-soc-hdac-hdmi
modprobe snd-sof-pci

And it does not happen with normal:
modprobe snd-sof-pci

There seems to be a slight difference in behaviour how "device_attach()" works in these scenarios. "snd-soc-hdac-hdmi" and "snd-hda-codec-hdmi" both offer a driver for this hardware. To complicate matters, we have no (known) means to identify the driver that was selected in the machine driver, so we have to rely on structure of the component private data and this leads to the pagefault (we assume the private data to be for snd-hda-codec-hdmi but when it's not, we simply crash). 

Good news is that you won't hit this in normal usage and if you use the sof-test scripts, module reload will also work fine. This does uncover a design issue in how we select between the codec drivers, and we could hit this later on in some other scenario, so we'll need to fix this one way or the other.

**Comment by plbossart** [comment]
Sorry @kv2019i I wasn't able to get the answer and when the bug does not happen.

**Comment by kv2019i** [comment]
@plbossart if you modify the test sequence so that all modules loaded as dependencies for "modprobe snd-sof-pci" are unloaded between tests, then the bug doesn't trigger. I.e. the flow that happens during boot when the PCI devices is found.

In terms of the script, i.e. this:

sleep 20; rmmod snd-sof-pci; sleep 10; cat /sys/kernel/debug/kmemleak; cat /sys/kernel/debug/kmemleak  > kmemleak1.txt; done

```
while true; do echo "MORE MORE MORE"; modprobe snd-sof-pci; sleep 20; sof-test/tools/kmod/sof_remove.sh; sleep 10; cat /sys/kernel/debug/kmemleak; cat /sys/kernel/debug/kmemleak  > kmemleak1.txt; done
```

**Comment by plbossart** [comment]
@kv2019i right, but this means that somehow the rmmod snf-sof-pci does not release resources that are explicitly released by unloading the modules. Not so good, eh?

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i right, but this means that somehow the rmmod snf-sof-pci does not release resources that are explicitly released by unloading the modules. Not so good, eh?

Absolutely, this is a real issue that needs to be fixed, not arguing that. It does seem this is not a problem of not releasing resources, but rather a problem in our flow to choose the codec driver and how we currently assume the hdac-hdmi driver to not be loaded when we probe SOF PCI driver. I say this as I could trigger this bug without any "rmmod" actions. Still a problem of course.
