### ISSUE TITLE
[BUG][JSL]No 'Headphone Jack' or 'Headset Jack' in amixer contents

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2329]
Describe the bug
No 'Headphone Jack' or 'Headset Jack' in amixer contents.

To Reproduce

Boot up system with headset connected.
Run with command "amixer contents"
Check if there is 'Headphone Jack" or "Headset Jack"

Reproduce rate
5/5

Expected result
There should be 'Headphone Jack" and "Headset Jack"

Actual result
No 'Headphone Jack' or 'Headset Jack' in amixer contents.
<img width="382" alt="Capture" src="https://user-images.githubusercontent.com/56707932/88772922-0798e300-d1b4-11ea-999e-14e9b5f67fd3.PNG">

Environment
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev(797eb03a)
SOF:https://github.com/thesofproject/sof/tree/releases/jsl/v4.0-rc1(21c8900f)
Topology:sof-jsl-da7219-mx98360a.tplg
Name of the platform(s) on which the bug is observed.
Platform: JSL  Chromebook  with codec da7219max98360a   in i2s mode

[dmesg0729.log](https://github.com/thesofproject/linux/files/4993465/dmesg0729.log)
[sof-logger0729.log](https://github.com/thesofproject/linux/files/4993467/sof-logger0729.log)
[amixercontents.txt](https://github.com/thesofproject/linux/files/4993473/amixercontents.txt)

**Comment by xiulipan** [comment]
Same behavior with Chrome OS on GLK. But evtest can show right jack and detction test can pass.
```
/dev/input/event5:      sof-rt5682 Headset Jack
Testing ... (interrupt to exit)
Event: time 1593782547.815596, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 1
Event: time 1593782547.815596, type 5 (EV_SW), code 4 (SW_MICROPHONE_INSERT), value 1
Event: time 1593782547.815596, -------------- SYN_REPORT ------------
Event: time 1593782549.438901, type 5 (EV_SW), code 2 (SW_HEADPHONE_INSERT), value 0
Event: time 1593782549.438901, type 5 (EV_SW), code 4 (SW_MICROPHONE_INSERT), value 0
Event: time 1593782549.438901, -------------- SYN_REPORT ------------
```

@yongzhi1 @sathya-nujella Is this designed to be so to not show Jack control in ALSA level?
@libinyang Will this influence the UCM things?

**Comment by sathyap-chrome** [comment]
amixer -c0 controls show Headphone / Headset. without c0, it wont be displayed

FYI from JSL : 
amixer -c0 controls | grep -i head
numid=63,iface=MIXER,name='Headphone Gain Ramp Switch'
numid=65,iface=MIXER,name='Headphone Jack Switch'
numid=64,iface=MIXER,name='Headphone ZC Gain Switch'
numid=62,iface=MIXER,name='Headphone Switch'
numid=61,iface=MIXER,name='Headphone Volume'
numid=66,iface=MIXER,name='Headset Mic Switch'

**Comment by udaymb** [comment]
This is the output in waddledoo - which gives Headphone Jack Switch
<img width="306" alt="amixer" src="https://user-images.githubusercontent.com/62392729/89763828-e9ff3e00-db10-11ea-90ef-dab001aa1f3d.png">

The output is similar in cml - Helios/hatch
Please can you confirm what should be the expected result look like?

**Comment by naveen-manohar** [comment]
I feel the control name for headphone jack for all i2s boards are taken from machine driver: SOC_DAPM_PIN_SWITCH("Headphone Jack") and then append with 'Switch' by asoc_simple_parse_pin_switches()
to finally list as "Headphone Jack Switch"

And for Soundwire, its like in https://github.com/thesofproject/linux/issues/2242#issuecomment-654581726

**Comment by plbossart** [comment]
@naveen-manohar @udaymb @sathyap-chrome @Liviali155 this doesn't seem like a real issue, and it's a codec issue anyways, not relevant for SOF bugs?
Any objections to closing this?

**Comment by sathya-nujella** [comment]
not relevant, we can close this. Thank you!
