### ISSUE TITLE
[BUG][CML][UCM2][HDA]Output device will auto switch from speaker to other source when unplug HDMI external port or headphone

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#2346]
Describe the bug
Output device will auto switch from speaker to other source when unplug HDMI external port or headphone.

Precondition:
1.Install ubuntu 20.04
UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: http://sof-ci-storage.sh.intel.com/share/alsa/alsa-lib/latest/libasound2_1.2.3.2-a3ca480/
Pulseaudio: http://sof-ci-storage.sh.intel.com/share/pulseaudio/latest/pulseaudio_13.99.1.1-47d8112/
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

To Reproduce

step 1: Boot up system with headphone and HDMI external port both connected
step 2: Open sound setting and select speaker as output device (corner case, as speaker has lowest priority)
step 3: Unplug HDMI external port.
step 4: Check the output device.
Reproduce rate
5/5

Expected result
Output source will stay in speaker.

Actual result
Output source will auto switch to headphone from speaker after unplugged HDMI external port.

Test recipe
Platform: CML laptop with onboard codec ALC3204 in HDA mode
Firmware: (3d8a0ac8) https://github.com/thesofproject/sof/commits/master
Kernel: (06accbaa) https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2: https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 3e897306)
Pulseaudio: pulseaudio (47d8112)

**Comment by libinyang** [comment]
compare to https://github.com/thesofproject/linux/issues/2126, this bug happens on HDA platform. This should be the pulseaudio issue. As this is a case that customer/user rarely meet, let's put it to P3.

**Comment by plbossart** [comment]
Why the HDA label when this happens on a SoundWire platform where HDA is not used at all?

**Comment by libinyang** [comment]
@plbossart Thanks for pointing it out. The description is updated

**Comment by plbossart** [comment]
@libinyang can we please try and close all those UCM2 issues? There's only few remaining.

**Comment by libinyang** [comment]
Sure, I will debug on it.

**Comment by libinyang** [comment]
The bug root cause is in pulseaudio. I will file a bug in https://gitlab.freedesktop.org/pulseaudio/pulseaudio. And hopefully I will submit a patch to pulseaudio to fix this issue this week.

The root cause is: when unplugging the HDMI, it will trigger to call switch_from_port(). It will compare the priority of the ports. This will cause pulseaudio pick up the headphone ahead of speaker. So the active port is changed to headphone. SOF + SDW platform works well because speaker and headphone are in different sinks. The "sink" mechanism makes sure that the speaker won't be switched to headphone. So this bug only happens on SOF + HDA platforms.

**Comment by libinyang** [comment]
patch has been submitted: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/370

**Comment by plbossart** [comment]
@libinyang doesn't look like we have a solution based on the PulseAudio discussions?

**Comment by libinyang** [comment]
Tanu gave some comments. I'm confirming with him for his idea.

**Comment by plbossart** [comment]
@libinyang @mengdonglin is this issue fixed? It's been 3 quarters already.

**Comment by libinyang** [comment]
The bug is already fixed and we can close it now.
