### ISSUE TITLE
[BUG][EHL] SOF takes ~60 seconds to finish the initialization w/o "i915.force_probe=$ID"

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#2356]
Describe the bug
SOF will take a long time to finish the initialization on EHL platform.

To Reproduce
reboot the EHL and run dmesg to check whether SOF finished initialization or not.

Reproduction Rate
3/3

Expected behavior
SOF finishes the initialization when user run `dmesg`

Impact
At the first several seconds, the audio can't be used.

**Comment by mengdonglin** [comment]
@libinyang Can you provide the data how long for audio driver to finish initialization and your test kernel/FW/topology recipe?

**Comment by plbossart** [comment]
> @libinyang Can you provide the data how long for audio driver to finish initialization and your test kernel/FW/topology recipe?

Indeed, this issue is somewhat useless as is. Please provide dmesg data, alsa-info, etc and start with a manual modprobe snd-sof-pci to make the measurements simple (without all the boot parts unrelated to SOF).

**Comment by libinyang** [comment]
I checked this issue on another board, without "i915.force_probe=$ID", it takes about 1 min to finish the initialization. After adding the kernel parameter, the boot latency is normal. And I checked the EHL in CI pool, it has added this parameter. So the boot latency seems OK. And I manually unload&load snd-sof-pci to check this issue. It seems OK. So it maybe another issue. I will continue checking this issue.

**Comment by juimonen** [comment]
@libinyang in RKL this is because without force_probe the correct i915 driver is not loaded and hda has 1 min timeout waiting for binding to it... I think this is some feature when i915 driver is in alpha, you need to force probe it.

**Comment by libinyang** [comment]
This bug is very weird. The dmesg shows normally and it passed the test if we trigger test plan 2 in https://sof-ci.sh.intel.com/#/test/testplanlist manually.

**Comment by libinyang** [comment]
> @libinyang in RKL this is because without force_probe the correct i915 driver is not loaded and hda has 1 min timeout waiting for binding to it... I think this is some feature when i915 driver is in alpha, you need to force probe it.

@juimonen Yes, and I have checked that the EHL DUT in CI has already added the 'force_probe' kernel parameter and the boot latency is much better but it still failed to pass the test.

**Comment by mengdonglin** [comment]
To file a new bug to track CI daily test failure.
