### ISSUE TITLE
ICL firmware boot errors

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2380]
We really need to solve this, this keeps polluting CI results:

https://sof-ci.01.org/sofpr/PR3296/build6981/devicetest/

````
kernel: [  730.773915] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x80000000 successful
kernel: [  730.773938] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x3010e0e successful
kernel: [  731.073971] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x6000010 timedout
kernel: [  731.073992] sof-audio-pci 0000:00:1f.3: unknown ROM status value 06000010
kernel: [  731.073998] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
kernel: [  731.074030] sof-audio-pci 0000:00:1f.3: error: extended rom status: 0x6000010 0x0 0x0 0x0 0x0 0x0 0x2001182 0x0
kernel: [  731.074036] sof-audio-pci 0000:00:1f.3: unknown ROM status value 06000010
````

Also seen on 02_01_TestPtpSimpleLoopbackMasterPlayback48000Hz32b32b8ch firmware tests
https://sof-ci.01.org/sof-pr-viewer/#/build/PR3296/build5404075

**Comment by ranj063** [comment]
@plbossart I dont think this a kernel issue. The driver does the right thing. It is more of a CI issue where it needs to realize that firmware boot can take more than 1 iteration.

**Comment by ranj063** [comment]
> @plbossart I dont think this a kernel issue. The driver does the right thing. It is more of a CI issue where it needs to realize that firmware boot can take more than 1 iteration.

sof-test issue related to this: https://github.com/thesofproject/sof-test/issues/340

**Comment by plbossart** [comment]
@ranj063 I can flip the argument and ask why the kernel flags an error when it should only complain when the last iteration fails.
The intermediate errors should really be warnings. It's not the job of CI scripts to translate error/warning levels, the kernel should do a better job here.

**Comment by xiulipan** [comment]
@ranj063 Agreed with @plbossart why we should print an error message when this actually is not an error.
PS: I also see same issue on CML these days, seems some change will make the FW boot retry happen more often.

**Comment by fredoh9** [comment]
related PR is https://github.com/thesofproject/linux/pull/2382

**Comment by mengdonglin** [comment]
@xiulipan is revising CI filter to check the new dmesg.
