### ISSUE TITLE
hdac_hdmi kernel warning at boot on GLK

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#239]
kernel branch: debug/cros-sof-v4.14-rebase

See log below for the kernel warning during hdac_hdmic runtime suspend. This potentially affects the ref counts for display and impact suspend stress test.

[    4.813835] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[    4.813956] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[    4.814145] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0
[    4.814357] WARNING: CPU: 0 PID: 3 at /mnt/host/source/src/third_party/kernel/v4.14/sound/hda/hdac_component.c:85 snd_hdac_display_power+0x75/0xa1 [snd_hda_core]
[    4.814360] Modules linked in: snd_soc_sst_bxt_da7219_max98357a(+) snd_soc_dmic snd_soc_hdac_hdmi lzo lzo_compress sof_pci_dev snd_sof_intel_hda_common zram snd_soc_hdac_hda snd_sof_intel_hda snd_sof_intel_byt snd_sof snd_sof_xtensa_dsp snd_soc_acpi_intel_match snd_soc_acpi snd_hda_ext_core acpi_als snd_soc_da7219 snd_soc_max98357a snd_hda_codec snd_hwdep snd_hda_core snd_seq_dummy snd_seq snd_seq_device bridge stp llc ipt_MASQUERADE nf_nat_masquerade_ipv4 xt_mark fuse iio_trig_sysfs btusb btrtl btbcm btintel bluetooth ecdh_generic uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core cros_ec_sensors cros_ec_sensors_ring industrialio_triggered_buffer cros_ec_sensors_core kfifo_buf industrialio iwlmvm iwl7000_mac80211 smsc75xx usbnet mii iwlwifi cfg80211 joydev
[    4.814412] CPU: 0 PID: 3 Comm: kworker/0:0 Not tainted 4.14.78 #5
[    4.814415] Hardware name: Google Yorp/Yorp, BIOS Google_Yorp.11123.0.2018_10_05_2322 10/05/2018
[    4.814422] Workqueue: pm pm_runtime_work
[    4.814425] task: ffff9f307b199c00 task.stack: ffffb585c0024000
[    4.814430] RIP: 0010:snd_hdac_display_power+0x75/0xa1 [snd_hda_core]
[    4.814432] RSP: 0018:ffffb585c0027d28 EFLAGS: 00010246
[    4.814435] RAX: ffff9f305caeada8 RBX: 0000000000000000 RCX: ffffb585c17d8000
[    4.814437] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff9f307322b828
[    4.814439] RBP: ffffb585c0027d38 R08: 0000000000000002 R09: 0000000000000001
[    4.814442] R10: ffffb585c18db7f0 R11: ffffb585c0027bf8 R12: ffff9f307322b828
[    4.814444] R13: ffff9f307322b828 R14: ffffb585c0027df8 R15: ffffb585c0027e00
[    4.814446] FS:  0000000000000000(0000) GS:ffff9f307fc00000(0000) knlGS:0000000000000000
[    4.814449] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    4.814451] CR2: 0000135189baf000 CR3: 000000015716e000 CR4: 00000000003406f0
[    4.814453] Call Trace:
[    4.814464]  hdac_hdmi_runtime_suspend+0x9e/0xc1 [snd_soc_hdac_hdmi]
[    4.814468]  __rpm_callback+0xf4/0x15c
[    4.814474]  ? __switch_to_asm+0x40/0x70
[    4.814477]  ? __switch_to_asm+0x34/0x70
[    4.814480]  ? hdac_hdmi_runtime_resume+0xb6/0xb6 [snd_soc_hdac_hdmi]
[    4.814484]  ? hdac_hdmi_runtime_resume+0xb6/0xb6 [snd_soc_hdac_hdmi]
[    4.814487]  rpm_callback+0x74/0x8a
[    4.814490]  rpm_suspend+0x2d3/0x443
[    4.814493]  pm_runtime_work+0x52/0x87
[    4.814499]  process_one_work+0x1b0/0x314
[    4.814503]  worker_thread+0x1cb/0x2c1
[    4.814507]  ? create_worker+0x1da/0x1da
[    4.814510]  kthread+0x156/0x15e
[    4.814513]  ? kthread_flush_work+0xea/0xea
[    4.814516]  ret_from_fork+0x35/0x40
[    4.814520] Code: 08 48 85 d2 74 08 48 8b 38 e8 94 11 64 f6 4c 89 e7 be 01 00 00 00 e8 24 fe ff ff 31 f6 4c 89 e7 e8 1a fe ff ff eb 29 85 db 75 02 <0f> 0b ff cb 41 89 9c 24 d0 04 00 00 85 db 75 ba 48 8b 50 08 48 
[    4.814558] ---[ end trace 7d5c26726b4b29bc ]---

**Comment by mengdonglin** [comment]
@ranj063  What's the possibility to reproduce this issue? And would you please share more info about the  steps to reproduce it?

**Comment by ranj063** [comment]
@mengdonglin this is a 100%. This kernel warning shows up in dmesg right after boot.

**Comment by keqiaozhang** [comment]
@ranj063
This issue is fixed on your kernel branch-cros-sof-v4.14-rebase.
I will close this issue once you rebase it to google release branch(thesofproject/linux/tree/topic/cros-sof-v4.14).

kernel driver- ranja063-cros-sof-v4.14-rebase:a38231
sof-master:1607737
soft-master:2cd668c

**Comment by ranj063** [comment]
@keqiaozhang i've updated the topic/cros-sof-v4.14-rebase branch

**Comment by mengdonglin** [comment]
@keqiaozhang Could help to verify and close it?

**Comment by keqiaozhang** [comment]
Confirmed that this issue is fixed.
Tested with:
Kernel-topic/cros-sof-v4.14-rebase: a38231
DSP FW-origin/glk-004-drop-stable: 1f79920
Topology-origin/master: 5894ed
