### ISSUE TITLE
SOF does not support 2^n period sizes as expected by apps like JACK 

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#2391]
The current SOF generic PCM code sets a PCM constraint that period size needs to be a multiple of minimum period size. In most topologies, this minimi period size is 192.

This has been discussed in multiple instnaces (https://github.com/thesofproject/linux/issues/1761 , https://github.com/thesofproject/linux/pull/1717 ).

This does cause practical issues to a large number of users who want to run JACK, or any similar audio software stack, which expect to use period and buffer sizes of 2^n bytes (to minimize playout/capture latency and use I/O size optimal for algorithms running in user-space). While this is not required by ALSA, this is so embedded to these applications, that e.g. running on JACK on any latop using using, takes some serious effort and leads to unoptimal results (as the chosen I/O size is not something most apps expect).

There's no technical limitation in play on most platforms, so we should just address this.

FYI @plbossart  @keyonjie  @ranj063 @juimonen

**Comment by plbossart** [comment]
@kv2019i I think we've used 1ms for internal timers for convenience and likely a Microsoft requirement that tricked down to firmware on precision of audio timestampts.
We could change the topologies to use 32 samples, in theory that should work - if not it's a bug.

**Comment by plbossart** [comment]
> @kv2019i I think we've used 1ms for internal timers for convenience and likely a Microsoft requirement that tricked down to firmware on precision of audio timestampts.
> We could change the topologies to use 32 samples, in theory that should work - if not it's a bug.

Actually that wouldn't work, we have too many cases where we use 1000 microseconds, but when they are fractional this wouldn't work. 666 microseconds would introduce an arithmetic error which would blow up real quick.

@lgirdwood @mmaka1 FYI, we need to think of scheduling periods that are not integer in ms...

**Comment by kv2019i** [comment]
Hmm, @plbossart  it seems overly restrictive for SOF to enforce its internal DSP timer tick to the application level. USB bus has similar fixed tick, but USB audio does not constraint application buffer sizes in a similar fashion as SOF now does. IOW, I think we should allow applications to use a period-size that is not aligned to our DSP timer tick and this should still work. Based on quick experiments, this in fact seems to work, but devil is probably in the details. Still, I think this should be the goal and allows to more easily change/tune the DSP side scheduling policies.

**Comment by plbossart** [comment]
@kv2019i as long as firmware folks keep using timer ticks, it'll be impossible to represent periods that are fractional. We have the same problem using 64.fs on interfaces, basic rules of integer divisions will not allow all configurations.

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i as long as firmware folks keep using timer ticks, it'll be impossible to represent periods that are fractional. We have the same problem using 64.fs on interfaces, basic rules of integer divisions will not allow all configurations.

I agree we should set the minimum period size based on the 1ms timer tick.

I'm however not convinced we should enforce a strict alignment for all period sizes. USB has a similar time based timer tick, but USB driver does not enforce this constraint on all period sizes to ALSA. It's only visible in the minimum period size.

This does lead to some unoptimal behaviour. Application can set a period size matching 1.1ms of wall-clock time, but it will get woken up in 1.9ms-0.1ms-1.9ms-0.1ms pattern due to SOF DSP timer tick. But this is something ALSA allows for, and matches with behaviour of widespread other drivers such as USB. And for these apps, it still makes sense. A wake-up with less data than 1.1ms, is useless for them, but it's still better than configuring a wakeup of 110ms (or some other very high multiple that matches both app and SOF constraints).

I think unless it causes some major problems elsewhere, we should align with the mainstream approach (and allow SOF to play nice(r) with apps like JACK and PipeWire). To be the best of friends, I think we need to discuss about the 1ms timer tick, but that's another topic.

**Comment by keyonjie** [comment]
@plbossart I think you have been mixing the constraint of ALSA buffer period size and FW buffer one, we are using 1ms period in most of FW buffers, but that should not be propagated to ALSA DDR buffers IMHO, we are able to make ALSA buffer constraint more friendly to user space, including period_size and buffer_size.

**Comment by plbossart** [comment]
I disagree with both @kv2019i and @keyonjie. Having period events that are not periodic is IMHO a bug, not a feature. we should not promote this sort of behavior.

**Comment by kv2019i** [comment]
@plbossart wrote: 
> I disagree with both @kv2019i and @keyonjie. Having period events that are not periodic is IMHO a bug, not a feature. we should not promote this sort of behavior.

I think this very similar to the discussion of accuracy of "avail" bytes at any given time. Like with "avail", ALSA doesn't guarantee wake-ups to be accurate and there is no API to let user-space know about e.g. DMA burst length. We do need to have X bytes available when period interrupt is raised, and for this we are compliant and applications are happy. If they care about more accurate timing, they should use pcm_avail and pcm_delay (and the timestamps) to observe the realtime status of the stream. 

I tried to give some more concrete example in the #2482 patch now, please check. The period events are still periodic, but the accuracy is reduced. Like usleep_range(), the wakeups are coalesced to nearest 1ms tick. In practical cases where period sizes are configured to 5.3/10.7/21.3/42.7ms period sizes, the error we cause with the 1ms timer tick, is fairly small and any application that cares the timing at this level, should use more appropriate ALSA calls. The period interrupts can be delayed and have variance for many other reasons as well (e.g. system load).

**Comment by kv2019i** [comment]
Patch merged, closing.
