### ISSUE TITLE
[Regression] No sound on kernel 5.8 series on systems with no i915

### ISSUE THREAD

**Issue by Valerio1474** [thesofproject/linux#2393]
**Describe the bug**
Hello,

I don't know what might be changed from kernel 5.7.x to kernel 5.8.x but the sound has stopped working under the newest kernel. I thought that the 1.5.1 firmware could fix the problem, but to no avail.

**To Reproduce**
Compile and boot any 5.8.x kernel with same options I have on 5.7.x

**Reproduction Rate**
Always

**Expected behavior**
The expected behavior is to seamlessly install and use a new kernel.

**Impact**
No sound at all.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.8.x
    * SOF: 1.5.1
2) Name of the topology file
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: Debian/Sid/amd64/Cannon Lake
[5.7.0_dmesg.txt](https://github.com/thesofproject/sof/files/5122491/5.7.0_dmesg.txt)

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

**Comment by kv2019i** [comment]
Fix picked to 5.8 stable as
https://git.kernel.org/pub/scm/linux/kernel/git/sashal/linux-stable.git/commit/?h=queue-5.8&id=322ed8850c263b6971e7ccf644fc37829b967325

... didn't quite make it to 5.8.5, but should be in 5.8.6. Thanks @Valerio1474 for reporting!
