### ISSUE TITLE
[TRAVIS CI] fails due to ppa configuration issues

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2398]
not sure what's going on:

https://travis-ci.org/github/thesofproject/linux/jobs/721742486
https://travis-ci.org/github/thesofproject/linux/jobs/721742488

The ppa configuration seems wrong?

@marc-hb @xiulipan FYI

**Comment by marc-hb** [comment]
Well, from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

> You can update your system with unsupported packages from this untrusted PPA by adding ppa:ubuntu-toolchain-r/test to your system's Software Sources.

We're just getting what we paid for?

This repo was added years ago by @xiulipan  in commit 9429ffcb9bd0, to upgrade (!) gcc to gcc version 7 so it could compile kernel 4.20.

As you can see from the top of the Travis log, Ubuntu 18.04 already has gcc 7.5 by default so I suggest reverting 9429ffcb9bd0. It will make the build not just simpler but faster.

**Comment by xiulipan** [comment]
@marc-hb Agreed, we may need some update on our Travis scripts. Now maybe Travis can support Ubuntu 20.04 and the default GCC can satisfy the Kernel build require. I will send a update patch.

**Comment by xiulipan** [comment]
@plbossart @marc-hb As the Travis now has Ubuntu 20.04 support with GCC 9.3 https://docs.travis-ci.com/user/reference/focal/ I will directly remove the PPA thing and use Ubuntu 20.04 with GCC 9.3 now.

**Comment by xiulipan** [comment]
PR send https://github.com/thesofproject/linux/pull/2402
