### ISSUE TITLE
CML RVP w/ RT700: Clock stop errors

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2407]
Tracking results from https://sof-ci.01.org/sofpr/PR3186/build7015/devicetest/

````
Aug 27 09:17:43 sh-cml-rvp-sdw-04 kernel: [  599.823866] rt700 sdw:1:25d:700:0: Clock Stop prepare failed for slave: -61
Aug 27 09:17:43 sh-cml-rvp-sdw-04 kernel: [  599.823874] rt700 sdw:1:25d:700:0: pre-prepare failed:-61
Aug 27 09:17:43 sh-cml-rvp-sdw-04 kernel: [  599.823878] intel-sdw intel-sdw.1: prepare clock stop failed -61
````

````
kernel: [  624.394843] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [  632.290153] intel-sdw intel-sdw.1: Msg Ack not received
kernel: [  632.290154] intel-sdw intel-sdw.1: Msg ignored for Slave 1
kernel: [  632.290156] rt700 sdw:1:25d:700:0: Unable to sync register 0x3121. -61
kernel: [  632.290227] intel-sdw intel-sdw.1: Msg Ack not received
kernel: [  632.290227] intel-sdw intel-sdw.1: Msg ignored for Slave 1
kernel: [  632.290229] rt700 sdw:1:25d:700:0: Unable to sync register 0x752010. -61
kernel: [  632.290233] intel-sdw intel-sdw.1: pm_runtime_get_sync failed in intel_startup, ret -22
kernel: [  632.290235] intel-sdw intel-sdw.1: ASoC: error at snd_soc_dai_startup on SDW1 Pin3: -22
kernel: [  632.290235] intel-sdw intel-sdw.1: ASoC: can't open DAI SDW1 Pin3: -22
kernel: [  632.290238]  SDW1-Capture: ASoC: BE open failed -22
kernel: [  632.290238]  SDW1-mics: ASoC: failed to start some BEs -22
````
@bardliao @RanderWang does this ring a bell? Looks like we still have a big issue on this RVP?

**Comment by RanderWang** [comment]
it is very strange that RT700 was working and suddenly got runtime suspended, why ?

````
kernel: [  599.244530] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
kernel: [  599.823854] intel-sdw intel-sdw.1: Msg Ack not received
kernel: [  599.823860] intel-sdw intel-sdw.1: Msg ignored for Slave 1
kernel: [  599.823866] rt700 sdw:1:25d:700:0: Clock Stop prepare failed for slave: -61
kernel: [  599.823874] rt700 sdw:1:25d:700:0: pre-prepare failed:-61
kernel: [  599.823878] intel-sdw intel-sdw.1: prepare clock stop failed -61
kernel: [  599.823883] intel-sdw intel-sdw.1: cannot enable clock stop on suspend
````

**Comment by RanderWang** [comment]
sorry, I made a mistake: RT700 was not working, but HDMI was.

**Comment by plbossart** [comment]
I don't think we've seen this lately, right @RanderWang @bardliao ?

**Comment by RanderWang** [comment]
> I don't think we've seen this lately, right @RanderWang @bardliao ?

yes, I sent a few day to reproduce it but never get it. And this device was removed from CI for rt700 is not used by any customer.

**Comment by bardliao** [comment]
Spring from Realtek suggest us to reduce the clock to see if it we can still reproduce the issue. But I think it is hard enough to reproduce it already.

**Comment by marc-hb** [comment]
Looks a bit like this other, very recent check-runtime-pm-status.sh failure in https://sof-ci.01.org/softestpr/PR469/build324/devicetest/ 

Same bug?
```
kernel: [  596.556018] sof-audio-pci 0000:00:1f.3: pcm: free stream 1 dir 1
kernel: [  596.556979] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
kernel: [  596.557084] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
kernel: [  596.557106] sof-audio-pci 0000:00:1f.3: pcm: close stream 1 dir 1
kernel: [  597.144374] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [  597.144416] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [  599.931170] intel-sdw intel-sdw.1: Msg Ack not received
kernel: [  599.931177] intel-sdw intel-sdw.1: Msg ignored for Slave 1
kernel: [  599.931183] rt700 sdw:1:25d:700:0: Clock Stop prepare failed for slave: -61
kernel: [  599.931192] rt700 sdw:1:25d:700:0: pre-prepare failed:-61
kernel: [  599.931197] intel-sdw intel-sdw.1: prepare clock stop failed -61
kernel: [  599.931201] intel-sdw intel-sdw.1: cannot enable clock stop on suspend
```

**Comment by bardliao** [comment]
> Looks a bit like this other, very recent check-runtime-pm-status.sh failure in https://sof-ci.01.org/softestpr/PR469/build324/devicetest/
> 
> Same bug?
> 
> ```
> kernel: [  596.556018] sof-audio-pci 0000:00:1f.3: pcm: free stream 1 dir 1
> kernel: [  596.556979] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
> kernel: [  596.557084] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
> kernel: [  596.557106] sof-audio-pci 0000:00:1f.3: pcm: close stream 1 dir 1
> kernel: [  597.144374] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
> kernel: [  597.144416] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
> kernel: [  599.931170] intel-sdw intel-sdw.1: Msg Ack not received
> kernel: [  599.931177] intel-sdw intel-sdw.1: Msg ignored for Slave 1
> kernel: [  599.931183] rt700 sdw:1:25d:700:0: Clock Stop prepare failed for slave: -61
> kernel: [  599.931192] rt700 sdw:1:25d:700:0: pre-prepare failed:-61
> kernel: [  599.931197] intel-sdw intel-sdw.1: prepare clock stop failed -61
> kernel: [  599.931201] intel-sdw intel-sdw.1: cannot enable clock stop on suspend
> ```

Yes, it is very likely the same issue.

**Comment by mengdonglin** [comment]
RT700 is not a production version codec. Will check the issue if it can be reproduced with SDW codecs.
