### ISSUE TITLE
SOF probe fails on GLK with 5.9-rc1

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#2410]
With recent patches to DRM driver, the DP/HDMI codec probe has started to fail on GLK hardware. 

Example failure:
https://sof-ci.01.org/linuxpr/PR2409/build4414/devicetest/

The issue is currently worked around in sof-dev, but in upstream the problem persists.

**Comment by kv2019i** [comment]
I have confirmed the root cause is too low CDCLK for GLK. The actual regression seems very subtle. The logic of the problematic new patches seem good, but still in practise the CDCLK is not bumped at probe. Investigation continues...

**Comment by kv2019i** [comment]
FYI @plbossart -- CI seems fine for Bobba GLK now. I'll send this to DRM list for review. Once I get an ack from them, I'll resubmit the PR with the approved fix, and we can merge (and get rid of the DRM reverts).

**Comment by plbossart** [comment]
ack, thanks @kv2019i 
Nothing like harmless code refactoring to add bugs....
