### ISSUE TITLE
[BUG] cavs: icl: core 3 must be powered on startup by the driver

### ISSUE THREAD

**Issue by mmaka1** [thesofproject/linux#2434]
**Describe the bug**
Since the DSP starts at full throttle (HP-RO 400 MHz is used as a clock source), the driver should set SPA for core3 in addition to core0 in order to propagate required notifications to other units. This should be done "silently", run-time environment for core3 is not required at this point, so the FW does not need to know about this.

In future, when more power optimizations will be implemented for icl, the FW will notify the driver (some new pwr state changed notification) when switching to LP-RO 120 MHz and back and the driver may toggle core3 SPA accordingly.

**Comment by plbossart** [comment]
I don't understand what the issue is and what in the driver code should be modified. As @ranj063 mentioned it all 4 cores get powered.

**Comment by mengdonglin** [comment]
@ranj063 @fredoh9 Can we close this issue now if all 4 cores get powered? Or need we wait for ICCMAX implementation on ICL is  done on ICL?

**Comment by fredoh9** [comment]
There was some fixes required in SOF firmware. First one is https://github.com/thesofproject/sof/pull/3465,

I got a patch today. Will continue to work on this.
https://github.com/thesofproject/sof/pull/3473

**Comment by fredoh9** [comment]
Without https://github.com/thesofproject/sof/pull/2957/files, there is no extended manifest support. This is not SOF v1.6 blocker.

**Comment by fredoh9** [comment]
https://github.com/thesofproject/linux/pull/2548 merged
