### ISSUE TITLE
[BUG] [TGL] [SDW]: v0.9 Headset Playback/Capture Fail

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#2440]
There is a headset functionality regression identified in SoF_v0.9 chrome-backported recipe.
Headset detection happens fine, but when we playback/capture stream, below issue is observed and usecase fails with no audio.
Attacked Log: 
[dmesg_sdw_inconsistent.log](https://github.com/thesofproject/linux/files/5229344/dmesg_sdw_inconsistent.log)

```
[   28.370328] sdw_enable_stream: subdevice #0-Capture: inconsistent state state 3
[   28.370333] intel-sdw intel-sdw.0: intel_trigger trigger 1 failed: -22
[   28.370335] intel-sdw intel-sdw.0: ASoC: error at snd_soc_pcm_dai_trigger on SDW0 Pin3: -22
[   28.370337]  SDW0-Capture: ASoC: trigger BE failed -22
[   28.370338]  Headset mic: ASoC: trigger FE cmd: 1 failed: -22

```
I suspect the backported kernel recipe, but wanted to confirm, if with v0.9 release (sof-dev linux & fw), headset functionality worked fine ?
Note: All other endpoints like max98373-sdw, dmic, hdmi works fine

Steps to reproduce:
1. Setup:
    Firmware: FW tag: tgl-009-drop-stable, commit: 319d914d
    Kernel: Chrome Backported Kernel: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2411126
                 Based on sof-dev: URL: https://github.com/thesofproject/linux/tree/topic/sof-dev  commit: a34de778
    Hardware: TGL Soundwire Chrome Reference Board
2. Build/Update above recipe & Boot the device and check for Headset Functionality
3.  Observe: Jack Detection passes but headset audio playback/capture fail with above mentioned issue

**Comment by naveen-manohar** [comment]
Observe the same issue with daily built libraries :
md5sum /lib/firmware/intel/sof/community/sof-tgl.ri af3d58407734d70326104576399f941f  
-rw-r--r--. 1 root root 356352 Sep 16 00:09 /lib/firmware/intel/sof/community/sof-tgl.ri
md5sum /lib/firmware/intel/sof-tplg/sof-tgl-max98373-rt5682.tplg f3e58ae66bc77e8b3daa8aa889d7a99d  
-rw-r--r--. 1 root root 48159 Sep 13 00:37 /lib/firmware/intel/sof-tplg/sof-tgl-max98373-rt5682.tplg

**Comment by RanderWang** [comment]
I debugged the issue: two patches missed: remove trigger, prepare hw_free in soundwire driver. these patches are hot points recently :)

**Comment by naveen-manohar** [comment]
Thanks for the quick turn-around @RanderWang ..
The below patches you shared weren't there in v0.9-sof-dev release(commit: a34de778), also they can't be directly applied without dependent patches after v0.9 tag.
```
soundwire: intel: remove .trigger operation
soundwire: intel: remove stream handling from .prepare and .hw_free
```

Hence tried comparing v0.9 (commit: a34de778) & chrome_backported_kernel wrt Soundwire & there were few more missing patches, Attaching [0001-v0.9-missing-patches.txt](https://github.com/thesofproject/linux/files/5232274/0001-v0.9-missing-patches.txt)

**With this I could verify headset functionality and no issues observed.**

Have shared to Backport Team & Waiting for their update.

**Comment by plbossart** [comment]
@naveen-manohar you probably need https://github.com/thesofproject/linux/pull/2438 as well

**Comment by naveen-manohar** [comment]
Many Thanks @plbossart for the quick response.
We could identify the below dependent patches was missing and dropped it for now, **with this all endpoints works.**
https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2294575.html

Thanks All for the Quick Response & Support. Closing this thread.
