### ISSUE TITLE
[TGL] RT715-SDCA pause/resume issues

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2463]
sof-test reports errors with multiple-pause-resume cases

````
kernel: [ 4694.475103] rt715-sdca sdw:3:25d:714:1: DPN_PortCtrl register write failed for port 4
kernel: [ 4694.475106] soundwire sdw-master-3: Program transport params failed: -61
kernel: [ 4694.475106] soundwire sdw-master-3: Program params failed: -61
kernel: [ 4694.475107]  SDW3-Capture: ASoC: error at snd_soc_link_prepare on SDW3-Capture: -61
kernel: [ 4694.475108]  SDW3-Capture: ASoC: backend prepare failed -61
````

[multiple-pause-resume.tar.gz](https://github.com/thesofproject/linux/files/5264426/multiple-pause-resume.tar.gz)

**Comment by plbossart** [comment]
@bardliao this is with your branch https://github.com/bardliao/linux/tree/for-sdca-test

sof-test with https://github.com/thesofproject/sof-test/pull/397 and 
[multiple-pause-resume.tar.gz](https://github.com/thesofproject/linux/files/5264462/multiple-pause-resume.tar.gz)

@shumingfan @jack-cy-yu FYI

**Comment by bardliao** [comment]
@plbossart Can you try https://github.com/bardliao/linux/tree/for-sdca-test-v2? https://github.com/thesofproject/linux/pull/2308 has been updated and I don't see the issue with my new branch
