### ISSUE TITLE
[SDW] [TGL] rt711-sdca jack detection only works when runtime pm disabled

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#2464]
rt711_sdca_interrupt_callback() is not triggered when a jack is inserted/removed in runtime suspended.
I do see interrupt when a jack is inserted/removed and sdw link is powered up, but I can only see SDW_SLAVE_ATTACHED event but no SDW_SLAVE_ALERT event.

testing branch https://github.com/bardliao/linux/tree/for-sdca-test-v2
@plbossart @shumingfan Let's track the issue here.

**Comment by shumingfan** [comment]
@bardliao I think that the sdw_handle_slave_alerts function can't see the DP0_SDCA_CASCADE flag when runtime resumes.
The bus driver will do the bus reset when runtime resumes. However, the bus reset will reset the SCP_SDCA_IntMaskY registers.
Could you test with the patch (https://github.com/shumingfan/linux/commit/092c260a1da151a363867d6590b85af0355dfad3)?
You also need to set the property in the codec driver as below.
If this patch is reasonable, the codec driver will not set SCP_SDCA_IntMask registers directly.

```
--- a/sound/soc/codecs/rt711-sdca.c
+++ b/sound/soc/codecs/rt711-sdca.c
@@ -364,6 +364,9 @@ static void rt711_sdca_jack_init(struct rt711_sdca_priv *rt711)
                        break;
                }

+               prop->scp_sdca_int1_mask = SDW_SCP_SDCA_INTMASK_SDCA_0;
+               prop->scp_sdca_int2_mask = SDW_SCP_SDCA_INTMASK_SDCA_8;
+
                /* set SCP_SDCA_IntMask1[0]=1 */
                regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1,
                        SDW_SCP_SDCA_INTMASK_SDCA_0);
@@ -380,6 +383,8 @@ static void rt711_sdca_jack_init(struct rt711_sdca_priv *rt711)
                rt711_sdca_index_update_bits(rt711, RT711_VENDOR_HDA_CTL,
                        RT711_GE_MODE_RELATED_CTL, 0x0c00, 0x0000);

+               prop->scp_sdca_int1_mask = 0;
+               prop->scp_sdca_int2_mask = 0;
                /*  set SCP_SDCA_IntMask1[0]=0 */
                regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1, 0x00);
```

**Comment by bardliao** [comment]
@shumingfan Thanks, it works on my side.

**Comment by plbossart** [comment]
@shumingfan @bardliao I am not sure it's wise to set the SDCA interrupt bits at the bus layer. It's not clear if the 4 mask registers are required for all implementations, so I would err on the side of caution and only enable SDCA interrupts in the codec driver .update_status() callback, after the device is detected as attached. 

Adding the properties is however fine, it doesn't hurt to declare them by default.

**Comment by plbossart** [comment]
@bardliao @shumingfan I actually don't understand the suggested fix. When the bus resumes, in the io_init() callback the codec will call rt711_sdca_jack_init(), which will re-enable the masks.


````c
static void rt711_sdca_jack_init(struct rt711_sdca_priv *rt711)
{
	mutex_lock(&rt711->calibrate_mutex);

	if (rt711->hs_jack) {
                [...]
		/* set SCP_SDCA_IntMask1[0]=1 */
		regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1,
			SDW_SCP_SDCA_INTMASK_SDCA_0);
		/* set SCP_SDCA_IntMask2[0]=1 */
		regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK2,
			SDW_SCP_SDCA_INTMASK_SDCA_8);
````

so why would we need to do this at the bus level again?

**Comment by shumingfan** [comment]
> ementations, so I would err on the side of caution and only enable SDCA interrupts in the codec driver .update_status() callback, after the device is detected as attache

@bardliao @plbossart I tried to re-enable SDCA interrupt in the .update_status() when the slave is detected as attached.
The test result is not good. Sometimes it could go to interrupt_callback, sometimes doesn't.
The failed case is that the bus driver goes to power down mode very soon.

**Comment by plbossart** [comment]
> > ementations, so I would err on the side of caution and only enable SDCA interrupts in the codec driver .update_status() callback, after the device is detected as attache
> 
> @bardliao @plbossart I tried to re-enable SDCA interrupt in the .update_status() when the slave is detected as attached.
> The test result is not good. Sometimes it could go to interrupt_callback, sometimes doesn't.
> The failed case is that the bus driver goes to power down mode very soon.

This could be a sign of a missing pm_runtime_mark_last_busy().
Can you share your code so that we can compare? Thanks @shumingfan

**Comment by shumingfan** [comment]
> This could be a sign of a missing pm_runtime_mark_last_busy().
> Can you share your code so that we can compare? Thanks @shumingfan

I tried to test again. I found out something I ignored before.
Due to the codec driver entered the suspend mode already, the act of re-enabling SDCA interrupt should be at cache-only=false mode.
Please check my test patch below. This patch works on my side.
If this patch is fine, I will update it to PR.

```
--- a/sound/soc/codecs/rt711-sdca-sdw.c
+++ b/sound/soc/codecs/rt711-sdca-sdw.c
@@ -142,6 +142,21 @@ static int rt711_sdca_update_status(struct sdw_slave *slave,
        if (status == SDW_SLAVE_UNATTACHED)
                rt711->hw_init = false;

+       if (status == SDW_SLAVE_ATTACHED) {
+               if (rt711->hs_jack) {
+                       regcache_cache_only(rt711->regmap, false);
+                       regcache_cache_bypass(rt711->regmap, true);
+                       regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1,
+                               SDW_SCP_SDCA_INTMASK_SDCA_0);
+                       regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK2,
+                               SDW_SCP_SDCA_INTMASK_SDCA_8);
+                       regcache_cache_bypass(rt711->regmap, false);
+               } else {
+                       regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1, 0);
+                       regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK2, 0);
+               }
+       }
+
```

```
--- a/sound/soc/codecs/rt711-sdca.c
+++ b/sound/soc/codecs/rt711-sdca.c
@@ -468,8 +468,14 @@ static void rt711_sdca_jack_init(struct rt711_sdca_priv *rt711)
                        break;
                }

-               prop->scp_sdca_int1_mask = SDW_SCP_SDCA_INTMASK_SDCA_0;
-               prop->scp_sdca_int2_mask = SDW_SCP_SDCA_INTMASK_SDCA_8;
+               /* set SCP_SDCA_IntMask1[0]=1 */
+               regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1,
+                       SDW_SCP_SDCA_INTMASK_SDCA_0);
+               /* set SCP_SDCA_IntMask2[0]=1 */
+               regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK2,
+                       SDW_SCP_SDCA_INTMASK_SDCA_8);
                dev_dbg(&rt711->slave->dev, "in %s enable\n", __func__);

                mod_delayed_work(system_power_efficient_wq,
@@ -479,8 +485,12 @@ static void rt711_sdca_jack_init(struct rt711_sdca_priv *rt711)
                rt711_sdca_index_update_bits(rt711, RT711_VENDOR_HDA_CTL,
                        RT711_GE_MODE_RELATED_CTL, 0x0c00, 0x0000);

-               prop->scp_sdca_int1_mask = 0;
-               prop->scp_sdca_int2_mask = 0;
+               /* set SCP_SDCA_IntMask1[0]=0 */
+               regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK1, 0);
+               /* set SCP_SDCA_IntMask2[0]=0 */
+               regmap_write(rt711->regmap, SDW_SCP_SDCA_INTMASK2, 0);
```

**Comment by plbossart** [comment]
@shumingfan I integrated the code on sdw/sdca-integration and I don't see any problems.

**Comment by keyonjie** [comment]
PR 2298 merged, @bardliao can we close it now?
