### ISSUE TITLE
[SDW] [TGL] rt715-sdca only works when runtime pm is disabled

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#2465]
rt715-sdca can only capture silence on my side.
But it works well if I add options below
options soundwire_intel sdw_link_mask=0xf sdw_md_flags=0x05050505
options snd_sof_pci sof_pci_debug=1

testing branch https://github.com/bardliao/linux/tree/for-sdca-test-v2
@plbossart @jack-cy-yu Let's track the issue here.

**Comment by jack-cy-yu** [comment]
@bardliao Please refer #2308 , driver has been updated. Thanks.

**Comment by bardliao** [comment]
> @bardliao Please refer #2308 , driver has been updated. Thanks.

Thanks @jack-cy-yu I verified #2308 on my side.
