### ISSUE TITLE
Early samples not played out correctly to DisplayPort receiver 

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#2468]
Test steps:
------------

1. Boot system with DisplayPort receiver connected
2. Connect DisplayPort receiver (test with Samsung U24E590)
3. check to which PCM monitor is connected (e.g. with amixer contents)
4. play ALSA test file to receiver (plughw:0,3 in this case, depends on how monitor is connected in step 3)

aplay -vv -i Dplughw:0,3 /usr/share/alsa/sounds/alsa/Front_Center.wav

5. immediately rerun aplay 
6. wait until display codec goes to runtime suspend, then rerun aplay

Expected results:
-------------------

Audio playback is clean from the start

Actual results:
----------------

Audio playback is missing 1-2sec of beginning. 

Notes:
--------

- Happens with current sof-dev and 5.7/5.8/5.9 stable releases of this date
- Enabling "silent streaming" helps for step 6 and subsequent runs and display codec is not put to runtime suspend as long as monitor is connected ("options snd_hda_codec_hdmi enable_silent_stream=Y" and kernel option CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM, since v5.9 kernel)
- Does not happen with HDMI, only with DisplayPort.
- Length of the gap varies, but systematically there is some glitch in step (4).
- Happens both with SOF and snd-hda-intel HDA controller drivers.
- Is not observed when playing audio from UI through Pulseaudio (or similar server) as the audio server playes out a preamble to the ALSA PCM before application audio starts and this hides the issue.

**Comment by kv2019i** [comment]
Further tests: 
- Is not dependent on the resolution and framerate (i.e. bandwidth used on DisplayPort link).

**Comment by kv2019i** [comment]
Latest findings point to following:
 - the delay is caused by analogue delay of the display audio receivers (most DP monitors behave like this, tested with e.g. Philips 276E8V),
 - there is a bug in silent-stream feature of snd-hda-codec-hdmi and the delay is seen also when silent streaming is enabled

**Comment by kv2019i** [comment]
Bug closed with following patch merged upstream:

b1a5039759cb7bfcb2157f28604dbda0bca58598 ALSA: hda/hdmi: fix silent stream for first playback to DP
Link: https://lore.kernel.org/r/20201210174445.3134104-1-kai.vehmanen@linux.intel.com

To avoid the problem, one will need the above patch _and_ enable silent-streaming for snd-hda-codec-hdmi:

/etc/modprobe.d/alsa-base.conf:
```
options snd_hda_codec_hdmi enable_silent_stream=Y
```

**Comment by hjl-tools** [comment]
The fix caused:

https://bugzilla.kernel.org/show_bug.cgi?id=210983
