### ISSUE TITLE
[TGL][SDW] settings for RT1316 don't seem right

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2471]
testing with https://github.com/plbossart/sound/tree/sof-sdca-test-v3 (based on @bardliao code) and https://github.com/plbossart/alsa-ucm-conf/tree/sdw/sdca, the sound doesn't seem to come out right (left/right and frequency content).

In 2ch mode, the right channel comes on the left side
in 4ch mode, the sound comes from the middle, but the left seems to be coming out of a tweeter and the right from a woofer. 

Something's not quite right so tracking this as an issue

@bardliao @RanderWang @libinyang @shumingfan @jack-cy-yu FYI.

**Comment by keyonjie** [comment]
no driver update needed, UCM config needed.

**Comment by plbossart** [comment]
The UCM settings were updated on the sdw/sdca branch, we need someone to verify the RT1316 setup is acceptable. IIRC @bardliao mentioned some issues with the initial codec config?

**Comment by bardliao** [comment]
> The UCM settings were updated on the sdw/sdca branch, we need someone to verify the RT1316 setup is acceptable. IIRC @bardliao mentioned some issues with the initial codec config?

Yes, the "RX Channel Select" control does not always take effect. @shumingfan is working on it.

**Comment by plbossart** [comment]
fixed with UCM config.
