### ISSUE TITLE
[BYT][NOCODEC] failed tests with simultaneous-playback-capture.sh	

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2472]
https://sof-ci.01.org/linuxpr/PR2469/build4579/devicetest/

Not sure what's going but we see again lots of errors at the firmware level.

@lgirdwood @lyakh @marc-hb @xiulipan @aiChaoSONG Does this ring a bell? I may be paranoid here but I suspect instability issues are re-occurring?

**Comment by plbossart** [comment]
Also seen in Intel daily tests, ID 479, on BYT_NOCODEC and BSW_CYAN.

This is not a drill, this looks real:

````
aplay: pcm_write:2061: write error: Input/output error
aplay: pcm_write:2061: write error: Input/output error
````

**Comment by marc-hb** [comment]
I think last time we saw `Input/output error` it was a disk issue. More specifically eMMC which is generally cr*p: https://www.google.com/search?q=mmc0+timeout

BTW issues like eMMC are exactly why it ignoring unknown errors and running tests anyway is worse than pointless. It's much worse because instead of the entire system clearly being flagged as unreliable, everyone wonders why only some tests are failing.

**Comment by aiChaoSONG** [comment]
@plbossart @marc-hb I think this is true FW issue. I also observed this IO error in stable-1.6 stress test:
- BYT, check-playback-300times, Report ID: 478
- BSW/BYT, multiple-pipeline-playback-200, Report ID: 478
- BYT, check-playback-all-formats-50, Report ID: 478

This issue is very easy to reproduce in stress test, especially in high load test, eg multiple-pipeline test. And notice when issue occurs, we can have this message: `no byte to produce/no byte to consume`.

**Comment by mengdonglin** [comment]
@plbossart @aiChaoSONG Is this the same issue as https://github.com/thesofproject/sof/issues/3462?

**Comment by aiChaoSONG** [comment]
@mengdonglin Yes, should be the same issue.

**Comment by plbossart** [comment]
I don't think it's a duplicate. We've changed the firmware quite a bit, the issue 'disappeared' and now shows up again. To me that's a separate issue that cause the same error to show up, but the root cause is different.

@lgirdwood @lyakh is this something you can reproduce? I don't think we want to hold 1.6 for this, but still it's concerning that we somehow either missed this problem in previous tests, or have missed a new regression.

**Comment by plbossart** [comment]
Actually I'd like to confirm if stable-1.6 actually shows this regression? I see in results that the 1.6 stress tests did not expose a regression, so wondering if the errors happen only with the sof 'main' branch.

**Comment by plbossart** [comment]
Still error for check-playback-100times.sh in Intel daily test 489...

**Comment by fredoh9** [comment]
> Actually I'd like to confirm if stable-1.6 actually shows this regression?

@plbossart I scanned test results in SOF v1.6 branch. I found same errors in BSW/BYT. Plan test result(not daily test) 488.

- Kernel Branch: topic/sof-dev
- Kernel Commit: 779efb50
- SOF Branch: stable-v1.6
- SOF Commit: 18fabd3d_release
 
I'm running simultaneous and multi-pipeline test locally with v1.6 rc3(same SOF hash with above).

**Comment by plbossart** [comment]
@fredoh9 is there a way we can comb through test results to see when the errors started to show up?
It could be that the errors were always present but somehow masked, but if on the contrary we have a case where errors didn't exist then at least we can start bisecting.

Thanks for your help on this!

**Comment by fredoh9** [comment]
@plbossart yes, we have a test result database(TCR). At this moment I cannot connect to the site. I will filter test results to see from when we have this error in BSW/BYT again.

BTW, I'm testing with simultaneous/multipipe on a BYT NOCODEC device locally. I can't reproduce the problem yet. The occurance rate get changed with local testing.

**Comment by fredoh9** [comment]
After searching through TCR, found good build and bad(first broken) build.

*Good build(dailiy build 2020-09-20)
- Kernel Branch: topic/sof-dev
- Kernel Commit: 33767414
- SOF Branch: master
- SOF Commit: 6e98d9dd

*Bad build(dailiy build 2020-09-21)
- Kernel Branch: topic/sof-dev
- Kernel Commit: 40e44b3a
- SOF Branch: master
- SOF Commit: 0a247928

After looking at the diff between two build, I can suspect linux build(but there is no clear candidate). To do git bisect, I need to find solid way to reproduce this problem with my engineering build.

*Linux diff
40e44b3a8841 ASoC: SOF: sof-audio: remove goto used for force-nocodec support
e92ffa9a96fa ASoC: Intel: add support for new SoundWire hardware layout on TGL
c5f920836b8f ASoC: Intel: sof_sdw_rt700: add codec prefix
3b9bbfb9f2c1 ASoC: Intel: sof_sdw: remove hard-coded codec_conf table
9e86aeabd947 ASoC: Intel: add codec name prefix to ACPI machine description
fd6a8f6c867e ASoC: hdac: make SOF HDA codec driver probe deterministic
f9f2b0574989 Revert "acpi: blacklist: remove quirk for Dell XPS13 when SOF is enabled"
253d57be7de4 Revert "ASoC: Intel: Kconfig: filter out not-recommended features"
75779bc0ee5a ASoC: SOF: imx: add missing MODULE_LICENSE() for imx-common
0cfb9952cc1a travis: add comments and learnings about git depth
7a5f88ff0048 fixup! ASOC: Intel: sof_sdw: restore playback functionality with max98373 amps
337674140e88 ASoC: SOF: topology: remove const in sizeof()

*SOF diff (No practical change)
0a247928b travis: upgrade distribution to Ubuntu 20.04
aa20048e9 travis: fold long lines; fixes the last yamllint warnings
6e98d9dde CODEOWNERS: really add marc-hb to scripts

**Comment by plbossart** [comment]
@fredoh9 have you been able to reproduce the results of the build with kernel good and bad commits ?

**Comment by fredoh9** [comment]
@plbossart Yes, I did bisect and get the result also. But the result didn't make sense to me, not sure good build/bad build is solid. This error is not 100% reproducible.

This is my git bisect. Set initial good as 3376741, bad to 40e44b3(above build info)
I used only BTY_MB_NOCODEC device. run 3 test cases to decide good or bad.

- simultaneous-playback-capture.sh 50 loop
- multiple-pipeline-playback.sh 50 loop
- multiple-pipeline-capture.sh 50 loop

As a result,
3b9bbfb9f2c1a41d666c6ea66073ee1f215c5ada (ASoC: Intel: sof_sdw: remove hard-coded codec_conf table) is the first bad commit

Even looking at the change, I don't see any connection with the failure.

**Comment by plbossart** [comment]
@fredoh9 this commit ID has nothing to do with the nocodec mode, the error seems random then.

**Comment by marc-hb** [comment]
> Yes, I did bisect and get the result also. But the result didn't make sense to me, not sure good build/bad build is solid. This error is not 100% reproducible.

Bisecting requires rock-solid reproduction, otherwise it's just a huge waste of time.

**Comment by plbossart** [comment]
we've lost context on this, closing
