### ISSUE TITLE
Mismatched core power down in snd_sof_dsp_remove()

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#2494]
The DSP cores are powered on when the run op is invoked. 

If snd_sof_load_firmware() fails (which is before run is invoked), snd_sof_dsp_remove() in the unwind path powering down the cores fails because they were never powered on.
sof_probe_continue()
    -> if snd_sof_load_firmware() < 0
         -> snd_sof_remove()
               -> snd_sof_core_power_down() --> FAIL

Similarly, in snd_sof_run_firmware(), the cores are already powered down in all error unwind paths, so snd_sof_dsp_remove() in the SOF core probe unwind path will fail too.

**Comment by bardliao** [comment]
Can we use ``sdev->fw_state`` to check if we need to do snd_sof_core_power_down() or not?
Like
```patch
--- a/sound/soc/sof/intel/hda.c
+++ b/sound/soc/sof/intel/hda.c
@@ -935,7 +936,7 @@ int hda_dsp_remove(struct snd_sof_dev *sdev)
                                SOF_HDA_INT_CTRL_EN | SOF_HDA_INT_GLOBAL_EN, 0);

        /* disable cores */
-       if (chip)
+       if (chip && sdev->fw_state == SOF_FW_BOOT_COMPLETE)
                snd_sof_dsp_core_power_down(sdev, BIT(0));

        /* disable DSP */

```

**Comment by ranj063** [comment]
> Can we use `sdev->fw_state` to check if we need to do snd_sof_core_power_down() or not?
> Like
> 
> ```diff
> --- a/sound/soc/sof/intel/hda.c
> +++ b/sound/soc/sof/intel/hda.c
> @@ -935,7 +936,7 @@ int hda_dsp_remove(struct snd_sof_dev *sdev)
>                                 SOF_HDA_INT_CTRL_EN | SOF_HDA_INT_GLOBAL_EN, 0);
> 
>         /* disable cores */
> -       if (chip)
> +       if (chip && sdev->fw_state == SOF_FW_BOOT_COMPLETE)
>                 snd_sof_dsp_core_power_down(sdev, BIT(0));
> 
>         /* disable DSP */
> ```

Possibly but I'm also thinking we should also protect the power down op with a check for enabled_cores_mask() and do nothing if the core is not enabled.

**Comment by keyonjie** [comment]
@ranj063 @bardliao let's mark it to P2 and assign it to you.

**Comment by bardliao** [comment]
> Possibly but I'm also thinking we should also protect the power down op with a check for enabled_cores_mask() and do nothing if the core is not enabled.

@ranj063 Please see https://github.com/thesofproject/linux/pull/2497
