### ISSUE TITLE
Dell XPS 15 9500 (2020) - all speakers not working

### ISSUE THREAD

**Issue by bv86** [thesofproject/linux#2505]
Hello,

I'm quite new to this, let me know which information you may need, but running Arch with latest soundwire-dkms, I get these messages in dmesg when trying to use the module snd-sof-pci:

[  487.848500] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[  487.848511] acpi PRP00001:00: ACPI reports 4 SDW Link devices
[  487.848514] acpi PRP00001:00: Link 0 not selected in firmware
[  487.848516] acpi PRP00001:00: Link 1 not selected in firmware
[  487.848517] acpi PRP00001:00: Link 2 not selected in firmware
[  487.848519] acpi PRP00001:00: Link 3 not selected in firmware
[  487.848520] sof-audio-pci 0000:00:1f.3: SOF PCI driver not selected, aborting probe

Do you know how I could get the different links to be selected in firmware?

**Comment by bv86** [comment]
I blacklisted snd-hda-intel, which kind of worked but with only 2 speakers out of 4 speakers I guess, with no bass at all.

Another thing I tried is "options snd-intel-dspcfg dsp_driver=3", this will give me this in dmesg: https://pastebin.com/jLn905pw
And then I get sound, which is better than with snd-hda-intel, but not yes as powerfull and full as on Windows, so I guess not all speakers are working. With this option, here is also the output of alsa-info.sh : https://pastebin.com/Gj9WGijf

I'd be willing to do more tests / provide logs if necessary, just let me know how to help.

**Comment by plbossart** [comment]
Thanks for reporting this @bv86.

Can you re-check the dmesg logs, it looks to me like you are using the HDAudio interface, not SoundWire? And if SOF is not selected, it could also be that you don't have SoundWire or DMIC interfaces, in which case the legacy snd-hda-intel might be good enough.

Can you provide a link to the results of 'alsa-info'? in addition a link to the output of 'sudo dmidecode' would help, we use the system sku to identify Dell platforms with SoundWire capabilities.

It's possible that the volume levels are not right, you could try to play with alsamixer if the UCM defaults are not enough. We try to provide 'reasonable' values, but they might not be good enough on specific platforms. A dedicated UCM would be required here.

Another possibility is that in the Windows solution there is additional processing. I am afraid we are not going to be able to match this capability with a generic SOF firmware, this might be something that is Dell-specific.

**Comment by bv86** [comment]
Sorry for my late reply, 

here is a fresh dmesg.log (it is verbose because I added some options from another post here to have more debug information): https://pastebin.com/XYwSydpX

here is dmidecode: https://pastebin.com/XahMEuua

here is the output of alsa-info: https://pastebin.com/HJXKWqXV

Hope it helps.

**Comment by plbossart** [comment]
Adding @kv2019i 

@bv86 thanks for the logs. I can confirm you don't have SoundWire enabled on this device, it's plain vanilla HDAudio with no DMIC 

````
([   39.332629] sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 0
````

The SOF driver does not give you any benefits over the legacy HDaudio driver, so you could just as well remove "options snd-intel-dspcfg dsp_driver=3".

Can you re-check what happens with and without this option, and let us know the results?

**Comment by bv86** [comment]
So without this option, another driver is loaded: snd_hda_intel.
The sound is not bad, but not as full yet as on Windows. I'm not sure if it's because there is some surround added by Windows drivers or if it's because not all speakers are working on Linux. 
Just in case, here is the output of alsa-info without the dsp_driver=3 option: https://pastebin.com/A1JvTjM7

Also, one test I did try was to comment:
	SND_PCI_QUIRK(0x1028, 0x097d, "Dell Precision", ALC289_FIXUP_DUAL_SPK),
in patch_realtek.c. The patch does help, because without it the sound is very flat, without bass. 

So in the end, the current sound I have with snd_hda_intel is correct I would say. 

This is probably not the place to ask this, but is there a way to use some kind of equalizer to tune things up a bit?

**Comment by RanderWang** [comment]
> So without this option, another driver is loaded: snd_hda_intel.
> The sound is not bad, but not as full yet as on Windows. I'm not sure if it's because there is some surround added by Windows drivers or if it's because not all speakers are working on Linux.
> Just in case, here is the output of alsa-info without the dsp_driver=3 option: https://pastebin.com/A1JvTjM7
> 
> Also, one test I did try was to comment:
> SND_PCI_QUIRK(0x1028, 0x097d, "Dell Precision", ALC289_FIXUP_DUAL_SPK),
> in patch_realtek.c. The patch does help, because without it the sound is very flat, without bass.
> 
> So in the end, the current sound I have with snd_hda_intel is correct I would say.
> 
> This is probably not the place to ask this, but is there a way to use some kind of equalizer to tune things up a bit?

how about to use equalizer in your audio player ?  You can use  some friendly graphics interface to archive it. Or you need to play with a batch of binary when using SOF.

**Comment by kv2019i** [comment]
@bv86 wrote:
> Also, one test I did try was to comment:
> SND_PCI_QUIRK(0x1028, 0x097d, "Dell Precision", ALC289_FIXUP_DUAL_SPK),
> in patch_realtek.c. The patch does help, because without it the sound is very flat, without bass.

Hmm, you commented it _out_? This sounds odd as the patch that added is was specifically to enable the bass speakers:
https://lore.kernel.org/r/229c7efa2b474a16b7d8a916cd096b68@realtek.com

If this is indeed the case, can you open a bug in bugzilla.kernel.org ? This needs to be patches in the codec driver.

> This is probably not the place to ask this, but is there a way to use some kind of equalizer to tune things up a bit?

There are multiple ways to do this. Now that you are using snd-hda-intel, you could start with:
https://wiki.archlinux.org/index.php/PulseAudio#PulseEffects

I'll propose to close this bug here as there is nothing to fix on SOF side.

**Comment by bv86** [comment]
> @bv86 wrote:
> 
> > Also, one test I did try was to comment:
> > SND_PCI_QUIRK(0x1028, 0x097d, "Dell Precision", ALC289_FIXUP_DUAL_SPK),
> > in patch_realtek.c. The patch does help, because without it the sound is very flat, without bass.
> 
> Hmm, you commented it _out_? This sounds odd as the patch that added is was specifically to enable the bass speakers:
> https://lore.kernel.org/r/229c7efa2b474a16b7d8a916cd096b68@realtek.com

Just to try, but it is worse if I comment it out, so in the end I reverted my changes.

> 
> If this is indeed the case, can you open a bug in bugzilla.kernel.org ? This needs to be patches in the codec driver.
> 
> > This is probably not the place to ask this, but is there a way to use some kind of equalizer to tune things up a bit?
> 
> There are multiple ways to do this. Now that you are using snd-hda-intel, you could start with:
> https://wiki.archlinux.org/index.php/PulseAudio#PulseEffects
> 
> I'll propose to close this bug here as there is nothing to fix on SOF side.

No problem to close this bug, sorry for the trouble.

**Comment by kv2019i** [comment]
Thanks @bv86 ! It's always good to file a ticket, so no problem there. And ack on the FIXUP_DUAL_SPK patch behaviour.
