### ISSUE TITLE
[TGL] [SDW]: max98373/rt5682 SDW error at soc_component_read_no_lock during suspend

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#2510]
Follow-up tracker to issue discussed at https://github.com/thesofproject/linux/issues/2473#issuecomment-707584225
Issue observed during suspend..
Recipe: TGL SoF_V010

LOG: 
[dmesg_regmap_print.log](https://github.com/thesofproject/linux/files/5383854/dmesg_regmap_print.log)

```
[   17.837742] naveen _regmap_read- Line=2545 reg=0, cache_bypass=0, cache_only=0, regmap_readable=-1362004410, ret=0
[   17.838644] **rt5682 sdw:0:25d:5682:0: ASoC: error at soc_component_read_no_lock on sdw:0:25d:5682:0: -16**
..
[ 18.144826] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 18.144846] naveen _regmap_read+ Line=2521 reg=8276, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144847] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 18.144864] naveen _regmap_read+ Line=2521 reg=8278, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144869] naveen _regmap_read+ Line=2521 reg=8274, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144870] naveen _regmap_read+ Line=2521 reg=8274, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144873] naveen _regmap_read+ Line=2521 reg=8274, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144878] naveen _regmap_read+ Line=2521 reg=8273, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144881] naveen _regmap_read+ Line=2521 reg=8277, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144882] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16

```
Registers in reference:
RT5682_RESET
MAX98373_R2054_MEAS_ADC_PVDD_CH_READBACK
MAX98373_R2055_MEAS_ADC_THERM_CH_READBACK
MAX98373_R20B6_BDE_CUR_STATE_READBACK

**Comment by keyonjie** [comment]
@naveen-manohar this is known limitation, @naveen-manohar  shall we close it as won't fix or invalid?

**Comment by naveen-manohar** [comment]
I will recheck post https://github.com/thesofproject/sof/issues/3541 is resolved.. And re-open if any functional issue I do notice because of this error.. Currently I haven't noticed any issue so its good to be closed.

**Comment by cujomalainey** [comment]
@keyonjie @mengdonglin if this is a non-issue then we should at least fix the log spam. To the uninformed observer this looks very bad.

**Comment by plbossart** [comment]
I think https://github.com/thesofproject/linux/pull/2521 is the 'right' way to fix this, e.g. if the user wants to get the value of a volatile register while the device is in suspend a -EBUSY is not a relevant answer. The device should be resumed.

@naveen-manohar @RanderWang I don't have a device so you guys will have to test for me, thanks!

**Comment by keyonjie** [comment]
@bardliao provide a fix https://github.com/thesofproject/linux/pull/2532 for it, @ryans-lee can you help to review as it is a codec fix?

**Comment by keyonjie** [comment]
@ryans-lee as it is codec issue, can you help to check it? if it is not an issue, feel free to comment and close it.

**Comment by mengdonglin** [comment]
Ongoing discussion in ALSA mailing list https://mailman.alsa-project.org/pipermail/alsa-devel/2020-November/176822.html

**Comment by plbossart** [comment]
@bardliao I think this issue with volatile registers is fixed so I'll close. If you disagree please reopen.
