### ISSUE TITLE
[FEATURE] Restore trace filters after FW suspend/resume

### ISSUE THREAD

**Issue by ktrzcinx** [thesofproject/linux#2528]
Trace filtering definition path looks like:

1. sof-logger read filters definition from argument list
2. sof-logger translate human readable form of components definition to UUID numbers using ldc file content
3. sof-logger saves translated filters values to `/sys/kernel/debug/sof/filter`
4. kernel translates filters to IPC message and send it to FW
5. firmware applies filter for selected components (in runtime memory)

Consequence of keeping active filter values only in firmware runtime memory is restoring default settings after firmware reboot eg. because of PM.

Current possible solution is to disable PM before settings filters (details https://github.com/thesofproject/sof-docs/pull/299).

@xiulipan give an idea to automate this mechanism a little bit (https://github.com/thesofproject/sof-docs/pull/299#discussion_r508970421). There are a two basic questions about it.
1. If is it needed.
2. How to do that.

For second question there are a few ideas:
1. Keeping IPC for filter setup in kernel space and send it before/after CTX_RESTORE, This solutions keeps user-space application data in kernel system, what is not a good practice. Moreover this value may used long after sof-logger application close up, and may try to modify already deleted/modified elements what will raise errors.

2. Notify user space application about PM status change, eg by new debugfs file or `sysfs_notify` (maybe there's some better suited mechanism?). Here new communication channel between sof-logger and kernel, perhaps reading 

3. Some other ideas.

**Comment by plbossart** [comment]
This topic has not received any feedback, I'll add @kv2019i @marc-hb and @lgirdwood for comments (if you've worked on sof-logger or the trace you're 'it').

**Comment by lgirdwood** [comment]
This will be changing with Zephyr so we will need to work out how filtering will work with Zephyr first.  Lets park this now, and once @marc-hb has completed the Zephyr trace work we can revisit (since this will require Zephyr tooling).

**Comment by plbossart** [comment]
closing since we have no plans to deliver anything here. If relevant please re-open as needed
