### ISSUE TITLE
[BUG][CML][CI][SDW] Clock Stop prepare failed for slave 1

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#2536]
In daily report 617, below error messages shows in dmesg in suspend-resume-with-playback test case.

```
kernel: [ 7539.803449] intel-sdw intel-sdw.2: Msg Ack not received
kernel: [ 7539.803456] intel-sdw intel-sdw.2: Msg ignored for Slave 15
kernel: [ 7539.803462] soundwire sdw-master-2: ClockStopNow Broadcast msg ignored -61
kernel: [ 7539.803890] intel-sdw intel-sdw.3: Msg Ack not received
kernel: [ 7539.803894] intel-sdw intel-sdw.3: Msg ignored for Slave 1
kernel: [ 7539.803900] rt715 sdw:3:25d:715:0: Clock Stop prepare failed for slave: -61
kernel: [ 7539.803910] rt715 sdw:3:25d:715:0: pre-prepare failed:-61
kernel: [ 7539.803916] intel-sdw intel-sdw.3: prepare clock stop failed -61
kernel: [ 7539.803921] intel-sdw intel-sdw.3: cannot enable clock stop on suspend
```

**Recipe**
Kernel Branch:  topic/sof-dev
Kernel Commit:  8290bd62
SOF Branch:  master
SOF Commit:  db09bb80
TPLG:  sof-cml-rt711-rt1308-mono-rt715.tplg

**Comment by aiChaoSONG** [comment]
@RanderWang @plbossart  Please help to confirm if this is an issue or false failure

**Comment by plbossart** [comment]
````
kernel: [ 7539.803456] intel-sdw intel-sdw.2: Msg ignored for Slave 15
````
is a really bad error. It's essentially a broadcast command that was not received, not good at all.

Can you please provide the command line used to get this result?

**Comment by RanderWang** [comment]
> ```
> kernel: [ 7539.803456] intel-sdw intel-sdw.2: Msg ignored for Slave 15
> ```
> 
> is a really bad error. It's essentially a broadcast command that was not received, not good at all.
> 
> Can you please provide the command line used to get this result?

@plbossart  there is no slave on link2, is this error ? thanks!

**Comment by plbossart** [comment]
> > ```
> > kernel: [ 7539.803456] intel-sdw intel-sdw.2: Msg ignored for Slave 15
> > ```
> > 
> > 
> > is a really bad error. It's essentially a broadcast command that was not received, not good at all.
> > Can you please provide the command line used to get this result?
> 
> @plbossart there is no slave on link2, is this error ? thanks!

Sorry, no. Somehow I saw the TGL title and was confused. On CML-mono you're right this is not a problem.

That said, the other errors are on link3 and are real bad as well

````
kernel: [ 7539.803890] intel-sdw intel-sdw.3: Msg Ack not received
kernel: [ 7539.803894] intel-sdw intel-sdw.3: Msg ignored for Slave 1
kernel: [ 7539.803900] rt715 sdw:3:25d:715:0: Clock Stop prepare failed for slave: -61
kernel: [ 7539.803910] rt715 sdw:3:25d:715:0: pre-prepare failed:-61
kernel: [ 7539.803916] intel-sdw intel-sdw.3: prepare clock stop failed -61
kernel: [ 7539.803921] intel-sdw intel-sdw.3: cannot enable clock stop on suspend
````

**Comment by aiChaoSONG** [comment]
After go through daily report of this week, the issue is not reproduced, close.
