### ISSUE TITLE
HP Zbook 17 G6:  error: ipc error for 0x50010000 size 108

### ISSUE THREAD

**Issue by chmooreck** [thesofproject/linux#2545]
```
[   12.752152] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000
[   12.752155] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000
[   12.752248] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x50010000 size 108
[   12.752250] sof-audio-pci 0000:00:1f.3: error: set/get ctrl ipc comp 58
[   12.752251] sof-audio-pci 0000:00:1f.3: error: failed kcontrol value set for widget: 58
[   12.752252] sof-audio-pci 0000:00:1f.3: error: restoring kcontrols after resume
[   12.752253] sof-audio-pci 0000:00:1f.3: error: failed to restore pipeline after resume -22
[   12.752258] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_pm_runtime_get on 0000:00:1f.3: -22

```

sof-firmware 1.6

kernel:
```
commit 70fe32e776dafb4b03581d62a4569f65c2f13ada (grafted, HEAD -> topic/sof-dev, origin/topic/sof-dev, origin/HEAD)
Author: Jack Yu <jack.yu@realtek.com>
Date:   Fri Oct 23 17:23:34 2020 +0800

    fixup! ASoC: rt715-sdca: First version of rt715 sdw sdca codec driver
    
    Add rt715_sdca prefix for both static and  non-static symbols.
    
    Signed-off-by: Jack Yu <jack.yu@realtek.com>
```

$ dmesg | grep -e "snd\|sof\|ASoC\|hda"
[dmesg.log](https://github.com/thesofproject/linux/files/5466734/dmesg.log)

**Comment by plbossart** [comment]
Just to clarify @chmooreck did you install both the sof-cfl.ri firmware binary and intel/sof-tplg/sof-hda-generic-4ch.tplg from the same 1.6 package? I'd like to rule out a mismatch (though the ABI looks the same so not sure).

@kv2019i @juimonen FYI.

**Comment by chmooreck** [comment]
@plbossart you nailed it. I had firmware from 1.5.1 and topology from 1.6. After switching both to 1.6 sound works fine (including microphone). Thanks a lot for help.

Checked 5.9.2 kernel too - works fine.

**Comment by keyonjie** [comment]
Hi @chmooreck @plbossart  so shall we close this?

**Comment by chmooreck** [comment]
@keyonjie 
Yes. Sound works fine now - it was caused by mismatched versions of topology and firmware.
