### ISSUE TITLE
digital microphone detected on hardware which do not have internal microphone

### ISSUE THREAD

**Issue by shengyao** [thesofproject/linux#2551]
Tested on a Lenovo ThinkCentre

BIOS Version: M3SKT1AA (10/16/2020)

with Windows 10, no digital microphone detected.

but with Ubuntu 20.04, kernel version 5.6.0-1028-oem, will detect a digital microphone. dmesg shows:

[    4.033335] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[    4.033489] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver

I attached /sys/firmware/acpi/tables/NHLT
[NHLT.gz](https://github.com/thesofproject/linux/files/5480017/NHLT.gz)

**Comment by jason77-wang** [comment]
We met the similar issue on Lenovo Thinkcenter M720q and M720s, Please refer to: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1001

**Comment by perexg** [comment]
I think that we may add a skip list to snd-intel-dspcfg to avoid SOF activation based on PCI IDs or DMI info for this hardware with the invalid NHLT descriptors.

**Comment by plbossart** [comment]
@shengyao I don't have an NHLT parser and can't really look for errors, the parsing is horrible.
is there a way you can test with a more recent kernel? We added more traces to tell how many mics were found, and that would help us detect something weird.

@perexg agree, I am pretty sure folks copy-pasted BIOS stuff even when there's no DMIC... quirks are unavoidable I am afraid.
that said, even if there are no microphones on the hardware I think SOF should not break. the mic input would remain silent indeed but there's no real harm.

**Comment by shengyao** [comment]
@plbossart sure, just give me your kernel, I am glad to test.

**Comment by kv2019i** [comment]
@shengyao I did a manual parse of the NHTL dump you attached and it describes one PCH DMIC link with DeviceType=cAVS1.8-PDM. So it seems this is a copy-n-paste error in the BIOS.

Considering this should be harmless and may be potentially fixed in later BIOS update, maybe no quirk is needed either.

**Comment by kv2019i** [comment]
@plbossart @perexg I wrote a (very) simple python tool to parse the relevant bits of NHLT. Currently at:
https://github.com/thesofproject/sof-test/pull/488

**Comment by plbossart** [comment]
@shengyao if you have access to a Windows 10 machine, could you track which driver is used? I wonder if the Windows in-box driver is used, or the Intel SST driver. In the latter case, they would have to rely on a local configuration (e.g. inf file) to disable the dmics or something.

**Comment by plbossart** [comment]
Note that we have a existing kernel parameter to override NHLT

````
modinfo snd_sof_intel_hda_common
filename:       /lib/modules/5.10.0-rc1-test+/kernel/sound/soc/sof/intel/snd-sof-intel-hda-common.ko
import_ns:      SOUNDWIRE_INTEL_INIT
import_ns:      SND_SOC_SOF_XTENSA
import_ns:      SND_SOC_SOF_HDA_AUDIO_CODEC_I915
import_ns:      SND_SOC_SOF_HDA_AUDIO_CODEC
license:        Dual BSD/GPL
depends:        snd-soc-acpi-intel-match,snd-pcm,snd-sof,soundwire-intel,snd-sof-intel-hda,snd-intel-dspcfg,snd-hda-ext-core,snd-hda-core,snd-soc-core,snd-soc-acpi,snd-soc-hdac-hda,snd-sof-xtensa-dsp
retpoline:      Y
intree:         Y
name:           snd_sof_intel_hda_common
vermagic:       5.10.0-rc1-test+ SMP mod_unload 
parm:           codec_mask:SOF HDA codec mask for probing (int)
parm:           enable_trace_D0I3_S0:SOF HDA enable trace when the DSP is in D0I3 in S0 (bool)
parm:           sdw_clock_stop_quirks:SOF SoundWire clock stop quirks (int)
parm:           use_msi:SOF HDA use PCI MSI mode (bool)
parm:           hda_model:Use the given HDA board model. (charp)
parm:           dmic_num:SOF HDA DMIC number (int)
parm:           use_common_hdmi:SOF HDA use common HDMI codec driver (bool)
````

so adding this in /etc/modprobe.d/alsa-base.conf would ignore the bad NHLT information.

````
options snd_sof_intel_hda_common dmic_num=0
````

**Comment by mrhpearson** [comment]
I've raised this with the ThinkCentre BIOS team and asked them to investigate.
(LO-885 for my reference and tracking). 
I'll update when I hear back from them
Mark

**Comment by mrhpearson** [comment]
Apparently BIOS M1UKT62A fixes this issue. My colleague tested it with Fedora33 on the M720 and it worked.

The good news - the BIOS is available on the Lenovo support site and has an iso for creating a bootable image to do the update.
The bad news - the desktop team haven't commited to putting this on LVFS I'm afraid. Still working on that but I don't have an ETA for that to happen.

Let me know if any questions
Mark

**Comment by plbossart** [comment]
Closing since there is both a kernel work-around and a BIOS update. Thanks @mrhpearson for following-up.
