### ISSUE TITLE
[TGL][SDW] warnings related to HDMI converters

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2573]
Filing an issue to keep track of this report on Volteer:

````
[  112.425297] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 4

[  112.425298] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 5

[  112.425299] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 6

[  112.425301] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 7

[  112.425302] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 8
````

No idea if this is a real problem @kv2019i ?

**Comment by kv2019i** [comment]
I'lll take this. This shouldn't be a warning.

**Comment by kv2019i** [comment]
I looked at this today. The message is harmless, but now with TGL and newer having a lot more pins, this uncovers a design issue in the way we plug SOF into patch_hdmi.c. I didn't notice this back when doing the original version as the pin count back then was same as converter count, but that no longer holds with TGL and newer.

I double-checked this today and this has no functional impact. So conclusion remains that these warnings are still harmless, but I'm now comtemplating on whether I should fix this on codec driver side. "hcodec->pcm_list_head" should only have as many entries as there are converters.

**Comment by kv2019i** [comment]
Also related to https://github.com/alsa-project/alsa-lib/pull/118 and whether to make changes in snd-hda-intel driver side as well.

**Comment by plbossart** [comment]
@kv2019i is this still on your TODO list?

**Comment by kv2019i** [comment]
Yes @plbossart - it's a list long list but this still needs to be fixed.

**Comment by plbossart** [comment]
@kv2019i ping

**Comment by kv2019i** [comment]
@plbossart Will try to tackle in 2021 still.

**Comment by kv2019i** [comment]
@plbossart Didn't quite make it in 2021, but better late than never. Draft available, this needs quite a bit of testing as we need to change code that is used by pretty much all HDA platforms across vendors and generations.

**Comment by kv2019i** [comment]
Fix sent for review upstream: https://lore.kernel.org/alsa-devel/20220414150516.3638283-1-kai.vehmanen@linux.intel.com/T/#u

**Comment by kv2019i** [comment]
Merged upstream, closing here.
