### ISSUE TITLE
[SDW] Bus clash detected

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#2578]
Bus clash detected error can be seen on many SoundWire devices on check-suspend-resume-with-playback-25.sh and check-suspend-resume-with-capture-25.sh test  (SOF v1.6.1 release test report ID 828)

Ideally, HW will be recovered from bus clash. But it could also be a sign.  So create a issue to track it.

Recipe:
Kernel: topic/sof-dev 38e180a4
SOF : master 90955de93e8f
 
Note that ``Bus clash detected`` doesn't contain any error key words, so CI didn't fail with the ``Bus clash detected`` log before.
It means that the issue could already exist for a while. 

@RanderWang @plbossart FYI

**Comment by mengdonglin** [comment]
This issue can also be reproduced in daily test report ID 829, on CML Oly* device, in the same test case check-suspend-resume-with-playback-25.sh.

**Comment by marc-hb** [comment]
@bardliao should the bus clash `ignore_str` filter be removed in `sof-test/tools/sof-kernel-log-check.sh`? See https://github.com/thesofproject/sof-test/pull/529/files

**Comment by bardliao** [comment]
> @bardliao should the bus clash `ignore_str` filter be removed in `sof-test/tools/sof-kernel-log-check.sh`? See https://github.com/thesofproject/sof-test/pull/529/files

Yes, we should not ignore "Bus clash"

**Comment by marc-hb** [comment]
Can you please delete the corresponding 2-3 lines?

**Comment by bardliao** [comment]
> Can you please delete the corresponding 2-3 lines?

Done https://github.com/thesofproject/sof-test/pull/542
