### ISSUE TITLE
Test check-kmod-load-unload.sh and check-kmod-load-unload-after-playback.sh fail

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#2589]
The run of test case 

`./check-kmod-load-unload.sh -l 50
`

Fails with error 

```
2020-11-30 13:01:05 UTC [ERROR] Caught kernel log error
===========================>>
[ 1036.878530] kernel: rt5682 i2c-10EC5682:00: Device with ID register ffff9acc is not rt5682
<<===========================

```

Script `check-kmod-load-unload-after-playback.sh` fails the the same error. The platform is BYT Minnowboard Max with sof-byt-nocodec.tplg topology. The tests fail also without repeats (without "-l"). The fresh kernel and FW versions are:

Kernel Branch: topic/sof-dev
Kernel Commit: 47f55b1feaa8
SOF Branch: master
SOF Commit: c8ae78ab0
sof-test Branch: master
sof-test Commit: 949e08e

[check-kmod-load-unload.txt](https://github.com/thesofproject/linux/files/5616088/check-kmod-load-unload.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/5616090/dmesg.txt)

**Comment by plbossart** [comment]
that's a CI issue, I don't know why the platform tries to load the RT5682 driver when they can use the LPEX.asl example.

@aiChaoSONG @xiulipan please fix CI devices and which file is used.

**Comment by singalsu** [comment]
@plbossart I think it's my fault, I didn't realize. This device used to have a codec board but I removed it to make a wired SSP loopback a while ago when we discussed if channels swap issue would be due to LBM. I should purge the RT5682 .asl install. I wonder if it can be done remotely to office based device without anything but ssh access.

**Comment by singalsu** [comment]
Close, this is not a real issue, just wrong usage.

**Comment by plbossart** [comment]
> @plbossart I think it's my fault, I didn't realize. This device used to have a codec board but I removed it to make a wired SSP loopback a while ago when we discussed if channels swap issue would be due to LBM. I should purge the RT5682 .asl install. I wonder if it can be done remotely to office based device without anything but ssh access.

yes, you can ssh into the device, then edit a file (/boot/EFI/.../startup.nsh, see details in the SOF documentation) and replace the existing RT5682 reference by LPEX. make sure the LPEX file is present!
