### ISSUE TITLE
[BUG][TGL] Internal DMIC with SST does not record sound

### ISSUE THREAD

**Issue by starnight** [thesofproject/linux#2592]
We have laptops ASUS B9400CEA and UX482EG which equip with i5-1135G7 and i7-1165G7.  The internal DMIC cannot record any sound.  I tested with mainline kernel 5.10-rc5 and place the firmware as following path:
```
$ ls -l /lib/firmware/intel/sof-tplg/ | grep tgl
-rw-r--r-- 2 root root 25647 Jan  1  1970 sof-tgl-nocodec.tplg
-rw-r--r-- 2 root root 25071 Jan  1  1970 sof-tgl-rt711-rt1308-nohdmi.tplg
-rw-r--r-- 2 root root 44607 Jan  1  1970 sof-tgl-rt711-rt1308.tplg
```
These come from ftp://ftp.alsa-project.org/pub/misc/sof/sof-firmware-1.4.2.tar.bz2

```
$ ls -l /lib/firmware/intel/sof/ | grep tgl
lrwxrwxrwx 2 root root     17 Nov 17 07:38 sof-tgl.ri -> signed/sof-tgl.ri
$ ls -l /lib/firmware/intel/sof/signed/ | grep tgl
-rw-r--r-- 1 root root 352256 Nov 25 16:20 sof-tgl.ri
$ ls -l /lib/firmware/intel/sof/signed/debug/ | grep tgl
-rw-r--r-- 1 root root 86116 Nov 25 16:20 sof-tgl.ldc
```
These come from TGL_SOF_FW_prod_signed_v0.6.2_release 

System loads module sof-audio-pci as the audio driver:
```
$ sudo lspci -nnvs 0000:00:1f.3
0000:00:1f.3 Multimedia audio controller [0401]: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller [8086:a0c8] (rev 20)
Subsystem: ASUSTeK Computer Inc. Tiger Lake-LP Smart Sound Technology Audio Controller [1043:1512]
Flags: bus master, fast devsel, latency 32, IRQ 200
Memory at 603f298000 (64-bit, non-prefetchable) [size=16K]
Memory at 603f000000 (64-bit, non-prefetchable) [size=1M]
Capabilities: [50] Power Management version 3
Capabilities: [80] Vendor Specific Information: Len=14 <?>
Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
Kernel driver in use: sof-audio-pci
Kernel modules: snd_hda_intel, snd_sof_pci
```
The DMIC is listed on system:
```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 6: DMIC48kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 7: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
However, when I try to record some audio with the DMIC at the driver level manually, it shows errors as following:
```
$ arecord -D hw:0,1 -f dat test-dmic.wav
arecord: main:828: audio open error: Invalid argument
$ arecord -D hw:0,6 -f dat test-dmic.wav
Recording WAVE 'test-dmic.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
arecord: set_params:1345: Channels count non available
$ arecord -D hw:0,7 -f dat test-dmic.wav
Recording WAVE 'test-dmic.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
arecord: set_params:1345: Channels count non available
```
So, there is no recording.
[dmesg.log](https://github.com/thesofproject/linux/files/5620210/dmesg.log)

**Comment by cooper-chiou** [comment]
This issue is reported by "Endless OS" team, and their codebase is "latest mainline kernel 5.10.0-rc5" + "TGL Linux SOF v0.6.2 production key signed firmware".

@starnight  please provide the audio HW block design information. And please try "sof-dev" kernel to reproduce issue.

**Comment by juimonen** [comment]
@cooper-chiou dmesg shows it should have 4 dmics... so we should have 4 channel stream. Could you do something like 
"amixer contents | grep -i dmic -A3", we could see how many channels alsa is giving us. Also you could then try the recording with -C 4 flags. There could be possibly a mismtch between kernel and topology also...

**Comment by juimonen** [comment]
@cooper-chiou actually for 4 dmic devices you need this: https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=fca18e62984a0d797da8379a422a6bb644d68244

and it is not yet in 5.10.0-rc5

**Comment by starnight** [comment]
>  Could you do something like "amixer contents | grep -i dmic -A3", we could see how many channels alsa is giving us.
```
amixer contents | grep -i Dmic -A3
numid=43,iface=MIXER,name='Dmic0 Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=on,on
numid=42,iface=MIXER,name='Dmic0 Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=70,step=0
  : values=50,50
  | dBscale-min=-50.00dB,step=1.00dB,mute=1
numid=45,iface=MIXER,name='Dmic1 Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=70,step=0
  : values=50,50
  | dBscale-min=-50.00dB,step=1.00dB,mute=1
```

**Comment by juimonen** [comment]
@starnight thanks, so I think what happens here is that dmic is creating 4 dmic device in firmware, but because of the missing kernel patch mentioned above, we try to connect 2-ch stream to 4-ch dmic ->fail. Are you able to try this with sof-kernel or cherry-pick the above mentioned patch? So my suspicion here is that firmware/kernel are not in sync...

**Comment by juimonen** [comment]
@starnight sorry, can you still try to record with just:
 arecord -Dhw:0,6 testi.wav -d 3 --dump-hw-params

so you could see what are the params alsa is giving to you? above you are specifying the format as "dat", which might not work...

then you could vary the format like with 
 arecord -Dhw:0,6 -r 48000 -f S16_LE -c 4 testi.wav -d 3 --dump-hw-params, if it has 4 channels etc...

**Comment by starnight** [comment]
Tried sof-kernel at [commit d1968d3b503 ("fixup! soundwire: use consistent format for Slave devID logs")](https://github.com/thesofproject/linux/commit/d1968d3b5031ca82e230b1c876087a944929cd1e), but seems get same result
```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 6: DMIC48kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 7: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ sudo arecord -D hw:0,6 -f dat -C 4 test-dmic.wav
Recording WAVE '4' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
arecord: set_params:1345: Channels count non available
$ sudo arecord -D hw:0,7 -f dat -C 4 test-dmic.wav
Recording WAVE '4' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
arecord: set_params:1345: Channels count non available

$ sudo amixer contents | grep -i Dmic -A3
numid=39,iface=MIXER,name='Dmic0 Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=on,on
numid=38,iface=MIXER,name='Dmic0 Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=70,step=0
  : values=50,50
  | dBscale-min=-50.00dB,step=1.00dB,mute=1
numid=41,iface=MIXER,name='Dmic1 Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=70,step=0
  : values=50,50
  | dBscale-min=-50.00dB,step=1.00dB,mute=1
```

I also upload the building config.  Do I miss some things? 
[config.txt](https://github.com/thesofproject/linux/files/5621803/config.txt)
[dmesg.log](https://github.com/thesofproject/linux/files/5621830/dmesg.log)

**Comment by juimonen** [comment]
@starnight please remove the "-f dat" from the arecord command line and put also --dump-hw-params

**Comment by juimonen** [comment]
@starnight and the "channel" is not capital "-C" but "-c"

**Comment by juimonen** [comment]
@starnight so please copy the exact command line from my above comment:
arecord -Dhw:0,6 -r 48000 -f S16_LE -c 4 testi.wav -d 3 --dump-hw-params

**Comment by starnight** [comment]
Oops!  Time slips!
Tested again with sof-kernel at [commit d1968d3b503 ("fixup! soundwire: use consistent format for Slave devID logs")](https://github.com/thesofproject/linux/commit/d1968d3b5031ca82e230b1c876087a944929cd1e):
```
$ arecord -Dhw:0,6 -r 48000 -f S16_LE -c 4 testi.wav -d 3 --dump-hw-params
Recording WAVE 'testi.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Channels 4
HW Params of device "hw:0,6":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S16_LE S24_LE S32_LE
SUBFORMAT:  STD
SAMPLE_BITS: [16 32]
FRAME_BITS: [64 128]
CHANNELS: 4
RATE: 48000
PERIOD_TIME: [250 42667)
PERIOD_SIZE: [12 2048]
PERIOD_BYTES: [192 16384]
PERIODS: [2 16]
BUFFER_TIME: [500 170667)
BUFFER_SIZE: [24 8192]
BUFFER_BYTES: [192 65536]
TICK_TIME: ALL
--------------------
```
The DMIC records some sound!

Will cherry pick the commit and test again.

**Comment by juimonen** [comment]
@starnight you might not actually even need the patch. The problem was originally that you we're trying to record with hardcoded 2 channel parameters from low level alsa interface (which was 4 channels). The patch is actually helping in controlling the volume of all 4 dmics.

So the 4 channel recording should just work (with correct low level params). If you have pulseaudio and latest ucm config, the dmics should open "automatically"

Anyway the patch is good to have -> you can properly control all channel volumes.

**Comment by juimonen** [comment]
@starnight so sorry about the hassle, I was somehow mistaking this as some tgl soundwire device, as it seems to be generic hda device. Also I didn't first notice the "-f dat" that you we're using, which means "forcibly record stereo data" -> alsa declines to do that as the device is 4 channels.

**Comment by starnight** [comment]
Is the ucm config in https://github.com/alsa-project/alsa-ucm-conf/ ?

**Comment by juimonen** [comment]
> Is the ucm config in https://github.com/alsa-project/alsa-ucm-conf/ ?

yes should be. The ucm is used in latest fedoras and ubuntus... and is at least somehow tested for example with lenovo x1 which has 4 dmics

**Comment by plbossart** [comment]
@cooper-chiou @starnight it's not clear to me why 5.10-rc5 would not work and topic/sof-dev would work, there's been no major changes to dmic apart from the ability to control volumes per channel. It'd be interesting to see if 5.10-rc1 works for you, that would give us an idea if there's a kernel patch missing.

**Comment by juimonen** [comment]
@plbossart it was a misunderstanding, both from reporter and me. 5.10-rc5 will probably work here, I just didn't notice the wrong arecord command line. 

If you want the full 4 ch dmic volume control in user space, then you need sof-dev.

**Comment by juimonen** [comment]
@starnight should we close this? I think sof is working as supposed to, so you just have 4ch dmic device as you have 4 physical dmics... If you find other issues, you can file new separate bugs.

**Comment by starnight** [comment]
Checked the mainline 5.10-rc5.  The sound is recorded by setting 4 channels with `arecord`.

**Comment by starnight** [comment]
After upgraded alsa-lib, alsa-utils, alsa-ucm-conf and alsa-topology-conf to version **1.2.4**, the internal DMIC works.  But, system hits issue #2617

**Comment by plbossart** [comment]
@starnight upgrading PulseAudio seems to solve #2617 so is there still an issue here?

**Comment by starnight** [comment]
No!  It is fine here now.  Thanks!
