### ISSUE TITLE
simultaneous playback and capture will cause Input/output error

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#263]
Summary:
When simultaneous playback and capture end, input/output error will occur.
This issue is moved from firmware issue https://github.com/thesofproject/sof/issues/180

Reproduce step:
```
test@test-CannonLake:~$ aplay -D hw:0,0 -c 2 -r 48000 -f s16_le /dev/zero -d 5 & arecord -D hw:0,0 -c 2 -r 48000 -f s16_le /dev/null -d 5
[1] 1611
Recording WAVE '/dev/null' : Signed 16 bit Little Endian, Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 48000 Hz, Rate 48000 Hz, Stereo
Stereo
arecord: pcm_read:2103: read error: Input/output error
[1]+  Done                    aplay -D hw:0,0 -c 2 -r 48000 -f s16_le /dev/zero -d 5
```
input/output error can reproduce every time.

Test env:
sof-master: 9b376d7
soft-master: 937032
kernel debug/v4.19-backport: 925637e3020ec5f5c058abd5944d8f7dbe4ff27a

Log:
sof-logger doesn't work due to firmware issue https://github.com/thesofproject/sof/issues/551
[dmesg.log](https://github.com/thesofproject/linux/files/2564367/dmesg.log)

**Comment by mengdonglin** [comment]
@keqiaozhang @keyonjie  Is this a common issue? Also happen on GLK?

**Comment by keqiaozhang** [comment]
@mengdonglin 
Yes, this is a common issue. This issue also happens on GLK and track in thesofproject/linux/issues/266.

**Comment by mengdonglin** [comment]
Duplicate to issue #266

**Comment by wenqingfu** [comment]
mark duplicate as closed
