### ISSUE TITLE
[ADL-S] [SDW] failed to runtime suspend

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#2633]
The /sys/devices/pci0000\:00/0000\:00\:1f.3/power/runtime_status always shows "active".

Nothing wrong is showed in dmesg.

**Comment by plbossart** [comment]
@libinyang there's nothing we can do with such reports. Closing. Please add a new report with dmesg logs w/ dynamic debug.

**Comment by libinyang** [comment]
This bug is fixed. The root cause is the rt711 onboard in hda mode is probed. And the sof is in SDW mode, which will cause the use count isn't back to 0. This will cause audio driver alwasy being active. After disabling HDA mode in BIOS, this bug is fixed.
