### ISSUE TITLE
[BUG][TGL] TGLU_VOLT_SDW has no sound when playback on speaker

### ISSUE THREAD

**Issue by RuiqingX** [thesofproject/linux#2637]
**Describe the bug**
On TGL Volteer device, we observed that sometimes there is no sound output through speaker(max98373) while the headset(rt5682) works well after OS boot. After investigation, we found fixed pattern to reproduce the issue:

1. reboot
2. use speaker-test to check if sound comes out from speaker
3. wait DSP to suspend (no operations on device > 6s)
4. repeat step 2 and step 3 several times (better > 10)
5. after several PM, there will be no sound through speaker.
Note: speaker always works well after kmod reload, and there is no error in the dmesg or sof-logger

Device
TGLU_VOLT_SDW with sh-tglu-volt-sdw-03

Environment
Kernel: { sof-dev 47f55b1f-1}
SOF: {c8ae78ab0e4e-3}
Platform: {Volteer}

Edit: this issue is root caused, see the last comment.

**Comment by aiChaoSONG** [comment]
To reproduce this issue, use below procedures:
1. reboot 
2. use speaker-test to check if  sound comes out from speaker
3. wait DSP to suspend 
4. repeat step 2 and step 3 several times (better > 10)

Note: speaker always works well after kmod reload.

These will be no sound through Speaker(max98373) after several runtime PM, once there is no sound over Speaker, check headset(rt5682), there is sound output.

Yali and I are re-doing bisect
Edit: bisect result   https://github.com/thesofproject/linux/commit/37740626

**Comment by plbossart** [comment]
@bardliao I don't really understand the revert. There is no explanation and we have not provided this upstream? Reopening since we don't have a solution for upstream.

**Comment by bardliao** [comment]
@plbossart The `regcache_sync()` will not take effect if we don't call `regcache_mark_dirty()`. Based on the test result, we need the `regcache_mark_dirty()` here. My theory is that some max98373 registers are changed. i.e. The regmap cache is out of sync. But we do need @ryans-lee's comment.

**Comment by plbossart** [comment]
Thanks @bardliao but why is this needed just for max98373? There's something very odd here. @ryans-lee can you take a look?

**Comment by bardliao** [comment]
@plbossart Can we close this issue now?

**Comment by plbossart** [comment]
humm, no, this is still open IMHO. We still have no explanation as to why we did a revert for max98373, and we haven't sent that patch upstream. We clearly need to figure this out. @bardliao @ryans-lee can you take a look?

**Comment by bardliao** [comment]
> humm, no, this is still open IMHO. We still have no explanation as to why we did a revert for max98373, and we haven't sent that patch upstream. We clearly need to figure this out. @bardliao @ryans-lee can you take a look?

@plbossart Somehow the `update_status` callback is never triggered when `status == SDW_SLAVE_UNATTACHED`. Therefore, `max98373->hw_init = false;` is never set and `max98373_io_init(slave)` is never called as `max98373->hw_init` = true.

**Comment by bardliao** [comment]
> > humm, no, this is still open IMHO. We still have no explanation as to why we did a revert for max98373, and we haven't sent that patch upstream. We clearly need to figure this out. @bardliao @ryans-lee can you take a look?
> 
> @plbossart Somehow the `update_status` callback is never triggered when `status == SDW_SLAVE_UNATTACHED`. Therefore, `max98373->hw_init = false;` is never set and `max98373_io_init(slave)` is never called as `max98373->hw_init` = true.

Talked with @shumingfan . He said rt711-sdca's volume control registers will be reset in bus reset. I guess some registers of max98373 will be reset, too. That's why we need https://github.com/thesofproject/linux/commit/b298102f34de81ab5603eee8d48d185832199b25

**Comment by plbossart** [comment]
@bardliao we already mark the cache as dirty on resume, it's not necessary to mark it on suspend...

**Comment by bardliao** [comment]
> @bardliao we already mark the cache as dirty on resume, it's not necessary to mark it on suspend...

Do we? I don't see `regcache_mark_dirty(max98373->regmap);` in [max98373_resume](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/max98373-sdw.c#L268). I see `regcache_mark_dirty(max98373->regmap);` in `max98373_io_init`, but `max98373_io_init` will not be triggered in a common suspend/resume case.

**Comment by plbossart** [comment]
> > @bardliao we already mark the cache as dirty on resume, it's not necessary to mark it on suspend...
> 
> Do we? I don't see `regcache_mark_dirty(max98373->regmap);` in [max98373_resume](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/max98373-sdw.c#L268). I see `regcache_mark_dirty(max98373->regmap);` in `max98373_io_init`, but `max98373_io_init` will not be triggered in a common suspend/resume case.

sure it will, on resume the device will re-attach and the io_init routine will be called

https://github.com/thesofproject/linux/blob/0e1e5072818cfd37c80010d2889f629ccb74c7ca/sound/soc/codecs/max98373-sdw.c#L825

That said, the name of the fields is slightly different from other drivers and maybe the flow is different.

````
git grep pm_init_once
max98373-sdw.c: if (max98373->pm_init_once) {
max98373-sdw.c: if (!max98373->pm_init_once) {
max98373-sdw.c: if (max98373->pm_init_once) {
max98373-sdw.c: max98373->pm_init_once = true;
max98373-sdw.c: max98373->pm_init_once = false;
max98373.h:     bool pm_init_once;
````

**Comment by bardliao** [comment]
@plbossart Thanks to @keqiaozhang. He tested the issue with https://github.com/thesofproject/linux/pull/2928 and https://github.com/thesofproject/linux/commit/4cfdde737ede7ae550cf7d4ee0c415dde83a94d5 reverted. i.e. Without `regcache_mark_dirty(max98373->regmap);` in `max98373_suspend(struct device *dev)` The test result is good, speaker playback works with the kernel.

**Comment by plbossart** [comment]
Ack @bardliao it looks like we didn't properly resume devices then, but only max98373 and rt711-sdca showed an issue.

**Comment by plbossart** [comment]
@bardliao @keqiaozhang can you please take a look at the alternative PR https://github.com/thesofproject/linux/pull/2941
It'd like to see if this works on Volteer (max98373) and TGL-SDCA (rt711-sdca)

**Comment by bardliao** [comment]
> @bardliao @keqiaozhang can you please take a look at the alternative PR #2941
> It'd like to see if this works on Volteer (max98373) and TGL-SDCA (rt711-sdca)

It works on my TGL-SDCA.

**Comment by keqiaozhang** [comment]
PR #2941 is merged, this issue can be closed.
