### ISSUE TITLE
[rt715] [SDW] rt715 sdw:3:25d:715:0: Initialization not complete, timed out on multiple-pause-resume-25 test

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#2644]
Kernel Branch: topic/sof-dev
Kernel Commit: 3ad56db9 + #2635 
SOF Branch: master
SOF Commit: fc9b89ad8b30

On Intel internal test 1198,  on CML platform we see below error with multiple-pause-resume-25.sh test.
```
kernel: [ 5809.713041] rt715 sdw:3:25d:715:0: Initialization not complete, timed out
kernel: [ 5809.713063] rt715 sdw:3:25d:715:0: ASoC: error at snd_soc_pcm_component_pm_runtime_get on sdw:3:25d:715:0: -110
kernel: [ 5809.713072]  SDW3-Capture: ASoC: BE open failed -110
kernel: [ 5809.713076]  Microphones: ASoC: failed to start some BEs -110
```

The issue seems to happen rarely, but it is still worth to create an issue to trace it.

[dmesg.txt](https://github.com/thesofproject/linux/files/5707953/dmesg.txt)

**Comment by mengdonglin** [comment]
This issue seems to be random and not caused by PR #2635. It is not observed in CI daily report 1165 (before https://github.com/thesofproject/linux/pull/2635 was merged) and 1305 (after https://github.com/thesofproject/linux/pull/2635 was merged).

This case only failed twice since 2020-12-11

**Comment by bardliao** [comment]
I can't reproduce it locally. The multiple-pause-resume-25.sh test is not supposed to trigger rt715_dev_resume() which is the only place that have the `Initialization not complete, timed out` trace. It is weird to me.

**Comment by bardliao** [comment]
rt715_dev_suspend() and rt715_dev_resume() are triggered when the pcm starts and stops. But I didn't find a scenario to reproduce the issue yet.

**Comment by bardliao** [comment]
Closing it for it is not seen for a long time. Will reopen it once it is reproduced again.
