### ISSUE TITLE
TGL: RT5682-SDW: "soundwire sdw-master-0: Update Slave status failed:-19" error seen during S0ix cycles.

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#2649]
Following issue is observed during PM stress testing on SoF_TGL_009 recipe on Volteer SDW SKU. 
I’m still waiting for results from validation team on new BKC with Debug Flag & Delay during codec init similar to i2c_probe. Sending the info. that I have got till now.
NOTE: snd-soc-rt5682-i2c was never probed/loaded.
 
What steps will reproduce the problem?
1. Boot the Chromebook and login to user
2. go the browser shell
3. initiate S0ix cycles " suspend_stress_test -c 2500"

Issue Observed: 
[messages.zip](https://github.com/thesofproject/linux/files/5728159/messages.zip)

"sound wire sdw-master-0: Update Slave status failed:-19" error seen during S0ix cycles.
Error Prints:
```
2020-12-16T11:35:39.133611Z ERR kernel: [18791.174874] rt5682 sdw:0:25d:5682:0: Device with ID register aaaaaaaa is not rt5682
2020-12-16T11:35:39.133611Z ERR kernel: [18791.174878] soundwire sdw-master-0: Update Slave status failed:-19
2020-12-16T11:35:39.133611Z ERR kernel: [18791.175541] rt5682 sdw:0:25d:5682:0: Device with ID register aaaaaaaa is not rt5682
2020-12-16T11:35:39.133612Z ERR kernel: [18791.175544] soundwire sdw-master-0: Update Slave status failed:-19
2020-12-16T11:35:39.133612Z DEBUG kernel: [18791.176484] PM: Finishing wakeup.

```
How frequently does this problem reproduce? (one of: Always, sometimes, hard to reproduce, X%, M/N )
Sometimes(4/2500 cycles) on one board
 
Modules Loaded:
```
localhost ~ # lsmod | grep snd
snd_soc_sof_sdw 40960 3
snd_soc_hdac_hdmi 32768 1 snd_soc_sof_sdw
snd_soc_rt5682_sdw 16384 1
snd_soc_rt5682 73728 1 snd_soc_rt5682_sdw
snd_soc_max98373_sdw 16384 2
snd_soc_max98373 32768 1 snd_soc_max98373_sdw
snd_soc_rl6231 16384 1 snd_soc_rt5682
regmap_sdw 16384 2 snd_soc_rt5682_sdw,snd_soc_max98373_sdw
snd_hda_codec_hdmi 53248 1
snd_soc_dmic 16384 1
snd_sof_pci 16384 0
snd_sof_intel_hda_common 65536 1 snd_sof_pci
snd_sof_xtensa_dsp 16384 1 snd_sof_intel_hda_common
snd_sof_intel_hda 16384 1 snd_sof_intel_hda_common
soundwire_intel 28672 3 snd_sof_intel_hda_common
snd_sof 81920 2 snd_sof_pci,snd_sof_intel_hda_common
snd_soc_hdac_hda 20480 1 snd_sof_intel_hda_common
snd_soc_acpi_intel_match 36864 2 snd_sof_pci,snd_sof_intel_hda_common
snd_soc_acpi 16384 2 snd_soc_acpi_intel_match,snd_sof_intel_hda_common
snd_hda_ext_core 16384 4 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda
soundwire_bus 61440 7 snd_soc_sof_sdw,regmap_sdw,snd_soc_rt5682_sdw,soundwire_intel,soundwire_generic_allocation,soundwire_cadence,snd_soc_max98373_sdw
snd_hda_intel 36864 0
snd_intel_dspcfg 20480 3 snd_hda_intel,snd_sof_pci,snd_sof_intel_hda_common
snd_hda_codec 106496 4 snd_soc_sof_sdw,snd_hda_codec_hdmi,snd_hda_intel,snd_soc_hdac_hda
snd_hwdep 16384 1 snd_hda_codec
snd_hda_core 65536 9 snd_soc_sof_sdw,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda

```

Further awaiting Chrome Validation Team's update for DUT Access

**Comment by bardliao** [comment]
@shumingfan @oder-chiou Do we need sleep for 300 ms as rt5682-i2c does?
```patch
--- a/sound/soc/codecs/rt5682-sdw.c
+++ b/sound/soc/codecs/rt5682-sdw.c
@@ -381,6 +381,9 @@ static int rt5682_io_init(struct device *dev, struct sdw_slave *slave)
        if (rt5682->hw_init)
                return 0;

+       /* Sleep for 300 ms miniumum */
+       usleep_range(300000, 350000);
+
        regmap_read(rt5682->regmap, RT5682_DEVICE_ID, &val);
        if (val != DEVICE_ID) {
```

**Comment by naveen-manohar** [comment]
To try have added above delay and enabled debug print in kernel.. request Chrome-Validation-Team to update us on this test.

**Comment by bardliao** [comment]
@naveen-manohar Do you know that will rt5682 be powered off in suspend?

**Comment by naveen-manohar** [comment]
Update from Chrome-validation-team with delay:
”sleep cycles got finished for 2.5K without any issues.
after the test, searched for the error prints which was reported and weren't observed”

During suspend cycle, audio device go to D3, clocks too go low. I believe so does the codec power. Need to re-confirm probing the power-lines.

**Comment by bardliao** [comment]
> Update from Chrome-validation-team with delay:
> ”sleep cycles got finished for 2.5K without any issues.
> after the test, searched for the error prints which was reported and weren't observed”

@naveen-manohar Did  Chrome-validation-team test with or without my patch https://github.com/thesofproject/linux/issues/2649#issuecomment-749375591?

**Comment by naveen-manohar** [comment]
> > Update from Chrome-validation-team with delay:
> > ”sleep cycles got finished for 2.5K without any issues.
> > after the test, searched for the error prints which was reported and weren't observed”
> 
> @naveen-manohar Did Chrome-validation-team test with or without my patch [#2649 (comment)](https://github.com/thesofproject/linux/issues/2649#issuecomment-749375591)?

This validation is with delay patch([your comment](https://github.com/thesofproject/linux/issues/2649#issuecomment-749375591))

**Comment by shumingfan** [comment]
@naveen-manohar 
I think we don't need to add the constant time to delay for now. The power supply for rt5682 should be stable already before the slave attached and the hardware is workable.
Our hardware engineer suspects the clock which is not stable yet.
Could you test this issue with the patch(8b153276cf62789d13b64e8f2b466e3d6ff32e77)?
If yes, please share the test log with me. Thanks.

**Comment by naveen-manohar** [comment]
Hi @shumingfan 
Thanks for the Patch. We are working on reproducing the issue with patch#8b15327, as this is random behavior observed during stress testing on random devices, it takes time..
By ww02.2 shall try to update.

**Comment by naveen-manohar** [comment]
Hi @shumingfan 
As suggested above, we ran S0ix for 2.5k cycles on two failure boards with the updated_kernel - patch#8b15327.
In both the DUTs, we don’t see the reported issue.
Please help proceed with the patch review/merge process.

**Comment by shumingfan** [comment]
@naveen-manohar The test result doesn't meet what I expected. It seems lucky not to see the reported issue with the patch (https://github.com/thesofproject/linux/commit/8b153276cf62789d13b64e8f2b466e3d6ff32e77).
I want to make sure the patch could read the correct device ID when the issue happened.
Could you arrange the time to test again?

**Comment by naveen-manohar** [comment]
Hi @shumingfan 
Apologies earlier Our test was checking for only "soundwire sdw-master-0: Update Slave status failed:-19" which weren't observed. Notice the following log
```
2021-01-08T13:21:59.045112Z DEBUG kernel: [ 3459.011971] PM: resume of devices complete after 427.851 msecs
2021-01-08T13:21:59.045114Z ERR kernel: [ 3459.013084] rt5682 sdw:0:25d:5682:0: 10, Device with ID register aaaaaaaa is not rt5682
2021-01-08T13:21:59.045116Z DEBUG kernel: [ 3459.014514] PM: Finishing wakeup.
```

**Comment by shumingfan** [comment]
@naveen-manohar Could you share the whole kernel log? Thanks.

**Comment by naveen-manohar** [comment]
As its a stress test of several cycles couldn't get particular cycle's dmesg, its of several MB, please check attached /var/log/message dump, let me know if this data helps.

[debug-logs_20210111-090605_messages.zip](https://github.com/thesofproject/linux/files/5794367/debug-logs_20210111-090605_messages.zip)

**Comment by shumingfan** [comment]
@naveen-manohar OK, I will send the patch to upstream.
But, I think this patch should be the workaround to fix getting the wrong device ID on the rare chance.
Our hardware engineer wants to check the signal(the related clock/data/power) when the issue happens.
However, this issue is hard to reproduce.

**Comment by shumingfan** [comment]
@naveen-manohar The patch had merged to upstream already.
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=867f8d18df4f5ccd6c2daf4441a6adeca0b9725b

**Comment by naveen-manohar** [comment]
JFYI, fix taken to Chrome Tree, Verification in-progress..

**Comment by keyonjie** [comment]
@naveen-manohar please help to close it if verified.

**Comment by naveen-manohar** [comment]
Validation Team verified on following Chrome Image & confirmed Issue was not observed - 2500 suspend-stress cycles completed on 2 SDW DUTs

OS: Google Chrome 89.0.4387.0(Platform 13731.0.0-21.01.16)
EC: RO version:    volteer_v2.0.6976-bca773799
CB: Google_Volteer2.13731.0.0
