### ISSUE TITLE
[BUG] Dell TGL-H Machine failed to load sof-tgl-h.ri

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [thesofproject/linux#2662]
**Describe the bug**
I got a new Dell hardware. It's CPU information:
[lscpu.log](https://github.com/thesofproject/sof/files/5733650/lscpu.log)

The failed kernel log:
[journalctl-k.log](https://github.com/thesofproject/sof/files/5733653/journalctl-k.log)

Its acpi device info:
\_SB_.PC00.HDAS.SNDW.SWD0
0x000020025d071100
\_SB_.PC00.HDAS.SNDW.SWD1
0x000120025d130800
\_SB_.PC00.HDAS.SNDW.SWD2
0x000220025d130800
\_SB_.PC00.HDAS.SNDW.SWD3
0x000320025d071500

The lspci info:
[lspci.log](https://github.com/thesofproject/sof/files/5733698/lspci.log)

**To Reproduce**
To boot into Ubuntu.

**Reproduction Rate**
100/100

**Expected behavior**
The machine can load sof firmware successfully and audio works for internal mic/speaker and headest input/output.

**Impact**
No ALSA card can playback and record audio.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.10.0-rc5
    * SOF: current sof-tgl.ri is not workable.
2) Name of the topology file
    * Topology: sof-tgl-rt711-rt1308-rt715.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: The Dell machine product sku is 0A5E

**Comment by KaiChuan-Hsieh** [comment]
@xiulipan Hello, you want to move this to linux, which means the sof-tgl-h.ri is available, but I still can't find a workable sof-tgl-h.ri, I try to build it from sof project but it seems the driver can't load successfully. Here is the log when loading the fw:
[load-fw-failed.log](https://github.com/thesofproject/linux/files/5749641/load-fw-failed.log), the full kernel log with dsp_driver=3: 
[tgl-h-soundwire.log](https://github.com/thesofproject/linux/files/5749644/tgl-h-soundwire.log)

I guess the signature maybe not correct, if you have a workable sof-tgl-h.ri in hand, can you share with me?

Thanks,

**Comment by xiulipan** [comment]
@KaiChuan-Hsieh We will try to have some hotfix to https://github.com/thesofproject/sof-bin for sof-tgl-h.ri please check later.

**Comment by KaiChuan-Hsieh** [comment]
@xiulipan I didn't see the hotfix of sof-tgl-h.ri, will it be released this week?

**Comment by mengdonglin** [comment]
@KaiChuan-Hsieh Please test SOF v1.6.1 engineering drop for TGL-H. Thanks!
