### ISSUE TITLE
[BUG] [Realtek ALC298] No sound from internal speakers

### ISSUE THREAD

**Issue by lo-leakage** [thesofproject/linux#2668]
**Describe the bug**
No sound from internal speakers. ( headset is ok ) 

I tried the test below 
1) options snd-intel-dspcfg dsp_driver=1 : no sound 
2) options snd-intel-dspcfg dsp_driver=3 : no sound 
3) options snd-hda-intel dmic_detect=0 and options snd-hda-intel models : no sound 

I have tested on windwos10 : ok, windows driver send some i2c command data for enable maxim sound amp. 

**To Reproduce**
Steps to reproduce the behavior: (e.g. list commands or actions used to reproduce the bug)

**Reproduction Rate**
100% 

**Expected behavior**
Working internal speakers 

**Impact**
Can't playback audio

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.10.0-rc1 
    * SOF: master and v1.6 tag 
2) Name of the topology file
    * Topology: sof-hda-generic-2ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: TigerLake Platform

**Screenshots or console output**
ALSA info : http://alsa-project.org/db/?f=7ba6e11f4fa1cfad5518a32bfcaaba5f5aff5aff
RtHDDump : [RtHDDump_V249.txt](https://github.com/thesofproject/sof/files/5745754/RtHDDump_V249.txt)
dmesg : [dmesg.log](https://github.com/thesofproject/sof/files/5745755/dmesg.log)
lspci : [lspci-vnvn.log](https://github.com/thesofproject/sof/files/5745756/lspci-vnvn.log)

**Comment by bardliao** [comment]
It is more like a driver issue.

> I have tested on windwos10 : ok, windows driver send some i2c command data for enable maxim sound amp.

@lo-leakage Where is the maxim sound amp connected to? Is it connected to rt298 or directly on TigerLake's i2s bus?

**Comment by lo-leakage** [comment]
> It is more like a driver issue.
> 
> > I have tested on windwos10 : ok, windows driver send some i2c command data for enable maxim sound amp.
> 
> @lo-leakage Where is the maxim sound amp connected to? Is it connected to rt298 or directly on TigerLake's i2s bus?

It is connected to rt298.

**Comment by lo-leakage** [comment]
> do you have any information on the i2c commands sent to maxim amp ? It looks like this is missing from the Linux driver.

I'm not sure but I think below log is related.  Can I send the I2C command date to maxim sound amp through codec driver ? 
( from RtHDDump ) 
        (REG_SZ) Count=0005 = Time=2020/11/30,6:45:5.337_WriteI2C,slaveID=38,regAddress=23FF,dataValue=00,ret=1
        (REG_SZ) Count=0006 = Time=2020/11/30,6:45:5.400_WriteI2C,slaveID=38,regAddress=203A,dataValue=80,ret=1
        (REG_SZ) Count=0007 = Time=2020/11/30,6:45:5.400_WriteI2C,slaveID=38,regAddress=23E1,dataValue=00,ret=1
        (REG_SZ) Count=0008 = Time=2020/11/30,6:45:5.400_WriteI2C,slaveID=39,regAddress=23FF,dataValue=00,ret=1
        (REG_SZ) Count=0009 = Time=2020/11/30,6:45:5.462_WriteI2C,slaveID=39,regAddress=203A,dataValue=80,ret=1
        (REG_SZ) Count=0010 = Time=2020/11/30,6:45:5.462_WriteI2C,slaveID=39,regAddress=23E1,dataValue=00,ret=1

**Comment by bardliao** [comment]
> > It is more like a driver issue.
> > > I have tested on windwos10 : ok, windows driver send some i2c command data for enable maxim sound amp.
> > 
> > 
> > @lo-leakage Where is the maxim sound amp connected to? Is it connected to rt298 or directly on TigerLake's i2s bus?
> 
> It is connected to rt298.

@lo-leakage We need Realtek's help on this. @shumingfan @kailangyang fyi.

**Comment by plbossart** [comment]
FYI, see the instructions in https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver to get the sequences needed to enable the amplifier.

**Comment by plbossart** [comment]
No update since January, closing. It's a codec driver issue anyways, not something the SOF team can fix.
