### ISSUE TITLE
TGL: Active System State:  DUT is not able to go below PC2 and causing Power regression

### ISSUE THREAD

**Issue by sathya-nujella** [thesofproject/linux#2678]
DUT:  TGL Chrome System
SOF fw: V11-release
Kernel:  Google kernel 5.4 

Test Step:
1) Boot DUT -> System is in S0 (i.e. Active state)
2) arecord -Dhw:0,100 -M -N -c 2 -f S24_LE -r 16000 --buffer-size=96000 tmp.wav -d 10
3) Check : "/sys/kernel/debug/pmc_core/package_cstate_show"
  Only "Package C2" is increasing. Not able to go below PC2.
4) Also, Power team checked: it is causing a very high power addition (app: ~800mW).

Note:
a) 
Without "wov capture ON",   DUT is able to go to "Package C6 /C8"

b) This power impact is there for all System scenarios 
   e.g.
   Idle + WoV-ON
   Playback + WoV-ON
   Meet Call + WoV-ON

**Comment by ranj063** [comment]
Enabling DMI L1 when WoV stream is the only active stream helps fix the issue. The delta is down to 100mW with the fix.
But it needs to be verified if it is a legitimate fix.

**Comment by keyonjie** [comment]
Thanks @ranj063 for addressing this.

Yes, we can move the DMI L1 toggle from suspend/resume() pair to hda_dsp_set_D0_state() to fix this.

We could still have potential risk to run WoV real-time capturing at D0I3, but that is another issue (https://github.com/thesofproject/sof/issues).

**Comment by plbossart** [comment]
@ranj063 I am not clear on how we would detect that 'WoV stream is the only active stream' in S0? The device is still in D0 state, there is no suspend stimulus, so we'd need an idleness detection, and possibly transition to D0i3 even where there is no transition to S0i1?

**Comment by ranj063** [comment]
@plbossart we dont need to detect if wov is the only active stream. All we need to do to exclude the wov capture stream from preventing DMI L1 entry. Please take a look at my PR

**Comment by plbossart** [comment]
If you really care about power consumption in S0, then the device should transition to D0i3. Incremental changes on L1 will not reduce DSP power, leakage, etc.

**Comment by ranj063** [comment]
But there are cases where we need DMI L1 even when the DSP is not in D0i3; for example headset playback + wov.

**Comment by plbossart** [comment]
this use case makes no sense to me... if you are using the headset, the internal mics are typically disabled ...
