### ISSUE TITLE
[NHLT parser] A NHLT could be parsed by Windows while can't be parsed by Linux kernel

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#2690]
ODM provided a NHLT, under linux, the sound/hda/intel-nhlt.c will print:
[ 7.189362] snd_hda_intel 0000:00:1f.3: undefined DMIC array_type 0x2
And the driver will fallback to legacy HDA.

ODM said they defined 1 dmic in the NHLT, and they followed the Intel IADK v2.6 spec and generated the NHLT with IADK tool. The Windows could work well with this NHLT.

HW: TGL-U laptop, Realtek HDA codec ALC3204, single DMIC on RGB camera connected to PCH.

Impact:
No built-in microphone option shows in sound settings page

**Comment by jason77-wang** [comment]
[TGL_HD_singlemic_1228.bin.txt](https://github.com/thesofproject/linux/files/5812209/TGL_HD_singlemic_1228.bin.txt)
This is the NHLT ODM provided. Please drop .txt when using it.

**Comment by mengdonglin** [comment]
SOF support for single DMIC https://github.com/thesofproject/linux/pull/2350/ has been integrated to customer kernel, confirmed by @jason77-wang

**Comment by juimonen** [comment]
@jason77-wang Do you have the following patch in your kernel?

Author: Jaska Uimonen <jaska.uimonen@linux.intel.com>
Date:   Tue Aug 25 16:50:36 2020 -0700

    ASoC: SOF: intel: hda: support also devices with 1 and 3 dmics

Actually not sure where this is travelling in upstream kernels...

**Comment by juimonen** [comment]
@plbossart saw that this is your code in sound/hda/intel-nhlt.c... and I see support here only for 2 or 4 dmics... I didn't stumble into this part of the code before, maybe this new case with nhlt and 1 dmic, so should we add the support here also for other dmic counts?

**Comment by juimonen** [comment]
@plbossart @jason77-wang checking the intel sst nhlt spec, to me it seems that Pierre's code is ok, there's no clear choice for 1 dmic conf other than using "vendor defined". @jason77-wang can you try this option? OTH if then windows doesn't work with this, we need to come up with some other solution...

**Comment by jason77-wang** [comment]
@juimonen OK, got it, I also think so since I checked the spec too. I told that to ODM already, they said they generated the nhlt with IADK tool and it is not possible the nhlt has problem.

But today, I saw ODM started changing the BIOS and provided a testing BIOS to us, let's wait for testing result first.

Thanks.

**Comment by jason77-wang** [comment]
ODM confirmed it is a BIOS issue, and they provided testing BIOS, we already verified the testing BIOS worked well with current Linux driver.

close this issue now.

**Comment by mengdonglin** [comment]
The old BIOS integrated a problematic NHLT table binary provided by FDK for Windows, the DMIC description is wrong for Linux.

**Comment by plbossart** [comment]
> The old BIOS integrated a problematic NHLT table binary provided by FDK for Windows, the DMIC description is wrong for Linux.

no one knows what's wrong here...
