### ISSUE TITLE
[RFC][SDW] dp0 folder not exist on sysfs

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#2693]
In soundwire/sysfs_slave.c, dp0 attributes and group are defined, and `slave->prop.dp0_prop` controls whether we will add the dp0 group. But I can not find the dp0 folder on a dell sku0a32 SDW device. I think the dp0 will always be used, so slave->prop.dp0_prop should not be empty, or I am wrong?

If I am wrong, that means `slave->prop.dp0_prop` can be empty, but `slave->prop.dp0_prop->num_words` is used in the `words_show` function without any check, some issue here?

@plbossart @RanderWang @bardliao Please answer my stupid questions, thx

**Comment by bardliao** [comment]
>In soundwire/sysfs_slave.c, dp0 attributes and group are defined, and slave->prop.dp0_prop controls whether we will add the dp0 group. But I can not find the dp0 folder on a dell sku0a32 SDW device. I think the dp0 will always be used, so slave->prop.dp0_prop should not be empty, or I am wrong?

@aiChaoSONG dp0 properties are get by the `read_prop` function. e.g. [rt1316_read_prop](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt1316-sdw.c#L122). So it could be empty. 
In fact, I don't see any codec driver set `dp0_prop`. So you will not able to see the dp0 folder in any devices.

> If I am wrong, that means slave->prop.dp0_prop can be empty, but slave->prop.dp0_prop->num_words is used in the words_show function without any check, some issue here?

[words_show](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/sysfs_slave.c#L158) will be called when user try to read dp0/words node. So it will be never called if dp0 folder does not exist.

**Comment by aiChaoSONG** [comment]
@bardliao After looking into codec code， it becomes much clear to me, thanks.

**Comment by plbossart** [comment]
@aiChaoSONG there are no stupid questions. 

DP0 is a 'special' data port, it was intended to allow command/control data to be transmitted using the audio payload space. That extends the command/control bandwidth considerably: You are no longer limited to sending commands in column0 of the frame. DP0 will be required for SDCA devices at some point, e.g. to retrieve a history buffer from a codec, or download firmware, but at the moment we don't have a real need for it.

Hope this helps.

**Comment by aiChaoSONG** [comment]
Thanks @plbossart and @bardliao for answering my questions, now everything is resolved, close this.
