### ISSUE TITLE
rt715-scda - controls coupling (FU02 Capture Volume, FU06 Capture Volume, FU0E Boost, FU0C Boost)

### ISSUE THREAD

**Issue by perexg** [thesofproject/linux#2696]
I came from https://github.com/alsa-project/alsa-ucm-conf/pull/71 . It seems that this is another attempt to use stereo to four or eight channels / inputs / registers mapping just because the current UCM cannot control this. See my arguments in https://lore.kernel.org/alsa-devel/7d74544f-77f2-db01-db3d-d1d8a56d576d@linux.intel.com/T/#m9d8869261e4531f537336da6b81085c1567034a9 . In my opinion, the codecs drivers should be universal without any usage assumptions, so if there are stereo inputs, don't couple them. If there are 4 or 8 inputs (and the codec is supposed to be used only in this way), create controls with 4 or 8 values and not one stereo control which maps to 2 + 2 and 2 + 2 + 2 + 2. Note that I update pulseaudio to support the multichannel controls since 14.0, so the multichannel controls are not an issue.

Reference: https://github.com/thesofproject/linux/pull/2670 .
FYI: @jack-cy-yu, @libinyang , @plbossart .

**Comment by juimonen** [comment]
@perexg in sof driver I needed to override the kcontrol info callback to be able to show multi channel control in user space... don't know if it is needed here also? So I think there's still quite a lot of stereo "hardcoding" in asoc level, I remember if I just created multi channel control in sof, it showed up as 2 stereo controls in user space, or am I totally mixing things here?

**Comment by perexg** [comment]
> @perexg in sof driver I needed to override the kcontrol info callback to be able to show multi channel control in user space... don't know if it is needed here also? So I think there's still quite a lot of stereo "hardcoding" in asoc level, I remember if I just created multi channel control in sof, it showed up as 2 stereo controls in user space, or am I totally mixing things here?

Yes, I think that asoc can easily create only mono and stereo controls. The multi channel controls do not have helpers / macros in the asoc layer yet. But I'm perfectly fine with the exporting of multiple stereo controls, if the codec was designed in this way (and the digital microphones are just connected to multiple stereo inputs). I just don't like the situation where one stereo kcontrol controls multiple stereo inputs (coupling).

**Comment by juimonen** [comment]
@perexg yes I have the same opinion about coupling. So just for the one who is implementing this -> if you _want_ to have multi channel control, the way to achieve it without changing asoc is to override the info callback. I think you could do it only for this particular control.

I was looking at the asoc thing and it was not totally obvious how to change it easily to support > 2 channels. I mean without causing possible issues to all legacy using it (and probably didn't have enough skills to do it nicely). But yes I think asoc should be changed eventually.

**Comment by libinyang** [comment]
> I came from [alsa-project/alsa-ucm-conf#71](https://github.com/alsa-project/alsa-ucm-conf/pull/71) . It seems that this is another attempt to use stereo to four or eight channels / inputs / registers mapping just because the current UCM cannot control this. See my arguments in https://lore.kernel.org/alsa-devel/7d74544f-77f2-db01-db3d-d1d8a56d576d@linux.intel.com/T/#m9d8869261e4531f537336da6b81085c1567034a9 . In my opinion, the codecs drivers should be universal without any usage assumptions, so if there are stereo inputs, don't couple them. If there are 4 or 8 inputs (and the codec is supposed to be used only in this way), create controls with 4 or 8 values and not one stereo control which maps to 2 + 2 and 2 + 2 + 2 + 2. Note that I update pulseaudio to support the multichannel controls since 14.0, so the multichannel controls are not an issue.
> 
> Reference: #2670 .
> FYI: @jack-cy-yu, @libinyang , @plbossart .

@perexg We used one kcontrol to controls multiple channels because UCM didn't support multichannel controls before. It is great that the feature is already supported in pulseaudio. If we want to use this feature, should we update to the latest alsa-lib and pulseaudio? And could you please give some instructs how to use this feature? Is the below UCM code correct:
```
    CaptureSwitch "control1 Capture Switch"
    CaptureVolume "control1 Capture Volume"
    CaptureSwitch "control2 Capture Switch"
    CaptureVolume "control2 Capture Volume"
```
I would like to have a test. 

updated: I updated to latest alsa-lib and pulseaudio. It seems not work. Did I miss something?

**Comment by perexg** [comment]
> @perexg We used one kcontrol to controls multiple channels because UCM didn't support multichannel controls before. It is 

I mean with the multichannel control one control which exports more than 2 values. The kcontrol driver API can pass up to 128 values per one kcontrol: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/sound/asound.h#n1051 .

> If we want to use this feature, should we update to the latest alsa-lib and pulseaudio? And could you please give some instructs how to use this feature?

The alsa-lib supports this by design. Only the PA code was restricted to stereo. My code was added to PA 14.0.

> Is the below UCM code correct:
> 
> ```
>     CaptureSwitch "control1 Capture Switch"
>     CaptureVolume "control1 Capture Volume"

I meant one control where the driver exports multiple values (4+) so you can refer only one control in UCM as before. The driver must be updated.

**Comment by plbossart** [comment]
I think there's two issues here.
One is the number of channels, and I agree with @perexg 

But the second issue is that the RT715 can be configured to use different microphones and DACs. Do we actually want PulseAudio to know about all the cases where this configuration may vary? That was the main intent of having a common control, that we could in one shot mute the microphones, without PulseAudio needing to know which microphones were used on the board.

**Comment by libinyang** [comment]
> I think there's two issues here.
> One is the number of channels, and I agree with @perexg
> 
> But the second issue is that the RT715 can be configured to use different microphones and DACs. Do we actually want PulseAudio to know about all the cases where this configuration may vary? That was the main intent of having a common control, that we could in one shot mute the microphones, without PulseAudio needing to know which microphones were used on the board.

I talked with @jack-cy-yu last week. RT715 may be used as 2 channels or multiple channels for MIC array. We can make a kcontrol with 4 (or 8) channels. Even there is only two channel DMIC connected, we can also mute other channels. It should have no side effect.

**Comment by jack-cy-yu** [comment]
@libinyang A patch (#2670 ) has been submitted regarding this issue. Note that amixer command should be modified to below format, which allows different values for different channels.

amixer cset name='rt714 FU02 Capture Switch' 1,1,1,1
amixer cset name='rt714 FU0A Capture Switch' 0
amixer cset name='rt714 ADC 22 Mux' 'DMIC3'
amixer cset name='rt714 ADC 23 Mux' 'DMIC4'
amixer cset name='rt714 FU02 Capture Volume' 100,100,100,100

**Comment by perexg** [comment]
Thank you for this work. Just to make sure - RT715 is not supposed to handle multiple stereo inputs? The configuration above 2 channels assume only multichannel operation for this change. Which may be correct, but if RT715 can handle for example stereo microphone (internal) and stereo line input (external), then this code / abstraction is problematic.

**Comment by libinyang** [comment]
> Thank you for this work. Just to make sure - RT715 is not supposed to handle multiple stereo inputs? The configuration above 2 channels assume only multichannel operation for this change. Which may be correct, but if RT715 can handle for example stereo microphone (internal) and stereo line input (external), then this code / abstraction is problematic.

@jack-cy-yu Could you please answer @perexg 's concern?

**Comment by jack-cy-yu** [comment]
Consider about sdca topology, kcontrol should be able to handle multiple stereo inputs.

**Comment by perexg** [comment]
> Consider about sdca topology, kcontrol should be able to handle multiple stereo inputs.

Ok, if there are stereo inputs which are independent (just dmic use two or more of those inputs in the coupled mode) then the driver should probably export all those controls as stereo only in the generic abstraction scheme.

If you like to have a separate mode for the digital microphones (export only the multichannel kcontrol), you should create those control conditionally (according the real hardware config). The question is  what code will control the stereo / multichannel mode in ASoC? The SOF mach configuration should pass this info somehow to the codec drivers. Or DMI should be used or so...

> But the second issue is that the RT715 can be configured to use different microphones and DACs. Do we actually want PulseAudio to know about all the cases where this configuration may vary? That was the main intent of having a common control, that we could in one shot mute the microphones, without PulseAudio needing to know which microphones were used on the boar

UCM can hide those internals for specific devices. PA just handles one volume / switch control per device.

**Comment by libinyang** [comment]
> Ok, if there are stereo inputs which are independent (just dmic use two or more of those inputs in the coupled mode) then the driver should probably export all those controls as stereo only in the generic abstraction scheme.
> 
> If you like to have a separate mode for the digital microphones (export only the multichannel kcontrol), you should create those control conditionally (according the real hardware config). The question is what code will control the stereo / multichannel mode in ASoC? The SOF mach configuration should pass this info somehow to the codec drivers. Or DMI should be used or so...
> 

@perexg Let's use FU02 as an example. FU02 is a mute/volume control for an audio PCM stream. (FU06 controls another audio stream). The audio stream can be 2 or 4 channels, and all the channels have already be merged into one stream. So we should control them in a kcontrol. The old codec driver exports 2 kcontrols, each kcontrols controls 2 channel in the same audio stream. This is not accurate. So I believe @jack-cy-yu 's latest patch is more reasonable for the rt715 topology.
FU02 doesn't control DMIC directly.

**Comment by perexg** [comment]
> @perexg Let's use FU02 as an example. FU02 is a mute/volume control for an audio PCM stream. (FU06 controls another audio stream). The audio stream can be 2 or 4 channels, and all the channels have already be merged into one stream. So we should control them in a kcontrol. The old codec driver exports 2 kcontrols, each kcontrols controls 2 channel in the same audio stream. This is not accurate. So I believe @jack-cy-yu 's latest patch is more reasonable for the rt715 topology.
> FU02 doesn't control DMIC directly.

If this combination is not feasible for RT715 for FU02, then I'm fine:

<pre>
stereo line-in no1 ----+--------+                                      +---- ALSA stereo PCM device no 1
                       |  FU02  +--- PCM link --- PCM / DMA bridge ----+
stereo line-in no2 ----+--------+                                      +---- ALSA stereo PCM device no 2
</pre>

The identical question is for FU06...

**Comment by libinyang** [comment]
@perexg From the HW spec, I don't think there is such scenario that the PCM will be divided into multiple PCM devices. It will be very strange. If customers want to have 2 PCM devices, they can use FU02 and FU06 for each. I checked Intel platforms, there is no such usage. 
In theory, customer may be able to create such usage. Host divides the PCM stream from codec FU02 into 2 PCM devices. In case customer did this, customer needs to offer the kcontrol for each PCM device himself. From codec view, Realtek still need to offer one kcontrol to control FU02 behavior, not two kcontrols.

@jack-cy-yu What's you opinion?

**Comment by jack-cy-yu** [comment]
My opinion is the same as before, as we consider about sdca topology, using latest kcontrols are more proper to describe sdca routing.

**Comment by perexg** [comment]
No further objections then. I don't know the RT715 codec diagram which may make things clear.

**Comment by libinyang** [comment]
@jack-cy-yu As we have aligned to your latest patch, would you send the patch to alsa or thesofproject? I have tested your patch on my platform, it works.

**Comment by libinyang** [comment]
@perexg Can we close this issue now as @jack-cy-yu 's patch has been merged.

**Comment by libinyang** [comment]
Let's close it as the PR has been merged.
