### ISSUE TITLE
[BUG] Microphone fails to be detected on Thinkpad X1 Carbon 7th Generation

### ISSUE THREAD

**Issue by cinerea0** [thesofproject/linux#2697]
**Describe the bug**
The built-in microphone in my Thinkpad X1 Carbon 7th Generation (X1C7) fails to be detected under PulseAudio even when using SOF firmware. Setting "options snd-intel-dspcfg dsp_driver=1" allows audio to be played but does not allow for microphone use. Setting "options snd-intel-dspcfg dsp_driver=3" does not allow either audio to be played or recorded.

**To Reproduce**
On a Thinkpad X1C7, install Void Linux, install the necessary ALSA and PulseAudio packages, and attempt to use the built-in microphone. I understand that this bug may be very hardware-specific, which may reduce the ability of others to reproduce this bug.

**Reproduction Rate**
This bug happens all the time.

**Expected behavior**
When using PulseAudio 14.0, SOF firmware 1.6.1, and alsa-ucm-conf 1.2.4, the microphone on this model of laptop should work without any further configuration.

**Impact**
This is a minor problem, since I can use an external microphone, but I would much prefer to be able to use the internal microphone because it's much more convenient.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: a60d1a8fea7579778cac14894e360a12365100e2 on branch v5.9.16
    * SOF: b77c851bc4ec1b6b552eaf1a61a66f3df4a13ab8 on branch stable-v1.6.1 in the sof-bin repository
2) Name of the topology file
    * Topology: sof-cnl-v1.6.1.ri
3) Name of the platform(s) on which the bug is observed.
    * Platform: Intel i7-10510U CPU with a glibc Linux system (not sure what was meant by 'platform')

**Screenshots or console output**
Output of `dmesg | grep audio`:
```
[    2.555127] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC285: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[    2.555128] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    2.555128] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[    2.555129] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[    2.555130] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[    2.555130] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19
[    3.756789] Modules linked in: ccm algif_aead des_generic libdes algif_skcipher cmac nf_tables nfnetlink md4 algif_hash af_alg nls_iso8859_1 nls_cp437 vfat fat uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_common videodev btusb btrtl mc btbcm btintel joydev hid_multitouch hid_generic iTCO_wdt intel_pmc_bxt iTCO_vendor_support mei_hdcp i2c_designware_platform i2c_designware_core intel_rapl_msr x86_pkg_temp_thermal intel_powerclamp coretemp snd_hda_codec_hdmi kvm_intel kvm iwlmvm irqbypass snd_hda_codec_realtek rapl snd_hda_codec_generic mac80211 intel_cstate snd_hda_intel psmouse libarc4 input_leds snd_intel_dspcfg snd_hda_codec intel_wmi_thunderbolt iwlwifi snd_hda_core wmi_bmof i2c_i801 snd_hwdep i2c_smbus mei_me intel_lpss_pci snd_pcm intel_lpss cfg80211 mei idma64 virt_dma processor_thermal_device intel_soc_dts_iosf intel_pch_thermal intel_rapl_common thermal thinkpad_acpi ledtrig_audio int3403_thermal int340x_thermal_zone ac int3400_thermal acpi_thermal_rel evdev
```

Output of `amixer contents` since I thought it was strange:
```
numid=4,iface=MIXER,name='Master Playback Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=3,iface=MIXER,name='Master Playback Volume'
  ; type=INTEGER,access=rw------,values=2,min=0,max=65536,step=1
  : values=16351,16351
numid=2,iface=MIXER,name='Capture Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=1,iface=MIXER,name='Capture Volume'
  ; type=INTEGER,access=rw------,values=2,min=0,max=65536,step=1
  : values=65536,65536
```

Full dmesg log: [dmesg.log](https://github.com/thesofproject/sof/files/5825670/dmesg.log)

Full output of alsa-info.sh: [alsa_info.txt](https://github.com/thesofproject/sof/files/5825674/alsa_info.txt)

**Comment by cinerea0** [comment]
Sure thing! In addition to the logs below I'll tell you that setting that option makes it so that my sound card isn't detected at all; an alsamixer screenshot showing that has been attached. I also enabled dynamic debugging as described [here](https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#enable-dynamic-debug).

![alsamixer](https://user-images.githubusercontent.com/49368915/104976314-d8419100-59f4-11eb-9b6a-7cb98984b115.png)

dmesg: [dmesg.log](https://github.com/thesofproject/linux/files/5833018/dmesg.log)
alsa-info: [alsa_info.txt](https://github.com/thesofproject/linux/files/5833019/alsa_info.txt)

**Comment by juimonen** [comment]
@cinerea0 so it still not loading sof driver at all... at least there's nothing related to sof in the logs, and there should be a lot of stuff.... 

@kv2019i again asking your help here... some config wrong here maybe?

**Comment by kv2019i** [comment]
@cinerea0 It seems this is a bug in Void Linux kernel packaging:

https://github.com/void-linux/void-packages/blob/196a3bba255bd37f47cb736548ea25b65f4954cb/srcpkgs/linux5.10/files/x86_64-dotconfig

... SOF support is enabled only for some platforms. Notably CONFIG_SND_SOC_SOF_COMETLAKE is not set:
```
# CONFIG_SND_SOC_SOF_COMETLAKE_LP_SUPPORT is not set
```

... i.e. SOF is disabled for all 10th Gen Core (aka CometLake) based platforms on Void LInux, like your X1.

FYI @plbossart Here's another case where the Kconfig options are causing issues.

**Comment by cinerea0** [comment]
@kv2019i To clarify, changing the line in that file to `CONFIG_SND_SOC_SOF_COMETLAKE_LP_SUPPORT=y` and recompiling the kernel should fix the problem? I ask because the other CPU architectures have another line like this: `CONFIG_SND_SOC_SOF_ICELAKE=m`. If so, I'll file a PR in the void-packages repo and report back here after the change gets merged.

**Comment by cinerea0** [comment]
One additional question: Where does `libsof_tplg_parser.so` come from? I ask because I'm the package maintainer for sof-bin for Void Linux (packaged there as sof-firmware) and our packaging system is complaining that it doesn't know where that library comes from when attempting to install the tools that comes with sof-bin.

**Comment by kv2019i** [comment]
Ack @cinerea0 , CONFIG_SND_SOC_SOF_COMETLAKE_LP_SUPPORT=y is the user-visible option to set, that will then autoselect other needed options like CONFIG_SND_SOC_SOF_COMETLAKE_LP. Same pattern as for other platforms.

@cinerea0 That is a library built by sof/tools/tplg_parser and AFAIK is only used test tools used by CI and developers. This is not needed by end-users. 

@xiulipan @ranj063 @lgirdwood @marc-hb   Why do we have "sof-fuzzer" binary in sof-bin? That doesn't seem to be needed there and you'd need extra libraries from sof to actually use it.

```
# download https://github.com/thesofproject/sof-bin/blob/stable-v1.6.1/tools/v1.6.1/sof-fuzzer?raw=true
$ ldd sof-fuzzer\?raw\=true 
        linux-vdso.so.1 (0x00007ffeabff3000)
        libsof_tplg_parser.so => not found
```

**Comment by marc-hb** [comment]
I've been looking at sof-bin only recently so I don't know all the history, however it's not because something is in sof-bin that it must be distributed to all users, in other words I don't think we want multiple sof-bin git repos for different audiences.

On the other hand, maybe something like `sof-fuzzer` should be in some separate, "developers" or something directory? Any suggestion?

Or are you saying there's no point distributing this as a binary to anyone at all?

PS: afraid this is all getting quite off-topic.

**Comment by cinerea0** [comment]
@kv2019i Thank you for the information! I've made a PR with the necessary changes to the void-packages repo, now I just have to see if it works.

@marc-hb I apologize for dragging the conversation off-topic. In the event that a Void user needs the sof tools, I'll package them from source.

**Comment by kv2019i** [comment]
@cinerea0 Thanks a lot and good that it works now! The many Kconfig options is somewhat challenging for distributions -- we are doing some refactoring to the driverss and might potentially reduce the options a bit going forward. I'll close this now as the main issue is closed. Thanks all!

**Comment by xiulipan** [comment]
@kv2019i Good point, we recently add all tools binary to sof-bin, did not notice we have extra dependency for sof-fuzzer. I think we can remove this binary in sof-bin/tools
