### ISSUE TITLE
"Tag 1 not opened" error message on each pm_runtime suspend

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#271]
Maybe it's harmless but I am tired of seeing it without understanding if it's a real issue or not. This message occurs before each suspend

````text
[  277.308258] sof-audio sof-audio: tag 1 not opened!
[  277.308309] sof-audio sof-audio: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  277.308481] sof-audio sof-audio: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  277.330229] sof-audio sof-audio: DSP core(s) enabled? 0 : core_mask 3
[  277.330264] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
````

**Comment by keyonjie** [comment]
fix is here:
https://github.com/thesofproject/linux/pull/248/commits/21e9ca1ba359beae02496323c25a4b330e41bee5

**Comment by plbossart** [comment]
@keyonjie can you submit this patch as a PR? Looks like this change will conflict with Rander's simplifications of get/put functions.

**Comment by keyonjie** [comment]
thesofproject/linux#287 merged to sof-dev, @ranj063 please backport it to cros branch then we can verify and close this issue on GLK.

**Comment by mengdonglin** [comment]
Closing this issue since it's fixed on kernel topic/sof-dev branch.
