### ISSUE TITLE
HDA: "patch" parameter support

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#2714]
Implement capability to load custom HDA verbs for initialization from a file.

This is a feature implemented in the non-DSP snd-hda-intel driver and commonly used to address issues in codec programming (something missing in BIOS or a new variant). Example bug:
https://github.com/thesofproject/linux/issues/2631

**Comment by jrelvas-ipc** [comment]
Desperately need support for this. My Laptop (a Thinkpad X1 Extreme Gen 5) doesn't have a fixup upstream and I'm unable to properly debug it with SOF enabled since there's no support for forcing a given model.

**Comment by plbossart** [comment]
closing since feature is implemented
