### ISSUE TITLE
Fix MSI support with HDMI outputs

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#272]
We all agreed we'd move to MSI, but the HDaudio code still have this TODO

````c
//	ret = pci_alloc_irq_vectors(pci, 1, 1, PCI_IRQ_MSI);
	/* todo: MSI mode doesn't work for HDMI yet, debug it later */
````

This needs to be fixed or explained before upstreaming

**Comment by plbossart** [comment]
@Jocelyn-Li can you please assign someone to work on this?

**Comment by libinyang** [comment]
#349 is to enable MSI for sof

**Comment by jocelyn-li** [comment]
@libinyang #349 is merged, can this issue be closed?

**Comment by libinyang** [comment]
> @libinyang #349 is merged, can this issue be closed?

Yes, I think so.
