### ISSUE TITLE
[BUG] [CNL] error on `SNDRV_PCM_TRIGGER_SUSPEND` during weekly testing

### ISSUE THREAD

**Issue by lyakh** [thesofproject/linux#2734]
When running the suspend-resume-with-capture test on Mantis after more than 30 iterations an error occurred:
```
kernel: [ 7514.596793] [127140] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
kernel: [ 7514.596955] [127140] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
kernel: [ 7514.597381] [127140] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x240002 timedout
kernel: [ 7514.597392] sof-audio-pci 0000:00:1f.3: error: hda_dsp_stream_trigger: cmd 5: timeout on STREAM_SD_OFFSET read
kernel: [ 7514.597410] [127140] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
kernel: [ 7514.597547] [127140] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
kernel: [ 7514.598142] [127140] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
kernel: [ 7514.598168] [127140] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
kernel: [ 7514.598306] [127140] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
```
After which no further communication with the DSP was possible.
[dmesg.txt](https://github.com/thesofproject/linux/files/5920776/dmesg.txt)
[slogger.txt](https://github.com/thesofproject/linux/files/5920778/slogger.txt)

**Comment by ranj063** [comment]
@lyakh the weird part is that after the STREAM_SD_OFFSET read timeout,2 other IPCs are still successful. So the DSP is clearly not dead. What did you mean by "no further communication was possible"? You couldnt start any stream after that?

**Comment by lyakh** [comment]
> @lyakh the weird part is that after the STREAM_SD_OFFSET read timeout,2 other IPCs are still successful. So the DSP is clearly not dead. What did you mean by "no further communication was possible"? You couldnt start any stream after that?

@ranj063 ok, you're right, sorry, missed those 2 IPCs. But that was suspending the DSP. But booting it again after that didn't work, as far as I can see:
```
kernel: [ 7524.296115] sof-audio-pci 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
kernel: [ 7524.296671] [127140] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140002 timedout
kernel: [ 7524.296677] sof-audio-pci 0000:00:1f.3: error: hda_dsp_stream_trigger: cmd 0: timeout on STREAM_SD_OFFSET read
kernel: [ 7524.296683] sof-audio-pci 0000:00:1f.3: error: DMA trigger stop failed
kernel: [ 7524.296690] [127140] sof-audio-pci 0000:00:1f.3: unknown ROM status value 05000001
kernel: [ 7524.296698] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
kernel: [ 7524.296715] sof-audio-pci 0000:00:1f.3: error: extended rom status:  0x5000001 0x0 0x0 0x0 0x0 0x0 0x1811102 0x0
kernel: [ 7524.296723] [127140] sof-audio-pci 0000:00:1f.3: unknown ROM status value 05000001
kernel: [ 7524.296728] sof-audio-pci 0000:00:1f.3: error: load fw failed ret: -110
kernel: [ 7524.296774] sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
kernel: [ 7524.296780] sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
```

**Comment by ranj063** [comment]
The same error happens on the helios within 5 iterations of suspend-resume with capture.

**Comment by plbossart** [comment]
> The same error happens on the helios within 5 iterations of suspend-resume with capture.

Weird, this is not reported by daily tests. Are we testing the same things?

**Comment by ranj063** [comment]
> > The same error happens on the helios within 5 iterations of suspend-resume with capture.
> 
> Weird, this is not reported by daily tests. Are we testing the same things?

hmm yes seems like we're not. I updated my FW to SOF master and I cant seem to reproduce it anymore.

**Comment by fredoh9** [comment]
@lyakh do you have linux and sof SHA1s?

**Comment by fredoh9** [comment]
I tested with CML Helios and CML_RVP_SDW. With two daily builds(below hash info). I couldn't reproduce the problem.

```
"kernelBranch" : "topic/sof-dev",
"kernelCommit" : "4c37c24f",
"sofBranch" : "master",
"sofCommit" : "372d3873bd55"

"kernelBranch" : "topic/sof-dev",
"kernelCommit" : "157a2621",
"sofBranch" : "master",
"sofCommit" : "372d3873bd55
```

This is the test command I used,
`./check-suspend-resume-with-audio.sh -m capture -l 35`

**Comment by lyakh** [comment]
@fredoh9 the test ran last Friday, Jan 29.
kernel 6fa085f3d92278d1a9fd28b0c760e3e4ee6c4e61
Interestingly, due to a problem with my weekly testing, the firmware hasn't been updated  stayed at an earlier checkout, same as during the test a week before, when this issue hasn't occurred. This confirms @ranj063 's suggestion from an email, that this should be a kernel regression. But to verify whether it has been fixed since last Friday, I've just re-run 50 iterations of the test with no failure. I'll run a complete "run all" test tomorrow again. Closing for now.
