### ISSUE TITLE
[Loader] Use fallback methodology when loading

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#2766]
Now that devices are starting to support non-upstream-able firmware they will start specifying alternative paths for the topology. If the device does this via something like the AP firmware that generates kernel command line parameters then these paths will persist through to additional OSes. These args as a result will break audio since the driver will not find the firmware at the specified location since a different OS is loaded. The solution is to let the driver gradually fallback when checking locations from more specific to less specific to preserve audio functionality on non default OSes.

So each step, should the file be missing, will continue onto the next, if file is found, stop and load it
1. If specified, check module params (via conf or cmdline args)
2. dmi match if found
3. default matching based on acpi/pci IDs.

FYI @plbossart @ranj063

**Comment by cujomalainey** [comment]
Reducing priority since we found a work around locally

**Comment by cujomalainey** [comment]
@plbossart this is done now right?

**Comment by plbossart** [comment]
> @plbossart this is done now right?

For PCI only.

**Comment by cujomalainey** [comment]
I don't see a need on legacy acpi platforms. OF is a different story

**Comment by plbossart** [comment]
we have the ability to override paths, filenames, use DMI quirks, there are more than enough solutions. closing
