### ISSUE TITLE
IPC timed out after boot on Yorp

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#277]
This regression is caused by the ABI change, since the ABI is changed in firmware side, but the according kernel PR thesofproject/linux/pull/260 is missing in cros-sof-v4.14-rebase branch.

dmesg log:
```
[    5.049045] sof-audio sof-audio: firmware boot complete
[    5.049057] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[    5.049059] sof-audio sof-audio: Debug PCIW: 00000002 at  00000048
[    5.049064] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[    5.049066] sof-audio sof-audio: Debug PCIW: 00000000 at  00000044
[    5.049120] sof-audio sof-audio: generating page table for ffffa74902fe2000 size 0x10000 pages 16
[    5.049122] sof-audio sof-audio: dma_trace_pages: 16
[    5.049159] sof-audio sof-audio: period_bytes:0x0
[    5.049160] sof-audio sof-audio: periods:1
[    5.049166] sof-audio sof-audio: stream_tag: 1
[    5.049181] sof-audio sof-audio: ipc tx: 0x90010000
[    5.352024] sof-audio sof-audio: error: ipc timed out for 0x90010000 size 0x1c
[    5.352037] sof-audio sof-audio: unknown ROM status value ffffffff
[    5.352183] sof-audio sof-audio: error: unexpected fault 0xffffffff trace 0xffffffff
[    5.352196] sof-audio sof-audio: error: can't set params for DMA for trace -110
[    5.352210] sof-audio sof-audio: warning: failed to initialize trace -110
[    5.352339] sof-audio sof-audio: created machine glk_da7219_max98357a
```
kernel driver- ranja063-cros-sof-v4.14-rebase:a38231
sof-master:73475e
soft-master:2cd668c

**Comment by ranj063** [comment]
@keqiaozhang thanks. I will update the cros branch after the ABI changes have been validated

**Comment by mengdonglin** [comment]
@ranj063 Please hold on backporting PR /pull/260 to the topic/cros-4.14-rebase branch. Please backport after release for this week is done.

Firmware glk-004-drop-stable branch plan to introduce ABI update for IPC refinement AFTER the release this week.  Only SOF master branch has the ABI update atm.

**Comment by plbossart** [comment]
@mengdonglin there is no plan to provide a different driver so firmware HAS to update. The ABI change was reviewed and no one from the firmware team chimed in, so silence means consent...

**Comment by mengdonglin** [comment]
Closing this issue because now kernel branch topic/cros-sof-v4.14-rebase is aligned with FW branch glk-004-drop-stable. And FW branch glk-004-drop-stable will not include any ABI change if not necessary for a hot fix.

So ABI update like https://github.com/thesofproject/sof/commit/9af90ce211203741d6b377d3aed7b837e2734306 will not be included in glk-004-drop-stable. Thus no need to backport PR /pull/260 to the topic/cros-4.14-rebase branch.
