### ISSUE TITLE
[BUG][TGL] "power off/power on" stress test make the system hang randomly

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#2781]
We have a LENOVO TGL laptop model, and  have 4 SKUs of this model.
We run "power off/power on" stress test on them, the "power off/power on" will repeat 30 times in a test round. we found the system will hang randomly during the power off process.

This  issue happened on all 4 SKUS. And we found if we blacklist snd-sof-pci, the system will not hang. And If we add snd_hda_intel.dmic_detect=0, the system will not hang.

We tested ubuntu 5.10.0-1013oem kernel, mainline 5.11-rc7 kernel and thesofproject/linux topic/sof-dev (5.11-rc7), all of them could reproduce the hang issue.

**Comment by jason77-wang** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/7478860/110064158-889e0580-7da7-11eb-8949-4b18cfd08be7.jpeg)
When power off process hang, we could see the error log from monitor:

**Comment by jason77-wang** [comment]
![Uploading webwxgetmsgimg.jpeg…]()

**Comment by jason77-wang** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/7478860/110064645-78d2f100-7da8-11eb-901b-e58cf67bc6d9.jpeg)

**Comment by jason77-wang** [comment]
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:a0c8] (rev 20) (prog-if 80)
	Subsystem: Lenovo Device [17aa:22d5]
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 64
	Interrupt: pin A routed to IRQ 183
	Region 0: Memory at 603d1d8000 (64-bit, non-prefetchable) [size=16K]
	Region 4: Memory at 603d000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: sof-audio-pci
	Kernel modules: snd_hda_intel, snd_sof_pci

**Comment by keyonjie** [comment]
Hi @jason77-wang can you upload the full dmesg with the fail case? We have a similar issue reported here: https://github.com/thesofproject/linux/issues/2775

@kv2019i @plbossart @ranj063 FYI.

@libinyang waiting for your PR to fix one more issue.

**Comment by jason77-wang** [comment]
@keyonjie, since this happens during the power off process, the error logs are not in the dmesg. This issue happens at the last step of power off, the dmesg daemon is already closed at the moment.

**Comment by keyonjie** [comment]
@jason77-wang thanks, so did you observe abnormal failure(e.g. dsp probing failed, sound card creating failed...) before initiating the reboot?

**Comment by jason77-wang** [comment]
@keyonjie no, the syslog could record the dmesg of booting process, we checked the syslog, there is no failure log during booting so far.

**Comment by libinyang** [comment]
@jason77-wang Could you have a try on https://github.com/thesofproject/linux/pull/2768 ?

**Comment by jason77-wang** [comment]
@libinyang OK, got it. The machine is in the office, we will test #2768 next Monday.  Thanks.

**Comment by jason77-wang** [comment]
@libinyang 

I applied the patches of #2768 to topic/sof-dev branch, and built a kernel, our QA reported this kernel still hang when executing poweroff/poweron stress test. The test should repeat poweroff/poweron 30 times, and the system got hang at the 28th poweroff.

**Comment by jason77-wang** [comment]
[hang-config.txt](https://github.com/thesofproject/linux/files/6127974/hang-config.txt)

Please use this kconfig with topic/sof-dev, it  is easier to reproduce this issue.

**Comment by cooper-chiou** [comment]
@jason77-wang Could you share the impacted project names as we need to have discussion internally.

**Comment by plbossart** [comment]
> [hang-config.txt](https://github.com/thesofproject/linux/files/6127974/hang-config.txt)
> 
> Please use this kconfig with topic/sof-dev, it is easier to reproduce this issue.

what's different about this?

**Comment by libinyang** [comment]
@jason77-wang There are 2 issues  in this bug as I can see from the symptom. 
One issue can be fixed by https://github.com/thesofproject/linux/pull/2768. 
Another issue is caused by DMI L1. Please de-select "SOF enable DMI Link L1 " in the menuconfig:  Device Drivers  ---> Sound card support  --->  Advanced Linux Sound Architecture  ---> ALSA for SoC audio support  ---> SOF enable DMI Link L1

**Comment by jason77-wang** [comment]
@libinyang 
Thanks, I will test it.

**Comment by plbossart** [comment]
FWIW we seen issues in reboot loops on WHL and TGL even with the fixes from @libinyang, something's still not quite right

**Comment by jason77-wang** [comment]
After applied the patch of #2768 and disable the DMI L1, the system didn't hang anymore during 90 times poweroff stress test. Let us close this bug temporarily.
thanks.
