### ISSUE TITLE
KWD not detecting on ADL

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#2782]
We are using the sof-tgl-max98373-rt5682.tplg    and the tglv011 based fw released for ADL.
When i run below command, i dont see clap / tap being recognised.
arecord -Dhw:0,100 -M -N -c 2 -f S16_LE -r 16000 --buffer-size=96000 /home/root/tmp3.wav -d 10 -vvv

Attaching logs captured with S16 as well as S32.
[hotwording_s16.log](https://github.com/thesofproject/linux/files/6103259/hotwording_s16.log)
[hotwording_s32.log](https://github.com/thesofproject/linux/files/6103260/hotwording_s32.log)

**Comment by sathyap-chrome** [comment]
@kv2019i  let me know if you need more details

**Comment by kv2019i** [comment]
@sathyap-chrome Can we close as config issue?

**Comment by sathyap-chrome** [comment]
Yes. lets close this.
