### ISSUE TITLE
[BUG][EHL] Kernel boot failure on EHL with PINCTL enabled

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2828]
**Describe the bug**
This is a regression on EHL, system hang when enters to kernel and no logs are available.  
Bisect result shows this issue is introduced by a kconfig change:
```
commit 402cb3a130660f95739ea1e0289f79cb99303762
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date:   Fri Mar 26 16:18:26 2021 -0500

    base-defconfig: add PINCTRL for ADL and ELK

    missing for some reason

    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

```

**To Reproduce**
Install the latest sof-dev kernel and reboot 

**Reproduction Rate**
100%

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 138a5d76

SOF Branch: main
SOF Commit: 2c69afc5fdeb
Platform: EHL-RVP I2S mode

**Comment by plbossart** [comment]
We had similar issues with TGL, where with the TGL pinctrl the touchpad wouldn't work on some Dell platforms. That was solved by @andy-shev.

A kernel that fails to boot is something else. @mengdonglin someone in your team will have to debug this, I don't have a platform to check.

**Comment by andy-shev** [comment]
EHL BIOS is not implementing pin control properly by some reason. So, communicate to EHL firmware team. I have heard that the same issue has been reported by another team.

**Comment by mengdonglin** [comment]
@plbossart Should we not add PINCTRL for EHL atm?

**Comment by plbossart** [comment]
@mengdonglin please talk with the firmware team and provide their feedback. If this option is not working, then it should be documented clearly.

**Comment by plbossart** [comment]
@mengdonglin any progress here, or should we revert and remove this PINCTRL for EHL in our test config?

**Comment by mengdonglin** [comment]
@keqiaozhang will test the latest EHL BIOS

**Comment by XiaoyunWu6666** [comment]
https://github.com/thesofproject/kconfig/pull/55 which  removes  PINCTRL for EHL is already merged . Will close this if daily test is good

**Comment by XiaoyunWu6666** [comment]
it is good in inner daily test 4487, close it

**Comment by plbossart** [comment]
let's keep this open until the BIOS issue is resolved.

**Comment by mengdonglin** [comment]
Waiting for official MR2 BIOS release with the fix for PINCTRL, ~ mid of October.

**Comment by mengdonglin** [comment]
Succeeded to apply apply the BIOS PINCTROL fix to EHL RVP.
Failed to apply the BIOS PINCTROL fix to EHL CRB:  the patch cannot be applied to the last working BIOS of CRB. The BIOS of CRB has been updated for months.

**Comment by plbossart** [comment]
@mengdonglin what does this mean? can we enable the kernel PINCTRL option?

**Comment by plbossart** [comment]
@mengdonglin @keqiaozhang ping? can we close this issue and enable the kernel PINCTRL option?

**Comment by keqiaozhang** [comment]
@plbossart , we have 2 types of EHL boards, one is normal RVP board and the other one is CRB board.
For RVP, we can apply the BIOS PINCTL fix to enable the PINCTL support to latest BIOS of RVP. 
But on CRB board, we failed to apply the BIOS PINCTL fix to last working BIOS of CRB.

So we have 2 options here:
1. Enable the PINCTL in kernel config, but there's only one EHL RVP board available in CI to run daily test(abandon the CRB board).
2. Continue to disable the PINCTL in kernel config, I will borrow another CRB board from local media team, then we will have 3 EHL boards(one RVP board + 2 CRB boards, all are in I2S mode) available in CI to support both PR test and daily test.

which one do you prefer?

**Comment by plbossart** [comment]
@keqiaozhang have you filed a ticket with the BIOS team for this CRB failure? If this is an unsupported board then we should probably move on and only use an RVP. I don't see the point of continuing with a broken solution.

**Comment by keqiaozhang** [comment]
@plbossart , Sure, I will enable the PINCTL on EHL-RVP board and track the CRB failure with BIOS team.

**Comment by aiChaoSONG** [comment]
On how to correct the wrong codec ID in the DSDT table:
- Install ACPI tools: `sudo apt install acpica-tools`
- Dump acpi tables: `sudo acpidump -o acpi.out`
- extract dsdt table:  `acpixtract acpi.out`, you got dsdt.dat here
- disassembly dsdt table:  `iasl -d dsdt.dat` you got dsdt.dsl here
- rename dsdt.dsl to dsdt.asl, and modify it: a) increase OEM Revision, replace all INTC1027(wrong ID) with 10EC5660(correct ID).
- With the tool here: https://github.com/thesofproject/acpi-scripts, override dsdt table with ./acpi-add PATH-TO-MODIFIED-DSDT-ASL-FILE
example diff:
[diff.txt](https://github.com/thesofproject/linux/files/7362865/diff.txt)

**Comment by XiaoyunWu6666** [comment]
will check whether EHL DUT in sh lab is rvp or crb after CNY

**Comment by plbossart** [comment]
@keqiaozhang @aiChaoSONG @XiaoyunWu6666 do we still care about this bug, if not please close.

**Comment by keqiaozhang** [comment]
I don't care about the PINCTL. Closing this bug.  BTW, we have added one EHL UP board in CI `251:sh-ehl-up-hda-01`
