### ISSUE TITLE
HDaudio: machine driver selection improvement

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#284]
In the existing code if there are no I2S codecs we fall back to HDAudio. This is not quite right, we should only do so if there are devices on the bus. The issue is that the HDaudio machine selection happens in sof-pci-dev.c before we probe the bus in intel/hda.c, so we have a chicken-and-egg problem.

Filing as an improvement to make sure we have a story and better handling of error cases.

**Comment by RanderWang** [comment]
@keyonjie , Hi keyon, I will work on SDL for SOF release, so I can't do it now, but we could have a discuss about it

**Comment by jocelyn-li** [comment]
@RanderWang  #321 is closed. Will you submit new PR to fix this issue?

**Comment by RanderWang** [comment]
@Jocelyn-Li  yes, I may need to spend some days to finish it.
