### ISSUE TITLE
[TGL][SDW][codec]mute 'rt711 FU0F Capture Switch' doesn't work

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#2843]
'rt711 FU0F Capture Switch' is used to control the RT711 headset MIC mute/unmute.
When I set this kcontrol to 0, I can still capture the sound from headset MIC.

**Comment by libinyang** [comment]
Debugged with Shuming. It shows to be the codec driver issue.
The FU0F is used as the DAPM node, which will automatically switch on when capture. So setting this kcontrol doesn't take effect. Shuming will remove FU0F kcontrol with a patch.

**Comment by libinyang** [comment]
An updated patch is submitted: https://github.com/thesofproject/linux/pull/2860

**Comment by shumingfan** [comment]
@libinyang The updated patch was merged to upstream.
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=ca5118c0c00f6bc8b7d0c82c95485159db3a5584
This patch is a little bit different from #2860. The functionality will be the same.

**Comment by libinyang** [comment]
@shumingfan Got it. Thanks.

@bardliao Maybe we need to port the patch to our SOF.

**Comment by bardliao** [comment]
> @shumingfan Got it. Thanks.
> 
> @bardliao Maybe we need to port the patch to our SOF.

@libinyang https://github.com/thesofproject/linux/pull/2868 or we can wait for the regular rebase which will merge the upstream patches.

**Comment by plbossart** [comment]
better to use regular rebase, patches in SOF topic/sof-dev generate extra work for us.

**Comment by libinyang** [comment]
Let's close it as Shuming's patch is merged in the community.
