### ISSUE TITLE
[BUG] Non-48 kHz rate playback via SRC pipeline into hda-generic headset wrong pitch and wrong length

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#2849]
**Describe the bug**
Playback at 48 kHz rate sounds correct and playback time is as expected, e.g. 10s length clip takes 10s time to play. If 32 kHz rate clip is played it takes about 48/32 amount of time, 10s takes 15s. The pitch is lower.

The source and sink buffer parameters show e.g. correct 32 and 48 kHz in params(), prepare() and copy(). SRC seems to get correct configuration. The amount from frames copied looks like DAI sink takes only 32 frames per copy. Much like the DAI would operate at that rate instead of fixed 48 kHz.

**To Reproduce**
Currently there is no topology with SRC for hda-generic. Such can be done with edit:

```
diff --git a/tools/topology/development/CMakeLists.txt b/tools/topology/development/CMakeLists.txt
index 11e462ae1..a775e2c8c 100644
--- a/tools/topology/development/CMakeLists.txt
+++ b/tools/topology/development/CMakeLists.txt
@@ -28,6 +28,7 @@ set(TPLGS_UP
        "sof-cml-rt5682\;sof-cml-eq-iir-rt5682\;-DPLATFORM=cml\;-DHSEARPROC=eq-iir-volume\;-DDMICPROC=eq-iir-volume\;-DDMIC16KPROC=eq-iir-volume"
        "sof-glk-da7219\;sof-glk-eq-da7219\;-DDMICPROC=eq-iir-volume"
        "sof-hda-generic\;sof-hda-generic-tdfb_50mm-2ch\;-DCHANNELS=2\;-DHSPROC=volume\;-DDMIC16KPROC=tdfb-eq-iir-volume\;-DDMIC16KPROC_FILTER1=tdfb/coef_line2_50mm_pm10deg_16khz.m4\;-DDMICPROC=tdfb-eq-iir-volume\;-DDMICPROC_FILTER1=tdfb/coef_line2_50mm_pm10deg_48khz.m4\;-DDMICPROC_FILTER2=eq_iir_coef_highpass_40hz_20db_48khz.m4\;-DDMIC16KPROC_FILTER2=eq_iir_coef_highpass_40hz_20db_16khz.m4"
+       "sof-hda-generic\;sof-hda-generic-2ch-src\;-DCHANNELS=2\;-DHSPROC=src-volume\;-DDMICPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_48khz.m4\;-DDMIC16KPROC_FILTER1=eq_iir_coef_highpass_40hz_20db_16khz.m4"
 )
 
 add_custom_target(dev_topologies ALL)

```
The built sof-hda-generic-2ch-src.tplg needs to be copied over default sof-hda-generic-2ch.tplg. The SRC is placed to headset playback pipeline.

**Reproduction Rate**
100%

**Expected behavior**
Playback sounds correct and playback time matches clip length.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA}
    * SOF: {SHA}
2) Name of the topology file
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {PLATFORM}

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

**Comment by singalsu** [comment]
Could someone familiar with HDA driver take a look. See my debug print add to hdac_hda.c, This actual rate should be updated to DSP DAI so it would pass to pipeline walk the correct rate.

**Comment by plbossart** [comment]
@kv2019i @ranj063 @singalsu I am not sure what to make of this issue. 

I don't fully understand the ask to be honest, usually one uses a sample rate to reach a fixed value enforced by a mixer. It looks like this is a test case where we artificially resample the FE with a fixed-rate SRC, but is this a real use case that we would see in a product?

**Comment by singalsu** [comment]
It seems like we should let HDA DAI to resample/re-program the codec (whatever it does) and never use SRC with HDA inputs/outputs as prevention of this issue to happen.

None of the released topologies have this issue as far as I know. So this issue could be closed if preferred.

The bug in HD-audio driver is that HDA FW driver does not get the actual rate it operates with in runtime and returns to pipeline the default 48 kHz. If the HDA DAI returned the correct actual rate, e.g. 32 kHz, then SRC would know to bypass itself. Now it doesn't have the information so SRC also does the 32->48 kHz conversion. With duplicate conversion things go wrong. HDA driver does not support all the rates that SRC does. But if 32/44.1/48 kHz covers like 99.9% of needs the need for SRC  with HDA is low.

**Comment by plbossart** [comment]
How is the SRC ratio determined? Fixed at compile-time or user-changeable?

**Comment by singalsu** [comment]
The SRC ratio is selected in run-time from pipeline upstream and downstream buffer params. In this SRC playback case the downstream params from DAI are incorrect. SRC was harmed in this case but similarly other components those are sample time interval or stream time aware would fail (beamformer, sound direction tracking). Even volume ramp time could be other than topology specifies.

Edit: I'm not sure what happens if host propagates downstream e.g. 32 kHz (what HDA codec operates at) while DAI propagates upstream the wrong 48 kHz. If the correct rate "wins" then the issues with other components won't happen.

**Comment by plbossart** [comment]
Not following at all @singalsu, a 'downstream buffer' doesn't really have a frequency, does it?

**Comment by singalsu** [comment]
In SOF src.c lines 575 - 577. The retrieved source_rate and sink_rate are used in SRC init in component params() and prepare().

```
	/* Set source/sink_rate/frames */
	cd->source_rate = sourceb->stream.rate;
	cd->sink_rate = sinkb->stream.rate;
```

(The comment there should "get") 

Originally the SRC source/sink rates were set from topology tokens where we usually fixed DAI side to 48 kHz and kept PCM side variable but changes to pipeline logic put to SRC component to only a "listener role" where it no more overwrites any stream  parameters. 

The SRC sink buffer gets the rate from pipeline parameters walk upstream where the wrong rate is returned by DAI hw params call. Linux kernel driver has initialized the wrong rate value for the HDA DAI.

**Comment by plbossart** [comment]
@singalsu do you mean that when you play 32kHz content, the DAI rate is also 32kHz because the input rate is propagated to the back-end/DAI?

**Comment by singalsu** [comment]
Yep, that happened at least when I reported this. I haven't re-checked lately. Normally we have in topology for PCMs rate min/max set to 48 kHz so the HDA driver does not try to alter the DAI rate.

**Comment by plbossart** [comment]
I don't know if this is a feature or a bug. In the case of HDAudio the DAI does not a notion of rate, see sof_pcm_dai_link_fixup(). Same for SoundWire/ALH. 

So there's really nothing telling the driver what to do. I also don't get how the firmware sink buffer might have a different rate than the inputs.

Confused.

**Comment by plbossart** [comment]
@singalsu what should we do with this issue? Either we do something or we close it...

**Comment by singalsu** [comment]
No one has had time for this, close for  now.
