### ISSUE TITLE
HDaudio: need to check if codec module is available

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#285]
The existing code fails silently if the HDaudio codecs are not selected in the Kconfig. We should have a means to find out that the request_module did not work and warn the user that the codec is not supported.
Filed as enhancement but will be needed to reduce our support load.

**Comment by wenqingfu** [comment]
please close accordingly if it's not valid any more. @RanderWang

**Comment by RanderWang** [comment]
I will check it after my tasks done.  I have 4 tasks being done now
