### ISSUE TITLE
[BUG] No sound from speakers on Acer Travelmate 614

### ISSUE THREAD

**Issue by ryanprescott** [thesofproject/linux#2851]
> Hey everyone! Thanks to the help of @Conmanx360 I have a full list of verbs that enable both speakers. However, when a sink closes, these verbs need to be reapplied. I am attaching the verbs below in hopes that someone can help further refine them (i.e. remove the unnecessary ones) and help me turn this into a patch that will be reliable and consistent.
> 
> For everyone who is struggling with this at the moment, I am going to attach a Python script with the verbs that will give you sound temporarily! Run the command again whenever the sound drops out. Extract the archive somewhere, cd into the directory, and then execute the following command:
> 
> sudo python3 applyverbs.py alc285.txt
> 
> If you're running a Lenovo Yoga / IdeaPad S740, you will have sound out of both speakers.
> 
> [verbs.zip](https://github.com/thesofproject/linux/files/6314986/verbs.zip)

Could you please provide the steps to achieve this? I have a similar problem with Acer Travelmate 614 and I dont know ho to get the verbs from Windows. It would be great to see how it can be done. Thanks.

_Originally posted by @stakaz in https://github.com/thesofproject/linux/issues/2748#issuecomment-820366778_

**Comment by ryanprescott** [comment]
@stakaz Would you be able to follow my instructions [here](https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver) and let me know if you're able to get a set of working verbs?

**Comment by stakaz** [comment]
Yeah, I already started. Thanks for this great tutorial. However, right now I cannot pass step 4. Because I first have to run `.configure` and that gies me a `-Werror:

```
ERROR: configure test passed without -Werror but failed with -Werror.
       This is probably a bug in the configure script. The failing command
       will be at the bottom of config.log.
       You can run configure with --disable-werror to bypass this check.
```

I am on Arch Linux so maybe some dependencies are missing. Have to check that further.

But I will try my best and will post my results here.

Thanks for opening this issue ;)

**Comment by stakaz** [comment]
Ah, using `--disable-werror` still ended up in an error in compilation.

**Comment by ryanprescott** [comment]
What error are you getting?

**Comment by stakaz** [comment]
Many similar things like this last one:

```
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /home/gluon/windows_vm/qemu/include/glib-compat.h:19,
                 from /home/gluon/windows_vm/qemu/include/qemu/osdep.h:107,
                 from /home/gluon/windows_vm/qemu/disas/arm-a64.cc:21:
/usr/include/c++/10.2.0/type_traits:2930:3: error: template with C linkage
 2930 |   template<typename _Fn, typename... _Args>
      |   ^~~~~~~~
/home/gluon/windows_vm/qemu/disas/arm-a64.cc:20:1: note: ‘extern "C"’ linkage started here
   20 | extern "C" {
      | ^~~~~~~~~~
make: *** [/home/gluon/windows_vm/qemu/rules.mak:86: disas/arm-a64.o] Error 1
```

**Comment by ryanprescott** [comment]
Check out this link, you'll probably have to patch this in:
https://lore.kernel.org/qemu-devel/20210320041854.68668-1-gshan@redhat.com/T/

**Comment by ryanprescott** [comment]
Here's another link that provides flags that might need to be set:
https://github.com/apertus-open-source-cinema/axiom-beta-qemu/issues/6

**Comment by stakaz** [comment]
Yeah, the build finished successfully now. Will see when I can work on it further and write here if further problems will occur.

**Comment by stakaz** [comment]
Now,  I cannot start the installation process: 

```
./qemu-system-x86_64 -enable-kvm -hda win10.img -cdrom win10.iso -m 4G -smp 4
Gtk-Message: 13:42:05.244: Failed to load module "appmenu-gtk-module"
qemu: could not load PC BIOS 'bios-256k.bin'
```

**Comment by ryanprescott** [comment]
> Now, I cannot start the installation process:
> 
> ```
> ./qemu-system-x86_64 -enable-kvm -hda win10.img -cdrom win10.iso -m 4G -smp 4
> Gtk-Message: 13:42:05.244: Failed to load module "appmenu-gtk-module"
> qemu: could not load PC BIOS 'bios-256k.bin'
> ```
Install seabios and add `-L /usr/share/seabios` to your qemu command.

**Comment by stakaz** [comment]
> > Now, I cannot start the installation process:
> > ```
> > ./qemu-system-x86_64 -enable-kvm -hda win10.img -cdrom win10.iso -m 4G -smp 4
> > Gtk-Message: 13:42:05.244: Failed to load module "appmenu-gtk-module"
> > qemu: could not load PC BIOS 'bios-256k.bin'
> > ```
> 
> Install seabios and add `-L /usr/share/seabios` to your qemu command.

Hey, this was not the solution. Bur running from original build directory was ok. Now, I am at this point: 

```
❯ sudo ./vfio-bind.sh 0000:00:1f.3
❯ ./startvm.sh
QEMU 2.12.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: -device vfio-pci,host=0000:00:1f.3,x-no-mmap=true: vfio error: 0000:00:1f.3: group 12 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
```

**Comment by ryanprescott** [comment]
Hey @stakaz!

If you get that, you need to bind each device in the 0000:00:1f group. You'll want to run:
`lspci -nn | grep 00\:1f`
and use vfio-bind.sh to bind the remaining devices. Do not rebind 0000:00:1f.3, only bind the others. For my setup I had to run:
`./vfio-bind.sh 0000:00:1f.0 0000:00:1f.4 0000:00:1f.5`
Your mileage may vary :)

**Comment by stakaz** [comment]
Its amazing! AMAZING! I have a verb sequence which enables the sound, finally. Many many thanks for it. Here it is:

[final_verbs.txt](https://github.com/thesofproject/linux/files/6330241/final_verbs.txt)

**Comment by stakaz** [comment]
It is quite large but I was not able to cut it at the beginning or the end any more. But still probably there is stuff unimportant inbetween.

**Comment by ryanprescott** [comment]
Were you getting errors from the codec when trying to cut it down or did you just lose sound from one or more speakers? You shouldn't need that many verbs to enable the sound, so I think it's worth trying to trim them down further if possible.

**Comment by ryanprescott** [comment]
[final_verbs.txt](https://github.com/thesofproject/linux/files/6330286/final_verbs.txt)
Let me know if this sequence gives you sound and if so what line number?

**Comment by stakaz** [comment]
Hey, unfortunately your provided final_verbs.txt did not worked. However, from my cleanverbs fie I was able to use a later sequence and reduce the number of verbs to 548. Here it is: 

[final_verbs.txt](https://github.com/thesofproject/linux/files/6332309/final_verbs.txt)

Hope, that this is enough...

**Comment by stakaz** [comment]
By the way, I have used the speakers for a one hour video and they did not become silent at all...

**Comment by ryanprescott** [comment]
> Hey, unfortunately your provided final_verbs.txt did not worked. However, from my cleanverbs fie I was able to use a later sequence and reduce the number of verbs to 548. Here it is:
> 
> [final_verbs.txt](https://github.com/thesofproject/linux/files/6332309/final_verbs.txt)
> 
> Hope, that this is enough...

Awesome! I can take this and turn it into a patch based on the solution that @tiwai put together. Give me a few hours and I should have something for you.

**Comment by ryanprescott** [comment]
@stakaz Hey! I need one more thing before I can get this patch going. Just need the output of the following command:
`cat /sys/bus/pci/devices/0000:00:1f.3/uevent | grep SUBSYS`

**Comment by stakaz** [comment]
> > Hey, unfortunately your provided final_verbs.txt did not worked. However, from my cleanverbs fie I was able to use a later sequence and reduce the number of verbs to 548. Here it is:
> > [final_verbs.txt](https://github.com/thesofproject/linux/files/6332309/final_verbs.txt)
> > Hope, that this is enough...
> 
> Awesome! I can take this and turn it into a patch based on the solution that @tiwai put together. Give me a few hours and I should have something for you.

Hey, unfortunately this sequence did not worked for me after a reboot. The first one still works...

I will come up with a new (hopefully short one) soon. Here it the information from `cat /sys/bus/pci/devices/0000:00:1f.3/uevent | grep SUBSYS`: 

```
PCI_SUBSYS_ID=1025:141D
```

**Comment by stakaz** [comment]
Hello, here a slightly shorter sequence but it is still ~3000 long. I cannot bring it to a shorter from. The problem is, that sometimes I can cut things from the middle and it works but after a reboot the longer sequence is needed again. 

[final_verbs_3.txt](https://github.com/thesofproject/linux/files/6336273/final_verbs_3.txt)

**Comment by stakaz** [comment]
And one more thing, I will not have the time right now to go into compiling the kernel and check the patch. Would it be possible to add it first and I will conform that it works once it is updated on my arch linux system?

**Comment by ryanprescott** [comment]
@stakaz 3000 verbs is still a bit much to try to get into the upstream kernel. If your current combination is persisting across reboots then I think you should keep using that until the Intel guys figure out how and why Realtek is using HDA verbs to control their amplifiers. With that knowledge they should be able to work to either find shorter verb sequences, or communicate with the amplifiers directly via I2C.

**Comment by stakaz** [comment]
Unfortunately, it was not persistent after a complete shutdown and restart. However, I could live with the temporary solution of using a script. Btw, could you tell me if I can apply the verbs before login after the boot process? I do not know how to run a sudo code without asking for password after I login.

**Comment by stakaz** [comment]
Possibly, at some point I could try to bring it down to less verbs but the problem is, that after I run the whole clean-verbs.txt, I end up in possible sequences of verbs which give me the sound back but which do not work after reboot... So, it is a time consuming thing to text one verb sequence at each booting time.

**Comment by ryanprescott** [comment]
@stakaz See the following:
https://wiki.archlinux.org/index.php/Systemd#Writing_custom_.service_files

**Comment by stakaz** [comment]
> @stakaz See the following:
> https://wiki.archlinux.org/index.php/Systemd#Writing_custom_.service_files

Thanks, am I correctly understand that it should be possible to use a service to apply the verbs at start?

**Comment by ryanprescott** [comment]
Yes, the daemon should be able to run those processes as root so you will
have sound immediately at startup.

**Comment by ryanprescott** [comment]
@plbossart Any luck with getting in touch with Realtek to help narrow the coefficients down?

**Comment by plbossart** [comment]
@bardliao can you try and see who supports HDaudio codecs at Realtek (Kailang?)

@ryanprescott it's a long shot, it could very well be that the amplifiers are not from Realtek. I think the idea of creating an I2C bus master to use i2c-detect would help solve this sort of support question, so that we can ask the right vendor for support.

**Comment by plbossart** [comment]
I also agree with @ryanprescott that the verb sequence is probably too verbose. There are lots of repeats, e.g.  the last ones

````
0x20 0x500 0x67
0x20 0x500 0x67
0x20 0x500 0x67
0x20 0x500 0x67
0x20 0x500 0x67
0x20 0x432 0x0
0x20 0x500 0x67
0x20 0x432 0x0
````
are not particularly self-explanatory...

**Comment by bardliao** [comment]
> @bardliao can you try and see who supports HDaudio codecs at Realtek (Kailang?)

Yes, it should be @kailangyang.

> 
> @ryanprescott it's a long shot, it could very well be that the amplifiers are not from Realtek. I think the idea of creating an I2C bus master to use i2c-detect would help solve this sort of support question, so that we can ask the right vendor for support.

ALC285 supports I2C master, so the amplifier's I2C could possibly be connected to ALC285. @ryanprescott @stakaz Do you happen to know which amplifier module it is and where is its I2C port connected to?

**Comment by stakaz** [comment]
Hello, I think it is the ALC295, not ALC285. Here the alsa-info.sh output: [alsa-info_output.txt](https://github.com/thesofproject/linux/files/6356494/alsa-info_output.txt)

**Comment by mengdonglin** [comment]
@stakaz Please contact OEM to work with Realtek and amplifier vendor to fix this issue in Linux.
