### ISSUE TITLE
[SDW][TGLU_SKU0A32_SDCA] clock stop prepare timeout

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2853]
The following warning appeared with recent code changes.
````
[  185.783544] kernel: soundwire sdw-master-3: clock stop prep/de-prep failed slave:15
[  185.783559] kernel: soundwire_intel soundwire_intel.link.3: prepare clock stop failed -110
[  185.783567] kernel: soundwire_intel soundwire_intel.link.3: cannot enable clock stop on suspend
````

Initially reported by Intel daily test 3289 but reproduced locally on my test device.

**Comment by plbossart** [comment]
git bisect shows this

````
aa90b4d4acf72a4df2c27c521ded443f48e764c0 is the first bad commit
commit aa90b4d4acf72a4df2c27c521ded443f48e764c0
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date:   Tue Apr 13 16:30:41 2021 -0500

    soundwire: bus: only use CLOCK_STOP_MODE0 and fix confusions
    
    Existing devices and implementations only support the required
    CLOCK_STOP_MODE0. All the code related to CLOCK_STOP_MODE1 has not
    been tested and is highly questionable, with a clear confusion between
    CLOCK_STOP_MODE1 and the simple clock stop state machine.
    
    This patch removes all usages of CLOCK_STOP_MODE1 - which has no
    impact on any solution - and fixes the use of the simple clock stop
    state machine. The resulting code should be a lot more symmetrical and
    easier to maintain.
    
    Note that CLOCK_STOP_MODE1 is not supported in the SoundWire Device
    Class specification so it's rather unlikely that we need to re-add
    this mode later.
    
    Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

 drivers/soundwire/bus.c       | 100 +++++++++++++++++-------------------------
 include/linux/soundwire/sdw.h |   2 -
 2 files changed, 40 insertions(+), 62 deletions(-)

````

**Comment by plbossart** [comment]
Instrumenting the code shows that this is not a regression but rather that the clock stop sequence NEVER worked properly. The commit above just forces the use of the Prepare/wait for NotFinished to be clear, and that does not happen for RT715-sdca

See https://github.com/thesofproject/linux/pull/2854, it seems that we skip the wait for the NotFinished bits for all links.

**Comment by plbossart** [comment]
@bardliao @RanderWang FYI

**Comment by plbossart** [comment]
this issue does not seem to happen with the SoundWire 1.1 version of RT715 on TGL Dell SKU 0A3E, so I am leaning to think it's any issue with the RT715-SDCA only.

@jack-cy-yu @shumingfan, can you please try on your devices? You should be able to reproduce the problem with our topic/sof-dev branch. Thanks!

**Comment by mengdonglin** [comment]
Set to P1 as it blocks us to add device TGLU_SKU0A32_SDCA to PR test.

**Comment by bardliao** [comment]
@plbossart I saw `rt715_dev_suspend` is called before `sdw_bus_prep_clk_stop`. It may not cause the issue, but is it expected?

**Comment by jack-cy-yu** [comment]
@plbossart @mengdonglin We've found the possible root cause for this timeout issue but still need some time to verify. I'll update it tommorrow.

**Comment by plbossart** [comment]
> @plbossart I saw `rt715_dev_suspend` is called before `sdw_bus_prep_clk_stop`. It may not cause the issue, but is it expected?

I think it's expected. The parent-child model will require all children to be suspended before the master device can suspend and stop the clock.

**Comment by jack-cy-yu** [comment]
@plbossart @mengdonglin  Please check #2861 for the fix.

**Comment by plbossart** [comment]
fixed.
