### ISSUE TITLE
[SDW] sof_sdw machine driver BE IDs assumes order in tables

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2894]
the sof_sdw machine driver allocates BE IDs with a specific order assumed in the descriptors, we need to have headset, amp and mic, in this order. This is typically using link 0, 1/2 and 3.

But on a Dell  TGL SKU 0A3E, the devices are swapped, and the code still assumed a fixed order in the descriptor. Changing the descriptor with the following patch to list the SoundWire parts by link number (mic, headset, amp) leads to the following topology load error:

[rt715_order.diff.txt](https://github.com/thesofproject/linux/files/6436994/rt715_order.diff.txt)

````
[   16.245041] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: physical link SDW1-Playback (id 0) not exist
[   16.245048] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: topology: could not load header: -22
[   16.245427] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1010f0f successful
[   16.245435] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[   16.245439] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[   16.245455] sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
[   16.245466] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
[   16.245471] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[   16.245528] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[   16.246008] sof_sdw sof_sdw: snd_soc_register_card failed -22
````

@RanderWang @bardliao @ranj063 FYI, we should not have any order assumed in ACPI match tables. We probably should add a BE ID property to the part descriptor in sof_sdw to avoid using an order (this would also help us get rid of the RT715 quirk).

**Comment by bardliao** [comment]
> the sof_sdw machine driver allocates BE IDs with a specific order assumed in the descriptors, we need to have headset, amp and mic, in this order. This is typically using link 0, 1/2 and 3.
> 
> But on a Dell TGL SKU 0A3E, the devices are swapped, and the code still assumed a fixed order in the descriptor. Changing the descriptor with the following patch to list the SoundWire parts by link number (mic, headset, amp) leads to the following topology load error:

The BE IDs order is based on the order in `snd_soc_acpi_link_adr` array.  That's why we have the link adr order in `tgl_sdw_rt711_link1_rt1308_link2_rt715_link0[]` for Dell TGL SKU 0A3E.

> 
> @RanderWang @bardliao @ranj063 FYI, we should not have any order assumed in ACPI match tables. We probably should add a BE ID property to the part descriptor in sof_sdw to avoid using an order (this would also help us get rid of the RT715 quirk).

Agree, adding a BE ID property can help us to specific any BE ID that we want.

**Comment by RanderWang** [comment]
> > the sof_sdw machine driver allocates BE IDs with a specific order assumed in the descriptors, we need to have headset, amp and mic, in this order. This is typically using link 0, 1/2 and 3.
> > But on a Dell TGL SKU 0A3E, the devices are swapped, and the code still assumed a fixed order in the descriptor. Changing the descriptor with the following patch to list the SoundWire parts by link number (mic, headset, amp) leads to the following topology load error:
> 
> The BE IDs order is based on the order in `snd_soc_acpi_link_adr` array. That's why we have the link adr order in `tgl_sdw_rt711_link1_rt1308_link2_rt715_link0[]` for Dell TGL SKU 0A3E.
> 
> > @RanderWang @bardliao @ranj063 FYI, we should not have any order assumed in ACPI match tables. We probably should add a BE ID property to the part descriptor in sof_sdw to avoid using an order (this would also help us get rid of the RT715 quirk).
> 
> Agree, adding a BE ID property can help us to specific any BE ID that we want.

BE ID order is based on topology, not snd_soc_acpi_link_adr array. We reuse our topology, so we have to match snd_soc_acpi_link_adr  with topology. Adding a BE ID can decouple snd_soc_acpi_link_adr with topology on definition order

**Comment by plbossart** [comment]
closing since the direction is to have a fixed order and indices to simplify topologies.
