### ISSUE TITLE
[WHL] HDA - 1, 4, 8 channels not supported by driver (used ALC700 codec)

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#290]
sof: whl-001-drop-stable/33e4b99

linux: sof-dev/af44aa9
patches:
- 0001-ASoC-codec-enable-loop-back-for-ALC700.patch
- 0001-ASoC-SOF-allocate-last-stream-for-trace.patch
[linux_rander_patches.zip](https://github.com/thesofproject/linux/files/2584449/linux_rander_patches.zip)

soft: master/5894ed4
patches:
- topology change from 32b to 16b for headphone

When I prepare tplg for 1, 4 or 8 channels and use loopback for testing. Then arecord freeze or record silence.
Example below:
![image](https://user-images.githubusercontent.com/41113230/48541891-ffa0ee80-e8bd-11e8-8a06-a208578c3d16.png)

For 2 channels aplay and arecord works fine.

**Comment by plbossart** [comment]
@emilchudzik why would you want to test 4 channel support from a codec that deals with stereo outputs? Are you expecting a downmix in the codec? What is the test case here?

**Comment by plbossart** [comment]
Also the mono case is not supported anywhere, so it's not specific to WHL. We have to decide if we want to support this or require userspace to provide stereo.

**Comment by plbossart** [comment]
@emilchudzik @mengdonglin is this issue still relevant or can it be closed?

**Comment by emilchudzik** [comment]
Yes, we can close it.
