### ISSUE TITLE
[BUG] Yoga slim 7i 15ITL05 Tiger lake only 2 of 5 speakers are working.

### ISSUE THREAD

**Issue by juliusvonkohout** [thesofproject/linux#2906]
**Describe the bug**
The three bass speakers above the keyboard do work in windows but not Linux (Fedora 34) with SOF 1.6.1. The bottom speaker for mids and highs do work. The volume for the bass speakers is fixed to "00".

**To Reproduce**
Play sound under Windows and then under Linux. The bass Speaker in Linux is off. It is not possible to change the bass speaker mixer volume.

**Reproduction Rate**
Always

**Expected behavior**
I expect the bass speaker to work.

**Impact**
showstopper

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.12.2 https://koji.fedoraproject.org/koji/buildinfo?buildID=1745028
    * SOF 1.6.1 https://koji.fedoraproject.org/koji/buildinfo?buildID=1722732

```
System Information
        MO: LR60B112001P
        MTM: 82ACCTO1WW
        Manufacturing Date: 2021/01/20
	Manufacturer: LENOVO
	Product Name: 82AC
	Version: Yoga Slim 7 15ITL05
	SKU Number: LENOVO_MT_82AC_BU_idea_FM_Yoga Slim 7 15ITL05
	Family: Yoga Slim 7 15ITL05

BIOS Information
	Vendor: LENOVO
	Version: FBCN23WW
	
Base Board Information
	Manufacturer: LENOVO
	Product Name: LNVNB161216
	Version: NO DPK          
```

**Screenshots or console output**
![grafik](https://user-images.githubusercontent.com/45896133/117548527-c7fe0200-b035-11eb-9574-1c0ed286a28b.png)

[dmesg.txt](https://github.com/thesofproject/sof/files/6446303/dmesg.txt)

"and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html" i do not know how to obtain sof-logger easily for Fedora 34.

**Comment by keyonjie** [comment]
@juliusvonkohout we support only 2 channels in hda-generic, can you ask support from the codec vendor?

**Comment by aiChaoSONG** [comment]
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/6449153/sof-dyndbg.conf.txt)

Please rename the attached file to sof-dyndbg.conf, and put it to `/etc/modprobe.d`, reboot, get dmesg output and upload again.

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout we support only 2 channels in hda-generic, can you ask support from the codec vendor?

It is stereo / 2.0 , but using multiple amplifiers and 5 Speakers. A lot of new Lenovo Laptops have that configuration.

**Comment by juliusvonkohout** [comment]
> [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/6449153/sof-dyndbg.conf.txt)
> 
> Please rename the attached file to sof-dyndbg.conf, and put it to `/etc/modprobe.d`, reboot, get dmesg output and upload again.

[dmesg.txt](https://github.com/thesofproject/linux/files/6451292/dmesg.txt)

**Comment by plbossart** [comment]
@juliusvonkohout please see some of the documentation at https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#disable-sof-on-pci-hdaudio-devices-to-test-audio-playback

As said above, SOF only generates 2 channels for HDaudio, so you are likely facing a codec driver issue. Please try to reproduce this issue with the legacy driver. 

If this is confirmed, then you are probably facing a case of additional I2C/I2S amplifiers connected behind the HDaudio amplifiers, with missing configurations for those additional amplifiers.

The good news is that there are instructions from @ryanprescott at https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver to get the codec configurations from Windows and create a set of commands that will work for Linux.

Also copying @mrhpearson, if indeed this configuration is present on all new Lenovo devices?

**Comment by juliusvonkohout** [comment]
[dmesg_snd-intel-dspcfg-dsp_driver=1.txt](https://github.com/thesofproject/linux/files/6454038/dmesg_snd-intel-dspcfg-dsp_driver.1.txt)

So i guess it is the amplifier. Other Lenovo Laptops have kernel bugs regarding the amplifiers https://bugzilla.kernel.org/show_bug.cgi?id=205755 but there are some models which have solutions https://bugs.launchpad.net/ubuntu/+source/alsa-ucm-conf/+bug/1872108.  This patch for the lenovo yoga X1 looks very similar https://mailman.alsa-project.org/pipermail/alsa-devel/2020-February/162605.html. I guess all Lenovo highend laptops with multiple speakers have that issue. 

I will try to reverse engineer it, but it will take some time because i have to adapt https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver to from Ubuntu to Fedora 34

**Comment by plbossart** [comment]
no update in 4 months and it's not an SOF bug but a codec driver issue, closing
