### ISSUE TITLE
Topology load fails if EQ configuration data is long enough to exceed 384 bytes IPC limit

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#2910]
The error in dmesg looks like:

```
[    2.787089] sof-audio-pci-intel-cnl 0000:00:1f.3: error: ipc error for 0x30010000 size 20
[    2.787093] sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to load widget EQFIR7.0
[    2.787185] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1010f0f successful
[    2.787509] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[    2.787514] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.787534] sof-audio-pci-intel-cnl 0000:00:1f.3: error: tplg component load failed -22
[    2.787543] sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to load DSP topology -22
[    2.787546] sof-audio-pci-intel-cnl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[    2.787574] cml_rt1011_rt5682 cml_rt1011_rt5682: ASoC: failed to instantiate card -22
[    2.787633] cml_rt1011_rt5682: probe of cml_rt1011_rt5682 failed with error -22

```

There is no firmware trace output from failed topology load but with a modified kernel it can be seen that it is issued by check hdr->size > SOF_IPC_MSG_MAX_SIZE in mailbox_validate() in handler-ipc3.c.

I used topology developoment/sof-cml-rt1011-rt5682-eq.tplg. The speaker EQ configuration was modified with topology build with additions -DSPKPROC_FILTER1=eq_iir_coef_pass.m4 and -DSPKPROC_FILTER2=eq_fir_coef_loudness.m4. The hex blob eq_fir_coef_loudness.m4 was modified by editing filter length to 192 from tools/tune/eq/example_fir_eq.m and re-run of the Octave script and topologies build.

The default eq_fir_coef_loudness.m4 loads correctly because the new() IPC just under 384 byte limit.

This issue impacts all components those depend on binary blob configuration that potentially exceeds SOF_IPC_MSG_MAX_SIZE.

**Comment by singalsu** [comment]
I just checked that commit da1f1790e64a00de9490891fc511f38537e4b070 works OK and next commit ff59766e99d9314013b697d0ab47f4fef170a328 fails.

**Comment by juimonen** [comment]
Trying to figure out with @singalsu what's going on here:

Loading a process component works currently by embedding the related controls data to the process widget. This is how the initial parameters are propagated to the process component. Getting the data from related control relies on the fact that the MAX_IPC_SIZE corresponds between kernel and fw. If the MAX_IPC_SIZE is exceeded, we just discard the control data and create the control anyway (with NULL config) -> control data needs to be sent separately later.

Now if the kernel says "you're not exceeding the ipc size limit", but fw say "yes you are" -> we fail to load the whole topology. So the fact that kernel and fw sizes should match is kind of crucial to this feature.

I see 2 solutions here:

1) we need to match the kernel and fw ipc max sizes
2) if we can rely on the fact that controls are always sent/set before streaming starts (even without PM), we could remove the initial embedding of the kcontrol data to the widget

@ranj063 do you know is 2 possible/working with current dynamic pipes?

**Comment by juimonen** [comment]
So if any product at this point has a topology with byte control over 384 bytes associated with process component -> the topology loading will fail with current sof-dev kernel.

**Comment by singalsu** [comment]
Reminder for myself once this fixed: Make the example FIR configuration larger to trigger this issue, get such pipeline to a topology that is being run in CI.

**Comment by singalsu** [comment]
#2911 is merged.
