### ISSUE TITLE
[BUG][TGL]TGLU_RVP_HDA failed when aplaying using HDMI , dai_hw_param error on iDisp1 Pin

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#2934]
**Describe the bug**

 Failed since internal daily test 3910 [May 12] , good in internal daily 3868[May 10]. (something wrong with May 11 daily test  so it is abandoned)
When aplaying on HDMI[hw:0,3],it failed.  Unable to install hw params

**To Reproduce**
aplay   -Dhw:0,3 -r 48000 -c 2 -f S16_LE -d 3 /dev/zero -v -q
OR
TPLG=sof-hda-generic-4ch-kwd.tplg ~/sof-test/test-case/check-playback.sh -d 10 -l 1 -r 1

**Reproduction Rate**
100%

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: : 93d91f00
SOF Branch: main
SOF Commit: d337c0a9bab0
TPLG= sof-hda-generic-4ch-kwd.tplg
Device:TGLU_RVP_HDA

**Screenshots or console output**
[Console log]
```
ubuntu@sh-tglu-rvp-hda-05:~$ aplay   -Dhw:0,3 -r 48000 -c 2 -f S16_LE -d 3 /dev/zero -v -q
aplay: set_params:1407: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: (85333 85334)
PERIOD_SIZE: 4096
PERIOD_BYTES: 16384
PERIODS: 4
BUFFER_TIME: (341333 341334)
BUFFER_SIZE: 16384
BUFFER_BYTES: 65536
TICK_TIME: 0

```
[dmesg]
 ```
sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on iDisp1 Pin: -22
iDisp1: ASoC: soc_pcm_hw_params() failed (-22)
HDMI1: ASoC: dpcm_fe_dai_hw_params failed (-22)
```
[sof-logger]
[sof-logger.txt](https://github.com/thesofproject/sof/files/6509600/sof-logger.txt)

**Comment by keyonjie** [comment]
Hi @kv2019i looks like it fails at the driver side, so no any FW error in sof-logger, can you help to check this?

**Comment by kv2019i** [comment]
@keyonjie and @XiaoyunWu6666 this seems like a regression in 5.13-rc1. We pulled in the 5.13-rc1 on May 12 (with https://github.com/thesofproject/linux/pull/2918 ) and that brought 14000+ new commits to sof-dev. Apparently this regression was introduced then. Let me investigate.

**Comment by kv2019i** [comment]
Investigated the issue on the affected test device and dmesg shows this:
[ 3323.645868] sof-audio-pci-intel-tgl 0000:00:1f.3: filtered codec_mask = 0x1

The error is expected in this case if playback to HDMI/DP is attempted.

Once the module parameter override is removed ("snd_sof_intel_hda_common codec_mask=0x1), HDMI/DP playback works again.

**Comment by keyonjie** [comment]
> Investigated the issue on the affected test device and dmesg shows this:
> [ 3323.645868] sof-audio-pci-intel-tgl 0000:00:1f.3: filtered codec_mask = 0x1
> 
> The error is expected in this case if playback to HDMI/DP is attempted.
> 
> Once the module parameter override is removed ("snd_sof_intel_hda_common codec_mask=0x1), HDMI/DP playback works again.

Nice quick fix! @marc-hb @aiChaoSONG @XiaoyunWu6666 can you help to change this on the TGLU RVPs in the CI pool, to survive tomorrow's daily?

**Comment by marc-hb** [comment]
Someone or something added the following 3 lines at the bottom of the stock Ubuntu `/etc/modprobe.d/alsa-base.conf` on `sh-tglu-rvp-hda-05`


```
options snd-sof sof_ipc_version_choice=1
options snd-sof-pci sof_ipc_version=1
options snd_sof_intel_hda_common codec_mask=0x1
```
There is no comment explaining who did this or why. @XiaoyunWu6666 , @keqiaozhang , @aiChaoSONG , @fredoh9 any idea?

I did not check other systems.

**Comment by fredoh9** [comment]
Nice catch, looks someone used that device for development/test, didn't restore all touched.
I think this is the danger of sharing devices. We need to have simple way to restore default settings. (I don't have simple/easy way but someone touched restores back)

**Comment by aiChaoSONG** [comment]
This issue is confirmed to be wrong kernel parameters are used,  remove below contents from `/etc/modprobe.d/alsa-base.conf`, we are good.
```
options snd-sof sof_ipc_version_choice=1
options snd-sof-pci sof_ipc_version=1
options snd_sof_intel_hda_common codec_mask=0x1
```
close for issue resolved.
