### ISSUE TITLE
Tiger lake-LP Smart Sound Technology Audio has no sound issue

### ISSUE THREAD

**Issue by iammrallblue** [thesofproject/linux#2939]
MODEL: LG GRAM 16 2021
Tiger lake-LP Smart Sound Technology Audio has no sound issue
Bluetooth and headphones are working without any issues.
However, the speaker is totally not functioning.

**Comment by plbossart** [comment]
@iammrallblue please take a look at https://thesofproject.github.io/latest/getting_started/index.html#debug-audio-issues-on-intel-platforms and try to provide a narrower description of the issue with the speakers. There's not much we can do with the 'totally not functioning' one-liner.

**Comment by kv2019i** [comment]
No update in a week. It would seem this is another case of custom code needed to initialize the speaker amp and thus is a codec driver side issue. Not a DSP/SOF issue, so closing here. Bug is tracked e.g. here https://bugzilla.kernel.org/show_bug.cgi?id=212041
