### ISSUE TITLE
3 possible memory leak issues

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#294]
There‘re three possible memory leak issues on kernel driver:

Details:
#1:Possible memory leak. Dynamic memory stored in 'sroute->route.source' allocated through function 'kstrdup' at line 2311 can be lost at line 2336
/home/otc/sof/kernel/cros-sof-v4.14-rebase/sound/soc/sof/topology.c:2336 | sof_route_load()

#2:Possible memory leak. Dynamic memory stored in 'sroute->route.sink' allocated through function 'kstrdup' at line 2315 can be lost at line 2336
/home/otc/sof/kernel/cros-sof-v4.14-rebase/sound/soc/sof/topology.c:2336 | sof_route_load()

#3:Memory leak. Dynamic memory stored in 'sroute->route.control' allocated through function 'kstrdup' at line 2322 is lost at line 2336
/home/otc/sof/kernel/cros-sof-v4.14-rebase/sound/soc/sof/topology.c:2336 | sof_route_load()

**Comment by mengdonglin** [comment]
@keqiaozhang @ranj063 are these 3 issues fixed?

**Comment by keqiaozhang** [comment]
@mengdonglin these three issues are still open.

**Comment by mengdonglin** [comment]
Closing this issue as they've been declared a non-issue for now.
