### ISSUE TITLE
[BUG] [SDW] IO error in rt700_jack_detect_handler on  CML_RVP_SDW

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#2943]
Describe the bug
Appeared on May 27 internal daily test , 4235 . in case check-suspend-resume-50
IO error in rt700_jack_detect_handler on  CML_RVP_SDW

To Reproduce
 TPLG=sof-cml-rt700-4ch.tplg ~/sof-test/test-case/check-suspend-resume.sh -l 50

Reproduction Rate
100%

Model
CML_RVP_SDW

Environment
Kernel Branch: topic/sof-dev
Kernel Commit: 6dca03a2
SOF Branch: main
SOF Commit: d736888

Screenshots or console output
[console]
```
2021-06-01 03:03:18 UTC [INFO] ===== Round(1/50) =====
2021-06-01 03:03:18 UTC [COMMAND] Run the command: rtcwake -m mem -s 5
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Tue Jun  1 03:03:24 2021
2021-06-01 03:03:26 UTC [COMMAND] sleep for 5
2021-06-01 03:03:31 UTC [INFO] Check for the kernel log status
declare -- cmd="journalctl_cmd --since=@1622516593"
2021-06-01 03:03:31 UTC [ERROR] Caught kernel log error
===========================>>
[  526.518862] kernel: IO error in rt700_jack_detect_handler, ret -16
<<===========================
2021-06-01 03:03:31 UTC [ERROR] Caught error in kernel log

```

**Comment by plbossart** [comment]
[dmesg.txt](https://github.com/thesofproject/linux/files/6554478/dmesg.txt)

**Comment by plbossart** [comment]
@XiaoyunWu6666 is this really 100% reproducible? If yes, can you try reverting PR https://github.com/thesofproject/linux/pull/2941 to see if this makes the problem go away?

**Comment by plbossart** [comment]
@shumingfan @bardliao I wonder if there is a potential for a race condition. The set_jack callback is invoked from the machine driver level, and I wonder if we should have a pm_runtime_get_sync()/ pm_runtime_put_autosuspend() protection when we try to initialize the jack. The current test on hw_init is a bit flaky IMHO. I also wonder if we should set the jack to NULL when we suspend, as done for a lot of cards.

**Comment by shumingfan** [comment]
> @shumingfan @bardliao I wonder if there is a potential for a race condition. The set_jack callback is invoked from the machine driver level, and I wonder if we should have a pm_runtime_get_sync()/ pm_runtime_put_autosuspend() protection when we try to initialize the jack. The current test on hw_init is a bit flaky IMHO. I also wonder if we should set the jack to NULL when we suspend, as done for a lot of cards.

@plbossart I also think it is possible that the unexpected interrupt happened after the codec suspended.
@XiaoyunWu6666 Could you test with PR #2949 and turn on the debug log of the codec driver?
If the test result still fails, please share the kernel log.

**Comment by XiaoyunWu6666** [comment]
@shumingfan @plbossart 
I'll check it asap , thanks.

**Comment by XiaoyunWu6666** [comment]
> @XiaoyunWu6666 Could you test with PR #2949 and turn on the debug log of the codec driver?
> If the test result still fails, please share the kernel log.

Tested with PR #2949  and the test result still failed.
The kernel log is as the attachment.
[dmesg.txt](https://github.com/thesofproject/linux/files/6567352/dmesg.txt)

**Comment by shumingfan** [comment]
> Tested with PR #2949 and the test result still failed.
> The kernel log is as the attachment.
> [dmesg.txt](https://github.com/thesofproject/linux/files/6567352/dmesg.txt)

@XiaoyunWu6666 Could you enable the debug log of the codec driver and share the kernel log again?

**Comment by XiaoyunWu6666** [comment]
@shumingfan  Sure 
[dmesg_with_codeclog.txt](https://github.com/thesofproject/linux/files/6567647/dmesg_with_codeclog.txt)

**Comment by shumingfan** [comment]
> @shumingfan Sure
> [dmesg_with_codeclog.txt](https://github.com/thesofproject/linux/files/6567647/dmesg_with_codeclog.txt)

@bardliao @plbossart I checked this log. The system is so quick going to suspend from the resume state when the issue happened.

**[  170.958907] rt700 sdw:1:025d:0700:00: in rt700_dev_resume jd enable**
[  170.958987] rt700 sdw:1:025d:0700:00: [rt700_sdw_write] 3501 <= 0003
[  170.959013] soundwire_intel soundwire_intel.link.1: Slave status change: 0x40
[  170.959079] rt700 sdw:1:025d:0700:00: [rt700_sdw_write] 3501 <= 0000
**[  170.959312] rt700 sdw:1:025d:0700:00: Slave impl defined interrupt**
[  170.959316] rt700 sdw:1:025d:0700:00: rt700_interrupt_callback control_port_stat=4
[  170.959407] rt700 sdw:1:025d:0700:00: [rt700_sdw_write] 3819 <= 0000
[  170.959676] rt700 sdw:1:025d:0700:00: [rt700_sdw_write] 3821 <= 0000
[  170.959761] rt700 sdw:1:025d:0700:00: [rt700_sdw_write] 3855 <= 0000
**[  170.959765] rt700 sdw:1:025d:0700:00: in rt700_dev_suspend jd disable**
[  170.959934] rt700 sdw:1:025d:0700:00: [rt700_sdw_write] 3501 <= 0003
[  170.959954] soundwire_intel soundwire_intel.link.1: Slave status change: 0x20
[  170.960045] soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
[  170.960081] soundwire_intel soundwire_intel.link.0: intel_suspend: pm_runtime status: suspended
[  170.960202] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x20140000 successful
[  170.960235] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  170.960479] sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  170.960624] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1010f0f successful
[  170.960656] sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[  170.960667] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  170.960923] sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[  170.960944] sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
[  170.960949] sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D3
[  170.963055] e1000e: EEE TX LPI TIMER: 00000011
**[  171.212657] IO error in rt700_jack_detect_handler, ret -16**

There is a Slave impl defined interrupt when the resume state, however, the system went to suspend state before the interrupt handler finishes.
In the bus driver, the sdw_handle_slave_alerts function should wake up the codec driver and call the interrupt callback function.
Could we add the pm_runtime_mark_last_busy in the front of sdw_handle_slave_alerts function that keeps the codec driver active?

**Comment by bardliao** [comment]
It is weird. We have [pm_runtime_mark_last_busy(&slave->dev);](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/bus.c#L1676) in [sdw_handle_slave_alerts](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/bus.c#L1480). `rt700_dev_suspend` is supposed to triggered after 3 sec.

**Comment by bardliao** [comment]
@XiaoyunWu6666 Can you try below patch?
```patch
diff --git a/sound/soc/codecs/rt700-sdw.c b/sound/soc/codecs/rt700-sdw.c
index ff9c081fd52a..5df68de7eac1 100644
--- a/sound/soc/codecs/rt700-sdw.c
+++ b/sound/soc/codecs/rt700-sdw.c
@@ -9,6 +9,7 @@
 #include <linux/delay.h>
 #include <linux/device.h>
 #include <linux/mod_devicetable.h>
+#include <linux/pm_runtime.h>
 #include <linux/soundwire/sdw.h>
 #include <linux/soundwire/sdw_type.h>
 #include <linux/soundwire/sdw_registers.h>
@@ -419,6 +420,7 @@ static int rt700_interrupt_callback(struct sdw_slave *slave,
                "%s control_port_stat=%x", __func__, status->control_port);

        if (status->control_port & 0x4) {
+               pm_runtime_mark_last_busy(&slave->dev);
                mod_delayed_work(system_power_efficient_wq,
                        &rt700->jack_detect_work, msecs_to_jiffies(250));
        }
```

**Comment by XiaoyunWu6666** [comment]
@bardliao  It still failed. (even faster...)
The dmesg log is as the following.
[dmesg_log.txt](https://github.com/thesofproject/linux/files/6573069/dmesg_log.txt)

**Comment by bardliao** [comment]
@XiaoyunWu6666 Sorry, I meant test with https://github.com/thesofproject/linux/pull/2949 + my [patch](https://github.com/thesofproject/linux/issues/2943#issuecomment-851759415)

**Comment by XiaoyunWu6666** [comment]
> @XiaoyunWu6666 Sorry, I meant test with #2949 + my [patch](https://github.com/thesofproject/linux/issues/2943#issuecomment-851759415)

oh I misunderstood. Let me check it again :)

It failed again @bardliao

**Comment by shumingfan** [comment]
@XiaoyunWu6666 Would you please check the node as below after the issue happened?
$ cat /sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power/audosuspend_delay_ms
$ cat /sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power/control
$ cat /sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power/runtime_status

**Comment by XiaoyunWu6666** [comment]
@shumingfan 
```
ubuntu@sh-cml-rvp-sdw-04:/sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power$ cat autosuspend_delay_ms
3000
ubuntu@sh-cml-rvp-sdw-04:/sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power$ cat control
auto
ubuntu@sh-cml-rvp-sdw-04:/sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power$ cat runtime_status
suspended
ubuntu@sh-cml-rvp-sdw-04:/sys/bus/soundwire/drivers/rt700/sdw:1:025d:0700:00/power$
```

**Comment by plbossart** [comment]
@bardliao @shumingfan this is a nice bug...

````c
static int sdw_handle_slave_alerts(struct sdw_slave *slave)
{
	sdw_modify_slave_status(slave, SDW_SLAVE_ALERT);

	ret = pm_runtime_get_sync(&slave->dev);

	do {
		slave_notify = false;

		// check interrupts 


		/* Update the Slave driver */
		if (slave_notify && slave->ops &&
		    slave->ops->interrupt_callback) {
			slave_intr.sdca_cascade = sdca_cascade;
			slave_intr.control_port = clear;
			memcpy(slave_intr.port, &port_status,
			       sizeof(slave_intr.port));

			slave->ops->interrupt_callback(slave, &slave_intr);
		}

		// recheck interrupt status

		/* we can get alerts while processing so keep retrying */
	} while (stat != 0 && count < SDW_READ_INTR_CLEAR_RETRY);

	if (count == SDW_READ_INTR_CLEAR_RETRY)
		dev_warn(&slave->dev, "Reached MAX_RETRY on alert read\n");

io_err:
	pm_runtime_mark_last_busy(&slave->dev);
	pm_runtime_put_autosuspend(&slave->dev);

	return ret;
````

We already state the mark_last_busy at the end of the interrupts handling, so adding one more in the codec driver will do nothing.

I think we need more traces to see what happens

**Comment by plbossart** [comment]
Cannot reproduce this bug on my side, added a test PR #2967 to try to get more traces. I've run 120+ cycles of suspend-resume and counting, no error

@XiaoyunWu6666 please re-run this PR if you don't mind.

**Comment by plbossart** [comment]
Changing test devices, I can reproduce this bug. This is really nasty, we suspend immediately after a resume and have an interrupt *after* the end of the suspend without resuming.

````
[  316.423170] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_resume: end
[  316.423173] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_suspend: start
[  316.423175] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_suspend: end
[  316.423325] kernel: rt700 sdw:1:025d:0700:00: Slave impl defined interrupt
[  316.423326] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_interrupt_callback: start
[  316.423327] kernel: rt700 sdw:1:025d:0700:00: rt700_interrupt_callback control_port_stat=4
[  316.423329] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_interrupt_callback: end
[  316.423599] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
[  316.423670] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x20140000 successful
[  316.423681] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  316.423997] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  316.424105] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1010f0f successful
[  316.424137] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[  316.424147] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  316.424403] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[  316.424424] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
[  316.424426] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D3

[  316.678395] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_jack_detect_handler: start
[  316.678547] kernel: IO error in rt700_jack_detect_handler, ret -16
````

**Comment by plbossart** [comment]
It turns out this is a case where we do a system_suspend immediately after a pm_runtime resume, and we get an interrupt *AFTER* the system suspend.

This is really interesting because we disable interrupts handling at the master level, but because of the parent-child hierarchy the child has to be suspended first, so there's a window where the child is system-suspended, but the parent isn't.

````
[   73.219827] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_resume: end
[   73.219828] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_pm_runtime_resume: end

[   73.219831] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_system_suspend: start
[   73.219832] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_suspend: start 
[   73.219834] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_suspend: end 
[   73.219835] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_dev_system_suspend: end

[   73.219978] kernel: rt700 sdw:1:025d:0700:00: Slave impl defined interrupt
[   73.219980] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_interrupt_callback: start
[   73.219981] kernel: rt700 sdw:1:025d:0700:00: rt700_interrupt_callback control_port_stat=5
[   73.219982] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_interrupt_callback: end

[   73.220256] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
[   73.220325] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x20140000 successful
[   73.220336] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   73.220874] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   73.220990] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1010f0f successful
[   73.221022] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[   73.221032] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[   73.221289] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[   73.221310] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Turning i915 HDAC power 0
[   73.221312] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: Current DSP power state: D3
[   73.228789] kernel: sd 2:0:0:0: [sda] Synchronizing SCSI cache
[   73.228868] kernel: sd 2:0:0:0: [sda] Stopping disk

[   73.472818] kernel: rt700 sdw:1:025d:0700:00: plb: rt700_jack_detect_handler: start
[   73.472970] kernel: IO error in rt700_jack_detect_handler, ret -16
````

If we have an interrupt while doing a pm_runtime suspend, there is a pm_runtime_get_sync() that will force a resume, but if we do a system suspend this will have no effect.

I think the only solution is to disable interrupts when we do a system suspend.

Wow, this is a nice one that could happen on all devices that can send an interrupt.

@bardliao @shumingfan comments welcome.

[dmesg.txt](https://github.com/thesofproject/linux/files/6594752/dmesg.txt)

**Comment by plbossart** [comment]
Updated PR #2967 with tentative fix to prevent the interrupt_callback from dealing with jack detection. Not completely happy about a custom solution when this can happen for other devices as well.

**Comment by bardliao** [comment]
> I think the only solution is to disable interrupts when we do a system suspend.
> 
> Wow, this is a nice one that could happen on all devices that can send an interrupt.
> 
> @bardliao @shumingfan comments welcome.
> 

I don't have a better solution, but if we disable the interrupt we will lose the wake up feature, right? For example, a product may want to wake up the system when the headset button is pressed.

**Comment by shumingfan** [comment]
> I think the only solution is to disable interrupts when we do a system suspend.
> 
> Wow, this is a nice one that could happen on all devices that can send an interrupt.
> 
> @bardliao @shumingfan comments welcome.

Is it possible to remove the SET_SYSTEM_SLEEP_PM_OPS?

**Comment by plbossart** [comment]
> Is it possible to remove the SET_SYSTEM_SLEEP_PM_OPS?

I don't think so @shumingfan, we still need to cancel the workqueues if an interrupt happens just before the suspend.

**Comment by plbossart** [comment]
Updated PR in https://github.com/thesofproject/linux/pull/2975

Let's see what @XiaoyunWu6666 and @fredoh9 find in tests.

**Comment by XiaoyunWu6666** [comment]
Sorry to miss the comment. @plbossart 

I just run the testcase[TPLG=sof-cml-rt700-4ch.tplg ~/sof-test/test-case/check-suspend-resume.sh -l 50] 4 times and 3  of them were 'PASS'! At least #2975 reduces the probability of this issue , compared to before.

However another error appeared once. Pity that I only got the console log of it and haven't reproduced it yet so far.
Put the log here and once I can reproduce it I'll post more detailed information . Thanks

```
2021-06-08 06:40:28 UTC [ERROR] Caught kernel log error
===========================>>
[  726.332598] kernel: soundwire_intel soundwire_intel.link.3: intel_resume failed: MCP_CONTROL_HW_RST is not cleared
[  729.526300] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: MCP_CONTROL_HW_RST is not cleared
<<===========================
2021-06-08 06:40:28 UTC [ERROR] Caught error in kernel log
```

Will check it later with other DUTs when they are availabel

**Comment by plbossart** [comment]
@XiaoyunWu6666 this is a separate issue, I also saw the problem with MCP_CONTROL_HW_RST and added a reference in issue https://github.com/thesofproject/linux/issues/2606

The good thing is that we know exactly where this happens so we can start debugging. But like I said it's a different issue happening on resume while this IO error happens on suspend.

**Comment by marc-hb** [comment]
FWIW this has been the most frequent failure in my (unrelated) Pull Requests over the last few days, I would say about 80-90% of the time. Fortunately the error message makes it very clear to identify, so it does not cost that much time.

**Comment by plbossart** [comment]
Fixed by https://github.com/thesofproject/linux/pull/2978
