### ISSUE TITLE
[BUG] [SDW] RT5682 not recognized on TGLU_VOLT_SDW

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#2945]
Describe the bug
Appeared on May 27 internal daily test , 4235
when check-suspend-resume-with-playback-25   on TGLU_VOLT_SDW , it failed

To Reproduce
TPLG=sof-tgl-sdw-max98373-rt5682.tplg ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 15 -m playback

Reproduction Rate
100%

Model
TGLU_VOLT_SDW

Environment
Kernel Branch: topic/sof-dev
Kernel Commit: 6dca03a2
SOF Branch: main
SOF Commit: d736888aa5a5

Screenshots or console output
[console]
```
2021-05-26 21:26:21 UTC [ERROR] Caught kernel log error
===========================>>
[  122.341922] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff is not rt5682
[  122.341937] kernel: rt5682 sdw:0:025d:5682:00: Update Slave status failed:-19
<<===========================
2021-05-26 21:26:21 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2021-05-26 21:26:21 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-playback.sh
```
[sof-logger.txt](https://github.com/thesofproject/sof/files/6551457/sof-logger.txt)

**Comment by plbossart** [comment]
[dmesg.txt](https://github.com/thesofproject/linux/files/6554701/dmesg.txt)

**Comment by plbossart** [comment]
@XiaoyunWu6666 You are confusing two issues, I modified the title to focus on the rt5682 problem. Please file a separate issue for HDMI.

**Comment by plbossart** [comment]
I don't know what is going on on this platform, there was a prior fix from @shumingfan in 867f8d18df4f5 to read the ID register in a loop.
@XiaoyunWu6666 is this really 100% reproducible?

**Comment by XiaoyunWu6666** [comment]
> I don't know what is going on on this platform, there was a prior fix from @shumingfan in [867f8d1](https://github.com/thesofproject/linux/commit/867f8d18df4f5ccd6c2daf4441a6adeca0b9725b) to read the ID register in a loop.
> @XiaoyunWu6666 is this really 100% reproducible?

Yes 100% reproducible. This  was reproduced by CI daily test since May 27. I also double-checked it manually.

**Comment by XiaoyunWu6666** [comment]
> I don't know what is going on on this platform, there was a prior fix from @shumingfan in [867f8d1](https://github.com/thesofproject/linux/commit/867f8d18df4f5ccd6c2daf4441a6adeca0b9725b) to read the ID register in a loop.
> @XiaoyunWu6666 is this really 100% reproducible?

hi @plbossart  may you try 'TPLG=sof-tgl-sdw-max98373-rt5682.tplg ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 15 -m playback' on ubuntu@sh-tglu-volt-sdw-03. This can reproduce the issue 100%.

**Comment by XiaoyunWu6666** [comment]
I will check whether this can be reproduced on another TGLU_VOLT_SDW DUT and bisect if yes

**Comment by XiaoyunWu6666** [comment]
Bisect Result
============
```
1d150b78ffb9813fac99ef1455887dffecf2ae79 is the first bad commit
commit 1d150b78ffb9813fac99ef1455887dffecf2ae79
Author: Bard Liao <yung-chuan.liao@linux.intel.com>
Date:   Mon May 17 17:24:39 2021 +0800

    soundwire: bus: update Slave status in sdw_clear_slave_status

    Call to sdw_update_slave_status() needs to be added to sdw_clear_slave_
    status() to ensure Slaves are informed of the new status via update_
    status() callback.

    This will enable codec drivers to reset their internal states and make
    sure the register settings are properly restored on pm_runtime or
    system resume

    BugLink: https://github.com/thesofproject/linux/issues/2908
    BugLink: https://github.com/thesofproject/linux/issues/2637
    Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

 drivers/soundwire/bus.c | 1 +
 1 file changed, 1 insertion(+)
```

**Comment by bardliao** [comment]
@oder-chiou With 1d150b78ffb9813fac99ef1455887dffecf2ae79 `rt5682_update_status(SDW_SLAVE_UNATTACHED)` and rt5682_io_init() will be called during suspend/resume cycle. But we will get `Device with ID register ffffff is not rt5682` in this process. Could you take a look?

**Comment by oder-chiou** [comment]
Please help to test the attached patch for debuging further, and please provide the dmesg.txt again, thanks.

[0001-ASoC-rt5682-Add-loop-time-for-test.zip](https://github.com/thesofproject/linux/files/6569423/0001-ASoC-rt5682-Add-loop-time-for-test.zip)

**Comment by XiaoyunWu6666** [comment]
@oder-chiou  tested on sh-tglu-volt-sdw-03 and dmesg log is shown as the following.
[dmesg.txt](https://github.com/thesofproject/linux/files/6605777/dmesg.txt)

**Comment by bardliao** [comment]
@XiaoyunWu6666 Could you test it with https://github.com/thesofproject/linux/pull/2977

**Comment by XiaoyunWu6666** [comment]
it works well @bardliao
