### ISSUE TITLE
[BUG] [ADL][1.8-rc2] hw param error when playback/capture

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#2950]
Describe the bug
Appeared on May 25 internal stable_v1_8_stress test , 4183
A lot of test cases related with playback/capture failed on ADLP_RVP_HDA

To Reproduce
TPLG=sof-hda-generic-4ch-kwd.tplg ~/sof-test/test-case/run-all-tests.sh

Reproduction Rate
5%

Model
ADLP_RVP_HDA

Environment
Kernel Tag: https://github.com/thesofproject/linux/commits/release-sof-1.8-20210524
Kernel Branch: release-v1.8 (this is a temp branch created from the above tag)
Kernel Commit: a2c895e8
SOF stable-v1.8
SOF Commit: 8d1a591ec22c_release

hw params issue happens when doing the test on ADLP_RVP_HDA. 

userspace log:
arecord: set_params:1407: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S32_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 128
CHANNELS: 4
RATE: 48000
PERIOD_TIME: (21333 21334)
PERIOD_SIZE: 1024
PERIOD_BYTES: 16384
PERIODS: 4
BUFFER_TIME: (85333 85334)
BUFFER_SIZE: 4096
BUFFER_BYTES: 65536
TICK_TIME: 0

dmesg:
[  695.629853] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30100000: GLB_TPLG_MSG: PIPE_NEW
[  695.630230] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30100000: GLB_TPLG_MSG: PIPE_NEW
[  695.630257] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.10.DMIC0.IN setup complete
[  695.630272] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[  695.630520] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[  695.630521] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM6C setup complete
[  695.630539] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[  695.630809] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[  695.630815] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget BUF10.0 setup complete
[  695.630833] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[  695.631249] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[  695.631278] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  695.631828] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x80010000 size 12
[  695.631837] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to set dai config for dmic01
[  695.631840] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load dai config for DAI DMIC0.IN
[  695.631849] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000: GLB_TPLG_MSG: COMP_FREE
[  695.632233] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30020000: GLB_TPLG_MSG: COMP_FREE
[  695.632249] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget DMIC0.IN freed
[  695.632253] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000: GLB_TPLG_MSG: COMP_FREE
[  695.632519] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30020000: GLB_TPLG_MSG: COMP_FREE
[  695.632520] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM6C freed
[  695.632527] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30210000: GLB_TPLG_MSG: BUFFER_FREE
[  695.632733] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30210000: GLB_TPLG_MSG: BUFFER_FREE
[  695.632737] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget BUF10.0 freed
[  695.632741] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30110000: GLB_TPLG_MSG: PIPE_FREE
[  695.633293] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30110000: GLB_TPLG_MSG: PIPE_FREE
[  695.633311] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.10.DMIC0.IN freed
[  695.633317] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed widget list set up for pcm 6 dir 1
[  695.633320] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -12
[  695.633328] kernel:  DMIC: ASoC: soc_pcm_hw_params() failed (-12)
[  695.633333] kernel:  DMIC: ASoC: dpcm_fe_dai_hw_params failed (-12)
[  695.633337] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: free stream 6 dir 1
[  695.633564] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: close stream 6 dir 1
[  696.596414] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  696.596473] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  697.767696] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x20140000 successful
[  697.822987] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  697.823319] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  697.823386] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xb010f0f successful
[  697.823609] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[  697.823615] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  697.823730] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[  697.823755] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Current DSP power state: D3

sof log:
[  1250158977.510645] (           0.000000) c0 dma-trace             src/trace/dma-trace.c:335  ERROR FW ABI 0x3012001 DBG ABI 0x5003000 tag v1.8-rc1-62-g8d1a591ec22c src hash 0xbc621119 (ldc hash 0xbc621119)
[     2022570.388380] (     2022570.375000) c1 memory                      src/lib/alloc.c:462  ERROR free_block(): invalid heap = 0x9e084000, cpu = 1
[     2023637.888338] (        1067.500000) c1 memory                      src/lib/alloc.c:462  ERROR free_block(): invalid heap = 0x9e084200, cpu = 1
[     4073385.515222] (     2049747.625000) c1 memory                      src/lib/alloc.c:462  ERROR free_block(): invalid heap = 0x9e084100, cpu = 1
[     4074959.629742] (        1574.114502) c1 memory                      src/lib/alloc.c:462  ERROR free_block(): invalid heap = 0x9e084400, cpu = 1
... ...
... ...
[   141045053.145373] (        1546.510376) c1 memory                      src/lib/alloc.c:462  ERROR free_block(): invalid heap = 0x9e08d800, cpu = 1
[   141072900.123433] (       27846.978516) c1 dai          10.62          src/audio/dai.c:736  ERROR dai_config(): No memory for dai_config.
[   141072918.300516] (          18.177082) c1 ipc                   src/ipc/helper-ipc3.c:487  ERROR ipc_comp_dai_config(): comp_dai_config() failed

**Comment by libinyang** [comment]
After disabling dynamic pipeline, the issue can't be reproduced. @ranj063

**Comment by ranj063** [comment]
@libinyang what kernel, tplg are you using? AFAIK, i have not enabled dynamic pipelines for any ADL topology

**Comment by ranj063** [comment]
can we get the logger output for this? looks like an IPC error during DAI config. also , please include kernel and fw hash when posting issues.

**Comment by libinyang** [comment]
> @libinyang what kernel, tplg are you using? AFAIK, i have not enabled dynamic pipelines for any ADL topology

@ranj063 It's ADL HDA platform. So it's using sof-hda-generic-4ch-kwd.tplg which has enabled dynamic pipelines. Please check CI report 4183 for the test report.

**Comment by ranj063** [comment]
@libinyang I need more info on how to reproduce the issue mentioned here on a non-ADL HDA platform. I tried the hda-generic-4ch-kwd tplg on my up extreme and I cannot reproduce it

**Comment by lgirdwood** [comment]
@libinyang can you try this with main HEAD as @keyonjie has fixed freeing on uncached aliases. 
```
[ 2022570.388380] ( 2022570.375000) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084000, cpu = 1
[ 2023637.888338] ( 1067.500000) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084200, cpu = 1
[ 4073385.515222] ( 2049747.625000) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084100, cpu = 1
[ 4074959.629742] ( 1574.114502) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084400, cpu = 1
```
These are all uncached aliases.

**Comment by keyonjie** [comment]
> @libinyang can you try this with main HEAD as @keyonjie has fixed freeing on uncached aliases.
> 
> ```
> [ 2022570.388380] ( 2022570.375000) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084000, cpu = 1
> [ 2023637.888338] ( 1067.500000) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084200, cpu = 1
> [ 4073385.515222] ( 2049747.625000) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084100, cpu = 1
> [ 4074959.629742] ( 1574.114502) c1 memory src/lib/alloc.c:462 ERROR free_block(): invalid heap = 0x9e084400, cpu = 1
> ```
> 
> These are all uncached aliases.

yes, @libinyang worth to try it with main branch.

**Comment by libinyang** [comment]
This bug can't be reproduced on main branch. @mengdonglin should we close it or put it to P3?

**Comment by keyonjie** [comment]
So this is 1.8 RC2 issue, @libinyang if it is fixed with both latest stable-v1.8 and main branch, we should close it.

**Comment by plbossart** [comment]
@keqiaozhang @libinyang rather than playing with priorities, can we check if the code is both is stable-v1.8 and main branch as asked by @keyonjie

We need to close issues faster, thanks for your help.

**Comment by libinyang** [comment]
Both stable-v1.8 and main branch can't reproduce this bug now.
