### ISSUE TITLE
No exception data in fs after FW exception/panic

### ISSUE THREAD

**Issue by dabekjakub** [thesofproject/linux#296]
After exception is triggered in FW if we try to collect exception info we instead get:

localhost ~ # cat /sys/kernel/debug/sof/exception
cat: /sys/kernel/debug/sof/exception: Permission denied

kernel branch: origin/topic/cros-sof-v4.14-rebase  a38231a7e8dce9af0916022c7994bcf0902219c9
FW - any that can provide exception
if needed use one with debug memory set to 1 
https://github.com/thesofproject/sof/issues/550

Way to reproduce:
Trigger exception in FW
cat or hexdump exception FS

[dmesg.txt](https://github.com/thesofproject/linux/files/2589444/dmesg.txt)

**Comment by dabekjakub** [comment]
@mengdonglin This blocks https://github.com/thesofproject/sof/issues/550 - or at least hinders it greatly.

**Comment by plbossart** [comment]
@ranj063 @dabekjakub isn't the fix already in sof-dev and needs to be applied on the cros branch?

**Comment by lgirdwood** [comment]
@dabekjakub just confirming you are running as root when you attempt to read the file ?

**Comment by ranj063** [comment]
@plbossart I will update the cros branch with the sof-dev updates today.

**Comment by dabekjakub** [comment]
@lgirdwood as Windows based as i am i did it as root ;)

**Comment by keyonjie** [comment]
yes, please wait for Ranjani's back porting.

**Comment by ranj063** [comment]
@dabekjakub is this issue resolved with the updated cros branch?

**Comment by mengdonglin** [comment]
@dabekjakub Closing this issue since the fix is backported to the cros branch. Please reopen if you still see issue.
