### ISSUE TITLE
[APL] Up2 recurring reboots

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2963]
Up2 boards seem to reboot a number of times before final reaching the UI. This was confirmed by @ranj063 and I see this behavior randomly with recent kernels. 

This does not happen with the stock Ubuntu 5.3 kernel.

Using netconsole shows the last trace before rebooting is

````
[   19.972648] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=321 reply_cookie=0 signature=uos error-name=n/a error-message=n/a
````

**Comment by kv2019i** [comment]
FYI to @ujfalusi , are you seeing this?

**Comment by ranj063** [comment]
I have 2 UP2's and I have this problem on both of them.

**Comment by plbossart** [comment]
I moved to Ubuntu 21.04 (was 19.10) and so far I haven't seen an issue with boot loops. I do see the screen tearing quite often but it's a different issue.

**Comment by ranj063** [comment]
also doesnt happen with 19.04 i boot without the HDMI monitor connected

**Comment by plbossart** [comment]
@fredoh9 @aiChaoSONG @keqiaozhang is there a way to connect the up2 devices used for CI to an HDMI monitor?

**Comment by fredoh9** [comment]
For JF labs, we don't have much space for HDMI monitor. When HMDI display is required, I used to bring a cart with Monitor/Keyboard/Mouse, but hard to keep that setup long. It will block the traffic. If we have smaller HDMI monitor, we could keep them in a shelf.

**Comment by fredoh9** [comment]
@marc-hb I know you are using APL UP2 for Zephyr, do you see this problem?

**Comment by fredoh9** [comment]
I thought I don't have this problem with my UP2 with Fedora 34, but 100% reproducible to me also.

**Comment by marc-hb** [comment]
Never had any reboot issue with my UP2 - EDIT: HOWEVER I disabled  graphics with `systemctl`, booting only the console. This makes it much easier to see kernel logs.

**Comment by plbossart** [comment]
To see problems with Up2, you need to

a) keep pulseAudio
b) have a monitor connected

SOF CI does neither....

**Comment by marc-hb** [comment]
We have tests both with and without pulseaudio, they're obviously distinct because Pulseaudio assumes exclusive ownership of the hardware and has been found interfering with the latter.

**Comment by plbossart** [comment]
> We have tests both with and without pulseaudio, they're obviously distinct because Pulseaudio assumes exclusive ownership of the hardware and has been found interfering with the latter.

I don't think that's true, the 'deploy' scripts remove pulseaudio on test devices. @fredoh9 can you confirm?

**Comment by marc-hb** [comment]
The distinct, pulseaudio test suite from @libinyang obviously installs pulseaudio before testing it. Disclaimer: I've never used it myself. EDIT, somewhat related: #2211

**Comment by plbossart** [comment]
I don't know what we are talking about here. 
this is what I see on my test device:

````
root@jf-cml-rvp-sdw-3:~# ls /usr/bin/pulseaudio*
/usr/bin/pulseaudio-bak
````

**Comment by fredoh9** [comment]
@marc-hb @plbossart you are both right.
YES, We are testing with pulseaudio enabled devices also but we have dedicated devices for that.
Yes, deploy script will remove pulseaudio.

**Comment by plbossart** [comment]
@fredoh9 can you clarify which devices use PulseAudio and where the results are posted. So far I only look at the CI results and the Intel daily tests. What am I missing?

**Comment by libinyang** [comment]
@plbossart @ranj063 which UP2 model are you using, HDA, nocodec or PCM512x? I found UP2 HDA are using PCM1, 2, 3 for HDMI audio, which doesn't match the UCM setting.

**Comment by fredoh9** [comment]
@plbossart Libin enabled `user_space_test`. Currently only one platform is being tested weekly, `CML_SKU0955_HDA_USER`. This has a dedicated device for user space test, pulseaudio is enabled. From testplanresult page, Plan Result List->search plans= `user_space_test`.

**Comment by plbossart** [comment]
@fredoh9 is this test in sof-test? 
also why only one platform tested weekly? What prevents us from testing all platforms during a week-end?

**Comment by fredoh9** [comment]
@plbossart Yes, all tests are in sof-test. This is first stage of testing with pulseaudio. To simplify setup issue, dedicated device is being used. If deploy script can handle more for user space related, we could share devices. I believe @libinyang is working on it also.

**Comment by plbossart** [comment]
I am going to close this: updating the platform to Ubuntu 21.04 solves this issue, this is not an SOF problem proper
