### ISSUE TITLE
[BUG]runtime_status remain active after aplaying on 0,0 Jack Out , on TGLU_VOLT_SDW

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#2968]
**Describe the bug**
After aplaying on -Dhw:0,0 Jack Out ,the runtime_status remain 'active'
happenen in internal daily test[id 4370]
**To Reproduce**

```
cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
aplay -D hw:0,0 -r 48000 -c 2 -d5 -f S16_LE /dev/zero -q
cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
```
**Reproduction Rate**
100%

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 3b025d22
SOF Branch: main
SOF Commit: fcaede7a8710
Topology: sof-tgl-sdw-max98373-rt5682.tplg 
 Platform: TGLU_VOLT_SDW

**Screenshots or console output**
```
ubuntu@sh-tglu-volt-sdw-03:~$ cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
suspended
ubuntu@sh-tglu-volt-sdw-03:~$ aplay -D hw:0,0 -r 48000 -c 2 -d5 -f S16_LE /dev/zero -q
ubuntu@sh-tglu-volt-sdw-03:~$ cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
active
ubuntu@sh-tglu-volt-sdw-03:~$ cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
active
```

**Comment by bardliao** [comment]
@XiaoyunWu6666 Could you try https://github.com/thesofproject/linux/pull/2976?

**Comment by XiaoyunWu6666** [comment]
> @XiaoyunWu6666 Could you try #2976?

@bardliao  it can fix the issue
