### ISSUE TITLE
[BUG][SDW]soc_component_read_no_lock error on tglh-0a5e-sdw

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#2983]
**Describe the bug**
in daily test 4434 , verify-kernel-boot-log failed on TGLH-0A5E-SDW.
when creating new PCM HDMI , error occured

**To Reproduce**
 TPLG=sof-tgl-rt711-rt1308-rt715.tplg ~/sof-test/test-case/verify-kernel-boot-log.sh
**Reproduction Rate**
100%

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: d07af131
SOF Branch: main
SOF Commit: d6e29ced2430
 Topology: sof-tgl-rt711-rt1308-rt715.tplg
 Platform:TGLH_0A5E_SDW

**Screenshots or console output**
[dmesg]
```
[    2.976482] kernel: SDW: Invalid device for paging :0
[    2.976505] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976516] kernel: SDW: Invalid device for paging :0
[    2.976517] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976524] kernel: SDW: Invalid device for paging :0
[    2.976525] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976532] kernel: SDW: Invalid device for paging :0
[    2.976533] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976539] kernel: SDW: Invalid device for paging :0
[    2.976541] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976547] kernel: SDW: Invalid device for paging :0
[    2.976548] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976554] kernel: SDW: Invalid device for paging :0
[    2.976556] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.976562] kernel: SDW: Invalid device for paging :0
[    2.976564] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at soc_component_read_no_lock on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.977113] kernel: SDW: Invalid device for paging :0
[    2.977115] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at snd_soc_component_update_bits on sdw:2:025d:1308:00 for register: [0x0000c320] -22
[    2.995566] kernel: SDW: Invalid device for paging :0
[    2.995572] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at snd_soc_component_update_bits on sdw:2:025d:1308:00 for register: [0x0000c070] -22
[    3.960769] kernel: SDW: Invalid device for paging :0
[    3.960772] kernel: rt1308 sdw:2:025d:1308:00: ASoC: error at snd_soc_component_update_bits on sdw:2:025d:1308:00 for register: [0x0000c070] -22
```
full dmesg log :
[dmesg_tglh.txt](https://github.com/thesofproject/sof/files/6613631/dmesg_tglh.txt)

========================================================
Also noted that aplay using -Dhw:0,2 in all  following cases failed. 

**To reproduce**
aplay   -Dhw:0,2 -r 48000 -c 2 -f S16_LE -d 3 /dev/zero -v -q
[console]
```
aplay: set_params:1407: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: (85333 85334)
PERIOD_SIZE: 4096
PERIOD_BYTES: 16384
PERIODS: 4
BUFFER_TIME: (341333 341334)
BUFFER_SIZE: 16384
BUFFER_BYTES: 65536
TICK_TIME: 0

```
[dmesg log]
```
[13762.499582] rt1308 sdw:1:025d:1308:00: rt1308_clock_config complete, clk_freq=4800000
[13762.499635] soundwire_intel soundwire_intel.link.2: Msg ignored for Slave 0
[13762.499637] rt1308 sdw:2:025d:1308:00: DPN_PortCtrl register write failed for port 1
[13762.499640] soundwire sdw-master-2: Program transport params failed: -61
[13762.499642] soundwire sdw-master-2: Program params failed: -61
[13762.499643]  SDW1-Playback: ASoC: error at snd_soc_link_prepare on SDW1-Playback: -61
[13762.499645]  SDW1-Playback: ASoC: soc_pcm_prepare() failed (-61)
[13762.499647]  Speaker: ASoC: dpcm_be_dai_prepare() failed (-61)
[13762.499649]  Speaker: ASoC: dpcm_fe_dai_prepare() failed (-61)
[13762.499825] sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: free stream 2 dir 0
[13762.499827] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[13762.500056] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[13762.500075] sdw_deprepare_stream: subdevice #0-Playback: inconsistent state state 1
[13762.500083] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[13762.500269] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[13762.500277] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[13762.500457] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[13762.500479] sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: close stream 2 dir 0
[13762.843314] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[13762.843365] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[13763.343290] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[13763.343325] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG

```

**Comment by keqiaozhang** [comment]
@plbossart , acpi table looks correct. there're 2 rt1308 codecs. one is one SWD1 and another one is on SWD2:
```
        Device (SWD1)
        {
            Name (_ADR, 0x000120025D130800)  // _ADR: Address
            Name (_DSD, Package (0x04)  // _DSD: Device-Specific Data

```
```
        Device (SWD2)
        {
            Name (_ADR, 0x000220025D130800)  // _ADR: Address
            Name (_DSD, Package (0x04)  // _DSD: Device-Specific Data
```

acpi table：[dsdt-dsl.txt](https://github.com/thesofproject/linux/files/6620732/dsdt-dsl.txt)

**Comment by plbossart** [comment]
@keqiaozhang @XiaoyunWu6666 I fundamentally don't understand what causes such a massive failure. We haven't changed any SoundWire code recently.

Is this a new device that wasn't tested before?
Or is this a regression and if yes what was the last time this device worked?

**Comment by plbossart** [comment]
> @plbossart , acpi table looks correct. there're 2 rt1308 codecs. one is one SWD1 and another one is on SWD2:

Is this from the regular DSDT or does it come from the additional initrd override with acpi scripts?
I've seen conflicts between the two leading to this sort of issues before.

**Comment by plbossart** [comment]
Another hypothesis is a broken device.

I see from the last trace that there's no RT1308 device that reports as 'attached' on the link2.

Could you try to see what happens is the link mask is 0xb (0b1011) to disable the link2.

````
options snd_intel_sdw_acpi sdw_link_mask=0xb
````

**Comment by plbossart** [comment]
@bardliao and @RanderWang can you help here? I don't have this device so can't test locally.

**Comment by plbossart** [comment]
If it's not a hardware issue, here is the information I can find. 

The last test that worked on this device is 4370
Start Time: 2021-06-03 21:21:46 UTC
Kernel Commit: 
3b025d22
 storage: 
3b025d22
SOF Branch: main
SOF Commit: 
fcaede7a8710
 storage: 
fcaede7a8710-1
sh-tglh-0a5e-sdw-01

The first test to fail, after 4 days with "NOT TESTED" is 4434

Start Time: 2021-06-07 21:21:21 UTC
End Time: 2021-06-08 01:54:38 UTC
Kernel Branch: topic/sof-dev
Kernel Commit: 
d07af131
 storage: 
d07af131
SOF Branch: main
SOF Commit: 
d6e29ced2430
 storage: 
d6e29ced2430-3
sh-tglh-0a5e-sdw-01

It's not very useful if NOT TESTED happened 4 days in a row, something's not right with the concept of daily test here.

**Comment by XiaoyunWu6666** [comment]
FYI,  aplay using -Dhw:0,2 in all  following cases failed also. @bardliao @plbossart @RanderWang 
Please check the original description for log details , thanks.

**Comment by XiaoyunWu6666** [comment]
> @keqiaozhang @XiaoyunWu6666 I fundamentally don't understand what causes such a massive failure. We haven't changed any SoundWire code recently.
> 
> Is this a new device that wasn't tested before?
> Or is this a regression and if yes what was the last time this device worked?

This device worked well on June 03 [internal daily 4370 ]
I will use the old recipe to check whether it can work or not

**Comment by XiaoyunWu6666** [comment]
I use the old recipe but the error happens again . Will check with @keqiaozhang  whether it is a hardware issue this afternoon
```
Kernel Commit: 20cf8377
SOF Branch: main
SOF Commit: c979ecbc8dd2
SOF PR: 4253
```

**Comment by bardliao** [comment]
I tested it with below recipe and no issue on my TGLH-0A5E-SDW device
Kernel Branch: topic/sof-dev
Kernel Commit: d07af13
SOF: 20210607 daily
Topology: sof-tgl-rt711-rt1308-rt715.tplg

**Comment by XiaoyunWu6666** [comment]
hi @plbossart , I synced with @keqiaozhang @bardliao  that it was a hardware-related issue.[ Trying the old good recipes did not make the result different.]
Firstly we tried cold reboot , it didn’t work .Then, we tried set default BIOS and it worked well . Will keep tracking sh-tglh-0a5e-sdw-01’s status in following CI daily tests.

**Comment by plbossart** [comment]
no longer an issue with Intel daily test 4532

**Comment by XiaoyunWu6666** [comment]
similar error happened today 
fixed it via the same way  （ Please shutdown the DUT , wait for several mins and reboot it ）
