### ISSUE TITLE
[ADL] display audio is not supported on ADL-P platform since i915 driver is not ready in mainline kernel v5.13-rc

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#2992]
Follow-up to https://github.com/thesofproject/linux/issues/2855

ADL-S is supported in sof-dev, ADL-P not yet.

**Comment by mengdonglin** [comment]
@kv2019i Should we wait for kernel v5.14-rc1?

**Comment by marc-hb** [comment]
Much more details in #3020 duplicate if you are interested: test failures, root cause etc.

**Comment by kv2019i** [comment]
@mengdonglin We now have basic support for ADL-P in sof-dev via 5.14-rc1. I justed tested on a local machine and seems to work ok with latest sof-dev.

@XiaoyunWu6666 Can you confirm the error seen in https://github.com/thesofproject/linux/issues/3020 no longer happens with latest sof-dev? If this is the case, we can close this bug.

**Comment by marc-hb** [comment]
Note `[BUG]ADLP firmware boot delayed by i915 issue (failure in check-sof-logger)` #3042

**Comment by XiaoyunWu6666** [comment]
HDMI1 worked well on ADLP_RVP_SDW (-Dhw:0,5 )and ADLP_RVP_HDA(-Dhw:0,3) with latest sof-dev and /etc/modprobe.d/i915.conf
```
options i915 force_probe=*
```
hi , @kv2019i , shall we close this ? :) thanks

**Comment by keqiaozhang** [comment]
Verified that display audio is supported in latest sof-dev/v5.14-rc3 kernel.  This issue can be closed.
