### ISSUE TITLE
Alsamixer does not show Switch controls

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3015]
With the nocodec topologies, only the volume controls are shows, the switches are not visible.

![playback](https://user-images.githubusercontent.com/1149035/123711385-03e36580-d836-11eb-9d68-283c5be7fc65.png)
![capture](https://user-images.githubusercontent.com/1149035/123711387-047bfc00-d836-11eb-9965-99b3dc49e626.png)

````
root@plb-UP-APL01:~/sof-test# amixer -Dhw:0 controls
numid=11,iface=MIXER,name='Dmic0 Capture Switch'
numid=10,iface=MIXER,name='Dmic0 Capture Volume'
numid=13,iface=MIXER,name='Dmic1 2nd Capture Volume'
numid=12,iface=MIXER,name='EQIIR20.0 eqiir_coef_20'
numid=14,iface=MIXER,name='EQIIR21.0 eqiir_coef_21'
numid=1,iface=MIXER,name='PGA1.0 1 Master Playback Volume'
numid=3,iface=MIXER,name='PGA2.0 2 Master Capture Switch'
numid=2,iface=MIXER,name='PGA2.0 2 Master Capture Volume'
numid=4,iface=MIXER,name='PGA3.0 3 Master Playback Volume'
numid=6,iface=MIXER,name='PGA4.0 4 Master Capture Switch'
numid=5,iface=MIXER,name='PGA4.0 4 Master Capture Volume'
numid=7,iface=MIXER,name='PGA5.0 5 Master Playback Volume'
numid=9,iface=MIXER,name='PGA6.0 6 Master Capture Switch'
numid=8,iface=MIXER,name='PGA6.0 6 Master Capture Volume'
````

This is not quite right, the 'm' shortcut to mute directly is not show or supported.

**Comment by plbossart** [comment]
It's actually the same for SoundWire topologies, the switches implemented on capture are only shown with amixer, not alsamixer, e.g.:

````
numid=50,iface=MIXER,name='PGA2.0 2 Master Capture Switch' << rt711 headset mic path
numid=53,iface=MIXER,name='PGA5.0 5 Master Capture Switch' << rt715 mic path
````
![sof-tgl-rt715-rt711-rt1308-mono](https://user-images.githubusercontent.com/1149035/124165309-3aec8d80-da67-11eb-867f-b2ffb38d9e33.png)

@perexg any idea if we are doing something wrong with those 'Switch' controls defined in the SOF topology?

**Comment by perexg** [comment]
Could you check TLV ? `amixer -c 0 contents`

**Comment by plbossart** [comment]
Here are the values for my SoundWire device @perexg 

[amixer_contents.txt](https://github.com/thesofproject/linux/files/6750307/amixer_contents.txt)

**Comment by perexg** [comment]
It seems that both volume and switch exists for the mentioned controls:

```
numid=50,iface=MIXER,name='PGA2.0 2 Master Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=on,on
numid=49,iface=MIXER,name='PGA2.0 2 Master Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=80,step=0
  : values=80,80
  | dBscale-min=-50.00dB,step=1.00dB,mute=1

numid=53,iface=MIXER,name='PGA5.0 5 Master Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=on,on
numid=52,iface=MIXER,name='PGA5.0 5 Master Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=80,step=0
  : values=80,80
  | dBscale-min=-50.00dB,step=1.00dB,mute=1
```

Could you also provide output from `amixer -c 0 scontents` ?

**Comment by plbossart** [comment]
here you go @perexg: [amixer_scontents.txt](https://github.com/thesofproject/linux/files/6750638/amixer_scontents.txt)

Yes the volume and switch are present but alsamixer doesn't show the mute with the usual "m" or "00" symbols.

**Comment by perexg** [comment]
It's also fine:

```
Simple mixer control 'PGA5.0 5 Master',0
  Capabilities: cvolume cswitch
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 80
  Front Left: Capture 80 [100%] [30.00dB] [on]
  Front Right: Capture 80 [100%] [30.00dB] [on]
```

The capture switches are controlled using *Space* or *;* and *'* keys for single channel. See *F1* help.

**Comment by plbossart** [comment]
Thanks for educating me @perexg, I didn't know Switches were handled differently on playback and capture.
