### ISSUE TITLE
[BUG] X1 Carbon (6th/7th/8th) not registering all microphone inputs (4-channel mic)

### ISSUE THREAD

**Issue by jacksongoode** [thesofproject/linux#3027]
So I've exhausted the resources online but maybe someone knows some more info. This may be an alsa issue but I suspect it could be something happening with sof. 

The microphone array on the X1 Carbon's from the 6th/7th/8th gen on have a 4 channel microphone array at the top. I recently reinstalled 20.04 (with kernel 5.8.0-45) and only the two microphones on the left side are registering. I've had the same issue with 20.10, kernel doesn't seem to matter (5.4, 5.8, or 5.10). What I've noticed, however, is that the live instance of Ubuntu does **not** have this issue and both pairs (left and right) of microphones are registered and pick up sound.

**The issue:** Once everything is updated after installation, the right side mic is disabled - so some update is breaking this - but I'm not sure which. One weird fix is to change the CapturePCM "hw:${CardId},6" to "hw:${CardId},7" in the file /usr/share/alsa/ucm2/sof-hda-dsp/HiFi.conf but this breaks the control on the mic as the mic control will only control the left two mics. However the live-boot instance has this value set at "6" so it shouldn't be the final fix.

(For anyone reading this - if you have a X1 Carbon 6th, 7th, or 8th gen (maybe 9th as well?), check if the microphones at the top right of your display appear to register any input levels in the Sound tab in Settings when rubbing your fingers over them.)

Ubuntu 20.04 - 5.10.0-1034-oem

**Comment by mengdonglin** [comment]
@jacksongoode Can you please share the full dmesg output? So we can know which topology is loaded for SOF.

**Comment by plbossart** [comment]
@jacksongoode this is surprising, we are using the BIOS-provided information to know how many microphone channels are present. This hasn't changed in a long time.

Can you please add this file as /etc/modprobe.d/sof-dyndbg.conf, reboot and attach the dmesg logs. This will show us how many mics are detected and what topology is used. 

[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/6769773/sof-dyndbg.conf.txt)


Thanks!

**Comment by jacksongoode** [comment]
@plbossart @mengdonglin Thanks for your quick responses! Excited to figure this issue out.

Here is the [dmesg log](https://github.com/thesofproject/linux/files/6771379/dmesg.txt). It looks like the mic inputs are being properly detected... Maybe there is something blocking them?

**Comment by plbossart** [comment]
@jacksongoode I see nothing wrong with the kernel:
````
[    3.741512] kernel: sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 4
[    3.863478] kernel: sof-audio-pci 0000:00:1f.3: loading topology:intel/sof-tplg/sof-hda-generic-4ch.tplg
````

I suspect a disconnect between this kernel and alsa-ucm-conf.

Can you attach the results of 'alsa-info' (or a link to the uploaded version on alsa-project)?

Also 'amixer -Dhw:0 info' would be a useful command to run, this is how we provide the information to PulseAudio/UCM (edit: or rather it lists the Components string that UCM uses).

And last if you can identify which version of alsa-ucm-conf you're using, and possibly test with the latest alsa-ucm-conf from https://github.com/alsa-project/alsa-ucm-conf that would help.

**Comment by jacksongoode** [comment]
Here is the [alsa-info log](https://github.com/thesofproject/linux/files/6771457/alsa-info.txt).

From `amixer -Dhw:0 info`:
```
Card hw:0 'sofhdadsp'/'sof-hda-dsp'
  Mixer name	: 'Realtek ALC285'
  Components	: 'HDA:8086280b,80860101,00100000 HDA:10ec0285,17aa22bf,00100002 cfg-dmics:4'
  Controls      : 53
  Simple ctrls  : 23
```

Finally, the version I've been using is 1.2.2-1ubuntu0.8, but I suspect this is not the root of the issue as I tried downgrading to the version used by the live instance of Ubuntu (where both mics **were** working) and there was no change.

**Comment by plbossart** [comment]
thanks @jacksongoode so there are two possibilities

a) somehow PulseAudio/UCM don't get the 'cfg-dmics:4' options. Can you apply this patch to /usr/share/alsa/ucm2/ 
[ucm.diff.txt](https://github.com/thesofproject/linux/files/6771522/ucm.diff.txt) and recheck? This removes a test and hard-codes the 4ch setup

b) somehow the topology doesn't report 4ch, this could be a setup issue. Let's look into this after option a) is checked.

**Comment by plbossart** [comment]
there's also option c), where PulseAudio does a downmix from 4ch to 2ch and somehow uses the wrong downmix matrix. You would be able to see this with 'pulseaudio -vvv' (after disabling the autospawn that makes it hard to test manually).

**Comment by jacksongoode** [comment]
Both right side mics are still undetected after patching the HiFI.conf with the diff file.

**Comment by plbossart** [comment]
@jacksongoode can you clarify what you mean by 'undetected'? The logs above show that we do find the 4 channels, and PulseAudio also uses the 4ch information.

Maybe let's also double-check the hw: level record. Can you record a 20s wave file with:

arecord -Dhw:0,6 -c4 -r48000 -f S32_LE -d 20 test.wav

Try to speak close to each mic while hiding the others and check with audacity that you do have 4 channels. If one of them is completely silent then this points to a mixer value.

**Comment by jacksongoode** [comment]
> @jacksongoode can you clarify what you mean by 'undetected'? The logs above show that we do find the 4 channels, and PulseAudio also uses the 4ch information.
> 
> Maybe let's also double-check the hw: level record. Can you record a 20s wave file with:
> 
> arecord -Dhw:0,6 -c4 -r48000 -f S32_LE -d 20 test.wav
> 
> Try to speak close to each mic while hiding the others and check with audacity that you do have 4 channels. If one of them is completely silent then this points to a mixer value.

Yes, sorry I should clarify that I have been testing the inputs just with the levels detected from the Gnome settings sound panel. Running my finger over all four mics only shows that the left two are detected. Here is the waveform (running my finger over each mic, right to left.

![image](https://user-images.githubusercontent.com/54308792/124644955-b1163900-de47-11eb-97ea-67f928d0aa36.png)

**Comment by plbossart** [comment]
@jacksongoode so if you already see two channels literally muted, it points to an ALSA mixer issue.

if you have a working setup with the live USB, then with a terminal you can try to extract the working configuration

alsactl --file ~/test_asound.state store

save this file and try to use it from the regular setup

alsactl --file ~/test_asound.state restore

You can also try to see if there 's any difference between /etc/asound.state and ~/test_asound.state.

**Comment by jacksongoode** [comment]
@plbossart Just tried the restore, logged out, still the mics are "muted". There is no file /etc/asound.state in my system or in the live boot. Nothing in alsamixer seems to be muted from that end as well.

**Comment by plbossart** [comment]
@jacksongoode there's got to be a difference between live USB and regular setup, no?

from the USB live, try 'alsactl --file ~/test_asound.state_usb.txt store'  and 'alsactl --file ~/test_asound.state_ws.txt store' from your regular boot and attach the two files.

**Comment by jacksongoode** [comment]
[test_asound_current.state.txt](https://github.com/thesofproject/linux/files/6772052/test_asound_current.state.txt)
[test_asound_live.state.txt](https://github.com/thesofproject/linux/files/6772024/test_asound_live.state.txt)

Edit, here is their diff from a reboot:
```
149c149
< 		value 62
---
> 		value 63
157c157
< 			dbvalue.0 -1875
---
> 			dbvalue.0 -1800
```

**Comment by plbossart** [comment]
I am out of options here, nothing that I can think of.

@juimonen do you have any memories of what could cause 2 out of 4 channels to be muted?

**Comment by jacksongoode** [comment]
@plbossart Would you like me to get post the output of `pulseaudio -vvv` - though I'm not sure how to disable autospawn.

**Comment by plbossart** [comment]
if you can't get 4 channels of audio with arecord, then it's not a pulseaudio issue. Something causes those channels to be muted at a low-level. I just don't know what :-(

**Comment by jacksongoode** [comment]
Hmmm, darn. Well I will test out which updates are triggering this and see if I can reproduce it.

**Comment by jacksongoode** [comment]
@plbossart Ok - so I went back to the live 20.04.2 and found that the `alsa-utils` package version `1.2.2-1ubuntu2.1` effectively silences the right side microphones.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  dialog
The following packages will be upgraded:
  alsa-utils
1 upgraded, 0 newly installed, 0 to remove and 326 not upgraded.
Need to get 1,021 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 alsa-utils amd64 1.2.2-1ubuntu2.1 [1,021 kB]
Fetched 1,021 kB in 2s (577 kB/s)     
(Reading database ... 189778 files and directories currently installed.)
Preparing to unpack .../alsa-utils_1.2.2-1ubuntu2.1_amd64.deb ...
Unpacking alsa-utils (1.2.2-1ubuntu2.1) over (1.2.2-1ubuntu2) ...
Setting up alsa-utils (1.2.2-1ubuntu2.1) ...
alsa-state.service is a disabled or a static unit not running, not starting it.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3.4) ...
```

There is no downgrade solution to version `1.2.2-1ubuntu2` but I did find a .deb of the old package and downgrading does not resolve the issue once there is an upgrade.

It should be trivial to track which files were changed to find out what is at the root of this bug.

**Comment by plbossart** [comment]
@jacksongoode I suspect a disconnect between alsa-ucm-conf and alsa-utils, or something that's just too old on Ubuntu 20.04. 

1.2.2 is a release from Feb 19, 2020. In the mean time there was a change to use UCM setups for the base settings and that was part of 1.2.3.

You may want to try the 21.04 live disk and see if this solves anything. It's clearly not an SOF issue proper.

**Comment by jacksongoode** [comment]
Well, I found one very odd solution `sudo apt purge libasound2-data` (I should say that this was after deleting the whole `/etc/share/alsa` directory to find a way to force repopulate the files - this shouldn't be necessary).

I believe the conf files created in this case re-enables something (?) and the right side now works. However, another oddity is that the right side is slightly quieter than the left and there is no way to seemingly control the balance between the two. An issue for another day.

**Comment by plbossart** [comment]
@jacksongoode it's indeed quite hard to wipe configurations clean, that's a recurring issue we all face.

The support for 4channels isn't very good to be honest, because there's missing information from platform firmware on how the microphones should be combined if you record in stereo. we can get geometry information from platform firmware (aka BIOS) in some cases, but that doesn't provide information on mechanical/form factor contributors to actual volume settings.

IIRC when you use PulseAudio to record, there will be a downmix from 4 to 2 channels, but that downmix is just applying the same coefficients. Ideally there should be *something* that tells PulseAudio how to downmix and how to keep the sound 'centered'. I think you can play with the PulseAudio downmix but that would be indeed a completely different story.

If you want to look into this try using pulseaudio -vvv and check the logs, there should be a matrix that tells you what coefficients are used for downmix.

If that's alright with you, I'd like to close this issue since there's really nothing that needs to be fixed in the SOF tree at the moment. Thanks!
