### ISSUE TITLE
[BUG] sof-logger resisted pkill -TERM, using -KILL  on  BYT_MB_NOCODEC

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#3043]
**Describe the bug**
'sudo pkill -TERM sof-logger'   failed  ,  so use 'pkill -KILL'  instead
found in inner daily test 4487 on BYT_MB_NOCODEC check-capture-10sec.

But cannot reproduced manually  , sof-logger can be pkilled normally via manual experiment.

**Log**
[dmesg]
```
2021-06-09 21:31:39 UTC [REMOTE_INFO] pkill -TERM sof-logger
5232 // the result of pgrep sof-logger
2021-06-09 21:31:40 UTC [REMOTE_ERROR] sof-logger resisted pkill -TERM, using -KILL
```

**Comment by keqiaozhang** [comment]
Fixed by thesofproject/sof-test#711.

**Comment by marc-hb** [comment]
Reported in https://github.com/thesofproject/sof/issues/4333#issuecomment-941866672

> happened again in inner daily 7315 on model=BYT_MB_NOCODEC in testcase=check-capture-50rounds.

Also
https://sof-ci.01.org/sofpr/PR4844/build10721/devicetest/?model=BYT_MB_NOCODEC&testcase=check-playback-all-formats

**Comment by marc-hb** [comment]
I only ever saw this on BYT which is now in "maintenance" mode. Closing as wontfix.
