### ISSUE TITLE
[SDW] TGLU_SKU0A3E: DSP boot failure in kmod-load-unload-25 tests

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3045]
Reported by Intel test 5281 on https://github.com/thesofproject/linux/pull/3044

https://sof-ci.sh.intel.com/#/result/planresultdetail/5281?model=TGLU_SKU0A3E_SDW&testcase=check-kmod-load-unload-25

````
[ 6005.333364] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: hda_dsp_core_reset_leave: timeout on HDA_DSP_REG_ADSPCS read
[ 6005.383872] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: hda_dsp_core_reset_leave: timeout on HDA_DSP_REG_ADSPCS read
[ 6005.434353] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: hda_dsp_core_reset_leave: timeout on HDA_DSP_REG_ADSPCS read
[ 6005.434356] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: dsp core 0/1 power up failed
[ 6005.434357] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 6005.434395] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: extended rom status:  0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff
[ 6005.434413] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 6005.434414] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: dsp init failed after 3 attempts with err: -110
[ 6005.434440] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to start DSP
[ 6005.434442] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to boot DSP firmware -110
[ 6005.437983] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -110
````

[dmesg.txt](https://github.com/thesofproject/linux/files/6818900/dmesg.txt)

@bardliao @RanderWang @ranj063 have you seen this before?

**Comment by ranj063** [comment]
This is not good. I thought we fixed the dump to not print after powering off but looks like we've missed something. @ujfalusi FYI

**Comment by ranj063** [comment]
And this isnt related to CSE right? Its even before we copy the firmware when we try to power up the cores.

**Comment by bardliao** [comment]
I can't reproduce the issue even on the same device and same recipe.

**Comment by plbossart** [comment]
re-started the same test with 5299 to see if this was an isolated incident or platform issue.

**Comment by plbossart** [comment]
Retried locally on my device, no issue. Intel test 5299 passes as well, so it's a random boot failure that we want to track but that's unrelated to PR #3044

**Comment by ujfalusi** [comment]
> This is not good. I thought we fixed the dump to not print after powering off but looks like we've missed something. @ujfalusi FYI

@ranj063, we print on power up and if there were dumps prior a power off then we re-enable the dumps.
This is failure via `snd_sof_run_firmware()` in that path we force re-enable the dumps.

**Comment by plbossart** [comment]
this sighting was not reproduced since mid July, almost 4 months. closing
