### ISSUE TITLE
SOF DMA Trace: avoid logs clearance at runtime suspend/resume

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#306]
We have enabled SOF Runtime Power Management on SKL+ platforms, where we will actually power off/on Audio DSP at suspend/resume, there, DMA trace will be re-initialized, those logs happened before last suspend will be overwritten from offset 0 at once after ADSP is resumed.

To fix this, we can do some extension to BDL setup function, e.g. add a member host_init_offset to store the last trace offset, and copying new generated trace logs to buffers(BDL entries) from this offset, with this implemented, FW won't overwrite the existed logs happened before suspend.

It is somehow different for SKL- platforms where we use GPDMA for DMA trace, we need to implement non-0 offset support to implement the similar feature, please refer to this:
thesofproject/sof#544

**Comment by ranj063** [comment]
@keyonjie we dont have suspend/resume on SKL- platforms yet

**Comment by keyonjie** [comment]
> @keyonjie we dont have suspend/resume on SKL- platforms yet

thanks for clarification, then we can focus on skl+ implementation ATM.

**Comment by plbossart** [comment]
well we don't even have SKL- support since the code doesn't even boot properly with the trace issues, so suspend-resume is not even a problem at this point. Gah.

**Comment by lgirdwood** [comment]
@keyonjie will this be a driver only fix, or does it need FW change too ?

**Comment by keyonjie** [comment]
@lgirdwood this will be driver only fix for SKL+ platforms.

**Comment by xiulipan** [comment]
@keyonjie 
So this is for DMA trace only. I think for error trace we need some FW change too.

**Comment by keyonjie** [comment]
@xiulipan right, it's for DMA trace only. for etrace, we need think about new solution to avoid clearance.

**Comment by plbossart** [comment]
@keyonjie Rather than muck with DMA/BDL programming, I thought the recommendation was to save all traces in host memory before suspend?

**Comment by keyonjie** [comment]
@plbossart that's another thought, but I believe that's belong to user space(e.g. running tools such as sof-logger all the time and saving output to an log file, similar to kern.log or syslog?)

**Comment by keyonjie** [comment]
anyway, porting our DMA trace log to standard system trace is good idea.

**Comment by plbossart** [comment]
@ranj063 @keyonjie is this trace support across suspend-resume a planned activity or is this dropped? There's been no update since November 26.

**Comment by ranj063** [comment]
@plbossart I think this issue has been tabled for far too long. Let me check with @keyonjie this week and maybe see if @mengdonglin can assign someone else if Keyon is busy with WoV.

**Comment by kv2019i** [comment]
Hey folks (especially @ranj063 and @keyonjie), I now made a pair of patches that makes "sof-logger -t" work more consistantly over suspends (both runtime and S3) -> PR781 linked above

This basicly allows to get the traces if you have sof-logger running. If sof-logger is not running and you start it later, you'll get traces since last resume (but not before). The patched sof-logger works also with S3/D3 suspends (so not just with runtime pm).

This is not necessarily a full replacement for Keyon's patchset, but it does improve trace consistency quite a bit already.

**Comment by ranj063** [comment]
> This basicly allows to get the traces if you have sof-logger running. If sof-logger is not running and you start it later, you'll get traces since last resume (but not before).
Thanks @kv2019i why is this the case? is it because you reset the host_offset to 0 in your open? wondering is that is required.

**Comment by plbossart** [comment]
@keyonjie @kv2019i is this still relevant?

**Comment by plbossart** [comment]
@keyonjie @kv2019i no answer -> closing
