### ISSUE TITLE
No audio/mic from internal speakers/build in microphone running Ubuntu 20.04, 20.10 or 21.04 .

### ISSUE THREAD

**Issue by mohitt** [thesofproject/linux#3060]
Hi, 

Please have a look at https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1935850?comments=all

As per this https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1935850/comments/16 . Topology file not suitable for the machine

**Comment by mohitt** [comment]
Issue exists

**Comment by plbossart** [comment]
duplicate of issue #3057
