### ISSUE TITLE
[APL][SSP] UP2 with PCM512x: kernel errors

### ISSUE THREAD

**Issue by lyakh** [thesofproject/linux#3061]
I'm routinely getting the following kernel errors on my UP2 with PCM512x:
```
SSP5-Codec: ASoC: no backend capture stream
```
and
```
SSP5-Codec: ASoC: no users capture at close - state 0
```
Sometimes I'm also getting firmware boot failures:
```
[ 2222.114879] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4c]=0x40000000 successful
[ 2222.114890] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x3030202 successful
[ 2222.115157] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x4]=0x1010202 successful
[ 2222.115163] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 2
[ 2222.131106] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80000]=0x5000001 successful
[ 2223.798272] [1910]  SSP5-Codec: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 2223.798342] [1910]  Media Playback 4: ASoC: pop wq checking: Playback status: inactive waiting: yes
[ 2225.131747] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80000]=0x81000012 timedout
[ 2225.131764] sof-audio-pci-intel-apl 0000:00:0e.0: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[ 2225.131780] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x160]=0x140000 successful
[ 2225.131789] sof-audio-pci-intel-apl 0000:00:0e.0: ------------[ DSP dump start ]------------
[ 2225.131798] [4823] sof-audio-pci-intel-apl 0000:00:0e.0: unknown ROM status value 81000012
[ 2225.131815] sof-audio-pci-intel-apl 0000:00:0e.0: error: extended rom status:  0x81000012 0xecc00302 0x0 0x0 0x0 0x0 0x1522101 0x0
[ 2225.131822] sof-audio-pci-intel-apl 0000:00:0e.0: ------------[ DSP dump end ]------------
[ 2225.131827] sof-audio-pci-intel-apl 0000:00:0e.0: error: load fw failed ret: -110
[ 2225.131873] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to start DSP
[ 2225.131879] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to boot DSP firmware after resume -110
[ 2225.131891] sof-audio-pci-intel-apl 0000:00:0e.0: ASoC: error at snd_soc_pcm_component_pm_runtime_get on 0000:00:0e.0: -110
```
which made me wonder whether that boot failure is related to the pop work? IIUC @lgirdwood suggested that the SSP5 errors are caused by errors in topology, and that the boot failure is probably unrelated to that.

**Comment by plbossart** [comment]
@lyakh I can reproduce the 'ASoC' errors, sof-test flags an error on every capture.

So far no boot issues though. Can you confirm this happens with a bog-standard SOF configuration?

**Comment by plbossart** [comment]
the DAPM map is all over the place. 
![widgets](https://user-images.githubusercontent.com/1149035/126792665-afbeb252-b6da-4d85-89c9-38e1b1087a5d.png)

We should use simpler topologies...

**Comment by lyakh** [comment]
@plbossart no, sorry for not mentioning, the boot error I've only seen with Zephyr so far. But since it's sporadic, and happens before the firmware is actually executed, IIUC, and I always reboot to reload firmware, it seems to me, that it shouldn't be Zephyr-related.

**Comment by plbossart** [comment]
@lyakh could still be due to power-down differences between xtos and Zephyr, no?

**Comment by lyakh** [comment]
@plbossart sorry, indeed, you're right. I thought I had cases where it failed the first firmware run, but I just double-checked, and yes, it's always one of follow-up boots after a D3. So, yes, it's possible.

**Comment by plbossart** [comment]
@lyakh it's a disconnect between topology and machine driver.

The topology exposes a capture path on PCM5.

The machine driver does not set dpcm_capture=1 for the dailink. it's explicited commented out. We haven't changed the code since 2020.

Ironically this points to an SOF commit

ea8055de1 topology: APL: add an SSP5 capture pipeline

This never worked...

**Comment by plbossart** [comment]
@lyakh PR #3092 fixes the ASoC issues. You should file the boot issues in a separate entry, this has nothing to do with topology, agree with @lgirdwood

**Comment by lyakh** [comment]
> @lyakh it's a disconnect between topology and machine driver.
> 
> The topology exposes a capture path on PCM5.
> 
> The machine driver does not set dpcm_capture=1 for the dailink. it's explicited commented out. We haven't changed the code since 2020.
> 
> Ironically this points to an SOF commit
> 
> [ea8055d](https://github.com/thesofproject/linux/commit/ea8055de143a944305c71f48786e853356d445f0) topology: APL: add an SSP5 capture pipeline
> 
> This never worked...

@plbossart Thanks for the investigation and a fix! Although I must disagree - I'm pretty sure it did work. I'm testing DMICs regularly enough on the hardware, and I'm sure I connected my phone headphone output to HiFiBerry input and captured audio multiple times too. This latter test I haven't done in a while, but I still have a cable plugged in into the 3.5mm line-in port of that card. Or have I misunderstood your "never worked" phrase?

**Comment by plbossart** [comment]
I stand by my comment @lyakh: the machine driver never had capture support but the topology did. It must have worked with the machine driver explicitly enabling the capture in your local setup, but not with a clean git reset --hard; git pull

**Comment by lyakh** [comment]
> I stand by my comment @lyakh: the machine driver never had capture support but the topology did. It must have worked with the machine driver explicitly enabling the capture in your local setup, but not with a clean git reset --hard; git pull

@plbossart I don't know what miracle is driving this, but I've just re-tested my UP2 with a DMIC attachment board and with no kernel modifications and I was able to record audio (and to play it back). EDIT: line-in on the HiFiBerry worked too.

**Comment by lyakh** [comment]
@plbossart can this be closed now?
