### ISSUE TITLE
[Yorp] Stream error 107 when playing HDMI after short break.

### ISSUE THREAD

**Issue by dabekjakub** [thesofproject/linux#308]
Way to reproduce :
play with aplay and after about 40 seconds play again 

aplay  test.wav

wait 40 seconds

aplay  test.wav
Playing WAVE 'test.wav' : Signed 32 bit Little Endian, Rate 48000 Hz, Stereo
Stream error -107

Kernel: /topic/cros-sof-v4.14-rebase/  bf94547
FW: /glk-004-drop-stable/  1f79920
SW: /master/  a01fd66 

[log_trace_dmsg.txt](https://github.com/thesofproject/linux/files/2603354/log_trace_dmsg.txt)
[log_trace_fw.txt](https://github.com/thesofproject/linux/files/2603355/log_trace_fw.txt)

**Comment by keyonjie** [comment]
are you running this on GLK with HDMI PCM?

**Comment by dabekjakub** [comment]
Yes , my default is HDMI - sorry for not writing that sooner

**Comment by keyonjie** [comment]
good, I can imagine how this happen, it's a driver issue, thanks for reporting.

**Comment by keyonjie** [comment]
I can write a quick fix to it, @dabekjakub can you help try if it fix your issue?

**Comment by dabekjakub** [comment]
Just point me to a kernel branch with your fix and i will check it :)

**Comment by keyonjie** [comment]
@dabekjakub 
https://github.com/thesofproject/linux/pull/309

**Comment by dabekjakub** [comment]
Looks good , couldn't reproduce it with Your changes. @keyonjie
