### ISSUE TITLE
[BUG]ADLS_RVP_HDA TIMEOUT when check-kmod-load-reload 

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#3086]
**Describe the bug**
This happened after ADL DUTs added back to inner daily tests , and check-kmod-load-reload-25 tested on ADLS_RVP_HDA.

TIMEOUT happened :
- before dsp suspended (inner daily 5657)
- OR  when check firmware load information after kmod load (inner daily 5685)
- OR  when waiting dsp to become suspended(inner daily 5595)

**To Reproduce**
TPLG=/lib/firmware/intel/sof-tplg/sof-hda-generic-2ch.tplg ~/sof-test/test-case/check-kmod-load-unload.sh -l 25
**Reproduction Rate**
100% almost

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 9474f300
SOF Branch: main
SOF Commit: 53718867df85
Topology: /lib/firmware/intel/sof-tplg/sof-hda-generic-2ch.tplg
 Platform: ADLS_RVP_HDA

**Screenshots or console output**
[console]
TIMEOUT happened :
- before dsp suspended (inner daily 5657)
```
2021-08-02 22:19:14 UTC [REMOTE_INFO] ==== firmware boot complete: 7 of 25 ====
(and then TIMEOUT , no console logs )
```
- OR  when check firmware load information after kmod load (inner daily 5685)

```
……(above is los of sof_remove and sof_insert)
MODPROBE	snd_sof_pci_intel_apl		 
MODPROBE	snd_sof_pci_intel_cnl		 
MODPROBE	snd_sof_pci_intel_icl		 
MODPROBE	snd_sof_pci_intel_tgl		 
MODPROBE	snd_sof_acpi		 
MODPROBE	snd_sof_pci		 
MODPROBE	snd_usb_audio		 
2021-08-03 23:12:03 UTC [REMOTE_INFO] checking for general errors after kmod insert with sof-kernel-log-check tool
declare -- cmd="journalctl_cmd --since=@1628032317"
2021-08-03 23:12:04 UTC [REMOTE_INFO] checking if firmware is loaded successfully
2021-08-03 23:12:04 UTC Sub-Test: [REMOTE_INFO] Checking SOF Firmware load info in kernel log
(and then TIMEOUT , no console logs )
```

- OR  when waiting dsp to become suspended(inner daily 5595)
```
2021-07-29 22:19:39 UTC [REMOTE_INFO] ===== Starting iteration 13 of 25 =====
2021-07-29 22:19:39 UTC [REMOTE_INFO] wait dsp power status to become suspended
(and then TIMEOUT , no console logs )
```

**Comment by lgirdwood** [comment]
@XiaoyunWu6666 are you saying the kernel freezes after the issue ?
@plbossart this could be kernel or FW issue, not sure yet.

**Comment by plbossart** [comment]
@XiaoyunWu6666 The problem with TIMEOUT results is that we don't know if it's a kernel/firmware issue or a CI/network infrastructure issue. We've had timeouts on ADPS for multiple weeks now.

Unless there's a manual reproduction it's hard to make progress.

**Comment by keqiaozhang** [comment]
This issue cannot be reproduced with QS Silicon and new BIOS.
