### ISSUE TITLE
Speakers not working on Thinkpad x12 detachable 

### ISSUE THREAD

**Issue by johnledezma34** [thesofproject/linux#3090]
Speakers fail to work. Only Bluetooth audio - works. Any help appreciated

**Comment by plbossart** [comment]
https://thesofproject.github.io/latest/getting_started/index.html#debug-audio-issues-on-intel-platforms

**Comment by johnledezma34** [comment]
> https://thesofproject.github.io/latest/getting_started/index.html#debug-audio-issues-on-intel-platforms

I appear to have the same issue as issue  #2748. I applied https://pastebin.com/60eUvKSM gotten from a kind redditor who sniffed his windows computer and used the applyverbs.py command to use it. As of now I need to apply the command while pavucontrol or another music thing is active to keep audio visible. I understand that this isn't your software's problem so I'll be frank. 

Do you think that this will this ever be fixed in the kernel or will I have to keep on doing this? 

Also, do I close this issue?

thanks.

**Comment by plbossart** [comment]
@johnledezma34 did you end-up with the *same* list of verbs as what was referenced in issue #2748 and integrated in the kernel with commit 26928ca1f06aab4361eb5adbe7ef3b5c82f13cf2

If yes the issue will be fixed when that commit lands in your distro kernel.
If no well then you'll have to carry these manual commands or submit a quirk to solve this for good.

**Comment by johnledezma34** [comment]
How do I submit a quirk Sir?

**Comment by plbossart** [comment]
@johnledezma34 do you have a quirk already, similar to what was implemented in https://github.com/thesofproject/linux/commit/26928ca1f06aab4361eb5adbe7ef3b5c82f13cf2?

If yes, then you can generate a patch and submit it directly to the alsa-devel mailing list. if you have no experience in submitting kernel patches, we're happy to help review your code and upstream it.

If no, then that's the first order of business :-)

**Comment by johnledezma34** [comment]
I'm closing this issue. I moved back to windows. Sound is essential and I don't really know how to create the audio hashes.
