### ISSUE TITLE
[BUG]ipc error then kernel oops when runtime resume on TGLU_RVP_NOCODEC_CI

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#3100]
**Describe the bug**
when kmod unload load for multiple rounds on TGLU_RVP_NOCODEC_CI , ipc timed out when CORE_ENABLE

**To Reproduce**
 TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-nocodec-ci.tplg ~/sof-test/test-case/check-kmod-load-unload.sh -l 25

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 32657609
SOF Branch: main
SOF Commit: e2fc7082e1be
 Topology: /lib/firmware/intel/sof-tplg/sof-tgl-nocodec-ci.tpl
 Platform: TGLU_RVP_NOCODEC_CI

**Screenshots or console output**

[dmesg]
[dmesg_CI.txt](https://github.com/thesofproject/sof/files/6929351/dmesg_CI.txt)

**Comment by keyonjie** [comment]
suppose this should already be fixed with the latest main or stable-v2.0 branch?

**Comment by keqiaozhang** [comment]
confirmed that this issue is fixed on latest main and stable-v2.0 branch.
