### ISSUE TITLE
Comet Lake can't load/init firmware

### ISSUE THREAD

**Issue by tkopecek** [thesofproject/linux#3114]
Fedora 34, kernel-5.13.12, sof 1.8, Comet Lake PCH-LP cAVS (t14s)

On boot dmesg will contain following and no sound device is created:
```
[   19.239568] snd_soc_skl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   19.239647] snd_soc_skl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   19.287391] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   19.288003] sof-audio-pci-intel-cnl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   19.288032] sof-audio-pci-intel-cnl 0000:00:1f.3: enabling device (0004 -> 0006)
[   19.288125] sof-audio-pci-intel-cnl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   19.288196] sof-audio-pci-intel-cnl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   19.297696] sof-audio-pci-intel-cnl 0000:00:1f.3: use msi interrupt mode
[   19.341758] sof-audio-pci-intel-cnl 0000:00:1f.3: hda codecs found, mask 5
[   19.341762] sof-audio-pci-intel-cnl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   19.341765] sof-audio-pci-intel-cnl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[   19.344592] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware info: version 1:8:0-9e7a8
[   19.344594] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[   19.344599] sof-audio-pci-intel-cnl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
(redacted unrelated lines)
[   20.209501] Lockdown: Xorg: raw io port access is restricted; see man kernel_lockdown.7
[   20.250500] sof-audio-pci-intel-cnl 0000:00:1f.3: error: cl_dsp_init: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   20.250506] sof-audio-pci-intel-cnl 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
[   20.250517] sof-audio-pci-intel-cnl 0000:00:1f.3: error: extended rom status:  0x6000021 0x0 0x0 0x0 0x0 0x0 0x1811102 0x0
[   20.250996] sof-audio-pci-intel-cnl 0000:00:1f.3: error: dsp init failed after 3 attempts with err: -110
[   20.251001] sof-audio-pci-intel-cnl 0000:00:1f.3: ROM error=0xffffffff: FW status=0xffffffff
[   20.251018] sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to reset DSP
[   20.251019] sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to boot DSP firmware -110
[   20.251610] sof-audio-pci-intel-cnl 0000:00:1f.3: error: sof_probe_work failed err: -110

# lspci -v
00:1f.3 Audio device: Intel Corporation Comet Lake PCH-LP cAVS (prog-if 80)
        Subsystem: Lenovo Device 22af
        Flags: bus master, fast devsel, latency 64, IRQ 16, IOMMU group 12
        Memory at ef73c000 (64-bit, non-prefetchable) [size=16K]
        Memory at eea00000 (64-bit, non-prefetchable) [size=1M]
        Capabilities: [50] Power Management version 3
        Capabilities: [80] Vendor Specific Information: Len=14 <?>
        Capabilities: [60] MSI: Enable- Count=1/1 Maskable- 64bit+
        Kernel driver in use: sof-audio-pci-intel-cnl
        Kernel modules: snd_hda_intel, snd_soc_skl, snd_sof_pci_intel_cnl
```

I've tried:
1) disable/enable ME (as it looks similar to #2478) - no change
2) use snd_hda_intel.dmic_detect=0 - enabled sound output, but no microphone
3) some older kernels/distros live images (Ubuntu 20.04, Fedora 33) - they don't detect it in the same way

**Comment by plbossart** [comment]
@tkopecek can you upload the results of 'alsa-info' please, just to verify the PCI ID.

Also if you can try to use 'dnf downgrade' to go back to the SOF firmware 1.7 or 1.6 it would help us identify if this is a firmware signature issue or if none of the releases work on your device.

Thanks!

**Comment by tkopecek** [comment]
[alsa-info.sof-1.6.txt](https://github.com/thesofproject/linux/files/7041659/alsa-info.sof-1.6.txt)
[alsa-info.sof-1.8.txt](https://github.com/thesofproject/linux/files/7041660/alsa-info.sof-1.8.txt)

**Comment by tkopecek** [comment]
Uploaded logs for both variants sof -1.6/1.8 it looks to be pretty same.

**Comment by plbossart** [comment]
I don't have any suggestions @tkopecek this looks like a nasty firmware signature issue, or there's something in the BIOS configuration that we don't handle well somehow.

@lgirdwood @mrhpearson FYI.

**Comment by lgirdwood** [comment]
@plbossart it looks like the FW has either not been copied by DMA or not booting once copied. @abonislawski @mwasko any idea on the ROM codes ?

**Comment by mrhpearson** [comment]
> @lgirdwood @mrhpearson FYI.

Thx - I don't have a T14s myself but I'm looking in our team to see who can help support with any debug. This platform was linux certified so it should work well and I've not heard/seen this issue before (which I'd expect if the issue is seen with older versions of SOF firmware). Any potential this could be triggered by bad HW?

@tkopecek - can you confirm which BIOS and EC version you are running please?

**Comment by tkopecek** [comment]
Sorry for the noise - I've found that EC was corrupted (during one of the boots seen very quick flash after POST with FW fail message). After reflashing it works as expected.

**Comment by dober60** [comment]
I tested this on my system and I find that all is fine until you update alsa-ucm package from the 1.2.4-5 to 1.2.5.1-1.  I do not get the errors in dmesg but sound no longer finctions. Kernel is the same as the users and firmware is 1.8-1

**Comment by plbossart** [comment]
> I tested this on my system and I find that all is fine until you update alsa-ucm package from the 1.2.4-5 to 1.2.5.1-1. I do not get the errors in dmesg but sound no longer finctions. Kernel is the same as the users and firmware is 1.8-1

@dober60 do you mind opening a separate issue?

**Comment by plbossart** [comment]
> Sorry for the noise - I've found that EC was corrupted (during one of the boots seen very quick flash after POST with FW fail message). After reflashing it works as expected.

Good to know, thanks for confirming!

**Comment by zippy2** [comment]
For anybody else, who runs into the same issue. I've too ran into the very same problem as described here. I've upgraded both system firmware and EC firmware but without any luck. I had to re-flash Intel's Management Engine (version 225.53.1649) and all of a sudden my sound card is back.
