### ISSUE TITLE
[IPC] No audio on fresh flashed device

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#3132]
We applied this [patch](https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3093619) per recommendation of our "find missing" robot which hunts down upstream patches to apply to our kernel based on the "Fixes" tags. This (innocent in appearance) commit caused a bug where no audio was presented after a device was flashed (with --clobber-stateful), rebooting restored audio. 

Stateful should not affect the audio subsystem so I am wondering if there is a synchronization bug on first boot when the stateful FS is being initialized.

**Comment by plbossart** [comment]
@cujomalainey how do you know it's precisely that patch 973b393fdf073a4ebd8d82ef6edea99fedc74af9 that causes issues?

@lyakh FYI

**Comment by cujomalainey** [comment]
@plbossart we reverted, rebuilt the image and cannot reproduce the bug anymore

**Comment by cujomalainey** [comment]
Also our testers bisected the failure down to the image that patch was introduced in

**Comment by plbossart** [comment]
Could it be that somehow your firmware sends a weird IPC message that's now detected as an error? In that case you would see an error in the kernel dmesg log, no?

**Comment by cujomalainey** [comment]
I did check that but didn't see anything in the tester logs, I will keep testing locally

**Comment by ranj063** [comment]
@cujomalainey could you please check if you have this patch in your kernel?


Author: Keyon Jie <yang.jie@linux.intel.com>
Date:   Sat Nov 9 05:21:00 2019 +0800

    ASoC: SOF: Intel: hda-loader: clear the IPC ack bit after FW_PURGE done

**Comment by cujomalainey** [comment]
@ranj063 yes, that appears to have been pulled in back in April

**Comment by cujomalainey** [comment]
our initial analysis appears to be in error. This CL just happens to be merged on an image that hits a race condition that wedges CRAS and SOF without error. I have only seen it once before and it was not fixed evidently. This time I figured out a way to unlock the filesystem without losing the bug. I will get an SOF trace and see if there is an error.

**Comment by cujomalainey** [comment]
Aha! I have clue about what is happening. Somehow one of the tasks for the speaker-path (this is a DSM device, so echo ref included in this situation) is never getting it's task created and just fails silently. Here is a [log](https://github.com/thesofproject/linux/files/7101941/log.txt), the bad case is `[     3277262.630190]` to  `[     3285308.254870]` I restart CRAS  at `[   730093261.978284]` and playback magically works.

It looks like it is the playback path that just never does anything after the prepare step.

**Comment by cujomalainey** [comment]
I am not entirely convinced yet that this actually is an SOF bug, it very well could be a CRAS bug where its not making all the proper ALSA calls which would explain why this is a silent failure in terms of logs.

**Comment by cujomalainey** [comment]
Issue traced up to ASoC. I only see trigger call come through once twice in bad case vs four times in good case. Blaming CRAS. Sorry for the noise.
