### ISSUE TITLE
No sound on HP x360 14-ea000t (tiger lake)

### ISSUE THREAD

**Issue by JonAnCla** [thesofproject/linux#3144]
I'm unable to get sound on my HP x360 tiger lake when I cold boot into linux. (booting via windows first and then doing a soft restart to linux works)

I have followed descriptions in various other places (particularly #2700) and arrived at the following setup:
- linux mint 20 (ubuntu 20.04 derivative)
- alsa-lib 1.2.5.1 & related alsa packages 
- 5.13 kernel
- firmware-sof 1.7

Even with that configuration, neither speaker-test or aplay work

Am I missing something?

Output of `sudo dmesg | grep 'audio\|sound'` below - is the line "unknown sof_ext_man header type 3" significant?  

```
[    4.662038] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    4.662062] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    4.662073] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
[    4.663254] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.663337] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    4.670119] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[    4.709011] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
[    4.709013] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    4.709016] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[    4.709967] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:7:0-47d07
[    4.709969] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[    4.709972] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[    4.798276] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:7:0-47d07
[    4.798280] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[    4.802109] sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:18:1 Kernel ABI 3:18:0
[    4.820475] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[    4.843404] snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC245: line_outs=1 (0x17/0x0/0x0/0x0/0x0) type:speaker
[    4.843408] snd_hda_codec_realtek ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    4.843409] snd_hda_codec_realtek ehdaudio0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[    4.843410] snd_hda_codec_realtek ehdaudio0D0:    mono: mono_out=0x0
[    4.843410] snd_hda_codec_realtek ehdaudio0D0:    inputs:
[    4.843411] snd_hda_codec_realtek ehdaudio0D0:      Mic=0x19
[    4.890049] snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[    4.890057] snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
[    4.907559] input: sof-hda-dsp Mic as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input30
[    4.907624] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input31
[    4.907695] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input32
[    4.907739] input: sof-hda-dsp HDMI/DP,pcm=4 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input33
[    4.907796] input: sof-hda-dsp HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input34
```

Output of alsa-info: https://pastebin.pl/view/a0e0536e

Beyond installing the packages listed above, I am not sure what to look out for in terms of errors or how to test things. 
 
Any help/tips appreciated.  Thanks!

**Comment by plbossart** [comment]
@hottwaj your pastebin.pl link is filtered with "NET::ERR_CERT_AUTHORITY_INVALID" errors. please use a different tool

Please clarify if you get audible sound on the headphone output, and if you get no sound on speakers only.

please see the suggestions at https://thesofproject.github.io/latest/getting_started/intel_debug/introduction.html
specifically try to use "options snd-intel-dspcfg dsp_driver=1" to force the use of the HDaudio legacy driver.

From your description, I suspect the amplifiers are not initialized, and you'll likely need the trickery described in https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver to get the right parameters.

**Comment by JonAnCla** [comment]
Thanks @plbossart, try this link for the alsa-info output instead:
https://drive.google.com/file/d/1wstEpK_loYdIfTNP8yyWNOsJlhs4LICx/view?usp=sharing

I do get headphone output.  It is only the onboard speakers of the laptop that are a problem (and only on a cold boot)

I understand that this model of HP laptop has already had quite a bit of attention e.g. see following link. 
 Some verb trickery is already mentioned there  https://bugzilla.kernel.org/show_bug.cgi?id=210633#c13

I have tried using the verb commands listed in that bug report and they do not seem to work despite use of the libraries/kernel listed in my initial post above

How can I check whether verbs for this laptop have already been included in firmware-sof?  (do I need to check for something that mentions the "Realtek ALC245" chip?)

i.e. at the moment I cannot tell whether the problem is due to either i) libraries/kernel that I have setup incorrectly or ii) libraries/kernel that cannot yet cope with this laptop/sound system.

Thanks for the suggestion to try "options snd-intel-dspcfg dsp_driver=1" - I will try that.  And if all else fails I will look into realtek-verb-tools when time allows :)

Thanks!

**Comment by plbossart** [comment]
@hottwaj this is really not something related to the SOF driver proper, in this case we reuse the HDaudio configurations from sound/pci/hda/, so if this model is not well handled and needs quirks, it has to be fixed in that driver. I think you should continue with the bugzilla link and report your findings there. This GitHub issue isn't going to be very helpful I am afraid.

**Comment by JonAnCla** [comment]
OK thanks @plbossart I will go back there, thanks for your help.

Closing assuming this needs to be fixed elsewhere
