### ISSUE TITLE
[BUG] [ADL-M RVP]: Failed to load DSP topology during Cold/warm boot tests with RT711 on board Soundwire codec

### ISSUE THREAD

**Issue by jairaj-arava** [thesofproject/linux#3154]
**Describe the bug**
During warm boot tests, we see DSP topology load failure randomly.

**To Reproduce**
1.Boot the Chromebook.
2. Copy the folder warm_cold_boot_device_check  script to the device.
3. Initiate test with command: ./start_test.sh 5 20 -> warm boot

**Reproduction Rate**
The issue happens randomly once or thrice so far in 1000 cycles.

**Expected behavior**
Sound card should be loaded in all warm boot cycles without any failure.

**Impact**
User may experience audio not working at any time due to random failure.

dmesg error logs:
	Line 2177: 2021-09-10T04:20:22,186809-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
	Line 2206: 2021-09-10T04:20:22,425045-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:18:1 Kernel ABI 3:18:0
	Line 2216: 2021-09-10T04:20:22,440359-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: invalid widget size
	Line 2218: 2021-09-10T04:20:22,455418-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: topology: could not load header: -22
	Line 2219: 2021-09-10T04:20:22,455428-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
	Line 2221: 2021-09-10T04:20:22,466202-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
	Line 2223: 2021-09-10T04:20:22,476542-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
	Line 2224: 2021-09-10T04:20:22,476586-07:00 sof_sdw sof_sdw: ASoC: failed to instantiate card -22
	Line 2224: 2021-09-10T04:20:22,476586-07:00 sof_sdw sof_sdw: ASoC: failed to instantiate card -22
	Line 2228: 2021-09-10T04:20:22,505175-07:00 sof_sdw sof_sdw: snd_soc_register_card failed -22
	Line 2228: 2021-09-10T04:20:22,505175-07:00 sof_sdw sof_sdw: snd_soc_register_card failed -22
	Line 2230: 2021-09-10T04:20:22,522316-07:00 sof_sdw: probe of sof_sdw failed with error -22
	Line 2230: 2021-09-10T04:20:22,522316-07:00 sof_sdw: probe of sof_sdw failed with error -22

Attached the dmesg log: 
[dmesg.txt](https://github.com/thesofproject/sof/files/7153966/dmesg.txt)

**Comment by aiChaoSONG** [comment]
@jairaj-arava Better to have the dynamic debug on and attach the full log when issue happens. Please also apply the patch below
```
diff --git a/sound/soc/soc-topology.c b/sound/soc/soc-topology.c
index 88f849b119da..06409ae683c6 100644
--- a/sound/soc/soc-topology.c
+++ b/sound/soc/soc-topology.c
@@ -1592,7 +1592,8 @@ static int soc_tplg_dapm_widget_elems_load(struct soc_tplg *tplg,
                int ret;
 
                if (le32_to_cpu(widget->size) != sizeof(*widget)) {
-                       dev_err(tplg->dev, "ASoC: invalid widget size\n");
+                       dev_err(tplg->dev, "ASoC: invalid widget size, expect %d, get %d at index=%d\n",
+                        sizeof(*widget), le32_to_cpu(widget->size), i);
                        return -EINVAL;
                }
```
If you cannot reproduce the issue with dynamic debug on, please try to reproduce with the patch. Better to have both.

Edit: I will also try to reproduce locally.

**Comment by aiChaoSONG** [comment]
I don't have a ADL-M device at my hand, so I am doing reboot test on ADL-P SDW device, after 3000+ iterations, I still cannot reproduce the issue, so may need to wait the latest test result from the issue reporter side.

**Comment by jairaj-arava** [comment]
Hi,
The issue is reproduced at our end with dynamic logs enabled + with above patch @aiChaoSONG has given. However, the error signature is different now, it's seems IPC timeout. Is this due to dynamic logs enabled?

sof-audio-pci-intel-tgl 0000:00:1f.3: tplg: ready widget id 40 pipe 8 type 23 name : PCM7P stream Passthrough Playback 7
2021-09-15T03:18:13,559412-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: loaded host PCM7P
2021-09-15T03:18:13,559418-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3:  config: periods snk 2 src 0 fmt 0
 2021-09-15T03:18:13,559437-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30010000
2021-09-15T03:18:14,062117-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: **error: ipc timed out for 0x30010000 size 92**
2021-09-15T03:18:14,080144-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
2021-09-15T03:18:14,095927-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
2021-09-15T03:18:14,115732-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
2021-09-15T03:18:14,130900-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
2021-09-15T03:18:15,278794-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
2021-09-15T03:18:15,298460-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: error: DSP failed to add widget id 0 type 23 name : PCM7P stream Passthrough Playback 7 reply 0
2021-09-15T03:18:15,313092-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: failed to load widget PCM7P
2021-09-15T03:18:15,321680-07:00 sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: topology: could not load header: -110

[New_dynamic_logs.txt](https://github.com/thesofproject/linux/files/7194304/New_dynamic_logs.txt)

@aiChaoSONG  Started test only with your patch.

**Comment by aiChaoSONG** [comment]
@jairaj-arava This looks like a different issue, the initial issue is that the kernel failed to load topology, but the new one looks like the firmware doesn't reply to the COMP_NEW ipc, so I think there is something wrong with the FW, could you please also attach the firmware trace log if possible.

Edit: In the dmesg_dynamiclogs.txt, I cannot see the IPC TIMEOUT you pasted above, it is still topology component load failure(without the debug patch), so you may attach a wrong log?

Please clarify the issue, and attach the corresponding __dmesg__ and __firmware log__, thank you, this will help up to diagnose the issue better.

**Comment by jairaj-arava** [comment]
@aiChaoSONG , sorry it's my bad, updated the actual dynamic logs file.
Yes, with dynamic logs enabled we see IPC timeout. 
However, the actual issue is topology component load failure which I reported earlier. Our team started the test only with the patch you have given but due to other issues the test is not complete. I will update here once I receive the results from the team after test completion.

Also, it's not possible to have firmware logs since it's a continuous warm/cold reboot test.  Heard from the team the issue is reproduced with cold boot test  too. Hence, updated the title.

**Comment by aiChaoSONG** [comment]
@jairaj-arava do you have any third-party or self-developed processing algo integrated in the topology?

Edit: is it possible to manually run sof-logger when the test fails? so the test won't stop even if there is a failure?

**Comment by jairaj-arava** [comment]
@aiChaoSONG , we are using ADL 002 release firmware and topology. It doesn't have any third party Algo.
Since it's a continuous test process, we can try stopping the test when the issue hits and check for firmware logs.
There was some mismatch in the Coreboot, kernel configuration used, I asked our team to re-run the tests. I will update as soon as I receive the results.

**Comment by jairaj-arava** [comment]
@aiChaoSONG, Team has shifted to use CPFE image. The issue was reproduced (below are the logs in dmesg) but couldn't find any hint unlike earlier. Hence, asking team to go with next BKC release, if similar behavior is observed will try to enable logs and check for the issue.
     sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
	 sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops 0xffffffffafab5310)
	 sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
	 sof-audio-pci-intel-tgl 0000:00:1f.3: NHLT table not found
	 sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 0
	 sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
	 sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:8:0-9a35f
	 sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
	 sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
	 sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
	 sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:8:0-9a35f
	 sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0

**Comment by keqiaozhang** [comment]
@jairaj-arava can we close it? since no reproductions for one month.

**Comment by jairaj-arava** [comment]
Hi @keqiaozhang, 
Our team tried to repro in the latest BKC too, however since it's not reproduced hence closing the issue for now. Will re-open this if observed consistently in the near by time. Thanks.
