### ISSUE TITLE
Alsamixer fail with cml_rt1011_rt5682

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#3191]
I'm not able to run alsamixer command in a cml_rt1011_rt5682 device:

```
$ alsamixer
cannot load mixer controls: Invalid argument
```

After running the command there's this message in dmesg:

`[   92.931088] cml_rt1011_rt5682 cml_rt1011_rt5682: control 2:0:0:TL I2S Reference:0: access overflow`

The error happens with git commit `87f40af26c26233b060767f3e7cff5e54647cf2b ASoC: rt1011: add i2s reference control for rt1011`. The previous git commit `756bbe4205bc63a84ab032a1b76970afe55e2d9d ASoC: SOF: Handle control change notification from firmware` works for me.

Aplay and arecord works and find these devices:

```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 0: Port1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 1: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 8: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 0: Port1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 2: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 3: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 4: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlrt1011rt5 [sof-cml_rt1011_rt5682], device 5: Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

[dmesg.txt](https://github.com/thesofproject/linux/files/7278158/dmesg.txt)

[alsa-info.txt](https://github.com/thesofproject/linux/files/7278291/alsa-info.txt)

Other info

Ubuntu 20.04.2 LTS
Linux: topic/sof-dev 786e304e22cec784d04c095e7215d3e44d8a7ebc
SOF: main 9f6c2e1136c1ea0e5bcfe6453da5b5761a46e75d
Topology: sof-cml-rt1011-rt5682.tplg

**Comment by plbossart** [comment]
@jack-cy-yu can you help? Are we missing a patch on top of 87f40af26c26233b060767f3e7cff5e54647cf2b?

**Comment by jack-cy-yu** [comment]
[0001-ASoC-rt1011-add-SND_SOC_NOPM-on-rt1011_i2s_ref_enum-.zip](https://github.com/thesofproject/linux/files/7282401/0001-ASoC-rt1011-add-SND_SOC_NOPM-on-rt1011_i2s_ref_enum-.zip)
@singalsu Could you please try attached patch? Thanks.

**Comment by plbossart** [comment]
@singalsu ping?

**Comment by singalsu** [comment]
@jack-cy-yu Thanks, I just tried the below current topic/sof-dev with out patch but unfortunately no help. The same error and message to dmesg happens.

```
commit 537a8612bfbb7da758617d740845be38b5003c08 (HEAD -> test_20211007_jack)
Author: Jack Yu <jack.yu@realtek.com>
Date:   Tue Oct 5 10:39:06 2021 +0800

    ASoC: rt1011: add SND_SOC_NOPM on rt1011_i2s_ref_enum to fix overflow issue
    
    Add SND_SOC_NOPM on rt1011_i2s_ref_enum to fix access overflow issue.
    
    Signed-off-by: Jack Yu <jack.yu@realtek.com>

commit bd1219a205dfb9f98d1c51f15e7f5b6062537ca3 (upstream/topic/sof-dev, origin/topic/sof-dev, origin/HEAD, topic/sof-dev)
Author: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Date:   Thu Sep 23 13:08:07 2021 -0500

    ALSA/ASoC: hda: move/rename snd_hdac_ext_stop_streams to hdac_stream.c
    
    snd_hdac_ext_stop_streams() has really nothing to do with the
    extension, it just loops over the bus streams.
    
    Move it to the hdac_stream layer and rename to remove the 'ext'
    prefix and add the precision that the chip will also be stopped.

```

**Comment by jack-cy-yu** [comment]
@singalsu I can reproduce this issue once with "amixer cget name='I2S Reference'", but when I use "amixer -c0 cget name='I2S Reference'" again, the issue just gone and I can't reproduce it again, and alsamixer works fine as well, even I reboot the device, the issue still can't be reproduce. Is this the same on your side?

**Comment by jack-cy-yu** [comment]
@singalsu Please try the attached patch, thanks
[0001-ASoC-rt1011-fix-access-overflow-issue.zip](https://github.com/thesofproject/linux/files/7303234/0001-ASoC-rt1011-fix-access-overflow-issue.zip)
.

**Comment by singalsu** [comment]
I have now your above new patch applied and same happened. My device seems to be different:

```
$ amixer controls | grep "I2S Reference"
numid=65,iface=MIXER,name='TL I2S Reference'
numid=85,iface=MIXER,name='TR I2S Reference'
numid=25,iface=MIXER,name='WL I2S Reference'
numid=45,iface=MIXER,name='WR I2S Reference'

$ amixer cget name='TL I2S Reference'
numid=65,iface=MIXER,name='TL I2S Reference'
  ; type=ENUMERATED,access=rw------,values=1,items=3
  ; Item #0 'None'
  ; Item #1 'Left Channel'
  ; Item #2 'Right Channel'
amixer: Control default element read error: Invalid argument

$ amixer cget name='TR I2S Reference'
numid=85,iface=MIXER,name='TR I2S Reference'
  ; type=ENUMERATED,access=rw------,values=1,items=3
  ; Item #0 'None'
  ; Item #1 'Left Channel'
  ; Item #2 'Right Channel'
amixer: Control default element read error: Invalid argument

$ amixer cget name='WL I2S Reference'
numid=25,iface=MIXER,name='WL I2S Reference'
  ; type=ENUMERATED,access=rw------,values=1,items=3
  ; Item #0 'None'
  ; Item #1 'Left Channel'
  ; Item #2 'Right Channel'
amixer: Control default element read error: Invalid argument

$ amixer cget name='WR I2S Reference'
numid=45,iface=MIXER,name='WR I2S Reference'
  ; type=ENUMERATED,access=rw------,values=1,items=3
  ; Item #0 'None'
  ; Item #1 'Left Channel'
  ; Item #2 'Right Channel'
amixer: Control default element read error: Invalid argument

```

If I add the -c0, the same happens

```
$ amixer -c0 cget name='TL I2S Reference'
numid=65,iface=MIXER,name='TL I2S Reference'
  ; type=ENUMERATED,access=rw------,values=1,items=3
  ; Item #0 'None'
  ; Item #1 'Left Channel'
  ; Item #2 'Right Channel'
amixer: Control hw:0 element read error: Invalid argument

```
I can do additional tests here by adding debug prints to code if you have ideas what to test.

**Comment by singalsu** [comment]
@jack-cy-yu I didn't have your first patch included this time. Should it have been there?

**Comment by jack-cy-yu** [comment]
@singalsu No need to include the first patch. I am confused why my CML device can't reproduce it again, even I reload the module or reboot the device. I find there is mail thread talking about "access overflow" 
https://bugzilla.kernel.org/show_bug.cgi?id=207139

Is setting CONFIG_SND_CTL_VALIDATION=n helps to fix it? Because I see no problem with this SOC_ENUM_EXT declaration, and it works on my device as well.

**Comment by jack-cy-yu** [comment]
@singalsu below I found some related topics about fail to load mixers, not sure if it helps?
https://askubuntu.com/questions/765396/alsamixer-cannot-open-mixer-invalid-argument
https://bbs.archlinux.org/viewtopic.php?id=123250

**Comment by ujfalusi** [comment]
a patch fixing the issue sent upstream:
https://lore.kernel.org/alsa-devel/20211011141543.31030-1-peter.ujfalusi@linux.intel.com/

**Comment by ujfalusi** [comment]
and a v3, hopefully the final one is:
https://lore.kernel.org/alsa-devel/20211011144518.2518-1-peter.ujfalusi@linux.intel.com/

**Comment by ujfalusi** [comment]
Another update for the fix after looking at the original once more:
https://lore.kernel.org/alsa-devel/20211012063113.3754-1-peter.ujfalusi@linux.intel.com/

**Comment by plbossart** [comment]
@ujfalusi @singalsu this looks like a fixed issue, please close this if indeed we have a solution. Thanks!

**Comment by ujfalusi** [comment]
@singalsu, the patch is in sof-dev now: f05a9b8552896d95fc22e135eaf9c6be541bfe79, can you verify again? Thanks.

**Comment by singalsu** [comment]
@ujfalusi Thanks, I just checked and things work now OK. 

Closing!
