### ISSUE TITLE
Cannot get audio on TGL based NUC laptop

### ISSUE THREAD

**Issue by ignaciohg** [thesofproject/linux#3241]
Hi, 

I got a NUC laptop and have been trying to get the audio to work, so far the only thing I see is Dummy output listed. I have tested Fedora 35 beta and now I am running Ubuntu 21.10 with no luck.

Not knowing what is useful to debug the problem, I ran alsa-info and the output is located at:

http://alsa-project.org/db/?f=d811895a16b7ba358f336c1d7c84300e5326f8e1

Thanks!

**Comment by plbossart** [comment]
@ignaciohg known issue, see https://github.com/thesofproject/linux/issues/3049

We've added support for this laptop and upstreamed the code, see https://lore.kernel.org/alsa-devel/20210719233248.557923-1-pierre-louis.bossart@linux.intel.com/

The code is already in 5.15-rc6 and will be part of 5.15 when it's released (likely next week?).

the minimum two patches you'll need for a backport are:

````
caa15c8dcb00 soundwire: dmi-quirks: add quirk for Intel 'Bishop County' NUC M15
1bd80ff2cfb3 ASOC: Intel: sof_sdw: add quirk for Intel 'Bishop County' NUC M15
````

Good luck!

**Comment by ignaciohg** [comment]
Thanks for the help. 

I tried with a nightly 5.15-rc7 build from Ubuntu and the machine hangs randomly while booting, no luck there. Then I tried building my own, did a localmodconfig build based on kernel.org 5.15-rc7 and the machine booted, just no audio.

I need to do a more careful config of the kernel to make sure it works. Do you have a list of required kernel options needed to have sof audio working?

**Comment by plbossart** [comment]
@ignaciohg you can look at the references we use:

https://github.com/thesofproject/kconfig/blob/master/sof-defconfig
https://github.com/thesofproject/kconfig/blob/master/mach-driver-defconfig

**Comment by plbossart** [comment]
no update and downstream problem, closing

**Comment by ignaciohg** [comment]
I dumped Ubuntu and installed Fedora, the test kernel for 5.15 and now the sound works fine for me. Now, to get camera and touchscreen working

Thanks a lot for the help!
