### ISSUE TITLE
AMD: sparse warning + ACP_DEFAULT_DRAM_LENGTH duplicate definition

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3265]
Sparse reports the following warning

````
CHECK   sound/soc/sof/amd/acp-loader.c
sound/soc/sof/amd/acp-loader.c:83:31: warning: memset with byte count of 524288
````

this is indeed in the code:
sound/soc/sof/amd/acp-loader.c:                 memset(adata->data_buf, 0, ACP_DEFAULT_DRAM_LENGTH);

but in addition the same pre-processing variable is defined twice?

sound/soc/sof/amd/acp.h:#define ACP_DEFAULT_DRAM_LENGTH                 0x00080000
sound/soc/sof/amd/acp.h:#define ACP_DEFAULT_DRAM_LENGTH                 0x00080000

@ajitkupandey can you please look into this?

**Comment by ajitkupandey** [comment]
Just wondering why this warning not reported with sparse check tool when PR was generated ? Are you using some extra sparse build flags or configuration ?

Anyways I've uploaded a fixup PR for this here https://github.com/thesofproject/linux/pull/3267

**Comment by plbossart** [comment]
Not sure why this wasn't shown earlier @ajitkupandey, just like I don't know how we missed the conflict between static and EXPORT_SYMBOL.
