### ISSUE TITLE
[BUG] Install custom kernel build on device for enabling debug data from DSP (HP Chromebook X360)

### ISSUE THREAD

**Issue by sanzazacuro** [thesofproject/linux#3268]
**Describe the bug**
When trying to get debug data from SOF, I encouter the errors:
`error: in logger_read(), fread(..., /sys/kernel/debug/sof/etrace) failed: Operation not permitted(-1)`
`error: debugfs entry cannot be read in DSP D3`

By reading other issues in GitHub, I figured this would be solved by building a new kernel with the Kconfig flags in `sof-dev-defconfig` (in Kconfig repo, CONFIG_SND_SOC_SOF_DEBUG, CONFIG_SND_SOC_SOF_DEBUG_ENABLE_FIRMWARE_TRACE etc.) and following [this guide.](https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html#step-6-build-linux-kernel). 

The guide says to pack the linux kernel in a .deb file and install with `dpkg` and `apt-get`, however the linux version on device does not have any of the standard applications such as these. How should a kernel image be loaded on this device and is this the correct way of enabling debugdata from DSP?

**To Reproduce**
- Build firmware and toplogy for tgl and sof-tgl-max-98357a-rt5682 and load on device
- Run `sof-logger -l sof-tgl.ldc -p`

**Reproduction Rate**
100%

**Expected behavior**
`sof-logger -l sof-tgl.ldc -p` should output trace/logs from DSP

**Impact**
Not able to get debug data from DSP.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.4.139-16311-g330b3df0010b
    * SOF: a03e5386dc49f824264c86a4a27a6d398c505d04
2) Name of the topology file
    * Topology: sof-tgl-max98357a-rt5682.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: Tigerlake (HP Chromebook X360)

**Comment by sanzazacuro** [comment]
@plbossart I built a new kernel from `topic/sof-dev` (5.15), applied with the kconfig parameters from the `kconfig-sof-default.sh` script. What is the recommended way to push and flash the `bzImage` or `.deb` on device without the std linux utilities?

**Comment by plbossart** [comment]
@sanzazacuro does the target run with ChromeOS developer mode or a regular Ubuntu/Fedora distribution? In the first case you need to use the Chrome build environment to install the new kernel. In the latter case you just need to push the new kernel image and modules and re-generate the initrd/initramfs part. I can provide more detailed instructions depending on the two options.

**Comment by sanzazacuro** [comment]
Thanks, that would be great! Yes, it runs ChromeOS Developer mode.

**Comment by plbossart** [comment]
@sanzazacuro this is hard...I haven't pushed an updated kernel to ChromeOS since 4.14, some 3 years ago. 

See this file 
[notes-public.txt](https://github.com/thesofproject/linux/files/7506584/notes-public.txt) which contained my cheat sheet at the time. @cujomalainey and @bzhg may be able to point you to a better documentation. 

Essentially the trick was to extract a Chrome build environment, change the kernel and the .config and use the chroot to build and remote install the kernel. A lot of things can go wrong here.

**Comment by cujomalainey** [comment]
@sanzazacuro are you running a test image?

**Comment by sanzazacuro** [comment]
@plbossart Thanks a lot, I will try it out.

@cujomalainey No, I dont believe so. Its a production chromebook in developer mode, ChromeOS version 94.0.4606.115 (Official build)

**Comment by sanzazacuro** [comment]
@cujomalainey Is it an option to dual boot with a distro, for instance ubuntu, develop with SOF with a 5.10+ kernel on that partition, and then just flash the DSP firmware on ChromeOS with the 5.4 kernel afterwards?

**Comment by cujomalainey** [comment]
@sanzazacuro that is likely possible but much more work than what our system is setup for. I recommend you read https://chromium.googlesource.com/chromiumos/docs/+/main/developer_guide.md

It will show you how to make a test image which will allow you to flash kernels and fw to the device with ease over ssh

**Comment by cujomalainey** [comment]
@sanzazacuro also in theory you should have to do minimal work on the kernel
