### ISSUE TITLE
Module get params is NULL for the 1st time query after boot: sof kcontrols issue

### ISSUE THREAD

**Issue by sathya-nujella** [thesofproject/linux#3316]
DUT: TGL system 
       (speaker amp path has Maxim DSM enabled)
Kernel:  chrome 5.4 kernel 

**Issue description:**
1. Boot DUT
2. Read DSM models params using:
        /usr/local/opt/sof-ctl -c "name=SMART_AMP1.0 Smart_amp Model_Get_params" -t 1 -b -r
        it returns all NULL data
3.  Read again using the same sof-ctl command as in 2nd step, now it returns the data

**What problem this issue cause:**
Audio tuning gets affected

**More Details of the issue:**
//for 1st time read: sparams.msg_bytes is zero in snd_sof_ipc_set_get_comp_data().
[   89.238147] snd_sof_ipc_set_get_comp_data 124 0 124
[   89.238150] snd_sof_ipc_set_get_comp_data 0
[   89.238157] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50040000
[   89.238408] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50040000
[   89.238409] snd_sof_ipc_set_get_comp_data 763 3632

//for 2nd time read, size is correct
[  114.317827] snd_sof_ipc_set_get_comp_data 3756 3632 124
[  114.317831] snd_sof_ipc_set_get_comp_data 3632
[  114.317834] sof-audio-pci 0000:00:1f.3: large ipc size 3756, control size 124
[  114.317885] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50040000
[  114.318796] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50040000
[  114.318846] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50040000

**Comment by sathya-nujella** [comment]
Thank you to @ranj063 , she provided this patch. With this change, I can see 1st time read is correctly giving the size.

**Comment by sathya-nujella** [comment]
Here is the change mentioned by @ranj063 
```
diff --git a/sound/soc/sof/topology.c b/sound/soc/sof/topology.c
index a6491846fe48..fe759c34984d 100644
--- a/sound/soc/sof/topology.c
+++ b/sound/soc/sof/topology.c
@@ -3515,6 +3515,50 @@ static int sof_set_pipe_widget(struct snd_sof_dev *sdev, struct snd_sof_widget *
 	return 0;
 }
 
+/* Function to set the initial value of SOF kcontrols.
+ * The value will be stored in scontrol->control_data
+ */
+static int snd_sof_cache_kcontrol_val(struct snd_soc_component *scomp)
+{
+	struct snd_sof_dev *sdev = snd_soc_component_get_drvdata(scomp);
+	struct snd_sof_control *scontrol = NULL;
+	int ipc_cmd, ctrl_type;
+	int ret = 0;
+
+	list_for_each_entry(scontrol, &sdev->kcontrol_list, list) {
+
+		/* notify DSP of kcontrol values */
+		switch (scontrol->cmd) {
+		case SOF_CTRL_CMD_VOLUME:
+		case SOF_CTRL_CMD_ENUM:
+		case SOF_CTRL_CMD_SWITCH:
+			ipc_cmd = SOF_IPC_COMP_GET_VALUE;
+			ctrl_type = SOF_CTRL_TYPE_VALUE_CHAN_GET;
+			break;
+		case SOF_CTRL_CMD_BINARY:
+			ipc_cmd = SOF_IPC_COMP_GET_DATA;
+			ctrl_type = SOF_CTRL_TYPE_DATA_GET;
+			break;
+		default:
+			dev_err(scomp->dev,
+				"error: Invalid scontrol->cmd: %d\n",
+				scontrol->cmd);
+			return -EINVAL;
+		}
+		ret = snd_sof_ipc_set_get_comp_data(scontrol,
+						    ipc_cmd, ctrl_type,
+						    scontrol->cmd,
+						    false);
+		if (ret < 0) {
+			dev_warn(scomp->dev,
+				 "error: kcontrol value get for widget: %d\n",
+				 scontrol->comp_id);
+		}
+	}
+
+	return ret;
+}
+
 /* completion - called at completion of firmware loading */
 static int sof_complete(struct snd_soc_component *scomp)
 {
@@ -3558,7 +3602,11 @@ static int sof_complete(struct snd_soc_component *scomp)
 	}
 
 	/* set up static pipelines */
-	return sof_set_up_pipelines(sdev, false);
+	ret = sof_set_up_pipelines(sdev, false);
+	if (ret < 0)
+		return ret;
+
+	return snd_sof_cache_kcontrol_val(scomp);
 }
 
 /* manifest - optional to inform component of manifest */
```

**Comment by ranj063** [comment]
@plbossart this only worked in the past by chance because we called snd_sof_cache_kcontrol_val() without knowing what size to get and resulted in actually getting the size of cdata from the FW. While it does help fix the problem, I'm not sure if this is the right solution.

How can we avoid this initial get to avoid this problem? Should a get always use the size requested by sof-ctl instead?
