### ISSUE TITLE
[FEATURE] use NHLT to detect which SSP is used for devices with ES8336

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3337]
So far we've never needed to guess what SSP was used, it was known by design for Chromebooks and SSP was never used in devices designed for Windows.

Devices with ES8336 break that assumption, they support Windows but also use I2S/SSP. We may need to use the NHLT information, if present, to detect what SSP to use in the machine driver and topology.

**Comment by plbossart** [comment]
@hli25 could you try to dump the NHLT tables used in the GLK and TGL devices you used?

**Comment by plbossart** [comment]
> @hli25 could you try to dump the NHLT tables used in the GLK and TGL devices you used?

I meant just dump the ACPI tables with 'sudo acpidump > dump.bin', for NHLT a newer version 20210930 acpica-tools version is needed.

**Comment by hli25** [comment]
Loop @yangxiaohua2009 too

**Comment by yangxiaohua2009** [comment]
@hli25 @plbossart we have glk, cml, cfl 8336 and 8326 tgl devices. [DUMP.zip](https://github.com/thesofproject/linux/files/7716988/DUMP.zip)

**Comment by plbossart** [comment]
Thanks @yangxiaohua2009.

I wasn't able to parse the CFL table.

For CML and TGL I see SSP0 being used.
For GLK I see SPP2 being used.

**Comment by plbossart** [comment]
solution implemented in 	https://github.com/thesofproject/linux/pull/3338

The only problem is that we need quite a few topology files, see 
[es8336-topologies-2.tar.gz](https://github.com/thesofproject/linux/files/7883781/es8336-topologies-2.tar.gz)
and it would be preferable to override a default SSP from the machine driver.

**Comment by plbossart** [comment]
feature completed and upstream
