### ISSUE TITLE
[BUG] No mic data on HP Chromebook X360 

### ISSUE THREAD

**Issue by sanzazacuro** [thesofproject/linux#3348]
**Describe the bug**
I am not able to get mic data on device with `intel-generic-dmic` pipeline. Kernel log reports `No GPIO consumer dmicen found` and 
`SSP1-Codec: ASoC: no backend capture stream`. Is there anything that needs to be patched for Intel dmic?

**To Reproduce**
`arecord -f dat micTest.wav`

**Reproduction Rate**
100%

**Expected behavior**
Get mic data in DSP.

**Impact**
Showstopper

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.15
    * SOF: 5ef33e6310b7921cb2fdae4bf2ae798d26cb5438
2) Name of the topology file
    * Topology: sof-tgl-max98357a-rt5682.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: tigerlake

**Screenshots or console output**
```
[   37.689624] dmic-codec dmic-codec: GPIO lookup for consumer dmicen
[   37.689641] dmic-codec dmic-codec: using lookup tables for GPIO lookup
[   37.689668] dmic-codec dmic-codec: No GPIO consumer dmicen found
...
[   39.045291]  SSP1-Codec: ASoC: no backend capture stream
[   39.047765]  SSP1-Codec: ASoC: no users capture at close - state 0
```

arecord -l gives:
```
**** List of CAPTURE Hardware Devices ****
card 0: sofrt5682 [sof-rt5682], device 6: EchoRef (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 99: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 100: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #
```0

**Comment by sanzazacuro** [comment]
@lgirdwood Anything I can do on my side to find the correct pin?

**Comment by plbossart** [comment]
@sanzazacuro can you retry using the hw devices? 

arecord -Dhw:0,0 -c4 -r48000 -f S32_LE

I don't understand how SSP1 can come in the picture here.

**Comment by sanzazacuro** [comment]
@plbossart with `arecord -Dhw:0,0 -c4 -r48000 -f S32_LE ` I get `arecord: main:828: audio open error: No such file or directory`. 

I am not able to trigger with `-Dhw:0,0`, even though the parameters seems correct. If I use arecord with `arecord -c4 -r48000 -f S32_LE` it runs, but no mic data is recieved.

**Comment by sanzazacuro** [comment]
@plbossart I was able to get mic data with `arecord -Dhw:0,99 -c4 -r48000 -f S32_LE`. It only works if I speficy 4 channels for the mic?

**Comment by plbossart** [comment]
> @plbossart I was able to get mic data with `arecord -Dhw:0,99 -c4 -r48000 -f S32_LE`. It only works if I speficy 4 channels for the mic?

Yes, the device was 99.

that's right we only support 4 channels for the dmic, the extra channels are removed by CRAS.

so if you are able to support HW devices, then the problem you had is at the alsa-lib level, or more likely in the CRAS plugins for alsa-lib
