### ISSUE TITLE
ADL: error: cl_dsp_init: timeout HDA_DSP_SRAM_REG_ROM_STATUS read

### ISSUE THREAD

**Issue by khfeng** [thesofproject/linux#3355]
No audio on an ADL laptop:
```
$ sudo dmesg | grep -E "snd|sof"
[   13.371209] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   13.371216] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   13.372094] snd_hda_intel 0000:03:00.1: enabling device (0000 -> 0002)
[   13.372253] snd_hda_intel 0000:03:00.1: Handle vga_switcheroo audio client
[   13.372256] snd_hda_intel 0000:03:00.1: Force to non-snoop mode
[   13.397103] snd_hda_intel 0000:03:00.1: bound 0000:03:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
[   13.455879] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   13.455884] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   13.455899] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
[   13.456129] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[   13.456639] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   13.464140] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[   13.532343] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
[   13.532347] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   13.532352] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 4
[   13.533180] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:0:0-b678a
[   13.533182] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[   13.533184] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[   13.533187] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[   14.438213] sof-audio-pci-intel-tgl 0000:00:1f.3: error: cl_dsp_init: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[   14.438224] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[   14.438227] sof-audio-pci-intel-tgl 0000:00:1f.3: Boot iteration failed: 3/3
[   14.438230] sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[   14.438248] sof-audio-pci-intel-tgl 0000:00:1f.3: extended rom status:  0x6000021 0x0 0x0 0x0 0x0 0x0 0x255052b 0x0
[   14.438251] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[   14.438822] sof-audio-pci-intel-tgl 0000:00:1f.3: error: dsp init failed after 3 attempts with err: -110
[   14.438866] sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to start DSP
[   14.438870] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to boot DSP firmware -110
[   14.489563] sof-audio-pci-intel-tgl 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[   14.489571] sof-audio-pci-intel-tgl 0000:00:1f.3: error: dsp core reset failed: core_mask 1
[   14.489819] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -110
```

**Comment by khfeng** [comment]
[dmesg.txt](https://github.com/thesofproject/linux/files/7811906/dmesg.txt)

**Comment by plbossart** [comment]
@khfeng could this be a mismatch between firmware signature keys? Is this device using a community, debug or production key?

**Comment by khfeng** [comment]
> @khfeng could this be a mismatch between firmware signature keys? Is this device using a community, debug or production key?

I actually don't know. How do I know that? Can how to switch to use the correct key?

**Comment by aiChaoSONG** [comment]
@khfeng Please try the latest sof release: https://github.com/thesofproject/sof-bin, install v2.0.x,  once you installed it according to readme, the default fw should be signed by production key. 
```
➜  ~ ls /lib/firmware/intel/sof/sof-adl.ri -al
lrwxrwxrwx 1 root root 23 Dec 25 10:06 /lib/firmware/intel/sof/sof-adl.ri -> intel-signed/sof-adl.ri
```
if the production key signed firmware can not work for you, you can try the community key signed one by overriding the soft link, and make it point to `community/sof-adl.ri`
Paste the error logs, if your problem still exist.

**Comment by plbossart** [comment]
@khfeng we cannot find out which key was used unfortunately, so either you can get the information from the OEM, or you try different keys until you find the right one.

The recommendation from @aiChaoSONG isn't the best solution. It's better to avoid mucking with the installed files and use the kernel parameter instead by adding this in /etc/modprobe.d/alsa-base.conf to use the community key.

````
options snd_sof_pci fw_path="intel/community"
````

**Comment by khfeng** [comment]
[dmesg-community.txt](https://github.com/thesofproject/linux/files/7851484/dmesg-community.txt)
[dmesg-intel-signed.txt](https://github.com/thesofproject/linux/files/7851485/dmesg-intel-signed.txt)

**Comment by khfeng** [comment]
BTW I can't find 2.0.x, so I am still using 2.0.0 like the original dmesg.

**Comment by aiChaoSONG** [comment]
OK, looks neither firmware works for you, the same code `0x6000021` from ROM.  @keqiaozhang  Did you see this error code before?

**Comment by plbossart** [comment]
@khfeng You may have an early version of the hardware with the debug key, you would need to ask Intel for the firmware. @mengdonglin FYI.

**Comment by keqiaozhang** [comment]
> OK, looks neither firmware works for you, the same code `0x6000021` from ROM. @keqiaozhang Did you see this error code before?

I met the same issue on ADLP Chrome device before, this is not the key error, but the CSE related. the CSE interface is disabled for some reason on ADLP Chrome device. The fix is from the coreboot. please refer to https://github.com/thesofproject/sof/issues/4923

**Comment by khfeng** [comment]
Thanks. Let me raise the issue to their platform team.

**Comment by kv2019i** [comment]
Closing. Please @khfeng  reopen if this is not solved via platform firmware update.
