### ISSUE TITLE
[BUG] No sound for Intel Cannon Lake PCH cAVS on Legion Y9000X 2020

### ISSUE THREAD

**Issue by fbl718** [thesofproject/linux#3356]
### Describe the bug
No sound from speakers, but from headphones. Both speakers and headphones can be detected correctly. Although the sound of the speakers can be temporarily fixed by https://github.com/thesofproject/linux/issues/2748#issuecomment-820028060, the speakers still have no sound after plugging in and out headphones.
### To Reproduce
No special steps to reproduce (the issue is always there right after boot).
### Reproduction Rate
100%
### Expected behavior
Audible sound.
### Environment
Manufacturer:      LENOVO
Product Name:      81TH
Product Version:   Lenovo Legion Y9000X 2020
Firmware Version:  CTCN19WW(V1.04)
System SKU:        LENOVO_MT_81TH_BU_idea_FM_Legion Y9000X 2020
Board Vendor:      LENOVO
Board Name:        LNVNB161216
Kernel: 5.15.12-051512-generic
Distribution: Ubuntu 20.04.3 LTS
Detailed information can be checked by `sudo alsa-info --no-upload`.
This is my [also-info.txt](https://github.com/thesofproject/linux/files/7811990/also-info.txt).
### Bug
- [x] No sound from speakers after booting
- [x] No sound from speakers after unplugging the headphones

**Comment by fbl718** [comment]
To solve the problem, I borrowed solution from [Ryan Prescott](https://patchwork.kernel.org/project/alsa-devel/patch/20210416081211.20059-1-tiwai@suse.de/) and [Cameron Berkenpas](https://patchwork.kernel.org/project/alsa-devel/patch/20210913212627.339362-1-cam@neo-zeon.de/).

Luckily, I found a fix for [v5.15.11](https://elixir.bootlin.com/linux/v5.15.11/source) and [v5.15.12](https://elixir.bootlin.com/linux/v5.15.12/source). I have submitted the [patch](https://lkml.org/lkml/2022/1/4/1173) to alsa, and you can try apply the patch to fix the speaker problem in Legion Y9000X 2020. It should work for kernel after [v5.14.10](https://elixir.bootlin.com/linux/v5.14.10/source), although I only tested it for [v5.15.11](https://elixir.bootlin.com/linux/v5.15.11/source) and [v5.15.12](https://elixir.bootlin.com/linux/v5.15.12/source).

**What's fixed**
- [x] No sound from speakers after booting
- [x] No sound from speakers after unplugging the headphones

**Comment by plbossart** [comment]
Nice work @fbl718, thanks for sharing your results. 

I'll close this issue since it's unrelated to SOF.
