### ISSUE TITLE
Dummy output and no sound with KUU Xbook laptop (ES8336)

### ISSUE THREAD

**Issue by hav4k** [thesofproject/linux#3363]
Hi.

Just install OpenSUSE Tumbleweed with last kernel 5.16 and SOF-bin, fixed dummy output but persist no sound. What can i do? Bluetooth works fine, speakers and headphones not. 

  5.277695] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    5.277999] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    5.278606] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    5.352756] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    5.418691] sof-audio-pci-intel-apl 0000:00:0e.0: hda codecs found, mask 4
[    5.421347] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 1:9:3-a9780
[    5.421355] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    5.421359] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
**[    5.421371] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30**
[    5.461261] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 1:9:3-a9780
[    5.461269] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    5.461272] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    5.805867] sof-audio-pci-intel-apl 0000:00:0e.0: Topology: ABI 3:20:0 Kernel ABI 3:18:0
[    5.805878] sof-audio-pci-intel-apl 0000:00:0e.0: warn: topology ABI is more recent than kernel

![Screenshot from 2022-01-10 13-16-53](https://user-images.githubusercontent.com/19598731/148765117-11157281-8a04-4a28-8292-940019aaafb3.png)

Regards and thanks for help.

**Comment by hav4k** [comment]
> like the same issue as #3336
> 
> try the suggested quirks and changes in topology if you can't get a working solution.

options snd-soc-sof-es8336 quirk=0x00
options snd-soc-sof-es8336 quirk=0x10
options snd-soc-sof-es8336 quirk=0x30 (with SSP0 topology)
options snd-soc-sof-es8336 quirk=0x31 (with SSP1 topology)
options snd-soc-sof-es8336 quirk=0x32 (with SSP2 topology)

Is these all? I will try later.

**Comment by plbossart** [comment]
I am afraid that you have to explore all combinatorial options

options snd-soc-sof-es8336 quirk=0x00 (with SSP0 topology)
options snd-soc-sof-es8336 quirk=0x01 (with SSP1 topology)
options snd-soc-sof-es8336 quirk=0x02 (with SSP2 topology)
options snd-soc-sof-es8336 quirk=0x10 (with SSP0 topology)
options snd-soc-sof-es8336 quirk=0x11 (with SSP1 topology)
options snd-soc-sof-es8336 quirk=0x12 (with SSP2 topology)
options snd-soc-sof-es8336 quirk=0x30 (with SSP0 topology)
options snd-soc-sof-es8336 quirk=0x31 (with SSP1 topology)
options snd-soc-sof-es8336 quirk=0x32 (with SSP2 topology)

Or test with https://github.com/thesofproject/linux/pull/3338 which should tell you which SSP is used.

**Comment by hav4k** [comment]
> I am afraid that you have to explore all combinatorial options
> 
> options snd-soc-sof-es8336 quirk=0x00 (with SSP0 topology) options snd-soc-sof-es8336 quirk=0x01 (with SSP1 topology) options snd-soc-sof-es8336 quirk=0x02 (with SSP2 topology) options snd-soc-sof-es8336 quirk=0x10 (with SSP0 topology) options snd-soc-sof-es8336 quirk=0x11 (with SSP1 topology) options snd-soc-sof-es8336 quirk=0x12 (with SSP2 topology) options snd-soc-sof-es8336 quirk=0x30 (with SSP0 topology) options snd-soc-sof-es8336 quirk=0x31 (with SSP1 topology) options snd-soc-sof-es8336 quirk=0x32 (with SSP2 topology)
> 
> Or test with #3338 which should tell you which SSP is used.

No success, still without sound. I tried all quirks. :(

**Comment by hav4k** [comment]
Finally solved with Linux Mint:

https://github.com/yangxiaohua2009/custom-kernel

Thanks!!!

**Comment by Burnoh** [comment]
> Finally solved with Linux Mint:
> 
> https://github.com/yangxiaohua2009/custom-kernel
> 
> Thanks!!!

Can I install this custom kernel on Elementary OS 6.1? It's based on Ubuntu just like Linux Mint afaik

**Comment by plbossart** [comment]
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.
