### ISSUE TITLE
[ADL] [HDA] 3.5mm headset recording not working - no audio

### ISSUE THREAD

**Issue by padmashree9110** [thesofproject/linux#3364]
Description
3.5mm recording is not working 

Platform
 AlderLake-P

Kernel Log:
[dmesg.txt](https://github.com/thesofproject/linux/files/7846198/dmesg.txt)

Steps:
1> Added adl.ri to /lib/firmware/intel/sof
2>able to see card getting listed
     intel@ADL-P-LP5-T4-RVP:~$ cat /proc/asound/cards
                                       [sofhdadsp      ]: sof-hda-dsp - sof-hda-dsp
                                       IntelCorporation-AlderLakeClientPlatform-0.1-AlderLake_PLP5RVP

3> 3.5mm playback is fine. Recording has no audio.
4> Checked the same using arecord command. results are same. No audio in recorded file.

Note: 3.5mm recording works fine with legacy HDA on the same device. Only with SOF-HDA, 3.5mm has recording issue.

**Comment by plbossart** [comment]
@padmashree9110 can you clarify why you're using kernel 5.10 on AlderLake? It's older than your BIOS :-)

````
[    0.000000] DMI: Intel Corporation Alder Lake Client Platform/AlderLake-P LP5 RVP, BIOS ADLPFWI1.R00.2471.A06.2112061651 12/06/2021
````

same question for the firmware, it's 1.8 and we released 2.0 in December 2021

````
[    7.177105] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:8:0-3099b
````

**Comment by keqiaozhang** [comment]
@padmashree9110 , please try with the latest kernel and firmware release: https://github.com/thesofproject/sof/releases/tag/v2.0

**Comment by padmashree9110** [comment]
@plbossart 5.10 kernel is our POR. So using it.  I tried with latest release v2.0 (sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:0). Still i see same issue with 3.5mm recording. 

and kernel minimum requirement i see 5.8 in sof wiki (Minimum requirement is 5.8). 

if 5.15 kernel this issue is not there, any patches which we can back port and use with 5.10 kernel?

**Comment by padmashree9110** [comment]
I tried with 5.15 kernel also. Issue is seen there also.
$ uname -r
5.15.0-051500-generic

Kernel log:
[dmesg_sof_5.15.txt](https://github.com/thesofproject/linux/files/8078499/dmesg_sof_5.15.txt)

**Comment by plbossart** [comment]
@padmashree9110 Are you sure that you have enabled all the volumes/switches on capture with alsamixer?

**Comment by padmashree9110** [comment]
yes...capture volume i set to maximum and checked. still no audio.

**Comment by padmashree9110** [comment]
@plbossart @keqiaozhang any update on this issue?

**Comment by plbossart** [comment]
@padmashree9110 it's quite unclear what you might expect of us. We can only comment on experiments and results that YOU would be doing.

**Comment by padmashree9110** [comment]
This issue got resolved after reinstalling ubuntu. Thanks for the support.
