### ISSUE TITLE
noise issue when both front L and front R are connected on GP-MRB

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#34]
This issue occurs when both front L and front R are connected, but disconnect one of them, the noise will disappear.
sof-dev:a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof-master:c4a9cca0a94969fbf1ecb42d660c0e40279d9ffa
soft-master:2abbfc0910ce9767d01462638d719309746844d1
tplg:sof-apl-tdf8532.tplg

How to reproduce:

1. Ensure both front L and front R are connected.
2. aplay -D hw:0,0 -f S32_LE -r 48000 -c 4 /home/rander/4ch_32bit.wav , you can hear the noise and the noise sounds like a rustle.
3. Disconnect front L or front R. the noise will disappear

**Comment by plbossart** [comment]
This looks like a platform/hardware/electrical issue. There is nothing in the kernel that handles plug-in events and deals with the connection/disconnection, on this board so there's no way to fix this...

**Comment by mengdonglin** [comment]
This platform is no longer supported and so close this bug
