### ISSUE TITLE
IRQ not handled on Broadwell -> IPC failures

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3400]
The tests of PR #3399 expose a large number of failures on Broadwell:

https://sof-ci.01.org/linuxpr/PR3399/build7065/devicetest/

````
[  355.848562] kernel: irq 3: nobody cared (try booting with the "irqpoll" option)
[  355.849136] kernel: handlers:
[  355.849146] kernel: [<0000000007b3a513>] bdw_irq_handler [snd_sof_acpi_intel_bdw] threaded [<00000000e5d9f32d>] bdw_irq_thread [snd_sof_acpi_intel_bdw]
[  355.849188] kernel: Disabling IRQ #3
````

after this initial error, all tests fail with IPC errors.

**Comment by lgirdwood** [comment]
Indeed an odd one, cant see the huge performance change here that could race.
