### ISSUE TITLE
No sound on Chuwi Herobook Pro Alsamixer Speaker 00 Intel Geminilake essx8336

### ISSUE THREAD

**Issue by phre2** [thesofproject/linux#3428]
Hi everyone -- Some months ago I bought this Chuwi Herobook Pro because my Macbook stopped working, so I returned using Linux after years.

First thing I noticed there was no audio, only Dummy Output. I've tried everything in these past months but no results. Finally it seems a solution, reading online: newest kernel + sof.

So I've installed Kernel 5.16 + sof-bin 2.0 and finally the audio card it's detected! But... still no sound as in alsamixer speaker is on 00 with no way to put the volume up.

I've read other issues open here, downloaded the suggested topology, added quirk 0x10 in alsa conf but still no result.

Anyone able to fix this freaking issue? It's driving me crazy.

Distro: Kubuntu 20.04
Kernel: 5.16.9
Sof-bin: 2.0

Sorry for my English, but it's not my first language.

Thanks everyone

![image](https://user-images.githubusercontent.com/96545137/153854282-23e90933-c5f7-447b-af7f-afff5c894b76.png)

**Comment by plbossart** [comment]
@phre2 the latest instructions are to try with 
https://github.com/thesofproject/linux/pull/3338
and updated topologies from https://github.com/thesofproject/linux/files/7871608/es8336-topologies-2.tar.gz

please attach alsa-info when the device is setup with this test kernel.

**Comment by phre2** [comment]
Copied the updated topologies in the right dir, but where to find the test kernel?

**Comment by plbossart** [comment]
> Copied the updated topologies in the right dir, but where to find the test kernel?

You have to compile it yourself I am afraid.We have an on-going PR to provide guidance in https://github.com/thesofproject/sof-docs/pull/404 but it's not merged just yet.

**Comment by phre2** [comment]
Oh, I see. Hopefully I still remember how to do it after all these years. Where to find the sources to compile it?

**Comment by plbossart** [comment]
https://github.com/plbossart/sound/tree/fix/sof-es8336-quirk

**Comment by phre2** [comment]
Thanks!

Compiling keeps failing 😅 but I'll keep going.

Let you guys know.

**Comment by plbossart** [comment]
I screwed up yesterday, you may have to pull the latest update.

**Comment by phre2** [comment]
Oh, ok. Will give another spin later tonight then. Many thanks.

**Comment by phre2** [comment]
Still getting 

`arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
`

as I said, I'm a bit rusty at compiling kernels on my own.

**Comment by yurisuki** [comment]
yes, id like to know also how do i compile this thing

**Comment by phre2** [comment]
For whoever still facing this issue, I fixed it with these commands

amixer cset name='Headphone Switch' on
amixer cset name='Speaker Switch' on
amixer cset name='Headphone Playback Volume' 3,3
amixer cset name='Right Headphone Mixer Right DAC Switch' on
amixer cset name='Left Headphone Mixer Left DAC Switch' on
amixer cset name='DAC Playback Volume' 999,999
amixer cset name='Headphone Mixer Volume' 999,999

**Comment by plbossart** [comment]
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.
