### ISSUE TITLE
Compressed streams should not be a mandatory config

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#346]
SOF should not depend on compressed streams by default, it should use them when they are available.

https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/Kconfig#L13

**Comment by cujomalainey** [comment]
@plbossart just wanted to follow up on our email chain and make sure it didn't get lost in the email noise

**Comment by plbossart** [comment]
@cujomalainey Sorry, I don't remember this thread. What is the impact of the 'select SND_SOC_COMPRESS'? Is this just to avoid a new SOF-specific variant in pineview.config? At the moment the code does nothing so it's probably removed by the linker?

**Comment by cujomalainey** [comment]
I'll send you an email to push it to the top, we just came to the conclusion that it should not be mandatory

**Comment by plbossart** [comment]
See https://github.com/thesofproject/linux/pull/378
