### ISSUE TITLE
[BUG] Suspend/resume test failed on CML and TGL chrome devices

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#3522]
**Describe the bug**
Recently, our CI detected the suspend/resume issue on 2 Chrome devices, One plaform is TGLU_VOLT_SDW and another one is CML_HEL_RT5682. There's no much logs available during the test, system failed to resume from suspending in the first round of testing. 
From the history of our CI testing, we determined this is a kernel regression.
Bisect result shows that this issue is caused by an acpi change from upstream rebase.
The bad commit is:
https://github.com/thesofproject/linux/commit/e38f9ff63e6d403f8e52302d223e3c5c110872ee

**To Reproduce**
$ rtcwake -m mem -s 5 

**Reproduction Rate**
100%

**Expected behavior**

**Environment**
1) kernel: tip sof-dev/d2937505b7b5
2) SOF: tip main/d792b0602dcf
3) Platform: TGL Chromebook Volteer and CML Helios

The DSDT table is attached:
[dsdt-dsl.txt](https://github.com/thesofproject/linux/files/8259495/dsdt-dsl.txt)

**Comment by marc-hb** [comment]
@plbossart can we revert https://github.com/thesofproject/linux/commit/e38f9ff63e6d403f8e52302d223e3c5c110872ee while we investigate this issue? This will allow us to catch other, unrelated suspend/resume issues, something we can't do right now on this platform.

**Comment by plbossart** [comment]
Yes, we can revert, but I was waiting to see an upstream commit for the revert. I'll add this manually and we can revert-reapply later.

**Comment by keqiaozhang** [comment]
https://github.com/thesofproject/linux/pull/3525 is merged, closing this issue.
