### ISSUE TITLE
[SoundWire] Kernel Oops on machine/codec driver remove

### ISSUE THREAD

**Issue by pablos-here** [thesofproject/linux#3531]
**Describe the bug**
I was attempting to configure the sound card on my _Dell XPS 9700_ as the mic was not working (speakers work).  This resulted in a kernel call trace which I submitted a bug against[1] against my distro.

I distilled the developer's test case so blame me for non-intuitive cruft.  There are two conditions which cause the _oops_ - see below.   

Just in case, I have captured separately the _call trace_ for each condition.

I'm also uploading [alsa-info.txt](https://github.com/thesofproject/linux/files/8319071/alsa-info.txt).

**Refernces**
1 - https://bugzilla.suse.com/show_bug.cgi?id=1197315

**Condition 1**
```
/sbin/modprobe -r snd_soc_sof_sdw
/sbin/modprobe -r snd_soc_rt711
```
**Condition 2**
```
# 
# Run me twice
# 
/sbin/modprobe -r snd_soc_sof_sdw
/sbin/modprobe -r snd_soc_rt1308_sdw
```
**Call trace per condition**
[condition-1.txt](https://github.com/thesofproject/linux/files/8319056/condition-1.txt)
[condition-2.txt](https://github.com/thesofproject/linux/files/8319059/condition-2.txt)

**Comment by plbossart** [comment]
@looney-loon Can you try and remove the parent PCI device first to see if this helps? this is what we do in our remove/insert tests. I am not sure if we've ever tested removing the machine driver this way.

````
/sbin/modprobe -r snd_sof_pci_intel_cnl
/sbin/modprobe -r snd_soc_sof_sdw
/sbin/modprobe -r snd_soc_rt711
/sbin/modprobe -r snd_soc_rt1308_sdw
```

**Comment by plbossart** [comment]
For reference, these are the scripts we use:

https://github.com/thesofproject/sof-test/blob/main/tools/kmod/sof_remove.sh
https://github.com/thesofproject/sof-test/blob/main/tools/kmod/sof_insert.sh

**Comment by plbossart** [comment]
I can reproduce the problem, see tentative fix at https://github.com/thesofproject/linux/pull/3534/commits/8274036a367c48128c5c0516872548abfcf5db27 PR https://github.com/thesofproject/linux/pull/3534

**Comment by pablos-here** [comment]
> Can you try and remove the parent PCI device first to see if this helps? this is what we do in our remove/insert tests. I am not sure if we've ever tested removing the machine driver this way.

```
/sbin/modprobe -r snd_sof_pci_intel_cnl
/sbin/modprobe -r snd_soc_sof_sdw
/sbin/modprobe -r snd_soc_rt711
/sbin/modprobe -r snd_soc_rt1308_sdw
```

Hi Pierre-Louis, 

I just tested the commands above and it works.  I'll update the SUSE bug.

Glad the issue netted something productive on your end. 

Let me know if you'd like me to close the issue or whether your workflow handles it.

Merci beaucoup!

**Comment by plbossart** [comment]
Fixed and changes shared upstream.
