### ISSUE TITLE
Mic not working, although speakers are ... speaking

### ISSUE THREAD

**Issue by pablos-here** [thesofproject/linux#3532]
Hi,
This is a place marker to potentially avoid new issues created until issue #3531 gets addressed.  It affects my _Dell XPS 9700_.

**Comment by plbossart** [comment]
please don't do this, create REAL issues with details, and certainly playing with modprobe is not going to make things better.

We've supported XPS 9700 for 2+ years now, please clarify what the problem is.

**Comment by pablos-here** [comment]
Hi Pierre-Louis,

Clearly the connection between the two issues was lost.  My bad.  I didn't mean my tongue-and-cheek message to insult anyone.

_Hitting the big old red reset button ... :) .... take two ..._ 

The problem is this _Dell XPS 9700_'s microphone does not capture any sounds.  The speakers work well.

The laptop is Linux-only.  I have set up pipewire for my user.

Before I converted it, I confirmed that the mic was working using this simple, [microphone testing website](https://www.onlinemictest.com/
).

Per the [debug suggestions](https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html
), here's the [alsa-info.txt](https://github.com/thesofproject/linux/files/8320654/alsa-info.txt).  Below are the results of other suggestions:

- Disabling SOF (`options snd-intel-dspcfg dsp_driver=1`) didn't help nor trying `options snd-intel-dspcfg dsp_driver=3`   
- As this is a Linux-only rig, I can't trying booting Windows first.
- In reviewing the Dell BIOS, I confirmed that the microphone and speakers are enabled.
- I confirmed `speaker-test` played white noise on the respective speaker.
- I confirmed that `arecord` **did not** record anything.
- I checked the `alsamixer` settings for the *Capture* device and each item has a value set to about the middle of the setting.

To rule out my user environment as being borked, I created a fresh, new Linux user.  I logged in (KDE) and tried the same microphone website test.  It didn't work.  To keep things simple, I didn't set up pipewire for this user.

I suspect that I'll need to enable one or all of the settings found in the **Enable dynamic debug** section.

Please advise on what other data is needed.

Thx a lot for your help!

**Comment by plbossart** [comment]
You need to use alsa-ucm-conf for all mixer settings, see https://github.com/alsa-project/alsa-ucm-conf
This should be packaged by your distro and settings applied by PipeWire.

If you want to try at the alsa hw:device level, you need to do something like

alsaucm -c sof-soundwire set _verb HiFi set _enadev Mic
arecord -Dhw:0,4 -c2 -r48000 -f S16_LE file.wav

**Comment by pablos-here** [comment]
Hi,

Thank you for the quick response.  Unfortunately after trying what was suggested, the mic is still not capturing anything.

When convenient, please advise on next steps.

Here's what I did:

**alsa-ucm-conf**

1. Downloaded the latest bits
2. I used `tar` to overlay `ucm/` and `ucm2` in `/usr/share/alsa`

To ensure a clean slate, I rebooted after the above.

**alsa test**

As instructed, I used the commands above for my unit test (as well as the **microphone testing website**).  I added `-d 3` to `arecord`.

**Comment by plbossart** [comment]
I don't have any real ideas to suggest @looney-loon. We've supported this device for a very long time and never had any reports of microphone issues.

Can you double check if the headset capture works?
Can you also check if there's no mic mute led button set (F4)?

**Comment by pablos-here** [comment]
Hi @plbossart,

Great idea.  I forgot about the jack and that I had tested it before.

I tested the jack and it works.

In my web searches, I have found many old posts about the microphone not working but they were related to older versions of the kernel and/or SOF.

I just had a thought .... I'm going to download a _Live CD_ of an older distribution and give that a shot.  Sometimes I miss the obvious.

I'll report back later ... merci beaucoup!  'preciate the help and patience thus far.

**Comment by plbossart** [comment]
I would recommend testing with Fedora 35, it's got the best support for SoundWire and UCM.

**Comment by pablos-here** [comment]
W00t!  Great information!

First, awesome tip to use _Fedora 35_.  Merci !

Mic + speakers worked with both GNOME and KDE.

The interesting thing is _Fedora 35_ is using several rev back versions of software.

For example, the kernel is 5.14.10 vs what I'm currently on (5.16.15).  

Just for grins, I checked the KDE version and it's quite old:  5.22.5 vs 5.24.3 (latest).

Back on point:  with your domain knowledge, do you have any suggestions on how we can find out the reason for the lack of functioning mic?

Let me know if you'd like me to close this issue out too.  

Thanks again for your help!

**Comment by plbossart** [comment]
I don't have a silver bullet here, this looks like a userspace and distro configuration issue where there are just tons of variables/dependencies.
Fedora35 has all the latest PipeWire/Wireplumber/UCM so that's probably where the issue is. I don't think the kernel matters, we've supported this device for 2 years now so 5.14 should be just fine.

**Comment by pablos-here** [comment]
The objects you listed is direction.  I appreciate it.  I'll circle back to my distro and find a subject matter expert.  I'm sure we can nail the issue.  

Thanks again and have a good one!

**Comment by tiwai** [comment]
Pierre, it's other way round -- the openSUSE Tumbleweed is a rolling distro, hence may have even much newer versions than Fedora (e.g. 5.16.x on openSUSE TW while 5.14.x on Fedora, etc).

So, although it's likely some missing configuration or weird combination, it's also possible that something got regressed in the recent versions, too.

In anyway, the best way to compare would be to take alsa-info.sh snapshot at the working state (mic recording on Fedora) against the broken state (mic recording on TW).  Also, you can compare the initial state right after alsaucm command invocation Pierre suggested in the above between two distros, too.

**Comment by plbossart** [comment]
Thanks @tiwai that's very interesting. Is this the moral equivalent of rawhide for Fedora?

**Comment by pablos-here** [comment]
Tumbleweed is indeed the functional equivalent (unsure of the morality angle here!  :D) of Rawhide.

@plbossart - would you like me to test with a _Live DVD_ of the latest Rawhide drop?  Or should I first do @tiwai test.

I'll reopen this issue.  :)

**Comment by pablos-here** [comment]
Hi,

If it's okay with everyone, let's keep things somewhat simple and not introduce Rawhide.  

I've collected some data between working and non-working environments for analysis.  Please let me know if additional data is required.

**Working**
[alsa-info.Fedora.txt](https://github.com/thesofproject/linux/files/8333097/alsa-info.Fedora.txt)

_Recording is low_
Now that I've tried to actually record something.  The recording is _extremely_ low.  I have a loud voice so it's not me.

The recording I made was done with the microphone set to 150% - see [Fed.wav](https://ufile.io/luy83fod).

**Not working**
[alsa-info.TW.txt](https://github.com/thesofproject/linux/files/8333101/alsa-info.TW.txt)

**Unit test**
As suggested by @tiwai, the following is snip of my parameterized tested script:
```
alsaucm -c sof-soundwire set _verb HiFi set _enadev Mic
arecord -Dhw:$MIC -c2 -r48000 -f S16_LE -d $DURATION file.wav
```

**Comment by plbossart** [comment]
I see significant differences in the rt715 controls, e.g.

TW:
Simple mixer control 'rt715 LINE1 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 2 [67%]
  Front Right: 2 [67%]
Simple mixer control 'rt715 LINE2 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 2 [67%]
  Front Right: 2 [67%]
Simple mixer control 'rt715 MIC1 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 2 [67%]
  Front Right: 2 [67%]
Simple mixer control 'rt715 MIC2 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 2 [67%]
  Front Right: 2 [67%]

Fedora
Simple mixer control 'rt715 LINE1 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 0 [0%]
  Front Right: 0 [0%]
Simple mixer control 'rt715 LINE2 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 0 [0%]
  Front Right: 0 [0%]
Simple mixer control 'rt715 MIC1 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 0 [0%]
  Front Right: 0 [0%]
Simple mixer control 'rt715 MIC2 Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 3
  Front Left: 0 [0%]
  Front Right: 0 [0%]

Alsa-utils has a different version as well, so I would really think the issue is really related to mixer values. It should be the same values that are applied, there's no reason why the setup should be different between the two distros.

**Comment by pablos-here** [comment]
Hi @plbossart ,

We have been conducting trials and your suspicions were correct:  it was an environmental issue.  A state file needed to be re-gen'd.  After which, the world rejoiced. 

Merci beaucoup for your help.  I very much appreciate it!!!

Have an excellent day.

**Comment by tiwai** [comment]
FWIW, some details are found in https://bugzilla.suse.com/show_bug.cgi?id=1197434

Though, I wonder whether it's rather some missing pieces in UCM profile.  That is, a mandatory path setup for the mic recording might be missing in rt715 codec, and it casually works with the default parameter for now.

**Comment by pablos-here** [comment]
I'm dedicated to contributing back in a testing capacity.  If there is _anything_ further I can do to gather data, please do not hesitate to ask.  Thx!

**Comment by pablos-here** [comment]
Hi,

Recently I tested my mic and found it not working again.  With @tiwai's help, tracked [here](https://bugzilla.suse.com/show_bug.cgi?id=1197434), I whittled down a reproducible test case.

The `alsa.cfg` file cited below and `alsa-info.txt` can be found in the **Additional information** below.

Thanks a lot for your help!

## Test case
1. **Prepare rig**
2. Confirm mic is working - [simple online user test](https://www.onlinemictest.com/).
3. **Store the driver state**
4. **Restore driver state**
5. Mic stops working

## Store the driver state
```bash
cat /proc/asound/cards
CARD=$(grep sofsoundwire /proc/asound/cards | awk '{print $1; exit}')
echo "Sussed sound card $CARD from above"

alsactl -f alsa.cfg store $CARD

ls -la alsa.cfg
```
## Restore driver state
```bash
# As root
cat /proc/asound/cards
CARD=$(awk '{print $1; exit}' /proc/asound/cards)
echo "Sussed sound card $CARD from above"

alsactl -d -f alsa.cfg restore $CARD
```
### Restore debug output
```
alsactl: set_controls:1499: device='hw:0', doit=0
alsactl: set_controls:1511: card-info-id: 'sofsoundwire'
alsactl: set_controls:1546: list count: 67
alsactl: set_controls:1574: maxnumid=67 maxnumid2=65
alsactl: set_controls:1579: more controls than maxnumid?
alsactl: set_controls:1587: result code: -11
alsactl: sysfs_init:45: sysfs_path='/sys'
alsactl: set_controls:1499: device='hw:0', doit=1
alsactl: set_controls:1511: card-info-id: 'sofsoundwire'
alsactl: set_controls:1587: result code: 0
```
## Prepare rig
```bash
# As root
cd /var/lib/alsa

# Nuke bits
rm -rf *

fuser -k /dev/snd/*
# Remove parent device
/sbin/modprobe -r snd_sof_pci_intel_cnl

mod=$(grep -m1 -E '^(snd[^ ]*|ac97_bus) [0-9]+ 0' /proc/modules)
while [ -n "$mod" ]; do
    mod=${mod%% *}
    /sbin/modprobe -r $mod
    mod=$(grep -m1 -E '^(snd[^ ]*|ac97_bus) [0-9]+ 0' /proc/modules)
done

# Should be empty
ls /var/lib/alsa

# confirm no cards listed
cat /proc/asound/cards

reboot
```
## Additional information
- [alsa.cfg](https://github.com/thesofproject/linux/files/8402814/alsa.cfg.txt)
- [alsa-info.txt](https://github.com/thesofproject/linux/files/8402816/alsa-info.txt)

**Comment by pablos-here** [comment]
Hi, 

Any thoughts on this issue?  Thanks a lot!

**Comment by pablos-here** [comment]
Hi again,
A later drop of openSUSE Tumbleweed has resolved the issue across multiple reboots.

Coma inducing details can be found in the downstream bug [1197434](https://bugzilla.suse.com/show_bug.cgi?id=1197434).
