### ISSUE TITLE
upstream: use devm_ routines and simplify error flow

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#354]
use devm_ioremap and pcim_

**Comment by bardliao** [comment]
@plbossart Do we also need to use devm_request_threaded_irq?

**Comment by plbossart** [comment]
On 12/4/18 12:50 AM, Bard Liao wrote:
> @plbossart <https://github.com/plbossart> Do we also need to use 
> devm_request_threaded_irq?

why not? Any reason not to do it?
