### ISSUE TITLE
[BUG] Crackling noise during login and jack headphones don't work on first connection

### ISSUE THREAD

**Issue by quintafeira** [thesofproject/linux#3590]
After boot, during login, I have a crackling noise from the speakers. When I connect the headphones, the same happen and the headphones are recognized, but if I play some audio, it outputs from speakers. To output audio from headphones, I have to follow these steps:
1. Connect headphones.
2. Play some audio (it will output from speakers) or change volume levels.
3. Connect headphones again.

Tried both the kernels 5.17.3 and 5.18rc2. Also tried sof-firmware v2.0 and v2.1.1. The result is always the same.

My sound card is an essx8336 (`00:0e.0 Multimedia audio controller: Intel Corporation Celeron/Pentium Silver Processor High Definition Audio (rev 06)`).

Here's the alsa-info:
[alsa-info.txt](https://github.com/thesofproject/linux/files/8495847/alsa-info.txt)

**Comment by plbossart** [comment]
@quintafeira this seems to be an ES8336 codec issue, the SOF firmware does not even know about the existence of speakers and doesn't deal with jack detection.

You would probably need to try with the UCM updates suggested in https://github.com/alsa-project/alsa-ucm-conf/pull/144 to have better settings.

**Comment by plbossart** [comment]
Recommended setup is described here: https://github.com/thesofproject/linux/issues/3336#issuecomment-1207200602

**Comment by plbossart** [comment]
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.
