### ISSUE TITLE
module reload cause PCM name error on UP^2 with sof-apl-pcm512x.tplg

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/linux#36]
System Environment:
sof-dev: 9b33dfacf8f0c9fffc22b1cdd5556faad31ed133 
sof:  20204a9cd7e4d89fc27008da7af3846c0c5b4015 
soft: 2abbfc0910ce9767d01462638d719309746844d1
using topology/sof-apl-pcm512x.tplg

reproduce steps:
rmmod sof_pci_dev 
rmmod snd_sof_nocodec
rmmod snd_sof_intel_byt 
rmmod snd_sof_intel_hda_common 
rmmod snd_sof 
modprobe sof_pci_dev
aplay -l  : 
**** List of PLAYBACK Hardware Devices ****
card 0: sofsofsofsofsof [sof-sof-sof-sof-sof-sof-sof-sof], device 0: Port5 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

log:
[dmesg.log](https://github.com/thesofproject/linux/files/2200756/dmesg.log)
[rmbox.log](https://github.com/thesofproject/linux/files/2200757/rmbox.log)
[rmbox-t.log](https://github.com/thesofproject/linux/files/2200758/rmbox-t.log)

**Comment by plbossart** [comment]
what is the name error? The prefix? If yes I believe this is handled in one of Liam's upstream patches, would need to be back-ported. will look into this.

**Comment by jocelyn-li** [comment]
@zhuqingliang Can you address Pierre's questions?

**Comment by zhuqingliang** [comment]
aplay -l :
**** List of PLAYBACK Hardware Devices ****
card 0: sofsofsofsofsof [sof-sof-sof-sof-sof-sof-sof-sof], device 0: Port5 (*) []

**Comment by plbossart** [comment]
can you retry this, this should be gone now that Liam's upstream patches are in topic/sof-dev.

**Comment by ZhendanYang** [comment]
Can't reproduce on latest code base.
kernel : sof-dev 64cf3e3
firmware : stable1.2 f883691
sof tool : d77beaf
