### ISSUE TITLE
Headphone Jack and Mic not working on GLK Chromebook

### ISSUE THREAD

**Issue by jthompson05** [thesofproject/linux#3612]
Hello. I've been here before to resolve the issue of no sound on my GLK chromebook. Now that is fixed, the only thing keeping my device from being fully functional under Linux is the lack of headphone jack and microphone support. I would like to know if there is anything I can do to fix the issue. 

Here is `alsa-info`: 
http://alsa-project.org/db/?f=d212af755856cf2cdd57b1f9f8e79786dd571cf6

**Comment by jthompson05** [comment]
@lgirdwood I saw you transferred this issue to github.com/thesofproject/linux. Is it a linux kernel issue and not an sof issue?

**Comment by plbossart** [comment]
@J0shuaT it's not even a kernel issue, it's an UCM issue. I tried to start an UCM support but I can't figure out how they are supposed to run any longer, see https://github.com/alsa-project/alsa-ucm-conf/pull/150

**Comment by jthompson05** [comment]
@plbossart MilkyDeveloper, https://github.com/MilkyDeveloper, has the ucm files from ChromeOS. I have no idea what to do with them but maybe you might: https://github.com/cb-linux/cb-ucm

**Comment by plbossart** [comment]
@J0shuaT I have those Chrome UCM but there's outdated and incompatible with alsa-lib upstream.

**Comment by jthompson05** [comment]
@plbossart Well I guess that won't work :(

**Comment by jthompson05** [comment]
@plbossart not sure if you already saw this, but someone on [reddit ](https://www.reddit.com/r/chrultrabook/comments/ui6ghn/workaround_for_glk_audio_sofglkda7219max/)found a way to get the mic and headphone jack working for GLK chromebooks. It works, but it requires pulseaudio. There is still a volume scaling issue unless I use an option called `Pro Audio` in Pulse Audio Volume control. `Pro Audio` requires pipewire. When `Pro Audio` is enabled, the headphone jack doesn't work anymore. Can you offer some advice?

**Comment by plbossart** [comment]
there's always all kinds of work-arounds, the 'right' way to fix this for good is to have UCM running. There was feedback from Jaroslav https://github.com/alsa-project/alsa-ucm-conf/pull/150#issuecomment-1122543956 that explained why my initial work didn't succeed, but I have limited cycles to sort this out. Once we have a UCM file up and running, we can fix parameters ad nauseam.

**Comment by jthompson05** [comment]
@plbossart I'm glad there's some progress on this issue. If you need me to test anything with the UCM, I'd be happy to do so.

**Comment by plbossart** [comment]
@J0shuaT please try https://github.com/alsa-project/alsa-ucm-conf/pull/150. It's not perfect but it's a start with UCM. Sorry it took so much time to find spare cycles to update this PR.

You want to clone/copy the entire ucm2 directory on /usr/share/alsa/ (keep your existing settings in a backup!).

**Comment by plbossart** [comment]
kernel and UCM files updated.

**Comment by jthompson05** [comment]
@plbossart Awesome. So now I have to wait for the linux kernel 5.20?

**Comment by plbossart** [comment]
> @plbossart Awesome. So now I have to wait for the linux kernel 5.20?

yes, unless the linux-stable team picks the changes and applies them to older versions (rather unlikely).

**Comment by jthompson05** [comment]
@plbossart Cool, I'll be waiting for 5.20. Do these changes allow the headphone jack to work OOTB?

**Comment by jthompson05** [comment]
@plbossart For the first time, everything is functional on my device under Linux! 
![image](https://user-images.githubusercontent.com/96457853/189804201-85160973-67c9-421d-8878-c3edc7d6abf7.png)
I still have some questions however. I used Kernel 6.0 from [here](https://kernel.ubuntu.com/~kernel-ppa/mainline/?C=N;O=D), and installed your UCM files. Interestingly audio didn't work right away. My device was able to detect the headphone jack when I plugged in headphones, but no sound came out. The sound only worked after running this [script](https://gist.github.com/unixabg/4ca86477b6ad0504d8b9486f1a160057) in addition to having the kernel and UCM. Do you know why that is? Have you gotten full sound to work on your GLK Chromebook on Linux 6.0?

**Comment by plbossart** [comment]
No idea @J0shuaT, it's likely that there are missing mixer values in the UCM file. 

I would be cautious with the script you mentioned, it makes no sense to reduce the PGA volumes. The PGA parts are meant for developers, but for actual devices all PGA volumes should be set to 0dB/100%.

You will have to find out what's missing and suggest a change to the UCM file for a turn-key experience.

**Comment by jthompson05** [comment]
@plbossart Thanks for the quick reply. I guess only lines 14-48 of the script are useful. So would I have to submit a pull request [here](https://github.com/alsa-project/alsa-ucm-conf)? I don't believe the UCM files for GLK Chromebooks are included by default in any linux distributions yet.

**Comment by plbossart** [comment]
Right, only some UCM changes were merged recently by @perexg for GLK

**Comment by jthompson05** [comment]
@plbossart I noticed that the audio can only be fully functional on a distro with PulseAusio installed. PulseAudio cannot be installed on Pop OS 22.04, so I can’t get fully functional audio on there. Have you experienced this as well?

**Comment by plbossart** [comment]
@J0shuaT you need PulseAudio or PipeWire mainly to parse the UCM files and apply the relevant settings when the desired sink/source changes. I have no idea what PopOS does, but it would need a similar solution to deal with endpoint-specific settings. Alternatively the settings can be used with alsaucm in a terminal, e.g. 
alsaucm -c bdw-rt5677  set _verb HiFi set _enadev Headphones

**Comment by jthompson05** [comment]
> alsaucm -c bdw-rt5677 set _verb HiFi set _enadev Headphones

Thanks for the tip. However when I run the command, I get this: 

```
root@pop-os:/usr/share/alsa/ucm2/Intel# alsaucm -c sof-glkda7219max set _verb HiFi set _enadev Headphones
ALSA lib parser.c:371:(evaluate_define_macro) DefineMacro is supported in v6+ syntax
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import sof-glkda7219max use case configuration -22
alsaucm: error failed to open sound card sof-glkda7219max: Invalid argument
```
I'm not sure what the issue is.

**Comment by plbossart** [comment]
@J0shuaT you need to have matching alsa-lib, alsa-utils and alsa-ucm-conf versions. If you have the latest of one and not the other things break.

**Comment by jthompson05** [comment]
> @J0shuaT you need to have matching alsa-lib, alsa-utils and alsa-ucm-conf versions. If you have the latest of one and not the other things break.

Thanks for your help. I'll check the versions now.

**Comment by jthompson05** [comment]
I gave up and stuck to Ubuntu 😅
