### ISSUE TITLE
[BUG] [ADL]: Sporadically Audio drivers are missing in Platform warm/cold boot cycling tests

### ISSUE THREAD

**Issue by jairaj-arava** [thesofproject/linux#3621]
What steps will reproduce the problem?
1.Boot the chromebook.
2. Copy the test scripts and start the cold/warm boot test without external device attached (NDA).

What is the expected output?
Test should complete for the given iterations without any issues.

What do you see instead?
Audio drivers are missing in Platform Cycling Tests and sound card is not listed.

Rate of issue repro: 1/1000 cycles.
[dmesg.txt](https://github.com/thesofproject/linux/files/8584951/dmesg.txt)

**Comment by jairaj-arava** [comment]
@sathya-nujella @sathyap-chrome @Vamshigopal @kv2019i

**Comment by plbossart** [comment]
@jairaj-arava I don't understand what "audio drivers are missing' means? The audio drivers are modules and they will probe based on ACPI and PCI IDs. 

The PCI ID is shown in your results
````
2022-04-12T00:52:46,455914+05:30 pci 0000:00:1f.3: [8086:51c8] type 00 class 0x040100

sound/soc/sof/intel/pci-tgl.c:  { PCI_DEVICE(0x8086, 0x51c8), /* ADL-P */
````

**Comment by ranj063** [comment]
@plbossart i think he means to say that the audio driver fails to probe

**Comment by jairaj-arava** [comment]
@plbossart , yes the audio driver probe is not happening. Listed below the modules from working and issue observed boards.

**List of modules loaded in normal scenario**
snd_soc_sof_rt5682     28672  0
snd_soc_hdac_hdmi      32768  1 snd_soc_sof_rt5682
snd_soc_intel_hda_dsp_common    16384  1 snd_soc_sof_rt5682
snd_soc_intel_sof_maxim_common    16384  1 snd_soc_sof_rt5682
snd_soc_rt5682         77824  1 snd_soc_sof_rt5682
snd_soc_rl6231         16384  1 snd_soc_rt5682
uinput                 20480  1
xt_cgroup              16384  2
snd_soc_dmic           16384  1
snd_hda_codec_hdmi     53248  1
intel_ipu6_psys        61440  0
iio_trig_hrtimer       16384  2
snd_sof_pci_intel_tgl    16384  0
snd_sof_intel_hda_common    65536  1 snd_sof_pci_intel_tgl
snd_soc_hdac_hda       20480  1 snd_sof_intel_hda_common
snd_sof_intel_hda      16384  1 snd_sof_intel_hda_common
soundwire_intel        28672  1 snd_sof_intel_hda_common
soundwire_generic_allocation    16384  1 soundwire_intel
soundwire_cadence      24576  1 soundwire_intel
snd_sof_xtensa_dsp     16384  1 snd_sof_intel_hda_common
snd_soc_acpi_intel_match    49152  2 snd_sof_intel_hda_common,snd_sof_pci_intel_tgl
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_sof_intel_hda_common
snd_hda_ext_core       24576  4 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda
soundwire_bus          61440  3 soundwire_intel,soundwire_generic_allocation,soundwire_cadence

**List of modules loaded when issue is seen:**
snd_sof_xtensa_dsp     16384  0
snd_soc_acpi_intel_match    49152  0
snd_soc_acpi           16384  1 snd_soc_acpi_intel_match
snd_hda_ext_core       24576  0
soundwire_bus          61440  0
snd_intel_dspcfg       24576  0
snd_intel_sdw_acpi     16384  1 snd_intel_dspcfg
snd_hda_codec         110592  0
snd_hwdep              16384  1 snd_hda_codec
snd_hda_core           69632  2 snd_hda_ext_core,snd_hda_codec

**Comment by plbossart** [comment]
@jairaj-arava module loaded and probe are different things.
You have to first look if the PCI driver probed, as seen with lspci, then that the probe completed with the dmesg log 

sof-audio-pci-intel-tgl 0000:00:1f.3: Completing SOF PCI probe

and last if there is a card created or not.

**Comment by jairaj-arava** [comment]
@plbossart , we don't see the pci driver probe happening in the logs. Also we could see DSP address is 0 too as shown below.
00:1f.3 Multimedia audio controller: Intel Corporation Device 51c8 (rev 01)
        DeviceName: Multimedia audio controller
Address: 0000000000000000  Data: 0000

**Comment by plbossart** [comment]
@jairaj-arava thanks for the precision. I don't think it's a SOF driver issue if the PCI probe doesn't even happen, likely something wrong with Coreboot, PCI configs, etc.

**Comment by plbossart** [comment]
@jairaj-arava No information provided in two months, is this still relevant or can we close?

**Comment by jairaj-arava** [comment]
As per the latest status from validation team issue is not observed in the recent images. Closing it for now, if issue happens again will re-open. Thanks.
