### ISSUE TITLE
[ipc4] some memory managment issues in ipc4-topology.c

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#3670]
There are some bugs in the memory management in the ipc4-topology.c.

For example, in sof_ipc4_widget_setup_pcm(), it will call sof_ipc4_get_audio_fmt() to allocate ipc4_copier->available_fmt->base_config and ipc4_copier->available_fmt->out_audio_fmt if has_out_format is true. But in the error handling, this function will never kfree ipc4_copier->available_fmt->base_config and ipc4_copier->available_fmt->out_audio_fmt.
sof_ipc4_widget_setup_comp_dai() has the same issue.

Another example is, snd_soc_dapm_pga uses sof_ipc4_widget_free_comp() as ipc_free() to free the memory. In the sof_ipc4_get_audio_fmt(), it will call sof_ipc4_get_audio_fmt() to allocate ipc4_copier->available_fmt->base_config and ipc4_copier->available_fmt->out_audio_fmt if has_out_format is true. But in the error handling and sof_ipc4_widget_free_comp(), it will never kfree the allocated base_config and out_audio_fmt. 
snd_soc_dapm_mixer has the same issue.

And if ipc_setup() of the widget, for example sof_ipc4_widget_setup_comp_dai(), fails, it will kfree the memory. However, ipc_free() will be called later, which will try to free them again as we didn't set the memory pointer to NULL in the error handling.

I'm wondering why we don't use devm_xxx to manage the memory. I checked the audio initialization and playback/capture flow roughly yesterday and It seems safe to me to use devm_xxx. Is there any side effect or other flows that will cause devm_xxx unsafe?

**Comment by plbossart** [comment]
you have to be very careful @libinyang when using devm_ for things that are allocated during the topology instantiation. This happens when the card machine driver is probed, so the memory has to be released when the card driver is removed. It's very easy to confuse the PCI device and the platform device.

**Comment by libinyang** [comment]
@plbossart Thanks for the comments. I have submitted the PR https://github.com/thesofproject/linux/pull/3674 to fix this issue. I did some check in the code last week and it seems safe to use devm_xxx. But I'm not 100% confident to use devm_xxx... So in this PR, I didn't use devm_xxx.

**Comment by plbossart** [comment]
Fixed by #3674
