### ISSUE TITLE
[BUG] Lenovo Yoga 9 14IAP7 - no sound from bass speakers

### ISSUE THREAD

**Issue by pjungkamp** [thesofproject/linux#3699]
# Description

The Yoga 9i 14" (2022) has a speakerbar above the keybaord and a bass speaker to the front left and right side of the chassis.
The bass speakers work under Windows 10/11, but not under Linux.
The speakerbar seems to be working fine.

# Why I am filing here

I searched for similar issue and found this Ubuntu Bug: https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1926165
As I was comparing the `alsa-info` files, I noticed that I don't have 'Bass Speaker Playback Switch' named control and no DAC1/2 controls listed.
Should these controls exist for this device?
Does this need a fixup in the kernel?

# Attachments

[dmesg.txt](https://github.com/thesofproject/linux/files/8909623/dmesg.txt)
[alsa-info.txt](http://alsa-project.org/db/?f=88c18fe2a7e900cc9a1aef2b62d5a963460b7d74)

**Comment by plbossart** [comment]
@PJungkamp the SOF driver and firmware know nothing about codec-level processing.

You would need to look at the suggestions in https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html to see if you have the same issue with the legacy HDaudio driver - without using SOF and the DSP.

It's likely that the issue is that the amplifiers for the bass speakers are connected to the HDaudio codec and not enabled by default. This seems to be a classic problem on Lenovo platforms, the only solution is to snoop HDaudio commands in Windows and try to reverse engineer what causes those amplifiers to be on.

see https://github.com/thesofproject/linux/issues/3699 and https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver

**Comment by pjungkamp** [comment]
Thanks for the fast response!

I already dumped the HDA verbs last weekend. [clean-verbs.txt](https://github.com/thesofproject/linux/files/8911188/clean-verbs.txt)

I also tried using the `snd-hda-intel` driver, even before I read the note on intel debugging suggestions.
But both drivers did not make a change, even with applied HDA verbs.

I also tried to apply various changes to the pin-mapping using `snd-hda-intel` with a `hdajackretask` patch file.
I also tried to mimic the 'Pin Complex' Mappings from the Lenovo Yoga 9 14ITL5 since it's a predecessor of my device with ALC287 and bass speakers.

See the DAC1/2 and Bass Speaker nodes in the [`alsa-input.txt`](https://launchpadlibrarian.net/535604803/AlsaInfo.txt) of the [thread](https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1926165) mentioned above.

What bothers me is that I can't seem to get the nodes `0x01` and `0x02` to show controls.
Changing the pin `0x17` init pin config is possible but I did not get any sound nonetheless. 

I don't really know how the HDA codec works, how the kernel decides on and exposes controls, where the controls are labeled and how alsa connects the the controls to profiles.

What I know is only from reading some docs and a lot of forums and code during the last week.
I'd like to know whether this Issue *could* be related to this repo and if this question/issue is directed to the right people.

# Comparison of the `alsa-info.txt` HDA codec information

## Lenovo Yoga 9 14ITL5
```
[...]
Node 0x02 [Audio Output] wcaps 0x41d: Stereo Amp-Out
  Control: name="DAC2 Playback Volume", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x57, nsteps=0x57, stepsize=0x02, mute=0
  Amp-Out vals:  [0x3a 0x3a]
  Converter: stream=1, channel=0
  PCM:
    rates [0x40]: 48000
    bits [0xe]: 16 20 24
    formats [0x1]: PCM
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
Node 0x03 [Audio Output] wcaps 0x41d: Stereo Amp-Out
  Control: name="DAC1 Playback Volume", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x57, nsteps=0x57, stepsize=0x02, mute=0
  Amp-Out vals:  [0x3a 0x3a]
  Converter: stream=1, channel=0
  PCM:
    rates [0x40]: 48000
    bits [0xe]: 16 20 24
    formats [0x1]: PCM
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
[...]
Node 0x14 [Pin Complex] wcaps 0x40058d: Stereo Amp-Out
  Control: name="Bass Speaker Playback Switch", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]
  Pincap 0x00010014: OUT EAPD Detect
  EAPD 0x2: EAPD
  Pin Default 0x90170111: [Fixed] Speaker at Int N/A
    Conn = Analog, Color = Unknown
    DefAssociation = 0x1, Sequence = 0x1
    Misc = NO_PRESENCE
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=00, enabled=0
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
  Connection: 1
     0x02
[...]
Node 0x17 [Pin Complex] wcaps 0x40058d: Stereo Amp-Out
  Control: name="Speaker Playback Switch", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]
  Pincap 0x0000001c: OUT HP Detect
  Pin Default 0x90170110: [Fixed] Speaker at Int N/A
    Conn = Analog, Color = Unknown
    DefAssociation = 0x1, Sequence = 0x0
    Misc = NO_PRESENCE
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=00, enabled=0
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
  Connection: 4
     0x02 0x03* 0x06 0x08
  In-driver Connection: 2
     0x02 0x03
[...]
```

## My Lenovo Yoga 9 14IAP7
```
[...]
Node 0x02 [Audio Output] wcaps 0x41d: Stereo Amp-Out
  Control: name="Speaker Playback Volume", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x57, nsteps=0x57, stepsize=0x02, mute=0
  Amp-Out vals:  [0x57 0x57]
  Converter: stream=1, channel=0
  PCM:
    rates [0x40]: 48000
    bits [0xe]: 16 20 24
    formats [0x1]: PCM
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
Node 0x03 [Audio Output] wcaps 0x41d: Stereo Amp-Out
  Control: name="Headphone Playback Volume", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x57, nsteps=0x57, stepsize=0x02, mute=0
  Amp-Out vals:  [0x36 0x36]
  Converter: stream=1, channel=0
  PCM:
    rates [0x40]: 48000
    bits [0xe]: 16 20 24
    formats [0x1]: PCM
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
[...]
Node 0x14 [Pin Complex] wcaps 0x40058d: Stereo Amp-Out
  Control: name="Speaker Playback Switch", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]
  Pincap 0x00010014: OUT EAPD Detect
  EAPD 0x2: EAPD
  Pin Default 0x90170120: [Fixed] Speaker at Int N/A
    Conn = Analog, Color = Unknown
    DefAssociation = 0x2, Sequence = 0x0
    Misc = NO_PRESENCE
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=00, enabled=0
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
  Connection: 1
     0x02
[...]
Node 0x17 [Pin Complex] wcaps 0x40058d: Stereo Amp-Out
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x80 0x80]
  Pincap 0x0000001c: OUT HP Detect
  Pin Default 0x411111f0: [N/A] Speaker at Ext Rear
    Conn = 1/8, Color = Black
    DefAssociation = 0xf, Sequence = 0x0
    Misc = NO_PRESENCE
  Pin-ctls: 0x00:
  Unsolicited: tag=00, enabled=0
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
  Connection: 4
     0x02* 0x03 0x06 0x08
[...]
```

**Comment by plbossart** [comment]
@PJungkamp I am afraid very few people on the SOF GitHub are familiar with the gory details of HDaudio pin configuration and retasking. I would include @tiwai and possibly move the question to the kernel bugzilla where such issues are typically logged.

(product: Drivers, Component Sound(ALSA))

**Comment by pjungkamp** [comment]
Thanks, I'll file a bug on mainline then. Or add my device on https://bugzilla.kernel.org/show_bug.cgi?id=208555 which I just discovered.
