### ISSUE TITLE
Problems on Dell XPS 17 9720

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [thesofproject/linux#3716]
Hi there! I am having some problems on my new Dell XPS 17 9720 with Intel i9-12900HK. 
My microphone does not work properly. It is detected but there is a weird sound. The speakers are good.

The output of `lspci | grep Audio`:
```bash
00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
01:00.1 Audio device: NVIDIA Corporation Device 228e (rev a1)
```

I checked `pavucontrol` and indeed detected the microphone. The name of the device displayed is Alder Lake PCH-P High Definition Audio Controller SoundWire microphones

The device is not completely silent. I tried to run arecorder and it turns out that the microphones gave me a white noise. Please help me if possible.

**Comment by eighthave** [comment]
I'm having all sorts of audio issues on a XPS 17 9720.  Did you find a solution?

**Comment by Gorgeous-Patrick** [comment]
I am not sure how to fix this actually. However, I have switched to ArchLinux and it turns out that it works automatically on ArchLinux. IDK why

**Comment by eighthave** [comment]
Could you tell me which Linux kernel version you're using?  Also, which version 
of the "sof" firmware?

**Comment by Gorgeous-Patrick** [comment]
This is my Linux version: 
Linux patrickli 6.1.15-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 03 Mar 2023 12:22:08 +0000 x86_64 GNU/Linux

and sof-firmware 2.2.5-1
