### ISSUE TITLE
[BUG] No sound below 100Hz in XPS 15

### ISSUE THREAD

**Issue by gimait** [thesofproject/linux#3729]
**Describe the bug**
The integrated speakers in my laptop do not output any frequencies below roughly 100Hz.
I have had this issue since I got the computer, several months ago, and tried to find a solution, asking for help [here](https://bugzilla.kernel.org/show_bug.cgi?id=215233) and [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2162), without much success so far.
I have tried out verbs sniffed from Windows, playing with HDAJackRetask and all I could find or think of, and I am hoping that someone here can have some idea I can try out.
One last thing I have noticed is that I am able to reproduce the issue in Windows when the laptop is running out of battery, so I could imagine that there is some power setting that is preventing all the audio from playing in the speakers.

**To Reproduce**
Run this command:
`speaker-test -c2 -D hw:PCH -t sine -f 100`

**Reproduction Rate**
All the time

**Expected behavior**
I would expect to hear something, but no luck

**Impact**
It's quite annoying, it would be great to be able to hear music properly on this laptop.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.17.15-1-MANJARO
    * SOF: 2.1.1.a-1
2) Name of the topology file
    * Topology: (I don't know how to check, help? :))
3) Name of the platform(s) on which the bug is observed.
    * Platform: Dell XPS 15 9510 (I believe it might affect the 9520 as well, I saw a reddit user complaining about the quality difference with Windows)

**Screenshots or console output**
Please let me know if there is something I can provide. I am not even sure wether sof supports my hardware, or how to set it up (I have it installed but seems like I keep using snd_hda?):

Running `sudo dmesg | grep 'snd\|soc\|sof'` gives me this:

```
[    0.560740] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.560741] software IO TLB: mapped [mem 0x0000000051091000-0x0000000055091000] (64MB)
[    0.656372] Initializing XFRM netlink socket
[    1.231085] systemd[1]: Listening on LVM2 poll daemon socket.
[    1.464247] Bluetooth: HCI socket layer initialized
[    1.464249] Bluetooth: L2CAP socket layer initialized
[    1.464250] Bluetooth: SCO socket layer initialized
[    2.219133] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[    2.219223] snd_hda_intel 0000:00:1f.3: enabling device (0000 -> 0002)
[    2.219469] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    2.324761] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC289: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[    2.324764] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    2.324765] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[    2.324767] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
[    2.324768] snd_hda_codec_realtek hdaudioC0D0:    inputs:
[    2.324769] snd_hda_codec_realtek hdaudioC0D0:      Headset Mic=0x19
[    2.324771] snd_hda_codec_realtek hdaudioC0D0:      Headphone Mic=0x1b
[    2.324772] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x12
[    2.992532] Bluetooth: BNEP socket layer initialized
[    7.132605] wlp0s20f3: associate with 10:da:43:f3:58:c0 (try 1/3)
[    7.134202] wlp0s20f3: RX AssocResp from 10:da:43:f3:58:c0 (capab=0x1011 status=0 aid=4)
[    7.140980] wlp0s20f3: associated
[   13.218728] Bluetooth: RFCOMM socket layer initialized
```

**Comment by lgirdwood** [comment]
@singalsu @plbossart could we be missing verbs for DSM or another smart amp here ?

**Comment by plbossart** [comment]
It's quite possible indeed that this platform relies on speaker-protection and enhancements on the Intel DSP. We know that some platforms enable such processing for Windows but it's not enabled for Linux - mostly due to the issue of 3rd party IP releases.

But before we go there, we'd need to check if this problem also happens with the HDaudio legacy driver.

@gimait can you add this in /etc/modprobe.d/alsa-base.conf

options snd-intel-dspcfg dsp_driver=1

reboot and check the sound quality.

**Comment by gimait** [comment]
@plbossart I didn't have an `alsa-base.conf` file, so I created one, added the option you suggested and rebooted.
The result is the same, low frequencies are still not being played.

Let me know anything else I can do to help.

(and btw, thanks to both for the very quick reply!)

**Comment by plbossart** [comment]
@gimait ok so definitively a codec configuration issue, or a missing component on the DSP.

@shumingfan can you please help check if Realtek did any special tricks to enable low-frequencies in Windows on this Dell XPS 9510 device?

**Comment by shumingfan** [comment]
@gimait I post the messages from our HDA SW engineer. He wants to check some info. from alsa-info.
"sudo su root" type password  to enter root
"echo 1 > /sys/module/snd_hda_codec/parameters/dump_coef "
"alsa-info --no-upload"
Please share the tmp/alsa-info.txt.xxxx to us.

**Comment by gimait** [comment]
Here it is, please let me know if I can provide any other information.

[alsa-info.txt](https://github.com/thesofproject/linux/files/9051331/alsa-info.txt)

**Comment by plbossart** [comment]
it's my understanding that this is a 'feature'. the HDaudio codec enables a high-pass filter with the corner frequency at 250Hz to protect the speakers on this specific model, so it's unlikely that the bass content will be played with the desired level.

**Comment by gimait** [comment]
Is it possible to change this filter, maybe fine-tune it to fit better the capabilities of the speakers? If you can point me in the right direction I'd be happy to test some things and see if I can come up with a safe, but less conservative setting.

**Comment by plbossart** [comment]
@gimait that would mean a very high likelihood of blowing your speakers.... all standard disclaimers apply. You are free to alter the verbs sent to tbe HDaudio speakers, but that's at your own risk.

**Comment by gimait** [comment]
@plbossart If I understand you correctly, the HDaudio verbs sent to the speakers on Linux differ from those on Windows on this device, and this causes the issue I'm experiencing, is this correct? Is this filter specific for the xps 15 model, or a general rule for other devices as well?

I understand the risks of playing the volume of the speakers, I would not dare try if it wasn't because there is such a big difference between both OS...

**Comment by plbossart** [comment]
No, the verbs are set in the BIOS and should be common for Windows and Linux. If you see a difference between the two OSes, there's something else at play.

**Comment by gimait** [comment]
I'm relieved that the issue might be elsewhere, hopefully, it's something safer I can test out. Do you have any other ideas about where could the problem be? 

I can hear the difference between OSes, and reproduce the issue every time: audio is great on Windows (except for some rare occasions when the laptop is about to run out of battery), but lower frequencies are gone when running Linux. That makes me believe there is some missing setting or misconfiguration.

Feel free to task me with any tests I can do to figure this out. I'd be happy to dig a bit into the code myself if that can be helpful (is there any documentation I can follow to get started on this part of the firmware, btw? I've tried to read the alsa docs and look around the kernel to try to understand how the drivers work, but it was a bit too much for me to handle).

**Comment by gimait** [comment]
Hi @plbossart and @shumingfan, 
Do you have any updates on this issue or is there something I can do to move it forward? 
Thank you for your help!

**Comment by plbossart** [comment]
@gimait I don't think it's wise to try and circumvent a protection added by the OEM to protect the speakers.

**Comment by gimait** [comment]
@plbossart I am sorry to insist, but I think I need a more clear answer.

Do you mean that the issue I'm experiencing is indeed a high pass filter set by the OEM?
This would be worrisome, since the issue, as I mentioned, happens only on Linux. I'm sure the OEM did not set up a filter that clearly mutes a wide range of the audible spectrum on purpose. And if they did, I am inclined to think that the reason is not protecting the speakers (because then the speakers would be in danger of blowing every time I boot on Windows..).

Can you point me to any material on the architecture of the audio firmware anyway? I'm keen to learn how audio works on my machine. Or if this doesn't exist, where is this filter defined in the code, so I have a place to start looking?

**Comment by plbossart** [comment]
@gimait the information on speaker protection came from Realtek, this was added at the request of the OEM.

This is not an SOF issue proper but a debate on amplifier configuration, closing this issue since there's nothing we can do for you. If you feel this is still a problem, you may want to file an issue on the kernel bugzilla. Thanks for your understanding.
