### ISSUE TITLE
MTL has a kernel RIP on build_sched_domains

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#3784]
Will track this issue internally.

**Comment by ricardon** [comment]
This seems to be an issue on how the topology of the system is being reported to the scheduler.  Our initial suspects were cluster scheduling (CONFIG_SCHED_CLUSTER) and the missing hybrid feature bit (X86_FEATURE_HYBRID_CPU) in CPUD.

The backtrace indicates that x86_cluster_flags() may have been called, indicating that CONFIG_SCHED_CLUSTER is selected in the kernel configuration. There is a runtime check to not use cluster scheduling on hybrid processors such as Meteorlake.  Hence, CONFIG_SCHED_CLUSTER should not be a problem.  @fredoh9 verified that the feature bit X86_FEATURES_HYBRID_CPU is present.

More investigation is needed. There may be an impact on how the scheduler balances load.

This warning does not prevent the system from functioning. If users are not interested on performance measurements, this issue may be treated as low priority for now.
