### ISSUE TITLE
SOF built-in mode doesn't work

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#38]
SOF built-in mode doesn't work now. Audio driver initialization will fail and no PCM is created.

**Comment by plbossart** [comment]
if you don't share the kernel sha1, a dmesg log and the .config you used I'll close this issue. Seriously, please share more information than "it does not work".

**Comment by jocelyn-li** [comment]
@libinyang please share more information.

**Comment by libinyang** [comment]
Hi Pierre,

Confirmed with QA, and it seems this is a feature we don't support now. It is not a bug. I think you closed it now.
Sorry for the inconvenience.

**Comment by jocelyn-li** [comment]
@RanderWang please test to see if it is working.

**Comment by RanderWang** [comment]
normally, SOF is built as a snd-sof.ko and dynamic loaded by kernel.
For built-in mode,  sof is built into kernel image named vmlinux.
You can make It when making menuconfig.

**Comment by RanderWang** [comment]
I reproduce it with BDW on Ubuntu 18.04. loading firmware intel/sof-bdw.ri failed.  The FW is loaded
before file system is ready, so it is failed. According to Xiuli, The better way it is to make FW built in kernel image  when SOF is in built-in mode

**Comment by keyonjie** [comment]
this is known issue, I believe cAVS with the same situation?

**Comment by mengdonglin** [comment]
Close this issue as an enhancement #139
