### ISSUE TITLE
[BUG] Microphone not detected ES8336

### ISSUE THREAD

**Issue by junocomp** [thesofproject/linux#3800]
I have a tablet with ES8336 (kernel enabled) and the speakers are now working thanks to this

https://github.com/thesofproject/sof/issues/6068#issuecomment-1205008960

Currently the Microphone is not detected. I can provide any info needed.

**Comment by plbossart** [comment]
If the microphone is not detected, it could be that the codec has incorrectly detected a headset. Try to plug a headset to see if this changes the behavior.

You should attach the results of 'alsa-info' and paste the values of all the controls with 'Jack' in their name.

**Comment by junocomp** [comment]
@plbossart 

https://justpaste.it/9s5zh

I have attached the alsa-info

I plugged a headphone jack, though it works the mic is still not detected. I am on debian, do you know which codec I may require?

**Comment by plbossart** [comment]
Not following what you are trying to say @junocomp, 'it works' is really hard to understand

did you mean
a) the jack is detected (as measured by what?)
b) the recording on the headset mic gives good results
c) the recording from the local mic gives no data (or noise?)

You are on 5.18.14, so there's no way this can work. You will need 5.19 plus the fix in https://github.com/thesofproject/linux/pull/3798

**Comment by junocomp** [comment]
I have just upgraded to 5.19 and I am having the same issue.

Speakers work but still no microphone.

The only things that work so far are the speakers and sound through headphone jack. 

I tried testing the headphone microphone using this website https://mictests.com/ and it does not work

**Comment by plbossart** [comment]
Recommended setup is described here: https://github.com/thesofproject/linux/issues/3336#issuecomment-1207200602

**Comment by plbossart** [comment]
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.

**Comment by katyo** [comment]
@plbossart I followed the instructions above.
Now sound works on Teclast F5, but integrated microphone still does not detected.

**Comment by plbossart** [comment]
@keyo can you try to check the status of the 'Jack' controls when you insert a headset?
````
amixer -Dhw:0 controls | grep Jack
amixer -Dhw:0 cget numid=<value found above>
````

**Comment by katyo** [comment]
@plbossart,

```
$ amixer -Dhw:0 controls | grep Jack
numid=33,iface=CARD,name='HDMI/DP,pcm=5 Jack'
numid=39,iface=CARD,name='HDMI/DP,pcm=6 Jack'
numid=45,iface=CARD,name='HDMI/DP,pcm=7 Jack'
numid=27,iface=CARD,name='Headphone Jack'
numid=28,iface=CARD,name='Headset Mic Jack'
```

Without headset:
```
$ amixer -Dhw:0 cget numid=27
numid=27,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off

$ amixer -Dhw:0 cget numid=28
numid=28,iface=CARD,name='Headset Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
```

With headset:
```
$ amixer -Dhw:0 cget numid=27
numid=27,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on

$ amixer -Dhw:0 cget numid=28
numid=28,iface=CARD,name='Headset Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```

```
$ dmesg | grep sof
[    0.575648] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.575651] software IO TLB: mapped [mem 0x000000006cfee000-0x0000000070fee000] (64MB)
[    1.110494] xor: measuring software checksum speed
[    5.697760] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    5.698062] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    5.698219] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    5.726158] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    5.764594] sof-audio-pci-intel-apl 0000:00:0e.0: NHLT_DEVICE_I2S detected, ssp_mask 0x5
[    5.764605] sof-audio-pci-intel-apl 0000:00:0e.0: Overriding topology with MCLK mask 0x2 from NHLT
[    5.764609] sof-audio-pci-intel-apl 0000:00:0e.0: hda codecs found, mask 4
[    5.789066] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:2:0-57864
[    5.789076] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:22:1 Kernel ABI 3:21:0
[    5.789080] sof-audio-pci-intel-apl 0000:00:0e.0: FW ABI is more recent than kernel
[    5.789093] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[    5.829280] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:2:0-57864
[    5.829290] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:22:1 Kernel ABI 3:21:0
[    5.829294] sof-audio-pci-intel-apl 0000:00:0e.0: FW ABI is more recent than kernel
[    5.841555] sof-essx8336 sof-essx8336: quirk mask 0x2
[    5.841565] sof-essx8336 sof-essx8336: quirk SSP2
[    5.844359] sof-audio-pci-intel-apl 0000:00:0e.0: Topology: ABI 3:23:0 Kernel ABI 3:21:0
[    5.844368] sof-audio-pci-intel-apl 0000:00:0e.0: warn: topology ABI is more recent than kernel
[    5.844625] sof-essx8336 sof-essx8336: ASoC: Parent card not yet available, widget card binding deferred
[    6.008971] input: sof-essx8336 Headset as /devices/pci0000:00/0000:00:0e.0/sof-essx8336/sound/card0/input9
[    6.009073] input: sof-essx8336 HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:0e.0/sof-essx8336/sound/card0/input10
[    6.009152] input: sof-essx8336 HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:0e.0/sof-essx8336/sound/card0/input11
[    6.009233] input: sof-essx8336 HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:0e.0/sof-essx8336/sound/card0/input12
```

**Comment by plbossart** [comment]
@katyo the results show the headphone/headset are detected by the codec, that's good news.
If you don't get sound captured when nothing is detected, then it's likely that you have wrong settings for the alsa mixers. 

Try to use the UCM file that was contributed by @yangxiaohua2009 in https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/Intel/sof-essx8336/sof-essx8336.conf or ask for support directly, I don't have any knowledge here.

**Comment by junocomp** [comment]
@plbossart I have the latest  alsa-ucm-conf=1.2.7.2-1 which has this file on Debian Sid. But for some reason is not picking up.

Is there a way to execute the dmic commands manually? 

Currently I have to execute the alsa commands manually as well, this is my current file.

https://textuploader.com/ttrhb

**Comment by junocomp** [comment]
I should have probably mentioned from the begining, my chip name is `Intel Jasperlake HDMI`

**Comment by plbossart** [comment]
You need to enable dynamic debug and check if you see any signs of the PCH-attached DMIC being enabled in the NHLT table. If not the microphones are attached to the ES8336 and not the Intel chipset, and it's a codec configuration issue (also GPIO possibly).

**Comment by junocomp** [comment]
I have dyndbg enabled from https://github.com/thesofproject/linux/issues/3827#issuecomment-1219687409

This is what I get

```
$ sudo dmesg | grep dmic
[    5.923127] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-icl 0000:00:1f.3: dmic number 0 max_ch 0
```

```
$ sudo dmesg | grep PCH
[    0.290774] acpi PNP0A08:00: _OSC: OS now controls [PCIeHotplug SHPCHotplug PME AER PCIeCapability LTR]
[    4.847265] iTCO_wdt iTCO_wdt: Found a Intel PCH TCO device (Version=6, TCOBASE=0x0400)
```

```
$ sudo dmesg | grep pch
[    1.035676] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
```

**Comment by junocomp** [comment]
I disabled dynamic dbg

I get this now

```
[    6.344520] sof-audio-pci-intel-icl 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    6.346076] sof-essx8336 sof-essx8336: ASoC: Parent card not yet available, widget card binding deferred
[    6.359629] NET: Registered PF_QIPCRTR protocol family
[    6.365839] es8316 i2c-ESSX8336:00: assuming static mclk
[    6.456842] sof-essx8336 sof-essx8336: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
[    6.456860] sof-essx8336 sof-essx8336: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 4
```

**Comment by katyo** [comment]
Built-in microphone worked fine (on Teclast F5) with #3107.
Currently it does not detected at all.
Also I have tested wired headset, mic does not work too.

**Comment by junocomp** [comment]
I still can't get the mic to work. I have the latest UCM and everything. 

LSHW finds the mic but it wont enable it.

```
$ sudo lshw -class multimedia
[sudo] password for mobian: 
  *-multimedia:0 UNCLAIMED  
       description: Multimedia controller
       product: JasperLake IPU
       vendor: Intel Corporation
       physical id: 5
       bus info: pci@0000:00:05.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm cap_list
       configuration: latency=0
       resources: iomemory:600-5ff memory:6000000000-6000ffffff
*-multimedia:1
       description: Multimedia audio controller
       product: Jasper Lake HD Audio
       vendor: Intel Corporation
       physical id: 1f.3
       bus info: pci@0000:00:1f.3
       logical name: card0
       logical name: /dev/snd/controlC0
       logical name: /dev/snd/hwC0D2
       logical name: /dev/snd/pcmC0D0c
       logical name: /dev/snd/pcmC0D0p
       logical name: /dev/snd/pcmC0D5p
       logical name: /dev/snd/pcmC0D6p
       logical name: /dev/snd/pcmC0D7p
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi bus_master cap_list
       configuration: driver=sof-audio-pci-intel-icl latency=32
       resources: iomemory:600-5ff iomemory:600-5ff irq:135 memory:6002120000-6002123fff memory:6002000000-60020fffff

```

**Comment by junocomp** [comment]
This has been closed but is still not fixed
