### ISSUE TITLE
[BUG] Huawei matebook d14, problem with sound

### ISSUE THREAD

**Issue by NikitaMarakushev** [thesofproject/linux#3801]
There is no sound on my system. Only dummy output.
I tried on various stable versions of distributions such as deepin, ubuntu, linux mint, debian, manjaro. I also tried changing kernel versions and installing proprietary drivers. 

Result of "inxi -Fxz":

1) Audio:

  Device-1: Intel Comet Lake PCH-LP cAVS vendor: QUANTA driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3
  Sound Server-1: ALSA v: k5.15.0-43-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes

2) My kernel version: 5.15.0-43-generic

3) Result of "lsb_release -a": 

  Distributor ID:	Linuxmint
  Description:	Linux Mint 21
  Release:	21
  Codename:	vanessa

3) Result of "aplay -l":

  **** List of PLAYBACK Hardware Devices ****
  card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
    Subdevices: 1/1
    Subdevice #0: subdevice #0
  card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
    Subdevices: 1/1
    Subdevice #0: subdevice #0
  card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
    Subdevices: 1/1
    Subdevice #0: subdevice #0
  card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
    Subdevices: 1/1
    Subdevice #0: subdevice #0
  card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]
    Subdevices: 1/1
    Subdevice #0: subdevice #0

4) Result of "sudo lshw -c multimedia":

*-usb:0                   
       description: Video
       product: HD Camera: HD Camera
       vendor: Azurewave
       physical id: 6
       bus info: usb@1:6
       logical name: input9
       logical name: /dev/input/event5
       version: 21.05
       serial: 0001
       capabilities: usb-2.01 usb
       configuration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
  *-multimedia
       description: Multimedia audio controller
       product: Comet Lake PCH-LP cAVS
       vendor: Intel Corporation
       physical id: 1f.3
       bus info: pci@0000:00:1f.3
       logical name: card0
       logical name: /dev/snd/controlC0
       logical name: /dev/snd/hwC0D2
       logical name: /dev/snd/pcmC0D10p
       logical name: /dev/snd/pcmC0D3p
       logical name: /dev/snd/pcmC0D7p
       logical name: /dev/snd/pcmC0D8p
       logical name: /dev/snd/pcmC0D9p
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi bus_master cap_list
       configuration: driver=snd_hda_intel latency=32
       resources: irq:148 memory:b121c000-b121ffff memory:b1000000-b10fffff
4) dmesg:

[dmesglog.txt](https://github.com/thesofproject/linux/files/9262880/dmesglog.txt)

**Comment by NikitaMarakushev** [comment]
![Screenshot_2022-08-04_22-59-20](https://user-images.githubusercontent.com/63608270/182941702-3f6cd2ef-52d6-412c-97f9-2ad00e0670f7.png)

**Comment by NikitaMarakushev** [comment]
I have two systems on the same laptop
. Secondary is windows 10 home, and everything is fine with the sound

**Comment by plbossart** [comment]
please attach the results of 'alsa-info'.
I would bet you have one of the ES8336-based codecs... That will require kernel v5.19+a known fix. your 5.15 kernel will not support this model. see https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html

**Comment by NikitaMarakushev** [comment]
> please attach the results of 'alsa-info'. I would bet you have one of the ES8336-based codecs... That will require kernel v5.19+a known fix. your 5.15 kernel will not support this model. see https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html

There is result written in .txt file 
[alsa-info.txt](https://github.com/thesofproject/linux/files/9266045/alsa-info.txt)

**Comment by plbossart** [comment]
/sys/bus/acpi/devices/ESSX8336:00/status 	 15

Bingo.

**Comment by plbossart** [comment]
@NikitaMarakushev if you want sound, I am afraid you will have to compile your own kernel for now. The only working branch is https://github.com/thesofproject/linux/pull/3798 (v5.19 + code queued for 5.20 + fixes)

**Comment by NikitaMarakushev** [comment]
@plbossart , do you mean this branch https://github.com/plbossart/sound/tree/fix/es8336-board-ids ?

**Comment by plbossart** [comment]
> @plbossart , do you mean this branch https://github.com/plbossart/sound/tree/fix/es8336-board-ids ?

yes, it's the same thing.

**Comment by yarbsemaj** [comment]
Hi @plbossart, Thank-you so much for your amazing work on this issue. I have an other Huawei laptop (d15) with the same audio chipset (and same symptoms). Other that building and running your kernel fork, is there any other steps required to getting audio working.

I’d love to help your test you fix on a wide range of H/W

**Comment by NikitaMarakushev** [comment]
@plbossart ,I do not know what the reason is, but when I compiled and updated grub, I got a kernel panic, cannot sync associated with the root partition, there was a uuid there, I changed it to my /dev/nvme0n1p4, but it did not help

**Comment by plbossart** [comment]
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.

**Comment by NikitaMarakushev** [comment]
@plbossart , thank u,  i'll test your solution

**Comment by skaldebane** [comment]
Could this make it upstream into the Linux kernel directly? @plbossart 
This is likely affecting many people and most of them are probably simply reverting back to Windows for now, not knowing about this fix / not being techy enough to apply it.

**Comment by plbossart** [comment]
The fixes in  https://github.com/plbossart/sound/tree/fix/es8336-board-ids are in kernel v6.1+

Support for this codec is a nightmare - I gave up

**Comment by skaldebane** [comment]
Ah alright - does that mean that it now works on v6.1 out of the box, or is there still some work to do?
I have no experience with drivers and whatnot but I may be able to continue the work on it with a little guidance

**Comment by plbossart** [comment]
Things work for some people, doesn't for others. That's the hard part, there are just too many different undocumented configurations and trial-and-error.

**Comment by skaldebane** [comment]
Ah I see; Thanks a lot anyways!
I'll try the v6.1 kernel and report to you if it works (Huawei Matebook d14).

**Comment by skaldebane** [comment]
Unfortunately didn't work (with Kernel v6.2, ZorinOS)
