### ISSUE TITLE
[BUG] Soundcard not found for ES8326

### ISSUE THREAD

**Issue by yangxiaohua2009** [thesofproject/linux#3802]
I'm developing driver for ES8326. I recently switched to topic/sof-dev 5.19-rc2 from 5.18-rc2. With other things unchanged, the sof_essx8336 driver is not probed on branch 5.19. Alsainfo attached.
[5.18](http://alsa-project.org/db/?f=dbec7034223d3204aedd1a5d6943f41b58566eb8
)
[5.19](http://alsa-project.org/db/?f=e9e020418923fab8c4a47b1662076caa8b913b1e
)

> [    4.708456] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x90030000: GLB_TRACE_MSG: DMA_PARAMS_EXT
[    4.709508] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x2014001e successful
[    4.709568] sof-audio-pci-intel-tgl 0000:00:1f.3: created machine sof-essx8336
[    4.709579] sof-audio-pci-intel-tgl 0000:00:1f.3: Completing SOF PCI probe
[    5.670792] Bluetooth: Core ver 2.22

From the log I see that the tplg is not loaded.

**Comment by yangxiaohua2009** [comment]
@plbossart Any ideas? All I know is that this is not a firmware/codec driver/tplg/sof_essx8336.c/dsp-config issue.

**Comment by plbossart** [comment]
yes, there's a probe bug that's fixed by PR https://github.com/thesofproject/linux/pull/3798

**Comment by plbossart** [comment]
Recommended setup is described here: 
https://github.com/thesofproject/linux/wiki/ES8336-support
