### ISSUE TITLE
CI: Push on more branches can trigger CI check

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#382]
The following branches are tracked and every push triggers a CI check.

SOF/linux github: topic/sof-dev, topic/sof-dev-rebase, topic/sof-rcX-rebase, topic/sof-next-rebase

Plbossart github: all branches

"I am clearly not asking this for every PR since there are usually multiple updates from developers, but it makes sense once the PR is approved and merged/rebased on topic/sof-dev.
Likewise for all the -rebase branches it’ll ensure there was no issue with the squash/rebase operation." - by Pierre.

**Comment by plbossart** [comment]
@xiulipan can you provide the list of branches that are tracked by CI?

**Comment by xiulipan** [comment]
@plbossart 
Now only **topic/sof-dev** is supported.
We are working on multiple branch support now and we are extend our storage server memory space.

**Comment by lgirdwood** [comment]
@xiulipan CI should not be cloning and building a clean kernel for every PR. Our CI should be using a pre-cloned and pre-built (using a golden config) so that every git update and build is incremental.

**Comment by xiulipan** [comment]
@lgirdwood 
For our own Jenkins CI. PR and Daily is done this way.
But for Travis, their test logic is to start an empty ENV every time. And we could not do anything on it.

**Comment by mengdonglin** [comment]
No longer track CI requirements or bugs in this repo
