### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by tvardar** [thesofproject/linux#3823]
`git clone https://github.com/thesofproject/linux.git
Klonlama konumu: 'linux'...
remote: Enumerating objects: 10244793, done.
error: RPC başarısız oldu; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: gövdenin 14051 baytı hâlâ bekleniyor
fetch-pack: unexpected disconnect while reading sideband packet
fatal: erken dosya sonu
fatal: fetch-pack: geçersiz index-pack çıktısı
`
error download and setup

**Comment by plbossart** [comment]
That's a network error @tvardar, not much we can do on our side since the code is hosted on GitHub
