### ISSUE TITLE
No sound after hibernate

### ISSUE THREAD

**Issue by junocomp** [thesofproject/linux#3827]
I have a tablet that can only go on Hibernate (suspend not supported).

Running `kernel 5.19` and have the latest topologies for `es8336` which sound is working.

After returning from hibernate (linux-swap partition) I get no sound at all. The sound card is detected, I can even see it on alsamixer but no sound is coming out. The only way to get sound again is by restarting the device.

**Comment by lgirdwood** [comment]
@junocomp can you attach the dmesg after hibernate and any dmesg logs when attempting playback after hibernate. Thanks

**Comment by plbossart** [comment]
@junocomp we are only aware of an issue when hibernating, that was resolved with this patch.

ASoC: SOF: Intel: disable IMR boot when resuming from ACPI S4 and S5 states

this is in linux-stable linux-5.19.y 

Please enable dynamic debug by adding this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/9373906/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf and attach the dmesg log (starting with the resume from hibernate) 

Thanks!

**Comment by junocomp** [comment]
@plbossart please check the file attached.

https://www.file.io/KoeZ/download/Y07YDz4DV8Bi

**Comment by plbossart** [comment]
I don't see any issues in the log @junocomp 

If you get sound when resuming from S3 and not from S4, this could indicate an issue with the codec configuration. It's possible that register contents are lost. Trying saving your alsa configuration before hibernating, and restore it manually after hibernating to see if anything differs.

**Comment by junocomp** [comment]
@plbossart I tried that as well. What I tried so far

1) pulseaudio -k && sudo alsa force-reload
2) disabling the module and renabling, manually and through systemd-sleep
3) Re running the alsa configuration manually.

The thing is, alsa detects the soundcard when is back from hibernate, I can even play with alsamixer. Is just that no sound comes out. I read a while ago that some soundcards bypass the BIOS when returning from hibernate, which causes the sound not to work. I can't find it now. I was wondering if you have heard of something like this?

**Comment by plbossart** [comment]
@junocomp I don't think there's any relationship between BIOS and codec, this would true only for some HDaudio cards where some configurations are updated by the BIOS. Here you have an I2C-based codec with nothing managed in the BIOS. It's got to be some registers lost.

**Comment by junocomp** [comment]
@plbossart mmm... do you know any other ideas of how I can solve this?

**Comment by yangxiaohua2009** [comment]
@junocomp Please refer to https://github.com/yangxiaohua2009/custom-kernel/issues/9

**Comment by junocomp** [comment]
@yangxiaohua2009 I tried your solution from custom kernel, it works!

**Comment by plbossart** [comment]
@junocomp solution posted on alsa-devel, can you give it a try with the recommended setting in the wiki

https://lore.kernel.org/alsa-devel/20220825014952.1038508-1-zhuning0077@gmail.com/

[es8316_suspend_resume.patch.txt](https://github.com/thesofproject/linux/files/9422782/es8316_suspend_resume.patch.txt)
