### ISSUE TITLE
[BUG] ASUS EXPERTBOOK B7402FEA not work headphones

### ISSUE THREAD

**Issue by Bsplesk** [thesofproject/linux#3828]
**Describe the bug**
When connect the 3.5 jack headphones, the device appears (detected), but there is no sound.

**Environment**
Operating System: Arch Linux                       
Kernel: Linux 5.19.2-arch1-1
Hardware Model: ASUS EXPERTBOOK B7402FEA_B7402FEA
Firmware Version: B7402FEA.303
extra/sof-firmware 2.2-1

https://alsa-project.org/db/?f=2a4e20e05d8671f43ca3b31463e486e563746da6

**Comment by lgirdwood** [comment]
@Bsplesk can you confirm is speakers or display audio work ? If so, it could be that the driver is not sending all the HDA verbs to enable the codec headphone path.

**Comment by plbossart** [comment]
@Bsplesk please check the documentation https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#disable-sof-on-pci-hdaudio-devices-to-test-audio-playback and double-check if jack detection works on this platform without the SOF driver used.

**Comment by Bsplesk** [comment]
@lgirdwood  Yes, speakers and built-in (digital) microphone work.

**Comment by Bsplesk** [comment]
@plbossart  There is no way to disable SOF in UEFI. Disabling via /etc/modprobe.d/alsa-base.conf does not solve problem. The speakers are working, but the headphones are not.

**Comment by plbossart** [comment]
@Bsplesk If the headphones are not working without SOF, it's not an SOF problem....

**Comment by Bsplesk** [comment]
@plbossart  OK I see. issue can be closed. If connect small headphones and set the maximum volume, the sound appears (poor quality). It looks like the driver does not enable an internal amplifier. When the headset is connected, the microphone works (after reassigning pin to hdajackretask).
