### ISSUE TITLE
`ACPI: \_SB_.PC00.HDAS.IDA_.SNDW.SWD1.AF04.E001: Can't tag data node`

### ISSUE THREAD

**Issue by paulmenzel** [thesofproject/linux#3837]
On the Dell XPS 13 9315, Linux 6.0-rc2+

    $ git describe --tags
    v6.0-rc2-159-g4c612826bec14
    $ git log --oneline --no-decorate -2
    16120b1aa5e13 x86/sgx: Do not consider unsanitized pages an error
    4c612826bec14 Merge tag 'net-6.0-rc3' of git://git.kernel.org/pub/scm/linux/kernel/git/netdev/net

logs the warnings below:

    [    0.000000] bach kernel: microcode: microcode updated early to revision 0x421, date = 2022-06-15
    [    0.000000] bach kernel: Linux version 6.0.0-rc2 (root@4beb429beb4a) (gcc (Debian 11.3.0-3) 11.3.0, GNU ld (GNU Binutils for Debian) 2.38) #381 SMP PREEMPT_DYNAMIC Fri Aug 26 11:41:38 UTC 2022
    [    0.000000] bach kernel: Command line: BOOT_IMAGE=/vmlinuz-6.0.0-rc2 root=UUID=ebbb839d-ba09-4c1a-9fef-e88a4eb2dad5 ro log_buf_len=8M quiet
    […]
    [    0.213231] bach kernel: ACPI: \_SB_.PC00.HDAS.IDA_.SNDW.SWD1.AF04.E001: Can't tag data node
    [    0.214155] bach kernel: ACPI: \_SB_.PC00.HDAS.IDA_.SNDW.SWD3.AF02.LC00: Can't tag data node

[Output of `journalctl -b -1 -o short-monotonic`](https://github.com/thesofproject/linux/files/9435227/20220826-dell-xps-13-9315-linux-6.0-rc2-dmesg.txt)

**Comment by ujfalusi** [comment]
@paulmenzel, it is fixed upstream by 2ea3b19792dbe32287b0c48f3ff7e866f61967c7
