### ISSUE TITLE
Graphical login manager hangs

### ISSUE THREAD

**Issue by paulmenzel** [thesofproject/linux#3838]
Building Linux myself with Debian’s Linux configuration, the graphical login manager does not start. The mouse cursor can move but switch TTYs does not work. Pressing the power button tries to shut down the system, but that hangs. No idea if it’s related to issue
https://github.com/thesofproject/linux/issues/3777. Please find the logs and configuration attached.

1.  [Output of `journalctl -b -1 -o short-monotonic`](https://github.com/thesofproject/linux/files/9435246/20220826-dell-xps-13-9315-linux-6.0-rc2-dmesg.txt)
2.  [Linux kernel configuration `.config`](https://github.com/thesofproject/linux/files/9435256/config-6.0-rc2.txt)

**Comment by ujfalusi** [comment]
@paulmenzel, audio is not even probed according to the log, usually what is not loaded can not make the login manager not start...
If no audio is present that I believe they should be able to handle that, if they need audio (which I'm not sure they do).

Can you check if it is working with newer rc? If I recall there were ACPI regressions which might got fixed after rc2. My 11th gen sdw laptop works wine with 6.0-rc5.

**Comment by paulmenzel** [comment]
Thank you for your analysis. The device is used by a user in production now with the distribution Linux kernel, so I can’t test anymore.

**Comment by ujfalusi** [comment]
@paulmenzel, I see, the laptop is working as expected with the distro kernel? Just out of curiosity.

**Comment by paulmenzel** [comment]
Sorry for not adding that information. There are also issues with the distribution kernel, but not the one described here.
