### ISSUE TITLE
No sound on KBL for ES8336

### ISSUE THREAD

**Issue by yangxiaohua2009** [thesofproject/linux#3840]
After changing the dsp-cfg.c and soc-acpi-intel-kbl-match.c, the soundcard still cannot be seen.
The log shows

> [    2.706113] sof-audio-pci-intel-skl 0000:00:1f.3: PCI DSP detected
[    2.706127] sof-audio-pci-intel-skl 0000:00:1f.3: enabling device (0000 -> 0002)
[    2.706331] sof-audio-pci-intel-skl 0000:00:1f.3: error: missing mandatory ops
[    2.706340] sof-audio-pci-intel-skl: probe of 0000:00:1f.3 failed with error -22

[kbl.zip](https://github.com/thesofproject/linux/files/9450151/kbl.zip)

@plbossart Do you have any idea what's wrong with the sof driver? Thanks.

**Comment by plbossart** [comment]
We don't support KBL with the SOF firmware, only closed-source. You would need to set the ipc_type=1 option, but if the hope is that we handle the ES8336 driver that's not going to work. We only support HDaudio on KBL and only for development. It is what it is.

If you have devices with KBL+ES8336 you would need to work with the AVS driver.

**Comment by yangxiaohua2009** [comment]
I wrote a [machine driver](https://github.com/yangxiaohua2009/linux/pull/2/files) based on existing kbl i2s driver. The driver is successfully loaded but the tplg firmware is no loaded. Do you know how to get the correct tplg firmware like kbl_tplg.bin? Can I use the firmware for windows?

**Comment by plbossart** [comment]
For KBL support, you need to talk with @crojewsk @crojewsk-intel. we don't support SOF with I2S codecs on those platforms.

**Comment by crojewsk-intel** [comment]
@plbossart thanks for the mention.

@yangxiaohua2009 I've included your request in out TODO list. There is an ongoing effort to share the tools and the topology examples for the avs-driver under SOF umbrella. It's not going to finish within a day or two, but we're just few weeks shy.

Could you provide alsa-info output and the model of your machine? I admit that KBL+ESXXXX is a configuration I hear of for the first time.

**Comment by yangxiaohua2009** [comment]
@crojewsk-intel See alsainfo [here](http://alsa-project.org/db/?f=92efa3d855b32f56f4f8860c920b150aeb2f84a9).
The OEM uses KBL -R with ES8336 and ask for Linux support. I wrote a machine diver but don't know how to generate tplg.bin.
I do have IADK but didn't see KBL tplg included.

**Comment by crojewsk-intel** [comment]
@yangxiaohua2009 thanks for the input. Will ping you back next week. Sharing binary version of the topology is less of a problem when compared to sharing the base (ADSP) firmware binary. Will sync with our folks regarding this.

Note: We do not posses device of yours (model) so we may need your help in testing the topology out. The base firmware is one for the entire platform family, but the topology files are tailored for specific configurations and thus applying a generic one may not always work.

**Comment by plbossart** [comment]
not an SOF issue or supported platform, closing

**Comment by yangxiaohua2009** [comment]
@crojewsk-intel Any updates so far? Thanks.

**Comment by crojewsk-intel** [comment]
> @crojewsk-intel Any updates so far? Thanks.

Hello @yangxiaohua2009,

Last Friday the publishing process for the topology configuration files and the dev tools has concluded. [thesoftproject/avs-topology-xml](https://github.com/thesofproject/avs-topology-xml) and [thesofproject/avsdk](https://github.com/thesofproject/avsdk) are available. With that done, the team is pushing [additional patches](https://lore.kernel.org/alsa-devel/20221010121955.718168-1-cezary.rojewski@intel.com) to alsa-devel to support additional configurations. You see, there are several configurations being addressed simultaneously.

Machine board for ES8336 should be ready either today's evening or tomorrow's and then provided for testing.

**Comment by yangxiaohua2009** [comment]
@crojewsk-intel 
Hi I'm testing the new avs driver, and the error message says `Direct firmware load for intel/avs/skl/dsp_basefw.bin failed`

Do you know how can I get the closed sourced firmware dsp_basefw.bin? Thanks.

Also, I changed board_selection.c but the HDA is still loaded by default. Log, 8336.c and board_selection.c attached. [board_selection.zip](https://github.com/thesofproject/linux/files/9797957/board_selection.zip)

**Comment by crojewsk-intel** [comment]
Thank you for the update, @yangxiaohua2009.

I've prepared a candidate for avs+es8336 configuration, it's available at [crojewsk-intel/linux/tree/avs_es8336](https://github.com/crojewsk-intel/linux/tree/avs_es8336). Number of not-yet-upstreamed patches has been kept to a minimum. Total of 27 commits there, It's based on recent broonie/for-next plus the 15 patches I'd mentioned above.

**Note:** this separated branch has not been tested yet i.e.: all commits except for `ASoC: Intel: avs: Add es8336 machine board` are part of our integration branch but the the mentioned commit *just compiles*. As with any untested code - please make sure that you have more than just one kernel image flashed so you have something to go back to. And of course backup any important data.

Will provide AudioDSP firmware and audio topology binaries tomorrow.
Also, I've managed to obtain few es8336 evaluation boards but it seems the existing instructions help enable it only on JSL/ADL platforms. Design for KBL-specific rework is in-progress but it will take another week or two before we deem it stable. And thus we're not able to test the es8336 machine board driver with our CI yet. You will have to do it yourself if you do not want to wait.

Perhaps we could have a short call to clarify integration details?

**Comment by yangxiaohua2009** [comment]
@crojewsk-intel 

I tested the latest firmware and kernel. `aplay -l` can finally list soundcards, and there are I2S clocks while music playing.
However, there is no I2S data so no sound can be heard. Do you have any idea how to send the data out? Any additional information needed? Thanks.

conf file, dmesg and nhlt table included.

[es8336-tplg.zip](https://github.com/thesofproject/linux/files/9874959/es8336-tplg.zip)
