### ISSUE TITLE
[IPC4] Suspend/resume support is broken

### ISSUE THREAD

**Issue by ujfalusi** [thesofproject/linux#3861]
**description**
Suspend resume does not work with IPC4 given if the buffer size (thus the stop_threshold) is small enough.
In this case we are going to get xrun before suspend and the xrun handling will do a TRIGGER_STOP (and because of this no TRIGGER_SUSPEND).
This will cause IPC errors and later the core use count is going to be off also which will lead unexpected core0 shutdown:
- The TRIGGER_STOP is not freeing the widgets, they are still in use, we just stopped the audio stream.
- the system enters to suspend (w/o TRIGGER_SUSPEND to free the widgets!), the core's use count is reset to 0 (from non zero, because they were still in use)
- on resume a TRIGGER_START comes as part of the xrun handling
- IPCs will fail as the firmware just booted up, lost all context we had before suspend
- Start fails and we begin to tear down the pipeline, but
- since the core use count got reset we will power down core0 after the first widget has been released
- after this the DSP is dead and all IPCs will time out with no response.

**Steps to reproduce**
arecord or aplay to _any_ PCM with `--buffer-size=2048` or less and do an `rtcwake -s 5 -m mem`

**Comment by ujfalusi** [comment]
@plbossart, @ranj063, @bardliao, @kv2019i, @lyakh FYI

**Comment by ujfalusi** [comment]
Can this be solved by implementing the `tear_down_all_pipelines` / `set_up_all_pipelines` callbacks for IPC4 as well, but I'm not sure how it should look like.

**Comment by ranj063** [comment]
@ujfalusi is this IPC4 specific only? How is this different for IPC3?

**Comment by ujfalusi** [comment]
Fixed by: https://github.com/thesofproject/linux/pull/3862
