### ISSUE TITLE
[BUG] Tiger Lake Sound controller detected but cannot be switched on

### ISSUE THREAD

**Issue by jorgev259** [thesofproject/linux#3885]
**Describe the bug**
Installed pipewire and the relevant sof packages after an Arch install. Before driver installs the controller wouldnt show as an audio device, and afterwards it shows up as Inactive and only has "Off" option in sound settings.

Other devices like bluetooth speakers and headphones work fine on the system.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel:  Linux version 5.19.10-arch1-1 
    * SOF: 2.2.2-1

Laptop model: XPG Xenia XE Intel 11th Gen

**Screenshots or console output**
![imagen](https://user-images.githubusercontent.com/19596334/192408819-a0e93c2a-a2e8-463f-9ec4-ae32de01f60f.png)

**Comment by plbossart** [comment]
This is a Linux issue, transferring

**Comment by plbossart** [comment]
please see https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html and try at the hw: device level, this looks like a userspace issue.

**Comment by jorgev259** [comment]
Did a fresh install only installing pulsewire and sof-firmware. Attempting to test the speakers throws the following:
```
[chito@archlinux ~]$ speaker-test -Dhw:0,0 -c2 -r48000 -f S16_LE

speaker-test 1.2.7

Playback device is hw:0,0
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
Playback open error: -2,No existe el fichero o el directorio
[chito@archlinux ~]$
```
The sound controller still appears as inactive and with only the Off option displayed

**Comment by plbossart** [comment]
well there you go, you have a kernel issue. As suggested, enable dynamic debug and attach the 'dmesg' results.

**Comment by jorgev259** [comment]
[log.txt](https://github.com/thesofproject/linux/files/9676964/log.txt)

**Comment by plbossart** [comment]
there's nothing problematic @jorgev259 

please attach the results of 'alsa-info'

**Comment by jorgev259** [comment]
[alsa-info.txt](https://github.com/thesofproject/linux/files/9677207/alsa-info.txt)

**Comment by plbossart** [comment]
Thanks @jorgev259 This model is an Intel NUC laptop: LAPBC710

this model is based on the SoundWire interface, NOT HDAudio, and we added support for this last year IIRC. see quirks below

````
drivers/soundwire/dmi-quirks.c:         /* quirk used for NUC15 'Bishop County' LAPBC510 and LAPBC710 skews */
sound/soc/intel/boards/sof_sdw.c:               /* NUC15 'Bishop County' LAPBC510 and LAPBC710 skews */
````
We need to enable more dynamic debug, by copying this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/9682133/sof-dyndbg.conf.txt)
as /etc/modprobe.d/sof-dyndbg.conf. reboot and attach the result of 'dmesg'

Also make sure that you have SOUNDWIRE enabled in your config. This is what I use:

````
CONFIG_REGMAP_SOUNDWIRE=m
CONFIG_REGMAP_SOUNDWIRE_MBQ=m
CONFIG_SND_INTEL_SOUNDWIRE_ACPI=m
CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE=m
CONFIG_SOUNDWIRE=m
CONFIG_SOUNDWIRE_CADENCE=m
CONFIG_SOUNDWIRE_INTEL=m
# CONFIG_SOUNDWIRE_QCOM is not set
CONFIG_SOUNDWIRE_GENERIC_ALLOCATION=m
````

**Comment by jorgev259** [comment]
Where is that configuration supposed to be, not sure where i should put that second part

**Comment by plbossart** [comment]
@jorgev259 The configuration of your kernel is usually kept in /boot/config-<version>

**Comment by jorgev259** [comment]
@plbossart i have no config folder/file inside /boot 
![imagen](https://user-images.githubusercontent.com/19596334/193432371-a6ef8dfe-2655-4434-a8b4-cc5a5d1a854f.png)

**Comment by jorgev259** [comment]
I used archinstall for the install process

**Comment by plbossart** [comment]
On 10/2/22 2:05 AM, jorgev259 wrote:
> I used archinstall for the install process

I'm sorry, you will have to find out by yourself how your distribution 
configures the kernel and where it finds the configuration file.

**Comment by jorgev259** [comment]
Ok my config was on /proc/config.gz.
The only difference is that my config does have CONFIG_SOUNDWIRE_QCOM set when yours doesnt

**Comment by jorgev259** [comment]
[log2.txt](https://github.com/thesofproject/linux/files/9702678/log2.txt)

**Comment by jorgev259** [comment]
Attached new dmesg log output

**Comment by plbossart** [comment]
Thanks @jorgev259 the logs show the problem alright

````
[    4.502368] sof-audio-pci-intel-tgl 0000:00:1f.3: No SoundWire machine driver found
[    4.502368] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
[    4.502369] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
````

I suspect the DMI quirk in drivers/soundwire/dmi-quirks.c is not applied properly. 

You reported:

Manufacturer:      ADATA
Product Name:      XENIAXe15TI7G11GXELX
Product Version:   M23101-507
Firmware Version:  BCTGL357.0064.2021.0518.1820
System SKU:        XENIAXe15TI7G11GXELX-SGCMX
Board Vendor:      Intel Corporation
Board Name:        LAPBC710


But we use:

https://github.com/thesofproject/linux/blob/ddc2987f8e32125e6e783e582e44babc303a70b8/drivers/soundwire/dmi-quirks.c#L85

````c
	{
		/* quirk used for NUC15 'Bishop County' LAPBC510 and LAPBC710 skews */
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "Intel(R) Client Systems"),
			DMI_MATCH(DMI_PRODUCT_NAME, "LAPBC"),
		},
		.driver_data = (void *)intel_tgl_bios,
	},
````

I guess someone modified the Intel reference, it's probably easiest to add a new DMI quirk based on

Board Vendor:      Intel Corporation
Board Name:        LAPBC710

I can't test the code so you'll have to experiment here...

**Comment by jorgev259** [comment]
![imagen](https://user-images.githubusercontent.com/19596334/193949498-c7bf987c-9515-45c3-a040-4d29b853623a.png)
Compiled kernel modules with the following change and reinstalled sof-firmware. It has reverted to only show Dummy Output instead of the Tiger Lake controoler

**Comment by jorgev259** [comment]
Went back and installed the whole compiled kernel and it does show the tiger lake controller but cant activate it still

**Comment by jorgev259** [comment]
Same error on dmesg

**Comment by plbossart** [comment]
of course there's no change in behavior @jorgev259 , you kept the same fields for the match. They are different here.

	DMI_BOARD_VENDOR "Intel Corporation"
	DMI_BOARD_NAME "LAPBC710"

Try with this, it's often guesswork to find the mapping that works.

**Comment by jorgev259** [comment]
I added a new entry not modified the existing one as shown in the screenshot

**Comment by plbossart** [comment]
The initial quirk was based on this dmidecode output:

Manufacturer:      Intel(R) Client Systems
Product Name:      LAPBC710
Product Version:   M13826-506
Firmware Version:  BCTGL357.0064.2021.0518.1820
System SKU:        BBC710ECB7B02
Board Vendor:      Intel Corporation
Board Name:        LAPBC710

You have 

Manufacturer: ADATA
Product Name: XENIAXe15TI7G11GXELX
Product Version: M23101-507
Firmware Version: BCTGL357.0064.2021.0518.1820
System SKU: XENIAXe15TI7G11GXELX-SGCMX
Board Vendor: Intel Corporation
Board Name: LAPBC710

So the suggestion is to use a new entry based on the last two values (board vendor and board name). Got it?

**Comment by jorgev259** [comment]
Thats exactly what i did
![imagen](https://user-images.githubusercontent.com/19596334/194101783-78db42b2-cbf3-494a-b7b8-22eb354ea39a.png)

**Comment by plbossart** [comment]
you have exactly the same DMI_SYS_VENDOR and DMI_PRODUCT_NAME macros used twice. Use **BOARD** instead

**Comment by jorgev259** [comment]
OH ok will do

**Comment by jorgev259** [comment]
Installed the kernel wth the suggested changes, it only shows Dummy Output now but the "soundwire machine not found" error no longer shows on logs
[log6.txt](https://github.com/thesofproject/linux/files/9717310/log6.txt)

**Comment by plbossart** [comment]
ok, that's good progress.

I forgot that there's an additional change needed in sound/soc/intel/boards/sof_sdw.c, there's a similar DMI quirk that needs to be duplicated to set the relevant number of HDMI outputs and the jack detection method.

**Comment by jorgev259** [comment]
![imagen](https://user-images.githubusercontent.com/19596334/194116495-43ed3f06-ea9f-4ace-b5d1-45d5e5655b49.png)
Seems to work now!

**Comment by plbossart** [comment]
Great. Can you share the differences you added with a patch? I'd like this to go upstream quickly. If you're not using git, just attach the two files you modified and I'll do it. Thanks!

**Comment by jorgev259** [comment]
[dmi-quirks.c.txt](https://github.com/thesofproject/linux/files/9717553/dmi-quirks.c.txt)
/drivers/soundwire/dmi-quirks.c

**Comment by jorgev259** [comment]
[sof_sdw.c.txt](https://github.com/thesofproject/linux/files/9717562/sof_sdw.c.txt)

/sound/soc/intel/boards/sof_sdw.c

**Comment by plbossart** [comment]
Thanks @jorgev259, the changes are in https://github.com/thesofproject/linux/pull/3906

**Comment by plbossart** [comment]
code is upstream
