### ISSUE TITLE
No Sound ESSX8336 Pipewire

### ISSUE THREAD

**Issue by junocomp** [thesofproject/linux#3932]
On Ubuntu 22.04 and 22.10 the es8336 sound card is detected on both alsamixer and Gnome Settings but no sound is coming out. I suspect this is related to Pipewire. 

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2154#note_1574487

I was wondering if anyone has been able to get es8336 working with Pipewire specially on Ubuntu 22.04/22.10.

**Comment by plbossart** [comment]
Have you followed the recommended setup in the wiki? 
What kernel, what setup have you used?

It's exhausting to have to reply the same basic questions.

**Comment by junocomp** [comment]
I do have es8336 and es8316 enabled on my kernel and the latest sof 2.2.2

The wiki doesnt mention anything about pipewire or wireplumber.

**Comment by plbossart** [comment]
Have you successfully played/captured to/from all existing endpoints at the hw: level and does jack detection work?

If not, you are not ready to even look at Pipewire/pulseaudio integration.

**Comment by junocomp** [comment]
I enabled everything on alsamixer and though is detected no sound comes out. I went back to Debian where is only running Pulseaudio (no pipewire/wireplumber installed) with the same settings and it works.

**Comment by plbossart** [comment]
what does 'it works' mean?

**Comment by junocomp** [comment]
Sound comes out

**Comment by plbossart** [comment]
I would recommend you try with Fedora. This will give you the latest and greatest integration of pipewire with UCM. All other platforms are behind.

**Comment by junocomp** [comment]
I will give it a try, thanks.

**Comment by roworu** [comment]
I'm also facing this issue on Matebook 14 Intel with ESSX8336 on 6.0 kernel version. Am I still need to apply setup from wiki?
I'm not quite sure I understand how to apply the settings from this guide as never applied any kernel patches or built kenrel myself :(

**Comment by plbossart** [comment]
you still need patches with v6.0, see updated wiki with additional pointers.

**Comment by roworu** [comment]
Thank you so much, finally able to use Linux on my laptop after compiling kernel on Fedora!
Also, is there any plans on implementing these patches in main Linux kernel?

**Comment by plbossart** [comment]
> Thank you so much, finally able to use Linux on my laptop after compiling kernel on Fedora! Also, is there any plans on implementing these patches in main Linux kernel?

All the patches will land in the mainline kernel, but there's a pipeline effect since the patches need to be sent first to maintainers. If I send a patch today, it will land in 6.2 at best.

**Comment by junocomp** [comment]
I got it to work, this has to be turned on.

amixer -c0 cset name='Right Headphone Mixer Right DAC Switch' on
amixer -c0 cset name='Left Headphone Mixer Left DAC Switch' on

**Comment by merura** [comment]
> Have you followed the recommended setup in the wiki? What kernel, what setup have you used?
> 
> It's exhausting to have to reply the same basic questions.

Sorry, I cannot find recommended setup. Can you please give the wiki link?

**Comment by plbossart** [comment]
https://github.com/thesofproject/linux/wiki/ES8336-support
