### ISSUE TITLE
Wrong enable_mask when sending core enable IPC

### ISSUE THREAD

**Issue by tlauda** [thesofproject/linux#394]
Wrong enable_mask is set for core enable IPC.
Kernel should keep track of how many cores should be currently enabled in order to handle this correctly.

Let's consider scenario, where the first pipeline in topology is scheduled on core 1 and the rest of them on core 0. Current flow:
1. Kernel sends IPC with enable_mask = 0x2 (core 1) for the first pipeline.
2. Kernel sends IPC with enable_mask = 0x1 (core 0) for the second pipeline.
The second IPC disables core 1, because the appropriate bit is 0. It should have value 0x3 instead.

**Comment by plbossart** [comment]
@ranj063 can you comment and/or describe how we might solve this? Wondering if this is a quick fix which can go in the next upstream batch or more time needed?

**Comment by tlauda** [comment]
@ranj063 Any updates?

**Comment by tlauda** [comment]
@plbossart @ranj063 Can we at least get estimates when it can be fixed?

**Comment by plbossart** [comment]
@ranj063 @tlauda is this issue still valid, we've merged a PR a while ago for this.

**Comment by ranj063** [comment]
@plbossart yes, this is fixed.
