### ISSUE TITLE
Use SMART_SUSPEND to prevent waking up dsp before system suspend

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#396]
Enable the SMART_ SUSPEND feature to prevent waking dsp up before system suspend

**Comment by bardliao** [comment]
@ranj063  It will also check !pci_dev_keep_suspended(pci_dev) in [pci-driver.c](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/pci/pci-driver.c#L758).
And currently, !pci_dev_keep_suspended(pci_dev) is true in sof-audio-pci driver.
Look into [pci_dev_keep_suspended](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/pci/pci.c#L2407), I found
pm_runtime_suspended() is true which is expected.
pci_target_state() is 4(PCI_D3cold) but pci_dev->current_state is 3 (PCI_D3hot)
platform_pci_need_resume(pci_dev) is 1
So, Besides enabling SMART_SUSPEND, there are much things to do.

**Comment by fredoh9** [comment]
Testing with smart suspend flags, DPM_FLAG_SMART_SUSPEND and DPM_FLAG_LEAVE_SUSPENDED. But PM behavior is same as before. Looking at the implementations from other drivers.


[   76.382590] PM: suspend entry (deep)
[   76.382593] PM: Syncing filesystems ... done.
[   76.403068] sof-audio-pci 0000:00:0e.0: PM: sof_resume: entry
[   76.449950] sof-audio-pci 0000:00:0e.0: PM: sof_restore_pipelines: entry
[   76.454807] sof-audio-pci 0000:00:0e.0: PM: sof_suspend: entry
[   76.672746] PM: Saving platform NVS memory
[   76.677791] PM: Restoring platform NVS memory
[   77.975280] sof-audio-pci 0000:00:0e.0: PM: sof_resume: entry
[   78.022971] sof-audio-pci 0000:00:0e.0: PM: sof_restore_pipelines: entry
[   78.045719] PM: suspend exit
[   78.840294] sof-audio-pci 0000:00:0e.0: PM: sof_suspend: entry

I think we need to check the flag when suspend/resume. SMART feature may be not that smart.

**Comment by bardliao** [comment]
@fredoh9 good to see someone follows up on this issue :) I think SMART_SUSPEND is needed but we also need something else. As I checked before, pci_target_state() is 4(PCI_D3cold) but pci_dev->current_state is 3 (PCI_D3hot) platform_pci_need_resume(pci_dev) is 1
The system will be waked up before suspend in such condition. So I think we can check and let pci_dev->current_state be 4 (PCI_D3cold) at first.

**Comment by plbossart** [comment]
@ranj063 @bardliao no information since last year, can we close?

**Comment by fredoh9** [comment]
This is supposed to work with simply setting the flag. Not sure what was the missing pieces. Close this for now, we will revisit if needed.
