### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by junocomp** [thesofproject/linux#3973]
I know this might not the best place to do this, but I am having a hard time a place where I can request this on github.

Can anyone enable `CONFIG_SND_SOC_INTEL_SOF_ES8336_MACH=m` on Debian's kernel? Is currently not enabled and it requires rebuilding the entire kernel just for this.

**Comment by plbossart** [comment]
probably best to use IRC for this

https://wiki.debian.org/DebianKernel

**Comment by junocomp** [comment]
IRC... that's a bit outdated. I'll give it a shot.

Thanks

**Comment by junocomp** [comment]
Still no luck. Can someone from the SOF team request this?

**Comment by plbossart** [comment]
I don't have any contacts with the Debian kernel team, sorry.

**Comment by junocomp** [comment]
Managed to get someone to upstream it. Closing.

https://salsa.debian.org/kernel-team/linux/-/merge_requests/575
