### ISSUE TITLE
[BUG] i915 failure prevents SOF from loading on MTLP_RVP_HDA

### ISSUE THREAD

**Issue by miRoox** [thesofproject/linux#3985]
**Describe the bug**
i915 driver/firmware is not ready on MTL. Previously, SOF continued to load when the init of i915 and HDMI codec failed. Now, SOF cannot load after i915 failure on MTLP_RVP_HDA.

NOTE1: there is no kernel log for SOF modules, dmesg seems to end with i915 failure after the system boot.
NOTE2: SOF modules look probed:
```
> lsmod | grep "sof"
snd_sof_pci_intel_mtl    16384  0
snd_sof_intel_hda_common   180224  1 snd_sof_pci_intel_mtl
soundwire_intel        49152  1 snd_sof_intel_hda_common
snd_sof_intel_hda      24576  1 snd_sof_intel_hda_common
snd_sof_pci            24576  2 snd_sof_pci_intel_mtl,snd_sof_intel_hda_common
snd_sof_xtensa_dsp     16384  1 snd_sof_intel_hda_common
snd_sof               299008  3 snd_sof_pci,snd_sof_intel_hda_common,snd_sof_intel_hda
snd_sof_utils          20480  1 snd_sof
snd_soc_hdac_hda       24576  1 snd_sof_intel_hda_common
snd_hda_ext_core       32768  3 snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_soc_acpi_intel_match    69632  2 snd_sof_pci_intel_mtl,snd_sof_intel_hda_common
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_sof_intel_hda_common
snd_soc_core          339968  5 soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_dmic
snd_intel_dspcfg       36864  2 snd_sof,snd_sof_intel_hda_common
snd_intel_sdw_acpi     20480  2 snd_sof_intel_hda_common,snd_intel_dspcfg
snd_hda_codec         176128  2 snd_soc_hdac_hda,snd_sof_intel_hda
snd_hda_core          118784  5 snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_pcm               176128  8 snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_sof_utils,snd_hda_core
snd                   110592  10 snd_seq,snd_seq_device,snd_hwdep,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi
```

**To Reproduce**
check the kernel log after the system boot.

**Reproduction Rate**
100%

**Expected behavior**
Skip HDMI and continue to load SOF even if i915 fails.

**Impact**
It prevents us from testing SOF on MTLP_RVP_HDA.

**Environment**
1) Branch name and commit hash.
    * Kernel: https://github.com/thesofproject/linux/commit/7d2d29c3fc54
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTLP_RVP_HDA

**Comment by kv2019i** [comment]
@keqiaozhang @miRoox This can be avoid by commenting out "options i915 force_probe=*" for now with sof-dev kernel.

**Comment by miRoox** [comment]
I have confirmed that now SOF can load without `options i915 force_probe=*`. But I'm not sure if this is a regression or expected behavior, because SOF can load even with `options i915 force_probe=*` on at least ea1ca7d0610c.

**Comment by kv2019i** [comment]
@miRoox This is a regression in i915 driver, but basicly we should not start to use it until it the version in sof-dev (which is quite old compared even to DRM tip) is mature enough. Only then we can add the "force_probe=" back.
