### ISSUE TITLE
HDMI: rework the code to align with upstream fixes

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#400]
Takashi just posted a set of patch on alsa-devel: ALSA: HD-audio display power fixes
We need to rework the code and make sure the i915 power management remains functional.
Yet another example of why we need to upstream faster.

Filing as a bug since it'll gate upstream merges.

**Comment by mengdonglin** [comment]
Takashi's patches https://patchwork.kernel.org/project/alsa-devel/list/?series=53881

**Comment by plbossart** [comment]
v2 is at https://patchwork.kernel.org/project/alsa-devel/list/?series=55081

**Comment by bardliao** [comment]
@plbossart I didn't have time to check v2 version today. But I did a basic test on v1. snd_hdac_display_power() is changed so we need to modify hda-codec.c to adapt the change .After that hdmi playback works on Up2.

**Comment by ranj063** [comment]
@bardliao after you finish your changes, please ensure it doesnt also break PM functionality on chrome.

**Comment by bardliao** [comment]
@ranj063 Sure. But will chrome apply these patches?

**Comment by plbossart** [comment]
> @ranj063 Sure. But will chrome apply these patches?

If they don't then it's their decision and the Chrome integration team will have to modify the HDMI code on SOF to use the old snd_hdac_display_power and deal with reference counts. we stick to upstream in topic/sof-dev

**Comment by plbossart** [comment]
@bardliao can you submit a PR with Takashi's v2 changes (make sure to use cherry-pick -x so that we track upstream) and the changes needed on the SOF sides? I will need to other changes from upstream but this needs to go into topic/sof-dev first, otherwise I'll break the build.
