### ISSUE TITLE
[GLK][KMOD] Kernel RIP during testing check-kmod-load-unload-after-playback

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#4008]
Found Kernel RIP OOPS.

- Platform: GLK_BOB_DA7219
- Kernel Branch: topic/sof-dev
- Kernel Commit: [551c11c310ac](https://github.com/thesofproject/linux/commit/551c11c310ac)
- SOF Branch: stable-v2.2
- SOF Commit: [afe466da0238](https://github.com/thesofproject/sof/commit/afe466da0238)

Internal test link: 17482?model=GLK_BOB_DA7219&testcase=check-kmod-load-unload-after-playback-5

```
[ 5971.316951] kernel: RIP: 0010:dapm_find_widget+0x76/0xe0 [snd_soc_core]
[ 5971.317048] kernel: Code: 00 48 89 e7 e8 3b 0a e8 d1 49 89 e7 48 8b 5d 18 45 31 ed 48 8b 83 c0 03 00 00 48 81 c3 c0 03 00 00 4c 8d 60 e8 48 39 c3 74 29 <49> 8b 7c 24 08 4c 89 fe e8 ad b3 e7 d1 85 c0 75 0a 49 39 6c 24 28
[ 5971.317060] kernel: RSP: 0018:ffff92eec165bd80 EFLAGS: 00010206
[ 5971.317073] kernel: RAX: dead000000000100 RBX: ffffffffc0f5e4a0 RCX: 0000000000000000
[ 5971.317082] kernel: RDX: 0000000000000050 RSI: ffffffffc07d2c15 RDI: ffff8ddc03fa4c40
[ 5971.317090] kernel: RBP: ffff8ddc1b502568 R08: 0000000000000000 R09: 0000000000000000
[ 5971.317098] kernel: R10: ffff92eec165be38 R11: 0000000000000001 R12: dead0000000000e8
[ 5971.317105] kernel: R13: 0000000000000000 R14: 0000000000000001 R15: ffffffffc07d2c15
[ 5971.317114] kernel: FS:  0000000000000000(0000) GS:ffff8ddd77a00000(0000) knlGS:0000000000000000
[ 5971.317123] kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 5971.317131] kernel: CR2: 000055ef852d8e80 CR3: 000000010e510000 CR4: 0000000000350ee0
[ 5971.317140] kernel: Call Trace:
[ 5971.317152] kernel:  
[ 5971.317161] kernel:  ? __mutex_unlock_slowpath+0x45/0x280
[ 5971.317180] kernel:  ? snd_soc_dapm_disable_pin+0x24/0x60 [snd_soc_core]
[ 5971.317269] kernel:  __snd_soc_dapm_set_pin+0x1d/0xa0 [snd_soc_core]
[ 5971.317353] kernel:  snd_soc_dapm_disable_pin+0x31/0x60 [snd_soc_core]
[ 5971.317436] kernel:  da7219_aad_irq_thread+0x259/0x2a0 [snd_soc_da7219]
[ 5971.317467] kernel:  ? irq_thread+0xaf/0x1d0
[ 5971.317482] kernel:  ? irq_forced_thread_fn+0x80/0x80
[ 5971.317493] kernel:  irq_thread_fn+0x1d/0x60
[ 5971.317506] kernel:  irq_thread+0xf9/0x1d0
[ 5971.317517] kernel:  ? __kthread_parkme+0x1e/0xa0
[ 5971.317530] kernel:  ? irq_thread_check_affinity+0xa0/0xa0
[ 5971.317542] kernel:  ? wake_threads_waitq+0x30/0x30
[ 5971.317555] kernel:  ? irq_thread_check_affinity+0xa0/0xa0
[ 5971.317567] kernel:  kthread+0xf0/0x120
[ 5971.317579] kernel:  ? kthread_complete_and_exit+0x20/0x20
[ 5971.317594] kernel:  ret_from_fork+0x1f/0x30
```

[dmesg-glk.txt](https://github.com/thesofproject/linux/files/9994139/dmesg-glk.txt)
[slogger-glk.txt](https://github.com/thesofproject/linux/files/9994140/slogger-glk.txt)

**Comment by fredoh9** [comment]
Found more,
17390?model=GLK_BOB_DA7219&testcase=check-kmod-load-unload-25
17390?model=GLK_BOB_DA7219&testcase=check-kmod-load-unload-after-playback-5

- Kernel Branch: topic/sof-dev
- Kernel Commit: [cb13f81e00b4](https://github.com/thesofproject/linux/commit/cb13f81e00b4)
- SOF Branch: stable-v2.2
- SOF Commit: [afe466da0238](https://github.com/thesofproject/sof/commit/afe466da0238)

**Comment by fredoh9** [comment]
For daily test, kernel RIP OOPS is found in this week for the first time(2022-11-06 23:58:41 UTC)

But after scanning test results database, some of kernel PR tests with stable-v2.2 branch found same RIP OOPS. For example, kernel PR 3787. Due to 01.org under migration/construction, I couldn't add the link here.

First PR stable test failed with same RIP is kernel PR 3888 at 2022-10-26T02:44:27.254Z.
After that PR 3964 test at 2022-10-26T20:52:30.027Z.

**Comment by fredoh9** [comment]
I kinds of remembered JF device had unstable issue in long time ago, I scanned the database again to make sure this is not found only one DUT. Yes, I found at least two devices had reported same RIP.

**Comment by plbossart** [comment]
It's a known codec issue @fredoh9, we've never been able to figure it out.

**Comment by fredoh9** [comment]
duplicated with https://github.com/thesofproject/linux/issues/2676

I kind of remembered the similar call trace but couldn't find the above known issue. Closing this now
