### ISSUE TITLE
CI: add support for make bindeb-pkg target

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#402]
Reported-by : @lgirdwood 

The bindeb-pkg target is used by distributions and detects circular dependencies between modules. The recent move of the compressed API support as a module broke this requirement, so this is a useful check to add.

**Comment by xiulipan** [comment]
@plbossart @lgirdwood 
For sof-ci the binary storage used the `make bindeb-pkg`.
So you would like to let travis-ci and sof-ci to build with `make bindeb-pkg` just after the make is done or replace the `make `with `make bindeb-pkg`

**Comment by xiulipan** [comment]
travis ci part
https://github.com/thesofproject/linux/pull/413
