### ISSUE TITLE
[BUG] Debian12 no sound

### ISSUE THREAD

**Issue by lzzu** [thesofproject/linux#4032]
OS: Debian12(Bookworm)
Kernel: Linux6.0
Desktop: Gnome43

Hi!
I downloaded `firmware-sof-signed2.2.2` and `sof-bin 2.2.2`, but they didn't work properly, no response even when the headset is plugged in.

```
$ sudo dmesg | egrep "audio|sof|snd"
[    0.036286] software IO TLB: area num 4.
[    0.449769] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.449770] software IO TLB: mapped [mem 0x000000006a17f000-0x000000006e17f000] (64MB)
[    3.940323] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    4.566320] sof-audio-pci-intel-icl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    4.566410] sof-audio-pci-intel-icl 0000:00:1f.3: enabling device (0000 -> 0002)
[    4.566625] sof-audio-pci-intel-icl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.566731] sof-audio-pci-intel-icl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    4.573574] sof-audio-pci-intel-icl 0000:00:1f.3: use msi interrupt mode
[    4.590246] sof-audio-pci-intel-icl 0000:00:1f.3: NHLT_DEVICE_I2S detected, ssp_mask 0x1
[    4.590255] sof-audio-pci-intel-icl 0000:00:1f.3: hda codecs found, mask 4
[    4.592162] sof-audio-pci-intel-icl 0000:00:1f.3: firmware: direct-loading firmware intel/sof/sof-jsl.ri
[    4.592175] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[    4.592177] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
[    4.592185] sof-audio-pci-intel-icl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[    4.693876] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[    4.693884] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
```

and 

```
$ lspci | grep audio
00:1f.3 Multimedia audio controller: Intel Corporation Jasper Lake HD Audio (rev 01)
```

and

```
$ aplay -l
aplay: device_list:275: no soundcards found...
```

I'm still in `/etc/modprobe.d/alsa-base.conf ` file attempts `options snd-intel-dspcfg dsp_driver=1` and `options snd-intel-dspcfg dsp_driver=3` options, no sound.

any advise is welcome!
thanks.

**Comment by lgirdwood** [comment]
@lzzu this looks like the HDA codec driver is missing the correct verbs for audio input/output. There are several similar issues reported, best to search as there are some methods to detect the missing verbs and have them added to the Linux HDA codec driver.

**Comment by plbossart** [comment]
@lzzu can you please run 'alsa-info' and attach the results. If you see 'ESSX8336' in there, then it's the classic issue with the codec, see https://github.com/thesofproject/linux/wiki/ES8336-support

**Comment by fredoh9** [comment]
@lzzu is this ESSX8336 codec case? I'm curious about the issue.
Either upload alsa-info or if you don't need any help can you close this issue?

**Comment by plbossart** [comment]
closing for now, @lzzu please reopen if/when you have information to share.
