### ISSUE TITLE
ADL / RPL - Sound card not listed rarely post warmboot

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#4034]
When we run warmboot cycling on RPL Chrome reference design ( also seen 1 time on ADL-N reference design) , in 1 out of 1000s of cycles, sound card is not listed.
Logs do not throw any obvious error. In error condition, if we manually probe the driver, the sound card is loaded.

After few weeks of tests, we are noticing a pattern in all failed logs. we see a print as below
**Module has invalid ELF structures**

Even i tried enabling more debug, but this is last error just after FW download is complete is seen.

Any insights ?

Note:
Issue happens 1 in 10 boards and 1 in 1000 cycles, so its hard to recreate the scenario.

ADL / RPL  are on chrome-v5.10 kernel and ADL- N is on chrome-v5.15 kernel.

Attaching dmesgs of failure case, failed case with debug enabled and a success case.
[dmesg.txt](https://github.com/thesofproject/linux/files/10059556/dmesg.txt)
[dmesg_working.txt](https://github.com/thesofproject/linux/files/10059557/dmesg_working.txt)
[debug_enabled_dmesg.txt](https://github.com/thesofproject/linux/files/10059558/debug_enabled_dmesg.txt)

**Comment by plbossart** [comment]
It looks like the PCI probe works fine:
````
sof-audio-pci-intel-tgl 0000:00:1f.3: created machine adl_mx98360_rt5682
sof-audio-pci-intel-tgl 0000:00:1f.3: Completing SOF PCI probe
````

This error message cannot be found in the kernel source, can't figure out where this is generated:
````
Module has invalid ELF structures
````

I would add a dev_info on entry and exit of the machine driver .probe function, just to see if there is a missing dependency on that prevents the probe from registering a card.

Alternatively, add dynamic debug for snd-soc-core but that will be very very verbose.

**Comment by plbossart** [comment]
any update @sathyap-chrome, is this still a problem?

**Comment by plbossart** [comment]
@sathyap-chrome @sathya-nujella @kv2019i is this still a problem? Closing by default in two weeks.

**Comment by kv2019i** [comment]
@plbossart No additional info on this. 

The "Module has invalid ELF" is curious and hints at corruption (of memory or disk). This patch in newer kernels might help to print a few more details:
https://lore.kernel.org/all/20211015205741.38283-1-skhan@linuxfoundation.org/T/

... but given this is a reboot test, the module binary should not be modified between tests.

**Comment by sathyap-chrome** [comment]
Not reproduced in recent weeks

**Comment by plbossart** [comment]
closing, please re-open a new issue if needed.
