### ISSUE TITLE
CI: add target with built-ins instead of modules

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#404]
Even if we need modules to deal with request_firmware() for now, it's still interesting to make sure we can compile with built-ins instead of modules
make allyesconfig will take way too much time, we'd need to use the existing fragments but demote all =m to =y in the .config (be it with a command or a script regexp replacement)

**Comment by xiulipan** [comment]
@plbossart 
Got that. Maybe only build for now.

**Comment by wenqingfu** [comment]
done even for just build? @xiulipan

**Comment by xiulipan** [comment]
@wenqingfu 
Not yet. Will try to find a way to convert the config to all built-in and add to CI.

**Comment by plbossart** [comment]
> Not yet. Will try to find a way to convert the config to all built-in 
> and add to CI.
>
perl -pi.bak -e 's/=m/=y/g' sof-dev-defconfig ?

**Comment by mengdonglin** [comment]
No longer track CI requirements or issues in this repo
