### ISSUE TITLE
[BUG] Kernel Oops: unable to handle page fault for address: 000015fe0000005e on TGLU_RVP_SDW and TGLU_SKU0A32_SDCA

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4051]
**Describe the bug**
We observed a kernel oops on TGLU_RVP_SDW and TGLU_SKU0A32_SDCA after booting. sof driver failed to load:

```
[    4.778011] snd_soc_sof_sdw:sof_card_dai_links_create: sof_sdw sof_sdw: sdw 3, ssp 0, dmic 2, hdmi 4
[    4.778016] snd_soc_sof_sdw:init_dai_link: sof_sdw sof_sdw: create dai link SDW0-Playback, id 0
[    4.778048] snd_soc_sof_sdw:init_dai_link: sof_sdw sof_sdw: create dai link SDW0-Capture, id 1
[    4.778054] snd_soc_sof_sdw:init_dai_link: sof_sdw sof_sdw: create dai link SDW1-Playback, id 2
[    4.778061] BUG: unable to handle page fault for address: 000015fe0000005e
[    4.778086] #PF: supervisor read access in kernel mode
[    4.778100] #PF: error_code(0x0000) - not-present page
[    4.778120] PGD 0 P4D 0
[    4.778137] Oops: 0000 [#1] PREEMPT SMP NOPTI

```
This is a kernel regression and caused by https://github.com/thesofproject/linux/commit/3e0e1df91f7fdea91e5e9fccef5c38d52765189a
```
ASoC: Intel: sof_sdw: use common helpers for all Realtek amps
sof_sdw_rt1308.c/sof_sdw_rt1316.c/sof_sdw_rt1318.c handle amp
in basically the same way, optimized and merged into one file.

Signed-off-by: Gongjun Song <gongjun.song@intel.com>

```

**Reproduction Rate**
100%

[dmesg.txt](https://github.com/thesofproject/linux/files/10118837/dmesg.txt)

**Comment by ranj063** [comment]
@keqiaozhang could you please check if https://github.com/thesofproject/linux/pull/3962/commits/c1bb7bb4f66bbc80e98ead9b10f51db4d191e9fe will fix this?

**Comment by keqiaozhang** [comment]
> @keqiaozhang could you please check if [c1bb7bb](https://github.com/thesofproject/linux/commit/c1bb7bb4f66bbc80e98ead9b10f51db4d191e9fe) will fix this?

It doesn't help. Sorry I posted a wrong link by mistake, the bad commit should be https://github.com/thesofproject/linux/commit/3e0e1df91f7fdea91e5e9fccef5c38d52765189a

**Comment by gongjun-song** [comment]
The issue is caused by forgetting to set empty data at the end of the structure array.
If empty data is not set, there will be random access to arbitrary memory after using the structure array, which will cause data validation issues.

I have submitted a PR(https://github.com/thesofproject/linux/pull/4054) to fix this bug.
