### ISSUE TITLE
Upstream: patch1/core issues

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#407]
```text

>> +    for (i = 0; i < pages; i++) {
>> +        u32 idx = (((i << 2) + i)) >> 1;
> Looks like
>
>     u32 idx = (5 * i) >> 1;
Yes, but we'd also want an explanation of what we try to multiply by 2.5... Liam or Keyon, can you chime in?
````

````text
>
>> +        u32 pfn = snd_sgbuf_get_addr(dmab, i * PAGE_SIZE) >> PAGE_SHIFT;
>> +        u32 *pg_table;
>> +
>> +        dev_vdbg(sdev->dev, "pfn i %i idx %d pfn %x\n", i, idx, pfn);
>> +
>> +        pg_table = (u32 *)(page_table + idx);
>> +
>> +        if (i & 1)
>> +            *pg_table |= (pfn << 4);
>> +        else
>> +            *pg_table |= pfn;
>> +    }
>> +
>> +    return pages;
>> +}
>> +    if (plat_data->type == SOF_DEVICE_PCI)
>> +        sdev->pci = container_of(plat_data->dev, struct pci_dev, dev);
> Why not to use generic functions?
>     dev_is_pci()
>     to_pci_dev()
````

**Comment by ranj063** [comment]
> ```
> 
> >> +    for (i = 0; i < pages; i++) {
> >> +        u32 idx = (((i << 2) + i)) >> 1;
> > Looks like
> >
> >     u32 idx = (5 * i) >> 1;
> Yes, but we'd also want an explanation of what we try to multiply by 2.5... Liam or Keyon, can you chime in?
@plbossart I think this because while packing the address bits into the compressed page table, we're using 20 bits for each page which is 2.5 bytes. 

> ```
> ```
> >
> >> +        u32 pfn = snd_sgbuf_get_addr(dmab, i * PAGE_SIZE) >> PAGE_SHIFT;
> >> +        u32 *pg_table;
> >> +
> >> +        dev_vdbg(sdev->dev, "pfn i %i idx %d pfn %x\n", i, idx, pfn);
> >> +
> >> +        pg_table = (u32 *)(page_table + idx);
> >> +
> >> +        if (i & 1)
> >> +            *pg_table |= (pfn << 4);
> >> +        else
> >> +            *pg_table |= pfn;
> >> +    }
> >> +
> >> +    return pages;
> >> +}
> >> +    if (plat_data->type == SOF_DEVICE_PCI)
> >> +        sdev->pci = container_of(plat_data->dev, struct pci_dev, dev);
> > Why not to use generic functions?
> >     dev_is_pci()
> >     to_pci_dev()
> ```

**Comment by plbossart** [comment]
Thanks Ranjani, so we need a comment telling exactly what those 20bits are for and also check the use of standard ways to get the pci device.

**Comment by ranj063** [comment]
https://github.com/thesofproject/linux/pull/423 fixes this
