### ISSUE TITLE
Upstream: patch3/debug and patch 7/logger: remove error checks

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#408]
This is a bit controversial. I understand that execution and inits should not stop if debugfs creation or writes fail.
I still think it makes sense to avoid adding new elements when one access to debugfs fails.

**Comment by libinyang** [comment]
we should not stop our code if debugfs goes wrong.
A better solution is:
int ()
{
struct dentry *d;
d = debugfs_...();
if (!d) {
	dev_err();
	return -ENOMEM; //It seem our -ENODEV is the wrong value
}
return 0;
}

The caller just call it and ignore the error.

**Comment by plbossart** [comment]
@libinyang do I get it correctly that you are going to submit a PR for this? Just trying to figure out who works on what.
