### ISSUE TITLE
upstream: patch4/ipc: if get_free_pages can be used

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#409]
Feedback from @andy-shev:

````text
>  /* pre-allocate message data */
> +    for (i = 0; i < IPC_EMPTY_LIST_SIZE; i++) {
> +        msg->msg_data = devm_kzalloc(sdev->dev, PAGE_SIZE, GFP_KERNEL);
> +        if (!msg->msg_data)
> +            return NULL;
> +
> +        msg->reply_data = devm_kzalloc(sdev->dev, PAGE_SIZE,
> +                           GFP_KERNEL);
> +        if (!msg->reply_data)
> +            return NULL;
Can't you just get enough (non-continuous?) pages at once via get_free_pages interface?
I didn't know that one, so, consider rather a way to look into. 
````

**Comment by libinyang** [comment]
Yes, we can use devm_get_free_pages() with __GFP_ZERO flag to replace devm_kzalloc().

__get_free_pages() will allocate pages directly from the buddy system while kmalloc will allocate the memory from slab for some small size memory (kmalloc can also allocate big memory size actually).

So devm_get_free_pages() will be more efficient than devm_kzalloc() in some corner case in our case (but it is not always right).

**Comment by plbossart** [comment]
> So devm_get_free_pages() will be more efficient than devm_kzalloc() in some corner case in our case (but it is not always right).

@libinyang can you clarify what you meant here? We certainly don't want a solution that's broken...

**Comment by libinyang** [comment]
> > So devm_get_free_pages() will be more efficient than devm_kzalloc() in some corner case in our case (but it is not always right).
> 
> @libinyang can you clarify what you meant here? We certainly don't want a solution that's broken...

@plbossart 
I will submit a patch later.

**Comment by libinyang** [comment]
patch submitted
https://github.com/thesofproject/linux/pull/440

**Comment by plbossart** [comment]
Agreed to keep things as is, closing
