### ISSUE TITLE
Upstream: patch 13/14: use hex_dump_to_buffer

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#410]
Feedback from @andy-shev

I don't recall why we did the manual formatting. If we have a good reason, let's add a comment. Otherwise use hex_dump_to_buffer

**Comment by RanderWang** [comment]
yes, I reply the email. hex_dump_to_buffer converts a blob of data to "hex ASCII" in memory, is not fit for us, here we want to dump the content of call stack, like:
[    3.250628] sof-audio sof-audio: 0x0049fbb0: 0x8000f2d0 0x0049fc00 0x6f6c6c61 0x00632e63
[    3.250670] sof-audio sof-audio: 0x0049fbb4: 0x00ffffff 0x0010b5d4 0x00000000 0x2000004c
[    3.250710] sof-audio sof-audio: 0x0049fbb8: 0x0040d000 0x00000000 0x0000024c 0x2000930c
[    3.250747] sof-audio sof-audio: 0x0049fbbc: 0x8000454c 0x0049fc30 0x00401e20 0x00000001
[    3.250787] sof-audio sof-audio: 0x0049fbc0: 0x8000454c 0x0049fc30 0x00401e20 0x00000001
[    3.250827] sof-audio sof-audio: 0x0049fbc4: 0x00000000 0x00000001 0x00000010 0x0049fcb8
[    3.250865] sof-audio sof-audio: 0x0049fbc8: 0x0040a000 0x00401e98 0x00000001 0x00000002
[    3.250889] sof-audio sof-audio: 0x0049fbcc: 0x80005ac5 0x0049fc60 0x00000000 0x00000000

**Comment by RanderWang** [comment]
sorry, I am failed to reply the email to alsa for I am not the member of alsa. I discussed with XiuLi, get a conclusion that we don't need ASCII code, it is confusing. We just need some address and use a
script to analysis the call stack(@xiulipan). @plbossart , what is your idea?

**Comment by plbossart** [comment]
@RanderWang I believe you already answered to the mailing list and my take-away is that we need a specific format with address and values interleaved, that hex_dump_to_buffer doesn't provide, so that closes the question.

**Comment by andy-shev** [comment]
Hmm... I still didn't get why it can't be used. hex_dump_to_buffer() can be ajusted by given parameters to do different outputs including what I see. Anything specific had I missed?

**Comment by RanderWang** [comment]
ok, I discuss with @keyonjie , and we will try print_hex_dump. what is your idea?

**Comment by RanderWang** [comment]
@andy-shev  I tried the print_hex_dump, and found it is not fit for us. Now I just use hex_dump_to_buffer. https://github.com/thesofproject/linux/pull/464/commits/43299983a8ef627fc29f5ae093ebf0dc94b026fa
