### ISSUE TITLE
Help with ES8336 quirk

### ISSUE THREAD

**Issue by luigir-it** [thesofproject/linux#4103]
Hello.
I have a Teclast F7 and the audio is not working. I discovered that is use the aforementioned codec unfortunately.

Right now I'm running EndeavourOs (kernel 6.0.12-arch1-1), stock kernel didn't work, so I manually compiled and installed [this branch](https://github.com/thesofproject/linux/tree/es8336-v6.0), as suggested.
I just copied the stock kernel config file and compiled it, since the options 
`CONFIG_SND_SOC_INTEL_SOF_ES8336_MACH=m
CONFIG_SND_SOC_ES8316=m` where already in there.

Following [this page ](https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#es8336-support) I did:

1. run alsa-info.sh and made sure that I was using ES833, [this ](https://shorturl.at/iquz3)is the output
2. boot in Windows first
3. add  “options snd-intel-dspcfg dsp_driver=1” to /etc/modprobe.d/alsa-base.conf.
4. enable dynamic debug
5. run [dmesg](https://justpaste.it/aghk8)

Now, the audio is still not working but I haven't touched the quirks yet, since I don't know what I'm doing.

The only difference I noticed with the patched kernel is that, opening pavucontrol, only the dummy output is shown, while with the stock kernel the "Celeron/Pentium Silver Processor High Definition Audio Stereo" is recognized. Moreover, with stock kernel, whenever I play audio, I hear a short weird sound, like when you plug a headphone in a loose jack.

Note: I never compiled/installed a kernel before, I followed the arch wiki page too and it seems that there weren't any particular errors, exept when generating the initramfs, where some modules were missing. Could I have missed some steps?

Can anyone help me?

**Comment by plbossart** [comment]
You cannot use options snd-intel-dspcfg dsp_driver=1 for ES8336 support, you need the SOF driver.

Remove it and retry.

**Comment by luigir-it** [comment]
Yes, I have already removed it. The only difference I noticed is that the stock kernel showed the dummy output only.

**Comment by luigir-it** [comment]
Hi, is there at least a guide/wiki on how to test those quirk values? Maybe with examples?

From what I understand, I had to add `options snd_soc_sof_es8336 quirk=<value>`
But what values are valid?

Moreover, I noticed that when booting from the custom kernel, the es8336 module is not loaded, while with stock kernel it is (in fact pavucontrol from stock kernel recognize the device while custom kernel shows only dummy output)
BUT if I manually load the module with modprobe or add an entry in /etc/modules-load.d, the module is indeed loaded (confirmed with lsmod) but pavucontrol still shows only dummy output.

Both stock and custom kernel shows a value of "-1" in /sys/module/snd_soc_sof_es8336/parameters/quirk

**Comment by plbossart** [comment]
https://github.com/thesofproject/linux/wiki/ES8336-support
https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#es8336-support

**Comment by luigir-it** [comment]
I know those pages, the custom kernel I'm referencing is the one you linked. What I asked is which quirk should I try (and maybe understand which module to load with your kernel, since pavucontrol don't recognize the speaker)

**Comment by plbossart** [comment]
if you know these pages, then you have the answer or read sideways. copy-pasting what is listed in the help.

````
#define SOF_ES8336_SPEAKERS_EN_GPIO1_QUIRK   BIT(4)
#define SOF_ES8336_JD_INVERTED               BIT(6)
#define SOF_ES8336_HEADPHONE_GPIO            BIT(7)
#define SOC_ES8336_HEADSET_MIC1              BIT(8)
````

**Comment by luigir-it** [comment]
Pls be patient, something that is easy for you may not be easy for others. So, what I should do is write 

`options snd_soc_sof_es8336 quirk=<value>`
Where value is "BIT(4)"? Or bit(6,7,8)

Or do I have to copy those line you posted as they are and paste in alsa.conf?

**Comment by luigir-it** [comment]
Update: after a lot of trial and error, I managed to make it works.
Now headphones work fine, speaker so and so.
The speaker volume work but volume is very low and the quality is bad. But at least it works now

**Comment by plbossart** [comment]
try with suggestions in https://github.com/thesofproject/linux/issues/4111#issuecomment-1364653840

**Comment by luigir-it** [comment]
I played with alsamixer and solved the volume issue too.

So, for anyone trying to make audio works, here's what I did.

Clone [this](https://github.com/thesofproject/linux/tree/es8336-v6.0) kernel.
Since the [official wiki](https://thesofproject.github.io/latest/getting_started/setup_linux/install_locally.html) is incomplete, I also followed the [Arch Wiki](https://wiki.archlinux.org/title/Kernel/Traditional_compilation#Kernel_configuration)

- Start following the official wiki
- On Arch Linux, instead of step 2 in official, use this command `zcat /proc/config.gz > .config`
- Edit the config and add `CONFIG_SND_SOC_INTEL_SOF_ES8336_MACH=m` and `CONFIG_SND_SOC_ES8316=m` . On my system, these lines were already there.
- follow step 3 and 4
- Now continue [here](https://wiki.archlinux.org/title/Kernel/Traditional_compilation#Installation)
- Follow 4.1, 4.2 and 4.3.1
- Now the kernel installation is done. Update your bootloader (usually with grub `sudo grub-mkconfig -o /boot/grub/grub.cfg`) and reboot the system
- Boot the new kernel. Check if audio is working.
- If yes, great. If not, first read [this](https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#es8336-support)
- Make sure that you're using the sof drivers: if you see only the dummy output in pavucontrol, create the file /etc/modprobe.d/sound.conf and write `options snd-intel-dspcfg dsp_driver=3`
- Check if those modules are loaded using lsmod: 
```
snd_hda_intel
soundwire_intel
snd_soc_skl
snd_sof_probes
snd_soc_dmic
snd_soc_sof_es8336
snd_sof_pci_intel_apl
```
if not, load them (in this order) by creating the file /etc/modules-load.d/es8336.conf and just paste the modules
I'm not sure if all those modules are actually needed, but I loaded all of them just to be sure
- reboot
- Check for your speaker in pavucontrol. Now they should appear but the sound may still not working properly (it may play a hiss whenever you're trying to play any sound). If it still doesn't work, you may want to change the quirks. To do that, add `options snd_soc_sof_es8336 quirk=X` in the file /etc/modprobe.d/sound.conf
- Substitute the chosen value instead of X. For example, I choose 400. There was a comment here in a issue that described the single quirks. But I can't find it right now. To choose the value, just sum the decimal value of the single quirk. For example 80 is valid (it's BIT4 and BIT6) or 128 (BIT7) or 400 (BIT4 and BIT7 and BIT8)
- And reboot. 

That's it. It should be working now.

If the audio is very low, play with the slider in alsamixer.
Select the sound card with F6. I had to slide all the way up the Headphon bar and Dac bar. To make changes permanent do `sudo alsactl store X`, where X is the id of your card. And after reboot sudo alsactl restore X.
