### ISSUE TITLE
Tigerlake no audio, suspend/resume takes long, warnings in dmesg

### ISSUE THREAD

**Issue by jnikula** [thesofproject/linux#4107]
Intel Tigerlake, PCI ID 9A49, Debian bullseye with kernel v6.0 from bullseye-backports. Audio does not work. Both suspend and resume take 30+ seconds, with a bunch of warnings in dmesg.

Tried `snd_intel_dspcfg.dsp_driver=1` module parameter as suggested by Kai Vehmanen, and the issue is gone.

Logs attached. I logged before suspend / after resume messages manually by echoing to `/dev/kmsg` to highlight the timing.

[dmesg.txt](https://github.com/thesofproject/linux/files/10269346/dmesg.txt)
[dmesg-snd_intel_dspcfg.dsp_driver=1.txt](https://github.com/thesofproject/linux/files/10269345/dmesg-snd_intel_dspcfg.dsp_driver.1.txt)

**Comment by jnikula** [comment]
Cc: @kv2019i

**Comment by kv2019i** [comment]
Something very strange happens here. System works with snd-hda-intel, but with SOF (Debian bullseye with SOF1.7) the following happens:

[   11.326395] snd_hda_codec_hdmi ehdaudio0D2: failed to create hda codec -12
[   11.327975] snd_hda_codec_hdmi ehdaudio0D2: ASoC: error at snd_soc_component_probe on ehdaudio0D2: -12

I can't immediately explain how the codec probe can return -ENOMEM, but that's what happening. ALSA card register fails and audio is broken on the device.

**Comment by plbossart** [comment]
it's likely a two-pronged issue, with the out of memory issue on probe resulting later in issues with suspend/resume.

**Comment by jnikula** [comment]
With 48 GiB RAM, the -ENOMEM sounds suspicious.

**Comment by plbossart** [comment]
who will ever need more than 48 GiB of RAM, heh?

**Comment by jnikula** [comment]
The codec, apparently? ;D

**Comment by ujfalusi** [comment]
The strange thing is that if an allocation fails then we should have a print about it, but I cannot see that in the dmesg.
This is odd in the log (**update**: not odd, just that most of my systems has this a bit differently):
```
[   11.019198] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[   11.021202] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   11.021366] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[   11.021447] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
```
@jnikula, can you add this to `/etc/modprobe.d/sof-dyndbg.conf` and reboot? (drop the `snd_intel_dspcfg.dsp_driver=1` for this)
```
options snd-intel-dspcfg dyndbg=+pmf
options snd_hda_intel dyndbg=+pmf
options snd_sof dyndbg=+pmf
options snd_sof_pci dyndbg=+pmf
options snd_sof_intel_hda_common dyndbg=+pmf
options snd_sof_intel_hda dyndbg=+pmf
options snd-hda-codec-realtek dyndbg=+pmf
options snd-hda-codec-generic dyndbg=+pmf
options snd-hda-codec-hdmi dyndbg=+pmf
options snd-hda-intel dyndbg=+pmf
options snd-hda-codec dyndbg=+pmf
```

**Comment by jnikula** [comment]
@ujfalusi I first dropped `snd_intel_dspcfg.dsp_driver=1` to ensure I could still reproduce the problem before adding the new options. But I couldn't anymore. Apparently the kernel update from `Debian 6.0.3-1~bpo11+1` to `Debian 6.0.12-1~bpo11+1` fixed it. And I seem to have unwittingly removed the old kernel. (And will probably switch to a newer kernel shortly.)

Do you want me to dig into this further, or does that help you root cause the issue I was seeing?

**Comment by ujfalusi** [comment]
6.0.12 was tagged on 8th of Dec, I'm not sure if it is feasible to debug this further. I don't see related additional patches added by Debian, the backport should be in all relevant kernels, likely.

Probably it would be a good education and data point to know exactly what helped, but finding that between 6.0.3 and 6.0.12 is not something I would expect from you.
I don't see SOF or HDA patches with a quick scan that would be of a help.

**Comment by jnikula** [comment]
Turns out I did still have the old kernel, I don't know what I was looking at. o_O Anyway, here's the dmesg with debugs, same behaviour as originally described. HTH.

[dmesg-with-debugs.txt](https://github.com/thesofproject/linux/files/11001034/dmesg-with-debugs.txt)

**Comment by ujfalusi** [comment]
@jnikula, thanks, well, I don't see why it is failing with -ENOMEM and I don't see anything related to this with
`git diff v6.0...v6.0.12 sound/` (the dmesg is with 6.0.0).

perhaps if you can share the dmesg with 6.0.13, which is working?

**Comment by jnikula** [comment]
I don't know what Debian is doing with their kernel version string, but the failing one is:

```
[    0.000000] Linux version 6.0.0-0.deb11.2-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PREEMPT_DYNAMIC Debian 6.0.3-1~bpo11+1 (2022-10-29)
```

and the working one is:

```
[    0.000000] Linux version 6.0.0-0.deb11.6-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19)
```

See the `6.0.3-1~bpo11+1` vs. `Debian 6.0.12-1~bpo11+1` near the end of the string, not the `Linux version 6.0.0-0.deb11.2-amd64` at the beginning.

Here's the dmesg with debugs for the working case.

[dmesg-6.0.12-working.txt](https://github.com/thesofproject/linux/files/11003166/dmesg-6.0.12-working.txt)

**Comment by ujfalusi** [comment]
@jnikula, interesting versioning.

The fix arrived in 6.0.4:
02356311982b ("Revert "ALSA: hda: Fix page fault in snd_hda_codec_shutdown()"")

btw: the laptop have NVIDIA gxf, right?

**Comment by ujfalusi** [comment]
@jnikula, if you are OK with the answer, can you close the issue? Thank you.

**Comment by jnikula** [comment]
> btw: the laptop have NVIDIA gxf, right?

No, Intel integrated only.

> @jnikula, if you are OK with the answer, can you close the issue? Thank you.

Sure, thanks for the effort in root causing!
