### ISSUE TITLE
Alldocube i1405 GT Book Jasper Lake ES8336 No Sound

### ISSUE THREAD

**Issue by RezinoviyDed** [thesofproject/linux#4117]
cat /proc/cmdline:
initrd=\EFI\com.solus-project\initrd-com.solus-project.current.6.0.11-225 root=PARTUUID=770af32c-d289-48e4-8d47-7157252e9dd0 quiet loglevel=3 splash systemd.show_status=false rw radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 resume=UUID=16b614c6-58e0-4266-872f-f5391649ab65 CONFIG_SND_SOC_INTEL_SOF_ES8336_MACH=m CONFIG_SND_SOC_ES8316=m CONFIG_DYNAMIC_DEBUG=y

Output device: "Speakers - jasper Lake HD Audio"

I also unpacked the archive from es8336_topologies_main.tar.gz to /lib/firmware/intel/sof-tplg
After starting the operating system, the speakers make a pops.
I also noticed that the sound still works, but it is so quiet that at a volume of 150% it is almost inaudible.
My new [alsa-info](http://alsa-project.org/db/?f=ba398bc88a145afe0e0169ac7be54f87a4d4234a)

**Comment by plbossart** [comment]
see https://github.com/thesofproject/linux/issues/4111#issuecomment-1364653840

**Comment by RezinoviyDed** [comment]
The script yangxiaohua2009 helped in solving the problem.
Sequence of actions:
1. run script, but the sound has not changed
2. reboot
3. run script again
4. check speakers on system settings

Sound is working. Solved. Thank you.
