### ISSUE TITLE
[BUG] Headset does not play/record sounds on Dell XPS 17 9710

### ISSUE THREAD

**Issue by JuanFcoMiranda** [thesofproject/linux#4120]
Describe the bug
The device does not reproduce or record any sound with a headset connected the jack port.

To Reproduce
Tried several tools, OBS Studio, kwave, audacity, zoom, youtube video, audacious with no sound, nor played nor recorded.

Reproduction Rate
All the time.

Expected behavior
Play/Record sounds from the headset.

Environment
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: 6.2.0-rc2
SOF: 2.2.3-1
Name of the topology file
Topology: intel/sof-tplg/sof-tgl-rt711-rt1308-rt715.tplg
Name of the platform(s) on which the bug is observed.
Platform: Dell XPS 17 9710
Bios version: 1.16.1

**Comment by plbossart** [comment]
@JuanFcoMiranda is the headphone/headset detected when you insert/remove it?

**Comment by JuanFcoMiranda** [comment]
Hi @plbossart,

I have tried today, and it works fine, both, recording and playback, but yesterday it did not work although the headset was detected by the system.

Maybe with the latest update, fixed the problem.

Sorry for the inconvenience.
