### ISSUE TITLE
[IPC4] SSP hw_params configuration selection not working

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#4139]
SOF driver has the capability to configure a SSP port out of multiple possible configurations (as specified in tplg). This has been used and tested widely with SOF driver in IPC3 mode.

This feature is not working correctly with IPC4. The DAI copier sampling rate is always used to pick SSP settings, ignoring the FE PCM configuration. Result is that only one SSP configuration can be selected.

**Comment by kv2019i** [comment]
WIP pull-request that demonstrates the issue https://github.com/thesofproject/linux/pull/4137

**Comment by plbossart** [comment]
does the SSP blob in topology contain multiple configurations?

**Comment by kv2019i** [comment]
@plbossart Yes, there is test topology at https://github.com/juimonen/sof/tree/generic_bt_topo2 This needs some updates to work with latest main and we have done the changes (very raw set available at https://github.com/kv2019i/sof/commits/202301-bt-offload-ipc4-test-jan13-raw). With #4137, we have been able to confirm we can select all the three blobs, and that they are correctly passed to FW (and programmed to HW). But obviously #4137 is not something that can be merged, so this requires investigation why the logic is different in IPC3 and IPC4.

**Comment by plbossart** [comment]
@kv2019i is this not fixed already with your BT changes?

**Comment by kv2019i** [comment]
Yes, this is fixed and patches merged to upstream.
