### ISSUE TITLE
[BUG] The kernel fails to boot sporadically on the MTL platform

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4189]
**Describe the bug**
In our CI test, we found that the kernel has a certain probability of booting failure, the reproduction rate is about 20%. The system will get stuck when booting kernel and no logs available. It affects our CI test, I will investigate this issue first, hoping to find some clues.

**To Reproduce**
do warm-reboot stress test

**Reproduction Rate**
20%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
kernel:sof-dev branch
2) platform: MTL platform

**Comment by keqiaozhang** [comment]
I captured some journctl logs when boot failed. I didn't find any fatal errors comparing with good one.

**Comment by marc-hb** [comment]
BTW the 3 log files attached in the previous comment show the infinite GDM crash loop https://github.com/thesofproject/sof-test/discussions/998. It's probably unrelated.

**Comment by keqiaozhang** [comment]
I have captured the error after enabling the graphics. 
![image](https://user-images.githubusercontent.com/22468760/218670131-8c1677a7-7811-49c5-88a6-fb169d984b42.png)

Looks like this issue is related to NVME, I will try to replace the NVME with a new model next.

**Comment by keqiaozhang** [comment]
This issue is not reproducible after replacing the NVME to `WD black SN850`. Will continue to monitor it for another 2 weeks.

**Comment by mengdonglin** [comment]
@fredoh9 Can you please check if we can also replace the NVME on MTL in JF CI?

**Comment by keqiaozhang** [comment]
Closing this bug, all MTL devices have replaced  the NVME to `WD black SN850` or other model.
