### ISSUE TITLE
No sound - hp chromebook 14 g5(apollo lake) laptop

### ISSUE THREAD

**Issue by foxrus** [thesofproject/linux#4193]
Hello! Will Apollo Lake support sound? My chromebook shows the following - 

`chronos@localhost / $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: avsda7219 [avs_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: hdaudioB0D2 [hdaudioB0D2], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: hdaudioB0D2 [hdaudioB0D2], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: hdaudioB0D2 [hdaudioB0D2], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0`

But when I run any linux-based operating system, I have no sound at all

**Comment by plbossart** [comment]
if you are using avsmax98357a, then you are not using the SOF driver infrastructure but the AVS driver. The bugs for the AVS driver are handled on bugzilla.kernel.org
