### ISSUE TITLE
Intel NUC M15 laptop with Alder Lake-P, speakers and mic don't work

### ISSUE THREAD

**Issue by mosomate** [thesofproject/linux#4218]
I have a Schenker branded Intel NUC M15 laptop with i7-1260P. I'm using Ubuntu 22.04.2 LTS and 5.19.0-32-generic kernel. Speakers and microphone don't work. I found support for the original LAPRC710 version in `drivers/soundwire/dmi-quirks.c`, but this matches the manufacturer and model which won't work for me because it's Schenker branded. Maybe adding something more generic like this could solve the problem:
```
{
    /* quirk used for NUC15 LAPRC710 skew */
    .matches = {
        DMI_MATCH(DMI_BOARD_VENDOR, "Intel Corporation"),
        DMI_MATCH(DMI_BOARD_NAME, "LAPRC710"),
    },
    .driver_data = (void *)intel_rooks_county,
},
```
By the way I tried a few other things to fix the audio. `lscpi` gives back the following audio device:
```
00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
	DeviceName: Onboard - Sound
	Subsystem: Intel Corporation Device 3022
	Flags: bus master, fast devsel, latency 32, IRQ 199, IOMMU group 17
	Memory at 603e1e0000 (64-bit, non-prefetchable) [size=16K]
	Memory at 603e000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: sof-audio-pci-intel-tgl
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl
```
The version of SOF shipped with this version of Ubuntu is `2.0-1ubuntu4.1`. That seems to be a bit old to support Alder Lake processors.

I tried to force the kernel to use the legacy `snd_hda_intel` driver by `options snd-intel-dspcfg dsp_driver=1`. Still no sound. With `options snd-hda-intel model=generic` I could make HDMI output to appear, but no sound on it as well. I have no idea what other model should I try.

At this point I'm out of ideas. Any suggestion would be appreciated. Thanks in advance!

Update (2023-02-26):

I did some research today according to this:
https://bytemeta.vip/repo/thesofproject/linux/issues/3727?page=1

I managed to override the DSDT table, so probably the kernel now gets the correct addresses.

```
$ cat /sys/bus/acpi/devices/*/adr  | grep 025d
0x000030025d071101
0x000230025d131601
```
and
```
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:01  sdw:2:025d:1316:01  sdw-master-0  sdw-master-1
```
seems right.

This dmesg message hints that it uses _sof-adl-rt711-4ch.tplg_:
```
[ 4270.075920] sof-audio-pci-intel-tgl 0000:00:1f.3: loading topology:intel/sof-tplg/sof-adl-rt711-4ch.tplg
```

The problem seems to be that the topology file tries to connect a 4th HDMI output, but my laptop has only 3:
```
[ 4270.075588] sof_sdw sof_sdw: sdw 2, ssp 0, dmic 2, hdmi 3
[ 4270.075597] sof_sdw sof_sdw: create dai link SDW0-Playback, id 0
[ 4270.075630] sof_sdw sof_sdw: create dai link SDW0-Capture, id 1
[ 4270.075633] sof_sdw sof_sdw: create dai link dmic01, id 2
[ 4270.075635] sof_sdw sof_sdw: create dai link dmic16k, id 3
[ 4270.075639] sof_sdw sof_sdw: create dai link iDisp1, id 4
[ 4270.075645] sof_sdw sof_sdw: create dai link iDisp2, id 5
[ 4270.075648] sof_sdw sof_sdw: create dai link iDisp3, id 6
```
So, it fails at the 4th:
`[ 4270.076613] sof-audio-pci-intel-tgl 0000:00:1f.3: error: can't connect DAI HDA3.OUT stream iDisp4`

**Comment by plbossart** [comment]
@mosomate we already have a fix for this, see https://github.com/thesofproject/linux/issues/4088 and https://github.com/thesofproject/linux/pull/4091

We couldn't find the time to send this in the previous kernel cycle, so this will land upstream in 6.4 at best. You will also need topology changes added in https://github.com/thesofproject/sof/pull/6763, IIRC this was added in sof-bin 2.4. Clearly the 2.0 release will not work.

**Comment by mosomate** [comment]
Sorry, I missed that issue. Thanks!

**Comment by mosomate** [comment]
One thing still concerns me. As I mentioned before I have the Schenker variant of the laptop, and `dmidecode` gives me the following results:
```
$ sudo dmidecode -s system-product-name
SCHENKER VISION 15 E23 (SVS15E23)

$ sudo dmidecode -s baseboard-product-name
LAPRC710

$ sudo dmidecode -s system-manufacturer
SchenkerTechnologiesGmbH

$ sudo dmidecode -s baseboard-manufacturer
Intel Corporation
```
I'm not sure that the changes in #4091 will match these "rebranded" hardwares.

**Comment by plbossart** [comment]
@mosomate you're the only one with such a device, we can't help you unless you try an updated kernel and suggest a change on the existing solution.

**Comment by mosomate** [comment]
Of course you can't, I don't expect that. I rebuilt the kernel with my changes and the speakers, microphones and jack socket are fine. I'll fork the project and make a PR in the near future.
