### ISSUE TITLE
Upstream: Patch 5/14: check if we need to use spin_lock_irqsave

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#422]
We need clear explanations as to why we are using spin_lock_irqsave(). Takashi mentions in his feedback we can use spin_lock_irq().
I've asked for this multiple times, now it's a higher power asking...

**Comment by RanderWang** [comment]
it is a fix: https://github.com/thesofproject/linux/pull/434

We discussed this issue before and got a conclusion: spin_lock_irq should be applied(https://github.com/thesofproject/linux/pull/279)
