### ISSUE TITLE
Subwoofer not detected on LG Gram 17Z90Q (17" 2022)

### ISSUE THREAD

**Issue by lnicola** [thesofproject/linux#4224]
With `dsp_mode=1` I can set up a pin assignment using `hdajackretask` and it shows up.

http://alsa-project.org/db/?f=c660cf88b4b088910a3a4abd410ee06d5ba1bacb

[Kernel issue](https://bugzilla.kernel.org/show_bug.cgi?id=217147)

EDIT: of course, this might be the intended behavior, but it seemed it wasn't working.

**Comment by plbossart** [comment]
This is a codec configuration issue @lnicola, we don't support all the tools that are exposed by the legacy snd-hda-intel driver.
If you want this to be supported with SOF, the recommendation is to add a quirk for this system so that no re-tasking is required. There are hundreds of such quirks in patch_realtek.c

**Comment by lnicola** [comment]
Sorry, but I'm quite new to this. My understanding is that:

 - the "legacy" mode (non-SOF) needs a fix or quirk for the subwoofer to be visible; this is a driver issue, unrelated to SOF
 - with SOF, the subwoofer might already be working, either with a hardware crossover or with one done by SOF, or it should be exposed as a 2.1 device. I don't know which.

I tried to test both, but couldn't spot any obvious difference between the two, but even at maximum volume I can't hear a 100 Hz sine wave and 150 Hz is pretty quiet. So it's probably not working.

**Comment by plbossart** [comment]
The SOF parts will not change anything or do any filtering. The same two-channel stream is provided for both headset and amps. The subwoofer is only handled by the codec driver.

So the point is that you want to remove the manual pin retasking for the snd-hda-intel driver - that can be done by adding a quirk in the kernel code. The SOF driver will use it as well, so both configurations will work out of the box.

**Comment by lnicola** [comment]
Well, the point is that I suspect the subwoofer isn't working.

With the pin retasking I get an extra "Bass Speaker" volume control, but changing it doesn't seem to do anything (with a 150 Hz sine wave), so it might need some extra initialization steps.

In any case you seem to suggest that this is out-of-scope for SOF, so I should try to get it fixed in the codec before doing anything more on the SOF side.
