### ISSUE TITLE
[dell xps 13 plus 9320 evo, 6.1.18 linux ] no sound via microphone 

### ISSUE THREAD

**Issue by basiliscos** [thesofproject/linux#4242]
Hi. 

There was a sound, but after upgrading kernel, there is only silence in the internal microphone. `pavucontrol-qt` displays only small sound volume, when mic is turned to max, and indeed, I can hear only weak noise.

![2023-03-13_21-31](https://user-images.githubusercontent.com/3630048/224796979-64a813cb-a99f-4c32-9a00-8e33de18e7bc.png)

**Comment by plbossart** [comment]
@basiliscos we'd need a lot more data to be able to comment, e.g.

a) what was the last known working configuration
b) alsa-info log attached
c) checks if things are working at the hw: level with arecord

**Comment by basiliscos** [comment]
> a) what was the last known working configuration

I don't know . My linux distro (void linux) has rolling release policy, so, no way to roll back.

>  b) alsa-info log attached

[alsa-info.txt](https://github.com/thesofproject/linux/files/10960849/alsa-info.txt)

 > c) checks if things are working at the hw: level with arecord
 
 ```
 arecord - -f S16_LE | aplay -f S16_LE
Recording WAVE '-' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono
Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono
^CAborted by signal Interrupt...
Aborted by signal Interrupt...
 ```
 
 There was the same noise or no sound.

**Comment by plbossart** [comment]
I don't know what to tell you @basiliscos, maybe try and compile your own kernel based on 6.0. 6.1,  6.2 and see what works.
We've added support for this SKU 0AF3 upstream some two years ago.

Also try to check if the alsa-ucm-conf and asound.state files are consistent.

**Comment by basiliscos** [comment]
ok, I have tried ` 6.0.19` kernel, and here the mic works perfectly without any changes in alsa-ucm-conf or asound.state: I just rebooted and the mic works.

**Comment by basiliscos** [comment]
it also works on `6.1.19`, so, I think it should be closed.
