### ISSUE TITLE
Upstream: Patch 14/14: simplify utils

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#426]
Feedback from @andy-shev

````text
> +int sof_bes_setup(struct device *dev, struct snd_sof_dsp_ops *ops,
> +		  struct snd_soc_dai_link *links, int link_num,
> +		  struct snd_soc_card *card)
> +{
> +	char name[32];
> +	int i;
> +
> +	if (!ops || !links || !card)
> +		return -EINVAL;
> +
> +	/* set up BE dai_links */
> +	for (i = 0; i < link_num; i++) {

> +		snprintf(name, 32, "NoCodec-%d", i);

sizeof(name) ?

> +		links[i].name = devm_kstrdup(dev, name, GFP_KERNEL);
> +		if (!links[i].name)
> +			return -ENOMEM;

...or better devm_kasprintf().
````
I always get things wrong with strings so better have someone deal with this...

**Comment by libinyang** [comment]
snprintf(name, 32, "NoCodec-%d", i);
I think both 32 or sizeof(name) is OK. I'm prefer 32 :) as the name is just a temporary variable. 

for devm_kasprintf() vs devm_kstrdup(), I'm not very sure. I will do more investigation on it.

**Comment by libinyang** [comment]
@plbossart 
After checking the source code of devm_kstrdup() and devm_kasprintf(), I think devm_kstrdup() should be enough for us in this case. Could you please ask Andy why he suggest using devm_kasprintf()? I really can't tell the advantage of devm_kasprintf() in our case.

**Comment by plbossart** [comment]
@libinyang why don't you ask Andy directly on the mailing list? I have no added value here, better have a direct interaction to report your concerns or findings.

**Comment by ranj063** [comment]
@libinyang the point that andy is making is that we're using a snprintf first and then a kstrdup....we can do both in one go with devm_kasprintf

**Comment by ranj063** [comment]
https://github.com/thesofproject/linux/pull/439 fixes this.

**Comment by libinyang** [comment]
> @libinyang why don't you ask Andy directly on the mailing list? I have no added value here, better have a direct interaction to report your concerns or findings.

Get it. I was thinking that you are the interface for our SOF driver upstreaming so everything should go out through you. I will send the comments directly to the community. It's more efficient.

**Comment by andy-shev** [comment]
There is even cocinelle script for such conversion. So, it means if you run a set of cocinelle scripts present in kernel, you can avoid doing all those small optimizations as a separate changes, just get your code cleaner in the first place

**Comment by libinyang** [comment]
@andy-shev 

Got it. Thanks for clarification
