### ISSUE TITLE
[BUG] sof_ipc3_tear_down_all_pipelines: widget PIPELINE.2.SAI3.IN is still in use: count -1

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/linux#4263]
**Describe the bug**

A simple system suspend/resume cycle after reboot on i.MX8 platforms  makes SOF driver - unusable.

```
[  218.992979] Freezing remaining freezable tasks completed (elapsed 0.001 seconds)
[  219.000402] printk: Suspending console(s) (use no_console_suspend to debug)
[  219.009743] sof-audio-of-imx8m 3b6e8000.dsp: sof_ipc3_tear_down_all_pipelines: widget PIPELINE.2.SAI3.IN is still in use: count -1
 [  219.009791] sof-audio-of-imx8m 3b6e8000.dsp: sof_ipc3_tear_down_all_pipelines: widget PGA1.0 is still in use: count -1
 [  219.009795] sof-audio-of-imx8m 3b6e8000.dsp: sof_ipc3_tear_down_all_pipelines: widget PCM0P is still in use: count -1
```

This happens after commit:
```
commit 62c1ccce6c6514a3ff8590156fbd7fff9d24586f
Author: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
Date:   Wed Nov 16 12:41:58 2022 -0800

    ASoC: SOF: pm: Always tear down pipelines before DSP suspend
```

**To Reproduce**

simple suspend/resume of your choice.

**Reproduction Rate**

Always

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: Linux imx8mpevk 6.2.0-rc4-next-20230119
    * SOF: main @ ac910714f4
2) Name of the topology file
    * Topology: sof-imx8mp-wm8960.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: imx8m, imx8, imx8x

**Comment by dbaluta** [comment]
@ranj063 

At boot we have the following sequence:

```
snd_device_probe
  -> set_up_all_pipelines
      -> sof_widget_setup
        -> ++swidget->use_count
```

then because of runtime pm (2ms timeout)

```
sof_suspend                                                                                                                                                  
       -> snd_sof_runtime_suspend                                                                                                                                     
          ->  tear_down_all_pipelines
             -> tear_down_all_pipelines
               -> --swidget->use_count

```

So, after this sequence use_count = 0 for ALL widgets.

Now, if we do a suspend / resume, the widgets have all use_count = 0 but because of  62c1ccce6c6514a3 we get to decrement again the use_count making it -1. 

And then everything breaks.

At System PM suspend we get:

```
[  828.910669]  sof_suspend+0x64/0x2a8 [snd_sof]                                                                                                                                                           
[  828.915062]  snd_sof_suspend+0x14/0x20 [snd_sof]                                                                                                                                                        
[  828.919706]  dpm_run_callback.isra.0+0x3c/0xf0      
```

which calls into tear_down_all_pipelines, which decrements use_count. Making it -1.

**Comment by ranj063** [comment]
@dbaluta I think the difference is that with PCI devices, if the device is runtime suspended, it is brought back to full power and then suspended again. But looks like it doesnt happen on the IMX. So maybe we need an exception for this?

**Comment by dbaluta** [comment]
Exactly, we need an exception for this OR I was thinking to revert ect/linux/commit/62c1ccce6c6514a3ff8590156fbd7fff9d24586f and find a better for FW_CRASHED  and find a better strategy to fix the FW crash issue

**Comment by ranj063** [comment]
@dbaluta do you think you can use the DSP state to determine if we should invoke tear down or not? In our case, the DSP will be in D0 but in yours it will be in D3 right?

**Comment by dbaluta** [comment]
@ranj063 At a first glance this should work https://github.com/thesofproject/linux/pull/4265

will do more testing tomorrow.

**Comment by dbaluta** [comment]
Fixed with https://github.com/thesofproject/linux/pull/4265
