### ISSUE TITLE
Upstream: soc-acpi: add constant ops field

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#427]
Feedback from Takashi Sakamoto. Currently we store the ops in a void *pdata structure. we can add a dedicated ops field and keep the const qualifier.

**Comment by libinyang** [comment]
a RFC patch is submitted
https://github.com/thesofproject/linux/pull/457

I'm not sure if my understanding is right or not. It seems we don't need a new member as we will not change it when running, do we?
