### ISSUE TITLE
SOF crash does not maintain PM context despite SND_SOC_SOF_DEBUG_RETAIN_DSP_CONTEXT being enabled

### ISSUE THREAD

**Issue by jairaj-arava** [thesofproject/linux#4274]
On the Alder lake device, when SOF crash happened the systen doesn't maintain the PM context irrespective of SND_SOC_SOF_DEBUG_RETAIN_DSP_CONTEXT being enabled. 

[   10.054898] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[   10.054899] sof-audio-pci-intel-tgl 0000:00:1f.3: widget BUF13.0 setup complete
[   10.054905] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[   10.055124] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[   10.055125] sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM7P setup complete
[   10.055129] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[   10.055251] sof-audio-pci-intel-tgl 0000:00:1f.3: error : DSP panic!
[   10.055261] sof-audio-pci-intel-tgl 0000:00:1f.3: panic: dsp_oops_offset 788480 offset 788480
[   10.055263] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[   10.055268] sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (5)
[   10.055282] sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
[   10.055417] sof-audio-pci-intel-tgl 0000:00:1f.3: reason: runtime exception (0x6)
[   10.055420] sof-audio-pci-intel-tgl 0000:00:1f.3: trace point: 0x00004000
[   10.055424] sof-audio-pci-intel-tgl 0000:00:1f.3: panic at :0
[   10.055427] sof-audio-pci-intel-tgl 0000:00:1f.3: error: DSP Firmware Oops
[   10.055431] sof-audio-pci-intel-tgl 0000:00:1f.3: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
[   10.055435] sof-audio-pci-intel-tgl 0000:00:1f.3: EXCCAUSE 0x0000000d EXCVADDR 0xbe1d0000 PS       0x00060b25 SAR     0x00000000
[   10.055439] sof-audio-pci-intel-tgl 0000:00:1f.3: EPC1     0xbe02e9b7 EPC2     0xbe04c962 EPC3     0x00000000 EPC4    0x00000000
[   10.055443] sof-audio-pci-intel-tgl 0000:00:1f.3: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[   10.055446] sof-audio-pci-intel-tgl 0000:00:1f.3: EPS2     0x00060b20 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
[   10.055450] sof-audio-pci-intel-tgl 0000:00:1f.3: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000222
[   10.055454] sof-audio-pci-intel-tgl 0000:00:1f.3: stack dump from 0xbe281b10
[   10.055459] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b10: 00000000 00000000 00000000 00000000
[   10.055463] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b20: fe05a168 be281b60 be281b90 0000000d
[   10.055467] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b30: be281b10 00000000 00000000 00000000
[   10.055471] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b40: 1fffa750 00002001 16fc9890 00000000
[   10.055475] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b50: 7e04a066 be281b90 fffffffc 00000000
[   10.055478] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b60: be02e9b7 00000000 00000000 00000000
[   10.055482] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b70: be0551ec be0cf0e4 00070000 ffffffff
[   10.055486] sof-audio-pci-intel-tgl 0000:00:1f.3: 0xbe281b80: be04a154 be281d90 20001744 fe04a066
[   10.055489] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[   10.557052] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx timed out for 0x40070000 (msg/reply size: 12/12)
**[   10.557058] sof-audio-pci-intel-tgl 0000:00:1f.3: preventing DSP entering D3 state to preserve context**  **// DSP is prevented to enter into D3 as expected since SND_SOC_SOF_DEBUG_RETAIN_DSP_CONTEXT is enabled**
[   10.557060] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ IPC dump start ]------------
[   10.557076] sof-audio-pci-intel-tgl 0000:00:1f.3: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[   10.557078] sof-audio-pci-intel-tgl 0000:00:1f.3: dsp irq ppsts 0x00000000 adspis 0x00000000
[   10.557096] sof-audio-pci-intel-tgl 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[   10.557098] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ IPC dump end ]------------
[   10.557101] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to enable target core for widget PIPELINE.10.DMIC0.IN
[   10.557103] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to restore pipeline after resume -110
[   10.557107] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_pm_runtime_get on 0000:00:1f.3: -110
[   10.557112]  dmic01: __soc_pcm_open() failed (-110)
[   10.557115]  DMIC: ASoC: dpcm_be_dai_startup() failed at dmic01 (-110)
[   10.557118]  DMIC: dpcm_fe_dai_startup() failed (-110)
**[ 1221.076174] sof-audio-pci-intel-tgl 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3**  **//DSP is powered down!!! caused by cat /sys/kernel/debug/sof/exception**

This broke exception window tracing and crash dump collection which impeded debugging. Attached the full log.
[error.txt](https://github.com/thesofproject/linux/files/11143541/error.txt)

Steps to repro the issue:
Update the kernel built with **CONFIG_SND_SOC_SOF_DEBUG_RETAIN_DSP_CONTEXT=y** and do a warm reboot using **reboot** command.

**Comment by jairaj-arava** [comment]
@cujomalainey @sathya-nujella @ranj063

**Comment by kv2019i** [comment]
@jairaj-arava Here's one solution to the problem:
https://github.com/thesofproject/linux/pull/4282

This also contains an error injection patch that allows to easily get reproduce the problem (albeit without an actual FW panic). 

Additionally, the existing CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y option needs to be enabled (not in used in the original report). In short the solution is to store the exception to debugfs cache upon failure, so it can be read back later.

**Comment by jairaj-arava** [comment]
> @jairaj-arava Here's one solution to the problem: #4282
> 
> This also contains an error injection patch that allows to easily get reproduce the problem (albeit without an actual FW panic).
> 
> Additionally, the existing CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y option needs to be enabled (not in used in the original report). In short the solution is to store the exception to debugfs cache upon failure, so it can be read back later.

@kv2019i , sure let me try this.

**Comment by cujomalainey** [comment]
> Additionally, the existing CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y option needs to be enabled (not in used in the original report). In short the solution is to store the exception to debugfs cache upon failure, so it can be read back later.

When this bug was first hit, enabling the cache would suppress the D3 error message but just produce an empty exception in debugfs

**Comment by kv2019i** [comment]
@cujomalainey wrote:
> When this bug was first hit, enabling the cache would suppress the D3 error message but just produce an empty exception in debugfs

Ack, the exception data in cache was not valid in this case. When the panic happens in runtime-pm transition, we are left in limbo with the cache not updated, and debugfs code is unable to read the hardware window anymore.

One alternative implementation would perhaps be to update the cache (if enabled) in the crash handler directly, but this will affect larger amount of scenarios. Solution in https://github.com/thesofproject/linux/pull/4282 is very limited in scope (and thus a bit more safer approach).

**Comment by cujomalainey** [comment]
> One alternative implementation would perhaps be to update the cache (if enabled) in the crash handler directly, but this will affect larger amount of scenarios. Solution in https://github.com/thesofproject/linux/pull/4282 is very limited in scope (and thus a bit more safer approach).

That sounds like an excellent approach that does not mess with power states.

**Comment by jairaj-arava** [comment]
> @jairaj-arava Here's one solution to the problem: #4282
> 
> This also contains an error injection patch that allows to easily get reproduce the problem (albeit without an actual FW panic).
> 
> Additionally, the existing CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y option needs to be enabled (not in used in the original report). In short the solution is to store the exception to debugfs cache upon failure, so it can be read back later.

I tried the commit da01b14f19e1086df0dc72e2b91a7adb99b9a934 ASoC: SOF: pm: store debugfs cache upon errors in resume in #4282 with CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y enabled.

As expected we don't see any D3 error (sof-audio-pci-intel-tgl 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3) and also @cujomalainey I don't found the execption as empty (not sure if the data is valid) in the debugfs (Attached)
[exception.txt](https://github.com/thesofproject/linux/files/11165203/exception.txt)

**Comment by cujomalainey** [comment]
> As expected we don't see any D3 error (sof-audio-pci-intel-tgl 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3) and also @cujomalainey I don't found the execption as empty (not sure if the data is valid) in the debugfs (Attached)
> [exception.txt](https://github.com/thesofproject/linux/files/11165203/exception.txt)
> 

Which kernel did you test? If it's Pierre's then that is likely a sign we are missing something in 5.10

**Comment by jairaj-arava** [comment]
> > As expected we don't see any D3 error (sof-audio-pci-intel-tgl 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3) and also @cujomalainey I don't found the execption as empty (not sure if the data is valid) in the debugfs (Attached)
> > [exception.txt](https://github.com/thesofproject/linux/files/11165203/exception.txt)
> 
> Which kernel did you test? If it's Pierre's then that is likely a sign we are missing something in 5.10

@cujomalainey I tried chrome 5.10 kernel.

**Comment by cujomalainey** [comment]
> > > As expected we don't see any D3 error (sof-audio-pci-intel-tgl 0000:00:1f.3: error: debugfs entry cannot be read in DSP D3) and also @cujomalainey I don't found the execption as empty (not sure if the data is valid) in the debugfs (Attached)
> > > [exception.txt](https://github.com/thesofproject/linux/files/11165203/exception.txt)
> > 
> > Which kernel did you test? If it's Pierre's then that is likely a sign we are missing something in 5.10
> 
> @cujomalainey I tried chrome 5.10 kernel.

Weird, I definitely got bogus exceptions

**Comment by kv2019i** [comment]
@cujomalainey @jairaj-arava At least Jairaj's exception attached seems valid (to the extend I can verify it without a matching FW binary), so seems the mechanism is working. In real-life cases, there's of course additional risk that the exception dump is not correctly done.

If no objections, I'll proceed to polish a version to support this and submit for review to sof-dev.

**Comment by kv2019i** [comment]
A more polished version now pushed for review. I first tried the " update the cache (if enabled) in the crash handler directly" approach, but I soon realized that is actually not needed, we already update the cache in all scenarios (except resume failing). So basicly it's easier to just add the cache update to resume code. This is also a nicer change as the debugfs cache is completely handled within sof/pm.c.

I also came up with a quick-n-dirty way to force a DSP panic on the resume path (commits linked in the pull req, see https://github.com/thesofproject/linux/pull/4302#issuecomment-1507159878). I verified exception dump is correctly copied to the debugfs cache, it can be read via debugfs, and the exception looks correct and can be loaded to gdb.

**Comment by kv2019i** [comment]
Patch merged, good to merge @jairaj-arava ?

**Comment by jairaj-arava** [comment]
> Patch merged, good to merge @jairaj-arava ?

Hi @kv2019i , 
Since there is no change in the patch since last time I verified apart from the  commit message and discription. We are good to close it. Thanks @cujomalainey  for closing this.
