### ISSUE TITLE
[BUG] Headphone cannot output sound with SN6140 in RPL

### ISSUE THREAD

**Issue by MrBook2019** [thesofproject/linux#4291]
**Describe the bug**
Thinkpad L14 got a senary SN6140 codec, speaker, Dmic, headset mic works fine.
Only no sound output from headphone.
When disable Audio DSP，the issue is reproduced too.
The same os and codec, but cpu change to ADL, headphone can output sound.

**To Reproduce**
Play music and then plugin headphone, or plugin headphone and then play music.

**Reproduction Rate**
100%

**Expected behavior**
Headphone can output sound.

**Impact**
I can't use headphone to listen music.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: Linux version 5.19.17 (root@book-ThinkPad-L14-Gen-4) (gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0, GNU ld (GNU Binutils for Ubuntu) 2.39) thesofproject/sof#1 SMP PREEMPT_DYNAMIC Mon Mar 13 10:36:48 CST 2023
    * OS:   Ubuntu 22.10
    * SOF: [    6.341055] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
               [    6.341059] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:21:0
2) Name of the topology file
    * Topology: default
3) Name of the platform(s) on which the bug is observed.
    * Platform: 
        CPU : 13th Gen Intel(R) CoreT i5-1340P
        audio codec : Conexant SN6140

**Screenshots or console output**
book@book-ThinkPad-L14-Gen-4:~$ inxi -A
Audio:
  Device-1: Intel driver: sof-audio-pci-intel-tgl
  Sound Server-1: ALSA v: k5.19.17 running: yes
  Sound Server-2: PipeWire v: 0.3.58 running: yes

book@book-ThinkPad-L14-Gen-4:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 31: HDA Analog Deep Buffer (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
book@book-ThinkPad-L14-Gen-4:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 6: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 7: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

When headphone plugin and play music:
book@book-ThinkPad-L14-Gen-4:~$ sudo hdajacksensetest 
[sudo] password for book: 
Pin 0x16 (Black Headphone, Left side): present = Yes
Pin 0x19 (Black Mic, Right side): present = Yes

When headphone plugout and play music:
book@book-ThinkPad-L14-Gen-4:~$ sudo hdajacksensetest 
Pin 0x16 (Black Headphone, Left side): present = No
Pin 0x19 (Black Mic, Right side): present = No

**Comment by MrBook2019** [comment]
sof log as below:
[    6.202409] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[    6.226174] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
[    6.226181] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    6.226205] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[    6.229055] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[    6.229060] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:21:0
[    6.229061] sof-audio-pci-intel-tgl 0000:00:1f.3: FW ABI is more recent than kernel
[    6.229070] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[    6.341055] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[    6.341059] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:21:0
[    6.341062] sof-audio-pci-intel-tgl 0000:00:1f.3: FW ABI is more recent than kernel
[    6.344256] sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:22:1 Kernel ABI 3:21:0
[    6.344260] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    6.344494] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Parent card not yet available, widget card binding deferred
[    6.375980] snd_hda_codec_conexant ehdaudio0D0: SN6140: BIOS auto-probing.
[    6.376568] snd_hda_codec_conexant ehdaudio0D0: autoconfig for SN6140: line_outs=1 (0x17/0x0/0x0/0x0/0x0) type:speaker
[    6.376571] snd_hda_codec_conexant ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    6.376573] snd_hda_codec_conexant ehdaudio0D0:    hp_outs=1 (0x16/0x0/0x0/0x0/0x0)
[    6.376574] snd_hda_codec_conexant ehdaudio0D0:    mono: mono_out=0x0
[    6.376575] snd_hda_codec_conexant ehdaudio0D0:    inputs:
[    6.376576] snd_hda_codec_conexant ehdaudio0D0:      Mic=0x19
[    6.384678] snd_hda_codec_conexant ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[    6.384687] snd_hda_codec_conexant ehdaudio0D0: ASoC: source widget AIF1RX overwritten
[    6.384839] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget hifi3 overwritten
[    6.384844] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget hifi2 overwritten
[    6.384849] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget hifi1 overwritten
[    6.384853] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Codec Output Pin1 overwritten
[    6.384857] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Codec Input Pin1 overwritten
[    6.384863] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Analog Codec Playback overwritten
[    6.384869] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Digital Codec Playback overwritten
[    6.384874] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Alt Analog Codec Playback overwritten
[    6.384882] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Analog Codec Capture overwritten
[    6.384888] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Digital Codec Capture overwritten
[    6.384893] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Alt Analog Codec Capture overwritten
[    6.384906] skl_hda_dsp_generic skl_hda_dsp_generic: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
[    6.409257] input: sof-hda-dsp Mic as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input16
[    6.409311] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input17
[    6.409343] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input18
[    6.409372] input: sof-hda-dsp HDMI/DP,pcm=4 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input19
[    6.409413] input: sof-hda-dsp HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input20

**Comment by lgirdwood** [comment]
> When headphone plugin and play music: book@book-ThinkPad-L14-Gen-4:~$ sudo hdajacksensetest [sudo] password for book: Pin 0x16 (Black Headphone, Left side): present = Yes Pin 0x19 (Black Mic, Right side): present = Yes
> 
> When headphone plugout and play music: book@book-ThinkPad-L14-Gen-4:~$ sudo hdajacksensetest Pin 0x16 (Black Headphone, Left side): present = No Pin 0x19 (Black Mic, Right side): present = No

@MrBook2019 sorry, can you confirm if it's the speakers or heaphone that does not work. It seems above when headphone is plugged in you can hear audio on the headphones but no audio from speakers when headphones removed?

If this is correct then I can see the SN6140 has a class D amplifier and it may not be enabled by the SN6140 codec driver.
https://en.senarytech.com/product/9.html

**Comment by plbossart** [comment]
I also don't get what "The same os and codec, but cpu change to ADL, headphone can output sound." means? this looks like a completely different platform, doesn't it? That means that the HDaudio verbs could be completely different due to a different BIOS setup.

**Comment by neowong-taiwan** [comment]
> I also don't get what "The same os and codec, but cpu change to ADL, headphone can output sound." means? this looks like a completely different platform, doesn't it? That means that the HDaudio verbs could be completely different due to a different BIOS setup.

The verb table from ADL vs RPL almost same except one minor place:

RPL :
/sys/class/sound/hwC0D0/init_pin_configs:
0x16 0x03211040
0x17 0x91170110
0x18 0x40f001f0
0x19 0x04a11030 <==
0x1a 0x40f001f0
0x21 0x40f001f0

ADL :
/sys/class/sound/hwC0D0/init_pin_configs:
0x16 0x03211040
0x17 0x91170110
0x18 0x40f001f0
0x19 0x03a11030 <== 
0x1a 0x40f001f0
0x21 0x40f001f0

**Comment by sathyap-chrome** [comment]
Can you drop the 2 m4 files if they are different ?

**Comment by plbossart** [comment]
@neowong-taiwan you probably need to experiment with the code in sound/pci/hda/patch_conexant.c

I see a reference to your codec and it could very well be that quirks are needed on one platform
````	
HDA_CODEC_ENTRY(0x14f11f87, "SN6140", patch_conexant_auto),
````

Adding Mark Pearson for Lenovo support @mrhpearson

**Comment by plbossart** [comment]
@neowong-taiwan you probably need to experiment with the code in sound/pci/hda/patch_conexant.c

I see a reference to your codec and it could very well be that quirks are needed on one platform
````	
HDA_CODEC_ENTRY(0x14f11f87, "SN6140", patch_conexant_auto),
````

Adding Mark Pearson for Lenovo support @mrhpearson

**Comment by neowong-taiwan** [comment]
> Can you drop the 2 m4 files if they are different ?

For the topology, I think both ADL/RPL using same topology package, pack from https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-1.2.5.tar.bz2
@MrBook2019 can you help to confirm RPL parts ?

**Comment by plbossart** [comment]
> > Can you drop the 2 m4 files if they are different ?
> 
> For the topology, I think both ADL/RPL using same topology package, pack from https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-1.2.5.tar.bz2 @MrBook2019 can you help to confirm RPL parts ?

the topology has indeed nothing to do with headphone issues. We only have an 'analog' PCM device, the routing between headphone/speakers is handled in the HDAudio codec, possibly with UCM help.

**Comment by MrBook2019** [comment]
> > When headphone plugin and play music: book@book-ThinkPad-L14-Gen-4:~$ sudo hdajacksensetest [sudo] password for book: Pin 0x16 (Black Headphone, Left side): present = Yes Pin 0x19 (Black Mic, Right side): present = Yes
> > When headphone plugout and play music: book@book-ThinkPad-L14-Gen-4:~$ sudo hdajacksensetest Pin 0x16 (Black Headphone, Left side): present = No Pin 0x19 (Black Mic, Right side): present = No
> 
> @MrBook2019 sorry, can you confirm if it's the speakers or heaphone that does not work. It seems above when headphone is plugged in you can hear audio on the headphones but no audio from speakers when headphones removed?
> 
> If this is correct then I can see the SN6140 has a class D amplifier and it may not be enabled by the SN6140 codec driver. https://en.senarytech.com/product/9.html

@lgirdwood In RPL, the speaker can work normally, and the headphone can not work.

**Comment by MrBook2019** [comment]
> @neowong-taiwan you probably need to experiment with the code in sound/pci/hda/patch_conexant.c
> 
> I see a reference to your codec and it could very well be that quirks are needed on one platform
> 
> ```
> HDA_CODEC_ENTRY(0x14f11f87, "SN6140", patch_conexant_auto),
> ```
> 
> Adding Mark Pearson for Lenovo support @mrhpearson

In RPL machine, the subsystem_id is 0x17aa50bd, it will match the quirk below:
SND_PCI_QUIRK_VENDOR(0x17aa, "Thinkpad", CXT_FIXUP_THINKPAD_ACPI),
it will add a func hda_fixup_thinkpad_acpi() to add mic mute led and mic led.
In ADL machine, the subsystem_id is 0x19e5328c,it will not match any quirk.

**Comment by pma1** [comment]
> > Can you drop the 2 m4 files if they are different ?
> 
> For the topology, I think both ADL/RPL using same topology package, pack from https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-1.2.5.tar.bz2 @MrBook2019 can you help to confirm RPL parts ?

OS distributions package the release of sof-bin from "  https://github.com/thesofproject/sof-bin", not built it from m4 files.
Already tested v2.2.4 of sof-bin, the issue is reproduced.

**Comment by pma1** [comment]
> > > Can you drop the 2 m4 files if they are different ?
> > 
> > 
> > For the topology, I think both ADL/RPL using same topology package, pack from https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-1.2.5.tar.bz2 @MrBook2019 can you help to confirm RPL parts ?
> 
> the topology has indeed nothing to do with headphone issues. We only have an 'analog' PCM device, the routing between headphone/speakers is handled in the HDAudio codec, possibly with UCM help.

Filed alsa-ucm-conf issue:
https://github.com/alsa-project/alsa-ucm-conf/issues/300

**Comment by MrBook2019** [comment]
@neowong-taiwan add ADL and RPL alsa-info:
[RPL_alsa-info.txt](https://github.com/thesofproject/linux/files/11195970/RPL_alsa-info.txt)
[ADL_alsa_info.txt](https://github.com/thesofproject/linux/files/11195971/ADL_alsa_info.txt)

**Comment by plbossart** [comment]
> @neowong-taiwan add ADL and RPL alsa-info: [RPL_alsa-info.txt](https://github.com/thesofproject/linux/files/11195970/RPL_alsa-info.txt) [ADL_alsa_info.txt](https://github.com/thesofproject/linux/files/11195971/ADL_alsa_info.txt)

@MrBook2019 your ADL device is from Huawei, the RPL one from Lenovo. How on earth can we draw any conclusions from such vastly different systems? We have to compare apples-with-apples, similar configurations otherwise anything goes and we are all wasting time.

**Comment by MrBook2019** [comment]
@plbossart the ADL and RPL machine although from two company, but the operation system is all the ubuntu, and the codec is all the SN6140. I think the hda controller driver and codec driver is similar, and it worth to compare.
If i'm not correct, please help to point it, thanks.

**Comment by mrhpearson** [comment]
Hi.

Sorry for the slow reply - was caught up in the recent ice-storm and it's taken me a while to get back on top of things.

We're still doing Linux enablement for the L14 G4 - but I was a bit surprised to see you have the Senary codec. That's not been delivered upstream yet, and we weren't expecting to see it as a primary source so it's not been a priority.

We are looking to get it supported on Linux and are working with the vendor on it - but you may have to wait a bit. I'll check with the team what the latest status is (as a note for myself - LO-2281)

Is this a production level unit?

Mark

**Comment by MrBook2019** [comment]
Below kernel log is with sof debug enable:
[ADL_dmesg_sofdebug.txt](https://github.com/thesofproject/linux/files/11259571/ADL_dmesg_sofdebug.txt)
[RPL_dmesg_sofdebug.txt](https://github.com/thesofproject/linux/files/11259576/RPL_dmesg_sofdebug.txt)

Also i dump the codec reg in ADL and RPL, in ubuntu and win11:
[ADL_regdump_linux.txt](https://github.com/thesofproject/linux/files/11259602/ADL_regdump_linux.txt)
[ADL_regdump_windows.log](https://github.com/thesofproject/linux/files/11259605/ADL_regdump_windows.log)
[RPL_regdump_linux.txt](https://github.com/thesofproject/linux/files/11259610/RPL_regdump_linux.txt)
[RPL_regdump_windows.log](https://github.com/thesofproject/linux/files/11259614/RPL_regdump_windows.log)
In RPL platform, i compare the reg in win11 and linux, and config the different reg value from win11 to linux, but the headphone still cannot output audio.

I think the SN6140 is working, but the audio stream cannot down to SN6140, then headphone cannot output. It may be a audio stream path issue.

**Comment by MrBook2019** [comment]
I conducted several tests:
1 With headphone plugin, when play music, use an oscilloscope to detect hda sdout, I can detect signal in hda sdout;
2 With headphone plugin and music playing, loopback sn6140's input to output, and use audacity to record input, i can record the music in play;
3 When speaker is playing, plugin headphone with it not detect, though alsamixer to unmute headphone, then headphone will output music together with speaker.
I dump the codec reg in RPL when headphone and speaker can output music in test 3:
[regdump_hpspkplay_1.txt](https://github.com/thesofproject/linux/files/11308085/regdump_hpspkplay_1.txt)

Though the test 1 and 2, i think we can confirm that the audio steam can down to codec when headphone plugin.
Though the test 3, i think the audio stream can down to headphone may because the speaker and headphone has the same stream id, just like below:
Get Channel Stream ID 10h   value = 0x10
Get Channel Stream ID 11h   value = 0x10
May this config will affect the headphone function?

**Comment by MrBook2019** [comment]
I have confirmed that the headphone cannot output sound just because spk_mute disable the headphone output.
By unmute headphone with codec vendor register, headphone can output sound.
I will close this issue, and thanks very much for @plbossart @neowong-taiwan , thanks.

**Comment by oldherl** [comment]
@MrBook2019 Which vendor register did you change? And what software did you use to dump the registers on linux and windows? Thanks
