### ISSUE TITLE
[Question] How do the kcontrols get restored upon DSP resume to the firmware side?

### ISSUE THREAD

**Issue by paulstelian97** [thesofproject/linux#4297]
Hello, in https://github.com/thesofproject/sof/pull/7129 I have made it so that the sof-ctl command can fail if the data blob is invalid upon change of a binary kcontrol. That pull request works fine so long as there is no suspend-resume cycle.

However, on a suspend-resume cycle the kcontrol is restored to the invalid data blob that was rejected by the firmware, as opposed to the last accepted version. That causes the next playback attempt to fail at hw_params.

Without that pull request, sof-ctl succeeds and the playback stops immediately, with no way to resume it.

I am requesting advice on how to deal with this on the kernel side. My intention is to fall back to the old bytes control value if the new one receives an error from the firmware side.

**Comment by paulstelian97** [comment]
As a follow-up question: if the firmware rejects a blob, how do we ensure the kernel side cache holds the previous, valid kcontrol value? Say that we only do that for bytes controls since that's what applies for the specific bug I'm looking at, but considering all kinds of controls is probably wise.

Late edit: Apparently the kernel has no mechanism of falling back to a previous valid configuration if sof-ctl sends a config that is invalid in _any_ way, including in ways that make it not even try to verify with the firmware. See https://github.com/thesofproject/linux/blob/96f8e58b6176b0cc12ec57185a2faf45f431cb96/sound/soc/sof/ipc3-control.c#L385-L406

Here the cdata field is updated despite it being invalid, and said field is read upon suspend-resume cycles.

**Comment by plbossart** [comment]
@juimonen @jsarha @ranj063 this question is probably for you?

**Comment by paulstelian97** [comment]
I have sent pull request #4314 which deals with my specific error. I'm almost certain that it needs significantly more improvement before it can actually be merged (which includes covering more use cases).

**Comment by paulstelian97** [comment]
In #4314 I have added some support for proper kernel side handling of kcontrol blobs that the firmware rejects. While it isn't perfect, it definitely helps with most of my issues.

I think this can be closed for the moment. If anyone else still finds this relevant feel free to reopen.
