### ISSUE TITLE
[BUG] error: the DSP is not enabled on this platform, aborting probe

### ISSUE THREAD

**Issue by unz3r0** [thesofproject/linux#4316]
**Describe the bug**
The kernel decides that `snd_hda_intel` is the correct driver/module for the sound card. On my research, I found that `sof-audio-pci-intel-cnl` or `snd_soc_skl` seems to be supported.

https://github.com/torvalds/linux/blob/master/sound/soc/sof/intel/pci-cnl.c#L122
https://github.com/torvalds/linux/blob/master/sound/soc/intel/skylake/skl.c#L1174
https://linux-hardware.org/?id=pci:8086-a348-103c-83e2

But DSP seems not to be available on my platform. What ever that means. And I am unsure if that is a bug of SOF, or it is related to the HP firmware.

If I miss something and have done something wrong. Please let me know.

**To Reproduce**
Add `options snd-intel-dspcfg dsp_driver=2` or `options snd-intel-dspcfg dsp_driver=3` to `/etc/modeprobe.d/sound.conf` and reboot.

**Reproduction Rate**
Every time.

**Expected behavior**
It should detect it and make sound useable.

**Impact**

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 6.1.24-1-MANJARO
    * SOF: 2.2.4
2) Name of the topology file
    * Topology: no idea?
3) Name of the platform(s) on which the bug is observed.
    * Platform: Intel Cannon Lake PCH cAVS vendor: Hewlett-Packard

**Screenshots or console output**
`options snd-intel-dspcfg dsp_driver=2`
```
[    3.701278] snd_soc_skl 0000:00:1f.3: enabling device (0100 -> 0102)
[    3.701525] snd_soc_skl 0000:00:1f.3: NHLT table not found
[    3.701527] snd_soc_skl 0000:00:1f.3: no nhlt info found, continuing to try to enable HDAudio codec
[    3.701747] snd_soc_skl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    3.764000] snd_soc_skl 0000:00:1f.3: tplg fw  load failed with -22, trying alternative tplg name skl_hda_dsp_generic-tplg.bin
[    3.764357] snd_soc_skl 0000:00:1f.3: Direct firmware load for skl_hda_dsp_generic-tplg.bin failed with error -2
[    3.764361] snd_soc_skl 0000:00:1f.3: tplg skl_hda_dsp_generic-tplg.bin failed with -2, falling back to dfw_sst.bin
[    3.764381] snd_soc_skl 0000:00:1f.3: Direct firmware load for dfw_sst.bin failed with error -2
[    3.764382] snd_soc_skl 0000:00:1f.3: Fallback tplg fw dfw_sst.bin load failed with -2
[    3.764383] snd_soc_skl 0000:00:1f.3: Failed to init topology!
[    3.764384] snd_soc_skl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -2
```
`options snd-intel-dspcfg dsp_driver=3`
```
[    3.593472] sof-audio-pci-intel-cnl 0000:00:1f.3: enabling device (0100 -> 0102)
[    3.593626] sof-audio-pci-intel-cnl 0000:00:1f.3: error: the DSP is not enabled on this platform, aborting probe
[    3.593628] sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to probe DSP -19
[    3.593629] sof-audio-pci-intel-cnl 0000:00:1f.3: error: sof_probe_work failed err: -19
```
```
Machine:
  Type: Desktop System: HP product: HP EliteDesk 800 G4 DM 65W v: N/A
    serial: <filter> Chassis: type: 6 serial: <filter>
  Mobo: HP model: 845A v: KBC Version 07.D2.00 serial: <filter> UEFI: HP
    v: Q21 Ver. 02.22.00 date: 11/29/2022
```
```
Audio:
  Device-1: Intel Cannon Lake PCH cAVS vendor: Hewlett-Packard
    driver: snd_soc_skl v: kernel bus-ID: 1-5:2
    alternate: snd_hda_intel,snd_sof_pci_intel_cnl chip-ID: 046d:0825
    bus-ID: 00:1f.3 class-ID: 0102 chip-ID: 8086:a348 serial: <filter>
    class-ID: 0403
  Device-2: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo
  API: ALSA v: k6.1.24-1-MANJARO status: kernel-api tools: alsamixer,amixer
  Server-1: sndiod v: N/A status: off tools: aucat,midicat,sndioctl
  Server-2: JACK v: 1.9.22 status: off tools: N/A
  Server-3: PipeWire v: 0.3.69 status: active with: 1: pipewire-pulse
    status: active 2: wireplumber status: active 3: pipewire-alsa type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
```

**Comment by plbossart** [comment]
@unz3r0 you cannot use the SOF driver on this device
a) the DSP is not enabled and 
b) there are no NHLT tables so no DMIC in the first place.

You have to use options snd-intel-dspcfg dsp_driver=0 and let the autoselection proceed to use snd-hda-intel. 

If the microphone does not work, then it's an HDaudio codec issue.

**Comment by unz3r0** [comment]
@plbossart Thank you for your confirmation, but I need a little clarification:

It seems, a DSP (Digital Signal Processor) is a hardware component, which is needed by SOF, even if the chipID of the sound card is supported. 

NHLT tables are like ACPI Tables located in the BIOS/Firmware of the system.

Is that correct? It would be good to have a little reference to this problem to understand the basic cause of the error. Thank you.

PS: The microphone works again with `snd-hda-intel`. I have no idea why it works again, but that is out of topic here.

**Comment by plbossart** [comment]
The hardware is present but disabled by your BIOS, and that configuration is locked. There's nothing we can do here at the kernel level to invalidate this decision made by your PC vendor. And since the DSP is disabled, there's no support for DMIC therefore no need to add NHLT for DMIC support.

We have seen multiple devices like this, and that's why the snd-hda-intel driver is still used.

**Comment by unz3r0** [comment]
Alright. Thank you. That makes sense.
