### ISSUE TITLE
[BUG] ESS8336 inbuilt microphone not capturing sound

### ISSUE THREAD

**Issue by bretantonio** [thesofproject/linux#4317]
**ESS8336 Microphone inbuilt mic not recording anything**
Without modifications the kernel calls `sof-apl-es8336-ssp1.tplg`. This makes `arecord -l` not show DMIC's, it just shows
```
**** List of CAPTURE Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
I then followed [sof suggestions](https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html), I `enabled options snd_sof_intel_hda_common dmic_num=4` then loaded `sof-apl-es8336-dmic4ch-ssp1.tplg`, now I get the following `arecord -l` output
```
**** List of CAPTURE Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 1: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 2: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
I then ran `arecord -Dhw:0,1 -c4 -r48000 -sS32_LE -d 10 test.wav`, the file channel 1 is blank. Channel 2 - 4 contain one click at the beginning of the file. Similar thing happens when I use `sof-apl-es8336-dmic4ch-ssp1.tplg`, Channel one blank, channel 2 has a click at the beginning no sound is being pick up other than that.

What can I do for it to pick audio, it was working in windows so the mic works.
I am on Ubuntu 23.04 Kernel: 6.2.0-20
[dmesg.log](https://github.com/thesofproject/sof/files/11289317/dmesg.log)
[recorded audio](https://user-images.githubusercontent.com/8401604/233454956-726e47bf-d242-43ec-92a4-9c1ce5375b62.jpg)

**Comment by plbossart** [comment]
I don't know what to tell you @bretantonio 

The driver does not find any information related to DMICs on your system:

````
[    9.667702] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-apl 0000:00:0e.0: dmic number 0 max_ch 0
````

You can override this parameter all you want, it's not going to make digital microphones appear.

The most likely problem is that you microphone is handled by the ES8336 codec, and that brings us back to the problem that this codec is not well supported in Linux. I tried and decided to stop given the proliferation of configurations and codec vendor/OEM lack of support.

If you want a quick solution, get a USB mic. That's the only pragmatic solution I am afraid.

**Comment by bretantonio** [comment]
Actually I went into the BIOS and there was an option to enable dmic channels to 2/4 channels now and exposing them on  NHLT table. Now the kernel recognises the channels. 
```
[    1.319021] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-apl 0000:00:0e.0: found 2 format definitions
[    1.319024] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-apl 0000:00:0e.0: max channels found 4
[    1.319027] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-apl 0000:00:0e.0: Array with 4 dmics
[    1.319030] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-apl 0000:00:0e.0: dmic number 4 max_ch 4
```
`arecord` is still blank on all channels no capture
[dmesg.log](https://github.com/thesofproject/linux/files/11295171/dmesg.log)

**Comment by bretantonio** [comment]
[amltables.dsl.txt](https://github.com/thesofproject/linux/files/11509611/amltables.dsl.txt)

Here is a list of ACPI Tables the NHLT is empty and won't decompile

[acpidump.txt](https://github.com/thesofproject/linux/files/11509626/acpidump.txt)

**Comment by plbossart** [comment]
"arecord is still blank on all channels no capture"

What does this mean @bretantonio ?
a) there are no capture devices
b) the DMIC device is present but capturing on this device yields a silence file
c) something else

Also I am not sure what you are trying to do with NHLT.

**Comment by bretantonio** [comment]
b) The dmic device is present but the recorded file has not sound

**Comment by plbossart** [comment]
Not sure what to suggested next @bretantonio, we've been using DMICs for a long time with no issues, so either the NHLT information is incorrect or your hardware is wired sideways.

**Comment by bretantonio** [comment]
As I had stated with the topology `sof-apl-es8336-ssp1.tplg`, no dmics appear when running `arecord -l`
```
**** List of CAPTURE Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

With the topology `sof-apl-es8336-dmic4ch-ssp1.tplg`, dmics appear when running `arecord -l`
```
**** List of CAPTURE Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 1: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 2: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
There is an option in BIOS to enable DMIC and switch channels to 2 channels or 4 channels. What I am not sure of is whether the option to change dmics channel is an option generally available, maybe the manufacturer enabled the ability to change channels because there are some of their devices which have 2 channels and some 4.

When I choose 2/4 channels and use audacity to record the wave pulse will not change like it would if sound was being input. So, maybe the hardware is wired in a different way, or the tables are wrong. I was just updating information maybe an idea could point out to why the mics are not working.

**Comment by bretantonio** [comment]
If you can also look into my volumes maybe they are the issue..

here is `amixer -c0`
[volumes.txt](https://github.com/thesofproject/linux/files/11513704/volumes.txt)

**Comment by bretantonio** [comment]
Inbuilt microphone is being detected 
```
Linux lenovo 6.8.0-11-generic #11-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 14 00:29:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
