### ISSUE TITLE
SoundWire: ADLP_RVP_SDW_IPC4ZPH: pm_runtime error

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#4328]
````
[ 1336.726222] kernel: rt711 sdw:0:025d:0711:00: runtime PM trying to activate child device sdw:0:025d:0711:00 but parent (sdw-master-0) is not active
````

https://sof-ci.01.org/linuxpr/PR4325/build4490/devicetest/index.html?model=ADLP_RVP_SDW_IPC4ZPH&testcase=check-kmod-load-unload-after-playback

[dmesg.log](https://github.com/thesofproject/linux/files/11325603/dmesg.log)

**Comment by plbossart** [comment]
Also seen in https://sof-ci.01.org/sofpr/PR7513/build6451/devicetest/index.html?model=ADLP_RVP_SDW_IPC4ZPH&testcase=check-kmod-load-unload-after-playback

This is not a random case if there are two instances. @bardliao FYI, not sure what caused this?

**Comment by plbossart** [comment]
Kernel commit 43dce32918b9 shows that issue, not sure if this was seen earlier than April 24.

**Comment by plbossart** [comment]
not able to reproduce the issue on the same device with kernel commit ff288622cdac0033ce16f1e561e42b068f8ff508

@keqiaozhang @fredoh9 please monitor if you see more sightings of this pm_runtime issue.

**Comment by bardliao** [comment]
> Kernel commit [43dce32](https://github.com/thesofproject/linux/commit/43dce32918b94b430db5b9f1d3e3733de00b9188) shows that issue, not sure if this was seen earlier than April 24.

I will take a look.

**Comment by bardliao** [comment]
@plbossart How did you reproduce this issue? I ran the check-kmod-load-unload-after-playback.sh test on sh-adlp-rvp-sdw-01, but can't reproduce it with latest topic/sof-dev branch or the https://github.com/thesofproject/linux/commit/43dce32918b94b430db5b9f1d3e3733de00b9188 commit.

**Comment by plbossart** [comment]
I cannot reproduce the error either @bardliao, and the error disappears if we run the test twice with the same PR #4325 

Not sure what happened, we'll probably have to wait to see if this occurs again and try to reproduce.

**Comment by fredoh9** [comment]
I scanned the test result database, it happened 3 times with only PR test(7512 7513 4325), not with daily test yet.
Each failure with different device. I can notice all 3 was failed on aplay with PCM 31, deep buffer. I will keep watching and try to reproduce it also.

**Comment by fredoh9** [comment]
I'm able to reproduce the problem with sof pr7512 build(PR7512-6508), kernel hash is ff288622cdac.
Let me try same test with sof main again, I tested it before but not stress tested.

**Comment by fredoh9** [comment]
yes, I can reproduce the problem with topic/sof-dev(ff288622cdac) and sof main (0c7db9a58ea6).

first skip HDMI pipelines and do more iterations(-l 10). With this command it fails in 10-15 min.

```bash
export NO_HDMI_MODE=true
TPLG=/lib/firmware/intel/avs-tplg/sof-adl-rt711-4ch.tplg MODEL=ADLP_RVP_SDW_IPC4ZPH ~/sof-test/test-case/check-kmod-load-unload-after-playback.sh -l 10
```

**Comment by bardliao** [comment]
> yes, I can reproduce the problem with topic/sof-dev([ff28862](https://github.com/thesofproject/linux/commit/ff288622cdac0033ce16f1e561e42b068f8ff508)) and sof main (0c7db9a58ea6).
> 
> first skip HDMI pipelines and do more iterations(-l 10). With this command it fails in 10-15 min.
> 
> ```shell
> export NO_HDMI_MODE=true
> TPLG=/lib/firmware/intel/avs-tplg/sof-adl-rt711-4ch.tplg MODEL=ADLP_RVP_SDW_IPC4ZPH ~/sof-test/test-case/check-kmod-load-unload-after-playback.sh -l 10
> ```

@fredoh9 I still can't reproduce the issue even with -l 20.

**Comment by kv2019i** [comment]
Seen in https://sof-ci.01.org/sofpr/PR7330/build6485/devicetest/index.html

**Comment by bardliao** [comment]
> Seen in https://sof-ci.01.org/sofpr/PR7330/build6485/devicetest/index.html

hmm, it is a different test case. And it seems the issue only happens on the PR test, not daily test?

**Comment by ranj063** [comment]
@bardliao the issue is hard to repruduce and has been seen with multiple PR tests

**Comment by bardliao** [comment]
@plbossart With #4334, I got below dmesg.
[dmesg_adl_runtime_pm_err.txt](https://github.com/thesofproject/linux/files/11382457/dmesg_adl_runtime_pm_err.txt)

Looking at the log, I think I got the issue now.
Please see below calling sequence.
[sdw_handle_slave_status](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/bus.c#L1823)
 -> [sdw_update_slave_status](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/bus.c#L1938)
 -> [rt711_update_status](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt711-sdw.c#LL317C12-L317C31)
-> [rt711_io_init](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt711.c#L1213)
->  [pm_runtime_set_active](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt711.c#L1236)
-> [pm_request_resume(&slave->dev);](https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/soundwire/bus.c#L1959)

pm_runtime_set_active(&slave->dev); in rt711_io_init may be called before pm_request_resume(&slave->dev); in sdw_handle_slave_status. And we will see the `runtime PM trying to activate child device sdw:0:025d:0711:00 but parent (sdw-master-0) is not active` error when it happens. @shumingfan FYI

**Comment by plbossart** [comment]
Not following @bardliao, pm_runtime_set_active() is only called in codecs for the first_hw_init.

And if I look at the sequence:

````c
	ret = sdw_update_slave_status(slave, status[i]);
		if (ret < 0)
			dev_err(&slave->dev,
				"Update Slave status failed:%d\n", ret);
		if (attached_initializing) {
			dev_dbg(&slave->dev,
				"signaling initialization completion for Slave %d\n",
				slave->dev_num);

			complete(&slave->initialization_complete);

			/*
			 * If the manager became pm_runtime active, the peripherals will be
			 * restarted and attach, but their pm_runtime status may remain
			 * suspended. If the 'update_slave_status' callback initiates
			 * any sort of deferred processing, this processing would not be
			 * cancelled on pm_runtime suspend.
			 * To avoid such zombie states, we queue a request to resume.
			 * This would be a no-op in case the peripheral was being resumed
			 * by e.g. the ALSA/ASoC framework.
			 */
			pm_request_resume(&slave->dev);
		}
````

So that's a logical sequence, no?

I think the problem is more that there's something between the codec and the host, e.g. I am not sure that the host is fully resumed and active before the peripheral requests the resume.

**Comment by bardliao** [comment]
@plbossart Yes, I was wrong. After checking a working dmesg, The parent (sdw-master-0) is not resumed by `pm_request_resume(&slave->dev);` here.
sdw-master-0 is supposed to be resume when we request rt711 resume.
When we start aplay with rt711, snd_soc_pcm_component_pm_runtime_get will call `pm_runtime_get_sync` for each component. Which are `soundwire_intel.link.0` and `sdw:0:025d:0711:01`. When `soundwire_intel.link.0` is powered up, rt711 will be attached. So, if rt711_update_status -> rt711_io_init is called before sdw-master-0 is resume **AND rt711->first_hw_init is false**, we will see the `runtime PM trying to activate child device sdw:0:025d:0711:00 but parent (sdw-master-0) is not active` error.
It is 100% reproducible that sdw-master-0 is not active when rt711_io_init is called if I add 1 sec delay in for_each_rtd_components https://github.com/thesofproject/linux/pull/4334/commits/e21606315f5af2484d47a020e48e7ffe0bda2a7a
But I don't see how can rt711->first_hw_init be false when we test with aplay.

**Comment by plbossart** [comment]
@bardliao would you happen to remember why we have pm_runtime() enabled and configured in master.c?

I thought that when we add the 'sdw-master-0' auxiliary device, the pm_runtime would be enabled only when we start the auxiliary device.

I don't recall why we added all this pm_runtime stuff in the master.c code, it seems like we are configuring pm_runtime twice and that seems completely inconsistent.

We already had this message with 20c620dd51a3ebe7a72dc1445026f3cba3f64b64 but I don't understand what I suggested at the time....

**Comment by bardliao** [comment]
@plbossart No, I can't remember why we have pm_runtime() enabled and configured in master.c. But I guess it is because that the soundwire_intel.link device is the parent of sdw-master-0 device. As a result, sdw-master-0 will not be active automatically when we request soundwire_intel.link device be active.
I got some useful dmesg log now.
[dmesg_adl_ok_2.txt](https://github.com/thesofproject/linux/files/11429651/dmesg_adl_ok_2.txt)
[dmesg_adl_err_3_bard.txt](https://github.com/thesofproject/linux/files/11429652/dmesg_adl_err_3_bard.txt)
The issue is that somehow rt711 is not attached when intel_link_power_up is first triggered after SOF is probed.
It means rt711_io_init is not called at that moment.
Then intel_link_power_up is triggered and rt711 is attached when we start a playback.
And we got the "runtime PM trying to activate child device sdw:0:025d:0711:00 but parent (sdw-master-0) is not active" error if 
`sdw-master-0` is not active.
In fact, `sdw-master-0` is usually not active when rt711_io_init is called when we start a playback, but there is no issue we won't try to enable pm_runeime after 1st attached.
The question is that why isn't rt711 attached when the link is powered up first time? And can we prevent the error if the codec is not attached when SOF is probed?

**Comment by plbossart** [comment]
I think I know what the problem is @bardliao 

We've changed the sequence on power-up, with a longer reset, which means the codec can take more time to show up as attached.

So the framework will try to resume the codec, but it's not present yet so it's not attached and returns -EACCESS (-13) pm_runtime not enabled.

So the link.0 is resumed, but the sdw-master-0 is not because it's not resumed by the codec resume, and then later on we do a set_active() in the io_init which fails because technically sdw-master-0 was never resumed....

we really have a big confusion between the auxiliary device and the sdw-master-X devices. All the runtime_pm is handled at the auxiliary device level and the codec device level, the sdw-master-X level is only made active by the codec resuming, but when we use the set_active on the codec device the sdw-master-X level was never properly resumed.

we can insert a pm_runtime_request_resume(bus->dev) somewhere, either in the intel_auxdevice.c or the bus.c code, but it's quite racy. Need to think a bit more on this.

**Comment by plbossart** [comment]
I am a bit lost on your results though @bardliao.

What worries me is that you are going an 'aplay' before the codec device is operational:

````
 rt711 sdw:0:025d:0711:00: bard: snd_soc_pcm_component_pm_runtime_get i 1 called pm_runtime_get_sync ret -13
 ````

 That means -ENOACCESS, which means pm_runtime_enable() has not been called yet.
 
 Your tests also contains device removal, so I have no idea how you reached that point.

The main problem is that even if we 'fix' the pm_runtime_set_active() error, the point is that the framework did not increase the refcount so the codec device will suspend after 3s.

So there's two problems here
a) how do we make sure the parent sdw-master-0 is active
b) how do we make sure the pm_runtime_get_sync() succeeds

**Comment by bardliao** [comment]
@plbossart I tested with `~/sof-test/test-case/check-kmod-load-unload-after-playback.sh -l 10`. Keep running check-kmod-load-unload-after-playback.sh until it failed.

**Comment by plbossart** [comment]
issue also seen with https://sof-ci.ostc.intel.com/#/result/planresultdetail/25352?model=ADLP_RVP_SDW_IPC4ZPH&testcase=check-playback-10sec

**Comment by plbossart** [comment]
so the issue really seems to only occur in the first playback/record *AFTER* doing a kmod remove/insert test.

I wonder if the only way to change this is to make the codecs pm_runtime active in the probe, but put all registers in cache-only mode until the moment where the codec is initialized.

**Comment by bardliao** [comment]
> so the issue really seems to only occur in the first playback/record _AFTER_ doing a kmod remove/insert test.

Yes, I think so. For some reason, the codec is always attached when we start the first playback/record. Though the codec is not attached in startup.

> 
> I wonder if the only way to change this is to make the codecs pm_runtime active in the probe, but put all registers in cache-only mode until the moment where the codec is initialized.

Is there any way that can guarantee the codec will be attached in startup? I still don't get why the codec is not attached in startup.

**Comment by plbossart** [comment]
Clearly there's a timing difference between the first time the card is used and after the kmod scripts are used.

Maybe this race condition is due to the kmod scripts?

We insert/probe the codec modules, which will register everything the card needs before the card is created by the SOF driver. If we did the opposite, most likely the problem would go away: the codec would be attached but without a driver, and the card would be waiting for the dependencies?

Alternatively adding a 1s delay after the probe happens may prevent the CI scripts from playing too early before the card is ready.
