### ISSUE TITLE
SoundWire: ADLP_RVP_SDW_IPC4ZPH: multiple-pipeline-all IPC timeout

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#4329]
https://sof-ci.01.org/linuxpr/PR4326/build4526/devicetest/index.html?model=ADLP_RVP_SDW_IPC4ZPH&testcase=multiple-pipeline-all

[dmesg.log](https://github.com/thesofproject/linux/files/11325612/dmesg.log)

[mtrace.log](https://github.com/thesofproject/linux/files/11325633/mtrace.log)

**Comment by plbossart** [comment]
@fredoh9 can you check if this error happens all the time?

It's a weird case because the first error is with the new multiple-pipeline-all.sh script, playback and capture seem to work fine.

**Comment by keqiaozhang** [comment]
Looks like this is a duplicate of https://github.com/thesofproject/sof/issues/7361.
We don't have similar issues in CI now. This bug can be closed.
