### ISSUE TITLE
[BUG] No sound devices detected on Dell XPS 9315 2-in-1

### ISSUE THREAD

**Issue by bblacher** [thesofproject/linux#4399]
**Describe the bug**
I don't get sound from the onboard devices on my Dell XPS 2-in-1 9315. Gnome only shows "Dummy Output".

**To Reproduce**
Install Arch Linux on a Dell XPS 2-in-1 9315 and install sof-firmware, pipewire, alsa-firmware and experience the lack of sound.

**Expected behavior**
Have working speakers & microphone.

Output of dmesg | grep sof-audio:

> [    5.264681] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
> [    5.264832] sof-audio-pci-intel-tgl 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
> [    5.264846] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
> [    5.265019] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
> [    5.265271] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
> [    5.272026] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
> [    5.288907] sof-audio-pci-intel-tgl 0000:00:1f.3: No SoundWire machine driver found
> [    5.288910] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
> [    5.288911] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
> [    5.288913] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 0
> [    5.290121] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
> [    5.290124] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
> [    5.290134] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
> [    5.384252] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
> [    5.384257] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
> [    5.499540] sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:22:1 Kernel ABI 3:23:0

**Comment by plbossart** [comment]
please attach the result of 'alsa-info', we track Dell devices by 'System SKU' not models.

**Comment by bblacher** [comment]
I put it in a [gist](https://gist.githubusercontent.com/bblacher/d3e1e5855620931c21cf073b163b8669/raw/ecf8f04cab75f4ce81803895189c92123d912c4f/gistfile1.txt).

The System SKU seems to be 0B34.

**Comment by plbossart** [comment]
ok, that's an unknown/unsupported SKU. Gah. I created a new label, maybe that will help at some point.

[8086:51cc] means  PCI_DEVICE(0x8086, 0x51cc), /* ADL-M */

Is there a way you can attach the DSDT:

cat /sys/firmware/acpi/tables/DSDT > dsdt.dat
iasl -tc dsdt.dsl
cp dsdt.dsl dsdt.dsl.txt

and attach the last file.

**Comment by bblacher** [comment]
[Here you go](https://gist.githubusercontent.com/bblacher/d1dd02f441f7a9402370f5c568940f36/raw/f6026a75f2d98566fa3e652bb19524c5ee24184e/dsdt.dsl.txt)

**Comment by plbossart** [comment]
from the DSDT, I can see this:

````
Name (_ADR, 0x000030025D071401)  // _ADR: Address <<< RT714 mic codec on link0
Name (_ADR, 0x000130025D131601)  // _ADR: Address <<< RT1316 amplifier on link1
````

Can you confirm you don't have a 3.5 mm jack on this device? we've seen variants like this before.

**Comment by bblacher** [comment]
I don't have a 3.5 mm jack. The only IO I have are two USB-C ports.

**Comment by plbossart** [comment]
Can you try the patches in PR #4405 ? 

You will also need to unzip and add this file 
[sof-adl-rt1316-l1-mono-rt714-l0.tplg.gz](https://github.com/thesofproject/linux/files/11627336/sof-adl-rt1316-l1-mono-rt714-l0.tplg.gz)
 in /lib/firmware/intel/sof-tplg

**Comment by bblacher** [comment]
@plbossart Do you maybe have some instructions on how to try the patches for me?

The unzip-and-add-file part is clear to me.

**Comment by bblacher** [comment]
Actually, nevermind. I just found [this](https://thesofproject.github.io/latest/getting_started/setup_linux/install_locally.html).

I'll try your patches tomorrow.

**Comment by bblacher** [comment]
@plbossart 
I installed fedora on a separate partition in order to follow the install instructions more easily, this is why the files attached here show fedora instead of arch.

I just tried your patches and they didn't fix the issue for me. Maybe the topology file is the issue here. On my fedora system all of the topology files in `/lib/firmware/intel/sof-tplg` are compressed with .xz, I've tried adding your topology file both extracted as you told me as well as compressed with xz default options, neither gets Gnome to pick up my speakers, it still just shows "Dummy Output".

Anyways, here is an updated [alsa-info.txt](https://gist.githubusercontent.com/bblacher/bbcd0c69f3b3b201d750ec2aa481ec27/raw/fe6b152c40e0f2393211dd059750a61d0f9c3ae5/alsa-info.txt.XFbrc95u8j) and an updated [dsdt.dsl.txt](https://gist.githubusercontent.com/bblacher/73d19a76f02184004f816c46f9a8ba80/raw/81076ce4ec6125ca7d4b8bffaaa82b5de54f121c/dsdt.dsl.txt).

**Comment by plbossart** [comment]
looks like you are not even loading the SOF driver.

Can you try to add this to /etc/modprobe.d/alsa-base.conf

options snd_intel_dspcfg dsp_driver=3

and add this to file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/11636354/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf

**Comment by bblacher** [comment]
Still not working. 
[Updated dmesg | grep sof-audio](https://gist.githubusercontent.com/bblacher/a4b4481daf568b2afbdce0b8149273df/raw/3a88bfa8313ddea2cb1cd0b5df3e2ae89acdbf94/dmesg.txt) 
[Updated alsa-info.txt](https://gist.githubusercontent.com/bblacher/e215e827f0223635e2c28677d7c38eaa/raw/399d04ca782c77a4a33f070dae7217fa1004ad12/alsa-info.txt.9EEJ296osA) 
[Updated dsdt.dsl.txt](https://gist.githubusercontent.com/bblacher/00e7afa6aac731002845fc1f141040dd/raw/626578104b9c7ac17758be989270fb4a1227210e/dsdt.dsl.txt)

**Comment by bblacher** [comment]
@plbossart 
Do you have any more instructions for me? I still wasn't able to get the sound working.

**Comment by plbossart** [comment]
@bblacher Can you provide the entire dmesg, not filtered? I can't see the SoundWire related stuff with your grep filter.

**Comment by bblacher** [comment]
@plbossart I don't have my device with me right now, I'll get back to you with the logs on Sunday.

**Comment by bblacher** [comment]
[Here you go](https://gist.githubusercontent.com/bblacher/ecb214a08d824c27af49b756cd37038d/raw/f2271bcc253c1fbe6bc4a2453a300edf60a68b52/dmesg.txt)

**Comment by plbossart** [comment]
Wow, that's wild

````
[   15.657219] snd_sof_intel_hda_common:hda_init_caps: sof-audio-pci-intel-tgl 0000:00:1f.3: skipping SoundWire, no links enabled
````

Of course it won't try SoundWire if it's not exposed in ACPI tables...

Can you retry with this "options snd_intel_dspcfg dsp_driver=3" remove and this updated file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/11725491/sof-dyndbg.conf.txt)
as /etc/modprobe.d/sof-dyndbg.conf (the extension matters).

**Comment by bblacher** [comment]
Same thing

Btw., could this be the issue here?

> "Nothing particularly strange here, most notable is probably just the quick revert of the module loading trial that caused problems for people in rc4 depending on just random timing luck (or rather, lack there-of). So if you tried rc4, and some devices randomly didn't work for you, that was likely the issue." - from the Linux 6.4-rc5 announcement

Anyways, here are my updated files:
[dmesg.txt](https://gist.githubusercontent.com/bblacher/25b45938155760ed0befec079515d87a/raw/86c4a9506b0f77dbf433255cb8b1a927c14c6760/dmesg.txt) 
[dsdt.dsl.txt](https://gist.githubusercontent.com/bblacher/d2e22a2098b36cf00a7af75746a5caa0/raw/595eae52cdc3c67ce62c2b934b0866a72901a2a6/dsdt.dsl.txt) 
[alsa-info.txt](https://gist.githubusercontent.com/bblacher/1242e741a2766bff463a712dfb311b78/raw/97e3fcdb4869c38b34bd3b1492f7363c89bfe52c/alsa-info.txt.YNUQW9QST8)

**Comment by plbossart** [comment]
I don't get what happens @bblacher 

Can you double-check you have CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE enabled?

The following code should detect SoundWire, but if you didn't compile it in then nothing will happen :-)


````c
#if IS_ENABLED(CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE)
static int snd_intel_dsp_check_soundwire(struct pci_dev *pci)
{
	struct sdw_intel_acpi_info info;
	acpi_handle handle;
	int ret;

	handle = ACPI_HANDLE(&pci->dev);

	ret = sdw_intel_acpi_scan(handle, &info);
	if (ret < 0)
		return ret;

	return info.link_mask;
}
#else
static int snd_intel_dsp_check_soundwire(struct pci_dev *pci)
{
	return 0;
}
#endif
````

if the code is enabled, you should see this:
````
	if (!count) {
		dev_warn(&adev->dev, "No SoundWire links detected\n");
		return -EINVAL;
	}
````

**Comment by bblacher** [comment]
I currently don't have the time to dig into this. I'll take a look at this and maybe recompile the kernel with the patches you gave me by the end of next week.

**Comment by paulmenzel** [comment]
@plbossart, I think Dell does not officially support GNU/Linux on this device, but can’t you establish an unofficial channel, so users do not have to report this?

**Comment by plbossart** [comment]
> @plbossart, I think Dell does not officially support GNU/Linux on this device, but can’t you establish an unofficial channel, so users do not have to report this?

I tried since CometLake, it's been 3 generations of devices. 
All I can do is tag the bugs as "DELL SDW SKU". Maybe at some point someone will see the light.
