### ISSUE TITLE
Stress Test: repetitive unloading and reloading driver causes computer halted on UP^2  and CNL using nocodec topology

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/linux#44]
Run `soft/kmod_scripts/sof_bootloop.sh` cause computer halted on UP^2  and CNL using nocodec topology

description：
In "sof_bootone.sh" , the sleep time is 1 second .  After about 2 to 4 cycles ， the system halted and can't resume anymore .  Can't get dmesg log since computer already halted .

System Environment:
sof-dev:  6786cd0b68def014764173c978b835346097f9be
sof:   d696d8f8bad1490575a8293e0982786300eb52db
soft:  a25f4b0b02b51d186d2a9c6d73c8126784a61997
using test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg 

reproduce steps:
./sof_bootloop.sh

log:
[boot_0.boot.log](https://github.com/thesofproject/linux/files/2213184/boot_0.boot.log)
[boot_1.boot.log](https://github.com/thesofproject/linux/files/2213185/boot_1.boot.log)
[boot_2.boot.log](https://github.com/thesofproject/linux/files/2213186/boot_2.boot.log)

**Comment by RanderWang** [comment]
I tested 3000 cycles on BDW, no such issue

**Comment by ZhendanYang** [comment]
Latest test with latest code base find out something new:
run 'soft/kmod_scripts/sof_bootloop.sh' on up^2 using test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg causes no problem.
run 'soft/kmod_scripts/sof_bootloop.sh' on cannonlake using test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24000k-nocodec.tplg cause firmware load fail.

dmesg.log:
[dmesg.log](https://github.com/thesofproject/linux/files/2252796/dmesg.log)

**Comment by mengdonglin** [comment]
stress test on module unload/reload is not priority atm.

**Comment by juimonen** [comment]
@zhuqingliang is this still an issue? I could run bootloop.sh in up2 without  errors...

**Comment by wenqingfu** [comment]
from the last few days' regression report, I think it can conclude it's fixed. Thank you for following up with this bug, @juimonen
