### ISSUE TITLE
built-in audio doesn't work - microphone, speakers one of them is not working - Del G3 3590 with Ubuntu 22.04, 22.10, 23.04

### ISSUE THREAD

**Issue by jboundaries** [thesofproject/linux#4404]
Built-in audio is not working in laptop Dell G3 3590 with Ubuntu 22.04, Ubuntu 22.10, and Ubuntu 23.04. 

| Audio I/O | Results |
| - | - |
| Microphone - Built-in Audio | dosn’t work if built-in speakers work. | 
| Speakers - Built-in Audio | dosn’t work if built-in microphone works. |
| Headset Microphone  | Working |
| Headset Speaker  | Working |

Here are the **_observations with config changes_**

i) blacklist snd-hda-intel 
blacklist snd-soc-skl
With the above config at at /etc/modprobe.d/alsa-base.conf, built-in mic is fine, Internal speakers are not working.

ii) GRUB_CMDLINE_LINUX_DEFAULT="quiet splash snd_hda_intel.dmic_detect=0" or
GRUB_CMDLINE_LINUX_DEFAULT="quite splash snd_intel_dspcfg.dsp_driver=1"
With the above config at grub, built in mic not working, built in speakers are fine.

iii) GRUB_CMDLINE_LINUX_DEFAULT="quite splash" or
GRUB_CMDLINE_LINUX_DEFAULT="quite splash snd_intel_dspcfg.dsp_driver=3"
With the above configs  at grub, built-in mic is fine, Internal speakers are not working.

https://github.com/thesofproject/linux/issues/1877#issuecomment-596600017
https://askubuntu.com/questions/1243369/sound-card-not-detected-ubuntu-20-04-sof-audio-pci

**_System info_**

alsa-info http://alsa-project.org/db/?f=306c16560f8211df12a74df3d8443f5101ff6738
firmware-sof-signed is already the newest version (2.2.4-1). 
libasound2 is already the newest version (1.2.8-1build1).
/usr/share/alsa/ucm - no files
/usr/share/alsa/ucm2 - have files

How to make both built in microphone and speaker working?

thanks

**Comment by plbossart** [comment]
Not sure where to start @jboundaries, this seems to be a regular codec and I don't see any specific quirks for this.

Codec: Realtek ALC3254 aka 295

@kv2019i any ideas?

**Comment by jboundaries** [comment]
Thanks for responding. 

If possible, please share steps for any tests that would provide additional info to guide me on this.

**Comment by kv2019i** [comment]
@plbossart  @jboundaries Hmm, I'm afraid the speaker requires a custom patch to get it working. @jboundaries what's the content of your: /lib/firmware/hda-jack-retask.fw ? 

SOF is still missing the "patch=" support, so you can't feed the retask output to SOF (and thus speaker won't work). 
https://github.com/thesofproject/linux/issues/2714

I.e. https://github.com/thesofproject/linux/issues/2714 would need to get implemented.

**Comment by jboundaries** [comment]
Thank you for the response. 

Here is the content of /lib/firmware/hda-jack-retask.fw

[codec]
0x10ec0295 0x10280949 0

[pincfg]
0x12 0x40000000
0x13 0x411111f0
0x14 0x90170110
0x16 0x411111f0
0x17 0x411111f0
0x18 0x411111f0
0x19 0x01a1913c
0x1a 0x411111f0
0x1b 0x01a1913d
0x1d 0x40400001
0x1e 0x411111f0
0x21 0x40f000f0

**Comment by plbossart** [comment]
Where does this /lib/firmware/hda-jack-retask.fw come from @jboundaries ?

**Comment by jboundaries** [comment]
Hi @plbossart, I don’t know if I get your question, haven’t done anything specific to get or update this file, should be from Ubuntu software install/upgrade/update. Last modified 7th Sep 2021.

![image](https://github.com/thesofproject/linux/assets/9209108/18e99743-f0ca-4c7e-8629-c84cbb8cf21b)

**Comment by plbossart** [comment]
@jboundaries I run Ubuntu and I don't have this file on my filesystem. In addition, it contains very specific 'verbs' that should be unique/relevant only for your device. 

@kv2019i  I am also not clear on how the snd-hda-intel picks up this specific patch as a kernel parameter.  Is this a grub command-line or /etc/modprobe.d configuration?

**Comment by kv2019i** [comment]
@plbossart I was also not aware that distributions would ship patch files directly. These are usually used with the GUI jack retask tool or copying from bugs (before the quirk is added to upstream kernel). Like https://gist.github.com/BXZ/48cd8173807676a1402cf4bc7928c0c0 and countless other examples. But here alsa-info dump shows patch is used and reporter confirmed the patch file exists on the system:
```
snd_hda_intel: patch=hda-jack-retask.fw,hda-jack-retask.fw,hda-jack-retask.fw,hda-jack-retask.fw
```

**Comment by plbossart** [comment]
Ah yes @kv2019i, I didn't see this in alsa-info

````
!!Modprobe options (Sound related)
!!--------------------------------
...
snd_hda_intel: patch=hda-jack-retask.fw,hda-jack-retask.fw,hda-jack-retask.fw,hda-jack-retask.fw
````

So yes definitively something that would not work with the SOF driver, known/old issue.

@jboundaries this is going to be really low compared to the existing priority, the best chances of "fixing" this would be to add a kernel quirk that gets rid of this patch.

**Comment by jboundaries** [comment]
Thank you for the responses.
