### ISSUE TITLE
[BUG] SDW: Invalid device for paging :0 on ADLP_SKU0B00_SDCA_IPC4ZPH, TGL

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4421]
**Describe the bug**
Observed this issue in CI test, it happens when doing kmod test. 
The reproduce rate is low, no reproductions with manual check and it only happened once in CI. Test ID:27322

**dmesg**
```
[  987.173703] kernel: sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
[  987.191815] kernel: input: sof-soundwire Headset Jack as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input45
[  987.191961] kernel: input: sof-soundwire HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input46
[  987.192136] kernel: input: sof-soundwire HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input47
[  987.192282] kernel: input: sof-soundwire HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input48
[  987.220673] kernel: SDW: Invalid device for paging :0
[  987.220683] kernel: SDW: Invalid device for paging :0
[  987.220720] kernel: SDW: Invalid device for paging :0
[  987.221684] kernel: SDW: Invalid device for paging :0
[  987.221709] kernel: SDW: Invalid device for paging :0
```

**To Reproduce**
~/sof-test/test-case/check-kmod-load-unload.sh -l 25

**Reproduction Rate**
Extremely low.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[0efaf69a10d7](https://github.com/thesofproject/linux/commit/0efaf69a10d7b59c78341e3ba2a908c1fbbdb081)}
    * SOF: {[5f118b761bf0](https://github.com/thesofproject/sof/commit/5f118b761bf023d74544d1554bada3c19a920982)}
2) Name of the topology file
    * Topology: {avs-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {ADLP_SKU0B00_SDCA_IPC4ZPH}

[dmesg.txt](https://github.com/thesofproject/linux/files/11702700/dmesg.txt)

**Comment by marc-hb** [comment]
Happened today in daily test run 28269 on `jf-tglu-sku0a32-sdca-02` after a few iterations

planresultdetail/28269?model=TGLU_SKU0A32_SDCA&testcase=check-kmod-load-unload-2 (failed on iteration 12 of 25)
planresultdetail/28269?model=TGLU_SKU0A32_SDCA&testcase=check-kmod-load-unload-after-playback-5 (failed oniteration 1 of 5)

Kernel Commit: [c0096387b083](https://github.com/thesofproject/linux/commit/c0096387b083)
SOF Branch: stable-v2.2
SOF Commit: [3ddd15caa482](https://github.com/thesofproject/sof/commit/3ddd15caa482)

**Comment by plbossart** [comment]
those errors happened before PR https://github.com/thesofproject/linux/pull/4345 was merged, it's not clear to me it this PR solves the issue. Let's see.

**Comment by keqiaozhang** [comment]
This issue has not happened in CI for nearly a month. Closing this bug.
