### ISSUE TITLE
[BUG] runtime PM trying to activate child device sdw:0:025d:0711:00 but parent (sdw-master-0) is not active

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4433]
**Describe the bug**
Observed this codec rt711  warning on TGLU-RVP-SDW-IPC4ZPH when testing check-playback-100sec.  But it's hard to reproduce. 
Test ID:28021.
```
[  631.285118] kernel: rt711 sdw:0:025d:0711:00: runtime PM trying to activate child device sdw:0:025d:0711:00 but parent (sdw-master-0) is not active
```

**To Reproduce**
~/sof-test/test-case/check-playback.sh -d 100 -l 1 -r 1

**Reproduction Rate**
Hard to tell, no reproductions by manual check so far. 

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[2776754a4cd9](https://github.com/thesofproject/linux/commit/2776754a4cd9)}
    * SOF: {[89660c616067](https://github.com/thesofproject/sof/commit/89660c616067)}
2) Name of the topology file
    * Topology: {avs-tplg/sof-tgl-rt711-rt1308-4ch.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {TGLU_RVP_SDW_IPC4ZPH}

[dmesg.txt](https://github.com/thesofproject/linux/files/11811652/dmesg.txt)

[mtrace.txt](https://github.com/thesofproject/linux/files/11811653/mtrace.txt)

**Comment by fredoh9** [comment]
Today daily test also found this issue. TGLU_RVP_NOCODEC_IPC4ZPH. Although mtrace doesn't have the exception printed.

Intel internal daily test: planresultdetail/28195?model=TGLU_RVP_NOCODEC_IPC4ZPH&testcase=check-capture-100times

**Comment by plbossart** [comment]
This should no longer happen now that https://github.com/thesofproject/linux/pull/4345 is merged

**Comment by plbossart** [comment]
closing since we haven't seen any new reports of that problem
