### ISSUE TITLE
[BUG] Device with ID register ffffff79 is not rt5682 on Brya-SDW

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4454]
**Describe the bug**
Observed this issue in CI daily test, this issue happens on ADLP Brya SDW Chromebook. This is just a warning error and does not affect functionality.  The reproduce rate is 100%. 

```
[   97.581648] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   97.581712] kernel: rt5682 sdw:0:025d:5682:00: Update Slave status failed:-19
```

**To Reproduce**
Check the dmesg after boot.

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[34b7f81747f8](https://github.com/thesofproject/linux/commit/34b7f81747f8)}
    * SOF: {stable-v2.2/[b6c174c8f9a8](https://github.com/thesofproject/sof/commit/b6c174c8f9a8)}
2) Name of the topology file
    * Topology: {sof-tplg/sof-adl-sdw-max98373-rt5682.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {ADLP_BRYA_SDW}

[dmesg.txt](https://github.com/thesofproject/linux/files/11953307/dmesg.txt)

**Comment by plbossart** [comment]
Not sure how this can happen. @bardliao @oder-chiou @shumingfan that seems like a pretty bad electrical or hardware issue, no?

**Comment by bardliao** [comment]
@plbossart I don't that is an issue. I guess 0xffffff79 is an uninitialized value of `val`. The message is a warning and rt5682 driver only shows the error message if we can't get the Device ID in 10 iterations. In other words, rt5682 driver expects some incorrect device id value before it gets the correct device id eventually. 
See https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt5682-sdw.c#L388

**Comment by plbossart** [comment]
Not following @bardliao. if after 10 loops the .update_status returns, the codec will never be initialized. 

I think the error condition below was detected in CI tests, because it's a dev_err() level. The log in the loop is just a warning, it would not be caught by CI

````c
if (val != DEVICE_ID) {
		dev_err(dev, "Device with ID register %x is not rt5682\n", val);
		ret = -ENODEV;
		goto err_nodev;
	}
````

**Comment by bardliao** [comment]
@plbossart Sorry, I was referring to the wrong log section. I was referring to
```
[   10.614332] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.619667] kernel: snd_soc_sof_sdw:mc_probe: sof_sdw sof_sdw: Entry
```
Indeed,
```
[   10.644535] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.675149] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.705778] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.736049] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.766329] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.796836] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.827376] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.857763] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.888364] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.918449] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   10.918474] kernel: snd_soc_rt5682_sdw:rt5682_io_init: rt5682 sdw:0:025d:5682:00: rt5682_io_init hw_init complete: -19
[   10.918484] kernel: rt5682 sdw:0:025d:5682:00: Update Slave status failed:-1
```
is an issue.

**Comment by plbossart** [comment]
maybe the delay is not long enough before the codec provides a correct ID register? the loop waits 10*30ms, 300ms total. That's still a rather long value for a codec, that's suspicious

**Comment by shumingfan** [comment]
Sorry, not sure what the root cause is. Could we increase the loop count to test?

**Comment by bardliao** [comment]
@keqiaozhang Could you check if https://github.com/thesofproject/linux/pull/4469 fix the issue?

**Comment by shumingfan** [comment]
@keqiaozhang Could you test #4473, too?

**Comment by keqiaozhang** [comment]
@shumingfan  and @bardliao 
Confirmed that both PRs can fix this issue.
