### ISSUE TITLE
[BUG] Pipeline ID is not aligned between firmware and Linux kernel

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#4474]
**Describe the bug**
The pipeline ID used in firmware and linux kernel is not aligned. In multiple stream playback(and maybe capture), it makes a component indistinguishable in mtrace.

Take HDA topology used in CI as an example, in the analog playback, there are three pipelines with ID 1, 2, 15.  If we do playback to HDA Analog, the pipeline gain.1.1->mixin.1.1 get the ID 0 in firmware, mixout.2.1->gain.2.1 get the ID 1. If we do playback to Deepbuffer HDA Analog, the pipeline gain.15.1->mixin.15.1 get the ID 0, mixout.2.1->gain.2.1 get the ID 1.

![Screenshot from 2023-07-14 14-04-18](https://github.com/thesofproject/linux/assets/52959957/0d055f3c-3534-47a5-817b-342272e14ffc)

The performance log: 
for gain.1.1: [    2.563948] <inf> component: comp_copy: comp:0 0x60000 perf comp_copy samples 48 period 1000 cpu avg 244 peak 288

for gain.15.1: [   81.930346] <inf> component: comp_copy: comp:0 0x60000 perf comp_copy samples 48 period 1000 cpu avg 278 peak 327

From the mtrace log solely, we can not tell which log is for which component without a correct pipeline ID corresponding to the pipeline ID in topology

**Comment by aiChaoSONG** [comment]
It seems that the kernel didn't sent pipeline id correctly, transfer to kernel.
play on HDA Analog, get below trace:
```
[    0.487963] <inf> ipc: ipc_pipeline_new: ipc: pipeline id = 0
[    0.487968] <inf> pipe: pipeline_new: pipeline new pipe_id 0 priority 0

[    0.490766] <inf> ipc: ipc_pipeline_new: ipc: pipeline id = 1
[    0.490773] <inf> pipe: pipeline_new: pipeline new pipe_id 1 priority 0

```

We were using swidget->pipeline_id, and this PR introduce ida for allocating pipe widget instance id: https://github.com/thesofproject/linux/pull/3771

**Comment by ranj063** [comment]
@aiChaoSONG Im not sure Im following the problem. The topology sets pipeline ID that are are incremental or rather unique so that they don't clash with other pipeline IDs. But when the kernel creates the pipeline, it assigns instance ID for the pipeline depending on currently available IDA. So it is expected that when you start HD Analog only, you get pipeline IS 0 and 1. And when you stop it and start deep buffer playback, the pipelines will get the same ID.

But is you start deep buffer playback alongside analog playback, you will see that the instance ID for pipeline 15 will be 2

**Comment by aiChaoSONG** [comment]
@ranj063 Correct, but in CI test cases, we run pipelines in sequential, one is started when the previous end, the gain components (maybe other component) in those pipelines is in indistinguishable, they could all share the same ID `comp:0 0x60000`, so we will never know a single performance log belongs to which gain.

And in practice, I don't think we would start HDA Analog and Deepbuffer HDA Analog in paralell.

```
[ 2.563948] component: comp_copy: comp:0 0x60000 perf comp_copy samples 48 period 1000 cpu avg 244 peak 288
```

It is not transparent that the kernel does something in the middle instead of using the pipeline ID from topology.

Edit: learned from Bard that the maximum supported number of pipelines is 32 in firmware, and in topology, we have some pipeline whose pipeline id is greater than the maximum, that's why IDA is introduced in the kernel for pipeline ID.

**Comment by aiChaoSONG** [comment]
Mark won't fix, and close.

**Comment by ranj063** [comment]
> And in practice, I don't think we would start HDA Analog and Deepbuffer HDA Analog in paralell.

@aiChaoSONG why? That's exactly the purpose of the deepbuffer PCM

**Comment by aiChaoSONG** [comment]
@ranj063 Isn't the Deepbuffer HDA Analog be designed for power saving (decrease the active time of host)? Then why do we do playback to both HDA Analog and Deepbuffer HDA Analog at the same time? Correct me, please

**Comment by marc-hb** [comment]
The kernel could remember the topology ID and print it for troubleshooting purposes. It can have its own, private ID for private purposes.

**Comment by plbossart** [comment]
> @ranj063 Isn't the Deepbuffer HDA Analog be designed for power saving (decrease the active time of host)? Then why do we do playback to both HDA Analog and Deepbuffer HDA Analog at the same time? Correct me, please

because at any time during the long low-power playback you may have a short notification or beep that needs to be mixed. The deep buffer is an optimization which cannot prevent other sounds from being heard.

In other words, it is a requirement to support both PCM devices being RUNNING simultaneously.

Makes sense now @aiChaoSONG ?

**Comment by aiChaoSONG** [comment]
@plbossart thanks for the explanation
