### ISSUE TITLE
[BUG] Louder sound from speakers (randomly right or left one) on Dell XPS 17 9710 after sleep

### ISSUE THREAD

**Issue by JuanFcoMiranda** [thesofproject/linux#4483]
**Describe the bug**
Everytime I close my laptop and it sleeps, when I reopen it again, one of the speakers gets louder than the other. Sometimes after a while or even playing some videos, it goes back to normal, but others, it does not.

**To Reproduce**
Play any videos from youtube or any sound file.

**Reproduction Rate**
After the laptop goes back from sleeping.

**Expected behavior**
Both speakers sound clear and at same level.

**Impact**
It's very annoying when reproducing any video to hear that one of the speakers sounds very much louder than the other.

**Environment**
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: 6.4.4
SOF: 2.2.6-1

**Name of the topology file**
Topology: intel/sof-tplg/sof-tgl-rt711-rt1308-rt715.tplg

**Name of the platform(s) on which the bug is observed**
Platform: Dell XPS 17 9710
Bios version: 1.21

**Comment by plbossart** [comment]
@JuanFcoMiranda You should check with amixer what the volume settings are in 'normal' cases and 'louder' cases, and compare. I don't think it's a regmap issue at the driver level, the same driver is used for both amps.

@shumingfan any other suggestions to figure this out?

**Comment by shumingfan** [comment]
@JuanFcoMiranda 
I test this issue on the same machine (kernel:6.2.0; SOF:v2.2.0). I only reproduce one time and I tested more than 10 times.
It is hard to reproduce. However, you could reproduce every time.
At that time I reproduce this issue, I dump the 1308-1/1308-2 registers and compare them.
The volume settings of both registers are the same and I also can't see any suspicion with amixer controls.
Could you dump the amixer controls/amp registers while the issue happened?

**Comment by JuanFcoMiranda** [comment]
Hi, the commands are these, right?

```
$ cat /sys/kernel/debug/regmap/sdw:1:025d:1308:00/registers

$ cat /sys/kernel/debug/regmap/sdw:2:025d:1308:00/registers
```
[Archive.zip](https://github.com/thesofproject/linux/files/12163828/Archive.zip)

Right now, only the right speaker sounds, the left one does not.

**Comment by plbossart** [comment]
@shumingfan any comments?

**Comment by shumingfan** [comment]
@JuanFcoMiranda 
Do you dump sdw1.txt while the speaker outputs?
The value of some registers is zero. You should dump registers when music is playing.
Could you dump amixer controls?  
$ amixer -c0 contents

@plbossart 
In the meantime, I will ask the HW engineer to check this.
Will let you know if any results.

**Comment by JuanFcoMiranda** [comment]
@shumingfan
Yes, I was playing a video with sound. I have just made a new test a few minutes ago, and it was even stranger, the right speaker was playing louder and lower every few seconds.

This is the contents while this new strange issue was happening:
[content.txt](https://github.com/thesofproject/linux/files/12175113/content.txt)

And this is the output for this command:

```
cat /sys/kernel/debug/regmap/sdw:1:025d:1308:00/registers
```
[sdw1.txt](https://github.com/thesofproject/linux/files/12175144/sdw1.txt)

I could not catch the other channel on time, the volumes went normal after the end of the video.

**Comment by shumingfan** [comment]
@JuanFcoMiranda 
Could you try to disable the BQ parameters for testing?

```
-
+#if 0
 static void rt1308_apply_bq_params(struct rt1308_sdw_priv *rt1308)
 {
        unsigned int i, reg, data;
@@ -208,7 +209,7 @@ static void rt1308_apply_bq_params(struct rt1308_sdw_priv *rt1308)
                regmap_write(rt1308->regmap, reg, data);
        }
 }
-
+#endif
 static int rt1308_io_init(struct device *dev, struct sdw_slave *slave)
 {
        struct rt1308_sdw_priv *rt1308 = dev_get_drvdata(dev);
@@ -631,7 +632,7 @@ static int rt1308_sdw_component_probe(struct snd_soc_component *component)
                return ret;

        /* apply BQ params */
-       rt1308_apply_bq_params(rt1308);
+       //rt1308_apply_bq_params(rt1308);

```
We ignore the distorted sound from the right speaker for this testing.
We just check the random louder sound issue.

**Comment by shumingfan** [comment]
@JuanFcoMiranda 
Could you also test the patch (8b7aa1f73d059f8d0e8161f05b244b2968bfa9a9)?
Sorry, I still don't know the root cause exactly. I will do more tests to find out.

**Comment by JuanFcoMiranda** [comment]
@shumingfan 
I have been testing with the BQ params disabled, and it seems there is no more louder sound from one of the speakers than other, but it still has the distortion on the right one, of course.

I'm going to test the new patch, and I'll tell how it is going. Thank you very much.

**Comment by JuanFcoMiranda** [comment]
@shumingfan 
I have been testing the patch you mentioned, both speakers sound good except for one strange side effect produced when I run Windows and then restart the laptop and run linux. In this moment if I play any video/audio, there is no sound at all, but if I make a sound test from the audio options settings in KDE, the sound comes back and sounds good.

**Comment by shumingfan** [comment]
@JuanFcoMiranda 
Could you share the kernel log when you restart the laptop from Windows to Linux?
Before you do the test, please put [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12211066/sof-dyndbg.conf.txt) (rename to sof-dyndbg.conf) into /etc/modprobe.d/ and reboot.

And please also enable the regmap log for 1308.
```
--- a/drivers/base/regmap/regmap.c
+++ b/drivers/base/regmap/regmap.c
@@ -30,12 +30,20 @@
  * sort of problem defining LOG_DEVICE will add printks for basic
  * register I/O on a specific device.
  */
-#undef LOG_DEVICE
+#define LOG_DEVICE "sdw:1:025d:1308:00"
```

**Comment by JuanFcoMiranda** [comment]
@shumingfan 
Here are the logs after the restart:

[log.txt](https://github.com/thesofproject/linux/files/12217816/log.txt)

[sdw1.txt](https://github.com/thesofproject/linux/files/12217818/sdw1.txt)

[sdw2.txt](https://github.com/thesofproject/linux/files/12217819/sdw2.txt)

**Comment by shumingfan** [comment]
@JuanFcoMiranda 
I updated the patch (de2a58dbd8a652003aa4639991b27ccbde31bd8f).
Please try the new patch and share the test result.

You could keep the changes mentioned in (https://github.com/thesofproject/linux/issues/4483#issuecomment-1657426539).
If there are any problems, please share the kernel log (/var/log/kern.log) and register dump.

**Comment by JuanFcoMiranda** [comment]
@shumingfan 
I have been testing the last patch during all day, and it seems it works fine. No more louder sounds from the speakers, and even when I reboot from Windows to Linux, the speakers sound correctly now.

Now I have also detected a little problem with the mic, but I'll open a new issue for it.

Thank you very much for your work.
