### ISSUE TITLE
[BUG] snd_sof_pci_intel_tgl loads incorrectly on kernel 6.1.38, needs a codec module loaded first

### ISSUE THREAD

**Issue by rbrockman2** [thesofproject/linux#4486]
When upgrading from kernel 5.15.14 to 6.1.38 on gentoo, the on-board sound on my Tiger Lake HP ZBook 15 G8 stopped working.  dmesg shows the following:

[ 1957.107441] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[ 1957.107458] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[ 1957.107883] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[ 1957.107926] sof-audio-pci-intel-tgl 0000:00:1f.3: init of i915 and HDMI codec failed
[ 1957.109209] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[ 1957.114602] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #0 probe error, ret: -2
[ 1957.114842] sof-audio-pci-intel-tgl 0000:00:1f.3: no hda codecs found!
[ 1957.114842] sof-audio-pci-intel-tgl 0000:00:1f.3: warning: No matching ASoC machine driver found
[ 1957.114843] sof-audio-pci-intel-tgl 0000:00:1f.3: error: no matching ASoC machine driver found - aborting probe
[ 1957.114843] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to get machine info -19
[ 1957.115004] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -19

Google search found a couple other people with similar problems.

What seems to be happening is that the new kernel has a different module load order, uncovering a missing dependency for sof-audio-pci-intel-tgl.  If I remove and reinstall the module manually with rmmod / modprobe, sound works again:

[ 2218.346905] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[ 2218.346922] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[ 2218.347311] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[ 2218.347374] sof-audio-pci-intel-tgl 0000:00:1f.3: init of i915 and HDMI codec failed
[ 2218.348570] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[ 2218.353894] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 1
[ 2218.353895] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[ 2218.353897] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 4
[ 2218.353901] Loading firmware: intel/sof/sof-tgl-h.ri
[ 2218.354008] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[ 2218.354009] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
[ 2218.354010] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[ 2218.463387] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[ 2218.463390] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
[ 2218.466261] Loading firmware: intel/sof-tplg/sof-hda-generic-4ch.tplg
[ 2218.466290] sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:22:1 Kernel ABI 3:23:0
[ 2218.466443] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Parent card not yet available, widget card binding deferred
[ 2218.475734] snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC285: line_outs=1 (0x17/0x0/0x0/0x0/0x0) type:speaker
[ 2218.475737] snd_hda_codec_realtek ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[ 2218.475737] snd_hda_codec_realtek ehdaudio0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[ 2218.475738] snd_hda_codec_realtek ehdaudio0D0:    mono: mono_out=0x0
[ 2218.475739] snd_hda_codec_realtek ehdaudio0D0:    inputs:
[ 2218.475739] snd_hda_codec_realtek ehdaudio0D0:      Mic=0x19
[ 2219.447149] input: sof-hda-dsp Mic as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input20
[ 2219.447175] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input21

This is just like the dmesg behavior that the working 5.15.41 kernel had.

I fixed the problem for my system by adding an entry to modprobe.d to enforce a soft dependency:

softdep snd_sof_pci_intel_tgl pre: snd_hda_codec_realtek

Pre-loading the module for either snd_hda_codec_generic or snd_hda_codec_realtek seems to fix the problem.  Now sound works fine on boot again.  This one shouldn't be tough to fix permanently for everyone.

sof-firmware is 2.2.6, kernel is 6.1.38

**Comment by plbossart** [comment]
@rbrockman2 do you see the same issue if you don't use the sof driver? This can be done with the following option

````
options snd_intel_dspcfg dsp_driver=1
````

**Comment by rbrockman2** [comment]
The module snd_intel_dspcfg gets compiled in, so I put snd_intel_dspcfg.dsp_driver=1 on the kernel command line.  This seems to break sound completely.  I have an nVidia dedicated graphics card on this laptop, usually its HDMI sound output gets recognized but with this option it is broke too.  aplay -l shows no soundcards.

relevant dmesg output:
[   20.981568] snd_hda_intel 0000:00:1f.3: enabling device (0000 -> 0002)
[   20.982022] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
[   20.982091] snd_hda_intel 0000:01:00.1: Disabling MSI
[   20.982098] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
[   20.982726] e1000e 0000:00:1f.6 enp0s31f6: renamed from eth0
[   20.987275] snd_hda_intel 0000:01:00.1: Cannot probe codecs, giving up
[   20.991938] snd_hda_intel 0000:00:1f.3: Cannot probe codecs, giving up

A possible nuance:  I have Intel graphics *disabled* on this laptop, I am only using the dedicated nVidia GPU.

**Comment by plbossart** [comment]
I think it's the same issue, with the SOF driver you also have an error at the codec probe level.

````
[ 1957.114602] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #0 probe error, ret: -2
[ 1957.114842] sof-audio-pci-intel-tgl 0000:00:1f.3: no hda codecs found!
````

Can you try with 6.4 to see if this is not fixed already?

**Comment by rbrockman2** [comment]
Still broke on kernel 6.4.4 in the same way.

**Comment by plbossart** [comment]
I think it's time to ask @tiwai if he has a suggestion, I don't understand what the module softdep would do to solve the issue.

**Comment by tiwai** [comment]
I guess it's just a matter of subtle timing, and softdep made the initialization slightly differently, which ended up with the working casually.

**Comment by rbrockman2** [comment]
softdep seems to force a valid codec module to be loaded before the sof-audio-pci-intel-tgl module that requires it.  Perhaps this can be fixed permanently by enforcing a hard dependency of some sort?

**Comment by plbossart** [comment]
I would have the exact opposite approach @rbrockman2, we need to figure out what is timing sensitive instead of hard-coding a module dependency that doesn't seem to have much technical merit other that making things work by accident.

**Comment by rbrockman2** [comment]
I also have a Cannon Lake HP ZBook 17 G7 -- it has the exact same problem and it's "fixed" with the exact same kludge.  Only difference is the module is now snd_sof_pci_intel_cnl.  

Suspicion:  the problem is related to the fact that my laptops are configured to use the dedicated nVidia card rather than the integrated Intel graphics on the CPU.  A normal user will have the laptop configured to use Optimus hybrid graphics where the integrated Intel graphics are still active.  I bet that the Intel graphics driver gets initialized much earlier than the nVidia driver, thus loading the HDMI audio codec module before snd_sof_pci_intel_tgl and curing the race condition.

Later today I will try and test this by reconfiguring my G8 for Intel graphics and seeing if that fixes the problem.

**Comment by rbrockman2** [comment]
I also have a Cannon Lake HP ZBook 17 G7 -- it has the exact same problem and it's "fixed" with the exact same kludge.  Only difference is the module is now snd_sof_pci_intel_cnl.

**Comment by rbrockman2** [comment]
Switching from discrete to integrated graphics did *not* affect the bug on the G8.

**Comment by plbossart** [comment]
@rbrockman2 the race condition is with the realtek stuff which deals with local amplifier/headset. There's no real dependency or interference from the NVidia stuff which deals with the display audio codec.

Can we try to identify the last kernel which worked and the first which didn't? There's just too many opens between 5.15 and 6.1

**Comment by rbrockman2** [comment]
Bisection results:  5.19.9 works, 6.0.1 is broken

**Comment by rbrockman2** [comment]
Interestingly, importing the kernel configuration from 5.19.9 to 6.0.1 changes the options for various sound modules.  Should I try and force any of these options back?

**Comment by rbrockman2** [comment]
Yes!  This fixes it.  6.0.1 and later has CONFIG_SND_SOC_SOF_METEORLAKE set to Y by default, this forces a bunch of other modules to be compiled in.  6.1.38 also had CONFIG_SND_SOC_SOF_SKYLAKE set to Y by default.  Once these were set back to N, leaving only CONFIG_SND_SOC_SOF_INTEL_TGL=m and CONFIG_SND_SOC_SOF_TIGERLAKE=m, the problem went away in both 6.0.1 and 6.1.38.

**Comment by rbrockman2** [comment]
It looks like the race condition manifests whenever any of the SOC_SOF modules are compiled in, including the appropriate one.  Normally this would only be a problem for people running module-less installations, I only discovered it because an inappropriate module got compiled in by mistake because of the default kernel configuration.  People using kernels provided by their distributions where basically everything is a module will never notice this bug, and people who obsessively uncheck unnecessary kernel drivers after an upgrade won't notice it either.

This problem could have existed for years, God only knows how far back we will have to go to find when it first showed up.

**Comment by plbossart** [comment]
Yes, we really only support modules. It's known that we could have random issues with firmware download not happening at the right time, or even file system not being available for built-in stuff.

We keep the compilation to make sure we don't have any broken dependencies, but this is mostly a test-only configuration. Actual devices SHALL use the modules.

**Comment by rbrockman2** [comment]
Ok, so the main kernel devs just need to fix their default configuration then.  It might also be nice to *force* kernel configuration to only allow loading these pieces as modules.

**Comment by plbossart** [comment]
closing as won't fix, I'll try to update the documentation to make sure only modules are used.
