### ISSUE TITLE
[BUG] [RPL] failed to ready HDA controller gctl 0x0 during kernel booting

### ISSUE THREAD

**Issue by Vamshigopal** [thesofproject/linux#4498]
**Describe the bug**
On RPL chromebook device  observed HDA controller failed to reset and sound card probe failed during kernel boot.

**To Reproduce**
1. Boot the chromebook 
2. Go to Settings page and search for Google assistant
3. Turn it ON and Retrain the voice
4. say "Ok google" and check system response
5. Play any youTube video and check for the audio
6. Crash the kernel using the command
   #echo BUG > /sys/kernel/debug/provoke-crash/DIRECT
  dut reboots after kernel crash
7. We observe sound card probe failed with HDA controller reset error.

**Reproduction Rate**
Always

**Environment**
Kernel Branch: https://chromium-review.googlesource.com/q/project:chromiumos/third_party/kernel+branch:chromeos-6.1
SOF Branch: https://github.com/thesofproject/sof/tree/cavs2.5-001-drop-stable
Topology:  sof-adl-max98360a-rt5682.tplg 
Platform: RPL

**Logs**
[dmesg.log](https://github.com/thesofproject/linux/files/12213015/dmesg.log)

**Screenshots or console output**
[    5.461435] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to ready HDA controller gctl 0x0
[    5.461441] sof-audio-pci-intel-tgl 0000:00:1f.3: error: get caps error
[    5.461538] dmic-codec dmic-codec: ASoC: Unregistered DAI 'dmic-hifi'
[    5.461729] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to probe DSP -5
[    5.461732] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -5

**Comment by plbossart** [comment]
@Vamshigopal we do know there's a required sequence on the shutdown and if you do not execute it the hardware is not doing to be reset properly.
We don't have any means to fix this problem.

**Comment by Vamshigopal** [comment]
Ack @plbossart , I tried reproducing the issue with proper flows like warmboot, coldboot , soix with 1000 iterations but we never saw this error.
I will watch for few more days on issue reproductions with proper flows , if it not reproduces i will close this issue.

**Comment by keqiaozhang** [comment]
@Vamshigopal  can we close this issue now?

**Comment by Vamshigopal** [comment]
Issue not reproduced with warmbook, coldboot and s0ix flows. Hence closing.
