### ISSUE TITLE
Stress Test: repetitive unloading and reloading driver causes kernel panic on UP^2 using codec topology

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/linux#45]
run `soft/kmod_scripts/sof_bootloop.sh` (repetitive unloading and reloading driver) cause kernel panic on UP^2 using codec topology

description：
After about 2 cycles ，prompt   'Killed    modprobe snd_soc_pcm512x_i2c'  . 

System Environment:
sof-dev: 6786cd0
sof: d696d8f8bad1490575a8293e0982786300eb52db
soft: a25f4b0b02b51d186d2a9c6d73c8126784a61997
using test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-codec.tplg

reproduce steps:
./sof_bootloop.sh

logs:
[boo2_2.boot.log](https://github.com/thesofproject/linux/files/2213375/boo2_2.boot.log)
[boot_0.boot.log](https://github.com/thesofproject/linux/files/2213376/boot_0.boot.log)
[boot_1.boot.log](https://github.com/thesofproject/linux/files/2213377/boot_1.boot.log)
[dmesg.log](https://github.com/thesofproject/linux/files/2213378/dmesg.log)

**Comment by mengdonglin** [comment]
Lower priority to P3 since stresssful module unload/reload is not priority atm.

**Comment by wenqingfu** [comment]
@stevyan can you please retest this?

**Comment by bardliao** [comment]
@wenqingfu I tested it few days ago, and it can only pass 5~10 iterations. I guess there are still some memory leak in our driver.

**Comment by mengdonglin** [comment]
Closed this issue that cannot be reproduced.
