### ISSUE TITLE
[BUG] Built-In microphone does not capture sound on Dell XPS 17 9710

### ISSUE THREAD

**Issue by JuanFcoMiranda** [thesofproject/linux#4504]
**Describe the bug**
The device does not record any sound from the built-in mic after rebooting from a Windows 11 session.

**To Reproduce**
Tried several tools, Kwave and Zoom with no sound activity from the mic.

**Reproduction Rate**
Everytime after rebooting from a Windows 11 session. If the computer is turned off, and it's started directly on Linux, the build-in mic works, at least, in Zoom, the level from the mic shows activity.

**Expected behavior**
Record sound from the mic.

**Environment**
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: 6.4.4
SOF: 2.2.6-1

**Name of the topology file**
Topology: intel/sof-tplg/sof-tgl-rt711-rt1308-rt715.tplg

**Name of the platform(s) on which the bug is observed**
Platform: Dell XPS 17 9710
Bios version: 1.21

**Comment by plbossart** [comment]
@JuanFcoMiranda That would suggest that some of the registers are modified by Windows and not properly reset to their default value?

Maybe you can try dumping the rt715 registers to see if there's any difference after the two types of boot?

@shumingfan @jack-cy-yu any recommendations?

**Comment by JuanFcoMiranda** [comment]
> Maybe you can try dumping the rt715 registers to see if there's any difference after the two types of boot?

Sure, but how do I dump those registers?

**Comment by plbossart** [comment]
@JuanFcoMiranda same as for amplifiers, something like:

cat /sys/kernel/debug/regmap/sdw:3:025d:7150:00/registers

**Comment by JuanFcoMiranda** [comment]
Hi, these are the contents of those registers in both cases:

Without reboot:
[sdw-715-1.txt](https://github.com/thesofproject/linux/files/12258220/sdw-715-1.txt)

After reboot from Windows:
[sdw-715-2.txt](https://github.com/thesofproject/linux/files/12258221/sdw-715-2.txt)

I did a diff, but it seems they are equals.

**Comment by plbossart** [comment]
@shumingfan @jack-cy-yu any advice? Looks like Windows establishes a state that gets in the way of recording in Linux?

**Comment by jack-cy-yu** [comment]
> Hi, these are the contents of those registers in both cases:
> 
> Without reboot: [sdw-715-1.txt](https://github.com/thesofproject/linux/files/12258220/sdw-715-1.txt)
> 
> After reboot from Windows: [sdw-715-2.txt](https://github.com/thesofproject/linux/files/12258221/sdw-715-2.txt)
> 
> I did a diff, but it seems they are equals.

@JuanFcoMiranda Did you get these two register dumps while recording? We need the register dump on mic recording condition, please help to confirm it, thanks.

**Comment by JuanFcoMiranda** [comment]
@jack-cy-yu 
These two register dumps were taken while recording:

Without reboot:
[sdw-715-1.txt](https://github.com/thesofproject/linux/files/12278958/sdw-715-1.txt)

After reboot from Windows:
[sdw-715-2.txt](https://github.com/thesofproject/linux/files/12278959/sdw-715-2.txt)

**Comment by jack-cy-yu** [comment]
@JuanFcoMiranda  I've attached two patches for debug, for "0001-ASoC-rt715-add-software-reset-before-io-init.patch", I added software reset before preset-register in io_init, please also help to dump registers while recording in both conditions (with/without reboot). For "0002-ASoC-rt715-Enable-DP4-PRBS-for-debug.patch", I enabled the PRBS to see whether any content could be received from DP4 in both conditions. Please use 0001 patch first, if 0001 patch doesn't work, then merge 0002 patch.
[0001-ASoC-rt715-add-software-reset-before-io-init.zip](https://github.com/thesofproject/linux/files/12300992/0001-ASoC-rt715-add-software-reset-before-io-init.zip)
[0002-ASoC-rt715-Enable-DP4-PRBS-for-debug.zip](https://github.com/thesofproject/linux/files/12300993/0002-ASoC-rt715-Enable-DP4-PRBS-for-debug.zip)

**Comment by JuanFcoMiranda** [comment]
How do I apply the patch?? I haven't done it before.

**Comment by jack-cy-yu** [comment]
@JuanFcoMiranda  Please use "git apply xxx.patch", or you can simply open the patch file, copy and paste the content to corresponding driver files.  https://www.specbee.com/blogs/how-create-and-apply-patch-git-diff-and-git-apply-commands-your-drupal-website

**Comment by JuanFcoMiranda** [comment]
@jack-cy-yu 
I have tried the patch 0001, on both cases, with and without reboot, and it seems it works fine. Now, I can record the sound from the microphone correctly.

Thank you very much.
