### ISSUE TITLE
[BUG] Parent card not yet available

### ISSUE THREAD

**Issue by RobusTetus** [thesofproject/linux#4509]
**Describe the bug**
This warning just shows up in my dmesg every boot, but the audio works fine.

**To Reproduce**
Just boot the laptop.

**Reproduction Rate**
Every boot.

**Expected behavior**
Clear dmesg.

**Impact**
It is just annoyance in my dmesg. I don't know what this is. The audio works fine.

**Environment**
    * Platform: Fedora Linux 37
    * Latest version from the repos.

**Screenshots or console output**
```
[    6.532236] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Parent card not yet available, widget card binding deferred
[    6.601163] snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[    6.601174] snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
[    6.601445] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget hifi3 overwritten
[    6.601455] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget hifi2 overwritten
[    6.601462] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget hifi1 overwritten
[    6.601469] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Codec Output Pin1 overwritten
[    6.601476] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Codec Input Pin1 overwritten
[    6.601487] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Analog Codec Playback overwritten
[    6.601498] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Digital Codec Playback overwritten
[    6.601507] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: sink widget Alt Analog Codec Playback overwritten
[    6.601519] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Analog Codec Capture overwritten
[    6.601528] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Digital Codec Capture overwritten
[    6.601537] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: source widget Alt Analog Codec Capture overwritten
[    6.601555] skl_hda_dsp_generic skl_hda_dsp_generic: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
```

**Comment by lgirdwood** [comment]
@ujfalusi @plbossart fyi

**Comment by RobusTetus** [comment]
Today I noticed some actual sound artifacts from my microphone, also that may as well be a problem with the external sound card for the microphone. It was using the Analog Input in my sound settings, so I've switched to Digital. Again no idea if my mic external sound card is faulty or the kernel driver.

But to clear the confusion I may cause with this. The warning messages do occur when nothing is plugged to the laptop as well.

**Comment by lgirdwood** [comment]
These messages are information only and should not be fatal. They indicate to driver engineers if something is overridden from the base topology in the case when audio does not work. i.e. no sound from speakers.

**Comment by RobusTetus** [comment]
@lgirdwood Wouldn't it be better to change the loglevel of those messages to INFO, in that case? Currently it shows as WARN in dmesg. (bold text when dmesg -l warn,err is run)

**Comment by lgirdwood** [comment]
> @lgirdwood Wouldn't it be better to change the loglevel of those messages to INFO, in that case? Currently it shows as WARN in dmesg. (bold text when dmesg -l warn,err is run)

It may well be, that's why I've added @plbossart and @ujfalusi to provide feedback. IIRC, this used to indicate potential issues in the past, but my understanding is that these old issues are all resolved now ?

**Comment by RobusTetus** [comment]
Just checking in again. The issue is still present on latest 6.4.7-200.fc38.x86_64 fedora kernel.

**Comment by lgirdwood** [comment]
@ujfalusi @plbossart is there a solution for this or is this still needed for 1st level triage ?

**Comment by plbossart** [comment]
No idea how to remove those warnings. maybe @kv2019i or @ranj063 have a better understanding of this.

BTW this is a kernel issue, not sure why it's here for SOF bugs. clearly not a firmware issue.

**Comment by RobusTetus** [comment]
> 

I didn't know. I figured it is tied to the sof modules. I was mistaken then... my apologies.

**Comment by ujfalusi** [comment]
I think the `ASoC: sink/source widget` widget_name `overwritten` is coming from the fact that we now use the hdac_hda for HDA and it is registering the same set of components, widgets for each device:
```
[  249.202316] [PETER] hdac_hda_dev_probe: ENTER for ehdaudio0D0 (vendor: Realtek, chip: ID 888)
[  249.202329] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'Analog Codec DAI'
[  249.202333] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'Digital Codec DAI'
[  249.202335] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'Alt Analog Codec DAI'
[  249.202337] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'intel-hdmi-hifi1'
[  249.202339] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'intel-hdmi-hifi2'
[  249.202341] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'intel-hdmi-hifi3'
[  249.202343] snd_soc_core:snd_soc_register_dai: snd_hda_codec_realtek ehdaudio0D0: ASoC: Registered DAI 'intel-hdmi-hifi4'
```
and
```
[  249.206256] [PETER] hdac_hda_dev_probe: ENTER for ehdaudio0D2 (vendor: Intel, chip: ID 2812)
[  249.206269] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'Analog Codec DAI'
[  249.206274] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'Digital Codec DAI'
[  249.206277] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'Alt Analog Codec DAI'
[  249.206279] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'intel-hdmi-hifi1'
[  249.206283] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'intel-hdmi-hifi2'
[  249.206286] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'intel-hdmi-hifi3'
[  249.206288] snd_soc_core:snd_soc_register_dai: snd_hda_codec_hdmi ehdaudio0D2: ASoC: Registered DAI 'intel-hdmi-hifi4'
```
When the card brought up some of these will have namespace collision.

The `ASoC: Parent card not yet available, widget card binding deferred` is something which looks like normal, probably the print level can be dropped to debug. I'm not sure if there is a way to fix it as we need to parse the topology before the card can be instantiated. It is like a chicken egg issue, but I will take a deeper look.

**Comment by ujfalusi** [comment]
right, with a hack I can get rid of the `overwritten` on my upx-i11:
```diff
diff --git a/sound/soc/codecs/hdac_hda.c b/sound/soc/codecs/hdac_hda.c
index be66853afbe2..e1ebc9c5b292 100644
--- a/sound/soc/codecs/hdac_hda.c
+++ b/sound/soc/codecs/hdac_hda.c
@@ -124,6 +124,9 @@ static struct snd_soc_dai_driver hdac_hda_dais[] = {
 		.sig_bits = 24,
 	},
 },
+};
+
+static struct snd_soc_dai_driver hdac_hda_hdmi_dais[] = {
 {
 	.id = HDAC_HDMI_0_DAI_ID,
 	.name = "intel-hdmi-hifi1",
@@ -578,6 +581,13 @@ static const struct snd_soc_component_driver hdac_hda_codec = {
 	.endianness		= 1,
 };
 
+static const struct snd_soc_component_driver hdac_hda_hdmi_codec = {
+	.probe			= hdac_hda_codec_probe,
+	.remove			= hdac_hda_codec_remove,
+	.idle_bias_on		= false,
+	.endianness		= 1,
+};
+
 static int hdac_hda_dev_probe(struct hdac_device *hdev)
 {
 	struct hdac_ext_link *hlink;
@@ -592,9 +602,15 @@ static int hdac_hda_dev_probe(struct hdac_device *hdev)
 	snd_hdac_ext_bus_link_get(hdev->bus, hlink);
 
 	/* ASoC specific initialization */
-	ret = devm_snd_soc_register_component(&hdev->dev,
-					 &hdac_hda_codec, hdac_hda_dais,
-					 ARRAY_SIZE(hdac_hda_dais));
+	if (hdev->vendor_id == 0x80862812) /* Tigerlake HDMI */
+		ret = devm_snd_soc_register_component(&hdev->dev,
+						&hdac_hda_hdmi_codec, hdac_hda_hdmi_dais,
+						ARRAY_SIZE(hdac_hda_hdmi_dais));
+	else
+		ret = devm_snd_soc_register_component(&hdev->dev,
+						&hdac_hda_codec, hdac_hda_dais,
+						ARRAY_SIZE(hdac_hda_dais));
+
 	if (ret < 0) {
 		dev_err(&hdev->dev, "failed to register HDA codec %d\n", ret);
 		return ret;
```
I'm not sure how safe it would be to do this in a bigger scale, what regression it might bring, but it is a lead...

**Comment by ujfalusi** [comment]
@RobusTetus, please see my #4620 PR, it fixes the widget overwritten prints, the parent card print cannot be fixed, as there is nothing to fix on that front, it is part of the normal sw flow.

**Comment by RobusTetus** [comment]
I for some reason suck at compiling kernel on fedora. :sob: It never boots for me, I am sure that it fixed it tho. Thank you for this. I'll let you know if I can manage to test it.

**Comment by RobusTetus** [comment]
Closing this as fixed since it is already in stable kernel releases. Sorry for not getting back, I completely forgot about this.
