### ISSUE TITLE
[ADL] suspend-resume test failed due to i915 firmware load failure

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#4530]
It happened in ADLP_SKU0B00_SDCA_IPC4ZPH. Not sure about about reproduction rate at the moment. Will try to reproduce and check the test results database also.

the command to reproduce,
TPLG=/lib/firmware/intel/avs-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg MODEL=ADLP_SKU0B00_SDCA_IPC4ZPH SOF_TEST_INTERVAL=5 ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 5 -m capture

```
[   61.507354] kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/adlp_guc_70.bin version 70.5.1
[   61.507360] kernel: i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[   61.509028] kernel: i915 0000:00:02.0: [drm] GT0: GUC: load failed: status = 0x800007EC, time = 0ms, freq = 1100MHz, ret = 0
[   61.509031] kernel: i915 0000:00:02.0: [drm] GT0: GUC: load failed: status: Reset = 0, BootROM = 0x76, UKernel = 0x07, MIA = 0x00, Auth = 0x02
[   61.509094] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GuC initialization failed -ENXIO
[   61.509096] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Enabling uc failed (-5)
[   61.509097] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize GPU, declaring it wedged!
```

Build information,
- Kernel Branch: topic/sof-dev
- Kernel Commit: [a512b8633674](https://github.com/thesofproject/linux/commit/a512b8633674)
- SOF Branch: main
- SOF Commit: [8f6018057b64](https://github.com/thesofproject/sof/commit/8f6018057b64)
- Zephyr Commit: [zephyr-v3.4.0-496-g431108d89e17](https://github.com/zephyrproject-rtos/zephyr/commit/zephyr-v3.4.0-496-g431108d89e17)

Intel internal daily test link:
planresultdetail/30191?model=ADLP_SKU0B00_SDCA_IPC4ZPH&testcase=check-suspend-resume-with-capture-5

cc:
- https://github.com/thesofproject/sof-test/pull/869

**Comment by kv2019i** [comment]
@fredoh9 I'd suggest we ignore this error in reporting SOF test results. We have no dependency on the GPU parts (we only need the display part to work), so if the audio test cases passes, test should pass. If this can be reproduce, this issue should be reported to https://gitlab.freedesktop.org/drm/intel/-/issues as nothing will be done to the bug here.

**Comment by fredoh9** [comment]
Same error happened today, will submit a PR to ignore i915 error.

```
[ 8196.629222] kernel: i915 0000:00:02.0: [drm] GT0: GuC firmware i915/adlp_guc_70.bin version 70.5.1
[ 8196.629227] kernel: i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[ 8196.630886] kernel: i915 0000:00:02.0: [drm] GT0: GUC: load failed: status = 0x800007EC, time = 0ms, freq = 1100MHz, ret = 0
[ 8196.630889] kernel: i915 0000:00:02.0: [drm] GT0: GUC: load failed: status: Reset = 0, BootROM = 0x76, UKernel = 0x07, MIA = 0x00, Auth = 0x02
[ 8196.630952] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GuC initialization failed -ENXIO
[ 8196.630953] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Enabling uc failed (-5)
[ 8196.630955] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize GPU, declaring it wedged!
```

planresultdetail/31556?model=ADLP_SKU0B00_SDCA-cavs2_5-ipc4&testcase=check-suspend-resume-50

**Comment by fredoh9** [comment]
duplicate with https://github.com/thesofproject/sof-test/issues/1048
