### ISSUE TITLE
[BUG] No sound from Tigerlake's speaker, no mic on Laptop Huawei D 15 i7, Ubuntu 22.04.3 

### ISSUE THREAD

**Issue by mcassisa** [thesofproject/linux#4534]
**Describe the bug**

Ubuntu 22.04 installed on Matebook D 15 BOD-WFE9 equipped with i7 and Tigerlake doesn't recognize the card ("dummy output").
After the firmware sof-2.2.6. has been installed in `/lib/firmware/intel/sof` and the topology file (intel signed) has been copied  into that directory the card is recognized, but no sound comes from internal speakers and no internal microphone is shown in volume control.

**Environment**
uname -a
Linux mate 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

sof-bin version
https://github.com/thesofproject/sof-bin/tree/main/v2.6.x
([commit:] (https://github.com/thesofproject/sof-bin/tree/main/v2.6.x#:~:text=Intel%20cAVS2.5%20hardware-,990f49b,-%C2%B7%C2%A0))
sof-tools
https://github.com/thesofproject/sof-bin/tree/main/v2.6.x/tools-v2.6
([commit:](https://github.com/thesofproject/sof-bin/commit/8e9fc88c44fa7c2cd75550fb4e96a040a9e9cc77))

**Reproducibility rate**
Always

**some context**

`dmesg |grep hda`
[    3.523384] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100

[    3.707779] Modules linked in: coretemp soundwire_bus kvm_intel snd_hda_intel i915(+) snd_intel_dspcfg snd_soc_es8316 snd_intel_sdw_acpi kvm snd_hda_codec snd_soc_core irqbypass snd_hda_core crct10dif_pclmul snd_compress drm_buddy snd_hwdep polyval_clmulni ac97_bus ttm snd_pcm_dmaengine polyval_generic drm_display_helper snd_pcm iwlmvm ghash_clmulni_intel btusb sha512_ssse3 snd_seq_midi mei_hdcp cec intel_rapl_msr mei_pxp joydev btrtl snd_seq_midi_event aesni_intel mac80211 rc_core processor_thermal_device_pci_legacy btbcm snd_rawmidi binfmt_misc btintel crypto_simd processor_thermal_device uvcvideo snd_seq drm_kms_helper btmtk cryptd processor_thermal_rfim videobuf2_vmalloc libarc4 videobuf2_memops nls_iso8859_1 rapl processor_thermal_mbox snd_seq_device huawei_wmi bluetooth i2c_algo_bit videobuf2_v4l2 iwlwifi cmdlinepart videodev intel_cstate processor_thermal_rapl input_leds ledtrig_audio syscopyarea snd_timer spi_nor snd mei_me videobuf2_common ecdh_generic intel_rapl_common
[    4.002278] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
[    4.216796] sof-essx8336 sof-essx8336: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
 

` journalctl -b | grep -i "essx8336\|ES8336\|0000:00:1f.3"`

ago 19 14:11:51 mate kernel: pci 0000:00:1f.3: [8086:a0c8] type 00 class 0x040100
ago 19 14:11:51 mate kernel: pci 0000:00:1f.3: reg 0x10: [mem 0x6001120000-0x6001123fff 64bit]
ago 19 14:11:51 mate kernel: pci 0000:00:1f.3: reg 0x20: [mem 0x6001000000-0x60010fffff 64bit]
ago 19 14:11:51 mate kernel: pci 0000:00:1f.3: PME# supported from D3hot D3cold
ago 19 14:11:52 mate kernel: snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: NHLT_DEVICE_I2S detected, ssp_mask 0x1
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Overriding topology with MCLK mask 0x1 from NHLT
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
ago 19 14:11:52 mate kernel: sof-essx8336 sof-essx8336: quirk mask 0x20
ago 19 14:11:52 mate kernel: sof-essx8336 sof-essx8336: quirk SSP0
ago 19 14:11:52 mate kernel: sof-essx8336 sof-essx8336: quirk DMIC enabled
ago 19 14:11:52 mate kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:22:1 Kernel ABI 3:23:0
ago 19 14:11:52 mate kernel: sof-essx8336 sof-essx8336: ASoC: Parent card not yet available, widget card binding deferred
ago 19 14:11:52 mate kernel: es8316 i2c-ESSX8336:00: assuming static mclk
ago 19 14:11:52 mate kernel: sof-essx8336 sof-essx8336: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
ago 19 14:11:52 mate kernel: input: sof-essx8336 Headset as /devices/pci0000:00/0000:00:1f.3/sof-essx8336/sound/card0/input13
ago 19 14:11:52 mate kernel: input: sof-essx8336 HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/sof-essx8336/sound/card0/input14
ago 19 14:11:52 mate kernel: input: sof-essx8336 HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:1f.3/sof-essx8336/sound/card0/input15
ago 19 14:11:52 mate kernel: input: sof-essx8336 HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sof-essx8336/sound/card0/input16
ago 19 14:11:52 mate alsactl[798]: Found hardware: "sof-essx8336" "Intel Tigerlake HDMI" "HDA:80862812,80860101,00100000 cfg-dmics:2" "" ""

`# lspci -k`
00:00.0 Host bridge: Intel Corporation 11th Gen Core Processor Host Bridge/DRAM Registers (rev 01)
	Subsystem: QUANTA Computer Inc 11th Gen Core Processor Host Bridge/DRAM Registers
	Kernel modules: igen6_edac
[...]
00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)
	Subsystem: QUANTA Computer Inc Tiger Lake-LP Smart Sound Technology Audio Controller
	Kernel driver in use: sof-audio-pci-intel-tgl
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl

`$ amixer`
Simple mixer control 'Headphone',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 3
  Mono:
  Front Left: Playback 0 [0%] [-48.00dB] [off]
  Front Right: Playback 0 [0%] [-48.00dB] [off]
Simple mixer control 'Headphone Mixer',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 11
  Front Left: 3 [27%] [-7.50dB]
  Front Right: 3 [27%] [-7.50dB]
Simple mixer control 'Speaker',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Mic Boost',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'IEC958',1
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'IEC958',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Playback Polarity',0
  Capabilities: enum
  Items: 'Normal' 'R Invert' 'L Invert' 'L + R Invert'
  Item0: 'Normal'
Simple mixer control 'Capture Polarity',0
  Capabilities: enum
  Items: 'Normal' 'Invert'
  Item0: 'Normal'
Simple mixer control 'ADC',0
  Capabilities: cvolume cvolume-joined
  Capture channels: Mono
  Limits: Capture 0 - 192
  Mono: Capture 0 [0%] [-99999.99dB]
Simple mixer control 'ADC Double Fs',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'ADC PGA Gain',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 10
  Mono: 2 [20%] [2.50dB]
Simple mixer control 'ADC Soft Ramp',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'ALC',0
  Capabilities: cswitch cswitch-joined
  Capture channels: Mono
  Mono: Capture [off]
Simple mixer control 'ALC Capture Attack Time',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 10
  Mono: 2 [20%]
Simple mixer control 'ALC Capture Decay Time',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 10
  Mono: 3 [30%]
Simple mixer control 'ALC Capture Hold Time',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 10
  Mono: 0 [0%]
Simple mixer control 'ALC Capture Max',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 28
  Mono: 28 [100%] [35.50dB]
Simple mixer control 'ALC Capture Min',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 28
  Mono: 0 [0%] [-12.00dB]
Simple mixer control 'ALC Capture Noise Gate',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'ALC Capture Noise Gate Threshold',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 31
  Mono: 0 [0%]
Simple mixer control 'ALC Capture Noise Gate Type',0
  Capabilities: enum
  Items: 'Constant PGA Gain' 'Mute ADC Output'
  Item0: 'Constant PGA Gain'
Simple mixer control 'ALC Capture Target',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 10
  Mono: 11 [110%] [0.00dB]
Simple mixer control 'DAC',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 192
  Mono:
  Front Left: Playback 152 [79%] [-20.00dB]
  Front Right: Playback 152 [79%] [-20.00dB]
Simple mixer control 'DAC Double Fs',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'DAC Mono Mix',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'DAC Notch Filter',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'DAC Soft Ramp',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'DAC Soft Ramp Rate',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 4
  Mono: 4 [100%]
Simple mixer control 'DAC Source Mux',0
  Capabilities: enum
  Items: 'LDATA TO LDAC, RDATA TO RDAC' 'LDATA TO LDAC, LDATA TO RDAC' 'RDATA TO LDAC, RDATA TO RDAC' 'RDATA TO LDAC, LDATA TO RDAC'
  Item0: 'LDATA TO LDAC, RDATA TO RDAC'
Simple mixer control 'DAC Stereo Enhancement',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 7
  Mono: 0 [0%]
Simple mixer control 'Differential Mux',0
  Capabilities: enum
  Items: 'lin1-rin1' 'lin2-rin2' 'lin1-rin1 with 20db Boost' 'lin2-rin2 with 20db Boost'
  Item0: 'lin2-rin2 with 20db Boost'
Simple mixer control 'Digital Mic Mux',0
  Capabilities: enum
  Items: 'dmic disable' 'dmic data at high level' 'dmic data at low level'
  Item0: 'dmic disable'
Simple mixer control 'Dmic0',0
  Capabilities: cvolume cswitch
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 70
  Front Left: Capture 0 [0%] [-99999.99dB] [off]
  Front Right: Capture 50 [71%] [0.00dB] [on]
Simple mixer control 'Dmic1 2nd',0
  Capabilities: cvolume
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 70
  Front Left: Capture 50 [71%] [0.00dB]
  Front Right: Capture 50 [71%] [0.00dB]
Simple mixer control 'Headset Mic',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Internal Mic',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Left Headphone Mixer LLIN',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Left Headphone Mixer Left DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Left Headphone Mux',0
  Capabilities: enum
  Items: 'lin1-rin1' 'lin2-rin2' 'lin-rin with Boost' 'lin-rin with Boost and PGA'
  Item0: 'lin1-rin1'
Simple mixer control 'PGA1.0 1 Master',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 32
  Mono:
  Front Left: Playback 32 [100%] [0.00dB]
  Front Right: Playback 32 [100%] [0.00dB]
Simple mixer control 'PGA2.0 2 PCM 0',0
  Capabilities: cvolume
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 40
  Front Left: Capture 32 [80%] [0.00dB]
  Front Right: Capture 32 [80%] [0.00dB]
Simple mixer control 'PGA5.0 5 Master',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 32
  Mono:
  Front Left: Playback 32 [100%] [0.00dB]
  Front Right: Playback 32 [100%] [0.00dB]
Simple mixer control 'PGA6.0 6 Master',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 32
  Mono:
  Front Left: Playback 32 [100%] [0.00dB]
  Front Right: Playback 32 [100%] [0.00dB]
Simple mixer control 'PGA7.0 7 Master',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 32
  Mono:
  Front Left: Playback 32 [100%] [0.00dB]
  Front Right: Playback 32 [100%] [0.00dB]
Simple mixer control 'Right Headphone Mixer RLIN',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Right Headphone Mixer Right DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
Simple mixer control 'Right Headphone Mux',0
  Capabilities: enum
  Items: 'lin1-rin1' 'lin2-rin2' 'lin-rin with Boost' 'lin-rin with Boost and PGA'
  Item0: 'lin1-rin1'

` cat /proc/asound/cards`
 0 [sofessx8336    ]: sof-essx8336 - sof-essx8336
                      HUAWEI-BOD_WXX9-M1010-BOD_WXX9_PCB_B3

` pactl list sinks`
Sink #0
	State: IDLE
	Name: alsa_output.pci-0000_00_1f.3-platform-sof-essx8336.stereo-fallback
	Description: Tiger Lake-LP Smart Sound Technology Audio Controller Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 61559 /  94% / -1,63 dB,   front-right: 61559 /  94% / -1,63 dB
	        balance 0,00
	Base Volume: 65536 / 100% / 0,00 dB
	Monitor Source: alsa_output.pci-0000_00_1f.3-platform-sof-essx8336.stereo-fallback.monitor
	Latency: 341844 usec, configured 341333 usec
	Flags: HARDWARE HW_MUTE_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = ""
		alsa.id = "ES8336 (*)"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "sof-essx8336"
		alsa.long_card_name = "HUAWEI-BOD_WXX9-M1010-BOD_WXX9_PCB_B3"
		alsa.driver_name = "snd_soc_sof_es8336"
		device.bus_path = "pci-0000:00:1f.3-platform-sof-essx8336"
		sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sof-essx8336/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "a0c8"
		device.product.name = "Tiger Lake-LP Smart Sound Technology Audio Controller"
		device.string = "hw:0"
		device.buffering.buffer_size = "65536"
		device.buffering.fragment_size = "16384"
		device.access_mode = "mmap+timer"
		device.profile.name = "stereo-fallback"
		device.profile.description = "Stereo"
		device.description = "Tiger Lake-LP Smart Sound Technology Audio Controller Stereo"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Ports:
		analog-output-speaker: Speakers (type: Speaker, priority: 10000, availability unknown)
		analog-output-headphones: Headphones (type: Headphones, priority: 9900, availability group: Legacy 1, not available)
	Active Port: analog-output-speaker
	Formats:
		pcm

`$ lsmod |grep snd`
snd_ctl_led            24576  0
snd_soc_sof_es8336     24576  3
snd_sof_probes         20480  0
snd_soc_intel_hda_dsp_common    20480  1 snd_soc_sof_es8336
snd_hda_codec_hdmi     94208  1
snd_soc_dmic           16384  1
snd_sof_pci_intel_tgl    16384  0
snd_sof_intel_hda_common   188416  1 snd_sof_pci_intel_tgl
soundwire_intel        57344  1 snd_sof_intel_hda_common
snd_sof_intel_hda      24576  1 snd_sof_intel_hda_common
snd_sof_pci            24576  2 snd_sof_intel_hda_common,snd_sof_pci_intel_tgl
snd_sof_xtensa_dsp     16384  1 snd_sof_intel_hda_common
snd_sof               311296  4 snd_sof_pci,snd_sof_intel_hda_common,snd_sof_probes,snd_sof_intel_hda
snd_sof_utils          20480  1 snd_sof
snd_soc_hdac_hda       24576  1 snd_sof_intel_hda_common
snd_hda_ext_core       36864  3 snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_soc_acpi_intel_match    77824  2 snd_sof_intel_hda_common,snd_sof_pci_intel_tgl
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_sof_intel_hda_common
snd_hda_intel          61440  0
snd_intel_dspcfg       36864  3 snd_hda_intel,snd_sof,snd_sof_intel_hda_common
snd_soc_es8316         53248  1
snd_intel_sdw_acpi     20480  2 snd_sof_intel_hda_common,snd_intel_dspcfg
snd_hda_codec         204800  5 snd_hda_codec_hdmi,snd_hda_intel,snd_soc_intel_hda_dsp_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_soc_core          417792  8 soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_sof_es8336,snd_sof_probes,snd_soc_es8316,snd_soc_dmic
snd_hda_core          135168  8 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_soc_intel_hda_dsp_common,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
snd_compress           28672  2 snd_soc_core,snd_sof_probes
snd_hwdep              20480  1 snd_hda_codec
ac97_bus               16384  1 snd_soc_core
snd_pcm_dmaengine      20480  1 snd_soc_core
snd_pcm               192512  12 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_es8316,snd_hda_core,snd_pcm_dmaengine
snd_seq_midi           20480  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            53248  1 snd_seq_midi
snd_seq                94208  2 snd_seq_midi,snd_seq_midi_event
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
ledtrig_audio          16384  2 snd_ctl_led,huawei_wmi
snd_timer              49152  2 snd_seq,snd_pcm
snd                   135168  20 snd_ctl_led,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_soc_sof_es8336,snd_pcm,snd_rawmidi
soundcore              16384  2 snd_ctl_led,snd

` modinfo snd_soc_sof_es8336`
filename:       /lib/modules/6.2.0-26-generic/kernel/sound/soc/intel/boards/snd-soc-sof_es8336.ko
import_ns:      SND_SOC_INTEL_HDA_DSP_COMMON
license:        GPL
description:    ASoC Intel(R) SOF + ES8336 Machine driver
srcversion:     44EA647BB35690EF2B89911
alias:          platform:adl_es83x6_c1_h02
alias:          platform:sof-essx8336
depends:        snd-soc-core,snd,snd-soc-intel-hda-dsp-common
retpoline:      Y
intree:         Y
name:           snd_soc_sof_es8336
vermagic:       6.2.0-26-generic SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        23:45:56:73:78:5E:C0:5B:92:50:3C:8A:D0:BF:8B:97:00:66:67:30
sig_hashalgo:   sha512
signature:      7E:D9:77:37:B1:3C:E5:C0:E8:D5:C9:30:C5:9D:91:D6:EE:CA:CC:8C:
		85:4C:C8:9E:82:E0:37:23:DE:E3:FD:05:70:0E:63:69:B2:EF:9B:9F:
		35:ED:DA:C1:97:FA:06:F8:99:05:98:46:4F:0A:EA:09:BC:AE:98:33:
		9F:CF:96:29:37:E9:C8:D1:21:D5:FD:1F:0F:C8:94:04:EC:32:87:BB:
		F3:A5:39:81:29:A1:FB:F9:25:50:B7:59:A2:84:81:2B:96:39:77:31:
		39:4B:7E:0B:DA:1F:F3:26:20:51:07:47:85:86:38:19:0E:76:B1:48:
		52:52:2E:B6:87:76:81:AA:13:86:18:58:1A:92:72:9D:66:3B:A3:CA:
		7B:19:77:BE:54:E6:9A:45:AE:23:AC:B0:6B:19:07:92:8D:06:6E:ED:
		AF:6F:CD:65:73:70:D6:0B:5A:CD:60:3B:46:B0:BD:1E:A2:62:A9:32:
		01:C0:5D:0C:F7:3A:0C:E6:24:DE:9F:44:D9:55:71:B1:D3:25:4A:48:
		06:BF:D4:B8:17:E6:68:5A:B7:15:83:9D:A6:A1:D5:0C:44:9A:17:85:
		BF:C1:9B:1C:2C:E9:00:95:B5:EA:7D:09:82:2A:50:81:E4:6A:C4:E5:
		73:BF:E0:CD:93:35:8B:DF:61:49:65:28:B0:85:AF:2B:35:0F:22:9C:
		D1:3F:CE:6B:19:97:34:EE:07:21:28:B8:89:C8:3D:24:EC:87:B6:F7:
		29:6B:28:1A:D5:1E:C3:10:CE:6A:56:DC:34:98:10:5A:EC:DF:3B:79:
		ED:E9:43:4F:15:0F:C8:86:C6:EF:68:72:D7:A5:A9:5F:EE:5D:B4:C6:
		9D:44:94:0F:57:8F:EA:8D:43:F2:06:44:62:1F:AE:2A:16:B9:E6:3F:
		CC:F5:75:CC:8C:23:68:12:32:52:50:05:96:4B:99:F4:29:3A:84:0F:
		4C:F6:BF:A3:EA:C2:B4:4C:4E:32:0D:C4:8C:70:FE:93:6B:B0:1D:C4:
		2B:91:4D:C0:EF:D9:A2:30:00:74:53:DE:92:D7:1A:4F:3D:17:2D:81:
		AA:14:6E:5D:FC:AC:C7:F5:FA:A1:2F:85:1D:77:D5:10:3A:84:39:85:
		5F:CD:0A:64:BE:91:F0:57:74:50:D4:57:4C:5A:7E:06:9A:96:4B:43:
		46:9E:DF:73:4D:32:9F:B8:4B:25:F1:B6:58:9E:A4:FE:51:E2:86:25:
		8A:05:5A:7A:28:23:23:49:EB:D5:BF:6B:17:04:6B:A9:FA:12:3C:23:
		A6:59:BC:BE:BB:FF:E0:60:1F:1E:42:20:0A:5D:7A:58:C1:85:DE:3B:
		C1:45:68:9C:F5:2D:5E:B7:5B:3D:6D:96
parm:           quirk:Board-specific quirk override (int)

`$ arecord -l`
**** List of CAPTURE Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 1: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 2: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

`$ aplay -l`
**** List of PLAYBACK Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 5: HDMI 1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 6: HDMI 2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 7: HDMI 3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by plbossart** [comment]
It's so bad we even have documentation about this class of devices. https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#es8336-support

I am not holding my breath on this one, it's been a recurring problem for 18 months and no solution provided by the codec vendor.

**Comment by mcassisa** [comment]
Update. Good news. Setting "pro audio" in pavucontrol as configuration I got both speakers and microphone. No need tio add quirks option to alsa-base.conf
Yet, the volume is very low.
