### ISSUE TITLE
CI: add support for Coccinelle

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#454]
Coccinelle is an extremely useful tool to detect conceptual errors or bad programming.
In 30mn it found one memory leak issue and one useless function, see https://github.com/thesofproject/linux/pull/453

let's add it to the CI (both Travis and Intel). Coccinelle version 1.0.7 is needed and may need to be build from code. It's easy to create a new Debian package

apt-get build-dep coccinelle
git clone https://github.com/coccinelle/coccinelle.git
cd coccinelle
git checkout 1.0.7
./autogen.sh
./configure
make -j4
make install (or create .deb)

https://bottest.wiki.kernel.org/coccicheck

for CI, let's use this command line 
make coccicheck MODE=report M=sound/soc/sof

Same as for Sparse, we only need to check SOF, not solve world hunger.

**Comment by xiulipan** [comment]
@plbossart 
Noted. Will enable it after local test success.

**Comment by xiulipan** [comment]
@plbossart 
apt-get have a released binary of 1.0.4
For travis-ci. I would like to use some pre-build one. Since I found a lot of dependency (about 400mb) is needed to build from binary. It will make travis-ci even slower.

**Comment by plbossart** [comment]
On 12/17/18 1:29 AM, xiulipan wrote:
>
> @plbossart <https://github.com/plbossart>
> apt-get have a released binary of 1.0.4
> For travis-ci. I would like to use some pre-build one. Since I found a 
> lot of dependency (about 400mb) is needed to build from binary. It 
> will make travis-ci even slower.
>
You can provide a debian package based on 1.0.7, it's no big deal.
>

**Comment by xiulipan** [comment]
@plbossart 
I will update that once we get a server that can be access from Internet.
Let use 1.0.4 for travis CI for now. https://github.com/thesofproject/linux/pull/462

**Comment by plbossart** [comment]
On 12/17/18 11:14 PM, xiulipan wrote:
>
> @plbossart <https://github.com/plbossart>
> I will update that once we get a server that can be access from Internet.
> Let use 1.0.4 for travis CI for now. #462 
> <https://github.com/thesofproject/linux/pull/462>
>
It's not going to work. I tried on my local machine and had a couple of 
errors due to the version mismatch. If we don't have a means to update 
to 1,.0.7 we need to wait or we'll have errors all the time.

**Comment by plbossart** [comment]
@xiulipan this is still outstanding, it's a really good check to add.

**Comment by xiulipan** [comment]
@plbossart 
I will try to prebuild the coccinelle and upload it to 01.org to reduce the time cost for travis ci.
