### ISSUE TITLE
Dell XPS 13 Plus 9320 (0AF3): No sound from right speakers since Linux v6.5

### ISSUE THREAD

**Issue by heftig** [thesofproject/linux#4559]
On my Dell XPS 13 Plus 9320 (SKU `0AF3`), after upgrading to from Linux v6.4.12 to Linux v6.5, ALSA no longer outputs from the right set of speakers.

It seems the `rt1316-2` mixer controls have disappeared and only `rt1316-1` remains.

**Comment by plbossart** [comment]
@heftig is there a way you could bisect between 6.4 and 6.5? I can't think of any obvious reasons why the code might no longer work. 6.5 is based on code we submittted about 2 months ago, and we've done a lot of changes since.

**Comment by heftig** [comment]
Reverting b62a1a839b48f55046727089c3ba7a8ebbf97f0e seems to restore proper operation.

**Comment by plbossart** [comment]
can you provide the results of "cat /sys/bus/soundwire/devices/*/firmware_node/adr | grep 025d"

Thanks!

**Comment by heftig** [comment]
```
0x000030025d071401
0x000131025d131601
0x000230025d131601
```

**Comment by plbossart** [comment]
Ah yes, we screwed-up. The patch https://github.com/thesofproject/linux/commit/b62a1a839b48f55046727089c3ba7a8ebbf97f0e deals with a single amplifier, and it was added first in the table, so it matches also for devices with two amps. I'll post a PR shortly this morning, thanks for reporting this.

**Comment by plbossart** [comment]
@heftig the patch https://github.com/thesofproject/linux/pull/4570/commits/dbfc86a9d7a8a44ea54d65adff264880fbf9549d should fix your problem.
