### ISSUE TITLE
[MTL] [BUG] Under Recovery boot ~ 45 seconds is taken for "MTL DSP init fail"

### ISSUE THREAD

**Issue by RDharageswari** [thesofproject/linux#4565]
the kernel should not spend ~ 45 seconds traversing an error path we expect in the recovery boot case. can we teach the kernel to handle this case more efficiently?
PS: Audio is not expected to work in recovery boot followed by cold reset and this is working as expected with the current design

  68.673585] init: cros-camera main process ended, respawning
[   73.126044] mtk_t7xx 0000:58:00.0: Port AT is not opened, drop packets
[   74.201174] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[   74.210639] sof-audio-pci-intel-mtl 0000:00:1f.3: MTL DSP init fail
[   74.217665] sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (3)
[   74.226633] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0xffffffff, ROM error: 0xffffffff
[   74.236363] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x80000009, ROM debug error: 0x48
[   74.246676] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit not enabled
[   74.254657] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[   74.546635] init: cros-camera main process (5642) terminated with status 1
[   74.554380] init: cros-camera main process ended, respawning
[   80.458539] init: cros-camera main process (5697) terminated with status 1
[   80.466436] init: cros-camera main process ended, respawning
[   86.360121] init: cros-camera main process (5757) terminated with status 1
[   86.368002] init: cros-camera main process ended, respawning
[   92.256658] init: cros-camera main process (5803) terminated with status 1
[   92.264427] init: cros-camera main process ended, respawning
[   94.266167] sof-audio-pci-intel-mtl 0000:00:1f.3: MTL DSP init fail
[   98.121020] init: cros-camera main process (5854) terminated with status 1
[   98.128798] init: cros-camera main process ended, respawning
[  103.980570] init: cros-camera main process (5900) terminated with status 1
[  103.988475] init: cros-camera main process ended, respawning
[  109.883095] init: cros-camera main process (5954) terminated with status 1
[  109.890992] init: cros-camera main process ended, respawning
[  114.275667] sof-audio-pci-intel-mtl 0000:00:1f.3: timeout waiting for purge IPC done
[  114.284350] sof-audio-pci-intel-mtl 0000:00:1f.3: MTL DSP init fail

**Comment by RDharageswari** [comment]
verified the patch and it looks good, fixes the issue.
Validation WIP

**Comment by RDharageswari** [comment]
Logs:
[   99.853113] sof-audio-pci-intel-mtl 0000:00:1f.3: -----------[ DSP dump start ]-----------
[   99.862564] sof-audio-pci-intel-mtl 0000:00:1f.3: MTL DSP init fail
[   99.869589] sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (3)
[   99.878544] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0xffffffff, ROM error: 0xffffffff
[   99.888269] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x80000009, ROM debug error: 0x48
[   99.898577] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit not enabled
[   99.906548] sof-audio-pci-intel-mtl 0000:00:1f.3: -----------[ DSP dump end ]-----------
[  100.418106] sof-audio-pci-intel-mtl 0000:00:1f.3: MTL DSP init fail
[  100.927591] sof-audio-pci-intel-mtl 0000:00:1f.3: timeout waiting for purge IPC done
[  100.936276] sof-audio-pci-intel-mtl 0000:00:1f.3: MTL DSP init fail
[  100.944325] sof-audio-pci-intel-mtl 0000:00:1f.3: error: dsp init failed after 3 attempts with err: -110
[  100.954950] sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to start DSP
[  100.962145] sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to boot DSP firmware -110
[  100.972906] sof-audio-pci-intel-mtl 0000:00:1f.3: error: sof_probe_work failed err: -110

**Comment by keqiaozhang** [comment]
@RDharageswari, is this still a bug to you? No updates for a long time.

**Comment by plbossart** [comment]
closing, no input since september 2023. Please reopen if it's still a problem
