### ISSUE TITLE
[BUG] suspend/hibernate doesn't work with kernel 6.4.12 (SUSE Leap 15.5, Lenovo X1 Extreme Gen.5)

### ISSUE THREAD

**Issue by heinlein-support** [thesofproject/linux#4569]
This is an upstream report for 
https://bugzilla.opensuse.org/show_bug.cgi?id=1207372

**Describe the bug**
Simular to https://bugzilla.suse.com/show_bug.cgi?id=1181974 we have some suspend/hibernate problems on our Lenovo X1 Extreme Gen.5.

Suspend is blocked because of a broken Module
snd_sof_pci_intel_tgl 
As a workaround, unloading this module before suspending and modprobing it after the wake up makes the suspend working on this machine - when it was using SUSE Thumbleweed. But hibernate always never worked.

After upgrading from Thumbleweed to SUSE 15.5 with Kernel 6.4.12 and sof 2.2.4 suspend and hibernate don't work any more.

**To Reproduce**
Install SUSE 15.5 on Lenovo Extreme X1 Gen.5 and try to suspend/hibernate.

**Reproduction Rate**
100%

**Expected behavior**
Suspend/hibernate should work.

**Impact**
Some kind of a showstopper. Booting takes tooooo much time.

**Comment by heinlein-support** [comment]
[dmesg-suspend.txt](https://github.com/thesofproject/sof/files/12519167/dmesg-suspend.txt)
[dmesg-hibernate.txt](https://github.com/thesofproject/sof/files/12519170/dmesg-hibernate.txt)

**Comment by plbossart** [comment]
@ranj063 @kv2019i does this error message ring a bell

````
[317180.829677] sof-audio-pci-intel-tgl 0000:00:1f.3: hda_dsp_set_hw_params_upon_resume: failure in hda_dsp_dais_suspend
[317180.829679] sof-audio-pci-intel-tgl 0000:00:1f.3: error: setting hw_params flag during suspend -22
[317180.829680] sof-audio-pci-intel-tgl 0000:00:1f.3: PM: pci_pm_suspend(): snd_sof_suspend+0x0/0x10 [snd_sof] returns -22
[317180.829694] sof-audio-pci-intel-tgl 0000:00:1f.3: PM: dpm_run_callback(): pci_pm_suspend+0x0/0x170 returns -22
[317180.829698] sof-audio-pci-intel-tgl 0000:00:1f.3: PM: failed to suspend async: error -22
````

**Comment by kv2019i** [comment]
@plbossart  The error is similar than in
https://github.com/thesofproject/linux/issues/4151
... but the fix for that was merged to 6.2 (and was backporrted to LTS kernels), so this is not the same.

**Comment by plbossart** [comment]
Indeed @kv2019i this looks new,

@heinlein-support is there a way you can add this file
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12524952/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf to help us see in more details what happens.

Also if you can identify the last working setup that would be nice. I hope it's not 5.12 as we've read in another report today...

**Comment by ujfalusi** [comment]
@heinlein-support, can you also attach a full dmesg log (boot followed by a suspend/hibernate try)?

**Comment by plbossart** [comment]
no data provided since September 2023, closing
