### ISSUE TITLE
Linux 6.5.2 does not compile snd-sof kernel module 

### ISSUE THREAD

**Issue by hauihau** [thesofproject/linux#4581]
I tried to compile linix 6.5.2 on my Thinkpad L460 and it failed with:

  MODPOST Module.symvers
ERROR: modpost: "sof_ipc3_do_rx_work" [sound/soc/sof/snd-sof.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:144: Module.symvers] Fehler 1
make[1]: *** [/usr/src/linux-6.5.2/Makefile:1984: modpost] Fehler 2
make: *** [Makefile:234: __sub-make] Fehler 2

The mentioned function has been added to sof-client.c with commit https://github.com/thesofproject/linux/commit/91774c9b5d56ab30c3b79773a34504354b440b5f / https://github.com/torvalds/linux/commit/70dad53ddff0778c4920a1ee9eb1cfea539d4e91

I don't see this compile error on my newer Intel NUC systems. As I'm having individual .configs related to the system hardware, I have seen that SND_SOC_SOF_IPC3 is not selected when SND_SOC_SOF_SKYLAKE is set, which itself selects SND_SOC_SOF_INTEL_SKL which itself selects only SND_SOC_SOF_INTEL_IPC4 with regardto IPC. 

The other two systems with CONFIG_SND_SOC_SOF_COFFEELAKE=m or CONFIG_SND_SOC_SOF_COMETLAKE=m select SND_SOC_SOF_INTEL_CNL which tiself selects SND_SOC_SOF_IPC3.

Manually adding select SND_SOC_SOF_IPC3 in sound/soc/intel/Kconfig in SND_SOC_SOF_INTEL_SKL fixes the compile error for me.

Maybe selecting SND_SOC_SOF_IPC3 was just missed for SND_SOC_SOF_INTEL_SKL in commits  https://github.com/thesofproject/linux/commit/b50c58edbe751e877e59792cc9665906738a53ef / https://github.com/torvalds/linux/commit/7ed1f83bb4f05fe460984ae49e98d1c1be38fb5f

Let me know if you need further information. I have attached my non working kernel .config. 

[config-6.5-HAUIHAU.txt](https://github.com/thesofproject/linux/files/12565871/config-6.5-HAUIHAU.txt)

**Comment by plbossart** [comment]
SND_SOC_SOF_INTEL_SKL only works with IPC4, so that's intentional.

You probably found a hole in the Kconfig dependencies, I'll look into this later.

**Comment by plbossart** [comment]
@hauihau please try PR #4586

**Comment by hauihau** [comment]
Both variants IS_ENABLED and #ifdef works.

**Comment by hauihau** [comment]
@plbossart is this fix going to land in mainline linux? I just tried 6.6.0 and the fix isn't included.

**Comment by plbossart** [comment]
it'll be in 6.7 https://lore.kernel.org/alsa-devel/20231030133347.21FE1C433C8@smtp.kernel.org/
