### ISSUE TITLE
Rename the default topology folder for MTL and LNL from intel/sof-ace-tplg to intel/sof-ipc4-tlpg

### ISSUE THREAD

**Issue by ujfalusi** [thesofproject/linux#4590]
# Problem statement

We have confusing firmware file layout for platforms supported by SOF IPC4.
As of today
## CAV2.5 (TGL family):
```
default_fw_path:	intel/avs/{platform_name}
default_lib_path:	intel/avs-lib/{platform_name}
default_tplg_path:	intel/avs-tplg
default_fw_filename:	dsp_basefw.bin
```
## MTL/LNL
```
default_fw_path:	intel/sof-ipc4/{platform_name}
default_lib_path:	intel/sof-ipc4-lib/{platform_name}
default_tplg_path:	intel/sof-ace-tplg
default_fw_filename:	sof-{platform_name}.ldc
```
For CAV2.5 there is a PR (#4382) to change the defaults
## Proposed layout for CAV2.5 (TGL family):
```
default_fw_path:	intel/sof-ipc4/{platform_name}
default_lib_path:	intel/sof-ipc4-lib/{platform_name}
default_tplg_path:	intel/sof-ipc4-tplg
default_fw_filename:	sof-{platform_name}.ri
```

# Proposal

All platforms supported by SOF IPC4 firmware should be moved to a common firmware file layout:
```
default_fw_path:	intel/sof-ipc4
default_lib_path:	intel/sof-ipc4-lib/{platform_name}
default_tplg_path:	intel/sof-ipc4-tplg
default_fw_filename:	sof-{platform_name}.ri
```
The layout will align with the current IPC3 (sof) layout and #4382 needs to be changed accordingly, however if we use the proposed layout in #4382 then it would be easier to provide backwards compatibility with symlink (sof-ace-tplg -> sof-ipc4-tplg) and no need to handle the firmware file subdir, but that could be done as well

# Notes

This will create packaging and CI issues for MTL/LNL but it is going to cause even more headache going forward when the adaptation of the IPC4 only platforms are high.

Platforms where the reference firmware might be used have different layout, the firmware file location is common with the AVS driver stack (and it is the one that is used currently for the CAV2.5, which is not correct, imho):
```
default_fw_path:	intel/avs/{platform_name}
default_lib_path:	intel/avs-lib/{platform_name}
default_tplg_path:	intel/avs-tplg
default_fw_filename:	dsp_basefw.bin
```

# Timeline

Sooner the better

**Comment by ujfalusi** [comment]
FYI: @kv2019i, @plbossart, @lgirdwood, @marc-hb, @bardliao, @ranj063

**Comment by plbossart** [comment]
@ujfalusi I believe this can be closed?

**Comment by ujfalusi** [comment]
@plbossart, MTL is in the todo, but I want to wait few SOF release before doing that. The plan is clear, I think this can be closed.
