### ISSUE TITLE
[MTL] [BUG] Jack mic not detecting post reboot RVP with 3.5mm jack connected  (ALC256)

### ISSUE THREAD

**Issue by syedk008** [thesofproject/linux#4599]
**Describe the bug**
Headset mic is not detecting in the input devices when the device is rebooted with the jack connected but the output devices show headphones-sof-hda-dsp.

**To Reproduce**
connect 3.5mm headset to the Gen4.1 AIOC board and reboot the RVP. Once the board is up, check if headset mic is detected in input devices(settings->sound).

**Reproduction Rate**
100%
**Expected behavior**
Input devices should show headset-mic.

**Impact**
High impact.

**Environment**
Kernel: 6.5.0-rc6 (sof-dev, cffcac365eac)
SOF: mtl-006
topology: sof-hda-generic-4ch.tplg
Platform: Ubuntu 22.04
![Screenshot1](https://github.com/thesofproject/linux/assets/19694094/454a18e1-28da-41e6-83c6-a459adff223c)

**Comment by bardliao** [comment]
@shumingfan Could you assign the issue to the right person? Thanks.

**Comment by shumingfan** [comment]
@bardliao Sorry, this is the HDA codec. The software owner will be Pshou (pshou@realtek.com).
I don't have his GitHub account ID. Please e-mail to him.

**Comment by plbossart** [comment]
@syedk008 just can you check if this behavior happens with the legacy snd-hda-intel driver

https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#disable-sof-on-pci-hdaudio-devices-to-test-audio-playback

**Comment by syedk008** [comment]
@plbossart same behavior, here is the snapshot
![image](https://github.com/thesofproject/linux/assets/19694094/6c55d83b-82db-4689-8ff2-a70eb0a1bb58)

**Comment by plbossart** [comment]
@syedk008 then it's not an SOF driver issue but a codec configuration issue on the RVP, likely the usual missing pin/verbs.

EDIT: it's not really surprising, you are connecting an external board to the RVP, so what are the odds the RVP BIOS has the right settings for that AOIC? it's almost "normal" that there's a configuration issue, BIOS folks cannot possibly know what might hypothetically be connected in a lab.

**Comment by mengdonglin** [comment]
@syedk008 Realtek has shared codec driver fix. Can you please close the issue after verifying the fix? 
[patch_realtek_alc256_jack_mic.zip](https://github.com/thesofproject/linux/files/12842864/patch_realtek_alc256_jack_mic.zip)

**Comment by syedk008** [comment]
Thanks, Patch is working.

**Comment by mengdonglin** [comment]
The Realtek's fix has been applied inupstream https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?id=ccbd88be057a38531f835e8a04948ebf80cb0c5d
@syedk008 @plbossart @bardliao @ujfalusi
