### ISSUE TITLE
Stress Test: repetitive unloading and reloading driver can cause kernel panic on BYT using nocodec topology

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/linux#46]
Run `soft/kmod_scripts/sof_bootloop.sh` that repetitively unloads and reloads driver can cause kernel panic on BYT using nocodec topology.

description：
After 61 cycles ，prompt 'Removing sof_acpi_dev  , Killed" 
`lsmod | grep sof` ：
sof_acpi_dev           16384   -1
snd_sof_intel_bdw      20480  1 sof_acpi_dev
...
...

System Environment:
sof-v4.14 :  287922311857961fb2e3d3b6d42f7e8b2f3f4ea9
sof: d696d8f8bad1490575a8293e0982786300eb52db
soft: a25f4b0b02b51d186d2a9c6d73c8126784a61997
using test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-nocodec.tplg

reproduce steps:
./sof_bootloop.sh

log:
[boot_59.boot.log](https://github.com/thesofproject/linux/files/2213584/boot_59.boot.log)
[boot_60.boot.log](https://github.com/thesofproject/linux/files/2213585/boot_60.boot.log)
[boot_61.boot.log](https://github.com/thesofproject/linux/files/2213587/boot_61.boot.log)
[boot_62.boot.log](https://github.com/thesofproject/linux/files/2213588/boot_62.boot.log)
[rmbox-t.log](https://github.com/thesofproject/linux/files/2213589/rmbox-t.log)

**Comment by plbossart** [comment]
Can you clarify why I see this log in the dmesg files:
[  210.916884] rt5651 i2c-10EC5651:00: Device with ID register 0xffff8c2d is not rt5651

This means you are not in nodec mode, you are using the ACPI ID to probe the codec. Or you must use the force-nocodec kconfig?

**Comment by ghost** [comment]
the PR #80  and PR #72  can fix this kind of kernel panic issue already.

**Comment by mengdonglin** [comment]
Stress test on driver unload/reload is not priority atm.

@lyakh it seem PR #130 still need to fix some check patch error. Please notify validation here when the PR is merged. Thanks!

**Comment by ZhendanYang** [comment]
Firmware load failed after booting. So tests were blocked.
Env:
sof-dev : 108d9cf
sof tool: 78748d4
sof stable-1.2: 7dd4b1d
tplg: sof-byt-nocodec.tplg
Log:
[dmesg-byt.log](https://github.com/thesofproject/linux/files/2401124/dmesg-byt.log)

**Comment by ZhendanYang** [comment]
Firmware load failed after booting once. So tests were blocked.
Test env:
kernel: sof-dev 160b45f
sof tool: 57b5212
sof stable-1.2: 7dd4b1d
tplg: sof-byt-nocodec.tplg
[dmesg-panic.log](https://github.com/thesofproject/linux/files/2418843/dmesg-panic.log)

**Comment by lgirdwood** [comment]
@ZhendanYang please paste the relevant dmesg sections .
```
[   58.688933] gnome-shell[1159]: segfault at 18 ip 00007f751d1b11bc sp 00007ffc174a36e0 error 4 in libmutter-1.so.0.0.0[7f751d0f7000+142000]
[   58.688949] Code: e5 f8 83 c5 0d 89 44 24 28 48 8b 43 30 4c 8d 74 24 30 89 74 24 24 48 8b 7b 20 4c 8d 6c 24 20 89 54 24 2c 4c 89 f2 89 4c 24 20 <8b> 70 18 e8 5c bb fd ff e8 e7 a2 fd ff 85 c0 0f 85 bf 00 00 00 4c 
```
sorry, I'm not seeing any audio driver bugs here. 
Can you retest this console mode only (i.e. don't start GUI) eneter a single user non graphical runlevel.

**Comment by zhuqingliang** [comment]
@lgirdwood 
After set  non graphical runlevel ,  fimware boot successfully  on latest codebase ,but module reload issue still exist.
Test env:
kernel: sof-dev 93853cbf8f8252ec
sof tool: 2d7a933aa86
sof stable-1.2: 7dd4b1d
tplg: sof-byt-nocodec.tplg
dmesg log before module reload:
[dmesg-byt.log](https://github.com/thesofproject/linux/files/2455182/dmesg-byt.log)

**Comment by lgirdwood** [comment]
@zhuqingliang ok thanks, I guess you have no log of the oops now ? hard lock up ?

**Comment by zhuqingliang** [comment]
@lgirdwood Here is module reload dmesg log
[oops.log](https://github.com/thesofproject/linux/files/2458666/oops.log)

**Comment by mengdonglin** [comment]
@stevyan @markyang Could you help to check if this issue is gone with fixing of #144 by PR #311?

**Comment by markyang** [comment]
**Summary:**
This issue cannot be reproduced on BYT-nocodec using the build on Dec 7.
There is no Kernel Panic.

**Test steps:**
1. kmod_scripts/sof_bootone.sh
2. aplay -l
```
**** List of PLAYBACK Hardware Devices ****
card 0: sofnocodec [sof-nocodec], device 0: Passthrough (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
3. arecord -l
```
**** List of CAPTURE Hardware Devices ****
card 0: sofnocodec [sof-nocodec], device 0: Passthrough (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
**Test env:**
sof master: b5d6c71b #Dec 7
kernel sof-dev: a71221d #Dec 7
tplg: test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-nocodec.tplg

**Comment by mengdonglin** [comment]
@markyang are you using https://github.com/thesofproject/soft/blob/master/kmod_scripts/sof_bootone.sh in you verification?

And here we need to run stress test with multiple unload/reload,  So we expect to use soft/kmod_scripts/sof_bootloop.sh

**Comment by markyang** [comment]
@mengdonglin  There is an invalid DAI type error in the _dmesg_, so _sof_bootloop.sh_  doesn't work. 
I can update the _sof_bootloop.sh_ script to ignore this error and try later.

**Comment by markyang** [comment]
**Summary:**
This issue was blocked by thesofproject/linux/issues/471

**Comment by juimonen** [comment]
I haven' t seen any bootloop errors with minnowboard after applying  https://github.com/thesofproject/linux/pull/695

**Comment by juimonen** [comment]
@zhuqingliang can we close this or is this still valid?

**Comment by wenqingfu** [comment]
from the last few days' regression report, I think it can conclude it's fixed. Thank you for following up with this bug, @juimonen
