### ISSUE TITLE
Support for disabling audio devices in BIOS

### ISSUE THREAD

**Issue by halobarrlets** [thesofproject/linux#4606]
In modern laptop BIOS there is a feature to disable audio devices like microphones/speakers/whole audio.
These BIOS settings are exposed to OS using sysfs interface and attribute values could be read to determine whatever audio devices should be disabled or not.
https://github.com/torvalds/linux/blob/master/Documentation/ABI/testing/sysfs-class-firmware-attributes
For example, Dell BIOS expose these attributes:
```
$ ls -la /sys/class/firmware-attributes
dell-wmi-sysman -> ../../devices/virtual/firmware-attributes/dell-wmi-sysman
```
```
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/current_value:Enabled
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/default_value:Enabled
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/dell_modifier:
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/dell_value_modifier:
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/display_name:Enable Microphone
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/display_name_language_code:en-US
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/possible_values:Disabled;Enabled;
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/Microphone/type:enumeration
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/current_value:Enabled
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/default_value:Enabled
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/dell_modifier:
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/dell_value_modifier:
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/display_name:Enable Internal Speaker
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/display_name_language_code:en-US
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/possible_values:Disabled;Enabled;
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/InternalSpeaker/type:enumeration
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/current_value:Enabled
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/default_value:Enabled
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/dell_modifier:
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/dell_value_modifier:
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/display_name:Enable Audio
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/display_name_language_code:en-US
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/possible_values:Disabled;Enabled;
/sys/devices/virtual/firmware-attributes/dell-wmi-sysman/attributes/IntegratedAudio/type:enumeration
```
It should be similar for HP/Lenovo/some other vendors.

This works in Windows and it would be nice to have this feature in Linux.
As far as I understand, to support this the capability to mask the ACPI information using the values of attributes should be added. And also to add all possible topology configurations for all combinations of the enabled devices.

**Comment by plbossart** [comment]
Thanks @halobarrlets, I've never heard of WMI and I had no idea it could control microphone usage. We'll look into this.

**Comment by marc-hb** [comment]
After searching for 5 minutes it looks like the main WMI use case is "hotkeys" that turn things on and off. @halobarrlets Can you confirm this is what you're after?

https://wiki.ubuntu.com/Kernel/Reference/WMI
https://www.kernel.org/doc/html/latest/wmi/acpi-interface.html

https://github.com/microsoft/Windows-driver-samples/blob/main/wmi/wmiacpi/wmi-acpi.htm

It can't be for privacy and security because asking the OS "hey, could you please be nice and disable this?" is not going to be more secure than turning it off in the OS directly.

**Comment by halobarrlets** [comment]
Typical WMI use case is certanly hotkeys but as stated in your second link it's also for:
> configuration of BIOS options.

It surely is not a strong privacy or security feature. I can see it as a low effort way to disable audio devices for corporate laptops used by simple users if you use BIOS password.
And if someone really want some privacy and disconnect the device physically then this could be a way to tell the OS that this device is disabled.

**Comment by marc-hb** [comment]
> configuration of BIOS options.

Indeed. I kept finding only super generic documentation and examples that never mentioned any real-world use case. That was frustrating. Then I added the name of a specific vendor to my search keywords and ta-da:

https://www.configjon.com/dell-bios-settings-management-wmi/

**Comment by plbossart** [comment]
@halobarrlets After checking with our Intel colleagues, it turns out that WMI is not supported by Intel drivers in Windows. It looks like these mic enable/disable knobs are mostly useless/unused.

**Comment by marc-hb** [comment]
> Then I added the name of a specific (PC) vendor to my search keywords and ta-da:

Searching for `wmi_` in the kernel sources (thanks Saket) also shows surprisingly widespread WMI use in the Linux kernel - apparently all from PC vendors:

https://github.com/search?q=repo%3Atorvalds%2Flinux+wmi_&type=code

**Comment by halobarrlets** [comment]
Seems like the WMI support for Windows is provided by Realtek driver:
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=xx2dk&oscode=w2021&productcode=xps-17-9720-laptop

**Comment by plbossart** [comment]
The Realtek Windows driver is known to be designed to work-around ACPI issues and might indeed support this Dell-specific interface. I am not sure how this could work in Linux, our baseline assumption is that ACPI has to be correct, and even if the codec driver did things on its own the SOF driver selects the topology based on ACPI information ...

The only solution I can think of would be to add a quirk in the machine driver selection for all entries where there's an RT714/714, and we skip that entry, but that would require us to add 2 topologies for each microphone-based configuration. That's a non-starter.

We really need a run-time way to disable specific topology paths, that would allow the machine driver to tell the topology layer to skip the microphone on Dell platforms, but that doesn't exist and no one has spare cycles to work on this...

Don't hold your breath on this capability @halobarrlets

**Comment by halobarrlets** [comment]
@plbossart
Yes, run-time control of topology is the best solution.
I understand that this is a low priority task given the limited resources and won't be implemented any time soon but I think it needs to be done at some point in the future.
