### ISSUE TITLE
Dummy Output - Missing tplg: sof-adl-rt711-2ch.tplg - OMEN by HP Gaming Laptop 16t-k000 - Debian Testing

### ISSUE THREAD

**Issue by Kavey78** [thesofproject/linux#4611]
This seems very similar to issues like this one https://github.com/thesofproject/linux/issues/4135 but I can't seem to find my device/model laptop sound card listed anywhere, so please forgive me if this has already been addressed.  Below is dmesg output and other details I hope will provide enough information.

[dmesg.txt](https://github.com/thesofproject/linux/files/12775157/dmesg.txt)

[inxi.txt](https://github.com/thesofproject/linux/files/12775159/inxi.txt)

[lspci.txt](https://github.com/thesofproject/linux/files/12775160/lspci.txt)

**Comment by plbossart** [comment]
@Kavey78 can you add this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12793612/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf and re-attach the dmesg log. Also attach the log of 'alsa-info'. Thanks!

**Comment by Kavey78** [comment]
Here is the output you requested.

[alsa-info.txt](https://github.com/thesofproject/linux/files/12806303/alsa-info.txt)
[dmesg-sof-dyndb.txt](https://github.com/thesofproject/linux/files/12806304/dmesg-sof-dyndb.txt)

**Comment by plbossart** [comment]
You have an RT1316 amplifier on link 3

````
sdw:3:025d:1316:01:0 
````

so it's clearly wrong to use the rt711-2ch topology.

the upstream code selects this topology in sound/soc/intel/common/oc-acpi-intel-adl-match.c

````c
	{
		.link_mask = 0x9, /* 2 active links required */
		.links = adl_sdw_rt711_link0_rt1316_link3,
		.drv_name = "sof_sdw",
		.sof_tplg_filename = "sof-adl-rt711-l0-rt1316-l3.tplg",
	},
````

**Comment by plbossart** [comment]
links 0 and 3 are enabled by ACPI
````
[    3.391186] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: ACPI reports 4 SDW Link devices
[    3.391190] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: Link 1 not selected in firmware
[    3.391193] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: Link 2 not selected in firmware
````

**Comment by plbossart** [comment]
It's probably a DMI match issue, we use

````
{
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "HP"),
			DMI_MATCH(DMI_PRODUCT_NAME, "OMEN by HP Gaming Laptop 16-k0xxx"),
		},
		.driver_data = (void *)hp_omen_16,
	},
````

and you have 

````
Product Name:      OMEN by HP Gaming Laptop 16t-k000
````

**Comment by plbossart** [comment]
can you please try the patches in https://github.com/thesofproject/linux/pull/4615 @Kavey78 ?

**Comment by Kavey78** [comment]
Thank you this worked perfectly.  As soon as I applied the patch to my kernel installed and rebooted the sound card immediately started working.  Sorry I didn't respond sooner, but I had a lot of issues getting the custom kernel installed properly.  Eventually worked it out.
