### ISSUE TITLE
MTL - Soundwire - clock stop prep/de-prep failed slave:15

### ISSUE THREAD

**Issue by udaymb** [thesofproject/linux#4619]
Below issue is observed
Codec - cs42l42 headset and max98363 speaker

In the Chrome MTL system - headset is connected, In UI, during youtube playback is on speaker, if switched to  headset, below log is seen in dmesg

soundwire sdw-master-0: clock stop prep/de-prep failed slave:15
soundwire sdw-master-0: clock stop deprepare wait failed:-110

Above message has no effect on audio. Audio is working fine and heard on headset.

Logs - [dmesg-clock-prep-deprep-15-110.log](https://github.com/thesofproject/linux/files/12827739/dmesg-clock-prep-deprep-15-110.log)

**Comment by plbossart** [comment]
-110 is ETIMEDOUT
slave:15 is a broadcast command to all peripherals.

I have no idea what setup you are using @udaymb, please add this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12831545/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf and re-attach the logs.

Also adding @rfvirgil and @charleskeepax for comments, IIRC there's something specific about clock stop with this CS42L42 device?

**Comment by rfvirgil** [comment]
On 06/10/2023 14:27, Pierre-Louis Bossart wrote:
> -110 is ETIMEDOUT
> slave:15 is a broadcast command to all peripherals.
> 
> I have no idea what setup you are using @udaymb, please add this file
> [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12831545/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf and re-attach the logs.
> 
> Also adding @rfvirgil and @charleskeepax for comments, IIRC there's something specific about clock stop with this CS42L42 device?
> 
The CS42L42 clock-stop issue is that jack detect can't send a bus wake
so it needs a separate INT line to notify jack plug/unplug events to
the host. This doesn't prevent entering or leaving clock-stop.

Do we know whether the -110 means there was no _response_ from the
CS42L42, or that it responded with clock-stop not allowed?

**Comment by plbossart** [comment]
@rfvirgil my guess based on the limited logs is that the broadcast read fails

````c
static int sdw_bus_wait_for_clk_prep_deprep(struct sdw_bus *bus, u16 dev_num)
{
	int retry = bus->clk_stop_timeout;
	int val;

	do {
		val = sdw_bread_no_pm(bus, dev_num, SDW_SCP_STAT);
		if (val < 0) {
			if (val != -ENODATA)
				dev_err(bus->dev, "SDW_SCP_STAT bread failed:%d\n", val);
			return val;
		}
		val &= SDW_SCP_STAT_CLK_STP_NF;
		if (!val) {
			dev_dbg(bus->dev, "clock stop prep/de-prep done slave:%d\n",
				dev_num);
			return 0;
		}

		usleep_range(1000, 1500);
		retry--;
	} while (retry);

	dev_err(bus->dev, "clock stop prep/de-prep failed slave:%d\n",
		dev_num);

	return -ETIMEDOUT;
}
````

We certainly need more logs but my money is on the "NotFinished" bit remaining set. If there was really a command issue we would not see the last dev_err() log.

**Comment by rfvirgil** [comment]
On 06/10/2023 15:07, Pierre-Louis Bossart wrote:
> @rfvirgil my guess based on the limited logs is that the broadcast read fails
> 
> ````c
> static int sdw_bus_wait_for_clk_prep_deprep(struct sdw_bus *bus, u16 dev_num)
> {
> 	int retry = bus->clk_stop_timeout;
> 	int val;
> 
> 	do {
> 		val = sdw_bread_no_pm(bus, dev_num, SDW_SCP_STAT);
> 		if (val < 0) {
> 			if (val != -ENODATA)
> 				dev_err(bus->dev, "SDW_SCP_STAT bread failed:%d\n", val);
> 			return val;
> 		}
> 		val &= SDW_SCP_STAT_CLK_STP_NF;
> 		if (!val) {
> 			dev_dbg(bus->dev, "clock stop prep/de-prep done slave:%d\n",
> 				dev_num);
> 			return 0;
> 		}
> 
> 		usleep_range(1000, 1500);
> 		retry--;
> 	} while (retry);
> 
> 	dev_err(bus->dev, "clock stop prep/de-prep failed slave:%d\n",
> 		dev_num);
> 
> 	return -ETIMEDOUT;
> }
> ````
> 
> We certainly need more logs but my money is on the "NotFinished" bit remaining set. If there was really a command issue we would not see the last dev_err() log.
> 
A log with DEBUG enabled in cs42l42.c and cs42l42-sdw.c would give us
some extra info. There is a dev_dbg when it handles the port_prep()
callback, and also when it enters and leaves runtime-suspend.

**Comment by plbossart** [comment]
That's not the port prep that's the issue here, it's the clock stop prep/deprep. Similar logic and wording but different steps. Ports are prepared/deprepared due to streaming actions, clock stop prep/deprep happens in suspend-resume steps.

**Comment by rfvirgil** [comment]
On 06/10/2023 15:21, Pierre-Louis Bossart wrote:
> That's not the port prep that's the issue here, it's the clock stop prep/deprep. Similar logic and wording but different steps. Ports are prepared/deprepared due to streaming actions, clock stop prep/deprep happens in suspend-resume steps.
> 
> 
Sorry, I was getting confused between the two similar but different
CS42L42 threads. A log with DEBUG in the cs42l42 drivers would still
be useful.

**Comment by udaymb** [comment]
> -110 is ETIMEDOUT slave:15 is a broadcast command to all peripherals.
> 
> I have no idea what setup you are using @udaymb, please add this file [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12831545/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf and re-attach the logs.
> 
> Also adding @rfvirgil and @charleskeepax for comments, IIRC there's something specific about clock stop with this CS42L42 device?

@plbossart - As suggested updated [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12831545/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf

and updated below soundwire codec related in the same file
options snd_soc_cs42l42 dyndbg=+pmf
options snd_soc_cs42l42_sdw dyndbg=+pmf
options snd_soc_max98363 dyndbg=+pmf

Logs - [dmesg-clock-prep-deprep-15-110-dyndbg.log](https://github.com/thesofproject/linux/files/12843193/dmesg-clock-prep-deprep-15-110-dyndbg.log)

**Comment by rfvirgil** [comment]
@plbossart Does MTL issue bus-reset after clock stop?
In this log it looks like it it has not. There is a log print in the cs42l42 driver if unattach_request is set:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/sound/soc/codecs/cs42l42-sdw.c?h=linux-6.5.y#n440

But that isn't in the log where it is exiting clock stop (starting at 216.804360). If unattach_request is correctly 0, the CS42L42 has not been reset, so it will still be in clock stop. Looks like something has gone wrong with sending Clock_Stop_Prepare=0. But there aren't any "trf on Slave %d failed" messages so all the writes were acked.

**Comment by plbossart** [comment]
I don't understand the sequence, there's just not enough information in the broken section

````
[  166.361093] snd_sof:sof_pcm_close: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: close stream 2 dir 0
[  166.853116] soundwire sdw-master-0: clock stop prep/de-prep failed slave:15
[  166.853132] soundwire sdw-master-0: clock stop deprepare wait failed:-110
[  166.854684] snd_soc_cs42l42_sdw:cs42l42_sdw_runtime_resume: cs42l42-sdw sdw:0:01fa:4242:00: Runtime resume
[  166.854707] snd_sof:sof_pcm_open: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: open stream 0 dir 0
````

**Comment by plbossart** [comment]
@udaymb please try with this patch and re-attach the logs

[0001-soundwire-bus-add-more-meaningful-logs-and-traces.patch.txt](https://github.com/thesofproject/linux/files/12847089/0001-soundwire-bus-add-more-meaningful-logs-and-traces.patch.txt)

**Comment by udaymb** [comment]
attached logs with  patch [0001-soundwire-bus-add-more-meaningful-logs-and-traces.patch.txt](https://github.com/thesofproject/linux/files/12847089/0001-soundwire-bus-add-more-meaningful-logs-and-traces.patch.txt)

Logs - [dmesg-clock-prep-deprep-15-110-dyndbg-patch.log](https://github.com/thesofproject/linux/files/12848063/dmesg-clock-prep-deprep-15-110-dyndbg-patch.log)

**Comment by plbossart** [comment]
Thanks @udaymb, that's what I suspected:

````
[  137.171017] snd_soc_cs42l42_sdw:cs42l42_sdw_runtime_suspend: cs42l42-sdw sdw:0:01fa:4242:00: Runtime suspend
[  137.171405] soundwire_bus:sdw_slave_clk_stop_prepare: cs42l42-sdw sdw:0:01fa:4242:00: sdw_slave_clk_stop_prepare: prepare done
[  137.171567] soundwire_bus:sdw_bus_wait_for_clk_prep_deprep: soundwire sdw-master-0: clock stop prepare done slave:15
[  144.661221] entering low_mem (avail RAM = 51012 kB, avail swap 0 kB, avail file 51012 kB, anon mem: 7268588 kB)
[  144.765862] soundwire_bus:sdw_slave_clk_stop_prepare: cs42l42-sdw sdw:0:01fa:4242:00: sdw_slave_clk_stop_prepare: deprepare done
[  144.766187] soundwire_bus:sdw_bus_wait_for_clk_prep_deprep: soundwire sdw-master-0: clock stop deprepare not complete slave:15, retry 300, STP_NF 0x1
...
[  145.291382] soundwire_bus:sdw_bus_wait_for_clk_prep_deprep: soundwire sdw-master-0: clock stop deprepare not complete slave:15, retry 1, STP_NF 0x1
[  145.292915] soundwire sdw-master-0: clock stop deprepare failed slave:15
[  145.292931] soundwire sdw-master-0: clock stop deprepare wait failed:-110
````

Somehow the CS42L42 does not clear the NotFinished bit. This doesn't seem correct, but it doesn't really matter in the end, the  error is squelched into a dev_warn and the resume proceeds anyways.

I don't really know what to make of this. This happens only on the exit from clock-stop, but the NotFinished logic is the same for the entry in clock-stop. The same logic has been used on all SoundWire devices.

@rfvirgil any ideas?

**Comment by rfvirgil** [comment]
@plbossart Do you have MTL + cs42l42 SoundWire in your Github automated test system?

**Comment by plbossart** [comment]
> @plbossart Do you have MTL + cs42l42 SoundWire in your Github automated test system?

No we do not. We only have basic RVPs with RT711-SDCA. We had a plan to introduce additional boards but it's also from Realtek.

**Comment by plbossart** [comment]
@udaymb can we close this issue? no input or follow-up since October.

**Comment by plbossart** [comment]
no reply, closing
