### ISSUE TITLE
CI: Work out default kconfig for WHL to build daily image for testing

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#463]
We need to work out a concise kconfig to support WHL that has an onboard HD-A codec. This kconfig will be used to build the kernel image for daily test and image for each PR.

**Comment by zhuyingjiang** [comment]
kconfig : https://github.com/thesofproject/kconfig : 1c7649a29db5b1930cc
make defconfig;
scripts/kconfig/merge_config.sh .config /kconfig/base-defconfig /kconfig/sof-defconfig /kconfig/hdaudio-codecs-defconfig
make menuconfig un-select HDA audio PCI

**Comment by plbossart** [comment]
On 12/18/18 12:45 AM, Zhu, Yingjiang wrote:
>
> kconfig : https://github.com/thesofproject/kconfig : 1c7649a29db5b1930cc
> make defconfig;
> scripts/kconfig/merge_config.sh .config /kconfig/base-defconfig 
> /kconfig/sof-defconfig /kconfig/hdaudio-codecs-defconfig
> make menuconfig un-select HDA audio PCI
>
the last step is not necessary, is it? I've used this configs for sst 
instead of SOF and never had to unselect anything

**Comment by zhuyingjiang** [comment]
> the last step is not necessary, is it? I've used this configs for sst instead of SOF and never had to unselect anything
The last step is not needed if we have blacklist and disabled HDA driver, or the HDA driver will be load instead of SOF.

**Comment by plbossart** [comment]
No need to change the configs, please try https://github.com/thesofproject/linux/pull/480 it should do everything you need.

**Comment by plbossart** [comment]
@zhuyingjiang Can you please check PR480 so that we merge it if successful early next year.

**Comment by zhuyingjiang** [comment]
@plbossart Sorry, I was working on enable the Cometlake, so have not read the mail. I will check it the first time when go to office.

**Comment by zhuyingjiang** [comment]
@plbossart I have checked the new kconfig works, it will enter into sof-audio with HD Audio PCI selected.

**Comment by zhuyingjiang** [comment]
Close this for now since unselect "HDA audio PCI" works and #480 is closed.
