### ISSUE TITLE
Suspicious dereference of pointer 'dai' before NULL check in topology.c

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#465]
This warning is found in sound/soc/sof/topology.c 

Suspicious dereference of pointer 'dai' before NULL check at line 1762
sound/soc/sof/topology.c:1759 \| sof_widget_unload() 

kernel branch: cros-sof-v4.14-rebase

**Comment by keyonjie** [comment]
hi @ranj063 , please keep(don't revert) your commit "ASoC: SOF: clean up widget_unload routine" to fix this issue.

**Comment by plbossart** [comment]
what tree is this supposed to be on? I don't see anything on sof/topic/cros-sof-v4.14-rebase

**Comment by keqiaozhang** [comment]
@plbossart 
This issue only happens on cros-sof-v4.14-rebase. Now it's fixed by Ranjani after re-applying "ASoC: SOF: clean up widget_unload routine". Close this issue.
