### ISSUE TITLE
[BUG][LNL] Jack detection doesn't work on LNL AIC rt711

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4687]
**Describe the bug**
We have one LNL-SDW device configured with Gen4.1 AIOC codec board, but jack detection doesn't work on rt711 codec. 
I checked with evtest(Input device event monitor and query tool),  no events posted when doing headset hot-plug. 
But it works on MTL with same hardware configuration and it also works with onboard rt711.

**To Reproduce**
1. run `sudo evtest`
2. select 5 for sof-soundwire headset Jack.
3. do headset hot-plug
4. check the evtest post message

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[09138cb33833](https://github.com/thesofproject/linux/commit/09138cb33833a7dd08e8323e3d589eac5e03a65d)}
    * SOF: {[a6d65ee6dcad](https://github.com/thesofproject/sof/commit/a6d65ee6dcada94b77e8b40ded12fdf596001196)}
2) Name of the topology file
    * Topology: {sof-ace-tplg/sof-lnl-rt711-l0-rt1316-l23-rt714-l1.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {LNLM-SDW-AIOC}

**Comment by plbossart** [comment]
@keqiaozhang please disable runtime_pm and make sure the bus is not in clock-stopped mode.

There's a specific sequence that needs to be done when the clock is stopped, we first want to check if the jack detection works at all. When runtime_pm is disabled, we should see an alert for the codec in the dmesg log.

**Comment by plbossart** [comment]
Also please check that jack detection works with a regular LNL RVP without an AIC, just to discard electrical issues. It's not clear from the initial description if this configuration works or not.
Thanks @keqiaozhang!

**Comment by keqiaozhang** [comment]
> @keqiaozhang please disable runtime_pm and make sure the bus is not in clock-stopped mode.
> 
JD works after disabling `runtime_pm`, I have confirmed it yesterday.

I also tried the mixed configuration(onboard rt711+ AIC board) yesterday, but met some issues when loading tplg, I will continue to debug it today.

**Comment by plbossart** [comment]
> > @keqiaozhang please disable runtime_pm and make sure the bus is not in clock-stopped mode.
> 
> JD works after disabling `runtime_pm`, I have confirmed it yesterday.

So is the problem happening only when the clock is stopped?

> I also tried the mixed configuration(onboard rt711+ AIC board) yesterday, but met some issues when loading tplg, I will continue to debug it today.

Why would we want a mixed configuration. Either we use the AIC or we don't. There's not much value in having a mixed configuration. The AIC is already quite complex as it is.

**Comment by keqiaozhang** [comment]
> Why would we want a mixed configuration. Either we use the AIC or we don't. There's not much value in having a mixed configuration. The AIC is already quite complex as it is.

I just want to do a cross check. Now I have a conclusion that no matter what codec configuration, as long as runtime_pm is disabled(options snd-sof-pci sof_pci_debug=0x01), JD can work on LNL.

**Comment by plbossart** [comment]
ok, so can we try to make progress with pm_runtime re-enabled:

a) boot and wait for the links to go to clock-stop
b) wait 10s
c) insert a jack

What happens then? 

1) does the bus restart (as measured by activity in the dmesg log?)
2) if yes, does the jack control change?
3) if yes, do we see any evtest values?

We need to root-cause at what level something is broken.

**Comment by keqiaozhang** [comment]
> ok, so can we try to make progress with pm_runtime re-enabled:
> 
> a) boot and wait for the links to go to clock-stop 
> b) wait 10s 
> c) insert a jack
> 
I enabled the run-time PM and rebooted the device, then inserted a headset(w/ mic) after DSP suspended for more than 100s.
I opened 3 terminals to monitor the changes for below items.
> What happens then?
> 
> 1. does the bus restart (as measured by activity in the dmesg log?)
>
No new dmesg log after inserting headset.
> 2. if yes, does the jack control change?
>
`Headset Mic Switch` always off.
> 3. if yes, do we see any evtest values?
> 
No events detected.

**Comment by plbossart** [comment]
Thanks @keqiaozhang, so clearly we are not able to detect anything when the clock is stopped. Need to think a bit more on this one.

**Comment by plbossart** [comment]
@bardliao @keqiaozhang for LNL we have to use a different signaling compared to previous platforms: we don't use the SoundWire wake but instead the HDAudio wake.

Can you try to see if we enter in the  intel_shim_check_wake() callback in intel_ace2x.c? If this is reached then it's a good sign that we are able to see an HDaudio wake, but somehow we don't resume the bus.

**Comment by keqiaozhang** [comment]
@bardliao  provided a debug patch:
```
diff --git a/drivers/soundwire/intel_ace2x.c b/drivers/soundwire/intel_ace2x.c
index fb64c6d37ab0..274820f92d36 100644
--- a/drivers/soundwire/intel_ace2x.c
+++ b/drivers/soundwire/intel_ace2x.c
@@ -41,6 +41,7 @@ static int intel_shim_check_wake(struct sdw_intel *sdw)
        u16 wake_sts;
        int ret;

+       pr_info("%s\n", __func__);
        /* find out which bits are set in LSDIID for this sublink */
        ret = hdac_bus_eml_sdw_get_lsdiid_unlocked(sdw->link_res->hbus, sdw->instance, &lsdiid);
        if (ret < 0)

```
But there's nothing different after applying this patch, no evtest or dmesg logs when inserting headset.

**Comment by plbossart** [comment]
Just to be clear @keqiaozhang, when we disable runtime_pm, do we ever go through those shim_wake functions, or is the jack detection performed by detecting an alert status (0x4)?

That would tell us that the HDaudio wake is never used...

**Comment by keqiaozhang** [comment]
@plbossart  , here is the dmesg output when runtime PM is disabled:

=========  insert headset ==========
```
[  110.694313] intel_shim_check_wake
[  110.694337] intel_shim_check_wake
[  110.694343] intel_shim_check_wake
[  110.694351] intel_shim_check_wake
[  110.694380] soundwire_intel:intel_link_power_up: soundwire_intel soundwire_intel.link.0: first link up, programming SYNCPRD
[  110.694483] soundwire_bus:sdw_modify_slave_status: rt711-sdca sdw:0:0:025d:0711:01: initializing enumeration and init completion for Slave 6
[  110.696319] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2
[  110.696363] soundwire_bus:sdw_handle_slave_status: soundwire sdw-master-0-0: Slave attached, programming device number
[  110.696840] soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-0: SDW Slave Addr: 30025d071101
[  110.696843] soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-0: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x3
[  110.696846] soundwire_bus:sdw_assign_device_num: soundwire sdw-master-0-0: Slave already registered, reusing dev_num:6
[  110.697270] soundwire_cadence:cdns_fill_msg_resp: soundwire_intel soundwire_intel.link.0: Msg ignored for Slave 0
[  110.697276] soundwire_bus:sdw_program_device_num: soundwire sdw-master-0-0: No more devices to enumerate
[  110.697337] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2000001
[  110.697370] soundwire_bus:sdw_modify_slave_status: rt711-sdca sdw:0:0:025d:0711:01: signaling enumeration completion for Slave 6
[  110.697621] soundwire_bus:sdw_slave_set_frequency: rt711-sdca sdw:0:0:025d:0711:01: Configured bus base 1, scale 3, mclk 19200000, curr_freq 4800000
[  110.892292] snd_soc_rt711_sdca:rt711_sdca_calibration: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_calibration calibration complete, ret=0
[  110.903372] snd_soc_rt711_sdca:rt711_sdca_jack_init: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_init enable
[  110.903384] snd_soc_rt711_sdca:rt711_sdca_io_init: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_io_init hw_init complete
[  110.903389] soundwire_bus:sdw_handle_slave_status: rt711-sdca sdw:0:0:025d:0711:01: signaling initialization completion for Slave 6
[  110.903499] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x4000000
[  110.921054] snd_soc_rt711_sdca:rt711_sdca_interrupt_callback: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_interrupt_callback control_port_stat=4, sdca_cascade=1
[  110.922325] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2000000
[  110.953387] snd_soc_rt711_sdca:rt711_sdca_headset_detect: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_headset_detect, detected_mode=0x0
[  110.953394] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, jack_type=0x0
[  110.953396] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, btn_type=0x0
[  110.953397] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, scp_sdca_stat1=0x1, scp_sdca_stat2=0x0
[  111.356396] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x4000000
[  111.358232] snd_soc_rt711_sdca:rt711_sdca_interrupt_callback: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_interrupt_callback control_port_stat=4, sdca_cascade=1
[  111.361222] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2000000
[  111.392511] snd_soc_rt711_sdca:rt711_sdca_headset_detect: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_headset_detect, detected_mode=0x5
[  111.392540] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, jack_type=0x3
[  111.392555] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, btn_type=0x0
[  111.392567] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, scp_sdca_stat1=0x1, scp_sdca_stat2=0x0
[  114.928729] soundwire_bus:sdw_bus_wait_for_clk_prep_deprep: soundwire sdw-master-0-0: clock stop prepare done slave:15
```

=========  unplug headset ==========
```
[  220.041901] intel_shim_check_wake
[  220.041926] intel_shim_check_wake
[  220.041932] intel_shim_check_wake
[  220.041940] intel_shim_check_wake
[  220.041970] soundwire_intel:intel_link_power_up: soundwire_intel soundwire_intel.link.0: first link up, programming SYNCPRD
[  220.042034] soundwire_bus:sdw_modify_slave_status: rt711-sdca sdw:0:0:025d:0711:01: initializing enumeration and init completion for Slave 6
[  220.043889] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2
[  220.043934] soundwire_bus:sdw_handle_slave_status: soundwire sdw-master-0-0: Slave attached, programming device number
[  220.044279] soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-0: SDW Slave Addr: 30025d071101
[  220.044282] soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-0: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x3
[  220.044285] soundwire_bus:sdw_assign_device_num: soundwire sdw-master-0-0: Slave already registered, reusing dev_num:6
[  220.044658] soundwire_cadence:cdns_fill_msg_resp: soundwire_intel soundwire_intel.link.0: Msg ignored for Slave 0
[  220.044664] soundwire_bus:sdw_program_device_num: soundwire sdw-master-0-0: No more devices to enumerate
[  220.044725] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2000001
[  220.044757] soundwire_bus:sdw_modify_slave_status: rt711-sdca sdw:0:0:025d:0711:01: signaling enumeration completion for Slave 6
[  220.045187] soundwire_bus:sdw_slave_set_frequency: rt711-sdca sdw:0:0:025d:0711:01: Configured bus base 1, scale 3, mclk 19200000, curr_freq 4800000
[  220.246314] snd_soc_rt711_sdca:rt711_sdca_calibration: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_calibration calibration complete, ret=0
[  220.257690] snd_soc_rt711_sdca:rt711_sdca_jack_init: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_init enable
[  220.257702] snd_soc_rt711_sdca:rt711_sdca_io_init: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_io_init hw_init complete
[  220.257706] soundwire_bus:sdw_handle_slave_status: rt711-sdca sdw:0:0:025d:0711:01: signaling initialization completion for Slave 6
[  220.257794] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x4000000
[  220.274191] snd_soc_rt711_sdca:rt711_sdca_interrupt_callback: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_interrupt_callback control_port_stat=4, sdca_cascade=1
[  220.275544] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2000000
[  220.306225] snd_soc_rt711_sdca:rt711_sdca_headset_detect: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_headset_detect, detected_mode=0x0
[  220.306236] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, jack_type=0x0
[  220.306241] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, btn_type=0x0
[  220.306245] snd_soc_rt711_sdca:rt711_sdca_jack_detect_handler: rt711-sdca sdw:0:0:025d:0711:01: in rt711_sdca_jack_detect_handler, scp_sdca_stat1=0x1, scp_sdca_stat2=0x0
[  224.018340] soundwire_bus:sdw_bus_wait_for_clk_prep_deprep: soundwire sdw-master-0-0: clock stop prepare done slave:15
```

**Comment by plbossart** [comment]
sorry @keqiaozhang I am not following at all

First the comment above says "runtime PM is disabled" but clock stop is used.
Second we can clearly see the alert when the clock is restarted, so what is the problem?

**Comment by bardliao** [comment]
@plbossart The issue is that there is no interrupt at all when runtime PM is **enabled**.

**Comment by keqiaozhang** [comment]
LNL-HDA has same issue.

**Comment by plbossart** [comment]
ok, I am officially lost in space

a) the results above where with clock stop, which can only be reach when runtime PM is enabled. There is no way "clock stop prepare done" would show if pm_runtime was disabled...

b) If LNL HDA has the same issue, then it's clearly a problem with wakes not enabled since we use the HDaudio wake mechanism for SoundWire. Can we check BIOS settings maybe?

Edit: for HDaudio, we should try with the legacy driver to see if anything works. 'options snd-intel-dspcfg dsp_driver=1'

**Comment by keqiaozhang** [comment]
> a) the results above where with clock stop, which can only be reach when runtime PM is enabled. There is no way "clock stop prepare done" would show if pm_runtime was disabled...
> 
I used `options snd-sof-pci sof_pci_debug=0x01` to disable runtime PM, but I didn't disable SDW runtime PM.

> b) If LNL HDA has the same issue, then it's clearly a problem with wakes not enabled since we use the HDaudio wake mechanism for SoundWire. Can we check BIOS settings maybe?
>
I will give it a try, hope I can find the related part.

> Edit: for HDaudio, we should try with the legacy driver to see if anything works. 'options snd-intel-dspcfg dsp_driver=1'
>
I tried the legacy driver on LNL-HDA device and got the same results. It seems that runtime PM is disabled as default. I checked the `runtime_status`(`/sys/bus/pci/devices/0000:00:1f.3/hdaudioC0D0/power/runtime_status`), it always `active` and JD works as expected. Then I enabled the runtime PM by `echo auto > control `, JD stopped working after `runtime_status` turned to `suspended`.

**Comment by plbossart** [comment]
@keqiaozhang can you try this patch for LNL/SoundWire?
[sdw-wake.diff.txt](https://github.com/thesofproject/linux/files/13549589/sdw-wake.diff.txt)

I am wondering if we need to clear the STS bits before enabling the wake, and also enable the wake before powering-down?

````diff
diff --git a/drivers/soundwire/intel_ace2x.c b/drivers/soundwire/intel_ace2x.c
index fb64c6d37ab0..b13bc0482e2d 100644
--- a/drivers/soundwire/intel_ace2x.c
+++ b/drivers/soundwire/intel_ace2x.c
@@ -68,6 +68,11 @@ static void intel_shim_wake(struct sdw_intel *sdw, bool wake_enable)
        if (ret < 0)
                goto unlock;
 
+       /* Clear wake status (W1C) */
+       wake_sts = snd_hdac_chip_readw(sdw->link_res->hbus, STATESTS);
+       wake_sts |= lsdiid;
+       snd_hdac_chip_writew(sdw->link_res->hbus, STATESTS, wake_sts);
+
        wake_en = snd_hdac_chip_readw(sdw->link_res->hbus, WAKEEN);
 
        if (wake_enable) {
@@ -80,10 +85,6 @@ static void intel_shim_wake(struct sdw_intel *sdw, bool wake_enable)
                wake_en &= ~lsdiid;
                snd_hdac_chip_writew(sdw->link_res->hbus, WAKEEN, wake_en);
 
-               /* Clear wake status (W1C) */
-               wake_sts = snd_hdac_chip_readw(sdw->link_res->hbus, STATESTS);
-               wake_sts |= lsdiid;
-               snd_hdac_chip_writew(sdw->link_res->hbus, STATESTS, wake_sts);
        }
 unlock:
        mutex_unlock(sdw->link_res->shim_lock);
diff --git a/drivers/soundwire/intel_bus_common.c b/drivers/soundwire/intel_bus_common.c
index e5ac3cc7cb79..72ec607c8e53 100644
--- a/drivers/soundwire/intel_bus_common.c
+++ b/drivers/soundwire/intel_bus_common.c
@@ -208,14 +208,14 @@ int intel_stop_bus(struct sdw_intel *sdw, bool clock_stop)
                return ret;
        }
 
+       sdw_intel_shim_wake(sdw, wake_enable);
+
        ret = sdw_intel_link_power_down(sdw);
        if (ret) {
                dev_err(dev, "%s: Link power down failed: %d\n", __func__, ret);
                return ret;
        }
 
-       sdw_intel_shim_wake(sdw, wake_enable);
-
        return 0;
 }

````

**Comment by keqiaozhang** [comment]
@plbossart , sorry for late response, I tested your patch on LNL-SDW-AIOC platform, same results as before. JD can only work when runtime_PM is disabled(`options snd-sof-pci sof_pci_debug=0x01`).

**Comment by plbossart** [comment]
Humm, I wonder if this is correct for SoundWire, it's enabled for SoundWire but we test something that doesn't exist for SoundWire.

````c
void hda_codec_jack_wake_enable(struct snd_sof_dev *sdev, bool enable)
{
	struct hda_bus *hbus = sof_to_hbus(sdev);
	struct hdac_bus *bus = sof_to_bus(sdev);
	struct hda_codec *codec;
	unsigned int mask = 0;

	if (IS_ENABLED(CONFIG_SND_SOC_SOF_NOCODEC_DEBUG_SUPPORT) &&
	    sof_debug_check_flag(SOF_DBG_FORCE_NOCODEC))
		return;

	if (enable) {
		list_for_each_codec(codec, hbus)
			if (codec->jacktbl.used)
				mask |= BIT(codec->core.addr);
	}

	snd_hdac_chip_updatew(bus, WAKEEN, STATESTS_INT_MASK, mask);
}
````

**Comment by bardliao** [comment]
> Humm, I wonder if this is correct for SoundWire, it's enabled for SoundWire but we test something that doesn't exist for SoundWire.
> 
> ```c
> void hda_codec_jack_wake_enable(struct snd_sof_dev *sdev, bool enable)
> {
> 	struct hda_bus *hbus = sof_to_hbus(sdev);
> 	struct hdac_bus *bus = sof_to_bus(sdev);
> 	struct hda_codec *codec;
> 	unsigned int mask = 0;
> 
> 	if (IS_ENABLED(CONFIG_SND_SOC_SOF_NOCODEC_DEBUG_SUPPORT) &&
> 	    sof_debug_check_flag(SOF_DBG_FORCE_NOCODEC))
> 		return;
> 
> 	if (enable) {
> 		list_for_each_codec(codec, hbus)
> 			if (codec->jacktbl.used)
> 				mask |= BIT(codec->core.addr);
> 	}
> 
> 	snd_hdac_chip_updatew(bus, WAKEEN, STATESTS_INT_MASK, mask);
> }
> ```

@plbossart I think the point is that HDA codecs have the same jack detection issue. And so does legacy HDA driver.

**Comment by plbossart** [comment]
@bardliao never mind, with the updatew() above the SoundWire settings are preserved. Discard my comment above.

**Comment by mengdonglin** [comment]
@plbossart @aiChaoSONG @bardliao Could PR #4761 also help the jack detection at least for SoundWire codec?

**Comment by keqiaozhang** [comment]
> Could PR #4761 also help the jack detection at least for SoundWire codec?

PR https://github.com/thesofproject/linux/pull/4761 is not helpful for JD issues.

**Comment by mengdonglin** [comment]
@keqiaozhang FYI. The latest kernel fix is https://github.com/thesofproject/linux/pull/4769
