### ISSUE TITLE
[BUG][LNL] IO transfer timed out on LNL-SDW when testing suspend/resume w/ audio

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4728]
**Describe the bug**
Observed this issue only on LNL-SDW platform when testing system S3 with audio. The reproduction rate is 100%. 

**dmesg**
```
[  228.249272] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-0: SDW Slave Addr: 30025d071101
[  228.249275] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-0: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x3
[  228.249277] kernel: soundwire_bus:sdw_assign_device_num: soundwire sdw-master-0-0: Slave already registered, reusing dev_num:6
[  228.249306] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-1: SDW Slave Addr: 30025d071401
[  228.249306] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-1: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x0714, unique_id 0x0, version 0x3
[  228.249308] kernel: soundwire_bus:sdw_assign_device_num: soundwire sdw-master-0-1: Slave already registered, reusing dev_num:7
[  228.249313] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-2: SDW Slave Addr: 31025d131601
[  228.249314] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-2: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x1316, unique_id 0x1, version 0x3
[  228.249315] kernel: soundwire_bus:sdw_assign_device_num: soundwire sdw-master-0-2: Slave already registered, reusing dev_num:1
[  228.249320] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-3: SDW Slave Addr: 30025d131601
[  228.249320] kernel: soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0-3: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x1316, unique_id 0x0, version 0x3
[  228.249321] kernel: soundwire_bus:sdw_assign_device_num: soundwire sdw-master-0-3: Slave already registered, reusing dev_num:1
[  228.635516] kernel: PM: suspend exit
[  228.753617] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 0 addr 46 len 1
[  228.753657] kernel: soundwire sdw-master-0-0: trf on Slave 0 failed:-110 write addr 46 count 0
[  228.753660] kernel: soundwire sdw-master-0-0: Program device_num 6 failed: -110
[  228.753661] kernel: soundwire sdw-master-0-0: Assign dev_num failed:-110
[  228.753686] kernel: soundwire_intel soundwire_intel.link.1: IO transfer timed out, cmd 3 device 0 addr 46 len 1
[  228.753693] kernel: soundwire sdw-master-0-1: trf on Slave 0 failed:-110 write addr 46 count 0
[  228.753695] kernel: soundwire sdw-master-0-1: Program device_num 7 failed: -110
[  228.753695] kernel: soundwire sdw-master-0-1: Assign dev_num failed:-110
[  228.753704] kernel: soundwire_intel soundwire_intel.link.2: IO transfer timed out, cmd 3 device 0 addr 46 len 1
[  228.753707] kernel: soundwire sdw-master-0-2: trf on Slave 0 failed:-110 write addr 46 count 0
[  228.753709] kernel: soundwire sdw-master-0-2: Program device_num 1 failed: -110
[  228.753709] kernel: soundwire sdw-master-0-2: Assign dev_num failed:-110
```

**To Reproduce**
~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 5 -m capture

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[266ee31b71f8](https://github.com/thesofproject/linux/commit/266ee31b71f88434f317d78a9ce3e3aec31fdbd8)}
    * SOF: {[fb229b9cc128](https://github.com/thesofproject/sof/commit/fb229b9cc1282779cbb289fbb0c2331f6fc893c0)}
2) Name of the topology file
    * Topology: {sof-lnl-rt711-l0-rt1316-l23-rt714-l1.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {LNL-SDW-AIOC}

[dmesg.txt](https://github.com/thesofproject/linux/files/13542393/dmesg.txt)

**Comment by aiChaoSONG** [comment]
This issue is happened on suspend-resume(50 iterations) stress test at 1st iteration, see internal report: 35856, 35919, 35927, etc. Even without audio playback or capture.

**Comment by aiChaoSONG** [comment]
reproduced the issue with only `sudo rtcwake -m mem -s 5` command, and the sleep(response) time is obviously larger than 5 second.

[  131.815439] PM: suspend entry (s2idle)
[  163.105309] PM: suspend exit

[edit] even with runtime PM, this issue can be reproduced. 
- wait 10 seconds to enter runtime suspend.
- do aplay, and you will see `IO transfer timed out` error in dmesg

On a working MTL device, on resume:
1. Power up all links
2. receive 0x80002000 interrupt (ATTACH)
3. receive 0x80000004 intterrupt (no sure what this is for)
4. program device number
5. keep receiving 0x80000004 intterrupts

On a LNL device that have IO transfer timeout
1. Power up all links
2. receive 0x80002000 interrupt (ATTACH)
3. receive 0x80000004 intterrupt (no sure what this is for)
4. program device number
5. no interrupt is received, and IO transfer timeout.

confirmed to be a regression, bisecting...
Revert https://github.com/thesofproject/linux/commit/9ae19556, issue could not be reproduced.
In my test, It doesn't work if we start sdw in firmware pre-run, and this patch even start sdw much earlier than that.
@plbossart FYI

**Comment by plbossart** [comment]
I am having a hard time following the regression findings from @aiChaoSONG 

the hda_sdw_startup() code in probe or post_fw_run is ONLY used for the first boot.

I don't get how this could result in a suspend-resume issue, since the code is only used once *BEFORE* the suspend.

@bardliao any ideas?

**Comment by plbossart** [comment]
it's more likely the interrupt that's not enabled in the resume stage, see https://github.com/thesofproject/linux/pull/4761 @aiChaoSONG

**Comment by bardliao** [comment]
> it's more likely the interrupt that's not enabled in the resume stage, see #4761 @aiChaoSONG

You are so quick. @plbossart I just think it could be due to `hda_sdw_int_enable(sdev, true);` was removed from `sof_lnl_ops.post_fw_run`, you already provided the fix.

**Comment by aiChaoSONG** [comment]
> it's more likely the interrupt that's not enabled in the resume stage, see #4761 @aiChaoSONG

From the different behavior on MTL and LNL, we don't receive further interrupt on LNL, yes, you are right.

**Comment by mengdonglin** [comment]
@keqiaozhang FYI.
