### ISSUE TITLE
No sound on speakers on dell 9730 (But works on wired headphones and bluetooth)

### ISSUE THREAD

**Issue by marcmerlin** [thesofproject/linux#4758]
Filing this as recommended by Kai:
https://alsa-project.org/db/?f=d732a80cdb3d8e569a97c7dc73a32ddc76aea8a9
this is using an ubuntu 23 kernel that does output sound in ubuntu 23, but not when booted in debian 12
thread with more details:
https://www.spinics.net/lists/kernel/msg5048945.html

everything seems to work great, but just no sound output at all, and I cannot unmute any extra channel with alsamixer

**Comment by kv2019i** [comment]
@marcmerlin Problem could be in too old alsa-ucm package in Debian. At least value of "rt1316-2 RX Channel Select" seems to be wrong. The enable sequence in UCM for the speaker amp is:

/usr/share/alsa/ucm2/sof-soundwire/rt1316-2.conf
```
                        EnableSequence [
                                cset "name='rt1316-1 RX Channel Select' L,L"
                                cset "name='rt1316-2 RX Channel Select' R,R"
                                cset "name='rt1316-1 DAC Switch' 1"
                                cset "name='rt1316-2 DAC Switch' 1"
                                cset "name='Speaker Switch' on"
                        ]
```

**Comment by marcmerlin** [comment]
OMG, I needed alsa-ucm-conf but it wasn't even installed.
Now, it works, finally! Thank You!
I spent so many hours on this and didn't find any reference to this. Alsamixer used to be enough, not anymore...

**Comment by kv2019i** [comment]
Good to hear @marcmerlin . It's puzzling how you managed to end up with a system without alsa-ucm-conf. This package is recommended by libasound2-data , which again is depended on by most audio apps. If this can be reproduced, might be a good Debian bug.

In other distros (Fedora, Ubuntu). there's more direct dependency to alsa-ucm-conf for any desktop installation.

And indeed, with more recent laptops, there are more models where some custom mixer settings are needed and UCM is the way for us to distribute the needed recipes in a way distributions can pick up.

Let me close the bug as this was a UCM/Debian issue in the end.

**Comment by marcmerlin** [comment]
My main issue is fixed, but I uploaded the same info from ubuntu 23 using the same exact kernel, to compare them:
https://alsa-project.org/db/?f=a0697fc8fd514cd4a6edf7efc28a463b14cf6bb7

The main difference, which is what distracted me from the real problem, is booting on debian, still shows these
[   66.871993] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx error for 0x60010000 (msg/reply size: 108/20): -5
[   66.872008] sof-audio-pci-intel-tgl 0000:00:1f.3: HW params ipc failed for stream 1
[   66.872016] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -5
[   66.872040]  HDMI 3: ASoC: error at __soc_pcm_hw_params on HDMI 3: -5
[   66.872083]  HDMI 3: ASoC: error at dpcm_fe_dai_hw_params on HDMI 3: -5
(cc @kv2019i )

I'm not sure what they really mean or are worth looking into, but after fixing alsa-ucm-conf kernel 6.6.9 isn't giving those errors anymore, so I think things are good, but reporting this bit in case it was useful. This bug can stay closed, thanks again.

**Comment by kv2019i** [comment]
@marcmerlin Late reply, but if Pulseaudio (or Pipewire) doesn't find an UCM file, it will try to open PCMs with all possible parameters and try to figure out what is supported. This leads to above errors as e.g. some parameters are not supported with SOF HDMI/PCM nodes. With UCM in place, this part is not done.

FYI @mrhpearson , the related Debian bugs are
        https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059871
	https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059872
