### ISSUE TITLE
The COMP_CMD_SET_DATA requires max. length acknowledge message from DSP

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#477]
Also it looks like the command also uses maximum length (384) for sent data even if the set data payload is much smaller. The set data IPC could be enhanced to be more efficient.

**Comment by plbossart** [comment]
@singalsu would you mind clarifying what the problem is and what you are looking for? is this an IPC change or just a change on the kernel side?

**Comment by singalsu** [comment]
If the usage of always max. size IPC is confirmed (the header size field is always 384 for EQs data with checks for it enforced, I noticed this due to the IPC size check bug) then just as kernel change by using as size the actual payload size + headers size would be a first improvement to reduce IPC traffic.

If we would optimize that response from firmware does not need to the same length but just sufficient to report back success it would optimize the traffic even more. But that would be an IPC change. Maybe not for ABI header files but for the usage of them.

**Comment by ranj063** [comment]
@plbossart this would not require any ipc change but just an appropriate reply size set for the command so that the DSP isnt sending the entire chunk back to the host.

**Comment by singalsu** [comment]
I will start working with this after my vacation in end of June. This is related to Linux #753 and PR #890.

**Comment by singalsu** [comment]
Not sure this is valid any more. I need to re-check and close this if such no more happens.

**Comment by lgirdwood** [comment]
@singalsu MAX IPC size has been recently updated too, best to check its in both FW and SW.

**Comment by singalsu** [comment]
I don't think this issue is relevant any more. Closing.
