### ISSUE TITLE
[FEATURE] Conexant SN6140 Codec Support (?)

### ISSUE THREAD

**Issue by salihefee** [thesofproject/linux#4786]
**Is your feature request related to a problem? Please describe.**
I am using A Huawei Matebook D16 with a Conexant SN6140 sound card. When I first installed Arch Linux, I did not have audio and a quick googling led me to download sof-firmware. That fixed my audio issue and my microphone issue. But the audio was low quality and the volume was very low. I am now using the snd_hda_intel kernel driver, which fixes the low quality and low volume audio issues, but now my internal microphone is not working.

**Describe the solution you'd like**
I am requesting support for the sound card Conexant SN6140 to be added.

**Describe alternatives you've considered**
I am currently using snd_hda_intel with my internal microphone not working.

Thank you.

**Comment by plbossart** [comment]
Just to be clear @salihefee, with the SOF driver you have low quality and low volume on the speakers, but with snd-hda-intel the sound is ok?

Can you clarify if the quality of the headphone output is acceptable?

Thanks!

@kv2019i @ujfalusi FYI

**Comment by salihefee** [comment]
Yes, that is what I said in my message but I can't tell if that is placebo or it is true after cycling back and forth between the two drivers.

And I forgot to mention, but the said issues are with the internal speakers. A speaker connected from the 3.5mm audio jack does not have the said problems. Now that i think about it, does that eliminate the driver as being the culprit? The internal speakers work fine on Windows 11 though. Forgive me for my ignorance since I am not that knowledgeable about the subject and how drivers work in general. 

Thank you.

**Comment by plbossart** [comment]
If's very simple: add “options snd-intel-dspcfg dsp_driver=1” to /etc/modprobe.d/alsa-base.conf. power-cycle and test the sound on internal speakers.

Remove the option, power-cyle and re-test the sound on internal speakers.

If you can't tell the difference there is no bug....
