### ISSUE TITLE
[BUG] refactoring breaks sof-rt5682 audio on chromebook; successfully bisected

### ISSUE THREAD

**Issue by 135e2** [thesofproject/linux#4807]
As described in the [kernel mailing list](https://lore.kernel.org/regressions/6013930.lOV4Wx5bFT@ayana/), commit [31ed8da](https://github.com/torvalds/linux/commit/31ed8da1c8e5e504710bb36863700e3389f8fc81) (ASoC: SOF: sof-audio:
Modify logic for enabling/disabling topology cores) seems to break audio on tigerlake chromebooks with soundcard sof-rt5682.

`alsa-info` and `dmesg` log pasted below (w/ dynamic debugging enabled), for both the working version and the broken version:
### revert 31ed8da, working
[alsa-info](http://alsa-project.org/db/?f=d570a71a13919eefb96e38f578c21adeaf75f442)
[full dmesg](https://github.com/thesofproject/linux/files/14176762/revert-31ed8da-dmesg.txt)

### vanilla linux-git kernel, no sound
[alsa-info](http://alsa-project.org/db/?f=d670ee203fcfb628469ba0e3f7f0d92abf3dd50c)
[full-dmesg](https://github.com/thesofproject/linux/files/14176758/vanilla-mainline-dmesg.txt)

### changes suggested in the email, still no sound
```
diff --git a/sound/soc/sof/sof-audio.c b/sound/soc/sof/sof-audio.c
index e693dcb475e4..a16dee8ee704 100644
--- a/sound/soc/sof/sof-audio.c
+++ b/sound/soc/sof/sof-audio.c
@@ -221,7 +221,7 @@ static int sof_widget_setup_unlocked(struct
snd_sof_dev *sdev,
 pipe_widget_free:
        if (swidget->id != snd_soc_dapm_scheduler) {
                sof_widget_free_unlocked(sdev, swidget->spipe->pipe_widget);
-       } else {
+       } else if (!use_count_decremented) {
                int j;

                /* decrement ref count for all cores that were updated previously */
```
[alsa-info](http://alsa-project.org/db/?f=98137efc49dc5f0bded8174dca39952719aa8653)
[full-dmesg](https://github.com/thesofproject/linux/files/14176744/patch-2-dmesg.txt)

---
Guess I'll also leave a link to the original issue here, maybe the ucm confs wasn't configured correctly either:
> https://github.com/WeirdTreeThing/chromebook-linux-audio/issues/70
https://github.com/WeirdTreeThing/chromebook-ucm-conf/tree/main/sof-rt5682

---
I don't really know much about the ALSA nor the linux sound subsystem, so apologize in advance if I did something wrong or if there're things can help further debugging, please let me know.

**Comment by ujfalusi** [comment]
@135e2, thank you for the logs, I see where the failure is:
working:
```
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PGA5.0 freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM2P freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30110000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.4.DMIC0.IN freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget DMIC0.IN freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30210000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget BUF4.0 freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40070000
snd_sof:snd_sof_dsp_core_put: sof-audio-pci-intel-tgl 0000:00:1f.3: Core 1 powered down
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM99C freed
```
fail:
```
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PGA5.0 freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PCM2P freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30110000
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40070000
snd_sof:snd_sof_dsp_core_put: sof-audio-pci-intel-tgl 0000:00:1f.3: Core 1 powered down
snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.4.DMIC0.IN freed
snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000
sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx error for 0x30020000 (msg/reply size: 12/0): -13
sof-audio-pci-intel-tgl 0000:00:1f.3: failed to free widget DMIC0.IN
```
Core1 is shut down too early while we still have widgets on the pipeline and the scheduler widget is in the middle of the path.
@ranj063, @plbossart, any quick idea?

**Comment by ujfalusi** [comment]
The topology used is `sof-tgl-max98373-rt5682.tplg`

**Comment by ujfalusi** [comment]
@135e2, can this patch help in your setup:
[0001-ASoC-SOF-sof-audio-Manage-core-refcount-per-widget-a.patch.txt](https://github.com/thesofproject/linux/files/14181958/0001-ASoC-SOF-sof-audio-Manage-core-refcount-per-widget-a.patch.txt)

**Comment by plbossart** [comment]
where does this topology come from? sof-bin or the Chrome overlays?

**Comment by ranj063** [comment]
> @135e2, can this patch help in your setup: [0001-ASoC-SOF-sof-audio-Manage-core-refcount-per-widget-a.patch.txt](https://github.com/thesofproject/linux/files/14181958/0001-ASoC-SOF-sof-audio-Manage-core-refcount-per-widget-a.patch.txt)

@ujfalusi I think I know the problem. This problem arises in the case of static pipelines where the widgets are freed in the order they're in the widget_list and in this case it so happens that the pipeline widget gets freed before the widgets in the pipeline themselves. Let me think a bit more about how to fix it gracefully.

**Comment by ranj063** [comment]
@135e2 can you please try this diff and see if it fixes your issue?
```
diff --git a/sound/soc/sof/ipc3-topology.c b/sound/soc/sof/ipc3-topology.c
index 0970dbdfa78a..b1bb287a20b2 100644
--- a/sound/soc/sof/ipc3-topology.c
+++ b/sound/soc/sof/ipc3-topology.c
@@ -2435,9 +2435,40 @@ static int sof_ipc3_tear_down_all_pipelines(struct snd_sof_dev *sdev, bool verif
                        continue;
                }
 
-               ret = sof_widget_free(sdev, swidget);
-               if (ret < 0)
-                       return ret;
+               /*
+                * do not free the scheduler widgets yet so that the secondary cores do not get
+                * powered down before all the widgets associated with the widgets are freed.
+                */
+               if (swidget->id != snd_soc_dapm_scheduler) {
+                       ret = sof_widget_free(sdev, swidget);
+                       if (ret < 0)
+                               return ret;
+               }
+       }
+
+       /* free the scheduler widgets now */
+       list_for_each_entry(swidget, &sdev->widget_list, list) {
+               if (swidget->dynamic_pipeline_widget) {
+                       dyn_widgets = true;
+                       continue;
+               }
+
+               /* Do not free widgets for static pipelines with FW older than SOF2.2 */
+               if (!verify && !swidget->dynamic_pipeline_widget &&
+                   SOF_FW_VER(v->major, v->minor, v->micro) < SOF_FW_VER(2, 2, 0)) {
+                       mutex_lock(&swidget->setup_mutex);
+                       swidget->use_count = 0;
+                       mutex_unlock(&swidget->setup_mutex);
+                       if (swidget->spipe)
+                               swidget->spipe->complete = 0;
+                       continue;
+               }
+
+               if (swidget->id == snd_soc_dapm_scheduler) {
+                       ret = sof_widget_free(sdev, swidget);
+                       if (ret < 0)
+                               return ret;
+               }
        }
 
        /*

```

**Comment by plbossart** [comment]
@ranj063 why would we have a static pipeline? Haven't we moved all topologies to dynamic stuff?

**Comment by ranj063** [comment]
> @ranj063 why would we have a static pipeline? Haven't we moved all topologies to dynamic stuff?

@plbossart this is a TGL chromebook and those still use static pipelines

**Comment by 135e2** [comment]
> where does this topology come from? sof-bin or the Chrome overlays?

> this is a TGL chromebook and those still use static pipelines

Yep, it's taken directly from sof-bin.


> @135e2 can you please try this diff and see if it fixes your issue?
> 
> ```
> diff --git a/sound/soc/sof/ipc3-topology.c b/sound/soc/sof/ipc3-topology.c
> index 0970dbdfa78a..b1bb287a20b2 100644
> --- a/sound/soc/sof/ipc3-topology.c
> +++ b/sound/soc/sof/ipc3-topology.c
> @@ -2435,9 +2435,40 @@ static int sof_ipc3_tear_down_all_pipelines(struct snd_sof_dev *sdev, bool verif
>                         continue;
>                 }
>  
> -               ret = sof_widget_free(sdev, swidget);
> -               if (ret < 0)
> -                       return ret;
> +               /*
> +                * do not free the scheduler widgets yet so that the secondary cores do not get
> +                * powered down before all the widgets associated with the widgets are freed.
> +                */
> +               if (swidget->id != snd_soc_dapm_scheduler) {
> +                       ret = sof_widget_free(sdev, swidget);
> +                       if (ret < 0)
> +                               return ret;
> +               }
> +       }
> +
> +       /* free the scheduler widgets now */
> +       list_for_each_entry(swidget, &sdev->widget_list, list) {
> +               if (swidget->dynamic_pipeline_widget) {
> +                       dyn_widgets = true;
> +                       continue;
> +               }
> +
> +               /* Do not free widgets for static pipelines with FW older than SOF2.2 */
> +               if (!verify && !swidget->dynamic_pipeline_widget &&
> +                   SOF_FW_VER(v->major, v->minor, v->micro) < SOF_FW_VER(2, 2, 0)) {
> +                       mutex_lock(&swidget->setup_mutex);
> +                       swidget->use_count = 0;
> +                       mutex_unlock(&swidget->setup_mutex);
> +                       if (swidget->spipe)
> +                               swidget->spipe->complete = 0;
> +                       continue;
> +               }
> +
> +               if (swidget->id == snd_soc_dapm_scheduler) {
> +                       ret = sof_widget_free(sdev, swidget);
> +                       if (ret < 0)
> +                               return ret;
> +               }
>         }
>  
>         /*
> ```

Can confirm this patch fixes the issue. I'll be pasting full dmesg log here just in case.

[patch-3-dmesg.txt](https://github.com/thesofproject/linux/files/14188629/patch-3-dmesg.txt)

**Comment by ranj063** [comment]
> > where does this topology come from? sof-bin or the Chrome overlays?
> 
> > this is a TGL chromebook and those still use static pipelines
> 
> Yep, it's taken directly from sof-bin.
> 
> > @135e2 can you please try this diff and see if it fixes your issue?
> > ```
> > diff --git a/sound/soc/sof/ipc3-topology.c b/sound/soc/sof/ipc3-topology.c
> > index 0970dbdfa78a..b1bb287a20b2 100644
> > --- a/sound/soc/sof/ipc3-topology.c
> > +++ b/sound/soc/sof/ipc3-topology.c
> > @@ -2435,9 +2435,40 @@ static int sof_ipc3_tear_down_all_pipelines(struct snd_sof_dev *sdev, bool verif
> >                         continue;
> >                 }
> >  
> > -               ret = sof_widget_free(sdev, swidget);
> > -               if (ret < 0)
> > -                       return ret;
> > +               /*
> > +                * do not free the scheduler widgets yet so that the secondary cores do not get
> > +                * powered down before all the widgets associated with the widgets are freed.
> > +                */
> > +               if (swidget->id != snd_soc_dapm_scheduler) {
> > +                       ret = sof_widget_free(sdev, swidget);
> > +                       if (ret < 0)
> > +                               return ret;
> > +               }
> > +       }
> > +
> > +       /* free the scheduler widgets now */
> > +       list_for_each_entry(swidget, &sdev->widget_list, list) {
> > +               if (swidget->dynamic_pipeline_widget) {
> > +                       dyn_widgets = true;
> > +                       continue;
> > +               }
> > +
> > +               /* Do not free widgets for static pipelines with FW older than SOF2.2 */
> > +               if (!verify && !swidget->dynamic_pipeline_widget &&
> > +                   SOF_FW_VER(v->major, v->minor, v->micro) < SOF_FW_VER(2, 2, 0)) {
> > +                       mutex_lock(&swidget->setup_mutex);
> > +                       swidget->use_count = 0;
> > +                       mutex_unlock(&swidget->setup_mutex);
> > +                       if (swidget->spipe)
> > +                               swidget->spipe->complete = 0;
> > +                       continue;
> > +               }
> > +
> > +               if (swidget->id == snd_soc_dapm_scheduler) {
> > +                       ret = sof_widget_free(sdev, swidget);
> > +                       if (ret < 0)
> > +                               return ret;
> > +               }
> >         }
> >  
> >         /*
> > ```
> 
> Can confirm this patch fixes the issue. I'll be pasting full dmesg log here just in case.
> 
> [patch-3-dmesg.txt](https://github.com/thesofproject/linux/files/14188629/patch-3-dmesg.txt)

@135e2 thanks for testing. I will post a pull request with the fix soon.

**Comment by ranj063** [comment]
@135e2 here's the PR: https://github.com/thesofproject/linux/pull/4808

**Comment by plbossart** [comment]
Thanks indeed for @135e2 for the bug report and bisect results, much appreciated!

**Comment by ujfalusi** [comment]
@135e2, can you please try the patch from https://github.com/thesofproject/linux/pull/4808 to make sure that we have the right fix

**Comment by 135e2** [comment]
> @135e2, can you please try the patch from #4808 to make sure that we have the right fix

Yes, just tested and it works like a charm.

**Comment by ujfalusi** [comment]
patch upstream: https://lore.kernel.org/linux-sound/20240208133432.1688-1-peter.ujfalusi@linux.intel.com/

**Comment by ujfalusi** [comment]
@135e2, thank you for the detailed report!

**Comment by ujfalusi** [comment]
@ranj063, thank you for the quick fix!
