### ISSUE TITLE
Dummy Output - Missing tplg: sof-adl-rt711-2ch.tplg - Maibenben P429 - Ubuntu

### ISSUE THREAD

**Issue by gradvis** [thesofproject/linux#4811]
This seems very similar to issues like this one [#4611](https://github.com/thesofproject/linux/issues/4611) but I don't know how to apply the same patch to get audio device work. Diagnostic information attached

**Comment by gradvis** [comment]
[lspci.txt](https://github.com/thesofproject/linux/files/14221758/lspci.txt)
[inxi.txt](https://github.com/thesofproject/linux/files/14221759/inxi.txt)
[dmesg-sof-dyndb.txt](https://github.com/thesofproject/linux/files/14221761/dmesg-sof-dyndb.txt)
[alsa-info.txt](https://github.com/thesofproject/linux/files/14221762/alsa-info.txt)

**Comment by plbossart** [comment]
It's a different issue we're never seen before

````
[    4.976078] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: ACPI reports 4 SDW Link devices
[    4.976082] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: Link 1 not selected in firmware
[    4.976084] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: Link 2 not selected in firmware
[    4.976085] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: Link 3 not selected in firmware
[    4.976086] soundwire_intel:sdw_intel_probe_controller: acpi PRP00001:00: Creating 4 SDW Link devices
[    4.976131] soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0: SDW Slave Addr: 20025d071100
[    4.976132] soundwire_bus:sdw_extract_slave_id: soundwire sdw-master-0: SDW Slave class_id 0x00, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x2
[    4.976269] snd_sof_intel_hda:hda_codec_probe: sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0256
````


So ACPI says you have one link with SoundWire and an rt711 SoundWire codec, but somehow an HDaudio codec probes.

It's the moral equivalent of trying to recharge a diesel engine. Different engine, different solution.

I would try to disable the SoundWire link0 and force the use of HDaudio. there's a kernel parameter for this in sdw_acpi.

try to add this to /etc/modprobe.d/alsa-base.conf

options snd-intel-sdw-acpi sdw_link_mask=0x10

That should disable all links 0..3

**Comment by gradvis** [comment]
> I would try to disable the SoundWire link0 and force the use of HDaudio. there's a kernel parameter for this in sdw_acpi.
> 
> try to add this to /etc/modprobe.d/alsa-base.conf
> 
> options snd-intel-sdw-acpi sdw_link_mask=0x10
> 
> That should disable all links 0..3

Thank you!

Your solution works great. Now i have a sound and i totally happy.
