### ISSUE TITLE
[AMD] Compile fails on release-sof-1.8-20210524-238671-geb27653f7110

### ISSUE THREAD

**Issue by telmich** [thesofproject/linux#4827]
```
[17:23] sun:linux-sof% make -j 6
mkdir -p /home/nico/debug-sun/linux-sof/tools/objtool && make O=/home/nico/debug-sun/linux-sof subdir=tools/objtool --no-print-directory -C objtool 
  INSTALL libsubcmd_headers
  CALL    scripts/checksyscalls.sh
  LDS     scripts/module.lds
  MODPOST Module.symvers
ERROR: modpost: "amd_sdw_scan_controller" [sound/soc/sof/amd/snd-sof-amd-acp.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:145: Module.symvers] Error 1
make[1]: *** [/home/nico/debug-sun/linux-sof/Makefile:1873: modpost] Error 2
make: *** [Makefile:240: __sub-make] Error 2
[17:24] sun:linux-sof% git describe 
release-sof-1.8-20210524-238671-geb27653f7110
```

Attached config.
[config.txt](https://github.com/thesofproject/linux/files/14341449/config.txt)

**Comment by telmich** [comment]
If I disable the AMD chipsets, the compile goes through, config attached.
[config-working.txt](https://github.com/thesofproject/linux/files/14341511/config-working.txt)

**Comment by plbossart** [comment]
@vijendarmukunda this is for you

**Comment by vijendarmukunda** [comment]
@telmich: Below mentioned patch is not merged in to SOF github tree.
https://lore.kernel.org/lkml/20240204212207.3158914-1-arnd@kernel.org/T/
Please test with this patch once.

**Comment by vijendarmukunda** [comment]
Below fix has to be merged in SOF github.
https://lore.kernel.org/all/20240204212207.3158914-1-arnd@kernel.org/
