### ISSUE TITLE
[Stress test]: IPC timed out after 39 times unload/load SOF modules on APL with PCM512x

### ISSUE THREAD

**Issue by markyang** [thesofproject/linux#485]
**Summary:**
  IPC timed out after 39 times unload/load SOF modules on APL with PCM512x.
  
**dmesg:**
```
[ 1262.779223] sof-audio sof-audio: channels_min: 2 channels_max: 2
[ 1262.779232] sof-audio sof-audio: pcm: hw params stream 0 dir 0
[ 1262.779241] sof-audio sof-audio: generating page table for 00000000529e6296 size 0x4b00 pages 5
[ 1262.779269] sof-audio sof-audio: period_bytes:0x480
[ 1262.779274] sof-audio sof-audio: periods:16
[ 1262.779287] sof-audio sof-audio: stream_tag 1
[ 1263.081226] sof-audio sof-audio: error: ipc timed out for 0x60010000 size 0x6c
[ 1263.081245] sof-audio sof-audio: status: fw entered - code 00000005
[ 1263.081403] sof-audio sof-audio: error: unexpected fault 0x00000000 trace 0x00004000
[ 1263.081408] sof-audio sof-audio: error: waking up any trace sleepers
[ 1263.081429] sof-audio sof-audio: error: hw params ipc failed for stream 1
[ 1263.081436] sof-audio sof-audio: ASoC: sof-audio hw params failed: -110
[ 1263.081445]  Port5: ASoC: hw_params FE failed -110
[ 1263.082739] sof-audio sof-audio: pcm: free stream 0 dir 0
[ 1263.385205] sof-audio sof-audio: error: ipc timed out for 0x60030000 size 0xc
[ 1263.385224] sof-audio sof-audio: status: fw entered - code 00000005
[ 1263.385370] sof-audio sof-audio: error: unexpected fault 0x00000000 trace 0x00004000
[ 1263.385377] sof-audio sof-audio: error: waking up any trace sleepers
[ 1263.387044] sof-audio sof-audio: rate_min: 48000 rate_max: 48000
```

**Test steps:**
```
1. sof_bootloop.sh(input 500 times)
2. aplay -Dhw:0,0 -fS32_LE -c2 -r 48000 /dev/zero
aplay: main:788: audio open error: Device or resource busy
```

**Test env:**
sof master: a2e6f82e
kernel sof-dev: 62aa5698
tplg: sof-apl-pcm512x.tplg

**Log:**
[dmesg-apl.txt](https://github.com/thesofproject/linux/files/2714393/dmesg-apl.txt)
[logger-t.txt](https://github.com/thesofproject/linux/files/2714394/logger-t.txt)
[logger.txt](https://github.com/thesofproject/linux/files/2714395/logger.txt)
[sof_bootloop.sh](https://github.com/markyang/mysof/blob/master/tools/kmod_scripts/sof_bootloop.sh)

**Comment by mengdonglin** [comment]
@markyang  Is this a regression? If yes, could you help on a git bisect ?

**Comment by markyang** [comment]
@mengdonglin I‘m not sure whether it is a regression or not. 
100-time unloading/loading SOF modules was passed twice before, it maybe also fail if try more times.

**Comment by markyang** [comment]
**Summary:**  
  This issue can also be reproduced on APL-nocodec

**Test env:**
sof master: 872cefe3
kernel sof-dev: 2ac82ee9
tplg: sof-apl-pcm512x.tplg & sof-apl-nocodec.tplg

**Comment by markyang** [comment]
Created a new issue #552 to follow the different callstack on APL-nocodec

**Comment by keyonjie** [comment]
can PR from @ranj063 #568 fix this issue?

**Comment by markyang** [comment]
@keyonjie #568 has been dropped, do we also need to check it?

**Comment by markyang** [comment]
**Summary:**  
  Recently this issue cannot be reproduced on APL with PCM512x.

**Test env:**
sof master: 29f7b31a
kernel sof-dev: 95a0bc34
tplg: sof-apl-pcm512x.tplg

**Comment by wenqingfu** [comment]
Not sure what changes fixed this. It's probably just a matter of possibility. Since we have several load/unload issues, I'm ok to close this one. Maybe @lyakh want to run the test script in issue description more than 100 times and see how it goes.  The test is like removing the carpet while standing on it,  should we return a "device busy" somewhere?
