### ISSUE TITLE
sof-logger -t will stop sometimes

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#486]
'sof-logger -t' should work like 'tail' and always waiting for available logs and output them, but actually it will stop from time to time(start it again will get new logs).

**Comment by plbossart** [comment]
@keyonjie is this fixed, something you are working on, or do you need @wenqingfu to assign someone?

**Comment by kv2019i** [comment]
I can take this. I'm learning about PR248 (possible reopening of this issue) and I think I need to study the sof-logger internals first.
