### ISSUE TITLE
SoundWire: CML: codec driver 'failed to get private value' error

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#4860]
We have a number of errors reported for CML/SoundWire
````
[    6.988564] Failed to get private value: 752001 => 0000 ret=-5
````

I tried for myself on SKU Number: 09C6 and I see this all the time.

[dmesg.log](https://github.com/thesofproject/linux/files/14655635/dmesg.log)

We also see the error in a number of internal tests

#/result/planresultdetail/38998?model=CML_SKU0983_SDW-ipc3&testcase=check-sof-logger

39560?model=CML_SKU0983_SDW-ipc3&testcase=check-kmod-load-unload-25

@bardliao @shumingfan this doesn't seem quite right?

**Comment by plbossart** [comment]
With additional traces, the culprit is the RT715. This shows on boot, so it's not a problem with suspend-resume or something. 

````
[    7.763426] soundwire_cadence:cdns_fill_msg_resp: soundwire_intel soundwire_intel.link.3: Msg ignored for Slave 0
[    7.763433] soundwire_bus:sdw_program_device_num: soundwire sdw-master-0-3: No more devices to enumerate
[    7.763529] soundwire_cadence:cdns_update_slave_status_work: soundwire_intel soundwire_intel.link.3: Slave status change: 0x20000001
[    7.763687] soundwire_bus:sdw_modify_slave_status: rt715 sdw:0:3:025d:0715:00: signaling enumeration completion for Slave 7
[    7.763715] snd_soc_rt711:rt711_sdw_write: rt711 sdw:0:0:025d:0711:00: [rt711_sdw_write] 4e12 <= 00d6
[    7.763818] snd_soc_rt711:rt711_sdw_write: rt711 sdw:0:0:025d:0711:00: [rt711_sdw_write] 4d12 <= 0011
[    7.763942] snd_soc_rt711:rt711_sdw_write: rt711 sdw:0:0:025d:0711:00: [rt711_sdw_write] 4c12 <= 0020
[    7.763998] snd_sof_intel_hda_common:hda_dsp_stream_trigger: sof-audio-pci-intel-cnl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x14001e successful
[    7.764086] snd_soc_rt711:rt711_sdw_write: rt711 sdw:0:0:025d:0711:00: [rt711_sdw_write] 4f13 <= 0091
[    7.764111] snd_soc_rt715:rt715_sdw_write: rt715 sdw:0:3:025d:0715:00: [rt715_sdw_write] ff01 <= 0000
[    7.764118] rt715_index_read_nid: Failed to get private value: 752001 => 0000 ret=-5
[    7.764165] snd_sof:sof_machine_register: sof-audio-pci-intel-cnl 0000:00:1f.3: created machine sof_sdw
````

[dmesg.log](https://github.com/thesofproject/linux/files/14706304/dmesg.log)

Maybe it's the card creation that does something too early?

**Comment by plbossart** [comment]
Adding @jack-cy-yu for comments

**Comment by plbossart** [comment]
This also happens with a 'blacklist snd-sof-sof-sdw', so it's really a problem with the codec driver itself.

**Comment by jack-cy-yu** [comment]
This might because 0x752001 is missed in both rt715_readable_register and rt715_volatile_register, please see the attachment for this issue. Thanks.
[0001-ASoC-rt715-add-vendor-clear-control-register.patch](https://github.com/thesofproject/linux/files/14770820/0001-ASoC-rt715-add-vendor-clear-control-register.patch)

**Comment by plbossart** [comment]
Thanks for the patch @jack-cy-yu it seems to remove the error message

I am not sure what this does though, adding a default value for a volatile register seems very odd to me. @bardliao what do you think?

**Comment by bardliao** [comment]
> Thanks for the patch @jack-cy-yu it seems to remove the error message
> 
> I am not sure what this does though, adding a default value for a volatile register seems very odd to me. @bardliao what do you think?

I think add the register to rt715_readable_register is enough.

**Comment by plbossart** [comment]
> > Thanks for the patch @jack-cy-yu it seems to remove the error message
> > I am not sure what this does though, adding a default value for a volatile register seems very odd to me. @bardliao what do you think?
> 
> I think add the register to rt715_readable_register is enough.

Indeed in my tests adding the one line for readable register seems to be enough.

**Comment by jack-cy-yu** [comment]
okay, I'll add register only to rt715_readable_register and send it upstream.

**Comment by marc-hb** [comment]
Still happening in today's daily 39484?model=CML_SKU0983_SDW-ipc3&testcase=check-sof-logger

**Comment by marc-hb** [comment]
Dumb Github auto-close. Will close once confirmed by daily test results

**Comment by marc-hb** [comment]
Great timing! Not. Our only CML_SKU0983_SDW device just crashed and hung today. I power-cycled it, hopefully OK. Tracked in internal issue 475.

**Comment by marc-hb** [comment]
Green in daily test 40059! Closing, thanks.
