### ISSUE TITLE
[MTL] Kernel log have errror probe with driver i8042 failed with error -5

### ISSUE THREAD

**Issue by ssavati** [thesofproject/linux#4901]
** Description**
Daily MTL verify-kernel-boot-log.sh test failing with below error
[    3.017791] kernel: i8042 i8042: probe with driver i8042 failed with error -5

Step to reproduce
Login into HDA or SDW device and execute below commnad. below cmd is for SDW

TPLG=/lib/firmware/intel/sof-ipc4-tplg/sof-mtl-rt711-l0-rt1316-l23-rt714-l1.tplg MODEL=MTLP_SDW_AIOC SOF_TEST_INTERVAL=5 ~/sof-test/test-case/verify-kernel-boot-log.sh

For more deatils refer daily_performance #39358

attached full log
[dmesg1.txt](https://github.com/thesofproject/linux/files/14854173/dmesg1.txt)

**Comment by plbossart** [comment]
We don't care about this driver @ssavati, see https://github.com/thesofproject/sof-test/issues/1163

**Comment by marc-hb** [comment]
Thanks @ssavati !

Duplicate of sof-test#1163, I will hopefully fix today.
