### ISSUE TITLE
[BUG] sof-firmware-2023.12, alderlake, no sound with kernel 6.6.21

### ISSUE THREAD

**Issue by psammarco** [thesofproject/linux#4910]
Hello folks,

I have recently built a gentoo-sources-6.6.21 kernel (basically mainline with Fedora patches) but it looks like the sound card is not recognised.

The 6.6.21 kernel was built using the previous 6.1.74 config where audio works just fine. 

**Information:**
ThinkPad P14s Gen 3 i7-1260P
Kernel 6.6.21
sof-firmware-2023.12

Output of alsa-info can be found [here](https://alsa-project.org/db/?f=3e4edbeaada8ae009f07d5f9059cba5c03387902).

This is how the soundcard is seen under [6.1.74](https://alsa-project.org/db/?f=c52efeed490bce3d7b0a1a49ce4e89efb5c8198d). Kernel config can be found [here](https://sprunge.us/1UzYcq).

Thanks :)

**Comment by plbossart** [comment]
It's probably something missing in your .config @psammarco, the HDaudio codecs are not detected:

````
[   15.603316] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #0 probe error, ret: -2
[   15.604291] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #2 probe error, ret: -2
[   15.604783] sof-audio-pci-intel-tgl 0000:00:1f.3: no hda codecs found!
[   15.604798] sof-audio-pci-intel-tgl 0000:00:1f.3: warning: No matching ASoC machine driver found
````

Can you clone this: https://github.com/thesofproject/kconfig
and then update your .config with 

kconfig/kconfig-distro-sof-update.sh

See https://thesofproject.github.io/latest/getting_started/setup_linux/install_locally.html

Also you should try the recommendations in https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#disable-sof-on-pci-hdaudio-devices-to-test-audio-playback to see what happens with the codec detection, it's not clear to me it's an SOF driver issue.

**Comment by psammarco** [comment]
Hello @plbossart ,

apology for the late reply but I just saw this yesterday.

You were right this was not a bug in sof. I merged my kernel config using the script you recommended and I can confirm audio works on 6.6.21.

Thanks
