### ISSUE TITLE
ba-mtlp-sdw-aioc-02: rt7111 codec lost, Msg ignored for Slave 0

### ISSUE THREAD

**Issue by marc-hb** [thesofproject/linux#5014]
_Originally posted by @marc-hb in https://github.com/thesofproject/linux/issues/4823#issuecomment-2127760465_

Most tests failed on MTLP_SDW_AIOC `ba-mtlp-sdw-aioc-02` in daily test run 41461?model=MTLP_SDW_AIOC&testcase=check-playback-all-formats

@ssavati is this a brand new device? Has it ever worked?

```
[  305.047841] kernel: soundwire_cadence:cdns_fill_msg_resp: soundwire_intel soundwire_intel.link.0: Msg ignored for Slave 0
[  305.047847] kernel: rt711-sdca sdw:0:0:025d:0711:01: DPN_PortCtrl register write failed for port 3
```
Linux Branch: [topic/sof-dev](https://github.com/thesofproject/linux/tree/topic/sof-dev)
Linux Commit: [deff86c7cb54](https://github.com/thesofproject/linux/commit/deff86c7cb5428925e759b920bc43735c4549092)
KConfig Branch: [master](https://github.com/thesofproject/kconfig/tree/master)
KConfig Commit: [c3171afedc63](https://github.com/thesofproject/kconfig/commit/c3171afedc632c389123d8b2cd77b467b8fa5655)

SOF Branch: [main](https://github.com/thesofproject/sof/tree/main)
SOF Commit: [a8f2b845ce07](https://github.com/thesofproject/sof/commit/a8f2b845ce07559b6d210010bed60a274691bb54)
Zephyr Commit: [9d8059b6e554](https://github.com/zephyrproject-rtos/zephyr/commit/9d8059b6e5541f7f6b4eb1697dccd475f2c1b39b)

```
 305.046276] kernel: snd_sof:sof_ipc4_route_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: bind gain.1.1:0 -> alh-copier.SDW0-Playback.0:0
[  305.046281] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x45010006|0x10004: MOD_BIND
[  305.047647] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x65000000|0x10004: MOD_BIND
[  305.047667] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x45010006|0x10004: MOD_BIND
[  305.047841] kernel: soundwire_cadence:cdns_fill_msg_resp: soundwire_intel soundwire_intel.link.0: Msg ignored for Slave 0
[  305.047847] kernel: rt711-sdca sdw:0:0:025d:0711:01: DPN_PortCtrl register write failed for port 3
[  305.047859] kernel: soundwire sdw-master-0-0: Program transport params failed: -61
[  305.047865] kernel: soundwire sdw-master-0-0: Program params failed: -61
[  305.047870] kernel:  SDW0-Playback: ASoC: error at snd_soc_link_prepare on SDW0-Playback: -61
[  305.047877] kernel:  SDW0-Playback: ASoC: error at __soc_pcm_prepare on SDW0-Playback: -61
[  305.047882] kernel:  Jack Out: ASoC: error at dpcm_be_dai_prepare on Jack Out: -61
[  305.047889] kernel:  Jack Out: ASoC: error at dpcm_fe_dai_prepare on Jack Out: -61
[  305.048228] kernel: snd_sof:sof_pcm_hw_free: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: free stream 0 dir 0
[  305.048239] kernel: snd_sof_intel_hda_common:hda_dsp_stream_trigger: sof-audio-pci-intel-mtl 0000:00:1f.3: FW Poll Status: reg[0x1c0]=0x140000 successful
[  305.048247] kernel: snd_sof:sof_ipc4_trigger_pipelines: sof-audio-pci-intel-mtl 0000:00:1f.3: trigger cmd: 0 state: 2
[  305.048255] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x13000002|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[  305.049397] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x33000000|0x1: GLB_SET_PIPELINE_STATE
[  305.049417] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x13000002|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[  305.049443] kernel: snd_sof:sof_ipc4_route_free: sof-audio-pci-intel-mtl 0000:00:1f.3: unbind modules host-copier.0.playback:0 -> gain.0.1:0


```

cc:
- https://github.com/thesofproject/linux/issues/4872

**Comment by marc-hb** [comment]
> yeah, best to track with a new bug. There's not much we can do with these errors, the entire SoundWire design is based on the premise that devices have an extremely low likelihood of losing sync. Of course Murphy's Law tells us otherwise.

_Originally posted by @plbossart in https://github.com/thesofproject/linux/issues/4823#issuecomment-2127925869_

**Comment by bardliao** [comment]
From https://github.com/thesofproject/linux/issues/5014's PR test https://sof-ci.01.org/linuxpr/PR5010/build3155/devicetest/index.html?model=MTLP_SDW_AIOC&testcase=check-playback-10sec. I can see
```
[  260.714329] kernel: rt711-sdca sdw:0:0:025d:0711:01: DPN_PortCtrl register write failed for port 3
[  260.714339] kernel: soundwire sdw-master-0-0: Program transport params failed: -61
[  260.714345] kernel: soundwire sdw-master-0-0: Program params failed: -61
[  260.714350] kernel:  SDW0-Playback: ASoC: error at snd_soc_link_prepare on SDW0-Playback: -61
[  260.714356] kernel:  SDW0-Playback: ASoC: error at __soc_pcm_prepare on SDW0-Playback: -61
[  260.714361] kernel:  Jack Out: ASoC: error at dpcm_be_dai_prepare on Jack Out: -61
[  260.714366] kernel:  Jack Out: ASoC: error at dpcm_fe_dai_prepare on Jack Out: -61
```
And looking at the dmesg, there is no `Slave attached, programming device number` trace for the rt711 codec. So, it is likely something wrong on sdw link 0 connection.

**Comment by ssavati** [comment]
@marc-hb this device is long back only deployed. Yes it was working fine till 22nd May and most of test passing in
https://sof-ci.01.org/sofpr/PR9158/build4827/devicetest/index.html

I have checked device, unfortunately i did not find quick solution to fix it  and take longer time to fix it so moving device to maintenance mode.

**Comment by plbossart** [comment]
It does look like a device-specific issue indeed, and it's repeatedly on link0 with the same RT711 which is NOT on the AIOC. That means we can rule out the connector/cable usual problems, the RT711 is on the same motherboard.

Trying to write to Port3 is perfectly legit on RT711-sdca, it's the port used for playback, so it's not a case of the kernel using the 'wrong' port.

One possibility is that the BIOS differs and that might cause the DOAIS values to be different, now that we read them from platform firmware. But otherwise it's trending to some hardware issue.

**Comment by marc-hb** [comment]
> I have checked device, unfortunately i did not find quick solution to fix it and take longer time to fix it so moving device to maintenance mode.

So you confirmed a 100% reproduction rate on this particular device?

**Comment by ssavati** [comment]
> So you confirmed a 100% reproduction rate on this particular device?

Yes It's seems to a HW issue. Checked BIOS also, settings are fine.

**Comment by fredoh9** [comment]
Let's check whether Soudwire HW rework is applied or not. This is right step to find right jack.

Then using right jack, let's check alsa settings to find jack is detected as headphone or headset.

**Comment by ssavati** [comment]
It's RVP issue. I given it to HW team to look into issue. I have changed the RVP with another RVP ba-mtlp-sdw-aioc-04.

@marc-hb now you can close this issue.
