### ISSUE TITLE
Microphone not working (Lenovo YOGA slim 7i)

### ISSUE THREAD

**Issue by cehkop** [thesofproject/linux#5027]
I upgraded system to ubuntu 24.04 with 6.8.0-31 kernel and my microphone stopped working
Laptop has new AMD Ryzen 7840S and before upgrading, laptop has issue with sound. Mic was working. 
After upgrading, sound is perfect, but mic is off

Here are logs:
```
uname -a
Linux yoga 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```
inxi -A
Audio:
  Device-1: AMD Rembrandt Radeon High Definition Audio driver: snd_hda_intel
  Device-2: AMD ACP/ACP3X/ACP6x Audio Coprocessor driver: snd_pci_acp6x
  Device-3: AMD Family 17h/19h HD Audio driver: snd_hda_intel
  API: ALSA v: k6.8.0-31-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active
```

```
sudo dmesg | grep snd
[    3.948575] snd_pci_acp6x 0000:c3:00.5: enabling device (0000 -> 0002)
[    4.055061] snd_hda_intel 0000:c3:00.1: enabling device (0000 -> 0002)
[    4.055134] snd_hda_intel 0000:c3:00.1: Handle vga_switcheroo audio client
[    4.056262] snd_hda_intel 0000:c3:00.6: enabling device (0000 -> 0002)
[    4.078090] snd_hda_codec_realtek hdaudioC1D0: bound i2c-TIAS2781:00 (ops tas2781_hda_comp_ops [snd_hda_scodec_tas2781_i2c])
[    4.078513] snd_hda_codec_realtek hdaudioC1D0: autoconfig for ALC287: line_outs=2 (0x14/0x17/0x0/0x0/0x0) type:speaker
[    4.078519] snd_hda_codec_realtek hdaudioC1D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    4.078522] snd_hda_codec_realtek hdaudioC1D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[    4.078524] snd_hda_codec_realtek hdaudioC1D0:    mono: mono_out=0x0
[    4.078526] snd_hda_codec_realtek hdaudioC1D0:    inputs:
[    4.078528] snd_hda_codec_realtek hdaudioC1D0:      Mic=0x19
[    6.047954] snd_hda_intel 0000:c3:00.1: bound 0000:c3:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
```

Found old issue with the same problem:
https://github.com/thesofproject/linux/issues/5006

alsa-info:
[alsa-info.txt](https://github.com/thesofproject/linux/files/15486521/alsa-info.txt)

**Comment by plbossart** [comment]
"before upgrading, laptop has issue with sound."

Did you mean "before upgrading, laptop has **NO** issue with sound."

Also what was the version before the upgrade?

**Comment by cehkop** [comment]
It was about the speaker. The laptop has several dynamics, but before the upgrade, it seems only one worked and the sound was flat (same time on Windows, it was good). After upgrade, the speaker sounds good, but the microphone doesn't work.

Before the upgrade, it was Ubuntu 23.10, with kernel 6.5 if I remember correctly
