### ISSUE TITLE
Kernel crash without firmware files

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#505]
Issue reported by Ranjani and reproduced by Pierre.

Reproduce steps:
1 installing Ubuntu, 
2. don't copy the fw and tplg binaries are not available under /lib/firmware/intel.
   or rename firmware and topology files with an "_" prefix
3. install the SOF kernel with ktest 
4. Reboot the system

Expected result:
System can boot although audio cannot work

Actual result:
kernel would just hang at the purple screen and the only way out is to reboot to another kernel version.

**Comment by xiulipan** [comment]
I think this is another case of https://github.com/thesofproject/linux/issues/494
@bardliao @plbossart What do you think
These issues are all triggered by failed DSP probe but success PCI probe.
But our PCI probe now have PM ops that directly required DSP probe result.

**Comment by xiulipan** [comment]
```c
static int sof_suspend(struct device *dev, bool runtime_suspend)
{
        struct sof_platform_priv *priv = dev_get_drvdata(dev);
        struct snd_sof_dev *sdev = dev_get_drvdata(&priv->pdev_pcm->dev);
        int ret = 0;

        // Maybe a simple check NULL for sdev here can solve the problem.
```

**Comment by bardliao** [comment]
@xiulipan Yes, I think we can add a simple check there. And we need to add the check in all sof_pci_pm{}

**Comment by libinyang** [comment]
@xiulipan @bardliao @mengdonglin 
After checking the dmesg, I think they are the similar issue.
I will write a patch to have check. Do you have the patch now?

**Comment by libinyang** [comment]
confirmed with my patch, it is caused by the sdev being NULL in sof_suspend.

**Comment by libinyang** [comment]
@xiulipan @bardliao @mengdonglin
I have a patch ready, which can boot successfully, suspend/resume successfully.

**Comment by xiulipan** [comment]
@libinyang 
I think the DSP is not actually **suspend/resume** but just power off/on?

**Comment by libinyang** [comment]
> @libinyang
> I think the DSP is not actually **suspend/resume** but just power off/on?

@xiulipan 
As fw is not loaded successfully, we can't handle FW. Just suspend/resume in kernel space successfully.

**Comment by plbossart** [comment]
fixed
