### ISSUE TITLE
[SoundWire] RT712 VA jack detection is broken

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#5129]
Not sure what happened, but jack detection no longer works with topic/sof-dev 

dc9dd7b28159 ("ASoC: SOF: Intel: hda: refactoring topology name fixup for SDW mach")

SKU Number: 0CC7

@bardliao @ujfalusi FYI

**Comment by plbossart** [comment]
merge/sound-upstream-20240624 works fine
merge/sound-upstream-20240704 is broken

**Comment by plbossart** [comment]
sound/upstream-20240704 is broken as well, so the odds of an upstream regression are high

**Comment by plbossart** [comment]
sound/upstream-20240624 works fine.

**Comment by plbossart** [comment]
sof-dev-rebase-20240624 works fine as well. Oh well.

**Comment by plbossart** [comment]
@shumingfan are you sure the two RT712 changes work on VA?

ASoC: rt712-sdca: add the function for version B
ASoC: rt712-sdca: change the definition name of SDCA channel number

Those were pushed upstream in late June....

**Comment by plbossart** [comment]
````
936abb09c1c7ce2c9c8b7838fc780e98c0140759 is the first bad commit
commit 936abb09c1c7ce2c9c8b7838fc780e98c0140759
Author: Shuming Fan <shumingf@realtek.com>
Date:   Thu Jun 20 18:32:37 2024 +0800

    ASoC: rt712-sdca: add the function for version B
    
    The version B will support the multi-lane function and integrate the DMIC function
    in one SoundWire interface.
    Due to some registers having different default values between version A and B,
    this patch also removes the redundant default registers to avoid confusion.
    
    Signed-off-by: Shuming Fan <shumingf@realtek.com>
    Link: https://patch.msgid.link/20240620103237.2124196-1-shumingf@realtek.com
    Signed-off-by: Mark Brown <broonie@kernel.org>

 sound/soc/codecs/rt712-sdca-sdw.c |  24 +-
 sound/soc/codecs/rt712-sdca-sdw.h |  69 ++---
 sound/soc/codecs/rt712-sdca.c     | 627 +++++++++++++++++++++++++++++++++++---
 sound/soc/codecs/rt712-sdca.h     |  40 +++
````

@shumingfan this commit breaks jack detection for me, can you take a look please?

**Comment by shumingfan** [comment]
@plbossart I pulled the latest sof-dev branch and tested the jack detection of RT713 on SKU 0CC7.
The jack detection still works.
Do you have the log? Let me analyze it.

**Comment by plbossart** [comment]
@shumingfan well nothing happens when I plug the jack...not a single dmesg log. This works fine if I revert the commit mentioned above.

**Comment by shumingfan** [comment]
@plbossart Is it possible to enable the regmap log for RT712?

To set LOG_DEVICE at the top of the source code of regmap.c file.
#define LOG_DEVICE "sdw:0:0:025d:0712:01"
I also want to check the codec driver log whether the rt712_sdca_jack_init function has been called.

**Comment by plbossart** [comment]
I actually have a 713 "sdw:0:0:025d:0713:01" so maybe the changes for RT722 VB impacted that configuration?

I'll add the logs.

**Comment by plbossart** [comment]
If I probe with the headset inserted, the detection happens

````
[   48.755857] rt712-sdca sdw:0:0:025d:0713:01: 40600490 => 3
[   48.756038] rt712-sdca sdw:0:0:025d:0713:01: 40600488 <= 3
[   48.756041] snd_soc_rt712_sdca:rt712_sdca_headset_detect: rt712-sdca sdw:0:0:025d:0713:01: rt712_sdca_headset_detect, detected_mode=0x3
[   48.756044] snd_soc_rt712_sdca:rt712_sdca_jack_detect_handler: rt712-sdca sdw:0:0:025d:0713:01: in rt712_sdca_jack_detect_handler, jack_type=0x1
[   48.756046] snd_soc_rt712_sdca:rt712_sdca_jack_detect_handler: rt712-sdca sdw:0:0:025d:0713:01: in rt712_sdca_jack_detect_handler, btn_type=0x0
[   48.756048] snd_soc_rt712_sdca:rt712_sdca_jack_detect_handler: rt712-sdca sdw:0:0:025d:0713:01: in rt712_sdca_jack_detect_handler, scp_sdca_stat1=0x1, scp_sdca_stat2=0x0
````

but if I leave the drivers suspend, and then insert the jack, nothing happens.

This is the same device that had issues with repeated insert/remove, reported in https://github.com/thesofproject/linux/issues/4872

[dmesg_bad.log](https://github.com/user-attachments/files/16440845/dmesg_bad.log)

**Comment by plbossart** [comment]
Log with the reverted commit @shumingfan, I tried multiple times and the jack is always detected, be it with clock stop or while the device is still active.

[dmesg_good.log](https://github.com/user-attachments/files/16440914/dmesg_good.log)

**Comment by shumingfan** [comment]
@plbossart  I tried the same way to test the jack detection of RT712VA . It still works.
Could you please test this issue when the system doesn't make the bus driver suspend?
If the issue still happens, we check the SCP registers 0x5c/0x5d whether the value is set to one.

**Comment by plbossart** [comment]
@shumingfan it seems that the small change below restores the functionality

````diff
iff --git a/sound/soc/codecs/rt712-sdca-sdw.c b/sound/soc/codecs/rt712-sdca-sdw.c
index 96d8302a8506..ecc541c5a583 100644
--- a/sound/soc/codecs/rt712-sdca-sdw.c
+++ b/sound/soc/codecs/rt712-sdca-sdw.c
@@ -178,8 +178,6 @@ static int rt712_sdca_read_prop(struct sdw_slave *slave)
        unsigned long addr;
        struct sdw_dpn_prop *dpn;
 
-       sdw_slave_read_prop(slave);
-
        prop->scp_int1_mask = SDW_SCP_INT1_BUS_CLASH | SDW_SCP_INT1_PARITY;
        prop->quirks = SDW_SLAVE_QUIRKS_INVALID_INITIAL_PARITY;
 
````

Can you remind me why we needed this change? I have an early prototype so it could be that the _DSD is not quite correct?

**Comment by plbossart** [comment]
oh I think I know what happens, device_property_read_bool() returns 'true' when the property is present. MIPI allows this property to have a 'false' value.

I knew this months ago, see https://github.com/thesofproject/linux/pull/4857/commits/d4546b03db73d5e05a0f498b18192bf4015bb474, but I didn't connect the dots.

Gah.

**Comment by bardliao** [comment]
> oh I think I know what happens, device_property_read_bool() returns 'true' when the property is present. MIPI allows this property to have a 'false' value.
> 
> I knew this months ago, see [d4546b0](https://github.com/thesofproject/linux/commit/d4546b03db73d5e05a0f498b18192bf4015bb474), but I didn't connect the dots.
> 
> Gah.

But why can't Shuming reproduce the issue even with the 0CC7 device? Did you modify the properties?

**Comment by plbossart** [comment]
@bardliao I didn't modify the properties. I don't think we tested the same branch, it's a conceptual bug with a logical inversion, that isn't platform-specific.  https://github.com/thesofproject/linux/pull/5131 works fine on top of topic/sof-dev.

**Comment by shumingfan** [comment]
> Can you remind me why we needed this change? I have an early prototype so it could be that the _DSD is not quite correct?

@plbossart 
The codec driver calls the sdw_slave_read_prop function for lane mapping information.
RT712VB could support the multi-lane function.
I tested it with PR #4733.

**Comment by plbossart** [comment]
yes, but the lane mapping information is not in topic/sof-dev, is it? PR #4733 is still worked on. For now, what the changes do is to add a regression wrt jack detection. The problem is that the addition of this function completely kills jack detection - the 'wake-capable' is not set so nothing happens.

**Comment by shumingfan** [comment]
The wake_capable is set to one behind calling sdw_slave_read_prop.
https://github.com/thesofproject/linux/blob/7df4fc116381da3438ad120b97d8fa2a9c4cc857/sound/soc/codecs/rt712-sdca-sdw.c#L249

Is there any code to overwrite this flag?

**Comment by plbossart** [comment]
good point, so there's something else happening in this function that is inverted. I don't have time to debug today, but the changes in PR #5131 do help.

**Comment by bardliao** [comment]
> good point, so there's something else happening in this function that is inverted. I don't have time to debug today, but the changes in PR #5131 do help.

@plbossart I can reproduce the issue. I added some trace and did some test. I am pretty sure that the issue is related to `mipi-sdw-simplified-clockstopprepare-sm-supported`
Jack detection can back to work with below change.
```patch
diff --git a/drivers/soundwire/mipi_disco.c b/drivers/soundwire/mipi_disco.c
index e5d9df26d4dc..0487488cf9ef 100644
--- a/drivers/soundwire/mipi_disco.c
+++ b/drivers/soundwire/mipi_disco.c
@@ -322,6 +322,7 @@ int sdw_slave_read_prop(struct sdw_slave *slave)

        prop->simple_clk_stop_capable = device_property_read_bool(dev,
                        "mipi-sdw-simplified-clockstopprepare-sm-supported");
+       prop->simple_clk_stop_capable = !prop->simple_clk_stop_capable; //bard invert simple_clk_stop_capable

        device_property_read_u32(dev, "mipi-sdw-clockstopprepare-timeout",
                                 &prop->clk_stop_timeout);
```

**Comment by plbossart** [comment]
Thanks @bardliao, this makes my case that the default helper introduces logical inversions.
