### ISSUE TITLE
Enable 4-channel DMIC capture on WHL

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#513]
Connect and enable 4-channel DMIC capture on WHL RVP, including upstreaming the necessary topology and machine driver update.

**Comment by singalsu** [comment]
@mengdonglin OK. What schedule there is for this feature?

**Comment by zhuyingjiang** [comment]
@mengdonglin Now the DMIC can capture 4 channel. @singalsu I think Mengdong means write the tplg file for this customer requirement, I have already write the tplg.

**Comment by singalsu** [comment]
@zhuyingjiang Excellent, can you please upstream your work. (Also I don't have a WHL here).

**Comment by zhuyingjiang** [comment]
@singalsu Yes, I will upstream it after after some check.

**Comment by wenqingfu** [comment]
Is there any PR from SOF repository side can point back to this issue? @zhuyingjiang

**Comment by zhuyingjiang** [comment]
@wenqingfu [#834](https://github.com/thesofproject/sof/pull/834) the tplg can enable a 4 channel DMIC.

**Comment by wenqingfu** [comment]
@zhuyingjiang @mengdonglin can this issue be marked as closed then?

**Comment by zhuyingjiang** [comment]
@wenqingfu Yes, it can be closed.
