### ISSUE TITLE
verify-kernel-boot-log fails with XE errors

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#5134]
Most of platforms failed with this error.
```
[    7.333139] kernel: sysctl table check failed: dev/xe/(null) procname is null
[    7.333150] kernel: sysctl table check failed: dev/xe/(null) No proc_handler
```

Last Working:
Linux Branch:  [topic/sof-dev](https://github.com/thesofproject/linux/tree/topic/sof-dev)
Linux Commit: [7df4fc116381](https://github.com/thesofproject/linux/commit/7df4fc116381da3438ad120b97d8fa2a9c4cc857)

Failed from:
Linux Branch: [topic/sof-dev](https://github.com/thesofproject/linux/tree/topic/sof-dev)
Linux Commit: [baba2a07492b](https://github.com/thesofproject/linux/commit/baba2a07492bd48ccfa8aa0a1873e210eb6cfdfe)

**Comment by plbossart** [comment]
fixed by https://github.com/thesofproject/linux/pull/5133
