### ISSUE TITLE
Write a generic SOF  machine driver and topology for Intel RVP to support HDMI/DP audio, ALC5682 and DMIC

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#514]
HDMI/DP audio, ALC5682 (I2S mode)  and DMIC can be a common audio configurations on recent Intel RVPs.

We hope to have a common machine driver and topology to cover all of them.

**Comment by plbossart** [comment]
you already have the glk_rt5682 machine driver to start from, all you need is to remove the maxim speaker amp.

**Comment by bardliao** [comment]
Fixed by #553
