### ISSUE TITLE
sof_ipc_reply_find_msg() may find wrong message from reply list

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#516]
Today, in sof/ipc.c: sof_ipc_reply_find_msg(), we find message from reply list with comparing to message_id only:
```
	list_for_each_entry(msg, &ipc->reply_list, list) {
		if (SOF_IPC_MESSAGE_ID(msg->header) == header)
			return msg;
	}
```

But the reality is that, we never set this message_id(low 16 bits of the message) in both FW and driver, which means the message_id for all today's messages are 0, with this, finding message in the reply_list with this no-difference message_id, we will always get the first message in the list.

This doesn't introduce issues as our host->fw IPCs are handled serially today, but the finding here really makes no sense, we should fix it.

**Comment by ranj063** [comment]
@lyakh @plbossart can we close this? we dont have a list anymore

**Comment by lyakh** [comment]
agree, made obsolete by #695
