### ISSUE TITLE
[LNL] Sound card can't be created

### ISSUE THREAD

**Issue by oortcomet** [thesofproject/linux#5202]
### Describe the bug
Null pointer dereference happens after applying the new patch and new topology on LNL platform.
So the sound card can't be created.

### To Reproduce
Please use below patch and topology:
Linux kernel patch: https://github.com/thesofproject/linux/pull/5201/commits/8b16099b1b3af5014c50881dfb4b3ceb549891fd
Topology patch: https://github.com/thesofproject/sof/pull/9550/commits/fa12b7ce30e4fc6f6e0e0b899112ba85ea7a4f61

Reproducible on ThinkPad-X1-2-in-1-Gen-10 hardware.

### Environment
Branch name and commit hash of the 2 repositories: sof (topology) and linux (kernel driver).
Kernel: 6.12.0-rc1-next (https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git)
SOF: v2.11.1
Name of the topology file: sof-lnl-rt713-l0-rt1318-l1-2ch.tplg
Name of the platform(s) on which the bug is observed: Lunarlake

[dmesg_SoundCard_issue.txt](https://github.com/user-attachments/files/17291060/dmesg_SoundCard_issue.txt)

**Comment by oortcomet** [comment]
```
[    7.831650] BUG: kernel NULL pointer dereference, address: 000000000000001c
[    7.831652] #PF: supervisor read access in kernel mode
[    7.831653] #PF: error_code(0x0000) - not-present page
[    7.831655] PGD 0 P4D 0 
[    7.831657] Oops: Oops: 0000 [#1] PREEMPT SMP NOPTI
...
[    7.831680] Call Trace:
[    7.831682]  <TASK>
[    7.831683]  ? __die+0x24/0x70
[    7.831687]  ? page_fault_oops+0x15a/0x460
[    7.831692]  ? __warn+0xbe/0x170
[    7.831695]  ? krealloc_noprof+0x28b/0x2b0
[    7.831697]  ? nbcon_cpu_emergency_exit+0xe/0x40
[    7.831703]  ? report_bug+0x18e/0x1a0
[    7.831707]  ? exc_page_fault+0x68/0x1e0
[    7.831710]  ? asm_exc_page_fault+0x26/0x30
[    7.831714]  ? krealloc_noprof+0x96/0x2b0
[    7.831717]  snd_array_new+0x56/0xc0 [snd_hda_core]
[    7.831726]  hdmi_parse_codec+0x2d7/0x4d0 [snd_hda_codec_hdmi]
[    7.831731]  parse_intel_hdmi+0x1b/0x100 [snd_hda_codec_hdmi]
[    7.831734]  patch_i915_adlp_hdmi+0x31/0x70 [snd_hda_codec_hdmi]
[    7.831738]  hdac_hda_codec_probe+0x131/0x400 [snd_soc_hdac_hda]
```

**Comment by oortcomet** [comment]
We switched to sof dev linux kernel and used the same patches and fw. The issue was not reproduced, and all audio functions work.
Kernel: 6.11.0-rc6
https://github.com/thesofproject/linux

So close this issue.

**Comment by ujfalusi** [comment]
@kv2019i, @bardliao, looks like linux-next has an i915/HDA regression?
