### ISSUE TITLE
Upstream: fix debugfs/runtime_pm

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#522]
The current solution relies on get_noresume() so that we can still read the debugfs entries in case of DSP panic, where a regular resume would not succeed. There are also mentions of autosuspend which make no sense.

sound/soc/sof/ipc.c needs to be reworked based on feedback from Rafael whose suggestion was to get rid of the pm calls while reading debugfs. We can make sure that all the values are flushed out of the dsp before suspending which will make the need to wake it up redundant.

**Comment by ranj063** [comment]
@plbossart I looked into the code as it is today and I think we can already get rid of the runtime_pm calls around the memcpy(). These are the situations to consider:

1. when the device is active: no need for any runtime pm calls at all. 
2. when the device is suspended: if the device is suspended, nothing is going to change in terms of the DSP status. So no need to wake it up either. The only question is whether any trace data needs to be flushed out.
3. when the device is in panic state: the device cant be resumed anyway. Also the DSP dumps out all the relevant data out before triggering the panic.

**Comment by ranj063** [comment]
https://github.com/thesofproject/linux/pull/633 fixes this.
