### ISSUE TITLE
Upstream: fix IPC (comments from Mark Brown)

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#524]
a) inline tx_wait_done (if relevant)?

b) check the sequence 
list_move(&msg->list, &ipc->reply_list);
snd_sof_dsp_send_msg(sdev, msg); 

can the send_msg() fail? If yes should the move be done after send? If no can we change the return type of send_msg() to void?

c) change default err from -EINVAL to 0 (ipc_msgs_rx, line 383)

d) Add support for stopping IPC before removing work queues in sof_ipc_free

 e) rename snd_sof_dsp_is_ready() to snd_sof_dsp_is_ipc_ready(), same for all callbacks in byt/apl/etc.

**Comment by ranj063** [comment]
@plbossart I'll pick up this one. I've had it in my mind to do b) for a while.

**Comment by keyonjie** [comment]
good @ranj063 can you look into https://github.com/thesofproject/linux/issues/516 also once you are at there?

**Comment by ranj063** [comment]
@keyonjie sure

**Comment by ranj063** [comment]
@plbossart https://github.com/thesofproject/linux/pull/538 addresses b), c), d) and e) but I think a) might not be relevant because we have a call to snd_sof_dsp_get_reply() in tx_wait_done() that is io bound. Please let me know what you think about it.

**Comment by plbossart** [comment]
@ranj063 yes there is no point in inlining with a wait. Thanks!

**Comment by plbossart** [comment]
fixed.
