### ISSUE TITLE
Upstream: scrub questionable patches

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#531]
We have two patches that are questionable and should probably be removed?

ASoC: SOF: topology: continue parsing when num_hw_configs is not 1
ALSA: HACK: Fix rmmod crash

**Comment by ranj063** [comment]
@plbossart @keyonjie 
ASoC: SOF: topology: continue parsing when num_hw_configs is not 1


this one needs to be reverted but it requires a fix in topology. Let me submit a PR today.

https://github.com/thesofproject/linux/pull/543
and
https://github.com/thesofproject/sof/pull/844

fix this issue.

**Comment by ranj063** [comment]
@plbossart @lgirdwood 
I'm not sure what issue this patch "ALSA: HACK: Fix rmmod crash" was trying to address. 
I couldnt tell much from the commit message either "Something appears to corrupt the runtime->status on second playback..."

But it looks like we can revert it as well. 

https://github.com/thesofproject/linux/pull/544 fixes this.

**Comment by ranj063** [comment]
@plbossart both these patches have been address. OK to close the issue now?
