### ISSUE TITLE
IPC handler should detect FW crash notifications

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#537]
FW sends an IPC message upon a FW exception notifying host driver an exception has occurred. This is currently ignored by the driver afaict.
```
[ 9768.126925] sof-audio sof-audio: error: rx list empty but received 0x4200
[ 9768.126927] sof-audio sof-audio: error: can't find message header 0x1004200
```
This IPC interrupts the host and sends the platform specific offset of the exception log. This should probably be handled in a platform specific detector that could call generic core code to reboot FW etc.

**Comment by xiulipan** [comment]
@lgirdwood 
This is not exception IPC. It should be purge FW request reply from ROM

@keyonjie found this IPCs are coming from
https://github.com/thesofproject/linux/blob/8ba11407f61cc7b78a60c9b244dc963d468ef10b/sound/soc/sof/intel/hda-loader.c#L94
```
	/* step 2: purge FW request */
	snd_sof_dsp_write(sdev, HDA_DSP_BAR, chip->ipc_req,
			  chip->ipc_req_mask | (HDA_DSP_IPC_PURGE_FW |
			  ((stream_tag - 1) << 9)));
```
https://github.com/thesofproject/linux/blob/8ba11407f61cc7b78a60c9b244dc963d468ef10b/sound/soc/sof/intel/hda.h#L193

As there is a `<< 9` so you will always see odd message like `0x1004200 `and `0x1004400`

@keyonjie 
Please check if I am right about above explanation.
PS: I remember there are fix about this?

**Comment by keyonjie** [comment]
this is actually only a warning, please ignore it, I can submit a patch to remove this warning message later.

It is 4200(stream_tag=2) here because stream_tag 1(4000) is occupied by the playback stream during suspend.

**Comment by wenqingfu** [comment]
even if specific 0x4200 is not a problem, the point still stands - say if there is a FW exception like panic, can we reboot the FW?

**Comment by plbossart** [comment]
> even if specific 0x4200 is not a problem, the point still stands - say 
> if there is a FW exception like panic, can we reboot the FW?
>
That's called firmware recovery, where the driver takes the decision to 
reset and restart when the DSP panics or there is a watchdog timeout - 
and there is no support for it yet. It's a known need that's documented 
in issues

https://github.com/thesofproject/linux/issues/452

**Comment by wenqingfu** [comment]
> That's called firmware recovery, where the driver takes the decision to reset and restart when the DSP panics or there is a watchdog timeout - and there is no support for it yet. It's a known need that's documented in issues #452

Yes, sir, tried to find this issue number to link it, but didn't get it. Thank you!

**Comment by xiulipan** [comment]
@lgirdwood I think we have the panic ipc handler inside kernel now:
https://github.com/thesofproject/linux/blob/66ca36b921dbd27778804a440ceea8668614b56c/sound/soc/sof/intel/hda-ipc.c#L194-L201
Maybe we can close this issue? And continue the FW recovery method in #452

**Comment by plbossart** [comment]
@lgirdwood is this issue still current or can it be closed?

**Comment by plbossart** [comment]
closing, this duplicates part of the functionality needed described by https://github.com/thesofproject/linux/issues/452
