### ISSUE TITLE
Should we remove snd_soc_tplg_component_remove() from snd_sof_free_topology()?

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#546]
There are two reason we can (should?) remove snd_soc_tplg_component_remove() from snd_sof_free_topology()
1. 
card->snd_card will be used in remove_widget() and some similar functions calling by snd_soc_tplg_component_remove(). But if we see [soc_cleanup_card_resources()](https://elixir.bootlin.com/linux/latest/source/sound/soc/soc-core.c#L2185), it will call snd_card_free(card->snd_card) and soc_remove_dai_links(card). card->snd_card will no longer be valid after snd_card_free(card->snd_card), and snd_sof_free_topology() will be invoked by soc_remove_dai_links().
```
soc_cleanup_card_resources()
    -> snd_card_free(card->snd_card) /* card->snd_card will be used by snd_soc_tplg_component_remove() */
    -> soc_remove_dai_links()
         -> soc_remove_link_components()
             -> soc_remove_component()
                   ->component->driver->remove()  ie. sof_pcm_remove()
                       -> snd_sof_free_topology()
                          -> snd_soc_tplg_component_remove()
```
So we will use an invalid card->snd_card in snd_soc_tplg_component_remove(). 
2.
snd_soc_tplg_component_remove() will be invoked by snd_soc_unregister_component(), and we call snd_soc_unregister_component() in sof_remove()
```
sof_remove() 
    -> snd_soc_unregister_component() 
        -> __snd_soc_unregister_component()
            -> snd_soc_tplg_component_remove()
```
So we don't need to call it again in snd_sof_free_topology()
@ranj063 @plbossart

**Comment by ranj063** [comment]
@bardliao point 1. is probably not going to be a valid case for us as we do remove the component before we clean up the card. But I agree 2. is a possibility. So yes, we could remove the call to snd_soc_tplg_component_remove() in free_topology. For that matter we could get rid of free_topology() and just set the flag for tplg_loaded to false in pcm_remove().

**Comment by plbossart** [comment]
@ranj063 do we actually need the flag tplg_loaded now? I added it because it was just chaotic but now that everything starts to look good maybe we no longer need this? or keep with as a DEBUG case?

**Comment by ranj063** [comment]
@plbossart yes, you are right, we dont need tplg_loaded anymore. I dont think this flag will ever be set to false unless the module is removed.

**Comment by bardliao** [comment]
@ranj063 @plbossart Sounds like we have a conclusion now. I will send a PR to remove snd_sof_free_topology(). I think we don't need the tplg_loaded at all. topology load/unload looks even now.
