### ISSUE TITLE
Voice Trigger: enable component channel selector

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#574]
There may be more than one microphone supported in always-on mode, but the algorithms may only support a subset (and typically only mono). Implement driver-side changes needed for this component

**Comment by keyonjie** [comment]
it is implemented, will submit patch soon.

**Comment by wenqingfu** [comment]
ok to close now, @keyonjie ?

**Comment by keyonjie** [comment]
yes, thanks for reminding, @wenqingfu. closing it now.
