### ISSUE TITLE
IPC: enable larger data messages

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#575]
Enable larger messages so that e.g. Voice Trigger models can be passed in multiple IPCs to the firmware, by e.g. chunks of 4Kb.

**Comment by keyonjie** [comment]
We actually can store/transmit these large data either in memory window, or inside any place of ADSP SRAM(using the similar method as FW downloading with host DMA stream), need align this with FW.

**Comment by mengdonglin** [comment]
The parameter size for voice trigger modules can be up to 30 KB

**Comment by plbossart** [comment]
On 1/24/19 6:42 AM, Mengdong Lin wrote:
>
> The parameter size for voice trigger modules can be up to 30 KB
>
Yes, but the IPC will have to slice the parameters and transmit them in 
multiple IPC transfers. We cannot afford to have 30KB dedicated to IPC...

**Comment by wenqingfu** [comment]
can be closed after #625 is merged.

**Comment by juimonen** [comment]
PR's are integrated to kernel and sof.
