### ISSUE TITLE
Voice Trigger: enable async/unsolicited notification

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#576]
Enable "metadata" notification to pass information from always-on firmware component to userspace.

**Comment by keyonjie** [comment]
This is enhancement at the moment, won't implement it in Voice Trigger 1.0 release.

**Comment by wenqingfu** [comment]
ok to close now, @keyonjie ?

**Comment by keyonjie** [comment]
This is not implemented in 1.0 release, let's keep it open to track 2.0 implementation.
