### ISSUE TITLE
PM: enable D0i1 support

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#577]
Currently on pm_runtime_suspend we turn off the DSP and reinitialize everything on startup. 
When the device is in active standby and the DSP working without interaction with the rest of the SOC, the PM flows will have to be different.
This will require a new IPC command passed to the firmware.

**Comment by keyonjie** [comment]
This is for next release, won't implement it in Voice Trigger 1.0 release.

**Comment by plbossart** [comment]
closing, already implemented
