### ISSUE TITLE
Up2: IPC error/DSP panic when HDMI support is removed

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#587]
For PM changes, I need to experiment with HDMI removed.
Of course this doesn't even work...

it can't be a memory issue in the firmware since we have fewer components than the default with HDMI (which works).

it's as if the firmware needs the kernel to initialize HDA DAIs even if they are not part of the topology? Or it could be an alignment issue?

kernel: e4fb585e96de3838849990362d52bf9fc1b0eec0
firmware: [8051fe393c88a3a541e102f83fd9135f6d3dca22](https://github.com/thesofproject/sof/commit/8051fe393c88a3a541e102f83fd9135f6d3dca22) (with attached patch for topology)

[dmesg_nohdmi.log](https://github.com/thesofproject/linux/files/2789514/dmesg_nohdmi.log)
[sof-dev-defconfig.txt](https://github.com/thesofproject/linux/files/2789520/sof-dev-defconfig.txt)
[nohdmi.diff.txt](https://github.com/thesofproject/linux/files/2789521/nohdmi.diff.txt)

[   21.131695] sof-audio sof-audio: error: ipc timed out for 0x30010000 size 0x4c
[   21.132168] sof-audio sof-audio: unknown ROM status value ffffffff
[   21.132422] sof-audio sof-audio: error: unexpected fault 0xffffffff trace 0xffffffff
[   21.132960] sof-audio sof-audio: error: DSP failed to add widget id 0 type 23 name : PCM0P stream Passthrough Playback 0 reply 0
[   21.133699] sof-audio sof-audio: ASoC: failed to load widget PCM0P
[   21.134090] sof-audio sof-audio: error: tplg component load failed -110
[   21.134720] sof-audio sof-audio: error: failed to load DSP topology -22
[   21.135139] sof-audio sof-audio: ASoC: failed to probe component -22
[   21.135643] bxt-pcm512x bxt-pcm512x: ASoC: failed to instantiate card -22
[   21.136114] bxt-pcm512x bxt-pcm512x: snd_soc_register_card failed -22

-- edited by Kelly Ledford to add direct link to firmware commit mentioned by plb

**Comment by plbossart** [comment]
it's actually the same error with the standard topology/firmware but with the kernel not including support for HDMI.

**Comment by fredoh9** [comment]
I'm working on this. I'm able to reproduce this problem with UP2 board. I'm also seeing same error without topology/firmware change if kernel remove HDA support. The first question is why this error happens 
 even without HDMI topology. Diving into the problem. If I see any progress, will update here.

**Comment by ranj063** [comment]
@plbossart @fredoh9 i cant reproduce this issue on my up2.
kernel : d7c0864128eca2c9f70ebba8b207ea0efb48cadd
fw: dee2ec871fa7bde52aab05355510c04efc5703c3
----master commit: [e56326a](github.com/thesofproject/sof/commit/e56326ab487ab048bde2a657c0d58ca155a3b4a8)
tplg: all HDMI pipelines removed.
[sof-apl-pcm512x.diff.txt](https://github.com/thesofproject/linux/files/2830673/sof-apl-pcm512x.diff.txt)
same defconfig as above

--- edited by Kelly Ledford to add direct link to firmware commit mentioned by ranj063

**Comment by plbossart** [comment]
@ranj063 confirmed fixed, but I hit a kernel oops if I keep the same topology with HDMI, see https://github.com/thesofproject/linux/issues/617. 
Let's close this issue and check the new sighting

**Comment by stripes416** [comment]
Just as an aside, git bisect says kernel: b145db03cadcc8e182808ea12ddc5440b43b6c86 'fixed' the ipc error.
