### ISSUE TITLE
[Regression]:  Failed to unload snd_sof_nocodec module on APL & BYT(maybe all platforms)

### ISSUE THREAD

**Issue by markyang** [thesofproject/linux#591]
**Summary:**
  Failed to unload snd_sof_nocodec module on APL & BYT(maybe all platforms).
  I'm not sure whether this is an issue or not,  because if I `rmmod snd_sof_intel_hda_common` before `rmmod snd_soc_acpi_intel_match` and `rmmod snd_sof` before `rmmod snd_sof_nocodec`, it will work. (see attached `sof_remove_ok.sh`)

**More info:**
```
$ lsmod  # on kernel: 4.20.0-daily-20190124
...
snd_sof                86016  5 snd_sof_intel_bdw,snd_sof_intel_hsw,sof_acpi_dev,snd_sof_intel_byt
snd_sof_nocodec        16384  2 snd_sof,sof_acpi_dev

$ lsmod  # on kernel: 4.20.0-daily-20190122 or previous version
...
snd_sof_nocodec        16384  1 sof_acpi_dev
snd_sof                86016  6 snd_sof_intel_bdw,snd_sof_nocodec,snd_sof_intel_hsw,sof_acpi_dev,snd_sof_intel_byt
```

**Test steps:**
```
1. sudo ./sof_remove.sh
...
Removing snd_sof_nocodec
rmmod: ERROR: Module snd_sof_nocodec is in use by: snd_sof
Removing snd_sof
...
```

**Test env:**
sof master: 8051fe39
kernel sof-dev: e4fb585e
tplg: sof-apl-pcm512x.tplg
tplg: sof-apl-nocodec.tplg
tplg: test-ssp0-mclk-0-I2S-volume-s16le-s16le-48k-24000k-codec.tplg
tplg: test-ssp0-mclk-0-I2S-volume-s16le-s16le-48k-24000k-nocodec.tplg

**Log:**
[dmesg-apl.txt](https://github.com/thesofproject/linux/files/2790084/dmesg-apl.txt)
[sof_remove.sh.txt](https://github.com/thesofproject/linux/files/2790086/sof_remove.sh.txt)
[sof_remove_ok.sh.txt](https://github.com/thesofproject/linux/files/2790088/sof_remove_ok.sh.txt)

**Comment by mengdonglin** [comment]
@markyang @stevyan could you help to bisect?

**Comment by plbossart** [comment]
On 1/23/19 9:31 PM, Mark Yang wrote:
>
> *Summary:*
> Failed to unload snd_sof_nocodec module on APL & BYT(maybe all platforms).
> I'm not sure whether this is an error or not, because if I |rmmod 
> snd_sof_intel_hda_common| before |rmmod snd_soc_acpi_intel_match| and 
> |rmmod snd_sof| before |rmmod snd_sof_nocodec|, it will work. (see 
> attached |sof_remove_ok.sh|)
>
Fixed with https://github.com/thesofproject/sof/pull/880
>

**Comment by markyang** [comment]
**Summary:**
  This issue cannot be reproduced using the latest scripts
