### ISSUE TITLE
 System cannot resume from S3 when playback on APL-nocodec.

### ISSUE THREAD

**Issue by markyang** [thesofproject/linux#592]
**Summary:**  
  System cannot resume from S3 when playback on APL-nocodec, and the system freeze caused no dmesg or logger info.
  BTW, if there is no aplay, rtcwake works fine.
  
**Test steps:**
```
1. aplay -Dhw:0,0 -c2 -fS16_LE -vv -i music.wav # Terminal 1
2. sudo rtcwake -m mem -s 2  # Terminal 2
```

**Test env:**
sof master: 8051fe39
kernel sof-dev: e4fb585e
tplg: sof-apl-nocodec.tplg

**Comment by mengdonglin** [comment]
@markyang @stevyan could you help to bisect?

**Comment by libinyang** [comment]
As Ranjani mentioned, #582 can fix it. Let's wait for 582 merged.

**Comment by wenqingfu** [comment]
bi-sect always helps since it's such a new issue @markyang

**Comment by ranj063** [comment]
@wenqingfu I'm not sure this is a regression. This should never have worked before PR #582

**Comment by wenqingfu** [comment]
it was green most time in the daily regression reports last week. Maybe this bug is on nocodec? or @markyang was testing something wrong ...

**Comment by keyonjie** [comment]
I remember it worked when I reported this(https://github.com/thesofproject/sof/issues/788) 25 days ago.

**Comment by markyang** [comment]
**The last working test env:**
```
sof master: 03ababfb
kernel sof-dev: a5dd3186
tplg: sof-apl-nocodec.tplg
````
the daily build is here: http://otc-sof-sh-build-01.sh.intel.com/daily/20190122/
I am going to bisect if I'm free.

**Comment by mengdonglin** [comment]
@markyang @stevyan Please help to verify if PR #582 can fix this issue.
According to https://github.com/thesofproject/sof/issues/788#issuecomment-453937254, HDMI playback cannot continue after a S3 cycle on APL w/ pcm512 codec.  And I believe S3 never worked on APL in nocodec mode.

**Comment by DarrenxWang** [comment]
The CML has the same issue.
Test env:
sof cml-001-drop-stable: 1f5a965711
kernel topic/cros-sof-v4.19: f69d61898a 
tplg: sof-cml-rt5682.tplg

**Comment by emilchudzik** [comment]
I have repro using our test env to check D3/D0.
Issue redirect to Bartosz Kokoszko for deeper debugging.

@markyang could you attach dmesg log from your env?

**Comment by markyang** [comment]
> @markyang @stevyan Please help to verify if PR #582 can fix this issue.
> According to [thesofproject/sof#788 (comment)](https://github.com/thesofproject/sof/issues/788#issuecomment-453937254), HDMI playback cannot continue after a S3 cycle on APL w/ pcm512 codec. And I believe S3 never worked on APL in nocodec mode.
@mengdonglin I'm sure it's a regression,  because S3 always works on APL-nocodec with the daily build on Jan 22, 2019 or before. 
----
The last working daily build is here: http://otc-sof-sh-build-01.sh.intel.com/daily/20190122/

**Comment by markyang** [comment]
@emilchudzik I don't know how to get the dmesg log when a device freezes, do you have any good idea?

**Comment by stevyan** [comment]
**Verify Result:**
This issue can be fixed with [PR#582](https://github.com/thesofproject/linux/pull/582)  based on APL-nocodec.

**Test Env:**
sof master: 365b132e
kernel sof-dev: [pr582-8](https://github.com/thesofproject/linux/pull/582)
tplg: sof-apl-nocodec.tplg

**Reference Info:**
> **ubuntu@cd-apl-up2-nocodec-04:\~$** ps aux | grep aplay
> ubuntu    2624  0.0  0.1  76460  5908 pts/0    S    23:58   0:00 aplay --dump-hw-params -Dhw:0,0 -r
> 48000 -c 2 -f S16_LE /dev/zero
> ubuntu    2640  0.0  0.0  21536  1052 pts/0    S+   23:59   0:00 grep --color=auto aplay
> **ubuntu@cd-apl-up2-nocodec-04:\~$** sudo rtcwake -m mem -s 2
> rtcwake: assuming RTC uses UTC ...
> rtcwake: wakeup from "mem" using /dev/rtc0 at Sun Mar 18 20:21:51 2012
> Suspended. Trying resume. **ubuntu@cd-apl-up2-nocodec-04:\~$** Done.

**Comment by libinyang** [comment]
OK. So let wait for #582 merging.

**Comment by DarrenxWang** [comment]
We apply PR #582 to topic/cros-sof-v4.19 kernel branch. Now CML can suspend, but can’t resume.

**Comment by markyang** [comment]
**bi-sect results**
revert c74579aa(ASoC: intel: skl: Fix display power regression), then S3 works.

**Comment by mengdonglin** [comment]
@markyang Good catch! Libin confirmed it's this patch https://github.com/thesofproject/linux/commit/c74579aa177b334b0b96b2b23f08014c5b70e223 caused regression on APL in no-codec mode and will debug it.

**Comment by emilchudzik** [comment]
Is this revert applies also for CML?

**Comment by markyang** [comment]
**Summary:**  
  This issue cannot be reproduced on APL-nocodec anymore.

**Test env:**
sof master: 29f7b31a
kernel sof-dev: 95a0bc34
tplg: sof-apl-pcm512x.tplg

**Comment by mengdonglin** [comment]
I think this issue is solved on APL by merging PR https://github.com/thesofproject/linux/pull/582

@xun2z Please verify the issue for CML (WHL in I2S mode). If you still see the system needs a long time to resume from S3, please file a new issue for CML.
