### ISSUE TITLE
ACPI platforms (Baytrail/CherryTrail): enable PM/runtime_pm

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#608]
Yes I know the MinnowBoard does not properly support suspend/resume, but that's not a reason to not do anything. There are multiple devices where suspend/resume works fine with the legacy drivers. We should really enable power management or we will end-up with untested code paths in our kernel code, really not the right direction

I believe it's a bug and not an enhancement. All platforms are supposed to support PM (suspend/resume) and runtime_pm, except when we have a good reason not to do so as with the MinnowBoard.

**Comment by Jiangxinx** [comment]
Still can not support runtime_pm on BYT platform.
***Env***
build date: 2019-08-02
sof master: 3ed68f15
kernel sof-dev: 9d7da69a
tplg: sof-byt-rt5651.tplg

**Comment by plbossart** [comment]
system suspend/resume is supported on Baytrail/Cherrytrail. pm_runtime is not but there's no power benefits anyways.
