### ISSUE TITLE
Firmware ABI changes are not reflected in kernel

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#639]
Guys, this is really sloppy work. There is no reason why ABI changes at the firmware level are not propagated to the kernel files with a matching PR or issue raised to make sure we remain aligned. Whoever adds a change to firmware files has a moral duty to follow-up on the kernel side - not necessarily with code but at least an issue.

control.h: tons of cosmetic issues, missing definitions for event_type and comp_event

header.h: missed definitions for GDB_DEBUG and COMP_NOTIFICATION

abi.h has not been updated?

eq.h: completely misaligned

manifest.h: sof_man_get_module() inline function should not be in UAPI file...this should be private to the firmware tree.

tokens.h: missing TONE_SAMPLE_RATE

tone.h: ABI version needs to go

trace.h: missing CLASS_SCHEDULE

**Comment by singalsu** [comment]
Yep, I'll start to work with tone and eq related.

**Comment by plbossart** [comment]
@singalsu maybe I am mistaken but was there any update for the tone and eq stuff?

**Comment by singalsu** [comment]
@plbossart Sorry I forgot this, thanks for remind.

**Comment by singalsu** [comment]
EQ header is addressed by Linux PR #709. The tone header is addressed by SOF PR #1110.

**Comment by singalsu** [comment]
EQ and tone header updates are now merged.

**Comment by plbossart** [comment]
@mmaka1 @lgirdwood I will consider that the kernel code to be shared this week is the reference for now and that firmware changes that haven't been reconciled will be in the next upstream batch, which will likely require an ABI bump for those existing yet unreconciled features.

**Comment by lgirdwood** [comment]
@plbossart Ack, this will be something we will need to manage especially after upstream. See https://github.com/thesofproject/sof/issues/1142, this should give us some tooling to bisect and track changes.

**Comment by plbossart** [comment]
@lgirdwood 90% of the differences in header files are due to 
a) different licenses. It's not clear to me why plain BSD 3-clause isn't enough for all cases
b) doxygen in some cases. we need to be consistent here, either we accept doxygen on both sides or we don't on any side.
c) __packed vs attribute((packed)). Can't we pick one?

**Comment by lgirdwood** [comment]
@plbossart we can reduce the text delta for a and c but I think there will be pushback for b upstream. Using GCC pre-processor reduces these differences to 0 for a and b.

**Comment by plbossart** [comment]
@lgirdwood can we agree that we don't use doxygen for the uapi/ipc parts?
