### ISSUE TITLE
Missing support for existing topology tokens

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#640]
We seem to have a lot of tokens that are not handled...

comp_tokens: preload_count
dai_tokens: dmac_config 
ssp_tokens: clks_control, frame_pulse_width, quirks, tdm_per_slot_padding_flag

There should be something that passes the information to firmware, or we remove those tokens...

**Comment by fredoh9** [comment]
I identified topology definitions and those fields mentioned above are not used in SOF firmware. I need to clarify couple of questions to myself before submitting a PR.

1. comp_token::preload_count is set to 2 in topology file but not being used in firmware. the other fields are not even being used from the beginning. What's the meaning of PRELOAD_COUNT=2?
2. My Dev environment is UP2(appololake), any difference on different platforms.
3. What will be the gain if we remove those fields?

Will submit a PR after investigate a bit more.

**Comment by plbossart** [comment]
@lgirdwood @keyonjie can you please comment on DMA/DAI related tokens?

**Comment by fredoh9** [comment]
@plbossart, I doubled checked all data fields you mentioned are not being used by the firmware in yesterday. Just wondering how you find all missing supports in that tokens. I think i need to go through all data structures to confirm there is no more missing support. It will require quite a bit amount of effort to do crosscheck for me. If you have automated script to do so, I'd like to use that also.

**Comment by plbossart** [comment]
> @plbossart <https://github.com/plbossart>, I doubled checked all data 
> fields you mentioned are not being used by the firmware in yesterday. 
> Just wondering how you find all missing supports in that tokens. I 
> think i need to go through all data structures to confirm there is no 
> more missing support. It will require quite a bit amount of effort to 
> do crosscheck for me. If you have automated script to do so, I'd like 
> to use that also.
>
Sorry I don't quite get the question. I generated the list by looking at 
each IPC field to see if there was a corresponding token, very manual 
work. I don't have anything scripted or a means to formally prove all 
the IPC parts are in use
>

**Comment by fredoh9** [comment]
@plbossart , got you. I will do same thing

**Comment by fredoh9** [comment]
@lgirdwood , one question. I identified the files need to be updated. They are distributed across two projects.
1. Linux project: tokens.h, topology.h, topology.c
2. Sof project: dai.m4, tokens.m4, topology.h
I can do manual update but double checking first. Most of structure seems generated from m4. Is manual update expected when you add or remove tokens or data fields on ward? Or do we need to regenerate files?

**Comment by fredoh9** [comment]
Under internal review with patch files.

**Comment by fredoh9** [comment]
Two PRs are already merged. Please close this CR.
