### ISSUE TITLE
Upstream: trace: clarify use of host_offset

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#655]
Feedback from Takashi Iwai

````
> +
> +	/* return bytes available for copy */
> +	if (sdev->host_offset < pos)
> +		return buffer_size - pos;
> +
> +	return sdev->host_offset - pos;

Are these sdev->host_offset accesses race-free?

If I understand correctly, snd_sof_trace_update_pos() can be called at
any time, and the offset might become inconsistent during these
multiple references.
````

**Comment by kv2019i** [comment]
@plbossart, @ranj063 Hmm, I was about to ack that I don't think this is an issue, but on a second thought, there may be an issue. The rx workqueue is not reentrant but the sysfs debug read can be run at the same time on another CPU. On x86 I think this will still work as integer read/writes are atomic and in worst case you'll read out less traces than there is available, but in general, I don't think this applies on all architectures.

**Comment by ranj063** [comment]
@kv2019i we dont have a workqueue for rx messages anymore. Does that change anything?

**Comment by ranj063** [comment]
@kv2019i like we talked there's definitely a race here and we probably need a spinlock to avoid inconsistencies while reading trace debugfs

**Comment by lgirdwood** [comment]
@kv2019i @ranj063 @plbossart Let's be careful what we are locking as we don't want to block PCM/kcontrol IO on debugFS IO. e.g we may need a separate local lock rather than using a global lock.

**Comment by kv2019i** [comment]
@ranj063 @plbossart @lgirdwood I've been reviewing the code paths from ipc.c to trace.c and elsewhere today and my conclusion is that we do not need a lock here. snd_sof_dev.host_offset is a 32bit value, so a simple load/store is atomic. Further sdev->host_offset is only written from the interrupt handler, so logic in trace.c seems solid. If the avail() function is preempted, we are checking for roll-over case first, so this seems safe as well.

There is a race where process context has decided that no traces are available and is going to sleep (in sof_wait_trace_avail) and that gets interrupted by IPC interrupt. If there's only a single trace IPC, then the user process will be stuck waiting and not woken up. As this only impacts the debugfs side, I wouldn't put a spinlock here just for this case alone.

I'll continue looking at ipc code (actions taken in the interrupt handlers without locks), but so far nothing found. @lyakh Guennadi, FYI for you as well if you are looking at the IPC code now.

If this is seen as issue upstream, I can make a patch that adds the spinlock, not a big thing to do.

**Comment by ranj063** [comment]
> There is a race where process context has decided that no traces are available and is going to sleep (in sof_wait_trace_avail) and that gets interrupted by IPC interrupt. If there's only a single trace IPC, then the user process will be stuck waiting and not woken up. As this only impacts the debugfs side, I wouldn't put a spinlock here just for this case alone.

@kv2019i will we not hit this case quite often when running the sof-logger?

**Comment by kv2019i** [comment]
> @kv2019i will we not hit this case quite often when running the sof-logger?

@ranj063 I believe not, as the firmware will be continuously sending traces. If one wakeup is missed, the next trace will wake up sof_wait_trace_avail.

**Comment by kv2019i** [comment]
I'll go through the rationale again and reply on the upstream mailing list. I don't think we need code changes for this.

**Comment by kv2019i** [comment]
I wrote earlier:
> I'll go through the rationale again and reply on the upstream mailing list. I don't think we need code changes for this.

Ok, it seems Takashi's email is so old that I don't have it in my local email box. It seems it is less effort to just do the patch rather than figure out a sane way to reply on the list, so here goes -> PR800 .
I used a local spinlock and tried to keep code under spinlock to a minimum so this should have minimal impact.
