### ISSUE TITLE
xrun handling should be handled by alsa instead of firmware

### ISSUE THREAD

**Issue by slawblauciak** [thesofproject/linux#660]
Currently the driver assumes the xrun will be handled by the firmware.
Ultimately it should be handled by alsa itself by simply restarting the stream, since firmware isn't capable of resetting DMA pointers.

**Comment by mengdonglin** [comment]
https://github.com/thesofproject/sof/pull/851 is to add support for ALSA xrun recovery in firmware side and also needs a kernel config DEBUG_XRUN_STOP=y

**Comment by plbossart** [comment]
@slawblauciak What you describe is the standard ALSA xrun handling, not sure what is needed in the SOF-specific parts?

**Comment by wenqingfu** [comment]
are we done with this topic? @keyonjie

**Comment by keyonjie** [comment]
@wenqingfu I think so, to move to ALSA Xrun handling, we should define NO_XRUN_RECOVERY in FW and select CONFIG_SND_SOC_SOF_DEBUG_XRUN_STOP in driver(or add this to FW_READY struct later), but as we haven't defined NO_XRUN_RECOVERY in FW yet, so QA haven't verified this.

So in short sentence, let's say we still have half day's work(add it to FW_READY and remove CONFIG_SND_SOC_SOF_DEBUG_XRUN_STOP item in kernel) remained for developing.

**Comment by plbossart** [comment]
@slawblauciak @keyonjie can we close this, it's been stale for 8 months now?

**Comment by keyonjie** [comment]
@plbossart I think so, as we already set NO_XRUN_RECOVERY in FW by default, and in driver CONFIG_SND_SOC_SOF_DEBUG_XRUN_STOP is not selected by default. Let me close it.
