### ISSUE TITLE
[WHL] Entering suspend cause reboot platform

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#662]
This command cause reboot instead od suspend/resume:
`sudo rtcwake -m mem -s 2`

Platform configuration:
WHL RVP
OS: Ubuntu 18.04.2
both kernel: 
topic/sof-dev: branch [69a41dab](https://github.com/thesofproject/linux/commit/69a41dab)
topic/cros-sof-v4.19: [8492020d5967](https://github.com/thesofproject/linux/commit/8492020d5967)

FW: [2a86314](https://github.com/thesofproject/sof/commit/2a863143e80baec223c9f670f3718f24432bb423)
topology: sof-cnl-nocodec.tplg

above command works for kernel branch: sof-dev/7b67e0bb

**Comment by emilchudzik** [comment]
I also checked using power button on platform - the same results.

"Sleep" works on legacy kernel from ubuntu.

**Comment by xun2z** [comment]
I cannot reproduce this reboot issue using the same configuration.

**Test Env**
WHL RVP
topic/cros-sof-v4.19: [8492020d5967](https://github.com/thesofproject/linux/commit/8492020d5967)
sof: [2a86314](https://github.com/thesofproject/sof/commit/2a863143e80baec223c9f670f3718f24432bb423)
topology: sof-cnl-nocodec.tplg

Here is the part of dmesg when entering suspend
```
[   68.491872] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[   68.491962] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[   68.492441] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[   68.492494] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[   68.493023] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[   68.493065] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[   68.493253] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[   68.493381] serial 00:06: activated
[   68.635927] ata3: SATA link down (SStatus 4 SControl 300)
[   68.725757] atkbd serio0: Failed to deactivate keyboard on isa0060/serio0
[   68.986590] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   68.986671] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   69.109761] atkbd serio0: Failed to enable keyboard on isa0060/serio0
[   69.486550] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   69.486632] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   70.390683] e1000e: enp0s31f6 NIC Link is Up 100 Mbps Full Duplex, Flow Control: None
[   70.390687] e1000e 0000:00:1f.6 enp0s31f6: 10/100 speed: disabling TSO
[   71.503766] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[   71.503771] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[   71.503775] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0
[   71.504732] acpi LNXPOWER:08: Turning OFF
[   71.505517] acpi LNXPOWER:07: Turning OFF
[   71.508407] OOM killer enabled.
[   71.508409] Restarting tasks ... done.
[   71.568960] video LNXVIDEO:00: Restoring backlight state
[   71.568964] PM: suspend exit
```

@emilchudzik can you paste the dmesg before you excute this command `sudo rtcwake -m mem -s 2`. Let's make sure there is no other issues.

**Comment by emilchudzik** [comment]
Here is a dmesg dump before entering command, there is no error from audio part:
[dmesg_4.19.14-i2s-8492020d-nocodec.txt](https://github.com/thesofproject/linux/files/2888493/dmesg_4.19.14-i2s-8492020d-nocodec.txt)

I check legacy kernel (default from Ubuntu 18) and Windows - for each od them platform going reboot instead of suspend, so it seems to be a platform specific issue.

On another WHL RVP suspend/sleep works good. I think we can close this issue.

**Comment by wenqingfu** [comment]
> On another WHL RVP suspend/sleep works good. I think we can close this issue.

close per the comment
