### ISSUE TITLE
Change of IIR and FIR coefficients in topology causes an IPC error

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#665]
I noticed this first in Chrome and repeated the same issue in fresh SOF git master and kernel topic/sof-dev. The error happens if I configure topology to use other that default flat EQ responses.

```
singalsu@singalsu-MOBL:~/work/current/sof/sof/tools/build_tools$ git diff
diff --git a/tools/topology/sof/pipe-eq-volume-playback.m4 b/tools/topology/sof/pipe-eq-volume-playback.m4
index 1e262940f5ba..dc34e6a8b0d1 100644
--- a/tools/topology/sof/pipe-eq-volume-playback.m4
+++ b/tools/topology/sof/pipe-eq-volume-playback.m4
@@ -30,7 +30,8 @@ C_CONTROLMIXER(Master Playback Volume, PIPELINE_ID,
 
 
 # Use coefficients for flat frequency response
-include(`eq_iir_coef_flat.m4')
+#include(`eq_iir_coef_flat.m4')
+include(`xxxx_spk_iir.m4')
 
 # EQ Bytes control with max value of 255
 C_CONTROLBYTES(EQIIR, PIPELINE_ID,
@@ -42,7 +43,8 @@ C_CONTROLBYTES(EQIIR, PIPELINE_ID,
        EQIIR_priv)
 
 # Use coefficients for flat frequency response
-include(`eq_fir_coef_flat.m4')
+#include(`eq_fir_coef_flat.m4')
+include(`xxxx_spk_fir.m4')
 
 # EQ Bytes control with max value of 255
 C_CONTROLBYTES(EQFIR, PIPELINE_ID,

```

The error seen in DMESG is

```
[    4.325060] sof-audio-pci 0000:00:0e.0: tplg: load control type 2 name : EQIIR
[    4.325062] sof-audio-pci 0000:00:0e.0: tplg: load kcontrol index 2 chans 0
[    4.325066] sof-audio-pci 0000:00:0e.0: tplg: ready widget id 2 pipe 1 type 33 name : EQIIR1.0 stream none
[    4.325069] sof-audio-pci 0000:00:0e.0:  config: periods snk 2 src 2 fmt 2
[    4.325122] sof-audio-pci 0000:00:0e.0: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    4.325181] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x30010000 size 0x14
[    4.325241] sof-audio-pci 0000:00:0e.0: error: effect loading failed
[    4.325277] sof-audio-pci 0000:00:0e.0: error: DSP failed to add widget id 0 type 33 name : EQIIR1.0 stream none reply -22
[    4.325336] sof-audio-pci 0000:00:0e.0: ASoC: failed to load widget EQIIR1.0
[    4.325376] sof-audio-pci 0000:00:0e.0: error: tplg component load failed -22
[    4.325441] sof-audio-pci 0000:00:0e.0: error: failed to load DSP topology -22
[    4.325483] sof-audio-pci 0000:00:0e.0: ASoC: failed to probe component -22
[    4.325548] bxt-pcm512x bxt-pcm512x: ASoC: failed to instantiate card -22
[    4.325625] bxt-pcm512x bxt-pcm512x: snd_soc_register_card failed -22
[    4.325672] bxt-pcm512x: probe of bxt-pcm512x failed with error -22

```
The error in sof-logger is

```
    0      2          IPC             75330.260417         3.645833 /home/singalsu/work/current/sof/sof/src/ipc/handler.c:920 	ipc: pipe 1 comp 1 -> new (type 5)
    0      2       VOLUME             75335.104167         4.843750 /home/singalsu/work/current/sof/sof/src/audio/volume.c:178 	volume_new()
    0      1          IPC             75506.250000       171.145828 /home/singalsu/work/current/sof/sof/src/ipc/handler.c:138 	ipc: msg too big at 0x1c4

```

The IPC length has become 452 that is much larger than the IIR blob. Also strange that the recipient looks like volume component while it should be eq_iir.

**Comment by singalsu** [comment]
FYI @juimonen @ranj063 I can look into this. I wonder if coming large IPC and processing components related PRs will cause the relevant kernel code parts to be re-written?

**Comment by singalsu** [comment]
I'm starting this and the other related issue now.

**Comment by singalsu** [comment]
The issue looks today different. The IIR coefficients can be changed and the impact of other EQ response can be heard in playback. However, FIR coefficients replace still causes an error:

```
[    4.545430] sof-audio-pci 0000:00:0e.0: error: process loading failed
[    4.545484] sof-audio-pci 0000:00:0e.0: error: DSP failed to add widget id 0 type 33 name : EQFIR1.0 stream none reply 0
[    4.545542] sof-audio-pci 0000:00:0e.0: ASoC: failed to load widget EQFIR1.0
[    4.545582] sof-audio-pci 0000:00:0e.0: error: tplg component load failed -105
[    4.545639] sof-audio-pci 0000:00:0e.0: error: failed to load DSP topology -22
[    4.545680] sof-audio-pci 0000:00:0e.0: ASoC: failed to probe component -22
[    4.545738] bxt-pcm512x bxt-pcm512x: ASoC: failed to instantiate card -22
[    4.545821] bxt-pcm512x bxt-pcm512x: snd_soc_register_card failed -22
[    4.545873] bxt-pcm512x: probe of bxt-pcm512x failed with error -22

```

There's no errors seen in sof-logger trace.

**Comment by singalsu** [comment]
@juimonen @lyakh The error is -ENOBUFS from sof_ipc_tx_message(), the function sof_process_load() does not split large IPC messages. The attempt was to send 504 bytes while max is 384.

**Comment by singalsu** [comment]
The message headers have grown a lot. I was able to confirm that lack of the large message split is the remaining issue. After trimming down the test FIR to about 40 taps (a non-practically low amount for any real need...) it could fit the IPC and this feature worked. So need to work with large IPC split for sof_process_load().

**Comment by juimonen** [comment]
@singalsu yes so this is a known feature which I tried to explain when doing large messages, the effort was futile so I let it be. Setting the params from control during runtime and setting them at boot/topology widget loading (without sending control msg) take different paths... Also we can't call the set_get_large_ctrl_data at widget loading because the pipeline isn't ready. Have to think of some method how to chop also the component loading...

**Comment by singalsu** [comment]
@juimonen Thanks for explanation. Do you mean that the pipeline not ready is a FW issue? I didn't look yet into the code but I wonder if we could avoid dependency to pipeline completion to be able to use the same  set_get_large_ctrl_data function.

**Comment by singalsu** [comment]
This works now for short coefficient sets without need for large IPC. Large IPC version is still in PR polishing phase so I'm still keeping this open.

**Comment by singalsu** [comment]
I tested today by embedding pass/flat/loudness blobs into IIR and FIR topologies as default and it worked perfectly. The current git master does not contain a large IPC loudness blob but my test version that I will upstream later was used.

- Firmware & topology: e69938583a8d15a1d7cb285f219ff782474aabc4

- Linux: 3779ba8c2ca467bf4681608068a271f2cf7ace58

Thanks @juimonen for all the work!

**Comment by singalsu** [comment]
This is OK to close.
