### ISSUE TITLE
Correct the HDA host DMA FMT programming flow

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#670]
According to information from FW side, here is the correct FMT programming flow:

Put DMA into coupled mode for the time of writing format to SDxFMT register.
a. Before writing format to SDxFMT, clear PPCTL.PROCEN bit for corresponding stream index.
b. Write SDxFMT
c. Set PPCTL.PROCEN bit for corresponding stream index.

Then check if https://github.com/thesofproject/sof/issues/856 can be fixed by this change.

**Comment by keyonjie** [comment]
Hi @RanderWang can you please help on this?

We may need to check if something change like below can fix sof issue #856:

```
diff --git a/sound/soc/sof/intel/hda-stream.c b/sound/soc/sof/intel/hda-stream.c
index c70046f20eec..c2c70c7d4907 100644
--- a/sound/soc/sof/intel/hda-stream.c
+++ b/sound/soc/sof/intel/hda-stream.c
@@ -363,12 +363,22 @@ int hda_dsp_stream_hw_params(struct snd_sof_dev *sdev,
                          sd_offset + SOF_HDA_ADSP_REG_CL_SD_CBL,
                          hstream->bufsize);
 
+       /* couple host and link DMA */
+       mask = 0x1 << hstream->index;
+       snd_sof_dsp_update_bits(sdev, HDA_DSP_PP_BAR, SOF_HDA_REG_PP_PPCTL,
+                               mask, 0);
+
        /* program stream format */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
                                sd_offset +
                                SOF_HDA_ADSP_REG_CL_SD_FORMAT,
                                0xffff, hstream->format_val);
 
+       /* decouple host and link DMA */
+       mask = 0x1 << hstream->index;
+       snd_sof_dsp_update_bits(sdev, HDA_DSP_PP_BAR, SOF_HDA_REG_PP_PPCTL,
+                               mask, mask);
+
        /* program last valid index */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
                                sd_offset + SOF_HDA_ADSP_REG_CL_SD_LVI,
```

**Comment by RanderWang** [comment]
I can't reproduce this bug so I can't fix it.

**Comment by plbossart** [comment]
@RanderWang can you clarify if you used the same tests as @keyonjie as described in thesofproject/sof#856 


"Using simultaneous pipelines stress test can duplicate this easily. Scrip here:
https://github.com/thesofproject/sof/blob/master/tools/test/qa/tests/stability_test/multiplex_pipeline-test.sh"

**Comment by keyonjie** [comment]
@RanderWang please use that test script directly, I remember both our QA and FW team can reproduce it also.

**Comment by RanderWang** [comment]
yes, I tried it but still be failed to reproduce it.
