### ISSUE TITLE
IPC TX Flow Clarification 1/3: send an IPC message

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#677]
This issue is to clarify the IPC Tx Flow: 

[1] 

```
sof_ipc_tx_message()
    /* get an empty message */
    msg = msg_get_empty(ipc);
    if (!msg) {
        spin_unlock_irq(&sdev->ipc_lock);
                return -EBUSY;
```

//<<< What happens here? if we try to send too many IPC messages
the SOF code will just crap out since there is no retry mechanism
at a later time.

// Should we have a blocking version of sof_ipc_tx_message() with
a timeout?

// RPMsg provides both solutions, send_to() will block until a TX
buffer is available (with a 15 mn timeout) and try_send_to will return
immediately.

```
    }

    /* schedule the message if not busy */
        if (snd_sof_dsp_is_ipc_ready(sdev)) [2]
        schedule_work(&sdev->ipc->tx_kwork);[3]
```

// why can't we send this immediately on TX? we could split
ipc_tx_next_msg() and send the message immediately with a helper
function.

````
[Rander] we can send this immediately on TX. In original code,
ipc_tx_next_msg() just send msg to dsp without dsp_ready check,
but later we find a bug that two threads would get into ipc_tx_next_msg()
because the check at above [2] is not complete. At that time, I want to
remove this schedule but it is too aggressive, so I gave up.
````

// what happens if the IPC is not ready and we don't schedule? That
was one comment from Mark Brown.

````
[Rander] Now if the IPC is not ready and we don't schedule, The IPC msg
would added in tx_list to wait for a completed msg in tx_wait_done to trigger
a msg in tx_list to be sent
````

// is the idea that if the IPC is not ready, then there is
already a workqueue dealing with the previous TX IPC and a
schedule will happen at the end of that workqueue. But that could
potentially be racy? the spinlocks don't protect _is_ipc_ready().

````
[Rander] is_ipc_ready is protected by spinlock in ipc_tx_next_msg
````
    /* now wait for completion */
        return tx_wait_done(ipc, msg, reply_data); [9]

[2] 

```
hda_dsp_is_ipc_ready(struct snd_sof_dev *sdev)
{
    u32 busy, done;

    /* is DSP ready for next IPC command */
    busy = snd_sof_dsp_read(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCI);
    done = snd_sof_dsp_read(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCIE);
        if ((busy & HDA_DSP_REG_HIPCI_BUSY) ||
```

// This means a previous IPC TX message is still being handled by firmware

```
            (done &HDA_DSP_REG_HIPCIE_DONE))
```

// this means the DSP handled the previous IPC message but is asking for a reply.

[3]

```
 ipc_tx_next_msg(struct work_struct *work)
{
    /* send message if HW ready and message in TX list */
        if (!list_empty(&ipc->tx_list) && snd_sof_dsp_is_ipc_ready(sdev)) {

        /* send first message in TX list */
        msg = list_first_entry(&ipc->tx_list, struct snd_sof_ipc_msg,
                       list);
        ret = snd_sof_dsp_send_msg(sdev, msg); [4]

                /* message sent. move it to the reply list */
        list_move(&msg->list, &ipc->reply_list);
}
```

[4] 

```
hda_dsp_ipc_send_msg(struct snd_sof_dev *sdev, struct snd_sof_ipc_msg *msg)
{
    u32 cmd = msg->header;

    /* send IPC message to DSP */
    sof_mailbox_write(sdev, sdev->host_box.offset, msg->msg_data,
              msg->msg_size);
    snd_sof_dsp_write(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCI,
                cmd | HDA_DSP_REG_HIPCI_BUSY);
```
// should we really do an OR here?

// Marcin states we should not use memory windows for power
messages, so maybe we can use the IPC registers, but if we do,
what is the format for this? BUSY is on but 31.

````
[Rander] It is a good advice. Now the format is  
30 - 28             27 - 16             15 - 0
cmd type             cmd msg            msg id

Actually msg id is alway zero in driver. This format is not work on BDW, because
bit 30 is used by HW

#define SOF_GLB_TYPE_SHIFT			28
#define SOF_GLB_TYPE_MASK			(0xf << SOF_GLB_TYPE_SHIFT)
#define SOF_GLB_TYPE(x)				((x) << SOF_GLB_TYPE_SHIFT)

/* Command Message - Generic */
#define SOF_CMD_TYPE_SHIFT			16
#define SOF_CMD_TYPE_MASK			(0xfff << SOF_CMD_TYPE_SHIFT)
#define SOF_CMD_TYPE(x)				((x) << SOF_CMD_TYPE_SHIFT)

#define SOF_IPC_MESSAGE_ID(x)			((x) & 0xffff)

````

Now we wait for an interrupt

**Comment by RanderWang** [comment]
@plbossart  @lyakh  I update my reply in issue msg for it is easy to follow in context. Please seach [Rander].  Or if you don't like this style, I would reply in normal style

**Comment by mengdonglin** [comment]
Attach Rander's diagram for flow of sending the IPC message
![ipc_send_msg](https://user-images.githubusercontent.com/8703742/53477125-fd4e5300-3aae-11e9-9a7e-68745be0aeca.png)

**Comment by xiulipan** [comment]
>  [4] hda_dsp_ipc_send_msg(struct snd_sof_dev *sdev, struct snd_sof_ipc_msg *msg)
> {
> u32 cmd = msg->header;
> 
> ```
> /* send IPC message to DSP */
> sof_mailbox_write(sdev, sdev->host_box.offset, msg->msg_data,
>           msg->msg_size);
> snd_sof_dsp_write(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCI,
>             cmd | HDA_DSP_REG_HIPCI_BUSY);
> ```
> // should we really do an OR here?

In some case I think this will set the bit, but as the `SOF_CMD_TYPE` increase, some of the CMD will have this bit set to 1.

As @RanderWang mentioned our IPC reister header is 
```
[Rander] It is a good advice. Now the format is  
31 - 28             27 - 16             15 - 0
cmd type             cmd msg            msg id
```
And for the IPC register, We can only use the 0-30 bit for msg, the 31bit is a busy bit.

**Comment by dbaluta** [comment]
@xiulipan @RanderWang if we want to implement a "real" doorbell mechanism we should not send any information via the SHIM layer registers. 

The SHIM layer registers should be used only for triggering interrupts on the other side and letting know about the status. The cmd is already in msg->header and it should be read from mailbox.

Btw, really cool diagram!

**Comment by RanderWang** [comment]
> @xiulipan @RanderWang if we want to implement a "real" doorbell mechanism we should not send any information via the SHIM layer registers.
> 
> The SHIM layer registers should be used only for triggering interrupts on the other side and letting know about the status. The cmd is already in msg->header and it should be read from mailbox.
> 
> Btw, really cool diagram!

@dbaluta  Actually the cmd in SHIM registers are only used for printing debug msg in FW now. And
FW gets msg from mailbox. So to remove cmd in SHIM registers, we need to refine debug msg in FW

**Comment by dbaluta** [comment]
> @dbaluta Actually the cmd in SHIM registers are only used for printing debug msg in FW now. And
> FW gets msg from mailbox. So to remove cmd in SHIM registers, we need to refine debug msg in FW

@RanderWang can you point me a place where debug msg are still using SHIM registers? I thought that i have already fixed that with 7c37501568dc9 ("drivers: Remove unused host_msg field")

**Comment by RanderWang** [comment]
@dbaluta , ok, I am out of day.

**Comment by wenqingfu** [comment]
close as low activity and new IPC discussion should be based on new implementation.
