### ISSUE TITLE
IPC TX Flow Clarification 2/3: Interrupt handling

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#678]
...
Now we wait for an interrupt

Interrupt first part:

[5] 

```
irqreturn_t hda_dsp_ipc_irq_handler(int irq, void *context)
{
    /* store status */
    sdev->irq_status = snd_sof_dsp_read(sdev, HDA_DSP_BAR,
                        HDA_DSP_REG_ADSPIS);

    if (sdev->irq_status & HDA_DSP_ADSPIS_IPC) {
        /* disable IPC interrupt */
        snd_sof_dsp_update_bits_unlocked(sdev, HDA_DSP_BAR,
                         HDA_DSP_REG_ADSPIC,
                         HDA_DSP_ADSPIC_IPC, 0);
        ret = IRQ_WAKE_THREAD;
    }
```

Interrupt second part:

[6] 

```
irqreturn_t hda_dsp_ipc_irq_thread(int irq, void *context)
{
    /* here we handle IPC interrupts only */
    if (!(sdev->irq_status & HDA_DSP_ADSPIS_IPC))
                return ret;
```
// Is this check required? do we have cases where we have other irq sources?

````
[Rander] yes, In legacy interrupt mode, Hda interrupt and IPC interrupt
share the same IRQ number. In MSI mode, I not sure it is like this.
````
    /* is this a reply message from the DSP */
    if (hipcie & HDA_DSP_REG_HIPCIE_DONE &&
        hipcctl & HDA_DSP_REG_HIPCCTL_DONE) {

        hipci = snd_sof_dsp_read(sdev, HDA_DSP_BAR,
                     HDA_DSP_REG_HIPCI);
        msg = hipci & HDA_DSP_REG_HIPCI_MSG_MASK;
        msg_ext = hipcie & HDA_DSP_REG_HIPCIE_MSG_MASK;

        /* mask Done interrupt */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR,
                    HDA_DSP_REG_HIPCCTL,
                    HDA_DSP_REG_HIPCCTL_DONE, 0);

// at this point the IPC cannot handle a new reply to a TX message until [13]

        /* handle immediate reply from DSP core - ignore ROM messages */
                if (msg != 0x1004000)

// What is the definition/format for msg and msg_ext bits?

````
[Rander] It is replied in IPC issue about the format of msg. Now we don't use msg_ext
which is not available on BYT & BDW
````
            reply = snd_sof_ipc_reply(sdev, msg); [7]

// that's the main difference with RPMsg, data provided back are
handled in a callback, no provided back to the initial requester as a
structure argument

        ret = IRQ_HANDLED;
    }

    if (ret == IRQ_HANDLED) {
        /* reenable IPC interrupt */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR, HDA_DSP_REG_ADSPIC,
                    HDA_DSP_ADSPIC_IPC, HDA_DSP_ADSPIC_IPC);
        }
// Here the IRQ is re-enabled but that's only for a potential DSP-initiated messages.

````
[Rander]  According to code, it is for both reply and initiated messages
````
}

**Comment by RanderWang** [comment]
@plbossart @lyakh I update my reply in issue msg for it is easy to follow in context. Please seach [Rander]. Or if you don't like this style, I would reply in normal style

**Comment by xiulipan** [comment]
[6]
```
 irqreturn_t hda_dsp_ipc_irq_thread(int irq, void *context)
{
    /* here we handle IPC interrupts only */
    if (!(sdev->irq_status & HDA_DSP_ADSPIS_IPC))
                return ret;
// Is this check required? do we have cases where we have other irq sources?

```
Yes, we need have other IRQ share the same IRQ NO
https://github.com/thesofproject/linux/blob/ee19d24e26c7e8cb193bfb72cce27561ec281c92/sound/soc/sof/intel/hda-stream.c#L415-L477

The other source is in 

```

    /* is this a reply message from the DSP */
    if (hipcie & HDA_DSP_REG_HIPCIE_DONE &&
        hipcctl & HDA_DSP_REG_HIPCCTL_DONE) {

        hipci = snd_sof_dsp_read(sdev, HDA_DSP_BAR,
                     HDA_DSP_REG_HIPCI);
        msg = hipci & HDA_DSP_REG_HIPCI_MSG_MASK;
        msg_ext = hipcie & HDA_DSP_REG_HIPCIE_MSG_MASK;



        /* mask Done interrupt */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR,
                    HDA_DSP_REG_HIPCCTL,
                    HDA_DSP_REG_HIPCCTL_DONE, 0);

// at this point the IPC cannot handle a new reply to a TX message until [13]

        /* handle immediate reply from DSP core - ignore ROM messages */
                if (msg != 0x1004000)

// What is the definition/format for msg and msg_ext bits?
```
Please see @RanderWang explanation in #677 for msg header.
Platforms before APL did not have `msg_ext ` at all.
I think we did not use msg_ext for the IPC, but used it as some status bit in boot up and panic handler.
https://github.com/thesofproject/linux/blob/ee19d24e26c7e8cb193bfb72cce27561ec281c92/sound/soc/sof/intel/hda-ipc.c#L194-L198

```

            reply = snd_sof_ipc_reply(sdev, msg); [7]

// that's the main difference with RPMsg, data provided back are
handled in a callback, no provided back to the initial requester as a
structure argument

        ret = IRQ_HANDLED;
    }


    if (ret == IRQ_HANDLED) {
        /* reenable IPC interrupt */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR, HDA_DSP_REG_ADSPIC,
                    HDA_DSP_ADSPIC_IPC, HDA_DSP_ADSPIC_IPC);
        }
// Here the IRQ is re-enabled but that's only for a potential DSP-initiated messages.
}
```

**Comment by plbossart** [comment]
> Yes, we need have other IRQ share the same IRQ NO
> [linux/sound/soc/sof/intel/hda-stream.c](https://github.com/thesofproject/linux/blob/ee19d24e26c7e8cb193bfb72cce27561ec281c92/sound/soc/sof/intel/hda-stream.c#L415-L477)

So why don't we filter the stream interrupt then?

**Comment by plbossart** [comment]
> ```
> 
> ```
> 
> Please see @RanderWang explanation in #677 for msg header.
> 
> Platforms before APL did not have `msg_ext ` at all.
> 
> I think we did not use msg_ext for the IPC, but used it as some status bit in boot up and panic handler.

Where is the reference documentation for this? I am not happy with magic values popping up without explanations.

**Comment by wenqingfu** [comment]
close as low activity and new IPC discussion should be based on new implementation.
