### ISSUE TITLE
IPC TX Flow Clarification 3/3: process the reply

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#679]
To follow up #677 (with flow diagram) and #678 
...
(interrupt context)
[7] 
```
snd_sof_ipc_reply(struct snd_sof_dev *sdev, u32 msg_id)
{
    struct snd_sof_ipc_msg *msg;

    msg = sof_ipc_reply_find_msg(sdev->ipc, msg_id);
    if (!msg) {
        dev_err(sdev->dev, "error: can't find message header 0x%x",
            msg_id);
        return -EINVAL;
        }
// What is the definition of msg_id? what do we have a list here?

````
[Rander] We never set msg id in msg, so it is always zero. And we always get the head
msg in list, so we should rework this function
```

    /* wake up and return the error if we have waiters on this message ? */
        sof_ipc_tx_msg_reply_complete(sdev->ipc, msg); [8]
}
```

(interrupt context)
[8]
```
sof_ipc_tx_msg_reply_complete(struct snd_sof_ipc *ipc,
                      struct snd_sof_ipc_msg *msg)
{
    msg->ipc_complete = true;
    wake_up(&msg->waitq); [10]
}
```

(normal context)
[9]
```
tx_wait_done()
{
    /* wait for DSP IPC completion */
    ret = wait_event_timeout(msg->waitq, msg->ipc_complete,
                 msecs_to_jiffies(IPC_TIMEOUT_MS));
```
[10]  
```
 /* copy the data returned from DSP */
    ret = snd_sof_dsp_get_reply(sdev, msg);
    if (msg->reply_size)
        memcpy(reply_data, msg->reply_data, msg->reply_size);

    /* return message body to empty list */
    list_move(&msg->list, &ipc->empty_list);

    snd_sof_dsp_cmd_done(sdev, SOF_IPC_DSP_REPLY); [11]

    /* continue to schedule any remaining messages... */
    schedule_work(&sdev->ipc->tx_kwork);
}

```
[11] 
```
hda_dsp_ipc_cmd_done(struct snd_sof_dev *sdev, int dir)
{
        /*
         * set DONE bit - tell DSP we have received the reply msg
         * from DSP, and processed it, don't send more reply to host
         */
        snd_sof_dsp_update_bits_forced(sdev,HDA_DSP_BAR,
                           HDA_DSP_REG_HIPCIE,
                           HDA_DSP_REG_HIPCIE_DONE,
                           HDA_DSP_REG_HIPCIE_DONE);
```
[12] only here can a new TX IPC message be sent per the definition of
is_ipc_ready(), so in effect we are dependent on a waitqueue before
clearing hardware bits.

```
        /* unmask Done interrupt */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR,
                    HDA_DSP_REG_HIPCCTL,
                    HDA_DSP_REG_HIPCCTL_DONE,
                    HDA_DSP_REG_HIPCCTL_DONE);
```

[13] // only at this point can a new reply to a TX message be handled.

**Comment by dbaluta** [comment]
@mengdonglin  can you please add markers for the code (start and end the code sections with ``` ).It is hard to read as it is.

**Comment by xiulipan** [comment]
@dbaluta good point. Already done for 3 issues.

**Comment by RanderWang** [comment]
@plbossart @lyakh I update my reply in issue msg for it is easy to follow in context. Please seach [Rander]. Or if you don't like this style, I would reply in normal style

**Comment by plbossart** [comment]
Sorry but it's just horrible to do this in github. Interleaved answers in the code are just a lot more convenient than this thread.

**Comment by wenqingfu** [comment]
> Sorry but it's just horrible to do this in github. Interleaved answers in the code are just a lot more convenient than this thread.

there was a mismatch of marker used, just fixed.

**Comment by wenqingfu** [comment]
close as low activity and new IPC discussion should be based on new implementation.
