### ISSUE TITLE
Check topology compatibility with FW ABI

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#691]
With components added/removed in the FW during compilation, there needs to be means to check whether the topology being loaded is compatible with the FW. Could we use the tplg manifest for this? 
Filing as a linux issue but needs work in SOF tplg as well.

@bardliao could you please help with this?

**Comment by plbossart** [comment]
There was a previous issue to check first if the topology file could be checked against the kernel (e.g. on some cAVS platforms there are messages showing the topology file is very very old and needs to be handled in a specific way). https://github.com/thesofproject/linux/issues/331

I think this issue goes one step further to check if the components represented in the topology are actually present/functional in the firmware.

**Comment by fredoh9** [comment]
@bardliao as you working on this, please take care of previous issue #331 too.

**Comment by bardliao** [comment]
@fredoh9 Yes, they are very similar issue. @ranj063 Yes, I think we can use tplg manifest to check ABI or something we want to check. [soc_tplg_manifest_load](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/soc-topology.c#L2407).
The idea is to create a SectionManifest section in the topology.

**Comment by bardliao** [comment]
If I add below to a .conf file and generate the .tplg file
```
SectionData."SOF_ABI" {
               bytes "0x53,0x4f,0x46,0x00"
}

SectionManifest."sof_manifest" {
        data [
                SOF_ABI
        ]
}
```
I can get 0x53, 0x4f, 0x46 and 0x00 from man->priv.data[0] to [3] in sof_manifest().
I think it is good enough for ABI check. So next step is to create SectionManifest section in topology.

**Comment by plbossart** [comment]
@ranj063 IIRC this is implemented, no? Can we close?

**Comment by lgirdwood** [comment]
Ack, I can even see the topology ABI in dev_info now.

**Comment by ranj063** [comment]
@plbossart yes closing now.
