### ISSUE TITLE
Topology: Need to manage multiple configurations per DAI

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#697]
We need the ability to expose multiple configurations per DAI in the topology file, and means for the driver to pass the relevant configuration over IPC to the firmware.
One example is support for 8 or 16 kHz for a Bluetooth HFP link.

this was filed initially as https://github.com/thesofproject/soft/issues/11. Making sure this is tracked at the kernel level as well.

**Comment by fredoh9** [comment]
Interesting issue. I'm not quite sure what change in kernel driver is required at this moment, but I will review at full stacks, driver/topology files/firmware. I will come up with the solution.

**Comment by lgirdwood** [comment]
@fredoh9 ASoC topology supports this already but is likely untested. You will need too

**Driver**

1) Write a simple topology with one DAI that has 2 or more configs.
2) Make sure the alsatplg compiler adds both configs in the binary file.
3) make sure sound/soc/topology.c parses both DAI configs.
4) Make sure sound/soc/sof/topology.c parses both configs and send IPC for both configs.

**Firmware**

1) FW should receive both configs and add to dai.c (only one supported today, we can have a list of configs)
2) By default FW will use config 0. @keyonjie is working on logic to select the best config based on stream params and topology. We may also need to add a manual config selection method too.

**Comment by fredoh9** [comment]
@lgirdwood wow, thank you for detailed guideline. Will work on it.

**Comment by wenqingfu** [comment]
@fredoh9 #758 may close this ticket

**Comment by dragosht** [comment]
@wenqingfu Actually #758 simply acknowledges the presence of multiple configs but adds an additional check for the assigned default hardware configuration and chooses that one to be send to the firmware. I think it is more work involved with this issues than just that. And based on @lgirdwood 's notes above, all the hardware configs should eventually be sent to the firmware via IPC, but first the firmware would need some reworks to allow handling multiple configurations on the same DAI.

**Comment by plbossart** [comment]
we have a multi-configuration support for SSP, let's close this.
