### ISSUE TITLE
New sparse warning after PM patches merged

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#71]
new error after PM patches merged:
 
make SUBDIRS=sound/soc/sof C=1

sound/soc/sof/pm.c:178:31: warning: incorrect type in assignment (different base types)
sound/soc/sof/pm.c:178:31:    expected int [signed] state
sound/soc/sof/pm.c:178:31:    got restricted snd_pcm_state_t [usertype] state
sound/soc/sof/pm.c:193:31: warning: incorrect type in assignment (different base types)
sound/soc/sof/pm.c:193:31:    expected int [signed] state
sound/soc/sof/pm.c:193:31:    got restricted snd_pcm_state_t [usertype] state

**Comment by plbossart** [comment]
@ranj063, can you look into this? somehow I can't assign this directly to you (probably you haven't cloned the linux tree from thesoftproject?)

**Comment by ranj063** [comment]
commit 323c12c9 fixes this problem already.
