### ISSUE TITLE
SOF topology load failed with previously used kernel configuration

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#712]
This happened to me this week when I started using new 5.0.0 kernel with UP^2. The firmware loads but topology sof-apl-pcm512x.tplg instantiate failed to this error:

```
[    4.290707] sof-audio-pci 0000:00:0e.0: error: tplg component load failed -22
[    4.290765] sof-audio-pci 0000:00:0e.0: error: failed to load DSP topology -22
[    4.290805] sof-audio-pci 0000:00:0e.0: ASoC: failed to probe component -22
[    4.290866] bxt-pcm512x bxt-pcm512x: ASoC: failed to instantiate card -22
[    4.290925] bxt-pcm512x bxt-pcm512x: snd_soc_register_card failed -22
```

The sof-logger dma trace and error trace were totally empty that was strange.

I got the problem fixed with new config from http://otc-sof-sh-build-01.sh.intel.com/daily/20190312/linux-facd448b/config-daily-hda-20190312

The difference in SOF Kconfigs was

```
singalsu@singalsu-MOBL:~/ktest$ diff -ud sof-dev-defconfig.old2 sof-dev-defconfig | grep SOF
+CONFIG_SND_SOC_INTEL_SOF_RT5682_MACH=m
 CONFIG_SND_SOC_SOF_TOPLEVEL=y
 CONFIG_SND_SOC_SOF_PCI=m
 CONFIG_SND_SOC_SOF_ACPI=m
 CONFIG_SND_SOC_SOF_SPIDSP=m
 CONFIG_SND_SOC_SOF_OPTIONS=m
 # CONFIG_SND_SOC_SOF_COMPRESS is not set
-CONFIG_SND_SOC_SOF_NOCODEC=m
+# CONFIG_SND_SOC_SOF_NOCODEC is not set
 CONFIG_SND_SOC_SOF_DEBUG=y
-# CONFIG_SND_SOC_SOF_FORCE_NOCODEC_MODE is not set
 # CONFIG_SND_SOC_SOF_DEBUG_XRUN_STOP is not set
 CONFIG_SND_SOC_SOF_DEBUG_VERBOSE_IPC=y
 # CONFIG_SND_SOC_SOF_DEBUG_FORCE_IPC_POSITION is not set
+CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y
 CONFIG_SND_SOC_SOF=m
+CONFIG_SND_SOC_SOF_PROBE_WORK_QUEUE=y
 CONFIG_SND_SOC_SOF_INTEL_TOPLEVEL=y
 CONFIG_SND_SOC_SOF_INTEL_ACPI=m
 CONFIG_SND_SOC_SOF_INTEL_PCI=m

```
This no more happens with new config so this is low priority but I wanted to file this for record if there possibly is something with kconfigs enabled code.

**Comment by singalsu** [comment]
Here's the offending configuration

[sof-dev-defconfig.old2.gz](https://github.com/thesofproject/linux/files/2957878/sof-dev-defconfig.old2.gz)

**Comment by singalsu** [comment]
I tried to set CONFIG_SND_SOC_SOF_NOCODEC=m into the new kernel configuration to see if it triggered this. It also caused SOF boot to fail but with other error. 

```
[    4.516663] bxt-pcm512x bxt-pcm512x: ASoC: CPU DAI iDisp1 Pin not registered
[    4.516668] bxt-pcm512x bxt-pcm512x: snd_soc_register_card failed -517

```
In this case also sof-logger output looked OK with four hda-dmac traces (not empty).

**Comment by plbossart** [comment]
@singalsu if you select NOCODEC, you cannot use a machine driver that depends on HDMI/HDA. So I guess the Kconfig entry is incorrect when HDMI/HDA is not allowed. SND_SOC_HDAC_HDMI should not be selected here.

**Comment by plbossart** [comment]
Also if you use NOCODEC then you should not be using the ACPI initird overlays and remove /lib/firmware/acpi-updates/*.aml and reinstall the initird.

**Comment by wenqingfu** [comment]
According to @plbossart 's explanation, not an issue, @singalsu ? If so, please close it.

**Comment by singalsu** [comment]
@plbossart @wenqingfu I see, thanks for explanation! I fully agree this was an user error. I'll close this now.
