### ISSUE TITLE
rt5682 capture won't work until a playback start if ADC asrc is enabled

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#713]
I believe that it is a rt5682 codec driver issue. File here to track it.
If we enable rt5682 ADC asrc function, we can only capture silence  until we start a playback.
Below is how we enable rt5682 ADC asrc function.
```
--- a/sound/soc/intel/boards/sof_rt5682.c
+++ b/sound/soc/intel/boards/sof_rt5682.c
@@ -117,7 +117,8 @@ static int sof_rt5682_codec_init(struct snd_soc_pcm_runtime *rtd)
        /* need to enable ASRC function for 24MHz mclk rate */
        if ((sof_rt5682_quirk & SOF_RT5682_MCLK_EN) &&
            (sof_rt5682_quirk & SOF_RT5682_MCLK_24MHZ)) {
-               rt5682_sel_asrc_clk_src(component, RT5682_DA_STEREO1_FILTER,
+               rt5682_sel_asrc_clk_src(component, RT5682_DA_STEREO1_FILTER |
+                                       RT5682_AD_STEREO1_FILTER,
                                        RT5682_CLK_SEL_I2S1_ASRC);
        }
```

**Comment by bardliao** [comment]
The issue can be fixed by [ASoC: rt5682: recording has no sound after	booting](https://mailman.alsa-project.org/pipermail/alsa-devel/2019-March/146467.html). I will cherry-pick it from upstream

**Comment by plbossart** [comment]
On 3/19/19 8:07 AM, Bard Liao wrote:
> The issue can be fixed by ASoC: rt5682: recording has no sound after 
> booting 
> <https://mailman.alsa-project.org/pipermail/alsa-devel/2019-March/146467.html>. 
> I will cherry-pick it from upstream

When you cherry-pick, please use the -x option that adds the upstream 
SHA1. It's very useful for people doing backports to track this is 
upstream already. Thanks!

**Comment by bardliao** [comment]
@plbossart Sorry, I didn't use the -x option. Should I redo it?

**Comment by plbossart** [comment]
No worries, it's just useful but not critical, I merged your code already and the patch will show up through the back ports anyway.
