### ISSUE TITLE
[WHL I2S] Audio jack detection cannot work on WHL RVP

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#715]
Audio jack detection cannot work for lack of Jack detection GPIO in ACPI of WHL RVP BIOS.

**Comment by bardliao** [comment]
Thanks for BIOS team support. We are using C8 pin and now I can get i2c->irq = 145 in rt5682.c if I add below to the .asl file
```
GpioInt(Edge, ActiveHigh, ExclusiveAndWake, PullNone, 0x0000, "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, EPII) { 0 }
``` 
But when I tried to request IRQ, it will say “cannonlake-pinctrl INT34BB:00: pin 0 cannot be used as IRQ”
I seems I may request the wrong pin. @plbossart Do you know what do "\\_SB.PCI0.GPI0 and EPII stand for? How does it map to C8? Maybe it is not GPI0?

**Comment by plbossart** [comment]
@bardliao sorry I didn't see this earlier. The last {0} refers to the pin list for that GPIO controller:

From ACPI 6.1: PinList is a list of (zero-based) pin numbers on the ResourceSource that are described by this descriptor. For interrupt pin descriptors, only one pin is allowed. The bit field name _PIN is automatically created to refer to this portion of the resource descriptor.

Are you sure it's 0 in your case?

**Comment by bardliao** [comment]
@plbossart No, I was told by BIOS team, it should be 0x108. But it didn't work yet.

**Comment by wenqingfu** [comment]
still an issue? @bardliao

**Comment by bardliao** [comment]
@wenqingfu Yes, we got a BIOS from BIOS team, but we still see ``cannonlake-pinctrl INT34BB:00: pin 189 cannot be used as IRQ`` log from kernel dmesg.

**Comment by mengdonglin** [comment]
Closing since this is a BIOS issue for this specific board and we haven't got a BIOS fix for a long time. 
This issue doesn't impact audio playback/capture. And it is not observed on the custom boards which have proper pin configuraiton.
