### ISSUE TITLE
Remove support for Haswell, Skylake, Kabylake

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#716]
The code for those 3 platforms is not tested and have never been shown to work. 
I don't see the point of keeping this code in SOF, is there any objection to remove it for now, and add it back if/when there is actually a plan to enable those platforms? we have more than enough on our plate already.
@lgirdwood any comments?

**Comment by lgirdwood** [comment]
No harm in keeping HSW as logic is the same as BDW (albeit it with different offsets). It's also easy to test for community as no code signing. It also means legacy HSW/BDW driver can be fully removed.

**Comment by plbossart** [comment]
Neither the legacy nor SOF driver run on actual HSW hardware - such platforms are just not available, so why bother?

**Comment by plbossart** [comment]
@lgirdwood maybe a reasonable compromise is to keep those files in topic/sof-dev, but not submit them upstream. That way we still have the ability to make progress and keep the code current, but we don't provide untested code upstream.

**Comment by plbossart** [comment]
Since I generally agree with me, myself and I and there was no objection, the code for Haswell, Skylake/Kabylake will not be shared upstream for now.
