### ISSUE TITLE
IPC: ops: push low level ops into HW drivers.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#720]
The core driver IPC operations currently have a complex set of functions for IPC abstraction that can be pushed into the HW drivers.
```
/* ipc */
	int (*send_msg)(struct snd_sof_dev *sof_dev,
			struct snd_sof_ipc_msg *msg);
	int (*get_reply)(struct snd_sof_dev *sof_dev,
			 struct snd_sof_ipc_msg *msg);
	int (*is_ready)(struct snd_sof_dev *sof_dev);
	int (*cmd_done)(struct snd_sof_dev *sof_dev, int dir);
```

ideally we should export
```
/* ipc */
	int (*tx_msg)(struct snd_sof_dev *sof_dev,
			struct snd_sof_ipc_msg *msg);
	int (*rx_msg_cb)(struct snd_sof_dev *sof_dev,
			 struct snd_sof_ipc_msg *msg);
```
This simplifies the core code and pushed the HW IPC complexity into HW drivers. It also allows the HW drivers to perform introspection of each IPC message as some messages need to be treated differently for different platforms.

Finally it also means the HW driver becomes responsible for large message partitioning and transport (since this can be quite platform specific).

**Comment by plbossart** [comment]
@lgirdwood the .tx_msg() callback is fine, but I am struggling on the definition of rx_msg_cb()? did you want this to be the reply to tx_msg() - as done in RPMsg - , or to provide support for unsolicited notifications and events (which are currently not exposed to the core).

**Comment by lyakh** [comment]
@lgirdwood could you please clarify? In fact currently there are only 3 IPC callbacks: .send_msg, .get_reply, and .cmd_done. .is_ready is already gone. So, we aren't very far from your goal of having two callbacks. Further, .get_reply is really the same on all platforms ATM. The only difference is, that the HDA version also handles the PM_CTX_SAVE message, but it can be safely done in the generic version too, since BYT and HSW don't support PM suspend anyway, so there this message will never occur. My latest SPI version was a bit different too, but it should be possible to make it the same too. So, shall we just remove the .get_reply callback and effectively make hda_dsp_ipc_get_reply() a generic function.

If we do that we'd just be left with .cmd_done, which is currently called for both DSP replies and new DSP messages. Would that be close enough to your wish?

**Comment by lgirdwood** [comment]
@plbossart rx_msg_cb is a callback for any DSP initiated messages like async notifications. It's not tied to any particular kernel IO/messaging subsystem and is meant to be completely generic (to allow easy maping to platform drivers and kernel IO APIs like SPI, virtio etc). Fwiw, It also allows the DSP to initiate large messages (when supported) as this will appear as one callback call.

@lyakh yes, we mostly keep send_msg() and get_reply() and change them to tx_msg() and rx_msg_cb() respectively. We remove cmd_done() since tx_msg() should block (simplifies logic further).

**Comment by plbossart** [comment]
@lgirdwood I agree with the two cases we have to handle:
1. host-initiated message w/ DSP reply
2. DSP-initiated notification (panic, watchdog, acoustic event, etc)
The use of _cb for callback is a bit weird, or we are abusing the traditional definition of 'callback'. People use a callback to get notified when an event occurred, so for host-initiated messages it's irrelevant and for DSP-initiated stuff it's also not quite clear what this means. 
We should use something like host_msg and dsp_notifier to make it unambiguous. Folks in the RPMSG world would e.g. map the send_to() and receive callback to the host-initiated message, with a synchronization primitive of their choice.

**Comment by lgirdwood** [comment]
> @lgirdwood I agree with the two cases we have to handle:
> 
> 1. host-initiated message w/ DSP reply
> 2. DSP-initiated notification (panic, watchdog, acoustic event, etc)
>    The use of _cb for callback is a bit weird, or we are abusing the traditional definition of 'callback'. People use a callback to get notified when an event occurred, so for host-initiated messages it's irrelevant and for DSP-initiated stuff it's also not quite clear what this means.

I think our intentions are the same with some different wording. The intention of the callback is to be notified when a DSP initiated IPC has been received by the host (and pre-processed/santized by the platform driver). 

>    We should use something like host_msg and dsp_notifier to make it unambiguous. Folks in the RPMSG world would e.g. map the send_to() and receive callback to the host-initiated message, with a synchronization primitive of their choice.

No issue with these names. These also map well to SPI and virtio.

**Comment by plbossart** [comment]
@lgirdwood what shall we do with this one, it's 2+ years old

**Comment by plbossart** [comment]
no reply or information, closing
