### ISSUE TITLE
Enable Intel GPU tool to dump audio info for WHL+ platforms

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#731]
The Intel gpu tool contains a program intel_audio_dump to dump audio register info. But it's not maintained after APL. We need to enable this tool to debug HDMI/DP audio issues on new platforms.

**Comment by lgirdwood** [comment]
@mengdonglin any links to the tool ? what license ?

**Comment by fredoh9** [comment]
Can we use the GPU tool on APL? Is it open source too? I'd like to try to debug HDMI audio also. Please share more information.

**Comment by plbossart** [comment]
@mengdonglin @kv2019i is this enhancement still relevant or can we close?

**Comment by kv2019i** [comment]
@plbossart I think this is still relevant. I think in practise we'll update the tool when we have an issue to debug that needs diving into the registers. This seems like a useful tool for that kind of debug:

https://cgit.freedesktop.org/drm/igt-gpu-tools/log/tools/intel_audio_dump.c

**Comment by lgirdwood** [comment]
@mengdonglin @kv2019i we should really add this to SOF docs unter a "trouble shooting" page, alongside other useful tips and techniques.

**Comment by kv2019i** [comment]
@lgirdwood  Ack, but we need to first fix the tool. Currently the tool doesn't support most recent platforms, so it is not very useful. Assigned this to myself...

**Comment by plbossart** [comment]
@kv2019i should we close this?

**Comment by kv2019i** [comment]
@plbossart Yes, let's close. I have not needed this during last year, and nobody has asked about the it.
