### ISSUE TITLE
HDMI playback resume has no sound

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#737]
This bug happens after resume from S3 when HDMI playback is running. It is obviously detected in 5.0 kernel. In 4.20 kernel, I didn't reproduce this bug. This bug is a general issue from the root cause. It should be reproduced on all platforms.
Reproduce step:
1. aplay -Dhw:0,n file.wav
2. call rtcwake to suspend/resume

Run several times of step 1 and step 2, and this bug will be reproduced.

No error message is dumped out.

**Comment by libinyang** [comment]
This bug only can be reproduced after applying https://github.com/thesofproject/linux/pull/725
Without patch https://github.com/thesofproject/linux/pull/725, playback will be crashed after S3 and never arrive at this bug step.

**Comment by libinyang** [comment]
This bug is because of the contest.
When resume, audio will try to get the lock to power on i915 audio domain. But if i915's lock is occupied, it will sleep. This will cause the contest and make something (register reading and writing on HDMI) which should not happen at that monent happens at that time.

**Comment by libinyang** [comment]
Patch is ready: https://github.com/thesofproject/linux/pull/744

**Comment by wenqingfu** [comment]
Is this still valid?  or it's fixed with upstream code merged in after #851? @libinyang

**Comment by libinyang** [comment]
This bug is fixed. Mark has merged the patch yesterday.

**Comment by wenqingfu** [comment]
You should have closed it in last reply,  and save one conversation cycle. thanks.

**Comment by libinyang** [comment]
I planed to close it after QA has verified on the latest kernel. OK. I will close it.

**Comment by wenqingfu** [comment]
thanks
