### ISSUE TITLE
Unload topology and load a new one at run time

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#747]
We need the means to tear down the pipelines in the currently loaded topology and load a new topology user space at runtime.

This possibly needs a new ALSA ioctl definition to load a new toplogy from userspace as well.

**Comment by plbossart** [comment]
@ranj063 are you asking for a means to only enable the pipelines when they are needed, or actually a way to take down an existing topology and load a new one? What is the use case or requirement for the latter case?

**Comment by ranj063** [comment]
@plbossart I suppose the first ask is to enable pipelines when needed and disable then when not needed.
But @lgirdwood also mentioned the need for take down the existing topology and load a new one. Liam, could you please clarify?

**Comment by lgirdwood** [comment]
We need to be able to:
1) tear down selected existing pipelines at runtime.
2) construct new pipelines at runtime.
But in order to do this we will need some new ioctl() within ALSA to do 1 & 2 above and some userspace cmd line app. The cmd line app should be able to list current pipelines and allow deletion and insertion.

**Comment by plbossart** [comment]
@lgirdwood are we only talking about 'front-end' pipelines here? if you we mucking with DAIs and dailinks then it's the entire card you'd have to change and take down.

**Comment by ranj063** [comment]
@plbossart @lgirdwood tearing down front end pipelines makes sense. After playing with the HWDEP interface for the past week, I think this could be a perfect candidate to do 2. in your comment above. 

The hard part will be do only tear down the FE part. It is easy to tell this apart from topology but the FW pipeline as it exists today goes all the way from host to the dai.

**Comment by plbossart** [comment]
@ranj063 @lgirdwood not sure what the ask was on this one either. it's 2.5 years old. Close?

**Comment by dbaluta** [comment]
This feature would be nice to have if someone will have some time to allocate for it.

**Comment by plbossart** [comment]
I am going to close this since we have no plans to work on this anytime soon. It's hard enough with a single topology :-)
