### ISSUE TITLE
[UCM] Add reference UCM file for DP-MST audio 

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#755]
This feature is to support SOF DP-MST audio integration with PulseAudio for Linux and Cras for ChromeOS, to allow users to set amixer settings automatically via ALSA UCM.

**Comment by wenqingfu** [comment]
low priority

**Comment by kv2019i** [comment]
I uploaded a new UCM file that works better with MST:
https://github.com/kv2019i/UCM/commit/902c328f7e7bd27fd409c704c4d73b0ed13ddd69
FYI @libinyang and @juimonen

**Comment by kv2019i** [comment]
This enhancement is now implemented with #1404 and #1422. The UCM change was merged usptream with this PR:
https://github.com/alsa-project/alsa-ucm-conf/pull/4
