### ISSUE TITLE
Clarify IPC usage of spin_lock_irq vs. spin_lock_irqsave

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#76]
Marking this as a bug to track email discussions with Rander, it's not clear why we use different APIs in different places in ipc.c
if it's not intentional it's a bug
If it is it needs to be commented/explained

**Comment by plbossart** [comment]
@Jocelyn-Li can you please assign someone to fix this (Rander?), there are a couple of IPC related issues that are likely linked to this.

**Comment by RanderWang** [comment]
Ok, I will fix it on v4.18 after it is ready

**Comment by RanderWang** [comment]
It should be fixed by https://github.com/thesofproject/linux/pull/89

**Comment by plbossart** [comment]
closed
