### ISSUE TITLE
System S3 failing on CML platform

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#763]
S/w Configuration : ww8.5 Alpha CML release

Issue description :  System S3 is failing due to DSP init failure. happens in less than 10 cycles.
Note that Soix is happening fine and tested for 500 cycles.

Log extract : (Full log attached)
[  387.978505] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 0x4c
[  387.978526] sof-audio-pci 0000:00:1f.3: error: status = 0x001d003c panic = 0x00000000
[  387.978549] sof-audio-pci 0000:00:1f.3: error: ctx_save ipc error during suspend -110
[  388.029089] sof-audio-pci 0000:00:1f.3: error: reset enter failed: core_mask f adspcs 0x1d003c
[  388.029102] sof-audio-pci 0000:00:1f.3: error: dsp core reset failed: core_mask f
[  388.029107] sof-audio-pci 0000:00:1f.3: error: failed to power down core during suspend
[  388.029112] sof-audio-pci 0000:00:1f.3: error: suspending dsp
[  388.029118] sof-audio-pci 0000:00:1f.3: error: failed to power down DSP during suspend -5
[  388.029134] pci_pm_suspend(): snd_sof_suspend+0x0/0x11 [snd_sof] returns -5
[  388.029145] dpm_run_callback(): pci_pm_suspend+0x0/0x1a1 returns -5
[  388.029155] sof-audio-pci 0000:00:1f.3: pci_pm_suspend+0x0/0x1a1 returned -5 after 350092 usecs
[  388.029162] PM: Device 0000:00:1f.3 failed to suspend: error -5

HOW TO
Steps to enter S3 and reproduce the issue
echo 0 > /var/lib/power_manager/suspend_to_idle 
restart powerd
suspend_stress_test -c 10 (or 20) should reproduce the issue.

[s3-failure.txt](https://github.com/thesofproject/linux/files/3027789/s3-failure.txt)

**Comment by ranj063** [comment]
@sathyap-chrome can you please confirm this is a stress test issue. Does S3 entry/exit work if you only do it once?

**Comment by sathyap-chrome** [comment]
I think it might work sometimes. as the issue happens after few iterations
but after 5 - 6 iterations

**Comment by sathyap-chrome** [comment]
@ranj063  is this similar to the issue below https://github.com/thesofproject/sof/issues/814 seen on apl ?

**Comment by ranj063** [comment]
@sathyap-chrome the issue you see with timeout is much after the first error which is the fw load failure. So I dont think it is related

**Comment by ranj063** [comment]
@sathyap-chrome just a quick update with the v5 SOF patches I am unable to reproduce this issue on the 2 boards that I have access to. I feel like we're hitting the same problem we saw in GLK where some boards manifested the problems but others didnt.

**Comment by keqiaozhang** [comment]
@sathyap-chrome 
What is the latest state of this issue at your end? I believe Ranjani has shared the new coreboot  and kernel branch to you. 
This afternoon, I tested this issue on my board, S3 works well in loop after updating the new coreboot and can pass more than 500 iterations.

Here is my test recipe:
kernel: https://github.com/ranj063/linux/tree/debug/cml-suspend 
sof/tplg: cml-003-drop-stable/4731a1ad

**Comment by sathyap-chrome** [comment]
@ranj063  and @keqiaozhang thanks for debug. The issue is not happening for me too. The actual root cause might be in the servo debug card we use. The issue happened on few boards ( including mine) where the debug card is connected. 

Once i removed, the v5 recipe ( as well as v4 based current chrome release) is working fine for 100+ iterations. This also explains why this didnt happen on RVP.

I'll close the issue and continue debug working with our platform hw engineers.
Thanks for all the debug help.

**Comment by ranj063** [comment]
@sathyap-chrome thanks for confirming. I'm curious to know why we see SOF FW fails to load with the servo connected. Seems like a timing issue but a very hard one to debug.
