### ISSUE TITLE
[WHL][HDA] Unable to play using aplay

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#774]
### Recipe:
platform: WHL RVP (HDA mode)
linux: Ubuntu 18
### kernel (v5.0): 
[e29122d6](https://github.com/thesofproject/linux/commit/e29122d6) with latest kconfig repo. Kernel build using commands:
```
make defconfig
./scripts/kconfig/merge_config.sh .config $KCONFIG_PATH/base-defconfig $KCONFIG_PATH/sof-defconfig $KCONFIG_PATH/hdaudio-codecs-defconfig
make bindeb-pkg -j8
```

### FW and topology:
master/[a10e69d2](https://github.com/thesofproject/sof/commit/a10e69d2) (from 28 March)
tplg file: sof-hda-generic.tplg

master/[d7b36bf3](https://github.com/thesofproject/sof/commit/d7b36bf3) (from 2 April)
tplg file: sof-hda-generic.tplg

### Description:
After booting linux OS with above kernel and for both FW, I checked dmesg: no errors. Then I checked `sudo aplay -l` which return properly 5 devices from topology.

but after execute:
`sudo aplay -vv -Dhw:0,0 music.wav`
I have output from aplay:
`aplay: main:788: audio open error: Invalid argument`

When I not used "sudo" I have errors from aplay:
```
> aplay -l
**** List of PLAYBACK Hardware Devices ****
ALSA lib conf.c:3545:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib/alsa-lib/libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL hw:0
aplay: device_list:279: control open (0): No such file or directory

```
I have never had these errors before.

On dmesg I see that errors for both FW:
![image](https://user-images.githubusercontent.com/41113230/55405583-b266a600-555a-11e9-80a3-e999a1283660.png)

Logs:
[dmesg.txt](https://github.com/thesofproject/linux/files/3034140/dmesg.txt)

### Windows OS: 
On python tests with diag driver there is no issue with FW.
- loading firmware ok
- basic playback and record on HDA (loopback on codec ALC700) - ok
- basic playback and record on SSP (loopback internal - using quirk) - ok

### CML003 release:
There is no such errors on cml003 release (kernel, fw, tplg)

**Comment by mengdonglin** [comment]
@emilchudzik We will share you a working recipe next Monday. Too many updates today

**Comment by emilchudzik** [comment]
With this env I can play using aplay, but there is and issue with pulse audio. Please check: https://github.com/thesofproject/sof/issues/1254#issuecomment-483200302

**Environment:**
Platform: WHL RVP - HDA mode
**Kernel:** 
2de29fae6 [thesofproject/linux: topic/sof-dev]
+d04ccf494 [RanderWang/linux: cml-validation-20190415]
+bfb0729dd [RanderWang/linux: cml-validation-20190415]
+8a2b13a81 [RanderWang/linux: cml-validation-20190415]
+63ceb8f68 [RanderWang/linux: cml-validation-20190415]
+db89510d0 [RanderWang/linux: cml-validation-20190415]

**Firmware:** 00bbb113d [thesofproject/sof: master]
**Topology:** 00bbb11 [thesofproject/sof: master] -> sof-hda-generic.tplg

**Comment by wenqingfu** [comment]
original issue is gone. new symptom points to thesofproject/sof#1254
