### ISSUE TITLE
[APL][GLK] harden: power-gating and clock gating needs to be disabled during firmware download

### ISSUE THREAD

**Issue by wenqingfu** [thesofproject/linux#776]
No.2 sub-task of #87.

**Comment by zhuyingjiang** [comment]
I think this has already been supported.

**Comment by mengdonglin** [comment]
@plbossart  Can this issue be closed?

**Comment by plbossart** [comment]
I'd like a comparison with the Skylake driver (including non-upstreamed parts). The ask for all this was to doubled-check what was done in the past and make sure all known recommended sequences are supported by SOF.

**Comment by zhuyingjiang** [comment]
@plbossart The clock/power gating for firmware download is done by PR #249 9e1dec61.
I will submit a PR for clock/power gating for suspend/resume, and also the misc clock gating(backbone).

**Comment by zhuyingjiang** [comment]
the misc clock gating part is fixed by #877.
as suggested by Lech's mail:
1.      PGCTL has a reversed logic. PGCTL.ADSPPG == 1 means that power gating is disabled
=> done by #249
2.      CGCTL.MISCBDCGE needs to be disabled during controller reset 
=>done by #877
mark as fixed.
