### ISSUE TITLE
[WHL HDA] can't boot up with lastest Linux kernel code

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/linux#784]
WHL hangs at booting screen and user can't login by ssh. I have no time to find which commit make this but I found it is caused by a series of IPC commits.

**Comment by emilchudzik** [comment]
I described it also here:
https://github.com/thesofproject/linux/issues/767#issuecomment-479449127

**Comment by wenqingfu** [comment]
mark as duplicate of #767. please move conversation there
