### ISSUE TITLE
cppcheck warning with polltimeout changes

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#791]
new warning popped up after poll timeout changes.

[sound/soc/sof/intel/hda-dsp.c:180]: (style) Argument '(__sleep_us)!=0' to function might_sleep_if is always 1

@kv2019i can you look if this can be removed or squelched?

**Comment by plbossart** [comment]
you need to install cppcheck from git (Ubuntu is just too old)

````
<path>/cppcheck --platform=unix32 --force --max-configs=1024 --inconclusive --enable=all sound/soc/sof
````

**Comment by kv2019i** [comment]
Ack, working on this now.

**Comment by kv2019i** [comment]
This seems a false alarm. I can get rid of it by having an extra local variable where to store the return value and then return it (versus return foobar()), but this has no functional impact so seems very suspect. I've been looking at the preprocessor output with and without the workaround and everything seems good. Although other drivers in kernel are using this just in the same way. 
I'll continue debug and try to rootcause why cppcheck complains about this (now using latest cppcheck from their git head).

**Comment by plbossart** [comment]
On 4/8/19 1:46 PM, Kai Vehmanen wrote:
> This seems a false alarm. I can get rid of it by having an extra local 
> variable where to store the return value and then return it (versus 
> return foobar()), but this has no functional impact so seems very 
> suspect. I've been looking at the preprocessor output with and without 
> the workaround and everything seems good. Although other drivers in 
> kernel are using this just in the same way.
> I'll continue debug and try to rootcause why cppcheck complains about 
> this (now using latest cppcheck from their git head).

This isn't a priority at this point, please don't waste too much time on 
this. First priority is to close on Takashi's comments and IPC integration.
