### ISSUE TITLE
Upstream: v5:  debugfs alignment issue?

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#792]
Feedback from Takashi Iwai:

````
> +static ssize_t sof_dfsentry_read(struct file *file, char __user *buffer,
> +				 size_t count, loff_t *ppos)
> +{
> +	struct snd_sof_dfsentry *dfse = file->private_data;
> +	struct snd_sof_dev *sdev = dfse->sdev;
> +	int size;
> +	u32 *buf;
> +	loff_t pos = *ppos;
> +	size_t size_ret;
> +
> +	size = dfse->size;
> +
> +	/* validate position & count */
> +	if (pos < 0)
> +		return -EINVAL;
> +	if (pos >= size || !count)
> +		return 0;
> +	/* find the minimum. min() is not used since it adds sparse warnings */
> +	if (count > size - pos)
> +		count = size - pos;
> +
> +	/* intermediate buffer size must be u32 multiple */
> +	size = ALIGN(count, 4);

Doesn't pos need to be aligned to 32bit as well (at least at actually
reading from iomem)?
````

**Comment by kv2019i** [comment]
Ack, working on this.

**Comment by kv2019i** [comment]
I have a working patch for this -- took a bit of effort to figure out a way to test non-aligned accesses as sof-logger always behaves nicely and is useless for testing this. I will post a review-ready patch tomorrow, @plbossart ping me if you need this sooner.

**Comment by plbossart** [comment]
@kv2019i I'd like this code to be merged tomorrow, can you post it as soon as possible? It's one of the last two review comments.

**Comment by kv2019i** [comment]
@plbossart 
> @kv2019i I'd like this code to be merged tomorrow, can you post it as soon as possible? It's one of the > last two review comments.

Ack, working on this still, not yet ready for review (functional issues after I rewrote it in a nicer looking patch). I'll try my best to get a version for review still today.
