### ISSUE TITLE
Upstream: v5: loader code hardening

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#793]
Feedback from Takashi Iwai

````
> +		if (remaining < block->size) {
> +			dev_err(sdev->dev, "error: not enough data remaining\n");
> +			return -EINVAL;
> +		}

remaining is unsigned, so a negative check doesn't work here.
Hence you need the explicit underflow check.
````

**Comment by plbossart** [comment]
@juimonen can you confirm you are looking into this, I'd like this to be fixed by tomorrow so that we can spend a v6 upstream by the end of the week. Thanks!

**Comment by juimonen** [comment]
@plbossart I've been debugging the byt noise issue for couple of days... so not done anything for this. However if this is just underflow check I can see what I can do
