### ISSUE TITLE
suspend/resume: IPC timed out after the system is recovered form S3

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#82]
This issue only happens with nocodec tplg and cannot be reproduced with pcm512 tplg.
How to reproduce:
1. rtcwake -m mem -s 5
2. check the trace and dmesg

sof-dev:2a7a5d
sof-master:bfc7e46
soft-master:fe1f3ba
[rmbox-s3.log](https://github.com/thesofproject/linux/files/2287113/rmbox-s3.log)
[rmbox-t-s3.log](https://github.com/thesofproject/linux/files/2287114/rmbox-t-s3.log)
[dmesg-s3.log](https://github.com/thesofproject/linux/files/2287115/dmesg-s3.log)

**Comment by mengdonglin** [comment]
@ranj063 could you help check this issue?
And if you have not started on issue #81 , we can ask Bard to check #81

**Comment by bardliao** [comment]
@ranj063 I will check this issue. :)

**Comment by ranj063** [comment]
@mengdonglin yes, I'll take a look today. The chrome team seems to face a similar issue.

**Comment by bardliao** [comment]
The issue should be fix by [PR #141 ](https://github.com/thesofproject/linux/pull/141)，please verify it.

**Comment by mengdonglin** [comment]
@ZhendanYang Please verify if it worked.

**Comment by ZhendanYang** [comment]
@mengdonglin Verified. This issue is gone on APL. @keqiaozhang Please verify on GLK.

**Comment by keqiaozhang** [comment]
On GLK, system failed to suspend. please refer to: thesofproject/sof/issues/375.
error log:
[  667.198388] PM: suspend of devices aborted after 0.024 msecs
[  667.198390] PM: Some devices failed to suspend, or early wake event detected
[  667.198395] PM: resume of devices complete after 0.001 msecs
[  670.204343] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[  670.204554] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[  670.204599] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0

**Comment by mengdonglin** [comment]
@ranj063 It seems system suspend/resume can work on your GLK, could you clarify which SOF firmware branch you're using? master or glk-003-drop-stable?

**Comment by keqiaozhang** [comment]
@mengdonglin @ranj063 
This issue is fixed in sof-glk-003-drop-stable, but in sof-master, this issue is still there.

**Comment by mengdonglin** [comment]
It seems to be a firmware issue since sof-glk-003-drop-stable is okay. So close this issue from kernel side.

@ranj063 do you want a firmware engineer to continue fixing IPC time out on master branch?
