### ISSUE TITLE
PM: save and restore DSP context during PM state transitions 

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#83]
Some DSP context can be lost when DSP is in D3 or S0ix states. This context can include system time and any persistent SRAM trace data. Add support to save context when DSP enters S0ix and restore at D0.

**Comment by plbossart** [comment]
@lgirdwood I don't think the context-saving requirement is needed atm, should we close this issue?

**Comment by plbossart** [comment]
@lgirdwood this is almost 3 years old, can you revisit and clarify what is needed?

**Comment by lgirdwood** [comment]
Can be closed.  No need to save context to IMR now.
