### ISSUE TITLE
Log LEC and trace point

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/linux#830]
Currently driver just logs FSR from window 0. Please dump also 2 next registers:
Last Error Code - Window 0 + (0x4)
Trace Point - Window 0 + (0x8)

**Comment by plbossart** [comment]
@jajanusz @lgirdwood is this enhancement still relevant?

**Comment by lgirdwood** [comment]
It's done IIRC. @ranj063 are you dumping this on CAVS platforms.

**Comment by plbossart** [comment]
closing, @jajanusz @ranj063 re-open if necessary.
