### ISSUE TITLE
[FEATURE] Dump IPC state machine status on IPC timed out

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#846]
IPC timeouts are often difficult to debug as we have two state machines running, one within the driver and the other within the FW.

This feature is to add useful debug output to the kernel when it detects and IPC timeout. i.e.
```
<< dmesg after current IPC timeout is printed >>
error: IPC host state: HOST_TO_DSP_CMD, DSP_TO_HOST_NOTIFICATION
error: IPC host mask: DSP_TO_HOST_NOTIFICATION
error: IPC host raw: status 0x00000003 mask 0x0000001
error: IPC dsp state: DSP_TO_HOST_NOTIFICATION
error: IPC dsp mask: DSP_TO_HOST_NOTIFICATION
error: IPC dsp raw: status 0x00000001 mask 0x0000001
```
The intention here is to show the IPC state machines for both DSP and host and show the **pending** operations in a high level manner alongside the raw status and mask.

**Comment by lgirdwood** [comment]
@ranj063 fyi, I think a feature like this would be useful for your debug today.

**Comment by xiulipan** [comment]
@lgirdwood 
ACK. will try to make a PR once I finished.

**Comment by xiulipan** [comment]
@lgirdwood 
A RFC is here: #872

**Comment by wenqingfu** [comment]
> @lgirdwood
> A RFC is here: #872

should it be closed then, since #872 is merged now? @xiulipan

**Comment by xiulipan** [comment]
@wenqingfu 
YES, I am glad that the RFC is just got accepted.

Fixed by #872

**Comment by ranj063** [comment]
@xiulipan dont we want to add the parser to show the status from the raw ipc regsiter values?

**Comment by xiulipan** [comment]
@ranj063 
I would like to do that with IPC2.0 feature. To define a state machine for the IPC mechanism, otherwise I am not sure if we can get some parser status with the bits we have.

**Comment by ranj063** [comment]
@xiulipan fair enough. Lets modify the issue requirement and keep it open. Else it will get swept under the carpet

**Comment by plbossart** [comment]
@ranj063 can you clarify what remains to be done, I can't follow this 2-yr old thread. thanks!

**Comment by lgirdwood** [comment]
It's done and upstream.
