### ISSUE TITLE
[UCM] Enable DMIC input device for generic HD-A machine

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/linux#855]
PulseAudio can detect input/output devices in 2 ways:
1. Check amixers with standard names defined in /user/share/pulseaudio/alsa-mixer/paths ... for legacy HD-A driver;
2. check playback/capture devices defined by UCM for a sound card ... for ASoC drivers

Current open:
SOF reuse the legacy analog codec drivers which exposed standard amixers for speaker and headset, and can be recognized by PA in way#1. But SOF support HDMI output devices and DMIC suppported in ASoC style but w/o UCM file.

It seems we need to write SOF UCM file for generic topology to cover speaker, headset, DMIC and HDMI.

***Describe the bug***
Wrong device list for sound input and output on CML and WHL platform.

***To Reproduce***
Check Settings->sound->Output/Input on ubuntu.

***Screenshot:***
![Screenshot from 2019-04-22 15-23-44](https://user-images.githubusercontent.com/44258626/56489273-c8d99f00-6513-11e9-8c7f-817dec86482d.png)
![Screenshot from 2019-04-22 15-05-11](https://user-images.githubusercontent.com/44258626/56489277-cb3bf900-6513-11e9-8d4a-07bf9846b76e.png)

***Expected behavior***
1.Outout and input hould not list Mutichannel device
2.Input device can not find DMIC device

***Environment***
Kernel Repo: https://github.com/RanderWang/linux/commits/cml-validation-20190422
Made from: RanderWang/linux@9086043 [thesofproject/linux: topic/sof-dev]
+RanderWang/linux@c105b1b
+RanderWang/linux@ffecddc8
+RanderWang/linux@3b917aa
+RanderWang/linux@6f928a3
+RanderWang/linux@a916d2d
+RanderWang/linux@694599b
+RanderWang/linux@a43379d
+RanderWang/linux@d36ed40
+RanderWang/linux@9b3bd71
+RanderWang/linux@e852311
+RanderWang/linux@8f30111
+RanderWang/linux@95cd082

Firmware Repo :https://github.com/bardliao/sof/tree/whl-daliy-20190422
Made from: bardliao@0c93261
+bardliao@35fbf79
+bardliao@3f91567

Topology: Same as above SOF repo

**Comment by ClarexZhou** [comment]
add CML laptop sound setting sreenshot
![soundSettingScreenshot](https://user-images.githubusercontent.com/49641224/56492274-db58d600-651d-11e9-8e98-4656ab6c2703.PNG)

**Comment by RanderWang** [comment]
Release alpha version of UCM. Next I will refine the UCM and machine driver to upstream it.

**Comment by mengdonglin** [comment]
Closing as fixed by adding UCM

**Comment by mengdonglin** [comment]
@RanderWang Please help to upstream UCM to alsa-lib.

**Comment by mengdonglin** [comment]
Will track upstream progress in feature #956
