### ISSUE TITLE
Gaps of ABI and headers for KeywordDectect

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/linux#858]
For Linux we have https://github.com/thesofproject/linux/pull/771
For SOF part we have https://github.com/thesofproject/sof/pull/1036

They have difference in each side and I am not sure if #857 would fix it

**Comment by xiulipan** [comment]
@plbossart @lgirdwood @ranj063 
Any idea about the header changes by KeywordDectect?

**Comment by plbossart** [comment]
@xiulipan is this issue still relevant, if not please close it.
