### ISSUE TITLE
Config: need auto detection and fallback between SOF/SST/Legacy drivers

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#86]
The current code requires users to compile out two out of the three drivers for APL/GLK registered for the same PCI ID - or use mod probe blacklists. This needs to eventually move to an autodetect when the probe is handled in sequence, e.g. SOF first, then fallback to SST if firmware authentication fails, and last legacy HDaudio.
Filing it as a bug since it's really required for distributions such as ClearLinux and Ubuntu

**Comment by mengdonglin** [comment]
@keyonjie could you help to take care of this?

**Comment by keyonjie** [comment]
This may need refine/unified probing(especially for sof and sst) part, furthermore, sometimes using sof or sst is totally an user end choice(e.g. on those no FW authentication skl- platforms), we can't make selection for end-user in hard-coded logic.

I thought of using exclusive kernel config item for SOF and SST, which means if you select one(the other one will be unselected automatically), but the cons of doing that is we can't configure e.g byt with SST + apl with SOF, I am afraid someone make want to try something like that, even though this is not important for me.

@lgirdwood any comments?

**Comment by mengdonglin** [comment]
This is an enhancement actually, so set label "enhancement"

**Comment by lgirdwood** [comment]
@keyonjie  We will have a single PCI and single ACPI entry point for all Intel SOF and legacy drivers. Drivers will default to legacy unless they are mentioned in the SOF lookup table (table of DMI names, DT names).

**Comment by plbossart** [comment]
Mechanism implemented upstream (will be in 4.21), SOF needs to implement the PCI class/subclass detection as described in https://github.com/thesofproject/linux/issues/468
