### ISSUE TITLE
[BUG][CML]Headset output is in mute state when system reboot with headset connected

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#869]
**Describe the bug**
Headset output is in mute state when system reboot with headset connected when Pulseaudio on.

**To Reproduce**
1. Pulseaudio is enabled
2. Connect headset and aplay  to -Dhw:0,0, music output on headset normally
3. "sudo reboot" to reboot system
4. aplay  to -Dhw:0,0, check, no audio output. 
5. Check on alsamixer, Headset output is in mute state.  Plug out and plug in headset again, can auto switch to unmute successfully.

**Expected behavior**
Headset should auto detected and in unmute status.

**Environment**
Kernel repo | https://github.com/RanderWang/linux/tree/cml-validation-20190425

  Made from:
  f7e9d4a [thesofproject/linux: topic/sof-dev]

8a8e045 [RanderWang/linux: cml-validation-20190425]
62eaa40 [RanderWang/linux: cml-validation-20190425]
bf461fd [RanderWang/linux: cml-validation-20190425]
49bb879 [RanderWang/linux: cml-validation-20190425]
6af82dc [RanderWang/linux: cml-validation-20190425]
e54f292 [RanderWang/linux: cml-validation-20190425]
e026573 [RanderWang/linux: cml-validation-20190425]
3bdeae3 [RanderWang/linux: cml-validation-20190425]
cea87d5 [RanderWang/linux: cml-validation-20190425]
 
Firmware repo | https://github.com/RanderWang/sof/tree/cml-linux-20190425
  Made from:
  395a34e [thesofproject/sof: master]
279c995 [RanderWang/sof: cml-linux-20190425]
8598799 [RanderWang/sof: cml-linux-20190425]
   
Topology: | https://github.com/RanderWang/sof/tree/cml-linux-20190425
  file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
   
Kconfig: | https://sof-ci-storage.sh.intel.com/daily/20190425/linux-2e945691-1/config-daily-hda-20190425

![alsamixerScreenshot](https://user-images.githubusercontent.com/49641224/56718918-50244e00-6772-11e9-94ec-27d0fa17328f.PNG)

Speakers setting is selected in Sound setting.
![SoundSetting](https://user-images.githubusercontent.com/49641224/56783941-b798d700-6820-11e9-9dfa-4649c6d6940e.PNG)

[pONHeadsetDefaultMute_dmesg.log](https://github.com/thesofproject/linux/files/3115786/pONHeadsetDefaultMute_dmesg.log)
[pONHeadsetDefaultMute_logger.log](https://github.com/thesofproject/linux/files/3115787/pONHeadsetDefaultMute_logger.log)

**Comment by wenqingfu** [comment]
why use wont fix label? @mengdonglin , you need to explain why, and close this issue. An open issue with "wont fix" label doesn't help.

**Comment by ClarexZhou** [comment]
Error can't be reproduce now. Close

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM   
Kernel repo：5b1bd17 https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Firmware repo: 39a3735  https://github.com/thesofproject/sof/commits/master |  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
