### ISSUE TITLE
[regression][APL] DSP panic dump to kernel log is not correct

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#871]
While working on the host side FW watchdog patches, I noticed the DSP panic dump printed to Linux kernel log (dmesg) is not sensible. 

Platform: APL / UP2
Linux: latest sofdev (f7e9d4a170ff0942bfab7d48f476dba5f8387c71)
FW: latest tip (81887c9f3add154a11df554bc67d6b09e6050cca

DSP panic dump looks like this now:
```
Apr 25 19:37:42 ubilinux4 kernel: [   44.558242] sof-audio-pci 0000:00:0e.0: error : DSP panic!
Apr 25 19:37:42 ubilinux4 kernel: [   44.558607] sof-audio-pci 0000:00:0e.0: panic: dsp_oops_offset 788480 offset 788480
Apr 25 19:37:42 ubilinux4 kernel: [   44.558616] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
Apr 25 19:37:42 ubilinux4 kernel: [   44.559163] sof-audio-pci 0000:00:0e.0: error: can't enter idle
Apr 25 19:37:42 ubilinux4 kernel: [   44.559564] sof-audio-pci 0000:00:0e.0: error: trace point 00004000
Apr 25 19:37:42 ubilinux4 kernel: [   44.559991] sof-audio-pci 0000:00:0e.0: error: panic at :0
Apr 25 19:37:42 ubilinux4 kernel: [   44.560347] sof-audio-pci 0000:00:0e.0: error: DSP Firmware Oops
Apr 25 19:37:42 ubilinux4 kernel: [   44.560750] sof-audio-pci 0000:00:0e.0: error: Exception Cause: IllegalInstructionCause, Illegal instruction
Apr 25 19:37:42 ubilinux4 kernel: [   44.561372] sof-audio-pci 0000:00:0e.0: EXCCAUSE 0x00000000 EXCVADDR 0x00000000 PS       0x00000000 SAR     0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.562048] sof-audio-pci 0000:00:0e.0: EPC1     0x00000000 EPC2     0x00000000 EPC3     0x00000000 EPC4    0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.562724] sof-audio-pci 0000:00:0e.0: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.563412] sof-audio-pci 0000:00:0e.0: EPS2     0x00000000 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.564093] sof-audio-pci 0000:00:0e.0: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.564775] sof-audio-pci 0000:00:0e.0: stack dump from 0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.565178] sof-audio-pci 0000:00:0e.0: 0x00000000: 00000000 00000000 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.565695] sof-audio-pci 0000:00:0e.0: 0x00000004: 00000000 00000000 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.566207] sof-audio-pci 0000:00:0e.0: 0x00000008: efd96700 76bf3185 f7143028 ffff8abd
Apr 25 19:37:42 ubilinux4 kernel: [   44.566723] sof-audio-pci 0000:00:0e.0: 0x0000000c: f852b600 ffff8abd f6a77600 ffff8abd
Apr 25 19:37:42 ubilinux4 kernel: [   44.567256] sof-audio-pci 0000:00:0e.0: 0x00000010: f6a77600 ffff8abd aeab5452 ffffffff
Apr 25 19:37:42 ubilinux4 kernel: [   44.567775] sof-audio-pci 0000:00:0e.0: 0x00000014: 408cfbf0 ffffac14 f6c40d00 ffff8abd
Apr 25 19:37:42 ubilinux4 kernel: [   44.568300] sof-audio-pci 0000:00:0e.0: 0x00000018: f75b2f40 ffff8abd 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.568814] sof-audio-pci 0000:00:0e.0: 0x0000001c: 00000000 00000000 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.569319] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
Apr 25 19:37:42 ubilinux4 kernel: [   44.569910] sof-audio-pci 0000:00:0e.0: error: trace IO error
```

The register values and stack pointer look completely wrong.

When I revert this FW patch, the register dump starts to look sane again (not yet sure about the stack part):
25cd7795 debugability: extend core dumps to provide AR registers

**Comment by plbossart** [comment]
well duh, looks like the firmware extensions are not backwards compatible??

````
struct sof_ipc_dsp_oops_xtensa {
 	struct sof_ipc_hdr hdr;		---> 	struct sof_ipc_dsp_oops_arch_hdr arch_hdr;
 	                                                                struct sof_ipc_dsp_oops_plat_hdr plat_hdr;
 	uint32_t exccause;		 	uint32_t exccause;
 	uint32_t excvaddr;		 	uint32_t excvaddr;
 	uint32_t ps;		 	uint32_t ps;
 @@ -68,6 +72,11 @@ struct sof_ipc_dsp_oops_xtensa {
 	uint32_t intenable;		 	uint32_t intenable;
 	uint32_t interrupt;		 	uint32_t interrupt;
 	uint32_t sar;		 	uint32_t sar;
 	uint32_t debugcause;
 	uint32_t widnowbase;
 	uint32_t windowstart;
 	uint32_t excsave1;
 	uint32_t ar[XCHAL_NUM_AREGS];
 	uint32_t stack;		 	uint32_t stack;
 } __attribute__((packed));		 } __attribute__((packed));
````

**Comment by xiulipan** [comment]
@plbossart 
I remember this PR https://github.com/thesofproject/sof/pull/591
Not sure if this should be some major ABI change or not, but if there are mismatch it should be a major ABI change?

**Comment by mmaka1** [comment]
Do not revert any FW patches. The core dump looks good and works fine with the core dumper tool. Decoding dumps for all different DSP architectures and their variations may simple do not scale when trying to decode all of them in the driver. I would suggest to keep just basic info in the driver and let the specialized tools to decode it (like our core dumper for xtensa does).

**Comment by kv2019i** [comment]
It seems we have more issues with the oops data when FW is built with gcc, see sof#1346 . With a XT-CC built FW, the kernel oops looks more correct, but is still wrong (due to the ABI differences discussed above). Keeping this open still.

**Comment by kv2019i** [comment]
@mmaka1 wrote:
> Decoding dumps for all different DSP architectures and their variations may simple do not scale when > trying to decode all of them in the driver. I would suggest to keep just basic info in the driver and let 
> the specialized tools to decode it (like our core dumper for xtensa does).

Leaving detailed parsing to the separate tool sounds reasonable, but I think we should still try to include as much of oops info in the dmesg. 

Operations-wise, attaching kernel logs is an established bug reporting method in Linux, i.e. most kernel bugs reported from the field will have the kernel log attached. Further dmesg can store multiple oopses and is not (as) susceptible to power and watchdog flows that are run soon or immediately after the error occurred. The need for users who are reporting errors, to dump a specific debugfs file at the right time, will likely be met less often. The two methods are not exclusive, but there are merits to both.
