### ISSUE TITLE
[UCM] Enable HDMI/DP audio output devices for generic HD-A machine

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#883]
Define audio playback devices for external HDMI/DP displays.

This feature will allow PulseAudio to recognize HDMI/DP sinks and get their hot-plug status.  Then Ubuntu GUI Sound Settings will display the available audio input/output devices

**Comment by libinyang** [comment]
The feature will be divided into below steps:
- [x] support hdmi items in gnome-sound-settings
(1) a patch for hdac_hdmi.c is needed. The patch is submitted to open source.
(2) UCM configure file is ready.

- [x] hdmi monitor hotplug detection
(1) need add jack detection support in hdac_hdmi driver. feature has been filed:  https://github.com/thesofproject/linux/issues/912
(2) refine the UCM configuration file to support it.

- [ ] DP-MST support #755 
Frankly, it is easy to support it in UCM files. But as there are (3 pins) * (3 DP-MST port per pin) = 9 items to fully support DP-MST in gnome-sound-setting. This is unacceptable. Need figure out a proper ways to support DP-MST.

**Comment by wenqingfu** [comment]
> 1. The patch is submitted to open source.

can you please share the link to your patch? is it merged? @libinyang

**Comment by libinyang** [comment]
patch for hdac_hdmi.c in item 1 is merged

**Comment by libinyang** [comment]
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/148874.html

**Comment by libinyang** [comment]
for step 3: https://github.com/thesofproject/linux/issues/755

**Comment by libinyang** [comment]
UCM for step1 and step2 is ready now and updated to Rander's branch.

**Comment by kv2019i** [comment]
Hotplug for DP-MST is now also supported via moving to common HDMI driver. This enhancement is now implemented with #1404 and #1422
