### ISSUE TITLE
[BUG][CML][UCM]Sound setting output can not change to speaker when unplugged headset sometimes.

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/linux#885]
***Describe the bug***
After system waiting for a few seconds, sound setting output  can not change to speaker when unplugged headset Headset. 

***To Reproduce***
1.Pluggin headset, sound setting output  change to headset
2.Waiting for 5 seconds
3.Unplug headset 

***Expected behavior***
sound setting output  change to speaker.

***Environment***

Kernel repo | https://github.com/bardliao/linux/tree/sof-dev-rebase-reduce-v3
-- | --
  |  
Firmware repo | https://github.com/thesofproject/sof/commits/master
  | be1331a [thesofproject/sof: master]
  |  
Topology: | https://github.com/thesofproject/sof/commits/master
  | file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

***UCM config file***
[hda-ucm.zip](https://github.com/thesofproject/linux/files/3124828/hda-ucm.zip)

**Comment by ClarexZhou** [comment]
Error still seen on CML laptop

Test Recipe | +Rander UCM
-- | --
Kernel repo | https://github.com/thesofproject/linux/tree/release/sof-v5.0
  | b6f189b
  |  
Firmware repo | https://github.com/thesofproject/sof/commits/master
  | de5bba4  [thesofproject/sof: master]
  |  
Topology: | https://github.com/thesofproject/sof/commits/master

**Comment by RanderWang** [comment]
@ClarexZhou   is this bug reproduced again? I find the change is late, not never. It is caused by codec driver, which sleeps a long time by msleep() when resuming.

**Comment by ClarexZhou** [comment]
Error not seen on latest UCM. Close

Test Recipe | '+Rander UCM https://github.com/RanderWang/intel-UCM |  
-- | -- | --
Kernel repo | https://github.com/thesofproject/linux/tree/release/sof-v5.0 |  
  | d698c4f | kernel topic/sof-dev branch
  | PR #853 | ASoC: sof: hda: fix fw loading failure
  | PR #868 | ASoC: soc-pcm: BE dai needs prepare when pause release after resume
  |   |  
Firmware repo | https://github.com/thesofproject/sof/commits/master |  
  | 47fcac2  [thesofproject/sof: master] | top of master branch
  |   |  
Topology: | https://github.com/thesofproject/sof/commits/master | Same as above SOF repo
  | file:  tools/topology/sof-hda-generic.m4,  sof-hda-generic-2ch.tplg |
