### ISSUE TITLE
[BUG][CML][UCM]Sound setting input can not remove headset Mic when unplugged headset.

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/linux#886]
***Describe the bug***
Sound setting input can not remove headset Mic device when unplugged headset Mic.

***To Reproduce***
1.Unplug headset
![test](https://user-images.githubusercontent.com/44258626/56862647-aea23400-69df-11e9-8725-c161abbb0804.png)

***Expected behavior***
sound setting input remove headset Mic.

***Environment***

Kernel repo | https://github.com/bardliao/linux/tree/sof-dev-rebase-reduce-v3
-- | --
  |  
Firmware repo | https://github.com/thesofproject/sof/commits/master
  | be1331a [thesofproject/sof: master]
  |  
Topology: | https://github.com/thesofproject/sof/commits/master
  | file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

**Comment by RanderWang** [comment]
This is not a bug. There is no jack exported by codec to detect microphone event. I checked with codec vendor and got the information: this is required by customer for secret reason.

**Comment by mengdonglin** [comment]
@RanderWang 
If there is no jack exported by codec to detect microphone event, why "Headset Mic" can appear? Via GUI pop-up menu which require a user to confirm there is a headset Mic?

If yes, the headset Mic should go away with headphone as well.
