### ISSUE TITLE
[enhancement][CI] add ICL CI tests

### ISSUE THREAD

**Issue by michalgrodzicki** [thesofproject/linux#889]
Please add CI tests for ICL, like we have for APL and WHL. (to avoid regressions)

**Comment by wenqingfu** [comment]
at least we can start with daily CI instead of PR CI. @xiulipan @fredoh9

**Comment by plbossart** [comment]
> at least we can start with daily CI instead of PR CI. 

Can you let me know if the kconfigs needs more work for ICL? I added the 
DRM_I915_ALPHA as suggested by @freqoh9 and it works on my local 
machine, but there CI machines might need other configs?

**Comment by xiulipan** [comment]
@plbossart 
I think @fredoh9 and I will try to do some PR to kconfig base-config to support ICL.

**Comment by fredoh9** [comment]
@xiulipan 
DRM_I915_ALPHA_SUPPORT is GPU's debug/temporary feature when new platform is initiated. It should not be enabled after reaching some milestones. Hence adding DRM_I915_ALPHA_SUPPORT to base-config may be not good idea.

**Comment by xiulipan** [comment]
@fredoh9 
But we may have more new platform, so keep it there will make sure all new platform work with i915 and HDMI codec.

**Comment by wenqingfu** [comment]
ICL added to SOF CI. Close this issue.
