### ISSUE TITLE
[Bug][CML][UCM]No headset/headphone/micrphone selection query when plug in headset after enable UCM

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#892]
**Describe the bug**
No headset/headphone/micrphone selection query when plug in headset after enable UCM

**To Reproduce**
1. Paulseaudio On.
2. Enabled UCM (Put ucm file folder into /usr/share/alsa/ucm/) and reboot system to active.
3. Plug in headset, wait and check

**Expected Result**
headset/headphone/micrphone selection query should pops up.

**Test Recipe**

Kernel repo | https://github.com/thesofproject/linux/commits/release/sof-5.0-slim
-- | --
  | 377dd1d
  |  
Firmware repo | https://github.com/thesofproject/sof/commits/v1.3-rc3
  | c540305  [thesofproject/sof: master]
  |  
Topology: | https://github.com/thesofproject/sof/commits/v1.3-rc3
  | file:  tools/topology/sof-hda-generic.m4,  sof-hda-generic-2ch.tplg

**Comment by ClarexZhou** [comment]
Effected : Need to select used Mic manually. Headset Mic always shown in sound input setting. 
@RanderWang  please comment and close if as required

**Comment by RanderWang** [comment]
I tested it on XPS13 on broadwell platform, and I also found there was no dialog when using UCM. The dialog is triggered by gnome-settings-daemon, which monitors pulse audio. So the behavior of pulse audio changes when using UCM. I don't think it is a bug caused by SOF or our UCM.

**Comment by mengdonglin** [comment]
Not a driver issue but a PulseAudio integration issue with UCM.

**Comment by wenqingfu** [comment]
@jason77-wang

**Comment by jason77-wang** [comment]
If we use the ucm, It is highly possible that we need to change gnome-settings-daemon and gnome-control-center to fix this issue.
