### ISSUE TITLE
Add basic CI for the SOF Linux kernel

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#90]
Need to have checkpatch.pl --strict --codespell and basic compilation information reported for each patch. Also kernel options need to be selected from the kconfig repository to reduce compilation time and cover all SOF targets.

**Comment by xiulipan** [comment]
I will handle the travis CI part.

**Comment by plbossart** [comment]
Thanks @xiulipan I already see some reports.

**Comment by Runoob5** [comment]
0-day CI already support this feature.
Please see CI report in https://github.com/thesofproject/linux/pull/93

**Comment by mengdonglin** [comment]
CI enabled this and so close this issue

**Comment by cujomalainey** [comment]
If we are running CI, once I repair the closed source drivers, can we also do a build with the closed source drivers enabled to verify we don't break them moving forward?
