### ISSUE TITLE
[CNL] It takes more than 1 sec from aplay cmd to sound comes out

### ISSUE THREAD

**Issue by bardliao** [thesofproject/linux#900]
**Describe the bug**
When we start to a playback from runtime suspended, the sound will come out after more than 1 sec. It can be 100% reproduced with headphone playback, but it is < 10% with speaker playback.

**To Reproduce**
1. Wait until DSP is in runtime suspended.
2. run aplay

**Expected behavior**
Sound comes out immediately after aplay cmd is executed.

**Environment**
sof-master: de5bba4
topic/soc-dev: 1071743
platform: CML laptop with ALC3204 codec, and CFL laptop with ALC3254 codec
Reproducibility Rate: 100% on headphone playback

dmesg
[   24.648422] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   24.648460] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   25.148765] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   25.148793] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   26.942076] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[dmesg_latency_debug.txt](https://github.com/thesofproject/linux/files/3146667/dmesg_latency_debug.txt)

**Comment by bardliao** [comment]
The root cause is [alc269_resume](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/pci/hda/patch_realtek.c#L3545) takes too much time.

**Comment by bardliao** [comment]
We can see exactly the same issue on legacy HDA driver. It does headset type detection before playback and it takes time. So close it since it is not a SOF issue

**Comment by mengdonglin** [comment]
@jason77-wang, please report this issue to codec vendor Realtek and ask Realtek to fix it. Thanks!

**Comment by mengdonglin** [comment]
@kailangyang @jason77-wang 

I backup your conclusion here:
"This issue was headset check type delay.
Headset, resume init delay 217ms and headset check type delay for 960ms.
So, 1.5s delay was make sense."

"It is not a new issue, and it is not specific to SOF driver."

**Comment by KailangYang** [comment]
@mengdonglin @bardliao 

>The reproduce steps are:
>1.      plug in headset but don’t select Audio device on the pop up menu.
>2.      run alsamixer and make sure the Input Source is Headset Mic
>3.      play a sound from headset
>The sound will come out about 1.5 sec latter and it is 100% reproduced.

I say it's make sense was upper. It was post by @bardliao.
Play a sound. it will trigger runtime resume.
It will run resume init then do headset check type.
It's 217ms+960ms for ALC3254(ALC295).
But if this hidden issue doesn't fix. This delay will higher than 3s for random.

**Comment by KailangYang** [comment]
@mengdonglin @bardliao @jason77-wang
I put chip->polling_mode = 1 with whisky lake ID in legacy HDA driver(hda_intel.c).
This random sound delay issue will be solved.
Hui Wang and I test it which issue was gone with option chip->polling_mode = 1.
But It's just workarround. it's not a real solution for major fixed.

**Comment by jason77-wang** [comment]
On my machine, it had playback delay and jack detection delay when using legacy HD-Audio driver, after setting polling_mode=1, the playback delay disappears, and the jack detection delay isn't that long, it is acceptable since it needs to run some jack checking routines.

The hda controller is 8086:9dc8.

I can confirm kailangyang's finding can work well on my machine.

**Comment by KailangYang** [comment]
@mengdonglin 
This issue was same as issue #953.
The reproduce rate was high than legacy HDA driver.

**Comment by bardliao** [comment]
Let's move the discussion to #953 and let #900 focus on headset detection issue

**Comment by wenqingfu** [comment]
headset detection issue is dup of #908 which has been fixed , see https://github.com/thesofproject/linux/issues/908#issuecomment-493326022

**Comment by mengdonglin** [comment]
Further track playback latency on issue #953
