### ISSUE TITLE
[BUG] About 2s delay to switch status in sound setting when plug in/out headset in idle.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#908]
**Describe the bug**
Plug in/out headset in idle, check the speaker and headset switch from sound setting. Delay about 2s to switch status.

**To Reproduce**
1.  Stop music 
2. Open sound setting of laptop
3. Plug in  headset, then plug out, check.

**Expected behavior**
About 2s delay to switch status in sound setting when plug in/out headset in idle.

**Environment**
platform: CML laptop with ALC3204 codec
Test Recipe | '+Rander UCM https://github.com/RanderWang/intel-UCM |  
-- | -- | --
Kernel repo | https://github.com/thesofproject/linux/tree/release/sof-v5.0 |  
  | d698c4f | kernel topic/sof-dev branch
  | PR #853 | ASoC: sof: hda: fix fw loading failure
  | PR #868 | ASoC: soc-pcm: BE dai needs prepare when pause release after resume
  |   |  
Firmware repo | https://github.com/thesofproject/sof/commits/master |  
  | 47fcac2  [thesofproject/sof: master] | top of master branch
  |   |  
Topology: | https://github.com/thesofproject/sof/commits/master | Same as above SOF repo
  | file:  tools/topology/sof-hda-generic.m4,  sof-hda-generic-2ch.tplg |  

[jackWithoutPlay_dmesg.log](https://github.com/thesofproject/linux/files/3151034/jackWithoutPlay_dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3151035/logger.log)

**Comment by RanderWang** [comment]
In this case, audio system just resumes from suspend status and codec driver spends much time to resume codec. Please dispatch it to codec vendor for help.

**Comment by mengdonglin** [comment]
Same root cause as #900

**Comment by mengdonglin** [comment]
@jason77-wang, please report this issue to codec vendor Realtek and ask Realtek to fix it. Thanks!

**Comment by KailangYang** [comment]
#908 and #909 were related with #900

**Comment by KailangYang** [comment]
@mengdonglin 

I had sent a fix patch to fix this issue.

**Comment by mengdonglin** [comment]
@kailangyang Could you also share your patch here? Thanks

**Comment by KailangYang** [comment]
Attch patch.

[0000-fix-check-headset-type.patch.txt](https://github.com/thesofproject/linux/files/3190001/0000-fix-check-headset-type.patch.txt)

**Comment by YvonneYang2** [comment]
Error not reproduced with Realtek commit ALSA: hda/realtek - Check headset type by unplug and resume. 

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM/tree/hdmi 
Kernel repo: df06e42 https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout
Topology: https://github.com/thesofproject/sof/commits/debug-ipc-timeout. Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
platform: CML laptop with ALC3204 codec
