### ISSUE TITLE
[UCM][CML]One time pop noise when plug in headset in idle or start play music

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#910]
**Describe the bug**
One time pop noise when plug in headset in idle or start play music.

**To Reproduce**
1. Stop music
2. Open sound setting of laptop
3. Plug in headset, check.

**Expected behavior**
No pop noise 

**Impact**
Pop noise output first.
Pop noise also observed when start music playback with headset connected after long time idle.

**Environment**
Platform: CML laptop with ALC3204 codec
Rander UCM https://github.com/RanderWang/intel-UCM   
Kernel repo：c99938c https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Firmware repo: 47fcac2  https://github.com/thesofproject/sof/commits/master |  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

[plug2sDelay_dmesg.log](https://github.com/thesofproject/linux/files/3151071/plug2sDelay_dmesg.log)
[plug2sdelay_logger.log](https://github.com/thesofproject/linux/files/3151073/plug2sdelay_logger.log)

**Comment by wenqingfu** [comment]
@mengdonglin to reach out to @jason77-wang for fix in codec driver

**Comment by KailangYang** [comment]
Could you describe the issue more?
This issue only occured on ALC3204 platform. Right?

**Comment by KailangYang** [comment]
@mengdonglin @bardliao 

I can't reproduce it on Mantis(ALC3204) and Wasp(ALC3204).
