### ISSUE TITLE
[FEATURE] hdmi needs to support Jack detection

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#912]
Currently, very little intel SOF driver support hdmi jack detection. We should add hdmi jack detection support on the intel sof platforms. It should be better to move jack support from machine drivers to hdac_hdmi.c

**Comment by mengdonglin** [comment]
@libinyang Please list short-term/long-term opens and effort here, provide PR ww20.1

**Comment by libinyang** [comment]
long term is to move jack to hdac_hdmi.c. short term is to implement in machine driver.
Currently I will do the short term.

And after check, our machine has some code to support jack. But it calls a wrong function, which will not create the jack.

**Comment by libinyang** [comment]
Patch is submitted https://github.com/thesofproject/linux/pull/935.
I will submit the patch to community later after a draft review internally.

**Comment by mengdonglin** [comment]
@libinyang please share UCM to Clare. @ClarexZhou please verify #935 and UCM

**Comment by libinyang** [comment]
UCM has been updated to  branch's branch.

**Comment by mengdonglin** [comment]
Fixed by PR #935 that was merged

**Comment by ClarexZhou** [comment]
Error not seen on CML laptop with PR #935 
**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM/tree/hdmi
Kernel：df06e42_ https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout 
Topology: https://github.com/thesofproject/sof/tree/debug-ipc-timeout . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
