### ISSUE TITLE
PGA volume seems to be set for right channel only

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#92]
I've noticed this on Up2 with PCM512x and the WM8804 codec I am working on, by default the left volume is not set:

root@ubilinux4:~# amixer -Dhw:0 cset numid=1
numid=1,iface=MIXER,name='PGA1.0 Master Playback Volume 1'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=32,step=0
  : values=0,32
  | dBscale-min=-64.00dB,step=2.00dB,mute=1

Not clear to me why the left and right values are not set to the same values, there must be some sort of mixer init/topology issue here.

**Comment by mengdonglin** [comment]
@ZhendanYang Could you help to check if this issue can be reproduced on UP2 with PCM512x now?

**Comment by ZhendanYang** [comment]
I test with latest code base(kernel: sof-dev c3ba91f7,sof stable-1.2 40f974 and soft d77beaf).

apl@UP-02:~$ amixer -D hw:0 cset numid=1
numid=1,iface=MIXER,name='Digital Playback Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=255,step=0
  : values=230,230
  | dBscale-min=-103.50dB,step=0.50dB,mute=1

The left and right values are set to the same values.
Seems this issue has been fixed.

**Comment by mengdonglin** [comment]
@juimonen Could you help to check if this issue is also gone in your side?
I closed this issue. But feel free to re-open it if you still see it on your UP^. Thanks!

**Comment by wenqingfu** [comment]
the two commands are not exactly same, name='Digital Playback Volume' vs name='PGA1.0 Master Playback Volume 1', does it matter? @ZhendanYang

**Comment by mengdonglin** [comment]
The mixer names are different but the id for Pierre's "PGA1.0 Master Playback Volume 1" and Zhendan's 'Digital Playback Volume'. @ZhendanYang could you attach the list of all mixers (amixer)?

**Comment by ZhendanYang** [comment]
apl@UP-02:~$ amixer 
Simple mixer control 'DSP Program',0
  Capabilities: enum
  Items: 'FIR interpolation with de-emphasis' 'Low latency IIR with de-emphasis' 'High attenuation with de-emphasis' 'Fixed process flow' 'Ringing-less low latency FIR'
  Item0: 'FIR interpolation with de-emphasis'
Simple mixer control 'Analogue',0
  Capabilities: pvolume
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 1
  Mono:
  Front Left: Playback 1 [100%] [0.00dB]
  Front Right: Playback 1 [100%] [0.00dB]
Simple mixer control 'Analogue Playback Boost',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 1
  Front Left: 1 [100%] [0.80dB]
  Front Right: 1 [100%] [0.80dB]
Simple mixer control 'Auto Mute',0
  Capabilities: pswitch
  Playback channels: Front Left - Front Right
  Mono:
  Front Left: Playback [on]
  Front Right: Playback [on]
Simple mixer control 'Auto Mute Mono',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Auto Mute Time Left',0
  Capabilities: enum
  Items: '21ms' '106ms' '213ms' '533ms' '1.07s' '2.13s' '5.33s' '10.66s'
  Item0: '21ms'
Simple mixer control 'Auto Mute Time Right',0
  Capabilities: enum
  Items: '21ms' '106ms' '213ms' '533ms' '1.07s' '2.13s' '5.33s' '10.66s'
  Item0: '21ms'
Simple mixer control 'Clock Missing Period',0
  Capabilities: enum
  Items: '1s' '2s' '3s' '4s' '5s' '6s' '7s' '8s'
  Item0: '1s'
Simple mixer control 'Deemphasis',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Digital',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 255
  Mono:
  Front Left: Playback 230 [90%] [11.50dB] [on]
  Front Right: Playback 230 [90%] [11.50dB] [on]
Simple mixer control 'Max Overclock DAC',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 40
  Mono: 26 [65%]
Simple mixer control 'Max Overclock DSP',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 40
  Mono: 31 [78%]
Simple mixer control 'Max Overclock PLL',0
  Capabilities: volume volume-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: 0 - 20
  Mono: 9 [45%]
Simple mixer control 'PGA1.0 Master Playback Volume 1',0
  Capabilities: volume
  Playback channels: Front Left - Front Right
  Capture channels: Front Left - Front Right
  Limits: 0 - 32
  Front Left: 18 [56%]
  Front Right: 18 [56%]
Simple mixer control 'Volume Ramp Down Emergency Rate',0
  Capabilities: enum
  Items: '1 sample/update' '2 samples/update' '4 samples/update' 'Immediate'
  Item0: '1 sample/update'
Simple mixer control 'Volume Ramp Down Emergency Step',0
  Capabilities: enum
  Items: '4dB/step' '2dB/step' '1dB/step' '0.5dB/step'
  Item0: '4dB/step'
Simple mixer control 'Volume Ramp Down Rate',0
  Capabilities: enum
  Items: '1 sample/update' '2 samples/update' '4 samples/update' 'Immediate'
  Item0: '1 sample/update'
Simple mixer control 'Volume Ramp Down Step',0
  Capabilities: enum
  Items: '4dB/step' '2dB/step' '1dB/step' '0.5dB/step'
  Item0: '1dB/step'
Simple mixer control 'Volume Ramp Up Rate',0
  Capabilities: enum
  Items: '1 sample/update' '2 samples/update' '4 samples/update' 'Immediate'
  Item0: '1 sample/update'
Simple mixer control 'Volume Ramp Up Step',0
  Capabilities: enum
  Items: '4dB/step' '2dB/step' '1dB/step' '0.5dB/step'
  Item0: '2dB/step'

**Comment by ZhendanYang** [comment]
@mengdonglin 
apl@UP-02:~$ amixer -Dhw:0 cset numid=21
numid=21,iface=MIXER,name='PGA1.0 Master Playback Volume 1'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=32,step=0
  : values=18,18
  | dBscale-min=-64.00dB,step=2.00dB,mute=1
