### ISSUE TITLE
Pass volume min/max linear values from actual volume scale to firmware

### ISSUE THREAD

**Issue by singalsu** [thesofproject/linux#922]
The driver currently passes the volume ramp type and length topology tokens to firmware. The min/max fields are left zeros (would be derived from TLV volume scale). Volume now assumes that ramp of mute to unity gain takes the defined linear ramp time and computes ramp step accordingly.

This assumption creates a very long ramp completion time for high gains (practical for microphone capture). It was fixed by firmware change to on the fly at new volume request re-calculate the the linear ramp step to not exceed the ramp time token.

If the driver is enhanced to lookup and pass the min/max values to firmware the volume component could use the same fixed linear ramp rate for any volume transition.

I marked this as enhancement. The current gain ramp operation with re-calculate step sounds subjectively good and I'm not aware of conflicting requirements for gain ramp so I didn't label this as bug.

**Comment by zhuyingjiang** [comment]
link to https://github.com/thesofproject/sof/issues/1297
