### ISSUE TITLE
[BUG][CML] ipc timed out for 0x30010000 size 84

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#924]
Sometimes I boot the kernel, the dmesg shows "ipc timed out for 0x30010000 size 84", then the sof driver fails to initialize. After entering the desktop, there is no audio deivces at all. The reproducing rate is about 1/10. (with the beta release of 0430)

The related dmesg is:

[    2.077322] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[    2.077324] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    2.094151] iwlwifi 0000:00:14.3 wlp0s20f3: renamed from wlan0
[    2.102628] usbcore: registered new interface driver btusb
[    2.103627] Bluetooth: hci0: Firmware revision 0.1 build 201 week 49 2017
[    2.105165] sof-audio-pci 0000:00:1f.3: unexpected ipc interrupt raised!
[    2.105166] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[    2.128269] HDMI HDA Codec ehdaudio0D2: Max dais supported: 3
[    2.188962] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:1:0-c5403
[    2.188964] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:6:0 Kernel ABI 3:4:0
[    2.188965] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    2.189838] sof-audio-pci 0000:00:1f.3: firmware boot complete
[    2.194021] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link iDisp1
[    2.194023] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link iDisp2
[    2.194024] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link iDisp3
[    2.194024] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link Analog Playback and Capture
[    2.194025] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link Digital Playback and Capture
[    2.194026] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link dmic01
[    2.194027] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link dmic16k
[    2.194385] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:6:0 Kernel ABI 3:4:0
[    2.194386] sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    2.196764] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec0_in not handled
[    2.198307] sof-audio-pci 0000:00:1f.3: warning: widget type 0 name codec1_in not handled
[    2.201046] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    2.201048] Bluetooth: BNEP filters: protocol multicast
[    2.201053] Bluetooth: BNEP socket layer initialized
[    2.254214] i2c_hid i2c-DELL0959:00: i2c-DELL0959:00 supply vdd not found, using dummy regulator
[    2.254224] i2c_hid i2c-DELL0959:00: Linked as a consumer to regulator.0
[    2.254225] i2c_hid i2c-DELL0959:00: i2c-DELL0959:00 supply vddl not found, using dummy regulator
[    2.412800] iwlwifi 0000:00:14.3: Conflict between TLV & NVM regarding enabling LAR (TLV = enabled NVM =disabled)
[    2.423931] iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS
[    2.512134] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x30010000 size 84
[    2.512145] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[    2.512389] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[    2.512390] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[    2.512392] sof-audio-pci 0000:00:1f.3: error: DSP failed to add widget id 0 type 6 name : PGA3.0 stream none reply 0
[    2.512395] sof-audio-pci 0000:00:1f.3: ASoC: failed to load widget PGA3.0
[    2.512422] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -110
[    2.512427] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[    2.512428] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[    2.512441] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: failed to instantiate card -22
[    2.512462] skl_hda_dsp_generic: probe of skl_hda_dsp_generic failed with error -22

**Comment by zhuyingjiang** [comment]
> [ 2.188962] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:1:0-c5403
> [ 2.188964] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:6:0 Kernel ABI 3:4:0

A ABI problem?

**Comment by emilchudzik** [comment]
@jason77-wang for reproduction purposes we need to know which branch/commit ID of kernel/topology/FW did you use.

**Comment by emilchudzik** [comment]
@jason77-wang I see that you used beta release 0430. So probably this is commit ID from these day:
FW/tplg: e4a9f86 = be1331a [thesofproject/sof: master] + Bartosz Kokoszko fix for timeout

With this FW we haven't reproduction 0/30 on production laptop.

**Comment by jajanusz** [comment]
@jason77-wang can you reproduce issue with latest changes? (they probably fix ipc timing issue)

**Comment by tlauda** [comment]
@jason77-wang Missing FW log.

**Comment by wenqingfu** [comment]
should be fixed by #943. please reopen if otherwise.
