### ISSUE TITLE
[Bug][CML]Audio output via DP have 2-5s latency at the beginning 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#925]
**Describe the bug**
Audio output have obvious latency at the beginning via DP

**To reproduce**
1.Play music via DP with command "aplay -Dhw:0,4 -f dat wav/48California_Dreaming.wav -vv -i"

**Expected behavior**
Audio output has no latency.

**Impact**
Audio output has obvious 2-5s latency at the beginning.

**Test env**
Rander UCM https://github.com/RanderWang/intel-UCM  
Kernel repo：5b1bd17
https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: 39a3735
https://github.com/thesofproject/sof/commits/master |  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

**No dmesg/logger error info**

**dmesg log**
```
[  353.358959] sof-audio-pci 0000:00:1f.3: pcm: stream dir 0, posn mailbox offset is 790604
[  353.360824] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 0 cmd 1
[  353.360831] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  353.360965] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  353.360968] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[  354.073172] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  354.073196] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  356.340390] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 0 cmd 0
[  356.340412] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  356.340622] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  356.340636] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=0
[  356.340725] sof-audio-pci 0000:00:1f.3: pcm: free stream 4 dir 0
[  356.340733] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  356.340918] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  356.341014] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 0
[  357.073451] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000
```

[DPOutputLatencyDmesg.log](https://github.com/thesofproject/linux/files/3161517/DPOutputLatencyDmesg.log)
[DPOutputLantencyLogger.log](https://github.com/thesofproject/linux/files/3161558/DPOutputLantencyLogger.log)

**Comment by mengdonglin** [comment]
@libinyang please help to share analysis.

**Comment by libinyang** [comment]
This may be caused by hdmi audio driver or monitor issue.
We have tried different monitors and the latency is different.

**Comment by libinyang** [comment]
Test on legacy hda audio driver:
The latency is long at the first several playbacks as well as the SOF. But after several playback rounds, the latency is acceptable in legacy hda audio driver. 

So this seems also to be related to the SOF audio driver.

**Comment by ClarexZhou** [comment]
Error seen on CFL laptop when playing HDMI via HW:0,5
**Environment**
Kernel: 723615b Canonical kernel https://github.com/jason77-wang/oem/commits/sof-pv
FW: 6cc8da10 https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable
Tplg: same with FW. sof-hda-generic-2ch.tplg

**Comment by dengyangchao** [comment]
issue still can Reproduced on ICL-RVP

test recipe:
Firmware: 9e2aa3d3 Master
Kernel: 53d7754 on topic/sof-dev
Topology: file: sof-hda-generic.tplg same path as firmware
platform: ICL-RVP

**Comment by Bin-QA** [comment]
Environment
Firmware: c8bc4b2 https://github.com/thesofproject/sof/commits/tgl-002-drop-stable
Kernel: intel-next kernel, tag intel-5.4-rc2-2019-10-10, commit id: fc2de5669533
tplg: sof-hda-generic.m4
platform: TGL with onbaoard ALC711 in HD-A mode.

**Comment by mengdonglin** [comment]
@YvonneYang2 @dengyangchao @Bin-QA Please compare the audio playback latency between using SOF and legacy HD-Audio. 

And how about APL/GLK?  Can we have short audio playback latency over DP with SOF and the same monitor?

**Comment by sinahuang** [comment]
This issue can be reproduced with kernel sof-dev on CML-S RVP with onboard ALC711 in HDA mode..

Test recipe:

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit: 4e76b4a
FW: https://github.com/thesofproject/sof/commits/master commit: 0e8cf66
Tplg: master e5fe2ca sof-hda-generic-4ch.tplg
Platform: CML-S RVP with onboard ALC711 in HDA mode.

**Comment by dengyangchao** [comment]
Error not seen after build kernel with config https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh, this config is for PR#1155 on both I2S and HDA.

Verified with below platforms:
CML laptop with onboard ALC3204 in HDA mode
CFL-S RVP with onboard ALC700 in HDA mode
ICL RVP with onboard ALC700 in HDA mode
GLK Chrome with onboard DA7219 in I2S mode
CML-S RVP with onboard ALC711 in HDA mode
