### ISSUE TITLE
[Bug][CML]ipc error for 0x60010000 size 20

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#934]
**Summary**:
100% reproduce 'ipc error for 0x60010000 size 20' after do steps as below.

**To reproduce**

1. aplay -Dhw:0,0 -f dat wav/48California_Dreaming.wav -vv -i
2. Pause music
3. Open another terminal, run 'sudo rtcwake -m mem -s 2' to enter S3 and wake up
4. Resume music
5. Ctl+z to put background
6. 'fg'. failed and error can been seen.

**Expect result**
Stream output normally.

**Reproduce rate: 100%**

**Test recipe**
Rander UCM https://github.com/RanderWang/intel-UCM
Kernel repo：d698c4f https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: 030c81c https://github.com/thesofproject/sof/commits/master |
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
File: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
Platform: CML laptop with ALC3204 codec

**dmesg**
```
[ 3722.528030] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 3722.528066] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 3724.556977] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[ 3724.556997] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 3724.557203] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 3724.557217] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=0
[ 3725.527644] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 3725.527676] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 3725.932393] sof-audio-pci 0000:00:1f.3: pcm: prepare stream 0 dir 0
[ 3725.932397] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 0
[ 3725.932429] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[ 3725.932431] sof-audio-pci 0000:00:1f.3: periods:4
[ 3725.932450] sof-audio-pci 0000:00:1f.3: stream_tag 1
[ 3725.932464] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[ 3725.932761] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60010000 size 20
[ 3725.932770] sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 1
[ 3725.932774] sof-audio-pci 0000:00:1f.3: error: set pcm hw_params after resume
[ 3725.932778] sof-audio-pci 0000:00:1f.3: ASoC: platform prepare error: -22
[ 3725.932783]  HDA Analog: ASoC: prepare FE HDA Analog failed
[ 3725.932873] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 0
[ 3725.932882] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 3725.933048] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 3725.933166] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 0
[ 3726.527978] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 3726.528010] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 3728.371886] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 3728.372112] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 3728.372165] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[ 3728.372172] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[ 3728.372175] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
[ 3728.372209] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
```
**Error logger**
![57506405-4ed85100-732e-11e9-97d9-055554e64b11](https://user-images.githubusercontent.com/50347470/57593691-3c008f00-756f-11e9-8967-24f599f7a22d.png)

[ipcError_All_logger.log](https://github.com/thesofproject/linux/files/3171001/ipcError_All_logger.log)
[ipcError_dmesg.log](https://github.com/thesofproject/linux/files/3171002/ipcError_dmesg.log)

**Comment by libinyang** [comment]
patch is submitted: https://github.com/thesofproject/linux/pull/936

**Comment by lyakh** [comment]
Interestingly the same test sequence also produces a similarly appearing (resume failing) error on Up^2 with different kernel and firmware messages. The proposed PR #936 also fixes it!

**Comment by ClarexZhou** [comment]
Retest on cml with PR #936 , ipc error issued is fixed. music can be switch to fg and output normally after s3
**Environment**
platform: CML laptop with ALC3204 codec, and CFL laptop with ALC3254 codec   
Rander UCM https://github.com/RanderWang/intel-UCM   
Kernel repo：9494607 https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/master +PR1354  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

**Comment by wenqingfu** [comment]
> Interestingly the same test sequence also produces a similarly appearing (resume failing) error on Up^2 with different kernel and firmware messages. The proposed PR #936 also fixes it!

please help to post your review to #936 and approve it if you agree @lyakh
