### ISSUE TITLE
[Bug][WHL] ipc timed out after S3 after '0x40010000: GLB_PM_MSG: CTX_SAVE'

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/linux#944]
**Summary:**
'ipc timed out for for '0x40010000: GLB_PM_MSG: CTX_SAVE' after stop aplay or system reboot.

**To reproduce**
Set up: Mantis WHL, no peripherals connected excepte USB etherner card for remote ssh.
Boot Mantis WHL device.
Log in.
Open shell and force S3 with:
<code>sudo rtcwake -m mem -s 3</code>

**Actual result**
error: ipc timed out for 0x40010000: GLB_PM_MSG: CTX_SAVE

**Reproduce rate:**
+20% (typically happens after three S3 tries after boot)

**Test recipe**
Kernel repo: 9d424352fe4 (sof/topic/sof-dev)
       - same results also with f19ab80480b8 (sof/topic/sof-dev) + thesofproject/linux#895
Firmware repo: 42390011 (master)
       - same results also with 4f239dea (HEAD -> dai-channel-fix, ranjani/fix/link-dma-allocation) of thesofproject/sof/pull/1354 
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

**Dmesg log**
```
[  141.785846] OOM killer enabled.
[  141.785847] Restarting tasks ... done.
[  141.833840] PM: suspend exit
[  141.855839] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  142.163915] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
[  142.163934] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  142.164207] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0xffffffff trace 0xffffffff
[  142.164221] sof-audio-pci 0000:00:1f.3: error: host status 0x80000000 dsp status 0x00000000 mask 0x00000003
[  142.164225] sof-audio-pci 0000:00:1f.3: error: ctx_save ipc error during suspend -110
```

Notes:
Similar to thesofproject/linux#934 but the fix (PR936) does not help in this case.

**Comment by kv2019i** [comment]
@ClarexZhou FYI ... this is similar to https://github.com/thesofproject/linux/issues/919 but this specifically appens with the S3 routine. Let's track separately as the steps to reproduce are different.

**Comment by kv2019i** [comment]
Assigning for myself as I can reproduce this easily.

To exclude possible compiler impact, tested this scenario today with both GCC built image and  XT-CC built image from @emilchudzik and outcome and repro rates are the same.

**Comment by kv2019i** [comment]
Log with some additional debugs (FYI @emilchudzik  and @lyakh), comments with KV:

<pre>
May 17 13:10:52 rukoilijasirkka kernel: [   96.488640] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40020000: GLB_PM_MSG: CTX_RESTORE
May 17 13:10:52 rukoilijasirkka kernel: [   96.960199] sof-audio-pci 0000:00:1f.3: IRQ!
***KV: added a trace to irq_thread to see when the thread is kicked
May 17 13:10:52 rukoilijasirkka kernel: [   96.960214] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x90020000 mask 0x00000003
May 17 13:10:52 rukoilijasirkka kernel: [   96.960232] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
May 17 13:10:52 rukoilijasirkka kernel: [   96.960256] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
May 17 13:10:52 rukoilijasirkka kernel: [   96.960265] sof-audio-pci 0000:00:1f.3: IRQ!
May 17 13:10:52 rukoilijasirkka kernel: [   96.960270] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
May 17 13:10:52 rukoilijasirkka kernel: [   97.460071] sof-audio-pci 0000:00:1f.3: IRQ!
May 17 13:10:52 rukoilijasirkka kernel: [   97.460086] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x90020000 mask 0x00000003
May 17 13:10:52 rukoilijasirkka kernel: [   97.460105] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
May 17 13:10:52 rukoilijasirkka kernel: [   97.460129] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
May 17 13:10:52 rukoilijasirkka kernel: [   97.460138] sof-audio-pci 0000:00:1f.3: IRQ!
May 17 13:10:52 rukoilijasirkka kernel: [   97.460146] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
May 17 13:10:52 rukoilijasirkka kernel: [   97.527407] OOM killer enabled.
May 17 13:10:52 rukoilijasirkka kernel: [   97.527407] Restarting tasks ... done.
May 17 13:10:52 rukoilijasirkka kernel: [   97.571340] PM: suspend exit
May 17 13:10:52 rukoilijasirkka kernel: [   97.602254] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
May 17 13:10:52 rukoilijasirkka kernel: [   97.612964] sof-audio-pci 0000:00:1f.3: KV: IPC round 1 ret 0
May 17 13:10:52 rukoilijasirkka kernel: [   97.612966] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
***KV: I added polling to driver side to observe status before the full IPC timeout elapses... no new info, but there are some more traces 
May 17 13:10:52 rukoilijasirkka kernel: [   97.612982] sof-audio-pci 0000:00:1f.3: unknown ROM status value 0000000c
May 17 13:10:52 rukoilijasirkka kernel: [   97.613250] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000081 trace 0x00000081
***KV: I'm using the debugs from 'debug-ipc-timeout' branch ... counter value of 81 has increased since 80, so based on thsi logs, DSP did reply to CTX_SAVE
***KV: no IRQ trace, so host side does not get the IRQ
May 17 13:10:52 rukoilijasirkka kernel: [   97.613258] sof-audio-pci 0000:00:1f.3: error: host status 0x80000000 dsp status 0x00000000 mask 0x00000003
</pre>

**Comment by wenqingfu** [comment]
what about if you don't apply 1354 and 895?

**Comment by kv2019i** [comment]
@lyakh Here's the full dmesg with unpatched SW+FW from the IPC timeout branches. In this log, FW load failed on 4th iteration.

Linux: 29fbf66682fe (sof/topic/ipc)
FW: 7330436e (debug-ipc-timeout)

[dmesg-20190520-i.txt](https://github.com/thesofproject/linux/files/3196867/dmesg-20190520-i.txt)

**Comment by kv2019i** [comment]
@wenqingfu wrote:
> what about if you don't apply 1354 and 895?

1354+895 is not applied in the IPC branch. I did earlier test with the patches applied as well, but no difference. I'll next test the 5.0 release branch as Claire reported different results with that.

**Comment by kv2019i** [comment]
@ClarexZhou @lyakh 
Tested with:
48e3f0b1b6be (sof/topic/ipc-v5.0)
... and I get the same result as Clare, __no IPC timeout__. Did stress runs 0/500 and 0/100 iterations (a full system reboot in between). The patch delta between v5.0 branches and latest sof-dev is of course rather massive, but it's either an issue in upstream suspend code or in our rebase.

**Comment by kv2019i** [comment]
@lyakh noticed that there is a 20sec gap in timestamps just before the error in [dmesg-20190520-i.txt](https://github.com/thesofproject/linux/files/3196867/dmesg-20190520-i.txt) 

I now took two more logs (with same 5.2-rc linux+fw as with previous log) and in these new logs, there is no 20sec gap visible:
[dmesg-20190520-iii-s3-stress-fails.txt](https://github.com/thesofproject/linux/files/3197523/dmesg-20190520-iii-s3-stress-fails.txt)
[dmesg-20190520-i.txt](https://github.com/thesofproject/linux/files/3197524/dmesg-20190520-i.txt)

So best lead seems to be to bisect what happened between 5.0 and 5.2-rc as timeouts disappear if we go back to 5.0 integration branch.

**Comment by kv2019i** [comment]
Hmm, I made an experiment and tried this scenario on sof/topic/sov-dev-rebase, then rebased the series back to 5.1 and back to 5.0. Results the following:

Branch  | Test result  | Comments 
-------- | -------------|--------
sof/topic/sof-dev | FAIL | 5.2-rc
sof/topic/sov-dev-rebase | FAIL | 5.2-rc 
above rebased to 5.1 | FAIL | https://github.com/kv2019i/linux/tree/topic/gh959-rebase-5.1-fails
above rebased to 5.0 | OK | https://github.com/kv2019i/linux/tree/topic/gh959-rebase-5.0-ok
topic/ipc-v5.0 | OK | 5.0 integration branch plus IPC debug patch

FAIL = at least one IPC timeout in 100 iterations of S3 suspend/resume, with 5sec duty cycles and no audio playback during test

The patch delta is still large, so rootcausing is probably easier by other means than bisect.

**Comment by kv2019i** [comment]
The problem always  occurs when runtime PM suspend is triggered for the first time after a S3 resume. 

Disabling runtime PM seems to avoid the problem and failures cannot be triggered.

**Comment by ranj063** [comment]
@kv2019i this change fixes the issue for me on CML:
```
diff --git a/sound/soc/sof/pm.c b/sound/soc/sof/pm.c
index 775551106bc9..ba6cd4d85aa8 100644
--- a/sound/soc/sof/pm.c
+++ b/sound/soc/sof/pm.c
@@ -350,11 +350,6 @@ static int sof_suspend(struct device *dev, bool runtime_suspend)
                return ret;
        }
 
-#if IS_ENABLED(CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE)
-       /* cache debugfs contents during runtime suspend */
-       if (runtime_suspend)
-               sof_cache_debugfs(sdev);
-#endif
        /* notify DSP of upcoming power down */
        ret = sof_send_pm_ipc(sdev, SOF_IPC_PM_CTX_SAVE);
        if (ret < 0) {
@@ -364,6 +359,12 @@ static int sof_suspend(struct device *dev, bool runtime_suspend)
                return ret;
        }
 
+#if IS_ENABLED(CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE)
+       /* cache debugfs contents during runtime suspend */
+       if (runtime_suspend)
+               sof_cache_debugfs(sdev);
+#endif
+
        /* power down all DSP cores */
        if (runtime_suspend)
                ret = snd_sof_dsp_runtime_suspend(sdev, 0);
```

**Comment by plbossart** [comment]
@ranj063 I don't get this fix at all. I thought we were not supposed to use any IPC or read memory windows after the CTX_SAVE IPC? Reading them after they are power gated sounds weird.

**Comment by ranj063** [comment]
@plbossart I totally agree and its quite bizarre that this seems to work. Let me try a test with CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE disabled to confirm my theory

**Comment by ranj063** [comment]
@plbossart I am convinced it is a problem with memcpy_fromio() thats causing the timeout but I am not an expert on it. I disabled CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE and I am able to run 100 iterations of the S3 stress test without any issues. 

But I am not an expert and I could use some help

**Comment by ranj063** [comment]
@kv2019i I think we should call this P2 as the issue occurs only when CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE is enabled

**Comment by kv2019i** [comment]
@ranj063 wrote:
> @kv2019i I think we should call this P2 as the issue occurs only when 
> CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE is enabled

Ack. Excellent finding. I could reproduce your results as well, disabling debufgs cache save avoids the issue, so P2 is warranted.

I think both this and rebase back to 5.0 change the timing of the flow, and that leads to different repro rate. The actual rootcause is still unclear and that's still something we need to find out (or otherwise this will pop back).

**Comment by kv2019i** [comment]
@ranj063 wrote:
> @plbossart I am convinced it is a problem with memcpy_fromio() thats causing the timeout but I am not an expert on it. I disabled CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE and I am able to run 100 iterations of the S3 stress test without any issues.

I bisected all iomem areas separately and none of them clearly trigger the problem (I was first suspecting reading the register area would have unwanted side-effects). So clearly changing whicha nd how many iomem areas are dumped, changes repro rate, but still doesn't explain the rootcause. Looking at hda_suspend/resume code now. FYI @lyakh

**Comment by kv2019i** [comment]
@lgirdwood FWIW, here are hda+regs dumps after scenario of this bug happens:
[dump-hda-after-ctx-save-fail.zip](https://github.com/thesofproject/linux/files/3202541/dump-hda-after-ctx-save-fail.zip)
[dump-regs-after-ctx-save-fail.zip](https://github.com/thesofproject/linux/files/3202545/dump-regs-after-ctx-save-fail.zip)

I've also gone through hda_suspend/hda_resume code and nothing obvious pops up. Especially this bug is not systematic, so basic suspend+resume logic seems ok. Further, if runtime-PM is disabled, the bug does not trigger, suggesting that the suspend+resume logic itself is correct.

**Comment by kv2019i** [comment]
Finally a potential rootcause candidate. I now see following sequence in multiple failures:

- sof_resume(runtime=0) completed
- firmware boot and topology parsing is ok (last IPC CTX_RESTORE)
- system S3 resume still running (syncing filesystems)
- sof_suspend(runtime=1) starts
     - snd_sof_release_trace()
     - hda_dsp_trace_release()
     - we stop the dma-trace DMA 
- IRQ while sof_suspend is copying iomem regions (debugfs cache), 
- ipc rx: 0x90020000: GLB_TRACE_MSG
      -> **ouch**, fw is sending traces while we have released the trace, should not happen!
- sof_suspend() resumes, sends CTX_SAVE IPC 
      -> no response and sof_suspend() fails

**Comment by ranj063** [comment]
@kv2019i fantastic. I filed an issue a while ago asking why we do not free DMA trace https://github.com/thesofproject/sof/issues/1234. Maybe this is what we need during suspend apart from just sending a stop trigger?

**Comment by plbossart** [comment]
Can you try adding https://github.com/thesofproject/linux/pull/949 to remove the trace and see if indeed it solves all our problems.

**Comment by plbossart** [comment]
I meant temporarily to further narrow down the issues to the trace.

**Comment by ranj063** [comment]
> Can you try adding #949 to remove the trace and see if indeed it solves all our problems.

@kv2019i @plbossart I disabled trace but it didnt help. I do not think the problem is because of trace.
The only way I can get it to work is if I disable debugfs caching.

**Comment by stevyan** [comment]
The same issue occurred on CFL RVP HDA.

**Test Recipe**
date: 2019-05-22
sof (master): 3e423f41
linux (topic/sof-dev): e3ec7cf
topology: sof-hda-generic.tplg

**dmesg log**
```
[  553.113537] OOM killer enabled.
[  553.113539] Restarting tasks ... done.
[  553.119556] video LNXVIDEO:00: Restoring backlight state
[  553.119558] PM: suspend exit
[  553.192381] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  553.493781] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
[  553.493799] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  553.494202] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0xffffffff trace 0xffffffff
[  553.494217] sof-audio-pci 0000:00:1f.3: error: host status 0x80000000 dsp status 0x00000000 mask 0x00000003
[  553.494221] sof-audio-pci 0000:00:1f.3: error: ctx_save ipc error during suspend -110
[  553.494231] sof-audio-pci 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -110)
```

**Comment by kv2019i** [comment]
@ranj063 wrote:
> @kv2019i @plbossart I disabled trace but it didnt help. I do not think the problem is because of trace.
> The only way I can get it to work is if I disable debugfs caching.

Confirmed on my side as well. It seems getting log traces out of sync was a symptom, not the rootcause. Back to square one.

I also got some not-so-good results with long tests with both debugfs-cache and dma-trace disabled. The test still fails me but it takes many more iterations, in this case after 119 and after 128 iterations.
Test recipe is S3 suspend with 3 sleep time in S3, and 5 second sleep with system up:
<code>while true ; do rtcwake -m mem -s 3 ; sleep 5 ; done</code>

Two logs attached:
[20190522-kernlog-nodebugfscache-nodmatrace-fails-logtail.txt](https://github.com/thesofproject/linux/files/3210887/20190522-kernlog-nodebugfscache-nodmatrace-fails-logtail.txt)
[20190523-kernlog-nodebugfscache-nodmatrace-fails-logtail.txt](https://github.com/thesofproject/linux/files/3210888/20190523-kernlog-nodebugfscache-nodmatrace-fails-logtail.txt)

**Comment by ClarexZhou** [comment]
"0x40010000: GLB_PM_MSG: CTX_SAVE" ipc timed out still can be reproduced after disable CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE in kernel config.

Kernel:
https://github.com/lyakh/linux/tree/ipc-timeout 
commit 5969756   ASoC: SOF: hda: couple host and link DMA during FE hw_free , PR 895
FW:
https://github.com/lyakh/sof/tree/ipc-timeout
commit: b527fd7  dai: assign/free link DMA channel during dai_config() , PR1354

[s3__test_63_dmesg_error .log](https://github.com/thesofproject/linux/files/3211900/s3__test_63_dmesg_error.log)
[s3__test_63_logger_error.log](https://github.com/thesofproject/linux/files/3211901/s3__test_63_logger_error.log)
[s3_test_63_logger_all.log](https://github.com/thesofproject/linux/files/3211902/s3_test_63_logger_all.log)

**Comment by kv2019i** [comment]
@lyakh @ranj063 @lgirdwood 
I today made following experiment. I added following to start of pm.c:sof_suspend():

1. send CTX_RESTORE ipc at start (no-op on FW side, good tool to check IPC is working)
2. sleep for 1sec
3. send another CTX_RESTORE
4. run existing save debugfs-cache code
5. send another CTX_RESTORE
6. send existing CTX_SAVE code and continue

Upon triggering the bug, IPC failure happens systematically at (3).

So that suggests that:

- bug is not related specifically to CTX_SAVE (as failure happens already with CTX_RESTORE)
- bug is not related to debugfs cache save (as failure happens before save)

Rootcause is still unknown, investigation continues.

**Comment by kv2019i** [comment]
Problem now tracked to following upstream patch that went into 5.1:
https://github.com/kv2019i/linux/commit/b5a236c175b0d984552a5f7c9d35141024c2b261 

If reverted, it seems the problem cannot be reproduced with the steps in this bug.

**Comment by kv2019i** [comment]
Problem root caused to power recycling the HDA codec while ADSP HDA controller is powered up. A simple IPC test loop (sending any IPC message to ADSP in a loop) stops working immediately when HDA codec power cycle happens. Upstream patch https://github.com/kv2019i/linux/commit/b5a236c175b0d984552a5f7c9d35141024c2b261 itself looks ok, but it starts to cause this problem more often.

**Comment by kv2019i** [comment]
PR978 is not a full fix -- it prevents codec-suspend cycle, but it doesn't prevent codec-resume. I have at least one case (with 150+ iterations) that still hits a problem and logs show codec-resume happens in middle of DSP suspend sequence. Reverting https://github.com/kv2019i/linux/commit/b5a236c175b0d984552a5f7c9d35141024c2b261 prevents this as well (but not fool-proof either).

**Comment by lyakh** [comment]
> PR978 is not a full fix -- it prevents codec-suspend cycle, but it doesn't prevent codec-resume. I have at least one case (with 150+ iterations) that still hits a problem and logs show codec-resume happens in middle of DSP suspend sequence. Reverting [kv2019i@b5a236c](https://github.com/kv2019i/linux/commit/b5a236c175b0d984552a5f7c9d35141024c2b261) prevents this as well (but not full-proof either).

@kv2019i what do you mean "not full proof?" Do you mean, that also with that revert IPC timeouts can be reproduced?

**Comment by kv2019i** [comment]
@lyakh wrote:
> @kv2019i what do you mean "not full proof?" Do you mean, that also with that revert IPC timeouts can be reproduced?

Oops, sorry, bad English.  Reverting the patch does prevent the IPC timeouts using the reproduction steps of this bug, no failing cases. By fool proof I mean that now that we know the actual mechanism, we can see the revert only addresses one specific case, but there might be many more scenarios where codec runtime PM is triggered, leading to a IPC fault. But true, probably best not to mix things -- for the repro steps of this bug, the revert is good with no failing cases and recent test rounds also point to this.

**Comment by kv2019i** [comment]
Update on status of this and different approaches to address this:

- https://github.com/kv2019i/linux/commit/577361d962f7f438ad89dbf3bca919e8ba7837a0 -> best known method now
- reverting https://github.com/kv2019i/linux/commit/b5a236c175b0d984552a5f7c9d35141024c2b261 -> not ok to push upstream
- https://github.com/thesofproject/linux/pull/978 -> abandoned

**Comment by kv2019i** [comment]
Problem rootcaused to MSI IRQ mode. This bug will be closed by disabling MSI:

* https://github.com/thesofproject/linux/pull/1002 -> this be used to close the bug, disable MSI Mode
* [kv2019i@577361d](https://github.com/kv2019i/linux/commit/577361d962f7f438ad89dbf3bca919e8ba7837a0) -> will be submitted to sof-dev also

Keeping open until patch is merged and fix can be validated with sof-dev.

**Comment by kv2019i** [comment]
A lot of progress has happened to refine the fixes to something we could merge upstream:

- https://github.com/thesofproject/linux/pull/1013 - always wake irq threads
- https://github.com/thesofproject/linux/pull/1011 - irq masking based
- https://github.com/thesofproject/linux/pull/1015 - combined the handlers

Plan is to still keep MSI enabled in sof-dev. Keeping open until one of the solutions is merged.

**Comment by kv2019i** [comment]
https://github.com/thesofproject/linux/pull/1013 was now merged and no new sightings -> closing this bug.
