### ISSUE TITLE
Silence issue when capture on cnl with rt274 codec.

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#95]
Summary:
I record a test wav file using "arecord -D hw；0，0 -c 2 -r 48000 -f s16_le", but the wav file is silent. 
but test it on SSP port, the recorded waveform is clean.

Env:
sof : 83ed9f8139869440247afcf9690b67d1d769030b
sof-dev : b73d79a0f72905146ff30465518aa7e6f0bc1655
soft : 53e8c47591c44dd8bfb075f9d8ba5d43142f797d
tplg: sof-cnl-rt274.tplg

Log:
[dmesg.log](https://github.com/thesofproject/linux/files/2317297/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/linux/files/2317298/rmbox-t.log)

**Comment by mengdonglin** [comment]
Only support no codec mode on CNL, so close this bug.
