### ISSUE TITLE
[BUG][CML]Aplay not exist after do Suspeand & Resume with playback_Analog_50 times

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#951]
**Describe the bug**
Aplay not exist after do Suspeand & Resume with playback_Analog_50 times

**To Reproduce**

Set Suspeand & Resume with playback_Analog_50 times via command “aplay -Dhw:0,0 -r48000 -c2 -fs16_le /dev/zero & sudo ./stress-s3.sh 50 1 1”

**Expected behavior**
Streaming will continuous playback during the 50 times test

**Actual result**
Show "aplay not exist", but do aplay again can output audio.

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM  
Kernel repo：9494607 https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/master +PR1354  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
platform: CML laptop with ALC3204 codec

**dmesg**
```
[  285.490582] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 1
[  285.490595] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  285.490767] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  285.490770] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[  286.445762] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  286.445804] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  291.019550] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  291.019577] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  291.019833] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  291.019845] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=0
[  291.019934] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 0
[  291.019939] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  291.020147] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  291.020171] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  291.020496] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  291.020633] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 0
[  291.945521] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  291.945553] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  293.134455] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  293.134800] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  293.134840] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[  293.134843] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[  293.134844] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
[  293.134869] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
```

[Aplayauto.log](https://github.com/thesofproject/linux/files/3185169/Aplayauto.log)
[AplayautoDisappeared_dmesg.log](https://github.com/thesofproject/linux/files/3185170/AplayautoDisappeared_dmesg.log)

**Comment by lyakh** [comment]
@YvonneYang2 could you please clarify what 'Show "aplay not exist"' means? Or paste the output or attach a screen shot?

**Comment by plbossart** [comment]
Agree with @lyakh, there is literally zero useful information to figure out what the issue might be. Even the logs don't show any error.

**Comment by YvonneYang2** [comment]
The issue so far only occurred once. 

Command “aplay -Dhw:0,0 -r48000 -c2 -fs16_le /dev/zero & sudo ./stress-s3.sh 50 1 1" is to stress test S3 and resume with aplay playback.

"Aplay not exist" means aplay process was killed during s3.
After the issue occurred, we do aplay again, can aplay music normally.

**Comment by wenqingfu** [comment]
Information has been distorted. Please open a new one next time when you use playback_Analog_50 test case

**Comment by YvonneYang2** [comment]
The issue not reproduced again till now. We will report a new issue once we reproduced again.
