### ISSUE TITLE
[BUG][CML]DP&HDMI hot plug detection failed after S3

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#952]
**Summary**:
DP and HDMI hot plug detection failed after S3

**To reproduce**

1. Plug in HDMI or DP before s3 and check the hot-plug status via "amixer cget numid=37" or "amixer cget numid=38"
2. Do s3 and plug out HDMI or DP after s3
3. Check the hot-plug status via "amixer cget numid=37" or "amixer cget numid=38"

**Expect result**
Hot-plug status should de "value=off" after plug out HDMI or DP

**Impact**
Status always be "value=on" no matter how many times you do hot plug after s3

**Reproduce rate: 100%**

**Test recipe**
Rander UCM https://github.com/RanderWang/intel-UCM/tree/hdmi
Kernel repo：c536f9f https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout	
Topology: https://github.com/thesofproject/sof/commits/debug-ipc-timeout	Same as above SOF repo	
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
platform: CML laptop with ALC3204 codec

**dmesg**
```
[ 1038.449211] OOM killer enabled.
[ 1038.449213] Restarting tasks ... done.
[ 1038.492836] PM: suspend exit
[ 1038.909721] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1038.909762] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1039.456167] sof-audio-pci 0000:00:1f.3: hda: prepare stream dir 1
[ 1039.456210] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[ 1039.456273] sof-audio-pci 0000:00:1f.3: pcm: prepare stream 0 dir 1
[ 1039.456277] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 1
[ 1039.456326] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[ 1039.456329] sof-audio-pci 0000:00:1f.3: periods:4
[ 1039.456352] sof-audio-pci 0000:00:1f.3: stream_tag 3
[ 1039.456367] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[ 1039.456694] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[ 1039.456703] sof-audio-pci 0000:00:1f.3: pcm: stream dir 1, posn mailbox offset is 790528
[ 1039.456802] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 1 cmd 1
[ 1039.456825] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 1039.457114] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 1039.457126] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[ 1039.915628] ax88179_178a 1-3:1.0 enx000ec6a1e569: ax88179 - Link status is: 1
[ 1040.222954] usb 1-4: USB disconnect, device number 17
[ 1040.306634] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[ 1040.409511] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1040.409533] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1115.573016] usb 1-4: new high-speed USB device number 18 using xhci_hcd
[ 1116.090046] usb 1-4: New USB device found, idVendor=2109, idProduct=0100, bcdDevice= 3.00
[ 1116.090053] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1116.090058] usb 1-4: Product: USB 2.0 BILLBOARD             
[ 1116.090062] usb 1-4: Manufacturer: VIA Technologies Inc.         
[ 1116.090065] usb 1-4: SerialNumber: 0000000000000001
[ 1125.222975] sof-audio-pci 0000:00:1f.3: pcm: open stream 4 dir 0
[ 1125.222980] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 1125.222983] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 1125.222986] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 1125.223462] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[ 1125.223479] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 4 dir 0
[ 1125.223485] sof-audio-pci 0000:00:1f.3: generating page table for 000000006f4a090d size 0xffc0 pages 16
[ 1125.223521] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[ 1125.223543] sof-audio-pci 0000:00:1f.3: periods:4
[ 1125.223562] sof-audio-pci 0000:00:1f.3: stream_tag 1
[ 1125.223576] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[ 1125.223763] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[ 1125.223769] sof-audio-pci 0000:00:1f.3: pcm: stream dir 0, posn mailbox offset is 790604
[ 1125.226032] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 0 cmd 1
[ 1125.226047] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 1125.226278] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 1125.226288] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[ 1125.909883] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1125.909931] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1145.511820] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 0 cmd 0
[ 1145.511841] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 1145.511990] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 1145.512002] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=0
[ 1145.512146] sof-audio-pci 0000:00:1f.3: pcm: free stream 4 dir 0
[ 1145.512154] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 1145.512328] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 1145.512405] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 0
[ 1146.409657] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1146.409691] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1157.392484] usb 1-4: USB disconnect, device number 18
[ 1157.479843] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
```
[DPNotTrigger_Dmesg.log](https://github.com/thesofproject/linux/files/3186343/DPNotTrigger_Dmesg.log)
[DPNottrigger_failed.log](https://github.com/thesofproject/linux/files/3186344/DPNottrigger_failed.log)
[DPNotTrigger.log](https://github.com/thesofproject/linux/files/3186345/DPNotTrigger.log)

**Comment by libinyang** [comment]
In this case, audio driver resume will be called before the eld is updated from gfx. This will cause the jack_event is wrongly counted.

**Comment by libinyang** [comment]
patch has been submitted to the community. Will update the mail thread address later because there is some latency of the emails in the web.

**Comment by mengdonglin** [comment]
Upstream thread: https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149747.html
[alsa-devel] [PATCH RFC] ASoC: hdac_hdmi: refine hdmi jacks

**Comment by libinyang** [comment]
> Upstream thread: https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149747.html
> [alsa-devel] [PATCH RFC] ASoC: hdac_hdmi: refine hdmi jacks

Thanks for help to update the link.

**Comment by YvonneYang2** [comment]
Issues not reproduced after apply “ASoC: hdac_hdmi: jack hotplug in S3” with test recipe as below:

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM/commits/hdmi
Firmware: 7a78809 https://github.com/bardliao/sof/tree/dell-test
Kernel: 1051f31 https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Topology: file: tools/topology/sof-hda-generic.tplg, sof-hda-generic-2ch.tplg same as firmware
platform ：CML laptop

**Comment by libinyang** [comment]
new patchset is updated: https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149862.html
[RFC PATCH 0/4] ASoC: hdac_hdmi: refine the hdac_hdmi jacks

**Comment by libinyang** [comment]
Takashi gave some comments. He requires the usespace should be ready firstly. So I will prepare the userspace configuration this week.
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/150029.html

**Comment by kv2019i** [comment]
@YvonneYang2 with common HDMI driver now merged and enabled in kconfig, can you retest this bug?

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced on CML laptop with ALC3204 codec with HDA kernel. Test recipe is as below:
Firmware: 0b7fd030 https://github.com/thesofproject/sof/commits/master
Kernel: 4e76b4a1 https://github.com/thesofproject/linux/commits/topic/sof-dev 

But issue can still be reproduced on CML laptop with codec ALC711 -RT1308, RT715 in SDW mode. Test recipe is as below:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 085b4bf + PR1403
FW: https://github.com/thesofproject/sof/commits/master  commit: 0b7fd03

Note:
Amixer can also detect HDMI unplug status if unplug HDMI external port **during** S3 on CML laptop with ALC3204 codec while cannot detect HDMI unplug status on CML laptop with codec ALC711 -RT1308, RT715 in SDW mode. This issue will track in https://github.com/thesofproject/linux/issues/1364

**Comment by YvonneYang2** [comment]
Close this bug for NOT reproduced on HDA kernel. Track SDW issue on #1364

**Comment by kv2019i** [comment]
Thank you @YvonneYang2 -- great to see this bug closed!
