### ISSUE TITLE
[BUG][CML]Audio output via internal speaker will have 1-2s latency

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#953]
**Summary**:
Audio output via internal speaker will have 1-2s latency

**To reproduce**
Make sure not plug in headphone or headset 
Play music via command "aplay -Dhw:0,0 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav"

**Expect result**
Streaming output normally without latency

**Impact**
Streaming output will have 1-2 latency between press the enter and show the music playing status.

**Reproduce rate: 4/10**

**Test recipe**
Rander UCM https://github.com/RanderWang/intel-UCM/commits/hdmi
Kernel repo：c536f9f https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout	
Topology: https://github.com/thesofproject/sof/commits/debug-ipc-timeout	Same as above SOF repo	
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

Upload 4 dmesg log to compare.
[failDmesg2.txt](https://github.com/thesofproject/linux/files/3186440/failDmesg2.txt)
[passDmesg1.txt](https://github.com/thesofproject/linux/files/3186441/passDmesg1.txt)
[passDmesg2.txt](https://github.com/thesofproject/linux/files/3186442/passDmesg2.txt)
[failDmesg1.txt](https://github.com/thesofproject/linux/files/3186443/failDmesg1.txt)

**Comment by KailangYang** [comment]
This issue was same as issue #900 .

**Comment by bardliao** [comment]
@mengdonglin The polling_mode is on [azx_rirb_get_response](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/pci/hda/hda_controller.c#L795), but SOF uses [snd_hdac_bus_get_response](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/hda/hdac_controller.c#L233). I think we can implement it on snd_hdac_bus_get_response

**Comment by YvonneYang2** [comment]
Issue not reproduced with headset or without headset with PR https://github.com/thesofproject/linux/pull/963, so close the bug.

**Test recipe**:
Firmware: 5fa2426 https://github.com/thesofproject/sof/tree/master
Kernel: b58f448 https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Topology:  file:  tools/topology/sof-hda-generic.tplg,  sof-hda-generic-2ch.tplg same as firmware
Kconfig: https://sof-ci-storage.sh.intel.com/daily/20190521/release/linux/topic/sof-dev/901cd2a5-2/config-daily-hda-20190521.txt
CML laptop

**Comment by mengdonglin** [comment]
Wait for PR #963 to be merged by topic/sof-dev at first.
