### ISSUE TITLE
[Feature] Better UCM support for SOF in upstream

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#956]
Let's collect key points to upstream a reference UCM for SOF to alsa-lib, welcome for comments/correction:

- Leverage long name of sound card for device differentiation that can share the same machine driver but using different codecs. 
- Separate codec UCM configuraiton, i.e. include different codec conf in machine conf
- Support  headset/headphone JACK detection via codec
- Support JACK detection for external displays (#883 , #912)
- Suppport DP-MST (#755 )
- Support DMIC connected to PCH (#855)
- support CRAS for ChromeOS
- support PulseAudio for Linux distributions like Ubuntu. 

Please note: PulseAudio also needs enhancement for UCM for hot-plug happened on multiple PCM devices, e.g. #892, #917, #954

**Comment by plbossart** [comment]
I'd like to find a way to reuse the legacy UCM files and just substitute the SST parts with the SOF info. it's not scalable if we have to maintain stuff twice. this means finding a way to detect that when the card begins with sof- it may still use existing components.

**Comment by RanderWang** [comment]
this is my suggestion and Pierre gave some advice
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149409.html

**Comment by mengdonglin** [comment]
@RanderWang @juimonen @wenqingfu 
Please also read the latest discussion between Pierre and Jaroslav:
[alsa-devel] SOF firmware/ucm/topology packaging
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-May/149961.html

**Comment by kv2019i** [comment]
@juimonen @mengdonglin @libinyang I would propose to close this feature ticket. I believe we have closed all the improvement items listed in this original items. We have two specific items left and I today filed separate items to track those: https://github.com/thesofproject/linux/issues/2068 and https://github.com/thesofproject/linux/issues/2067

**Comment by mengdonglin** [comment]
@kv2019i Closed and thanks for identifying current gap!
