### ISSUE TITLE
[BUG][CML]HDMI hot plug out status cannot be detected.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#957]
**Summary**:
[BUG][CML]Can not detect the HDMI plug out status

**To reproduce**

1. Make sure no external monitor or headphone plug in after system reboot
2. Check the HDMI detect status via command "amixer cget numid=37"
3. Plug in external HDMI monitor and check the HDMI status via command "amixer cget numid=37"
4. Plug out HDMI monitor, and check check the HDMI status via command "amixer cget numid=37"

**Expect result**
All HDMI hot plug status should be detected 

**Actual result**
HDMI hot plug out status can not be detected. After step 4, value always is on, can not detect "value = off "status.

**Reproduce rate: 100%**

**Test recipe**
Rander UCM https://github.com/RanderWang/intel-UCM/tree/hdmi 
Kernel repo：c536f9f https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout	
Topology: https://github.com/thesofproject/sof/commits/debug-ipc-timeout	Same as above SOF repo	
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
platform: CML laptop with ALC3204 codec

**Step 2/3/4 amixer status**
```
test@test-Inspiron-5490:~$ amixer cget numid=37
numid=37,iface=CARD,name='HDMI/DP, pcm=11 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
test@test-Inspiron-5490:~$ amixer cget numid=37
numid=37,iface=CARD,name='HDMI/DP, pcm=11 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
test@test-Inspiron-5490:~$ amixer cget numid=37
numid=37,iface=CARD,name='HDMI/DP, pcm=11 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```
[amixer.txt](https://github.com/thesofproject/linux/files/3189797/amixer.txt)
[amixer_dmesg.log](https://github.com/thesofproject/linux/files/3189798/amixer_dmesg.log)
[amixer.log](https://github.com/thesofproject/linux/files/3189799/amixer.log)

**Comment by mengdonglin** [comment]
@kv2019i This issue may have the same root cause as https://github.com/thesofproject/linux/issues/878
and it seems GFX doesn't detect the disconnection of the monitor in time. @YvonneYang2 doesn't see the LCD splash after plugging out the monitor. Please help to give a check.

**Comment by kv2019i** [comment]
@mengdonglin Ack, will check.

**Comment by libinyang** [comment]
The hdmi hotplug seems to be OK on my wasp. (very few times failed. It's more like the mechanical issue)

**Comment by wenqingfu** [comment]
@kv2019i would you please test if the legacy HDA driver also have the same symptom? thanks!

**Comment by kv2019i** [comment]
@YvonneYang2 if you can reproduce this easily, could you try this with HDA legacy driver and see if the problem happens with that.

I can look at this on Thursday earliest, so this would help rootcausing.

**Comment by YvonneYang2** [comment]
I've checked the bug with HDA legacy driver, and the issue still reproduced. 
Besides, I found the issue may be related to the speed of pluging out HDMI.  You can try plug out HDMI slowly, may can increase the reproduce rate.

**Comment by kv2019i** [comment]
@YvonneYang2 wrote:
> I've checked the bug with HDA legacy driver, and the issue still reproduced.

Thanks, then I think this is different from #878 (FYI @mengdonglin) and may be issue on i915 side.

I'm still working on 944 so not actively working on this yet.

**Comment by wenqingfu** [comment]
| | CML1 | CML2 | CML3 |
|--- | --- | --- | --- |
|Monitor 1 (Dell u2414hb_QA)+wire   A | 2/10 | 2/10 | 3/10|
|Monitor 2 (Dell _Libin )+wire B | 3/10 | 1/10 | 2/10|
|Monitor 3 (Dell)+wire C | 2/10 | 2/10 | 2/10|

Similar status as but patch at https://bugs.freedesktop.org/show_bug.cgi?id=107125 doesn't resolve the issue.  Bug reproduced rate almost reach 100% if we plug out HDMI very slowly

With HDA legacy driver, same symptom still exist.

Need to fix in graphics driver.

**Comment by kv2019i** [comment]
> Similar status as but patch at https://bugs.freedesktop.org/show_bug.cgi?id=107125 doesn't resolve the issue. Bug reproduced rate almost reach 100% if we plug out HDMI very slowly
[...] 
> Need to fix in graphics driver.

@YvonneYang2 can you file this to graphics (bugs.freedesktop.org)? Once we have a bug id, we can close this. Let me know if you need help in filing.
UPDATE: or alternatively just add a comment to above fd.o bug 107125 . It seems that is not considered closed either and others have reported issues with very slow removals.

**Comment by YvonneYang2** [comment]
Issues will be fixed by graphics. 
So close the bug and track the issue in https://bugs.freedesktop.org/show_bug.cgi?id=110835
