### ISSUE TITLE
WHL DMIC capture - DC filter on startup and low volume

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#960]
Not necessarily a bug but when trying DMIC capture on a WHL device with DMIC, the volume is extremely low and I can see a DC filter quicking in at the start. This is with the sof-cnl-nocodec topology and the latest firmware signed with the production key.

@singalsu care to take a look?

Stupid GitHub doesn't support wave files so using gzip. Meh.
[whl_dmic.wav.gz](https://github.com/thesofproject/linux/files/3194543/whl_dmic.wav.gz)

**Comment by singalsu** [comment]
@plbossart Thanks for testing. It looks like there's four microphones in use, every channel is unique.

The low sensitivity is normal. Is this with our DMIC kit board? I think all mic capture pipelines should now contain a volume control so you could set the gain to e.g. +20 .. +30 dB to make it louder. With such gain applied it sounded quite good to me subjectively.

Yep, the gain ramp could be made longer. The DC level has not settled well when the gain ramp starts to pass audio. The ramp could made 100 - 200ms longer to hide better the start glitch. I'll create a FW issue about it.

The gain ramp is hardcoded at FW dmic.h so initially it should be adjusted from there. Once FW can support logarithmic volume ramp control the DMIC driver could utilize it too to use a topology controlled ramp. The log ramp worked better for start glitch mitigation so I used such gain update for updating the DMIC HW gains. We are missing still some math functions to handle log ramp calculation in FW like we now support linear ramp.

**Comment by singalsu** [comment]
@plbossart I remembered there's an issue that impacts 4ch capture volume control. It could be that ALSA/ASoC cannot expose other but 2ch volume control or do we present such case in wrong way in topology?

I tried to say in my test topology that the additional volume controls are surround left, surround right.  But still I could not achieve working 4ch volume control from alsamixer. Thoughts?

**Comment by plbossart** [comment]
> @plbossart <https://github.com/plbossart> I remembered there's an issue 
> that impacts 4ch capture volume control. It could be that ALSA/ASoC 
> cannot expose other but 2ch volume control or do we present such case in 
> wrong way in topology?
> 
> I tried to say in my test topology that the additional volume controls 
> are surround left, surround right. But still I could not achieve working 
> 4ch volume control from alsamixer. Thoughts?

I was using the cnl-nocodec topology which is very different from the 
apl-nocodec topology.
I still believe that the DC issue is independent of the volume config 
and likely independent of the topology as well, no?

**Comment by singalsu** [comment]
> I was using the cnl-nocodec topology which is very different from the apl-nocodec topology. I still believe that the DC issue is independent of the volume config and likely independent of the topology as well, no?

Yes, the DC is totally independent of volume component. I will make the capture start HW ramp longer to mitigate it. In fact the DC thump is even stronger with lower sample rates capture.

The (off-topic) volume issue that I mentioned is a restriction to apply gain in firmware for >2ch streams for lower sensitivity microphones. The EQ can do fixed gain for 4ch (an available solution if need) but I wasn't able to control 4ch volume via amixer. I'm not yet sure it's a bug or lack of my understanding but I'll file an issue when I'm more confident it's a bug.

**Comment by singalsu** [comment]
I'll change the ramp length 300 ms -> 400 ms. There will be still some DC settling left but I'm getting worried about missing speech from capture start due to low gain if extending it even more.

Below is zoom to your capture start waveform. The peak in the curves is where the current ramp ends at 300 ms.

![whl_dmic](https://user-images.githubusercontent.com/28754793/58428677-e61e0200-80ab-11e9-95dd-d20c2380e694.png)

**Comment by singalsu** [comment]
This can be closed since this PR https://github.com/thesofproject/sof/pull/1479 is merged.
