### ISSUE TITLE
[Feature][sof driver]:  could coexist with legacy HD-audio driver and skylake asoc driver

### ISSUE THREAD

**Issue by jason77-wang** [thesofproject/linux#961]
So far, we need to blacklist snd_hda_intel.ko or snd_soc_skl.ko to let sof driver work, could we don't blacklist any audio drivers and let them work togeter in the future, let the driver decide on its own if it should work or not runtime.

**Comment by kv2019i** [comment]
Ack. @plbossart had a patch to do just this (see https://github.com/thesofproject/linux/pull/927 ), see status update in https://github.com/thesofproject/linux/pull/927#issuecomment-501767908

**Comment by plbossart** [comment]
I'll restart working on this in mid-July, I had to put this on the back burner and rework some of the NHLT parts.

**Comment by kv2019i** [comment]
First set of patches merged upstream (stop legacy probe if DMICs are detected via NHLT):
https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?h=topic/hda-dmic&id=8c57588313805d4e12a3d470dee3405c2236655f

**Comment by kv2019i** [comment]
This feature is now implemented by merging the following patch series upstream:
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-October/157142.html
