### ISSUE TITLE
[BUG][GLK]Alsamixer has no capture PGA volume control option of DMIC

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#962]
**Describe the bug**
Alsamixer has no PGA volume control option of DMIC

**To Reproduce**

1. arecord with DMIC via command "arecord -Dhw:0,99 -fs16_le -r 48000 -c 4 1.wav"
2. Open alsamixer and check the capture PGA volume control of DMIC

**Expected result**
Alsamixer will have capture PGA volume control of DMIC

**Actual result**
Alsamixer will have capture PGA volume control of DMIC. Only has headset capture PGA volume control.

**Environment**
Kernel repo：901cd2a https://github.com/thesofproject/linux/commits/topic/sof-dev
Firmware repo: 2150974 https://github.com/thesofproject/sof/commits/master
tplg name：sof-glk-da7219.tplg
GLK Chromebook.
Reproducibility Rate：100%

![Capture](https://user-images.githubusercontent.com/50347470/58020749-b3b85600-7b3b-11e9-8bd2-afd05704df7d.PNG)

**Comment by ranj063** [comment]
@YvonneYang2 why is this a bug? the DMIC capture pipeline in sof-glk-da7219 uses a passthrough pipeline. So there will be no volume coomponent or a volume control, isnt it?

**Comment by YvonneYang2** [comment]
OK. Agree with it. It's not a bug, close it.
