### ISSUE TITLE
IPC: dump code is broken for CAVS1.8+

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#979]
The following code dumps IPC state during an IPC timeout on all Intel CAVS platforms.
```c
void hda_ipc_dump(struct snd_sof_dev *sdev)
{
	u32 hipcie;
	u32 hipct;
	u32 hipcctl;

	/* read IPC status */
	hipcie = snd_sof_dsp_read(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCIE);
	hipct = snd_sof_dsp_read(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCT);
	hipcctl = snd_sof_dsp_read(sdev, HDA_DSP_BAR, HDA_DSP_REG_HIPCCTL);

	/* dump the IPC regs */
	/* TODO: parse the raw msg */
	dev_err(sdev->dev,
		"error: host status 0x%8.8x dsp status 0x%8.8x mask 0x%8.8x\n",
		hipcie, hipct, hipcctl);
}
```
However, there are host side register differences between CAVS 1.5 and CAVS 1.8. It looks like the code above is for CAVS version 1.5 only.

**Comment by plbossart** [comment]
looks like an invalid bug, we have a separate function for cAVS 1.8:

apl.c:  .ipc_dump       = hda_ipc_dump,
cnl.c:  .ipc_dump       = cnl_ipc_dump,

**Comment by lgirdwood** [comment]
@plbossart yep, @xiulipan and I just discussing the need to try and better partition/document which files/functions relate to 1.5, 1.8 and 2.x
