### ISSUE TITLE
Need comments or docments to mapping CAVS version and files

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/linux#987]
For example:
apl cavs1.8 is binding to apl.c and most function in hda.c
cnl cavs2.x is binding to cnl.c and functions are in hda.c and cnl.c

Need some comments or documents about what cavs version is bind with files and functions.

**Comment by kv2019i** [comment]
@xiulipan Can this be closed? Doesn't seem like something that needs to be tracked as an issue...
